### ISSUE TITLE
Multiple XY LineChart support

### ISSUE THREAD

**Issue by Cloudo** [recharts/recharts#1]
I really impressed by your work.
Is there any support for LineChart to generate lines with not equal sets of `x` coordinates?

Example: http://c3js.org/samples/simple_xy_multiple.html
Thanks!

**Comment by xile611** [comment]
Thank you very much!
Recharts is not  prefect yet. util now, recharts do not support XY LineChart of C3 yet.
We will consider about XY LineChart.

**Comment by xile611** [comment]
@Cloudo 
Thank you very much!
Recharts is not prefect yet. util now, recharts do not support XY LineChart of C3 yet.
We will consider about XY LineChart.

**Comment by xile611** [comment]
@Cloudo 
I think XY LineChart of C3 is much more like ScatterChart with line jointed by all points.
Add the points in the demo of C3 are ordered by x-coordinate.
So we add curve in scatter, and the type of line can by 'joint' and 'fitting'. 
The 'joint' curve in scatter just joint all the points.
The 'fitting'  curve is more difficult which we  support in the future.

Maybe you can look for  the demo in ScatterChart.

**Comment by Cloudo** [comment]
Thank you for adding ScatterChart example. It is exactly what I was looking for.
