### ISSUE TITLE
set minPointSize for stacked bar

### ISSUE THREAD

**Issue by maxlibin** [recharts/recharts#1001]
How do I set minPointSize to stacked bar if the column value is 0, maybe add the property to BarChart and Bar components?

**Comment by hueitan** [comment]
Confirmed 🐛 , if you set the minPointSize to both bars, the latter bar will cover the first bar. 

But I'm wondering what's the use case of setting minPointSize for the stacked bar. :thinking:

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by sabitalizade** [comment]
same problem 2.1.8 version can`t show label couse of hight is small minPointSize not working
