### ISSUE TITLE
Passing activeDot prop to Bar breaks Tooltip

### ISSUE THREAD

**Issue by richsilv** [recharts/recharts#1002]
## Do you want to request a feature or report a bug?
Report a bug.

## What is the current behavior?
Whilst `activeDot` is not listed in the props for `Bar`, I've been abstracting the choice of cartesian component away to allow for bar and line graphs to be toggled between, and passing the same props to both `Bar` and `Line` as a result.  However, if you pass an `activeDot` prop to the bar graph, the `Tooltip` rendering breaks, but you receive no warning to assist with debugging.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).
http://jsfiddle.net/8r61ubLd/1/

## What is the expected behavior?
It would be great to receive an explicit warning advising that the `activeDot` prop will prevent tooltips from working.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Only affects 1.0.0-beta.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue guide.
