### ISSUE TITLE
Display tooltip of the closet series

### ISSUE THREAD

**Issue by alyssaq** [recharts/recharts#1003]
## Do you want to request a feature or report a bug?
Feature request

## What is the current behavior?
Currently, tooltips display all series of an x-axis slice.
Even when defining a custom tooltip, only the payload of a x-slice is accessible in props. 
<img width="575" alt="screen shot 2017-11-09 at 11 58 46 am" src="https://user-images.githubusercontent.com/2819448/32587914-3c08f3a0-c546-11e7-9939-3130379b0410.png">

## What is the desired behavior?
I would like to be able to display the tooltip of the closet series. This is extremely useful when there are too many lines on one chart. For example, grafana has an option to automatically display the closet series in the tooltip.
![untitled](https://user-images.githubusercontent.com/2819448/32587736-0af2a24e-c545-11e7-822f-df279cee7188.png)

Example with recharts where the closet series is displayed in all synced charts (hard coded to only display `amt` as an example). Having the same series displayed in all the synced charts' tooltip is also useful when comparing across multiple groups over the same timespan.  Fiddle: http://jsfiddle.net/alyssaq/oj5m1xsx/

<img width="658" alt="screen shot 2017-11-09 at 12 15 51 pm" src="https://user-images.githubusercontent.com/2819448/32588184-ee6e837e-c547-11e7-859f-0c0b7628fb07.png">

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts 1.0.0-beta.1. Tested on Chrome v62.0.3202.75 and Safari v11.0.01.

**Comment by alyssaq** [comment]
@xile611 Im happy to work on this if you're alright with having this feature in recharts.

**Comment by cainianhua** [comment]
@xile611 @alyssaq I also would like this feature.

**Comment by xile611** [comment]
It's recommended to use customized `content` of `Tooltip` to cover default tooltip.
