### ISSUE TITLE
animation #910 still an issue in 1.0.0-beta.1

### ISSUE THREAD

**Issue by gaukharaya** [recharts/recharts#1004]
## Do you want to request a feature or report a bug?
Related to animation issue from https://github.com/recharts/recharts/pull/910.
## What is the current behavior?
If a user hovers over a loading bar chart while it animation is in progress. isAnimationFinished flag remains false and does not get changed afterwards by subsequent hover overs. 

## What is the expected behavior?
If a user hovers over a loading bar chart while it animation is in progress animation should finish and set isAnimationFinished flag to true.
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.0.0-beta.1, Chrome. No this has not worked since adoption (alpha.3 version), cannot tell about previous versions.

**Comment by mshameer** [comment]
label is not re-rendering..   Is this issue fixed ?

**Comment by gaukharaya** [comment]
Hi no that is the issue the label does not get re-render since isAnimationFinished is stuck as false value. The issue is still observed in latest 1.0.0-beta.1 version.

**Comment by xile611** [comment]
Any idea  to reproduce this issue?

http://jsfiddle.net/u3nny58q/

The labels are re-rendered when you change `isAnimationActive`.

**Comment by chrisbutler** [comment]
this is still an issue for me in `1.0.1`

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
