### ISSUE TITLE
max-height

### ISSUE THREAD

**Issue by maxlibin** [recharts/recharts#1005]
How do I max out the yAxis as you can see my screenshot, the highest number I have is about 70, can I max out the height ?
<img width="753" alt="screen shot 2017-11-09 at 7 31 19 pm" src="https://user-images.githubusercontent.com/1277038/32603437-b9bf1228-c584-11e7-894b-e651aa193aca.png">

**Comment by hueitan** [comment]
I'm not sure what's the meaning of the "max out", I assume you need the yAxis to have the range from 0 to 100 for example.

You can use the **domain** property in the YAxis component http://recharts.org/#/en-US/api/YAxis

Here's the fiddle example http://jsfiddle.net/uwak0tzh/

![screen shot 2017-11-09 at 10 23 17 pm](https://user-images.githubusercontent.com/2560096/32630343-a3525898-c59c-11e7-8864-2a9dde51e22d.png)

**Comment by maxlibin** [comment]
Can you remove the space on top,  stretch bar to make use of full height of the container

**Comment by tongyy** [comment]
@maxlibin   Use the 'dataMax' keywords. @hueitan already gave the answer.
<YAxis domain={[0, 'dataMax']}/>

**Comment by maxlibin** [comment]
👍
