### ISSUE TITLE
maxAngle property of RadialBar not working

### ISSUE THREAD

**Issue by flankstaek** [recharts/recharts#1006]
## Do you want to request a feature or report a bug?
There is currently a bug with RadialBar not updating based on the maxAngle property.

## What is the current behavior?
Nothing happens when using a maxAngle property, my understanding was that it should set the angle of the max value in the data, if I'm misunderstanding let me know.

Currently setting it or changing it affects absolutely nothing on the graph that I can see.

## Example JSFiddle
Here is the RadialBarChart example JSFiddle with an added maxAngle property that changes nothing, you can attempt to remove the property or update the value and nothing in the graph will change.
http://jsfiddle.net/4qo7ba5L/21/

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Google chrome 61, Mac OSX El Capitan, Rechart 1.0.0-apha.5

**Comment by NoPPT** [comment]
I have the same problem， Google chrome 61.0.3163.100, Rechart 1.0.0-beta.1, macOS Sierra 10.12.6

**Comment by xile611** [comment]
Duplicated to #955
