### ISSUE TITLE
Left and right padding on CartesianGrid on ComposedChart

### ISSUE THREAD

**Issue by rafaelveiga** [recharts/recharts#1009]
Hi everyone. I'm currently experiencing a weird margin on my CartesianGrid relative to my ComposedChart.

![luft](https://user-images.githubusercontent.com/3176838/32670528-2c0cde4a-c62b-11e7-89e5-042ff5f151f7.png)

I've tried using `margin={{left: -20, right: -20}}` on all my components, but nothing seems to remove it. 

This is my component:
```
     <ResponsiveContainer 
        className={this.props.className} 
        width="100%" 
        height={210}
      >
        <ComposedChart data={projectedData}>
          <XAxis 
            dataKey="name"
            padding={{ left: 0, right: 0 }}
            tickLine={false}
            axisLine={false}
            tick={{fontSize: '10px', marginTop: "8px"}}
            minTickGap={64}
          />
          <YAxis
            dataKey="projected"
            padding={{ left: 0, right: 0 }}
            tickLine={false}
            axisLine={false}
            tick={{fontSize: '10px'}}
            tickFormatter={(tick) => ((tick / 1000) + 'k')}
            minTickGap={50}
          />
          <CartesianGrid strokeDasharray="2 2" strokeWidth="0.5" stroke="white" />

          <Bar dataKey="realized" stackId="a" fill="transparent" />
          <Bar dataKey="diffToProjected" stackId="a" maxBarSize={8} />
          <Line type="linear" dataKey="projected" stroke="white" dot={false} />
          <Line type="linear" dataKey="realized" stroke="#263465" dot={false} />
        </ComposedChart>
      </ResponsiveContainer>
```

Any tips on how to remove this left/right margin?

**Comment by cesargdm** [comment]
I have the same issue and plus this, the x axis is not being shown and the labels are misplaced
<img width="826" alt="screen shot 2017-11-12 at 3 03 55 pm" src="https://user-images.githubusercontent.com/10179494/32703394-c666be76-c7ba-11e7-9e9e-82ec79d22e84.png">

**Comment by hueitan** [comment]
Try using domain for XAxis and YAxis.

**Comment by robinwhittleton** [comment]
I’m seeing the same problem. `domain` doesn’t seem applicable for my data, but I tried it anyway with no luck. I can force negative padding on `XAxis`, the values needed change depending on the width of the chart which is painful.

**Comment by flyingalex** [comment]
Anybody has any idea?

**Comment by bishwenduk029** [comment]
I faced a similar problem and applied rotation on customized ticks for various chart sizes. That worked for customer. Hope it helps in your case too.

**Comment by j-jackson** [comment]
Did anyone find a solution to this?

**Comment by diego-betto** [comment]
I think it's related to band padding
https://stackoverflow.com/a/30597679

**Comment by serkanozer** [comment]
any update on this?

**Comment by andreev-danila** [comment]
Same problem, guys

**Comment by noxalex** [comment]
On XAxis and YAxis you can use prop tick={{ dx: -25 }}  **dx** to move labels by X axis and dy to move labels by Y axis, example:

<YAxis type="number" ticks={[0, 25, 50, 75]} tickCount={4} tickSize={0} axisLine={false} tick={{ dx: -25 }} />

**Comment by seryozhatebe** [comment]
scale = point for XAxis, work me!

<XAxis dataKey="name" scale="point" />

**Comment by alain0** [comment]
Thank you @seryozhatebe !

**Comment by iMerica** [comment]
Replacing `domain={['auto, 'auto']}` with `domain={['dataMin', 'dataMax']}` on the XAxis component fixed this issue for me.
