### ISSUE TITLE
Update the jsfiddle link in the Issue Template

### ISSUE THREAD

**Issue by hueitan** [recharts/recharts#1010]
> [link to =>](https://github.com/recharts/recharts/blob/master/.github/ISSUE_TEMPLATE.md#if-the-current-behavior-is-a-bug-please-provide-the-steps-to-reproduce-and-if-possible-a-minimal-demo-of-the-problem-via-httpsjsfiddlenet-or-similar-template-httpjsfiddlenetqbmg1567)
> If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).

The lib used in http://jsfiddle.net/qbmg1567/ doesn't valid now, please update, do you have any preference cdn?

**Comment by xile611** [comment]
It has been updated.
