### ISSUE TITLE
Tooltip not working for radial bar chart when startAngle > endAngle 

### ISSUE THREAD

**Issue by agaurav** [recharts/recharts#1011]
## Do you want to request a feature or report a bug?
Bug
## What is the current behaviour?
No tooltips shown when startAngle > endAngle for e.g. `startAngle={180} endAngle={0}`
There is no error or warning in console
## minimal demo of the problem
http://jsfiddle.net/4qo7ba5L/42/
## What is the expected behaviour?
Tooltips should be visible in all cases.
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
recharts@1.0.0-beta.1, Chrome 61/ macOS Sierra. Not sure about previous versions.

**Comment by nowke** [comment]
Are you facing the issue yet? I am able to see the tooltip from your demo.

![screen shot 2017-12-09 at 9 51 03 pm](https://user-images.githubusercontent.com/5479836/33797301-65e4744a-dd2b-11e7-9601-0dbab192779c.png)

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue guide.
