### ISSUE TITLE
Question about final component structure of #586 - Brush with embedded chart

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#1012]
I've tried the example (below) from #586 , but can't make it work:

```
<Brush>
  <AreaChart>
    <CartesianGrid />
    <YAxis hide domain={['auto', 'auto']} />
    <Area dataKey="price" stroke="#ff7300" fill="#ff7300" dot={false} />
  </AreaChart>
</Brush>
```

I appears to have been merged long ago, but what is the final structure that was implemented for this feature?

**Comment by evisong** [comment]
Sorry I've just found this after years ... 

For any others who happen to read this issue, please checkout the master branch, and run `npm run demo`, you'll find the demo "LineChart with panoramic brush and custom tooltip styles" working at the page bottom of http://127.0.0.1:3000/?group=chartWrapper&component=LineChart

Thanks.
