### ISSUE TITLE
[Feature/Bug] Line animation from a smaller to bigger data 

### ISSUE THREAD

**Issue by huei-tan-sociomantic** [recharts/recharts#1015]
## Do you want to request a feature or report a bug?

Please let me know if this is a Feature or Bug

## What is the current behavior?

The animation looks buggy and not a good user experience

## If the current behavior is a bug, please provide the steps to reproduce

jsfiddle : http://jsfiddle.net/7yb87att/
Click the More Data / Less Data Button

![bug-more-less-data](https://user-images.githubusercontent.com/18140315/32848536-0b7867f2-ca2d-11e7-8ca7-1bd0cb8ae89b.gif)

## What is the expected behavior?

Better animation for the data update?

Desired behaviour, demo from React-vis
![vis-desired-behaviour](https://user-images.githubusercontent.com/18140315/32848847-cd840202-ca2d-11e7-957b-ac02c262659b.gif)

**Comment by xile611** [comment]
@huei-tan-sociomantic Yeah. The behavior of animation is really strange.

**Comment by huei-tan-sociomantic** [comment]
Here's the temporary solution for **appending the data** which the domain is type number.

http://jsfiddle.net/csen65sk/
```es6
// example code
appendData() {
 this.setState( () => ({
  	left : 1, right : 7, animation : false, data : data2.slice()
 }) );
    
setTimeout( () => { // setTimeout does the trick
  this.setState( () => ({
      left : 1, right : 20, animation : true, data : data2.slice()
    }) );
  }, 0 );
},
```
![recharts-append-animation](https://user-images.githubusercontent.com/18140315/32943540-bf92cede-cb8c-11e7-9147-30d6bec88993.gif)

But this trick doesn't apply to updating the data **in-between**, because the animation doesn't happen
http://jsfiddle.net/o0v5heyp/
![recharts-update-inbetween](https://user-images.githubusercontent.com/18140315/32943801-a18bf108-cb8d-11e7-9ef5-f49dc395a769.gif)
