### ISSUE TITLE
label for stacked bar 

### ISSUE THREAD

**Issue by kamarajuPrathi** [recharts/recharts#1016]
how to give label to stacked bar

**Comment by hueitan** [comment]
Put a `LabelList` component as the nested component of `Bar`

```html
<Bar dataKey="uv" stackId="a" fill="#82ca9d">
    <LabelList dataKey="name" position="top" />
</Bar>
```

jsfiddle link http://jsfiddle.net/dv9ctsrq/

**Comment by goodrichj** [comment]
I'm also seeing the same problem.

@hueitan, 
That works in the fiddle but the exact same code doesn't work in my own project.

"recharts": "^1.0.0-beta.1",

**Comment by hueitan** [comment]
the jsfiddle uses the recharts version beta.1

https://npmcdn.com/recharts@1.0.0-beta.1/umd/Recharts.min.js

**Comment by goodrichj** [comment]
@hueitan,
Yeah, I know -- I can't explain why it's not working on my own project though. The same exact code doesn't work but I'm not sure why. I'm using the same version of React and the same version of the Recharts library (es6 though, not umd).

The <g class="recharts-layer recharts-label-list" ...> is never rendered into the DOM for me...

**Comment by xile611** [comment]
@goodrichj Please show more information about your problem.

**Comment by goodrichj** [comment]
@hueitan,
I really appreciate the help. I tracked down the issue on my end -- apparently my outer component containing the chart was causing the chart to re-render very quickly and that was somehow causing the labels to never render (probably related to the way the animations work but to be honest I don't fully understand the source code or the cause yet). If I have some time I'll try to setup a minimal sample case and post it here under another ticket.

**Comment by hueitan** [comment]
Great! Just use the jsfiddle link above(lots of the setups are already done), all you have to do is updating the code.

**Comment by bibblebabl** [comment]
But if you'll try to give label list for more than one bar you get another problem - positioning/zindex
![2017-11-22 17 29 00](https://user-images.githubusercontent.com/9008978/33132426-b20b6fa6-cfaa-11e7-8b58-eef346681c34.png)
any way to solve this?

**Comment by marcbc** [comment]
@bibblebabl was experiencing the same myself with versions prior 1.0.0-beta.3. Upgraded to the last 1.0.0-beta.4 and working for me!

**Comment by xile611** [comment]
@bibblebabl Just try the latest version 1.0.0-beta.5.
