### ISSUE TITLE
Always show _all_ ticks

### ISSUE THREAD

**Issue by emiloberg** [recharts/recharts#102]
There's some magic going on where Recharts figures out which tick labels to show, depending on the available screen estate. However, if I rotate a label (e.g. via transform in a custom tick component), the original width is still (of course) used.

Is there a way to override the magic and make sure _all_ ticks are always shown, no matter the available space?

**Comment by emiloberg** [comment]
Did some code digging. This can be done by adding `interval={0}` to the axis. E.g.

     <XAxis interval={0} />

**Comment by mattpage** [comment]
Thank you, @emiloberg

This was driving me crazy

**Comment by jcaryk** [comment]
@emiloberg 4 years late, but thank you. this has been plaguing me for 2.5 days now. thank you!!

**Comment by rahulbagad** [comment]
@emiloberg Thank you!

**Comment by LorenzoCM** [comment]
> @emiloberg 4 years late, but thank you. this has been plaguing me for 2.5 days now. thank you!!

haha same here! almost 2 days... Thanks @emiloberg !!!

**Comment by ksbulgakov** [comment]
+ 
almost 2 days)))

**Comment by kyle-ssg** [comment]
6 years later and you're still a legend

**Comment by Clebiez** [comment]
8 years later 🎉 thank you !
