### ISSUE TITLE
XAxis width overflow

### ISSUE THREAD

**Issue by dbalutsel** [recharts/recharts#1020]
Hi, is there a way to make chart scrollable? 
By default, when new data is added chart is squashed.

<img width="580" alt="screen shot 2017-11-16 at 8 34 27 pm" src="https://user-images.githubusercontent.com/18720927/32908882-9cc957e4-cb0d-11e7-8b12-6a068f966972.png">

But i want to make its width auto resized.

**Comment by hueitan** [comment]
You have several different requirements

1. Chart Scrollable

I suppose you are looking for a feature name `Pan`, you can use the Axis `domain` or `padding` to achieve the scrollable behaviour.

Here's the example when clicking **pan right**, **pan left** to update the padding of Axis
http://jsfiddle.net/su3ub6uz/

2. when new data is added chart is squashed.

I don't really understand what's the meaning of squashed here.

3. Make the width auto resized.

If you are saying Axis, you can use `domain={['auto', 'auto']}` to make it auto resized

Please let me know if you have any other questions here.
