### ISSUE TITLE
Pie Chart height calculation for angle charts too large

### ISSUE THREAD

**Issue by li1** [recharts/recharts#1021]
## Feature/Bug
bug

## Current behaviour
When creating Straight Angle Pie Charts (e.g. http://recharts.org/#/en-US/examples/StraightAnglePieChart), heights are calculated based on a circular pie chart and not based on the visible part of the chart. This leads to layout issues (see screenshots), especially in responsive layouts.

## Minimal Reproduction
*Edit:* I've taken the example from http://recharts.org/#/en-US/examples/StraightAnglePieChart and added a gray background to demonstrate the issue: http://jsfiddle.net/ahppaxdn/3/

~~JSFiddle appears to be down right now, but http://recharts.org/#/en-US/examples/StraightAnglePieChart with responsive width/height should show this issue easily.~~

## Expected Behaviour
See screenshot comparison:

Expected behaviour:
<img width="356" alt="screen shot 2017-11-18 at 15 35 22" src="https://user-images.githubusercontent.com/9516121/32981449-37ae43dc-cc76-11e7-961a-6600f9c22c59.png">

Actual behaviour (.recharts-wrapper height is set for a complete pie chart, not an angle chart)
<img width="355" alt="screen shot 2017-11-18 at 15 35 41" src="https://user-images.githubusercontent.com/9516121/32981454-40508c3e-cc76-11e7-9291-37263898f51e.png">

----

There's a similar issue for Victory (https://github.com/FormidableLabs/victory/issues/278), which was solved there by providing a standalone prop that enables manually editing the <g> rendered in an <svg>.

Also, I think the most common use of angle pie charts are 180°-charts such as the one in the screenshots, so a simple possibility to calc with `height/2` might cover most use cases.

**Comment by li1** [comment]
For now I worked around this by simply adding a prop to `<PieChart>` and using it together with `props.height` to update the `recharts-wrapper` class' height style attribute in `generateCategoricalChart.js`.

If there's a less hacky way that doesn't require editing library code, please let me know!

**Comment by davidramos-om** [comment]
How about considering updating the DOM as another temporary solution?https://github.com/FormidableLabs/victory/issues/278#issuecomment-2241796373
