### ISSUE TITLE
Area throws an error and rest of chart does not render

### ISSUE THREAD

**Issue by livingston** [recharts/recharts#1023]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
`Area` throws an error when all the value of the property passed as `dataKey` is either `undefined` or `null` and does not render the rest of the chart like the x-axis, y-axis, grid etc..

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net.
[Demo](http://jsfiddle.net/b9pjzn9t/64/) 

In the above example, the `Area` is being assigned the `dataKey` as `total`, which has `null` as value for all the data items.

`<Area type='monotone' dataKey='total' /> `

The error is thrown by the `map` happening [here](https://github.com/recharts/recharts/blob/b95a84aa1e879c0f6de05219696a54220048a976/src/cartesian/Area.js#L266).

## What is the expected behavior?

It should not throw an error (handle this case) and render the rest of the chart

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

All versions till `1.0.0-beta.2`

All modern browsers

**Comment by huei-tan-sociomantic** [comment]
I think it makes sense because from your demo http://jsfiddle.net/b9pjzn9t/64/ 

all the `total` data is null, so the chart doesn't have sufficient data to draw the graph (no YAxis can be drawn)

What you can do for now is

1. Serialize your data to integer `0` when it is `Null | Undefined`
2. Having another Component with a valid dataKey so the chart has data to draw YAxis

---

Other concern, I will vote for 
> throwing an explanation exception message instead of `n.map` is not a function.

**Comment by livingston** [comment]
Serializing data to `0` when all the values are `null` or `undefined` will result in looping of data at least twice, and will be a performance problem when the data is large.

Other charts/shapes(`Bar`, `Line`) do handle such situations gracefully.

Throwing an exception or error will create problems with React 16 apps, as it results in the unmounting of the whole render tree [[Ref](https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html#new-behavior-for-uncaught-errors)].
