### ISSUE TITLE
Unexpected Label positioning on VerticalBarCharts for Version 1.0.0-beta.2

### ISSUE THREAD

**Issue by quorak** [recharts/recharts#1024]
Hey there,

thanks for this great library, I have found a rendering issue of the current Version `1.0.0-beta.2` with LabelList in vertical bar charts. It does workwith Version `1.0.0-apha.5`. see the below images, whatever I try it seems as the labels are aligned to the YLegend, not to the bar itself.

**Expected behavior as wished with Version `1.0.0-apha.5`**
![image](https://user-images.githubusercontent.com/68172/33024790-5eb5d4d0-ce0c-11e7-9222-75c78d80ed45.png)

**Unexpected behavior with Version `1.0.0-beta.2`**
![image](https://user-images.githubusercontent.com/68172/33024774-52b0bad8-ce0c-11e7-8236-cb1f5b8d99de.png)

The corresponding code is:
```
   				 <ResponsiveContainer width="100%" height={1500}>
					<BarChart data={this.state.data} layout='vertical'>
						<XAxis type="number" orientation='top' hide={true}/>
						<CartesianGrid strokeDasharray="3 3" horizontal={false}/>
						<Bar dataKey="value" fill="#8884d8" barSize={30}>
							<LabelList dataKey='label' position='center' />
						</Bar>
						<YAxis type="category" hide={false}/>
					</BarChart>
		    	 </ResponsiveContainer>
```

**Comment by StK88** [comment]
Same issue, after update to 1.0.0-beta.2

**Comment by klandell** [comment]
I'm seeing this too after upgrading from 1.0.0-beta.1.  I don't have any time to look into it right now, but my hunch is that it is related to commit 93c1366b38affe57531c8e66fb43d2a204bde04d.

**Comment by xile611** [comment]
Try 1.0.0-beta.3.
