### ISSUE TITLE
Yaxis height not working

### ISSUE THREAD

**Issue by hc1skalyanasundaram** [recharts/recharts#1026]
I'm trying to define a height on y axis, but looks like it is calclauting the height internally and not taking my height into account. The reason I'm trying to set height is, the height first calculated is different from subsequent renders. Not sure why

`<ResponsiveContainer>
                            <BarChart layout='vertical' data={this.props.data}
                                      margin={{top: 5, right: 30, left: 20, bottom: 5}}
                                      barGap={2}>
                                <XAxis tick={{fontSize: 12}}
                                       tickFormatter={this.formatValue}
                                       type="number" dataKey="value"
                                       />
                                <YAxis tick={<CustomizedTick tickFontSize={this.tickLabelFontSize}/>} tickSize={4}
                                       interval={0} type="category" width={70} height={190} dataKey="name" />
                                <Tooltip formatter={this.formatValue} wrapperStyle={{ fontSize : 12, maxWidth:200, whiteSpace: 'normal'}}/>
                                <Legend chartHeight={195}/>
                                <Bar name={this.props.legend} dataKey="value" 
                                     label={this.renderCustomizedLabel} maxBarSize={12}>
                                </Bar>
                            </BarChart>
                        </ResponsiveContainer>`

**Comment by huei-tan-sociomantic** [comment]
Try using the domain and allowDataOverflow

```html
<YAxis height="100" domain={[ ..., ... ]} allowDataOverflow={true}/>
```

**Comment by hc1skalyanasundaram** [comment]
Thanks. So what should the domain values be? like the min and max

**Comment by huei-tan-sociomantic** [comment]
1. Try setting the width, height to BarChart
1. Creating the jsfiddle demo link so that everyone can easily help with debugging

**Comment by hc1skalyanasundaram** [comment]
trying to create jsfiddle. Meanwhile please note my yaxis type is category. so domain would still work?

**Comment by xile611** [comment]
@hc1skalyanasundaram Why you want to set the domain of `<YAxis />`.
And you can set the height of charts and the height of <YAxis />.

```jsx
<BarChart  width={400} height={100} />
```

**Comment by hc1skalyanasundaram** [comment]
Here is my problem:

1st render:
<img width="445" alt="screen shot 2017-11-22 at 6 35 13 am" src="https://user-images.githubusercontent.com/26306011/33125685-7ccbb05e-cf4f-11e7-987c-ca1e50862d6b.png">

2nd render:
<img width="437" alt="screen shot 2017-11-22 at 6 35 26 am" src="https://user-images.githubusercontent.com/26306011/33125691-843c030c-cf4f-11e7-813a-df42c6d6c4a0.png">

The legend overlaps with my xaxis ticks

**Comment by xile611** [comment]
@hc1skalyanasundaram Can you show the codes of both renders?

**Comment by hc1skalyanasundaram** [comment]
First render DOM:

<img width="983" alt="screen shot 2017-11-23 at 2 51 20 pm" src="https://user-images.githubusercontent.com/26306011/33187162-e18e2b3e-d05d-11e7-98cc-d6ec6435d5c0.png">

Second render DOM:

<img width="1000" alt="screen shot 2017-11-23 at 2 51 41 pm" src="https://user-images.githubusercontent.com/26306011/33187168-eb0cf762-d05d-11e7-86b7-1c2440e29e14.png">

**Comment by hc1skalyanasundaram** [comment]
@xile611 My code:

` <div className={classnames('chart-box', { active: this.state.collapse })} >
            <h5 className="toggle " onClick={this.toggleCollapse}>{this.props.title} <i className="fa fa-caret-down pull-right" aria-hidden="true"></i></h5>
            <Collapse isOpen={this.state.collapse}>
                <div style={{height: this.props.height || 250}}>
                    {!dataLoaded &&
                        <div className="loader"></div>
                    }
                    {dataLoaded &&
                        <ResponsiveContainer>
                            <BarChart layout='vertical' data={this.props.data}
                                      margin={{top: 5, right: 30, left: 20, bottom: 5}}
                                        >
                                <XAxis tick={{fontSize: 12}}
                                       tickFormatter={this.formatValue}
                                       type="number" dataKey="value"
                                       padding={{ right: 10 }}/>
                                <YAxis tick={<CustomizedTick tickFontSize={this.tickLabelFontSize}/>} tickSize={4}
                                       interval={0} type="category" dataKey="name"/>
                                <Tooltip formatter={this.formatToolTipValue} wrapperStyle={{ fontSize : 12, maxWidth:200, whiteSpace: 'normal'}}/>
                                <Legend />
                                <Bar name={this.props.legend} dataKey="value" fill="rgba(65,167,192,0.9)"
                                     label={this.renderCustomizedLabel} maxBarSize={12}>
                                </Bar>
                            </BarChart>
                        </ResponsiveContainer>
                    }
                </div>
            </Collapse>
        </div>
`

**Comment by xile611** [comment]
@hc1skalyanasundaram Everything seems ok. Can you create an online demo to reproduce this problem?

**Comment by tomtobac** [comment]
http://jsfiddle.net/ndLhnegs/686/
