### ISSUE TITLE
Downloading charts from client side?

### ISSUE THREAD

**Issue by justduy** [recharts/recharts#1027]
How do I download the chart from client side? I want to be able to download/export the graph to a .png or something like that extension.

**Comment by HunterEl** [comment]
I would also like to see this as a feature of this library, or even a way to assign an id to the root level svg and allow the export logic to occur from outside the library. Any clarification on this would be great. I see in this pull-request https://github.com/recharts/recharts/pull/959 `id` was added to the pie chart. I feel that adding an id to root level svg would at least provide a clean way to reference the chart and then using a library like https://github.com/exupero/saveSvgAsPng . This is a similar strategy followed in https://github.com/rrag/react-stockcharts .Thanks!

**Comment by justduy** [comment]
SaveSvgAsPng almost works actually, the only problem is that that the chart consists of seperate `<svg>`-elements so I can only export them individually. 

e.g

![image](https://user-images.githubusercontent.com/8453104/33388857-658f23b6-d531-11e7-8f0c-48ecb92d7f7f.png)

I can target the chart itself and the two legend components are seperate giving me only: 

![image](https://user-images.githubusercontent.com/8453104/33389075-08e0d83e-d532-11e7-8b8d-0b36bb325b0c.png)

**Comment by arttay** [comment]
Has there been any work on this? I'm working on an application that has several use cases around exporting complicated charts to PDF. I'd also like to use the same functionality for another use case around printing.

**Comment by ateufel** [comment]
Maybe this helps? https://stackoverflow.com/questions/45086005/recharts-component-to-png

**Comment by xang555** [comment]
for me i use `dom-to-image` convert DOM to image https://github.com/tsayen/dom-to-image
and download that image by using `js-file-download` https://github.com/kennethjiang/js-file-download

``` js
import domtoimage from 'dom-to-image';
import fileDownload from "js-file-download";

domtoimage.toBlob(document.getElementById('node-to-convert'))
    .then(function (blob) {
       fileDownload(blob, 'dom-to-image.png');
    });
```
Maybe help!!

**Comment by manu1222** [comment]
Any update on  this issue?

**Comment by iawebwork** [comment]
Hi, so is there any direct solution from recharts to export the graphs to PDF along with some other content (including table, etc) of the page?

**Comment by odarino** [comment]
@iawebwork just use @xang555's solution, it worked for me. 

I have question. In case graph is too long, is there any way to "zoom in", then exporting as image ? Because afaik `dom-to-image` has only property `style` which I can embedd the `transform` property but it will go outside the viewport.

**Comment by perdanafm** [comment]
> for me i use `dom-to-image` convert DOM to image https://github.com/tsayen/dom-to-image
> and download that image by using `js-file-download` https://github.com/kennethjiang/js-file-download
> 
> ```js
> import domtoimage from 'dom-to-image';
> import fileDownload from "js-file-download";
> 
> domtoimage.toBlob(document.getElementById('node-to-convert'))
>     .then(function (blob) {
>        fileDownload(blob, 'dom-to-image.png');
>     });
> ```
> 
> Maybe help!!

hi, i want to know what is node-to-convert mean in this case, because iam using component based and i dont have id

**Comment by vaasu070** [comment]
@xang555 I am doing just like you instructed . Image is being downloaded but it is improper. But when I open the same in paint , it looks fine.[
![dom-to-image](https://user-images.githubusercontent.com/33760706/85216763-4615d380-b3a6-11ea-9190-a90315898c6e.png)
]

why it is happening?

**Comment by xang555** [comment]
> @xang555 I am doing just like you instructed . Image is being downloaded but it is improper. But when I open the same in paint , it looks fine.
> 
> ![wrong](https://user-images.githubusercontent.com/33760706/85216802-af95e200-b3a6-11ea-88ba-103b86a0608f.PNG)
> 
> this is the download function I am writing
> ` const download = ()=>{
> 
> ```
> domtoimage.toBlob(document.getElementById('node-to-convert'))
> .then(function (blob) {
>    fileDownload(blob, 'dom-to-image.png');
> });
> ```
> 
> }`
> why it is happening?

Hello, i suggest you check document `dom-to-image` https://github.com/tsayen/dom-to-image .to change background color

**Comment by vasanvijay** [comment]
`import React from "react";
import {
  LineChart,
  Line,
  CartesianGrid,
  XAxis,
  YAxis,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from "recharts";

export default function Chart({ data }) {
  const handleDownload = () => {
    const chartContainer = document.getElementsByClassName("recharts-wrapper")[0];
    const chartSvg = chartContainer.querySelector("svg");
    const chartXml = new XMLSerializer().serializeToString(chartSvg);
    const image = new Image();
    const svgBlob = new Blob([chartXml], { type: "image/svg+xml;charset=utf-8" });
    const url = URL.createObjectURL(svgBlob);

    image.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = chartContainer.clientWidth;
      canvas.height = chartContainer.clientHeight;
      const context = canvas.getContext("2d");
      context.drawImage(image, 0, 0);

      const dataUrl = canvas.toDataURL("image/png");
      const link = document.createElement("a");
      link.href = dataUrl;
      link.download = "chart.png";
      link.click();
    };

    image.src = url;
  };

  return (
    <>
      <div style={{ height: "300px" }}>
        <ResponsiveContainer width="100%" height="100%">
          <LineChart data={data}>
            <Line type="monotone" dataKey="value" stroke="#8884d8" />
            <CartesianGrid stroke="#ccc" />
            <XAxis dataKey="name" />
            <YAxis />
            <Tooltip />
            <Legend />
          </LineChart>
        </ResponsiveContainer>
      </div>
      <button onClick={handleDownload}>Download Chart</button>
    </>
  );
}`


Here's a description of how the code works:

The Chart component receives the data prop, which represents the data to be displayed in the Recharts chart.

The handleDownload function is triggered when the "Download Chart" button is clicked.

Inside the handleDownload function:

The chart container element is obtained using document.getElementsByClassName("recharts-wrapper")[0].
The SVG content of the chart is extracted by selecting the first SVG element within the chart container.
The SVG content is serialized into a string using XMLSerializer().serializeToString(chartSvg).
An image element is created, and a blob is created from the SVG string using new Blob([chartXml], { type: "image/svg+xml;charset=utf-8" }).
A URL for the blob is created using URL.createObjectURL(svgBlob).
An onload event handler is attached to the image element, which ensures that the image is fully loaded before performing further actions.
Inside the onload event handler:
A canvas element is created with the same dimensions as the chart container.
The image is drawn onto the canvas using context.drawImage(image, 0, 0).
The canvas is converted to a data URL using canvas.toDataURL("image/png").
A temporary link element is created with the data URL as its href and "chart.png" as the download attribute value.
The link element is clicked programmatically using link.click(), triggering the download of the binary file.
The Chart component renders a responsive container with a Recharts LineChart inside it. The chart is configured with the provided data, and various components such as Line, CartesianGrid, XAxis, YAxis, Tooltip, and Legend are added as needed.

The rendered chart is enclosed within a <div> element with a fixed height of 300px.

A "Download Chart" button is rendered below the chart, and the handleDownload function is attached to its onClick event.

When the "Download Chart" button is clicked, the code extracts the SVG content of the chart, converts it to a binary file (PNG format), and triggers the download of the file.

Make sure to import the necessary components from the recharts library in your project, and customize the chart configuration and data according to your requirements.
