### ISSUE TITLE
YAxis customised labels in vertical BarCharts

### ISSUE THREAD

**Issue by zvictor** [recharts/recharts#103]
I am not being able to have customised labels in `YAxis` in vertical `BarChart`s. It complains about the way `props` are being propagated.

# code
```js
const CategoryLabel = ({ x, y, fill, payload }) => (
  <text>whatever component...</text>
);

...

<ResponsiveContainer>
    <BarChart layout="vertical" data={ data }>
      <YAxis dataKey="name" type="category" label={ <CategoryLabel /> } />    <--- problem is here
      <XAxis type="number" />
      <Bar dataKey="myKey" />
    </BarChart>
</ResponsiveContainer>
```

# errors
> Warning: CartesianAxis: `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)

&

> Warning: CartesianAxis: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)

# versions:
```json
"react": "^15.1.0",
"react-dom": "^15.1.0",
"recharts": "^0.10.5",
```

**Comment by xile611** [comment]
The problem is due to we use `cloneElement` to pass props into the label component.

```js
  React.cloneElement(label, this.props);
```

See [facebook/react#6268](https://github.com/facebook/react/pull/6268) for detail.

**Comment by xile611** [comment]
See [facebook/react#6880](https://github.com/facebook/react/pull/6880)

**Comment by ItisSyedimran** [comment]
How to change the xaxis ticks above small line. likes on attached below image. 
![9b7_0900_results_bar_graph_align_wrong_crop](https://user-images.githubusercontent.com/33149279/32549954-4e9e865a-c4b1-11e7-9fba-bb9eef3ecd35.jpg)
