### ISSUE TITLE
[Bug] XAxis repeats itself in ScatterChart when type="category"

### ISSUE THREAD

**Issue by JarLowrey** [recharts/recharts#1034]
## Do you want to request a feature or report a bug?

Bug

## What is the current behavior?

XAxis is repeated for each additional selection, but all the lines are graphed on top of each other.

## What is the expected behavior?

 I want the lines on top of each other and do not want the empty XAxis labels to appear

## Demo

http://jsfiddle.net/ndLhnegs/318/

![selection_038](https://user-images.githubusercontent.com/7429786/33139512-7eb5d738-cf7b-11e7-889f-31476dc6ee29.png)

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

recharts - 1.0.0-beta.2, react- 16.1.0, Brave browser 0.19.88 (newest chromium), Ubuntu 16.04

**Comment by JarLowrey** [comment]
The same issue occurs in a [slightly modified version](http://jsfiddle.net/7coegorj/2/) of the [JointLineScatterPlot](http://recharts.org/#/en-US/examples/JointLineScatterChart).

**Comment by JarLowrey** [comment]
This looks like it may be related from the [changelog](https://github.com/recharts/recharts/blob/master/CHANGELOG.md#100-alpha6oct-10-2017)

> Fix ScatterChart when the type of XAxis is "category"

**Comment by xile611** [comment]
@JarLowrey Duplicated ticks of XAxis is allowed in LineChart, AreaChart...  In the case of ScatterChart, It seems more reasonable to remove duplicated ticks of category xAxis. I wonder,  is there any case that the ticks of XAxis can be duplicated too.

In such case, we may need a props allowDuplicated in XAxis when the type is `category`.

**Comment by JarLowrey** [comment]
Is there any way to disable this or workaround it now? What is the best way to achieve my desired graph in current version?

**Comment by hueitan** [comment]
The current workaround I can thinking of is using XAxis as the type `number`, and using tickFormatter to format all the given number to the string value.

**Comment by ZephD** [comment]
Similar to #866
