### ISSUE TITLE
`Scatter` doesn't Provide Properties that `getLegendProps` Expects when Defining `ScatterChart`

### ISSUE THREAD

**Issue by ZheyangSong** [recharts/recharts#1035]
## Do you want to request a feature or report a bug?
A bug

## What is the current behavior?
`getLegendProps` expects property that is not defined by some cartesian components

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
http://jsfiddle.net/xbuvvgoe/

**NOTE:** The lines are not drawn because the `dataKey` is missing on `Line`. But the example is used to demo that `Legend` can somehow use `name` on `Line` to add label to the rendered legend view. This implies that `Legend` consumes (via `getLegendProps` call in `generateCategoricalChart`) non-exist property/attribute from `Line` (`Line`'s propTypes doesn't describe an attribute called `name`).

## What is the expected behavior?
`getLegendProps` should only expect defined properties from a ReactElement.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.0.0-beta.0. The source code I refer to is the master branch. This is a code logic issue and, thus, happen in all environments. Not sure if it's been this case all the time.

**Comment by ZheyangSong** [comment]
Extra comment: if I'm understanding the code correctly, this seems to be related to the recent change of replacing `name` with `dataKey` (which is a required attribute).

**Comment by xile611** [comment]
@ZheyangSong Thanks! But we have defined `name` in `Line`, `Area`, and so on.


[propType of name in Line](https://github.com/recharts/recharts/blob/master/src/cartesian/Line.js#L36)

**Comment by ZheyangSong** [comment]
@xile611 Sorry. It's my bad. The issue happens when using `ScatterChart`.

**Comment by xile611** [comment]
@ZheyangSong Thanks, I'll add propType of name in `Scatter`.

**Comment by ZheyangSong** [comment]
@xile611 I mean... `Scatter doesn't use either `name` nor `data`. Is it possible to add these to its propType? I'm kind of new to React itself.

**Comment by xile611** [comment]
@ZheyangSong `name` is a configuration property of `Scatter`. So I think it's ok!
