### ISSUE TITLE
stackedBarChart got error of using label props

### ISSUE THREAD

**Issue by eldyvoon** [recharts/recharts#1036]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?

I got below error 

`Error: Label(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object`

when doing this

```
<BarChart data={data} 
stackOffset="sign"
>
	<XAxis margin={{top: '10px'}} angle={-90} interval={0} fontSize={11} tickLine={false} axisLine={false} dataKey="date" />
	<Bar isAnimationActive={false} label={({value}) => {return value != 0 ? `${value}%` : <text></text>}} barSize={24} dataKey="female" fill="#ddd" stackId="stack" />
	<Bar isAnimationActive={false} label={({value}) => {return value != 0 ? `${value}%` : <text></text>}} barSize={24} dataKey="male" fill="#eee" stackId="stack" />
</BarChart>
```

## What is the expected behavior?
it should show the label. I tried the exact props value on Pie, it just worked.

## Which versions of Recharts, and which browser / OS are affected by this issue?
I'm using Mac and Chrome.

**Comment by xile611** [comment]
@eldyvoon  You must return a svg element when `value != 0`.

Otherwise you can use `formatter` to return a formatted value. 

[Try this demo](http://jsfiddle.net/1cu9amk9/)

**Comment by eldyvoon** [comment]
@xile611 but it's still a bug, it has inconsistency issue where the use of label props is limited on stackedBarChart.
