### ISSUE TITLE
Precompile ES6 features to ES5

### ISSUE THREAD

**Issue by webair** [recharts/recharts#1037]
## Do you want to request a feature or report a bug?
I would like to report a bug

## What is the current behavior?
If i want to build our react app the production build fail:

Failed to minify the code from this file: 
./node_modules/recharts/es6/util/PolarUtils.js:104 

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

Install "recharts": "^1.0.0-beta.3" with npm or yarn
run npm run build
or
run yarn build

## What is the expected behavior?

recharts should provide precompiled es5 module, see http://bit.ly/2tRViJ9

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

recharts 1.0.0-beta.3
npm 5.5.1
yarn 1.0.2

**Comment by livingston** [comment]
the error is due to the exponentiation operator `**` not being transpiled to ES5 (`Math.pow`)

**Comment by pustun** [comment]
We have the same issue

```
var distanceBetweenPoints = function distanceBetweenPoints(point, anotherPoint) {
  var x1 = point.x,
      y1 = point.y;
  var x2 = anotherPoint.x,
      y2 = anotherPoint.y;


  return Math.sqrt((x1 - x2) ** 2 + (y1 - y2) ** 2);
};
```

**Comment by xile611** [comment]
Sorry! My fault! I removed  **  in src/. But the lib/ were not updated.

**Comment by xile611** [comment]
1.0.0-beta.4 has been released to resolve this. But 1.0.0-beta.4 still has some bug related to Tooltip.
