### ISSUE TITLE
Can not build successfully after the recharts version is upgraded to Version 1.0.0-beta.3

### ISSUE THREAD

**Issue by poryzhao** [recharts/recharts#1038]
## Do you want to request a feature or report a bug?
I want to report a bug

## What is the current behavior?
After we upgrade recharts to Version 1.0.0-beta.3, we can not build successfully with Webpack.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
The error info is: 
16:10:23 [1m[31mERROR in ./~/recharts/lib/shape/Symbols.js
16:10:23 Module parse failed: /home/xiaoju/workspace/lean_web_ci/node_modules/recharts/lib/shape/Symbols.js Unexpected token (72:94)
16:10:23 You may need an appropriate loader to handle this file type.

## What is the expected behavior?
Building successfully

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Version 1.0.0-beta.3

**Comment by poryzhao** [comment]
Version 1.0.0-beta.2 is fine

**Comment by xile611** [comment]
Try 1.0.0-beta.4.
