### ISSUE TITLE
CartesianGrid gives warnings for percentages in 'verticalPoints' & 'horizontalPoints'

### ISSUE THREAD

**Issue by ljwagerfield** [recharts/recharts#1040]
When I do this...

```
<CartesianGrid verticalPoints={["33%", "66%"]} horizontalPoints={["33%", "66%"]} />
```

I get the following warnings:

```
Warning: Failed prop type: Invalid prop `verticalPoints[0]` of type `string` supplied to `CartesianGrid`, expected `number`.
Warning: Failed prop type: Invalid prop `horizontalPoints[0]` of type `string` supplied to `CartesianGrid`, expected `number`.
```

However, everything works fine (i.e. the warnings appear to be false negatives).

---

_Tested in version `1.0.0-beta.4`_

**Comment by xile611** [comment]
@ljwagerfield `verticalPoints` and `horizontalPoints` are the coordinates of vertical points and horizontal points. Only number type is supported now.

**Comment by ljwagerfield** [comment]
The use case is to render exactly 5 lines, evenly spaced apart, on a responsive chart -- how would I achieve this given the chart is responsive?

Also, this it appears to work, so perhaps "adding the feature" would be as simple as just removing the warning? 😛

**Comment by xile611** [comment]
@ljwagerfield I forget that svg support percentage coordinate. But the percentage means the percentage of the whole viewBox of <svg />, not the percentage of the main chart area now.

**Comment by ljwagerfield** [comment]
ahh yes - that would explain the behaviour I saw when the grid lines were being drawn relative to top-left corner of the viewbox.

For my specific case this is actually fine, but understand why this wouldn't be desirable for others.

What's the recommended way forward?

IMO percentages are a must for `CartesianGrid` when combined with `ResponsiveContainer` -- everything else scales relatively, so must the grid.

**Comment by xile611** [comment]
@ljwagerfield Thanks! We'll consider about this kind of request.

**Comment by merraysy** [comment]
@xile611 What's the status of this issue ?

**Comment by andrew-w-ross** [comment]
@merraysy Looks like it works.

**Comment by bardsol** [comment]
I still get the warnings…

**Comment by sarates** [comment]
Any updates?

**Comment by rokija** [comment]
Any updates?

**Comment by bryceosterhaus** [comment]
@xile611, since you closed this, is this resolved?
