### ISSUE TITLE
Pie chart: chart and legends disappear if all the values are 0

### ISSUE THREAD

**Issue by guilhermedelucas** [recharts/recharts#1042]
When I pass an object with all the value equal to zero to Pie chart, as expected the chart disappear, but the legend is also missing. 
My chart tool has a controller when click on legend, it sets the value to 0 to hide the data from the chart.
I'm setting the value to zero, to keep the legend displayed on the chart, and it's possible to return the old values clicking again.
Here's the example of data passed to the Pie chart.

```javascript
const pieChartData = [
  {name: "Bar", value: 0},
  {name: "Foo", value: 0}
]
```

The bar charts on the other hand if I pass values equal to zero, the legend and the Cartesian grid is still there. There's mine expected behavior for the PieChart. Keep the legend to control the values.

```javascript
const barChartData = [
  {timestamp: 1483315200000, foo: 0, bar: 0},
  {timestamp: 1483401600000, foo: 0, bar: 0}
]
```
Someone had this problem? There's a workaround? Is it a bug??

**Comment by xile611** [comment]
@guilhermedelucas All you need is the legend should keep visible when all the datas are 0. right ?

**Comment by guilhermedelucas** [comment]
@xile611 Yes, that's exactly what I need to do

**Comment by bubenkoff** [comment]
@guilhermedelucas thanks for bringing this up - we have the same issue

**Comment by vikramkhot111** [comment]
@xile611 Is it fixed?

Steps to reproduce
    open https://jsfiddle.net/L3qcx9ys/1/

**Comment by clluiz** [comment]
Any solution ou hack to overcome this?
