### ISSUE TITLE
Pie Charts - Cell color don't change

### ISSUE THREAD

**Issue by iphonic** [recharts/recharts#1043]
I am facing a very strange problem, I have followed the samples in which it is shown how to use colors and set to pie cells. In my case the pie cell color always remains same even if I hardcode a different color, check my code below

  ```
<PieChart width={500} height={220}>
           <Pie data={this.props.iosVersions}
                    outerRadius={80}
                    innerRadius={70}
                    dataKey="value"
                    label>
                    {
                      this.props.iosVersions.map((entry, index) => {
                        console.log("Color ",this.state.colors[index]);
                        <Cell key={`slice-${index}`} fill="#ff9896"/>
                      })
                    }
              </Pie>
              <Tooltip/>
    </PieChart>
```

I have got set of 60 random colors, which prints fine in the log.. As you can see I have hardcoded fill color to **#ff9896**, but the chart turn out to be always in dark grey color, where as the color I am providing is light red shade.. I inspected the cell, and found that the cell color is always **#808080** on its own.. See image how my chart looks

![screen shot 2017-11-24 at 7 30 46 pm](https://user-images.githubusercontent.com/5745637/33213773-f7c8f216-d14e-11e7-97d3-ef17130e6bc1.png)

Thanks for Helping.

**Comment by iphonic** [comment]
Problem was the code chunk below
```
this.props.iosVersions.map((entry, index) => {
   console.log("Color ",this.state.colors[index]);
   <Cell key={`slice-${index}`} fill="#ff9896"/>
})
```

The above code wasn't returning the color filled cell properly I change the code to

`this.props.iosVersions.map((entry, index) =><Cell key={`slice-${index}`} fill="#ff9896"/>)`

Its working now..

**Comment by andrefox333** [comment]
I'm not too sure what code changed in your solution, could you clarify @iphonic?
