### ISSUE TITLE
Recharts breaks with react 15.6.1

### ISSUE THREAD

**Issue by eranhirs** [recharts/recharts#1044]
## Do you want to request a feature or report a bug?
bug

## What is the current behavior?
Exception thrown
`TypeError: Cannot read property 'ReactCurrentOwner' of undefined`

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
Use react `15.6.1` and recharts `beta.5`

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

It seems that updating to react-dom 16 is the cause.
https://github.com/recharts/recharts/commit/eb5e1fc6fe0c0739139a4efd0e200ab9f68bf392#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
Last version working is `alpha.6`

**Comment by xile611** [comment]
![image](https://user-images.githubusercontent.com/6111424/33253677-9086bcfe-d37f-11e7-9158-d32595813bed.png)

@eranhirs It works in the project of recharts.org. I can't reproduce this case.

**Comment by eranhirs** [comment]
Thanks! Probably something wrong with my `package.json`, I will test it later today and reopen if it's relevant.
