### ISSUE TITLE
Using in same chart a horizontal bar and a vertical line 

### ISSUE THREAD

**Issue by kassimorra** [recharts/recharts#1045]
## Do you want to request a feature or report a bug?
A user question, not a feature or bug.

## What is the current behavior?
I just want to build a chart that shows 5 bar in horizontal and 1 line in vertical. My line will represent the average of all five bar.
The documentation don´t have this information.

**Comment by manasa884** [comment]
http://recharts.org/en-US/api/ReferenceLine The ReferenceLine component should be able to do what you're looking for

**Comment by AdamAvix** [comment]
You can do this by having two x-axis data keys that correspond to different values. For example, with the dataset (on the domain [0, 10]):

[{x: 5, y: 0}, {x:5, y:5}]

This will draw a vertical line with those coordinates. I just pushed bunch of objects with duplicate x-axis keys to the end of my data array with a new data key name. Might not the correct way to do it but it worked for me.
