### ISSUE TITLE
BarChart - expend the click event to all the column

### ISSUE THREAD

**Issue by NadavGab** [recharts/recharts#1047]
## Do you want to request a feature or report a bug?
feature

## What is the current behavior?
In BarChart - if you click above a bar (not directly on the bar) the click event is not working

## What is the expected behavior?
The click event will be envoke
I need it because sometimes I have very tiny bar:
https://ibb.co/bEXda6

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

"recharts": "1.0.0-beta.3"

**Comment by ledicana** [comment]
I don't think this is possible, see the answer here :  https://github.com/recharts/recharts/issues/167

**Comment by isaac-ipl** [comment]
Add an `onClick` handler for the `<BarChart>` component. This should provide you with props such as `activePayload` which is the highlighted data.

**Comment by uazure** [comment]
> Add an `onClick` handler for the `<BarChart>` component. This should provide you with props such as `activePayload` which is the highlighted data.

it worked for me in some scenarios, but it doesn't work when scale is 'band': clicking a bit to the left of the center of the bar reports index of the left axis marker, and clicking bit to the right off the bar center - reports the next axis tick, though it's the same bar :(
