### ISSUE TITLE
LineChart with logarithmic scale doesn't work with 0 value

### ISSUE THREAD

**Issue by ghost** [recharts/recharts#1049]
LineChart with log scale doesn't render anything if there is 0 value in data array.

**Comment by sooheon** [comment]
What should it render? ln(0) is negative infinity.

**Comment by GuLinux** [comment]
Hi,
I guess an option would be to let the user provide a replacement value for ln(0)

**Comment by GuLinux** [comment]
I'll elaborate more: I'm using recharts to display images histogram, in both linear and logarithmic scales.
Basically, it shows how many pixels have a certain value. On a linear scale, of course everything works fine. On a log scale, though, you'll see that a value with 0 pixels will break the chart, though if you think about it, in this particular domain, you still want to see values with 0 pizels as `0`
