### ISSUE TITLE
Scatterchart shapes don't appear on proper y-axis (introduced in alpha.6)

### ISSUE THREAD

**Issue by jgentes** [recharts/recharts#1051]
## Do you want to request a feature or report a bug?

bug

## What is the current behavior?

Multiple items on a single chart stack up on the same Y-Axis.. 

## What is the expected behavior?

They should be on different lines.. see screenshot: http://prntscr.com/hg09ug

In alpha.6 and later, the shapes only appear on one line (ie. the PROGRAM line in the screenshot)

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Works fine prior to alpha.6, still a bug in beta.5

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
