### ISSUE TITLE
Line chart dot missing if Yaxis has single item

### ISSUE THREAD

**Issue by eldyvoon** [recharts/recharts#1053]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
Missing a dot on lineChart
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
http://jsfiddle.net/ezx7sjrp/
## What is the expected behavior?
It should show second dot because the color of store has value

I tested with different set of data but same structure (https://pastebin.com/WjwevF0n), the bug didn't exist.

**Comment by xile611** [comment]
@eldyvoon The second dot just has empty stroke, and the default fill `#fff`. So The second dot is  invisible.
![image](https://user-images.githubusercontent.com/6111424/33469541-696f749a-d69e-11e7-8ef8-ce5e1dcc974f.png)
