### ISSUE TITLE
Can't reach bottom of side-bar in recharts documentation site

### ISSUE THREAD

**Issue by tozekh** [recharts/recharts#1056]
Don't know if this belongs here:

The bottom of the API components side-bar of the API page in recharts.org cannot be reached on Firefox or Edge. It gets stuck at Dot and cannot scroll more.

**Comment by hueitan** [comment]
Can confirm, but this issue should go to this repo https://github.com/recharts/recharts.org

**Comment by tozekh** [comment]
Thanks. Posted to the recharts.org repo.
