### ISSUE TITLE
Module parse failed error when loading ResponsiveContainer module

### ISSUE THREAD

**Issue by adrienpoly** [recharts/recharts#1057]
Hello 

I have small charting component that is working fine.
My environment is Rails 5.1 + Webpack 3, Recharts 1.0 beta 5 (latest)
When I try to add a Responsive component I am getting the error bellow:

```
ERROR in ./node_modules/recharts/src/component/ResponsiveContainer.js
Module parse failed: Unexpected token (13:21)
You may need an appropriate loader to handle this file type.

class ResponsiveContainer extends Component {
  static displayName = 'ResponsiveContainer';
  static propTypes = {
  aspect: PropTypes.number,
@ ./app/javascript/page_speed_chart/chart.js 15:27-80
@ ./app/javascript/packs/application.js
```

As soon as I include the ResponsibleContainer component into my app I get this error message.
Import is rather standard:

```
import React,{Component} from 'react';
import { LineChart, Line, Tooltip, YAxis, XAxis, ResponsiveContainer } from 'recharts';
```

Rails 5.1 comes with preconfigured loaders, an up to know all package were correctly loaded. Only for this specific ResponsiveContainer I get the error....

Any idea what could be wrong?

Thanks

**Comment by adrienpoly** [comment]
Ok I have completely restarted my server and now getting a different error message.

I can import the ResponsiveContainer with 
`import { LineChart, Line, Tooltip, YAxis, XAxis, ResponsiveContainer } from 'recharts';`

but when I use it I get this error message:
```
invariant.js?7313:42 Uncaught Error: Element type is invalid: expected a string (for built-in
components) or a class/function (for composite components) but got: undefined. 
You likely forgot to export your component from the file it's defined in, or you might 
have mixed up default and named imports.
    at invariant (23:42)
    at createFiberFromElement (132:5751)
    at updateElement (132:6912)
    at updateFromMap (132:7141)
    at reconcileChildrenArray (132:7324)
    at reconcileChildFibers (132:7672)
    at reconcileChildrenAtExpirationTime (132:7788)
    at reconcileChildren (132:7771)
    at updateHostComponent (132:8024)
    at beginWork (132:8257)
```

**Comment by xile611** [comment]
@adrienpoly Can you create a simple project to reproduce this problem. Everything works in my local project.

**Comment by adrienpoly** [comment]
Hello I have created several stand alone projects and was not able to reproduce. I just found out the issue. Probably an issue on my side.
I have a custom component <ChartStats /> that was embedded inside the ResponsiveContainer. 
Moving this component outside of the Container make everything working as expected.
The error message was really not explicit at all but it is solved now. 
Thanks for your help

**Comment by fllprbt** [comment]
In my case I was mapping multiple LineChart into the ResponsiveContainer...

**Comment by sesteva** [comment]
Im having the same problem. Im using webpack and I've tried adding
mainFields = ['jsnext:main', 'browser', 'main']

and 

loaders = [{
    test: /\.js$/,
    loader: 'babel',
    exclude: /node_modules\/(?!(([^\/]+?\/){1,2}(src|es6)))/ 
  }]

Errors below...

`ERROR in ./packages/charts/node_modules/recharts/es6/container/Layer.js
Module parse failed: Unexpected token (33:4)
You may need an appropriate loader to handle this file type.
| import PropTypes from 'prop-types';
| import classNames from 'classnames';
| var if ('development' !== "production") {
|   propTypes = {
|     className: PropTypes.string,
 @ ./packages/charts/node_modules/recharts/es6/index.js 4:0-39
 @ ./packages/charts/pie-chart/index.js
 @ ./packages/charts/pie-chart/piechart.example.js
 @ ./packages ^((?!node_modules).)*\.example\.js$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js (webpack)-hot-middleware/client.js?reload=true ./.storybook/config.js

ERROR in ./packages/charts/node_modules/recharts/es6/container/Surface.js
Module parse failed: Unexpected token (34:4)
You may need an appropriate loader to handle this file type.
| import classNames from 'classnames';
| import { getPresentationAttributes } from '../util/ReactUtils';
| var if ('development' !== "production") {
|   propTypes = {
|     width: PropTypes.number.isRequired,
 @ ./packages/charts/node_modules/recharts/es6/index.js 2:0-43
 @ ./packages/charts/pie-chart/index.js
 @ ./packages/charts/pie-chart/piechart.example.js
 @ ./packages ^((?!node_modules).)*\.example\.js$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js (webpack)-hot-middleware/client.js?reload=true ./.storybook/config.js

ERROR in ./packages/charts/node_modules/recharts/es6/component/Label.js
Module parse failed: Unexpected token (61:4)
You may need an appropriate loader to handle this file type.
| import { isNumOrStr, isNumber, isPercent, getPercentValue, uniqueId, mathSign } from '../util/DataUtils';
| import { polarToCartesian } from '../util/PolarUtils';
| var if ("development" !== "production") {
|   cartesianViewBoxShape = PropTypes.shape({
|     x: PropTypes.number,
 @ ./packages/charts/node_modules/recharts/es6/index.js 16:0-39
 @ ./packages/charts/pie-chart/index.js
 @ ./packages/charts/pie-chart/piechart.example.js
 @ ./packages ^((?!node_modules).)*\.example\.js$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js (webpack)-hot-middleware/client.js?reload=true ./.storybook/config.js

ERROR in ./packages/charts/node_modules/recharts/es6/component/LabelList.js
Module parse failed: Unexpected token (74:4)
You may need an appropriate loader to handle this file type.
| import { getPresentationAttributes, findAllByType } from '../util/ReactUtils';
| import { getValueByDataKey } from '../util/ChartUtils';
| var if ("development" !== "production") {
|   propTypes = {
|     id: PropTypes.string,
 @ ./packages/charts/node_modules/recharts/es6/index.js 18:0-47
 @ ./packages/charts/pie-chart/index.js
 @ ./packages/charts/pie-chart/piechart.example.js
 @ ./packages ^((?!node_modules).)*\.example\.js$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js (webpack)-hot-middleware/client.js?reload=true ./.storybook/config.js`

**Comment by inaamiub** [comment]
In my case, I mistakenly put '}' in ResponsiveContainer children and I was getting this error.
My code was 
`<ResponsiveContainer width="100%" height={75}>
  <AreaChart data={[]}>...</AreaChart>
  }
</ResponsiveContainer>`
I just removed '}' and now it works fine
