### ISSUE TITLE
Brush component not scaling properly inside of ResponsiveContainer

### ISSUE THREAD

**Issue by joshburgess** [recharts/recharts#106]
Hey, guys. Nice work on recharts. Really enjoying using it so far, but just noticed one issue. When using the Brush component (view finder/zoom control/slider bar) in charts that are wrapped with a ResponsiveContainer component, they don't resize/rerender correctly like the rest of the chart does. 

Is there a prescribed way to make this work that I haven't found or is this a visual bug that needs to be fixed? I first noticed it my project, but added a Brush to the ComposedChart demo on JSFiddle and had the same issue.

[http://jsfiddle.net/8uzkn19y/](http://jsfiddle.net/8uzkn19y/)

It's not a huge deal but seems a little wonky. Could we maybe rerender the Brush to its initial state (slider bar at 100% width) for smoother transitions on resize?

**Comment by xile611** [comment]
It's a bug. We'll fix it in soon.

**Comment by xile611** [comment]
Fixed in version 0.10.7.
