### ISSUE TITLE
Brush x, y, no longer required props

### ISSUE THREAD

**Issue by flyg101** [recharts/recharts#1062]
## What is the current behavior?

Considering the fix for #1022, the x and y props of the <Brush /> component should no longer be required as they show a warning in React of expected values
<img width="467" alt="screen shot 2017-12-02 at 6 31 18 am" src="https://user-images.githubusercontent.com/21314258/33512162-939c51fc-d72a-11e7-8486-be887707767c.png">

**Comment by xile611** [comment]
@flyg101 Thanks! This has been fixed in latest 1.0.0-beta.6.

[Brush.js#L25](https://github.com/recharts/recharts/blob/master/src/cartesian/Brush.js#L25)

**Comment by flyg101** [comment]
Thanks, was preparing a PR already 🙂
