### ISSUE TITLE
reduce-css-calc really useful?

### ISSUE THREAD

**Issue by hlehmann** [recharts/recharts#1063]
reduce-css-calc is mostly use on build process.

It's only use there:
https://github.com/recharts/recharts/blob/master/src/component/Text.js#L141 (3 times)

Does it really worth to load reduce-css-calc and its dependencies in order to precalculate something the browser easily calculate ?

**Comment by xile611** [comment]
@hlehmann PR is welcome, `reduce-css-calc` is not necessary.
