### ISSUE TITLE
BarChart only renders highest value chart

### ISSUE THREAD

**Issue by PJEstrada** [recharts/recharts#1064]
## Do you want to request a feature or report a bug?
Im reporting a bug.
## What is the current behavior?

I have a multi bar chart with two bars in it. When I render it, it just renders the bar with the highest value. The bar with the lowest value does not render unless it has the same value as the highest valued bar.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem 

http://jsfiddle.net/oqg00j2j/

## What is the expected behavior?

The expected behaviour is to render both bars.

**Comment by xile611** [comment]
@PJEstrada 

http://jsfiddle.net/oqg00j2j/21/

You should change the `type` of `XAxis`.

```jsx
<BarChart layout="vertical" data={rows}
                              margin={{top: 5, right: 30, left: 20, bottom: 5}}>

                        <YAxis axisLine={false} tickLine={false}  dataKey="name" type="category">
                        </YAxis>
                        <XAxis type="number" />
                        <Bar dataKey="valuePre" fill="#00a0dc" label={<Text scaleToFit={true} verticalAnchor="middle" />}/>
                        <Bar dataKey="valuePost" fill="#c7c7c7"  label={<Text verticalAnchor="middle" />}/>

                    </BarChart>
```
