### ISSUE TITLE
Suggestion: YAxis should take multiple dataKeys

### ISSUE THREAD

**Issue by kevinhikaruevans** [recharts/recharts#1065]
## Do you want to request a feature or report a bug?

I want to suggest a feature, where YAxis can take multiple dataKeys to display, e.g., instead of having two separate axes for two items, I want to merge them into a single axis.

## What is the current behavior?

It can only be passed in a single string or number.

## What is the expected behavior?

If you pass in an array of dataKeys, it should be able to use multiple lines, and scale according to the min/max of those keys.

**Comment by Kenigmatic** [comment]
@kevinhikaruevans do the suggestions I made in #1052 meet your needs? I suggested dataKey should accept a function (that could potentially be more flexible than an array). Or maybe both suggestions: dataKey ... [string | number | function, ...]

**Comment by kevinhikaruevans** [comment]
@Kenigmatic I think so, as long as it can return multiple values
