### ISSUE TITLE
Question : How to set transparency to Bars in SimpleBarChart

### ISSUE THREAD

**Issue by iamanoopmk** [recharts/recharts#1066]
Need help to change the transparency of the bars in a bar chart.

I want to achieve a faded look on the bar charts. The first bar will be full opaque and the last bar will be at half opacity. I can assign different colours using the following

` 
 <Bar dataKey="pv" >
       		{
          	data.map((entry, index) => {
            	 //colour chosing logic here
            	return <Cell fill={color} />;
            })
          }
       </Bar>
` 
But if I give a clour code with alpha the bar become complete black. Is there a way to achieve what I want ?

Here is a js fiddle example 

[JSFiddle](http://jsfiddle.net/6ypvrjup/)

in the colours list the first one has alpha and it is rendered in black

**Comment by hueitan** [comment]
opacity

**Comment by iamanoopmk** [comment]
@hueitan 

Thank you for that. This can be added to the API menu on the website. Would be helpful to others
