### ISSUE TITLE
Axis domain does not encompass children

### ISSUE THREAD

**Issue by ZephD** [recharts/recharts#1067]
## Do you want to request a feature or report a bug?
Feature/bug

## What is the current behaviour?
Children, such as Ref Line, can be outside of the axis domain and therefore not rendered.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
N/A

## What is the expected behaviour?
The axis domain should adjust to include the children values

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
All

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
