### ISSUE TITLE
Syncing Brush & Hover Events (Tooltips) for Multiple Charts or Composing Charts

### ISSUE THREAD

**Issue by joshburgess** [recharts/recharts#107]
I'm trying to create functionality that syncs up 2-3 charts so that I can use one Brush component to keep the displayed chart area in sync across all charts. Similarly, when I hover over a chart and get the tooltip popup display, I'd like to sync this across all charts to be able to compare all 3. The goal is to have a more clear alternative to having multiple y-axes on a single chart. 

A good example of what I'm trying to do can be seen in the visualizations here:

[http://projects.fivethirtyeight.com/election-2016/delegate-targets/](http://projects.fivethirtyeight.com/election-2016/delegate-targets/)

Is there anyway to compose multiple charts together to be able to more easily use singular controls like the brush across multiple charts? Something like a ComposedVisualization component wrapping multiple LineCharts (or whatever else). 

Or do you have any tips on how I can tap into the onHover event for a chart to trigger all tooltips displaying simultaneously for a given point hovered over?

**Comment by joshburgess** [comment]
A little more info: I've been looking at the state properties being used for each LineChart (or ComposedChart/AreaChart/etc.) to track & show the toolTip... just trying to figure out a good way to wrap my set of charts with a container component that syncs those state properties on each chart anytime the state changes & isTooltipActive is true.

**Comment by xile611** [comment]
@joshburgess 

We consider your issue for a long time, found that it's a very different to sync brush and hover events across more than one chart. Because we change state of a LineChart to track and show the Tooltip now. If a LineChart want to keep synchronous with another chart, the LineChart must receive some props from the external. 
These two kinds of behaviour is contradictory.

**Comment by xile611** [comment]
Fixed in version 0.13.3.
