### ISSUE TITLE
Stacked Bar chart with one data point does not draw bar

### ISSUE THREAD

**Issue by tozekh** [recharts/recharts#1072]
When a stacked bar chart has only one data point it is not drawn, while 2 identical data points with different X value are both drawn.

Please see http://jsfiddle.net/omhruw4p/ for an example: nothing is drawn, but if you un-comment the second data point, both are drawn OK.

I'm using:
Recharts 1.0.0-beta.6
React 15.6.1
Firefox 56
Windows 10

Tried also chrome on Linux (Cent OS 7)

**Comment by erickakoyama** [comment]
I noticed this when doing a single bar BarChart in the vertical layout as well

**Comment by MrAlexLau** [comment]
Noticed this too, in fact for my particular example I'm working with I can just add a second empty object `{}` (similar to what you have but without any props) and the chart will display.

**Comment by jendamozna** [comment]
same for scale=time/utc

https://jsfiddle.net/bpsv2ru9/

https://npmcdn.com/recharts@1.4.2/umd/Recharts.min.js
Chrome 71

Hack with {} does not work.

**Comment by natasha-robarge** [comment]
Has anyone found a solution for this?

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
