### ISSUE TITLE
change height dynamically in Vertical Bar Chart with scroll bar

### ISSUE THREAD

**Issue by KamiGim** [recharts/recharts#1073]
## Do you want to request a feature or report a bug?
bug

## What is the current behavior?
when not set height show nothing

## What is the expected behavior?
when set height should dymically change the height with fixed bar size and bar gap

**Comment by xile611** [comment]
@KamiGim You can use `ResponsiveContainer` to render a chart which has dynamic height.

[Docs of ResponsiveContainer](http://recharts.org/#/en-US/api/ResponsiveContainer)

**Comment by orangewit3** [comment]
is there a fix for this? I'm having the same issue. I don't want to have to set the height because I'm not sure how much data im rendering, whether its 2 data points or 20 I want the same barsize and bargap and the height should be set automatically without influence from the parent container.

**Comment by shanben7** [comment]
@orangewit3 did you ever find a solution for this?

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
