### ISSUE TITLE
Bar order doesn't reflect coded bar order.

### ISSUE THREAD

**Issue by dbanks6990** [recharts/recharts#1074]
Feature/ maybe bug

Currently, when you have multiple bars don't display in the order that you code them too.

![screen shot 2017-12-07 at 1 00 18 pm](https://user-images.githubusercontent.com/6228120/33736166-d3b1ac06-db4e-11e7-9c5f-51320272325b.png)

       <Bar yAxisId="left" dataKey="pv" fill="#8884d8" /> // bar  position 1

       <Bar yAxisId="right" dataKey="uv" fill="#82ca9d" /> // bar  position 3

       <Bar yAxisId="left" dataKey="pvc" fill="#8884d8" /> // bar  position 2

       <Bar yAxisId="right" dataKey="uvc" fill="#82ca9d" /> // bar  position 4

I am wanting the bars to appear in the order that they are placed within the BarChart. (the legend does it) but the bars do not. 

       <Bar yAxisId="left" dataKey="pv" fill="#8884d8" /> // bar  position 1

       <Bar yAxisId="right" dataKey="uv" fill="#82ca9d" /> // bar  position 2

       <Bar yAxisId="left" dataKey="pvc" fill="#8884d8" /> // bar  position 3

       <Bar yAxisId="right" dataKey="uvc" fill="#82ca9d" /> // bar  position 4

See the js fiddle
http://jsfiddle.net/dbanks6990/1ab56c19/1/

React  v15.3.2
Recharts v1.0.0-beta.5

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
