### ISSUE TITLE
Server-side rendering fails because of inconsistent params

### ISSUE THREAD

**Issue by lerayne** [recharts/recharts#1076]
It seems that SSR doesn't work properly because of some inner data is not the same:

<img width="630" alt="screenshot at dec 11 00-28-08" src="https://user-images.githubusercontent.com/671158/33810198-a7bae20c-de0a-11e7-8647-d0ceddea3cbf.png">
<img width="443" alt="screenshot at dec 11 00-27-50" src="https://user-images.githubusercontent.com/671158/33810171-6915aca8-de0a-11e7-932b-77fbb5286314.png">

Recharts 1.0.0-beta.6
macOS 10.13.1 High Sierra
React & react-dom 15.6.2

**Comment by xile611** [comment]
@lerayne When you render Pie in SSR, you can set the props `id` of <Pie />:

```js
<Pie id="specifiedId" />
```

**Comment by lerayne** [comment]
I also had different similar problems with areachart, I'll post them here if it happens again, so please don't close the issue for now

**Comment by pixelass** [comment]
Any news here? This is still an issue. Adding a custom id does not resolve this issue 

related: #1959

**Comment by ke1vin1993** [comment]
Adding an unique `id` did solve my problem, that warning doesn't show anymore.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
