### ISSUE TITLE
Feature Request: Custom Component rendering for LabelList

### ISSUE THREAD

**Issue by pachuka** [recharts/recharts#1077]
Hi, I think the LabelList feature could be a lot more powerful if it allowed for taking a custom component similar to how the standard Label (and other recharts components already do). This would be really useful for a project I am currently working on. I basically need the same functionality that it currently has with the accumulator, but able to wrap the result in my own custom html. I am using this for rendering the total above a stacked bar chart. If there is another way to do this and still keep the result centered above  the bar, then that would work for me as well.

Thanks!

**Comment by xile611** [comment]
@pachuka You can check [the latest doc of LabelList](http://recharts.org/#/en-US/api/LabelList). You can render customized component by adding props `content` of LabelList.
