### ISSUE TITLE
Line components render offset from rest of chart when the XAxis component's 'scale' property is assigned to 'linear'

### ISSUE THREAD

**Issue by B3rry** [recharts/recharts#1080]
## Do you want to request a feature or report a bug?
Report a bug
## What is the current behavior?
When using a `scale` of `linear` with time series data (encoded in unix timestamps), `Line` components within a `LineChart` render offset to the rest of the chart. (Mine were wrapped in `ResponsiveContainer`, but I have validated that removing this does not solve my occurrence of this issue.)
<img width="148" alt="screenshot 2017-12-11 16 49 04" src="https://user-images.githubusercontent.com/5562161/33855552-3df4930c-de93-11e7-8d57-de4f307f89b3.png">

> _Appears in the fiddle posted below. Notice how the orange and green lines run off the chart_

<img width="286" alt="screenshot 2017-12-11 16 38 57" src="https://user-images.githubusercontent.com/5562161/33855555-4001f842-de93-11e7-952a-3c90967311f9.png">

> _This behavior does not effect the `Tooltip`'s `cursor`._

[jsfiddle Demo of problem (on right-hand side)](http://jsfiddle.net/zqu3rb8s/3/)
## What is the expected behavior?
`Line`'s output should render in the appropriate position. Note: this happens with multiple different `scale`.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
macOS High Sierrra, Chrome 62, using the latest npm release at time of writing (`1.0.0-beta.6`)

**Comment by tkeffer** [comment]
I have seen this as well. It's as if the line gets shifted to the right slightly, as there is a corresponding gap on the left hand side:

![image](https://user-images.githubusercontent.com/3321259/35947239-1b0ba3b2-0c24-11e8-9205-62ebee98434b.png)

Recharts: `1.0.0-beta.10`
Chrome 64
macOS High Sierra

**Comment by tkeffer** [comment]
Setting `type='number'` in `<XAxis>` solved my problem:

```
 <XAxis
     dataKey='timestamp'
     domain={['auto', 'auto']}
     scale='time'
     type='number'
/>
```

Otherwise, the default `type='category'` applies, resulting in categories that center on the tick marks, and thus stray beyond the end of the x-axis.

Applying the fix to @B3rry JSFiddle fixes his problem as well: http://jsfiddle.net/zqu3rb8s/4/

I leave it to him to close the issue.

**Comment by guiguan** [comment]
@tkeffer yep, thanks. That fixed my problem as well. Also, `domain` has to set to `{['auto', 'auto']}` as well

**Comment by orhan-swe** [comment]
I have also seen this; initial XAxis: 
```
<XAxis
                    dataKey="name"
                    scale="time"
                    interval="preserveStartEnd"
                    tickFormatter={getTickFormat}
                    ticks={ticks}
                />
```
I had to add both type and domain to get rid of the offset:
```
<XAxis
                    dataKey="name"
                    scale="time"
                    interval="preserveStartEnd"
                    tickFormatter={getTickFormat}
                    ticks={ticks}
                    domain={['auto', 'auto']}
                    type="number"
                />
```
It should not be necessary to add both domain and type, I would suggest that this is a bug.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue guide.

**Comment by tkurki** [comment]
Thanks @tkeffer - your answer keeps on giving.
