### ISSUE TITLE
not getting  proper data mouseHover on Line graph.

### ISSUE THREAD

**Issue by jshupptechnologies** [recharts/recharts#1084]
I tried 
<Line name="speed"  dot={false} onMouseMove={(e)=>props.handleChartEnter(e)} dataKey="s" stroke="#0000FF" />

on mouseMove getting data
{
	"stroke": "#0000FF",
	"strokeWidth": 1,
	"fill": "none",
	"width": 719,
	"height": 360,
	"className": "recharts-line-curve",
	"clipPath": null,
	"points": [{
		"x": 80,
		"y": 365,
		"value": 0,
		"payload": {
			"s": 0,
			"d": 0,
			"c": 0,
			"lp": 0,
			"rp": 0,
			"ts": "5:57:53 PM"
		}
	}, {
		"x": 102.46875,
		"y": 365,
		"value": 0,
		"payload": {
			"s": 0,
			"d": 0,
			"c": 0,
			"lp": 0,
			"rp": 0,
			"ts": "5:57:58 PM"
		}
	}
	}],
	"type": "linear",
	"layout": "horizontal",
	"connectNulls": false
}

i need data where mouse point.
any suggest how to get data on mouseHover or mouseEnter ?

**Comment by xile611** [comment]
@jshupptechnologies  Add `onMouseMove` to `LineChart`.

```jsx
<LineChart onMouseMove={...}>
  <Line />
</LineChart>
```
