### ISSUE TITLE
Bug in scatter chart - ignoring axis domains

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#1087]
## Do you want to request a feature or report a bug?
bug

## What is the current behavior?
![image](https://user-images.githubusercontent.com/685316/33974997-6d085894-e051-11e7-9a3d-cde2e37b98a3.png)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
The axis domains seem to be ignored on a scatter chart. I've tried axis domains on other chart types and they work as expected. I've also try omitted the domain and setting it to fixes values, like [0, 100], all with no effect.

The JSON below is the source of what is processed by our software, which directly creates React ReCharts components. This mechanism is not in question--it works fine under both versions of ReCharts. I've included it to show you the ReCharts components that are being created and the values of the props being set.

```
 {
      "component": "ScatterChart",
      "container": "chart",
      "margin": {
         "top": 20,
         "right": 20,
         "bottom": 10,
         "left": 15
      },
      "components": [
         {
            "component": "Scatter",
            "name": "Falcons",
            "data": "falcons",
            "fill": "#638ccc",
            "stroke": false,
            "shape": "circle",
            "legendType": "circle"
         },
         {
            "component": "Scatter",
            "name": "Hawks",
            "data": "hawks",
            "fill": "#72a555",
            "stroke": false,
            "shape": "square",
            "legendType": "square"
         },
         {
            "component": "Scatter",
            "name": "Eagles",
            "data": "eagles",
            "fill": "#ca5670",
            "stroke": false,
            "shape": "triangle",
            "legendType": "triangle"
         },
         {
            "component": "XAxis",
            "name": "Wingspan",
            "unit": "cm",
            "datakey": "X",
            "height": 22,
            "domain": [
               0,
               "auto"
            ]
         },
         {
            "component": "YAxis",
            "name": "Weight",
            "unit": "g",
            "datakey": "Y",
            "width": 30,
            "domain": [
               0,
               "auto"
            ]
         },
         {
            "component": "ZAxis",
            "name": "Count",
            "datakey": "Z",
            "range": [
               0,
               50
            ]
         },
         {
            "component": "CartesianGrid",
            "stroke": "white",
            "strokeDasharray": "2 2"
         },
         {
            "component": "Tooltip",
            "cursor": {
               "stroke": "black",
               "strokeDasharray": "5 3 2 3"
            }
         },
         {
            "component": "Legend"
         }
      ]
   }
```

## What is the expected behavior?
![image](https://user-images.githubusercontent.com/685316/33975005-7530a33c-e051-11e7-882a-36d2d2553fb8.png)

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Current (broken): 1.0.0-beta.6
Prior (working): 0.21.2

**Comment by xile611** [comment]
@Eric24 Add `type = "number"` to `XAxis`

**Comment by Eric24** [comment]
Excellent. Yes, that fixes it!
