### ISSUE TITLE
How to set the number of lines on a polar grid?

### ISSUE THREAD

**Issue by rainandwind0** [recharts/recharts#109]
I am using a RadarChart to represent a bunch of scores ranging from 0-3 (whole numbers only) in different categories. However, no matter what I try there are always five circles drawn on the grid, one of them being at radius zero of course. As you can imagine, this seems confusing when the grid lines are between actual possible scores. How Would I go about setting the number of circles on my grid? I was hoping setting the polarRadius array on PolarGrid would do it, but I have had no luck.

```
<ResponsiveContainer width={'100%'} height={300}>
  <RadarChart
    data={radarData}
    margin={{top: 20, right: 20, bottom: 20, left: 20}}
    innerRadius="0%"
    outerRadius="100%"
  >
    <Radar name="Left" dataKey="L" stroke="#e91e63" fill="#e91e63" fillOpacity={0.3} />
    <Radar name="Right" dataKey="R" stroke="#673ab7" fill="#673ab7" fillOpacity={0.3} />
    <PolarGrid gridType="circle" polarRadius={[0, 50, 100, 150]} />
    <Legend />
    <PolarAngleAxis dataKey="test" />
  </RadarChart>
</ResponsiveContainer>
```

**Comment by rainandwind0** [comment]
My current solution was to set a domain of 0-4 instead of 0-3 to make results appear on the gridlines. However, this does add an extra gridline to the graph that is "unreachable".
`<PolarRadiusAxis domain={[0,4]} tick={false} axisLine={false}  />`

**Comment by xile611** [comment]
@rainandwind0 

You can set the props `tickCount` in `PolarRadiusAxis`. The default value of `tickCount` is *5*, that's why you always get five circles.

```
<PolarRadiusAxis angle={30} domain={[0, 3]} tickCount={4}/>
```

**Comment by xile611** [comment]
My fault! I forgot to add `tickCount` in the API of `PolarRadiusAxis`.

**Comment by rainandwind0** [comment]
Thank you! Surprised I missed that...

**Comment by rainandwind0** [comment]
Ah that makes more sense. (: I also noticed it says default type is circle but mine defaults to the polygon...?

**Comment by xile611** [comment]
Yeah, I'll update the document. Welcome to point our mistakes.

**Comment by rainandwind0** [comment]
Sounds good. I will let you know if I find anything else. Thank you much for theverything library. Works wonderfully.
