### ISSUE TITLE
Questions about 1.0.0-beta6

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#1090]
I have a few questions about 1.0.0-beta6:

1. Is there a list of deprecated props (like Pie.valueKey)?

2. What is a LabelList used for (what kinds of chart elements can it apply to)?

3. What is the difference between a Label component and label prop?
```
  <XAxis dataKey="name">
    <Label value="Pages of my website" offset={0} position="insideBottom" />
  </XAxis>
  <YAxis label={{ value: 'pv of page', angle: -90, position: 'insideLeft', textAnchor: 'middle' }} />
```

4. What controls the presence/color/style of grey area that appears on a barchart on tooltip hover?
![image](https://user-images.githubusercontent.com/685316/33975421-12a3b42c-e054-11e7-8ee9-5a40c8ab02aa.png)

5. Are current on-line examples and API documentation considered up-to-date with code release 1.0.0-beta6? If not, is there documentation available elsewhere?

**Comment by xile611** [comment]
1. Only valueKey is deprecated, we have updated the props in [recharts.org](http://recharts.org/#/en-US/api/Pie).
![image](https://user-images.githubusercontent.com/6111424/33984658-60dbdb3e-e0f3-11e7-8754-bc11a73e1bf4.png)

2.  LabelList can be used in `<Area />`, `<Bar />` , `<Line />`, `<Scatter />` , `<Pie />`, `<Radar />`, `<RadialBar />`. This'll be displayed in [recharts.org](http://recharts.org/#/en-US/api/Pie)
3. When you add `label` props, a `<Label />` will be created internally.
```jsx
<XAxis dataKey="name">
    <Label value="Pages of my website" offset={0} position="insideBottom" />
</XAxis>
```

equals to

```jsx
<XAxis dataKey="name" label={{ value: 'Pages of my website', offset: 0, position: 'insidebottom' }} />
```
4. When you mouse enter the chart area, the grey rectangle which is called `cursor` of `Tooltip` will appear. You can change the style of "the grey rectangle" by setting [`cursor` of `Tooltip`](http://recharts.org/#/en-US/api/Tooltip).

5. We'll try to update the demos, but PR is also welcome in [recharts.org](https://github.com/recharts/recharts.org). We need more contribution to make recharts better and better.
