### ISSUE TITLE
Bug in tooltip on radial bar chart

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#1092]
## Do you want to request a feature or report a bug?
bug

## What is the current behavior?
![image](https://user-images.githubusercontent.com/685316/33975850-f24fa30e-e056-11e7-9f32-04720db8da6d.png)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
There does not appear to be any props on the Tooltip component to change this behavior, but the currently tooltip on radial bar charts does not show the same values as before.

Note that the ReCharts demo shows the same behavior: http://recharts.org/#/en-US/api/RadialBarChart

The JSON below is the source of what is processed by our software, which directly creates React ReCharts components. This mechanism is not in question--it works fine under both versions of ReCharts. I've included it to show you the ReCharts components that are being created and the values of the props being set.

```
  {
      "component": "RadialBarChart",
      "container": "chart",
      "data": "traffic",
      "innerRadius": "10%",
      "outerRadius": "80%",
      "components": [
         {
            "component": "RadialBar",
            "dataKey": "waiting",
            "clockwise": true,
            "startAngle": 135,
            "endAngle": -135,
            "minAngle": 15,
            "maxAngle": 255,
            "cornerRadius": 10,
            "background": {
               "fill": "#eee"
            }
         },
         {
            "component": "Legend",
            "layout": "vertical",
            "align": "left",
            "verticalAlign": "middle",
            "iconType": "circle"
         },
         {
            "component": "Tooltip"
         }
      ]
   }
```

## What is the expected behavior?
![image](https://user-images.githubusercontent.com/685316/33975854-f632fa34-e056-11e7-8c4a-884eb8bc2dc6.png)

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Current (broken): 1.0.0-beta.6
Prior (working): 0.21.2

**Comment by xile611** [comment]
@Eric24 The behavior of RadialBarChart is same to BarChart's behavior now.

**Comment by Eric24** [comment]
Hmmm. I'm not sure what that means. So do I need to add some props to the tooltip component?

**Comment by xile611** [comment]
@Eric24 If you don't want to show the `label` in `Tooltip`, you can hide it.

**Comment by loris** [comment]
@xile611 I confirm the same issue, if the provided data collections contains `name` parameter, it should be the one displayed in the tooltip, ie in @Eric24 example, it shows `waiting` which is the name of the dataKey instead of `Dogwood`, which is the name of hovered value. This is how BarChart behaves, but RadialBarChart do not.

**Comment by loris** [comment]
@xile611 A JSfiddle to reproduce the bug: http://jsfiddle.net/4qo7ba5L/118/
(I just forked the SimpleRadialBarChart http://recharts.org/#/en-US/examples/SimpleRadialBarChart jsfiddle example to add a `<Tooltip />` component). As you can see, if you hover the purple radial bar, the tooltip displays `uv: 31.37`, instead of `18-24: 31.37`
Hope this clarifies.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.

**Comment by Himujjal** [comment]
@xile611 Same problem does persist in the latest version. Please check this part or at least provide a solution to the above problem.
Thank you.

**Comment by bduff9** [comment]
This still seems to be an issue 4 years later, any update or workarounds here?

**Comment by ckifer** [comment]
You can try `<Tooltip shared={false} />`

That has some other issues, but it does get rid of the index.

You could also create a custom tooltip which does not render that content

Shared false: https://codesandbox.io/p/sandbox/simple-radial-bar-chart-forked-mgzxxw

Custom tooltip: https://codesandbox.io/p/sandbox/simple-radial-bar-chart-forked-llg9hh

**Comment by bduff9** [comment]
Thanks for the reply.  The issue is I need the label in there and it doesn't get passed in even with a custom tooltip for me to show it.  Otherwise it just shows the value which is already printed on the graph so is not very useful.  Does that make sense?

**Comment by ckifer** [comment]
Sure it is
https://codesandbox.io/p/sandbox/simple-radial-bar-chart-forked-llg9hh

**Comment by bduff9** [comment]
You are correct, thank you for the example.  For some reason, when I console.logged out the props given to CustomTooltip, there was no name property (it was undefined).  But your code does work and so this work around works for me, thanks again
