### ISSUE TITLE
FR: Confidential intervals to line chart

### ISSUE THREAD

**Issue by fedorocko** [recharts/recharts#1096]
It would be very valuable if `Area` can be defined as interval. This would alove us to simulate the confidential interval such as this one:

![image](https://user-images.githubusercontent.com/4131617/34097293-f02e4384-e3d8-11e7-8d1c-42c57c52148c.png)

**Comment by VojtechBartos** [comment]
+1

**Comment by xile611** [comment]
Maybe you can use `<ComposedChart />`
