### ISSUE TITLE
FR: Multi-category X axis

### ISSUE THREAD

**Issue by fedorocko** [recharts/recharts#1097]
It would be very valuable if X-axis can receive multiple levels of category. This would alove us to build more complex time-series visualizations. Good example of multi-category X-axis is this: 
![image](https://user-images.githubusercontent.com/4131617/34097950-1b2551b6-e3db-11e7-8d13-b5c83f2d65ab.png)

**Comment by VojtechBartos** [comment]
+1

**Comment by DeadcatDev** [comment]
+1

**Comment by peteruithoven** [comment]
Relevant: https://github.com/recharts/recharts/issues/1732
