### ISSUE TITLE
Change Area color by value

### ISSUE THREAD

**Issue by aromanet42** [recharts/recharts#1098]
Hello, 
I just discovered your lib, it is awesome!

I have just one question.

I would like to have an Area chart, displaying the difference between 2 values. For example, it could be one line for the money you have earned by month, and the other for the money you spent.
I would like to display the area between the two line in green if I earned more than I spent, and red otherwise.

Here is an example of what I would like to achieve: 
![array-color](https://user-images.githubusercontent.com/7204715/34099403-b93550be-e3df-11e7-9edd-29370dbe3f69.png)

If I use the "array" data (as in the http://recharts.org/#/en-US/api example), I cannot find a way to change the color depending of the data.
Here is my jsFiddle: http://jsfiddle.net/aromanet42/jcjy9qt4/

If I draw 2 Area, I cannot draw only the "diff" part. I find it not very readable (http://jsfiddle.net/aromanet42/ffemp77j/)

I tried the "gradient" way (as in http://recharts.org/#/en-US/examples/AreaChartFillByValue), but how to determine the gradient dynamically ? In the given example, it is static: all values above 0 are green, all values below 0 are red.

Thanks in advance!

**Comment by ben2323** [comment]
Hi,
Any news with this issue?
I'm interesting in the same thing.

**Comment by hueitan** [comment]
I would recommend to use two area element and both of them bind to the same yaxis

In this splitting code, you are easily assign the spent and earn two datasets in each area.

**Comment by aromanet42** [comment]
@hueitan Thanks for your response !

I think that your proposition corresponds to this jsFiddle: http://jsfiddle.net/aromanet42/ffemp77j/. 
Is that was you meant ?
If yes, I am not very fond of what the chart look like: there is an area where the two colors (red & green) are overlapping. I'd rather have this overlapping area stay transparent than having the two colors mixed this way.

**Comment by dubravcik** [comment]
I'd need the same area chart as you...  
In the meantime I used a bar chart, which is far from the requested solution but it provides similar info. Maybe somebody finds it useful:
![image](https://user-images.githubusercontent.com/2481962/35618878-8cd98da4-067c-11e8-98c0-5a11197ae1a1.png)
http://jsfiddle.net/4d4my44z/

**Comment by TheBreadMan** [comment]
I too have found this extremely frustrating. Anything to do with dynamic styling is a huge pain with ReCharts

**Comment by veddermatic** [comment]
I have a way of getting this done in a non-elegant but functional way. Go through the data and get the lowest value for each pair, subtract an amount (you'll probably need to tweak this based on your domain) and then render a pure white 100% opacity area of this "lower" value data set on top of your existing charts. You'll need to exclude it from the tooltip, obviously, but it gets you pretty close with minimal effort.

https://codesandbox.io/s/fake-difference-pr0rk

**Comment by gaurav5430** [comment]
Closed without any information or solution ?

I have a similar requirement for a line chart and for now I am rendering 2 lines, but would be great to have the capability to decide the stroke color based on a function which gets called with the current data

**Comment by JulianLang** [comment]
> Closed without any information or solution ?
> 
> I have a similar requirement for a line chart and for now I am rendering 2 lines, but would be great to have the capability to decide the stroke color based on a function which gets called with the current data

Could share how you do this? I also need to change the color of a line based on the point values

**Comment by gaurav5430** [comment]
I was able to achieve it using a svg gradient with percentages being calculated dynamically.

https://github.com/recharts/recharts/issues/407#issuecomment-631549245

**Comment by tbntdima** [comment]
Hello, here is my solution [https://codesandbox.io/s/focused-euclid-qdlyi](https://codesandbox.io/s/focused-euclid-qdlyi).
I spent looots of time this, hope it can save somebody else's time.

**Comment by jeanlucmongrain** [comment]
> here is my solution

lol `.js`

**Comment by ckifer** [comment]
sorry this got closed randomly a long time ago without an official solution. @tbntdima's looks great and is the way that we recommend this is accomplished. There is a simplified example in the [storybook](https://release--63da8268a0da9970db6992aa.chromatic.com/?path=/story/examples-areachart--area-chart-fill-by-value) and [website](https://recharts.org/en-US/examples/AreaChartFillByValue)
