### ISSUE TITLE
Warning: Expected server HTML to contain a matching <g> in <g>.

### ISSUE THREAD

**Issue by Pimaweichai** [recharts/recharts#1099]
##### current behavior:
react component render by server in next.js

##### problem as below:

<img width="1328" alt="2017-12-19 11 01 04" src="https://user-images.githubusercontent.com/13933022/34138724-f42fc786-e4ab-11e7-984d-4a23c7e5b157.png">

##### version 
"recharts": "^1.0.0-beta.6"

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
