### ISSUE TITLE
How to set the percent of each RadialBar in RadialBarChart?

### ISSUE THREAD

**Issue by Pimaweichai** [recharts/recharts#1100]
## Do you want to request a feature or report a bug?
feature
## What is the current behavior?
The code as below:
```
import  {ResponsiveContainer, RadialBar,RadialBarChart,Legend} from 'recharts';
const data = [
    { uv: 100, fill: '#ffff00' },
    { uv: 20, fill: '#83a6ed' },
    { uv: 30, fill: '#83a6ed' },
];
const SimpleRadialBarChart = () => {
        return (
                <ResponsiveContainer width={200} height={200}>
                <RadialBarChart className="radial" cx="50%" cy="50%" innerRadius='20%' outerRadius="80%" data={data}>
                    <RadialBar minAngle={15}  background clockWise={true} dataKey='uv'/>
                </RadialBarChart>
                </ResponsiveContainer>
        );
    };
```
export default SimpleRadialBarChart;
result is as 
<img width="267" alt="2017-12-19 11 59 43" src="https://user-images.githubusercontent.com/13933022/34140213-253df3fe-e4b4-11e7-8dad-ba819a91ef04.png">

## What is the expected behavior?
how to set the percent of each RadialBar. If I  want  to set the percent of the  yellow circle ,what can i do ?

<img width="226" alt="2017-12-19 12 04 19" src="https://user-images.githubusercontent.com/13933022/34140485-ff45d85e-e4b5-11e7-8340-4a370dde72a9.png">

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
"recharts": "^1.0.0-beta.6"

**Comment by jefferymills** [comment]
It would be nice if you could pass a prop to the RadialBar component specifying a value in the data to be the denominator along with the dataKey that specifies the numerator. So each bar would have its own scale.

`{ uv: 100, pv: 150, fill: '#ffff00', }`

`<RadialBar dataKey='uv' denominator='pv' background />`

**Comment by Pimaweichai** [comment]
@jefferymills , 
bro,  it not worked.
I checked the api document of RadialBar, there's no property named [RadialBar]('denominator'.http://recharts.org/#/en-US/api/RadialBar)

my code is as below:

```
import  {ResponsiveContainer, RadialBar,RadialBarChart} from 'recharts';

const data = [
    { uv: 100,pv:200, fill: '#00ff00' },
    { uv: 100, pv:200,fill: '#ffff00' },
    { uv: 50,pv:200, fill: '#83a6ed' },
    { uv: 50,pv:200, fill: '#83a6ed' },
];

const SimpleRadialBarChart = () => {
        return (
            <ResponsiveContainer width={200} height={200}>
                <RadialBarChart className="radial" cx="50%" cy="50%" innerRadius='20%' outerRadius="80%" data={data}>
                    <RadialBar dataKey='uv' denominator='pv' background />
                </RadialBarChart>
            </ResponsiveContainer>
        );
    };

export default SimpleRadialBarChart;
```

**Comment by jefferymills** [comment]
@Pimaweichai 
My apologies. I was saying it would be nice if it worked that way. It doesn't currently work that way. I'm in the same boat as you.

**Comment by Pimaweichai** [comment]
@jefferymills   yes, much agree with you

**Comment by jefferymills** [comment]
@Pimaweichai In case you haven't discovered yet here is how this can be done: 
```
const data = [
    { uv: 100, fill: '#ffff00' },
    { uv: 20, fill: '#83a6ed' },
    { uv: 30, fill: '#83a6ed' },
];
<RadialBarChart width={200} height={200} data={data}>
    <PolarAngleAxis type="number" domain={[0, 300]} angleAxisId={0} tick={false} />
    <PolarAngleAxis type="number" domain={[0, 200]} angleAxisId={1} tick={false} />
    <PolarAngleAxis type="number" domain={[0, 100]} angleAxisId={2} tick={false} />
    <RadialBar background dataKey="uv" angleAxisId={0} data={[data[0]]} />
    <RadialBar background dataKey="uv" angleAxisId={1} data={[data[1]]} />
    <RadialBar background dataKey="uv" angleAxisId={2} data={[data[2]]} />
</RadialBarChart>
```

**Comment by Pimaweichai** [comment]
@jefferymills  Great, it works well. Thanks a lot~~

**Comment by chrislaskey** [comment]
Thanks @jefferymills!

Your solution works, however the dimensions of the overall chart shrink. Any ideas on how to keep dimensions of the original chart?

**Comment by jefferymills** [comment]
@chrislaskey I was not actually able to figure that out to my liking. I played with the measurements a bunch but couldn't quite get it right. I actually ended up forking the library and adding a solution similar to my first suggestion on this thread.

Basically, I made it so RadialBar accepts a prop called `domainKey` that references a property in the data to use as the max of the scale's domain. Then I just modify the scale's domain within the getComposedData function inside RadialBar.js around line 96.

`{ uv: 100, pv: 150, fill: '#ffff00' }`

`<RadialBar dataKey='uv' domainKey='pv' background />`

```
if (domainKey) {
    angleAxis.scale.domain([0, entry[domainKey]]);
}
```

**Comment by chrislaskey** [comment]
@jefferymills I hear that. Although it's always nice to solve something without having to fork, glad to know it is possible to solve it. Thanks for the quick response and the pointer on where to drop the change. It's much appreciated.

**Comment by felippepuhle** [comment]
thanks @jefferymills

**Comment by svarlamov** [comment]
Adding on to @jefferymills for folks with `n` potential bars, that you can just pass the entire `data` array to the `RadialBar` as usual too. Solution looks like this:

```
const data = [
    { pct: 80, fill: '#ffff00' },
    { pct: 50, fill: '#ffff00' },
    { pct: 70, fill: '#ffff00' },
];
<RadialBarChart width={200} height={200} data={data}>
    <PolarAngleAxis type="number" domain={[0, 100]} dataKey={'pct'} angleAxisId={0} tick={false} />
    <RadialBar background dataKey="pct" angleAxisId={0} data={data} />
</RadialBarChart>
```

**Comment by carcruz** [comment]
@svarlamov Great! Works perfect for me

**Comment by liavst2** [comment]
Hi, I'm following what you wrote and still the max value bar is full. What am I doing wrong?
Thanks.

const data = [
    {name: '1', value: 31.47, fill: '#edd551'},
    {name: '2', value: 26.69, fill: '#18ffff'},
    {name: '3', value: 15.69, fill: '#4fe49d'},
    {name: '4', value: 8.22, fill: '#7d84a0'},
];

render() {
    return (
      <RadialBarChart 
          width={274} 
          height={134} 
          cx={180} 
          cy={65} 
          startAngle={90}
          endAngle={-270}
          innerRadius={45} 
          outerRadius={70} 
          barSize={3} 
          data={data}
      >
      <PolarAngleAxis type="number" dataKey="value" angleAxisId={0} tick={false} tickFormatter={null}/> 
      <RadialBar angleAxisId={0} animationEasing="ease-out" background={{fill: '#262847'}} dataKey="value" data={data}/>
      <Legend iconSize={0} width={120} height={140} layout='vertical' verticalAlign='middle' wrapperStyle={style}/>
      </RadialBarChart>
    )
 }

**Comment by svarlamov** [comment]
@liavst2 I believe that the `domain` prop is sort of critical here... That's how the chart knows what is truly 'zero' and what is the limit of the input... I would reckon without the `domain` prop you are unlikely to get to where you need to be...

Perhaps you're on a different version? I've got `"recharts": "^1.0.0-alpha.2"` in my `package.json`. To add to the mess, I was also using typescript so had to play around with that...

Hope this helps 😄

**Comment by liavst2** [comment]
@svarlamov You're right! I reinstalled and it worked perfectly :) Thanks!!

**Comment by svarlamov** [comment]
@liavst2 Great to hear that 👍

**Comment by madmax141** [comment]
Using version 1.1 and the domain prop doesn't exist on PolarAngleAxis, I'm sort of at a loss here

**Comment by svarlamov** [comment]
@madmax141 I think it's because you're using v1.1

Have you tried setting the version to `^1.0.0-alpha.2` in your `package.json`? This has solved the issue for several folks

**Comment by svarlamov** [comment]
I'm by no means a JS expert, but I think that it picks the latest of these if you delete your `node_modules` dir and re-run `yarn/npm install`

![image](https://user-images.githubusercontent.com/10859025/43872233-421858b4-9bb3-11e8-8d00-ddab568f917e.png)

**Comment by omarsafwany** [comment]
@svarlamov I tried your solution for `n` bars but it does not work as expected.
Expected Chart:
<img width="438" alt="Screen Shot 2019-09-25 at 11 27 30 AM" src="https://user-images.githubusercontent.com/5818047/65588333-9ed74d80-df87-11e9-90c0-0d0902330867.png">

Actual Chart:
<img width="416" alt="Screen Shot 2019-09-25 at 11 27 16 AM" src="https://user-images.githubusercontent.com/5818047/65588353-a8f94c00-df87-11e9-8d02-1c0fa003d1a7.png">

And here's the code to generate the chart:
```
<ResponsiveContainer width="100%" height="100%">
    <RadialBarChart data={this.props.data}>
        {this.props.gradients}
        <PolarAngleAxis type="number" domain={[0, 100]} angleAxisId={0} tick={false} />
        <RadialBar data={this.props.data} background dataKey="value" angleAxisId={0}  barSize= {"5"} />                
    </RadialBarChart>
</ResponsiveContainer>
```

As mentioned, it's something related to the domain but I can't figure it out.
