### ISSUE TITLE
Question about BarChart margins

### ISSUE THREAD

**Issue by tomasruud** [recharts/recharts#1102]
I currently have two charts which are somewhat related. The top chart is displaying temperatures for a time period as a line chart. The bottom chart is displaying precipitation for the same period of time as a bar chart. Ultimately I would like both x-axes to look the same, without the extra margin on the left and the right side (as highlighted on the image).

Is it possible to remove the margins on the x-axis for the bar chart?

![image](https://user-images.githubusercontent.com/5978545/34153006-cd80879c-e4b0-11e7-96d7-1a6a7bdf060b.png)

**Comment by xile611** [comment]
You can change the `padding` and `scale` of `<XAxis />`
