### ISSUE TITLE
Bar Chart cannot draw bars elegantly for categories with different data structure/keys

### ISSUE THREAD

**Issue by joelplums** [recharts/recharts#1105]
Documentation, open issues and existing SO questions seem to not give indication how to resolve the following issue so I presume this is a bug.

### Issue

For a given data set
```
const data = [
   {name: 'Savings', Apples: 100, Oranges: 250},
   {name: 'Spend', Groceries: 1000},
   {name:'Membership Cost', Cost: 50}
];
```
Recharts seems to be drawing each objects' data with a lot of extra padding. I assume the extra padding is caused by the rendering of empty 'bars' belonging to keys only found in other objects for the data set. e.g. for `data[0]` extra space seems to be added for 'Groceries' and 'Cost' found in `data[1]` and `data[2]`

### Fiddle Demo
Here is a JSFiddle demonstrating the behaviour
http://jsfiddle.net/joelplums/fn0swrxv/ 

Thank you for Recharts, its been a pleasure working with :+1:

**Comment by abarandica** [comment]
Did you find any solution? @joelplums

**Comment by KyleAsaff** [comment]
also looking for a solution for this lol
