### ISSUE TITLE
Fails with combination of line chart + error bars + log scale + missing values

### ISSUE THREAD

**Issue by SmoooZ** [recharts/recharts#1107]
## Do you want to request a feature or report a bug?
BUG
## What is the current behavior?
the chart is broken when combining the following settings 
* a missing value
* line chart
* error bars
* log scale

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
broken in beta (tested 6 and 10), but working fine in v0.21.2

**Comment by huxiaoyun** [comment]
can u give an example on jsfiddle ?   thank u ~~~

**Comment by SmoooZ** [comment]
Reproduced here : https://codesandbox.io/s/01v0359knv

As commented in the code there are 4 ways to make it work again in this example:
* put back the missing value (commented out)
* set the scale to linear (instead of log)
* remove the error bars
* make use of BarChart (instead of LineChart)

**Comment by jzillmann** [comment]
Facing the same in version 1.0.1! Getting 
```
Error: <line> attribute y1: Expected length, "NaN".
```

**Comment by SmoooZ** [comment]
any comment or work on going with this issue?  the above provided sandbox should greatly help to fix

**Comment by SmoooZ** [comment]
still broken in 1.8.5

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by vtarelkin** [comment]
@xile611 it still persists.

**Comment by uazure** [comment]
Doesn't seem to be an issue of the charts library, but rather a specifics of log scale. 
For my purpose (displaying lines of data with different orders of magnitude to give idea of the trend of each sequence) it was enough to use `scaleSymlog` from `d3` package. Another idea that could be helpful is to use `scalePow().exponent(0.1)`

So here's my workaround:

```
import { scaleSymlog } from 'd3';
const scale = scaleSymlog();
...
<YAxis scale={scale} ... />
```
