### ISSUE TITLE
Multiple dot types and line types in one data series

### ISSUE THREAD

**Issue by nightlyop** [recharts/recharts#111]
I'm considering to switch to recharts and have a question. I'd like to draw a line which is made of different line types and has dots of different types (see image).

![unbenannt](https://cloud.githubusercontent.com/assets/5469488/15931865/b7dda384-2e59-11e6-99af-3e3806f52428.PNG)

Is that's supported? If not, might a workaround like creating multiple data series and connecting them in the chart work?

**Comment by xile611** [comment]
@nightlyop   Yeah, I think it's a good workaround to create multiple data series, just like <http://jsfiddle.net/ott0xtdy/> .
If there is anything that can't meet your requirement, please let me know.

**Comment by nightlyop** [comment]
@xile611 Thank you, but that's not quite what I want. I'd like to draw one line made of different line types. I forked your example and tried it here: http://jsfiddle.net/nightlyop/ggg0trdh/1/ Unfortunately it does not compile, because I added the property `type="number"` to `XAxis`. Without that property, the two `4` are regarded as two different categories.

**Comment by xile611** [comment]
<http://jsfiddle.net/ggg0trdh/2/>

Maybe you can repeat the value where the line types change.

**Comment by nightlyop** [comment]
The chart is ok. I guess I could use the `content` attribute of the `Tooltip` component to make sure, that the data of the point connecting two series appears only once.

Using `type="number"` does still break the example. Is this my mistake?

**Comment by xile611** [comment]
Yeah, you are right, you can use customized `content` in `Tooltip`. 
I forgot to remove `type="number"`. You can see: <http://jsfiddle.net/ggg0trdh/3/>.
And because the default `type` of `YAxis` is `"number"`,  if you want to set the `type` of both x-axis and y-axis to `"number"`, you should change to `ScatterChart`.
