### ISSUE TITLE
How can I start chart from min or custom value?

### ISSUE THREAD

**Issue by SilencerWeb** [recharts/recharts#1112]
Hello!

How can I start chart from min value or custom value? As I see, charts always start from 0, but what if I want to start it from min value or custom value?

For example, [here](http://jsfiddle.net/b9pjzn9t/84/) I want to start my chart from min value(4000), is it possible?

**Comment by huxiaoyun** [comment]
how about this api  domain
![image](https://user-images.githubusercontent.com/4345248/34339389-678c3cb2-e9ae-11e7-850e-ae3b32dc6c0b.png)

and this demo   http://jsfiddle.net/6eahhf5f/  
it may solve ur problems

**Comment by SilencerWeb** [comment]
@huxiaoyun, yes, it helps! Thank you so much

**Comment by revathi-pumex** [comment]
It worked when the Yaxis was set like
