### ISSUE TITLE
Maximum Call Stack Exceeded 

### ISSUE THREAD

**Issue by PurpleBracket** [recharts/recharts#1115]
## Bug with area charts

Hey, 
When I try to set a maximum tick count on area charts I get the following error:

Uncaught RangeError: Maximum call stack size exceeded
    at Object.getDigitCount (arithmetic.js?88a1:47)
    at getFormatStep (getNiceTickValues.js?3c6b:63)
    at calculateStep (getNiceTickValues.js?3c6b:130)
    at calculateStep (getNiceTickValues.js?3c6b:153)
    at calculateStep (getNiceTickValues.js?3c6b:153)
    at calculateStep (getNiceTickValues.js?3c6b:153)
    at calculateStep (getNiceTickValues.js?3c6b:153)
    at calculateStep (getNiceTickValues.js?3c6b:153)
    at calculateStep (getNiceTickValues.js?3c6b:153)
    at calculateStep (getNiceTickValues.js?3c6b:153)

Can't reproduce in jsfiddle for some reason.. I guess it may be the amount of data passed to the chart. 

Here's my component:

           <ResponsiveContainer width={'100%'} height={'100%'} className={'chartContainer'}>
            <AreaChart data={data}
              margin={{top: 0, right: 0, left: 0, bottom: 0}}>
              <defs>
                <linearGradient id='gradient' x1='0' y1='1' x2='0' y2='0'>
                  <stop offset='0%' stopColor='#a6a2c4' stopOpacity={0.15} />
                  <stop offset='49%' stopColor='#7056bd' stopOpacity={0.15} />
                  <stop offset='80%' stopColor='#3807b7' stopOpacity={0.15} />
                </linearGradient>
              </defs>
              <YAxis tickLine={false} axisLine={false} type='number' domain={['auto', 'auto']} allowDecimals={false} mirror tickCount={2} />
              <Area type='natural' dataKey='uv' stroke='#8884d8' fill='url(#gradient)' />
            </AreaChart>
          </ResponsiveContainer>

Using recharts "^1.0.0-beta.7" in chrome 

Has anyone seen this before?

**Comment by cephirothdy2j** [comment]
We had a similar issue and tracked it down to a domain of `['auto', 'auto']` when dealing with very large numbers in or data. There were some other cases where we got the error, such as `['dataMin', 'auto']`. The error did NOT through for cases such as `['dataMin', 'dataMax']` or [0, 'auto'].

Our workaround was to set our domain to the following, which works well for our purposes:

```
[
   (dataMin) => {
      const axisMin = dataMin - (dataMin * 0.1);
      return dataMin >= 0 && axisMin <= 1 ? 0 : Math.floor(axisMin);
   },
   'auto'
]
```

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
