### ISSUE TITLE
Display label as "name" property instead of "value" property?

### ISSUE THREAD

**Issue by stephenrs** [recharts/recharts#1118]
I'm having trouble understanding the documentation for the label property of the Pie component.

I'd like to show names around the outside of the Pie chart, rather than the default values.

Is there a way to do this?

**Comment by stephenrs** [comment]
Nevermind...I figured it out by setting the label prop to a function, and inspecting the arguments to the function. Thanks!

**Comment by MincePie** [comment]
Please can you show me how you did this. I'm stuck on the same problem

**Comment by stephenrs** [comment]
It's been a long time since I looked at this particular code, but from what I'm seeing now after a quick look, it appears there are 2 pieces to make this work:

1. Define a function to render you labels the way you want, some like:

```
let renderLabel = function(entry) {
    return entry.name;
}
```

2. Set the label prop to point to your function:

```
<Pie label={renderLabel} [ you other properties ]>
[ your content ]
</Pie>
```

I hope this helps.
