### ISSUE TITLE
Syntax error with version 1.0.0-beta.7 in IE11 because ** operator

### ISSUE THREAD

**Issue by cjgarde** [recharts/recharts#1119]
I'm experiencing is a bug even using babel-plugin-recharts. 
When using recharts (v. 1.0.0-beta.7, as well beta.3) in IE11 (and in Windows 10 and Windows 8) and React 16. 

IE11 doesn't understand the ES6 syntax **. You can find it in distanceBetweenPoints function.

This could be fixed using Math.pow

<img width="372" alt="screen shot 2017-12-28 at 13 13 29" src="https://user-images.githubusercontent.com/2249288/34410501-256bb00e-ebd1-11e7-9ee1-10210771cf3d.png">

My .babelrc file contains (using babel-plugin-recharts version 1.1.1):

> {
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["ie >= 11"]
      }
    }],
    "react",
    "es2015"
  ],
  "plugins": [
    "react-hot-loader/babel",
    "transform-object-rest-spread",
    "transform-export-extensions",
    "transform-class-properties",
    "recharts"
  ]
}

**Comment by cjgarde** [comment]
Hi guys,

 Solved including in babel-loader the node_modules recharts file, in the webpack dev and prod file.

 Something like this:

>  const includePaths = ... //paths to include in an array;
>  const includeWithRecharts = include.concat(path.resolve(config.basePath, "node_modules/recharts"));
> 
> 		module: {
> 			loaders: [
> 				{
> 					test: /\.jsx?$/,
> 					include: includeWithRecharts,
> 					loader: "babel-loader"
> 				},

Anyway, would be nice if you could change it to don't include the folder in the babel-loader.
Thanks! :)

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
