### ISSUE TITLE
Published version on NPM is "beta"

### ISSUE THREAD

**Issue by iMerica** [recharts/recharts#1120]
Hi,

Thanks for your work on this excellent library. I was about to upgrade to latest until I noticed the  version on NPM is called "1.0.0-beta.7". It would be good to publish this as `1.0.0` if it is indeed stable and not beta, otherwise it's a bit misleading/confusing.

Thanks,

Michael

P.S The original impetus for upgrading Recharts was that I'm upgrading to React 16 and noticed my currently installed version of recharts uses `React.createClass` (which is not supported in React 16).

**Comment by dmr** [comment]
@xile611 Thank you for merging a few features recently.

Is there a reason not to call recharts 1.0.0?

I think it would be good to just call it 1.0.0 and start with semantic versioning. What do you think?

**Comment by IanVS** [comment]
I'd also love to see a migration guide for 1.0.0.  Are there any breaking changes?  I can't really figure it out, currently.

**Comment by xile611** [comment]
Thanks for your suggestion.
