### ISSUE TITLE
Tooltip not working correctly with activeIndex on pie charts

### ISSUE THREAD

**Issue by joshualcoffee** [recharts/recharts#1125]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
Pie charts that utilize `Tooltip` and `activeIndex` does not work correctly.  The tooltip will not show up unless you re-enter the same sector.
## What is the expected behavior?
for tooltips to work with activeIndex.
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Im not sure.

I will dig a little deeper to see if I can see the underlying problem.  I wanted to throw it out to the community to see if anyone else has had issues with this.

**Comment by joshualcoffee** [comment]
I still have not been able to look through the source to see what the underlying issue is.  I think it has something to do with the re-render and activeIndex not being set for the correct payload on re-render.

For the time being the work around I have is to do something like this.
```javascript
<Tooltip
          data={data}
          dataKey={'value'}
          nameKey={'name'}
          content={<CustomTooltip />}
          activeIndex={this.state.activeIndex}
          wrapperStyle={{ visibility: 'visible'}} />
```

In my custom tooltip I'm doing this:
```javascript
const Tooltip = (props) => {
  const {
    data,
    nameKey,
    dataKey,
    activeIndex
  } = props;

  const metric = data[activeIndex];
  if ( !metric ) { return null; }
  const fill = metric.color || null;
  const blockStyles = Object.assign(colorBlockStyles, { backgroundColor: fill });
  return (
    <div style={wrapperStyles}>
      <table>
        <tr style={trStyles}>
          <td style={tdStyles}>
            <div style={blockStyles} />
            {metric[nameKey]}
          </td>
          <td style={tdStyles}>{metric[dataKey]}</td>
        </tr>
      </table>
    </div>
  );
};
```

Just in cast anyone else runs in to this before it's fixed.  Hopefully I'll be able to help out with this issue soon.

**Comment by ZephD** [comment]
Similar to https://github.com/recharts/recharts/issues/390

**Comment by miteshtagadiya** [comment]
I have the same issue, when I hover over on pieChart then tooltip shows correctly, but when I hover out of the container then tooltip automatic hidden.
I try this and it works, because when we hover out of container then activeIndex is changed automatically and it returns the object, and actually activeIndex is number type so I check for should component update method and it returns true if activeIndex is number only.
So if the activeIndex type is not a number then component will not be updated.

`shouldComponentUpdate(nextProps, nextState) {
    return typeof nextState.activeIndex === "number";
  }
`
