### ISSUE TITLE
[Bug] Y Axis overflow on large numbers

### ISSUE THREAD

**Issue by hosseintalebi** [recharts/recharts#1127]
## Do you want to request a feature or report a bug?
I'm reporting a bug.

## What is the current behavior?
If there are large numbers in the data, then the number shown on the y axis will overflow. Initial solution to this is to add a margin but if you don't know your data in advance or if the data has a large dynamic range then this solution is inefficient. 

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
Here is a jsfiddle example:
http://jsfiddle.net/m1k83awt/

As you can see in the screenshot below, the number on the y axis are not entirely visible:
![image](https://user-images.githubusercontent.com/16542956/34571648-4c2f7f9e-f12c-11e7-88a4-44bd24492c6a.png)

## What is the expected behavior?
It's ideal that the width of the axis is calculated automatically based on the data.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
It happens on 1.0.0-beta.7 and previous versions.

**Comment by danizord** [comment]
Any workaround for now?

**Comment by hueitan** [comment]
I don't think it calculated automatically before ☹️ , so it is kind of styling feature.

**Comment by hosseintalebi** [comment]
My workaround (and I admit it is ugly) is to consider the longest value and add extra margin to the chart so it will accommodate that. The problem is that the margin is there even for values that don't need it.

**Comment by danizord** [comment]
@hosseintalebi I'm doing the same here. That's strange because the whole chart can be responsive, only the Y axis has fixed size :/

**Comment by KagamiChan** [comment]
Would be also glad to see the axis could be responsive or automatically sized, or something like `text-overflow: ellipsis` for css (I do know this does not exist for canvas text).

My work around is to dynamically compute the label text width and choose the max value from them, like this:
```js
let canvas
let root

const getFont = () => {
  const div = root || document.querySelector('#root')
  const style = window.getComputedStyle(div)
  return style.getPropertyValue('font')
}

const getTextWidth = (text) => {
  canvas = canvas || document.createElement('canvas')
  const context = canvas.getContext('2d')
  context.font = getFont()
  const metric = context.measureText(text)
  return Math.ceil(metric.width * 1.1) // measureText method's return value may be slightly underestimated, add some pixels scale it
}
```

**Comment by tapok26** [comment]
Isn't fixed version of recharts yet?
Hey, support team, wake up!

**Comment by KagamiChan** [comment]
@tapok26 I think the mail I received is from you. Sorry for the retarded reply but what's the error message you have with my snippet?

**Comment by DiagoSmith** [comment]
Also encountered this :( 

To set the width "dynamically" I ended up making use of the tick formatter function and a global variable that updates the left margin of the chart based on the length of the tick - the only issue with this is that because the ticks are rendered/formatted after the chart, the chart resizes after the initial load. Also using a global variable is not very nice. 

However on the plus side, if you have a large data set you don't have to loop through every single value but rather just the ticks instead so it's much more performant, and you also don't need to mess around with canvas 😁

**Comment by gustaflindqvist** [comment]
We have the same problem with overflow for Y-axis. Might need to consider add extra margin or set width dynamically. Workarounds. :(

**Comment by Ej-leone** [comment]
I solved mine by  calculating my max values and setting them   with 
` <YAxis type="number" domain={[0,  'enter your max value ']} />`

**Comment by xile611** [comment]
Duplicated with #2027

**Comment by pavanjn** [comment]
Added a width in the tick of the YAxis with the left margin to the bar chart, somewhat fixed the issue for a long labels in yaxis

```
<BarChart data={ data } layout="vertical" margin={{ top: 5, right: 0, left: 200, bottom: 5  }}>
```

```
<YAxis type="category" dataKey="name" tick={{ fontSize: 14, width: 250 }} />
```

**Comment by louis97** [comment]
Setting a margin at <BarChart>  did the trick for me.

**Comment by rahulraj-120799** [comment]
<BarChart
        width={width}
        height={height}
        data={data}
        margin={{
          top: 20,
          right: 30,
          left: 35,
          bottom: 50,
        }}
      />
set margin in barchart, It will help

**Comment by GBachheimer** [comment]
You can change the fontSize with tick={{ fontSize: 10 }} until numbers will fit:
<XAxis dataKey="time" tick={{ fontSize: 10 }} />
<YAxis type = "number" tick={{ fontSize: 10 }} />

**Comment by kodo-yousif** [comment]
You can set `tickSize={0}`

cause what is causing this overflow is the tick and its size, it will push the text to the overflow area, then some how adding some margin

you can set it to 0 or just find a way to fix the `tick` and not the width of `YAxis`

`            <YAxis
              tickSize={0}`

**Comment by kavitasingh1993** [comment]
I Added the below line
 <YAxis type="category" dataKey="name"  tick={{ fontSize: '8px', width: 300, height:150,wordBreak:"break-word" }} interval={0} fontSize={12}  />

I need the yaxis data to come in multiple line if the data is large but currently it hides the initial data and after that the data are coming.
For eg: Export Cables within the HHW SAC 
for the above data it just displays "Cables within the HHW SAC" and the initial data is hidden.

**Comment by toms** [comment]
I dynamically set the tick width according to a specific font size by using the formula `tickWidth = largestTick x charPxWidth` in my component by doing something like:

```jsx
import { useState } from 'react';

function exampleDynamicTicks() {
  const [longestTick, setLongestTick] = useState('');

  const tickFormatter = (val) => {
    const formattedTick = // do your formatting here (if you don't format, just set it to val)
    if (longestTick.length < formattedTick.length) {
      setLongestTick(formattedTick);
    }
    return formattedTick;
  };

  const getYAxisTickLen = () => {
    const charWidth = 8; // example w/ estimated 8px width/char
    return longestTick.length * charWidth;
  };

  return (
    <WhateverChartYouUse>
      <YAxis tickFormatter={tickFormatter} width={getYAxisTickLen()} />
    </WhateverChartYouUse>
  );
}
```

**Comment by liorEhrlich** [comment]
This was also discussed in https://github.com/recharts/recharts/issues/1618

> I set `overflow: 'visible'` to the chart component and the labels are fully visible:
> 
> ```
> <BarChart
>   {...{
>      overflow: 'visible'
>    }}
> >
> ```
> 
> (I used the spread syntax, because else typescript would complain that the overflow prop does not exist)

**Comment by jsonchou** [comment]
``` js
<YAxis type="number" 
tickCount={100} // default 5
 />
```
It will show all your view data.
