### ISSUE TITLE
layout=vertical doesn't work (at least in bar charts)

### ISSUE THREAD

**Issue by jobjorn** [recharts/recharts#1128]
I want a vertical bar chart. Simple enough! Just add `layout="vertical"`.

Unfortunately, it doesn't work.

Adding `layout="vertical"` to the `BarChart` tag in the [JSFiddle linked from the documentation](http://jsfiddle.net/v8gxrbyu/) produces this:
![cut from jsfiddle](https://user-images.githubusercontent.com/6715772/34619142-75026722-f241-11e7-9345-309aed778f3f.PNG)

**Comment by feelCrazy** [comment]
https://github.com/recharts/recharts/issues/746

**Comment by atapas** [comment]
It doesn't work.. how come it is closed?

**Comment by zhangwins** [comment]
still seeing this same issue

**Comment by bryg217** [comment]
Same.

**Comment by williamfenu** [comment]
> I thought the same, but the issue linked contains the solution.

Thanks for advise

**Comment by akhilaravind** [comment]
> #746

This the solution, for those who are looking for fix, please refer this
