### ISSUE TITLE
PolarAngleAxis: how to set custom ticks

### ISSUE THREAD

**Issue by ABBVelocityDev** [recharts/recharts#1129]
recharts version: 1.0.0-beta.6

I am creating a RadarChart, where each angle axis value corresponds to an hour-of-day on a 24-hour clock.  It is possible to have datasets for which not all 24 hours are present; however, I want all 24 hours represented on the chart axis even when they are not present in the data.

I first attempted to fill in my data set with null values for the missing 24 hours.  However, the chart treats the null values as 0 values when drawing, which is not desirable, particularly if there are negative values in the data set.  If I instead use the minimum value in the chart for each missing hour, then the tooltips show values for those hours, which could be confusing for our users.

My next thought is to try to specifically set the PolarAngleAxis ticks to include all 24 hours and use the unmodified data source with missing hours.  Can you please help me with a working sample of using custom ticks?  If there is a better way to achieve my goal, please let me know.

Thanks.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
