### ISSUE TITLE
Values over Bars in BarChart

### ISSUE THREAD

**Issue by NoWay1201** [recharts/recharts#113]
I need a BarChart, where Bars values will be displayed over them. Im attaching image, showing what Im talking about. How can I easly achieve that?
![screen](https://cloud.githubusercontent.com/assets/11422162/16005321/ebe3b528-3166-11e6-9e96-87f023df1d76.png)

**Comment by xile611** [comment]
@NoWay1201 
Where do you want to attach images?

**Comment by NoWay1201** [comment]
This image just shows what Im talking about. I want to display values over Bars, like it's presented on image, that I attached.

**Comment by xile611** [comment]
@NoWay1201  
Is this (<http://jsfiddle.net/nbk125Lj/>) what you want? 
If it is, you just need to set "label={true}" in `Bar`.

**Comment by NoWay1201** [comment]
Yes, thats what Im talking about. Thank you.
