### ISSUE TITLE
YAxisId easily breaks chart

### ISSUE THREAD

**Issue by tracykm** [recharts/recharts#1131]
## Do you want to request a feature or report a bug?
bug

## What is the current behavior?
specifying a yAxisId without using it breaks the chart

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
http://jsfiddle.net/rkgdgs8c/
the only thing I changed was adding the `yAxisId`

## What is the expected behavior?
able to add a `yAxisId` whether you have a matching `<Line yAxisId="4" />`

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

I don't think there is a version it worked in. I'm using recharts@1.0.0-beta.7

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
