### ISSUE TITLE
I don't like blinking LabelList. How can I prevent blinking it?

### ISSUE THREAD

**Issue by LunaJeong** [recharts/recharts#1133]
I'd like to place LabelList on my bar graph, so I did:
```
<Bar dataKey=count>
    <LabelList dataKey="count" position="right"
</Bar>
```

and my data are
```
data = [
{ name: "O", count: 0 },
{ name: "X", count: 0 }
]
```

and my data will be updating by certain action.

In this situation, I can find the LabelList is blinking whenever the data are updating,
but I don't like it. 

How can I stop it?
I think it is because of animation effect. 
Can I stop LabelList animation only?

**Comment by hueitan** [comment]
+1

**Comment by huxiaoyun** [comment]
can u give an example on  jsfiddle ?? thank u ~

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
