### ISSUE TITLE
scale time with one hour intervals

### ISSUE THREAD

**Issue by Rd30** [recharts/recharts#1137]
Hello everyone. I am trying to use recharts XAxis for time series. I have points(data) coming in every minute. I am not able to resolve how to set the scale='time' to one hour time interval. Any help would be highly appreciated. Thank You.

**Comment by Rd30** [comment]
Thanks a lot Tom :)

**Comment by maracuja-juice** [comment]
How can I do this without d3?

**Comment by maracuja-juice** [comment]
@tkeffer 
I get
```
TS2345: Argument of type 'TimeInterval | null' is not assignable to parameter of type 'TimeInterval'.
```
on the line: 
`const ticks = domainToday.ticks(d3.timeHour.every(1));`

Where am I going wrong?

**Comment by BreakBB** [comment]
@tkeffer Thanks for your example it helped me a lot. As you already hinted recharts doesn't like different formats than unix timestamps. Therefore I had to pass an array with unix timestamps to domain like ```domain={[startTime, endTime]}```.

**Comment by Nawal00** [comment]
Can anyone share a working example on recharts? 
@Rd30 did you solve this?

**Comment by corneliushka** [comment]
UP ! Also, I cannot understand how use this in recharts.js 
Should I use recharts with D3 package & apply D3 logic ? 

>  const now = new Date();
>    const domainToday = d3.scaleTime().domain([d3.timeDay.floor(now), d3.timeDay.ceil(now)]);
>    const timeFormatter = (tick) => {return d3.timeFormat('%H:%M:%S')(new Date(tick));};
>    const ticks = domainToday.ticks(d3.timeHour.every(1));

**Comment by gaurav5430** [comment]
> UP ! Also, I cannot understand how use this in recharts.js
> Should I use recharts with D3 package & apply D3 logic ?
> 
> > const now = new Date();
> > const domainToday = d3.scaleTime().domain([d3.timeDay.floor(now), d3.timeDay.ceil(now)]);
> > const timeFormatter = (tick) => {return d3.timeFormat('%H:%M:%S')(new Date(tick));};
> > const ticks = domainToday.ticks(d3.timeHour.every(1));

These are the things i needed to install for this to work:
`d3-time` for `timeHour`
`d3-time-format` for `timeFormat`
`d3-scale` for `scaleTime`

**Comment by columk1** [comment]
Here's another solution without using d3 libraries. My data was coming in with Unix timestamps at odd intervals over an unfixed period, but I wanted ticks on the hour.

```js
const getXAxisTicks = () => {
  const ONE_HOUR = 3600000
  const startTime = data.time[0]
  const endTime = data.time[data.time.length - 1]

  // Round the startTime up to the nearest whole hour
  const firstHour = Math.ceil(startTime / ONE_HOUR) * ONE_HOUR

  // Calculate the number of hours between the rounded start time and the end time
  const hourlyTicks = Math.ceil((endTime - firstHour) / ONE_HOUR)

  // Generate an array of timestamps for each hour
  return Array.from({ length: hourlyTicks }, (_, i) => firstHour + i * ONE_HOUR)
}

// ...Chart...
<XAxis
  dataKey='time'
  domain={['auto', 'auto']}
  scale='time'
  tickFormatter={(time) => new Date(time).toLocaleString('en-US', { hour: '2-digit' })}
  ticks={getXAxisTicks()}
  type='number'
/>
```

**Comment by ckifer** [comment]
Technically d3 is still being used since recharts uses d3 for scale, but looks good!
