### ISSUE TITLE
[Docs] ResponsiveContainer has undocumented prop maxHeight

### ISSUE THREAD

**Issue by iamvanja** [recharts/recharts#1138]
## Do you want to request a feature or report a bug?
Report an undocumented prop in `ResponsiveContainer`

## What is the current behavior?
`maxHeight` is respected, but http://recharts.org/#/en-US/api/ResponsiveContainer does not mention it.

## What is the expected behavior?
`maxHeight` should be mentioned at http://recharts.org/#/en-US/api/ResponsiveContainer

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts v1.0.0-beta.6

**Comment by xile611** [comment]
Thanks! PR to [recharts.org](https://github.com/recharts/recharts.org) is welcome.
