### ISSUE TITLE
Incorrect domain when using dataMin, auto

### ISSUE THREAD

**Issue by drj17** [recharts/recharts#1139]
## What is the current behavior?
When trying to implement a timescale, the domain prop doesn't seem to work properly. when using `domain={["dataMin, "auto"]}` the first point is in the middle of the graph. If I use `domain={["dataMin, "dataMax"]}` the first point is in the correct position, however the last point stretches to the end of the graph.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar

Here's a recreation of this issue, you'll notice that the first point is in the middle of the graph
http://jsfiddle.net/uqk3n59q/

## What is the expected behavior?
I would expect the first point to be at the start of the graph, instead of somewhere in the middle.  This seems like a bug to me but maybe I'm just implementing it wrong?

**Comment by adoel90** [comment]
After i face the same problem with dataMin, dataMax in Recharts, i think instead use domain=["dataMin", "dataMax"].

We can simply to solve the bug dataMin dataMax with `domain=[Math.min(...valueTemperatureY), Math.max(...valueTemperatureY)]`

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
