### ISSUE TITLE
Bug: Mirror axis gets obscured by the chart

### ISSUE THREAD

**Issue by cbovis** [recharts/recharts#1140]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
When the axis is mirrored it can get obscured by the chart due to the ordering of SVG elements.

![doh](https://user-images.githubusercontent.com/34132/34968989-a8d226dc-fac0-11e7-87b0-d437c53882f0.png)

## What is the expected behavior?
The axis should be displayed on top of the chart or there should be an option to choose preferred behaviour.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.0.0-beta.9

**Comment by christiancho** [comment]
@cbovis It's not a bug. SVG elements will order depth in order of rendering. Make sure you put your `YAxis` component after your `Area` component (or whatever component you're using).

**Comment by cbovis** [comment]
Thanks @christiancho , this resolved my issue so I'm closing it off 😄
