### ISSUE TITLE
onMouseEnter type definition is not accurate

### ISSUE THREAD

**Issue by thomasthiebaud** [recharts/recharts#1141]
## Do you want to request a feature or report a bug?
Report a bug

## What is the current behavior?
Based on the documentation (http://recharts.org/#/en-US/examples/CustomActiveShapePieChart), `onMouseEnter` accepts at least 2 arguments, but in the type definition, `onMouseNeter` is define as follow

```
export type RechartsFunction = () => void;
onMouseEnter?: RechartsFunction;
```

## What is the expected behavior?
`onMouseEnter` should be correctly defined

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

```
    "@types/recharts": "1.0.10",
    "typescript": "2.6.2"
    "react": "16.2.0",
    "recharts": "1.0.0-beta.9"
```

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
