### ISSUE TITLE
Custom tooltip + dot does not get stroke information.

### ISSUE THREAD

**Issue by troyblank** [recharts/recharts#115]
Hello,

I am working with recharts and and trying to produce something like this:

![mock](https://cloud.githubusercontent.com/assets/996725/16024302/a70bc204-3186-11e6-8e22-74df5c99ff9c.png)

But this is not easy to achieve with recharts as the stroke I get for any custom tooltip or active dot seems to be hardcoded to `#fff`.

The fill is the only thing that has my custom color information passed down, and considering it's a reference to a gradient it doesn't do me much good. The closest I can get achieving the look given the information is this:

![weirddot](https://cloud.githubusercontent.com/assets/996725/16024411/4e02d548-3187-11e6-90f7-2411a6738595.png)

I have made a jsfiddle to demo this:

http://jsfiddle.net/troyblank/ae55bfLm/6/

As you can see `{props.stroke}` is always `#fff` on any custom dot, and there is no stroke information for custom tooltip payloads to use. It would be a lot more useful for both cases to have the stroke color of the actual line in which it is referencing, which in jsfiddle's case is `#82ca9d`. This would allow any custom tooltip or dot work to be able to really leverage the colors set by any gradient area.

Thanks for an amazing tool outside of this issue, and let me know if I can elaborate on this issue.

**Comment by xile611** [comment]
Thank you for your advice! We'll add more information for customized tooltip payload. 

And you can achieve your target by managing the colors outside (<http://jsfiddle.net/nbsb32nd/>), but it seems to be not elegant.

**Comment by troyblank** [comment]
Thank you and thank you for the advice. My team actually came to that conclusion this morning as well. It works pretty straightforward for the dot. The tooltip does work with custom data, but as you said is not as elegant. `<CustomTooltip colors={{ someProp: blue, someOtherProp purple }} /`

**Comment by xile611** [comment]
Yeah, we'll fix this in the next version.

**Comment by xile611** [comment]
Fixed in version  0.11.0.
