### ISSUE TITLE
Pie Chart Background Color?

### ISSUE THREAD

**Issue by bhellman1** [recharts/recharts#1150]
When creating a PieChart like so: 
<img width="190" alt="screen shot 2018-01-23 at 11 36 00 am" src="https://user-images.githubusercontent.com/298219/35296685-af52860c-0031-11e8-89de-8ac369ef30f5.png">

Is it possible to add a background color of gray, so when the pie chart first renders you see the arc with the gray background and then the value fills with the value's color?

**Comment by breadadams** [comment]
![pie_chart_background](https://user-images.githubusercontent.com/5795227/39609408-ffbbdb64-4f48-11e8-962f-c1781bd3d4cc.gif)

Something like this @bhellman1? I've managed to achieve the effect stacking 2 `<Pie/>`'s like so:

```jsx
const EXAMPLE_DATA = [
  {
    name: 'example1',
    value: 25,
  },
  {
    name: 'example2',
    value: 75,
  }
];

<PieChart>
  <Pie data={[{ value: 100 }]} dataKey="value" innerRadius="86%" outerRadius="100%" fill="#0000ff" isAnimationActive={false} />
  <Pie data={EXAMPLE_DATA} dataKey="value" innerRadius="86%" outerRadius="100%" fill="#ff0000" paddingAngle={20} />
</PieChart>
```

**Comment by SergheiTibulschii** [comment]
> ![pie_chart_background](https://user-images.githubusercontent.com/5795227/39609408-ffbbdb64-4f48-11e8-962f-c1781bd3d4cc.gif)
> 
> Something like this @bhellman1? I've managed to achieve the effect stacking 2 `<Pie/>`'s like so:
> 
> ```js-jsx
> const EXAMPLE_DATA = [
>   {
>     name: 'example1',
>     value: 25,
>   },
>   {
>     name: 'example2',
>     value: 75,
>   }
> ];
> 
> <PieChart>
>   <Pie data={[{ value: 100 }]} dataKey="value" innerRadius="86%" outerRadius="100%" fill="#0000ff" isAnimationActive={false} />
>   <Pie data={EXAMPLE_DATA} dataKey="value" innerRadius="86%" outerRadius="100%" fill="#ff0000" paddingAngle={20} />
> </PieChart>
> ```

Thanx a lot! Worked perfectly

**Comment by Thatchidinma** [comment]
> ![pie_chart_background](https://user-images.githubusercontent.com/5795227/39609408-ffbbdb64-4f48-11e8-962f-c1781bd3d4cc.gif) [ ![pie_chart_background](https://user-images.githubusercontent.com/5795227/39609408-ffbbdb64-4f48-11e8-962f-c1781bd3d4cc.gif) ](https://user-images.githubusercontent.com/5795227/39609408-ffbbdb64-4f48-11e8-962f-c1781bd3d4cc.gif) [ ](https://user-images.githubusercontent.com/5795227/39609408-ffbbdb64-4f48-11e8-962f-c1781bd3d4cc.gif)
> 
> Something like this @bhellman1? I've managed to achieve the effect stacking 2 `<Pie/>`'s like so:
> 
> ```js
> const EXAMPLE_DATA = [
>   {
>     name: 'example1',
>     value: 25,
>   },
>   {
>     name: 'example2',
>     value: 75,
>   }
> ];
> 
> <PieChart>
>   <Pie data={[{ value: 100 }]} dataKey="value" innerRadius="86%" outerRadius="100%" fill="#0000ff" isAnimationActive={false} />
>   <Pie data={EXAMPLE_DATA} dataKey="value" innerRadius="86%" outerRadius="100%" fill="#ff0000" paddingAngle={20} />
> </PieChart>
> ```

2024 and this still came in handy, Thank you!
for anyone using this with a legend component just add ` legendType='none' ` to the background pie chart
