### ISSUE TITLE
LineChartHasMultiSeries don't support <Brush /> bar and zoom data.

### ISSUE THREAD

**Issue by ntatuan411** [recharts/recharts#1152]
I you can update for MultiSeries line chart support Brush and zoom data.

**Comment by DmitryEremenko** [comment]
Any changes with this issue?

**Comment by mudrila** [comment]
Still nothing? :(

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
