### ISSUE TITLE
How to set the domain on a RadialBarChart?

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#1157]
There does not appear to be a way to set the domain for a RadialBarChart. Currently, the radial bars are scaled to the full size of the bars (so the bar with the highest value always appears as a circle, assuming defaults for startAngle/endAngle). For a regular bar chart, the domain of the YAxis allows the bars to be scaled independently of the physical size of the chart.

**Comment by lfbayer** [comment]
I would like to do the same thing. According to #171 it sounds like this isn't supported using the RadialBarChart.

**Comment by jakubbloksa** [comment]
I am trying to workaround this by adding one "max" data value, while setting the color to the color of the background to make it invisible. But I can't get rid of the "background border"... Any ideas how to do this?
![image](https://user-images.githubusercontent.com/4365817/97801668-ac590f80-1c3e-11eb-9eb3-fcb792de2df0.png)

**Comment by spyrosbazios** [comment]
Hi I was facing the same issue !

You can use inside the RadialBarChart , to specify the bar range with the domain 

`        <PolarAngleAxis
          type="number"
          domain={[0, 100]}
          angleAxisId={0}
          tick={true}
        />
`

**Comment by tran-simon** [comment]
@spyrosbazios 
Thanks for the solution! This should probably be in the doc

**Comment by ckifer** [comment]
@tran-simon feel free to open a PR! This should be visible in the storybook at least
