### ISSUE TITLE
Feature request: Does recharts supports react-native

### ISSUE THREAD

**Issue by VineethArvindFluke** [recharts/recharts#1161]
Feature request: Does recharts supports react-native?

**Comment by VineethArvindFluke** [comment]
Any updates on this feature request. Is there anyway we can use recharts in react-native.

**Comment by seekshiva** [comment]
You can see in #188 that they've mentioned they don't have enough experience with mobile design to add support.

Someone [commented there](https://github.com/recharts/recharts/issues/188#issuecomment-349839407) about how they were able to do it. Perhaps that might be useful for you.

**Comment by bakhaa** [comment]
+1

**Comment by xile611** [comment]
Related PR is still welcome
