### ISSUE TITLE
how to display icon instead x-axis label ?

### ISSUE THREAD

**Issue by elinortl** [recharts/recharts#1162]
I was trying to follow the example from the getting-started page but i couldn't customize the x-axis label. are there any examples  to see how to customize it by using icons? thanks

**Comment by aprasad-cs** [comment]
any updates on this?

**Comment by ilyichvismara** [comment]
I recently find a way, it depends on which icon library you are using. 
In general you have to create a custom component to assign to the `tick` property. 

So in your chart you will write something like
`<XAxis  axisLine={false} tickLine={false} tick={<this.CategoryTick/>} />`

And then you define your custom tick as follows 
```
CategoryTick = props => {
   return <foreignObject x={props.x - 10} y={props.y} width={20} height={30} style={{fill: "#BCBCBC",}}><i  className={this.props.data[props.payload.value].icon}></i></foreignObject>
}
```

As you can see I returned a `<foreignObject>` that lets you insert HTML in, in my case I inserted an `<i>` with the icon related className.

**Comment by DenHelsing** [comment]
> I recently found a way, it depends on which icon library you are using.
> In general you have to create a custom component and assign it to the `tick` property.
> 
> So in your chart you will write something like
> `<XAxis axisLine={false} tickLine={false} tick={<this.CategoryTick/>} />`
> 
> And then you define your custom tick as follows
> 
> ```
> CategoryTick = props => {
>    return <foreignObject x={props.x - 10} y={props.y} width={20} height={30}><i  className={this.props.data[props.payload.value].icon}></i></foreignObject>
> }
> ```
> 
> As you can see I returned a `<foreignObject>` that lets you insert HTML in, in my case I inserted an `<i>` with the icon related className.

What if I want to display different icons depending on my Y axis? I tried passing an array with different icons to "ticks" prop, but X-axis just disappears.
