### ISSUE TITLE
Reference line "isFront" prop doesn't seem to work

### ISSUE THREAD

**Issue by jparklev** [recharts/recharts#1163]
## Do you want to request a feature or report a bug?

report a bug

## What is the current behavior?

The reference line is rendered behind the chart even though the inFront prop is set to true

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

Code:
`        <ReferenceLine
          x={minRatioObj.i}
          stroke="#fb8f93"
          alwaysShow
          label={{
            position: "top",
            value: "Lowest Ratio",
            fill: "white",
            fontSize: 14,
            dy: 12,
            dx: dx,
            fillOpacity: 1
          }}
          strokeDasharray="3 3"
          strokeWidth={2}
          isFront={true}
        />`

Demo:
<img width="165" alt="screen shot 2018-01-30 at 2 12 50 am" src="https://user-images.githubusercontent.com/24902242/35555136-df953986-0563-11e8-9580-7153d9fdc928.png">

## What is the expected behavior?

For the reference line to be rendered in front of the other cartesian components

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

It's the same in both Chrome & Safari. I'm using recharts 1.0.0-beta.9

**Comment by SimchaShats** [comment]
Is here any updates?

**Comment by jorgeto86** [comment]
I have the same problem! Any solution?

Thanks

**Comment by sarates** [comment]
Still without any updates?

**Comment by amonsech** [comment]
Not sure if this works for your case, but moving your <ReferenceLine/> to the end of your chart should do the trick. SVG's will render based on document order by default.

```
<Chart>
    <Bar/>
    ...
    <ReferenceLine/>
</Chart>
```

**Comment by Eric24** [comment]
Is the isFront property even really needed (i.e. should it be deprecated), since the order of chart sub-components defines the "layering" of how they appear?

**Comment by sanehab** [comment]
@Eric24  I think it should still be there, think of cases where you conditionally render components but you still want to make them appear inFront on certain conditions. In fact i think that this property should be there for any svg component that appears on screen, and not only ReferenceLine. 

Btw, at the time i'm writing this, it still seems not working.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.

**Comment by Sotatek-ThuyetNguyen** [comment]
> Not sure if this works for your case, but moving your `<ReferenceLine/>` to the end of your chart should do the trick. SVG's will render based in document order by default.
> 
> ```
> <Chart>
>     <Bar/>
>     ...
>     <ReferenceLine/>
> </Chart>
> ```
Work for me!
