### ISSUE TITLE
two lines with different data sources 

### ISSUE THREAD

**Issue by pablobovi** [recharts/recharts#1167]
Hey there is any way to do that, i mean i'm working with a line chart with two lines and in the samples you're using just one data constant for both lines, thanks in advance

**Comment by Penson122** [comment]
I don't know if there is a correct solution, but I couldn't find a way to attach a particular data series to a particular plotting component. Only globally to the parent container.

I'm using multiple data sources, up to 4 in some cases and some with different lengths. I'm using `map` and `Object.assign` to put them all into one array like this:

```
const series = modelMeans.map((x, i) => {
      let res = ({ year: x.year, range: [x.data[0].mean, x.data[1].mean] });
      return Object.assign(res, hadCrutMeans[i] && {
        hadcrutMean: hadCrutMeans[i].mean,
        cowtanMean: cowtanMeans[i].mean,
        gistempMean: gistempMeans[i].mean
      });
    });
```

Luckily in my case they all have the same period in the y axis, one is just longer than all the others.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by gaurav5430** [comment]
Does the latest version solve this problem of two Lines having different data sources ?

**Comment by yeddlapurishivasai** [comment]
Hey @gaurav5430 was trying to do the same today. you can pass data to Line instead of Linechart

```
const {LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend} = Recharts;
const data1 = [
      {name: 10,  pv: 2400, amt: 2400},
      {name: 20,  pv: 1398, amt: 2210},
      {name: 30,  pv: 9800, amt: 2290},
      {name: 40,  pv: 3908, amt: 2000},
      {name: 50,  pv: 4800, amt: 2181},
      {name: 60,  pv: 3800, amt: 2500},
      {name: 70,  pv: 4300, amt: 2100},
];

const data2 = [
      {name: 10, uv: 4000, amt: 2400},
      {name: 45, uv: 3490, amt: 2100},
];
const SimpleLineChart = React.createClass({
	render () {
  	return (
    	<LineChart width={600} height={300}
            margin={{top: 5, right: 30, left: 20, bottom: 5}}>
       <XAxis type="number" dataKey="name" domain={['auto', 'auto']} />
       <YAxis/>
       <CartesianGrid strokeDasharray="3 3"/>
       <Tooltip/>
       <Legend />
       <Line type="monotone" data={data1} dataKey="pv" stroke="#8884d8" activeDot={{r: 8}}/>
       <Line type="monotone" data={data2} dataKey="uv" stroke="#82ca9d" />
      </LineChart>
    );
  }
})

ReactDOM.render(
  <SimpleLineChart />,
  document.getElementById('container')
);
```

**Comment by gaurav5430** [comment]
@yeddlapurishivasai that's great. I have solved my current use case by using functions to pass different data to different Line charts, but this would give me more flexibility. Would try this out.

**Comment by devdream123** [comment]
> Hey @gaurav5430 was trying to do the same today. you can pass data to Line instead of Linechart
> 
> ```
> const {LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend} = Recharts;
> const data1 = [
>       {name: 10,  pv: 2400, amt: 2400},
>       {name: 20,  pv: 1398, amt: 2210},
>       {name: 30,  pv: 9800, amt: 2290},
>       {name: 40,  pv: 3908, amt: 2000},
>       {name: 50,  pv: 4800, amt: 2181},
>       {name: 60,  pv: 3800, amt: 2500},
>       {name: 70,  pv: 4300, amt: 2100},
> ];
> 
> const data2 = [
>       {name: 10, uv: 4000, amt: 2400},
>       {name: 45, uv: 3490, amt: 2100},
> ];
> const SimpleLineChart = React.createClass({
> 	render () {
>   	return (
>     	<LineChart width={600} height={300}
>             margin={{top: 5, right: 30, left: 20, bottom: 5}}>
>        <XAxis type="number" dataKey="name" domain={['auto', 'auto']} />
>        <YAxis/>
>        <CartesianGrid strokeDasharray="3 3"/>
>        <Tooltip/>
>        <Legend />
>        <Line type="monotone" data={data1} dataKey="pv" stroke="#8884d8" activeDot={{r: 8}}/>
>        <Line type="monotone" data={data2} dataKey="uv" stroke="#82ca9d" />
>       </LineChart>
>     );
>   }
> })
> 
> ReactDOM.render(
>   <SimpleLineChart />,
>   document.getElementById('container')
> );
> ```

I tried this one , it works for lines but the x-axis is broken.

**Comment by gaurav5430** [comment]
I also realized that in my case my approach with accessor functions to access data from different objects only works because both the series data are derived from the data passed to the `LineSeries`. In case the data is not derived, all the different automatic calculations that happen internally might break because they would only be considering the data that is passed to the top level container, instead of to specific Line series. 

That might be a reason why the above examples for @ktrip96 and @devdream123 are broken

**Comment by gaurav5430** [comment]
Here is the issue discussing different ways of accessing data in Recharts: https://github.com/recharts/recharts/issues/383

Also, here is a post documenting the different ways of accessing data in Recharts and some workarounds: [Exploring Recharts: different ways to access data](https://medium.com/@gaurav5430/exploring-recharts-different-ways-of-accessing-data-d9d6f2caf0b8?source=friends_link&sk=718cf5faa69a1d96db05e37063156a5c)

**Comment by talor-hammond** [comment]
Late here, but a problem I ran into was two-different data sources for a `ComposedChart` (I wanted to display a `Line` and `Area` with different data-sources) -- I solved it by merging the two data sources into one array:

### Setup
```jsx
// merge two different data sources into one array
  const data = oneSourceOfData.map(
    (datum, i) => ({
      [DATA_KEY_AGE]: datum.age,
      [DATA_KEY_ACTUAL_PROJECTION]: datum.balance,
      [DATA_KEY_TARGET_PROJECTION]:
        otherSourceOfData[i].balance, // in my case each data source is a consistent length so i can safely use indexing here
    }),
  );
```

### Rendering
```jsx
       <ComposedChart data={data}>
            <Area dataKey={DATA_KEY_ACTUAL_PROJECTION} />
            <Line dataKey={DATA_KEY_TARGET_PROJECTION} />
        </ComposedChart>
```

**Comment by GoetheProductions** [comment]
In case anyone runs into an issue of dublicate xaxis with two data sources (like i did), here is a solution for that as well:

```
<LineChart>
     <XAxis dataKey="date" xAxisId={"benchmark"} interval={datesInterval} />
     <XAxis hide={true} dataKey="date" xAxisId={"value"} interval={datesInterval} />                              
      <YAxis />                            
       <Line xAxisId={"value"}  data={assets.complexAssetChartData} type="monotone" dataKey="value" stroke="#8884d8" dot={null} activeDot={{ r: 8 }} />
       <Line xAxisId={"benchmark"} data={assets.benchmarkChartData} type="monotone" dataKey="benchmark" stroke="#82ca9d" dot={null} activeDot={{ r: 8 }} />
 </LineChart>
```

create an `<XAxis />` for each datasource and optionally hide the ones you dont need. It is important to set `xAxisId` on the `<Line />` component

**Comment by Bhavyam-Arora** [comment]
I want to make bars from different data and Xaxis from different data can anyone help me please?

**Comment by Emokores256** [comment]
> Late here, but a problem I ran into was two-different data sources for a `ComposedChart` (I wanted to display a `Line` and `Area` with different data-sources) -- I solved it by merging the two data sources into one array:
> 
> ### Setup
> ```js
> // merge two different data sources into one array
>   const data = oneSourceOfData.map(
>     (datum, i) => ({
>       [DATA_KEY_AGE]: datum.age,
>       [DATA_KEY_ACTUAL_PROJECTION]: datum.balance,
>       [DATA_KEY_TARGET_PROJECTION]:
>         otherSourceOfData[i].balance, // in my case each data source is a consistent length so i can safely use indexing here
>     }),
>   );
> ```
> 
> ### Rendering
> ```js
>        <ComposedChart data={data}>
>             <Area dataKey={DATA_KEY_ACTUAL_PROJECTION} />
>             <Line dataKey={DATA_KEY_TARGET_PROJECTION} />
>         </ComposedChart>
> ```

This solution is straightforward and I think the best. It has worked for me.

**Comment by alleksei37** [comment]
I found the following option useful in order to remove duplication on the XAxis:
`allowDuplicatedCategory={false}`
