### ISSUE TITLE
Tooltip not showing when data array has only one item

### ISSUE THREAD

**Issue by Nishchit14** [recharts/recharts#117]
Here is [fiidle](http://jsfiddle.net/mcf1akad/1/)

If data has only one item then tooltip not showing up, But when data has more than one item (uncomment second one in fiddle) then showing tooltip.

Is there any other configuration to allow tooltip in single item ?

**Comment by xile611** [comment]
@Nishchit14 Thanks! It's a bug.We'll fix it as soon as possible.

**Comment by xile611** [comment]
Fixed in version 0.11.0
