### ISSUE TITLE
Apply bar background on selected data points based on condition

### ISSUE THREAD

**Issue by waqidvolli** [recharts/recharts#1171]
## Do you want to request a feature or report a bug?
Feature request/bug

## What is the current behavior?
When you apply background to <Bar>, it applies the background to all bars.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
http://jsfiddle.net/o6qc5pw7/

## What is the expected behavior?
As mentioned in docs, the background can be assigned a function. But this function does not receive the current data point and hence there is no way to assign background for a specific data point (bar) based on condition.
 
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.0.0-beta.9

**Comment by alexgurr** [comment]
Samee problem here...

**Comment by maximgeerinck** [comment]
I think you could use something like this?

```
const colors = [ "green", "red", "blue", "black", "gray", "white"];
<Bar
          dataKey='ac'
        >{
          data.map((entry, index) => (
            <Cell key={`cell-${index}`} fill={colors[index]}}/>
          ))
        }</Bar>
```

**Comment by alexgurr** [comment]
That's what I ended up doing. Seems like a bit of a messy solution to achieve something simple though.
