### ISSUE TITLE
Improving rendering speed of scatter graph

### ISSUE THREAD

**Issue by iamanoopmk** [recharts/recharts#1172]
## Do you want to request a feature or report a bug?
I am not sure if I can call it a feature request. I need some helo

## What is the current behavior?
I am trying to load moderately large data into a scatter graph. I want to compare two variables and each one has about 4000 data point. In total, the graph will be showing roughly 8000 data points. The graph takes a long time to load (about 8 seconds) and the scroll becomes choppy

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
here is the link to jsfiddle [http://jsfiddle.net/iamanoopmk/1med34hu/1/](http://jsfiddle.net/iamanoopmk/1med34hu/1/)

## What is the expected behavior?
Expected to increase the rendering speed. I want to increase the data set in the future. But if it takes even more time to load then the user experience will not be very good. Is there anything I can do to increase the rendering speed and make the page a bit lighter. Currently scrolling also feel a bit heavier.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts version is 1.0.0-beta.10, I have tested on both chrome and firefox(quantum) on ubuntu OS. I have tried on version 1.0.0-beta.5 and it was the same.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
