### ISSUE TITLE
Legend shows no markers for Area without stroke

### ISSUE THREAD

**Issue by Philipp91** [recharts/recharts#1174]
I have an `AreaChart` where my `Area`s only have a `fill` but no `stroke` color. Because of this code: https://github.com/recharts/recharts/blob/b48b6d6c912e354a918d2b6307f5c8c6ada210df/src/util/ChartUtils.js#L132 all my legend elements end up with `"none"` as their color and hence aren't visible at all (except the text).

Would a fallback to the `fill` color make sense?

**Comment by MasroorHamdani** [comment]
I am facing same issue for LineChart, Where I need to display only dots. The legend ends up just showing the names and no color, as stroke in set to false.

@Philipp91 did you got any solution for it yet?

**Comment by Philipp91** [comment]
No solution. But it's not that much of a problem for me. The text still has the respective color and can be clicked, just the dot/rect next to the text is invisible and sort of acts as a spacer.

**Comment by MasroorHamdani** [comment]
Yeah, looks like I can do the same till we get the solution and change text color itself.

**Comment by jvsonica** [comment]
I ran into this issue and got around it by adding a `stroke` with the desired color and setting `strokeWidth` to `0`, for example:

```javascript
<Area dataKey="myKey" fill="blue" stroke="blue" strokeWidth={0} legendType="circle" />
``` 
The stroke still isn't visible, but my legend elements now display properly.
