### ISSUE TITLE
Add info about chart data to documentation

### ISSUE THREAD

**Issue by AlexGrafe** [recharts/recharts#1175]
## Do you want to request a feature or report a bug?
feature

## What is the current behavior?
No info on the chart's data.

## What is the expected behavior?

Please add more info on the chart data and how to compile it.
Especially it's unclear to me what the `amt` parameter is.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

newest

**Comment by hueitan** [comment]
the document page repo sits here https://github.com/recharts/recharts.org
