### ISSUE TITLE
In Area chart area is overlapping and overlapping color is showing

### ISSUE THREAD

**Issue by kmahawar** [recharts/recharts#1176]
Bug

In Area chart for particular data area overlapping

Please find fiddle link
http://jsfiddle.net/2j1hpc4a/79/

## What is the expected behavior?
Area should not overlap..

versions of Recharts = recharts@1.0.0-beta.10
browser  = chrome
OS = Windows
previous versions of Recharts = Not know

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
