### ISSUE TITLE
Hide dots on scatter

### ISSUE THREAD

**Issue by levininja** [recharts/recharts#1177]
## Do you want to request a feature or report a bug?
Request a feature (or for someone to tell me how to do this if it's actually already possible)

## What is the current behavior?
It seems that Scatters do not have an option to not display the dots (or whatever symbol, crosses, wyes, etc).  With the Line component you can pass in `dot={false}` but there is no such option with a Scatter.

This is especially useful in a chart that mixes lines and dots.  I don't want the lines to also display dots as the chart gets too cluttered.

## What is the expected behavior?
Could we have a `dot` property for Scatter that works the same way as Line's dot prop?

Even better, if there was a way to specify the size (or 'stroke') of the dots that would be even better.

**Comment by levininja** [comment]
In case anyone else is searching for how to do this, I figured out, by passing a react element that returns null into the prop `shape`, that's a way you can achieve having no dots.

`<Scatter name={model.name} data={model.data} fill={fillColor} dot={ dotStyle }  line shape={<noShape />}   />

//and elsewhere
const noShape = (props)=>{
    return null;
}
`

**Comment by yahengqi** [comment]
If hiding does not have tooltip effect

**Comment by eatyourpeas** [comment]
I know this is closed by I have another work around which I stumbled on and may be useful to others:
`<ZAxis range={[5, 5]} dataKey='label' unit='cm' />
<Scatter
            name={result.name}
            data={result.data}
            line={{
              stroke: this.props.yourLineColour,
              strokeWidth: 1,
              strokeDasharray: '5 10'
            }}
            fill='#00000000'
          />
` 
The effect of this is to have a reasonable large scatter dot (zAxis range) which will then pick up a tool tip, but by setting the alpha to 0 in effect hides the dots so the line can be seen.

**Comment by JakeG-9191** [comment]
> I know this is closed but I have another work around which I stumbled on and may be useful to others:
> `<ZAxis range={[5, 5]} dataKey='label' unit='cm' /> <Scatter name={result.name} data={result.data} line={{ stroke: this.props.yourLineColour, strokeWidth: 1, strokeDasharray: '5 10' }} fill='#00000000' /> `
> The effect of this is to have a reasonable large scatter dot (zAxis range) which will then pick up a tool tip, but by setting the fill colour alpha to 0, in effect the dots are hidden so the line can be seen.

This worked like a charm, I needed to hide the tooltip until hovering directly over data and even though I wanted a line chart, the scatter chart was the only option to resolve the tooltip issue, by removing the stroke dash array the line works well
