### ISSUE TITLE
wrong tooltip label if I don't use x-axis

### ISSUE THREAD

**Issue by mayacode** [recharts/recharts#1178]
## Do you want to request a feature or report a bug?

bug

## What is the current behavior?

If I don't use x-axis with defined data source tooltip displays wrong label

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

http://jsfiddle.net/ndLhnegs/709/

## What is the expected behavior?

I would like to have an option to define data source for tooltip label, even if x-axis is not in use

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

newest version (`"recharts": "^1.0.0-beta.10",`), I didn't work with previous versions of recharts

**Comment by brianjp93** [comment]
I was able to fix this by adding the XAxis, but then hiding it.

```jsx
<XAxis hide={true} dataKey='name' />
```

**Comment by Luisetelo** [comment]
Hi people,

I would like to have different labels in the tooltip and in the X Axis and due to this bug, I need to do a "hack".  Any progress on this?  I would like to help :)

This is still happening on `2.0.0-beta.2`
