### ISSUE TITLE
Recharts + Ant Design Responsive Container Issue

### ISSUE THREAD

**Issue by DeadcatDev** [recharts/recharts#1180]
Im using clear Ant Design Layout (example from their site) + newest recharts (nothing more).

## Do you want to request a feature or report a bug?
Bug.

## What is the current behavior?
Current behaviour is：
https://youtu.be/xNC6S3Ir-aE.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
Not suitaible, code:
```
<ResponsiveContainer debounce={200} width="100%" height={400}>
        <BarChart data={this.props.dataSet}>
          <CartesianGrid strokeDasharray="3 3"/>
          <XAxis dataKey="name"/>
          <YAxis/>
          <Tooltip/>
          <Legend/>
          <Bar isAnimationActive={true}
               animationBegin={100}
               animationDuration={1500}
               animationEasing="ease-in"
               dataKey="pv" fill="#8884d8"/>
          <Bar isAnimationActive={true}
               animationBegin={100}
               animationDuration={1500}
               animationEasing="ease-in"
               dataKey="uv" fill="#82ca9d"/>
    </BarChart>
</ResponsiveContainer>
```

## What is the expected behavior?
This one (code below), used fixed 800px:
https://youtu.be/V2tv9Sma6uM

```
<ResponsiveContainer debounce={200} width={800} height={400}>
[... same]
```

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Newest, Win10, Chrome (newest), don't know does it works.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
