### ISSUE TITLE
Radar Chart - Y axis label should have a white background (Recharts)

### ISSUE THREAD

**Issue by bhagtana** [recharts/recharts#1182]
![freeform design](https://user-images.githubusercontent.com/12777744/35992749-0962b258-0cc0-11e8-9bbc-b19b9fd11270.png)

## Do you want to request a feature or report a bug?
A feature

## What is the current behavior?
The Y axis labels are hard to make out against the lines and grid lines of the chart.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
http://jsfiddle.net/b97cn1do/1/

## What is the expected behavior?
The should be a way to white out behind the Y axis labels so they are easier to see. 

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Its not possible on any version or any browser yet.

**Comment by xile611** [comment]
You can use [`tick` of PolarRadiusAxis ](http://recharts.org/en-US/api/PolarRadiusAxis#tick) to render customized tick.
