### ISSUE TITLE
[Feature] Reference Line for y = ax + b

### ISSUE THREAD

**Issue by dsbrutha777** [recharts/recharts#1185]
## Do you want to request a feature or report a bug?

Feature

## What is the current behavior?

It can only draw vertical and horizontal reference lines now.

## What is the expected behavior?

When I need to draw a oblique straight line, like y = ax + b

***

maybe or there are other ways to complete this feature. 

Thanks.

**Comment by paulmelnikow** [comment]
This was implemented in #1380.

**Comment by xile611** [comment]
Thanks for your suggestion, we have added this feature to the plan of 2.0
