### ISSUE TITLE
[Feature] onMouseUp prop for Brush

### ISSUE THREAD

**Issue by justduy** [recharts/recharts#1186]
As of now, only onChange is possible with Brush. In my use case it would be preferable to have the brush call a function on mouse up, so that it doesn't set the variables for every change.

**Comment by mdizzy** [comment]
I ran into this problem because I wanted to get the brush position and use it to make changes to other components. I bound the startIndex and endIndex to my component state. I made this workaround that uses a delay to update the state.

https://jsfiddle.net/incipire/0uoygda5/

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
