### ISSUE TITLE
Brush Error: Cannot read property 'range' of undefined

### ISSUE THREAD

**Issue by ZephD** [recharts/recharts#1187]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?

> Uncaught TypeError: Cannot read property 'range' of undefined
>    at Brush.componentWillReceiveProps (Brush.js:120)
>    at callComponentWillReceiveProps (react-dom.development.js:6389)
>    at updateClassInstance (react-dom.development.js:6575)
>    at updateClassComponent (react-dom.development.js:7848)
>    at beginWork (react-dom.development.js:8225)
>    at performUnitOfWork (react-dom.development.js:10224)
>    at workLoop (react-dom.development.js:10288)
>    at HTMLUnknownElement.callCallback (react-dom.development.js:542)
>    at Object.invokeGuardedCallbackDev (react-dom.development.js:581)
>    at invokeGuardedCallback (react-dom.development.js:438)

https://github.com/recharts/recharts/blob/e0fa3779cfc2e136468df58c2d30e02c5a88316c/src/cartesian/Brush.js#L85

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
To reproduce, load a blank (data={[]}) graph with a Brush, and resize the window.

## What is the expected behavior?
No error

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.0.0-beta.10

**Comment by ZephD** [comment]
Example: https://codesandbox.io/s/yp1729xkkv
Just resize the preview window's width.

**Comment by nukc** [comment]
Mybe you can:
```js
const SampleChart = props => {
  return (
    <ResponsiveContainer aspect={1.6}>
      <LineChart data={this.state.data}>
        {this.state.data.length > 0 && <Brush />}
      </LineChart>
    </ResponsiveContainer>
  );
};
```

**Comment by ZephD** [comment]
Nice workaround. Obviously not a solution (the bug still needs fixing), but thanks.

**Comment by NataliiaDieieva** [comment]
Any updates?
Have the same issue.
Brush works well until you try to resize the browser window

**Comment by avindra** [comment]
Still in issue in v2 beta

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by avindra** [comment]
Reopened as Issue #2093
