### ISSUE TITLE
A tooltip Per bar withing the same group

### ISSUE THREAD

**Issue by Abouyer20** [recharts/recharts#1188]
I need to have a tooltip per bar which are withing the same bar
My data looks like this
` [
0 : {rangeLabel: 0-18, a_0: 10 a_1: 20, b_0: 0 b_1: 5, c_0: 14 c_1: 20, d_0: 45 d_1: 0},
1 : {rangeLabel: 18-36, a_0: 45 a_1: 0, b_0: 45 b_1: 3, d_0: 45 d_1: 75},
2 : {rangeLabel: 36-54, b_0: 0 b_1: 5, c_0: 35 c_1: 20, d_0: 75 d_1: 3}
] `

What the graph looks like

![image](https://user-images.githubusercontent.com/15029952/36032182-1cd1d3a6-0da5-11e8-9d0f-7700edafa83e.png)

What my code looks like;

           <BarChart data={barChartData} margin={{top: 5, right: 20, left: 20, bottom: 20}}>
              <pattern id="pattern-stripe"  
                             width="4" height="8" 
                             patternUnits="userSpaceOnUse" 
                             patternTransform="rotate(45)">
                <rect width="3" height="8" transform="translate(0,0)" fill="white"></rect>
              </pattern>
              <mask id="mask-stripe">
                <rect x="0" y="0" width="100%" height="100%" fill="url(#pattern-stripe)"/>
              </mask>

              <XAxis dataKey="rangeLabel">
                <Label value="Price range/Retailer" offset={-15} position="insideBottom"/>
              </XAxis>
              <YAxis label={{ value: 'Products', angle: -90, position: 'insideLeft' }}/>

              <CartesianGrid strokeDasharray="3 3"/>
              { retailers.map((retailer, index) => {
                return <Bar key={`p-${index}`}
                            dataKey={`${retailer}_p`}
                            name={`${retailer} Promo`}
                            shape={<CandyBar fill={this.retailerColor(retailer)} />}
                            stackId={retailer}>
                </Bar>
              })}
              { retailers.map((retailer, index) => {
                return <Bar key={`np-${index}`}
                            dataKey={`${retailer}_np`}
                            name={`${retailer} No Promo`}
                            fill={this.retailerColor(retailer)}
                            stackId={retailer}>
                </Bar>
              })}
              </BarChart>
` 

So what I need is to be able to have a tooltip per bar, 
Would anyone know how to do this?
Thanks in advance

**Comment by xile611** [comment]
Sorry, not supported yet. It's recommended to use customized `content` of `Tooltip` to cover default tooltip.

**Comment by Glenncito** [comment]
@xile611 is there anything wrong with using the approach suggested in [this StackOverflow post](https://stackoverflow.com/questions/55301556/recharts-tooltip-for-each-bar-in-a-bar-chart-composed-of-three-bars)?
