### ISSUE TITLE
Intelligent X-axis label text resize

### ISSUE THREAD

**Issue by darky** [recharts/recharts#1190]
## Do you want to request a feature or report a bug?
feature

## What is the current behavior?
Now label simply hide, if it can't to fit.
Also can force to show it, via `interval={0}`, but it looks awful.

## What is the expected behavior?
Would be cool to use `<title>Very very long label</title>` inside `<text />` svg element and collapse text appearance like `<tspan>Very ver...</tspan>`

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
