### ISSUE TITLE
XAxis label wrap text in a simple bar chart

### ISSUE THREAD

**Issue by sapnalakhi** [recharts/recharts#1192]
Am new to Recharts and working on using a simple bar chart and the text label is pretty long for the Xaxis, due to which not all the content is displayed. Is there a way to word wrap the text . There is a text component but its not very clear on how to use it. 

Code:
import React from 'react';
import {BarChart, Bar, XAxis, YAxis, Cell, CartesianGrid, Tooltip, Legend, Text, Label} from 'recharts';
const data = [
      {type: 'Funneled Bag',  count: 120},
      {type: 'Prioritized Backlog',  count: 210},
      {type: 'Committed Backlog', count: 42},
      {type: 'Enterprise Asset',  count: 176}   
];
const COLORS = ['#0088FE', '#00C49F', '#FFBB28', '#FF8042'];
class SimpleBarChart extends React.Component{
	render () {
  	return (
    	<BarChart width={600} height={400} data={data} 
            margin={{top: 5, right: 35, left: 20, bottom: 5}}>
       <XAxis width={30} dataKey="type" >
       <Label value="Data Catalog" offset={0} position="bottom" />
       <Text  style={{fontSize:2}} width={30} textAnchor="start" scaleToFit={true} />
       </XAxis>
       <YAxis/>
       <CartesianGrid strokeDasharray="3 3"/>
       <Tooltip/>
       <Legend />
       <Bar barSize={30} dataKey="count">
       		{
          	data.map((entry, index) => {
            	const color = COLORS[index];
            	return <Cell fill={color} />;
            })
          }
          </Bar>
      </BarChart>
    );
  }
}
  export default SimpleBarChart;

Output:
![image](https://user-images.githubusercontent.com/8292414/36082762-5c5c8f32-0fd2-11e8-9c07-f0f863e3af3c.png)

Also i dont want the count to be displayed below the chart.

Appreciate your help!

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue guide.
