### ISSUE TITLE
Tooltip's labelFormatter does not respect newline characters

### ISSUE THREAD

**Issue by ZephD** [recharts/recharts#1193]
## Do you want to request a feature or report a bug?
Feature

## What is the current behavior?
`firstline\nsecondline`
displays as 
"firstline secondline"

## What is the expected behavior?
`firstline\nsecondline`
displays as
"firstline
secondline"

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
All

**Comment by christiancho** [comment]
This can already be achieved:

```
<Tooltip
  labelFormatter={() => <div>firstline<br />secondline</div>}
/>
```

**Comment by ZephD** [comment]
Great. Thanks!
The suggestion to allow newline chars still stands though :)

**Comment by ZephD** [comment]
Hmm. I'll leave that up to the authors then.
I did notice that the label is wrapped in a `<p>`, and I got an error using your code as `<div>` is not allowed inside `<p>`.
I changed it to `<span>` to fix.
