### ISSUE TITLE
Spacing between ticks are uneven

### ISSUE THREAD

**Issue by oskarer** [recharts/recharts#1194]
## Do you want to request a feature or report a bug?
Possible bug
## What is the current behavior?
Spacing between ticks are uneven
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
Distance between K and N ticks is bigger than the other ticks.
http://jsfiddle.net/rsdm1hxz/
## What is the expected behavior?
Even spacing between ticks

**Comment by christiancho** [comment]
This is not a bug. The ticks are rendered so that they don't overlap, obscuring the labels. Try increasing the width of the chart and more will fit. Developers can get around this by using the `ticks` and/or `ticksFormatter` props of `XAxis`.
