### ISSUE TITLE
adding content in Dot

### ISSUE THREAD

**Issue by AakashFG** [recharts/recharts#1197]
I want to add graph content on the dot, like in the pic below, but I am not able to find a solution. 

![screen shot 2018-02-13 at 5 26 39 pm](https://user-images.githubusercontent.com/31609187/36150632-4ae079f8-10ea-11e8-8141-48936c68e303.png)

I tried seeing the ActiveDot and Dot property in Area Component, but did not find any feature to add content. 

Please tell me if I am missing something.

My present code is : -

                `<ResponsiveContainer width="100%" height={400}>
                     <AreaChart data={data} margin={{ top: 10, right: 30, left: 0, bottom: 0 }}>
		          <defs>
		            <linearGradient id="colorUv" x1="0" y1="0" x2="0" y2="1">
			         <stop offset="5%" stopColor="#e9feec" stopOpacity={0.8} />
							<stop offset="95%" stopColor="#e9feec" stopOpacity={0} />
						</linearGradient>
						<linearGradient id="colorPv" x1="0" y1="0" x2="0" y2="1">
							<stop offset="5%" stopColor="#e9feec" stopOpacity={0.8} />
							<stop offset="95%" stopColor="#e9feec" stopOpacity={0} />
						</linearGradient>
					</defs>
					<XAxis dataKey="name" />
					<YAxis />
					<Tooltip content={<CustomTooltip />} />
					<Area type='monotone' dataKey='uv' fillOpacity={1} stroke='#3f51b5' fill='url(#colorUv)' activeDot={{r: 8}} />
					<Area type='monotone' dataKey='pv' fillOpacity={1} stroke='#4bc04e' fill='url(#colorPv)' activeDot={{r: 8}} />
				</AreaChart>
			</ResponsiveContainer>`

**Comment by huei-tan-sociomantic** [comment]
I don't think the current version supports circle with text.

**Comment by huei-tan-sociomantic** [comment]
You can customize [the area dot](http://recharts.org/en-US/api/Area#dot) with React component that draws the svg circle with text

**Comment by chrisLoPresti** [comment]
would love to know how you made your tooltip look like that! 

and for the dot you can do a custom dot, with a custom SVG that takes a label and give the label your value
