### ISSUE TITLE
Consistent height between charts with and without legend.

### ISSUE THREAD

**Issue by mrozbarry** [recharts/recharts#1198]
## Do you want to request a feature or report a bug?

Might be a bug or a feature, depending on your perspective

## What is the current behavior?

I'm using a grid layout, and have two graphs side by side. They both have the same height and width set, and are wrapped in a ResponsiveContainer. One of the graphs has a legend, while the other does not. Now the graph with the legend is technically shorter than the graph without the legend.

## What is the expected behavior?

I don't know if this is expected, but I'd like the two graphs to consistently remain the same height, and just have the ResponsiveContainer grow vertically to fit in the legend.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Currently tested on Chome, and Recharts 1.0.0-beta.6 and 1.0.0-beta.10 with the same result

**Comment by ZephD** [comment]
The ResponsiveContainer fits its container.
What you're asking for is for the legend to go OUTSIDE the container, therefore going into another grid's cell.

The behaviour you are seeing is expected. You may want to add padding to your non-legend graph to make it match in size the other one.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
