### ISSUE TITLE
Horizon charts

### ISSUE THREAD

**Issue by sankho** [recharts/recharts#120]
Using this library for work @ NS1.com. In the past we've used Horizon charts (see http://www.perceptualedge.com/articles/visual_business_intelligence/time_on_the_horizon.pdf) for certain sets of data where there are large spikes which obfuscate changes that are not of the same delta across the given data set (think of a line chart where there's one data point at 10000, but most other changes are in the 10's, and how the visual appearance for the lower changes are sometimes incorrectly seen as subtle).

There are some D3 applications of horizon charts out there (see http://bl.ocks.org/mbostock/1483226).

I'd love to take on the coding work, add animations + tooltip formatting in the manner to which other chart types behave, and submit a PR but wanted to see if
1.) That's cool re: contribution guidelines and
2.) If horizon charts are even of interest

LMK and I'll get on it!

**Comment by xile611** [comment]
@sankho Thank you for your sharing, horizon chart is very interesting. PR is welcome. We don't have guidelines for contribution yet. The most basic is that you should run `npm run lint ` and `npm run test` when you finish a chart.

**Comment by xile611** [comment]
Closed temporarily. Looking forward for your pr.
