### ISSUE TITLE
Smaller Cartesian Grid

### ISSUE THREAD

**Issue by lotusms** [recharts/recharts#1200]
Is there an option to draw a denser cartesian grid? (smaller grid). The way it is drawn right now it creates a vertical line per line of data. And I am not really sure how it defines how many horizontal lines or how it defines which values to render in the YAxis for the horizontal line to draw.

Essentially I want it to draw a grid regardless of what it is being drawn. A small grid. Is this possible with an available option or different grid component?

Thanks

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by gaurav5430** [comment]
I think the cartesian grid is bound to the ticks as they appear on the axis
