### ISSUE TITLE
How to set number of horizontal lines of cartesiangrid?

### ISSUE THREAD

**Issue by crazydev71** [recharts/recharts#1202]
As decribed in title, I want to set the number of horizontal lines of cartesiangrid.
Currently it shows up 5 lines by default, and I want to show 3 lines.
Thanks in advance

![image](https://user-images.githubusercontent.com/20955573/36427026-b23d10c2-1697-11e8-8ad3-244da7a3f1b4.png)

**Comment by lotusms** [comment]
I'm having a similar issue reported as well.

**Comment by lotusms** [comment]
Related to #1200

**Comment by yezhi780625** [comment]
`<YAxis tickCount={3} />`.

**Comment by binarygrrl** [comment]
horizontalPoints={[80, 140, 200]}
Change the points to be the x value of where you want the lines to appear (relative to the size of your chart)

**Comment by TiagoPortfolio** [comment]
> `<YAxis tickCount={3} />`.

Is this deprecated? At least I didn't find it at http://recharts.org/en-US/api/YAxis

**Comment by gaurav5430** [comment]
@yezhi780625  I don't think it can be directly controlled using <YAxis tickCount={...} /> , except for the basic/default case, in case scale="linear" and domain={['dataMin', 'dataMax']} this would break, as observed here: https://github.com/recharts/recharts/issues/2153

@binarygrrl 's solution would work, but in that case, If i want to show the lines for all yAxis ticks, except the first and the last, I have to now somehow calculate where recharts would show the y axis ticks, unless I am already calculating them manually.

**Comment by makhloufi-lounis** [comment]
<YAxis
          allowDecimals={false}
          axisLine={false}
          domain={[1, 3]}
          tickLine={false}
          tickMargin={10}
          ticks={[1, 2, 3]}
          type="number"
        />
it's works for me

**Comment by TiagoPortfolio** [comment]
> `<YAxis allowDecimals={false} axisLine={false} domain={[1, 3]} tickLine={false} tickMargin={10} ticks={[1, 2, 3]} type="number" />` it's works for me

It works for your use case but not for any domain.
You have hardcoded tick values to display 3 lines for your domain.
