### ISSUE TITLE
Testing attribute value does reflect actual attribute

### ISSUE THREAD

**Issue by aaronang** [recharts/recharts#1204]
## Do you want to request a feature or report a bug?

🐛 Bug

## What is the current behavior?

When I add the following test to `test/specs/components/LabelSpec.js`, as shown below, it will fail.

```js
it('Render overridden presentation attributes (postion="insideLeft")', () => {
  const wrapper = render(
    <Surface>
      <Label viewBox={cartesianViewBox} value="text" postion="insideLeft" />
    </Surface>
  );
  const label = wrapper.find('.recharts-label');
  expect(label.attr('text-anchor')).to.equal('start');
});
```

The error message:

```
AssertionError: expected 'middle' to equal 'start'
    at Context.<anonymous> (webpack:///test/specs/component/LabelSpec.js:112:41 <- test/index.js:243411:53)
```

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

1. Add the test to `test/specs/components/LabelSpec.js`
2. `npm run test`

## What is the expected behavior?

The test should pass because:

1. Spreads `positionAttrs` as properties for `<Text />`, see [L313](https://github.com/recharts/recharts/blob/master/src/component/Label.js#L313).
2. `positionAttsr` is determined in [L144](https://github.com/recharts/recharts/blob/master/src/component/Label.js#L144).
3. Since we defined `position="insideLeft"`, the `text-anchor` is assigned the `start` value, see [L185](https://github.com/recharts/recharts/blob/master/src/component/Label.js#L185).
4. Test should pass because we just showed that `text-anchor` should equal `start`.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

https://github.com/recharts/recharts/commit/b48b6d6c912e354a918d2b6307f5c8c6ada210df

## Comments

I am really curious why this test does not pass.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
