### ISSUE TITLE
Last XAxis label not aligned with tick mark when rotated -45 degrees.

### ISSUE THREAD

**Issue by smock** [recharts/recharts#1206]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
When rotate -45 degrees, the last XAxis label is offset from the tick mark it represents.
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
![image](https://user-images.githubusercontent.com/75959/36683432-9025d804-1aeb-11e8-86d5-ba8489fb17b2.png)
My XAxis code is as follows:
```
                    <XAxis height={100} dataKey="date" angle={-45} textAnchor="end" />
```
## What is the expected behavior?
I'd expect the label to be aligned with the tick mark it represents.
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
I'm using 1.0.0-beta.1.

**Comment by fktrctqnjrfhtd** [comment]
Same with 1.3.4

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.

**Comment by rbhalla** [comment]
This is still an issue in 1.8.5

**Comment by GuillaumeDesforges** [comment]
Works for me in 1.8.19

```
<XAxis
  dataKey="x"
  angle={-45}
  textAnchor="end"
/>
```
