### ISSUE TITLE
Log Scale not working in 1.0.0-beta.10

### ISSUE THREAD

**Issue by davodesign84** [recharts/recharts#1208]
## Do you want to request a feature or report a bug?
Bug Report
## What is the current behavior?
No data is displayed when scale="log" prop is passed on the Axis
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

https://codesandbox.io/s/9z8172zv9w

## What is the expected behavior?
Data should be displayed using a log scale

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
V: 1.0.0-beta.10
OS: Mac OSX
Browser: verified on Chrome / Safari

**Comment by mr-devboy** [comment]
Try to use ` <YAxis scale="log" domain={['dataMin', 'dataMax']} allowDataOverflow />`
