### ISSUE TITLE
Click/drag on chart to "zoom" X-Axis

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#1209]
I don't think there is a way to currently do this, but a common thing that many charting packages support is the ability to zoom in the X-axis by clicking and dragging a portion of the chart (and then typically an icon appears on the chart to reset the zoom to it's maximum). I realize that the brush is an alternative to this, but I think it would be a nice feature to integrate into the chart itself.

**Comment by iamanoopmk** [comment]
Looking for this too. Would be really nice to have this

**Comment by davekeehn** [comment]
+1

**Comment by vamsi0212** [comment]
+1

**Comment by dmitryvmin** [comment]
+1

**Comment by jtiagodev** [comment]
+1

**Comment by ITXpander** [comment]
Did you all consider this example? http://recharts.org/en-US/examples/HighlightAndZoomLineChart

**Comment by Eric24** [comment]
@ITXpander - Nope, but that's what I was looking for. Thanks for pointing it out!

**Comment by chey22** [comment]
How would you go about a highlight and zoom giving more detail in the x axis? Like if it were date values, could the x axis change to hourly ticks if you zoom in on just one day? Or with number values, could they show decimals when you zoom in?
