### ISSUE TITLE
How to display Negative values on LineBarAreaComposedChart

### ISSUE THREAD

**Issue by GambinoRacing** [recharts/recharts#1211]
I try to display a negative values on <Line> but the result is null. (Negative Tempetures)

I also have positive values in the range of 1 to 5 and their line is also not visualized. (WindSpeed)

This is screen of my chart.

![xmk9i](https://user-images.githubusercontent.com/20344707/36889230-d6b9fd7c-1e01-11e8-85a1-d20a9dbec3d9.png)

`<div className="col-md-12">
            <ComposedChart width={1100} height={700} data={this.state.data} stackOffset="expand">
              <XAxis dataKey="Date" interval={3}/>
              <YAxis />
              <Tooltip />
              <Legend />
              <CartesianGrid strokeDasharray="3 3" />
              <Area type='monotone' dataKey='Apress' fill='#726a64' stroke='#726a64' />
              <Bar dataKey='Rain' barSize={20} fill='#000cff'>
                <LabelList dataKey="Rain" position="top" />
              </Bar>
              <Bar dataKey='Snow' barSize={20} fill='#6387ff'>
                <LabelList dataKey="Snow" position="top" />
              </Bar>
              <Line type='monotone' dataKey='Temp' stroke='#ff0000' />
              <Line type='monotone' dataKey='WindSpeed' stroke='#00ff1a' />
            </ComposedChart>
          </div>
        </div>`

**Comment by jindrichkuba** [comment]
Fox XAxis put there allowDataOverflow
