### ISSUE TITLE
TimeSeries LineChart renders poorly

### ISSUE THREAD

**Issue by kennetpostigo** [recharts/recharts#1212]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
Chart renders with barely any curves almost like a straight line
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
The code is:
```js
<LineChart
  width={410}
  height={200}
  data={this.props.series}
  margin={{ top: 10, right: 30, left: 0, bottom: 0 }}
>
  <Line
    typ="monotone"
    dataKey="mid"
    xAxisId="ts"
    yAxisId="mid"
    strokeWidth={3}
    stroke="#fff"
    connectNulls={false}
    dot={false}
    fill="#fff"
  />
</LineChart>
```
The data shape is `[{mid: int, ts: int}]` It is a time series chart, but the values for mid can differentiate from a few tenths of a whole number to a few whole numbers. the values for ts are unix timestamp integers. The chart renders almost like a straight line with very little curvature:
<img width="475" alt="screen shot 2018-03-02 at 10 09 48 pm" src="https://user-images.githubusercontent.com/8888991/36929970-77fda62a-1e66-11e8-8166-ee0220e516bf.png">

## What is the expected behavior?
It should scale the line to show more depth of the curvature of the line for points.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
I'm using `recharts: ^1.0.0-beta.10`

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
