### ISSUE TITLE
## Legend is not picking the margin property??

### ISSUE THREAD

**Issue by PandiyanSS** [recharts/recharts#1213]

**Comment by breadadams** [comment]
Here's a jsfiddle example: https://jsfiddle.net/4fjas9yr/1/

**Comment by scotthovestadt** [comment]
I can reproduce this, even with the JSFiddle. The `<Legend />` does not react to the `marin` property at all, regardless of `verticalAlign`, `align`, or even without both.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
