### ISSUE TITLE
PieCharts labels not drawn when activeIndex prop changes before end of animation

### ISSUE THREAD

**Issue by romgrk** [recharts/recharts#1215]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
PieCharts labels not drawn when activeIndex prop changes before end of animation

- Goto [http://jsfiddle.net/romgrk/rsxkwamw/](http://jsfiddle.net/romgrk/rsxkwamw/)
- Mouse over the pie before the end of the animation

**What is the expected behavior?**
Labels are drawn

**Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?**
`1.0.0-apha.5`

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
