### ISSUE TITLE
Dynamic height in the container (div)

### ISSUE THREAD

**Issue by xnog** [recharts/recharts#1218]
Is it possible to set dynamic height in the container? 

If a just put the ResponsiveContainer, the chart doesn't appear. I have to put a div outside with the 'height' set. Is it possible to change this 'height' based in some rule, dynamically?

Thanks

**Comment by xile611** [comment]
@xnog `ResponsiveContainer` will calculate the height of its parent node, so you just need to make sure its parent node has right height, otherwise  `ResponsiveContainer` can't calculate right height.

**Comment by sKopheK** [comment]
can't it be the other way around - i need container to take as much space as the graph and its legend need
