### ISSUE TITLE
Unable to View all X-axis values

### ISSUE THREAD

**Issue by dbMundada** [recharts/recharts#1219]
## What is the expected behavior?
<a href="https://ibb.co/jkeDsn"><img src="https://preview.ibb.co/bH7Nk7/Screenshot_from_2018_03_11_13_25_05.png" alt="Screenshot_from_2018_03_11_13_25_05" border="0"></a>

### Version: "recharts": "^1.0.0-beta.10", I am using this library first time

**Comment by xile611** [comment]
@dbMundada  

You can set `interval` of `XAxis` to be `0` which has default value `preserveEnd`(Chech [doc of XAxis](http://recharts.org/#/en-US/api/XAxis) for detail) to force all the ticks to be shown.
 Meanwhile you may need to set the `angle` of <XAxis /> to rotate the ticks.
