### ISSUE TITLE
Putting Label on top of YAxis

### ISSUE THREAD

**Issue by mpodlasin** [recharts/recharts#1224]
Hi.

I want to put label exactly on top of YAxis. I was under the impression that `position="top"` will do the job:

```jsx
<YAxis>
   <Label value="°C" position="top" />
</YAxis>
```

Docs clearly suggest that label will appear centered on top of its container:

![screenshot from 2018-03-13 16-58-24](https://user-images.githubusercontent.com/7916523/37353499-c2ebf4d0-26df-11e8-8476-a8f09453dbc2.png)

But results are not perfect:

![screenshot from 2018-03-13 16-56-45](https://user-images.githubusercontent.com/7916523/37353394-8d66c092-26df-11e8-84b7-dbdf895b6e30.png)

Is this a bug? If not, what am I doing wrong?

Cheers.

**Comment by xile611** [comment]
It's not a bug. Because YAxis has default width.

**Comment by FFJohandroG** [comment]
Try with "offset: 10"  to add something like "margin-bottom", and also with the margins of <ComposedChart/> This may help a little with the position.

Something like this: 
label={{ value: "Open Emails", angle: 0, position: "top", offset: 10 }}
