### ISSUE TITLE
One tick is not displayed

### ISSUE THREAD

**Issue by yantakus** [recharts/recharts#1225]
## Do you want to request a feature or report a bug?

Report a bug.

## What is the current behavior?

One of ticks is not being rendered (for Mar 3, 2018).

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

Here's the codesandbox live example: https://codesandbox.io/s/3qwkl3vnqq

## What is the expected behavior?

All the ticks should be rendered.

## Which versions of Recharts, and which browser / OS are affected by this issue?

Latest version of recharts, Chrome, Mac OS.

## Did this work in previous versions of Recharts?

I'm not sure, didn't use it before.

**Comment by yantakus** [comment]
Guys, any ideas on this issue? Would appreciate your input on this. I had another chance to investigate on it and it really seems to be a bug, not a misconfiguration or smth like this. Can you please have a look at the example and confirm or refute my conclusion?

**Comment by alexmortensenhq** [comment]
You can add interval={0} to the XAxis to fix this.
