### ISSUE TITLE
How to make a half doughnut chart?

### ISSUE THREAD

**Issue by ikteru** [recharts/recharts#1228]
I have a question: How can I make a "Half doughnut chart"?
I can't find anyway to make it, one way would be to change the startAngle and the endAngle of the Pie chart: 
{
startAngle: 180,
endAngle: 0
}

But you don't provide an endAngle property.
I tried to see if you already have a "half doughnut chart" pre-configured like you did with all the other (line, bar, pie, ... ) but apparently there is none!
I checked out your demos as well, none of them features a "half doughnut chart".

So, How can I make one?

**Comment by jeffeld** [comment]
This works for me:
`<RadialBarChart startAngle={180} endAngle={0} width={400} height={200} cx={200} cy={200} innerRadius={20} outerRadius={180} barSize={10} data={graphData}>
                <RadialBar minAngle={15} background clockWise={true} dataKey='value'/>
                <Tooltip/>
            </RadialBarChart>`
