### ISSUE TITLE
Feature request: Y Axis padding

### ISSUE THREAD

**Issue by troyblank** [recharts/recharts#123]
I am struggling to find a way to allow padding on the Y axis so that the top value is not coming close to the top of the graph itself. This is a stylistic thing that I believe should probably be best achieved while building the svg elements and can not be easily modified using css after the svg has rendered.

A good example of what I want to be able to control in recharts is [how c3 handles Y axis padding](http://c3js.org/samples/axes_y_padding.html).

Here is an image of what I am seeing is desirable to be able to control.

![paddingtop](https://cloud.githubusercontent.com/assets/996725/16247420/418978e6-37cf-11e6-9489-3693b8448d05.png)

**Comment by xile611** [comment]
@troyblank  It's a workaround to set the `domain` of `YAxis`yourself.
Here is a [example](http://jsfiddle.net/hqe9c1uk/1/).
And you can see the [api](http://recharts.org/api#YAxis) for detail.

And we'll discuss this feature. 

Do you think this feature is necessary after you know more about `domain`?

**Comment by troyblank** [comment]
@xile611  I saw `domain` and if I understand it correctly the problem I see is that is you can't really say `max + 20px` as `max` could be any number large or small. The designer in me loves how easy c3 allows you to just throw pixel values at it so my chart doesn't look so crammed and I don't have to worry about the data involved as it's merely a style issue.

So for example your example of `[0, max + 100]` works great for any data that is in the 100's .... but say you have data that could exit in the 100's in some cases but then exist in the 10,000's the next time the same chart is used. This means you would have to evaluate the data first and decide on what fraction of the total data gives you the best breathing room. `[0, max + (n * dataRange)]`

I see value in separating style from data in this case, but I appreciate the example it will definitely work to give the desired result.

**Comment by xile611** [comment]
@troyblank  
Thank you for your sharing! I misunderstood the `padding` of C3. It's really necessary for `XAxis` and `YAxis`.

**Comment by xile611** [comment]
Fixed in V0.12.0.

`XAxis` and `YAxis` can support domain like `['dataMin - 100', 'dataMax + 50'] `.

**Comment by troyblank** [comment]
You are awesome, thanks a lot!

**Comment by vtarelkin** [comment]
anyone who will be there searching how to add padding for time axis: 

change values to epoch
turn        
      ```
               // scale="time"
                            tickFormatter={tickFormatter}
                            allowDuplicatedCategory={false}
                            type="number"
                            domain={['auto', 'auto']}
```

**Comment by markhalonen** [comment]
For anyone searching for the c3 style, `YAxis` has `padding` attribute:
```javascript
                <YAxis label={{ value: 'FooBar'}} padding={{ top: 10, bottom: 10 }} />
```
