### ISSUE TITLE
No Line When All Values Zero

### ISSUE THREAD

**Issue by erayalakese** [recharts/recharts#1230]
## Do you want to request a feature or report a bug?
bug
## What is the current behavior?
There is no line
![image](https://user-images.githubusercontent.com/782514/37895960-6579481e-30eb-11e8-8f6e-31726f10f059.png)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
https://codepen.io/anon/pen/zWEjRN (line 22-23 is important)

## What is the expected behavior?
There should be a line on X-Axis

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
  "recharts": "^1.0.0-beta.9"

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
