### ISSUE TITLE
bad js fiddle bases

### ISSUE THREAD

**Issue by jamesjtong** [recharts/recharts#1232]
## Do you want to request a feature or report a bug?
Bug with all jsfiddles in documentation examples

## What is the current behavior?
http://jsfiddle.net/kca9npkg/117/
Getting the following error-Bad JSFiddle configuration, please fork the original React JSFiddle

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem 
1. go to http://jsfiddle.net/kca9npkg/117/
2. see error

## What is the expected behavior?
working fiddles

**Comment by Lelith** [comment]
Have the same issue with other JSFiddle Examples e.g. http://jsfiddle.net/Lg5myu33/

**Comment by jaylucas** [comment]
I have had this issue with ALL JSFiddle examples

**Comment by kevinahuber** [comment]
Here's a stop-gap: 
https://github.com/recharts/recharts/issues/1205#issuecomment-368023090
