### ISSUE TITLE
multiple rows in one chart?

### ISSUE THREAD

**Issue by lidaof** [recharts/recharts#1233]
## Do you want to request a feature or report a bug?
request a feature
## What is the expected behavior?
Say if I would like to represent 20 groups of bar chats for 4 different data serious, I would like to break the 20 bar group to 4 rows maybe? Thanks.

**Comment by gajus** [comment]
What is the reason you cannot simply have multiple Rechart components?

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
