### ISSUE TITLE
Linear gradient color setting doesn't work for stroke sometimes

### ISSUE THREAD

**Issue by sergeysolovev** [recharts/recharts#1234]
## Do you want to request a feature or report a bug?

Bug

## What is the current behavior?

The Area's stroke disappears when using the linear gradient approach for it's coloring. In my case I have a few areas and the problematic one has the biggest values among the others and they're constant.

Notice in this demo how the line disappears when I click the "Over Time" button

![2018-03-28 15 04 48](https://user-images.githubusercontent.com/5831301/38014134-2d8871ae-329a-11e8-8838-da2a3706c166.gif)

## What is the expected behavior?

The line should stay

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

recharts 1.0.0-beta.10
macOS 10.13.3
Chrome 65.0.3325.162, Chrome 67.0.3381.1, Safari 11.0.3

**Comment by sergeysolovev** [comment]
UPD: it reproduces only when the Y values are all the same. If I slightly change the first value it works as expected (notice the line is a bit bended on the onset)

![screenshot 2018-03-28 16 04 11](https://user-images.githubusercontent.com/5831301/38016644-3f13342e-32a2-11e8-9ad2-c70227df6e02.png)

**Comment by hotovshchikov** [comment]
I have the same problem, did you find the way to fix it?

**Comment by hotovshchikov** [comment]
@xile611 As for my issue https://github.com/recharts/recharts/issues/1583 here is the same problem.
Watch this sandbox please, https://codesandbox.io/s/31v83o4xp5 you will see gradient line, change value of pv: 1010 to pv: 1000, line become straight and disapear.

**Comment by francisbotero** [comment]
This seems to still be occurring

**Comment by Therises** [comment]
So, nobody's gonna even look into it. Good to know -_-

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by peterklingelhofer** [comment]
Here's another potential [workaround](https://stackoverflow.com/questions/72559003/how-to-show-data-with-no-variation-with-linear-gradient-using-rechart).

**Comment by ckifer** [comment]
Lots of related issues to this. This is an SVG spec and browser limitation rather than something recharts does specifically. 

https://stackoverflow.com/a/21639059
