### ISSUE TITLE
Question: Radar + Tooltip, how to show tooltip only at the dot, not along all axis?

### ISSUE THREAD

**Issue by andrevinsky** [recharts/recharts#1236]
Ref. #536 
Please suggest how to turn off the feat. requested in the referenced Issue. 
I would like to switch animations off completely. Dragging tooltip along the axis seems like an animation, too. And I want it switched off in favor of showing a static tooltip at the dot on that axis.

To illustrate, 
**Desired** (the tooltip at the dot, no matter where the pointer is in relation to the axis):
![image](https://user-images.githubusercontent.com/932990/38109283-5550182a-33a0-11e8-9109-fcca134db190.png)

**To Be Avoided** (the tooltip follows the pointer, appears anywhere along the axis):
![image](https://user-images.githubusercontent.com/932990/38109321-6fc10f16-33a0-11e8-956c-893d9013ac30.png)

I cannot seem to achieve it with a `position` property.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
