### ISSUE TITLE
ResponsiveContainer not resizing

### ISSUE THREAD

**Issue by LeinadDC** [recharts/recharts#1238]
Hey guys,

I'm currently building an app for a NGO and i'm using Recharts. So far it looks great however when I try to go into responsive mode the charts won't resize.

Code I'm using:

Where it is rendered: 

`              <div className="row">

                    <div className=" col-md-6 col-sm-12 col-xs-12">

                           <Chart />

                    </div>

                </div>
`

And the component itself:
`         <div style={{height:'300px', width: '600px'}}> 

                <ResponsiveContainer width="100%">
                        <BarChart data={data}
                            margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
                            <XAxis dataKey="estadoCivil" />
                            <YAxis />  
                            <CartesianGrid strokeDasharray="3 3" />
                            <Tooltip />
                            <Legend />
                            <Bar dataKey="cantidad" fill="#8884d8" />
                        </BarChart>
                </ResponsiveContainer>
             </div>`

I'm using React 16.0 and Recharts 1.0.0

I've tried a few solutions I found online but none is working so far. My lastest attempt was wrapping the component inside a div with fixed height and width just as a test, but still not working.

**Comment by patriqdesigns** [comment]
The last example you provided is working fine for me.

I am using React 16.0 and Recharts 1.0.0-beta.10 using the example data set.

![Example](https://i.imgur.com/el8f9MA.png)

Here you can see it in the mobile view in Chrome.

**Comment by tomasztomys** [comment]
You probably have some display: flex before charts.. for example on body element

**Comment by Nikhdy** [comment]
i had the same issue but passing minWidth and and minHeight solved the issue for me even though i used flex

**Comment by knro** [comment]
I'm using material-ui, so there is `display:flex` all over. I'm trying to embed the chart within `ExpansionPanelDetails`, but the chart does not resize at all. Is there a way to force it somehow?

**Comment by ericdcobb** [comment]
@knro did you happen to figure this out?
