### ISSUE TITLE
Question: select per default a value of LinearCharts

### ISSUE THREAD

**Issue by EpicNem** [recharts/recharts#1239]
Hi, I read the documentation but I didn't find the solution.
My question is: is it possible to set per default a selected/hovered active dot when LinearChart is initiated.

Like this when page is loaded: 
![image](https://user-images.githubusercontent.com/29951952/38191485-38461dd0-3669-11e8-87c8-d269c60c2a02.png)

**Comment by jevy-wangfei** [comment]
> Hi, I read the documentation but I didn't find the solution.
> My question is: is it possible to set per default a selected/hovered active dot when LinearChart is initiated.
> 
> Like this when page is loaded:
> ![image](https://user-images.githubusercontent.com/29951952/38191485-38461dd0-3669-11e8-87c8-d269c60c2a02.png)

Have similar requirement, use this resolved:
``` <ReferenceLine x="Page C" stroke="red" label="Max PV PAGE" />```
