### ISSUE TITLE
Question: How can i set min-height of <Bar /> component ?

### ISSUE THREAD

**Issue by ochervak** [recharts/recharts#124]
Question: How can i set min-height of `<Bar />` component ?

**Comment by xile611** [comment]
@ochervak `Bar` don't support min-height now.

**Comment by xile611** [comment]
Fixed in V0.12.0. You can set `minPointSize` of `Bar`.

```
 <Bar dataKey="pv" minPointSize={10} />
```

**Comment by ochervak** [comment]
@xile611 wow! thank you so much!

**Comment by rodoabad** [comment]
@xile611 what does the number represent? Percentage? Or pixels?

**Comment by yarinoo** [comment]
@xile611 there is an option to set min-height when the data is above 0?
e.g: on bars with 0 data I don't want to see the bar but if it's 1 I want a min-height

**Comment by rmlevangelio** [comment]
@yarinoo did you manage to set min-height?

**Comment by ckifer** [comment]
The number represents direct SVG height - so if your `minPointSize` is 10 that is equivalent to if you directly set a `height` of 10.

Here is a sandbox that uses a custom shape to enforce a `minPointSize` conditionally (if a datum is 0 height is 0, if a datum is > 0 but less than minPointSize then use minPointSize)
https://codesandbox.io/p/sandbox/simple-bar-chart-forked-fj29hw
