### ISSUE TITLE
🐛Bug: Order in tooltip is reversed

### ISSUE THREAD

**Issue by michalsnik** [recharts/recharts#1241]
## Do you want to request a feature or report a bug?
I want to report an unintentional behavior.

## What is the current behavior?
On Safari the order of items in tooltip is reversed as compared to chrome.

## Reproduction
https://codesandbox.io/s/231m0rvz6y 

## What is the expected behavior?
The order in tooltip should reflect the order of components in code, just as it does in Chrome.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts 1.1.0-beta.10
Safari 11.0.3

I didn't check previous versions of library.

**Comment by mikegoatly** [comment]
@michalsnik I've noticed that the order is reversed as well, although it would seem to be a general issue. When I look at your sample in Chrome, the order is reversed for me as well:

![image](https://user-images.githubusercontent.com/4577868/55079700-995e8080-5094-11e9-884f-2e570a56b4ec.png)

**Comment by mikegoatly** [comment]
Ok, so looking at the code, the default behaviour is to use this sorter in the tooltip:

``` javascript
itemSorter: () => -1,
```
([from here](https://github.com/recharts/recharts/blob/master/src/component/Tooltip.js#L97))

If you specify an itemSorter on your tooltip like this:

``` tsx
<Tooltip itemSorter={() => 1} />
```

Then the items will be in the same order as in code.

I'm not sure why using `() => -1` would have been used as the default sorter?

**Comment by kolesan** [comment]
Still getting the same issue in v1.8.12, and `itemSorter={() => 1}` does not help, order is still reversed.

**Comment by rajadain** [comment]
I'm seeing the same behavior as well, where the order of items in the tooltip is opposite that of the stacked bar chart:

![image](https://user-images.githubusercontent.com/1430060/108163836-a6881c80-70bd-11eb-970b-8053946883bb.png)

Seen in Chrome and Firefox. Using `itemSorter={() => 1}` has no effect. Specifying `reverseStackOrder` in the `BarChart` reverses _both_ the stacked items and the tooltip, so they still remain out of sync.

**Comment by laylapku** [comment]
I have the same issue in my stack area chart. Using `itemSorter={() => 1}` has no effect. I changed to `{(item) => -item.value}` and the tooltip items are then in ascending order based on the data count of each area.

**Comment by dohomi** [comment]
Can this issue be re-openeded? Because the BarChart order in tooltip is upside down and the itemSorter seems not be able to fix that issue

**Comment by ckifer** [comment]
Sure. I'll try to take a look soon to at least document what's going on

**Comment by ckifer** [comment]
Actually going to leave this one closed and prefer https://github.com/recharts/recharts/issues/2123 for this issue
