### ISSUE TITLE
[Feature] New line for <Text /> in custom ticks

### ISSUE THREAD

**Issue by justduy** [recharts/recharts#1242]
Support new lines for ticks e.g:
23/03/18 \n 12:02 

to

23/03/18
12:02

**Comment by lsarkisov** [comment]
Hey. I need to break text in PolarRadiusAxis ticks. 
Does recharts provides this functionality?

Thanks.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
