### ISSUE TITLE
Add ReferenceLine info to Legend

### ISSUE THREAD

**Issue by sys13** [recharts/recharts#1243]
## Do you want to request a feature or report a bug?
Not sure

## What is the current behavior?
Legend only displays Bar label

## What is the expected behavior?
Would like the reference line to show up in the legend.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.0.0-beta.10 / Firefox

**Comment by noahjohn9259** [comment]
+1

**Comment by wasim-abuzaher** [comment]
Has there been any work toward getting this done? I need this for both barchart and linechart.

**Comment by freeman1995** [comment]
+1

**Comment by kronenbourg** [comment]
any updates?

**Comment by dcarrot2** [comment]
Just ran into this for our use case. Otherwise, it seems the alternative is to hook into the `content` prop and roll out your own legend which means having to re-implement the stuff recharts gives for free.

**Comment by xile611** [comment]
Thanks for your suggestion, we have added this feature to the plan of 2.0

**Comment by woltsu** [comment]
One can add a new line like `<Line name="X" dataKey="null123" stroke="colorOfReferenceLine" />` to add a new line into the legends without actually showing any new data.
