### ISSUE TITLE
Prevent hiding of tick labels

### ISSUE THREAD

**Issue by batjko** [recharts/recharts#1244]
## Do you want to request a feature or report a bug?
More of a question since the docs do not seem to show examples for this.

## What is the current behavior?
In this example, every other tick on the y-axis is not displayed:

![image](https://user-images.githubusercontent.com/7287076/38367884-c32d5976-38db-11e8-9562-09d879e0ac48.png)

And this is already with `<YAxis minTickGap={1}...` prop set.

## What is the expected behavior?
I would like to still show every bar's label. 
At the number of bars shown this should still work just fine (i.e. without overlapping).

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in 
previous versions of Recharts?

Browsers: Latest Chrome and Firefrox
Recharts version: 0.22.0

**Comment by Liam-Tait** [comment]
The solution to this seems to be setting `interval={0}`

**Comment by abineshr64** [comment]
labels are showing but they are merging

**Comment by ckifer** [comment]
Interval 0 means display all labels. Otherwise it tries to collision detect

**Comment by Abinesh64** [comment]
> Interval 0 means display all labels. Otherwise it tries to collision detect

I used interval 0 and it displays all my ticks. But they are colliding what to do?
How to make it wrappable?

**Comment by ckifer** [comment]
You can't, SVGs do not support text wrapping so we have to do it internally in recharts. Interval 0 means "show all ticks no matter what". If you use other settings such as "equidistantPreserveStart" it will try to hide ticks that collide

**Comment by abineshr64** [comment]
Then how to do it internally? The below is my code
      <XAxis 
        dataKey="name" 
        axisLine={{ stroke: '#38537E', strokeWidth: 1 }} 
        tick={{ fill: '#fff', fontWeight:"500", fontSize:"18px", marginRight:"36px", dy: 10 }} 
        textAnchor='middle'
        interval={0}
      />
