### ISSUE TITLE
Recharts chart svg export/download

### ISSUE THREAD

**Issue by sjandro** [recharts/recharts#1245]
## Do you want to request a feature or report a bug?
Request a feature.

## What is the current behavior?
Cannot download recharts chart root svg.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
N/A

## What is the expected behavior?
A built in way to download recharts chart root svg.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.0.0-beta.10

**Comment by Ruffeng** [comment]
I've seen several places that let you download the charts in SVG. Especially the b2b business, which they need to download the graphs for reporting high staff. Definitely, a very nice addition that would be very interesting to see in the library

**Comment by sivapriya-k** [comment]
Has this been resolved? Is there a way to achieve this today?
