### ISSUE TITLE
LabelList postion="top" with negative value wrong position

### ISSUE THREAD

**Issue by lorenzo-pomili** [recharts/recharts#1246]
## Do you want to request a feature or report a bug?
bug Report
## What is the current behavior?
if you use LabelList in bar with position="top" label will rendered in wrong position
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
https://jsfiddle.net/p38pwgxb/1/
## What is the expected behavior?
for negative value the top of label we should have same distance from bar it has with positive value bottom of label from bar
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
"recharts": "1.0.0-beta.10"
Chrome and Firefox Linux

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
