### ISSUE TITLE
scatter plot show different dots while the y-values are same

### ISSUE THREAD

**Issue by lidaof** [recharts/recharts#1247]
![image](https://user-images.githubusercontent.com/102806/38463016-b452ccd4-3ab5-11e8-8238-3603c9ea5337.png)

## Do you want to request a feature or report a bug?
feature
## What is the current behavior?
values with same y-value are plotted together, see the x-axis 2018-03-21
## What is the expected behavior?
if the dots could be put horizontally would be great
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

**Comment by meain** [comment]
Set the `XAxis` and `YAxis` `type` prop as undefined. That seemed to work for me

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
