### ISSUE TITLE
Can not use different nameKey for chart

### ISSUE THREAD

**Issue by nzhtrtlc** [recharts/recharts#1248]
## Do you want to request a feature or report a bug?
I think it is a feature.

## What is the current behavior?
Current behavior based on only one nameKey.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
No its not a bug.

## What is the expected behavior?
I should be able to use different nameKey property for each sector.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Rechart: **^1.0.0-beta.10**
OS: **macOS High Sierra v10.13.1**
Browser: **Chrome**
I did not use previous version of rechart.

**Explanation of issue**
I have a data array. And in that array, i have objects includes **key** property which i use for **nameKey** prop. But in some objects there is another property name instead of **key** so chart can not found anything called **key** here is my problem.
I need to be able to define different nameKey for different sectors (pieces of pie)

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
