### ISSUE TITLE
Legend overlap with chart in tabview (second/hidden tab)

### ISSUE THREAD

**Issue by danielistyo** [recharts/recharts#1249]
## Do you want to request a feature or report a bug?
report bug

## What is the current behavior?
I have 2 tabs. For first tab, chart works so good. In second tab, legend overlap with chart. When I hover to chart, chart is shrinking into correct size.   

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
-create 2 tabs
-add chart and legend for each tabs
-then click second tab

## What is the expected behavior?
chart in second tab doesn't overlap with legend

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
version 16.2, chrome, linux, no

![image](https://user-images.githubusercontent.com/8994371/38560219-521da466-3cff-11e8-84a9-489d4570e6c1.png)

**Comment by Bhargav-Narayan** [comment]
I'm facing the same issue when I'm placing the chart inside an accordion. I'm using react-accessible-accordion npm library. If the accordion is expanded by default, I'm not facing this issue. If user clicks on accordion title and tries to expand, legend will be overlapped on the chart. If user do mouseOver on the chart, then legends resizes and displays properly. 
Need a solution asap. 
Thanks in advance.

**Comment by stevenheffner** [comment]
What did you end up doing?

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
