### ISSUE TITLE
Tooltip/highlighted on wrong tick when cursor is in second half of the correct tick

### ISSUE THREAD

**Issue by george-cz** [recharts/recharts#125]
Hi,

I just updated Recharts in our project to version 0.11.0 and noticed a problem. When I hover over a tick and my cursor is in the right hand half of the tick, the tooltip is displayed on next tick.

Its even visible in example here: http://recharts.org/examples#SimpleBarChart

Do you know about this issue? Are you planning to address it anytime soon?

**Comment by xile611** [comment]
@george-cz thank you, i'll fix this bug today.

**Comment by george-cz** [comment]
Hey, I created a pull request that should fix this: https://github.com/recharts/recharts/pull/126

**Comment by xile611** [comment]
Fixed in V0.12.0.
