### ISSUE TITLE
Multiline Text / label

### ISSUE THREAD

**Issue by hunhejj** [recharts/recharts#1250]
Recently I was trying to achieve something like this: https://stackoverflow.com/questions/45723641/recharts-donut-chart-w-two-labels-in-center

The accepted answer helps a lot however it still doesn't tell how to create a multiline label (using the Text component?).

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
