### ISSUE TITLE
Animations Behaving Unpredictably

### ISSUE THREAD

**Issue by AceCat** [recharts/recharts#1251]
## Do you want to request a feature or report a bug?
I'd like to report a bug
## What is the current behavior?
The animation for my chart is lines floating in from the right side of the chart. It looks... bizarre. On the initial page load I can prevent his behavior by setting an interval and only assigning the chart container a height after the component is initially constructed. However, if the props change for the chart the right-side animation resumes. (Gif below)
![recharts](https://user-images.githubusercontent.com/28152216/38571834-35373f58-3cb7-11e8-988e-dba3288cf05a.gif)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
I'm unable to reproduce the bug - I've used your example and jsfiddle code as the baseline for my own chart. I'm tried tweaking and changing the animation behaviors to no avail.

## What is the expected behavior?
I'd like the nice animation of the lying drawing itself - it's one of the reasons I'm trying to integrate Rechart into my application.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
I'm using version 1.0.0-beta.10. This is my first time using Recharts.

**Comment by samklemm** [comment]
I'm having the same issue. It worked normally for several weeks and now is suddenly rendering the same way as yours. Would love to hear if you found a solution to this!

**Comment by AceCat** [comment]
I ended up fixing it by setting a loading delay (half a second) before the chart displays data. The full mechanics of the issue elude me, but in basic terms it's an issue of the chart loading before the data is provided for it. To fix it, I only show the chart after I've given it a moment to intake the data that I'm passing to the chart.

This is the code I'm using, I suspect there is a less janky solution, but this has been fine for my needs.

`  componentDidMount() {
    var self = this;
    this.arrangeDriversToUse(this.props);
    this.props.getModelDrivers(this.props.selectedModel.modelId);
    this.fetchDriverPositionsForModel(this.props);
    setTimeout(function() {
      self.setState({
        chartContainerStyle: {height: "500px"},
        loading: false
      })
    }, 500);
  }`

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by michaeltomasik** [comment]
I'm still having this issue and im using 1.8.5v
