### ISSUE TITLE
different shapes in one scatter?

### ISSUE THREAD

**Issue by lidaof** [recharts/recharts#1252]
## Do you want to request a feature or report a bug?
feature
## What is the expected behavior?
Can we set different shapes in one <Scatter?/>, also possible to output the legend for different shapes in one scatter?
like in the figure below, for each x-axis, I would like to have different shapes indicating different samples, like change some of dots to starts etc..Thanks.
![image](https://user-images.githubusercontent.com/102806/38624445-b1dc3e26-3d6d-11e8-9636-760b7bd38979.png)

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
