### ISSUE TITLE
shapes in legend in scatter plot should be consistent

### ISSUE THREAD

**Issue by lidaof** [recharts/recharts#1253]
## Do you want to request a feature or report a bug?
bug
## What is the current behavior?
![image](https://user-images.githubusercontent.com/102806/38628592-5bf8dcda-3d77-11e8-8c55-0ffd056b7600.png)
shapes in legend should be star and triangle?
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
https://jsfiddle.net/alidingling/3mw50Lc9/

**Comment by meain** [comment]
You can actually change the shape that appear in the legend by mentioning `legendType` in `Scatter`.

https://github.com/recharts/recharts/blob/0d03d942112000a1d08146f667438fb74fa81913/demo/component/ScatterChart.js#L148

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
