### ISSUE TITLE
Guide, API, Examples, and Blog links from http://recharts.org are all 404ing

### ISSUE THREAD

**Issue by Soundvessel** [recharts/recharts#1254]
Guide, API, Examples, and Blog links from http://recharts.org are all 404ing. Even the getting started link, http://recharts.org/en-US/guide/getting-started, is 404ing. We need detailed documentation to consider using this project.

**Comment by TheShrike** [comment]
Direct links are broken, but they work if you get there by browsing the site:
http://recharts.org/ > Guide > Getting Started

**Comment by franciscop-invast** [comment]
The fix is in a link in [Create-React-App documentation](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#notes-on-client-side-routing):

[Single Page Apps for GitHub Pages](https://github.com/rafrex/spa-github-pages)

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
