### ISSUE TITLE
how to remove default gap between sectors in Pie Chart ?

### ISSUE THREAD

**Issue by raviteja83** [recharts/recharts#1255]
## Do you want to request a feature or report a bug?
Question.
## What is the current behavior?
Unable to remove the default spacing between sectors of Pie

## What is the expected behavior?
There should be an option to remove the default gap. The paddingAngle prop can only be used to increase the gap.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
v1.0.0-beta.10
Chrome 65

**Comment by devinceble** [comment]
+1

**Comment by ryangiglio** [comment]
It's sort of unbelievable to me that 1px of padding is unremovable. Pie charts differentiated by color are the most standard way of using them.

**Comment by lylejantzi3rd** [comment]
+1

**Comment by burkel24** [comment]
+1

**Comment by burkel24** [comment]
As a workaround, you can set the ```stroke``` prop of each slice of the pie to be the same color as the ```fill``` prop. 

It would be nice if there was a prop we could pass to the ```<Pie>``` to automatically match the stroke color to the fill color

**Comment by burkel24** [comment]
Fixed in `v1.2.0` with the addition of the `blendStroke` property to the pie component.

This issue can be closed

**Comment by nagamallikam** [comment]
> It's sort of unbelievable to me that 1px of padding is unremovable. Pie charts differentiated by color are the most standard way of using them.

Giving stroke="" solves the problem.

**Comment by Yyana22** [comment]
"Giving stroke = "" also solves the problem." But if stroke need on one white sectors ?
