### ISSUE TITLE
Avoidable Re-rendering.

### ISSUE THREAD

**Issue by amanshu-kataria** [recharts/recharts#1256]
## Do you want to request a feature or report a bug?
No.

## What is the current behavior?
The graph is rendering which is avoidable.
![screen shot 2018-04-12 at 4 10 33 pm](https://user-images.githubusercontent.com/13014093/38672669-7bb95c98-3e6c-11e8-9e27-20ed3d994838.png)

## What is the expected behavior?
The graph shouldn't re-render until prop changes.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.0.0-beta.10.

You can only view the above warning by adding [why-did-you-update](https://github.com/maicki/why-did-you-update) as dependency. You can check this [medium post](https://benchling.engineering/a-deep-dive-into-react-perf-debugging-fd2063f5a667) for ref.

**Comment by jwm0** [comment]
I've also noticed this issue, it seems like multiple consecutive rerenders also halt the animation.

**Comment by amanshu-kataria** [comment]
@xile611 please check this issue.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
