### ISSUE TITLE
CustomizedLableLineChart jsfiddle demo points to CustomizedDotLineChart jsfiddle.

### ISSUE THREAD

**Issue by jseparovic** [recharts/recharts#1258]
In the docs, CustomizedLableLineChart jsfiddle demo points to CustomizedDotLineChart jsfiddle.
Is there a link somewhere for the CustomizedLableLineChart jsfiddle?

**Comment by euandrei** [comment]
+1

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
