### ISSUE TITLE
Code Splitting

### ISSUE THREAD

**Issue by franciscop-invast** [recharts/recharts#1260]
## Do you want to request a feature or report a bug?

Feature request / improvement.

## What is the current behavior?

When importing Rechart with React, the whole library is imported even if we only use a part of it. See partial screenshot from `source-map-explorer`:

![rechart](https://user-images.githubusercontent.com/36914428/38850548-e6fef966-424c-11e8-8850-a9552c2700cf.png)

Right now I am importing it like this:

```js
import { AreaChart, XAxis, Tooltip, Area, ResponsiveContainer } from "recharts";
```

Is there a way to import only the parts we need? Something like this:

```js
import AreaChart from 'recharts/AreaChart';
import XAxis from 'recharts/XAxis';
import Tooltip from 'recharts/Tooltip';
import Area from 'recharts/Area';
import ResponsiveContainer from 'recharts/ResponsiveContainer';
```

It is more verbose, but since it is likely many people are wrapping 3rd parties components such as this with their own components then it is a 4 extra lines for a ~80% reduction of the size.

Recharts is the second largest library I have in my code only after Auth0's Lock (which [is very notorious](https://github.com/auth0/lock/issues/113) about this) so reducing the code size would be very nice.

So, is it possible to do code splitting with Recharts? If this is possible, then the feature request is to document it 😄

**Comment by franciscop-invast** [comment]
After digging a bit in the code it seems to be working:

```js
import AreaChart from "recharts/es6/chart/AreaChart";
import XAxis from "recharts/es6/cartesian/XAxis";
import Tooltip from "recharts/es6/component/Tooltip";
import Area from "recharts/es6/cartesian/Area";
import ResponsiveContainer from "recharts/es6/component/ResponsiveContainer";
```

Happy to report that Rechart size has been reduced. I expected a larger reduction though, but still I saw a ~10% reduction on my total code size:

![rechart](https://user-images.githubusercontent.com/36914428/38852127-80237850-4253-11e8-98e3-ea1f9aca7c9d.png)

I leave this open as a suggestion for documenting this; feel free to close it though.

**Comment by franciscop-invast** [comment]
It doesn't work with `npm test` for Create-React-App though, since that uses Node.js and you cannot `import` on Node. I'll leave the heavier version then, since there's not such a big difference and test >>> ~10% code size.

**Comment by spjpgrd** [comment]
Ended up doing the same thing as @franciscop-invast — used the `recharts/es6/index.js` to easily tell where an import was.

**Comment by vigyanhoon** [comment]
Doesn't work with typescript.

`import LineChart from 'recharts/es6/chart/LineChart'`

I have already installed "@types/recharts": "^1.8.12",

getting error

Could not find a declaration file for module 'recharts/es6/chart/LineChart'. 'c:/Users/vigya/Desktop/projects/the-list/node_modules/recharts/es6/chart/LineChart.js' implicitly has an 'any' type.
  If the 'recharts' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/recharts`ts(7016)
