### ISSUE TITLE
Do not hide my horizontal ticks, please

### ISSUE THREAD

**Issue by mpodlasin** [recharts/recharts#1262]
I am settning tick values on axis by hand:
```jsx
            <YAxis 
                domain={[minValue, maxValue]} 
                unit={unit} 
                axisLine={false} 
                tickLine={false} 
                allowDecimals={false}
                ticks={[minValue, (maxValue - minValue) / 2, maxValue]} // here!!!
                tickCount={3}
                tickFormatter={(tick: number) => tick.toFixed(0)} 
            />
```
And yet chart tries to be "smart" and hides middle tick on smaller devices, even though there still seems to be a lot of space:

![screenshot from 2018-04-18 13-54-55](https://user-images.githubusercontent.com/7916523/38930412-17f84946-4310-11e8-8d5d-8cf298dfbb19.png)

How can I override that?

**Comment by praveenksharma** [comment]
I have the same issue. Why one of my tick is hidden? How can I override this behavior. Can I make the ticks vertical?

**Comment by dangh** [comment]
I get the same result and I found out that you need to force the axis to `number` type by:
- set `type` to `"number"`
- remove `unit` prop
