### ISSUE TITLE
Axis ticks have unreasonable values

### ISSUE THREAD

**Issue by mpodlasin** [recharts/recharts#1263]
My code:
```jsx
            <YAxis 
                domain={[minValue, maxValue]} 
                unit={unit} 
                axisLine={false} 
                tickLine={false} 
                allowDecimals={false}
                tickFormatter={(tick: number) => tick.toFixed(0)} 
            />
```

I would assume that ticks on axis will have some reasonable out of the box values.

But what I get is this:

![screenshot from 2018-04-18 14-01-42](https://user-images.githubusercontent.com/7916523/38930690-0a0118d0-4311-11e8-9b74-0282a429217f.png)

Based on what is this generated?

I tried to pass own scales, but I get as crazy results. For example with `scale="linear"` I get:

![screenshot from 2018-04-18 14-03-06](https://user-images.githubusercontent.com/7916523/38930753-3c752f68-4311-11e8-9aa3-c9c0f03c40f3.png)

**How can I get some reasonable, more or less evenly spaced ticks?**

**Comment by m1chah** [comment]
Try 'auto', works for me [http://recharts.org/en-US/api/YAxis#domain](http://recharts.org/en-US/api/YAxis#domain )

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
