### ISSUE TITLE
Conditionally skip a bar

### ISSUE THREAD

**Issue by bpatterson-r7** [recharts/recharts#1265]
I want to conditionally skip rendering a bar in a bar chart. If the data exists, I want to render the bar, but if the data doesn't exist, I don't want there to be an empty space in the bar chart.

This is what my chart looks like
```
<ComposedChart data={data}>
    <Bar dataKey="a"/>
    <Bar dataKey="b"/>
    <Bar dataKey="c"/>
    <Bar dataKey="d"/>
</ComposedChart>
```
For example, if dataKey "c" is 0 or doesn't exist, I want to render a, b and d without the empty space that c should occupy.

**Comment by jackmarketon** [comment]
Generate your `Bar` components based on the data.
```
const actives = data.reduce((acc, datum) => ({...acc, ...datum}), {});
Object.keys(actives).map((dataKey) => <Bar dataKey={dataKey} />)
```

**Comment by hos4m** [comment]
You can use the `hide` attribute on the `Bar` component. Unfortunately it's not mentioned in the documentation, I got it from exploring the source code.

**Comment by dgarciasarai** [comment]
How can I do this? Someone can help me? @bpatterson-r7 @hos4m

**Comment by tramax** [comment]
This ticket is not resolved yet. I think @bpatterson-r7 wanted to skip a bar conditionally (in some rows), not to hide one totally.

**Comment by DmitriyKochergin** [comment]
Found solution to skip a single bar in this example: https://recharts.org/en-US/examples/CustomShapeBarChart
Cell is used to wrap all bars (https://recharts.org/en-US/api/Cell)
Then you can use that to attach additional styles needed:
------------------------------------------------------------------------
<Bar dataKey="x" fill={'#F2F2F2'}>
    {data.map((entry, index) => {
        return <Cell key={`cell-${index}`}
            style={{display: entry.property === 0 ? '' : 'none'}}/>
    })}
</Bar>
------------------------------------------------------------------------

**Comment by margretb17** [comment]
Has anyone found a solution for this problem?

**Comment by bloodteller123** [comment]
> I tried approach with custom shape for each `Bar` and manually generating `path` for each `Bar` depending on the payload it gets. Came up with the `ConditionalRectangleBar` that will have 0 width when no specific key is present and normal `RectangeBar` which will adjust it's position on `AxisX` whenever first conditional `Bar` is not here.
> 
> Here is sandbox, try playing with `y` key in data array. https://codesandbox.io/s/recharts-conditional-double-bar-chart-7kgze
> 
> @bpatterson-r7 @dgarciasarai check this out if this is the outcome you need 😄

What if you wanted to have legend for each item? This doesn't seem to work.

**Comment by somani09** [comment]
Has there been any Updates to this issue?

**Comment by axebnoo** [comment]
Has there been any Updates to this issue?

**Comment by ckifer** [comment]
This issue doesn't really make it clear what everyone wants as an end result. Since this is closed and has been for a while, can anyone looking at this issue create a new one?

I believe all of the above answers are still valid depending on what you're trying to do. 

You can hide a bar with the hide prop or via conditional rendering
