### ISSUE TITLE
Recharts - Multiple charts in one page optimization perfomance

### ISSUE THREAD

**Issue by ncnthuy** [recharts/recharts#1266]
Dear, 

I am facing with the problem about performance when implement about 100 recharts in one page.
And the screen is really terrible slow when scrolling.
With this issue, how can I optimize recharts for best performance?

**Comment by marinodorador** [comment]
I dear maybe you can use react virtualize to only render those charts that you're seeing.

https://github.com/bvaughn/react-virtualized

Maybe collections or grid can be use useful for your use case, take a look =)

**Comment by ncnthuy** [comment]
Hi @marinodorador 
Thanks for your recommendation. I was take a look `react-virtualized`, then I used https://github.com/joshwnj/react-visibility-sensor

**Comment by danielkrich** [comment]
Hey @ncnthuy 
I'm experiencing the same problem, do you remember how did you end up using this library to speed things up? just hiding non-visible charts?
