### ISSUE TITLE
Tooltip delay show

### ISSUE THREAD

**Issue by reginavlee** [recharts/recharts#1269]
## Do you want to request a feature or report a bug?
Request Feature
## What is the current behavior?
Tooltips have animations, but proposing a delay show
## What is the expected behavior?
the ability to pass down a prop (delayShow / delayHide) to delay the enter of the tooltip
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

If there is an existing way to do this? So far, I am only aware of adding animations which I don't want. I want it to just appear as is, just delay the entering.

**Comment by huei-tan-sociomantic** [comment]
just appear as is, you can `isAnimationActive={false}`

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue guide.
