### ISSUE TITLE
Can a tooltip be added for a ReferenceLine? Or can Legend information be included with details of ReferenceLine?

### ISSUE THREAD

**Issue by gajjammt** [recharts/recharts#1271]
Can a tooltip be added for a ReferenceLine? Or can Legend information be included with details of ReferenceLine?

I have a BarChart and a ReferenceLine along x-axis(representing the average of scales on y-axis).
I want the details of Average to be shown either on hovering on the reference line or it should be part of Legend. Is it possible to do?

Thanks in advance!

**Comment by freeman1995** [comment]
+1

**Comment by xile611** [comment]
Sorry, not supported yet. It's recommended to use customized `content` of `Tooltip` to cover default tooltip.
