### ISSUE TITLE
Label of the ToolTip doesn't work

### ISSUE THREAD

**Issue by Wing-Lo** [recharts/recharts#1272]
## Do you want to request a feature or report a bug?
**bug**
## What is the current behavior?
setting ToolTip's label property.
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
here is template:https://jsfiddle.net/jsfiddlewing/k5kbpve6/
look at the part of Babel+JSX and the line at 19th,the property of label doesn't work.
## What is the expected behavior?
it will change the "title" in the ToolTip
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
versions of Recharts : ^1.0.0-beta.10
browser: Chrome
OS: Mac OS
I didn' t try the previous versions of Recharts.

**Comment by phamj88** [comment]
+1
Documentation has no examples

**Comment by devlin-playlogix** [comment]
+1
chart looks quite odd when my tooltip is forced to say `timeTaken` as opposed to `Time Taken` because of the key inference.

**Comment by hybmg57** [comment]
You need to use both `label` and `labelFormatter`
<Tooltip label="{timeTaken}" labelFormatter={(name) => 'Time Taken: ' + name} />

**Comment by xtrinch** [comment]
@hybmg57 Doesn't seem to work for me, labels are not changing
