### ISSUE TITLE
Pie Charts do not respect data sort when rendering slices

### ISSUE THREAD

**Issue by jackmarketon** [recharts/recharts#1273]
## Do you want to request a feature or report a bug?
Bug Report

## What is the current behavior?
When feeding the `<Pie>` component data it does not seem to respect the sorted order of the data.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

Since JS fiddle isn't working:

```
        <ResponsiveContainer aspect={1.5}>
            <PieChart>
                <Pie
                    label={({ name, value }) => `${name}: ${value}`}
                    labelLine={false}
                    data={data}
                    nameKey="name"
                    dataKey="value"
                    innerRadius="25%"
                    outerRadius="50%">
                    {data.map(({ id }) => <Cell key={id} fill={colorConfig[id]} />)}
                </Pie>
            </PieChart>
```

Example Data:
```
const data = [
  { id: 0, value: 3, name: 'Assigned' },
  { id: 'unassigned', value: 2, name: 'Unassigned' },
  { id: 2, value: 10, name: 'Created' },
].sort(({ name: a }, { name: b }) => a.localeCompare(b));
```
<img width="385" alt="pie chart sorting" src="https://user-images.githubusercontent.com/1520289/39196381-9b9f4d4e-47a7-11e8-8ff1-caf4955d4950.png">

## What is the expected behavior?
Pie chart should be rendered in sorted order, for example clockwise: Assigned, Created, Unassigned if respecting the example data

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
recharts version: 1.0.0-alpha.4

**Comment by bsobotta** [comment]
You can control this behaviour actually by using the startAngle and endAngle props of the Pie component:
http://recharts.org/en-US/api/Pie#startAngle

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by senthilaru** [comment]
works perfectly., clockwise - aligned with clock-timing
```
startAngle={-90}
endAngle={-450}
```
