### ISSUE TITLE
Method "find" does not exist in IE

### ISSUE THREAD

**Issue by tortillaj** [recharts/recharts#1274]
## Do you want to request a feature or report a bug?

bug

## What is the current behavior?

IE reports that `find` is not available to it, causing the tooltip to not display. There may be other side effects, but the tooltip is the one I've noticed so far. In the app I'm working on, supplying a polyfill corrected the problem.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

Make a bar chart with a tooltip, and try to view it in IE11.

## What is the expected behavior?

You should see the tooltip.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Not sure if it previously worked, but I wouldn't be surprised if it did. [The changelog shows that version 1.0.0-beta.8 introduced Array.prototype.find](https://github.com/recharts/recharts/blob/b48b6d6c912e354a918d2b6307f5c8c6ada210df/CHANGELOG.md#fix-2), so the error may be related to changes in that release.

**Comment by trsiddiqui** [comment]
@tortillaj @maiis @dlindahl @ahmedelgabri @txgruppi has this been resolved? If yes then please share the solution.

**Comment by txgruppi** [comment]
Sorry @trsiddiqui but there is a while I don't work with recharts. I'm not really sure about the state of this issue. Cheers.
