### ISSUE TITLE
Support Drilldown on multi level Tree Map data

### ISSUE THREAD

**Issue by mattspeller** [recharts/recharts#1276]
## Do you want to request a feature or report a bug?
Feature
## What is the current behavior?
Treemap is static after render
## What is the expected behavior?
When user clicks on a section of the treemap, the data is expanded showing the level n+1 and all data within. User has option to go back to top level. On data refresh the level is respected if the top level data still remains. Type of features already exist in similar controls available by Highcharts.  See the example I put together with highcharts that does this - however it is ugly and hard to code - https://codesandbox.io/s/mmzp61k779
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Not currently implemented

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
