### ISSUE TITLE
The demo url doesn't work other than the default URL http://recharts.org

### ISSUE THREAD

**Issue by xcv58** [recharts/recharts#1279]
The http://recharts.org page will redirect user to http://recharts.org/en-US/. It shows 404 if user hit refresh button or share the link.

![image](https://user-images.githubusercontent.com/503123/39336116-ac20309c-496a-11e8-8a74-ce8b3ebbc711.png)

**Comment by raelmiu** [comment]
Ping, it's hard to use without any documentation pages...

**Comment by breadadams** [comment]
Pretty crucial issue for documentation, it deems the docs impossible to share with team members without giving instructions on how to actually get to a page.

**Comment by xile611** [comment]
This issue has been fixed.
