### ISSUE TITLE
isAnimationActive is ignored when data changed on TreeMap

### ISSUE THREAD

**Issue by mattspeller** [recharts/recharts#1281]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
When changing data the Treemap animates the changes, when isAnimationActive is false. When attempting to update the Treemap data < 100ms it is impossible for the chart to keep up with animation enabled.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
https://jsfiddle.net/m02y2dhz/

See timer changes data and animation occurs on change. Note the initial load does not animate.

## What is the expected behavior?
On change the Treemap does not animate

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Chrome, Recharts@1.0.0-beta.10

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
