### ISSUE TITLE
Bar ignores 'fill' prop if dataset has 'fill' key

### ISSUE THREAD

**Issue by rafaelrene** [recharts/recharts#1282]
## Do you want to request a feature or report a bug?
I'm not quite sure whether it's a bug or intentional, but `fill` property in `Bar` component does not seem to work as expected

## What is the current behavior?
When provided data is an array of objects that contain `fill` key, it can not be overriden by passing a prop to `Bar` component.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
JSFiddle can be found here: https://jsfiddle.net/LL4abs3w/2/

Notice that near the top we have two datasets defined. `data` is regular data and `dataWithFill` is a dataset where each datum has a different color.

Lower in the code we have two `Bar` components. One of them has `fill` prop with value `transparent`, while the other one has a color.

When using `data`, everything seems to be working perfectly fine and as expected, however when `dataWithFill` is passed to `BarChart` component, suddenly both `fill` props in `Bar` components are ignored and it seems that what is in the dataset has the greatest priority (hence why I am not quite sure whether this is a bug or intended behavior).

## What is the expected behavior?
Since `Bar` component is defined deeper in the structure, I expected to be able to override `fill` prop, but it didn't have any effect.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts: `1.0.0-beta.10`

**Comment by ckeeney** [comment]
Right now I'm styling all my bars the same color with the `fill` prop mentioned above.  I wanted to style each bar separately based on data and was surprised to see that [the `fill` prop is missing from the docs](http://recharts.org/en-US/api/Bar) completely.

Maybe the `fill` prop is not meant to be used?

Fortunately the `fill` set in data makes styling each bar easier.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
