### ISSUE TITLE
React and Recharts upgrade issue

### ISSUE THREAD

**Issue by bishwenduk029** [recharts/recharts#1283]
## Do you want to request a feature or report a bug?
A bug

## What is the current behavior?
For recent version of react 16.x and recharts 1.0.0-beta.10, there is an error encountered at line 

var AxisLabel = _react2.default.createClass({ in recharts reported in console logs)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
By upgrading the react, react-dom from 15.x to 16.x and also upgrading recharts from 0.22.8 to 1.0.0

## What is the expected behavior?
The incompatibility with older version due to react class definition method should not occur.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts: 1.0.0-beta.10 (latest) and chrome browser. Yes it did work in older versions. Now the entire application is not working.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
