### ISSUE TITLE
Change bar color on mouseover with tooltip

### ISSUE THREAD

**Issue by stephenrichard** [recharts/recharts#1285]
Hi everyone,

I'd like to ask you a question because I can't figure out how to achieve this:

**My goal**

I'm trying to change the color of the bar when I hover that bar.

![image](https://user-images.githubusercontent.com/4067686/39570897-10f4486e-4eca-11e8-9220-6151246d26fb.png)

**My problem**

When I hover the area around the bar, the tooltip shows up before the hover on the bar is detected. I figured out how to change the bar color when you hover it precisely, only.
![image](https://user-images.githubusercontent.com/4067686/39570983-50a8aa2c-4eca-11e8-9110-9bf2067fffc6.png)

**Question**: Is there a way to change the bar color when I enter the area around it like the tooltip does (in the same time as the tooltip) ?

Thanks in advance ✌️

**Comment by koenvosdesign** [comment]
See https://github.com/recharts/recharts/issues/811

This can be achieved with CSS.

**Comment by stephenrichard** [comment]
Hey @koenvosdesign, thanks for pointing this issue. I can do it with css but it's not exactly what I'm trying to do. This way, I can only change the color on exact bar hover, what I want to achieve is change bar's color on the area hover, the same area as the Tooltip.

Like in [this example from the doc](http://recharts.org/en-US/examples/SimpleBarChart)

See how the tooltip is triggered even when you don't hover exactly the green and purple bar. I'd like to change my bar's color at the same moment the tooltip changes. And I'm not sure how to do that.

My guessing so far is I'll have to use a custom tooltip and display it only when you hover precisely a bar. But this way I'm not sure I'll be able to use the tooltip's auto-positioning 🤔

**Comment by nhungnguyen3011** [comment]
Hi,

I would like to know how to handle the mouse enter event when hovering the area around the bar too.

 @stephenrichard, did you find any solution yet?

**Comment by stephenrichard** [comment]
Hello,

Nope. It was for a project in short delays and I jumped to another part. I tried the custom tooltip trick but letting recharts handle the responsive/boundaries positioning was more effective.
So I have no solutions to my problem so far and haven't tried anything since.

Sorry I can't help you more with that 😅
(I'll probably close the issue)

**Comment by ohtanya** [comment]
I'm trying to achieve the same. @nhungnguyen3011 were you able to find a solution?

**Comment by nhungnguyen3011** [comment]
@ohtannya, I’m sorry but no, I didn’t find any solution for this yet. We decided to use current hovering behavior and put this issue aside to do other important task first. We’ll try to do this later. If I find anything in the future, I’ll try to comment it here :)

**Comment by danielkrich** [comment]
@fllprbt 
Maybe I'm missing something, but in case you add `onMouseEnter` on the Bar, it triggers only when you hover on the actual Bar. So it's not the same action that triggers the default hover background.

**Comment by fllprbt** [comment]
> us
Yes, but we mostly use that for `<Bar />` logic like changing the bar's color on hover... What would you want to achieve with the background?

**Comment by hoangnm284** [comment]
Hi, 

I've just come across the same problem, and after digging out the source code, I find the solution for BarChart using `onMouseMove` event. The param passed into `onMouseMove`  includes information about tooltip state: `isTooltipActive` and `activeTooltipIndex`. 

So the code looks likes this:

```jsx
const [focusBar, setFocusBar] = useState(null);
return (
  <BarChart
    data={data}
    onMouseMove={state => {
      if (state.isTooltipActive) {
        setFocusBar(state.activeTooltipIndex);
      } else {
        setFocusBar(null);
      }
    }}
  >
    <Tooltip />
    <Bar dataKey="value">
      {data.map((entry, index) => (
        <Cell key={`cell-${index}`} fill={focusBar === index ? '#0057B6' : '#007AFF'} />
      ))}
    </Bar>
  </BarChart>
);

```

Hope it helps.

**Comment by ypresto** [comment]
Only using onMouseMove is insufficient, sometimes a bar is remain focused after leaving mouse from the chart.

`onMouseLeave` should be specified to surely receive `state.isTooltipActive === false` event (and perhaps `onMouseEnter`, for first event).

**Comment by dsldsl** [comment]
very helpful @hoangnm284 thank you

**Comment by Phonixoop** [comment]
```
.recharts-rectangle.recharts-tooltip-cursor {
  fill: #00000049;
}

```
