### ISSUE TITLE
Add className props to certain components

### ISSUE THREAD

**Issue by breadadams** [recharts/recharts#1287]
## Do you want to request a feature or report a bug?

Request a feature

## What is the current behavior?

Many of the components don't take a `className` prop, where it could be rather useful.

## What is the expected behavior?

Adding a `className` prop to components such as `Legend`, `Tooltip`, etc. would allow for easier customization with style systems like JSS or styled-components (without needing to reference the classNames defined by recharts).

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Latest version, wasn't a present feature previously as far as I can tell.

**Comment by breadadams** [comment]
Happy to provide a PR! 🙂

**Comment by HaritDivyesh** [comment]
How I wish this was a feature! Would make everything so much simpler. I simply need to make my legend text bold and for that I am trying to create a custom component. Problem with that is, as far as I can tell, I'm not able to display the icon for my bar chart bars.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by mm105** [comment]
this issue is still there, it's not possible to add className to <Legend />

**Comment by piatrashkakanstantinas** [comment]
It is not possible to add `className` to `Legend` component.
