### ISSUE TITLE
Test SankeySpec.js is fails with "Timeout of 2000ms exceeded." Solution suggested, need comments.

### ISSUE THREAD

**Issue by meghalidhoble** [recharts/recharts#1290]
## Do you want to request a feature or report a bug?
Report a bug

## What is the current behavior?
One of the tests execution is failing for me. 

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
I am trying to build recharts on ppc64le platform and it builds fine without issues. However while running the tests using "npm test", a particular test was failing with below error: 

> Firefox 52.0.0 (Linux 0.0.0) <Sankey /> re-renders links and nodes when data changes FAILED
>         Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

With some changes to the test file - test/specs/chart/SankeySpec.js  I could fix the errors, however need to understand if the changes I made are good to be merged with the main-stream and those won't cause any regressions. 

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts version :  "1.0.0-beta.10" (master code)
Browser  :  Firefox (for the tests to use firefox, I had to make changes) 
OS : Linux (Rhel 7.4) 
Platform : ppc64le 

I would like to push the changes if those looks fine. Please let me know your thoughts or any suggestions around this. 
Thanks,
Meghali

**Comment by meghalidhoble** [comment]
I would like to contribute the fix for this to the community. Need someone to take a look and guide me if the change I made is the correct way to fix this test for ppc64le. Please let me know.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
