### ISSUE TITLE
The data is empty array

### ISSUE THREAD

**Issue by hqzh** [recharts/recharts#1295]
![111](https://user-images.githubusercontent.com/26128706/39965053-63d4faf4-56c4-11e8-9935-0c2f9cdc8abd.png)
I think if the data is empty,it's better show 'no data' in the page

**Comment by huei-tan-sociomantic** [comment]
what do you mean 'no data'?

**Comment by hqzh** [comment]
![this](https://user-images.githubusercontent.com/26128706/40352586-ccbb4338-5de1-11e8-8fa7-ce2a6a991468.png)
@huei-tan-sociomantic view like this

**Comment by huei-tan-sociomantic** [comment]
you can simply check the `data` before rendering the Chart.

**Comment by hqzh** [comment]
@huei-tan-sociomantic I think global configuration may be better

**Comment by hqzh** [comment]
`const RechartView = props => (<React.Fragment>{!props.data.length ? < div style={{ textAlign: 'center' }} > No Data</div> : props.children}</React.Fragment >)`

like this wrap

**Comment by hqzh** [comment]
@huei-tan-sociomantic

**Comment by hqzh** [comment]
先关了,看来作者没有维护了,自己项目中全局处理下
