### ISSUE TITLE
No Labels and Tooltip info in PieChart when passing data containing `key` properties

### ISSUE THREAD

**Issue by jzipfler** [recharts/recharts#1298]
## Do you want to request a feature or report a bug?
bug

## What is the current behavior?
Passing data to the pie chart where the entries contain objects with a `key` property, this property will be used as key for `renderSectors` and `renderLabels`.
The related name in the tooltip will also not be shown.

As far as we could trace the behaviour, it seems to be the following problem:

On the `renderLabels` function, the `labelProps` will be constructed with spread syntax out of some `sectors`.
The `sectors` are constructed with the spread syntax as well on the passed data in the `getSectors` function.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

https://jsfiddle.net/jzipfler/1kmpjpzf/

## What is the expected behavior?

I would expect, that the data passed to an React component, can not change the behaviour of some components that are used internally in a library.
This means, that the spread syntax for objects that are working on the passed data should be used with caution.

If you want to keep the code as it is, it would be an enhancement, if the described behaviour would be added to the documentation.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Tested with the following versions
* 0.22.4
* 0.22.5
* 1.0.0-beta.10

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
