### ISSUE TITLE
Scatter plus Line combination doesn't work using ComposedChart

### ISSUE THREAD

**Issue by shakalakatechie** [recharts/recharts#130]
Thanks for this fantastic library which saved my time.

Could you please share any ideas on how to get a Scatter plus Line combination chart using this.

**Comment by xile611** [comment]
@shakalakatechie 
Recharts only support simple line in ScatterChart now. [Here](http://recharts.org/examples#JointLineScatterChart) is an example.

Can you share what's kind of Line you want to add in Scatter?

**Comment by shakalakatechie** [comment]
@xile611 
I am looking for something like this - Please let me know if there is a workaround to get this done using ReCharts.
![linescatter](https://cloud.githubusercontent.com/assets/19373614/16406473/1ae8655a-3d2c-11e6-97fd-9fafb033f171.png)

**Comment by xile611** [comment]
How about [this example](http://jsfiddle.net/ctu7hbjj/)?

**Comment by jcarian** [comment]
@xile611 - Hey, can we connect to talk ReCharts?

**Comment by xile611** [comment]
@jcarian you can connect to us on [gitter](https://gitter.im/recharts/recharts?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
