### ISSUE TITLE
Examples Link Broken

### ISSUE THREAD

**Issue by karlpatrickespiritu** [recharts/recharts#1300]
<img width="1024" alt="screen shot 2018-05-14 at 9 51 52 pm" src="https://user-images.githubusercontent.com/10472504/40002050-24d54db4-57c2-11e8-9dba-6ecbcd26603a.png">

**Comment by JoshClose** [comment]
Looks like anything that isn't the root path doesn't work.

**Comment by xile611** [comment]
This has been fixed.
