### ISSUE TITLE
Many warnings about unsupported behaviour when using the label attribute with React 16

### ISSUE THREAD

**Issue by pjverity** [recharts/recharts#1302]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
Using the `label` attribute on chart components results in countless React warnings in the console.

> Encountered two children with the same key, '`label-name`'. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted  - their behavior is unsupported and could change in a future version.

The <Layer> component renders two child components: `<Curve>` and `<Text>` when rendering the labels, both are given the same key leading to this warning.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
Could not get a JSFiddle to compile or run with React 16.3.2 and Recharts 1.0.0-beta.10. Will keep trying!

## What is the expected behavior?
That each child has a different key when rendering labels

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Using 1.0.0-beta.10 with React 16.3.1 on Chrome. I don't see this occurring with the online examples, but believe they use React 15.

**Comment by sergeysolovev** [comment]
This reproduces for me also, the same versions of React and Recharts.

In my case the labels don't get rendered until I resize viewport a bit and then click the pie chart. This seems to be related to the duplicate keys issue. I would like to have a workaround for this.

**Comment by amimas** [comment]
Any update on this issue?

**Comment by pouretrebelle** [comment]
+1

**Comment by ivorbosloper** [comment]
The problem starts at https://github.com/recharts/recharts/blob/master/src/polar/Pie.js#L342 . Both `labelProps` and `lineProps` are filled with `...entry` and therefore inherit the same key property. The elements with these same key props are both added to the resulting `<Layer>`. I'll try to create a pull-request fixing this issue.
