### ISSUE TITLE
Provide "paint order" to stacked bars in bar chart

### ISSUE THREAD

**Issue by mitchellcunha** [recharts/recharts#1304]
## Do you want to request a feature or report a bug?
Feature / Enhancement

## What is the current behavior?
Currently, there is no way (that I see documented) to give preference to which bar is painted on top when rendering a stacked bar chart.

Swapping the order of the bar components doesn't swap priority, but swaps which bar is on top or bottom. This is an issue for me because I would like to show labels above each stacked bar, and the first bar's label is being covered by the second, due to the paint order.

![screen shot 2018-05-16 at 3 47 43 pm](https://user-images.githubusercontent.com/12757306/40147955-862cd352-5920-11e8-87f1-5654ca179646.png)

## Demo
See fiddle here: https://jsfiddle.net/kcunha/vu4fr3Lz/2/
In the fiddle above, I have manually given one of the bars 0.5 opacity to demonstrate the issue.

## What is the suggested enhancement/behavior?
Ideally, it would be helpful if there was a prop which would be passed to each `Bar` component rendered with a number indicating its priority. That way developers could customize which bar is on top / bottom. The following screenshot is a hacked visual with the bottom bar forced to be painted on top:
![screen shot 2018-05-16 at 3 43 47 pm](https://user-images.githubusercontent.com/12757306/40147808-fcac0bf2-591f-11e8-86de-fceb317ec8d2.png)

If something like a "paint order" prop is too involved, maybe an "id" that can be given to the `Bar` component, so that the paint order can be overridden with `<use xlinkHref="bar-id"  />` elements on a more custom basis.

## Which versions of Recharts?
"recharts": "1.0.0-beta.6",

**Comment by xile611** [comment]
Duplicated with #1184

**Comment by Haraldson** [comment]
These are different needs, @xile611. Not a duplicate.

Being able to know which segment is last, is different from being able to reorder them. A use case, other than the one provided in this issue, is applying `radius` only to the last segment in any given stack/bar. All segments aren’t always present in every stack, and so you need more meta data to determine which is last/topmost.

---

Over the short time I’ve been using Recharts, I’ve seen you close issue after issue in this project, most of the time without providing much – if any – explanation or insight, and seemingly without haven taken the time to understand the different needs. Where is the value in doing this?

**Comment by liujiajun** [comment]
I agree with @Haraldson.

**Comment by gabrielmoterani** [comment]
@mitchellcunha did you find any solution to this? I also need to know the last segment of a stacked bar chart.

**Comment by gabrielmoterani** [comment]
@Haraldson Did you know of any workaround to apply a radius to the top bar?
