### ISSUE TITLE
Using custom tooltip with onMouseMove in Line/Area/ComposedChart

### ISSUE THREAD

**Issue by jzaczek** [recharts/recharts#1305]
## Do you want to request a feature or report a bug?
Report a bug.

## What is the current behavior?
I've stumbled upon a problem described in: https://github.com/recharts/recharts/issues/991. Updating state in onMouseMove interferes with rendering custom tooltip component. JSFiddle below.

https://jsfiddle.net/nxr4gwkz/

Note that I've added both custom tooltip (simple div that displays payload) and onMouseMove. onMouseMove prevents tooltip from being rendered. 

## What is the expected behavior?

Tooltip is rendered and setState works properly when onMouseMove is set on Line/Area/ComposedChart

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

I've tested this only on Recharts version 1.0.0-beta.10.

**Comment by llamamoray** [comment]
@jzaczek I've just solved this by using the onMouseOver prop instead.

**Comment by llamamoray** [comment]
When using onMouseMove if you put a delay on the `setState` using `setTimeout` you momentarily see the custom tooltip so it's definitely the act of calling setState and the resulting render that is casuing the custom tooltip to not display. I've spent a few hours looking through and debugging the code but can't see the problem. My only suspicion is in the logic here:

https://github.com/recharts/recharts/blob/db0f3f254f12d59583052e77a43822163c476c9f/src/component/Tooltip.js#L83-L91

Do any of the maintainers have any ideas? I actually can't use my workaround of using onMouseOver as it only captures mouse overs of the Bars in my BarChart rather that the entire vertical space.

**Comment by jzaczek** [comment]
Thanks for the PR, but I'm still experiencing the same issue in my app. Which is weird, because the jsfiddle I've attached earlier that looks more-or-less like my app works fine:

https://jsfiddle.net/nxr4gwkz/5/

Do you have any suggestions? What I'm trying to achieve is to show both tooltip and activeLabel on the XAxis. JSFiddle works ok, while in my app I see only the activeLabel - tooltip is not showing.

**Comment by simonhessner** [comment]
I am still experiencing the problem in 1.8.5. Did you find a solution?

**Comment by jesperlandmer** [comment]
I am also experiencing this issue. Have you found a solution?
