### ISSUE TITLE
How to put custom texts to labels of Xaxis and Yaxis?

### ISSUE THREAD

**Issue by DmitryGG** [recharts/recharts#1306]
How can I add '%' to every label of YAxis? Thank you
I explored API but not found it...

<img width="419" alt="screen shot 2018-05-17 at 18 54 15" src="https://user-images.githubusercontent.com/25539852/40185605-058008b6-5a04-11e8-8e71-4991df70b505.png">

**Comment by LucasKr** [comment]
This can help [#838](https://github.com/recharts/recharts/issues/838)

```
<YAxis orientation="left" stroke="black" tickFormatter={(label) => `${label}%`}/>
```

**Comment by adnan2508** [comment]
what is Label?

**Comment by ckifer** [comment]
@adnan2508 not sure what you mean. In this case label is a parameter to the tickFormatter callback function that gives you the value of the tick
