### ISSUE TITLE
Broken website

### ISSUE THREAD

**Issue by abdulrahman-khankan** [recharts/recharts#1307]
## Do you want to request a feature or report a bug?
Report a bug
## Steps to reproduce
[http://recharts.org](http://recharts.org) works, after it loads, it redirects to [http://recharts.org/en-US/](http://recharts.org/en-US/) and from that point on, any URL will not work. i.e. Refresh and it is broken.
## What is the expected behavior?
• Doesn't break after refresh.
• Traversing to sub levels such as [http://recharts.org/en-US/examples/TwoLevelPieChart](http://recharts.org/en-US/examples/TwoLevelPieChart) works without having to go to the root and browsing my way from there.

**Comment by huei-tan-sociomantic** [comment]
ping @xile611

**Comment by hueitan** [comment]
I think this is high priority issue, this is annoying, @xile611 @arcthur can you work on this?

**Comment by hueitan** [comment]
I put the second comment here to let you know this is bad you didn't come and fix this.

**Comment by arcthur** [comment]
I fix the problem, but the url is http://recharts.org/#/en-US/, and not  http://recharts.org/en-US/

**Comment by abdulrahman-khankan** [comment]
@hueitan @arcthur @xile611 this issue is back. Please reopen until fixed.

**Comment by paulmelnikow** [comment]
It's working for me. Has someone already fixed it?

**Comment by abdulrahman-khankan** [comment]
@paulmelnikow it works, but any URL redirects always to http://recharts.org/en-US/
Try:
- http://recharts.org/#/en-US/
- http://recharts.org/#/en-US/examples/TwoLevelPieChart
- The link which you see if you navigate manually doesn't work if you refresh. Example: http://recharts.org/en-US/examples/TwoLevelPieChart

**Comment by paulmelnikow** [comment]
I’m able to navigate to the examples fine. However if I refresh or copy a link, it doesn’t have the hash and so doesn’t work.

As stated by OP:

> Refresh and it is broken.

Is that what you’re observing too?

**Comment by abdulrahman-khankan** [comment]
Yes exactly.

**Comment by rojasmi1** [comment]
Was this fixed? i believe you're missing the redirection rules in the .htaccess file, navigating from the home page works, but when I share a link from the samples page i.e. the page doesn't load and shows a 404 error.
