### ISSUE TITLE
Do we handle animation by hand?

### ISSUE THREAD

**Issue by xiaoyu-tamu** [recharts/recharts#1310]
## Do you want to request a feature or report a bug?

The animation behavior is unpredictable when I create a new Line  components dynamically. The existing <Line /> Components also get re-render and trigger animation.

Currently, I just use a variable store the last updated key and set isAnimationActive to false.

```
  renderLine = dataKey => (
    <Line
      key={dataKey}
      dataKey={dataKey}
      stroke={colors[dataKey]}
      type="monotone"
      isAnimationActive={dataKey === this.state.lastToggleKey}
    />
  );
```

Did I misunderstand something?

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
