### ISSUE TITLE
Horizontal bar chart does not working properly

### ISSUE THREAD

**Issue by Junbong** [recharts/recharts#1311]
I'm using rechart `1.0.0-beta.10`

#### Here's my code:
```jsx
import React from 'react'
import { BarChart, Bar } from 'recharts'

class ChartTest extends React.Component {
  render() {
    const data = [
      { name: 'a', foo: [-10, 10] },
      { name: 'b', foo: [-4, 8] },
      { name: 'c', foo: [0, 9] },
      { name: 'd', foo: [2, 15] },
    ]

    return (
      <BarChart
        width={500}
        height={100}
        data={data}
        layout="vertical">
        <Bar background label dataKey="foo" fill="#8884d8" />
      </BarChart>
    )
  }
}

export default ChartTest
```

#### And this code rendered as:
<img width="841" alt="2018-05-21 6 00 37" src="https://user-images.githubusercontent.com/6138662/40299350-f0f8c3e0-5d20-11e8-8cfa-0fa6bb5c8ef8.png">
As you see, not any bars are displayed.

#### But when I set `layout="horizontal"`
<img width="580" alt="2018-05-21 6 03 30" src="https://user-images.githubusercontent.com/6138662/40299491-5ab5867e-5d21-11e8-9852-b81380009b5a.png">

I need vertical bar chart.
What should I do??

**Comment by Helga108** [comment]
You gotta explicitly say which axis represents what. See a working demo with your data here: https://jsfiddle.net/kh8Ls7og/

**Comment by adriantoine** [comment]
And if you don't want the axis to show, you can use the `hide` property: https://codesandbox.io/s/n97xpmr464
