### ISSUE TITLE
Handle negative values on Scatter charts  

### ISSUE THREAD

**Issue by abdallahokasha** [recharts/recharts#1312]
Scatter doesn't handle negative values on x-axis, y-axis or both even using `domain={['auto', 'auto']}` or 
`domain={['dataMin', 'dataMax']}`
```
<XAxis dataKey='x' name={'Return'} domain={['dataMin', 'dataMax']} />                        
<YAxis dataKey='y' name={'Risk'} domain={['dataMin', 'dataMax']}  />
```
Question is how we can handle this ? .. thanks

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
