### ISSUE TITLE
Vertical bars always center-aligned in BarChart

### ISSUE THREAD

**Issue by hermos** [recharts/recharts#1313]
It does not seem to be possible to left-align the categories in BarChart when type=category. Please make this possible in order to improve the feasibility of Recharts being used in production environments.

Please consider the picture below:
![screen shot 2018-05-21 at 14 39 31](https://user-images.githubusercontent.com/4581544/40360788-e3be0ef6-5dcf-11e8-8788-2bf158a56c1d.png)

The two categories (2017, 2018) shown here should be positioned on the left side of the container instead of being aligned in the center.

**Comment by orrybaram** [comment]
@hermos I was able to hack a fix by filling the data set with empty values. It's not ideal but it works if you know the total amount of bars you want to display.

Here's an example
```jsx
const reportData = [{ count : 10}, { count: 4 }];
const data = new Array(12).fill({ count: 0 }).map((item, idx) => {
  if (reportData[idx]) {
    return reportData[idx];
  }
  return item;
});

<BarChart data={data}>
   <Bar barSize={15} dataKey="count" fill="#ada3c1" />
</BarChart>
```

**Comment by akshayhegde333** [comment]
any good solution introduced for this issue?

**Comment by milanpoudelwebdeveloper** [comment]
Hello has anyone found the solution for this?

**Comment by ckifer** [comment]
Here you are https://codesandbox.io/p/sandbox/simple-bar-chart-forked-6gqtw7

Make a custom bar shape which offsets left or right depending on the direction you want to go. As you can see it isn't perfect, the cursor now requires the same offset.
