### ISSUE TITLE
Documentation (examples) broken

### ISSUE THREAD

**Issue by rafaeldalpra** [recharts/recharts#1318]
This is not a bug in the library itself, but the documentation.

## Current behavior
Currently, on the examples page, if you click the `AreaChartConnectNulls` example , the page breaks and no other links work.
From console:
![image](https://user-images.githubusercontent.com/390641/40615327-3873b4fc-627e-11e8-8aa3-1a31c3e5609d.png)

## Expected behavior
Page should not break and the example should be shown.

If this is the wrong place for this, please advise.

🍻

**Comment by ppaul** [comment]
@rafaeldalpra , could you  please provide more context to reproduce the issue? I couldn't reproduce it on Chrome/Firefox on Linux. Thanks

**Comment by rafaeldalpra** [comment]
@ppaul I have tried to reproduce the issue now and it seems to be working correctly. Thanks for looking into it!
