### ISSUE TITLE
Fill AreaChart

### ISSUE THREAD

**Issue by ikrivosheev** [recharts/recharts#1319]
Hello, I have ReferenceLine and AreaCharts. How I can create linearGradient where vector is equal ReferenceLine?
![image](https://user-images.githubusercontent.com/6786239/40631860-5c30dad0-62e9-11e8-86ad-4f8405bd6f67.png)
```
<ResponsiveContainer width="100%" height={330}>
            <AreaChart data={data}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis
                tickFormatter={this.xAxisTickFormatter}
                ticks={dateRange(this.props.xAdomain, tick)}
                type="number"
                domain={this.props.xAdomain}
                dataKey="date"
              />
              <YAxis domain={[50, 250]} />
              <ReferenceLine y={border} stroke="red" />
              <Tooltip content={<CustomTooltip />} />
              <Area type="monotone" dataKey="pulse" fill="url(#splitColor)" dot={<CustomDot />} />
            </AreaChart>
          </ResponsiveContainer>
```

**Comment by ssotangkur-kahuna** [comment]
You might have to simulate it by creating a stacked area chart where you cap the data in one <Area> to  `border` (ie `Math.min(border, value)`) and provide the remainder in the other <Area> (ie `value > border ? value - border : 0`). Additionally you may have to set the type to `linear` so that the border is flat.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.

**Comment by radoo11** [comment]
@ikrivosheev have you done that case and you'd like to share the code?

**Comment by ckifer** [comment]
Try something like this

https://recharts.org/en-US/examples/AreaChartFillByValue

**Comment by ikrivosheev** [comment]
@radoo11 hello! I was 7 years ago, I don't remember. Sorry)
