### ISSUE TITLE
Enhancement in Pie chart

### ISSUE THREAD

**Issue by ycpatel813** [recharts/recharts#132]
Hi 
 
![chart](https://cloud.githubusercontent.com/assets/8921044/16487191/d6913c44-3ee6-11e6-8c71-b6abaeb208fa.png)

I am trying to create pie chart like uploaded image since 3 days but i did not get success so i want to ask that is it possible to create pie chart like uploaded image ???

**Comment by xile611** [comment]
@ycpatel813  You can use customized label to get what you want.

[example](http://jsfiddle.net/xcjLLuej/)

**Comment by ycpatel813** [comment]
@xile611 thanks for giving nice example
