### ISSUE TITLE
Export Chart

### ISSUE THREAD

**Issue by WaranchitPk** [recharts/recharts#1321]
Please. I want to export chart to .png or jpeg

**Comment by Francisjhacke** [comment]
Charts are built on top of SVG elements. That means you should be able to capture generated SVG and export to PNG/JPEG. 

This should be as simple as serializing the SVG, creating a blob, and then either saving to browser using something like Filesaver.js or saving server side with node.

**Comment by diegodebonis** [comment]
How could i implement the PNG export?

**Comment by DeividhyTonetti** [comment]
> Charts are built on top of SVG elements. That means you should be able to capture generated SVG and export to PNG/JPEG.
> 
> This should be as simple as serializing the SVG, creating a blob, and then either saving to browser using something like Filesaver.js or saving server side with node.
> 
> ```
> // Exports the graph as embedded JS or PNG
> exportChart(asSVG) {
> 
>     // A Recharts component is rendered as a div that contains namely an SVG
>     // which holds the chart. We can access this SVG by calling upon the first child/
>     let chartSVG = ReactDOM.findDOMNode(this.currentChart).children[0];
> 
>     if (asSVG) {
>         let svgURL = new XMLSerializer().serializeToString(chartSVG);
>         let svgBlob = new Blob([svgURL], {type: "image/svg+xml;charset=utf-8"});
>         FileSaver.saveAs(svgBlob, this.state.uuid + ".svg");
>     } else {
>         let svgBlob = new Blob([chartSVG.outerHTML], {type: "text/html;charset=utf-8"});
>         FileSaver.saveAs(svgBlob, this.state.uuid + ".html");
>     }
> }
> ```
> 
> Source: [javascript - Recharts component to PNG](https://stackoverflow.com/questions/45086005/recharts-component-to-png)


For me, it was the best solution! Before I used the recharts-to-png library, which converted the reacharts svg to a png and generated the export, but it took around 19.25s. With this solution the export dropped to just a few ms.

```
  const handleAreaDownload = () => {
    const element = ReactDOM.findDOMNode(referenceToSvgChart.current).parentNode;

    const svgURL = new XMLSerializer().serializeToString(element);
    const svgBlob = new Blob([svgURL], {type: "image/svg+xml;charset=utf-8"});
    
    saveAs(svgBlob,"Hello.svg");

  }
```
