### ISSUE TITLE
Axis breaks

### ISSUE THREAD

**Issue by llamamoray** [recharts/recharts#1323]
## Do you want to request a feature or report a bug?
Feature

## What is the current behavior?
I can't see if it's possible to have an axis break. E.g. https://en.wikipedia.org/wiki/Misleading_graph#/media/File:Y-axis_break.svg
![image](https://user-images.githubusercontent.com/2970147/40708698-01919958-63ec-11e8-8df3-7fae3476141c.png)

## What is the expected behavior?
Ability to configure an axis to break between values.

**Comment by hueitan** [comment]
no, it doesn't support this feature.

**Comment by astrofrans** [comment]
No plans on supporting this feature in future releases?
