### ISSUE TITLE
Create a scrollable legend

### ISSUE THREAD

**Issue by Norbo11** [recharts/recharts#1324]
I would love to hear some pointers on how I can go about creating a scrollable legend for my chart. I want to display a lot of lines on my graph (>50), and the current behaviour of the legend means that it becomes larger that the graph container and overlaps with everything above and below it. I would love for the legend to be able to take space, or to wrap it in a scrollable container. I have tried playing with `wrapperStyle={{position: 'relative'}}` but I don't think this is the intended use. I also tried creating a custom legend by passing in a `content` attribute, but this seems broken (`expected ReactElement, got function`, but the docs say that passing a function is allowed).

Any ideas?

**Comment by Norbo11** [comment]
I figured this out by using the `react-custom-scrollbars` package and creating a custom function to pass in to the `content` prop of a `Legend` component. You can use DeafaultLegendContent to keep the original recharts rendering and wrap it in your scrollbars:

```
import { Scrollbars } from 'react-custom-scrollbars';
import DefaultLegendContent from 'recharts/lib/component/DefaultLegendContent';

const scrollableLegend = (props) => {
    const newProps = {...props};
    newProps.layout = 'vertical';
    return (
        <Scrollbars
            style={{
                width: 'fit-content',
            }}
            autoHeight
            autoHeightMax={100}
        >
            <DefaultLegendContent {...newProps} />
        </Scrollbars>
    );
};

<Legend
  content={scrollableLegend}
>
```

It would be nice if this made it natively into recharts.

**Comment by brookjordan** [comment]
Why was this closed? I’d really like to be able to import `DefaultLegendContent`.

My use-case is to be able to render `DefaultLegendContent` into a React portal so it can be displayed elsewhere. I’ve gotten this working, but I’m having to add a type to `@types/recharts` and an export in `recharts/es6/index.js`

Is this not on the cards at all?

**Comment by siddhantsin** [comment]
You can still import it. Its just not a default export anymore for some reason. You can import it like so:
```import { DefaultLegendContent } from "recharts/lib/component/DefaultLegendContent";```
It is sort of unintuitive to import it this way and not as a default import because the name of the component is already in the path. I guess in one of the updates, it got changed from a default export to a named export?

**Comment by karthikkumar** [comment]
For simple scrollable `Legend`, appropriate props and `wrapperStyle` attributes do the job

```jsx
<Legend
  align="right"
  verticalAlign="middle"
  layout="vertical"
  wrapperStyle={{
    padding: '0 2rem',
    height: '80%',
    overflow: 'auto',
  }}
/>
```
