### ISSUE TITLE
Q: End of animaton event & transition

### ISSUE THREAD

**Issue by ppseprus** [recharts/recharts#1325]
Im developping a custom composed chart where I have reference dots around a line chart (..and some extra details). My issue is that all the custom dots appear instantly at the exact position where they should, however, the rest of the suff just ease in.
Is there a way to sync these?

Ive read back and forth the API docs, but I could not find anything.
Please help!

Thanks in advance!

**Comment by ppseprus** [comment]
A simplified demo for this question:
https://jsfiddle.net/pgz3uvLt/1/

**Comment by jrlimtiaco** [comment]
@ppseprus Did you find a solution?

**Comment by LR-brendan** [comment]
Old question, but you could try adding `isAnimationActive={false}` to your  `<Line/>`
This will mean both the line and the dot will just appear together (but not ease in).
