### ISSUE TITLE
Rendering LabelList with animation and two graphs on page doesn't work

### ISSUE THREAD

**Issue by nebojsanb** [recharts/recharts#1326]
The problem occurs when I place two graphs on one page and load data parallel for both.

Both graphs have animation on, and LablelList component with custom content (I don't think it is related to custom content).

When I load data to graphs, in most cases almost at the same time, animation for only one graph is started, and for that graph LabelList is shown. For other there was no animation and no LabelList.

If I resize the screen, which triggers re-rendering, both graphs start the animation and LabelList is shown for both.

Any ideas about this and is this recognised issue or I am doing something wrong?

Thank you.

**Comment by ShepelievD** [comment]
It is not related to the count of bars. I have the same issue.  `LabelList` is not being rendered at first render. I use `next.js` and `graphql`, I **disabled** server side render. @nebojsanb

**Comment by loopbender** [comment]
I have the same issue, two graphs on one page and LabelList doesn't render with first render. Any idea to solve this problem?

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
