### ISSUE TITLE
Adding unit to YAxis makes some ticks disappear

### ISSUE THREAD

**Issue by mpodlasin** [recharts/recharts#1328]
## Do you want to request a feature or report a bug?

A bug. Possibly same issue causes: #1263 

## What is the current behavior?

Adding unit property to `YAxis` makes one tick disappear

![screenshot from 2018-06-05 08-47-11](https://user-images.githubusercontent.com/7916523/40959582-5aa766ac-689d-11e8-85a1-aa3651b958ec.png)
![screenshot from 2018-06-05 08-47-31](https://user-images.githubusercontent.com/7916523/40959584-5e66e8b2-689d-11e8-8274-fa2481d85795.png)

## What is the expected behavior?

Since unit of tick is just a presentational addition, it should not interfere with any logic - in that case, how many ticks are displayed to user.

**Comment by m1chah** [comment]
Same here. Highest value is a little below the tick line, maybe there is a connection?

**Comment by lwjameson** [comment]
I had a similar issue.  After tracing through some code I was able to restore lost ticks by specifying an interval of 0 on my Axis.  The function in question is getTicks. 

https://github.com/recharts/recharts/blob/master/src/cartesian/CartesianAxis.js#L80
