### ISSUE TITLE
Missing ticks on x-axis

### ISSUE THREAD

**Issue by farhan-sauce** [recharts/recharts#1330]
## Do you want to request a feature or report a bug?
Probably Bug

## What is the current behavior?
Chart miss first tick for small devices

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal 
[JSFiddle demo](https://jsfiddle.net/9y60fdsk/)

## What is the expected behavior?
Start and End ticks should not be missed.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Latest version, Chrome MacOS

**Comment by ppseprus** [comment]
The chart is intelligent enough to see if there will be no space for the labels on the axes to show. When this happens, since the labels are bound to the ticks (or something) the disappear. This is why you dont see the ticks, the labels and the grid lines.
Try setting the label size smaller and you will see the difference.

**Comment by ppseprus** [comment]
I've removed "point" from the labels and changed the font-size to 12px...
https://jsfiddle.net/9y60fdsk/2/

**Comment by farhan-sauce** [comment]
Hi @ppseprus 
Thanks for reply, I am using `date time` as my x-axis value, that's why start and end tick labels are very important, is there any way to forcefully show start and end label? I am fine if some other ticks/labels will be missed.

my chart x-axis 

![screen shot 2018-06-05 at 3 04 08 pm](https://user-images.githubusercontent.com/39295560/40969742-55d0c734-68d6-11e8-89ad-4f39aca8991b.png)


Here other tick label doesn't make any sense without first label.

**Comment by farhan-sauce** [comment]
@ppseprus Thanks for solution jsfiddle,

But I am following theme so, can't reduce font-size or trim text from first and last labels,
Please let me know if there is anyway to enforce first and last label in chart.

**Comment by ppseprus** [comment]
Well, Im not part of this project. Im just waiting for an issue to be solved..
However, what I can say is that this is not an issue. This is a workaround so that svg labels are not rendered on top ov eachother. I dont think you can enforce it.
You could to something like makng the minutes part smaller than the hour part, and also Nov-11 0:20 ccould be just Nov-11...
I hope that helps...

**Comment by farhan-sauce** [comment]
Thanks for trying to help,

I am still waiting for the answer from contributor or I can implement this feature and create PR if Repo owner is willing to merge this feature.

**Comment by ppseprus** [comment]
Hey @farhan-sauce!
Axes have a `minTickGap` set to 5. I assume pixels. Try setting that to 0.. or even a negative number!
Regards,
P.

**Comment by uyuarasy** [comment]
Any news on this? I have a LineChart in a ResponsiveContainer and if I render every tick's label with _interval={0}_, the labels overlaps on small window size.
<img width="573" alt="screen shot 2018-10-05 at 22 48 39" src="https://user-images.githubusercontent.com/5305557/46559501-dbcab000-c8f0-11e8-83bb-426efa8e3c86.png">

With the other options (preserveStart, preserveEnd, preserveStartEnd) I got another issue. Sometimes one label is missing and the spacing looks bad:
<img width="568" alt="screen shot 2018-10-05 at 22 19 01" src="https://user-images.githubusercontent.com/5305557/46559772-a07cb100-c8f1-11e8-9143-01800ea1a541.png">

**Comment by saranshbansal** [comment]
This is really annoying. Why not add a word wrap property on these labels? I believe this shouldn’t be that hard. It’s a very basic requirement. What’s the point of showing charts if we don’t know what it represents?

As someone mentioned that the labels are svgs, I don’t understand the point of using SVGs here. 
Please fix this issue.

**Comment by danedavid** [comment]
I think we can add a prop `forceTicks` that will show the ticks, no matter if the style breaks. So after that it can be user's concern whether to show or hide them.

**Comment by Temuchin26** [comment]
I found solution in the docks, if you set interval on XAxis to 0, then all ticks will be displayed
`<XAxis
                    dataKey="name"
                    tick={<CustomizedAxisTick />}
                    height={200}
                    interval={0}
                />`

**Comment by collinewait** [comment]
> I found solution in the docks, if you set interval on XAxis to 0, then all ticks will be displayed
> `<XAxis dataKey="name" tick={<CustomizedAxisTick />} height={200} interval={0} />`

This worked for me.

**Comment by kmayur35** [comment]
tick={{ fontSize: '10px', width: '50px', wordWrap: 'break-word' }}

use this in <Xaxis />

it worked for me.

**Comment by jabberwo** [comment]
Ticks still missing if you are trying to plot time series with gaps between data points.

**Comment by zotijs** [comment]
> tick={{ fontSize: '10px', width: '50px', wordWrap: 'break-word' }}
> 
> use this in
> 
> it worked for me.

this solution with `interval={0}` worked for me

**Comment by rjattrill** [comment]
I have seen the same thing on the y-axis.  Setting `interval=0` fixed it - I will raise an issue.

**Comment by elliotaplant** [comment]
I found that `<XAxis interval="preserveStartEnd"` /> worked for me. Setting `interval={0}` displayed all the ticks but cut off the begginning/end of the first/last ticks.

**Comment by franfj** [comment]
> Ticks still missing if you are trying to plot time series with gaps between data points.

Any solution to this issue? Thanks!

**Comment by sgleong** [comment]
I'm having a problem with only every other tick showing even when ticks is defined and `interval={0}`. Changing interval seems to do nothing. I'm wondering if it's a particular problem with `scale='time'`. I have a custom tick function and only every other tick value hits that function at all. Any ideas?

**Comment by yuikoito** [comment]
``interval={0}`` works for me! Thank you.

**Comment by Sotatek-ThuyetNguyen** [comment]
`interval={0}` work for me

**Comment by Kitketovsky** [comment]
I encountered the same problem and after a lot of experimenting I noticed that Recharts calculates width of a tick somewhat before rendering it. It means, that if you do the following:
` 
const data = [{ date: new Date(), value: Math.random() }, { date: new Date(), value: Math.random() } ... ]
`

`
<XAxis dataKey="date" tick={<YourCustomTickWithCustomStyling />} />
`
...the width of one tick will be calculated based on how much space would "Tue Sep 13 2022 16:10:52 GMT+0500" take ("date" in "data"). It doesn't matter if you format the date in your custom tick component so it looks smaller (e.g. 13/09), it will take initial full width.

**Solution**: 
Try to style the tick as much as possibe "vanilla" way and use `tickFormatter` function. The width of a tick will be calculated after this function.

**Comment by jasoncarrillo0** [comment]
`interval={0}` worked great for keeping the lines from disappearing.
To achieve the word-wrap feature, create a custom tick with the fontSize and width property the same. It doesn't respond to changes it seems in the browser console, but works if you re-render your component.


const CustomXAxisTick = ({ x, y, payload }: any) => {
    if (payload && payload.value) {
      return (
        <Text
            fontSize={"12px"}
            width={"12px"}
            x={x} 
            y={y} 
            textAnchor="middle" 
            verticalAnchor="start"
        >{payload.value}</Text>
      );
    }
    return null;
};
<XAxis interval={0} tick={<CustomXAxisTick/>} dataKey="name" />
`

**Comment by RedirexStudio** [comment]
> I found solution in the docks, if you set interval on XAxis to 0, then all ticks will be displayed

Thank you very much! It's work for me!
