### ISSUE TITLE
The positioning of the Tooltip lags under IE 11

### ISSUE THREAD

**Issue by ppseprus** [recharts/recharts#1331]
## Do you want to request a feature or report a bug?
I beleive this is a bug, however, I'm not entirely sure it is with Recharts.

## What is the current behavior?
The positioning of the Tooltip component lags under IE 11. Especially when the mouse moves slowly.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
https://jsfiddle.net/alidingling/xqjtetw0/
This is the original demo linked under simple line charts.

## What is the expected behavior?
To work as smoth as it does under Chrome 67.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
recharts@1.0.0-beta.10
IE 11.431.16299

**Comment by waltersjack** [comment]
Same issue in Edge and see with example provided

**Comment by fgkolf** [comment]
The animation of the tooltip seems to be the problem, if you use a browser detection library you can disable the animation in internet explorer and edge by setting the isAnimationActive property (http://recharts.org/en-US/api/Tooltip#isAnimationActive ) of the tootltip  to false.

If your target browser is one of those you can disable it unconditionally.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
