### ISSUE TITLE
hope have a way to dynamic calc pie radius

### ISSUE THREAD

**Issue by Kingwl** [recharts/recharts#1334]
## Do you want to request a feature or report a bug?
feature request 

## What is the current behavior?
pie chart only accept fixed radius: string or number
but i(we) need calculate ~the fucking~ radius dynamic with value
eg: wind rose chart

## What is the expected behavior?
radius props could accept a callback that return the dynamic radius

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

latest

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
