### ISSUE TITLE
Reference Area should still cover area, when x/y values outside of axis domain

### ISSUE THREAD

**Issue by faeron** [recharts/recharts#1335]
## Do you want to request a feature or report a bug?
Probably a bug. Related to #847

## What is the current behavior?
The reference area is only drawn if both y-values are in range of the y-Axis domain.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

Set any x/y value outside of (internally calculated) axis domain.
Here a sample I borrowed and updated from #847:
https://codesandbox.io/s/m72oxy7oqy

## What is the expected behavior?
I would expect, that even if I set the y2 value outside of that domain, that the reference area will adapt and still render, but with the upper/lower y-value set to the min/max values of the y-Axis domain.

Of course only when I let the recharts components calculate everything internally. 

#931 is part of the solution, because now I can omit x values, as it should span the full x range.

If that is the desired behavior for ReferenceArea, I think the fix would be to check in https://github.com/recharts/recharts/blob/master/src/cartesian/ReferenceArea.js#L69-L91 first if the values are in their respective axis domain, before scaling them. If not, use the max/min value of that domain instead of the scaled one.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

- recharts v1.0.0-beta10
- Affected should be all browsers and OS. 
-  Did never work afaik.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
