### ISSUE TITLE
ReferenceLine (for y-axis) with Biaxial (y-axes)

### ISSUE THREAD

**Issue by tallx** [recharts/recharts#1336]
How-To?

With Biaxial (left & right y-axes), how to use ReferenceLine for left y-axis?

**Comment by faeron** [comment]
The reference line has a property yAxisId that tells it to use the data of specified Axis http://recharts.org/#/en-US/api/ReferenceLine
So give your y-axis an yAxisId and use it for the reference Line.

I just added a reference line for the left y-axis to the biaxial demo
https://jsfiddle.net/alidingling/zjb47e83/

**Comment by tallx** [comment]
Thanks for your help! I completely missed yAxisId.
