### ISSUE TITLE
Dynamic isAnimationActive flag exhibits odd behaviour

### ISSUE THREAD

**Issue by pojka** [recharts/recharts#1337]
## Do you want to request a feature or report a bug?

Bug

## What is the current behavior?

If I switch a Bar or Area (possibly other components too) `isAnimationActive` flag on an existing component, some settings appear to be stored.

Our use case is that we want to disable animations on our responsive components on resize, this works great until the next setState occurs, but when it does, the charts jump to the prior end state of an animation (the state prior to resize) and then animate from there to the current dimensions

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

Will update this issue with a demo once I get a chance

## What is the expected behavior?

Toggling `isAnimationActive` from `false` to `true` on an existing component reinitialises the settings to the current state so an animation does not occur.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Version - 1.0.0-beta.10
Browsers - Chrome and Safari (possibly more)
Did this work in previous versions - Unknown

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by wmy94827** [comment]
+1
