### ISSUE TITLE
How to apply word wrap for text in pie chart?

### ISSUE THREAD

**Issue by NilapuAnusha** [recharts/recharts#1339]
Please refer
https://jsfiddle.net/alidingling/hqnrgxpj/

How to apply word-wrap for text
![image](https://user-images.githubusercontent.com/8502891/41340309-b2415602-6f14-11e8-8c75-66649f79f2f4.png)

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by wellyal** [comment]
Why was this closed?
