### ISSUE TITLE
Why is `cursor: default` set as an inline style that cannot be overridden?

### ISSUE THREAD

**Issue by Vazerthon** [recharts/recharts#1340]
## Do you want to request a feature or report a bug?

Report a bug / as a question

## What is the current behavior?

Charts set `cursor: default` as an inline style that is difficult to override

##  minimal demo

https://repl.it/repls/PastelProfuseTree
Chart has `style={{ cursor: 'pointer' }}` set but default cursor is shown.
https://github.com/recharts/recharts/blob/master/src/chart/generateCategoricalChart.js#L1501 shows where the default value is set.

## What is the expected behavior?

Users should be able to set whatever styles they like. 
Changing the line linked above to spread `...style` _after_ the defaults would allow this.
`style={{ position: 'relative', cursor: 'default', width, height, ...style }}`

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

1.0.0-beta.10 for sure. Possibly others. All browsers.

**Comment by kiranvj** [comment]
Setting cursor props should work 
`
<LineChart width={100} height={25} data={data} cursor="pointer">`

**Comment by sha237gh** [comment]
This doesn't work for me, I am using a `Pie` chart

**Comment by agos** [comment]
> Setting cursor props should work ` <LineChart width={100} height={25} data={data} cursor="pointer">`

this is not reflected in the types for `LineChart` and albeit it works it won't pass type checking
