### ISSUE TITLE
JSFiddle contains incorrect prop for Treemap - ratio vs. aspectRatio

### ISSUE THREAD

**Issue by mjoyce91** [recharts/recharts#1343]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
Jsfiddle code for both Treemap examples in the documentation use the prop `ratio` when the actual prop is `aspectRatio`.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
1. Click "Try the demo in jsfiddle" for these links:
http://recharts.org/#/en-US/examples/SimpleTreemap
http://recharts.org/#/en-US/examples/CustomContentTreemap
2. Compare the `ratio` prop used to documentation at http://recharts.org/#/en-US/api/Treemap

## What is the expected behavior?
Jsfiddle example should use the `aspectRatio` prop to avoid confusion.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Not browser-specific.

**Comment by ferristocrat** [comment]
+1

**Comment by xile611** [comment]
Fixed
