### ISSUE TITLE
RadialBar Label does not update after data update

### ISSUE THREAD

**Issue by oasisvali** [recharts/recharts#1344]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
The label on a radial bar does not update after the underlying data passed to the chart is updated

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
https://jsfiddle.net/z9Lcb2da/2/

## What is the expected behavior?
The state update triggered by the setTimeout causes the switch to the new data object, which should show a different label for the innermost radial bar (55.47), but the label remains the same (31.47)

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Reproduced with recharts beta v10

**Comment by xile611** [comment]
It works in the latest version
