### ISSUE TITLE
Interactive Reference Lines

### ISSUE THREAD

**Issue by kevinxia787** [recharts/recharts#1345]
## Do you want to request a feature or report a bug?
Request a feature
## What is the current behavior?
Would like to see if there is a way to make reference lines interactive - dragging across a line chart for example
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
n/a
## What is the expected behavior?
n/a
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
n/a

**Comment by waltersjack** [comment]
Would also be nice to be able to add a tooltip to reference lines and reference dots

**Comment by sadia-onyxtec** [comment]
@kevinxia787, Can you please share a demo or code-pen repo?
