### ISSUE TITLE
Legend component triggers immediate reflow upon componentDidMount, breaking compatibility with react-transition-group

### ISSUE THREAD

**Issue by mindnektar** [recharts/recharts#1347]
## Do you want to request a feature or report a bug?

Bug

## What is the current behavior?

I have implemented a slideshow using react-transition-group, with each slide containing a different chart rendered by recharts. Whenever a slide appears containing a chart with a Legend component, the enter transition does not work. This is because the Legend component re-renders immediately after componentDidMount, which interferes with the internal workings of the CSSTransition component from react-transition-group. It is possible that other recharts components do the same thing, but I haven't come across any yet.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

Here is a breakdown of the issue on the react-transition-group repository: https://github.com/reactjs/react-transition-group/issues/10

react-transition-group is the de-facto leading tool for transitions in react. They seem to be aware of the general issue, but as of yet no solution exists, and they suggest not to cause immediate reflows within CSSTransition children.

## Proposed solution

Rather than directly calling `this.updateBBox()` in componentDidMount, you might consider calling it in a requestAnimationFrame callback instead. Doing this fixes the issue for me. Unfortunately, I don't know if this might cause problems elsewhere within recharts. Would this be a reasonable solution for you? If not, do you have any other ideas?

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by the-nemz** [comment]
Hi @xile611, I am using the latest version (2.1.16) and am still seeing this issue. What version was the patch released in? I also experienced the issue on version 1.8.5.
