### ISSUE TITLE
ResponsiveContainer doesn't render

### ISSUE THREAD

**Issue by nickstanish** [recharts/recharts#135]
On IOS 8.3 the AreaChart does not render if it is within a ResponsiveContainer. Used the example from the docs. http://jsfiddle.net/znqLLdev/1/

Removing ResponsiveContainer and adding width/height props to AreaChart renders successfully.

**Comment by xile611** [comment]
@nickstanish Can you provide any logs?

**Comment by xile611** [comment]
@nickstanish  Can you show more about the browser you used ? And how about the version of browser?

**Comment by nickstanish** [comment]
@xile611 There were no console logs. Browser is mobile safari. Tried iOS simulator with ios8.3, and tried an iPhone 4 with ios 6. However, IOS 8.4 simulator worked fine.

This may have to do with how safari is handling the dimensions of the parent element.

**Comment by xile611** [comment]
@nickstanish  Do you know the version of safari in ios8.3?

**Comment by xile611** [comment]
![image](https://cloud.githubusercontent.com/assets/6111424/16608715/adea4418-4380-11e6-93fb-4a754bf1c463.png)
![image](https://cloud.githubusercontent.com/assets/6111424/16608734/ef42c61a-4380-11e6-9b1b-291fd5663901.png)


@nickstanish It works fine in my ios8.3 simulator. 

![image](https://cloud.githubusercontent.com/assets/6111424/16608789/601b9916-4381-11e6-9da6-93cf0a4fc724.png)

And it seems no ios6 simulator in xcode now.

**Comment by nickstanish** [comment]
@xile611 Safari version on io8.3 simulator is the same as yours. Strangely enough, it renders some times but not every time. The axes are there though.

![image](https://cloud.githubusercontent.com/assets/1869157/16621983/e9e01a1a-435d-11e6-8b91-a00cf92299d4.png)

**Comment by nickstanish** [comment]
Discovered the issue while using it with ReactBootstrap tabs which hide/show content depending on which tabs are selected, and then I went back to the recharts website to see if they worked there. The navigation needs some work on mobile, but I tried a direct link to the responsive container examples and the jsfiddles. The axes and gridlines would appear despite the area not appearing. 

In my case, the charts wouldn't render at all, until I forced the tabs component to remove the nodes from the dom. It seems that react-container-dimensions was getting 0 for the dimensions of the parent element despite the styles being set to 100%, and then didn't trigger an update as the visibility changed. That doesn't appear to be the case with the jsfiddle though since the axes and gridlines are there.

**Comment by xile611** [comment]
@nickstanish How about the version of Recharts? The problem of AreaChart in ios8.3 seems to be the bug of Animation. And your case seems to the the bug of react-container-dimensions or the style of parent node. Please check the size of parent node. And If possible, you can create an example of your case in jsfiddle. Then we can find the bug easier.

**Comment by joshburgess** [comment]
I'm having this exact problem right now in a react/redux/react-router app. Any charts wrapped in a responsive container won't render at all on first load... It has to be some kind of timing issue with the route switching and the responsive container not being able to read the height of the parent correctly. It works fine if I resize the window immediately after page load... but it just won't load anything otherwise. Kinda makes it unusable in its current state :/

**Comment by xile611** [comment]
@joshburgess  Can you describe your question in a simple project that we can have access to ?

**Comment by joshburgess** [comment]
@xile611  I'll try to put something together when I get some time.

**Comment by xile611** [comment]
@joshburgess OK! It's helpful for us to find the problem.

**Comment by sebinsua** [comment]
`ResponsiveContainer` fails for me if I place it in a container with `height: 100%`.

**Comment by nickpalmer** [comment]
I am having the same problem with ResponsiveContainer and react-router. The container is set to a height of 100%, but there is other content above and below the chart and so the browser is happy to squish the div to zero height because there is no content in it. The SVG doesn't render because the div has zero height and thus the container never gets any height and the SVG never can render. I have to set a height on the container to get it to render, but then it isn't really responsive in terms of changes in width shrinking the height. Also when it gets narrow the SVG is cropped instead of scaling in both height and width.

Why not use a different technique for scalable SVGs? In particular I am used to specifying the desired aspect ratio of the chart using the viewBox and then scaling that using an <object> tag. One could also use the padding-bottom hack if you object to the <object> tag method. See here for a discussion of techniques for scaling them without the use of javascript:

https://css-tricks.com/scale-svg/

I will look to put a pull request together today that uses this technique in conjunction with the ability to pass down a viewBox. It seems Surface supports the viewBox but charts (like PieChart) don't allow it to be specified and passed to the Surface. They are just taking height and width parameters, which are useful but specify the aspect ratio of the container not the chart.

Thoughts?

**Comment by joshburgess** [comment]
Sorry, I was never able to put something together. I ended up removing recharts from the project & using a different charting library due to bugs like this & having very limited time to get things done. FWIW, this chart is now using react-highcharts, and it doesn't have the same issue w/ react-router + velocity-react being used for transitions. I agree with @nickpalmer that there is probably a better way to approach the problem.

**Comment by nickpalmer** [comment]
Here is a fiddle with the problem I am having:

http://jsfiddle.net/d0k0rk0m/

**Comment by xile611** [comment]
@nickpalmer  
We have discussed these two kinds of responsive strategies. Take the display of texts as an example.

The original size:
![image](https://cloud.githubusercontent.com/assets/6111424/17723347/fb5ddab4-646b-11e6-82ae-1fe10aaecb56.png)

Larger size and more space to display texts (The responsive strategy we adopted now) :
![image](https://cloud.githubusercontent.com/assets/6111424/17723356/12fc9ac0-646c-11e6-9619-7225919f2920.png)

Larger size and larger texts (scalable SVGs):
![image](https://cloud.githubusercontent.com/assets/6111424/17723418/931bdcb6-646c-11e6-8512-223d1e53f125.png)

And we think this first responsive strategy is now more widely used.

**Comment by xile611** [comment]
@nickstanish  
Although I don't exactly know what is your demand. But your problem can be solved by setting the height of "content" node to be `100%`;
```
.content {
  height: 100%;
  min-height: 500px;
}
```
<http://jsfiddle.net/d0k0rk0m/2/>

**Comment by nickstanish** [comment]
@xile611 
Sorry I haven't had a chance to create a jsfiddle for it. 

In my case the issue was that the chart wouldn't render on ios 8 at all when used with react-router and tabs through react-bootstrap. However I was able to fix the issue by forcing the react-bootstrap tabs to remove the tab's content (including the chart) so that the chart is re-rendered and the height is correct. It seems that react-container-dimensions doesn't respond to the way react-bootstrap hides/shows the tab content by default without a re-render. 

In the process of debugging that issue, I found the issue on the recharts jsfiddle where sometimes when refreshing the axes would be visible and correct height but area chart would not be visible.

**Comment by joshburgess** [comment]
@nickstanish sounds very related to the problem I was having with react-router & velocity-react. In my case, elements were hidden as velocity-react transitioned them into view (animation). The responsive container seems to have problems with calculating proper values in scenarios where there are hidden parent elements.

**Comment by nickpalmer** [comment]
@xile611 Forcing users of the library to set heights on all elements of the tree that leads to a responsive graph really lowers usability. Most developers are used to just placing elements and allowing the browsers render engine to sort out the required height to contain the content.

I think the main problem is that ResponsiveContainer doesn't render anything if the height or width are zero. It just returns null. Maybe defaulting to some minimum height or width would be better?

**Comment by nickpalmer** [comment]
An additional idea would be to set an aspect ratio on ResponsiveContainer and if one of the measures is zero then use the aspect ratio and the other to come up with the initial size.

**Comment by nickpalmer** [comment]
Something like this:
https://github.com/nick-codes/recharts/commit/0d66374ee06db2c498b458e686f7815e7807c4be

Thoughts?

**Comment by nickstanish** [comment]
@nickpalmer What if you use `Math.max` along with the calculatedWidth/calculatedHeight so that percentages are still supported? Maybe aspect should be optional.

**Comment by xile611** [comment]
@nickstanish @joshburgess It seems to be the problem of calculating width and height for hidden parent! Thank you! I'll try to find the reason.

**Comment by xile611** [comment]
@nickpalmer 
I don't mean to force users of the library to set heights on all elements of the tree. But if someone want to set the height of a node to be a relative value (a percent value), then one of its ancestor node should have  a absolute height.
 
And it's a good idea to an option of  aspect ration. And the aspect and minHeight, minWidth should be optional, meanwhile `width` and `height` need to be retained. what @nickstanish has said is a good advice.

**Comment by nickpalmer** [comment]
Second pass:
https://github.com/nick-codes/recharts/commit/839506e318b880f955db21800217b58f0cb83f19
Feel free to comment on the commit as well.

If this is more like what you would accept I will add some tests around it and submit a PR.

**Comment by xile611** [comment]
@nickpalmer PR is welcome.

I have submitted some comments. Hope useful to you.

**Comment by xile611** [comment]
@nickpalmer 
I think this issue has been fixed. Thank you very much!

@nickstanish @jasonslyvia 
<http://jsfiddle.net/k14xykqv/1/> and <http://jsfiddle.net/k14xykqv/> are two examples of ResponsiveContainer used with react-bootstrap which specify the aspect of ResponsiveContainer or specify the height of `.tab-pane`.

**Comment by jasonslyvia** [comment]
Awesome!

**Comment by SachaG** [comment]
I feel like I'm running into a similar issue. This renders fine:

```
<BarChart width={600} height={400} data={data} barCategoryGap="30%" margin={{top: 75, right: 30, left: 20, bottom: 5}}>
          <Bar className="not-interested" isAnimationActive={false} dataKey="I've heard of it, and am not interested" stackId="a" fill={fills.notInterested} />
          <Bar className="never-heard" isAnimationActive={false} dataKey="I've never heard of it" stackId="a" fill={fills.neverHeard} />
</BarChart>
```

But if I wrap the block in `<ResponsiveContainer>`, it stops rendering. Am I missing something?

**Comment by SachaG** [comment]
It turns out that ResponsiveContainer doesn't work when the inner component has a `height` and width`. This makes sense I guess, but maybe something about it could be added to the docs, if that's the expected behavior?

**Comment by xile611** [comment]
@SachaG Yeah, it's the expected behavior. We'll add this in the document.

**Comment by harshjv** [comment]
Still not working for me :/ (Safari 9.3.1 & Chrome 52)

    import React from 'react'
    import { AreaChart, ComposedChart, Line, Area, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts'

    import Navbar from './common/Navbar.jsx'

    const data = [
          {name: 'Page A', uv: 4000, pv: 2400, amt: 2400},
          {name: 'Page B', uv: 3000, pv: 1398, amt: 2210},
          {name: 'Page C', uv: 2000, pv: 9800, amt: 2290},
          {name: 'Page D', uv: 2780, pv: 3908, amt: 2000},
          {name: 'Page E', uv: 1890, pv: 4800, amt: 2181},
          {name: 'Page F', uv: 2390, pv: 3800, amt: 2500},
          {name: 'Page G', uv: 3490, pv: 4300, amt: 2100}
    ]

    export default class App extends React.Component {
      render () {
        return (
          <div className='react-wrapper'>
            <Navbar />
            <div className='container'>
              <ResponsiveContainer>
                <AreaChart data={data}>
                  <XAxis dataKey='name' />
                  <YAxis />
                  <CartesianGrid strokeDasharray='3 3' />
                  <Tooltip />
                  <Area type='monotone' dataKey='uv' stroke='#8884d8' fill='#8884d8' />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          </div>
        )
      }
    }

**Comment by nickpalmer** [comment]
Add an aspect to the ResponsiveContainer to resolve the issue. When embedded in a zero height container it needs an aspect to determine the height based on the width.

**Comment by meatnordrink** [comment]
A note for others who might encounter this problem - even with an aspect (height and width values), the `<ResponsiveContainer>` needs to be *within an element with a fixed size.* In other words, it needs to be wrapped within a parent element with a fixed height/width of its own. (Just having fixed-size elements higher in the tree doesn't necessarily do it, I think; I suspect it needs to be in the module the chart is in.)

**Comment by nayebare** [comment]
Thank you for this question. I think you need a div wrapper around the ResponsiveContainer like this.
<div className="wrapper">
<ResponsiveContainer width="100%" height="100%">
</ResponsiveContainer> 
</div>
.wrapper{
  position:relative;
    height:600px !important;
    width:100%;
}

**Comment by SirPm** [comment]
This still doesn't work for me at all, this is my code snippet
<div className="overview-analytics ">
   <ResponsiveContainer width="100%" height="600" >
				<LineChart
					width={500}
					height={300}
					data={data}
					className="overview-analytics-chart"
				>
					<CartesianGrid strokeDasharray="3 3" />
					<XAxis dataKey="name" />
					<YAxis />
					<Tooltip />
					<Legend />
					<Line type="monotone" dataKey="pv" stroke="#8884d8" activeDot={{ r: 8 }} />
					<Line type="monotone" dataKey="uv" stroke="#82ca9d" />
				</LineChart>
			</ResponsiveContainer>
</div>

I've given the outer div a fixed width and height, still it just shows an empty graph and my react app becomes unresponsive and I get in the console "Uncaught RangeError: Maximum call stack size exceeded". The moment I remove the responsiveContainer everything works normally. And I've tried removing the width and height from the LineChart, and added aspect to the ResponsiveContainer but the moment I put back the ResponsiveContainer my app becomes unresponsive and unclickable
