### ISSUE TITLE
How to mark point for highest and lowest value

### ISSUE THREAD

**Issue by edwardfhsiao** [recharts/recharts#1350]
## Do you want to request a feature or report a bug?
feature
## What is the current behavior?
no mark point for highest and lowest value
## What is the expected behavior?
![image](https://user-images.githubusercontent.com/11728228/41636337-6e9cbd26-7480-11e8-9bba-ef0ee667e31d.png)

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
    "recharts": "^1.0.0-beta.10",
osx

**Comment by albinekb** [comment]
Use [ReferenceLine](http://recharts.org/#/en-US/api/ReferenceLine)


```js
    <ReferenceLine y={4000} label="Max" stroke="#ccc" strokeDasharray="3 3" />
```

Replace 4000 with your max value.

**Comment by edwardfhsiao** [comment]
thanks man

**Comment by edwardfhsiao** [comment]
@albinekb  thanks man
