### ISSUE TITLE
Render/style null values on an area chart

### ISSUE THREAD

**Issue by nhpace** [recharts/recharts#1355]
## Do you want to request a feature or report a bug?
Feature

## What is the current behavior?
No way to style null values

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Would like to render null values like this:

<img width="234" alt="add null data styling to chart widget clubhouse 2018-06-22 13-46-26" src="https://user-images.githubusercontent.com/4217759/41791087-ac34390e-7622-11e8-8adb-668aa99a62fb.png">

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
