### ISSUE TITLE
Question : make a chart responsive = fit parent div

### ISSUE THREAD

**Issue by Aarbel** [recharts/recharts#1357]
Hi Rechart teams,

how difficult could it be to make your charts UI-responsive and adapt to parent div size, or maybe page size ?

Thanks a lot !

**Comment by FerusAndBeyond** [comment]
You could do it yourself by calculating window.innerWidth after each componentDidUpdate

**Comment by Aarbel** [comment]
It's easy

**Comment by ShinHyunJong** [comment]
@Aarbel Hi! Aarbel Could you pls tell me how did you solve the problem? I am struggling with responsive issue too! thanks a lot!
