### ISSUE TITLE
Why does my axis ticks are hidden ?

### ISSUE THREAD

**Issue by lucasriondel** [recharts/recharts#1360]
I am creating a simple chart with this data : 

```
const data = [
      {
        label: 'somethingA',
        values: [
          { x: 0, y: 0 },
          { x: 1, y: 1 },
          { x: 2, y: 3 },
          { x: 3, y: 4 },
          { x: 4, y: 3 },
          { x: 5, y: 4 },
          { x: 6, y: 5 }
        ]
      }
```

```
                <ResponsiveContainer width="100%" height={150}>
                  <LineChart data={data} margin={{ top: 5, right: 20, left: 20, bottom: 5 }}>
                    <XAxis />
                    <YAxis />
                    <Tooltip />
                    <CartesianGrid stroke="#f5f5f5" />
                    <Line type="monotone" dataKey="uv" stroke="#ff7300" yAxisId={0} />
                    <Line type="monotone" dataKey="pv" stroke="#387908" yAxisId={1} />
                  </LineChart>
                </ResponsiveContainer>
```

And my chart is correctly displayed, even though i don't why (because there's no uv property in my data array). 

But this is what is displayed to me : 

https://i.imgur.com/cm6UfVs.png

As you can see, the right value is in the dom, but not displayed on my browser.

Does someone have a clue ?

**Comment by kevinxia787** [comment]
Your data is formatted incorrectly; should be formatted as a sole array of objects.

The XAxis component also needs a prop called "dataKey" for the axis to show. Here is a fiddle:

https://jsfiddle.net/21vytmw3/2/

Issue can be closed.

**Comment by lucasriondel** [comment]
@kevinxia787 thank you for your answer, i am going to fix my code. 

but it feels weird though ! why can't the X axis figure out by itself what to display ? i mean, i am using numbers...

**Comment by kevinxia787** [comment]
Not sure why XAxis requires a dataKey prop but my guess is since in D3 you have to format your axis with various scales you need the dataKey to access the value - but anyways, glad I could help - look at the recharts API for more information too.
