### ISSUE TITLE
Possible to set new default props for Bar?

### ISSUE THREAD

**Issue by bbshih** [recharts/recharts#1361]
I was trying to create a wrapper component for Bar so that I could have a default fill color

```
import * as React from 'react';
import * as Charts from 'recharts';

export * from 'recharts';

// Doesn't render
export function Bar(props) {
  return <Charts.Bar fill="#ff0000" {...props} />;
}

// Does render
export function Tooltip(props) {
  return <Charts.Tooltip isAnimationActive={false} {...props} />;
}
```

However the Bar doesn't render. I see that in generateCategoricalChart.js, it does a check on the type
`var componsedFn = item && item.type && item.type.getComposedData;`

It fails on `item.type.getComposedData` because Bar is the function above and now the true Charts.Bar.

Is there another way I can override the default props or set new ones?

**Comment by xile611** [comment]
@bbshih Not supported yet.
