### ISSUE TITLE
Datapoints outside XAxis.

### ISSUE THREAD

**Issue by zimonitrome** [recharts/recharts#1363]
## Do you want to request a feature or report a bug?

Bug report

## What is the current behavior?

Datapoints are drawn outside of XAxis (shifted to the right)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

https://jsfiddle.net/vcewxh2t/

## What is the expected behavior?

Should be drawn within the XAxis. Correct behavior is shown if you uncomment the last data line from jsfiddle or when type is set to "number" and correct domain is given.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Recharts 1.0.23
Chrome
Mac

**Comment by Yilun-Sun** [comment]
Please make sure to add `type="number"` and `domain={['auto', 'auto']}` when you have an XAxis with the scale of **'time'**.

![image](https://user-images.githubusercontent.com/43896664/215431998-57ce8908-00e5-4a92-9286-0980a5619d27.png)
