### ISSUE TITLE
ScatterChart does not respect dataKey={function} when displaying tooltip

### ISSUE THREAD

**Issue by fsoikin** [recharts/recharts#1365]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
When `dataKey` on `XAxis` or `YAxis` is set to a function (as opposed to number or string), `ScatterChart` will fail to display the tooltip.

This happens because of these three lines: https://github.com/recharts/recharts/blob/c2f9424f9a900ac5492d2f3ba25021099701150c/src/cartesian/Scatter.js#L110-L112

Here, `x`, `y`, and `z` are taken by directly indexing `entry` instead of using `getValueByDataKey`.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

Here's a working example, using strings as `dataKey`s: https://jsfiddle.net/q8j0xm69/2/
This example shows tooltips as expected.

Here's a faulty example, using functions as `dataKey`s: https://jsfiddle.net/vwyLepcq/1/
This example doesn't show tooltips at all.

## What is the expected behavior?
Tooltips should be displayed when `dataKey` is a function.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
