### ISSUE TITLE
Lack of docs for <Legend> payload element

### ISSUE THREAD

**Issue by DeadcatDev** [recharts/recharts#1368]
## Do you want to request a feature or report a bug?

Lack of docs.

## What is the current behavior?

Documentation instuffient for <Legend>, especially for payload: 
- Which options can be provided by payload? 
- How to set color?
- How to set default iconType (and why its called type, not 'iconType' in payload) with payload?
- What does 'id' do on payload?

also bugs:
- adding type: 'none' will remove the set from legend (should remove only the icon)
- using payload with the 'type:line' and with 'color:#' will give You default icon (also with color ;)), without 'color', 'type:line' is just now working at all

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
X
## What is the expected behavior?

Add additional info to docs

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
X

**Comment by tymanchik1991** [comment]
Hi. Any plans to fix it? I have problem with LegendPayload interface where you described only 3 fields :
```
export interface LegendPayload {
    value: any;
    id: any;
    type: LegendType;
}
```

but I have: 
```
{
  color: "#3182bd"
  dataKey: "test"
  inactive: false
  payload: {dataKey: "test", xAxisId: 0, yAxisId: 0, connectNulls: false, activeDot: true, …}
  type: "line"
  value: "test"
}
```
And I've got a compilation error when typescript trying to parse my code

**Comment by SamMade** [comment]
was able to generate something with just `color`, `type`, and `value`. my code is:
```
<Legend
            payload={[
              { value: 'Group A', type: 'square', color: '#112E51' },
              { value: 'Group B', type: 'square', color: '#0071bc' },
              { value: 'Group C', type: 'square', color: '#00a6d2' },
            ]}
          />
```

**Comment by xile611** [comment]
PR is welcome to [recharts.org](https://github.com/recharts/recharts.org)
