### ISSUE TITLE
Pie with multiple activeIndex

### ISSUE THREAD

**Issue by GregoryPotdevin** [recharts/recharts#137]
I'm looking for a React charting library, mostly for pie charts, that can render multiple active slices.

It looks like it would be pretty simple to also allow an array of numbers for activeIndex, and the code change would be minor : https://github.com/recharts/recharts/blob/master/src/polar/Pie.js#L317 (array lookup if activeIndex is an array)

Would a PR with this enhancement be merged ?

**Comment by xile611** [comment]
@GregoryPotdevin PR is welcome. And It's compatible to allow both an array of numbers and a number for `activeIndex`.

**Comment by xile611** [comment]
Closed in version 0.12.4.
