### ISSUE TITLE
how to fill only selected cells (slices) on a pie chart

### ISSUE THREAD

**Issue by MiriamAparicio** [recharts/recharts#1370]
Hi,

I'm trying to make a pie chart with a default color where I only change the color of a selected cells:

![image](https://user-images.githubusercontent.com/31922082/42273355-366624a6-7f89-11e8-905a-e40f6eb72342.png)

I tried the following but it's not working.

``` jsx
   	<PieChart width={600} height={300}>
        <Pie 
          data={data} 
          cx={200} 
          cy={200} 
          innerRadius={50} 
          outerRadius={90} 
          fill="#E5E5E5" 
          paddingAngle={2}>
          {
          	data.map((entry, index) => {
            	if(entry.value === 2400) {
              	<Cell fill='#868686'/>
              }
            })
          }
          </Pie>
       </PieChart>
```
Any idea how I can do it.
Many thanks.
Miriam

**Comment by xile611** [comment]
Maybe [this demo](http://recharts.org/en-US/examples/CustomActiveShapePieChart) can help you

**Comment by MiriamAparicio** [comment]
Thanks @xile611!!
