### ISSUE TITLE
DefaultTooltipContent is overriding wrapperStyle

### ISSUE THREAD

**Issue by farzadmf** [recharts/recharts#1377]
## Do you want to request a feature or report a bug?
I want to report a bug; It was working fine, but I don't know for what reason, now I see this behavior. I updated from `1.0.0-beta.10`  to `1.0.1`. Maybe that's the reason?

## What is the current behavior?
`DefaultTooltipComponent`'s `style` is overriding `wrapperStyle` (screenshots attached)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
Here is my set-up for a line chart (I'm using TypeScript):

```tsx
import * as ch from 'recharts';

const CustomFormatter: ch.TooltipFormatter = value => {
  return (
    <span>
      <i>{(+value).toFixed(5)}</i>
    </span>
  );
};

// My stateless component's 'return' statement:
return (
  <ch.ResponsiveContainer>
    <ch.LineChart>
      <ch.XAxis ... />
      <ch.YAxis ... />

      <ch.Tooltip
        formatter={CustomFormatter}
        isAnimationActive={false}
        wrapperStyle={{ backgroundColor: '#222' }}
      />
    </ch.LineChart>
  </ch.ResponsiveContainer>
)
```

## What is the expected behavior?
I expect to see a dark background on my tool-tip (i.e., `#222`), but I'm seeing a white background; as seen below:
![image](https://user-images.githubusercontent.com/5768792/42411675-cd698b22-81cd-11e8-80f9-b882cd396a8d.png)

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
It seems to me that it was working fine in version `1.0.0-beta.10`, but doesn't work in `1.0.1`

I used React dev-tools to investigate elements and this is what I see (as you can see from the screenshots, `DefaultTooltipComponent` is overriding the `backgroundColor` I have specified:

My specified style appears here:
![image](https://user-images.githubusercontent.com/5768792/42411691-19aa520a-81ce-11e8-9fe4-5451256417a1.png)

The child `DefaultTooltipContent` is overriding it:
![image](https://user-images.githubusercontent.com/5768792/42411695-1f964ca0-81ce-11e8-8f21-1d5fe833b7c7.png)

**Comment by joshpson** [comment]
Just discovered this bug as well. If you create your own custom tooltip through content this doesn't happen, but wrapperStyle by itself no longer works.

**Comment by MarcusPenn** [comment]
I was looking into this the other week, it looked like there was a final style that was added that can only be overwritten using important in CSS.

I believe it was added as a response to an issue but I'm having trouble finding it again. Will update if I can.

**Comment by GreenGremlin** [comment]
Here's the merge request that removed the `wrapperStyle` from `DefaultTooltipContent`: https://github.com/recharts/recharts/pull/1322
Here is the issue that led to removing `wrapperStyle`: https://github.com/recharts/recharts/issues/798

It seems a `contentStyle prop`, for overriding `DefaultTooltipContent` styles is needed.
