### ISSUE TITLE
Cannot Display Custom Shapes

### ISSUE THREAD

**Issue by klapouchy** [recharts/recharts#1378]
I'd like to know what is the proper way to display`<Dot>` or `<Curve>` on top on my chart. 

https://codesandbox.io/s/j3ql6l6qq3

**Comment by paulmelnikow** [comment]
I think you may be looking for [ReferenceDot](http://recharts.org/en-US/api/ReferenceDot).

**Comment by klapouchy** [comment]
@paulmelnikow ReferenceDot solves part of my problem. What I really need is to be able to draw a custom shape (in my case `Curve`). What's in the [API documentation](http://recharts.org/en-US/api/Curve) doesn't really help.

**Comment by paulmelnikow** [comment]
I think you can specify your own shape with ReferenceArea. Would that help?

**Comment by iTeex** [comment]
I experienced the same issue when trying to display a rectangle on my chart. The `<Rectangle>` component never worked but using `<ReferenceArea>` did the trick!
