### ISSUE TITLE
Warning: Failed prop type: Invalid prop `scale` supplied to `XAxis`. or ERROR

### ISSUE THREAD

**Issue by tomasztomys** [recharts/recharts#1379]
## Do you want to request a feature or report a bug?
bug

## What is the current behavior?
When pass 'utcTime': `Warning: Failed prop type: Invalid prop `scale` supplied to `XAxis`.`

or a lot of ERRORS when pass 'time'

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

pass 'utcTime' or 'utc' to prop scale in XAxis

## What is the expected behavior?
no warnings and errors

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.0.1
It works before 1.0.0 (it works on beta.10)

**Comment by tomasztomys** [comment]
probably because of #1195

**Comment by thehungrycoder** [comment]
In [api doc](http://recharts.org/en-US/api/XAxis#scale), seems a valid value can be 'utcTime' but [in source](https://github.com/recharts/recharts/blob/master/src/util/ReactUtils.js#L136) it seems 'utc'. I'm getting that error either way.
