### ISSUE TITLE
Unknown props warnings when rendering PieChart

### ISSUE THREAD

**Issue by dorsha** [recharts/recharts#138]
Got the following warnings when rendering the below code:
![image](https://cloud.githubusercontent.com/assets/5429033/16583986/c6a2e1be-42c1-11e6-8a67-7b7a474d6afe.png)

![image](https://cloud.githubusercontent.com/assets/5429033/16583994/d359fe7e-42c1-11e6-98c3-b48c6bc16368.png)

```
import React, { PropTypes } from 'react';
import { PieChart, Pie, Legend, Tooltip } from 'recharts';

const SectionPieChart = ({ data, style }) =>
  <div className="section-pie-chart" style={style}>
    <PieChart width={800} height={400}>
      <Tooltip />
      <Legend />
      <Pie data={data} cx={200} cy={200} startAngle={90} endAngle={-270} outerRadius={80} label />
    </PieChart>
  </div>
;
SectionPieChart.propTypes = {
  data: PropTypes.oneOfType([
    PropTypes.object,
    PropTypes.array
  ]),
  style: PropTypes.object
};

export default SectionPieChart;
```

Data:
```
const data = [
    { "name": "Group B", "value": 4567, "fill": "#82ca9d" },
    { "name": "Group C", "value": 1398, "fill": "#ffbb28" },
    { "name": "Group D", "value": 9800, "fill": "#ff8042" },
    { "name": "Group E", "value": 3908, "fill": "#0088fe" },
    { "name": "Group F", "value": 4800, "fill": "#8884d8" }
]
```

React: 15.2.0
recharts: 0.12.3

Warnings does not appear when running in NODE_ENV=production, since React does not print them.

**Comment by xile611** [comment]
It's the bug of [React 15.2.0](https://github.com/facebook/react/pull/6532).

**Comment by dorsha** [comment]
OK, there are also other warnings for props like: `percent', 'innderRadius' and etc.

**Comment by xile611** [comment]
@dorsha We will check these props. React will check all the props now, you can see [this document](https://gist.github.com/jimfb/d99e0678e9da715ccf6454961ef04d1b) for detail.
