### ISSUE TITLE
Bubble charts are not consistent in size

### ISSUE THREAD

**Issue by dsuraj72** [recharts/recharts#1381]
Hi,

I've replicated the bubble chart [example()](http://recharts.org/en-US/examples/BubbleChart) in one of my project, 

Some bubbles with less values gets rendered larger in size, but larger values gets rendered smaller in size for certain cases.

[bubble_chart.js.txt](https://github.com/recharts/recharts/files/2176716/bubble_chart.js.txt)

I've also changed the range variable values but it's not seem to be working.
If we increase the dataset, the inconsistency is more.

Pls. assist on this.

Thanks.

**Comment by xile611** [comment]
You can reopen this issue if online demo is provided.
