### ISSUE TITLE
Dot onMouseOver function issue

### ISSUE THREAD

**Issue by WinfredMa** [recharts/recharts#1382]
1. Please added more details about the function parameters.
2. The function parameter is Proxy {dispatchConfig: {…}, _targetInst: FiberNode, isDefaultPrevented: ƒ, isPropagationStopped: ƒ, _dispatchListeners: ƒ, …} in old version, but it is {cx: 445, cy: 57.5, r: 9.848284000000001, width: 146, height: 73, …} in the latest version.
3. I find that the onmouseover function parameter is Proxy {dispatchConfig: {…}, _targetInst: FiberNode, isDefaultPrevented: ƒ, isPropagationStopped: ƒ, _dispatchListeners: ƒ, …} for Rectangle. Could you keep the uniform callback function parameter structure?

**Comment by xile611** [comment]
PR is welcome
