### ISSUE TITLE
Pie chart as progress chart

### ISSUE THREAD

**Issue by frnk01** [recharts/recharts#1383]
I am wondering if there is any way of displaying the pie chart as a progress chart with a value, and a max value. I can`t find any documentation around this possibility but I`ve seen some people achieve it like the user in this issue [https://github.com/recharts/recharts/issues/309](https://github.com/recharts/recharts/issues/309)

I would also like to add some threshold values for the chart, like a red background when the pie reaches 
maximum (90-100%), and a yellow background for values between 80-90%.

Any help is much appriciated 😃

**Comment by strange** [comment]
I added another pie outside that indicates the thresholds. The inner pie has two values: the actual value and `max - value` with a white background as a placeholder for "unused" values (could also be light gray in this example). You may need to adjust the values a bit to keep the two pies aligned if you support negative values and whatnot. Good luck!

~~~
<ResponsiveContainer height="100%" width="100%">
    <PieChart>
        <Pie startAngle={200} endAngle={-20} data={thresholds} dataKey="value" innerRadius="90%" outerRadius="100%" />
        <Pie startAngle={200} endAngle={-20} data={data} dataKey="value" innerRadius="65%" outerRadius="89%" fill={this.props.color}/>
    </PieChart>
</ResponsiveContainer>
~~~ 

Looks like this:

![2018-07-18-100538_402x424_scrot](https://user-images.githubusercontent.com/61257/42868186-faf768e6-8a71-11e8-9caf-0c489da78159.png)
