### ISSUE TITLE
LineChartMultiSeries example couldn't be reproduced in fiddle

### ISSUE THREAD

**Issue by adtm** [recharts/recharts#1384]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
When I go to the LineChartMultiSeries graph page ([link](http://recharts.org/en-US/examples/LineChartHasMultiSeries)) and click on the JSFiddle example, I cannot see the same example with multiple x-axis data points and a tooltip (even if I changed the data from `Math.random()` to the same input as in the page [(link)](https://jsfiddle.net/ewcqxbwo/462/)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
Original Example with the same data as in webpage: https://jsfiddle.net/ewcqxbwo/462/
My Example where I try to implement by the above chart: https://jsfiddle.net/ewcqxbwo/461/

## What is the expected behavior?
I should see a tooltip with correctly mapped information in both of the examples.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts 1.0.1

**Comment by xile611** [comment]
please try the new demo: http://recharts.org/en-US/examples/LineChartHasMultiSeries
