### ISSUE TITLE
Distance between grid Lines

### ISSUE THREAD

**Issue by sughanpandita** [recharts/recharts#1393]
How to reduce the distance between gridlines in BarChart ?
![screen shot 2018-07-19 at 9 55 25 am](https://user-images.githubusercontent.com/17419896/42958412-4f1fe51a-8b3a-11e8-85a7-fc38a4a46c93.png)

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
