### ISSUE TITLE
How to create sorted stack Bar? 

### ISSUE THREAD

**Issue by sughanpandita** [recharts/recharts#1394]
Want to have sorted stack bar, like this 
<img width="599" alt="screen shot 2018-07-20 at 7 32 57 am" src="https://user-images.githubusercontent.com/17419896/43008245-6164bcc2-8bef-11e8-840a-9a72dd8f0630.png">

**Comment by HunterEl** [comment]
Also very interested in this 👍

**Comment by sughanpandita** [comment]
@HunterEl  Found this solution
Sort the oldData(the way you want) and pass the newly created array to data property of BarChart
const newData = [].concat(oldData).sort((a, b) => a[this.props.dataKeyIn]  < b[this.props.dataKeyIn])

**Comment by jayanthbabu123** [comment]
how can we render that chart showed above with dynamic data
