### ISSUE TITLE
BarChart doesn't work when iterating through a multi-dimensional array

### ISSUE THREAD

**Issue by prankris** [recharts/recharts#1397]
## Do you want to request a feature or report a bug?
Report a bug with BarChart
## What is the current behavior?
Bars do not show up when data is iterated from a multi-dimensional array, same code works with LineChart though.  Even the Tooltip seems to work.
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

Demo at [https://codesandbox.io/s/lr4x4ymlll](https://codesandbox.io/s/lr4x4ymlll)

```
const data = [
  { name: "Page A", uv: 4000, pv: 2400 },
  { name: "Page B", uv: 3000, pv: 1398 },
  { name: "Page C", uv: 2000, pv: 9800 }
];

const mydata = [
  {
    name: "uv",
    val: [
      { value: 4000, label: "Page A" },
      { value: 3000, label: "Page B" },
      { value: 2000, label: "Page C" }
    ]
  },
  {
    name: "pv",
    val: [
      { value: 2400, label: "Page A" },
      { value: 1398, label: "Page B" },
      { value: 9800, label: "Page C" }
    ]
  }
];

const lineColor = ["#8884d8", "#82ca9d"];

function App() {
  return (
    <div>
      <h1>Doesn't Fill the Bars</h1>
      <BarChart width={730} height={250}>
        <CartesianGrid strokeDasharray="3 3" />
        <XAxis dataKey="label" allowDuplicatedCategory={false} />
        <YAxis />
        <Tooltip />
        <Legend />
        {mydata.map((s, i) => (
          <Bar
            dataKey="value"
            fill={lineColor[i]}
            data={s.val}
            name={s.name}
            key={s.name}
          />
        ))}
      </BarChart>
      <h1>Same code for Line chart Works</h1>
      <LineChart width={730} height={250}>
        <CartesianGrid strokeDasharray="3 3" />
        <XAxis dataKey="label" allowDuplicatedCategory={false} />
        <YAxis />
        <Tooltip />
        <Legend />
        {mydata.map((s, i) => (
          <Line
            dataKey="value"
            stroke={lineColor[i]}
            data={s.val}
            name={s.name}
            key={s.name}
          />
        ))}
      </LineChart>
      <h1>Basic Examples that Works</h1>
      <BarChart width={730} height={250} data={data}>
        <CartesianGrid strokeDasharray="3 3" />
        <XAxis dataKey="name" />
        <YAxis />
        <Tooltip />
        <Legend />
        <Bar dataKey="pv" fill="#8884d8" />
        <Bar dataKey="uv" fill="#82ca9d" />
      </BarChart>
      <LineChart width={730} height={250} data={data}>
        <CartesianGrid strokeDasharray="3 3" />
        <XAxis dataKey="name" />
        <YAxis />
        <Tooltip />
        <Legend />
        <Line dataKey="pv" stroke="#8884d8" />
        <Line dataKey="uv" stroke="#82ca9d" />
      </LineChart>
    </div>
  );
}
```

## What is the expected behavior?
Bars should show up with data.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.1.0, all browsers

**Comment by jakeFeldman** [comment]
@xile611 Do you have a chance to look at this?

**Comment by ErickMwazonga** [comment]
Hello, include data={data} in the <BarChart  /> tag, i.e 
`<BarChart width={730} height={250} data={data} >
        <CartesianGrid strokeDasharray="3 3" />
        <XAxis dataKey="label" allowDuplicatedCategory={false} />
        <YAxis />
        <Tooltip />
        <Legend />
        {mydata.map((s, i) => (
          <Bar
            dataKey="value"
            fill={lineColor[i]}
            data={s.val}
            name={s.name}
            key={s.name}
          />
        ))}
      </BarChart>`

**Comment by prankris** [comment]
Following code is working
`<BarChart data width={730} height={250}>...</BarChart>`
and
`<BarChart data={mydata} width={730} height={250}>...</BarChart>`

**Comment by prankris** [comment]
> Hello, include data={data} in the tag, i.e
> `<BarChart width={730} height={250} data={data} >... </BarChart>`
> 
> ![screenshot from 2018-12-20 11-18-13](https://user-images.githubusercontent.com/19705223/50272532-22886a80-0449-11e9-895b-1812300bf06a.png)
> ![screenshot from 2018-12-20 11-18-00](https://user-images.githubusercontent.com/19705223/50272533-22886a80-0449-11e9-998a-8b628fc94e68.png)

Thanks
