### ISSUE TITLE
Calculate tick number by final rendered name

### ISSUE THREAD

**Issue by edwardfhsiao** [recharts/recharts#1398]
## Do you want to request a feature or report a bug?
feature
## What is the current behavior?
```js
const data = [
      {name: '2018-05-11 15:30:28ssssssss', uv: 4000, pv: 2400, amt: 2400},
      {name: '2018-05-12 15:30:28ssssssss', uv: 3000, pv: 1398, amt: 2210},
      {name: '2018-05-13 15:30:28ssssssss', uv: 2000, pv: 9800, amt: 2290},
      {name: '2018-05-14 15:30:28ssssssss', uv: 2780, pv: 3908, amt: 2000},
      {name: '2018-05-15 15:30:28ssssssss', uv: 1890, pv: 4800, amt: 2181},
      {name: '2018-05-16 15:30:28ssssssss', uv: 2390, pv: 3800, amt: 2500},
      {name: '2018-05-17 15:30:28ssssssss', uv: 3490, pv: 4300, amt: 2100},
];

<XAxis tick={<CustomizedTickX />} dataKey="name" />

const CustomizedTickX = React.createClass({
  render() {
    const { payload, x, y } = this.props;
    return (
      <Text x={x} y={y + 15} style={{ fontSize: 12 }} textAnchor="middle">
        {payload.value.substr(0, 4)}
      </Text>
    );
  }
})
```
![image](https://user-images.githubusercontent.com/11728228/43254689-8379c072-90fa-11e8-9c93-7cc3a5220ef8.png)

Only display two ticks even though I trimmed the string to make them shorter and set them even smaller font size.

## What is the expected behavior?
Determin the tick number by final rendered value, for instance 
caculate by ```{payload.value.substr(0, 4)}``` instead of original value ```name``` in the data array

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
```js
"recharts": "^1.0.0-beta.10",
```
macOs

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
