### ISSUE TITLE
Can I Toggle line chart in recharts ?

### ISSUE THREAD

**Issue by pawansaket** [recharts/recharts#1399]
Is there any way to toggle the line chart by clicking the x-axis text. Such look at the picture:
![image](https://user-images.githubusercontent.com/26107608/43257153-96d34818-90ec-11e8-9d6d-e7a724dffcfd.png)
If I click on Item1 then line chart of item1 disappear and reappear on clicking, as I got to many lines and item to display on chart.
If there is any functionality or any idea how to do , it would be helpful.Thanks.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
