### ISSUE TITLE
fluid size

### ISSUE THREAD

**Issue by salzhrani** [recharts/recharts#14]
Awesome work,
Are there any plans to make charts adapt to the container size on resize? or is it a concern of the container component?

**Comment by xile611** [comment]
I think the adaptation should be a concern of the container component, just like the example (http://jsfiddle.net/cmx66300/).

Maybe we can provide a component to wrap the chart. The wrapper component can do the event binding.

**Comment by xile611** [comment]
We add a wrapper component AdaptionWrapper in version 0.5.0. 
Here is an example (http://jsfiddle.net/Lpk2ky66).
And in the future we need to support percentage value of cx, cy, innerRadius, outerRadius in polar coordinate charts, such as  PieChart, RadarChart, RidalBarChart.

**Comment by xile611** [comment]
Support percentage value of cx, cy, innerRadius, outerRadius in v0.5.1
