### ISSUE TITLE
Suggestion: Give user more precise control over rendering cartesian grid.

### ISSUE THREAD

**Issue by JakubSimandl** [recharts/recharts#1401]
Feature request.

Currently, there is no way to overload `verticalCoordinatesGenerator` or `horizontalCoordinatesGenerator` for the `CartesianGrid` component. 

It would be really helpful if those props could be provided by the user. 

Possible fix: https://github.com/recharts/recharts/pull/1396

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by nielsuit227** [comment]
Thanks for implementing this feature. Is there somewhere I can find how to use these CoordinatesGenerators?
