### ISSUE TITLE
Tooltip backgroundColor

### ISSUE THREAD

**Issue by tobzed** [recharts/recharts#1402]
## Do you want to request a feature or report a bug?
Feels like it is a bug.

## What is the current behavior?
When supplying the backgroundColor property in the wrapperStyle of Tooltip nothing happens, yet other properties such as borderColor do change. 

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
-
## What is the expected behavior?
-
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Chome Version 67.0.3396.99
Recharts 1.0.1

**Comment by tobzed** [comment]
#1377
think these are related :)

**Comment by l20DfX35JnKBfRn** [comment]
This is still an issue, I do not know why this was closed.

**Comment by rslavey** [comment]
I figured out that if you set the contentStyle it works. I needed to do this with my dark theme:

``<Tooltip contentStyle={{backgroundColor: theme.semanticColors.bodyBackground}} itemStyle={{ color: theme.semanticColors.bodyText }} />``
