### ISSUE TITLE
Can the chart data be dynamically calculated?

### ISSUE THREAD

**Issue by amimas** [recharts/recharts#1404]
## Do you want to request a feature or report a bug?
Help/question

## What is the current behavior?

Both bar chart and pie charts expect a data structure like the following according to docs and examples:

```
const data = [
      {name: 'Page A', uv: 4000, pv: 2400, amt: 2400},
      {name: 'Page B', uv: 3000, pv: 1398, amt: 2210},
      {name: 'Page C', uv: 2000, pv: 9800, amt: 2290},
      {name: 'Page D', uv: 2780, pv: 3908, amt: 2000},
      {name: 'Page E', uv: 1890, pv: 4800, amt: 2181},
      {name: 'Page F', uv: 2390, pv: 3800, amt: 2500},
      {name: 'Page G', uv: 3490, pv: 4300, amt: 2100},
];

    	<BarChart width={600} height={300} data={data}
       <CartesianGrid strokeDasharray="3 3"/>
       <XAxis dataKey="name"/>
       <YAxis/>
       <Tooltip/>
       <Legend />
       <Bar dataKey="pv" fill="#8884d8" />
       <Bar dataKey="uv" fill="#82ca9d" />
      </BarChart>
```
## What is the expected behavior?

If I have the data in a different format, how can I tell Bar component in above example to calculate the value. For example, lets say the `uv` in the example data above has another object, whose value should be used in Bar chart; or an array, whose count should be used in Bar chart.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
