### ISSUE TITLE
Percentages from PIE Chart disappear if react component is updated/re-rendered

### ISSUE THREAD

**Issue by iamsaksham** [recharts/recharts#1405]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
Label i.e Percentages/Description of data on PIE Chart disappear from PIE chart if the component where it is placed is re-rendered/updated.

## What is the expected behavior?
Percentages/PIE Chart description data should persist

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
recharts version -> `^1.0.0-beta.10` and `1.1.0`

**Comment by OlivierNguyen** [comment]
It might be related to this issue: https://github.com/recharts/recharts/issues/1305.
Maybe this PR would fix your issue: https://github.com/recharts/recharts/pull/1406. 

Can you fork this repo with the fix and check if it resolves your bug?

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
