### ISSUE TITLE
active Tooltip when mouse down is true

### ISSUE THREAD

**Issue by tobzed** [recharts/recharts#1407]
## Do you want to request a feature or report a bug?
feature.

## What is the current behavior?
tooltip is inactive whenever the mouse is pressed (for instance I want to be able to show a tooltip when selecting an area of the graph so that I can see the area labels I'm currently selecting).

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue guide.
