### ISSUE TITLE
Add an option to hide legend items related to an empty chart component

### ISSUE THREAD

**Issue by RobbyUitbeijerse** [recharts/recharts#1408]
## Do you want to request a feature or report a bug?
Feature request for (optionally) removing legend items related to an empty (zero value) chart component.

## What is the current behavior?
The legend shows all items even when the related chart component value is zero throughout the whole graph. In my case, this is undesired, since the data I'm displaying is build up through a process of form steps, and not all chart components I would like to display are relevant for all users. 

<img width="603" alt="schermafbeelding 2018-07-31 om 12 24 27" src="https://user-images.githubusercontent.com/10176709/43454241-b04ca9be-94bc-11e8-956e-4e4f809ad81a.png">

## What is the expected behavior?
Add an option (or a field to the legend payload) for removing legend items if the related chart component is empty.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.1.0, all browsers

**Comment by bsplosion** [comment]
@RobbyUitbeijerse did you come up with a solution for this?  I'm also hunting for either a switch or method to hide from the legend where an item doesn't appear as a value anywhere in the chart.
