### ISSUE TITLE
Use "dataKey" to specify the value of pie

### ISSUE THREAD

**Issue by wellyal** [recharts/recharts#1410]
## Do you want to request a feature or report a bug?
Report a bug

## What is the current behavior?
Using PieChart I keep getting **Use "dataKey" to specify the value of pie, the props "valueKey" will be deprecated in 1.1.0** warning. I'm not even using "valueKey. When I put "dataKey" the graph doesnt render.

```javascript
<PieChart width={180} height={150}>
  <Pie
    data={data}
    innerRadius={40}
    outerRadius={70}
    fill="#8884d8"
    paddingAngle={1}
  >
    {data.map((entry, index) => (
      <Cell fill={colors[index % colors.length]} />
    ))}
  </Pie>
  <Tooltip content={<TooltipsComponent />} />
</PieChart>
```

Heres the sandbox version, if you open the console you'll get the warning.
https://codesandbox.io/s/l92o8qo2nz

**Comment by rpuls** [comment]
I'm struggling right here as well. Pie will only render without dataKey property, but raises strong error msgs.

**Comment by rpuls** [comment]
What I ended up doing, was adding to the pie element: `datakey: 'value'` (js), with html that would be `datakey="value"`.
This removed the error message.

**Comment by adeelibr** [comment]
This should be updated in the examples as well. `dataKey="value"`, Can I make a PR for this in the documentation.

**Comment by shawnmuzick** [comment]
I still seem to be experiencing this error
