### ISSUE TITLE
Stacked Area Chart - colours are not filling as expected

### ISSUE THREAD

**Issue by eolhc** [recharts/recharts#1412]
## Do you want to request a feature or report a bug?
Bug 

## What is the current behavior?
Colours in stacked area chart do not fill as expected

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
To reproduce, compare the colour filling of the chart here: http://recharts.org/en-US/examples/StackedAreaChart vs the demo here: https://jsfiddle.net/alidingling/c1rLyqj1/

## What is the expected behavior?
Colours should fill as per the stacked area chart example

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
This was previously was working in v0.22.5, not working in v1.1.0

Thanks

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue guide.
