### ISSUE TITLE
Unit formatting should have a space between value and unit (most of the time).

### ISSUE THREAD

**Issue by geon** [recharts/recharts#1413]
## Do you want to request a feature or report a bug?

Bug

## What is the current behavior?

On the YAxis, specifying the unit prints it as "123m".

## What is the expected behavior?

"123 m"

https://english.stackexchange.com/questions/2794/punctuation-with-units

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Mac OS, Chrome

**Comment by xile611** [comment]
You can set the unit to be  `${space}m`
