### ISSUE TITLE
Vertical barchart orientation to the right

### ISSUE THREAD

**Issue by maalej** [recharts/recharts#1415]
## Do you want to request a feature or report a bug?
feature
## What is the current behavior?
Vertical barcharts renders only from LEFT to RIGHT
## What is the expected behavior?
Enable `orientation: "right"` for bars and layout like for the axis. 
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
last

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
