### ISSUE TITLE
Charts using only a single data key

### ISSUE THREAD

**Issue by vamzz1** [recharts/recharts#1416]
## Do you want to request a feature or report a bug?
Feature
## What is the current behavior?
So currently when I plot a Line or an Area using a set of tuples <x1, y1>, <x2. y2> and so on. The line only uses one axis coordinate and is independent of the other axis coordinate.

## What is the expected behavior?
I expected the line to take into consideration both the axis coordinates so that line looks like an actual representation of my data.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
version 1.1.0, I don't think this issue has anything to do with the browser I'm testing it on.

**Comment by HaritDivyesh** [comment]
Any updates? I'm in a similar situation. Idk how to make it consider both x and y coordinates.

**Comment by anil1712** [comment]
Yes, I wanted the same thing. 

Did you guys find any solution?

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
