### ISSUE TITLE
Large bundle size

### ISSUE THREAD

**Issue by ankitsinghaniyaz** [recharts/recharts#1417]
My gzipped bundle size for rechart is ~40kb which is quite big. I'm just trying to understand what makes it so huge? Any suggestions on how to reduce the size?

**Comment by TrySound** [comment]
I working on it. This is the first step.
https://github.com/recharts/recharts/pull/1414

**Comment by rmckeel** [comment]
For context, I measured 127KB gzipped with C3 + D3 plus a single file React wrapper around C3.  For how capable recharts seems (testing it now), 40kb seems reasonable & fairly small in my opinion.  Obviously there is always room for improvement / tree shaking, but wanted to add that for context!

**Comment by anirban09** [comment]
I made a small area chart by using:

```javascript
import { Area, AreaChart, ResponsiveContainer } from 'recharts';
```

And this increased the gzipped bundle size by **92.59 KB**.

Is this the way it's supposed to work, or is there there some way to decrease bundle size by selectively importing only a few components from recharts?

**Comment by mgallegoccxc** [comment]
Any updates on this?

**Comment by oziniak** [comment]
@xile611 why is this closed? I'm facing the same issue. And when I try to use [babel-plugin-recharts](https://github.com/recharts/babel-plugin-recharts) I get the same issue as here https://github.com/recharts/babel-plugin-recharts/issues/12

**Comment by ypresto** [comment]
Tree shaking is disabled (sideEffects in package.json) because polyfill is imported on index.ts .

https://github.com/recharts/recharts/blob/d36d5af0cce84494b4bb70c994a1556c83f6e54b/src/index.ts#L1

We can enable it by moving polyfill to a separated file.

**Comment by gaurav5430** [comment]
@ypresto I think tree shaking works now as sideEffects have been added in 1.8.5 and 2.x.x package.json like this:
```
  "sideEffects": [
    "./*/index.js",
    "./*/polyfill.js"
  ],
```

**Comment by ypresto** [comment]
@gaurav5430 `sideEffects` is a list of file to *disable* tree shaking so once you import index.js it won't work.

**Comment by gaurav5430** [comment]
@ypresto yes, sideEffects is an array of files which have side effects and shouldn't be dropped. In this case, the index.js and polyfills shouldn't be dropped. But all other files are free of sideEffects, so if you import LineChart, you can see that it doesn't import BarChart in your bundle, as BarChart.js is not mentioned in sideEffects and can be dropped.
Tested this with webpack bundle analyser.

**Comment by ypresto** [comment]
> But all other files are free of sideEffects, so if you import LineChart, you can see that it doesn't import BarChart in your bundle

You mean that to import js files for LineChart, BarChart and etc. one by one?

It is not tree shaking and is what webpack does while constructing [dependency graph](https://webpack.js.org/concepts/dependency-graph/), even without tree shaking. What here [tree shaking](https://webpack.js.org/guides/tree-shaking/) is to remove dead code (function and etc.) from the bundle.

Importing each file is not only a hassle but also impossible with TypeScript: `@types/recharts` only provides typing for index.js.

**Comment by ypresto** [comment]
@gaurav5430 

> But all other files are free of sideEffects, so if you import LineChart, you can see that it doesn't import BarChart in your bundle

You mean that to import js files for LineChart, BarChart and etc. one by one?

It is not tree shaking and is what webpack does while constructing [dependency graph](https://webpack.js.org/concepts/dependency-graph/), even without tree shaking. What here [tree shaking](https://webpack.js.org/guides/tree-shaking/) is to remove dead code (function and etc.) from the bundle.

Importing each file is not only a hassle but also impossible with TypeScript: `@types/recharts` only provides typing for index.js.

**Comment by gaurav5430** [comment]
@ypresto 
Apologies if it wasn't clear. I am not suggesting to import each component from its absolute path.

I mean this:

`import { LineChart, Line } from 'recharts' `

<img width="1223" alt="Screenshot 2020-06-27 at 8 51 27 PM" src="https://user-images.githubusercontent.com/12510548/86261242-ec9a7980-bbdb-11ea-92a2-cbc9cbe8bb67.png">

`import { BarChart, Bar } from 'recharts'`

<img width="1409" alt="Screenshot 2020-06-27 at 8 51 45 PM" src="https://user-images.githubusercontent.com/12510548/86261409-253a5300-bbdc-11ea-8d6d-7f16eed1f229.png">

`import { LineChart, BarChart, Line, Bar } from 'recharts'`

<img width="1237" alt="Screenshot 2020-06-27 at 8 57 51 PM" src="https://user-images.githubusercontent.com/12510548/86261430-2b303400-bbdc-11ea-9655-abf2e860dfc9.png">
