### ISSUE TITLE
ReferenceLine generates warning about alwaysShow

### ISSUE THREAD

**Issue by DavidHenri008** [recharts/recharts#1419]
There is a bug when using a ReferenceLine or ReferenceDot or ReferenceArea in a chart.

When a one of the reference is used in a chart a warning saying "The alwaysShow property is deprecated" is displayed when the mouse hover the chart. Obviously the alwaysShow property is not set on the reference.
It seems to be related with the modification of July 6th commit 51c55a6ea4c93034b756700bc350d5d538b22425, by @paulmelnikow. The warning should have been: 
```
 warn(alwaysShow === undefined,
      'The alwaysShow prop is deprecated. Please use ifOverflow="extendDomain" instead.');
```
Where the condition is "===" instead of "!==" since the warn function condition is what you are expecting to avoid the warning and not what cause the warning to be displayed. 

Obviously the workaround is to set the alwaysShow property to something different than undefined.

**Comment by paulmelnikow** [comment]
Oops! Sorry about that. I’ll open a PR with a fix.

**Comment by DavidHenri008** [comment]
Great thank you!

**Comment by matsilva** [comment]
Can close this issue now?

**Comment by DavidHenri008** [comment]
Let's close it.

**Comment by dkulakowska** [comment]
I still get that warning in the console, don't really know why.

**Comment by olelivalife** [comment]
How to fix this?

**Comment by crickford** [comment]
`ifOverflow` is a prop on the `ReferenceLine`, `ReferenceDot`, and `ReferenceArea` components which should be used rather than the `alwaysShow` prop referenced in the docs. It is used to configure how reference components which fall outside of the domain of the chart are rendered, here are the options it accepts (from @types/recharts 1.1.22):
`'hidden' | 'visible' | 'discard' | 'extendDomain'`

**Comment by crickford** [comment]
I've created a PR for the docs here: https://github.com/recharts/recharts.org/pull/101
Here's an example of how to use the `ifOverflow` prop: https://jsfiddle.net/fqt7xw0m/
