### ISSUE TITLE
PieChart gap between pie cells/sectors

### ISSUE THREAD

**Issue by isilweo** [recharts/recharts#142]
Hi,

is there a way to change gaps between pie cells (Sectors)? Something like this:
![image](https://cloud.githubusercontent.com/assets/1628252/16726566/2c331266-475d-11e6-89ee-8f321e62c0da.png)

**Comment by xile611** [comment]
@isilweo You mean `paddingAngle` of `Pie`. We will support this feature in the next version. Thank you for your advice.
