### ISSUE TITLE
Allow viewBox property on Surface

### ISSUE THREAD

**Issue by DavidHenri008** [recharts/recharts#1420]
It would be a great enhancement to allow the viewBox property to be passed to the Surface component.

Currently, the render function of generateCategoricalChart() function filters the viewBox property via javascript deconstruction and by calling getPresentationAttributes() function. The Surface component is already designed to handle the viewBox property so passing it would increase flexibility of the component and allow to have a viewbox bigger than the specified width and height.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
