### ISSUE TITLE
Remove the spacing between 2 cells

### ISSUE THREAD

**Issue by wellyal** [recharts/recharts#1421]
## Do you want to request a feature or report a bug?
Report a bug

## What is the current behavior?
I can't remove the spacing between 2 cells, is there any way to accomplish this

![image](https://user-images.githubusercontent.com/3047016/43598450-196e0fba-965b-11e8-8093-ee9de83a8386.png)

```javascript
<PieChart width={180} height={150}>
  <Pie
    data={data}
    innerRadius={40}
    outerRadius={70}
  >
    {data.map((entry, index) => (
      <Cell fill={colors[index % colors.length]} />
    ))}
  </Pie>
  <Tooltip content={<TooltipsComponent />} />
</PieChart>
```

## What is the expected behavior?
Thats what I'd like to do

![image](https://user-images.githubusercontent.com/3047016/43598475-28eb536c-965b-11e8-9f6f-7344a8b6fc11.png)

**Comment by pouretrebelle** [comment]
It's the svg stroke that's creating the margin, try setting the css property of `stroke-width` on the Pie path to 0, alternatively you can set the stroke value to match the fill, like:
`<Cell fill={colors[index % colors.length]} stroke={colors[index % colors.length]} />`

**Comment by wellyal** [comment]
@pouretrebelle thank you. That just did the trick.

**Comment by wellyal** [comment]
@pouretrebelle thank you. That just did the trick for me.
