### ISSUE TITLE
Wrapper components/HOCs Not Rendering

### ISSUE THREAD

**Issue by pouretrebelle** [recharts/recharts#1425]
I'm trying to abstract away the common styles/options I plan on using in charts across the site by creating wrapper components for select recharts components, but although they load and run with no errors, the chart loads without the modified components showing up.

``` js
import React from 'react'
import { Legend } from 'recharts'

const CustomLegend = (props) => (
  <Legend
    iconType="circle"
    layout="vertical"
    align="right"
    verticalAlign="top"
    {...props}
  />
)

export default CustomLegend
```

I've also tried the same with a higher order component pattern and no dice, is there any way to accomplish this? Thanks

**Comment by judyzaratan** [comment]
@pouretrebelle There was similar issue raised in https://github.com/recharts/recharts/issues/412 .  There is a workaround solution noted in there where you can extend the rechart component and define custom props there.  Maybe that can help?

**Comment by pouretrebelle** [comment]
Closing because duplicate

**Comment by m3h0w** [comment]
So now both issues on HOCs not rerendering are closed? Or is this duplicating something else than #412? This is a huge problem for using recharts in larger applications.
