### ISSUE TITLE
Plotting a threshold line on top of a bar chart

### ISSUE THREAD

**Issue by adrianmc** [recharts/recharts#143]
Is it possible to use this library to make a chart similar to this:

![bar chart with threshold line](http://www.nature.com/nclimate/journal/v1/n8/images/nclimate1265-f1.jpg)

Additionally, can I colour the bars differently depending on whether or not they are above the threshold line?

**Comment by xile611** [comment]
@adrianmc [Here](http://jsfiddle.net/0mgjy8nf/) is a workaround, though I don't quite understand this chart.

You can color the bars differently by customized `shape` in `Bar`.
I wonder why "Fossil fuels" have a different fill color?

**Comment by adrianmc** [comment]
@xile611 thanks for the reply. That is very helpful! 

Re: fossil fuels, I'm not sure either. I just found this random chart on the web as an example. My own application has nothing to do with it. My guess is that the chart is trying to say something about replacing fossil fuels with bio-fuels.
