### ISSUE TITLE
Polyfills should not be included for builds targeting ES6+

### ISSUE THREAD

**Issue by use-strict** [recharts/recharts#1432]
## Do you want to request a feature or report a bug?
Request a feature

## What is the current behavior?
polyfills are included regardless of target (es5/es6/jsnext)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
-
## What is the expected behavior?
Polyfills should be included only for the es5 build, not the es6+ builds. This means there should be a separate index.js that doesn't import polyfill.js

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
latest/master; unknown

**Comment by talentlessguy** [comment]
same problem, pnpm doesn't want to work because there is this error:

```
🚨  /home/v1rtl/Coding/forks/SkBoost-FrontEnd/node_modules/recharts/es6/polyfill.js:2:7: Cannot resolve dependency 'core-js/es/number'
  1 | import 'core-js/es/math';
> 2 | import 'core-js/es/number';
    |       ^
```

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by madshargreave** [comment]
> same problem, pnpm doesn't want to work because there is this error:
> 
> ```
> 🚨  /home/v1rtl/Coding/forks/SkBoost-FrontEnd/node_modules/recharts/es6/polyfill.js:2:7: Cannot resolve dependency 'core-js/es/number'
>   1 | import 'core-js/es/math';
> > 2 | import 'core-js/es/number';
>     |       ^
> ```

Did you ever find a solution?
