### ISSUE TITLE
Max number of ticks

### ISSUE THREAD

**Issue by davidkcyip** [recharts/recharts#1433]
## Do you want to request a feature or report a bug?

feature

## What is the current behavior?

No prop to set max number of ticks

## What is the expected behavior?

Would like a prop to set the max number of ticks in XAxis and YAxis so that if there are hundreds of ticks in the chart it doesn't get cluttered. I know there is the interval prop that allows you set the interval of ticks but this does not allow an easy way to limit the number of ticks.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

1.0.0-beta.10

**Comment by pardesiaka08** [comment]
I am also facing the same issue, not able to figure out how to set maximum number of intervals from user side.Please let me know if anyone can help on this.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
