### ISSUE TITLE
Remove random white lines between vertical bars of CartesianGrid

### ISSUE THREAD

**Issue by VictorChen** [recharts/recharts#1435]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
The chart currently draws random white lines between bars, eg:

<img width="563" alt="screen shot 2018-08-18 at 10 18 47 pm" src="https://user-images.githubusercontent.com/1408813/44304805-bed42080-a334-11e8-800d-6682c5354f5c.png">

```jsx
<ResponsiveContainer width="100%" height={300}>
  <LineChart data={data}>
    <XAxis dataKey="name"/>
    <YAxis/>
    <CartesianGrid
      fillOpacity={1}
      vertical
      horizontal={false}
      verticalFill={['black', 'midnightblue']}
      />
    <Line type="monotone" dataKey="pv" stroke="#8884d8" dot={false} />
    <Line type="monotone" dataKey="uv" stroke="#82ca9d" dot={false} />
  </LineChart>
</ResponsiveContainer>
```

You can see the lines move around as you resize the window.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
https://jsfiddle.net/xwLp9v57/1

## What is the expected behavior?
The random white vertical lines should not be rendered

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
v1.1.0

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by gf5901** [comment]
This can be fixed by adding `stroke="none"` to your `CartesianGrid`.
