### ISSUE TITLE
Tooltip formatter

### ISSUE THREAD

**Issue by NoWay1201** [recharts/recharts#144]
Hello,

I'm trying to use formatter from Tooltip, here's my code:
`<Tooltip formatter={(a) => {console.log('asd')}} />`

But my console.log is not working. I want to just format my value properly

**Comment by xile611** [comment]
Hi, @NoWay1201 

It works fine in this [example](http://jsfiddle.net/4sqe4625/).
No tooltip content will be rendered when your mouse is outside the chart. You can mouse enter the chart, and the log will work.

**Comment by NoWay1201** [comment]
It's working now. I don't know, why it wasn't.
