### ISSUE TITLE
How to test tooltip 

### ISSUE THREAD

**Issue by mjhymowitz** [recharts/recharts#1442]
## Do you want to request a feature or report a bug?
feature (if it doesn't exist)

## What is the current behavior?
test for tooltip or way to test tooltip so coverage map returns 100% for testing

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
make react program with LineChart or AreaChart (I'm using both in mine)
put ```<Tooltip formatter={(value, name, props) => "$"+ value.toFixed(2).replace(/\d(?=(\d{3})+\.)/g, '$&,')}/>``` in the chart so values inputed are displayed as money
run test using ```jest --setupTestFrameworkScriptFile=raf/polyfill --coverage```

![chart](https://user-images.githubusercontent.com/9580326/44480361-e27abd80-a5f7-11e8-8e3e-da3612cdb3f5.PNG)

## What is the expected behavior?
want all 100s on the coverage map for LineChart.js and AreaChart.js but I can understand If I have to write one test to do so. Just dont know how to access tooltip to test the formatter

![capture](https://user-images.githubusercontent.com/9580326/44480107-46e94d00-a5f7-11e8-9703-3b6f3f274da8.PNG)

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
don't know about previous versions but I'm using react 16.4.1 on windows 10

**Comment by narsaynorath** [comment]
Were you able to find a suitable solution for this? I'm having trouble testing Tooltips with Jest as well.
