### ISSUE TITLE
Title in tooltip mismatch tickFormatter

### ISSUE THREAD

**Issue by bogutski** [recharts/recharts#1443]
How to set different format to Tooltip label?

## Do you want to request a feature or report a bug?
bug or wrong settings

## What is the current behavior?
![2018-08-22_10-32-34](https://user-images.githubusercontent.com/8984909/44480145-654f4880-a5f7-11e8-86ab-c631cce47069.png)

## If the current behavior is a bug, please provide the steps to reproduce

```javascript 
    <ResponsiveContainer width="100%" aspect={5.0 / 1.0}>
      <LineChart
        data={codewarsAnalytics}
        margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
      >
        <XAxis
          dataKey={'timestamp'}
          tickFormatter={timestamp => moment(timestamp).format('DD MMM')}
        />
        <YAxis />
        <CartesianGrid strokeDasharray="3 3" />
        <Tooltip />
        <Legend />
        <Line
          type="monotone"
          dataKey="data.honor"
          name="Honor"
          strokeWidth={2}
          stroke="#8884d8"
        />
        <Line
          type="monotone"
          dataKey="data.codeChallenges.totalCompleted"
          name="Completed Tasks"
          strokeWidth={2}
          stroke="#82ca9d"
        />
      </LineChart>
    </ResponsiveContainer>
```

## What is the expected behavior?
Label of tooltip should be like in `tickFormatter`

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
    "react": "^16.4.1",    "recharts": "^1.1.0",

**Comment by watsoncj** [comment]
The Tooltip has a [`labelFormatter`](http://recharts.org/en-US/api/Tooltip#labelFormatter) property to customize the format of the label.

```jsx
 <Tooltip labelFormatter={t => new Date(t).toLocaleString()} />
```
