### ISSUE TITLE
Tooltip order is wrong when size > 10 in chrome

### ISSUE THREAD

**Issue by pbdm** [recharts/recharts#1444]
## Do you want to request a feature or report a bug?
bug
## What is the current behavior?
tooltip order is wrong when size > 10 in chrome
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
see https://jsfiddle.net/xqjtetw0/11974/
we got `a, c, d, e, b, g, h, i, j, k, f` when row data is `{ a: 10, b:10 ,c : 10, d: 10, e: 10, f: 10, g: 10, h: 10 , i: 10, j: 10, k: 10}`
## What is the expected behavior?
tooltips must show in right order
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
seems after this commit https://github.com/recharts/recharts/pull/151/commits/da74569392b1a811cd8d0c0fee3ad1890d93ca23

It's not a chrome problem, we need to complete our sort function(not only return -1). more info see: https://stackoverflow.com/questions/23076776/sorting-an-array-of-more-than-10-objects-in-chrome

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
