### ISSUE TITLE
Reference Line not displayed in graph if y value too high

### ISSUE THREAD

**Issue by pengcheng95** [recharts/recharts#1447]
## Do you want to request a feature or report a bug?
bug

## What is the current behavior?
If a reference line y or x value is a lot larger than values displayed on the graph, the graph does not display the line.

## What is the expected behavior?
The reference line is visible on the graph

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.1

**Comment by alaney** [comment]
Here is a repro. Notice the first vertical reference line does not display, however, if you remove one data point it will display.

https://jsfiddle.net/or98swy3/

**Comment by kanestapler** [comment]
Bump. Anyone else have this issue or find a good solution for it?

**Comment by dclorena11** [comment]
Bump! Also experiencing this issue

**Comment by dclorena11** [comment]
@kanestapler I found a fix for you! There's a `alwaysShow` prop you can pass to the `ReferenceLine`

**Comment by pasan9** [comment]
It works but there's a warning that this props is deprecated. `alwaysShow` prop is deprecated, Use `ifOverflow="extendDomain"`. `ifOverflow` also works fine.
