### ISSUE TITLE
React does not recognize the `...` prop on a DOM element

### ISSUE THREAD

**Issue by dbroadhurst** [recharts/recharts#1448]
## Do you want to request a feature or report a bug?
bug

## What is the current behavior?
I see console warnings for prop such as;

React does not recognize the `iconSize` prop on a DOM element
React does not recognize the `verticalAlign` prop on a DOM element
React does not recognize the `chartWidth` prop on a DOM element

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
Any build

## What is the expected behavior?
Run with no warnings

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Chrome, React 16.4.1,recharts 1.1.0

I think the lib could be running into the issues described here
https://reactjs.org/warnings/unknown-prop.html

**Comment by dbroadhurst** [comment]
did this get solved? Any workarounds or is everyone ok with warnings spamming the console?

**Comment by fourlincoln10** [comment]
I ran into this when I added a content prop to a Legend component. I got around it by passing a function instead of an element. 

Instead of this:
```
<Legend content={<div className='total'>Total</div>} />
```

I used:
```
<Legend content={() => <div className='total'>Donation Total</div>} />
```

**Comment by jakubbloksa** [comment]
> I ran into this when I added a content prop to a Legend component. I got around it by passing a function instead of an element.
> 
> Instead of this:
> 
> ```
> <Legend content={<div className='total'>Total</div>} />
> ```
> 
> I used:
> 
> ```
> <Legend content={() => <div className='total'>Donation Total</div>} />
> ```

This just doesn't use the prop parameter, therefore no error, or am I wrong?
This problem for me still persists when you want to make custom Tick for example.
