### ISSUE TITLE
StackedAreaChart colors shifted up by one

### ISSUE THREAD

**Issue by majidalfifi** [recharts/recharts#1449]
## Do you want to request a feature or report a bug?
Bug
See a snapshot of correct and wrong behavior here:
https://www.evernote.com/l/AGjVs4iUUl5HIJjKSGNRSB3im_ctOlFD2ck

## What is the current behavior?

The example at http://recharts.org/en-US/examples/StackedAreaChart and the behavior at the jsfiddle demo linked on the same page are different. The colors of the areas below the curves get shifted up by one.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

This is easy to reproduce.

1. Go the example at http://recharts.org/en-US/examples/StackedAreaChart
2. Click on the jsfiddle demo link provided. 

The image on the example page is the correct behavior and demo show the wrong behavior.
A snapshot is also here https://www.evernote.com/l/AGjVs4iUUl5HIJjKSGNRSB3im_ctOlFD2ck

## What is the expected behavior?

Colors and areas should match

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Not sure if this used to work but I would assume so because the example shown is correct.

**Comment by rarous** [comment]
It worked in 1.0, broken in 1.1

**Comment by ssotangkur-kahuna** [comment]
@xile611,
This error was introduced by this commit: https://github.com/recharts/recharts/commit/80b0174559a8230d494addd53c637a7c5cf69b1a

I tried reverting the changes and that resolves the issue. I'm not sure what issue the commit was trying to resolve.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
