### ISSUE TITLE
Legend Icon Not Rendering

### ISSUE THREAD

**Issue by adrianmc** [recharts/recharts#145]
I'm having a little trouble getting the legend icon to show up properly. Take a look at how my chart is currently displaying, and notice how there is no icon beside where it says "Registered Users":

![screen shot 2016-07-17 at 6 33 00 pm](https://cloud.githubusercontent.com/assets/943555/16900350/f6e6fa10-4c4c-11e6-8b0c-75ad18c9f2b9.png)

I suspect I am not using the `Legend` component correctly, but I am not sure how. The following is the code I am using to generate the above chart:

```jsx
import React from 'react';
import { LineChart, Line, XAxis, YAxis,
  Tooltip, CartesianGrid, Legend } from 'recharts';

const data = [
  { name: 'Mon', pv: 10 },
  { name: 'Tue', pv: 24 },
  { name: 'Wed', pv: 34 },
  { name: 'Thu', pv: 40 },
  { name: 'Fri', pv: 52 },
  { name: 'Sat', pv: 62 },
  { name: 'Sun', pv: 70 },
];

const Component = () =>
  <LineChart
    width={600}
    height={240}
    data={data}
    margin={{ top: 20, right: 120, left: 20, bottom: 5 }}
  >
    <XAxis dataKey="name" />
    <YAxis />
    <CartesianGrid strokeDasharray="3 3" />
    <Tooltip />
    <Legend payload={[{ value: 'Registered Users', type: 'line', id: 'pv' }]} />
    <Line type="monotone" dataKey="pv" stroke="#8884d8" />
  </LineChart>;

export default Component;
```

**Comment by xile611** [comment]
@adrianmc You have two methods to solve your problem.

One is that you need to add `color` in your payload of Legend. Otherwise icon will not be filled, so you can't see the icon.

```
<Legend payload={[{ value: 'Registered Users', type: 'line', id: 'pv', color: '#8884d8' }]} />
```

Another is using the default `Legend` which only need to remove `payload` in `Legend` and add `name` in `Line`.

```
<LineChart
    width={600}
    height={240}
    data={data}
    margin={{ top: 20, right: 120, left: 20, bottom: 5 }}
  >
    <XAxis dataKey="name" />
    <YAxis />
    <CartesianGrid strokeDasharray="3 3" />
    <Tooltip />
    <Legend />
    <Line name="Registered Users'" type="monotone" dataKey="pv" stroke="#8884d8" />
  </LineChart>
```

**Comment by adrianmc** [comment]
@xile611 Thanks. I wasn't aware of the name property because I didn't see it in the examples. Maybe it would be a good idea to put it in some of the examples? All of the examples simply use `pv` and `pu`.

**Comment by xile611** [comment]
@adrianmc Yeah, it's a good idea. I'll update the examples.
