### ISSUE TITLE
Can't Used the components of Brush?

### ISSUE THREAD

**Issue by Rain120** [recharts/recharts#1451]
## Do you want to request a feature or report a bug?
It always has an error when I used the component of Brush in the demo display.

## What is the current behavior?

![image](https://user-images.githubusercontent.com/20939839/44697904-780ec500-aab0-11e8-9da1-d8fa0a881b51.png)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
There is my repo: https://codesandbox.io/s/139omxrxr4

## What is the expected behavior?
I just want to design the charts be sync to show the analysis result at the same time area, just like the pic show.
![image](https://user-images.githubusercontent.com/20939839/44698072-084d0a00-aab1-11e8-80df-82000e5bc549.png)

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
![image](https://user-images.githubusercontent.com/20939839/44698013-d3d94e00-aab0-11e8-8ff3-c97fb22be063.png)
recharts 1.1.0

**Comment by Rain120** [comment]
Find，no one replies to me for the solution, and I should fix by myself.

[Solution Code](https://codesandbox.io/s/139omxrxr4)

After a week of learning and code review, I had found the error with my code.

First, we found the error at line 'node_modules/recharts/lib/chart/generateCategoricalChart.js:1393' from the console.
![image](https://user-images.githubusercontent.com/20939839/44977176-e6182800-af99-11e8-82c2-f999e41a0e84.png)

You can see, at the file named generateCategoricalChart. Find, we will jump the file
![image](https://user-images.githubusercontent.com/20939839/44977137-cb45b380-af99-11e8-9469-acccb151b65e.png)

Second, we will clone the code from the recharts, and open the file named generateCategoricalChart, found the function about handleReceiveSyncEvent. According to previous analysis, we kown the error 
occurred in tooltipTicks.

From the code, We found the way tooltipTicks are assigned.

![image](https://user-images.githubusercontent.com/20939839/44977683-393eaa80-af9b-11e8-90b2-cc02a5f7e223.png)

![image](https://user-images.githubusercontent.com/20939839/44977700-4360a900-af9b-11e8-9fa7-9db9db7920ef.png)

![image](https://user-images.githubusercontent.com/20939839/44979092-c59e9c80-af9e-11e8-9e39-5f15904fd83e.png)

**Comment by peteruithoven** [comment]
Maybe rename this into something a bit more informative like "Can't use only Brush in chart"?
