### ISSUE TITLE
Bug: ErrorBars are missing and/or drawn incorrectly

### ISSUE THREAD

**Issue by klandell** [recharts/recharts#1453]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
ErrorBars are drawn improperly.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
The issue I describe can be seen directly in the API documentation for ErrorBar on the recharts.org page. (The direct link is http://recharts.org/en-US/api/ErrorBar, but the website router doesn't work properly)

The code on the API page for Error bar as seen here:

```javascript
const data = [
  { x: 45, y: 100, z: 150, errorY: [30, 20], errorX: 5 },
  { x: 100, y: 200, z: 200, errorY: [20, 30], errorX: 3 },
  { x: 120, y: 100, z: 260, errorY: 20, errorX: [5, 3] },
  { x: 170, y: 300, z: 400, errorY: [15, 18], errorX: 4 },
  { x: 140, y: 250, z: 280, errorY: 23, errorX: [6, 7] },
  { x: 150, y: 400, z: 500, errorY: [21, 10], errorX: 4 },
  { x: 110, y: 280, z: 200, errorY: 21, errorX: [5, 6] },
];

<ScatterChart width={730} height={250}
  margin={{ top: 20, right: 20, bottom: 0, left: 20 }}>
  <CartesianGrid />
  <XAxis dataKey="x" type="number" name="stature" unit="cm" />
  <YAxis dataKey="y" type="number" name="weight" unit="kg" />
  <Tooltip />
  <Scatter name="A school" data={data} fill="#ff7300">
    <ErrorBar dataKey="errorY" width={4} strokeWidth={2} stroke="green" direction="y" />
    <ErrorBar dataKey="errorX" width={0} strokeWidth={1} stroke="blue" opacity={0.8} direction="x" />
  </Scatter>
  <Legend/>
</ScatterChart>
```

produces an output of:
![image](https://user-images.githubusercontent.com/15675184/44744378-072cd480-aad3-11e8-9c7b-b6527f2e66f1.png)

I can't wrap my head around how this code could possibly produce error bars that look like this.  Firstly, there are no X error bars drawn, even though errors are defined.  Secondly, taking the first data point as an example `{ x: 45, y: 100, z: 150, errorY: [30, 20], errorX: 5 }` I would expect the Y error bar to stretch from y = 70 to y = 120.  However, it appears to actually be a line from ~140 to ~190.

To make things even more confusing, it appears to work exactly as expected for line charts.  See https://jsfiddle.net/k81an5c7/.  I believe that this is an issue in both scatter and bar charts based on experiences I'm having in my application code.

## What is the expected behavior?
I expect the drawn error bars to reflect the values that define them.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Tested in v1.1.0 via Chrome.

**Comment by camray** [comment]
This happened to me also and was quite confusing. I switched to a line chart for the same reason.
This can't be intentional, but if it is the documentation for ErrorBar is very sparse and even shows the graph above.
