### ISSUE TITLE
Incorrect ReferenceLine position

### ISSUE THREAD

**Issue by stanislav-kholodar** [recharts/recharts#1457]
ReferenceLine displayed correct only using it with LineChart. How to center ReferenceLine in this case?
https://jsfiddle.net/wpfnfmh7/1071/

**Comment by AdityaAnand1** [comment]
Any updates? My ReferenceLine seems to randomly disappear when there are more than ~30 or so data points in the chart.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
