### ISSUE TITLE
Radar.js, typo in prop name (currently it's `playload` instead of `payload`)

### ISSUE THREAD

**Issue by andrevinsky** [recharts/recharts#1459]
## Do you want to request a feature or report a bug?
It's a bug. Nature: typo.

## What is the current behavior?
When rendering the dots in the Radar, the payload property is misnamed as `playload`

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

Link to source:
https://github.com/recharts/recharts/blob/master/src/polar/Radar.js#L163

## What is the expected behavior?
Prop should be named `payload` (pay, not play)

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
n/a

Again, the source is here:
https://github.com/recharts/recharts/blob/master/src/polar/Radar.js#L163

![image](https://user-images.githubusercontent.com/932990/44904412-edc89a00-ad17-11e8-9fc8-df5618903716.png)

**Comment by robd003** [comment]
Fixed in this pull request: https://github.com/recharts/recharts/pull/1460

**Comment by robd003** [comment]
Fix has been merged, you can close this issue.

**Comment by robd003** [comment]
Just got this fix merged, feel free to close the issue @andrevinsky
