### ISSUE TITLE
Can't set different formatting on different axis values in tooltip on ScatterChart

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#1461]
## Do you want to request a feature or report a bug?
bug (or maybe I'm missing something)

## What is the current behavior?
There does not appear to be a way to format different axis values differently in a tooltip on a ScatterChart. "labelFormatter" is apparently meaningless for a ScatterChart. Using "formatter" works, in that the values are thus formatted, but this produces the same formatting for all axis values.

## What is the expected behavior?
Ideally, there should be a way to format each axis separately, or better yet, have the tooltip "inherit" the "tickFormatter" formatting of the respective axis. Separately from this, it should be possible to set the "name" of an axis explicitly to "false" in order to not display a label and colon in the tooltip for that axis (having a "value label" in the tooltip isn't always preferred).

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Latest version of recharts; all browsers. Not sure if this ever worked.

**Comment by franz101** [comment]
same here :(
