### ISSUE TITLE
CartesianAxis on charts with large datasets causes performance issues with the default interval

### ISSUE THREAD

**Issue by lightsinthesky** [recharts/recharts#1465]
## Do you want to request a feature or report a bug?

Bug

## What is the current behavior?

With a large dataset (~10000 items) rendering on a simple line chart,  adding an XAxis with the default interval (preserveEnd) results in a chart taking several seconds to render (depending on cpu). Drilling into the perf you can see that getTicksEnd is the blocking function (more specifically getStringSize which is forcing reflow)

<img width="715" alt="screen shot 2018-09-04 at 2 47 39 pm" src="https://user-images.githubusercontent.com/8852073/45048148-7f564580-b051-11e8-8618-10ff447cdd06.png">

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

goto : https://jsfiddle.net/dbwnv9fp/15/ and "run" then add interval={1000} to the XAxis and notice the speed increase.

## What is the expected behavior?

adding an xaxis should not increase the render time by 4-5x for large datasets.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

recharts 1.1.0 - chrome latest (osx and windows).

**Comment by weiyuxuan** [comment]
Try adding a specific key on the XAxis component, which can prevent XAxis to reRender.

**Comment by m3h0w** [comment]
@lightsinthesky thank you so much for reporting this - I've been struggling so much with the performance I almost changed the library but maybe with setting the interval somehow based on the viewport I can hack around this issue.

@xile611 why is this issue closed?

**Comment by Eric24** [comment]
> Try adding a specific key on the XAxis component, which can prevent XAxis to reRender.

If you mean setting the `dataKey` property, that is something we always do. I has no effect. The root issue is the getStringSize() function.

**Comment by weiyuxuan** [comment]
> > Try adding a specific key on the XAxis component, which can prevent XAxis to reRender.
> 
> If you mean setting the `dataKey` property, that is something we always do. I has no effect. The root issue is the getStringSize() function.

I mean the `key` property  instead of the `dataKey` property.

**Comment by Eric24** [comment]
The `key` property? I don't see that in the documentation. What does the `key` property do?
