### ISSUE TITLE
Routing in Recharts documentation 404's

### ISSUE THREAD

**Issue by TaeKimJR** [recharts/recharts#1466]
## Do you want to request a feature or report a bug?
Report a bug

## What is the current behavior?
When accessing Recharts documentation directly by going to [http://recharts.org/en-US/api/RadialBarChart](http://recharts.org/en-US/api/RadialBarChart), I get a `404`. This happens for all pages except the root - [http://recharts.org/](http://recharts.org/).

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
1. Go to [http://recharts.org/en-US/api/RadialBarChart)](http://recharts.org/en-US/api/RadialBarChart))
2. Receive `404`

## What is the expected behavior?
I should be routed to the RadialBartChart documentation, or any other child routes.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Chrome Version 68.0.3440.106 (Official Build) (64-bit)
MacOS High Sierra

**Comment by thomasparsons** [comment]
I too get this, on every page - so I can not send links to people, or bookmark pages

**Comment by xile611** [comment]
This has been fixed.
