### ISSUE TITLE
How to fix active index of tooltip?

### ISSUE THREAD

**Issue by Eijun** [recharts/recharts#1467]
## Do you want to request a feature or report a bug?
request a feature

## What is the expected behavior?
I have been trying to fix active index of tooltip with click event like stop the chart world. I'm using custom tooltip component so I tried to implement this using "shouldComponentUpdate" in custom tooltip component. But it was not working well. Is there any way that implement this functionality in Recharts? If not, I want to request this feature. I need this feature for looking at a lot of chart's tooltip concurrently.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts version: 1.2.0
browser: Chrome 68.0.3440.106 (64bit)

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.

**Comment by seiyab** [comment]
I also want the feature.
My current workaround is here.
But fixing active dots is very hard.
```tsx
import * as React from 'react';
import { Tooltip, TooltipProps } from 'recharts';

type CustomProps = {
  fixed?: boolean;
};

type Props = TooltipProps & CustomProps;

export const CustomTooltip: React.FC<Props> = ({ fixed, ...props }) => {
  const savedProps = React.useRef(props);
  const propsToUse = fixed ? savedProps.current : props;
  React.useEffect(() => {
    if (!fixed) {
      savedProps.current = props;
    }
  });
  return <Tooltip {...propsToUse} />;
};

CustomTooltip.displayName = Tooltip.name;

export default CustomTooltip;
```
