### ISSUE TITLE
domain dataMin and ReferenceAreas not working together

### ISSUE THREAD

**Issue by jsmith-phoenix** [recharts/recharts#1468]
## Do you want to request a feature or report a bug?
Bug Report
## What is the current behavior?
if you use the dataMin for the Range on a scatter chart you will NOT see the reference areas show up even when the area IS within the bounds of the domain range.

If you hardcode the min of the domain to a good value all of your ranges are inside they will show up.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

const {ScatterChart, Scatter, XAxis, YAxis, CartesianGrid, ReferenceArea, Tooltip, Legend} = Recharts;
const data = [{x: 100, y: 200, z: 200}, {x: 120, y: 100, z: 260},
                  {x: 170, y: 300, z: 400}, {x: 140, y: 250, z: 280},
                  {x: 150, y: 400, z: 500}, {x: 110, y: 280, z: 200}]

const SimpleScatterChart = React.createClass({
	render () {
  	return (
    	<ScatterChart width={400} height={400} margin={{top: 20, right: 20, bottom: 20, left: 20}}>
      	<CartesianGrid />
        <XAxis dataKey={'x'} type="number" name='stature' unit='cm' domain={['dataMin', 'dataMax']} />
      	<YAxis dataKey={'y'} type="number" name='weight' unit='kg'/>
        <Scatter name='A school' data={data} fill='#8884d8'/>
      	<Tooltip cursor={{strokeDasharray: '3 3'}}/>
          <ReferenceArea x1={150} x2={180} y1={200} y2={300} stroke="red" strokeOpacity={0.3} />

      </ScatterChart>
    );
  }
})

ReactDOM.render(
  <SimpleScatterChart />,
  document.getElementById('container')
);

## What is the expected behavior?
- you can use dataMin for the Range of a scatter 
- a range within the dataMin and dataMax will show up.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
"recharts": "^1.2.0",

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
