### ISSUE TITLE
Line chart with big difference in data value

### ISSUE THREAD

**Issue by zeeshan774r** [recharts/recharts#1469]
When using linechart with big difference in data value suppose first line receiveing in range of 5500, and second line recieving in range of 50 then  second line didnt have any visiblity and it sticking to the base line(x-axis)...How to overcome this situation???

**Comment by DiagoSmith** [comment]
+1

**Comment by ra89fi** [comment]
+1

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
