### ISSUE TITLE
What can modify the starting point ?

### ISSUE THREAD

**Issue by squll1** [recharts/recharts#147]
![Alt text](http://cfile26.uf.tistory.com/image/24409948578C91583446EB "0 start")
![Alt text](http://cfile29.uf.tistory.com/image/22470150578C9268247AC5 "0 start")
The starting point of the chart is zero .
What can modify the starting point ?

**Comment by xile611** [comment]
@squll1  Of course, you can modify the starting point by [domain](http://recharts.org/api#YAxis) in `YAxis`.

**Comment by squll1** [comment]
@xile611 Thank you :)
