### ISSUE TITLE
Render custom component inside Chart

### ISSUE THREAD

**Issue by dariuszpaluch** [recharts/recharts#1470]
## Do you want to request a feature or report a bug?
request a feature

## What is the current behavior?
Custom component pass by children in Chart is ignore in render method: `renderByOrder`.

## What is the expected behavior?
All components pass to Chart will render in svg with props like (width, height, ...others)

**Comment by PetroPavlenko** [comment]
I have done close enough to this by
```
export const axis = () => [
    <XAxis
        key="XAxis"
        dataKey="legend"
        axisLine={false}
        tickLine={false}
    />,
    <YAxis
        key="YAxis"
        axisLine={false}
        tickLine={false}
    />,
]
```
and in chart
```
{axis()}
```
As it is filtered by renderByOrder
Probably that can help you some how

**Comment by gaurav5430** [comment]
@PetroPavlenko returning an array is a great hack.
(Of course, needing to call it as a function instead of as a React component is ugly, but I think returning an array opens a whole lot of possibilites for Custom components)

**Comment by gaurav5430** [comment]
Since, we are not rendering this as a React component anymore, I suspect if this would have problems with React state and lifecycle, though any basic example like the one above is fine.
