### ISSUE TITLE
Custom XAxis Tick Component

### ISSUE THREAD

**Issue by jibin23** [recharts/recharts#1471]
![issue-customtick](https://user-images.githubusercontent.com/6236473/45359175-5a317c00-b5e9-11e8-8d9c-4df108fdf7cc.png)

This is a high fidelity mockup that I am trying to re-create as a recharts component. The data is a list of objects having value and the corresponding unix timestamp:

```
const timeData = [
  { value: 14, time: 1536310615 },
  { value: 0, time: 1548497015},
  { value: 0, time: 1560683415 },
  { value: 26, time: 1572869815 }
]
```
 

I have the following Setup:

```
   <XAxis
              (other props)
              dataKey="time"
              tick={
                <CustomXAxisTick
                  style={{
                    fill: "#BCBCBC",
                    fontSize: "12px",
                    fontFamily: "Montserrat",
                    fontWeight: 600,
                    lineHeight: "18px"
                  }}
                  labelFormatter={this.labelFormatter}
                />
              }
            />
```
Which accepts a fn called labelFormatter, which uses momentjs to format the unixTimestamp
`  labelFormatter = unixTime => {
    return moment.unix(unixTime).format("ll");
  };`

The CustomXAxisTick Component is:
```
const CustomXAxisTick = props => {
  console.log(props.payload.value);
  return <Text {...props}>{props.labelFormatter(props.payload.value)}</Text>;
};
```

Which yields:
![outcome](https://user-images.githubusercontent.com/6236473/45359922-a978ac00-b5eb-11e8-9d8e-66d1a6ae0dd7.png)

### Question:
How do I put the year on a new line and style it separately?
How can I insert more elements like images, icons etc as siblings?

If I add the year in the <Text> along with the value, they get seperated by comma's automatically.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by eyalgromzin** [comment]
@jibin23 hi, i can see youre returning <Text {...props}>{props.labelFormatter(props.payload.value)}</Text>;
are you using react native ? 
because trying to return a div or a span does nothing.
thnx
