### ISSUE TITLE
Composed chart - Select multiple Bars to get total data ( number value ) in tooltip

### ISSUE THREAD

**Issue by kasarlavinaysrivastav** [recharts/recharts#1472]
## Do you want to request a feature or report a bug?
Request a feature.

## What is the current behavior?
Can select only one bar at any given point of time, and that single selection shows data values in Tooltip. 

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
1. Once ComposedChart is rendered. 
2. Roll over/ Mouse over the bar, that selects one bar everytime it is mouseovered. 
3. Values are shown in the tooltip. 

## What is the expected behavior?
1. On mouse click, select the bar and that way I want to select multiple bars at the same time and the total sum values should display in the tooltip. 

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
"recharts": "^1.0.0-beta.10",
OS: Mac

**Comment by kasarlavinaysrivastav** [comment]
Any update on this issue Folks? Appreciate any response, thanks.

**Comment by xile611** [comment]
Sorry, not supported yet. It's recommended to use customized `content` of `Tooltip` to cover default tooltip.
