### ISSUE TITLE
Is there a way to disable zoom while playing with brush?

### ISSUE THREAD

**Issue by farhan-sauce** [recharts/recharts#1474]
## Do you want to request a feature or report a bug?
- Feature request

## Question
I want to achieve [something like this](https://bl.ocks.org/mbostock/34f08d5e11952a80609169b7917d4172). Is there a way to have one stable tiny chart with Brush and render another chart on base of selected region?
![screen shot 2018-09-13 at 2 11 00 pm](https://user-images.githubusercontent.com/39295560/45488131-a3580c00-b760-11e8-9769-4dd5db75e0a3.png)

As you can see in image there are 2 charts one is stable with brush and another is result of the selected region.

Thanks.

**Comment by gajus** [comment]
@farhan-sauce What solution did you come up with at the end?

**Comment by gajus** [comment]
@xile611 @farhan-sauce What solution did you come up with at the end?

**Comment by farhan-sauce** [comment]
@gajus Checkout this solution: https://github.com/farhan687/chart-test 
I am not sure if it covers all the cases.
