### ISSUE TITLE
Adding xAxisId to <XAxis> crashes with JS error

### ISSUE THREAD

**Issue by DeadcatDev** [recharts/recharts#1476]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
Crashes with bug:
![error](https://user-images.githubusercontent.com/15237149/45559425-ba6f2a80-b842-11e8-934e-de4e164e5648.png)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
https://jsfiddle.net/f3muaogw/
## What is the expected behavior?
To work - i was trying to user 2 XAxis when found it.
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Newest (modyfied ReCharts example) - any, just JS error.

**Comment by rdml** [comment]
@DeadcatDev I'm not a dev but I ran into this issue. Turns out its the naive implementation underneath is expecting the id really to be the index of the declared xAxis from a list of Axes.

I was able to get something other than 0 with:
       <XAxis dataKey="name" orientation="top" xAxisId="0"/>
       <XAxis dataKey="name" orientation="bottom" xAxisId="1"/>
(which was what I was trying to do; show a top and bottom x-axis) Hope that helps you.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by jzeilmann93** [comment]
The first xAxis you use should have a xAxisId="0", the second should have xAxisId="1", and so on.
