### ISSUE TITLE
"You do not have permission to update this wiki."

### ISSUE THREAD

**Issue by RLDoor3** [recharts/recharts#1477]
Trying to ad my company into this wiki post and keep getting a "You do not have permission to update this wiki."

Page is:
https://github.com/facebook/react/wiki/Sites-Using-React

Sites Using React
Tom Esterez edited this page on Jan 19 · 1049 revisions
If you use React, don't be shy – edit this page!

**Comment by paulmelnikow** [comment]
Hi there! This is the issues page for a totally independent library called recharts, so it's definitely not the right place to raise that issue.

**Comment by RLDoor3** [comment]
lol Lazy solution but that works lol

**Comment by DeveloperMujtaba** [comment]
@RLDoor3  Can you explain what u did to fix the issue? Thank you!
