### ISSUE TITLE
LabelList is blinking

### ISSUE THREAD

**Issue by rodolfobarretoweb** [recharts/recharts#1478]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
I make a video to show: https://s.nimbusweb.me/share/2084967/28iipnqxowstgg57ehry

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
```
import React, { PureComponent } from 'react';
import PropTypes from 'prop-types';
import { BarChart, LabelList, Bar, XAxis, YAxis, ResponsiveContainer } from 'recharts';

class DailySteps extends PureComponent {
  static propTypes = {
    data: PropTypes.instanceOf(Array).isRequired
  };

  render() {
    return(
      <ResponsiveContainer minWidth="100%" height={400}>
        <BarChart margin={{ top: 10 }} data={this.props.data}>
          <XAxis dataKey="date" />
          <YAxis dataKey="steps" />

          <Bar dataKey="steps" fill="#666">
            <LabelList dataKey="steps" position="top" />
          </Bar>
        </BarChart>
      </ResponsiveContainer>
    );
  }
}

export default DailySteps;
```

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts: 1.2.0
Mac OS

**Comment by AnjaliSing** [comment]
Facing the same issue.

Was any solution found?

**Comment by theanhmx** [comment]
When you declare your Bar, add the prop isAnimationActive and set it to false
https://stackoverflow.com/questions/55722306/label-list-is-not-showing-in-recharts

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
