### ISSUE TITLE
Understanding the Interval Property

### ISSUE THREAD

**Issue by adrianmc** [recharts/recharts#148]
I'm having trouble understanding how the CartesianAxis interval property works.

My main goal is to make sure that every number on the scale must be an integer (no decimal places allowed).

Unfortunately, when I set:

```jsx
<YAxis interval={0} />
```

I get this:

![screen shot 2016-07-19 at 1 57 02 am](https://cloud.githubusercontent.com/assets/943555/16926738/43fdee28-4d54-11e6-93b9-9da03e33a1f1.png)

But when I set:

```jsx
<YAxis interval={1} />
```

I get:

![screen shot 2016-07-19 at 1 57 44 am](https://cloud.githubusercontent.com/assets/943555/16926756/5a57fbdc-4d54-11e6-899c-22599cb14cb2.png)

And when I set:

```jsx
<YAxis interval={2} />
```

I get:

![screen shot 2016-07-19 at 1 59 56 am](https://cloud.githubusercontent.com/assets/943555/16926789/855140dc-4d54-11e6-901d-07e819c414e4.png)

I find this to be very strange, because I was expecting the interval prop to mean the base number for ticks to be generated.

For example:

- For `interval={1}`, I would expect: `0, 1, 2, 3, 4, 5, 6, 7, 8`
- For `interval={2}`, I would expect: `0, 2, 4, 6, 8, 10, 12, 14`

Can I get some explanation for how the `interval` prop actually works. I tried to read through the source code, but it was a little confusing. I'll try again tomorrow, but if you have a better explanation, I could rephrase it for you and submit a PR to the docs.

**Comment by xile611** [comment]
@adrianmc The default value of `tickCount` in `YAxis` is 5 which means that five ticks will be generated in a y-axis. If the `interval` is set to 1, then the first tick, the third tick and the fifth tick will be showed, other ticks will be hidden.

It's just like the `tickInterval` in [HighCharts](http://api.highcharts.com/highcharts#xAxis.tickInterval). Maybe `tickInterval` is a better choice.

**Comment by adrianmc** [comment]
I see, interesting.

What do you suggest for ensuring tick values are integers only?

**Comment by adrianmc** [comment]
Apparently HighCharts has an "allowDecimals" option. Can we have something similar?

Docs: http://api.highcharts.com/highcharts#yAxis.allowDecimals
SO Question: http://stackoverflow.com/questions/14238780/how-to-show-only-integer-values-on-yaxis-of-highchart

**Comment by xile611** [comment]
@adrianmc 
There are two ways to solve such kind of accuracy problem.

One way is to add `allowDecimals` option like HighCharts.
Another way is to tweak calculative strategy of step between ticks which should be integer when the minimum and maximum value of `YAxis` are integers.

I'm more inclined to the second way for the convenience of developers.

**Comment by xile611** [comment]
Fixed in version 0.12.6.

**Comment by adrianmc** [comment]
@xile611 
I'm not sure I understand. I looked at the changelog of 0.12.6, but I don't see where this is fixed? Can you give a quick example of how to set the YAxis to integers only? Thanks.

**Comment by xile611** [comment]
I optimize the step calculation in [recharts-scale](https://github.com/recharts/recharts-scale/blob/master/src/getNiceTickValues.js#L44). Integers can't be guaranteed for all the input, but the ticks would be more reasonable.

**Comment by adrianmc** [comment]
@xile611
Wouldn't it be a good idea to have an option to guarantee integers? There are a lot of good use cases for this, such as when you are counting the number of people, it would be strange to have a tick that says 2.5 people.

**Comment by xile611** [comment]
@adrianmc  OK! recharts-scale can generate readable ticks in the most time. We would add a props `allowDecimals ` to `XAxis` and `YAxis`, which will have a default value `true`.

**Comment by thienanle** [comment]
> For `interval={1}`, I would expect: `0, 1, 2, 3, 4, 5, 6, 7, 8`
For `interval={2}`, I would expect: `0, 2, 4, 6, 8, 10, 12, 14`

+1 on this

**Comment by wyaeld** [comment]
Just in case people come across this, it was actually implemented and works.

**Comment by adrianmcli** [comment]
Awesome!

**Comment by gaurav5430** [comment]
`allowDecimals={false}` does not seem to work when domain is specified like this:

```
<YAxis
  domain={['dataMin', 'dataMax']}
  allowDecimals={false}  
/>
```

but works when:
```
<YAxis
  domain={['dataMin', 'auto']}
  allowDecimals={false}  
/>
```

example here: https://jsfiddle.net/up3a1t92/
