### ISSUE TITLE
yAxis tick labels are clipped on a vertical bar chart

### ISSUE THREAD

**Issue by lidermanrony** [recharts/recharts#1480]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
yAxis labels (if long) get clipped
![image](https://user-images.githubusercontent.com/199509/45653680-bd119000-ba8d-11e8-970b-ea971161e4df.png)
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal 
https://codesandbox.io/s/232wz70p8p
## What is the expected behavior?
The expected behavior is - show the entire text of yAxis tick values
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
This happens in all browsers

**Comment by lidermanrony** [comment]
thanks @euan-gwd - but i don't know in advance the amount of margin i'm going to need... I was expecting recharts to figure this out all on its own

**Comment by lidermanrony** [comment]
ended up going through all my tick labels, calling 
[measureText](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/measureText) for each of them, taking the max, and setting the margin accordingly

**Comment by scotthovestadt** [comment]
@lidermanrony Thanks for the tip. For future visitors, here is an implementation that's working for me:

```js
ctx: CanvasRenderingContext2D;

measureText(text: string) {
    if (!this.ctx) {
        this.ctx = document.createElement('canvas').getContext('2d')!;
        this.ctx.font = '12px "Helvetica Neue"';
    }

    return this.ctx.measureText(text).width;
}

render() {
    const layout = 'vertical';

    // Horizontal tick labels are clipped on vertical chart.
    // https://github.com/recharts/recharts/issues/1480
    let leftMargin = 0;
    if (layout === 'vertical') {
        for (const value of values) {
            const textWidth = this.measureText(value.name);
            if (textWidth > leftMargin) {
                leftMargin = textWidth;
            }
        }

        // We have pixel-perfect measurements for the width of our labels, but we also need to account for the default spacing.
        leftMargin = Math.max(0, leftMargin - 50);
    }

    // Within the chart components:
    return <BarChart data={values} layout={layout} margin={{ left: leftMargin }}>;
}
```

**Comment by ytus** [comment]
Another workaround, that can help when the labels are not too long or all of simillar length, is to show the overflowing content (as suggested here https://github.com/recharts/recharts/issues/266#issuecomment-257968244): 

~~~css
.recharts-surface {
    overflow: visible;
}
~~~

And you can combine it with moving the labels a bit to the left:

~~~css
svg > g.recharts-layer.recharts-cartesian-axis.recharts-yAxis.yAxis {
    transform: translate(0.5rem, 0);
  }
~~~

**Comment by xile611** [comment]
Related to #2027

**Comment by pavanjn** [comment]
Added a width in the tick of the YAxis with the left margin to the bar chart.

`<BarChart data={ data } layout="vertical" margin={{ top: 5, right: 0, left: 200, bottom: 5  }}>`

`<YAxis type="category" dataKey="name" tick={{ fontSize: 14, width: 250 }} />`

**Comment by JonasBa** [comment]
@ scotthovestadt @lidermanrony just a small improvement as I just stumbled on this -> in case of retina screens, you will need to divide the measured width with window.devicePixelRation (provided you do not initialize the canvas with the appropriately scaled width and height when measuring as described [here](https://www.html5rocks.com/en/tutorials/canvas/hidpi/)). 

In my case, this resulted in a more accurate measurement, see screenshot (the product is internal, so excuse me for the poor quality, it's best I could do for now) 

Before (the margin is double the width)
<img width="183" alt="CleanShot 2020-12-16 at 12 11 40@2x" src="https://user-images.githubusercontent.com/9317857/102341271-e5073b00-3f97-11eb-8e00-e24e2b04a3ec.png">

After:
<img width="124" alt="CleanShot 2020-12-16 at 12 10 33@2x" src="https://user-images.githubusercontent.com/9317857/102341186-c2752200-3f97-11eb-9ec4-3cf0300e4ed9.png">

**Comment by Janaka-Steph** [comment]
My solution

```
 const yAxis = document.getElementsByClassName('recharts-cartesian-axis recharts-yAxis')[0];
 const yAxisWidth = (yAxis as SVGGraphicsElement)?.getBBox().width;
```

```
<BarChart>
    <YAxis width={yAxisWidth} />
    ...
</BarChart>
```
