### ISSUE TITLE
Can you do a smooth curve inside a ScatterChart? 

### ISSUE THREAD

**Issue by Tzikas** [recharts/recharts#1482]
I have a scatter plot, and a prediction line and it's working fine, but I'd like the line to be smooth, not jagged, is that possible?  

```       
return (
            <div>
                         
            <ScatterChart  width={600} height={400} margin={{top: 20, right: 20, bottom: 20, left: 20}}>
                <XAxis type="number" dataKey={'date'} tickFormatter={tickFormatter} name='date' domain={['dataMin', 'dataMax']}  unit=''/>
                <YAxis type="number" dataKey={'retention'} name='retention' unit=''/>
                <ZAxis range={[100]}/>
                <CartesianGrid />
                <Tooltip cursor={{strokeDasharray: '3 3'}}/>
                <Legend/>
                
             **<Scatter name='Predicted R' data={prediction} fill='green' r={20} line />**
                {plots}
             <Scatter data={this.props.data} fill={'red'} />
                
            </ScatterChart>
            </div>
        );
```

**Comment by valstu** [comment]
This should do the trick
`<Scatter name='Predicted R' data={prediction} fill='green' r={20} lineJointType = 'monotoneX' line />`

**Comment by xile611** [comment]
@Tzikas  @valstu had given the answer.

**Comment by tran-simon** [comment]
Is there a way to do this with a radar chart? I want to link the points with a curve

**Comment by ckifer** [comment]
@tran-simon can you give an example of what you mean?

**Comment by tran-simon** [comment]
@ckifer 

My radar chart:

<img width="400" src="https://github.com/recharts/recharts/assets/8755930/34680b1a-7e63-45fc-a440-caf4cb3da04f">

I would like the points to be connected with curves instead of straight lines, like this scatter chart:

<img width="282" alt="image" src="https://github.com/recharts/recharts/assets/8755930/19a8fc08-92f0-436b-a2af-86b11236d28f">

**Comment by ckifer** [comment]
`Polygon` is used for `Radar` instead of `Curve`
https://github.com/recharts/recharts/blob/master/src/polar/Radar.tsx#L261

So I don't think this is possible
