### ISSUE TITLE
Label is preventing Tooltip invocation

### ISSUE THREAD

**Issue by michalsvorc** [recharts/recharts#1483]
## Do you want to request a feature or report a bug?
I want to report a bug.
## What is the current behavior?
Label is preventing Tooltip invocation for Cell rendered under/behind the Label.
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
In official example for ScatterChartWithLabels: https://jsfiddle.net/alidingling/gvsspn0h/
When you remove the <LabelList/> and rerun the fiddle, <Tooltip/> will be invoked upon hovering over the Scatter dot.
## What is the expected behavior?
Label should have the same listener and upon hovering invoke <Tooltip/> with the same data payload as the element which the Label belongs to.
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Tested with latest Chrome and Firefox on Windows 10. I'm new to Recharts, dunno.

**Comment by arcthur** [comment]
you can use position to change demo, https://jsfiddle.net/gvsspn0h/269/

**Comment by michalsvorc** [comment]
Thanks, but we're going for this visualization of dots:
http://wpsites.net/wp-content/uploads/2014/02/with-box-shadow.png
where value of the dot is always inside the circle. 

Users by nature always tend to point directly to the center of the dot when they want do display the tooltip. I guess this is pretty common visualization of dots/bubbles, would be nice to have this possibility.

**Comment by michalsvorc** [comment]
If it's not possible, then the Tooltip component in example https://jsfiddle.net/alidingling/gvsspn0h/ is obsolete.

**Comment by arcthur** [comment]
you can custom the shape of scatter with react component. this is the api, http://recharts.org/en-US/api/Scatter#shape

**Comment by michalsvorc** [comment]
Will try, thanks

**Comment by AntonSmatanik** [comment]
Solution was not so simple, it was little bit tricky, but still logical. If we can't do anything with way how is SVG rendering elements, can't use z-index, we still can set them opacity.

    const CustomizedCircle = props => {
        const {
            cx, cy, fill, size, z,
        } = props;
        const radius = size / 70;
        const value = z;
    
        return (
            <svg width={radius} height={radius} style={{overflow: 'visible'}}>
                <text style={{fontWeight: FONT_WEIGHT, fontSize: FONT_SIZE}} x={cx} y={cy + 5} textAnchor="middle">{value}</text>
                <circle style={{opacity: OPACITY}} cx={cx} cy={cy} r={radius} fill={fill} />
            </svg>
        );
    };

So we are first rendering the text, then we render the circle and to see text beneath the circle we are setting the circle some kind of opacity.
