### ISSUE TITLE
Line docs missing 'renderDot' function signature and CustomizedDotLineChart examples gives 404

### ISSUE THREAD

**Issue by madwill** [recharts/recharts#1484]
Would it be possible for anybody to share an example of 'renderDot' function on Line Cartesian Component ?

It appear it is not in the doc and the example that might contain it gives a 404 right now

http://recharts.org/en-US/examples/CustomizedDotLineChart

By the way many examples gives 404:
http://recharts.org/en-US/examples/CustomizedLabelLineChart
http://recharts.org/en-US/examples/SynchronizedLineChart
http://recharts.org/en-US/examples/LineChartWithReferenceLines
http://recharts.org/en-US/examples/HighlightAndZoomLineChart

And possibly more. 

Thank you very much for this! I need dots that are of special colors on certain conditions.

**Comment by xile611** [comment]
This has been fixed.
