### ISSUE TITLE
BarChart background is white on Phone

### ISSUE THREAD

**Issue by jesperlandmer** [recharts/recharts#1487]
## Do you want to request a feature or report a bug?
The background turns white when displaying a `Barchart` in a `ResponsiveContainer`.

## What is the current behavior?

Chrome on iPhone 7 (bug):
![barchartbug](https://user-images.githubusercontent.com/21334341/45945433-d1a1db00-bfed-11e8-8077-2b9923b231b3.png)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

Not working code, but show the barchart instance:
https://jsfiddle.net/70e9rmnb/3/

## What is the expected behavior?

Chrome on Computer (correct):
<img width="411" alt="skarmavbild 2018-09-24 kl 11 32 10" src="https://user-images.githubusercontent.com/21334341/45945468-e9795f00-bfed-11e8-8c8f-0650458f9004.png">

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Recharts ^1.0.0-beta.10
On computer: Chrome Version 68.0.3440.106
On iPhone: Chrome Version 69.0.3497.105

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
