### ISSUE TITLE
possible website bug

### ISSUE THREAD

**Issue by kiranvj** [recharts/recharts#1488]
## Do you want to request a feature or report a bug?
report a bug

## What is the current behavior?
not working as expected

## If the current behavior is a bug, please provide the steps to reproduce

1. goto http://recharts.org  It redirects to http://recharts.org/en-US/ and everything works fine, site loads and homepage is shown.
2. wait for the site to full load
3. refresh page F5 or via icon
4. getting 404

![image](https://user-images.githubusercontent.com/3539487/45946538-cc08bd00-c00e-11e8-9edb-dd4e5e10b9e8.png)

## What is the expected behavior?

should not show 404

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Window 10. 
Chrome Version 67.0.3396.79 (Official Build) (64-bit)
Behind corporate proxy ( but it should not be a prob)

**Comment by zidian257** [comment]
yeah if you type that link in browser it won't work either..

**Comment by klandell** [comment]
@xile611 This issue has been reported several times.  Any timeline for when this will be looked at?

**Comment by kiranvj** [comment]
Looks good now.
