### ISSUE TITLE
Is it possible to draw bar chart in ascending order?

### ISSUE THREAD

**Issue by wonjiky** [recharts/recharts#1490]
Is there a simple way to draw the bar chart so it draws the y values in ascending order?

**Comment by klandell** [comment]
I think the easiest way to accomplish this would be to just sort the array of your data.

**Comment by klandell** [comment]
You could potentially sort the data in `static getDerivedStateFromProps`, and only re-sort if the data changes.  It really depends on the specifics of your use case though.

I'm not sure why the chart component would re-arrange when updated.  I don't see anything in the docs to explain it, and haven't experienced anything like that myself.  Someone else may have some idea?  Sorry I'm not much help here.

**Comment by wonjiky** [comment]
@klandell Hi, I figured out the sorting! Yes, automatically sorting was a weird behavior but couldn't really figure out a reason why..

Thank you again!

**Comment by dhianharyono** [comment]
how can you sort data, is there an automatic method from rechart @wonjiky ?
