### ISSUE TITLE
Fix overlapping in ScatterChart

### ISSUE THREAD

**Issue by natanbcpc** [recharts/recharts#1492]
## Do you want to request a feature or report a bug?
Feature

## What is the current behavior?
Today, if you create a 3D ScatterChart with overlapping values, it might place bigger scatters on top of smaller ones. The solution I found for this was ordering my data set in a descending order. However, I would rather have an option to have Recharts itself fixing this.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
https://jsfiddle.net/3mw50Lc9/796/

## What is the expected behavior?
The expected behavior would be to have a flag in ZAxis that would ask it to order values for you. Something like:

`<ZAxis dataKey={'z'} range={[60, 400]} name='z' overlapping='ordered'/>`

This way, the standard value could be 'unordered', avoiding performance issues when ordering is not necessary.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
I've tested it in version 1.0.0 in Chrome - Ubuntu, but I believe it's a universal problem. It's never previously worked on Recharts.

**Comment by xile611** [comment]
Maybe you can sort your data first.
