### ISSUE TITLE
Bar missing hover effect in ComposedChart

### ISSUE THREAD

**Issue by namho102** [recharts/recharts#1497]
## Do you want to request a feature or report a bug?
a bug or a feature I do not know :)
## What is the current behavior?
Bar is missing hover effect in ComposedChart.
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
http://recharts.org/en-US/examples/LineBarAreaComposedChart
## What is the expected behavior?
ComposedChart shows hover effect in bar like a normal BarChart
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.12.0

**Comment by namho102** [comment]
We can use Tooltip cursor API for this.

**Comment by chrismcleod** [comment]
@namho102 how?
