### ISSUE TITLE
unable to use recharts from umd

### ISSUE THREAD

**Issue by kdipika** [recharts/recharts#1498]
I have been trying to use recharts through UMD as defined in the site
http://recharts.org/en-US/guide

Included this script file in my html
<script src="https://unpkg.com/recharts/umd/Recharts.min.js"></script>

When i run the html on browser by window.Recharts is always undefined.

Looking to use Recharts directly from Html without npm . Please let me know the best way to do this.

## What is the current behavior?
Recharts works with npm

## What is the expected behavior?
Use recharts directly by downloading it or from cdn

**Comment by matsilva** [comment]
Can confirm. If you open up dev tools on this page https://codesandbox.io/s/jn6xrp5649
see the console logged Recharts is undefined.

**Comment by xile611** [comment]
```html
 <script src="https://unpkg.com/react/umd/react.production.min.js"></script>
 <script src="https://unpkg.com/react-dom/umd/react-dom.production.min.js"></script>
 <script src="https://unpkg.com/prop-types/prop-types.min.js"></script>
 <script src="https://unpkg.com/recharts/umd/Recharts.min.js"></script>
```

@kdipika You need to add the sources of React too.

**Comment by ViggoV** [comment]
Same issue using JSFiddle. I have tried both using the urls from the Recharts Readme as @xile611 mentions, and through cdnjs. 

I have of course included React and ReactDOM, and so have @matsilva in his Codesandbox, so I believe this issue has been prematurely closed.

My fiddle using the urls from the Readme (except prop-types): https://jsfiddle.net/Viggotron/tesgovhj/32/
