### ISSUE TITLE
Tooltip jumps around when moving cursor across chart in firefox

### ISSUE THREAD

**Issue by rickymetz** [recharts/recharts#1499]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
Tooltip jumps around erratically when steadily moving the cursor along a chart
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
![oct-03-2018 15-48-25](https://user-images.githubusercontent.com/2237073/46435467-6316f880-c724-11e8-8b76-1efa63d37f95.gif)

Slowly drag tooltip across the chart while in firefox to reproduce.
## What is the expected behavior?
Smooth non jerky snapping to cursor location
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts `1.3.1` | Firefox `62.0.2` | osX `10.13.6`

Does not appear to be a problem in Chrome `69.0.3497.100`

**Comment by inje** [comment]
Is there any update on this? Getting this error as well on the latest version of Firefox @ `67.0.4 (64-bit)`. Works fine on Chrome, Safari, and Opera for me.
