### ISSUE TITLE
Sort order for tooltip

### ISSUE THREAD

**Issue by nickstanish** [recharts/recharts#150]
It would be great to be able to sort the order of items in the tooltip. This could be a prop for ASC/DESC of the original order, or a sorting function with the label name and value.

The use case is that with stacked bar charts where bars are stacked bottom-up but tooltip labels are top-down. http://jsfiddle.net/nickstanish/zrhudh0f/1/

**Comment by xile611** [comment]
Fixed in version 0.12.7.
