### ISSUE TITLE
Xaxis data to display every nth 

### ISSUE THREAD

**Issue by dkulakowska** [recharts/recharts#1502]
I'm trying to find a way of showing every 10th value on the xaxis like in the image below. 
Has anyone solved that?

![screen shot 2018-10-05 at 11 16 04](https://user-images.githubusercontent.com/31188583/46527046-4992bf80-c890-11e8-9003-03735e0a4fb6.png)

**Comment by uyuarasy** [comment]
You can set it manually in through the ticks property. `ticks={['10 Jahre', '20 Jahre', '30 Jahre']}`
