### ISSUE TITLE
RadialBartChart BarGap not working

### ISSUE THREAD

**Issue by bendiggle** [recharts/recharts#1503]
I'm trying to increase the gap in between the bars and it isn't working. Have also tried `barCategoryGap`.
```
    <RadialBarChart width={200} height={200} data={data} innerRadius={50} barSize={35} startAngle={90} endAngle={-250} barGap={50}>
      <PolarAngleAxis type="number" domain={[0, 120]} dataKey={'value'} angleAxisId={0} tick={false}/>
      <RadialBar background dataKey="value" angleAxisId={0} data={data} />
    </RadialBarChart>
```

<img width="211" alt="screen shot 2018-10-05 at 14 43 33" src="https://user-images.githubusercontent.com/11047071/46538905-10b51380-c8ad-11e8-8c8b-1cc0d2f6c817.png">

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
