### ISSUE TITLE
Need Scroll bar for any axis in Bar chart

### ISSUE THREAD

**Issue by Ramkumar2411** [recharts/recharts#1507]
## What is the current behavior?
Thare is no API to add scroll bar for bar chart

## What is the expected behavior?
There should be a API for scroll bar on any axis

Is there any way to add scroll bar on bar chart  like below I want : 

![chart-4](https://user-images.githubusercontent.com/14074230/46615303-7e737080-cb35-11e8-9a64-0fefb65b2b80.png)

**Comment by FengHuangDong** [comment]
Maybe you need to give the outer container a height and set overflow: auto,Then the height of the graph needs to be dynamically assigned by data.length * bar height

**Comment by xile611** [comment]
Duplicated with #1761

**Comment by Nawal00** [comment]
What was the outcome?

**Comment by stearruda** [comment]
I am also curious about this feature.
Is there any workaround of this? I am especially interested in horizontal scrolling and actually showing the (custom) scrollbar.

**Comment by Enriquemnd** [comment]
Is there a way to do this yet?
