### ISSUE TITLE
Custom marker/line on Bar in BarChart

### ISSUE THREAD

**Issue by rpuls** [recharts/recharts#1516]
I'm using recharts@1.2.0
I have been trying to add bechnmarks lines to the Bar component without luck. I can see that BarChart has a ReferenceLine child component, but that spans over the entire BarChart and not for individual Bar's. 

Here is my result with a CSS overlay, but it performs poorly in terms of responsiveness, and I have also not been able to vertically align them pefectly.
![image](https://user-images.githubusercontent.com/14924038/46800965-93304e00-cd59-11e8-8bb7-207c36b42610.png)

Are there any suggested way to achieve this with any of the recharts component? Bar doesn't seem to have a lot of child options.

I have also tried with custom shape, but the height/value of the green bar is not parsed through the scale Y function, which give it incorrect height. Example here: https://jsfiddle.net/rnywhbu8/1911/

Thanks!

**Comment by adrienpoly** [comment]
Hello I am trying to do the exact same thing? Has anyone found a solution yet?

**Comment by evgeniisidorov** [comment]
> Hello I am trying to do the exact same thing? Has anyone found a solution yet?

Hey! I found a workaround. I tried using a custom react element in `Bar`. I render an svg image which contains several rectangles in one `Bar`. The approach is to use `shape` property.

Consider that recharts passes the whole object not only property stated in value. It means you somehow can access all values in one Bar (instead of using several in stacked bar). So your `shape` renders all the rectangles you need. Whatever, you have to do some calc in order to make it look pretty.

See API: [http://recharts.org/en-US/api/Bar#shape](http://recharts.org/en-US/api/Bar#shape)

**Comment by adrienpoly** [comment]
Thanks @evgeniisidorov I will try.

**Comment by rpuls** [comment]
> > Hello I am trying to do the exact same thing? Has anyone found a solution yet?
> 
> Hey! I found a workaround. I tried using a custom react element in `Bar`. I render an svg image which contains several rectangles in one `Bar`. The approach is to use `shape` property.
> 
> Consider that recharts passes the whole object not only property stated in value. It means you somehow can access all values in one Bar (instead of using several in stacked bar). So your `shape` renders all the rectangles you need. Whatever, you have to do some calc in order to make it look pretty.
> 
> See API: http://recharts.org/en-US/api/Bar#shape

I tried something similar, but was unable to get the height of the line/shape right. Can you share your implementation?

**Comment by oranoran** [comment]
Maybe this can be done as a ComposedChart, containing a BarChart and a ScatterChart. So you can use any symbol supported by a scatter chart.

**Comment by wasim-abuzaher** [comment]
Thanks @evgeniisidorov , that worked perfect for me,  below is the code to how I did it in case anyone is trying to achieve the same 

```
//CustomBarWithTarget.js
import React from 'react';

const CustomBarWithTarget = (props) => {
    const { fill, x, y, width, height, amt, t } = props;

    let totalHeight = y + height;
    let targetY = totalHeight - ((height/amt) * t)

    return <svg>
        <rect x={x} y={y} width={width} height={height} stroke="none" fill={fill}/>
        <line x1={x - 8} x2={x + (width + 8)} y1={targetY} y2={targetY} stroke={"#2967c1"} strokeWidth={2} strokeDasharray={"10 5"}/>
    </svg>;
};

export default CustomBarWithTarget
```

then use it on the bar like this:

`<Bar dataKey='amt' shape={<CustomBarWithTarget/>} isAnimationActive={false}/>`

Here `t` is the target dataKey, and `amt` is the bar dataKey

**Comment by OrdinaSimke** [comment]
`      <ResponsiveContainer width="100%" height="100%">
        <ComposedChart data={data} layout="vertical">
          <XAxis type="number" hide={true}/>
          <YAxis type="category" dataKey="name" hide={true} />
          <Bar dataKey="uv" fill="#8884d8" />
          <Scatter dataKey="amt" fill="red" />
        </ComposedChart>
      </ResponsiveContainer>`
