### ISSUE TITLE
Is it possible the add min value that the bar chart can show?

### ISSUE THREAD

**Issue by raymondsze** [recharts/recharts#152]
![legend_r1](https://cloud.githubusercontent.com/assets/15674149/17133701/c20ff6ac-5359-11e6-9326-105826bc1b80.png)
I would like to make a bar chart where the the upper min value of y-axis set to 10000 although the highest value is 8000.

**Comment by xile611** [comment]
@raymondsze  You can set the [domain](http://recharts.org/api#YAxis) of `YAxis`.
