### ISSUE TITLE
ResponsiveContainer width prop ignored

### ISSUE THREAD

**Issue by mathieu-anderson** [recharts/recharts#1520]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
`ResponsiveContainer` does not set the width at 100% of the container when `width=”100%”` is given as prop (observed when rendering PDFs).

## How to reproduce ?
* In a Chrome browser : access https://1o1nxjq3vq.codesandbox.io/ (preview for the sandbox at https://codesandbox.io/s/1o1nxjq3vq)
* Display the `Print preview` for the page (Ctrl+p, or right click -> `Print…`) 
* Bug visible : the graph is not taking the full width of the page
* Mac users : `Open PDF in Preview` shows a buggy PDF

## What is the expected behavior?
`ResponsiveContainer` styles applied as expected (width set at 100%). To see the expected behaviour (v1.3.0), same steps as above with this url :  https://lxxl9232nz.codesandbox.io/ (sandbox : https://codesandbox.io/s/lxxl9232nz)

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
* OS: Mac OS High Sierra (v10.13.6)
* Browser: Google Chrome 69.0.3497.100 (64 bits)

* Versions affected : > 1.3.0 (starting with 1.3.1)
* Versions not affected : < 1.3.0

## Comment
This bug surfaced after the release of 1.3.1, a downgrade of the `react-resize-detector` dependency, which was a fix to https://github.com/recharts/recharts/issues/1496.

**Comment by polkhovsky** [comment]
Maybe this'll help somebody in the future: I came across this issue when working on the print version of my page. The height of my components is fixed, but the width is supposed to be dynamic @100%. While material-ui components rendered perfectly in print view, the charts wrapped in the ResponsiveContainer would only take a portion of the width they were supposed to.  `getContainerSize` in the ResponsiveContainer is looking at `clientWidth` and `clientHeight`.  For a quick and dirty fix I cloned the ResponsiveContainer and changed the function to use `offsetWidth` and `offsetHeight`, which fixed my problem.
