### ISSUE TITLE
ReferenceLine in ComposedChart showing on a left side instead of the middle

### ISSUE THREAD

**Issue by dbknickerbocker** [recharts/recharts#1521]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
ReferenceLine is showing on the left side when using ComposedChart.  #1494 fixed for BarChart, but bug still present when using ComposedChart.
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
[jsfiddle](https://jsfiddle.net/53dwuenj/)
## What is the expected behavior?
ReferenceLine lines up with axis.
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts:1.3.4

**Comment by dantheman39** [comment]
+1 on this

**Comment by Hinaser** [comment]
Bump. I've come across the same thing.

**Comment by Hinaser** [comment]
Accidentally found temporary solution.
https://jsfiddle.net/Hinaser/1usntL5m/3/

Add `scale="point"` to `<XAxis />`.

For example,
```
<XAxis dataKey="name" scale="point" />
```

**Comment by moorthi07** [comment]
Large DATA not showing ReferenceLine in the Chart, instead shows outside on the left (for x axis). 
Also, the data is not sorted in sort order - it shows mixed numbers in wrong orders in X axis. 
[https://jsfiddle.net/marsmoorthi/uqtuc1mp/192/](https://jsfiddle.net/marsmoorthi/uqtuc1mp/192/)

Any comments?

**Comment by dbknickerbocker** [comment]
Fixed in v1.5.0.  ReferenceLine in ComposedChart now renders in the correct location.

**Comment by jatingarg619** [comment]
Am using v1.6.2 but still reference line showing on the left side. Any solution?

**Comment by paulkuhle** [comment]
@jatingarg619 The problem can occur when your x axis stores numerical values and not categories (e.g. `[1, 2, 3, 4, 5...]` and not `["Page 1", "Page 2", ... ]`). By default, the x axis is set to `type="category"`, which means that Recharts will try to map the reference line onto a value of your x axis input array. Now if you try to plot a reference line at 1.5 it will not find that category. The solution is to add `type="number` to your x axis definition, like so:

`<XAxis type="number" />`

**Comment by JakeG-9191** [comment]
Still running into this issue, but I don't think I will be able to add `type="number"` because my xAxis is a date using moment, it just forces an incredibly long domain for X, has there be any additional work arounds introduced for this issue?

**Comment by hbermani** [comment]
@JakeG-9191 @moorthi07 Have you managed to resolve / work around this? 

I am using a date (category) x-axis with a Brush component, and I noticed this interesting behaviour, when the number of data points on display is relatively small with the category rendered on x-axis the Reference Line renders correctly, however the moment it's outside view or there is large number of points it drops to the left of the chart. meanwhile in the logs the viewBox is complaining of NaN x attribute with Error: <line> attribute x1: Expected length, "NaN" and Error: <line> attribute x2: Expected length, "NaN" incrementing errors in the hundreds until the reference line is correctly position on small scale and in view.

I think what is happening is x-axis isn't maintaining the category for the Reference Line despite  ifOverflow="extendDomain" being there in the Reference Line. 

I would appreciate your help / guidance with this

**Comment by imjakr6** [comment]
> @JakeG-9191 @moorthi07 Have you managed to resolve / work around this?
> 
> I am using a date (category) x-axis with a Brush component, and I noticed this interesting behaviour, when the number of data points on display is relatively small with the category rendered on x-axis the Reference Line renders correctly, however the moment it's outside view or there is large number of points it drops to the left of the chart. meanwhile in the logs the viewBox is complaining of NaN x attribute with Error: attribute x1: Expected length, "NaN" and Error: attribute x2: Expected length, "NaN" incrementing errors in the hundreds until the reference line is correctly position on small scale and in view.
> 
> I think what is happening is x-axis isn't maintaining the category for the Reference Line despite ifOverflow="extendDomain" being there in the Reference Line.
> 
> I would appreciate your help / guidance with this
> 
> Edit: Removing "ifOverflow="extendDomain" makes the errors disappear however the Reference Line now only shows when the chart is zoomed in to the point the x-axis includes a matching category.
> 
> Edit: (SOLVED): Finally managed to resolve this, if anyone else comes across this in the future the trick to fix it is add allowDuplicatedCategory={false} in XAxis...... That's two days of my life I won't be getting back!!

Thank you for saving 2 days of my life

**Comment by YaminiSuman** [comment]
> 



> @JakeG-9191 @moorthi07 Have you managed to resolve / work around this?
> 
> I am using a date (category) x-axis with a Brush component, and I noticed this interesting behaviour, when the number of data points on display is relatively small with the category rendered on x-axis the Reference Line renders correctly, however the moment it's outside view or there is large number of points it drops to the left of the chart. meanwhile in the logs the viewBox is complaining of NaN x attribute with Error: attribute x1: Expected length, "NaN" and Error: attribute x2: Expected length, "NaN" incrementing errors in the hundreds until the reference line is correctly position on small scale and in view.
> 
> I think what is happening is x-axis isn't maintaining the category for the Reference Line despite ifOverflow="extendDomain" being there in the Reference Line.
> 
> I would appreciate your help / guidance with this
> 
> Edit: Removing "ifOverflow="extendDomain" makes the errors disappear however the Reference Line now only shows when the chart is zoomed in to the point the x-axis includes a matching category.
> 
> Edit: (SOLVED): Finally managed to resolve this, if anyone else comes across this in the future the trick to fix it is add allowDuplicatedCategory={false} in XAxis...... That's two days of my life I won't be getting back!!

Thanks [hbermani](https://github.com/hbermani) 🚀

**Comment by lbellman** [comment]
> @JakeG-9191 @moorthi07 Have you managed to resolve / work around this?
> 
> I am using a date (category) x-axis with a Brush component, and I noticed this interesting behaviour, when the number of data points on display is relatively small with the category rendered on x-axis the Reference Line renders correctly, however the moment it's outside view or there is large number of points it drops to the left of the chart. meanwhile in the logs the viewBox is complaining of NaN x attribute with Error: attribute x1: Expected length, "NaN" and Error: attribute x2: Expected length, "NaN" incrementing errors in the hundreds until the reference line is correctly position on small scale and in view.
> 
> I think what is happening is x-axis isn't maintaining the category for the Reference Line despite ifOverflow="extendDomain" being there in the Reference Line.
> 
> I would appreciate your help / guidance with this
> 
> Edit: Removing "ifOverflow="extendDomain" makes the errors disappear however the Reference Line now only shows when the chart is zoomed in to the point the x-axis includes a matching category.
> 
> Edit: (SOLVED): Finally managed to resolve this, if anyone else comes across this in the future the trick to fix it is add allowDuplicatedCategory={false} in XAxis...... That's two days of my life I won't be getting back!!

Was absolutely baffled by this for so long, adding that prop to the XAxis fixed it, thank you for this!
