### ISSUE TITLE
Remove axis information from tooltip

### ISSUE THREAD

**Issue by mpbunch** [recharts/recharts#1523]
## Do you want to request a feature or report a bug?
Not sure if this is a feature request, or document enhancement.
-- how do i remove the yaxis from the tooltip?

xaxis dataKey="name" name="SomeName"
yaxis dataKey="other" name="SomeOther"
<tooltip /> (only show the xaxis in the tooltip)

**Comment by mpbunch** [comment]
current solution:
```
import DefaultTooltipContent from 'recharts/lib/component/DefaultTooltipContent';

const CustomTooltipContent = function(props){
  if(props.payload != null && props.payload[0] != null){
    const newPayload = [];
    props.payload.forEach(function(k){
      if(k['name'] !== 'delete'){
        newPayload.push(k);
      }
    });
    return <DefaultTooltipContent {...props} payload={newPayload} />;
  }
  return <DefaultTooltipContent {...props}/>;
}
export {CustomTooltipContent}
```
-----------
```
import { CustomTooltipContent } from "./wherever"
<... GRAPH ...>
<YAxis type="number"    dataKey="meh"       name="delete" />
<Tooltip content={<CustomTooltipContent />}/>
</ ... GRAPH ... >
```


----
seems like crazy overkill for something that should be as simple as
<yaxis tooltipshow={false} />

**Comment by egertaia** [comment]
I would say that is what custom tooltip is made for - you can draw whatever elements you want.
No-one forces you to use defaulttooltipcontent :)
