### ISSUE TITLE
hiding y axis on mobile & have the chart take the available width

### ISSUE THREAD

**Issue by dominikabieder** [recharts/recharts#1525]
Hi,

I want to hide the y axis on mobile (669px) and make the chart take all the available space. Currently, I'm using css media query that doesn't display the cartesian axis ticks, that works fine, but the chart doesn't extend. It also hides the x axis ticks, which is not what I want. 

```
@media (max-width: 669px) {
  .recharts-cartesian-axis-ticks, .recharts-cartesian-axis-tick {
    display: none;
  }
}
```
Before the breakpoint
![screen shot 2018-10-18 at 09 23 58](https://user-images.githubusercontent.com/31188583/47137726-bad26980-d2b7-11e8-990e-0cdfe7c07b50.png)

After the breakpoint (mobile)
![screen shot 2018-10-18 at 09 24 06](https://user-images.githubusercontent.com/31188583/47137735-bf971d80-d2b7-11e8-9af4-9a1c88a9b969.png)

**Comment by tymanchik1991** [comment]
Still nothing? very actual issue. that padding is very unpleased thing. Please give an answer (

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
