### ISSUE TITLE
Trend lines overshoot boundary of graph

### ISSUE THREAD

**Issue by ht2** [recharts/recharts#1527]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
Trend lines escape chart area

![image](https://user-images.githubusercontent.com/1352590/47145865-af387000-d2c2-11e8-9a43-e397a7ac593e.png)

## What is the expected behavior?
Trend lines do not overflow chart area

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.3.2

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
