### ISSUE TITLE
AreaChart height not consistent

### ISSUE THREAD

**Issue by BionBit** [recharts/recharts#1529]
The height of the AreaChart differs with different data sets - even though a fixed height is specified.

For example,
Correct behavior: https://jsfiddle.net/r1tf29ap/
(The height of the chart is '100', like specified)

Incorrect behavior: https://jsfiddle.net/8415b7yx/
(The height of the chart is '84.17' - it should stretch to '100')

Last working version was 0.7.x

**Comment by xile611** [comment]
@BionBit 
Thanks for your opinion ~

It's supposed to specify the domain of `YAxis` to be `['dataMin', 'dataMax']`. If you want to fill the fixed height of AreaChart.

```jsx
const {AreaChart, Area, YAxis} = Recharts;
const data = [
      {name: 'Page A', uv: 101, pv: 2400, amt: 2400},
      {name: 'Page B', uv: 10, pv: 1398, amt: 2210}
];
const TinyAreaChart = React.createClass({
	render () {
  	return (
    	<AreaChart width={200} height={100} data={data}
            margin={{top: 0, right: 0, left: 0, bottom: 0}}>
        <YAxis domain={['dataMin', 'dataMax']} hide />
        <Area dataKey='uv' stroke='#8884d8' fill='#8884d8' />
      </AreaChart>
    );
  }
})

ReactDOM.render(
  <TinyAreaChart />,
  document.getElementById('container')
);

```

**Comment by BionBit** [comment]
@xile611 
Thank you for the workaround.

I've tested all the demo cases in various conditions (different data, with and without X and Y axes) and couldn't find any erratic behavior.

Can you point me to some areas you think this commit can be dangerous, so I can refactor the underlying design if possible?
