### ISSUE TITLE
LabelList generates lables for invisible stacked bars

### ISSUE THREAD

**Issue by varijkapil13** [recharts/recharts#1530]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
I have a chart that has stacked bars with labels that are generated using LabelList component. The problem is that the labels are also generated for bars that are not visible on the chart. And value is used from the previous bar in the series. For eg. if I have a bar A, B, and C. A=10, B=0,C=0. There will be a label on A with value 10, and there will be two labels above A with value 10.

![screenshot 2018-10-19 at 11 30 59](https://user-images.githubusercontent.com/8291077/47210171-85e71500-d392-11e8-987c-252bd595db7d.png)

See here for example: https://jsfiddle.net/90v76x08/7356/

**it works fine when the bars are not stacked**
See Example: https://jsfiddle.net/jx8atr59/

![image](https://user-images.githubusercontent.com/8291077/47210223-a9aa5b00-d392-11e8-8149-ac0f1a799244.png)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
See here for example: https://jsfiddle.net/90v76x08/7356/

**it works fine when the bars are not stacked**
See Example: https://jsfiddle.net/jx8atr59/
## What is the expected behavior?
The chart should not multiple labels in stacked bar chart

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
recharts verison 1.3.4

**Comment by carlos-peru** [comment]
@varijkapil13 I found a workaround which is to derive your input data in such a way that when a value does not pass a rule, do not include it in the dataset. And you have to use the `LabelList`. Since the data is not provided, then it does not get displayed. A rule could be is less than 5 euros for example.
