### ISSUE TITLE
Conflicts with global CSS after version 1.2.0

### ISSUE THREAD

**Issue by guilhermedelucas** [recharts/recharts#1532]
I would like to inquiry about the recharts CSS.
After the upgrade for version 1.2.0 I've having some conflicts with CSS on my project. I have some dropdown menu's, or custom select inputs, that are not displaying correct after the update.
When you open the menu, if it's inside a table, or a div, it's stays partially hidden inside the container.
Before the update it was displaying correctly.
Anyone knows can inform where can I find the rechart's base CSS to investigate the conflicts?
FIY: I'm using tailwind as CSS lib.

**Comment by abhishekti7** [comment]
Hi, facing this issue with version 2.10.3. I have a select html component for which the dropdown does not render. After trying everything, I just removed all the chart components from the page and the dropdowns started working fine.

Has anyone figured this out yet?

**Comment by ckifer** [comment]
@abhishekti7 can you give an example of your code or create a codesandbox? All recharts css is prefixed with "recharts" so I'm confused on how it could conflict

**Comment by ckifer** [comment]
If you're rendering components within the chart, the chart is wrapped in an SVG so everything will be bounded by that SVG

**Comment by abhishekti7** [comment]
Hi, thanks for the reply.

I am currently using recharts inside another (very extensive) project. I will try to replicate this issue in a sandbox and share it here  if I can.

**Comment by ckifer** [comment]
Yeah, doesn't need to be the whole project. Try just to add your dropdown with the same styles and add your chart with mock data - once we can reproduce I can look further
