### ISSUE TITLE
Chart Height jumps on load

### ISSUE THREAD

**Issue by solprofi** [recharts/recharts#1536]
## Do you want to request a feature or report a bug?
I want to report a bug
## What is the current behavior?
When my component loads the CartesianGrid itself seems to ignore the Legend and stretches all the way to the top to fill the whole height. After a split second its height becomes what it should be (considering that Legend has its own height the CartesianGrid becomes shorter). You can see the screenshots below. 
<img width="883" alt="before" src="https://user-images.githubusercontent.com/26505954/47427228-6720be00-d798-11e8-8a01-e4a186ee7b59.png">
<img width="880" alt="after" src="https://user-images.githubusercontent.com/26505954/47427226-6720be00-d798-11e8-982f-254029a92f23.png">
How can I fix the initial height so it doesn't jump when it is loading?
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
<img width="1172" alt="screen shot 2018-10-24 at 14 27 21" src="https://user-images.githubusercontent.com/26505954/47427431-f62dd600-d798-11e8-983c-c1815aba8810.png">

## What is the expected behavior?
Should be rendered as on the second image
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
recharts 1.1.0, Chrome. Did not test for earlier versions.

**Comment by freeman1995** [comment]
+1

**Comment by scallaway** [comment]
Still having this issue a year and a half onwards. Would be very keen to know if anyone has found a robust solution to this (other than just forcing a re-render).

A similar issue https://github.com/recharts/recharts/issues/511 was closed very early on by the maintainers and is still getting comments on it in 2020. Any information would be greatly appreciated.

**Comment by nmoinvaz** [comment]
The problem seemed to go away when I stopped trying to make the chart container div visible by toggling `display: none` and `display: block`. Instead I used something like this to toggle the visibility:

```
  position: fixed;
  visibility: hidden;
  &.selected {
    visibility: visible;
  }
```

**Comment by clarsen23** [comment]
#511
