### ISSUE TITLE
Pie Chart standard axis label not following textAnchor definition

### ISSUE THREAD

**Issue by rweller59** [recharts/recharts#1537]
I am trying to use standard axis label and position it on tick mark ('start'). Label shows up just fine but its positioned between tick marks.
```
<Pie data={timeData} innerRadius={50} outerRadius={55} label textAnchor="start" >
     { timeData.map((d, index) => { return(<Cell fill={d.color}/>)}) }
</Pie>
```

using recharts 1.3.4, react 16.2

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
