### ISSUE TITLE
Defining labelKey for pie chart

### ISSUE THREAD

**Issue by rweller59** [recharts/recharts#1538]
I've seen some reference to labelKey and LabelList but can't figure out how to use either. All I'm trying to do is use a data object key as the label for a pie chart. So, rather than label=data.value, I want the label=data.label. Is this possible?

Data array looks like this: [{time: i, value: 1, label: hour, color: color}]

```
<Pie data={timeData} innerRadius={50} outerRadius={55} clockwise={true}
              startAngle={90} endAngle={-270} >

          
          <LabelList dataKey="label" position="top" />          
          { timeData.map((d, index) => { return(<Cell fill={d.color}/>)}) }
        </Pie>
      </PieChart>
```

**Comment by JackNeto** [comment]
I have the same issue, basically in this example http://recharts.org/en-US/api/PieChart I want to use the name instead of the value for the label

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
