### ISSUE TITLE
Unable to use number type in both axis

### ISSUE THREAD

**Issue by manuviswam** [recharts/recharts#154]
I am trying to plot a time series graph using line chart. X axis will have time and Y axis will have price of an item. Since there is not date/time type in this library, I'm using a number corresponding to the time. But when I render, I get a console warning "x-axis should be category axis when the layout is horizontal" and an error "Uncaught TypeError: Cannot read property 'coordinate' of undefined"

Here is the code I am trying
```
import React from 'react';
import ReactDOM from 'react-dom';
import { LineChart, Line, CartesianGrid, YAxis, XAxis, Tooltip } from 'recharts';

const data = [
	{date:10, price:50 },
	{date:11, price:60 },
	{date:12, price:54 },
	{date:15, price:55 },
	{date:18, price:58 },
	{date:20, price:53 }
]

const SimpleLineChart = React.createClass({
	render() {
		return (
			<LineChart width={600} height={300} data={data} margin={{ top: 5, right: 20, bottom: 5, left: 0 }} >
			  <Line type="monotone" dataKey="price" stroke="#8884d8" xAxisId="dateAxis" yAxisId="priceAxis" unit="Kg" />
			  <CartesianGrid stroke="#ccc" strokeDasharray="5 5" />
			  <XAxis type="number" dataKey="date" xAxisId="dateAxis" />
			  <YAxis yAxisId="priceAxis" />
			  <Tooltip />
			</LineChart>
		);
	}
})

ReactDOM.render(<SimpleLineChart />, document.querySelector("#main"));
```

**Comment by xile611** [comment]
@manuviswam If both XAxis and YAxis are numeric axis, you should use ScatterChart. In your case, you should set the type of XAxis to be `category` just like this [demo](http://jsfiddle.net/3w1b41yd/).

But I wonder why your data isn't continuous in `date`.

**Comment by manuviswam** [comment]
I have only two data axes so line chart is better suite for my purpose. In my use case some days the product may be unavailable so I have to skip plotting a data point on that line and plot the trend accordingly.

**Comment by xile611** [comment]
@manuviswam  Which of the following curves do you want to get ?

1. Remove unavailable dates
![image](https://cloud.githubusercontent.com/assets/6111424/17315914/4d43bdf6-58a2-11e6-8d11-733feafc5ce5.png)

2. Filled with unavailable dates
![image](https://cloud.githubusercontent.com/assets/6111424/17315937/80423d18-58a2-11e6-9bcd-fd2d5ae10c1d.png)

3. Skip unavailable dates
![image](https://cloud.githubusercontent.com/assets/6111424/17316037/49647f62-58a3-11e6-97fb-509f586ca5ea.png)

**Comment by manuviswam** [comment]
Second chart is exactly what I am looking for. But I want the line connecting all the data points (In the image, line is only connecting data points against 10,11 and 12)

**Comment by xile611** [comment]
@manuviswam As you said, you should use ScatterChart to draw the curve. When you use  
LineChart to draw the second, you should fill the data with unavailable dates:

```js
const data = [
    {date:10, price:50 },
    {date:11, price:60 },
    {date:12, price:54 },
    {date:13},
    {date:14},
    {date:15, price:55 },
    {date:16},
    {date:17},
    {date:18, price:58 },
    {date:19},
    {date:20, price:53 }
];
```

Because the price of date 13, and date 14 is unavailable, so the line between date 12 and date 15 is disconnected. So a workaround is to use ScatterChart instead.

**Comment by manuviswam** [comment]
Thank you @xile611 
Problem with the scatter charts is that it lacks the **curves** ;-)
It would be great if you can include a time series chart in your future plans.
Thanks a lot

**Comment by xile611** [comment]
@manuviswam  
OK! We will discuss how to implement your case. In my opinion a time series chart is also a line chart, the only difference is that the ticks of x-axis in a time series chart are time strings. So I'd like to implement your case in two ways:

1. Support smooth curve in ScatterChart
2. Support two options of breakpoints display method:  one is `disconnected`, another is `skip and connected`

**Comment by manuviswam** [comment]
Great news. Waiting for the update.

**Comment by Eric24** [comment]
I actually prefer using Composed, Line, or Area charts for time-series data. It works OK with the X axis being "category", but I think it makes more sense to use "number" (there are fewer tick labels and the labels shown are evenly spaced, regardless of the exact time values in between). Of course, as expected, it doesn't work (exception right after the X axis is redrawn), but why it is a problem to use "number" for both X and Y axis?

**Comment by xile611** [comment]
@Eric24 Both `XAxis` and `YAxis` can be "number-axis" now.

**Comment by Eric24** [comment]
Hmmm. Since what version? We are having trouble with this with version 0.18.0.

**Comment by xile611** [comment]
@Eric24 Since version 0.16.0. So can you raise an online demo ?

**Comment by Eric24** [comment]
Ah so. Yes, it turns out we were running 0.15.3. After upgrading 0.19.0, it now works as expected.

**Comment by manuviswam** [comment]
Wow. Tested it and it works great. Thanks a lot.

**Comment by i3130002** [comment]
I'm using 2.1.8 and setting both axis to number gives me the following output:
![image](https://user-images.githubusercontent.com/11602376/151681250-67582c82-b8f8-498b-baf8-6e6f9da51220.png)

```html
<XAxis
tickFormatter={tickFormatter}
dy={10}
dataKey="timestamp"
angle={0}
minTickGap={50}
type="number"
scale="time"
interval="preserveStartEnd"
/>
<YAxis
>
```
