### ISSUE TITLE
Event for animation finished

### ISSUE THREAD

**Issue by lidermanrony** [recharts/recharts#1540]
## Do you want to request a feature or report a bug?
Request a feature / ask a question
## What is the current behavior?
I don't have any idea when animation finished
## What is the expected behavior?
i'd like to get an event after animation finished

In my case, i want to copy the chart to clipboard as image. for that i'm using html2canvas, but i need to know when animation is finished otherwise the chart looks empty.

**Comment by ackvf** [comment]
Same story, but I want to generate a PDF.

**Comment by emer7** [comment]
You can pass onAnimationEnd props to the component. I need to use it for Pie component, here it is:
https://github.com/recharts/recharts/blob/deff10242b0761f91871367cdc643e41888264de/src/polar/Pie.js#L277

**Comment by xile611** [comment]
The docs has been updated.
