### ISSUE TITLE
Pie with new Label component - position property does not work

### ISSUE THREAD

**Issue by rweller59** [recharts/recharts#1542]
Using version 1.3.4
Simple pie chart and trying to add label. Label gets added but I cannot change the position - changing the value of position has no effect. Thought it might have something to do with coordinate system but neither cartesian or polar work with Pie component. Tried setting viewBox but it made no difference.
```
<Pie data={timeData} 
         viewBox={`${svgView.x} ${svgView.y} ${svgView.width} ${svgView.height}`}>
```
 
```
<ResponsiveContainer width="110%" height={190}>
      <PieChart>
        <Pie data={timeData} 
          <Label value='AM' position='right'/>
        </Pie>
      </PieChart>
</ResponsiveContainer>
```

**Comment by SamMade** [comment]
seems like only `center` works. the rest do not
