### ISSUE TITLE
background in Bar not working if it's a function

### ISSUE THREAD

**Issue by diego-betto** [recharts/recharts#1543]
## Do you want to request a feature or report a bug?
bug

## What is the current behavior?
`background` in `Bar` seems not working if you pass a function

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
https://jsfiddle.net/ex3ntia/vcfwjno4/

## What is the expected behavior?
function should be executed

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts 1.3.5
Chrome 70.0.3538.67 (Official Build) beta (64 bit)
Ubuntu 18.04

**Comment by JakeDluhy** [comment]
I've narrowed it down to this line: https://github.com/recharts/recharts/blob/3b807be36f35e0ae8ecb6918cd57f6c0bc257f4a/src/cartesian/Bar.js#L330

Changing it to
```js
return this.constructor.renderRectangle(this.props.background, props);
```
fixes the bug.

I'd be willing to submit a PR if maintainers would accept it.

**Comment by JakeDluhy** [comment]
https://github.com/recharts/recharts/pull/1550

**Comment by diego-betto** [comment]
thank you @JakeDluhy :)

**Comment by JakeDluhy** [comment]
Should maybe keep it open until it gets merged?
