### ISSUE TITLE
Area Dots overflow into Y-Axis

### ISSUE THREAD

**Issue by KayBeSee** [recharts/recharts#1544]
## Do you want to request a feature or report a bug?
Report a bug

## What is the current behavior?
Dots on area charts overflow into the Y-Axis

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

<img width="751" alt="screen shot 2018-10-29 at 11 45 19 am" src="https://user-images.githubusercontent.com/1429113/47662330-141c8180-db71-11e8-825b-310607cdcffd.png">

JSFiddle: https://jsfiddle.net/b0vqd138/

## What is the expected behavior?
I would expect the dots to cut off at the end of the chart and not overflow into the Y-Axis similar to how they behave with line charts (see image below)

<img width="748" alt="screen shot 2018-10-29 at 11 45 32 am" src="https://user-images.githubusercontent.com/1429113/47662331-14b51800-db71-11e8-8548-070d7df13ea7.png">

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts v1.1.0 - I am not sure if it worked on previous versions of Recharts.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
