### ISSUE TITLE
ResponsiveContainer not filling height

### ISSUE THREAD

**Issue by BarnabyKincaid** [recharts/recharts#1545]
## Do you want to request a feature or report a bug?
Reporting a bug

## What is the current behavior?
I have a ResponsiveContainer sitting in a div. The div has a height and width specified in vh and vw units and a background color so that I can confirm that it appears on the screen. I have given the ResponsiveContainer a height and width of 100%. The chart inside the responsive container will not appear with this configuration. If I give it a minimum height then it will appear. The width will span the entire width of the div, but the height will stay fixed at the minHeight value.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

JSX:
```
<div className="histogram">
    <ResponsiveContainer minHeight={100} width="100%" height="100%">
        <AreaChart data={data} margin={{top: 10, right: 30, left: 0, bottom: 0}}>
            <CartesianGrid strokeDasharray="3 3"/>
            <XAxis dataKey="name"/>
            <YAxis/>
            <Tooltip/>
            <Area type='monotone' dataKey='key1' stackId="1" stroke='#8a4242' fill='#cc0000' />
            <Area type='monotone' dataKey='key2' stackId="1" stroke='#0505c7' fill='#0566c7' />
       </AreaChart>
    </ResponsiveContainer>
</div>
```

CSS:
```
.histogram {
  min-height: 90vh;
  min-width: 90vw;
  background-color: blue;
  background: blue;
}
```
## What is the expected behavior?
The ResponsiveContainer should fill both the width and height of the div.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
I am running this in Chrome in Ubuntu. Recharts 1.3.5.

**Comment by BarnabyKincaid** [comment]
Forgot to block out the code for JSX:

```
<div className="histogram">
    <ResponsiveContainer minHeight={100} width="100%" height="100%">
        <AreaChart data={data} margin={{top: 10, right: 30, left: 0, bottom: 0}}>
            <CartesianGrid strokeDasharray="3 3"/>
            <XAxis dataKey="area"/>
            <YAxis/>
            <Tooltip/>
            <Area type='monotone' dataKey='rbc' stackId="1" stroke='#8a4242' fill='#cc0000' />
            <Area type='monotone' dataKey='retic' stackId="1" stroke='#0505c7' fill='#0566c7' />
       </AreaChart>
    </ResponsiveContainer>
</div>
```

**Comment by BarnabyKincaid** [comment]
Excellent, this fixed it!

**Comment by PascalPixel** [comment]
Could we have `ResponsiveContainer` listen to `min-height` if there is no height?

**Comment by Ishtiaq-Ahmad** [comment]
@diego-betto thank you. your solution worked
