### ISSUE TITLE
Need DoubleClick Event on the each pie cell bar

### ISSUE THREAD

**Issue by Visaali95** [recharts/recharts#1547]
## Do you want to request a feature or report a bug?
feature
## What is the current behavior?
single click is possible
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.3.4

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
