### ISSUE TITLE
In IE I am getting issue saying Object doesnt support property or method 'isFinite'

### ISSUE THREAD

**Issue by kaleemullah19** [recharts/recharts#1549]

**Comment by minal22289** [comment]
Did you find any solution for above problem, I am also facing same issue

**Comment by mehamasum** [comment]
Faced same issue, tested on IE 11

**Comment by armanewy** [comment]
We are still seeing this issue on IE 11.  Getting the same error message (Object doesnt support property or method 'isFinite')
