### ISSUE TITLE
Pie clipPath clipping labels

### ISSUE THREAD

**Issue by GregoryPotdevin** [recharts/recharts#155]
I combined a few example to have a nice half-circle PieChart with an active state. The clipPath used for animating the pie chart (even though I disabled the animation) is actually clipping my active labels as well.

![image](https://cloud.githubusercontent.com/assets/1522455/17277268/f5600d7e-573e-11e6-81cc-af42ce967bf2.png)
(http://jsfiddle.net/j3d22g0m/)

I tried passing a custom maxRadius to the Pie component, but PieChart actually overrides it based on the Pie width and height.

I guess I could subclass Pie and just remove the clippath, but it feels like there could be a better solution. Maybe Pie could take the max of it's computed maxRadius and the one in Pie's props (if passed), for example.
Not a big issue and there are workarounds, just wondering what the optimal solution would be and if you'd like a PR for it.

Other than that, works perfectly fine, great work !

**Comment by xile611** [comment]
@GregoryPotdevin 

Thanks! Maybe the max radius of clipPath should be tweaked.

**Comment by GregoryPotdevin** [comment]
I can do a quick test/PR with a different approach to maxRadius : compute the minimum radius that covers the whole surface of the bouding box.

**Comment by GregoryPotdevin** [comment]
Probably as simple as `maxRadius = 0.5 * Math.sqrt(width * width + height * height)` (maybe using cx and cy to compute the maximum width/height values)

**Comment by xile611** [comment]
Yeah! `maxRadius = 0.5 * Math.sqrt(width * width + height * height)` is a good idea.

**Comment by GregoryPotdevin** [comment]
Thanks !
