### ISSUE TITLE
Scatterchart not plotting basic chart properly

### ISSUE THREAD

**Issue by jgentes** [recharts/recharts#1551]
Thanks for the great library - I know it must be difficult to keep up with all of the activity. Seems like being successful has it's downsides :)

## Do you want to request a feature or report a bug?
bug

## What is the current behavior?
Points are not plotted, or if they are, they are in the wrong location

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.
Here's an example: https://jsfiddle.net/ukh9ndej/

Simple data model:
```
<ScatterChart width={400} height={400} margin={{top: 20, right: 20, bottom: 20, left: 20}}>
  <XAxis dataKey="timestamp" type="number"/>
  <YAxis dataKey="type" type="category"/>
  <CartesianGrid />
  <Scatter data={[
      {type: 'A', timestamp: 1}, 
      {type: 'B', timestamp: 2}
      ]}
    />
</ScatterChart>
```
The above code displays this:
![image](https://user-images.githubusercontent.com/1149470/47965215-31ca6a80-dff9-11e8-8ad0-acdf06da5f68.png)

If I change the xAxis to a category, it is also off:
![image](https://user-images.githubusercontent.com/1149470/47965230-64746300-dff9-11e8-8d2f-9447d8ade980.png)

If I change 'type' to a number (using 1 and 2 instead of A and B) it plots correctly:
![image](https://user-images.githubusercontent.com/1149470/47965244-84a42200-dff9-11e8-952a-ab6c8e7bb615.png)

## What is the expected behavior?
Data should plot correctly on categorical axes

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Latest chrome,Windows 10,  Recharts v1.3.5

**Comment by socramm** [comment]
Have the same Problem. My solution for now will be to rotate my chart container 90° and setting the orientation of the YAxis to "orientation='right'".

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by azzageee** [comment]
I am also experiencing the above issue :(
