### ISSUE TITLE
Can recharts elements be extracted to just html/css?

### ISSUE THREAD

**Issue by roneesh** [recharts/recharts#1552]
## Do you want to request a feature or report a bug?
Neither, a request for information.

## What is my requested information?
Right now recharts is a React library Is there any way to get the *exact same* look and feel of recharts components without react? I know the recharts site says that the library is "Built on top of SVG elements with a lightweight dependency on D3 submodules." Are those SVG elements and D3 submodules formulated as such that one could easily pull them out and just make server side rendered charts without React? Does Recharts utilize any pattern or component libraries that one could use?

## Why am I asking? 
Honestly I realize this is kind of a silly question, there's really no reason not to use React. But it was asked of me and I figured I'd do my due diligence.

**Comment by joewood** [comment]
You could try looking at [gatsbyjs](https://gatsbyjs.org) - which enables server side rendering of React Components. This works well for reports etc...

**Comment by sauravexodus** [comment]
Do you have any example somewhere?
