### ISSUE TITLE
Area charts are not clipping data that falls outside the chart bounds

### ISSUE THREAD

**Issue by cephirothdy2j** [recharts/recharts#1553]
## Do you want to request a feature or report a bug?

Report a bug

## What is the current behavior?

Dots for data passed into an area chart that has points beyond the boundaries of the chart is being displayed as "spilled over" onto the axes areas.

![screen shot 2018-11-06 at 4 54 38 pm](https://user-images.githubusercontent.com/881769/48096552-71ee4080-e1e5-11e8-9b7c-62237542c610.png)

## What is the expected behavior?

The dots would be clipped from the graph if they fall outside the graph area. It looks like this issue was already [fixed for line charts](https://github.com/recharts/recharts/commit/c1423726fb7b7e5c22e076d9bf556c8644b4a5a3).

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
