### ISSUE TITLE
Dot event handlers not invoked when in ReferenceArea

### ISSUE THREAD

**Issue by nathan-haines** [recharts/recharts#1558]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
If I have a dot rendered behind a reference area, I cannot click it to active an onClick handler. The dot will change to be "active" so I know it is registering that my cursor is there but I cant click it. Dots not behind the ReferenceArea will have the handler called.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

Create a LineChart that has a line with dots behind a ReferenceArea. I am using a custom method to render dots with a specific fill depending on position.

Example:
https://jsfiddle.net/wsumdh2b/

Clicking dot for "Page C" will put up an alert. Clicking, for example, the dot for "Page D" will do nothing because its behind the ReferenceArea.

## What is the expected behavior?
The onClick handler should be called. I have tried to find if im just doing this wrong and theres a proper way to do what I'm trying to do, but I haven't been successful this far

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
    "recharts": "^1.2.0",

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.

**Comment by vtarelkin** [comment]
@nathan-haines @xile611  the problem still persists. Any suggestions?
