### ISSUE TITLE
Make recharts compatible with React 15.3 StrictMode

### ISSUE THREAD

**Issue by hlehmann** [recharts/recharts#1559]
More info: https://reactjs.org/docs/strict-mode.html

it imply replacing componentWillMount with componentDidMount and componentWillReceiveProps with getDerivedStateFromProps

this is needed for new features of React such as Suspense.

**Comment by remi2j** [comment]
Pinging this issue, since strict mode is becoming more necessary with React concurrent mode coming up.

**Comment by mowriz** [comment]
any updates on this issue?
