### ISSUE TITLE
Great libarary!  I don't see how to customize color of axis and text

### ISSUE THREAD

**Issue by alisman** [recharts/recharts#156]
I'm trying to put rechart on dark background.  For a line chart I can see how to change color (stroke) of the lines but I it's not clear to me from docs how to customize any other colors.   I see fill colors specified in SVG attributes.

**Comment by xile611** [comment]
For example, if you want to set the color of `XAxis`, you can set the props `stroke` of `XAxis` just like a svg element:

```jsx
<XAxis dataKey="name" stroke="red" />
```
Then the stroke color of axis line, tick line and the fill color of ticks are set to `red`. If you want to set the fill color of ticks to be another color, you can set `tick` of `XAxis`:

```jsx
 <XAxis dataKey="name" stroke="red" tick={{fill: 'orange'}} />
```
So just like `XAxis`, most other Components of Recharts except `Legend` and `Tooltip` can receive props `fill` and `stroke`.
