### ISSUE TITLE
XAxis rightmost label getting clipped.

### ISSUE THREAD

**Issue by roneesh** [recharts/recharts#1560]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
My vertical Line chart is clipping off it's x-axis rightmost label.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

I'm not aware of the steps to reproduce. I'll post my code *below* and hope someone can shine some light on my issue. 

Here is the issue, the "Wed" label is getting clipped off: https://imgur.com/DIgtm6p

The only way I can fix it is to apply a PaddingRight to the <XAxis/> , but it looks pretty ugly: https://imgur.com/QJJrS5q

## What is the expected behavior?
The line chart should not clip it's right most x-axis label, like in the recharts docs.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Recharts: "1.2.0"
React: "16.5.2"
ReactDOM: "16.5.2"
Chrome: Evergreen latest- Version 70.0.3538.77 (Official Build) (64-bit)

## Code
```
return (
    <div className="vLineChart">
      <ChartColorDefs />
      <ResponsiveContainer width="90%" height="80%">
        <LineChart
          data={chartData}
          margin={{ left: 0 }}
          padding={{ right: 15 }}
        >
          <CartesianGrid strokeDasharray="3 3" stroke="#C3C5C8" horizontal={false} />
          <XAxis dataKey="name" tick={TICK_CONFIG} interval={0}  padding={{ right: 15 }} />
          <YAxis tick={TICK_CONFIG} padding={{ top: 15 }} />
          <Legend iconType="circle" />
          {renderLines()}
          {refLine}
        </LineChart>
      </ResponsiveContainer>
    </div>
  );
```

**Comment by xile611** [comment]
@roneesh It's recommend to set the props `interval` in`<XAxis />` to be `preserveStartEnd`. The recharts will calculate the offset value to preserve displaying the start and end tick. 


[the api of interval in XAxis](http://recharts.org/en-US/api/XAxis#interval)
