### ISSUE TITLE
Incorrect AreaChart/baseValue description in API docs.

### ISSUE THREAD

**Issue by yogintas** [recharts/recharts#1562]
http://recharts.org/en-US/api/AreaChart#baseValue

Format definition doesn't make sense.

**Comment by xile611** [comment]
Thanks! The docs has been updated.

**Comment by BrunoQuaresma** [comment]
the baseValue prop is not working for me at all.

**Comment by veddermatic** [comment]
It looks like it was added, then removed. I really need this functionality. No idea why it was reverted, but it would be great to have it back.
