### ISSUE TITLE
cell

### ISSUE THREAD

**Issue by wonjiky** [recharts/recharts#1563]
Hi,

From a selected value from an input select, I dynamically highlight a single bar using <Cell />. However, is there a way to dynamically highlight two (more than one) bars? 

For example, if I had two search bars sending firstValue and secondValue, I want to highlight two bars with red and blue dynamically. I've been stuck with this for quite a while now.. Any suggestions or feedback would be greatly appreciated.

**Comment by xile611** [comment]
@wonjiky You can set the color by <Cell />

[the docs of Cell](http://recharts.org/en-US/api/Cell)
