### ISSUE TITLE
Old version of react-resize-detector

### ISSUE THREAD

**Issue by Glitches** [recharts/recharts#1566]
When resizing the browser, react-resize-detector throws a resizeObserver loop error (can be seen with JavaScript Errors Notifier chrome extension).
Everything is working well, but you could get rid of this warning using a newer version of this package.

i'm using the latest rechart package (1.4.1), created a progressbar customizing piechart component, inside a responsive container.

**Comment by Glitches** [comment]
I've sent a PR with the update.
I'm triyng on my project and seems working.

**Comment by dmr** [comment]
@Glitches Thank you

**Comment by xile611** [comment]
Please try recharts@2.0.0-beta.0
