### ISSUE TITLE
Issue with hover

### ISSUE THREAD

**Issue by chaitanyapotti** [recharts/recharts#1569]
Bug

## What is the current behavior?
When 3 lines are present in a line chart, hover highlight doesn't occur correctly,

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

http://recharts.org/en-US/examples/SimpleLineChart
vs
https://jsfiddle.net/xqjtetw0/17797/

## What is the expected behavior?
The hover highlighting must work exactly as when there are only two lines

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Latest version. All browsers. No

**Comment by ckifer** [comment]
This doesn't seem to be an issue anymore, resolving
