### ISSUE TITLE
LabelList scaleToFit / hide required to prevent overlap when Bar is not wide or high enough

### ISSUE THREAD

**Issue by deadlyfingers** [recharts/recharts#1572]
# LabelList feature request

I would like to see option to automatically hide / resize LabelList when nested inside a Bar component. Currently if you have a lot of bars the labels overlap horizontally as the bar width isn't wide enough for the label. Or if the bar is too short you will get overlap vertically. 

Now you can hide the label when the height value is too short using a *formatter* function:
```js
const barFormatter = (value, unit='%') => {
  if (value < 10) return '';
  return Math.round(value) + unit;
};
```
> However I can't seem to find a way to get the width of the bar to hide the label using this method.

Another useful option would be to support the "scaleToFit" attribute as listed in the Text component API.

**Comment by xile611** [comment]
@deadlyfingers You can get the `x`, `y`, `width`, `height` of each bar from the parameters when you use customized `content` to render the LabelList.

 [Here is a demo](https://jsfiddle.net/alidingling/njfhbdtu/)

You can reopen this issue if you have other questions. If so, would you please give an online demo?
