### ISSUE TITLE
[Docs] filterNull prop missing in Tooltip docs

### ISSUE THREAD

**Issue by vrunjeti** [recharts/recharts#1576]
## Do you want to request a feature or report a bug?
feature? requesting updating the docs

## What is the current behavior?
the `filterNull` prop is missing from the `Tooltip` [docs](http://recharts.org/en-US/api/Tooltip)

## What is the expected behavior?
the `filterNull` prop exists and is explained on the `Tooltip` [docs](http://recharts.org/en-US/api/Tooltip)

**Comment by xile611** [comment]
Thanks! Fixed in recharts.org
