### ISSUE TITLE
Console warning when using ResponsiveContainer

### ISSUE THREAD

**Issue by elya158** [recharts/recharts#1579]
## Do you want to request a feature or report a bug?
bug

## What is the current behavior?
After the ResponsiveContainer unmounts this warning appears in the browser's console:
`The width(0) and height(0) of chart should be greater than 0,
       please check the style of container, or the props width(100%) and height(100%),
       or add a minWidth(undefined) or minHeight(undefined) or use aspect(undefined) to control the
       height and width.`

It seems like the ResizeDetector calls onResize with 0 width and height.
Is this a bug in the `react-resize-detector`? Is there a way to disable or fix this warning?

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts v1.4.1, haven't used previous versions
Chrome Version 70.0.3538.102
macOS High Sierra version 10.13.1

**Comment by xile611** [comment]
@elya158 You should make sure we can calculate the width and height of the chart container dom node.
