### ISSUE TITLE
LineChart line disappear

### ISSUE THREAD

**Issue by hotovshchikov** [recharts/recharts#1583]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
In case you have same data at your period, line become horizontal and disappear.
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
![line_bug_gif](https://user-images.githubusercontent.com/23641694/49643033-56ad6580-fa1d-11e8-830e-abf1d31b7f2d.gif)

## What is the expected behavior?
Line should not disappear.
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts v.1.0.1. Chrome  70.0.3538.110

**Comment by xile611** [comment]
@hotovshchikov Please try the latest version. If the case still exist, please reopen this issue and give us an online example to reproduce it.
