### ISSUE TITLE
Error Bar for stacked bar graph

### ISSUE THREAD

**Issue by alexlhanson** [recharts/recharts#1585]
## Do you want to request a feature or report a bug?
Feature Request
## What is the current behavior?
Error Bar doesn't work with stacked bar graph
## What is the expected behavior?
An error bar to put on a stacked bar graph
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
I think I read in previous issues last year that it had not yet been developed

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by drewjex** [comment]
I am still seeing this issue even after updating to latest version. I opened a new ticket here: https://github.com/recharts/recharts/issues/2602

Thanks!
