### ISSUE TITLE
connectNulls={false} being ignored when attribute stackId is set on an <Area> element

### ISSUE THREAD

**Issue by LukaneCZ** [recharts/recharts#1586]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
When **stackId** attribute is present on a **\<Area\>** element, **connectNulls** seems to be set to **true** and cannot be changed.
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
[jsfiddle example](https://jsfiddle.net/fw5kcon6/1/)
Attribute **connectNulls** is set to **false** in both cases, but when **stackId** attribute is present, nulls are connected despite the attribute setting.
## What is the expected behavior?
No connection to and from **Page D** when attribute **stackId** is set and **connectNulls** is set to **false** (should be set to **false** by default).
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
recharts@1.4.1, Chrome 70.0.3538.110, Windows 10 v1809

- I have no clue if this worked in some previous version, tried setting recharts@1.3.0 in the fiddle above, but the whole area in the first chart just flipped :D nulls were still connected

- v1.3.6 same behaviour as v1.4.1

**Comment by yarokon** [comment]
![Selection_215](https://user-images.githubusercontent.com/4423716/56667996-7802ab80-66b7-11e9-892d-57ead6544197.png)

**Comment by kostadriano** [comment]
@yarokon Can you show the code to reproduce your example?

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
