### ISSUE TITLE
Pie chart onMouseEnter events not firing in Firefox

### ISSUE THREAD

**Issue by lstuartfry** [recharts/recharts#1587]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
The `onMonuseEnter` event never fires for the PieChart.
Note - possibly related to this recent PR - https://github.com/recharts/recharts/pull/1582
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
In Firefox - use the standard demo of the two-level pie chart here - https://jsfiddle.net/alidingling/hqnrgxpj/

## What is the expected behavior?
In Google chrome - observe the `onMouseEnter` behavior here - https://jsfiddle.net/alidingling/hqnrgxpj/
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Firefox is the only version effected I've noticed so far.

**Comment by hugobarragon** [comment]
Hi, this is appening on the new firefox version 64 Quantum, on 63 it fires just fine maybe we need to check the release notes on firefox...

**Comment by AlekzandrG** [comment]
Hi,

I have the same problem, maybe you could suggest me a workaround until the problem is solved.

**Comment by Fonger** [comment]
Same here. I can't figure out why it doesn't work on Firefox.

**Comment by Fonger** [comment]
I've submitted a PR to resolve this bug
