### ISSUE TITLE
How do I group data in a series?

### ISSUE THREAD

**Issue by michaelgriffithus** [recharts/recharts#1589]
See Codepen: https://codepen.io/michael-griffith/pen/OrMNBe
![screenshot 2018-12-14 15 22 50](https://user-images.githubusercontent.com/12091730/50025620-23864b80-ffb4-11e8-92e0-c1d305890a30.png)
See the series for events (labs, notes, etc) causing a duplicate key on my XAxis.  I want the Note and Lab events to show on the same date.  Also the event should be horizontally aligned with the events yAxis.  While they are roughly aligned the data point is too far above the intersection of where I thought it would be. 
Screen shot shows desired position
![screenshot_2018-12-14_15_22_50-2](https://user-images.githubusercontent.com/12091730/50025829-e1a9d500-ffb4-11e8-9acd-de3d86f27d6f.png)

**Comment by ckifer** [comment]
`allowDuplicatedCategory` can be set to false for this. Resolving as stale
