### ISSUE TITLE
Ticks for missing data

### ISSUE THREAD

**Issue by juankmarin** [recharts/recharts#1593]
Hi guys!

Is possible make something like this image for the xAxis ticks
![img_40279d958412-1](https://user-images.githubusercontent.com/12274907/50308523-77d47400-0469-11e9-9f36-a190d1167f3f.jpeg)

Thanks

**Comment by JonasJonny** [comment]
Maybe at #1028 you can find useful information.

**Comment by juankmarin** [comment]
> Maybe at #1028 you can find useful information.

Hi @JonasJonny thanks for your quick response but that doesn't work for me, the idea is to show all the ticks in a 24 hours period but I just have data for some time periods (i.e. between 9am and 3pm)

**Comment by JonasJonny** [comment]
I think you have to specify `domain` and `ticks` in a similar way as I am using with "months".
But maybe someone else will have a better answer.

```
<XAxis
  dataKey="axisX"
  scale="time"
  type="number"
  domain={['1', '12']}
  ticks={['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12']}
  tickFormatter={value => moment(value, 'M').format('MMMM')}
  interval="preserveStartEnd"
  padding={{ left: 50, right: 50 }}
  tickMargin={10}
/>
```

**Comment by juankmarin** [comment]
Hi @JonasJonny, thank you but I'm still without the missing month (in this case), check my example https://jsfiddle.net/e6df7s41/, the idea is to get Jun - Nov ticks without data. Let me know if I'm doing something wrong.

Thanks
