### ISSUE TITLE
Reversed Vertical Barchart with Rounded Corners have Inverted Ends

### ISSUE THREAD

**Issue by HelloTomatoPerson** [recharts/recharts#1596]
I want to create a bar chart with rounded bars that looks like this, but have the bars in reverse

![image](https://user-images.githubusercontent.com/46103427/50397102-ee4fcb00-0722-11e9-8331-4e994069fe72.png)

But after adding the **reversed** prop to the **XAxis** component, it becomes like this

![image](https://user-images.githubusercontent.com/46103427/50397134-2951fe80-0723-11e9-9882-3bc1e57435c7.png)

Is this a bug? Here is my code. Thanks in advance.
```
const {BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend} = Recharts;
const data = [
      {name: 'Page A', uv: 4000, pv: 2400, amt: 2400},
      {name: 'Page B', uv: 3000, pv: 1398, amt: 2210},
      {name: 'Page C', uv: 2000, pv: 9800, amt: 2290},
      {name: 'Page D', uv: 2780, pv: 3908, amt: 2000},
      {name: 'Page E', uv: 1890, pv: 4800, amt: 2181},
];

const SimpleBarChart = React.createClass({
   render () {
     return (
       <BarChart width={ 600 } height={ 400 } data={ data } maxBarSize={ 20 } layout={ 'vertical' }>
         <CartesianGrid strokeDasharray="3 3" />
         <XAxis type={ 'number' } orientation={ 'top' } reversed />
         <YAxis type={ 'category' } orientation={ 'right' } dataKey={ 'name' } />
         <Bar dataKey={ 'pv' } fill={ '#8884d8' } radius={ 20 }/>
      </BarChart>
    );
  }
})

ReactDOM.render(
  <SimpleBarChart />,
  document.getElementById('container')
);
```

*Update* - I tried removing the **reversed** prop and just added data with negative values to see if the same inverted bars would happen and the results were the same. So it would seem that when the values are negative and the bars are in the vertical layout, rounded corners will just happen to act this way. Does anyone have any idea what is going on.

**Comment by Ineedsomehelphere** [comment]
I have the same issue. Is this a bug?

**Comment by Ineedsomehelphere** [comment]
Anyone have any idea what going on with this issue?
