### ISSUE TITLE
Simpler custom labels

### ISSUE THREAD

**Issue by techniq** [recharts/recharts#160]
Currently it seems to take a good bit of boilerplate code just to customize the text on a pie label.  For example, I wanted to include an additional piece of text for the label (the textual name along with the value), which from my understanding, requires the following:

``` js
const renderLabel = ({cx, cy, midAngle, innerRadius, outerRadius, percent, index}) => {
  const radius = innerRadius + (outerRadius - innerRadius) * 1.5;
  const x = cx + radius * Math.cos(-midAngle * RADIAN);
  const y = cy + radius * Math.sin(-midAngle * RADIAN);

  const item = chartData[index];

  return (
    <text x={x} y={y} fill="black" textAnchor={x > cx ? 'start' : 'end'} dominantBaseline="central" key={`label-${data.Id}-${item.Id}`}>
      {item.Name} ({item.Count})  // all I really need to customize
    </text>
  )
};
```

Semi-related (and I can create a separate issue if needed), it would be nice if we could use d3-shape's [arc.centroid](https://github.com/d3/d3-shape#arc_centroid) (or another simpler way) to center a label within a pie piece, or expose a prop to allow placing labels within the pie or outside with the line.

Not that I don't appreciate all the control within the functions, it just seems like I need to "brake glass" too often for simple use cases.

**Comment by xile611** [comment]
@techniq The display of labels in PieChart can be multifarious. That's why we allow develops to customize the labels by a function. Maybe we can export some utils, and refactor `label` in Pie. But we won't add more and more props to meet all the requirements, It's would be very difficult to find the needed props.

**Comment by techniq** [comment]
@xile611 Understood.  I think some util functions would be great (basically expose the same default rendering calls if possible, as well as some additional (render labels in the center of a pie slice, etc).

**Comment by xile611** [comment]
@techniq Thank you!  Looking forward to hear more of your advices.

**Comment by techniq** [comment]
@xile611 Since you mention it... :), and speaking of labels on pie charts...

While I might ultimately take a different approach to these charts, I'm currently having difficulty getting the labels and/or activeShape's to always been visible when using a `<ResponsiveContainer>` with little real estate.

![image](https://cloud.githubusercontent.com/assets/177476/17425891/65637f70-5aa0-11e6-8eff-044ebaf06b58.png)

It seems like I need to be able to determine the `<ResponsiveContainer>`'s width/height and account for a label being rendered outside it's bounds and reposition the labels/etc accordingly (place them in the corners with longer connecting lines, etc)

Any thoughts (or examples) on how to accomplish this?  I might ultimately put all the label in the inside of the pie (when active), or show just the percentages within the pie slices themselves, but it seemed like something that could be solvable none-the-less.

Oh, and great work on the library.  It's been the best React graphing/d3 library I've [come across](https://github.com/techniq/wiki/wiki/React-Components#libraries)

**Comment by xile611** [comment]
@techniq 
We used this kind of PieChart in our products too.  In our case, the height of container is fixed, and the width is responsive which have a minimum width. Then we set the innerRadius and outerRadius  to be a percent value,  and limit the angle of label line.
Here is [a example](http://jsfiddle.net/o39d7va5/).

But when not enough space, this labels can't be guaranteed to render inside the bounds of svg.

**Comment by jochenberger** [comment]
We could check the return value of the `label` function and, if it is a string, render it as a regular `text` element.

**Comment by jochenberger** [comment]
PR created: #219

**Comment by xile611** [comment]
The label can be must simpler in 1.0.0+.
