### ISSUE TITLE
How to disable Stacked Area Chart Draw 0 when data is undefined

### ISSUE THREAD

**Issue by JQuu** [recharts/recharts#1601]
I recently noticed when using StackedId in Area chart, it always draw 0 if there is no data for one x-axis, this is possible in a normal area chart [Non-Stacked Area Char works fine - JSFiddle](https://jsfiddle.net/6yoqhvfk/). 

However when using stackedArea chart it will always bring areas to 0.
[Stacked Area Chart with no data - JSFiddle](https://jsfiddle.net/n9xjcurh/1/)

Is there a way to make stacked chart behavior consistent with non-stacked cart?

**Comment by dd1mk** [comment]
Hi, are there any updates on this feature?
