### ISSUE TITLE
PieChart not working on Firefox

### ISSUE THREAD

**Issue by studiojms** [recharts/recharts#1602]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
PieChart mouse events are not working on the latest version of Firefox (v 64)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

Here (https://codesandbox.io/s/kxyv8xn58o) is a simple example of a pie chart that show an alert message when clicking on a pie. Using Chrome or and older Firefox version it works correctly, showing the pointer cursor when hovering the chart and, when clicked, the alert is shown.
When using Firefox 64, the cursor doesn't change and the click has not effects.
(I tested some other charts and it looks like it happens only on PieChart, the other charts are working fine)

The same problem occurs with the Recharts Docs example (http://recharts.org/en-US/examples/CustomActiveShapePieChart). The active shape should change when hovered, but it is not working on Firefox 64.

## What is the expected behavior?
The click event should behave correctly on all browsers.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Recharts version: (1.4.2)
Browser: Firefox 64
OS: Tried on Linux (Ubuntu 16.04) and Windows 10

**Comment by avrittrohwer** [comment]
I too am affected by this bug.  The `onMouseEnter` prop does not fire.  Chrome and IE11 work as normal, only Firefox has this problem.

**Comment by Ahmed-Essam-WasilaDev** [comment]
same problem here working fine on Chrome, but not working on Firefox
the documentation example aslo not working :
http://recharts.org/en-US/examples/CustomActiveShapePieChart

Browser: Firefox 64

**Comment by shaheenumar** [comment]
I too have same issue. Any work arounds?

**Comment by yshua5631** [comment]
I also run into the same issue, can anyone has a workaround solution?

**Comment by Fonger** [comment]
I've submitted a PR to resolve this bug
