### ISSUE TITLE
how to make 'Highchart with 500,000 points  example' to work with reharts - linechart? 

### ISSUE THREAD

**Issue by moorthi07** [recharts/recharts#1603]
This is an Highchart JS example rendering 500000 points in minutes , How to make the same in rechart - linechart?

[https://jsfiddle.net/marsmoorthi/q93bLomc/](https://jsfiddle.net/marsmoorthi/q93bLomc/)

Here is what I'm trying with rechart  -  simplelinechart example,
[https://jsfiddle.net/marsmoorthi/wpfnfmh7/1852/](https://jsfiddle.net/marsmoorthi/wpfnfmh7/1852/)

**Comment by xile611** [comment]
@moorthi07 Maybe you can check this [demo](http://recharts.org/en-US/examples/HighlightAndZoomLineChart).
