### ISSUE TITLE
Don't show bars with when label does not exist

### ISSUE THREAD

**Issue by ErickMwazonga** [recharts/recharts#1604]
How do you skip a bar when the label does not exist in the current iteration. It has been addressed here as well https://stackoverflow.com/questions/49909093/recharts-skip-a-bar.

![screenshot from 2019-01-04 16-50-43](https://user-images.githubusercontent.com/19705223/50691183-ef48fc80-1040-11e9-99ae-d8a834afb023.png)

Technically, I would like to skip the labels that not in a specific month.

**Comment by xile611** [comment]
@ErickMwazonga Sorry, this isn't supported, maybe you can format the data to reach your demand.
