### ISSUE TITLE
Adding Line to Linechart with Different Stroke

### ISSUE THREAD

**Issue by bsaid97** [recharts/recharts#1605]
So I'm trying to compare two different sets of data on the same linechart component. The idea is, when the user presses a button, a new line is added to chart below the button in a different stroke to allow the user to compare the data against the original data. When the button is pushed, the new data is pushed to my `dataPoints` variable which is structured like so: 
``` 
@observable dataPoints = [
    {
      name: "",
      data: [
              sentiment: "",
              tweet:"",
              date: ""
       ]
    }
  ];
```
I've currently set up my Linechart to have a line which is mapped to each index in the `dataPoints` store. 
```
{this.store.dataPoints.map(s => (
          <Line
            data={s.data}
            name={s.name}
            key={s.name}
            type={this.store.lineType}
            dot={false}
            dataKey="sentiment"
            stroke="#8ab6fc"
          />
        ))}
```
However, this yields two lines with the same stroke. Any suggestions?

**Comment by xile611** [comment]
@bsaid97 you can change the `stroke="#8ab6fc"` of `<Line />`.
