### ISSUE TITLE
LodashModuleReplacementPlugin causing recharts graph to flip upside down

### ISSUE THREAD

**Issue by alexanderwhatley** [recharts/recharts#1607]
I'm running into a weird issue where if I use LodashModuleReplacementPlugin in webpack, the recharts graphs I have flip upside down. Has anyone else run into this issue?

**Comment by xile611** [comment]
@alexanderwhatley Can you provide a simple example to reproduce your case?

**Comment by taddeini** [comment]
we ran into this problem this week as well. it presented itself as soon as we added `stackId` to the Area components. here's a repo that reproduces the issue:

https://github.com/taddeini/recharts-lodash-flip

**Comment by avindra** [comment]
I'm not using this plugin but I'm getting a similar issue.

If I remove `stackId`, the grid gets holes torn out of it

![image](https://user-images.githubusercontent.com/126848/62647135-e47b8080-b91d-11e9-8094-99890713655f.png)

**Comment by avindra** [comment]
![image](https://user-images.githubusercontent.com/126848/62648114-17267880-b920-11e9-9e1b-6ce18f2c1712.png)


This is happening after upgrading 0.22.5 to 1.6.2

**Comment by avindra** [comment]
If I apply `reversed: true` to `YAxis`, it flips back to normal. Can be used as a workaround, but this definitely seems like a bug, and unrelated to the lodash plugin as I am not using it.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
