### ISSUE TITLE
Space between XAxis axisLine and Bars?

### ISSUE THREAD

**Issue by erosenberg** [recharts/recharts#1611]
## Do you want to request a feature or report a bug?
Bug/Probably misunderstanding

## What is the current behavior?
Bars are overlapping with the actual axisLine and I would like to move it slightly lower so the bars appear to be on top of the axisLine instead of overlapping.

**Comment by xile611** [comment]
@erosenberg 
Maybe you should change the order of <XAxis /> and <Bar />.
You should provide more information about your code

**Comment by geon** [comment]
From the examples page: http://recharts.org/en-US/examples/SimpleBarChart

![screenshot 2019-02-19 at 10 35 59](https://user-images.githubusercontent.com/228012/53004812-33962d80-3432-11e9-8694-a02745516b58.png)

The bar starts in the middle of the axis line.

**Comment by emadabdulrahim** [comment]
Any solution to this?

**Comment by MatthieuVeillon** [comment]
Had the same issue raised by our PO - found out a solution by adding 1 px padding to the the `XAxis` with  `padding={{ bottom: 1 }}`

Not perfect but does the trick

**Comment by CrazyRedTime** [comment]
This working pefectly 

> <YAxis padding={{ bottom: 10 }} hide />

**Comment by Yilun-Sun** [comment]
### Solution 
`<YAxis padding={{ bottom: 2 }} />`

Close issue
