### ISSUE TITLE
Tooltip item color with dynamic bar color

### ISSUE THREAD

**Issue by ericraq** [recharts/recharts#1612]
Hi everyone,

I have changed the bar color of my bar chart (y 3) dynamically according to my data by changing the cell fill color. Now I would like the tooltip information color for y 3 to match the bar color (green or red).

 Can you help me on how to achieve this?

![image](https://user-images.githubusercontent.com/46633188/51077767-f354ca00-1691-11e9-8019-83225c774bc8.png)

**Comment by ericraq** [comment]
I could achieve what I needed by using the custom tooltip.

**Comment by JohnAJimenez** [comment]
@ericraq can you provide the code you used? I'm looking into how to solve a similar issue.

**Comment by ericraq** [comment]
@JohnAJimenez I did something like this:

		const CustomToolTip = props => {
		  const { active, payload, label } = props;
		  if (!active || !payload) {
			return null;
		  }
		  
		  const tooltip = {
			backgroundColor: 'white',
			opacity: '0.9',
			border: '1px solid black',
			borderRadius: '15px',			
			paddingLeft:'10px',
			paddingRight:'10px'
		  }
		  
		  return (
			<div> 
				<div className="custom-tooltip" style={tooltip}	>
				  <p style={{textAlign: 'center'}}>
					<strong>label</strong>
				  </p>
				  {payload.map((item, i, payload) => {
					  
					const itemColor = i == 1 ? (item.value > payload[0].value ? '#00A86B' :  '#FF2400') : item.color
				
					return(
						<div key={i}>
							<p style={{color: itemColor}} key={i}>
							  {item.name}: <strong>{valor}</strong>
							</p>
						</div>
						)
				  })
				 }
				</div>
			</div>
		  )
		}
And then add it in the tooltip content.

Hope it helps!
