### ISSUE TITLE
Tooltips are not appearing the Firefox v64 for the Pie Charts

### ISSUE THREAD

**Issue by uday-squadcast** [recharts/recharts#1613]
## Do you want to request a feature or report a bug?
Report a bug
## What is the current behavior?
Tooltips for PieChart are appearing in Google Chrome but not appearing in the Firefox
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
Open the Piecharts demo which has tooltips in Firefox
## What is the expected behavior?
Tooltips should appear even in Firefox
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Using recharts v1.4.1 , Firefox v64 , Mac OS - Mojave

**Comment by ponciusz** [comment]
Have same problem it's not working on Firefox

**Comment by Fonger** [comment]
I've submitted a PR to resolve this bug
