### ISSUE TITLE
Vertical XAxis labels are getting cut off

### ISSUE THREAD

**Issue by danielo515** [recharts/recharts#1618]
## Do you want to request a feature or report a bug?
Problem
## What is the current behaviour?

I have the XAxis rotated 45. But when the names are too long they are cut off. I have enough space on the screen so I would prefer to display them entirely.
See the attached image:

![image](https://user-images.githubusercontent.com/2270425/51340583-9db45f00-1a8f-11e9-894a-7981b1b2c34b.png)

## What is the expected behaviour?

I expect the chart area to grow to accommodate all the labels.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

```
    "recharts": "^1.4.2",

```

The browser is Electron

**Comment by YamatoDX** [comment]
This helped me, thanks!

**Comment by therealbluepandabear** [comment]
Still doesn't work

**Comment by tran-simon** [comment]
I set `overflow: 'visible'` to the chart component and the labels are fully visible:

```
<BarChart
  {...{
     overflow: 'visible'
   }}
>
```

(I used the spread syntax, because else typescript would complain that the overflow prop does not exist)

**Comment by monstermichl** [comment]
With this setup, it still doesn't work properly for me even though overflow is set to *visible*. Is there an option to just reduce the height of the chart automatically to fit everything, including the labels, into the space provided or am I just missing something?

```typescript
export default function BarChart(props: {
    data?: BarChartData[],
    title?: string,
    xAxis?: boolean,
    yAxis?: boolean,
    showDataLabels?: boolean,
    labelsAngle?: number,
    className?: string,
}) {
    const { title, labelsAngle } = props;
    const xAxis = useMemo(() => props.xAxis ?? true, [props.xAxis]);
    const yAxis = useMemo(() => props.yAxis ?? true, [props.yAxis]);
    const data = useMemo(() => (isNil(props.data) ? [] : props.data).map((chunk) => ({
        ...chunk,
        label: 'asdfasdfsadfsadfdsafsafsafsadfsafaf',
        fill: '#000000',
    })) , [props.data]); /* Fix data if necessary. */
    const additionalProps = useMemo(() => {
        const angleProps = {
            angle: -90,
            textAnchor: 'end',
        };
        return {
            ...angleProps,
        };
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [labelsAngle]);

    return <div className={`bar-chart-container ${props.className || ''}`}>
        {title ? <div className="bar-chart-title">{title}</div> : undefined}
        <ResponsiveContainer width="100%" height="100%">
            <ReactBarChart data={data} {...{overflow: 'visible'}}>
                <Bar dataKey='data' />
                {xAxis ? <XAxis dataKey="label" {...additionalProps} /> : undefined}
                {yAxis ? <YAxis /> : undefined}
            </ReactBarChart>
        </ResponsiveContainer>
    </div>;
}
```

![image](https://github.com/user-attachments/assets/9d00bcae-cdc6-4400-931f-fc2ac5865f22)

**Comment by ckifer** [comment]
generally I would use `margin` for this rather than XAxis height or overflow: visible. But no, unless you measure the length of your labels yourself and dynamically adjust margin there is no setting at the moment that includes them in the offset calculation.

**Comment by glocore** [comment]
I was able to apply the overflow behaviour to all my charts using this CSS override from [this comment](https://github.com/recharts/recharts/issues/181#issuecomment-519697623):
```css
.recharts-wrapper svg{
  overflow: inherit !important;
}
```

**Comment by johnhuichen** [comment]
> generally I would use `margin` for this rather than XAxis height or overflow: visible. But no, unless you measure the length of your labels yourself and dynamically adjust margin there is no setting at the moment that includes them in the offset calculation.

I think @ckifer is right. Margin is the better answer because it's the  more idiomatic usage of recharts. Setting overflow hidden is both hacky and prone to side effects.

**Comment by budres** [comment]
use `outerRadius` as `<RadarChart outerRadius={200} data={chartData}>`
