### ISSUE TITLE
Tooltip incorrect data point detection with ComposedChart [bug report]

### ISSUE THREAD

**Issue by alexsmartens** [recharts/recharts#1620]
## Current behavior

Tooltip messes up multiple series in ComposedChart when there is more than one point with the same `x` coordinate. Example, consider two points with IDs of 1 and 2 and `x=100`.  Each point can be detected with both IDs by Tooltip (seems like y coordinate is ignored):

- Cursor is on the lower point:

![image](https://user-images.githubusercontent.com/26261714/51404747-5aef9700-1b22-11e9-87cc-0d7a26be388d.png)
![image](https://user-images.githubusercontent.com/26261714/51404757-6216a500-1b22-11e9-8139-4795bfe08af8.png)

- Cursor is on the upper point:

![image](https://user-images.githubusercontent.com/26261714/51404769-6773ef80-1b22-11e9-8eea-71f7f3142a19.png)
![image](https://user-images.githubusercontent.com/26261714/51404779-6fcc2a80-1b22-11e9-93e7-64d30a1325e6.png)

## Minimal demo

https://jsfiddle.net/ro1x0q9s/4/

## What is the expected behavior?
If the cursor is located closer to the point with ID 1 then the Tooltip payload ID is 1, otherwise if the cursor is located closer to the point 2 the the detected ID is 2.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts: 1.4.2, not tested with different Recharts versions
Tested with Firefox 64.0.2 and Edge 44.17763.1.0

**Comment by xile611** [comment]
@alexsmartens ComposedChart has default layout, which is `horizontal`. So we'll calculate the active dot by the coordinate of only x. 

Maybe you should use `ScatterChart` when you only render scatters.
