### ISSUE TITLE
How to completely rerender the graph?

### ISSUE THREAD

**Issue by aditya81070** [recharts/recharts#1624]
## What is the current behavior?
When I change the `data` to `LineChart`, the only curve is rerendered. But the initial animation(showing the drawing of the graph) is not there. I am using this into a `ResponsiveContainer`.
Here is my state and state update function:
```js
state = {
    first: true,
    second: false,
    color: '#44cc44'
  }

  componentDidMount () {
    this.timer = setInterval(() => {
      if (this.state.first) {
        this.setState({
          first: false,
          second: true,
          color: '#44cc44'
        })
      } else {
        this.setState({
          first: true,
          second: false,
          color: '#ff0000'
        })
      }
    }, 4000)
  }
```
```js
{
                this.state.first
                  ? (
                    <ResponsiveContainer height={120}>
                      <LineChart data={data0}>
                        <Line type='monotone' dataKey='pv' dot={false} strokeWidth={5} stroke={this.state.color} />
                        <CartesianGrid vertical={false} />
                      </LineChart>
                    </ResponsiveContainer>
                  )
                  : (
                    <ResponsiveContainer height={120}>
                      <LineChart data={data1.slice()}>
                        <Line type='monotone' dataKey='pv' dot={false} strokeWidth={5} stroke={this.state.color} />
                        <CartesianGrid vertical={false} />
                      </LineChart>
                    </ResponsiveContainer>
                  )
              }
```
## What is the expected behavior?
When I change the data, the whole graph should be rerendered.

**Comment by aimeelaplant** [comment]
I would like to know how to do this, too, as I also had this happen to me. 

As a workaround, I ended up wrapping the components in a stateless component and passing in a property to force the re-render when the props change, so that I wasn't declaring the chart for every possible if-condition.

**Comment by xile611** [comment]
@aditya81070 Can you create an online demo to reproduce your case? I don't know exactly what the problem

**Comment by klarstrup** [comment]
You can force a remount by setting and changing the `key` prop

**Comment by AdamAvix** [comment]
Thank you @klarstrup, this just saved me hours of headache with this confusing library.

**Comment by FrankMa1** [comment]
Yup, thank you very much @klarstrup

**Comment by Takage** [comment]
@klarstrup 

Can you explain a little bit more? Cause I have the same problem:

`const buildChartHtml = () => {
    let elements = [];
    if (activeType === 0) {
      elements.push(<XAxis dataKey="day" type="number" tickCount={11} label={CHART_INFO[activeType].xAxis_label} />);
      elements.push(<YAxis type="number" label={CHART_INFO[activeType].yAxis_label} />);
      elements.push(<Line data={chartData} dataKey={CHART_INFO[activeType].dataKey} stroke="#FF3333" dot={false} strokeWidth={2} legendType="square" />);
      elements.push(<Line type="linear" data={testline} dataKey="y" stroke="#0000ce" dot={false} strokeWidth={2} legendType="square" />);
    } else if (activeType === 1) {
      elements.push(<XAxis dataKey="day" type="number" tickCount={11} label={CHART_INFO[activeType].xAxis_label} />);
      elements.push(<YAxis type="number" label={CHART_INFO[activeType].yAxis_label} />);
      elements.push(<Line data={chartData} dataKey={CHART_INFO[activeType].dataKey} stroke="#FF3333" dot={false} strokeWidth={2} legendType="square" />);
      elements.push(<ReferenceLine y="1000" label={{ position: "center", value: "Max Budget" }} />);
    }
    setChartHTML(elements);
  };

  // render onMount
  useEffect(() => {
    //check which type of process is run
    setChartData(buildChartData());
    buildChartHtml();
  }, []);

  // change chartData when activeType is changed
  useEffect(() => {
    //check which type of process is run
    if (activeType === 0 && chartData.length > 1) {
      setChartData(data1);
      buildChartHtml();
    }
    if (activeType === 1) {
      setChartData(data2);
      buildChartHtml();
    }
  }, [activeType]);

  const handleChangeTabs = (event, newValue) => {
    setValue(newValue);
  };

  return (
    <div>
      <AntTabs value={value} onChange={handleChangeTabs}>
        {CHART_INFO.map((item, index) => (
          <Tab label={item.name} onClick={() => [setActiveType(item.id), setActiveIndex(index)]} />
        ))}
      </AntTabs>
      <LineChart key={CHART_INFO[activeType].dataKey} width={500} height={300} margin={{ top: 5, right: 20, bottom: 5, left: 0 }}>
        {chartHTML}
        <Legend verticalAlign="top" />
        <Tooltip />
      </LineChart>
    </div>
  );
}`

**Comment by reliacon-dev** [comment]
> You can force a remount by setting and changing the `key` prop

Yep - this did it for me. Setup is:
```typescript
<ComposedChart
          key={(brushIndex.startIndex || 0) + (brushIndex.endIndex || 0)}
          ...
```
where brushIndex is set either by this chart or the parent.


> Can you explain a little bit more? Cause I have the same problem:

Not sure what you're showing us, but whatever action you want to force a rerender of the chart, make sure that it changing affects the calculation of the chart's `key`
