### ISSUE TITLE
Tooltip payload contains duplicated values if <XAxis /> allowDuplicatedCategory is true

### ISSUE THREAD

**Issue by nicohartto** [recharts/recharts#1625]
## Do you want to request a feature or report a bug?

Bug

## What is the current behavior?

Tooltip renders duplicated values for Lines, if X-Axis **allowDuplicatedCategory** is set to default value of "false". E.g. three lines are rendered per dataSet (in example total 6 lines). The payload contains only the values from the first dataSet, but draws both (the second one with wrong values.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

https://codesandbox.io/s/7y8yj3wwzj

Very minimal example, check the tooltip values after and before toggling **allowDuplicatedCategory** for X-Axis.

Idea is that there might be X amount of data in the dataSet, and each of those would be given to a specific line. Timestamp would be in real-life a unix-timestamp with correct ticks/domain etc.. But this example already shows the issue.

## What is the expected behavior?

Tooltip should show all of the values of the lines under current selection. Not just the values from the first one. The payload that is given for Tooltip should contain correct values, not just for the dataKey & name, but for the actual "payload" of said payload.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

1.4.2 (happens with earlier version as well, 1.1.0 at least.

**Comment by xile611** [comment]
@nickpalmer 

The props `allowDuplicatedCategory`  doesn't affect the behavior of tooltip. If you have 6 <Line />, then you'll get 6 items in the tooltip.

`allowDuplicatedCategory = true ` will only affect the behavior of <XAxis />

You should use [`formatter`](http://recharts.org/en-US/api/Tooltip#formatter) or [`content`](http://recharts.org/en-US/api/Tooltip#content) to get your expected behavior

**Comment by cdupont** [comment]
I had the same issue. Setting:
```
<XAxis allowDuplicatedCategory={false}/>
```
Solved it. See also https://stackoverflow.com/questions/57359903/recharts-tooltip-displays-same-value

**Comment by codegefluester** [comment]
I'm so happy I found this issue here, I was already going crazy seeing my tooltip being broken like this. Since this feels more like a workaround, is there something we should do differently with our data that may cause this to happen?
