### ISSUE TITLE
Pass value of dataKey to child component

### ISSUE THREAD

**Issue by L3mmAa** [recharts/recharts#1626]
How can i pass the value of a dataKey to another component? I have a line chart with a custom dot, this dots needs a value from the data. How can i pass the value of a datakey to it?
``` 
const data = [
    { name: 'abc', value: '1' },
    { name: 'cde', value: '2',},
    { name: 'fgh', value: '3' }
    ...
];

<LineChart data={data} margin={{ right: 50, left: 50 }}>
    <Tooltip />
    <Line type="monotone" dataKey="value" stroke="black" strokeWidth="1px" dot={<CustomDot name={[[[name dataKey]]]} />} />
</LineChart>
```

**Comment by xile611** [comment]
@L3mmAa You can check this [demo](https://jsfiddle.net/alidingling/9y9zrpjp/2353/).

You can get all the information you need from the props of `CustomDot`.
![17_58_47__02_12_2019](https://user-images.githubusercontent.com/6111424/52627246-ea088880-2eef-11e9-8dd9-e9dfc839f057.jpg)
