### ISSUE TITLE
Legend overlaps with chart in Accordion

### ISSUE THREAD

**Issue by Bhargav-Narayan** [recharts/recharts#1629]
I'm facing the same issue when I'm placing the chart inside an accordion. I'm using react-accessible-accordion npm library. If the accordion is expanded by default, I'm not facing this issue. If user clicks on accordion title and tries to expand, legend will be overlapped on the chart. If user do mouseOver on the chart, then legend resizes and displays properly. 
Need a solution asap. 
Thanks in advance.

_Originally posted by @Bhargav-Narayan in https://github.com/recharts/recharts/issues/1249#issuecomment-458095743_

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
