### ISSUE TITLE
Getting data from Area charts

### ISSUE THREAD

**Issue by Algiras** [recharts/recharts#163]
I want to be able to click on the area chart and be able to retrieve the data that was used to create that point. 
For example:

``` javascript
const collection = [{a: 1, b: 2}, {a:2, b:4}];
...
<Area type="monotone" dataKey="b" onClick={x} stroke="#8884d8" fill="#8884d8" />
```

Updated area example: http://jsfiddle.net/5p61t9qp/4/ to use the click. As you can see it return info about dispatch event and not the data, what should I change?

Kind Regards,
AK

P.S. It works with Bar charts.

**Comment by xile611** [comment]
@Algiras   `Area` does not support this function now.

**Comment by Algiras** [comment]
Thank you for the quick answer!

**Comment by xile611** [comment]
@Algiras We'll refactor the events of some components in a few time.

**Comment by Algiras** [comment]
Awesome! Looking forward to it!

**Comment by mberhorst** [comment]
It would also be nice to select an area and not only one point. Would be useful for time-based area charts.

**Comment by mberhorst** [comment]
@Algiras 
Maybe you can use an composed chart to get informations from an area chart:
http://recharts.org/api#ComposedChart

I need that functionality to and I got that idea to draw hollow bar charts which I can click to get the data. Its a workaround but maybe it fits your needs.

**Comment by pcmaffey** [comment]
Here's a solution for getting data/coordinates:

Assign a ref to your chart. Add onClick function to a wrapper div. You can then reference the chart and get state.chartX and state.chartY... or any properties you want.

`<LineChart ref={(ref) => (this.lineChart = ref)} >
...
handleClick(event) {
    event.preventDefault();
    const { chartX, chartY } = this.lineChart.state;
}
`
