### ISSUE TITLE
Add  a new tick at Yaxis.

### ISSUE THREAD

**Issue by weilunc93** [recharts/recharts#1631]
## Do you want to request a feature or report a bug?
Feature

## What is the current behavior?
Tick show correctly based on data.

## What is the expected behavior?
Currently the YAxis tick showing based on domain. I am doing some performance chart and YAxis represent the percentage of performance. The data could be from 0 to 300% and i want the chart to always show a tick at 100%.

**Comment by xile611** [comment]
@weilunc93 You can specify the `domain` of `<YAxis />` to be `[0, 1]`.
