### ISSUE TITLE
Forcing same scale for both Axis

### ISSUE THREAD

**Issue by Gorbus** [recharts/recharts#1632]
## Do you want to request a feature or report a bug?
Feature

## What is the expected behavior?
Forcing same scale for both axis. I do not find a way to have the same scale for both axis. Both my axis are representing "cm" values and I would like them to be represented without any deformation. Which means that 5cm on the x scale should be the same length (in pixels) as a 5cm value on the y scale.

**Comment by xile611** [comment]
@Gorbus In your case, It's recommended to specify the `domain`  of <XAxis /> and <YAxis />, and the `width` must equal to  `height`
