### ISSUE TITLE
Even padding for PieChartWithPaddingAngle

### ISSUE THREAD

**Issue by alex-polunochev** [recharts/recharts#1634]
## Do you want to request a feature or report a bug?
Feature request / update

## What is the current behavior?
The white space between sectors of PieChartWithPaddingAngle has a trapezoid shape. http://recharts.org/en-US/examples/PieChartWithPaddingAngle

## What is the expected behavior?
Whitespace should be able to have rectangular shape. That way the donut look harmoniously. 

It's not as evident when the inner and outer radiuses have small delta (as by the link above).

But when the inner radius is significantly shorter and inner donut edge is closer to the center of the chart, then the padding looks odd.
https://jsfiddle.net/dwLz64mg/

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Using 1.4.2 
Didn't use library before.

**Comment by xile611** [comment]
@alex-polunochev The white space between between sectors is also a sector, so It seems to be a trapezoid shape. We don't think this is a problem, maybe you should use `paddingAngle` when the sectors are very thin.
