### ISSUE TITLE
AreaChart with stackOffset displays negative values on y-axis

### ISSUE THREAD

**Issue by b00sta** [recharts/recharts#1636]
## Do you want to request a feature or report a bug?
Report
## What is the current behavior?
In stacked area chart with stackOffset: silhouette, i see negative ticks on y axis, but there is no negative values in data provided.
![image](https://user-images.githubusercontent.com/16989421/52195131-63f99b80-2878-11e9-8e23-13d9553fdbd6.png)
## What is the expected behavior?
Show only positive values.
## Which versions of Recharts, and which browser / OS are affected by this issue? 
recharts@1.4.2
## Did this work in previous versions of Recharts?
No

**Comment by xile611** [comment]
@b00sta Can you give an online demo of your case ?

**Comment by b00sta** [comment]
@xile611 Sure, https://codesandbox.io/s/pjoo413v6m

**Comment by xile611** [comment]
@b00sta 



https://github.com/d3/d3-shape/blob/master/README.md#stackOffsetSilhouette

![image](https://user-images.githubusercontent.com/6111424/52682493-9abb6a00-2f7a-11e9-8061-c364828d72e6.png)

**Comment by b00sta** [comment]
@xile611, Ok, how can i implement streamgraph?
