### ISSUE TITLE
Use custom SVG for tool tip for one of two lines

### ISSUE THREAD

**Issue by jlei523** [recharts/recharts#1637]
Hey everyone, I have a line chart with two lines.

For one of the lines, I want to use a custom svg to represent it in the chart. See screenshot. 

How can I do this?

![recharts](https://user-images.githubusercontent.com/3815607/52415966-764b3200-2b23-11e9-84f9-629f8b6e8fd7.jpg)

Here's my code:

> <ResponsiveContainer>
              <LineChart
                // width={800}
                onClick={() => {}}
                height={300}
                data={this.state.data}
                // margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
              >
                <XAxis dataKey="to_char" />
                <YAxis
                  tickFormatter={value => {
                    let val = value / 1000000;
                    return `$${new Intl.NumberFormat("en").format(val)}m`;
                  }}
                />
                <CartesianGrid strokeDasharray="3" vertical={false} />
                <Tooltip />
                <Legend />
                <Line
                  dot={false}
                  type="monotone"
                  dataKey="predictedprice"
                  stroke="#1C85E8"
                  activeDot={{ r: 8 }}
                  name="True Home Estimate™"
                  strokeWidth={3}
                />
                <Line
                  type="monotone"
                  name="Sold Price"
                  dataKey="soldprice"
                  stroke="#82ca9d"
                  shape="star"
                />
              </LineChart>
            </ResponsiveContainer>

**Comment by xile611** [comment]
@jlei523 Use customized [dot](http://recharts.org/en-US/api/Line#dot) and [activeDot](http://recharts.org/en-US/api/Line#activeDot) to render your customized svg icon.

[A demo of rendering customized dot](http://recharts.org/en-US/examples/CustomizedDotLineChart)
 
You can render customized activeDot in the same way
