### ISSUE TITLE
Update componentWillReceiveProps with getDerivedStateFromProps

### ISSUE THREAD

**Issue by pengcheng95** [recharts/recharts#1638]
## Do you want to request a feature or report a bug?
bug

## What is the current behavior?
Currently, some of the components use componentWillReceiveProps. Since this lifecycle method is unsafe, they should be updated to the new React lifecycle methods. (This includes other lifecycle methods as well) 

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts 1.4.2

**Comment by pengcheng95** [comment]
I would be happy to update the files if this isn't on anyone's road map just yet?

**Comment by alanjohnson** [comment]
I'm seeing these warnings as well (when running unit tests)

**Comment by eliotball** [comment]
Also seeing this.

**Comment by ctafield** [comment]
Still seeing this in 1.8.5. Are there any plans to address it?

**Comment by demian85** [comment]
I would replace it with `componentDidUpdate`, but really depends on the use case. I'd be happy to send a PR if someone is interested.

**Comment by malimccalla** [comment]
This is the warning as I currently see it in the chrome console

<img width="640" alt="Screenshot 2019-11-08 10 14 24" src="https://user-images.githubusercontent.com/18899991/68468768-958d0200-0210-11ea-9152-53b3b407d9fb.png">

I'm happy to make the quick fix to change them to `_UNSAFE`?

**Comment by crscaballero** [comment]
It's looks like this warning only appears when you use `<ResponsiveContainer>`

**Comment by jordymeow** [comment]
I believe it's also happening with `ResponsiveContainer`.

**Comment by crscaballero** [comment]
Fixed on `"recharts": "^2.0.0-beta.1"` version

**Comment by ryansutc** [comment]
If this is just a switch to ComponentDidUpdate would it be possible to just apply it as a fix to the latest 1x non-beta version? I don't really want to apply a major update to something still beta just so I can avoid an UNSAFE react method warning.
