### ISSUE TITLE
How can I change the color of the legend text?

### ISSUE THREAD

**Issue by promitanan** [recharts/recharts#1639]
Currently the legend text is always black, but it is hard to read with the background color I have. Is there a way to change the text to a custom color?

![image](https://user-images.githubusercontent.com/18385581/52515105-971b9200-2bcc-11e9-8d9f-99e06b9ae237.png)

**Comment by xile611** [comment]
@promitanan 
You can use [`formatter`](http://recharts.org/en-US/api/Legend#formatter) of Legend to change the color of text.

[the doc of Legend#formatter](http://recharts.org/en-US/api/Legend#formatter)
[A example of colorful legend text](https://jsfiddle.net/alidingling/32zbsx71/1/)
