### ISSUE TITLE
Stacked Charts for Positive and Negative Numbers?

### ISSUE THREAD

**Issue by atyndall** [recharts/recharts#164]
There seems to be an issue with stacking positive and negative numbers on BarCharts, I'm not sure if it's a known issue.

Here is a JS fiddle showing the issue, which presents differently depending on the ordering of the two Bar elements; http://jsfiddle.net/p9830b6y/

Here is what I would expect the generated chart to look like in both cases;
<img width="533" alt="screenshot 2016-08-09 12 10 49" src="https://cloud.githubusercontent.com/assets/1833303/17504318/807db95a-5e2a-11e6-95f9-3db0fd870662.png">

Is there some way for me to achieve this result? Have I made a mistake, or is this a bug?

Thanks,
Ash

**Comment by atyndall** [comment]
To clarify, I would expect any chart value that starts at zero and goes into negative (pv in this example) to stack under bars with positive values, and run from 0 to the given negative value (in this case -100).

**Comment by xile611** [comment]
@atyndall You can't use stacked bar chart in such case. Because the stacked chart will display the sum values.
[Here](http://jsfiddle.net/vxnhLa14/) is a workaround.

**Comment by atyndall** [comment]
@xile611 Thank you for your help, much appreciated! I will use that method.
However, I would consider this behaviour a bug. Would you agree?

**Comment by xile611** [comment]
@atyndall  😂 I don't consider it as a bug. Stacked chart need to display the sum values, and it works in your demo. Meanwhile stacked chart will vary according to the order of stacked elements.
You can check [this demo](http://jsfiddle.net/u7949z3f/) for detail.

**Comment by atyndall** [comment]
I agree that a stacked chart should display the sum of positive values as you've indicated. However you can see in other charting libraries that the common approach is that positive and negative values are generally separated and stacked above and below zero respectively.

Some examples;
Highcharts: http://www.highcharts.com/demo/bar-negative-stack
Excel: http://peltiertech.com/images/2016-03/StackedWithNegative1.png

**Comment by xile611** [comment]
@atyndall It's a good idea. We'll add an option `'sign'` to the props `stackOffset` in BarChart and AreaChart which allows the bars and areas to be stacked according to the sign of value.

**Comment by atyndall** [comment]
Cheers, thanks for all your help :)
