### ISSUE TITLE
How to make clickable tooltip?

### ISSUE THREAD

**Issue by SkryGun** [recharts/recharts#1640]
I created a custom tooltip in line chart which has a link in it but it is impossible to click.

**Comment by xile611** [comment]
@SkryGun Sorry, this feature isn't supported.  The tooltip div has attribute `pointerEvents: 'none'`  to make the hover event more smoothly.

**Comment by akzarma** [comment]
As I needed this feature urgently, I made a custom scrollable tooltip. I have also made a public repo which contains the sample project.
[https://github.com/akzarma/Recharts-Custom-Tooltip](url)

**Comment by neomehta** [comment]
@akzarma can you send me your sample code ? 
I tried the link but it doesn't work

**Comment by akzarma** [comment]
> @akzarma can you send me your sample code ?
> I tried the link but it doesn't work

Sorry, for the broken link, I updated it now.
https://github.com/akzarma/Recharts-Custom-Tooltip

**Comment by jroitgrund** [comment]
Is this still unsupported? Any suggested workarounds?

I've tried reducing the offset so you can still hover over the tooltip, but this is really iffy because the tooltip still jumps around whenever you move your cursor.

Another issue is that mouse event handlers inside the tooltip don't work at all, both with a negative offset and with trigger="click", all the onClick handlers inside my custom tooltip are completely ignored.

**Comment by connorproctor** [comment]
>Another issue is that mouse event handlers inside the tooltip don't work at all, both with a negative offset and with trigger="click", all the onClick handlers inside my custom tooltip are completely ignored.

This is because the tooltip wrapper has `pointer-events: none` set in css. I was able to have clickable links in the tooltip by setting `pointer-events: auto` on them.

**Comment by swapNXplore** [comment]
Hello i tried this solution in ScatterChart and tooltip is getting display on clicking dots, but the tooltip is not getting hide on mouse leave or outside click on graph area. It's just get displayed on clicking different dot's.
So i have to do following 2 things 

1. I want a default behaviour of tooltip, as it should be display on hover and hide on mouse leave.
2. Clickable link in tooltip and hide tooltip on mouse out.

any help would be appreciated

![Screenshot 2022-09-01 at 1 50 01 PM](https://user-images.githubusercontent.com/108389819/187867242-be5001d3-8b2d-4a15-9330-c446d5316eb3.png)

**Comment by ronalddas** [comment]
> trigger='click'

After setting, trigger to `click`, the tooltip is not auto-closing , once the cursor moves out of the canvas, in `hover` , it automatically closes,

**Comment by PratikshitSingh** [comment]
A clickable tooltip can be made using some custom defined components, below is example showing a custom clickable tooltip for LineChart:

![image](https://github.com/recharts/recharts/assets/29308153/eaef0cc0-0931-4c42-bfcf-8cf1b93d1555)
![image](https://github.com/recharts/recharts/assets/29308153/4f7917a7-9625-49f7-945e-32f637677860)
![image](https://github.com/recharts/recharts/assets/29308153/3a23bc62-641b-4ca1-9981-765d0081bdd4)
