### ISSUE TITLE
Chart top and bottom margin = 0 isn't actually 0 

### ISSUE THREAD

**Issue by b00sta** [recharts/recharts#1647]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
Chart has some space below x axis if margin.bottom = 0
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
https://codesandbox.io/s/91kk39olnw
## What is the expected behavior?
Chart border should be as close as possible to chart content
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
recharts@1.4.2

**Comment by xile611** [comment]
@b00sta Try to change the `height` of `XAxis` to reduce the space at the bottom, and change the `domain` of `YAxis` to reduce the space at the top.
