### ISSUE TITLE
How to show the legend on different position according to viewport ? 

### ISSUE THREAD

**Issue by fireworks2005** [recharts/recharts#1648]
![image](https://user-images.githubusercontent.com/18452929/52928415-89a79a00-337a-11e9-810b-0a0ee7db8a4a.png)

I would like to show the legend at the top when it is on desktop view and show the legend in the bottom on the mobile view.

**Comment by JulioVMelo** [comment]
In this case you can alter flexbox order property on media query.

example 
`
.container {
 display: flex;
 flex-direction: column;
}
`

on media query 

`
.chart {
order: 1
} 
.legend {
order: 2
}
`
