### ISSUE TITLE
Chart data toggles on click of chart legend

### ISSUE THREAD

**Issue by suriya-p-rivet** [recharts/recharts#1651]
It will be good if you guys provide the toggling functionality of chart data based on legend click. There are some temporary solutions(reducing opacity, etc....) to make it work. But those will not work for all chart components(for pie chart, doughnut chart).

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
