### ISSUE TITLE
Attribute height not allowed on element path at this point

### ISSUE THREAD

**Issue by kodermax** [recharts/recharts#1652]
## Do you want to request a feature or report a bug?
bug
## What is the current behavior?
Recharts adds height attribute and width to path (svg)
Validator W3C
![image](https://user-images.githubusercontent.com/590985/53329185-af91e900-38fc-11e9-9c68-d53ed87c08c7.png)

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
