### ISSUE TITLE
StackedBarChart with static Tooltip

### ISSUE THREAD

**Issue by erosenberg** [recharts/recharts#1653]
It is not obvious how to position a static Tooltip (relative to data point), accessing all related data, and only show on click or mouseover/hover.

## What is the current behavior?
I am unable to retrieve any information or control the coordinates very well with the `Tooltip` component based on the bar's value and not the x coordinates of the mouse. I would ideally like to have it render right above a stacked bar chart (top and centered).

I want to be able to say `followMouse: true/false` for tooltips. Is this possible?

**Comment by xile611** [comment]
It‘s recommend to use customized event.
