### ISSUE TITLE
Upgrade react-resize-detector dependency to v4

### ISSUE THREAD

**Issue by maslianok** [recharts/recharts#1659]
I'm the author of `react-resize-detector` library and I'd like to ask you to update this dependency to v4.

Recently we refactored the module to make it more performant. I hope you won't have any problems with v4.

This is crucial because some of our users have problems using resize-detector@4 with recharts which use version 2 under the hood https://github.com/maslianok/react-resize-detector/issues/63

**Comment by maslianok** [comment]
Well, we found a bug described in the issue above.

But anyway it would be great if you update to v4 🙃

**Comment by adi518** [comment]
I had my Sentry quota explode because of the exceptions caused by v2 of this dependency. Should be merged asap, however, @maslianok I take it that this PR assures v4 is fully backward compatible?

**Comment by xile611** [comment]
Please try recharts@2.0.0-beta.0
