### ISSUE TITLE
Composed chart doesn't allow scatter component

### ISSUE THREAD

**Issue by LalithKumarN** [recharts/recharts#166]
Would like to pass scatter component to a composed chart. Currently it doesn't allow to do.

**Comment by xile611** [comment]
@LalithKumarN Scatter can't be composed with Area and Line. Because  both the `XAxis` and `YAxis` are numeric axis for scatter. But for Line and Scatter, one of the XAxis or YAxis should be a categorical axis.

> It is similar to a scatter plot except that the measurement points are ordered (typically by their x-axis value) and joined with straight line segments. - [wiki](https://en.wikipedia.org/wiki/Line_chart)

You can check [this issue](https://github.com/recharts/recharts/issues/154) for detail.

**Comment by LalithKumarN** [comment]
Ok @xile611 Thanks for your help. I can use the idea of using smooth curve in scatter chart.

**Comment by tzachshabtay** [comment]
@xile611 is this still not supported?
I want to have a 3d scatter chart (like ThreeDimScatterChart in the samples) in a composed chart, I don't think I can do that with a line chart, or can I?

**Comment by geon** [comment]
The problem with both axes being of type="number" is no longer valid. Time series data *must* be of type="number" on the time-axis: http://recharts.org/en-US/api/XAxis#scale

**Comment by dsldsl** [comment]
I am looking to create a scatter plot chart with a composed layout adding bar graphs to the bottom (time) and left (float) axis.  Currently digging into this to see my options -- if it is supported directly or if I need to overlay a few charts.  If anyone has done this already or has suggestions I would welcome them.  🙏 

![image](https://user-images.githubusercontent.com/50015/175758983-f3eb8920-f3e8-4db1-b5d1-b1b497cf5ee5.png)

**Comment by Hugo-Persson** [comment]
@dsldsl did you find a solution for this?

**Comment by ckifer** [comment]
What is the use case? You might be able to use Dot

**Comment by ckifer** [comment]
`Dot` is the individual item that `Scatter` uses but it requires x and y positioning so its harder to use. Probably won't work for your case.

But see this example https://63da8268a0da9970db6992aa-xjrzabcpxn.chromatic.com/?path=/story/examples-composedchart-boxplot--box-plot-chart

I might be missing something but that looks like Scatter working within Composed chart
