### ISSUE TITLE
Bar chart with only negative values leads to some cells not being displayed correctly

### ISSUE THREAD

**Issue by huseingagajew** [recharts/recharts#1661]
## Do you want to request a feature or report a bug?
Bugreport, scaling of bars in bar chart with only negative values
## What is the current behavior?
When creating a barchart with only negative values, the scaling does not work correctly (the heights of the bars are not relative to eachother, e. g. -8 does not have double the height of -4).
If a value >= 0 is added to the data set, the scaling works again. In my example, -4 was not even displayed as a bar, until I added the minPointSize attribute.
![bug_recharts](https://user-images.githubusercontent.com/15113512/53967097-d5856d80-40f4-11e9-9696-0173956247ae.PNG)
![bug_recharts_1](https://user-images.githubusercontent.com/15113512/53967196-0e254700-40f5-11e9-834b-bcd23f8b9f11.PNG)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
https://jsfiddle.net/3efdw45r/6/

## What is the expected behavior?
The expected behavior is that the negative values are scaled correctly and lead to a bar height, which is relative to the other bars in the same chart.
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts versions 1.2.0 and 1.5.0 (did not try any versions between)
Browser/OS does not affect the bug

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
