### ISSUE TITLE
Active Dots showing outside of grid when allowDataOverflow = true

### ISSUE THREAD

**Issue by joshuagish** [recharts/recharts#1662]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
If you manually set the domain for a line graph, everything is hidden outside of the grid except for the active dots.

## If the current behavior is a bug, please provide the steps to reproduce.
https://jsfiddle.net/thecitywelivein/kgy2vnsx/13/
**Hover your mouse to see the active dots

## What is the expected behavior?
The active dots should be hidden once it reaches the X-Axis

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Using latest recharts. Bug in all browsers.

**Comment by HemapriyaG** [comment]
Any update on this?

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
