### ISSUE TITLE
Stacked bar chart stroke shouldn't overlay

### ISSUE THREAD

**Issue by ibarrae** [recharts/recharts#1666]
## Do you want to request a feature or report a bug?
Feature
## What is the current behavior?
When adding `stroke` to a `Bar` or `Cell` component, it doesn't render completely.

## What is the expected behavior?
`stroke` should render inside of `Bar`.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.5.0

## Preview
<img width="583" alt="Screen Shot 2019-03-11 at 4 18 56 PM" src="https://user-images.githubusercontent.com/22796877/54158812-64f28f80-4419-11e9-9c7c-5e5938a263cc.png">

As you can see, bar component with `32%` overlaps the stroke of `68% first post-assessment`.

**Comment by xile611** [comment]
@ibarrae It's the default behavior of svg.
Maybe this [question](https://stackoverflow.com/questions/7241393/can-you-control-how-an-svgs-stroke-width-is-drawn) can help you

**Comment by xile611** [comment]
@ibarrae Anyway, you can implement your case by customized `shape` of <Bar />
