### ISSUE TITLE
How to use Brush component on its own?

### ISSUE THREAD

**Issue by gajus** [recharts/recharts#1668]
I want to render the brush component on its own, e.g.

```js
export default () => {
  return <div>
    brush:

    <Brush
      dataKey='timeStart'
      data={data}
      width={200}
      height={30}
      stroke="#8884d8"
    />
  </div>;
};

```

But this renders nothing.

It appears that Brush must be used with Line or another chart.

I can workaround this by creating a dummy/ invisible barchart, e.g.

```js
export default () => {
  return <div>
    brush:
      <BarChart
        width={40}
        height={40}
        data={data}
        margin={{
          left: 0,
          right: 0,
          bottom: 0,
          top: 0
        }}
      >
        <Bar dataKey='measurement' maxBarSize={0} />
        <Brush
          dataKey='timeStart'
          data={data}
          stroke="#8884d8"
        />
      </BarChart>
  </div>;
};

```

Though ideally I should be able to use the Brush component on itself.

**Comment by gajus** [comment]
This could address the https://github.com/recharts/recharts/issues/1474 issue too.

**Comment by peteruithoven** [comment]
Somewhat related to: https://github.com/recharts/recharts/issues/1451

**Comment by ayepRahman** [comment]
Seems like there no solution to use Brush component on its own?

**Comment by natBizitza** [comment]
You can try to wrap it in LineChart, it works.
