### ISSUE TITLE
Vertical Barchart + Tooltip :: Click event on complete row when hovering

### ISSUE THREAD

**Issue by mberhorst** [recharts/recharts#167]
Is it possible to bind a click event, not only on the bar, but also on the bar with the grey background when hovering.

Would be really useful when the bar is to small to click.

**Comment by xile611** [comment]
@mberhorst It will be confused to bind the bar event on the background, especially for stacked bar. Maybe you can set the min height or min width of bar by the props `minPointSize`.

**Comment by mberhorst** [comment]
Yeah that will do.
