### ISSUE TITLE
How can I prevent duplicate ticks?

### ISSUE THREAD

**Issue by ohtanya** [recharts/recharts#1670]
Here's how I have it now: https://i.imgur.com/hkHIB7C.png

How can I display only 1 label per tick? I assumed the tick type="category" would do this for me but it's not working.

**Comment by burgua** [comment]
Are you using this example http://recharts.org/en-US/examples/LineChartHasMultiSeries?
**allowDuplicatedCategory** should be set to false.

**Comment by twmulloy** [comment]
this doesn't work with a `tickFormatter`.

**Comment by ailchenkoDynamo** [comment]
@twmulloy Are you fixed this issue?

**Comment by brookjordan** [comment]
I would love for a way to make this work i cases where the `tickFormatter` outputs the same value

**Comment by mateus4k** [comment]
> I would love for a way to make this work i cases where the `tickFormatter` outputs the same value

Just use `ticks` to remove duplicated values by using a `Map` for registering the first occurrences of a value.
