### ISSUE TITLE
Area Chart - On Click  function breaks, if the callback is passed conditionally via props

### ISSUE THREAD

**Issue by chetan25** [recharts/recharts#1671]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
Write now if I minify/run the code for the BarChart and have a click function passed conditionally through the props, the Bar Chart handles the click in a smart way and does not complain about the function not being defined.

Added a example -  https://jsfiddle.net/t4xLczh8/

But the same behaviour is not true for the Area Chart. The Area chart On click function throws an error if we have  click function passed conditionally .

Added a example -  https://jsfiddle.net/0uvgr5yw/ 
check the console for the error.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

Sample Added for the Bar Chart and Area Chart

Added a example -  https://jsfiddle.net/t4xLczh8/ - Area Chart
Added a example -  https://jsfiddle.net/0uvgr5yw/  - Bar Chart

* Please check the console for the error.

## What is the expected behavior?
The behaviour should remain consistent for all the charts. We can either go with throwing an error if the click function is not passed or handle it smartly like the Bar Chart.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
 
This is present in current version as the sample is taken from there.
![Screen Shot 2019-03-18 at 3 20 37 PM](https://user-images.githubusercontent.com/8482179/54567546-709e0300-4991-11e9-9e76-7c152e4d4247.png)

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
