### ISSUE TITLE
ConnectNulls line customization

### ISSUE THREAD

**Issue by sarates** [recharts/recharts#1672]
Is there any way to customize view of ConnectNulls line (color, dash type, etc)? Thanks

**Comment by rahul-desai3** [comment]
Is there a solution for this yet?
I am trying to get it to work the way it works here in Highcharts - http://jsfiddle.net/mtg6bd0o/3/

**Comment by xile611** [comment]
It's recommend to use customized `shape` to do this kind of feature.
