### ISSUE TITLE
Does not support new corejs@3

### ISSUE THREAD

**Issue by ChrisW-B** [recharts/recharts#1673]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
When compiling with .babelrc of 
```json
"presets": [
    "@babel/preset-react", 
    ["@babel/preset-env", 
      {
        "useBuiltIns": "usage",
        "corejs": "core-js@3",
        "targets": { "browsers": "> 10%" },
        "modules": false 
      }
    ]
  ],
  "plugins": ["@babel/plugin-syntax-dynamic-import", "@babel/plugin-transform-runtime"],
```
and core-js@3, the following output is produced
```
ERROR in ./node_modules/recharts/es6/polyfill.js
Module not found: Error: Can't resolve 'core-js/es6/math' in '${PATH}/node_modules/recharts/es6'
 @ ./node_modules/recharts/es6/polyfill.js 1:0-26
 @ ./node_modules/recharts/es6/index.js

ERROR in ./node_modules/recharts/es6/polyfill.js
Module not found: Error: Can't resolve 'core-js/es6/number' in '${PATH}/node_modules/recharts/es6'
 @ ./node_modules/recharts/es6/polyfill.js 2:0-28
 @ ./node_modules/recharts/es6/index.js

```
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts v1.5.0

**Comment by afgrant** [comment]
The `@babel/preset-env` property `"corejs": "core-js@3"` should instead be `"corejs": 3`

https://github.com/babel/babel/issues/9713#issuecomment-474828830

**Comment by ChrisW-B** [comment]
Thanks! That didn't fix the errors in the recharts package though, is there any other information that would help?

**Comment by vlazh** [comment]
I ran into a similar problem with latest version of @babel/register and recharts. But I'm using webpack for building. Temporary I have resolved it with webpack in not good way:
```js
    externals: (context, request, callback) => {
      if (context.includes('recharts/es6') && request.includes('/polyfill')) {
        // remove from build: module.exports = {}
        callback(null, `{}`);
        return;
      }
      callback();
    },
```
Just exclude polyfill from bundle. Maybe it will causes problem in production but works for me so far in dev mode.

**Comment by lkornilenko** [comment]
`core-js@3` doesn't have `es5/6/etc` folders anymore. They have a single folder called `es`.

So, here is my workaround using `webpack.config.js`:
```
module.exports = {
    resolve: {
        alias: {
            'core-js/es6': 'core-js/es'
        }
    }
}
```

**Comment by pedroabreu** [comment]
Is there a specific reason for the library handling polyfills ? Seems something that should be the consumer responsibility

**Comment by avindra** [comment]
So what's the story, should the polyfill be removed and we add a note to the Readme?

Or update the library to use corejs 3?

Either way, this seems like a good item to include in 2.x: https://github.com/recharts/recharts/issues/1910

**Comment by gaillota** [comment]
I think you should update to core-js 3 as it fixes a number of issues

**Comment by kelly-tock** [comment]
when will a version be published with core-js 3?

**Comment by avindra** [comment]
@kelly-tock try one of the version 2 "beta" releases. Latest as of today is [v2.0.0-beta.7](https://github.com/recharts/recharts/releases/tag/v2.0.0-beta.7) I updated to the v2 beta in a React 16 production application that uses recharts quite a bit without any issues.

**Comment by kelly-tock** [comment]
any chance there are beta types?

**Comment by kelly-tock** [comment]
also, are there new docs?  getting an error for TickFormatterFunction not being found.

**Comment by bendulum** [comment]
> Is there a specific reason for the library handling polyfills ? Seems something that should be the consumer responsibility

Imho this is a good question and valid point. Can somebody give an answer?
Dealing with `core-js` dupes because of various libraries pulling in different version can be quite nasty.

**Comment by reifnotreef** [comment]
Currently having this issue. I have tried everything described here, and on several SO topics, and nothing has been able to fix the issue.
