### ISSUE TITLE
TreeMap rect's with depth of 1 being buried by others. Cannot display depth 1 titles. 

### ISSUE THREAD

**Issue by GavinThomas1192** [recharts/recharts#1677]
## Do you want to request a feature or report a bug?
BUG / probably just me ;)
## What is the current behavior?
When using a complex 'fill' statement, the tiles with depth of 1 are being buried under the others, not allowing me to display depth 1 names, or the groups names. 
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
https://jsfiddle.net/7u4wc8ko/3/
## What is the expected behavior?
I can do complicated fills, and also render depth 1 names. 
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.4.2 / Chrome.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
