### ISSUE TITLE
Add support for Annotations component

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#1678]
## Do you want to request a feature or report a bug?
Feature

## What is the expected behavior?
There are many charting applications that require annotations. This is not significantly different than a regular data series, except that it is usually sparse on the X-axis, and in addition to having a Y-value, it also has an associated text property. The codepen example below (from a different component) shows a version of how this might work. I could see config options for controlling whether the annotation text shows on hover or on click, "dot" symbol selection and customization, etc.

https://codepen.io/susielu/pen/wrNRRK?editors=0010#0

Maybe this component could be integrated to ReCharts? https://react-annotation.susielu.com/

PS - If anyone with solid React and ReCharts experience is interested in developing this feature, I'm willing to fund the project.

**Comment by ivan-ivan** [comment]
Was this feature added? I see that the issue is closed, but couldn't find the Annotation component in a codebase.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Same question here again?

**Comment by jaekunchoi** [comment]
Any update here? I need this feature too

**Comment by h0jeZvgoxFepBQ2C** [comment]
@Eric24 Could you reopen this issue? Looks like there is no annotation-support? Or did you get this working?

**Comment by matt-takumi** [comment]
I would love something similar, such as this https://www.fusioncharts.com/fusiontime/examples/annotating-single-data-point?framework=javascript

**Comment by ugoi** [comment]
Any support for this in 2025?

**Comment by ckifer** [comment]
I didn't know this issue existed. Will look at reopening

**Comment by ckifer** [comment]
I would rather give the opportunity for the user to be able to do this themselves with coordinates from recharts than integrate this into the library. 

I would imagine that is already possible - would just need to do some experimentation

**Comment by ugoi** [comment]
I would like to do something like this: https://youtu.be/ssNBCeWKW8k?t=41
How would I implement this with coordinates from recharts?

**Comment by PavelVanecek** [comment]
Is `react-annotation` the best library for this? Looks like it's not maintained, and only supports React 16.

**Comment by PavelVanecek** [comment]
@ugoi you should be able to get the information you need from `useActiveTooltipDataPoints`, see https://main--63da8268a0da9970db6992aa.chromatic.com/?path=/story/examples-linechart-duallinechart--dual-line-chart and https://main--63da8268a0da9970db6992aa.chromatic.com/?path=/story/api-hooks-useactivetooltipdatapoints--use-active-tooltip-data-points and https://github.com/recharts/recharts/blob/main/storybook/stories/Examples/LineChart/DualLineChart.stories.tsx. The storybook example is using a different hook but the information coming out of it should be the same.

**Comment by PavelVanecek** [comment]
Also check out the Crosshairs - I added that as a helper/debug tool for our storybooks:

<img width="1251" height="715" alt="Image" src="https://github.com/user-attachments/assets/21e09afe-3a2e-4c88-9ca7-67b43546bd74" />

This is available in every storybook on recharts.org, here is how to use it: https://main--63da8268a0da9970db6992aa.chromatic.com/?path=/docs/api-hooks-hookinspector--docs

Here is the impl: https://github.com/recharts/recharts/blob/main/storybook/storybook-addon-recharts/crosshairs/CrosshairControls.tsx

**Comment by ugoi** [comment]
@PavelVanecek @ckifer  
I found this other library which does what I want. How difficult is it to adjust Recharts to have this annotation capability?  
I'd rather stick to Recharts since I'm already using it and it's more modular.  

**AG Grid Charts Annotations:**  
https://www.ag-grid.com/charts/react/annotations/

**Example video of what I want:**  
<video src="https://github.com/user-attachments/assets/6486c8bd-61bd-447a-8bfd-e3c3913d4798" controls width="700"></video>

Here’s where I’m currently at:  
I figured out how to add lines using the `ReferenceLine` component.  
Now I just need to:
- detect if and where the user clicked in the chart to add a reference line,  
- detect when the user is hovering over an existing line to highlight it.  
- detect when the user clicks an existing line to show a floating toolbar for editing or deleting,  
- detect when the user drags a line to move it.  

Is this all possible within Recharts, or should I render an invisible overlay for interactive elements?

**Current progress:**  
<img width="980" height="697" alt="Current Progress" src="https://github.com/user-attachments/assets/3979780c-8d75-4ba9-9172-ac6257aefb53" />

**Comment by kvtemadden** [comment]
> [@PavelVanecek](https://github.com/PavelVanecek) [@ckifer](https://github.com/ckifer) I found this other library which does what I want. How difficult is it to adjust Recharts to have this annotation capability? I'd rather stick to Recharts since I'm already using it and it's more modular.
> 
> **AG Grid Charts Annotations:** https://www.ag-grid.com/charts/react/annotations/
> 
> **Example video of what I want:**
> 
>  Screen.Recording.2025-11-13.at.21.00.47.mov 
> Here’s where I’m currently at: I figured out how to add lines using the `ReferenceLine` component. Now I just need to:
> 
> * detect if and where the user clicked in the chart to add a reference line,
> * detect when the user is hovering over an existing line to highlight it.
> * detect when the user clicks an existing line to show a floating toolbar for editing or deleting,
> * detect when the user drags a line to move it.
> 
> Is this all possible within Recharts, or should I render an invisible overlay for interactive elements?
> 
> **Current progress:** <img alt="Current Progress" width="980" height="697" src="https://private-user-images.githubusercontent.com/96357300/514080874-3979780c-8d75-4ba9-9172-ac6257aefb53.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjY0MDUxMjQsIm5iZiI6MTc2NjQwNDgyNCwicGF0aCI6Ii85NjM1NzMwMC81MTQwODA4NzQtMzk3OTc4MGMtOGQ3NS00YmE5LTkxNzItYWM2MjU3YWVmYjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjIyVDEyMDAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNGJmOTAyNDI2MTU3MjI4MWYzMWUxOWIyODgzNDFhN2I5OWZkZmJhMmNlN2MxMmFjMDRjMjc3NDkwYzUzN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jGmCXk3DsgxoRamAjmAx3TviM59s2TqYiYbbHgxdtwA">

@PavelVanecek did you get any further with this?

**Comment by PavelVanecek** [comment]
Negative @kvtemadden I was doing other things. I'll get to annotations once https://github.com/recharts/recharts/issues/6069 and https://github.com/recharts/recharts/issues/6645 are done I think. Feel free to contribute, this should be fairly simple to document and/or add I imagine.
