### ISSUE TITLE
Data points flow outside Area Chart

### ISSUE THREAD

**Issue by MagWeaver** [recharts/recharts#1680]
## Do you want to request a feature or report a bug?
Report a bug

## What is the current behavior?
Data flows outside of the chart. The slider controls the number of data points. This seems to be a problem when the total number of data points is high ~50.
![image](https://user-images.githubusercontent.com/16656834/54857823-8fb4d180-4cbe-11e9-8531-e337c10d0a34.png)

## What is the expected behavior?
Data points should be contained in the chart always.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
v 1.4.2
FireFox  65
Chrome  73
This was an issue in v 0.22.5 also.

**Comment by xile611** [comment]
@MagWeaver Please reopen this issue if an online demo can be provided.
