### ISSUE TITLE
ReferenceArea not rendering path element

### ISSUE THREAD

**Issue by diego-betto** [recharts/recharts#1682]
## Do you want to request a feature or report a bug?
bug

## What is the current behavior?
ReferenceArea is rendered without `path` element inside in some chart ( => it's not visible)

## What is the expected behavior?
ReferenceArea rendered completely

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Recharts 1.5.0
Ubuntu 18.10
Chromium 73

Maybe related to #606 

Sometimes xAxis contains an attribute `duplicateDomain`. 
If it exists all calls to `scale.x.apply(<value>)` fail. 

Example data. 

``` JSON
{
  "hide": true,
  "dataKey": "time",
  "label": "",
  "height": 30,
  "axisLine": false,
  "tickLine": false,
  "domain": [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,

....

    112,
    113,
    114,
    115,
    116,
    117,
    118,
    119,
    120,
    121,
    122,
    123,
    124,
    125
  ],
  "interval": "preserveStartEnd",
  "allowDecimals": true,
  "orientation": "bottom",
  "width": 1180,
  "mirror": false,
  "xAxisId": 0,
  "tickCount": 5,
  "type": "category",
  "padding": {
    "left": 0,
    "right": 0
  },
  "allowDataOverflow": false,
  "reversed": false,
  "allowDuplicatedCategory": true,
  "axisType": "xAxis",
  "duplicateDomain": [
    1553519700,
    1553519871,
    1553520566,
    1553521937,
    1553522962,
    1553522977,
    1553523404,
    1553524208,
    1553524448,
    1553524652,
    1553524944,
    1553525511,
    1553525800,
    1553526447,

....

    1553549247,
    1553549547,
    1553549847,
    1553550147,
    1553550447,
    1553550747,
    1553551047,
    1553551347,
    1553551647
  ],
  "originalDomain": [
    "auto",
    "auto"
  ],
  "isCategorial": true,
  "layout": "horizontal",
  "realScaleType": "band",
  "x": 60,
  "y": 400,
  "bandSize": 9.365079365079366
}
```

If I run these calls from inspector (after a breakpoint there https://github.com/recharts/recharts/blob/master/src/cartesian/ReferenceArea.js#L78 ) 

`scale.x.apply(1553522962)`    ---->  result `undefined`, but exists in `duplicateDomain`
`scale.x.apply(60)`    ---->  result `621.9047619047619`

When there is no `duplicateDomain` everything works fine.

It seems to me that this ends with a `return null` here
https://github.com/recharts/recharts/blob/master/src/shape/Rectangle.js#L138

**Comment by diego-betto** [comment]
`duplicate Domain` is present if there are duplicate keys. Ok.
I don't anyway understand why ReferenceAreas are not rendered correctly

**Comment by xile611** [comment]
It's recommended to remove duplicated keys.
Becase It'll be difficult to find which key you are specifying.
