### ISSUE TITLE
ReferenceLine is not showing when alwaysShow is set for axis X

### ISSUE THREAD

**Issue by hartatovich** [recharts/recharts#1683]
## Do you want to request a feature or report a bug?
BUG
## What is the current behavior?

ReferenceLine is not showing when alwaysShow is set for axis X

https://jsfiddle.net/wLdf9hs0/

## What is the expected behavior?

if you will go into the fiddle at line 21 and change the value from 2501 into 2500 the line will be visible - alwaysShow is set however when line 21 is with value 2501 the line is not visible 

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

1.5.0

**Comment by mbj36** [comment]
It is visible on the left side, however reference line will be visible inside chart if the value of x is one of the values of dataKey (which is `amt` in your case), If you replace `x={2501}` with `x={2500}` you can see the line inside graph

**Comment by hartatovich** [comment]
yeah.. but on y axis it seems to work differently 
it seems that on y axis i can use a reference line even if its not in the values
i need it to be visible when the value is NOT inside the data it self

**Comment by mbj36** [comment]
You can use the closest value and show the line 
 
Here `score` is 2501, and `x` is x-axis data
   ```
const closest =
      x &&
      x.reduce(function(prev, curr) {
        return Math.abs(curr - score) < Math.abs(prev - score) ? curr : prev;
      });
```

This will give you the closest value and reference line will be visible too

**Comment by hartatovich** [comment]
@mbj36 
thank you for this but this is not what i need
i need to show exactly the value i need for the reference line regardless if its on the data or not 

(this is the default behaviour for y axis so i don't understand why its not the same for the x axis , feel like a bug  )

**Comment by stephenw1016** [comment]
@hartatovich 
If you can, please describe the intent of your reference line? The X-axis in your demo is "ordinal" (or grouping into categories). So when you specify x={2501}, you're attempting to show a reference line in a category that doesn't exist.

Typically a Line chart is used to visualize data over time... where you would be able to use a "time" scale for your X-axis. Which would place your reference line at the correct point.

Perhaps I can suggest a more appropriate visualization or scale if I can learn more about what you're trying to do.

**Comment by rgallison** [comment]
I second this need. I have a bar graph with set ticks on the x axis and the y to represent the probability of getting between x1 and x2, etc.  I need to add a reference line to a bar bar chart to show the average
