### ISSUE TITLE
Axis tick label alignment issue

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#1684]
## Do you want to request a feature or report a bug?
Not sure, refer to this image:
![image](https://user-images.githubusercontent.com/685316/55046399-72aa3680-500f-11e9-980f-47e8fd415983.png)

## What is the current behavior?
This applies to charts inside a clipping element (such as a UI tab). The calculation that sets the position of the tick label appears to try to compensate for the length of the label text. That's good, but perhaps the calculation of the text length is thrown off by the particular font?

In any case, maybe it's not possible to always calculate this correct, which is fine. So my attempt to fix the clipped text was to add some right-side padding to the chart. Unfortunately, whatever is calculating the text position decides that it now has enough room to move the text to the right (presumably until it's centered on the tick), resulting in the same clipped character. In order to fix this using chart padding, way too much padding is necessary.

## What is the expected behavior?
Ideally, there should be some way to control the position of the tick label text (either automatically or manually) at the ends of the axis.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
All browsers, all recent versions.

**Comment by xile611** [comment]
Related to #2027
