### ISSUE TITLE
Suppress LogUtils warning when using Responsive Container

### ISSUE THREAD

**Issue by kimfucious** [recharts/recharts#1686]
Recharts v. 1.5.1

I don't think this is a bug, _per se_, but it's confounding behavior.

I've also seen questions being asked about this topic, but I've not every seen them answered.

The current behavior is that warnings are being sent to the console log, when using a Responsive Container and no specific sizing on the width or height (i.e. both are set with percentages).

```console
The width(0) and height(0) of chart should be greater than 0, please check the style of container, or the props width(100%) and height(100%), or add a minWidth(undefined) or minHeight(undefined) or use aspect(undefined) to control the height and width.
```

The chart is rendering correctly in the UI, and its size "responds" accordingly when the size of its parent container changes.

So at this point, there seems to be no need for throwing a warning, though I'm sure you have a reason.

To see this, just try to render a chart like the below:

```react
    <ResponsiveContainer height={"100%"} width={"100%"}>
         ...
    </ResponsiveContainer>
```
The expected behavior is that if a Responsive Container is placed into a parent container, and that parent has a height and a width, then the Responsive Container should render appropriately (which it does) **and** should not show a warning in the console.  

Or there should be a way to get rid of the console warning *without* having to add erroneous size-related params.

**Comment by xile611** [comment]
please open a new issue according to the issue guide, if you have more detail suggestion .

**Comment by llccrr** [comment]
Well, everytime I find a post with the same warning that I do, you are just ignoring it and closing the issue...
Using ResponsiveContainer into a component imported dynamically with React Suspense throw this warning too while it's working perfectly and resizing well.

**Comment by wuifdesign** [comment]
having the same issue

**Comment by MikeDrewitt** [comment]
I'm having a similar issue where I'm getting 

```
react_devtools_backend.js:3973 The width(200) and height(200) are both fixed numbers,
       maybe you don't need to use a ResponsiveContainer. 
```

Use case is a wrapped component that takes a prop which sometimes renders it as a response container with an `80%` width, other times it renders as a static container with a provided px width. 

Everything is working correctly, I would just like a way to suppress the warnings if at all possible.

**Comment by MarceloArraes** [comment]
As no one commented here, there is a quick trick to make the warning go away and it is declaring its height as a fixed value. It's not ideal considering that using 100% for height and width works perfectly, but I did it like this to make the warning go away:
`        <ResponsiveContainer height={245} width={'100%'}>
          {children}
        </ResponsiveContainer>`

**Comment by albertocubeddu** [comment]
<ResponsiveContainer
                        width="100%"
                        height="100%"
                        initialDimension={ { width: 320, height: 200 } }
                    >

@MarceloArraes if you need this is a nice workaround

**Comment by ldeveber** [comment]
> <ResponsiveContainer width="100%" height="100%" initialDimension={ { width: 320, height: 200 } } >
> 
> [@MarceloArraes](https://github.com/MarceloArraes) if you need this is a nice workaround

This worked for me, but the `width="100%" height="100%"` is not necessary. Just adding `initialDimension` will suppress the warning.

```tsx
<ResponsiveContainer initialDimension={{ width: 320, height: 200 }}>
```
