### ISSUE TITLE
Reference Line breaks when Lines have an assigned axis.

### ISSUE THREAD

**Issue by aflegel** [recharts/recharts#1688]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
Reference Line crashes component when Line is assigned to a specific axis
> Cannot read property 'scale' of undefined at t.value (ReferenceLine.js:312)
### Functional:
* 2 axis graph: 
  * https://jsfiddle.net/alexgflegel/5unx4087/7/
* With Line, 1 axis: 
  * https://jsfiddle.net/alexgflegel/nxgduo83/4/

### With Bug:
* Line has assigned yAxisId: 
  * https://jsfiddle.net/alexgflegel/mwd097sf/
* Adding an xAxisId breaks the XAxis component (even if you add a type):
  * https://jsfiddle.net/alexgflegel/uym7f309/1/

## What is the expected behavior?
Reference Line should display on specific axis as indicated
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Chrome@73.0.3683.86
recharts@1.5.0

**Comment by rlemon** [comment]
This is still happening for me on recharts 1.6.2, chrome 74.0.3729.131   

Is there currently a workaround? I am having no luck.

**Comment by aflegel** [comment]
I was unable to find a workaround.

**Comment by rlemon** [comment]
It appears to be related to adding `xAxisId` to an `<XAxis>` throwing errors. see #1476 

however, I still have not found a proper workaround. If I find something I'll make sure to update you.    

Cheers.

**Comment by rlemon** [comment]
@aflegel https://jsfiddle.net/j67cphox/ see if this helps. instead of using an xAxisId I've set the xaxis directly, and I've used the integer values for the axis id's. Seems to have solved my immediate problems. Hope this can be of some help.

**Comment by aflegel** [comment]
Sadly TypeScript doesn't like that workaround, but I'll see if I can adapt it

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
