### ISSUE TITLE
How to change responsive container's height in % instead of default 100%?

### ISSUE THREAD

**Issue by eXtremeX** [recharts/recharts#169]
Hi, I'm not sure how to do this.

I have this:
```
<ResponsiveContainer>
        <AreaChart data={this.props.data} margin={{top: 5, right: 30, left: 20, bottom: 5}}>
                .....
        </AreaChart>
</ResponsiveContainer>
```

When I inspect it, it shows:
`<div class="recharts-responsive-container" style="width: 100%; height: 100%; position: relative;">`

I'd like to change that height: 100% to height: 80%.
What's best way to do that?    

I tried doing this: `<ResponsiveContainer height={'80%'}>` and visually it worked, but when inspecting I still noticed it says the same: `<div class="recharts-responsive-container" style="width: 100%; height: 100%; position: relative;">`

And because of that, chart is rendered in 80% of the space, but then there's a lot of "margin" below it (looks like it's still using the 100% of the height, like chart is 80% of the height now, there's empty space below it and that combined still takes 100% of the div's height) and only then does the other content continues. When I manually, in inspector change 100% to 80% it works as I want it to work.

-------------------------div----------------------------
[Chart]
[Chart]      <- chart using 80% of the height
[Chart]                                                                                       
.     <- empty space (other 20% of the height)
------------------------/div------------------------------
[other content]

And I'd like:
-------------------------div----------------------------
[Chart]
[Chart]      <- chart using 80% of the height
[Chart]                                                                                       
[other content]      <- other 20% of the height
------------------------/div------------------------------

Any ideas?

**Comment by xile611** [comment]
@eXtremeX In such case, you can set the style of the parent node of responsive container.
