### ISSUE TITLE
Line chart line does not get drawn on Microsoft Edge

### ISSUE THREAD

**Issue by priyath** [recharts/recharts#1690]
## Do you want to request a feature or report a bug?
Bug (?)

## What is the current behavior?
The line chart gets rendered without the line that interconnects the data points. (See attached image)
![dot-chart](https://user-images.githubusercontent.com/10166923/55329542-7bd25200-54ac-11e9-91ca-474b74c4eeb0.png)

The issue is sporadic in nature and a toggle between the line and bar chart fixes this. The chart works as expected on Chrome and Firefox. I have also noticed that when the issue arises, the path element (within the svg) has 0px 0px as the `stroke-dasharray` value, which seems to be the reason for the line to not get drawn on render. (see html code snippet shown below)

This same behavior is observed on chrome; However when this happens in chrome the line appears. (without the usual drawing animation)

If it is important, the data is loaded to the chart via an API call.

`<path class="recharts-curve recharts-line-curve" fill="none" stroke="#ffab00" stroke-opacity="0.8" stroke-dasharray="0px 0px" stroke-width="3" d="M 100 345 L 156.167 345 L 212.333 345 L 268.5 345 L 324.667 345 L 380.833 345 L 437 345 L 493.167 345 L 549.333 345 L 605.5 344.31 L 661.667 278.671 L 717.833 64.2212 L 774 345" width="764" height="305" />`

## What is the expected behavior?
The line chart should render with the line interconnecting the data points.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Rechart version: 1.2.0
Operating System: Windows 10
Browser: Edge

I would appreciate some pointers on what could be the reason for this issue as I am mainly interested in figuring out the root cause of the problem. I am unable to provide a workable demo as this problem is observed in an internal web application. So apologies for that

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
