### ISSUE TITLE
Chart jumps instead of animating when data updates

### ISSUE THREAD

**Issue by refrigerator** [recharts/recharts#1691]
## Do you want to request a feature or report a bug?
Report a bug

## What is the current behavior?
With a `ScatterChart`, when updating the `data` for a particular `Scatter` series, the chart doesn't animate from the old to the new data points. Instead, it "jumps":

![image](https://cl.ly/e1f1c516fd0f/Screen%20Recording%202019-04-01%20at%2010.08%20PM.gif)

(the animation you see at the end is when it brings the data points onto the new chart scale)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

```
<ScatterChart
            height={500}
            margin={{ top: 20, right: 20, bottom: 10, left: 10 }}
          >
            <CartesianGrid strokeDasharray="2 2" />
            <XAxis
              dataKey="x"
              name="years"
              unit=" years"
              type="number"
              domain={[0, maxX]}
              tickCount={maxX / 5 + 1}
            />
            <YAxis
              dataKey="mean"
              name="value"
              tickCount={tickCountY}
              tickFormatter={tick => formatValue(tick, "currency")}
              domain={[minY, maxY]}
            />        
            <Scatter
              name="Buy"
              data={[...buyData]}
              fill="#2D9CDB"
              shape={
                <ScatterShape
                  startColor="#2D9CDB"
                  endColor="rgba(255,255,255,0)"
                  width={2}
                />
              }
            />
          </ScatterChart>
```
`buyData` gets updated.

## What is the expected behavior?
It should animate from old to new data points.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
OSX 10.13.6, Chrome Version 73.0.3683.86

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
