### ISSUE TITLE
Adding static text on chart

### ISSUE THREAD

**Issue by dandrei** [recharts/recharts#1696]
## Do you want to request a feature or report a bug?
Feature or guidance

## What is the expected behavior?
Using recharts `1.5.0` to draw a chart with the following components:
- `ResponsiveContainer`
- `LineChart`
- `CartesianGrid`
- `XAxis`
- `YAxis`

So it's a vanilla rectangular line chart. I'm trying to add static a piece of text (not related to the data being displayed) in the lower-right corner of the grid. I could hack together some CSS & HTML to get the text there from a neighboring DOM element, but I'd rather do it using the recharts API.

Any idea? Thanks!

**Comment by xile611** [comment]
@dandrei You can use [<ReferenceDot />](http://recharts.org/en-US/api/ReferenceDot) to calculate the location of text, and render the static text through the `label` of ReferenceDot
