### ISSUE TITLE
Brush doesn't render Graph

### ISSUE THREAD

**Issue by nk2580** [recharts/recharts#1698]
## Do you want to request a feature or report a bug?

BUG

## What is the current behavior?

when using a Brush component the control work as desired but there is no visual graphabe data inside the control

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

standard usage of library as per documentation

## What is the expected behavior?

the brush should render a graph inside its control

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts? 

this worked in the early Beta releases but now no longer works

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
