### ISSUE TITLE
Bar Chart not rendering correctly when data is provided to the bar rather than the chart

### ISSUE THREAD

**Issue by david-cunningham-rezult** [recharts/recharts#1699]
Do you want to request a feature or report a bug?
BUG

What is the current behavior?
Instead of rendering like the scatter/line chart when data is provided to the bars, the bars will fail to render but the tooltip still appears as if it had

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
Fiddle for the bar char (bugged):
https://jsfiddle.net/epdrw6kt/4/

Fiddle for a line chart for the same information:
https://jsfiddle.net/t6kax2vs/2/

What is the expected behavior?
The bars should render

Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.5.0 (or whatever the JS fiddle is)

Original Issue (Might be helpful)
So I have it set up where I try and treat all Cartesian plots a little like you would a scatter plot. As such, different lines, bars, etc are represented by different data sets for the sake of clarity (also, considering that there might not be a 1:1 coordination between each slot).

This works fine on LineCharts and Scatter Charts, but seems to fail for a BarChart.
Take for example this fiddle for the bar chart:
https://jsfiddle.net/epdrw6kt/4/

And this fiddle for a line chart for the same information:
https://jsfiddle.net/t6kax2vs/2/

**Comment by natasha-robarge** [comment]
I'm having this issue as well - I'm trying to find a fix for it

**Comment by david-cunningham-rezult** [comment]
You can workaround by converting your code a format that the bar chart can use (like is provided in the examples).

Obviously not idea, as it makes the code less configurable if you're trying to get all your cartesian charts to render in the same way. Here's some example code on the conversion.
````
const usableData = {};
    Object.keys(data).forEach((s)=>{
        data[s].forEach(d=>{
            const x = d[xAxis];
            const y = d[yAxis];
            let entry = usableData[x];
            if (!entry) entry = {};
            Object.assign(entry, {"xAxis": x, [s]: y});
            usableData[x] = entry;
        })
    });
```

With the bar chart looking like this:

```
<ResponsiveContainer height={300} width="95%">
            <BarChart data={Object.values(usableData)}>
                <CartesianGrid strokeDasharray="3 3"/>
                <XAxis dataKey="_xAxis" type="category"/>
                <YAxis/>
                <Tooltip/>
                <Legend />
                {Object.keys(data).map((s, index) => (
                    <Bar dataKey={s} name={s} key={s} fill={colors[index%colors.length]}/>
                ))}
            </BarChart>
        </ResponsiveContainer>
```

**Comment by natasha-robarge** [comment]
Hmm.. That's a really useful solution - thank you. I'm currently trying to create a stacked bar chart with data coming in from an API - the data would be an array of objects that has the id of the object, and then it would have a property called "products" that holds the array with the actual data. I'm unsure if your solution would work for my scenario, but hopefully it gives me an idea for how to handle the data.

**Comment by Gcuencam** [comment]
This issue should be reopened. When you provide the data through Bar component instead of BarChart component the bars are not printed. 
A lot of times when you want to create a stacked bar chart, the data of the stack is in different objects, for example: 
`const data = [
  {
    country: 'Perú',
    values: [
      { x: '1998', y: 2, },
      { x: '2000', y: 3, },
      { x: '2005', y: 5, },
      { x: '2010', y: 4, },
      { x: '2020', y: 6, }
    ]
  },
  {
    country: 'Argentina',
    values: [
      { x: '1998', y: 1, },
      { x: '2000', y: 1, },
      { x: '2005', y: 2, },
      { x: '2010', y: 3, },
      { x: '2020', y: 5, }
    ]
  },
  {
    country: 'México',
    values: [
      { x: '1998', y: 3, },
      { x: '2000', y: 4, },
      { x: '2005', y: 3, },
      { x: '2010', y: 2, },
      { x: '2020', y: 3, }
    ]
  }
]`
The final result should be: 
`
  <BarChart width={730} height={300}>
    <XAxis dataKey="x" tick={<MyAxisLabel />} height={60} />
    <YAxis dataKey="y" />
    <Bar data={data[0].values} dataKey="y" />
    <Bar data={data[1].values} dataKey="y" />
    <Bar data={data[2].values} dataKey="y" />
  </BarChart>
`
But in the examples the stacked data is only provided in the same object: http://recharts.org/en-US/examples/StackedAreaChart (with differente keys, pv-uv)

**Comment by Mathijs003** [comment]
any update on this? seems not to work

**Comment by gmartinezETRA** [comment]
Has this issue been solved? I see it is closed, but I don't see it working yet on my code (while with the Line it works)

**Comment by Y2KForever** [comment]
I'm still seeing this issue. Will this not be fixed?

**Comment by sirowood** [comment]
A quick but not the best working way:
`<BarChart width={730} height={300} **data={data }**>
// ...
`

**Comment by luap2703** [comment]
Any update until now? :)

**Comment by ckifer** [comment]
Still unsupported. Once 3.0 is out it this can probably be worked on
