### ISSUE TITLE
How to hide reference dots & reference lines?

### ISSUE THREAD

**Issue by nrkin** [recharts/recharts#170]
Hello!

I want to create a Spark Line - so I used TinyLineChart with width = 50 and height = 30. But the reference dots are still visible and disproportionately big. So I want to hide them or at least make them very very small. How can we do that?

Thank you for any help.
Nachiket.

**Comment by xile611** [comment]
@nrkin Can you provide an online fiddle demo ?  You can fork [this demo](http://jsfiddle.net/xyw5e9yb/3/?utm_source=website&utm_medium=embed&utm_campaign=xyw5e9yb) and update it.

**Comment by nrkin** [comment]
@xile611: Here it is : http://jsfiddle.net/16h2935k/1/. I have just set the width to 50 and height to 30 of TinyLineChart. 
Apologies for not providing the link before.

**Comment by xile611** [comment]
@nrkin When the props `dot` is set to be `false`, no dots will show. [Here](http://recharts.org/api#Line) is the api of `Line`. And you can check [this demo](http://jsfiddle.net/16h2935k/3/) for detail.

**Comment by nrkin** [comment]
Yes. `dot` is the prop I was looking for. Thanks! :-)

**Comment by nrkin** [comment]
Sorry to comment on a closed issue - but the question I have is related to this question.
I have a spark line kind of component with tooltip. I have "dot" set to false. If I use Tooltip in the LineChart, the vertical reference line becomes visible. Is there a way to hide the line?

**Comment by xile611** [comment]
@nrkin  You can set the props `cursor` of `Tooltip`  to be `false`.

```jsx
  <Tooltip cursor={false} />
```

**Comment by nrkin** [comment]
@xile611 : Thanks! It worked.
