### ISSUE TITLE
Production build with rechart getting crashed because of 1.toFixed

### ISSUE THREAD

**Issue by knitvijay** [recharts/recharts#1702]
## What is the current behavior?

I am using rechart to plot bar chart in my app and on local machine it is working fine but white trying to deploy prod build it is getting crashed with below error, it is caused by code like s=1.toFixed after minification using webpack. This error is coming even for a very simple graph. 

"SyntaxError: identifier starts immediately after numeric literal"

using "recharts": "^1.5.0", with react 16.x

below are some code parts I copied from main-bundle.js.

,**s=1.toFixed**,d=Math.floor,p=[0,0,0,0,0,0],c='Number.toFixed: incorrect invocation!',u='0',h=function(e,t){for(var a=-1,n=t;6>++a;)n+=e*p[a],p[a]=n%1e7,n=d(n/1e7)},g=function(e){for(var t=6,a=0;0<=--t;)a+=p[t],p[t]=d(a/e),a=1e7*(a%e)},b=function(){for(var e=6,a='';0<=--e;)if(''!=a||0==e||0!==p[e]){var n=p[e]+'';a=''==a?n:a+l.call(u,7-n.length)+n}return a},v=function(e,t,a){return 0===t?a:1==t%2?v(e,t-1,a*e):v(e*e,t/2,a)},T=function(e){for(var t=0,a=e;4096<=a;)t+=12,a/=4096;for(;2<=a;)t+=1,a/=2;return t};n(n.P+n.F*('0.000'!==8e-5.toFixed(3)||'1'!==0.9.toFixed(0)||'1.25'!==1.255.toFixed(2)||'1000000000000000128'!==**1000000000000000100.toFixed(0)**||!a(85)(function(){s.call({})})),'Number',{toFixed:function(t){var a=r(this,c),n=o(t),d='',s=u,p,m,f,_;if(0>n||20<n)throw RangeError(c);if(a!=a)return'NaN';if(-1e21>=a||1e21<=a)return a+'';if(0>a&&(d='-',a=-a),1e-21<a)if(p=T(a*v(2,69,1))-69,m=0>p?a*v(2,-p,1):a/v(2,p,1),m*=4503599627370496,p=52-p,0<p){for(h(0,m),f=n;7<=f;)h(1e7,0),f-=7;for(h(v(10,f,1),0),f=p-1;23<=f;)g(8388608),f-=23;g(1<<f),h(1,1),g(2),s=b()}else h(0,m),h(1<<-p,0),s=b()+l.call(u,n);return 0<n?(_=s.length,s=d+(_<=n?'0.'+l.call(u,n-_)+s:s.slice(0,_-n)+'.'+s.slice(_-n))):s=d+s,s}})},function(e,t,a){'use strict';var n=a(22),o=a(85),r=a(679),**s=1.toPrecision**;n(n.P+n.F*(o(function(){return'1'!==s.call(1,void 0)})||!o(function(){s.call({})})),'Number',

## What is the expected behavior?

Code should work for production build also.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

using "recharts": "^1.5.0", with react 16.x

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
