### ISSUE TITLE
Animating Reference Line breaks Hovering to show Tooltip

### ISSUE THREAD

**Issue by Falieson** [recharts/recharts#1703]
## Do you want to request a feature or report a bug?
This is probably more of a feature than a bug

## What is the current behavior?
I'm using charts to show data over time and I want to "play" that data by changing the index of the reference line. If you hover over the chart while its playing the label appears and then disappears when the reference line is updated.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
(When adding recharts to coderpen it doesn't appear to be available on the global this?)

## What is the expected behavior?
The label stays visible while hovering, regardless of the reference line updating

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts 1.5.0, React 16.8.6

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
