### ISSUE TITLE
Allow hiding tooltips in synchronized graphs

### ISSUE THREAD

**Issue by sevdog** [recharts/recharts#1704]
## Do you want to request a feature or report a bug?
Feature

## What is the current behavior?
As of now when two or more graphs share the same `syncId` if one gets focused showing tooltip all the othesr will follow (see picture).
![actual](https://user-images.githubusercontent.com/13779643/56037233-1180a380-5d2f-11e9-9994-366c6da1ff60.png)

## What is the desired behavior?
It could help to disable just the tooltip component in synchronized charts while keep showing active dot and line and keeping the actual behaviour in the focused chart (see picture)
![desired](https://user-images.githubusercontent.com/13779643/56037263-23fadd00-5d2f-11e9-9c17-b8ed57afb2d5.png)

**Comment by xile611** [comment]
Duplicated with #1231
