### ISSUE TITLE
Duplicate keys in x-axis cause ReferenceLine not to render

### ISSUE THREAD

**Issue by TeemuKoivisto** [recharts/recharts#1709]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
Currently if x-axis receives a duplicate string(possibly happens also with number) key it causes every x-axis ReferenceLine not to render.
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
I couldn't get the JSFiddle to work but I forked the repo and replicated the problem with the demo-site: https://github.com/TeemuKoivisto/recharts/commit/0bd163b77bc009b75e02b335322293b01b4c663f
## What is the expected behavior?
To throw an error about duplicate values in x-axis, quite difficult bug to find. I tracked it down to CartesianUtils.js `isInRange` returning false for the x-axis domain (list of the keys).
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Latest recharts & Chrome.

**Comment by devdream123** [comment]
I got this bug. This happens when you have duplicated x-axis values. For example hours. 3am , 6am ... , 3am. If you have reference line at 3am, it will. throw error due to duplication.
