### ISSUE TITLE
What is uv and pv?

### ISSUE THREAD

**Issue by RichardJECooke** [recharts/recharts#171]
Please add a note in the documentation defining uv and pv:
 http://recharts.org/examples#SimpleRadialBarChart

**Comment by xile611** [comment]
@RichardJECooke  [uv](https://en.wikipedia.org/wiki/Unique_user#Unique_visitor) and [pv](https://en.wikipedia.org/wiki/Page_view) are just two indicators commonly used in web analysis. You can search `uv` and `pv` in google.

**Comment by RichardJECooke** [comment]
Oh, I see. I was hoping they were Recharts values, like min & max.  Thanks for replying.

How can I make just a one-bar chart like this?
![untitled](https://cloud.githubusercontent.com/assets/5468805/17664257/25578b8c-62f3-11e6-95ec-7c0e47a9d22d.png)

From your API I cannot see a way of specifying the max value for a chart. I've tried this:

```
const chartData = [
    {name: 'score', value: data.creditScore, fill: '#aaa'}
  ];
  return React.createClass({
    render () {
      return (
        <RadialBarChart   width={300} height={244} cx='50%' cy='50%'
                          outerRadius={50} barSize={40} data={chartData}>
          <RadialBar startAngle={-1 * 135} endAngle={-1 * 405} background clockWise={true} dataKey='value'/>
        </RadialBarChart>
      );
    }
  });
```

but only actual value is set, not the max value, so the chart isn't showing 68%, it shows 50%

![untitled2](https://cloud.githubusercontent.com/assets/5468805/17664321/8990a570-62f3-11e6-8a20-461d0359234a.png)

**Comment by xile611** [comment]
@RichardJECooke  
There are two workarounds: 
[One](http://jsfiddle.net/vfeoLdp6/1/) is done by PieChart, and [another](http://jsfiddle.net/exjbso5f/) is through RadialBarChart.

**Comment by RichardJECooke** [comment]
Thanks, that'll help for now.  But this is a bit hacky and will prevent people from doing more complex graphs.

Are you saying there's no way to set the range and domain of your data? It's all auto-calculated from the data given?  

That is sad :(  I think I might be forced to use chartist then as it can set more complex values: https://gionkunz.github.io/chartist-js/api-documentation.html

**Comment by xile611** [comment]
Yeah, the range and domain of RadialBarChart is auto-calculated now. But other charts like LineChart, ScatterChart, RadarChart can set the range and domain.

Thank you for your advice, chartist is a great library.

**Comment by jasonslyvia** [comment]
@RichardJECooke http://lmgtfy.com/?q=what+is+uv+and+pv

**Comment by kvz** [comment]
I found a different workaround for setting a domain onto a RadialBar in this ticket https://github.com/recharts/recharts/issues/1100. Worked for me by just adding the max (`1000` in my case):

```jsx
<PolarAngleAxis
            type="number"
            domain={[0, 1000]}
            dataKey={'value'}
            angleAxisId={0}
            tick={false}
          />
```

Alongside a bar of:

```jsx
<RadialBar
            angleAxisId={0} 
            minAngle={15}
            label={{ fill: '#666', position: 'inside' }}
            background
            clockWise={true}
            dataKey='value'
          />
```

**Comment by vincentreynaud** [comment]
@kvz That sounded great but now it's not possible to use the `domain` prop on `<PolarAngleAxis />` (using recharts 1.8.3). I haven't found something that would replace that.
Maybe unrelated but I can't use the `minAngle` prop on `<RadialBar />` either with this version, the docs online need an update.
