### ISSUE TITLE
Manually Trigger Click Event From Scatter Chart

### ISSUE THREAD

**Issue by daniellehoo** [recharts/recharts#1712]
## Do you want to request a feature or report a bug?
Request feature/functionality

## What is the current behavior?
No built in functionality

## What is the expected behavior?
The ability to trigger an on hover from a corresponding element with the same data point id from outside of the scatter chart component

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
n/a

**Comment by daniellehoo** [comment]
Figured out how to do it:

Create a ref on <ScatterChart/> and another one on <Scatter />

Then update state from another component by setting and calling a global function
for <ScatterChart /> by calling the ref as follows:

  const chart = this.scatterChart.current;
  chart.setState({ [ set state here ] })

**Comment by dsldsl** [comment]
Could you elaborate on this @daniellehoo if you still have context for it?
