### ISSUE TITLE
draw "active dot" last so it isn't bisected by cursor

### ISSUE THREAD

**Issue by deborah-ufw** [recharts/recharts#1716]
Current behavior:  Active dot is drawn before cursor.  Cursor sits on top of Active dot, bisecting it.

Desired behavior:  Active dot is drawn last, so it sits on top of everything else and is never bisected.

**Comment by deborah-ufw** [comment]
Bisected dot (shudder) !

![image](https://user-images.githubusercontent.com/378599/56690457-56db9400-6692-11e9-9bfa-68f98623437d.png)

**Comment by xile611** [comment]
@deborah-ufw The order of cursor is decided by the position of `<Tooltip />`. So just change the position of `<Tooltip /> and <Area />`

```jsx
<LineChart
        width={500}
        height={300}
        data={data}
        margin={{
          top: 5, right: 30, left: 20, bottom: 5,
        }}
      >
        <CartesianGrid strokeDasharray="3 3" />
        <XAxis dataKey="name" />
        <YAxis />
        <Tooltip />
        <Legend />
        <Line type="monotone" dataKey="pv" stroke="#8884d8" activeDot={{ r: 8 }} />
        <Line type="monotone" dataKey="uv" stroke="#82ca9d" />
      </LineChart>
```

**Comment by Rafael-Ramblas** [comment]
It is possible to draw the cursor between the area and the dot to achieve the following result?
![image](https://user-images.githubusercontent.com/19700568/107890396-aa6a4200-6ef7-11eb-8e6a-491b9ffbff97.png)
