### ISSUE TITLE
Feature: custom range

### ISSUE THREAD

**Issue by stereobooster** [recharts/recharts#1718]
## Do you want to request a feature or report a bug?

I guess this is the feature. I want to draw N (some number) BarCharts. Like this

<img width="406" alt="Screenshot 2019-04-26 at 13 58 12" src="https://user-images.githubusercontent.com/179534/56806137-5b878000-682b-11e9-8dac-60ee3e034ce4.png">

They all suppose to have the same scale. Where is they all have the same height, they can have different range, but range is calculated from the given data. Is there a way to provide range outside instead of automatically calculated from the data?

**Comment by xile611** [comment]
@stereobooster You can set the [same domain of YAxis](http://recharts.org/en-US/api/YAxis#domain) for each chart

**Comment by stereobooster** [comment]
But I don't want to draw the `<YAxis />`. `<YAxis />` would be drawn once per all charts in the row

**Comment by mariano-aguero** [comment]
> But I don't want to draw the `<YAxis />`. `<YAxis />` would be drawn once per all charts in the row

You can set the props hide to true.
`<YAxis hide={true} />`
