### ISSUE TITLE
Seperating Recharts component in its own deticated custom component file

### ISSUE THREAD

**Issue by HelloTomatoPerson** [recharts/recharts#1720]
I wish to create a bar chart, but have each Recharts component be in its own dedicated custom component like this:

X axis in XAxis.js
Y axis in YAxis.js
Tool tip in ToolTip.js
Cartesian grid in CartesianGrid.js
Cell in Cell.js
Bar in Bar.js
etc...

And then have one component that brings it all together. 
The reason for this is I sending a lot of props in with a ton of customization and i wish to separate everything to make it cleaner and readable

I tried putting a tool tip and Cartesian grid in its own separate file, but it ends up not rendering anything even though i basically copied it over and it worked before i moved it

So is this possible? And how would i go about this?

Heres an example i did on jsfiddle

```
const {BarChart, Bar, XAxis, YAxis, CartesianGrid} = Recharts;
const data = [
      {name: 'Page A', uv: 4000, pv: 2400, amt: 2400},
      {name: 'Page B', uv: 3000, pv: 1398, amt: 2210},
      {name: 'Page C', uv: 2000, pv: 9800, amt: 2290},
      {name: 'Page D', uv: 2780, pv: 3908, amt: 2000},
];

const customCartesianGrid = React.createClass({
	render () {
  	return (
    	<CartesianGrid strokeDasharray="3 3" />
    );
  }
})

const StackedBarChart = React.createClass({
	render () {
  	return (
    	<BarChart width={600} height={300} data={data}
            margin={{top: 20, right: 30, left: 20, bottom: 5}}>
       <customCartesianGrid/>
       <XAxis dataKey="name"/>
       <YAxis/>
       <Bar dataKey="pv" fill="#8884d8" />
      </BarChart>
    );
  }
})

ReactDOM.render(
  <StackedBarChart />,
  document.getElementById('container')
);
```

![image](https://user-images.githubusercontent.com/46103427/57176064-27eabe00-6e08-11e9-8ab3-fa7944277887.png)

**Comment by xile611** [comment]
@HelloTomatoPerson It's not supported.

**Comment by gaurav5430** [comment]
There are some workarounds as mentioned here: 

https://github.com/recharts/recharts/issues/1470
https://github.com/recharts/recharts/issues/412
