### ISSUE TITLE
Long strings in labels generate overlap in YAxis for horizontal barchart

### ISSUE THREAD

**Issue by cjoecker** [recharts/recharts#1722]
How can I change dynamically the height of my ResponsiveContainer in Recharts if the labels in the YAxis are too long?

This is my code:
         
```
<ResponsiveContainer height={items.length * 50 + 10} width="100%">
                <BarChart
                    data={items}
                    margin={{top: 0, right: 40, left: 40, bottom: 20}}
                    layout="vertical"
                    barCategoryGap="20%"
                    barGap={2}
                    maxBarSize={10}
                >
                    <CartesianGrid
                        horizontal={false}
                        stroke='#a0a0a0'
                        strokeWidth={0.5}
                    />
                    <XAxis
                        type="number"
                        axisLine={false}
                        stroke='#a0a0a0'
                        domain={[0, 10]}
                        ticks={[0, 2.5, 5, 7.5, 10]}
                        strokeWidth={0.5}
                    />
                    <YAxis
                        type="category"
                        dataKey={this.props.YKey}
                        width={40}
                    />
                    <Bar
                        dataKey="score"
                        animationDuration={1000}
                        label={{position: 'right', backgroundColor: '#fff'}}
                        shape={<Rectangle
                            className={classes.rectangle}
                            radius={[0, 10, 10, 0]}
                        />}

                    >
                    </Bar>
                </BarChart>
            </ResponsiveContainer>

```
This is how it looks like:
![vBQwc](https://user-images.githubusercontent.com/46030630/57065700-8f025880-6cca-11e9-8fe4-04c7457226d8.png)

I can calculate the height somehow with the length of the strings in the labels but I want to know if there is an "automatic" way of adapting the height of the responsive container if the labels in the YAxis are too long.

**Comment by cjoecker** [comment]
[Here ](https://codesandbox.io/embed/ql20lrrkm6)is a codesandbox with some example data. The diagram should work with itemsEg1, itemsEg2 and itemsEg3.

**Comment by FengHuangDong** [comment]
has any solution?

**Comment by cjoecker** [comment]
I made the axis height dependent of the label's length. Is not perfect but is the only solution I found...

**Comment by Burdis28** [comment]
@cjoecker can you provide how you did it?

**Comment by cjoecker** [comment]
`
            const labelsMaxNumChars = 18;
            const maxNumOffset = 35;

            let longestWord = Math.max(...items.map(movie => movie.name.length));

            const labelsOffset = parseInt(longestWord / labelsMaxNumChars) * maxNumOffset;
`
