### ISSUE TITLE
Conditional line rendering messing up data values.

### ISSUE THREAD

**Issue by saulojoab** [recharts/recharts#1723]
Hello. I'm displaying the lines on my LineChart depending on which of these checkboxes are selected. Ex: if "Sensor A" is selected, it'll render the black line.
![image](https://user-images.githubusercontent.com/37988252/57212016-c0c03b80-6fb8-11e9-8b2c-95502c61ea25.png)

But every time I click on one of these checkboxes, I get this weird behavior where it seems like my data values get all messed up until I get new values from my server, which makes it go back to normal.

![](https://i.imgur.com/XMLcFF0.gif)

As you can see, whenever I click one of the checkboxes, the values get all weird then snap back to normal when I get the data from my server.

Here's my code:
```js
<ResponsiveContainer width="95%" height={400}>
    <LineChart
    data={this.state.data[0].reverse()}
    margin={{
    top: 5, right: 5, left: 5, bottom: 5,
    }}
    >
    <CartesianGrid strokeDasharray="3 3" />
    <XAxis dataKey="data" />
    <YAxis />
    <Tooltip />
    <Legend />
    {this.state.a ? <Line type="monotone" isAnimationActive={false} dataKey="a" stroke="#252526" activeDot={{ r: 8 }} /> : ''}
    {this.state.b ? <Line type="monotone" isAnimationActive={false} dataKey="b" stroke="#82ca9d" /> : ''}
    {this.state.c ? <Line type="monotone" isAnimationActive={false} dataKey="c" stroke="#8884d8" /> : ''}                    
     </LineChart> 
</ResponsiveContainer>
```

I'm using `recharts 1.5.0` in a Opera Browser.

**Comment by xile611** [comment]
@saulojoab Can you create an online demo to reproduce your problem?

**Comment by saulojoab** [comment]
@xile611 I'll do that in a while. I'll send you when it's done.

**Comment by saulojoab** [comment]
@xile611 I can't send an example with the values I'm using because those are private. Maybe you can take something out of this: https://codesandbox.io/embed/a-simple-react-router-v4tutorial-hs8lo

**Comment by saulojoab** [comment]
Try enabling sensor A and B, then disabling sensor A.

**Comment by xile611** [comment]
enabing A

![image](https://user-images.githubusercontent.com/6111424/57835574-6497bb80-77f1-11e9-8ffa-b7c3511cf8e3.png)


enabing sensor A and B

![image](https://user-images.githubusercontent.com/6111424/57835479-27cbc480-77f1-11e9-8c4c-c71d381caa8b.png)

enabing sensor B
![image](https://user-images.githubusercontent.com/6111424/57835534-4b8f0a80-77f1-11e9-9e8d-0c99ff1bb48d.png)

@saulojoab Everything is OK, I can't get your problem.

**Comment by burgua** [comment]
@saulojoab have you tried to set dataDomain?

```
<XAxis domain={[0, 10000]}  dataKey="data" />
<YAxis domain={[0, 9000]} />
```

I think, wod "messing" is kind of not exact here. If you remove/add some lines it changes also min/max values for XAxis and YAxis.

**Comment by saulojoab** [comment]
@burgua I wish I could send you the actual code I'm using so you would see by yourself. 

I'll try to set the dataDomain. If the problem still persists, I'll create a better demo and send it here.
