### ISSUE TITLE
Cartesian Grid lines are drawn on top of axes

### ISSUE THREAD

**Issue by danatemple** [recharts/recharts#1724]
This is a bug, I believe that the cartesian grid lines should not be drawn on top of the actual axes (e.g. vertical gridline at x = 0 appears on top of the Y axis).

This is visible when the axes have a different color to the grid lines. Please see an example here:

https://jsfiddle.net/needlethread/e5hk4r7x/

I would expect the grid to only draw lines that were within the main chart area.

This is found in the latest version (I just edited the simple linechart example above to demo).

**Comment by xile611** [comment]
@danatemple Just change the order of `<CartesianGrid />` and `<XAxis />` 、`<YAxis />` to upate the render order of these component.

```jsx
<LineChart width={600} height={300} data={data}
            margin={{top: 5, right: 30, left: 20, bottom: 5}}>
       <CartesianGrid />
       <XAxis dataKey="name" stroke="#000060" strokeWidth="5px"/>
       <YAxis stroke="#000060" strokeWidth="5px"/>
       
       <Tooltip/>
       <Legend />
       <Line type="monotone" dataKey="pv" stroke="#8884d8" activeDot={{r: 8}}/>
       <Line type="monotone" dataKey="uv" stroke="#82ca9d" />
      </LineChart>
```

**Comment by p0k8h** [comment]
Awesome
