### ISSUE TITLE
TreeChart with a legend?

### ISSUE THREAD

**Issue by aidanlister** [recharts/recharts#1725]
Feature request: Is it possible to have a legend with the TreeChart?

**Comment by xile611** [comment]
@aidanlister TreeMap ?

**Comment by shubhgol** [comment]
@xile611   Legend is not working in case of Treemap chart . how to resolve that problem?

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
