### ISSUE TITLE
Can I create a radar with just the dots with no lines connecting and no fill?

### ISSUE THREAD

**Issue by Jasonspd** [recharts/recharts#1726]
I'm looking to build something similar to this:
https://radar.thoughtworks.com/?sheetId=https://docs.google.com/spreadsheets/d/1YXkrgV7Y6zShiPeyw4Y5_19QOfu5I6CyH5sGnbkEyiI

I can remove the fill and the stroke, however the stroke colour is tied to both the dot and the lines joining them:

`<Radar name="" dataKey="A" stroke="" fill="" fillOpacity={0} dot={true} />`

**Comment by xile611** [comment]
@Jasonspd You can check [this demo](https://jsfiddle.net/6fj7kthw/)

```jsx
<Radar name="Mike" dataKey="A" stroke="none" fill="none" fillOpacity={0.6} dot={{ fill: 'red', r: 5 }}/>
```

[the docs of Radar#dot](http://recharts.org/en-US/api/Radar#dot)
you can also use function component to render customized `dot` of `<Radar />`.
