### ISSUE TITLE
how to clean axis datakey when data has same key value?

### ISSUE THREAD

**Issue by JungHeum-Park** [recharts/recharts#1727]
when I use data like
`[
    {
       key: 1,
       value: somevalue
    },
    {  
       key: 1,
       value: anotherValue
    }
    {
       key: 1,
       value: asomevalue
    },
    {  
       key: 2,
       value: aanotherValue
    }
.
.
.
.
`
this

When I try 
`<XAxis dataKey="key />`
the graph's XAxis looks like 
![캡처](https://user-images.githubusercontent.com/47998293/57460197-a1bef380-72af-11e9-9545-57ad493fcd70.PNG)

this.

I want make XAxis like
![ddd](https://user-images.githubusercontent.com/47998293/57460233-aedbe280-72af-11e9-9176-f91aea2936d3.PNG)
this.

I read docs, but I can't find the way

**Comment by xile611** [comment]
@JungHeum-Park Maybe you can use customized `tick` of <XAxis /> to reach your demand.
[the docs](http://recharts.org/en-US/api/XAxis#tick)
