### ISSUE TITLE
ReferenceDot component does not recognize decimal values

### ISSUE THREAD

**Issue by stinoga** [recharts/recharts#1729]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
`ReferenceDot` component does not recognize decimal values.

## If the current behavior is a bug, please provide the steps to reproduce
To reproduce, add a `ReferenceDot` to an `AreaChart` or `ComposedChart`, and set a coordinate to a decimal value.

In this fiddle, the `x` prop on `ReferenceDot` is a decimal value. The dot doesn't show up. If you change it to an integer, the dot shows correctly.
https://jsfiddle.net/stinogle/h60gvy8r/15/

## What is the expected behavior?
`ReferenceDot` should show with decimal values.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Latest Recharts.

**Comment by xile611** [comment]
@stinoga  Because the default `type` of `XAxis` is `category`, the domain of x-axis scale is `[1, 2, 3, 4, 5, 6, 7]`, `3.5` is not one of them,  So we can't calculate the coordinate of `3.5`.

Maybe you can change the `type` ot `XAxis` to `category`.

https://jsfiddle.net/stinogle/h60gvy8r/15/
