### ISSUE TITLE
layout="vertical" breaks bar chart

### ISSUE THREAD

**Issue by RichardJECooke** [recharts/recharts#173]
To reproduce:
1) Edit the fiddle for http://recharts.org/examples#StackedBarChart
2) Add `layout="vertical"` attribute to the `BarChart` element
3) Run

It breaks - `TypeError: g[t] is undefined`

**Comment by xile611** [comment]
@RichardJECooke  
The type of XAxis in a vertical BarChart should be `category`, and the type of YAxis should be `number`.
So the code should be tweaked like the following:

```jsx
<BarChart layout="vertical" width={600} height={300} data={data}
            margin={{top: 20, right: 30, left: 20, bottom: 5}}>
  <XAxis type="number"/>
  <YAxis dataKey="name" type="category"/>
  <CartesianGrid strokeDasharray="3 3"/>
  <Tooltip/>
  <Legend />
  <Bar dataKey="pv" stackId="a" fill="#8884d8" />
  <Bar dataKey="uv" stackId="a" fill="#82ca9d" />
 </BarChart>
```

When you code in local development environment, error logs will be printed in the console.

**Comment by RichardJECooke** [comment]
On my localhost I just get 'coordinate not defined'. 

One would think that changing `horizontal` to `vertical` would simply put the charts on their side, without further intervention from the user.

I'm not sure why you have to change the datatypes of the axes but it isn't explained in the documentation. It would be awesome to have a note explaining how `layout` works in there somewhere. And at least one example of a chart with horizontal bars.

**Comment by xile611** [comment]
@RichardJECooke Documentation is weak now. I'll add the detail explanation in the documentation. Here are some examples for vertical chart:

[Vertical LineChart](http://recharts.org/examples#VerticalLineChart)
[Vertical ComposedChart](http://recharts.org/examples#VerticalComposedChart)
[Vertical LineChart which specify the domain of numerical axis](http://recharts.org/examples#VerticalLineChartWithSpecifiedDomain)
