### ISSUE TITLE
Pie chart not coloring all slice colors as expected

### ISSUE THREAD

**Issue by douglasrcjames** [recharts/recharts#1730]
Pie chart is not using all 6 colors from my COLORS variable, and instead uses the fill color (#8884d8) for those extra two. 

Following this example and editing it a bit, I get the expect behavior: https://jsfiddle.net/5xbm0gsw/9/

But mine won't work. Any idea why that might be?

```
const data2 = [
      {name: 'Property Tax', value: 34}, 
      {name: 'Income Tax', value: 30},
      {name: 'Intergov. Aid', value: 17}, 
      {name: 'Energy Tax', value: 4},
      {name: 'Fees and Fines', value: 4},
      {name: 'Other', value: 11}
    ];
const COLORS = ['#0088FE', '#00C49F', '#FFBB28', '#FF2F30', '#FFFFFF', '#8884d8'];

const RADIAN = Math.PI / 180;                    
const renderCustomizedLabel = ({ cx, cy, midAngle, innerRadius, outerRadius, percent, value, name, index }) => {
 	const radius = innerRadius + (outerRadius - innerRadius) * 1.1;
  const x  = cx + radius * Math.cos(-midAngle * RADIAN);
  const y = cy  + radius * Math.sin(-midAngle * RADIAN);
 
  return (
    <text
      x={x}
      y={y}
      fill="black"
      style={{ fontSize: 10 }} 
      textAnchor={x > cx ? "start" : "end"}
      dominantBaseline="central"
    >
      {`${name}: ${(percent * 100).toFixed(0)}%`}
    </text>
  );

};

<ResponsiveContainer width="100%" height={250}>
          <PieChart height={250}>
            <Pie
              data={data2} 
              cx="50%"
              cy="50%"
              dataKey="value"
              labelLine={false}
              label={renderCustomizedLabel}
              outerRadius={80}
              fill="#8884d8"
              >
              {
                data1.map((entry, index) => <Cell fill={COLORS[index % COLORS.length]}/>)
              }
            </Pie>
          </PieChart>
</ResponsiveContainer>
````

**Comment by antoninklopp** [comment]
Hi @douglasrcjames , 

If I am understanding your problem right (which means the jsfiddle link is working and your code is not working), I think that you are just trying to map data1 instead of data2 in your pie on the following line :

`data1.map((entry, index) => <Cell fill={COLORS[index % COLORS.length]}/>)`

When I change the variable from data1 to data2, I get the same color behavior as your fiddle code.

**Comment by douglasrcjames** [comment]
@antoninklopp my apologizes, I found my error. I was referencing data1 in my second data set instead of data2 when mapping the colors. So it was only mapping 4 colors and showing the pie chart fill (background) color, instead of mapping 6 colors because it only saw 4 values in data set instead of 6 values.
