### ISSUE TITLE
Why is tooltip series order the opposite of legend order by default?

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#1731]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
Legend order appears in the other the data series (i.e. a list of Lines) was declared (which is good), but the same items appear in the opposite order in the tooltip by default.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
ReCharts examples (like Simple Line Chart) shows this behavior.

## What is the expected behavior?
I realize that there is no "always right" answer (thus the sortItems function on the tooltip), but I would think that the default behavior would be to show both legend and tooltip data series in the order they were declared.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Latest/All (not sure how long it's been this way, but it didn't always work like this)

**Comment by DavidSvetlik** [comment]
@xile611 Hi, was this fixed or what? I have the same issue.

**Comment by Eric24** [comment]
Yes, this was fixed in 1.6.2
