### ISSUE TITLE
How to create a multi-tier x-axis?

### ISSUE THREAD

**Issue by JemRF** [recharts/recharts#1732]
Is there a way to create a multi-tier x-axis, for example Year/Month where you have a major tick for Year and a minor tick for Month? Both major a minor ticks are labelled. I've attached an example I did in Excel to illustrate what I mean. 

Apologies if this is documented somewhere but I have not been able to find it on the website or through google so it might benefit others. 

![image](https://user-images.githubusercontent.com/39573756/57638939-d2877d00-757c-11e9-9769-11b80778dfa7.png)

**Comment by bill-feng** [comment]
Hey there.
I believe you can simply add multiple `<XAxis />` components in your chart withe different options passed in to style the ticks.

Here's an example from the repo that has multiple `<YAxis />` components:

```
const data = [
  { name: 'Page A', uv: 1000, pv: 2400, amt: 2400, uvError: [75, 20] },
  { name: 'Page B', uv: 300, pv: 4567, amt: 2400, uvError: [90, 40] },
  { name: 'Page C', uv: 280, pv: 1398, amt: 2400, uvError: 40 },
  { name: 'Page D', uv: 200, pv: 9800, amt: 2400, uvError: 20 },
  { name: 'Page E', uv: 278, pv: null, amt: 2400, uvError: 28 },
  { name: 'Page F', uv: 189, pv: 4800, amt: 2400, uvError: [90, 20] },
  { name: 'Page G', uv: 189, pv: 4800, amt: 2400, uvError: [28, 40] },
  { name: 'Page H', uv: 189, pv: 4800, amt: 2400, uvError: 28 },
  { name: 'Page I', uv: 189, pv: 4800, amt: 2400, uvError: 28 },
  { name: 'Page J', uv: 189, pv: 4800, amt: 2400, uvError: [15, 60] },
];
```

```
<LineChart width={600} height={400} data={data}>
  <YAxis type='number' yAxisId={0} domain={[0, 1020]}/>
  <YAxis type='number' orientation='right' yAxisId={1}/>
  <YAxis type='number' orientation='right' yAxisId={2}/>
  <XAxis dataKey='name'/>
  <Tooltip position={{y: 200}} />
  <CartesianGrid stroke='#f5f5f5'/>
  <Line dataKey='uv' stroke='#ff7300' strokeWidth={2} yAxisId={0}/>
  <Line dataKey='pv' stroke='#387908' strokeWidth={2} yAxisId={1}/>
  <Line dataKey='amt' stroke='#38abc8' strokeWidth={2} yAxisId={2}/>
</LineChart>
```

You can try rendering this and modify it to your needs.

**Comment by JemRF** [comment]
That worked partially, thanks! I had tried multiple XAxis statement but I did not give them unique xAxisId (xAxisId={0} and xAxisId={1}). I set interval={10} on the Year so it only prints one year per year. However I have not figured out how to display a major tick line on change of year and position the year midway through the year (refer excel chart). Here is the code I have so far:

        <XAxis tickLine={true} xAxisId={0} dy={0} dx={-0} label={{ value: '', angle: 0, position: 'bottom' }} interval={0} dataKey="Month" tickLine={false} tick={{fontSize: 9, angle: 0 }} />
            <XAxis xAxisId={1} dy={-15} dx={0} label={{ value: '', angle: 0, position: 'bottom' }} interval={10} dataKey="Year" tickLine={false} tick={{fontSize: 9, angle: 0}} />
    
![recharts multi tier x-axis](https://user-images.githubusercontent.com/39573756/57744398-1078c400-7697-11e9-8478-b71ac67f2b07.png)

**Comment by xile611** [comment]
@JemRF you can check [this demo](http://recharts.org/en-US/examples/BarChartWithMultiXAxis)

**Comment by ahmadjoya** [comment]
I have the same problem. did u find how can we do?

**Comment by ahmadjoya** [comment]
@JemRF  I have the same problem. did u find how can we do?

**Comment by simcha90** [comment]
I think we example of it in our repo:
https://5fec4c81935a8c002151e85f-ompoasodjs.chromatic.com/?path=/story/plugins-composed-chart-playground--time-series
https://github.com/nielsen-oss/superset-viz-plugins

**Comment by ledfordtj** [comment]
@simcha90 Hello, this is a great example for what I need to do. But I am having a hard time decoupling the logic that you are using to create the x-axis in the time series chart. Do you have a similar example that isnt as involved?
