### ISSUE TITLE
ReferenceLine viewBox prop gets overwritten

### ISSUE THREAD

**Issue by bill-feng** [recharts/recharts#1733]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
According to the documentation, `<ReferenceLine />` should be able to take a prop called `viewBox`. However, it seems to be overwritten if the component is used in an `<AreaChart />` component (potentially other places too, but this is the situation I ran into).

## JS Fiddle
[https://jsfiddle.net/eov7pbyL/8/](https://jsfiddle.net/eov7pbyL/8/)

## What is the expected behavior?
The display of the Reference Line can be affected by setting the viewBox prop.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Version 1.5.0 tested on Chrome.

**Comment by xile611** [comment]
@bill-feng The `viewBox` is calculated inernally.
![image](https://user-images.githubusercontent.com/6111424/57745219-de02b180-76fe-11e9-8dca-cead0e7c009f.png)

**Comment by bill-feng** [comment]
@xile611 Thanks for the reply! :)

Since the documentation says "_usually_ calculated internally", do you happen to know what are the circumstances in which it is not calculated internally?

I'm trying to draw a reference line that does not go through the entire graph, and the `viewBox` prop seemed like it would be helpful. Looking at the source code though, it seems like it gets overwritten if it is put inside a chart element:

Inside `generateCategoricalChart.js`:
![Screen Shot 2019-05-15 at 2 06 48 PM](https://user-images.githubusercontent.com/7489794/57752197-d94bf680-771a-11e9-94bb-465ef2cd639c.png)

Would it be possible to make it such that the `viewBox` received through props has higher priority than the `offset` from the component state, or would that cause other problems?

**Comment by ArmandoGraterol** [comment]
@bill-feng Hello, were you able to solve this? I'm also trying to make the ReferenceLine not take all of the height in the chart

**Comment by bill-feng** [comment]
@ArmandoGraterol hey man, I couldn't do it with `ReferenceLine` but I did find a work around. You can use `ComposedChart` and fake a reference line that does not take all of the height by adding a bar graph with the right values.

- You can control the position of the fake line by adjusting the x or y axis values.
- You can change the bar width to 1px so it looks like a line.

You can make it - for all intents and purposes - behave like a reference line, but you'll have to do a bunch of number crunching to make it look how you want. It's definitely a bit hacky.

**Comment by mesrbn** [comment]
You can achieve this by referenceArea where you can define both x and y. It's completely customizable.
