### ISSUE TITLE
Min Max value

### ISSUE THREAD

**Issue by kenzo23312** [recharts/recharts#1734]
Hi,

Is it possible to achieve min and max line on bar chart depending on value of bar ?
Green line when it's ok or above, red line when it's below.

Attached screen:

<img width="441" alt="Screen Shot 2019-05-14 at 1 25 59 PM" src="https://user-images.githubusercontent.com/19548207/57696158-6c6c2a00-7650-11e9-9e1d-eb1f3d8852c2.png">

**Comment by kenzo23312** [comment]
I managed to achieve this with Scatter, but I can't get line shape is it possible to override shape / how?

<img width="366" alt="Screen Shot 2019-05-14 at 2 17 34 PM" src="https://user-images.githubusercontent.com/19548207/57697231-0b922100-7653-11e9-9a24-8a1384f72f9f.png">

**Comment by kenzo23312** [comment]
Please close this issue.

**Comment by xile611** [comment]
@kenzo23312  Please `shape` props of `<Scatter />` to render customized shape. [the docs](http://recharts.org/en-US/api/Scatter#shape)
