### ISSUE TITLE
Potential breaking change in v1.6

### ISSUE THREAD

**Issue by taylordowns2000** [recharts/recharts#1737]
Think this may be a bug in the new release (it appeared after i upgraded from 1.5 to 1.6 and I fixed it by downgrading from 1.6 to 1.5) and won't have time to properly document until later today. Apologies. I'll come back and edit the card with better data for reproducing shortly.

When an area chart is loaded and there is no data point above 0 on a line, I get an uncaught error:
```js
<AreaChart
  data={job ? job.stats : []}
  margin={{
  top: 20, right: 30, bottom: 0, left: -10,
  }}
>
  <Area type="monotone" stackId="1" dataKey="failure" stroke={theme.palette.error.main} fill={theme.palette.error.main} dot={false} strokeWidth={2} />
```
Where job.stats is an array built like this:
```ex
defp job_stats(job_id) do
    RunQuery.stats_for_job(job_id)
    |> Repo.all
    |> Enum.map(fn(result) ->
      %{
        "date" => Date.to_iso8601(elem(result, 0)),
        "success" => elem(result, 1),
        "failure" => elem(result, 2),
        "crashed" => elem(result, 3)
      }
    end)
  end
```
We always have 30 `date`s, but if success = 0 for all 30, it throws this error:
```
TypeError: Cannot read property '0' of undefined
    at Area.js:359
    at Array.map (<anonymous>)
    at Area.js:356
    at c.e (Animate.js:319)
```
![image](https://user-images.githubusercontent.com/8732845/57772684-fc23de00-770d-11e9-8c14-09c3bece0e93.png)

**Comment by xile611** [comment]
@taylordowns2000 Can you create an online demo to reproduce this problem? I can't reproduce this problem.

**Comment by davidalekna** [comment]
1.6 also broke our app. We get following error

![Screenshot 2019-05-16 at 11 12 12](https://user-images.githubusercontent.com/17140381/57846174-88480b00-77cb-11e9-8a0c-8edb337b0af3.png)

**Comment by imjustd** [comment]
@davidalekna Your error is more related to this issue https://github.com/recharts/recharts/issues/1738
