### ISSUE TITLE
Allow for 2 YAxis

### ISSUE THREAD

**Issue by marchaos** [recharts/recharts#174]
Would it be possible to allow for 1 left YAxis and a right YAxis? I want to do something like 

```xml
<ComposedChart data={data} margin={{top: 20, right: 0, bottom: 0, left: 0}}>
    <XAxis dataKey="name" tickLine={false} axisLine={false} />
    <YAxis tickCount={10} tickLine={false} axisLine={false} minTickGap={600} />
    <YAxis orientation='right' tickCount={10} tickLine={false} axisLine={false} minTickGap={600} />
    <Tooltip formatter={this.props.drawTooltip} wrapperStyle={{display: 'none'}} />
    <Legend />
    <CartesianGrid stroke='#f5f5f5' vertical={false} />
    <Bar dataKey='pv' barSize={40} fill='#F7B7B4'/>
    <Line type='linear' dataKey='uv' stroke='#41527D' strokeWidth={3} />
    <Line type='linear' dataKey='amt' stroke='#F70D1C' strokeWidth={3} />
</ComposedChart>
```

Where the YAxis on the right represents a different scale (related to one of the line charts).

**Comment by xile611** [comment]
@marchaos [Here](http://recharts.org/examples#BiaxialLineChart) is a demo of LineChart which has two y-axes. 

```jsx
<ComposedChart data={data} margin={{top: 20, right: 0, bottom: 0, left: 0}}> 
  <XAxis dataKey="name" tickLine={false} axisLine={false} /> 
  <YAxis yAxisId="left" tickCount={10} tickLine={false} axisLine={false} minTickGap={600} /> 
  <YAxis yAxisId="right" orientation='right' tickCount={10} tickLine={false} axisLine={false} minTickGap={600}/>
  <Tooltip formatter={this.props.drawTooltip} wrapperStyle={{display: 'none'}} /> 
  <Legend /> 
  <CartesianGrid stroke='#f5f5f5' vertical={false} /> 
  <Bar yAxisId="left" dataKey='pv' barSize={40} fill='#F7B7B4'/> 
  <Line yAxisId="left" type='linear' dataKey='uv' stroke='#41527D' strokeWidth={3} /> 
  <Line yAxisId="right" type='linear' dataKey='amt' stroke='#F70D1C' strokeWidth={3} /> 
</ComposedChart>
```
 You just need to specify the `yAxisId` of two y-axes, and graphical Component, like `Line`, `Area`, `Bar`.

**Comment by marchaos** [comment]
ah ha! thanks.

**Comment by marchaos** [comment]
For anyone else working example with a composed chart. http://jsfiddle.net/w7qdap9f/

**Comment by marchaos** [comment]
Is there a way to get both axis (and the data) to align their 0 to the center?

**Comment by xile611** [comment]
@marchaos A workaround is setting the `domain` and `ticks` of two y-axes like [this demo](http://jsfiddle.net/w7qdap9f/1/). But it may be very complex to calculate the domain and ticks.
How about the data you want to display?

**Comment by marchaos** [comment]
My 2 domains are {-4, 4} and {-1, 1}.

**Comment by xile611** [comment]
@marchaos  If the domains are fixed, you can specify the domain and ticks of YAxis like the following:

```
<YAxis yAxisId="left" orientation="left" domain={[-4, 4]} ticks={[-4, -2, 0, 2, 4]} stroke="#8884d8"/>
<YAxis yAxisId="right" orientation="right"  domain={[-1, 1]} ticks={[-1, -0.5, 0, 0.5, 1]} stroke="#82ca9d"/>
```

**Comment by kekeuy** [comment]
I used [yAxisId="right" orientation="right" ],but they throw some errors like 'Uncaught TypeError: Cannot read property 'scale' of undefined'! I don't know how to fixed it......

**Comment by pat310** [comment]
@kekeuy  I'm getting the same error when I use a string for the `yAxisId`:
```
Uncaught TypeError: Cannot read property 'scale' of undefined
    at eval (webpack:///./~/recharts/es6/chart/LineChart.js?:101:86)
```
However, the docs do say that you can also use a number for the `yAxisId` and that seems to work.  Could be a good PR opportunity 😄

**Comment by Ghirro** [comment]
FYI, it seems the axis id's need to be sequential numbers rather than just integers.

**Comment by lancelodliu** [comment]
This feature is broken for now. You can see example here: https://jsfiddle.net/4652aL9c/7/
The line is missing and so is the right Y axis.
