### ISSUE TITLE
Add tooltip position options for a LineChart

### ISSUE THREAD

**Issue by olgaivanysko** [recharts/recharts#1741]
## Do you want to request a feature or report a bug?
Feature

## What is the current behavior?
The coordinates of a tooltip position are calculated internally by default. If they are provided, then we see that the tooltip position is always fixed and remains the same independently of the hovered chart area.

## What is the expected behavior?
Being able to position tooltip to the right/right/top/bottom of the chart, something like
`<Tooltip position="top" />`
![24e31094-e79c-11e6-9f3a-9a0c1c807df0](https://user-images.githubusercontent.com/23654355/58037182-85d01300-7b35-11e9-92e6-e6218d2e1705.png)

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts v1.5.0

**Comment by xile611** [comment]
Sorry, not supported. It's recommended to use customized `content` of `Tooltip` to cover customized style.
