### ISSUE TITLE
Labels with name value as label

### ISSUE THREAD

**Issue by MincePie** [recharts/recharts#1743]
## Do you want to request a feature or report a bug?

Can't figure out how to get labels to render with 'name' value instead of data value

## What is the current behavior?

The label on the chart is displayed as the data value.

## What is the expected behavior?

I want to use the name of the value rather than it's data as the value.

Here is my form:

Currently the label on the pie chart reads as '400' instead of 'Group A'.

```
[import React, { PureComponent } from 'react';
import {
  ResponsiveContainer, PieChart, Pie, Legend, Label, LabelList, Tooltip
} from 'recharts';

const data = [
  { name: 'Group A', value: 400 }, { name: 'Group B', value: 300 },
  { name: 'Group C', value: 300 }, { name: 'Group D', value: 200 },
];

export default class Example extends PureComponent {
  static jsfiddleUrl = '//jsfiddle.net/alidingling/6okmehja/';

  render() {
    return (
      <div style={{ width: '100%', height: 300 }}>
        <ResponsiveContainer>
          <PieChart>
            <Pie dataKey="value" 
            data={data} 
            fill="#536A6D" 
            label nameKey="name"    
            />
          </PieChart>

        </ResponsiveContainer>
      </div>
    );
  }
}
](url)

```

If I use uppercase L for label (ie             label nameKey="name"    ) - then no labels are rendered.

**Comment by MincePie** [comment]
More background to the attempts made at getting this to work is here. There must be a simple solution for this. https://stackoverflow.com/questions/56104004/rechart-adding-labels-to-charts

**Comment by MincePie** [comment]
Thanks @stephenrs.

Your suggestion works.  For anyone else looking for the answer, this works:

Define a function to render you labels the way you want, some like:
```
let renderLabel = function(entry) {
    return entry.name;
}
```
Set the label prop to point to your function:
```
<Pie label={renderLabel} [ you other properties ]>
[ your content ]
</Pie>

```

**Comment by marvinahv** [comment]
Thanks for the solution, @MincePie. You can also use an anonymous function to do it inline:

```javascript
<Pie data={data} [ other properties ] fill="#82ca9d" label={(entry) => entry.name} />
```

**Comment by neeco1991** [comment]
what if i need both value inside the slice and name with labelLine?
