### ISSUE TITLE
Legend component in PieChart renders incorrect value if dataKey prop value is "name".

### ISSUE THREAD

**Issue by kirthegrave** [recharts/recharts#1744]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
Legend component in PieChart renders incorrect value if dataKey prop value is "name".

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
There is two examples https://codesandbox.io/s/1tfsj. First example's legend is incorrect. 

## What is the expected behavior?
Legend will respect dataKey value.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Reproduced in:
Versions: 1.0.0-beta.10 and 1.6.
OS: MacOS 10.14.4 
Browsers: Chrome 74.0.3729.131. Safari 12.1

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
