### ISSUE TITLE
vertical graph svg is way outside the viewport

### ISSUE THREAD

**Issue by dudo** [recharts/recharts#1745]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
1.6.0 Seems to have introduced a viewport issue on the vertical axis for very steep slopes.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
![Screen Shot 2019-05-21 at 10 39 35 AM](https://user-images.githubusercontent.com/2963800/58122538-b60fc400-7bbe-11e9-9d72-0ce1409b504f.png)

## What is the expected behavior?
See picture. Top graph shows issue. Bottom graph is fine. Steep slopes should scale appropriately.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.6.0 and 1.6.1 have the problem. 1.5.0 does not.

**Comment by joshuadoan** [comment]
I can confirm this is related to giving the chart numbers vs strings. Strings were working fine before 6.0, but not after. Looking at the change log this might be related to the switch to lodash.

**Comment by RevoluPowered** [comment]
Any chance someone can look into this as I don't know how to work around it in my app as I display strings with numerical values like £100,000.00 in the graph data

**Comment by freddiehonohan** [comment]
I am getting this error with numbers too FYI, rolling back to 1.5.0 fixed it for me.

**Comment by RevoluPowered** [comment]
Yeah had to do this myself, it fixed it reverting.

I did actually notice that lodash had not changed since I updated the lib so don't think it is to do with lodash.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
