### ISSUE TITLE
onAnimationEnd not exposed / not in the API?

### ISSUE THREAD

**Issue by emer7** [recharts/recharts#1747]
Based on this snippet, it seems that onAnimationEnd is exposed and can be used (I tried it in my own project and it works)
https://github.com/recharts/recharts/blob/deff10242b0761f91871367cdc643e41888264de/src/polar/Pie.js#L277

Is onAnimationEnd intentionally not exposed or the developer missed it? There is also an issue #1540 that is asking for this feature.

**Comment by xile611** [comment]
The docs has been updated.
Meanwhile, PR is welcome.
