### ISSUE TITLE
Issue with line alignment when YAxis prop domain is set to [0,0]

### ISSUE THREAD

**Issue by tgwozdzik** [recharts/recharts#1749]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
From version 1.6.0 the `Line` or `Area`  in `LineChart` or `AreaChart` are centered when passing `domain={[0,0]}` to `YAxis` 

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
![image](https://user-images.githubusercontent.com/9334679/58318542-43018a00-7e18-11e9-9ecc-af3afe2e8642.png)

Code sample: https://codesandbox.io/s/recharts-playground-5phz1

## What is the expected behavior?
Restore the behavior from the version 1.5.0

![image](https://user-images.githubusercontent.com/9334679/58318509-341ad780-7e18-11e9-85e4-7d8638e798ce.png)

Code sample: https://codesandbox.io/s/recharts-playground-6weee

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.6.2, 1.6.1, 1.6.0 seems to have that problem.   
1.5.0 works as expected.

**Comment by tomasztomys** [comment]
+1

**Comment by krynhild** [comment]
+1

**Comment by krynhild** [comment]
Looks like it's caused by https://github.com/d3/d3-scale/issues/117.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
