### ISSUE TITLE
Question regarding custom labels

### ISSUE THREAD

**Issue by patryk0605** [recharts/recharts#175]
Is there an easy way to create custom labels while maintaining the layout in the following example: 

- http://recharts.org/examples/#StraightAnglePieChart

My end goal is to have custom labels and have them outside of the pie chart with lines directing the label to the slice. I have reviewed your example for custom labels (http://recharts.org/examples/#PieChartWithCustomizedLabel) and set **labelLine** to **true**, but can't figure out the math/logic to have the label be outside of the pie, by the line. The following is the function I am referring to, taken from your example: 

``` javascript
const renderCustomizedLabel = ({ cx, cy, midAngle, innerRadius, outerRadius, percent, index }) => {
  const radius = innerRadius + (outerRadius - innerRadius) * 0.5;
  const x  = cx + radius * Math.cos(-midAngle * RADIAN);
  const y = cy  + radius * Math.sin(-midAngle * RADIAN);
 
  return (
    <text x={x} y={y} fill="white" textAnchor={x > cx ? 'start' : 'end'} 	dominantBaseline="central">
    	{`${(percent * 100).toFixed(0)}%`}
    </text>
  );
};
```

A side note: The example for **label** on http://recharts.org/api/#Pie is pointing to a 404.

**Comment by xile611** [comment]
@patryk0605 

Is [this demo](http://jsfiddle.net/sheubr4L/) what you want ?

The example for label is <http://recharts.org/examples/#PieChartWithCustomizedLabel>. I can access to this page in the most times, but not all the times. It's strange.

And your issue is similar to [#160](https://github.com/recharts/recharts/issues/160).  I'll temporarily close this issue. If you have more questions about label of Pie, you can discuss with us.

**Comment by patryk0605** [comment]
Thanks! That demo is exactly what I wanted.

**Comment by brianyang** [comment]
@patryk0605 you can get the labels to appear outside the pie by increasing the radius:
```js
const renderCustomizedLabel = ({ cx, cy, midAngle, innerRadius, outerRadius, percent, index }) => {
  const radius = innerRadius + (outerRadius - innerRadius) * 1.5;
  const x  = cx + radius * Math.cos(-midAngle * RADIAN);
  const y = cy  + radius * Math.sin(-midAngle * RADIAN);

  return (
    <text x={x} y={y} fill="white" textAnchor={x > cx ? 'start' : 'end'}    dominantBaseline="central">
        {`${(percent * 100).toFixed(0)}%`}
    </text>
  );
};
```

**Comment by halfice** [comment]
is there any way to show label vertical in line chart.
