### ISSUE TITLE
recharts linechart change  line color for null vlaues

### ISSUE THREAD

**Issue by EdisonDevadoss** [recharts/recharts#1752]
I have created a line chart. Now I can change line colour if values are negative(-). But I could not able to change if values are null.

```
const gradientOffset = () => {
  const dataMax = Math.max(...data.map(i => i.uv));
  const dataMin = Math.min(...data.map(i => i.uv));
  if (dataMax <= 0) {
    return 0;
  } else if (dataMin >= 0) {
    return 1;
  } else {
    return dataMax / (dataMax - dataMin);
  }
};
```

The above code is applicable for negative value.

```
const off = gradientOffset();
     <defs>
          <linearGradient id="splitColor" x1="0" y1="0" x2="0" y2="1">
            <stop offset={off} stopColor="green"  />
            <stop offset={off} stopColor="red"  />
          </linearGradient>
        </defs>
```
Sample output is:

![Screenshot from 2019-05-28 12-44-42](https://user-images.githubusercontent.com/30063304/58458393-b839cb80-8146-11e9-90d8-eff62ca37a32.png)

How do I change the line chart colour if values are null?

**Comment by antoninklopp** [comment]
But where would you display the point of a null value?

**Comment by xile611** [comment]
It's recommend to use customized gradient to implement this feature.
