### ISSUE TITLE
Whole stacked AreaChart uses stroke of last area

### ISSUE THREAD

**Issue by peteruithoven** [recharts/recharts#1755]
## Do you want to request a feature or report a bug?
Bug 

## What is the current behavior?
When drawing a stacked AreaChart (using `stackOffset="expand"` and multiple area's with the same `stackId`) the stroke color of the last added area is used as a stroke color for the whole chart. 
![Screenshot from 2019-05-30 17-02-29@2x](https://user-images.githubusercontent.com/523210/58642038-be71a880-82fc-11e9-9001-8afd8dd5482d.png)

## Steps to reproduce
Example: https://codesandbox.io/s/recharts-stacked-areagraph-stroke-color-8e7r8
1. Create `AreaChart` with multiple `Area`'s.
2. Add multiple `Area`'s.
3. Give `Area`'s the same `stackId`.
4. Give `Area`'s different stroke colors.

## What is the expected behavior?
I'd expect each area to be stroked with it's own color, just like in a non stacked area graph. 
For example, using the same data with a not stacked graph (removed `stackId`'s):
![Screenshot from 2019-05-30 17-03-32@2x](https://user-images.githubusercontent.com/523210/58642098-e234ee80-82fc-11e9-9d08-f82b1f4387bd.png)

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts: 1.6.2. 
Browsers: All

**Comment by peteruithoven** [comment]
One explanation could be that the last area is layed on top as a thin line?

**Comment by xile611** [comment]
Sorry! It seems hard to implement this feature.
