### ISSUE TITLE
Customizable pies in PieChart

### ISSUE THREAD

**Issue by ArashDKH** [recharts/recharts#1759]
## Do you want to request a feature or report a bug?
feature
## What is the current behavior?
In piecharts the pie's shape is not customizable with custom svg.
In the onHover mode u can customize it but on the static mode it can not be customized

## What is the expected behavior?
There be a props which accepts a function which can render customized svg for each pie

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
