### ISSUE TITLE
How I can set a space between bars

### ISSUE THREAD

**Issue by iamgbayer** [recharts/recharts#1760]
In the image, I've a table and a composed chart above, I would like to align the bar and table column centers, I tried to do it with `barGap`, but without way.

Anyone would have any ideia about how do it?   

![Screen Shot 2019-06-01 at 14 48 17](https://user-images.githubusercontent.com/5483459/58751933-6366bf80-847c-11e9-81b9-48b09736629e.png)

**Comment by ckifer** [comment]
Looks like this is a really old issue and it's unclear what's being looked for here. Could you make a new issue by chance?
