### ISSUE TITLE
Label issue with BarChartStackedBySign

### ISSUE THREAD

**Issue by PlatypusColi** [recharts/recharts#1762]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
The position label in case of a BarChartStackedBySign doesn't take into account the offset produced by stackOffset="sign".
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
https://jsfiddle.net/n04ehy72/
## What is the expected behavior?
I would expect the labels to appear under the negative bars.
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
-

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
