### ISSUE TITLE
How to add arrow in Pie chart hover to an element?

### ISSUE THREAD

**Issue by aaron170** [recharts/recharts#1763]
New Add on.

![chart](https://user-images.githubusercontent.com/19680243/58855470-c6936480-86bd-11e9-9dbc-b13c804fc8f3.jpg)

I am trying to get this arrow in the pie chart. 

![chart-result](https://user-images.githubusercontent.com/19680243/58855592-06f2e280-86be-11e9-997f-c20810ff9a54.jpg)
Till Now I have achieved this. Below is my code.

`const renderActiveShape = (props) => {
    const RADIAN = Math.PI / 180;
    const { cx, cy, midAngle, innerRadius, outerRadius, startAngle, endAngle, fill, payload, percent, value } = props;
    const sin = Math.sin(-RADIAN * midAngle);
    const cos = Math.cos(-RADIAN * midAngle);
    const sx = cx + (outerRadius + 10) * cos;
    const sy = cy + (outerRadius + 10) * sin;
    const mx = cx + (outerRadius + 30) * cos;
    const my = cy + (outerRadius + 30) * sin;
    const ex = mx + (cos >= 0 ? 1 : -1) * 22;
    const ey = my;
    const textAnchor = cos >= 0 ? 'start' : 'end';

    return (
        <g>
            <text className="text-value" x={cx} y={cy - 5} dy={8} textAnchor="middle" fill={fill}>{payload.value}</text>
            <text className="text-name" x={cx} y={cy + 25} dy={5} textAnchor="middle" fill="#A3A3A3">{payload.name}</text>
            <Sector cx={cx} cy={cy} innerRadius={innerRadius} outerRadius={outerRadius} startAngle={startAngle} endAngle={endAngle} fill={fill} />
            <Sector cx={cx} cy={cy} innerRadius={outerRadius - 28} outerRadius={outerRadius - 25} startAngle={startAngle} endAngle={endAngle} fill={fill}>
            </Sector>
        </g>
    );
};

`
<ResponsiveContainer aspect={1} width="99%">
                                        <PieChart>
                                            <Pie activeIndex={this.state.activeIndex} activeShape={renderActiveShape} data={data} startAngle={185} endAngle={-5}
                                                innerRadius="80%" stroke="none" paddingAngle={2} outerRadius="100%" fill="none" dataKey="value" onMouseEnter={this.onPieEnter}>
                                                {
                                                    data.map((entry, index) => <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />)
                                                }
                                            </Pie>
                                        </PieChart>
                                    </ResponsiveContainer>
`

`

Any help would be appriciated.

Thanks

**Comment by antoninklopp** [comment]
Hi, 

Here is what you could do with a custom render function : 
```javascript
const renderActiveShape = (props) => {
  const RADIAN = Math.PI / 180;
  const {
    cx, cy, midAngle, innerRadius, outerRadius, startAngle, endAngle,
    fill, payload,
  } = props;
  const sin = Math.sin(-RADIAN * midAngle);
  const cos = Math.cos(-RADIAN * midAngle);
  const mx = cx + (innerRadius - 18) * cos;
  const my = cy + (innerRadius - 18) * sin;
  const ex = mx + (cos >= 0 ? 1 : -1) * 10;
  const ey = my;
  return (
    <g>
      <text x={cx} y={cy} dy={8} textAnchor="middle" fill={fill}>{payload.name}</text>
      <Sector
        cx={cx}
        cy={cy}
        innerRadius={innerRadius}
        outerRadius={outerRadius}
        startAngle={startAngle}
        endAngle={endAngle}
        fill={fill}
      />
      <g transform={`translate(${ex + (cos >= 0 ? 1 : -1) * 2} ${ey})`}>
        <g transform={`rotate(${-midAngle + 180})`}>
          {/* Draw the triangle with custom shape */}
          <polygon points="5,-5 5,5 -5,0 " style={{fill:'lime', stroke:'purple', strokeWidth:'1' }}/>
        </g>
      </g>
    </g>
  );
};
```

Here is the link to the full gist : https://gist.github.com/antoninklopp/fd629341e0a5e91bb46ed9a4037131fa

Please next time, make a jsfiddle, a simple gist or github repo or even some markdown editing to make your code clearer than just pasting it as text :smile:
