### ISSUE TITLE
How to specify a line-break in an axis tick label?

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#1765]
## Do you want to request a feature or report a bug?
Question or Feature

## What is the current behavior?
There does not appear to be a way to insert a line-break in an axis tick label. I added a tick formatter and tried `\n` and `<br/>`, but neither worked. The objective is to be able to show the date on one line and the time on the next line, both centered on the tick (on a time-based axis, of course).

## What is the expected behavior?
Ability to support `\n` or `<br/>` to insert a line break in an axis tick label.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
All current browser; latest Recharts.

**Comment by alainotjens** [comment]
You could do this with a custom axis tick: https://jsfiddle.net/sovtzeqb/

**Comment by Eric24** [comment]
Very helpful. Thank you.
