### ISSUE TITLE
Synced charts with Brush with startIndex are not in sync

### ISSUE THREAD

**Issue by alain0** [recharts/recharts#1766]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
Synced charts (by using `syncId` prop) are not in sync with `startIndex` of the Brush on initial load. Only after user interaction with the brush do the charts do sync.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/)
I've created a simple example here: https://jsfiddle.net/mcux97nv/

## What is the expected behavior?
All synced charts have the same Brush scope on initial load. If more charts have Brushes, the `startIndex` of the first is leading.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.6.2

**Comment by alainotjens** [comment]
BTW: A hacky solution is to include a hidden Brush with the same `startIndex` to every synced chart. Hiding can for example be done by giving it a `width` of 0 and a `height` of 0.00001 (with a `height` of 0 some space is still reserved within the chart).
Example here: https://jsfiddle.net/32fkjctL/

**Comment by xiaoyu-tamu** [comment]
Encountered same issues. Hope this can be addressed :)

**Comment by xile611** [comment]
@alain0 
When you want to sync two charts, we have a hypothesis that their initial state is synchronized, otherwise we cannot decide what state to use
