### ISSUE TITLE
Animate Arrow in Pie chart like a progress bar.

### ISSUE THREAD

**Issue by aaron170** [recharts/recharts#1768]
## Request a feature
Animate an arrow to the path of the value. E.g.
![meter](https://user-images.githubusercontent.com/19680243/59181172-589ae180-8b84-11e9-8f88-4d1ca74d1b98.jpg)

"You can see the arrow in the above example. It should start from the starting point and stop at the value of the filled path."

## What is the current behavior?
Prepared a fiddle in which I am stuck to this point. [Here it is.](https://jsfiddle.net/aaron170/j8bhw7vm/35/)

## What is the expected behavior?
The arrow should animate to the filled path like a progress bar.

Any help would be appreciated.
Thanks

**Comment by xile611** [comment]
It's recommended to use customized shape to implement this kind of feature.
