### ISSUE TITLE
Some stacks are shown in unexpected position in Stacked Barchart.

### ISSUE THREAD

**Issue by kazup0n** [recharts/recharts#177]
As shown in the attached screenshot, The third stack in a stacked bar chart will be shown in unexpected position.
If a bar chart contains more than three stacks, the position of stacks may be misplaced

![](https://i.gyazo.com/4fdca38e3d69e5d5c7ea8557dd99bfe9.png)

Here's a reproduction code.
http://jsfiddle.net/kauzp0n/m7w8c7uq/

And it is not happened if value is negative.
http://jsfiddle.net/kauzp0n/csqxnk43/1/

**Comment by xile611** [comment]
@kazup0n Thank you. It's the bug of stackOff.

**Comment by xile611** [comment]
Fixed in version 0.13.3.
