### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by osmarpetry** [recharts/recharts#1770]
## Do you want to request a feature or report a bug?
BUG

## What is the current behavior?
Throw a error, I don't know exactly when it happen. I discovered these erros on my Sentry log 

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
Not able to do it, because is hard to happen. But happen some times

## What is the expected behavior?
Not throw this error

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
We work with the latest release of rechats, the 1.6.2

Browser versions:
- Chrome 74 - Linux, Windows 10 and MacOS
- Opera 60 - Windows 10
- Chrome 73 - Linux, Windows 10
- Chrome Mobile - Android
- Chrome 72 - Linux, Windows 10 and MacOS
- Chrome 69 and 70 - Linux
- Samsung Internet 9.2 - Android 8 (Samsung SM-A720F)

**Comment by shawnatxapp** [comment]
It seems that the ResponsiveContainer (which I suspect is at the heart of this issue) has an optional debounce prop that will *hopefully* resolve this.

Going to try it in our app. Will report back if Sentry is quiet after the next deploy.

**Comment by shawnatxapp** [comment]
Sentry reported another instance of the error after adding the debounce, so it seems that this alone is not sufficient to prevent the error.

**Comment by sscholle** [comment]
im still getting the same after upgrading to v1.6.2 which was supposed to address this issue

**Comment by vtereshyn** [comment]
any updates here?

**Comment by xile611** [comment]
Please try to add `debounce`.

**Comment by youngmoon715** [comment]
How is this not fixed yet? I still get the error everytime the screen width changes. Debounce messes with the animation

**Comment by ckifer** [comment]
@youngmoon715 do you mind making a codesandbox repro?  https://codesandbox.io/s/area-chart-in-responsive-container-e6dx0

I cannot reproduce
