### ISSUE TITLE
Documentation link broken in API section

### ISSUE THREAD

**Issue by areq** [recharts/recharts#1771]
## Do you want to request a feature or report a bug?
Report a bug in the documentation page, not in the library.
Inside the section http://recharts.org/en-US/api

## What is the current behavior?
Going to the section  _Label List_ under **General Components** section, clicking on that option get's to a broken page like shows in the screenshot:
[http://recharts.org/en-US/api/LabelList](http://recharts.org/en-US/api/LabelList)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

![image](https://user-images.githubusercontent.com/896517/59310439-b874b380-8c7c-11e9-97ab-b3e91097dbae.png)
![image](https://user-images.githubusercontent.com/896517/59310626-608a7c80-8c7d-11e9-880f-7b4f63580378.png)

**Tested in Chrome & Firefox.**

## What is the expected behavior?
To see the page of the documentation.

**Comment by sainthkh** [comment]
Works in Oct 17th, 2019. Closed.
