### ISSUE TITLE
Please include release notes with releases. 

### ISSUE THREAD

**Issue by coreysnyder** [recharts/recharts#1773]
## Do you want to request a feature or report a bug?
Feature

## What is the current behavior?
This one's quite simple. Do you guys mind describing your releases. I recently see that you've released version 1.6 but under the releases there's no description of what's changed. Could someone take a moment to put some release notes down. If these already exist somewhere and I've missed it can you point me in the right direction?

**Comment by FoxShaunR** [comment]
They have them in a file here: https://github.com/recharts/recharts/blob/master/CHANGELOG.md
