### ISSUE TITLE
Is there any way to hide text in brush?

### ISSUE THREAD

**Issue by JungHeum-Park** [recharts/recharts#1781]
![d](https://user-images.githubusercontent.com/47998293/60164599-d9223900-9838-11e9-8140-69953e2f9c02.PNG)

I want hide that text.
I read docs about brush API but I can't find about this
Is any way not to show this?

**Comment by JungHeum-Park** [comment]
just add css
`.recharts-brush-texts {
  font-size: 0;
}`

**Comment by ildevelop** [comment]
```
.recharts-brush-texts {
  display:none;
}
```
