### ISSUE TITLE
"Cannot read property 'value' of undefined" error after upgrading to v1.6.2

### ISSUE THREAD

**Issue by GreenGremlin** [recharts/recharts#1784]
## Do you want to request a feature or report a bug?

Report a bug

## What is the current behavior?

Starting in recharts@1.6.2, the following tooltip started generating "TypeError: Cannot read property 'value' of undefined" errors.
```js
<Tooltip itemSorter={(a, b) => a.value - b.value)} />
```

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

It looks like the signature of the `itemSorter` callback [recently changed](https://github.com/recharts/recharts/commit/25f0f95d00ca1126845fee638aef0167b0b50bfe#diff-872af309bdd843e8ed5cb5140d87c715). In recharts@1.6.1 it used `Array.prototype.sort` but in recharts@1.6.2 it was updated to use `_.sortBy`. 

The signature for `Array.prototype.sort` is `(a, b) => a - b`.

The signature for `_.sortBy` is `a => a`.

## What is the expected behavior?

Breaking changes should be released as a major version bump.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Version 1.6.2

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue guide.
