### ISSUE TITLE
Need help - ComposedChart - BiAxis - Multiple Bar Chart

### ISSUE THREAD

**Issue by ganapativs** [recharts/recharts#179]
I want to achieve something like this.
<img width="976" alt="chart" src="https://cloud.githubusercontent.com/assets/4010960/17737257/e32de0ae-64a9-11e6-990e-ed2f49c6083a.png">

But the bars are overlapping(http://jsfiddle.net/ragrbruL/15/). i want it to be on side by side.

I can add placeholder dataKey to achieve this though(http://jsfiddle.net/ragrbruL/22/).

Is there anyway to do this without placeholder dataKey?

**Comment by xile611** [comment]
@ganapativs Thank you! I'll tweak the position of bars for multiple y-axes!
