### ISSUE TITLE
The custom label page on the api documentation is broken

### ISSUE THREAD

**Issue by kostadriano** [recharts/recharts#1791]
## Bug

![image](https://user-images.githubusercontent.com/15300776/60593540-61449900-9d79-11e9-83ee-eebb54a3204b.png)

The custom label page (http://recharts.org/en-US/api/Customized) is broken

The website is on this repository? I can take a look at this :thinking:

**Comment by kaizoku-kenshin** [comment]
Any update on this?

**Comment by kostadriano** [comment]
I think [this](https://github.com/recharts/recharts.org/pull/91) solve the issue
