### ISSUE TITLE
Incorrect docs for Pie API

### ISSUE THREAD

**Issue by maybebored** [recharts/recharts#1793]
## What is the current behavior?
[Documentation for Pie API](http://recharts.org/en-US/api/Pie#labelLine) says `labelLine` prop is `false` by default, however it is not.

## Current behaviour
https://jsfiddle.net/maybebored/xLvsjpz5/2/ - notice a label line being rendered although `labelLine` prop isn't explicitly set.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts v1.6.2

**Comment by xile611** [comment]
Thanks! PR to [recharts.org](https://github.com/recharts/recharts.org) is welcome.
