### ISSUE TITLE
Support Cell for Treemap

### ISSUE THREAD

**Issue by SevereOverfl0w** [recharts/recharts#1795]
## Do you want to request a feature or report a bug?

Feature

If Cell was supported for Treemap then areas could have their fill varied.

**Comment by SevereOverfl0w** [comment]
From reading the source, I have found there's an undocumented "colorPanel" option which can be used to vary the fill.

**Comment by xile611** [comment]
Thanks! PR to [recharts.org](https://github.com/recharts/recharts.org) is welcome.
