### ISSUE TITLE
Multiple synced charts each with a brush, brush doesn't get updaed

### ISSUE THREAD

**Issue by bmtdh** [recharts/recharts#1796]
## What is the current behavior?
I have 3 line charts on a page. Each chart shares a syncId and each chart has a brush. When I change the brush on one chart each chart changes correctly, however the brush on the other charts don't update.

## If the current behavior is a bug, please provide the steps to reproduce.
Have multiple charts all synced all with their own Brush
![brush-example](https://user-images.githubusercontent.com/44874175/60718405-76a5f880-9f1c-11e9-90b8-80b111744705.png)

## What is the expected behavior?
I would assume that all the brushes would also get updated on synced charts? I can't find anything to say they shouldn't be updated, apologies if I missed this.

## Which versions of Recharts, and which browser / OS are affected by this issue? 
1.6.2
All browser and all OS

Any help or guidance would be greatly appreciated. Thanks!

**Comment by avindra** [comment]
Thanks for reporting this issue, I wouldn't have found the `syncId` property otherwise. I can see that setting this can be used to sync up `Brush` for multiple charts.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
