### ISSUE TITLE
tooltip location is not correct 

### ISSUE THREAD

**Issue by mosy1378** [recharts/recharts#1799]
i am using the linechart and the tooltip location has been shifted to right direction and is not in the currect place .how can i change the tooltip cordination ??? is there any way to do this ??
<img width="956" alt="Capture" src="https://user-images.githubusercontent.com/33086771/60767237-413f0d80-a0ca-11e9-9dac-51866a552ab5.PNG">

**Comment by aleeHe** [comment]
the same thing happened to me. I tested it and it seems the problem is with RTL direction.
if I change the parent container direction to LTR, the position of the tooltip is correct
