### ISSUE TITLE
Hovering over legend to highlight the corresponding chart

### ISSUE THREAD

**Issue by malrase** [recharts/recharts#180]
For complex graphs, it is sometimes necessary to highlight one data stream over the others. Hovering over the legend is a good trigger for this. An example of this is found in the [c3 library](http://c3js.org/) (e.g. [here](http://c3js.org/samples/simple_multiple.html))

In the jsfiddle graph linked below, for example, hovering over the "Left" area of the legend would make the corresponding "Left", purple bars highlighted and the "Right", green bars decrease their opacity.
http://jsfiddle.net/dyujxk7L/

I've been trying to figure out how to do this by myself, but although the legend has some unique class names, the charts themselves do not. Therefore I can't do a quick jQuery `onHover` link between the two items.

I suppose I'm asking if option 1 (hover over legend to highlight the corresponding chart) is a possible feature. If not, could option 2 (an id correspondence between the legend and the chart itself) be implemented – or do you have another suggestion for how to achieve the desired effect?

Great job with this library; I've found it very useful.

**Comment by xile611** [comment]
@malrase  Thank you for your advice! We are just planning to implement the linkage between legend and chart.
