### ISSUE TITLE
 is it possible to define the distance between <PolarAngleAxis> and <Radar>?

### ISSUE THREAD

**Issue by GSANCHESAV** [recharts/recharts#1800]
I wonder if it is possible to define a distance between **PolarAngleAxis** and **Radar**, because the Text is getting on top of the Radar? Look at the image:
![Captura de Tela 2019-07-09 às 23 57 10](https://user-images.githubusercontent.com/30024243/60937055-9125fc00-a2a5-11e9-91e7-22f7ce2cbe52.png)

**Comment by kaizoku-kenshin** [comment]
You can use a custom `tick` to render svg `text` component to your liking
