### ISSUE TITLE
Custom label in YAxis - how to rotate and scaleToFit at the same time?

### ISSUE THREAD

**Issue by Dr-Boomerang** [recharts/recharts#1801]
## Do you want to request a feature or report a bug?
I'm not sure if it's a bug, or maybe I'm just doing something wrong.

## What is the current behavior?
I'm building a composed chart and I am unable to use two specific props of the <Text> element in a YAxis custom label at the same time - I would like to rotate the label and also use the scaleToFit option, but when I set the scaleToFit, the rotation stops working.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
https://jsfiddle.net/DrBoomerang/msd2xf8h/19/

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
I'm currently using Recharts 1.6.2

**Comment by Dr-Boomerang** [comment]
Found a solution. Thanks! :)

**Comment by max4kaps** [comment]
@Dr-Boomerang was you able to get it working **scaleToFit** and **angle** the same time?

I receive this error:
`Error: <text> attribute transform: Expected number, "scale(NaN) rotate(45, …`

My example: https://jsfiddle.net/tjkrpn4u/46/
