### ISSUE TITLE
Recharts not working with `renderToStaticMarkup` SSR 

### ISSUE THREAD

**Issue by sauravexodus** [recharts/recharts#1806]
## Do you want to request a feature or report a bug?
Just a question

## What is the current behavior?
Bar Chart is missing from the HTML obtained from `renderToStaticMarkup` function.

## What is the expected behavior?
Bar Chart should be visible

**Comment by sauravexodus** [comment]
For some reason, it doesn't work when the radius of a `Bar` is set.

**Comment by xile611** [comment]
Please use the latest version `2.0.0-beta.5`. You can import `Global` from `recharts` to set `isSsr`.
