### ISSUE TITLE
Question: Handling overflow on PieChart's? 

### ISSUE THREAD

**Issue by patryk0605** [recharts/recharts#181]
Is there a way i can force the overflow to be visible? As you can see in the below example, the results are being cut off: 

![image](https://cloud.githubusercontent.com/assets/7227636/17787218/2d33ddb4-6556-11e6-8b2d-7ed0f817fe66.png)

Thanks in advance for your help!

**Comment by xile611** [comment]
@patryk0605 Sorry! There isn't any way to force the text to be visible, because the canvas of svg is too smaller to show all the texts. It's recommended to  position the texts inner the PieChart.
You can also check [this issue](https://github.com/recharts/recharts/issues/160) for discussion before.

**Comment by programador-gustavo** [comment]
.recharts-wrapper svg{
	overflow: inherit !important;
}
