### ISSUE TITLE
Example CustomizedCursor Component for Tooltip

### ISSUE THREAD

**Issue by aelfric** [recharts/recharts#1816]
The API documentation for `Tooltip` states that you can also pass a custom Component as the `cursor` prop.  (http://recharts.org/en-US/api/Tooltip#cursor).  Would you be able to provide an example of a cursor component that would work for this purpose?

**Comment by andynguy3n** [comment]
Same here. Thanks in advance.

**Comment by amcsi** [comment]
+1

I tried doing the following to try and get rectangle tooltip cursors, but I still get the curve type for my ComposedChart:

```jsx
<ComposedChart>
    ...
    <Tooltip cursor={Rectangle} />
</ComposedChart>
```

and

```jsx
<ComposedChart>
    ...
    <Tooltip cursor={<Rectangle />} />
</ComposedChart>
```

**Comment by ckifer** [comment]
doing something like this works but throws an error about brushBottom
` cursor={<rect fill="red" stroke="red" />}`

this works. customize anything from there with the props given. Props are: 
`bottom,
brushBottom,
className: "recharts-tooltip-cursor",
fill,
height,
left,
payload,
pointerEvents,
right,
stroke,
top,
width,
x,
y`
```javascript
const CustomCursor = props => {
    const { x, y, width, height, stroke } = props;
    return <Rectangle fill="red" stroke="red" x={x} y={y} width={width} height={height} />;
};
```
```javascript
<Tooltip
   cursor={<CustomCursor />}
/>
```

**Comment by xile611** [comment]
Thanks! PR to [recharts.org](https://github.com/recharts/recharts.org) is welcome.

**Comment by acomito** [comment]
@ckifer where is the <Rectangle /> coming from?

**Comment by ckifer** [comment]
Hey @acomito, I haven't been very active in recharts but from what I can tell the props have changed just a bit. There should be a `points` prop that has two sets of x and y values. From playing around I can't quite get them to work as they used to but feel free to post back here if you find a solution. [https://codesandbox.io/s/simple-composed-chart-forked-hsvfk?file=/src/App.tsx](Not quite working example)

**Comment by wmy94827** [comment]
> 从何而来？
> 
> 当我重新创建这个时，就像
> 
> ```
>  cursor={<CustomCursor />}
> ```
> 
> 我没有得到任何 y/x 道具......我确实看到了高度/宽度/笔触道具

+1

**Comment by alexevladgabriel** [comment]
> Hey @acomito, I haven't been very active in recharts but from what I can tell the props have changed just a bit. There should be a `points` prop that has two sets of x and y values. From playing around I can't quite get them to work as they used to but feel free to post back here if you find a solution. [Not quite working example](https://codesandbox.io/s/simple-composed-chart-forked-hsvfk?file=/src/App.tsx)

I'm required to make custom cursor with a button on top of the cursor, so If I found something I post here. 
Wish me luck 😁

**Comment by alexevladgabriel** [comment]
Well, that's how I do it and I hope it helps will help people like me in future.

```jsx
function CustomCursor(props) {
  const {
    stroke, pointerEvents, height, points, className,
  } = props;

  const { x, y } = points[0];
  return (
    <>
      {/*
        Default DOM Cursor
        <path
          stroke="#ccc"
          pointerEvents="none"
          width="892"
          height="276"
          points="[object Object],[object Object]"
          className="recharts-curve recharts-tooltip-cursor"
          type="linear"
          d="M615.483870967742,50L615.483870967742,326"
        />
      */}
      <Rectangle
        x={x}
        y={y}
        fillOpacity={0}
        stroke={stroke}
        pointerEvents={pointerEvents}
        width={1}
        height={height}
        points={points}
        className={className}
        type="linear"
      />
    </>
  );
}
```

**Comment by Evavic44** [comment]
Had to use the style prop directly before I could change the background color.

```tsx
<Tooltip
  cursor={<Rectangle style={{ fill: "red" }} />}
  defaultIndex={0}
/>
```
