### ISSUE TITLE
Type definitions for custom tick components

### ISSUE THREAD

**Issue by mchong-teal** [recharts/recharts#1817]
## Do you want to request a feature or report a bug?
Feature

## What is the current behavior?
No type definitions for props passed to custom 'tick' components

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
Uh, is there a typescript template?

## What is the expected behavior?
I can import a tick props interface and know what props I can use to render

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
recharts 1.6.2, browser/OS: n/a, previous versions: unkown

**Comment by sainthkh** [comment]
Solving #1390 will solve this problem.

**Comment by barrymichaeldoyle** [comment]
We need better docs for this because I had to find out how to do this from this issue.

**Comment by barrymichaeldoyle** [comment]
Yeah I pre-emptively commented here, couldn't find the type of ticks via that issue...

**Comment by barrymichaeldoyle** [comment]
Thanks for the tip, I guess I'll do that and create my own interface on my
side for now.
