### ISSUE TITLE
Question: how can i make a point jump ?

### ISSUE THREAD

**Issue by Aarbel** [recharts/recharts#1818]
![image](https://user-images.githubusercontent.com/25119847/61813532-2c8ea380-ae46-11e9-9182-59ff240c8724.png)

Do you know a way to "break" the chart in some parts, and make it end and start from 2 different values ? 

For example the yellow area in the above picture (the jump should be vertical)

Thanks a lot for your help !

**Comment by xile611** [comment]
Maybe you can try `<ReferenceLine />`
