### ISSUE TITLE
MultiLine Chart is not working in antd framework with reactjs, ver 15.6

### ISSUE THREAD

**Issue by arunDM** [recharts/recharts#1819]
I am trying to integrate Multiline Chart in Antd with react version 15.6.
I could see it in jsFiddle, BUT, when i try to integrate it in the project I cannot see the graph and also no error or issues or log to validate

JSFiddle Link

https://jsfiddle.net/arunkkumar2207j/hmerLzv1/39/

Thank you

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
