### ISSUE TITLE
Limit tooltip render frequency

### ISSUE THREAD

**Issue by mchong-teal** [recharts/recharts#1820]
## Do you want to request a feature or report a bug?
Bug Report

## What is the current behavior?
Tooltip re-renders for every mouse movement event on the chart.  I have a custom tooltip with a table in it, and tooltip performance is really poor.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
- I have a custom tooltip component that renders a styled table that slightly re-arranges the same data.

## What is the expected behavior?
I would like to have some options to change the tooltip behaviour:  ideally I have a more static tooltip that repositions itself only over each bar, and is static enough for the user to interact with the tooltip content (e.g. to scroll).

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts 1.6.2

**Comment by gndelia** [comment]
considering  a custom tooltip is on your side, why don't you apply memoizing in your component?
Could you provide a sandbox to reproduce your problem?

**Comment by xile611** [comment]
Use `throttleDelay` for chart of change the tooltip render frequence.

**Comment by eszthoff** [comment]
Could you add this prop `throttleDelay` to the documentation?

**Comment by mroz22** [comment]
+1

**Comment by ZarifS** [comment]
Still running into this, using the throttleDelay doesn't change the behaviour, any updates on what the best way to fix this is? Running into it in BarCharts but not PieCharts.
