### ISSUE TITLE
yAxis tick rendering isn't working for LineChart

### ISSUE THREAD

**Issue by natasha-robarge** [recharts/recharts#1823]
## Do you want to request a feature or report a bug?
Report a bug

## What is the current behavior?
Given a stacked bar chart with the same data as a line chart, the bar chart renders the yAxis tick marks fine based on the yAxis data received but it doesn't do the same for the line chart - instead, the tick values for the yAxis will not match up even though it has the same data as the bar chart. 

See images for bug.

<img width="823" alt="Screen Shot 2019-07-31 at 10 56 26 AM" src="https://user-images.githubusercontent.com/30872051/62228029-90532800-b382-11e9-85d9-e13ebee256e6.png">

<img width="823" alt="Screen Shot 2019-07-31 at 10 56 37 AM" src="https://user-images.githubusercontent.com/30872051/62228030-90532800-b382-11e9-89fe-c19abb609ce7.png">

Bar chart image displays data fine line chart does not

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

Create a bar chart and line chart with the same data and the bar chart will render the yAxis correctly but the lines in the line chart with the same data as the bar chart will overflow past the yAxis values

## What is the expected behavior?
The tick values of the yAxis should match with the same data being received

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Version 1.6.0 - was working with Chrome.

It works as expected in version 1.5.0

Working line chart image attached

<img width="802" alt="Screen Shot 2019-07-31 at 11 01 10 AM" src="https://user-images.githubusercontent.com/30872051/62228069-a2cd6180-b382-11e9-84c8-b9571b9cf89b.png">

**Comment by RickEyre** [comment]
+1

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue guide.
