### ISSUE TITLE
Changing start and end angle for RadarChart interferes with active dot

### ISSUE THREAD

**Issue by hknowlton** [recharts/recharts#1828]
## Do you want to request a feature or report a bug?
bug

## What is the current behavior?
Passing a start and end angle prop to the RadarChart component causes the active dot to be on the wrong axis when hovering 

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

To reproduce pass a start and endangle prop to the RadarChart component. Also set up an active dot on your Radar and add a tooltip. When hovering over the RadarChart the active dot will be on the wrong axis.
demo - https://jsfiddle.net/b0tu9gLf/2/

## What is the expected behavior?
The active dot should be on the axis that you are hovering over

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

I am on v 1.6.2 and I just started using the library, not sure if it worked previously.

**Comment by antoninklopp** [comment]
Hi @hknowlton , 

I am investigating the issue but did not find a code fix for now. 
However, it seems to work better in one direction than in the other. 

If you don't care about the direction of your chart, you can just swap **startAngle** and **endAngle** and it will work magically !

**Comment by hknowlton** [comment]
That is an acceptable workaround for sure. Thanks, @antoninklopp! Do you want me to leave this open for tracking purposes?

**Comment by antoninklopp** [comment]
Yes, I think that it should be tracked, thanks !

**Comment by xile611** [comment]
Sorry for not handling your issue in time, I can't open the jsfiddle url now, please try the latest version.  If the problem persists, please open a new issue according to the issue guide.
