### ISSUE TITLE
Cursor position off when using zoom in body tag

### ISSUE THREAD

**Issue by JackHull** [recharts/recharts#1829]
Hi,

I currently face the issue of my cursor position being off when hovering a chart; it seems slightly translated, which is most likely caused by my body tag using the CSS zoom variable; this is the only library in my project that seems to face this issue. See image below for clarification.

![showcase](https://user-images.githubusercontent.com/8144791/62484073-a1a09800-b7b9-11e9-9f4e-b23828eaa017.png)

Is there any workaround for this behaviour or fix coming soon? I am using Recharts 1.4.2 with React 16.7.0.

Thank you,

Jack

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by ashishihota** [comment]
Hi, I am trying to learn the recharts library and I am also getting the same issue. I was just wondering if this problem has been fixed?

**Comment by MS-Zapata** [comment]
Hello!
I also encounter this error by using transform: scale(0.8) css style on parent container.
Because of this I can't use Recharts's tooltip.
Any solution/counter measure is appreciated. Thanks.

I am using recharts 2.1.7

**Comment by ckifer** [comment]
This should work as of 2.9
