### ISSUE TITLE
Add support for arrow keys to move "tooltip cursor"

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#1834]
## Do you want to request a feature or report a bug?
Feature: Add support for precise movement of "cursor" (i.e. mouse position that sets data point used for tooltip) using keyboard arrow keys

## What is the current behavior?
Arrow keys are ignored by ReCharts

## What is the expected behavior?
Arrow keys would move the "cursor" that is currently moved by the mouse

**Comment by mgifford** [comment]
I think the primary accessibility improvement would be for better tab shift-tab support. That's a lot more common than the use of arrow keys. That said, for some graphs, charts, arrow keys would be pretty ideal. Might be a challenge to map top/bottom/left/right actions, but still would be useful. 

I see not having tab support as a bug, and arrow keys as a feature request. Just wanting to make sure that dots are connected here.

**Comment by ckifer** [comment]
Going to close this one out as it is currently possible with `accessibilityLayer` https://release--63da8268a0da9970db6992aa.chromatic.com/?path=/docs/api-accessibility--docs
