### ISSUE TITLE
Bar Chart tooltip currently doesn't work in JSFiddle examples

### ISSUE THREAD

**Issue by riceofearth** [recharts/recharts#1836]
Goto: http://recharts.org/en-US/examples

Go to any barcharts 
Hit try in jsfiddle

JSFiddle Barcharts doesn't have tooltips.

This is also happening in my product.

**Comment by riceofearth** [comment]
![jsfiddle](https://user-images.githubusercontent.com/3210756/62814686-fba9a200-bac6-11e9-99c1-ce5877a9b213.gif)

**Comment by bogem** [comment]
Downgrade to `"recharts": "1.6.2"` fixed for me

**Comment by EugeneDraitsev** [comment]
I created PR #1837 with fix for this issue
