### ISSUE TITLE
Vertical Y-Axis Label?

### ISSUE THREAD

**Issue by jacktasia** [recharts/recharts#184]
There doesn't seem to be way to do a vertical Y-Axis Label like this:

![image](https://cloud.githubusercontent.com/assets/31308/17833451/864d77f2-66d2-11e6-980a-876703191ddd.png)

Maybe I am missing something, but if I am not it would be great to support. Right now I am using multiple `div`s and transforming `transform: 'rotate(270deg)`, which becomes problematic when dynamic labels are different lengths. Or maybe there's an easy way to use the `label` prop on `YAxis`? Thanks!

**Comment by xile611** [comment]
@jacktasia Currently, you can get this only by a customized label which can be a function or a react element. And we'll trying to simplify the labels of recharts components.  Thank you!

And this issue is duplicated with [#160](https://github.com/recharts/recharts/issues/160).

**Comment by jacktasia** [comment]
> Currently, you can get this only by a customized label which can be a function or a react element. 

Fair enough, thanks for the response. FWIW, I would argue that for a `YAxis` label it should be vertical by default mainly because I've never seen a library that doesn't do it that way. When it's horizontal it's either creating extra width on the left or it's bleeding over the axis and potentially clashing with the proper title of the graph.

**Comment by ZephD** [comment]
I don't see how #160 is a solution to this issue, and therefore am confused as to why this issue was closed.
The current axis label positioning is very unusual.

It would be good to have the common situation:
Y-axis label vertical and to the left of the y-axis (rather than at the top of the axis)
X-axis label horizontal and under the x-axis (rather than at the far right)
Legend to be vertical and on the right of the chart

I've tried multiple libraries and rechart is truly the best I've found, apart from the above issues.

**Comment by ZephD** [comment]
custom label with these values sort of works...

`const AxisLabel = ({ axisType, x, y, width, height, children }) => {
  const isVert = axisType === 'yAxis';
  const rot = isVert ? -90 : 0;
  const cx = isVert ? -height / 2 : x + (width / 2);
  const cy = isVert ? y : y + (height / 2) + 14;
  return (
    <text x={cx} y={cy} transform={`rotate(${rot})`} textAnchor="middle">
      {children}
    </text>
  );
};`

The vertical alignment of the y-axis label is not quite right.
Also, transforming rotates before doing the x-y offset, so have to switch those values.

**Comment by youngnicks** [comment]
Changing the rotation point makes positioning the y-axis label much easier. The following is working for me.

``` javascript
const AxisLabel = ({ axisType, x, y, width, height, stroke, children }) => {
  const isVert = axisType === 'yAxis';
  const cx = isVert ? x : x + (width / 2);
  const cy = isVert ? (height / 2) + y : y + height + 10;
  const rot = isVert ? `270 ${cx} ${cy}` : 0;
  return (
    <text x={cx} y={cy} transform={`rotate(${rot})`} textAnchor="middle" stroke={stroke}>
      {children}
    </text>
  );
};
```

**Comment by malbolge44** [comment]
Hey @youngnicks can you please provide an example on how would you call this inside <YAxis 
label={SOMETHING} /> I'm new to react and not yet used to all the prop stuff.

**Comment by youngnicks** [comment]
@malbolge44, just create the component above and include it in your graph component. You would then use it with the following.

```javascript
<YAxis label={<AxisLabel axisType='yAxis'>Cost / Customer</AxisLabel>} />
```

**Comment by neekey** [comment]
@youngnicks thanks it works well. The only thing for me now is that it looks that the `label` prop does not render HTML element (like div, span), I still need to do some format for the label ( in my case the label will consist of two paragraph, one is like `last available month` and the second is`05/06/2016 - 05/07/2016)

**Comment by neekey** [comment]
I enhanced a little based on @youngnicks 's work:

```html
import React from 'react';

function renderText(child, x, y, rotate, stroke, key) {
  if (child && child.content) {
    return (<text
      key={key}
      x={x}
      y={y}
      transform={`rotate(${rotate})`}
      textAnchor="middle"
      stroke={stroke}
      {...child.props}>
      {child.content}
    </text>);
  }

  return (<text
    key={key}
    x={x}
    y={y}
    transform={`rotate(${rotate})`}
    textAnchor="middle"
    stroke={stroke}>{child}</text>);
}

export default function AxisLabel({ axisType, x, y, width, height, stroke, children }) {
  const isVert = axisType === 'yAxis';
  const cx = isVert ? x : x + (width / 2);
  const cy = isVert ? (height / 2) + y : y + height + 20;
  const rot = isVert ? `270 ${cx} ${cy}` : 0;
  const lineHeight = 20;

  if (children.length > 1 && children.map) {
    return (<g>
      {children.map((child, index) =>
        renderText(
          child,
          cx,
          cy + index * lineHeight,
          rot,
          stroke,
          index)
      )}
    </g>);
  }

  return renderText(children, cx, cy, rot, stroke);
}

AxisLabel.propTypes = {
  axisType: React.PropTypes.oneOf(['yAxis', 'xAxis']),
  x: React.PropTypes.number,
  y: React.PropTypes.number,
  width: React.PropTypes.number,
  height: React.PropTypes.number,
  stroke: React.PropTypes.string,
  children: React.PropTypes.any,
};
```

So that you can use it as simple: 

```html
<XAxis label={<AxisLabel axisType="xAxis">Hello</AxisLabel>}
```

Or you have multiple paragraphes, you can do:

```html
<XAxis label={<AxisLabel axisType="xAxis">{['hello', 'world']}</AxisLabel>}
```

You can also tweak the text a little bit:

```html
<XAxis label={<AxisLabel axisType="xAxis">{{
    content: 'hello',
    props: { fontSize: 14, fontWeight: 200 },
}}</AxisLabel>}
```

**Comment by ZephD** [comment]
I had to use:
`
const cx = isVert ? x +20 : x + (width / 2);
const cy = isVert ? (height / 2) + y : y + height;
`
to get it to align nicely. 
(Notice the +20 moved. The y-axis label was too far left, and the x-axis was too low)

Does this mean the alignment is not adaptive enough yet?

**Comment by oliverwatkins** [comment]
Your example : 

`<XAxis label={<AxisLabel axisType="xAxis">Hello</AxisLabel>}`

Doesn't work for me.

I get - 

> Error: <text> attribute y: Expected length, "NaN".

Do you need to feed in the arguments as properties like something like this ?

`<AxisLabel axisType="yAxis" x={123} y={123} stroke="blah">`

My full code :  

```
        <LineChart width={600} height={300} data={data}
                   margin={{top: 5, right: 30, left: 20, bottom: 5}}>
          <XAxis dataKey="name" label="asdfasdf"/>
          <YAxis label={<AxisLabel axisType="yAxis">Hello</AxisLabel>}/>
          <CartesianGrid strokeDasharray="3 3"/>
          <Tooltip/>
          <Legend />
          {lines}
        </LineChart>
```

(Still newish to react)

**Comment by sashahe** [comment]
Hey @oliverwatkins I had the same problem and I solved it by specifying default values for x and y (the origin). I am also new to React so if this is not a good solution please let me know :)

`var AxisLabel = ({ axisType, x=0, y=0, width, height, stroke, children }) => {
		var isVert = axisType === 'yAxis';
		var cx = isVert ? x + 20 : x + (width / 2);
		var cy = isVert ? (height / 2) + y : y + height;
		var rot = isVert ? `270 ${cx} ${cy}` : 0;
		return (
		<text x={cx} y={cy} transform={`rotate(${rot})`} textAnchor="middle" stroke={stroke}>
			{children}
		</text>
  );
};`

**Comment by jthetzel** [comment]
{ x, y, width, height } need to be defined. Try something like:
```
        <LineChart width={600} height={300} data={data}
                   margin={{top: 5, right: 30, left: 20, bottom: 5}}>
          <XAxis dataKey="name" label="asdfasdf"/>
          <YAxis label={<AxisLabel axisType="yAxis" x={25} y={125} width={0} height={0}>Hello</AxisLabel>}/>
          <CartesianGrid strokeDasharray="3 3"/>
          <Tooltip/>
          <Legend />
          {lines}
        </LineChart>
```

**Comment by ZephD** [comment]
I'm having to use
```label={({ viewBox }) => <AxisLabel axisType="yAxis" {...viewBox}>{yLabel}</AxisLabel>}```
to get it to position nicely.

I'm still having to tweak the cx and cy values each time...

**Comment by levininja** [comment]
@jacktasia how did you get your y axis to have dollar units in _front_ of the values?  i.e. $150k instead of 150k$

**Comment by jacktasia** [comment]
> @jacktasia how did you get your y axis to have dollar units in front of the values? i.e. $150k instead of 150k$

Sorry @levininja I can't remember (we eventually moved off recharts a short time later) and I no longer work where we were doing this so I can't access the code to look it up.

**Comment by levininja** [comment]
@jacktasia thanks for the quick response.  

I actually figured out it's tickFormatter for anyone else reading this.

**Comment by KyleAsaff** [comment]
the solutions are great and all but `AxisLabel`, unfortunately, doesn't seem to work when the graph is inside` <ResponsiveContainer></ResponsiveContainer>`

**Comment by antegulin** [comment]
Anyone made this work with `<ResponsiveContainer>`?

**Comment by ZephD** [comment]
The newer API for Labels should work inside:

http://recharts.org/en-US/api/Label

e.g.
`<YAxis label={{ value: 'My Y Axis', angle: -90, position: 'insideLeft' }} />`

**Comment by brian-fivetalent** [comment]
This doesn't fix longer text strings. The rotation is still happening from (0,0) of the text.

**Comment by calvinwyoung** [comment]
@brian-fivetalent Something like this works for me:

```
<YAxis type="number">
    <Label
        value="My Y Axis"
        position="insideLeft"
        angle={-90}
        style={{ textAnchor: 'middle' }}
        />
</YAxis>
```

**Comment by navarro-david** [comment]
I have this but the label is completely unaffected. No rotation. 

I am on `v2.0.0-beta.1`

Anyone running into these issues? 

```
<YAxis
   padding={{ top: 12 }}
   type='number'
   domain={[0, "dataMax + 2"]}
   yAxisId='hours'
   orientation='left'>
	<Label
	   value='Hours'
	   position='insideLeft'
	   angle={-90}
	/>
</YAxis>
```

**Comment by chrisgzf** [comment]
@navarro-david i installed version 1.8.5 and it fixed the problem. seems like the latest version might have broken the rotation, that even the website's provided jsfiddle doesn't work https://jsfiddle.net/alidingling/q5atk5jr/

**Comment by navarro-david** [comment]
I found a workaround that does work in `v2.0.0-beta.1`

Pass in a `Text` component with the angle prop
```
<YAxis
padding={{ top: 12 }}
type='number'
domain={[0, "dataMax + 2"]}
yAxisId='hours'
orientation='left'
label={
   <Text
      x={0}
      y={0}
      dx={50}
      dy={150}
      offset={0}
      angle={-90}
   >Hours</Text>
} />
```

**Comment by vanoMekantsishvili** [comment]
> Changing the rotation point makes positioning the y-axis label much easier. The following is working for me.
> 
> ```js
> const AxisLabel = ({ axisType, x, y, width, height, stroke, children }) => {
>   const isVert = axisType === 'yAxis';
>   const cx = isVert ? x : x + (width / 2);
>   const cy = isVert ? (height / 2) + y : y + height + 10;
>   const rot = isVert ? `270 ${cx} ${cy}` : 0;
>   return (
>     <text x={cx} y={cy} transform={`rotate(${rot})`} textAnchor="middle" stroke={stroke}>
>       {children}
>     </text>
>   );
> };
> ```

How to you pass the function to label, for me it says `label?: string | number | Label | LabelProps | undefined` No overload matches this call.

**Comment by iamyojimbo** [comment]
@calvinwyoung thank you: `style={{ textAnchor: 'middle' }}` was very useful!

**Comment by athenawisdoms** [comment]
@navarro-david @chrisgzf 

I tried your method but found that there is an error using `angle` when using Typescript. Using recharts v2.0.3...

Any ideas please? :)

```
Type '{ value: string; position: "insideLeft"; angle: number; }' is not assignable to type 'IntrinsicAttributes & Pick<Props, "string" | "style" | "clipPath" | "filter" | "mask" | "path" | "type" | "ref" | "key" | "className" | "id" | "lang" | ... 462 more ... | "textBreakAll"> & Partial<...> & Partial<...>'.
  Property 'angle' does not exist on type 'IntrinsicAttributes & Pick<Props, "string" | "style" | "clipPath" | "filter" | "mask" | "path" | "type" | "ref" | "key" | "className" | "id" | "lang" | ... 462 more ... | "textBreakAll"> & Partial<...> & Partial<...>'.  TS2322
```
