### ISSUE TITLE
Not possible to set a CustomTooltip on BarChart

### ISSUE THREAD

**Issue by gorshipaktsyan** [recharts/recharts#1840]
It's not possible to set a CustomTooltip for BarChart. It shows the default Tooltip. Even when I remove the Tooltip component, the BarChart still shows the default tooltip

**Comment by natasha-robarge** [comment]
Did you set content to `content={<CustomTooltip />}` ? 
http://recharts.org/en-US/api/Tooltip#content

**Comment by gorshipaktsyan** [comment]
Yes, I did. It works fine for LineChart and PieChart. For the BarChart, even when I remove the <Tooltip /> component, it does not hide from the chart

**Comment by marciobarrios** [comment]
Can you create a codesandbox reproducing the issue? I am using a custom tooltip in a BarChart without problems using the `content` prop as Natasha already commented.

**Comment by skipjack** [comment]
I'm seeing a similar issue with `<ComposedChart>`. The custom tooltip is rendered but `visibility` remains `hidden` on the `.recharts-tooltip-wrapper` element.

**Comment by skipjack** [comment]
I worked around this issue by just overriding it...

``` css
.recharts-tooltip-wrapper {
    visibility: visible !important;
}
```

And handling hiding/showing from the custom renderer. Obviously this isn't super ideal but may be necessary anyway if you want to animate in and out.
