### ISSUE TITLE
No Tooltip Payload at Bar Chart

### ISSUE THREAD

**Issue by MagdaxMai** [recharts/recharts#1841]
Hello!

I use a custom tooltip for my bar chart, but it doesn't work anymore because the payload is always null. I tried to use the standard tooltip instead but this also doesn't work. I also use some Line Charts where the tooltip is still working.

**Comment by cstoddart** [comment]
@MagdaxMai I am having the same issue. Were you able to fix this?

**Comment by cstoddart** [comment]
Just saw this: https://github.com/recharts/recharts/pull/1837

Updating to 1.7.1 fixed my issue 👍
