### ISSUE TITLE
How to align XAxis ticks?

### ISSUE THREAD

**Issue by app06** [recharts/recharts#1842]
I have AreaChart. Need align XAxis ticks. I can't really find a way to move the ticks. Possible to move ticks text?
![Безымянный](https://user-images.githubusercontent.com/12737668/63036453-bb329580-bec5-11e9-9f71-87388fcd2345.png)

https://jsfiddle.net/8s7tp4gc/

1.7.1

**Comment by natasha-robarge** [comment]
Have you tried using minTickGap for your issue?

http://recharts.org/en-US/api/XAxis#minTickGap

I would also suggest asking on StackOverFlow to see if you can get a faster response rather than GitHub.

**Comment by antoninklopp** [comment]
Hi @app06 , 

Just using the doc [CustomizedLabelLineChart](http://recharts.org/en-US/examples/CustomizedLabelLineChart). 

You could do something like this : 
https://jsfiddle.net/r4k3pfxg/2/

Hope it helps !
