### ISSUE TITLE
Be able to style axis datakey labels passing html

### ISSUE THREAD

**Issue by KaotikS** [recharts/recharts#1843]
## Do you want to request a feature or report a bug?
Request a feature

## What is the current behavior?
Can't pass html into tickFormatter or any other property in order to customize yAxis datakey labels
The idea is to be able to customize the labels so if, for example, we want to show two texts for each value (title and description) we can pass html and style them as we want.

I've tried with a custom tick, but when using html it prints [Object object] into the graph

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.4.3

**Comment by KaotikS** [comment]
Already found a solution!
The trick is to use a CustomTick and return an array of Text objects.

![Untitled](https://user-images.githubusercontent.com/18339464/63171701-854ef780-c012-11e9-95b0-f69b184cb1fe.png)

![Untitled](https://user-images.githubusercontent.com/18339464/63171799-b29ba580-c012-11e9-967b-94bd3be1bdde.png)

**Comment by Mathijs003** [comment]
How to do this in a Typescript environment? Text is not defined

**Comment by EikESousA** [comment]
JMSuarez, have example this picture?
