### ISSUE TITLE
API documentation does not include details on function props

### ISSUE THREAD

**Issue by C-Higgins** [recharts/recharts#1845]
Whenever a function is referenced in a prop type, such as `label: Boolean | Object | ReactElement | Function [optional]`, there is no mention of what parameters the function receives, nor what the function should return. This is crucial information for anyone using the library. A solution should be determined for how to document these functions so that PRs can be opened for them. Should the word "function" be a link to another page? Should the function definition be below the prop definition? Please agree upon a standard and perhaps implement an example definition so others can proceed from that.

**Comment by xile611** [comment]
Thanks! PR to [recharts.org](https://github.com/recharts/recharts.org) is welcome.
