### ISSUE TITLE
How to position tooltip on the top of a barchart in rechart?

### ISSUE THREAD

**Issue by jagadish-V277** [recharts/recharts#1848]
Problem: I have created a bar chart with a custom tooltip. Now What I need is to position tooltip on top of the bar not within the area of the chart. Like in this picture.

https://i.stack.imgur.com/QYyEZ.jpg
![image](https://user-images.githubusercontent.com/54352722/63416728-9be3bd00-c41d-11e9-9038-0d59e997c739.png)

This is how It looks like now.
![image](https://user-images.githubusercontent.com/54352722/63417213-75725180-c41e-11e9-82d6-00bda89599ca.png)

**Comment by marciobarrios** [comment]
You can do it using the http://recharts.org/en-US/api/Tooltip#coordinate prop.

**Comment by jagadish-V277** [comment]
> You can do it using the http://recharts.org/en-US/api/Tooltip#coordinate prop.

Thanks @marciobarrios  - What exactly do I need to pass in coordinates to appear on top of the bar
I tried differnet combinations
like coordinate = { {x: 100, y: 140 } } 
but no luck .

**Comment by marciobarrios** [comment]
@jagadish-V277 sorry I haven't really tried so I'm not sure (I was reading the documentation), but checking the code you have several alternatives, probably an easier on is to use `wrapperyStyle`, try with `top` and `left` (the tooltip has a `position: absolute`):
```js
<Tooltip wrapperStyle={{ top: -150, left: 200 }} />
```

I'm not sure 100% this will work because tooltip also has a translation that modifies the position, but you can try to tweak these values to your needs.

You can also use `position` prop (I see it in the code, but it's not documented and it's completely static so I don't know how to change it for every tooltip), and finally the `coordinate`, the problem I see with coordinate is that the calculation of the tooltip position always tries to keep it inside the graph, so it's difficult to predict.

**Comment by matthewbschneider** [comment]
Set the `position` prop with a value for `y`.  This will give the tooltip a fixed y coordinate, while allowing x to be variable.

```
<Tooltip position={{ y: -100 }} />
```

See the logic here:  https://github.com/recharts/recharts/blob/master/src/component/Tooltip.js#L181

**Comment by gaurav5430** [comment]
> Set the `position` prop with a value for `y`. This will give the tooltip a fixed y coordinate, while allowing x to be variable.
> 
> ```
> <Tooltip position={{ y: -100 }} />
> ```
> 
> See the logic here: https://github.com/recharts/recharts/blob/master/src/component/Tooltip.js#L181

This works!

**Comment by vanoMekantsishvili** [comment]
> > Set the `position` prop with a value for `y`. This will give the tooltip a fixed y coordinate, while allowing x to be variable.
> > ```
> > <Tooltip position={{ y: -100 }} />
> > ```
> > 
> > 
> > See the logic here: https://github.com/recharts/recharts/blob/master/src/component/Tooltip.js#L181
> 
> This works!

Link is not working, please can you share the solution? I understand that we should use Tooltip - position api but how should we detect active bar (x,y) positions ?

**Comment by gaurav5430** [comment]
here is an example where the tooltip moves around in x dimension but is fixed in the y dimension:
https://codesandbox.io/s/recharts-fixed-y-tooltip-xdyln?file=/index.js

**Comment by vanoMekantsishvili** [comment]
@gaurav5430 Thank you for your response, but to be honest I couldn't understand from where are you calling this function.
I am trying to achieve exactly same what @jagadish-V277  pointed out in first comment. I have a bar chart and I just need to display tooltip on one of bar, tooltip should be fixed.
If you have solution and find some free time to share I really appreciate that. thanks!

**Comment by gaurav5430** [comment]
You are right, my example just shows a Tooltip at a fixed y position. 

Some workarounds are mentioned here: https://github.com/recharts/recharts/issues/488

**Comment by sanjay1909** [comment]
Hi @jagadish-V277 

This is the trick i did
`const handleBarEnter = (data, index) => {
    const {width, paddingLeft, paddingRight, height, paddingTop, paddingBottom, arrowHeight } = toolTipDimension;
    const toolTipTotalWidth = (width + paddingLeft + paddingRight );
    const toolTipXCenter = toolTipTotalWidth / 2;

    const toolTipTotalHeight = (height + paddingTop + paddingBottom );

    setToolTipPos({
      x: data.x + (barSize / 2) - toolTipXCenter , // Left corner + Half of bar size - tooltip center
      y: data.y - toolTipTotalHeight - arrowHeight
    });
  }
  
  
  // CustomTool Tip will receive the toolTipDimension, use those values to set the style of custom tool tip
  <Tooltip
        allowEscapeViewBox={{
          x: true,
          y: true
        }}
        contentStyle={toolTipDimension}
        active={false}
        isAnimationActive={false}
        position={toolTipPos}
        cursor={false}
        content={CustomTooltip}
        data={data}
      />
  
  `

**Comment by morozovkirill** [comment]
> > You can do it using the http://recharts.org/en-US/api/Tooltip#coordinate prop.
> 
> Thanks @marciobarrios - What exactly do I need to pass in coordinates to appear on top of the bar
> I tried differnet combinations
> like coordinate = { {x: 100, y: 140 } }
> but no luck .

You should use [viewBox](https://recharts.org/en-US/api/Tooltip#viewBox) prop to make coordinate work.

**Comment by amrendracs** [comment]
adasd

**Comment by amrendracs** [comment]
WORKING SOLUTION

Set bar graph coordinate in state on mouseover and use it to dynamically update position of tooltip

```js
const BarGraphComponent = () => {
  let [barGraphData, setBarGraphData] = useState({})

  return (
    <BarChart width={730} height={300} data={data}>
      <XAxis dataKey="date" />
      <YAxis
        domain={[0, 2000]}
        tickCount={8}
        padding={{ top: 10 }}
        ticks={[0, 250, 500, 750, 1000, 1250, 1500, 1750, 2000]}
        // tick={{ stroke: 'red', strokeWidth: 2 }}
      />
      <Tooltip
        content={<CustomTooltip />}
        viewBox={{ x: 100, y: 140, width: 400, height: 400 }}
        cursor={false}
        position={{ x: barGraphData.x, y: barGraphData.y - 40 }}
      />
      <Bar
        dataKey="usage"
        fill="#8884d8"
        onMouseOver={(data) => {
          console.log('data', data)
          setBarGraphData(data)
        }}
      ></Bar>
    </BarChart>
  )
}
```

**Comment by amrendracs** [comment]
WORKING SOLUTION

Set bar graph coordinate in state on mouseover and use it to dynamically update position of tooltip

```js
const BarGraphComponent = () => {
  let [barGraphData, setBarGraphData] = useState({})

  return (
    <BarChart width={730} height={300} data={data}>
      <XAxis dataKey="date" />
      <YAxis
        domain={[0, 2000]}
        tickCount={8}
        padding={{ top: 10 }}
        ticks={[0, 250, 500, 750, 1000, 1250, 1500, 1750, 2000]}
        // tick={{ stroke: 'red', strokeWidth: 2 }}
      />
      <Tooltip
        content={<CustomTooltip />}
        viewBox={{ x: 100, y: 140, width: 400, height: 400 }}
        cursor={false}
        position={{ x: barGraphData.x, y: barGraphData.y - 40 }}
      />
      <Bar
        dataKey="usage"
        fill="#8884d8"
        onMouseOver={(data) => {
          console.log('data', data)
          setBarGraphData(data)
        }}
      ></Bar>
    </BarChart>
  )
}
```

**Comment by amrendra007** [comment]
WORKING SOLUTION

Set bar graph coordinate in state on mouseover and use it to dynamically update position of tooltip

```js
const BarGraphComponent = () => {
  let [barGraphData, setBarGraphData] = useState({})

  return (
    <BarChart width={730} height={300} data={data}>
      <XAxis dataKey="date" />
      <YAxis
        domain={[0, 2000]}
        tickCount={8}
        padding={{ top: 10 }}
        ticks={[0, 250, 500, 750, 1000, 1250, 1500, 1750, 2000]}
        // tick={{ stroke: 'red', strokeWidth: 2 }}
      />
      <Tooltip
        content={<CustomTooltip />}
        viewBox={{ x: 100, y: 140, width: 400, height: 400 }}
        cursor={false}
        position={{ x: barGraphData.x, y: barGraphData.y - 40 }}
      />
      <Bar
        dataKey="usage"
        fill="#8884d8"
        onMouseOver={(data) => {
          console.log('data', data)
          setBarGraphData(data)
        }}
      ></Bar>
    </BarChart>
  )
}
```
https://codesandbox.io/s/tooltip-position-recharts-53qef

**Comment by berkin** [comment]
> WORKING SOLUTION
> 
> Set bar graph coordinate in state on mouseover and use it to dynamically update position of tooltip
> 
> ```js
> const BarGraphComponent = () => {
>   let [barGraphData, setBarGraphData] = useState({})
> 
>   return (
>     <BarChart width={730} height={300} data={data}>
>       <XAxis dataKey="date" />
>       <YAxis
>         domain={[0, 2000]}
>         tickCount={8}
>         padding={{ top: 10 }}
>         ticks={[0, 250, 500, 750, 1000, 1250, 1500, 1750, 2000]}
>         // tick={{ stroke: 'red', strokeWidth: 2 }}
>       />
>       <Tooltip
>         content={<CustomTooltip />}
>         //viewBox={{ x: 100, y: 140, width: 400, height: 400 }}
>         cursor={false}
>         position={{ x: barGraphData.x, y: barGraphData.y - 40 }}
>       />
>       <Bar
>         dataKey="usage"
>         fill="#8884d8"
>         onMouseOver={(data) => {
>           console.log('data', data)
>           setBarGraphData(data)
>         }}
>       ></Bar>
>     </BarChart>
>   )
> }
> ```
> 
> https://codesandbox.io/s/tooltip-position-recharts-53qef

it is not working well. if you move your mouse on the empty area, the tooltip does not move.

**Comment by Garry14** [comment]
> > WORKING SOLUTION
> > Set bar graph coordinate in state on mouseover and use it to dynamically update position of tooltip
> > ```js
> > const BarGraphComponent = () => {
> >   let [barGraphData, setBarGraphData] = useState({})
> > 
> >   return (
> >     <BarChart width={730} height={300} data={data}>
> >       <XAxis dataKey="date" />
> >       <YAxis
> >         domain={[0, 2000]}
> >         tickCount={8}
> >         padding={{ top: 10 }}
> >         ticks={[0, 250, 500, 750, 1000, 1250, 1500, 1750, 2000]}
> >         // tick={{ stroke: 'red', strokeWidth: 2 }}
> >       />
> >       <Tooltip
> >         content={<CustomTooltip />}
> >         //viewBox={{ x: 100, y: 140, width: 400, height: 400 }}
> >         cursor={false}
> >         position={{ x: barGraphData.x, y: barGraphData.y - 40 }}
> >       />
> >       <Bar
> >         dataKey="usage"
> >         fill="#8884d8"
> >         onMouseOver={(data) => {
> >           console.log('data', data)
> >           setBarGraphData(data)
> >         }}
> >       ></Bar>
> >     </BarChart>
> >   )
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://codesandbox.io/s/tooltip-position-recharts-53qef
> 
> it is not working well. if you move your mouse on the empty area, the tooltip does not move.

Just add onMouseLeave at the Bar

**Comment by abdelmoulaBouc** [comment]
this solution works for me:

allowEscapeViewBox and you can specifiy the position of the tooltip by x and y translation
```
      <Tooltip
        allowEscapeViewBox={{ x: true, y: true }}
        cursor={{ stroke: 'gray', strokeWidth: 1, strokeDasharray: '5' }}
        content={<CustomToolTip />}
      />
```
```
const CustomToolTip = (props: any) => {
  return (
    <div
      className='bg-white shadow-md rounded-lg debug'
      style={{
        transform: 'translate(-80px,-110px)',
      }}
    >
  tooltip content
    </div>
  );
};
```
![Screenshot from 2023-08-22 14-17-47](https://github.com/recharts/recharts/assets/122528110/71dc0e16-04f4-41f0-9a51-569ebf729fdd)

**Comment by WATA-Yiju** [comment]
> > WORKING SOLUTION
> > Set bar graph coordinate in state on mouseover and use it to dynamically update position of tooltip
> > ```js
> > const BarGraphComponent = () => {
> >   let [barGraphData, setBarGraphData] = useState({})
> > 
> >   return (
> >     <BarChart width={730} height={300} data={data}>
> >       <XAxis dataKey="date" />
> >       <YAxis
> >         domain={[0, 2000]}
> >         tickCount={8}
> >         padding={{ top: 10 }}
> >         ticks={[0, 250, 500, 750, 1000, 1250, 1500, 1750, 2000]}
> >         // tick={{ stroke: 'red', strokeWidth: 2 }}
> >       />
> >       <Tooltip
> >         content={<CustomTooltip />}
> >         //viewBox={{ x: 100, y: 140, width: 400, height: 400 }}
> >         cursor={false}
> >         position={{ x: barGraphData.x, y: barGraphData.y - 40 }}
> >       />
> >       <Bar
> >         dataKey="usage"
> >         fill="#8884d8"
> >         onMouseOver={(data) => {
> >           console.log('data', data)
> >           setBarGraphData(data)
> >         }}
> >       ></Bar>
> >     </BarChart>
> >   )
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://codesandbox.io/s/tooltip-position-recharts-53qef
> 
> it is not working well. if you move your mouse on the empty area, the tooltip does not move.

Try move "onMouseMove" Event to <BarChart>

```js
const BarGraphComponent = () => {
  let [barGraphData, setBarGraphData] = useState({})

  return (
    <BarChart width={730} height={300} data={data}         
          onMouseOver={(data) => {
          console.log('data', data)
          setBarGraphData(data)
        }}
>
      <XAxis dataKey="date" />
      <YAxis
        domain={[0, 2000]}
        tickCount={8}
        padding={{ top: 10 }}
        ticks={[0, 250, 500, 750, 1000, 1250, 1500, 1750, 2000]}
        // tick={{ stroke: 'red', strokeWidth: 2 }}
      />
      <Tooltip
        content={<CustomTooltip />}
        //viewBox={{ x: 100, y: 140, width: 400, height: 400 }}
        cursor={false}
        position={{ x: barGraphData.x, y: barGraphData.y - 40 }}
      />
      <Bar
        dataKey="usage"
        fill="#8884d8"
      ></Bar>
    </BarChart>
  )
}
```

**Comment by rafaelgfx** [comment]
> WORKING SOLUTION
> 
> Set bar graph coordinate in state on mouseover and use it to dynamically update position of tooltip
> 
> ```js
> const BarGraphComponent = () => {
>   let [barGraphData, setBarGraphData] = useState({})
> 
>   return (
>     <BarChart width={730} height={300} data={data}>
>       <XAxis dataKey="date" />
>       <YAxis
>         domain={[0, 2000]}
>         tickCount={8}
>         padding={{ top: 10 }}
>         ticks={[0, 250, 500, 750, 1000, 1250, 1500, 1750, 2000]}
>         // tick={{ stroke: 'red', strokeWidth: 2 }}
>       />
>       <Tooltip
>         content={<CustomTooltip />}
>         //viewBox={{ x: 100, y: 140, width: 400, height: 400 }}
>         cursor={false}
>         position={{ x: barGraphData.x, y: barGraphData.y - 40 }}
>       />
>       <Bar
>         dataKey="usage"
>         fill="#8884d8"
>         onMouseOver={(data) => {
>           console.log('data', data)
>           setBarGraphData(data)
>         }}
>       ></Bar>
>     </BarChart>
>   )
> }
> ```
> 
> https://codesandbox.io/s/tooltip-position-recharts-53qef

Instead of applying the mouse event in `Bar` component. Add it to the `BarChart` using the `onMouseMove` event:

```
<BarChart
  onMouseMove={(_, e) => {
    setBarGraphData({ x: e.clientX, y: e.clientY })
  }}
  ...
/>
```
