### ISSUE TITLE
Bug: Y-Axis data point extends beyond chart (and "auto" or "dataMin|Max" has no effect)

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#1849]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
See the screenshot below. Notice how the 3.20 value is rendered off the bottom of the chart. The behavior is the same for Y-Axis domain of `["auto", "auto"`] and `["dataMin", "dataMax"]`. The only way to "fix" it is to set a fixed domain value, like `[0, "auto"]`.
![image](https://user-images.githubusercontent.com/685316/63444503-56fb5e80-c3fc-11e9-8de2-ec07f6a13e91.png)

## What is the expected behavior?
The Y-Axis should auto-adjust to the full range of values in "auto" or "dataMin|Max" domain modes.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Currently using ReCharts 1.6.2
I can't be sure if it worked in a previous version or not. It's not something I've seen before, but it may be data-related. The only "unusual" thing about this data is that some of the values are nulls, but I wouldn't think that should cause a problem.

**Comment by adoel90** [comment]
After i face the same problem with dataMin, dataMax in Recharts,  i think instead use domain=["dataMin", "dataMax"].

We can simply to solve the bug dataMin dataMax with domain=[Math.min(...valueTemperatureY), Math.min(...valueTemperatureX)]

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by mattboan** [comment]
Could be that your data is an array of strings? That was my problem.

**Comment by joshuadschoep** [comment]
> Could be that your data is an array of strings? That was my problem.

Anyone coming in after, check for this. This ended up being my silly problem as well.
