### ISSUE TITLE
Tooltip and XAxis

### ISSUE THREAD

**Issue by areski** [recharts/recharts#185]
Tooltip doesn't display the same way if you add or remove `XAxis`.

Without `XAxis` the tooltip doesn't know the datakey and so display a number.
http://jsfiddle.net/areski/97q4apgw/2/

With `XAxis` we got a perfect tooltip:
http://jsfiddle.net/areski/97q4apgw/5/

**Comment by xile611** [comment]
Yeah! It's true. Without XAxis, the tooltip just display the serial number.

**Comment by areski** [comment]
Additionally if the chart is display inside a `html table` the tooltip is not being displayed

**Comment by xile611** [comment]
@areski Can you support an online example?

**Comment by xile611** [comment]
I have checked LineChart in a table, seems no problem.

**Comment by brianjp93** [comment]
I was able to fix this by adding the XAxis, but then hiding it.

`<XAxis hide={true} dataKey='name' />`
