### ISSUE TITLE
How To create dynamic data.

### ISSUE THREAD

**Issue by jbcloudtVk** [recharts/recharts#1850]
Hello,

I need help with follwing example.
https://jsfiddle.net/nvxcd6jL/
I have created dynamic data but data is not showing in bar-chart same as below.
e.g 
const data = [
      {name: 'Page A', uv: 4000, female: 2400, male: 2400},
      {name: 'Page B', uv: 3000, female: 1398, male: 2210},
      {name: 'Page C', uv: 2000, female: 9800, male: 2290},
      {name: 'Page D', uv: 2780, female: 3908, male: 2000},
      {name: 'Page E', uv: 1890, female: 4800, male: 2181},
      {name: 'Page F', uv: 2390, female: 3800, male: 2500},
      {name: 'Page G', uv: 3490, female: 4300, male: 2100},
];

  if (data) {
     console.log("data",data);
      data.forEach(element => {
        let dataArray = {
          name: element.name ? element.name : null,
          air: element.uv ? element.uv : 0,
          land: element.male ? element.male : 0,
          sea: element.female ? element.female : 0
        };
        this.state.objectOf.push(dataArray);
      });
      this.setState({
        objectOf: this.state.objectOf      });
    }

**Comment by antoninklopp** [comment]
Hi @jbcloudtVk , 

Your problem is actually not with recharts, but with react. 
It is not recommended to change this.state as it should be immutable. 

This could be a solution for you : https://jsfiddle.net/a7oj9fv6/5/

**Comment by antoninklopp** [comment]
@jbcloudtVk Could you close this issue please? 
Or @sainthkh ? 

Thanks !

**Comment by jbcloudtVk** [comment]
@antoninklopp Thanks a lot !!! I will try your solution.
