### ISSUE TITLE
Allow brush to have a fixed range

### ISSUE THREAD

**Issue by gndelia** [recharts/recharts#1851]
## Do you want to request a feature or report a bug?

Feature

## What is the current behaviour?

When rendering a brush, the user can update the range. There are two properties that allow  devs to set the initial state for the brush, but then the state is handled internally, and there is no way to keep it fixed

## What is the expected behaviour?

It would be great if we could set a fixed range - so the user can move it within the brush, but not expanding (so the difference between the end index and the start index stays the same). That means the user would always see the same number on bars while moving the brush

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

It is a feature, so it would be only for future versions. OS should not be affected

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by RodolfoSilva** [comment]
This problem persists.

**Comment by RodolfoSilva** [comment]
This problem persists. @xile611

**Comment by cooperjones** [comment]
In case someone else lands here, I was able to hack a solution by targeting the traveller elements that allow the user to change the range with css and hiding them. First set the travellerWidth prop of the Brush component to 0. Then add the following CSS (or target the .recharts-brush-traveller class with your favorite css lib)
.recharts-brush-traveller {
  display: none
}

It would still be great if this could be handled through props...

**Comment by enthusapp** [comment]
If set to travellerWidth=0 with specific start/endIndex, fixed range work.

**Comment by nehanisarkhan** [comment]
@enthusapp I was having this issue with my chart.This Worked thank you so much :)

**Comment by voldemort13** [comment]
With travellerWidth set to 0 it will not work perfectly since you can still select the traveller elements, but it's so hard to get the mouse to the exact position to be able to select, it that it makes this solution viable.

**Comment by hongvantruong** [comment]
`travellerWidth={0}` is not the best solution — it causes glitchy behavior in the brush. For example, even when your brush is set to `{ startIndex: 0, endIndex: 12 }`, it can still move further left to { 0, 11 }. This happens because there's always a small interactive space left by the invisible traveller, allowing the brush slide to shift unexpectedly.

Inspired by the solution from @voldemort13, here’s my solution:

```
<Brush
  travellerWidth={1}
  traveller={(props) => (
    <div
      {...props}
      style={{ opacity: 0, pointerEvents: "none" }}
    />
  )}
/>
```
