### ISSUE TITLE
Dynamic ReferenceArea highlights Axis labels as well

### ISSUE THREAD

**Issue by torte** [recharts/recharts#1853]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
While using the example for zooming into a line chart (http://recharts.org/en-US/examples/HighlightAndZoomLineChart) in JSFIddle (https://jsfiddle.net/alidingling/nhpemhgs/), when using the ReferenceArea, some of the Axis labels get focused/highlighted as well, even I did not move the mouse outside of the inner chart. This happens before the actual zoom action is triggered and while moving the mouse around in the chart and holding the mouse button to choose the reference area. Attached a screenshot of the fiddle when doing so:

![screenshot-jsfiddle net-2019 08 29-12_22_19](https://user-images.githubusercontent.com/165341/63905642-3795ae80-ca58-11e9-8807-b3a7261303c0.png)

![screenshot-jsfiddle net-2019 08 29-12_34_35](https://user-images.githubusercontent.com/165341/63906035-9576c600-ca59-11e9-9f48-c5abb1019f9f.png)

For some strange reason it does not happen in the embedded example on the recharts page itself, but only the fiddle. As a side note it **does** happen on a project I am working on, but I did not want to show an example here, since it is reproducible in the original JSFiddle of the example.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
As explained above.

## What is the expected behavior?
I would not except the axis labels to highlight if I don't select the ReferenceArea outside of the inner chart.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Latest (1.6.2). I don't know if it worked before, since I only started with latest. The browser I used when doing the screenshot above was Chrome, but it happens in other webkit browsers as well. Could not reproduce it in Firefox.

**Comment by sibbl** [comment]
You could simply apply the CSS `user-select: none;` to the `.recharts-wrapper` element (or to the axis elements specifically if required) as a workaround.

Maybe this CSS rule could be applied while the mouse is pressed during the selection of the area to zoom into.

**Comment by torte** [comment]
@sibbl Thanks for the workaround. I applied the CSS rule to the Axis ticks and that works for now.
