### ISSUE TITLE
Custom `shape` for each of the `Bar`s in `BarChart`

### ISSUE THREAD

**Issue by aaronzhou-houzz** [recharts/recharts#1856]
Right now the only customizations we can have at the per bar level by accessing the `Cell` are `fill` and `stroke`. http://recharts.org/en-US/api/Cell

Can we also support `shape` at the per `Cell` level?

**Comment by xile611** [comment]
@aaronzhou-houzz You can use `shape` of <Bar />.

http://recharts.org/en-US/api/Bar#shape
