### ISSUE TITLE
Combined stacked bar with line chart

### ISSUE THREAD

**Issue by MatheusPopp** [recharts/recharts#1859]
Is it possible to build a stacked bar with a line chart? Like a <ComposedChart><BarChart/><Line/></ComposedChart>? If isn't, is there any plan to build this feature on the future?

I'm trying to use <ComposedChart> with <BarChart> and <Line> but is not rendering the chart, with normal bar and line works.

**Comment by guilhermealles** [comment]
Have you tried using the Composed Chart? I believe something like [this example](http://recharts.org/en-US/examples/LineBarAreaComposedChart) is what you are looking for.

**Comment by MatheusPopp** [comment]
@guilhermealles  yeah i have, but with stacked bar didn't work, just with normal bar. Have you ever tried stacked bar with line on Composed Chart?

**Comment by GergelyMolnar** [comment]
I have no trouble plotting stacked bar series with line series in the same composed chart.

Here's what I use to plot both stacked bar and line series on the same chart
```
const dataSeries = (d) => {
    let series = [];
    dKeys = Object.keys(d[0]);
    for (const dkey of dKeys) {
        const color = cGen.next().value;
        if (dkey !== 'xName') {
            series.push(<Bar dataKey={dkey} stackId="a" opacity='0.8' fill={color}/>);
            series.push(
                <Line type="linear" dataKey={dkey} stroke={color} activeDot={{ r: 8 }} legendType='none' hide={false}/>
             );
        }
    }
    return series;
};
```

and in the JSX
```
...
    {dataSeries(data)}
...
```

![image](https://user-images.githubusercontent.com/16977780/68273572-bada0e80-005e-11ea-8328-ea6e9c1daf3d.png)
_(recharts stacked bar- and line series on the same composed plot)_

My idea was to plot the same series as bar- and line charts and hide the line charts and use an `onMouseEnter() / onMouseLeave()` event on a series to show/hide the relevant line series.

My issue is the line charts won't stack and it's difficult to read tendencies of a single series when we have several series with zero value is allowed (common in fact) plot and hide.

This is what I meant:
![image](https://user-images.githubusercontent.com/16977780/68274779-ead6e100-0061-11ea-9066-1ddd7ac470de.png)
_(react-vis mixed chart)_

I've tried to add the same and different `stackId` prop to the line series too but it has no effect.

**It would be a useful addition if the line series would take the (same) `stackId` prop the same way as the bar series do thus those could be used to show tendencies.**

**Comment by OtaniJun** [comment]
Same trouble here.
@GergelyMolnar 
May I see your minimal src which reproduce combination of stacked bar and line?

**Comment by J-x-D** [comment]
In my case the line chart appears first. The stacked bar chart wasn't there. What fixed the problem was specifying the boxSize. 
`
<Line type="linear" dataKey="uv" stroke="#b0b0b0" activeDot={{ r: 8 }} legendType='none' hide={false} />
<Bar dataKey="uv" barSize={20} stackId="a" fill="#b0b0b0" opacity="0.75" onClick={onClick} isAnimationActive={false} label={renderCustomizedLabel} />
<Bar dataKey="pv" barSize={20} stackId="a" fill="#616161" opacity="0.75" onClick={onClick} isAnimationActive={false} label={renderCustomizedLabel} />
                    `

**Comment by jamesphongduong** [comment]
![image](https://user-images.githubusercontent.com/42558385/76388233-bc289880-63bc-11ea-9265-f2cc84b16513.png)

Anyone else having it render like this? Using the code out of the box
`import React, { PureComponent } from 'react';
import {
  ComposedChart, Line, Area, Bar, XAxis, YAxis, CartesianGrid, Tooltip,
  Legend, Scatter,
} from 'recharts';

const data = [
  {
    name: 'Page A', uv: 590, pv: 800, amt: 1400, cnt: 490,
  },
  {
    name: 'Page B', uv: 868, pv: 967, amt: 1506, cnt: 590,
  },
  {
    name: 'Page C', uv: 1397, pv: 1098, amt: 989, cnt: 350,
  },
  {
    name: 'Page D', uv: 1480, pv: 1200, amt: 1228, cnt: 480,
  },
  {
    name: 'Page E', uv: 1520, pv: 1108, amt: 1100, cnt: 460,
  },
  {
    name: 'Page F', uv: 1400, pv: 680, amt: 1700, cnt: 380,
  },
];

export default class Example extends PureComponent {
  static jsfiddleUrl = 'https://jsfiddle.net/alidingling/9xopwa9v/';

  render() {
    return (
      <ComposedChart
        width={500}
        height={400}
        data={data}
        margin={{
          top: 20, right: 20, bottom: 20, left: 20,
        }}
      >
        <CartesianGrid stroke="#f5f5f5" />
        <XAxis dataKey="name" />
        <YAxis />
        <Tooltip />
        <Legend />
        <Area type="monotone" dataKey="amt" fill="#8884d8" stroke="#8884d8" />
        <Bar dataKey="pv" barSize={20} fill="#413ea0" />
        <Line type="monotone" dataKey="uv" stroke="#ff7300" />
        {/* <Scatter dataKey="cnt" fill="red" /> */}
      </ComposedChart>
    );
  }
}
`

**Comment by J-x-D** [comment]
I suppose you want to avoid the overlapping of the axis. Adding padding, like the following, should fix your problem.

```
<XAxis dataKey="name" padding={{ left: 30, right: 30 }}/>

**Comment by hellsing2030** [comment]
hola estuve observando la libreria y hasta este año 2022 no hay areas stakeables, lo que me soluciono el problema para stakear las areas es sumar las 2 anteriores como se hace en las bar stack id, puedes hacer un mapeo de informacion en la data que se recibe y sumar los datos para stakear la area, utilizando .map y arreglando los toolpid y legend con un custom
