### ISSUE TITLE
Customized Dots based on the Problem Title in the Payload

### ISSUE THREAD

**Issue by Vinay9427** [recharts/recharts#1860]
I am using Scatter chart for the plotting the time series information. Here every dot is in purple color. All i need is to have single color based on Problem Title as shown in the image below.
![image](https://user-images.githubusercontent.com/25826205/64260185-0af60100-cf48-11e9-8f93-86fac716c0ab.png)

Ex : something like this.

Below image is having different color based on the type of issue.
![image](https://user-images.githubusercontent.com/25826205/64260457-86f04900-cf48-11e9-8f4e-bd870fe393c2.png)

Do we have anything for customizing Dots color based on label?

**Comment by swetha2** [comment]
Hi... Even i have a similar requirement. Is there any way to achieve this?

**Comment by xile611** [comment]
use customized shape of dot to handle this.
