### ISSUE TITLE
Pie chart label not working with 'isAnimationActive=true'

### ISSUE THREAD

**Issue by rumsky** [recharts/recharts#1861]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
Pie chart label not working when isAnimationActive=true
## If the current behavior is a bug, please provide the steps to reproduce.
`<ResponsiveContainer width={width} height={height}>
      <PieChart>
        <Pie
          data={data}
          dataKey="value"
          cx={width / 2}
          cy={height / 2.6}
          outerRadius={80}
          fill={primary20}
          startAngle={90}
          endAngle={450}
          stroke={0}
          label>
          {data.map((entry, index) => (
            <Cell
              key={`cell-${index}`}
              fill={chartColors[index % chartColors.length]}
            />
          ))}
        </Pie>
        <Tooltip />
      </PieChart>
    </ResponsiveContainer>`

## What is the expected behavior?
show label when ssr
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
"recharts": "^1.7.1",

**Comment by rumsky** [comment]
Update: the reason not SSR, because "isAnimationActive" when add this prop label was not working.

**Comment by LoicSalaris** [comment]
Hi, got the same bug here when isAnimationActive is at true, label don't work, or randomly

**Comment by matYang** [comment]
+1 here, in version 2.0 isAnimationActive is true by default, and label never shows up, wasted a lot of my time, none of the examples mentioned this. To have label show up, needed to override isAnimationActive to be false

**Comment by HaveAGitGat** [comment]
Encountered this bug suddenly on 1.8.5. It was working on 1.8.5 a few weeks ago.

I reverted the CSS changes for my project, used the old package.json and used the exact same component while disabling all other component and still had the issue. Hmm.

Using `isAnimationActive={false}` for now.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.

**Comment by SaliMike** [comment]
The problem in version 1.8.5 still occurs. When PieChart has the active flag isAnimationActive label does not appear, or it appears randomly during the re-rendering of the component (it is easy to observe during change fill colour on props, pie 2 in in the example below). 
Example: https://codesandbox.io/s/festive-wiles-tjfte?fontsize=14&hidenavigation=1&theme=dark

It is true that disabling the animation with isAnimationActive with the false flag will cause the label to appear. However, it excludes the possibility of animating the chart.

**Comment by brandonwisnicki** [comment]
Bump. This also happens with BarCharts as well.

**Comment by johhnry** [comment]
Same issue here with `recharts@2.0.8`, when animating a Pie chart with labels they disappear when the cells are animated.

Is there a way to animate the labels and smoothly interpolate the values ? (in percent in this case)

![ezgif-2-ecf775ba92af](https://user-images.githubusercontent.com/35373357/109579292-e8bb5000-7af8-11eb-9dea-5809cc01bae6.gif)
