### ISSUE TITLE
How to customize the size(radius) of Scatter? 

### ISSUE THREAD

**Issue by CallMeSaltyF1sh** [recharts/recharts#1862]
Is there any configuration item for Scatter to change its initial size?

**Comment by xile611** [comment]
You can change the props `range` of `<ZAxis />`

http://recharts.org/en-US/api/ZAxis#range

**Comment by dsldsl** [comment]
@CallMeSaltyF1sh I know this was a few years ago - did you every figure it out?  Working on the same thing now.  Unsure how ZAxis fits in.

**Comment by codytodonnell** [comment]
@dsldsl I just struggled with the same thing and managed to figure out the solution. You can use the `shape` prop on the `<Scatter/>` component to render a custom `<Dot/>` component that you give your own radius to:

```
const RenderDot: FC<DotProps> = ({ cx, cy }) => {
  return (
    <Dot cx={cx} cy={cy} fill="red" r={15} />
  )
}

...

<ScatterChart
  width={400}
  height={400}
>
  <XAxis type="number" dataKey="myKey" name="myKey" />
  <YAxis type="number" dataKey="myOtherKey" name="myOtherKey" />
  <Tooltip cursor={{ strokeDasharray: '3 3' }} />
  <Scatter data={myData} fill="#8884d8" shape={<RenderDot/>}/>
</ScatterChart>
```
