### ISSUE TITLE
Inverted Funnel Chart

### ISSUE THREAD

**Issue by adamawang** [recharts/recharts#1866]
Is there any way to get the funnel chart to render inverted? 

Currently, if you add data from smallest to largest, the chart will render way out of bounds. I haven't been able to find too many examples of the Recharts funnel chart, but I did find d3-funnel by Jake Zatecky has an isInverted option.

**Comment by kylejginavan** [comment]
+1 I would like this too!

**Comment by vemundeldegard** [comment]
Would also like this!

**Comment by arielmeneses** [comment]
+1
