### ISSUE TITLE
How to make single value pie chart?

### ISSUE THREAD

**Issue by amitava82** [recharts/recharts#187]
Something like this?
![image](https://cloud.githubusercontent.com/assets/1279530/17845458/93b848ca-685f-11e6-8c8f-cf0eefecf942.png)

**Comment by xile611** [comment]
@amitava82 You can check [this issue](https://github.com/recharts/recharts/issues/171) for two workarounds.

**Comment by amitava82** [comment]
Not exactly same but close. How do I start it from 12'o clock?

**Comment by xile611** [comment]
@amitava82 You can set the `startAngle` and `endAngle` of `Pie` like this:

```jsx
<PieChart width={300} height={244}>
  <Pie
     data={chartData} 
     cx="50%" 
     cy="50%" 
     startAngle={90}
     endAngle={-270}
     innerRadius="60%"
     outerRadius="80%"
     stroke="none"
  />
</PieChart>
```

[Here](http://jsfiddle.net/vfeoLdp6/2/) is a demo.
Please check [document](http://recharts.org/api#Pie) for detail.

**Comment by KoushikGoramane** [comment]
I am not getting with the single value and I tried the above methods still not getting

![image](https://user-images.githubusercontent.com/45486173/123742346-1a86cc80-d8c9-11eb-8a3e-73afd048a302.png)
