### ISSUE TITLE
BarProps is missing the optional 'id' attribute in the typings

### ISSUE THREAD

**Issue by jcapinc** [recharts/recharts#1871]
This is the interface for BarProps, which will determine what typescript allows you to add to a Bar element:
```ts
export interface BarProps extends EventAttributes, Partial<PresentationAttributes>, Animatable {
    className?: string;
    fill?: string;
    radius?: number | number[];
    layout?: LayoutType;
    xAxisId?: string | number;
    yAxisId?: string | number;
    yAxis?: object;
    xAxis?: object;
    stackId?: string | number;
    barSize?: number;
    unit?: string | number;
    name?: string | number;
    legendType?: LegendType;
    minPointSize?: number;
    maxBarSize?: number;
    hide?: boolean;
    shape?: React.ReactElement | ContentRenderer<RectangleProps>;
    data?: BarData[];
    background?: boolean | React.ReactElement | ContentRenderer<any> | object;
    // see label section at http://recharts.org/#/en-US/api/Bar
    label?: boolean | Label | LabelProps | React.SFC<LabelProps> | React.ReactElement<LabelProps> | ContentRenderer<any>;
}
```

[According to the documentation](http://recharts.org/en-US/api/Bar#id),  this should have an optional `id` attribute. None of interfaces that this extends has an id attribute either. Attached is an image of my VSCode calling me out for using a property (id) that does not exist on the BarProps interface.

![image](https://user-images.githubusercontent.com/1325626/64726038-cd432c00-d4a3-11e9-8452-6ad72d6a5625.png)

This seems like an easy fix, I don't mind doing it and making a PR, but I wanted to check in and confirm whether this was a problem with the typings or the documentation (maybe ID is intentionally being removed?)

LMK

**Comment by jcapinc** [comment]
Bump?

**Comment by gndelia** [comment]
the types in [definitely typed](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/recharts/index.d.ts) are out of date. I will create a ticket an a PR for this

**Comment by jcapinc** [comment]
Ah, I did not realize this came from DT. Closing.

**Comment by gndelia** [comment]
[@types/recharts](https://www.npmjs.com/package/@types/recharts) is now published
