### ISSUE TITLE
domains are not correct when injecting data

### ISSUE THREAD

**Issue by ponciusz** [recharts/recharts#1872]
## Do you want to request a feature or report a bug?
BUG

## What is the current behavior?
When dynamically injecting data domain `dataMax` is not correct. The bar is much bigger and come out of the chart area.

example here: click the toggle button to toggle data check the console for `dataMax`
https://codesandbox.io/s/hopeful-clarke-gj34c?fontsize=14

## What is the expected behavior?
Domain `dataMax` should be calculated correctly 

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

The bug is present on latest Chrome/Firefox/Safari
I noticed it is working in version 1.5.0

**Comment by santhosh77h** [comment]
@ponciusz is this issue fixed... I have faced the same issue on version recharts@1.8.5

**Comment by ponciusz** [comment]
probably that was not an issue. it was my mistake. make sure you always provide numbers not a strings after data changes.
