### ISSUE TITLE
Each data entry has different innerRadius and outerRadius in PieChart

### ISSUE THREAD

**Issue by ke1vin1993** [recharts/recharts#1873]
## Do you want to request a feature or report a bug?
A feature
## What is the current behavior?
In \<PieChart\>, I couldn't set different innerRadius/outerRadius in \<Cell\> via props, and 'd' prop in \<Cell\> doesn't work
## What is the expected behavior?
I wanna set data entries with different innerRadius/outerRadius

**Comment by ke1vin1993** [comment]
<img width="97" alt="QQ20190917-113737@2x" src="https://user-images.githubusercontent.com/8654679/65009529-9eafd000-d93f-11e9-8ecf-f83a40c3ac9c.png">
Just like this

**Comment by YIZHUANG** [comment]
I ended up re-writing this component myself from scratch...

**Comment by ke1vin1993** [comment]
> I ended up re-writing this component myself from scratch...

I solved my problem by activeIndex and activeShape props...

**Comment by catmando** [comment]
@YIZHUANG @ke1vinn Would you mind sharing your solutions.  In particular I am looking for a static solution (i.e. it does not react to the user, just uses a different radius for each pie segment.
