### ISSUE TITLE
not show all AxisTick labels when exists very data

### ISSUE THREAD

**Issue by mauriciolucas22** [recharts/recharts#1876]
When i have very data, the ticks in aXis not show all labels!

Use this example and add more items in data:
https://jsfiddle.net/alidingling/5br7g9d6/

**Comment by oihandover** [comment]
I am using label for date: 01/01/2019

**Comment by xile611** [comment]
Set interval={0} to force show all the ticks.
http://recharts.org/en-US/api/XAxis#interval
