### ISSUE TITLE
Tooltip to be fixed to body element instead of parent element, currently getting cut out when reached borders

### ISSUE THREAD

**Issue by MohibWasay** [recharts/recharts#1877]
## Scroll Issue

When I scroll somewhere near the edges of a chart element placed inside a scrollable div, It brings tooltip with animation effect, causing div to show scroll and tooltip cannot appear correctly. Need to fix Tooltip to the body element instead of parent element.

**Comment by SenelithPerera** [comment]
Having the same issue. Any updates on this ?

**Comment by xile611** [comment]
Please open an issue follow the issue guide.
