### ISSUE TITLE
This plugin is dead, is there any substitute for Recharts ? 

### ISSUE THREAD

**Issue by ke1vin1993** [recharts/recharts#1878]
No one maintains, I should find a substitute.

**Comment by avindra** [comment]
Not officially dead, but the project is looking for contributors https://github.com/recharts/recharts/issues/1833 

You may want to try react-vis from uber, but even that project has halted :

https://github.com/uber/react-vis/issues/1248

**Comment by Kukunin** [comment]
The last commit was in August, a month ago. The library is powerful and well designed, 12k of stars on Github. I definitely wouldn't call it a dead plugin

**Comment by avindra** [comment]
As someone who has removed technical debt from  projects using 6k+ star libraries, I disagree with the 12k star as a good metric.

But as mentioned, the project was updated one month ago, and there _is_ an open call for action to maintenance.

Wondering if we can get @xile611 in here. This PR https://github.com/recharts/recharts/pull/1839 already resulted in someone forking and pushing another package to npm.

**Comment by iMerica** [comment]
I've switched to this fork:

https://github.com/salvoravida/recharts
