### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by simonbdev** [recharts/recharts#188]
This library is great. 

Any chance of porting to React Native? Charting libraries are few and far between on React Native.

**Comment by techniq** [comment]
Victory charts just recently added React Native support. Maybe some ideas
on how Recharts can add support can be determined from their approach -
https://formidable.com/blog/2016/08/05/announcing-victory-0-10-2-and-victorynative/

**Comment by xile611** [comment]
Recharts will not support react native in a short period of time. Because we think the differences between the charts in pc and in mobile is apparent, we don't have enough experience of mobile development.  And our team have chose to use native ios or android to develop wireless apps after some gays have tried to develop h5 apps hardly.

**Comment by techniq** [comment]
If Recharts ever does decide to support React Native, https://github.com/react-native-community/react-native-svg might make things easier (Victory uses it and created a [mock](https://github.com/FormidableLabs/react-native-svg-mock) library for it as well)

**Comment by thoqbk** [comment]
@xile611 I used Recharts in my React Native app with some customizations. The result is good. Can you have a look? [Using Recharts in React Native project](https://dzone.com/articles/using-recharts-in-react-native-project)

**Comment by aditya1711** [comment]
is there still no support by parent itself? Is it recommended to use recharts in react native?

**Comment by ddtch** [comment]
Guys it is time to open this issue again and contribute to all. If not a native support I suggest to do a wrapper with webview

**Comment by yinshurman** [comment]
+1 for React Native

**Comment by cesar-presence** [comment]
+1 for React Native

**Comment by miquelnez** [comment]
Still nothing?
