### ISSUE TITLE
Recharts: Can't find Event for Button in Custom Tooltip

### ISSUE THREAD

**Issue by rashmimh** [recharts/recharts#1883]
Using recharts for generating a line graph. Customizing tooltip as I need a button inside it. The issue is I am unable to get any event on the button present in the tooltip as tooltip doesn't stay stable it is destroying and recreating itself frequently. Any help will be appreciated. Thanks in advance.

       

    <Tooltip content={this.renderCustomTooltip}/>
     renderCustomTooltip = (props) => {
                    return (
                             <div>
                                 <button className="tooltip-view-button" onClick={()=>this.showModal}> . 
                                  <a>View More</a>
                                    </button>
                                   </div>
                              ); }

In show modal function I am just setting a boolean value state for modal show/hide.
Raised at Stackoverflow: https://stackoverflow.com/questions/58281511/recharts-cant-find-event-for-button-in-custom-tooltip

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue guide.

**Comment by rashmimh** [comment]
Thank you for taking the feature request. I will check it asap with a new version.

**Comment by thekamahele** [comment]
@rashmimh were you able to resolve this - having the same issue.

**Comment by olegzaitsevway** [comment]
Hi there guys!
Please help me to understand if there any progress with this feature. Using the latest version of recharts and still can't add onClick event to the custom tooltip item.
Thank you in advance.

**Comment by neomehta** [comment]
Guys, I need the same thing. Is there any update on it ?

**Comment by rashmimh** [comment]
We moved without this feature because of deadlines. Haven't tried yet.

**Comment by amandayhuang** [comment]
Any update on this?

**Comment by Zein-Fakhreddine** [comment]
Hey I got it working for me. Try adding ` pointerEvents: 'all'` to the CSS attributes of your button.

**Comment by aravindpadmanaban** [comment]
> Hey I got it working for me. Try adding ` pointerEvents: 'all'` to the CSS attributes of your button.

Thanks. It worked.

**Comment by smilexu** [comment]
> Hey I got it working for me. Try adding ` pointerEvents: 'all'` to the CSS attributes of your button.

Worked for me also, thanks.
