### ISSUE TITLE
Add y values to MouseEvents

### ISSUE THREAD

**Issue by levandosky** [recharts/recharts#1884]
## Feature
Add y values to MouseEvents

## What is the current behavior?
MouseEvent payload - argument in onMouse* events:

interface RechartsMouseEvent {
    chartX: number;
    chartY: number;
    activeTooltipIndex: number;
    activeLabel: number;
    activePayload: ActivePayload[];
    activeCoordinate: ActiveCoordinate;
}

interface ActivePayload {
    stroke: string;
    strokeWidth: number;
    fill: string;
    dataKey: string;
    name: string;
    color: string;
    value: number;
    payload: Payload;
}

interface ActiveCoordinate {
    x: number;
    y: number;
}

interface Payload {
    [key: string]: number
}

## What is the expected behavior?
In context of mouse handler y axis values should be passed. Just like activeLabel is passed - x axis value

**Comment by xile611** [comment]
Duplicated with #2283
