### ISSUE TITLE
ComposedChart margin not work inside ResponsiveContainer

### ISSUE THREAD

**Issue by ccamusso** [recharts/recharts#1887]
I have a problem when I using ComposedChart inside ResponsiveContainer
I set ComposedChart margin at zero, but not work.

This is my example:
https://codesandbox.io/s/responsivecontainer-seu9b

Where is the problem?

**Comment by xile611** [comment]
@ccamusso It's recommended to add `<XAxis scale="point"/>` if you want to change the default behavior.
