### ISSUE TITLE
AreaChart with animation doesn't work in Firefox

### ISSUE THREAD

**Issue by eXtremeX** [recharts/recharts#189]
Hey guys, 
This might be weird since the Recharts.org example page of AreaChart really works well in both Chrome and Firefox, but I'd really like some help or direction as I'm clueless what to do next but I really like this library and would be more than happy to keep using it in all my future projects.

I'm using Recharts.js in Meteor.js application (if it helps). 
On the page I render 2 Line charts and 1 Area charts . 
What happens is the following:
- On Chrome, every chart works nicely, meaning animation fully plays.
- On Firefox, every chart works nicely except the AreaChart type. In its case, animation kinda jumps from 0% to 100% in like a second, barely noticeable that there's is animation in it, more like jerk effect, video below.

What I did is I basically took the simplest area chart example (http://recharts.org/examples/#SimpleAreaChart) and put it on the page, no responsive containers (so I can rule that as being the problematic thing out), basically the simplest I can make it.

```
import {AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer} from 'recharts';

const data = [
      {name: 'Page A', uv: 4000, pv: 2400, amt: 2400},
      {name: 'Page B', uv: 3000, pv: 1398, amt: 2210},
      {name: 'Page C', uv: 2000, pv: 9800, amt: 2290},
      {name: 'Page D', uv: 2780, pv: 3908, amt: 2000},
      {name: 'Page E', uv: 1890, pv: 4800, amt: 2181},
      {name: 'Page F', uv: 2390, pv: 3800, amt: 2500},
      {name: 'Page G', uv: 3490, pv: 4300, amt: 2100},
];

<AreaChart width={600} height={400} data={data} margin={{top: 10, right: 30, left: 0, bottom: 0}}>
    <XAxis dataKey="name"/>
    <YAxis/>
    <CartesianGrid strokeDasharray="3 3"/>
    <Tooltip/>
    <Area type='monotone' dataKey='uv' stroke='#8884d8' fill='#8884d8' />
</AreaChart>
```

The only two differences that I'm doing VS the recharts.org site that I can think of are:
- I'm using class Panel extends React.Component { } notation instead of React.createClass({})
- I'm using Meteor.js 

Here's video of what's happening:
Chrome: https://miscstuff.tinytake.com/sf/OTI2OTE1XzM5MTM1MTQ
Firefox: https://miscstuff.tinytake.com/sf/OTI2OTE4XzM5MTM1MTc

The console output on both Chrome and Firefox shows exactly 0 errors/warnings.
Firefox is also updated to its latest version available as of this moment.

Any ideas? Could Meteor.js, server-side/client-side rendering play role on this?
Thanks in advance!

**Comment by xile611** [comment]
@eXtremeX  Can you try to update the latest version of Recharts. We used transform of svg element  to animate Area before, but it seems not work some time in safari of ios8.3. So we have refactored the animation area.

**Comment by eXtremeX** [comment]
@xile611 That totally worked! Thanks! I though I had the latest version but I obviously didn't. I guess you can close this issue then. I can't thank you enough, really good support on this package!
