### ISSUE TITLE
v1.8.0 is causing various crashes

### ISSUE THREAD

**Issue by raRaRa** [recharts/recharts#1894]
Recharts started crashing a lot after upgrading to `1.8.0`. I'm working on sandbox demo to reproduce the crash.

But this is the error I'm getting:

```
Error: TypeError: Cannot read property 'left' of undefined

in BarChart (at Purchases.js:369) in div (created by ResponsiveContainer) in ResponsiveContainer (at Purchases.js:368) 
```

The same error happens for `PieChart` and other charts. I'm using functional components.

**Comment by raRaRa** [comment]
v1.8.1 is still crashing for me, for the same reason. Did you update other components as well?

```
Error: TypeError: Cannot read property 'left' of undefined

in PieChart (at Purchases.js:473) in div (created by ResponsiveContainer) in ResponsiveContainer
```

**Comment by raRaRa** [comment]
Created new ticket with sandbox demo here: https://github.com/recharts/recharts/issues/1899

**Comment by eliotball** [comment]
Also seeing this.
