### ISSUE TITLE
v1.8.1 and v1.8.0 crash

### ISSUE THREAD

**Issue by raRaRa** [recharts/recharts#1899]
I have my charts in a hidden tab, where the tab content is set to `display: none;`. When I remove the `display: none;` then the chart component will crash. This didn't happen prior to v1.8.0.

Here's a sandbox demo: https://codesandbox.io/s/youthful-mahavira-82d24?fontsize=14

Click on the `Show charts` button and you'll see it crash.

**Comment by xile611** [comment]
Please try recharts@1.8.3
