### ISSUE TITLE
AreaChart with fill staying below curve?

### ISSUE THREAD

**Issue by eXtremeX** [recharts/recharts#190]
Hi once again,
This will be a quick question.

![example](https://cloud.githubusercontent.com/assets/8009142/17900257/d0f026fe-695e-11e6-82ea-797688dc8289.png)

Would it be possible to somehow force the Area chart to start applying that fill below the curve (at all times), so that I don't get that sort of effect where the curve is intercepting "fills", but instead get the effect where fill is always below the curve? 

Thanks again, super charting library!

**Comment by xile611** [comment]
@eXtremeX OK! We'll try to add a props to support customized base value.

**Comment by veddermatic** [comment]
So a change for this was added and reverted? How can we achieve the desired behavior in this issue?

**Comment by jokklan** [comment]
I would really like this function as well? Is development stoped on rechart?

**Comment by leshnevskyi** [comment]
Need this feature a lot! A prop is present in the docs though does not seem to affect the fill. Please, add implementation for it, would truly appreciate it. Thank you!
