### ISSUE TITLE
Get tooltip content onclick

### ISSUE THREAD

**Issue by omarsafwany** [recharts/recharts#1900]
## Do you want to request a feature or report a bug?
I need to get the tooltip content when clicking a point in the graph. It will basically get the axis values.
## What is the current behavior?
Currently I did that using `document.querySelector`, fetch the tooltip and get the `textContent`. The behavior was working to a certain extent but no longer works. Currently the content is almost empty but if I try to inspect element, the value is there.
## What is the expected behavior?
Get the tooltip content on click
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
`recharts 1.7.1`

**Comment by xile611** [comment]
duplicated with #1883
