### ISSUE TITLE
Recharts 1.8.1 YAxis in LineChart cause crash

### ISSUE THREAD

**Issue by LeonidGrr** [recharts/recharts#1901]
Cannot render YAxis components with dynamic ids and keys from array in LineCharts after updating recharts to 1.8.1.

App crashes with following error:
![image](https://user-images.githubusercontent.com/45781017/66923287-308b2580-f031-11e9-8d64-00d46309b673.png)

Had to fallback to 1.7.1 to resolve this crash.

**Comment by sainthkh** [comment]
Can you give us a crashing example with codesandbox or jsfiddle? Currently, all of our examples work fine.

**Comment by LeonidGrr** [comment]
Simple example dont throw an error. 
https://codesandbox.io/s/prod-shape-bk4vo

Problem lies whitin 
const yAxisIds = new Set();
 yAxisIds.add("999");
  const yAxisLabels = { "999": new Set("m/s") };

When I assign them like in example everything works fine. 

But in our project we get some data from server and dynamicaly calculate yAxisIds and yAxis labels based on this data and the we pass this values as props from our parent component.

As I said before in 1.7.1 everything is ok and its is not a problem for us to use 1.7.1, but after update to 1.8.1 app crashes when YAxis is being created from yAxisLabels and yAxisIds (which is quite unexpected behavior) .

**Comment by xile611** [comment]
@LeonidGrr Please try recharts@1.8.3

**Comment by LeonidGrr** [comment]
With 1.8.3 everything works. Thank you very much!
