### ISSUE TITLE
Composed LineChart's activeDot clickEvent not triggered on click.

### ISSUE THREAD

**Issue by ThekhoN** [recharts/recharts#1902]
## Do you want to request a feature or report a bug?
Feature Request

## What is the current behavior?
Composing LineChart with AreaChart.
```
<ComposedChart>
    <Area onClick={e => console.log("onClick Area: ", e)} stackId={1} />
    <Line 
      activeDot={{onClick: e => console.log("onClick Line ActiveDot: ", e)}} stackId={2} />
</ComposedChart>
```
Expected `<Line />`'s clickEvent to get triggered (cascade, higher stackId).
But `<Area />` clickEvent is fired when we click on <Line /> 's activeDot

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
https://codesandbox.io/s/pedantic-mclaren-t4o0o

## What is the expected behavior?
Expected `<Line />`'s clickEvent to get triggered (cascade, higher stackId).
But `<Area />` clickEvent is fired when we click on <Line /> 's activeDot

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
All OS - Windows, Mac
Recharts 1.8.1

**Comment by dauletisataev** [comment]
Is this issue still relevant to fix? I would like to debug this. Can you please confirm @sainthkh

**Comment by sainthkh** [comment]
I guess so. Can you reproduce it on your environment?

**Comment by dauletisataev** [comment]
@ThekhoN Yes, I could. It is indeed firing listener of the area, when I click on the dots.

**Comment by sainthkh** [comment]
Then how about fixing it?

**Comment by dauletisataev** [comment]
Yep, already work in progress :) @sainthkh

**Comment by xile611** [comment]
Please add `onClick` to the activeDot of `<Area />` and `<Line />` to fix this.
```
<ComposedChart width={900} height={900} data={data}>
          <CartesianGrid strokeDasharray="3 3" />
          <XAxis dataKey="period" />
          <YAxis dataKey="maxStream" />
          <Tooltip content={CustomTooltip} />
          {streamIds.map((stream, index) => (
            <Area
              onClick={e => console.log("onClick Area: ", e)}
              activeDot={{
                onClick: e => console.log("onClick Area ActiveDot: ", e)
              }}
              key={stream}
              type="monotone"
              dataKey={stream}
              stackId={index}
              stroke={colors[index]}
              fill={colors[index]}
            />
          ))}
          {streamIds.map((stream, index) => (
            <Line
              activeDot={{
                onClick: e => console.log("onClick Line ActiveDot: ", e)
              }}
              key={stream}
              type="monotone"
              dataKey={stream}
              stackId={index + streamIds.length}
              stroke={colors[index]}
              fill={colors[index]}
            />
          ))}
        </ComposedChart>
```
