### ISSUE TITLE
Cartesian Grid causing performance issues in graph with big data

### ISSUE THREAD

**Issue by pesekviktor** [recharts/recharts#1907]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/heuristic-chandrasekhar-xmq64)

### Steps to reproduce
Open the page and use chrome react profiler to record length of renders. You can see that "cartesian grid" took 500ms to render, which is a lot and seems not necessary at all.

### What is expected?
The grid should render quickly.

### What is actually happening?
The grid renders slowly

| Environment | Info |
|---|---|
| Recharts | v1.8.3 |
| React | 16.9.2 |
| System | Ubuntu |
| Browser | chrome |

---
Sandbox is here https://codesandbox.io/s/heuristic-chandrasekhar-xmq64?fontsize=14, here https://xmq64.csb.app/ you can use dev tools to see the cartesian grid render time. I do not see a place I could paste a screenshot of the render speed, but can provide.

**Comment by pesekviktor** [comment]
![image](https://user-images.githubusercontent.com/33232478/67032612-3443a880-f114-11e9-806c-67dfacce6ed4.png)

**Comment by xile611** [comment]
@pesekviktor Maybe you can create a PR to fix this. Have no idea now

**Comment by pesekviktor** [comment]
This is a while ago. For that project I had to count my scales anyway, so eventually I sorted it by painting grid lines as ReferenceLine and never actually looked into recharts code.

Hopefully if I find time I will try to investigate

**Comment by xile611** [comment]
@pesekviktor Hopes PR from you. Thanks.
