### ISSUE TITLE
Cannot read property left of undefined

### ISSUE THREAD

**Issue by nik72619c** [recharts/recharts#1909]
The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.

---

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。
I am using react-bootstrap with recharts, which renders two different charts using react-bootstrap Tab component. But ongoing to the other tab, the app crashes and the following error is shown :-
![Capture](https://user-images.githubusercontent.com/30630904/67036249-e5f4d080-f138-11e9-9f8c-7549d40cd4e3.PNG)

**Comment by sainthkh** [comment]
Does it happen with 1.8.3, too?
