### ISSUE TITLE
Label in center of PieChart

### ISSUE THREAD

**Issue by bduff9** [recharts/recharts#191]
I see a couple examples where there is text placed into the center of Donut Pie Chart based on active index.  In my case, I need static text placed into the center representing the data (i.e. 30% if that is what the data represents).  I can kind of get by this using custom label, but if I ever need labels outside of the center too, this won't work.

Am I missing something or is this currently accurate in how one might do this?  Thanks!

**Comment by xile611** [comment]
@bduff9  If the width and height is fixed number,  you can place some text in the center of donut pie chart by adding svg elements in `PieChart`.

```jsx
<PieChart width={800} height={400}
   <text x={400} y={200} textAnchor="middle" dominantBaseline="middle">
    Donut
   </text>
   ...
</PieChart>
```

[Here](http://jsfiddle.net/gzzq6jn3/) is a demo.

**Comment by bduff9** [comment]
@xile611 Awesome, thank you so much for the demo.  Unfortunately, the width is not static as I am using responsivecontainer, so I really need cx and cy, like in the custom label function.

**Comment by xile611** [comment]
@bduff9 We'll try to support centered label. But it may take some time. You can try to fix it. Or a workaround is to use a position absolute text.

**Comment by bduff9** [comment]
@xile611  Thank you!  For now, I am fine with my workaround but I appreciate the quick reply

**Comment by xile611** [comment]
New components `Label` and `LabelList` are arrived in version 1.0.0-alpha.0. Centric label can be rendered by the following demo.

```jsx
<Pie>
  <Label value="any text" position="center" />
</Pie>
```

**Comment by qborreda** [comment]
Is there an example of this using the Label component?

**Comment by sppatel** [comment]
What if I want multiple labels inside the pie chart?

For example..

      60%
Completed

**Comment by essaji** [comment]
I tried putting a react component in the `content` property of `Label` but for some reason its not rendering the react component.
e.g. 
```
<Label content={<h4>My label here</h4>} position="center" />
```

but its not working :/ any idea?

**Comment by nivedhithaVenkatachalam** [comment]
@essaji Did you figure out a way to make it work? I am trying to add JSX either to content prop or as children prop (displays as [object Object]) and both does not work.

**Comment by lecerd** [comment]
@essaji, @nivedhithaVenkatachalam: I've hit the same rock, seems that `Label` actually implements `Text` [(link)](https://github.com/recharts/recharts/blob/master/src/component/Text.js) which is basically `<text>` [(link)](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text) so it won't support html elements.

**Comment by Elia-Sh** [comment]
@xile611 ,
Hi I'm utilizing recharts for our new project that includes data visualization, 
and one of the requirements is to present some text in middle of the pie/donut charts - 
![image](https://user-images.githubusercontent.com/4598162/34953334-377f1c06-fa25-11e7-9b97-bac644e125b0.png)

I've noticed that I can use the `<Label >` element to present some text,
but I can't influence on it's position by setting the `position` prop or x/y props, the following failed - 
```
        <PieChart width={200} height={200}>
            <Pie dataKey="value" data={data} innerRadius={60} outerRadius={80} >
                {
                    data.map((entry, index) => <Cell fill={COLORS[index % COLORS.length]} key={entry.name} />)
                }
                <Label value="any text" position="center" />
                <Label value="more text" position="insideBottomRight" />
            </Pie>
            <Tooltip />
        </PieChart>
```

Are there additional options to control the label location or utilizing multiple labels, or even pass some "child" elements to the Pie chart to be presented in the middle that I missed in the documentation?

Thanks.

**Comment by uiruson** [comment]
Any update on supporting multiple labels in center of PieChart?

**Comment by hunhejj** [comment]
Any update?

**Comment by lednhatkhanh** [comment]
Hello, any updates?

**Comment by jarekwg** [comment]
+1
Label appears to work with a plaintext `value`, plaintext `children`, and `content=renderLabel`, where `renderLabel` returns plaintext.
But attempting to return html elements from `renderLabel`, or passing them directly to `content` does nothing..

**Comment by mikiol60** [comment]
@qborreda You got those demos?

**Comment by arthur-machado** [comment]
Any update about this?

I'm trying to put an icon inside my PieChart, but it only works with plaintext. It would be great if the Label component accepts JSX as children

![Captura de tela de 2021-10-06 11-30-38](https://user-images.githubusercontent.com/50958424/136224529-5414c15e-df50-47e8-b562-6fe3e86a3260.png) 

![Captura de tela de 2021-10-06 11-35-11](https://user-images.githubusercontent.com/50958424/136224739-94e65095-d12f-48e6-b6d6-4a59c670d46c.png)

**Comment by LarryKarani** [comment]
any updates

**Comment by hongvantruong** [comment]
I use `<Label>` to add image into svg element 
`<Label content={renderLabel} position="center" />`

```
const renderLabel = (props) => {
        return (
          <g>
            <image href={require("../image.svg").default} width={60} height={60} x={40} y={40} />
          </g>
        );
    };
```

**Comment by martinGM05** [comment]
Someone can do it?, I need to pass a children, this children arrive by props like a JSX element but I can't show it.

**Comment by amarsik1** [comment]
I had the same problem as you, I wanted to have 2 lines in the center of the graph. The only thing that helped me was this:
``` javascript
        <Label
          content={({ viewBox }) => {
            const { cx, cy } = viewBox;
            return (
              <text x={cx} y={cy} textAnchor="middle" dominantBaseline="middle">
                <tspan x={cx} dy="-0.5em">
                 Zone 2
                </tspan>
                <tspan x={cx} dy="1.2em">
                  69%
                </tspan>
              </text>
            );
          }}
          position="center"
        />
```

and it looks like as 

<img width="250" height="162" alt="Image" src="https://github.com/user-attachments/assets/fc9b7653-41a8-4313-820b-60e79183ffcf" />

from what i found, we can't use regular jsx because it all works within the svg framework. so we have to style what we have.

hope this helps someone and saves time

**Comment by ckifer** [comment]
SVG when rendered with React is JSX technically, but yes regular HTML can't be rendered within a recharts surface because it is an SVG. 

The Text component works and so does custom svg text. 

Technically you can use html if you wrap everything within foreignObject but that still requires absolute positioning props.
