### ISSUE TITLE
Change the data source of the chart,XAxis YAxis data name is not redrawn why, help

### ISSUE THREAD

**Issue by BLUE-FAT** [recharts/recharts#1925]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-xn6nd?fontsize=14)

### Steps to reproduce
Click the test button to change the chart data, the chart,XAxis YAxis does not redraw

### What is expected?
Change the data data and redraw the chart

### What is actually happening?
Change data data without redrawing the chart

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 3.1.2 |
| System | window10 |
| Browser | chrome |

**Comment by sherodtaylor** [comment]
This is happening on our application as well

**Comment by sherodtaylor** [comment]
Upgrading to 1.8.5 worked. Your example has 1.8.1 as a dependency.

**Comment by BLUE-FAT** [comment]
work out,very thankful

**Comment by BLUE-FAT** [comment]
@sherodtaylor    work out,very thankful
