### ISSUE TITLE
When use one circle for Radial Bar Chart it feels the entire circle

### ISSUE THREAD

**Issue by t-zander** [recharts/recharts#1930]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/t_Zander/na5j6e0g/2/](https://jsfiddle.net/t_Zander/na5j6e0g/2/)

### Steps to reproduce
Just create a RadialBarChart with a single object in data array.

### What is expected?
It should draw the percentage of the full circle length. We should be able to have a background for the unfilled part of the circle.

### What is actually happening?
It just filling the entire circle. Even when uv is not 100

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.10.2 |
| System | Ubuntu 18.04 |
| Browser | Chrome |

**Comment by antoninklopp** [comment]
Hi @t-zander , 

If I am not mistaking, the radial bar chart is using the biggest value in your data to calculate which bar will be the most filled. 
Since you have only one bar, it will be entirely field.
