### ISSUE TITLE
Composed chart - stacked bars with cell unexpected behaviour

### ISSUE THREAD

**Issue by GergelyMolnar** [recharts/recharts#1932]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/recharts-issue-template-vrzyg?fontsize=14)

### Steps to reproduce
Generate the <Bar.../> series in a for loop with a <Cell.../> wrapped into it.
Apart from the visual proof please, check the console after hovering one bar from the colored stack and compare it with the log after hovering any of the "black" bars. (the id and the fill doesn't show)

### What is expected?
Adding the fill color and the id prop to the Cell within the <Bar../>  would propagate thorugh the whole chart, the color would propagate to the Legend, the relevant id would return hovering any individual bar of any stack.

### What is actually happening?
the very first bar get the fill props and the id, the legend and the rest of the stacks are black, and the bars in the other stack don't return the id.

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | react@16.11.0 |
| System | Linux 5.3.1-1.el7.elrepo.x86_64 #1 SMP Sat Sep 21 09:44:09 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Browser | Google Chrome Version 78.0.3904.87 (Official Build) (64-bit) |

---
I'm trying to highlight the hovered series on the composed chart with a strong color or border, also looking for a way to highlight the name of the series in the tooltip. It is required because we stack sometimes 20  series and the color-shades sometimes too close to identify series only by that.
None of these work out of the box, mainly due to the stacks do not behave as expected. Most solutions work nicely on normal bar charts. The closest solution I found in the issues changes the colour of the complete stack.

**Comment by antoninklopp** [comment]
Hi @GergelyMolnar,

I think that I reproduced what you are trying to achieve here : https://codesandbox.io/s/hardcore-euclid-qq7jg?fontsize=14

You should not pass a list of bars to the Chart component, but directly the children components. And *Barchart* can handle multiple *Bars*, so I think that it is better to use directly this one.

**Comment by GergelyMolnar** [comment]
Hi @antoninklopp,

Thanks for the response. I don't think you reproduced what I actually trying to achieve. You actually just removed all the functionality I need: 
- get back some sort of "ID" of the hovered sub-bar of a stack of one data series (stack = eg. 'Page A' in your example) - so if you hover over over eg. a green part of a stack it would return which data-series the cursor is above. This is actually done in my "broken" solution but it works only in the first stack and doesn't propagate to the rest of the stacks - that is achieved by introducing the Cell child component to each series wich then would have the fill prop for that series. 
- afterwards having the "ID" of the hovered series I need to highlight (somehow) the relevant tooltip line for the identified/hovered series or show only that one optionally

These are important because our data can be dauntingly rich and having up to ~130 data-series on a stacked bar chart is confusing and the tooltip easily grows over the chart height (it actually does even with having ~20 data-series cutting-off the bottom part of the tooltip). The analyst will look for extremes where the data is larger than others on a stack and they need to identify the data source by just hovering over that part of a stack.

To demonstrate it with examples: by adding the cell to the data-series generator function like this:`... <Cell id={"cell_" + i + "_" + dKey} fill={color} /> ...`

will produce the "broken" chart where
![image](https://user-images.githubusercontent.com/16977780/68585608-9de87580-047a-11ea-8293-5e6050496c6f.png)

- if you hover over the first (colored) stack you will get back the object as: 
``` 
Object {name: "Page A", uv: 4000, pv: 2400, amt: 2400, x: 87…}
name: "Page A"
uv: 4000
pv: 2400
amt: 2400
x: 87
y: 186.5
width: 56
height: 60.5
value: Array[2]
payload: Object
background: Object
id: "cell_0_uv"
fill: "#b16b25"
```
let me emphasize the two fields at the bottom of it: `id: "cell_0_uv"`
`fill: "#b16b25"`
- but hovering above any other (black/uncolored) stack the returned bject has no `id` of `fill` fields
```
Object {name: "Page B", uv: 3000, pv: 1398, amt: 2210, x: 157…}
name: "Page B"
uv: 3000
pv: 1398
amt: 2210
x: 157
y: 147.054
width: 56
height: 33.42625000000001
value: Array[2]
payload: Object
background: Object
```

I hope this clarifies what I'm trying to achieve.

**Comment by antoninklopp** [comment]
Hi @GergelyMolnar , 

Is [this] (https://codesandbox.io/s/hardcore-dijkstra-rmqhv?fontsize=14), more like you are trying to achieve?

**Comment by antoninklopp** [comment]
@GergelyMolnar Happy it helped, 
Don't hesitate to close the issue if it solved your problem !
