### ISSUE TITLE
Draw vertical lines on referenceLine

### ISSUE THREAD

**Issue by kasturisameer** [recharts/recharts#1933]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

Is it possible to draw a vertical line on a **ReferenceLine**? 

### Sample image
![image](https://user-images.githubusercontent.com/36661062/68337353-4c508b80-0106-11ea-9da1-e1380f6046e6.png)

Any way to achieve this with any **recharts** component?

**Comment by dkloke** [comment]
You can use the `label` property to draw another line.

```
const AnotherLine = props => {
  const {viewBox: {x, y}, xoffset, yheight} = props;
  // console.log("ANOTHER LINE",props)
  return <line x1={x +xoffset} x2={x + xoffset} y1={y - yheight/2} y2={y + yheight/2} {...props}  />;
};
...
     <ComposedChart
        id="masterChart"
      />
          <ReferenceLine
            label={<AnotherLine
              xoffset={100}
              yheight={10}
              stroke={"red"}
              strokeWidth={5}
              strokeOpacity={.5}
            />}
            y={10}
            // label={<Label textLength={60} value={title}  offset={0} position="insideTop" />}
            stroke={"green"} strokeWidth={2} strokeOpacity={.5}
          />
```
The xoffset is in pixels, you will have to calculate a Yaxis position by hand, this can be done my managing Yaxis ticks and getting the live chart width. The following function may come in handy, note the ` id="masterChart"` property applied above. Recharts will use the id to create a `clipPath` `defs` element.
```
const hotChartWidth = () => {
  const peg = document.querySelector("#masterChart-clip");
  if(peg && peg.firstElementChild)
    return peg.firstElementChild.width.baseVal.value;
  return 0;
};
```
