### ISSUE TITLE
Have a bold line indicating a "limit" in CartesianGrid

### ISSUE THREAD

**Issue by nijona** [recharts/recharts#1934]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to have a bar chart with a bold line in the CartesianGrid indicating a limit of 90%, so I can easily see which bar is above that limit, Is there any option available?

### What does the proposed API look like?
 `<CartesianGrid limitLine="90%" />`

![image](https://user-images.githubusercontent.com/44019432/68367298-0fa08680-013e-11ea-8ff0-296bbb80a681.png)

**Comment by antoninklopp** [comment]
Hi @nijona, 

I think that this a thing that you can easily achieve with a [ReferenceLine](http://recharts.org/en-US/examples/LineChartWithReferenceLines).

**Comment by nijona** [comment]
@antoninklopp Thanks!
