### ISSUE TITLE
use Popper.js (well, technically Tooltip.js) for Tooltips

### ISSUE THREAD

**Issue by dimitropoulos** [recharts/recharts#1935]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Popper.js is a small (~6kb) library that offers a powerful, customizable positioning engine and operates at blazing speed (~60fps).

There are many edge case issues with the Tooltip Component (i.e. positioning, styling, the current lack of using portals) that are out of scope for a project like recharts, but are categorically solved by Popper.js, a battle tested library that many other popular libraries (e.g. [material-ui](https://material-ui.com/api/popper/), and [blueprint.js](https://blueprintjs.com/docs/#core/components/popover.closing-on-click)) are utilizing.

### What does the proposed API look like?
I am opening this issue to gauge interest in using Popper.js before spending additional time drafting an API.

**Comment by xile611** [comment]
Thanks! The tooltip of chart maybe very different from Popper.js.
Maybe you can help to solve the cases of Tooltip.

**Comment by dimitropoulos** [comment]
Can you say a little more about what's different such that Popper.js wouldn't be an improvement?

**Comment by CyrilQuandalle** [comment]
Hello,
Any update on this ?

**Comment by CyrilQuandalle** [comment]
Ok I understand.
Thank you very much for your quick answer @ckifer
