### ISSUE TITLE
How to make X-axis tick adaptive arrangement while changing tick font size？

### ISSUE THREAD

**Issue by Yuuzelin** [recharts/recharts#1939]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-zo5yp?fontsize=14)

### Steps to reproduce
Run code to find bugs.

### What is expected?
Making X-axis tick adaptive arrangement while changing tick font size.

### What is actually happening?
X-axis tick is not adaptive arrangement while changing tick font size.

| Environment | Info |
|---|---|
| Recharts | 1.8.5 |
| React | react16.8.3 |
| System | mac |
| Browser | chrome |

**Comment by antoninklopp** [comment]
Hi @Yuuzelin , 

I don't know if the text arrangement is something that this library wants to handle since it can be quite a complicated problem.
You could customize your XAxis tick props like this
https://codesandbox.io/s/recharts-issue-template-6umdi?fontsize=14
