### ISSUE TITLE
Yaxis units is not given in CustomTooltip

### ISSUE THREAD

**Issue by cedeber** [recharts/recharts#1940]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/jgv2bLxm/](https://jsfiddle.net/jgv2bLxm/)

### Steps to reproduce
Look at the example, It sets "undefined" for unit.

### What is expected?
Show the unit sets in the Yaxis for the Tooltip.

### What is actually happening?
Look at the example, It sets "undefined" for unit.

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.11.0 |
| System | ubuntu 19.10 |
| Browser | Chromium 78 |

**Comment by xile611** [comment]
Please add the `unit` to <Bar /> to fix this.


![image](https://user-images.githubusercontent.com/6111424/76737866-80b71100-67a4-11ea-862d-72707f1b1fae.png)
