### ISSUE TITLE
Images as ticks, but not based on "dataKey"

### ISSUE THREAD

**Issue by jivanmukti** [recharts/recharts#1941]
Is there any way to use images as ticks in place of numbers? For example if I have a bar chart where the y-axis is a subject such as math or English, and the x-axis is the score which ranges from 0,5 and with ticks of [0, 1, 2, 3, 4, 5], is it possible to have an image replace the numbers? 

For example instead of having the numbers 1,2,3,4,5, can we have a pictures of 1 banana, 2 bananas, 3 bananas, 4 bananas, 5 bananas?

**Comment by antoninklopp** [comment]
Hi @jivanmukti , 

As recharts is fully customizable, you can customize the axis ticks like [this](http://recharts.org/en-US/examples/CustomizedLabelLineChart)

**Comment by jivanmukti** [comment]
@antoninklopp I've seen that example but that's not what I'm referring because in the example, each page has a data point. My data set looks like this:

`data = [
    { name: "History", score: 5 },
    { name: "Math", score: 1 },
    { name: "Chemistry", score: 2 },
    { name: "Physics", score: 4 }
  ] `

I want the Y-axis ticks to be the subject names and the X-axis ticks to be 0,1,2,3,4,5 represented by images. All of the examples in recharts , including the example you linked, reference a a dataKey. I don't want to reference a dataKey, but instead replace the 0,1,2,3,4,5 ticks with images.

**Comment by antoninklopp** [comment]
@jivanmukti , I see your point, you can simply invert your data and customize the X axis tick

**Comment by jivanmukti** [comment]
@antoninklopp I don't get what you mean by inverting data, can you show me an example?

**Comment by luc-tuyishime** [comment]
> @antoninklopp I don't get what you mean by inverting data, can you show me an example?

Have you been able to do that.
