### ISSUE TITLE
Brush Component varies number of data points shown on x-axis when moving horizontally

### ISSUE THREAD

**Issue by patrickdemers6** [recharts/recharts#1942]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-k2xqp)

### Steps to reproduce
1. Shrink the Brush to less than 75%.
2. Slowly move the Brush horizontally.
3. While moving horizontally observe the number of x-axis data points varies.

### What is expected?
While scrolling horizontally using the brush, the number of data points shown on x-axis should stay consistent throughout the scroll action.

### What is actually happening?
While scrolling horizontally using the brush, the number of data points shown on x-axis varies.

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | react v16.11.0 |
| System | Windows 10 OS Version 1803 (Build 17134.1069) |
| Browser | 78.0.3904.70 (Official Build) (32-bit) (cohort: Stable) |

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
