### ISSUE TITLE
Composed Chart with X and Y Axis does not display on Safari/Firefox

### ISSUE THREAD

**Issue by mcdappdev** [recharts/recharts#1943]
- [X] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-gwpov)

### Steps to reproduce
Open the provided link inside of Chrome. Then, open it inside of Safari/Firefox to see it not appear. 

### What is expected?
The graph should show in both browser.

### What is actually happening?
The graph is only showing in Chrome. 

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.9.0 (React) |
| System | MacOS |
| Browser | Safari/Firefox |

---
For some reason this code is working fine on the playground but my local project (which uses the same code) produces the wrong code. When I use Safari it is just a blank graph and it seems like it is not rendering all of the SVG elements to actually display. Works fine in Chrome   Brave but not in Safari/Firefox. I apologize for not getting it to reproduce in the sandbox, but it's the exact same code that I use locally and I can't get it to work.

**Comment by xile611** [comment]
Sorry！ I Can't reproduce this issue both in my local code and your demo. You can create a new issue if more information can be provided.
