### ISSUE TITLE
Bar/Line onClick does not pass original click event (and useful info like shiftKey/ctrlKey)

### ISSUE THREAD

**Issue by damianobarbati** [recharts/recharts#1946]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have a bar chart where users can click on single bars to open the bar specific insights.
Users would like to click on the bar and open the page in new tab if ctrl/cmd is pressed (common behaviour in the browser) but I can't detect the shift/ctrl/command without the original click event.

### What does the proposed API look like?
Pass a third argument to the handler:

handleClick(data, index, originalEvent) {}

**Comment by Harukisatoh** [comment]
For future readers, although this issue has no answers, it seems that this feature has already been implemented

**Comment by igorgarbuz** [comment]
Can observe the same issue, `event` passed to `Bar`'s `onClick` is not a standard event in the version `2.1.9`

**Comment by ckifer** [comment]
Closing this as resolved as you can access `(data, index, originalEvent)` on singular bars as per the latest recharts and before. Track the above linked issue https://github.com/recharts/recharts/issues/2674 for typescript issues with these events.
