### ISSUE TITLE
Is there a way to set BACKGROUND COLOR on XAxis.

### ISSUE THREAD

**Issue by reni11111** [recharts/recharts#1956]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In my UX design, the XAXIS are needed with background WHITE (not transparent like default),
I checked the docs and all I could find was to set a stroke but I need the whole xAxis background and not font color.
Would appreciate any workaround :)

**Comment by reni1111** [comment]
Still not solved, so let's close it
