### ISSUE TITLE
Bar onClick does not work when bar is empty

### ISSUE THREAD

**Issue by damianobarbati** [recharts/recharts#1957]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/5sezmL8b/](https://jsfiddle.net/5sezmL8b/)

### Steps to reproduce
- open https://jsfiddle.net/5sezmL8b/
- click on the middle bar (empty), alert does not fire

### What is expected?
Alert should fire with associated payload, undefined if none

### What is actually happening?
Click does not trigger alert

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | latest |
| System | macos |
| Browser | chrome |

**Comment by matthewkwong2** [comment]
Not a bug, the click event only fires if you clicked the actual bar (coloured in green in your example) instead of the highlight (coloured in grey in your example). This also applies to the right bar in your example.

**Comment by damianobarbati** [comment]
@matthewkwong2 I see now. Any workaround for this? How can I detect a click on it without the bar onclick?

**Comment by DawidWetzler** [comment]
Any updates on this?

**Comment by Angusross111** [comment]
Move the onclick function into the <BarChart> section
https://jsfiddle.net/trw4bgmc/
