### ISSUE TITLE
`rank` for a TreeMap is not implemented

### ISSUE THREAD

**Issue by philip-peterson** [recharts/recharts#1958]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The DemoTreemapItem source code [here](https://github.com/recharts/recharts/blob/master/demo/component/DemoTreemapItem.js#L26) would seem to imply that the property `rank` exists for a TreeMap content. Unfortunately it does not, though `depth` is (in `computeNode`), so this seems like it may be a simple fix.

### What does the proposed API look like?
Providing `rank` as an additional prop on the return value of `Treemap::computeNode`.

**Comment by xile611** [comment]
@philip-peterson It may be a outdated demo.
