### ISSUE TITLE
 Getting this error in console: Prop `id` did not match

### ISSUE THREAD

**Issue by nguyenhai31096** [recharts/recharts#1959]
Getting this error in console.
Warning: Prop `id` did not match. Server: "recharts25-clip" Client: "recharts1-clip"

**Comment by pixelass** [comment]
why was this closed without response?

**Comment by nguyenhai31096** [comment]
> why was this closed without response?

i don't know @pixelass , it's still happen with me

**Comment by pixelass** [comment]
@xile611 why was this closed without a response?

**Comment by ke1vin1993** [comment]
@pixelass @nguyenhai31096 Adding an unique `id` prop did solve my problem, that warning doesn't show anymore.

**Comment by bel7aG** [comment]
Hey, **_skip the first render_** in your chart component:
```


const [ready, setReady] = useState<null | true>(null)

useEffect(() => {
  setReady(true)
}, [])

return ready && (..."your chart JSX");
```

**Comment by xargr** [comment]
try to add prop `instanceId` set as unique string and should work
