### ISSUE TITLE
How LineChart width set 100%

### ISSUE THREAD

**Issue by gischina** [recharts/recharts#196]
How LineChart width set 100%

**Comment by xile611** [comment]
@gischina You can use [ResponsiveContainer](http://recharts.org/api#ResponsiveContainer) to set the width of LineChart to be `100%`.

**Comment by godmar** [comment]
How about for BarChart?
I'm using

```
<ResponsiveContainer height='100%' width='100%'>
              <BarChart data={data} 
                margin={{top: 5, right: 30, left: 20, bottom: 5}}>
                <XAxis dataKey="description"/>
                <CartesianGrid strokeDasharray="3 3"/>
                <Tooltip/>
                <Legend />
                <Bar dataKey="votecount" fill="#82ca9d" />
              </BarChart>
           </ResponsiveContainer>
```

and the chart does not show.
Error:

```
LogUtils.js:23 The width(521) and height(0) of chart should be greater than 0,
       please check the style of container, or the props width(100%) and height(100%),
       or add a minWidth(undefined) or minHeight(undefined) or use aspect(undefined) to control the
       height and width.
```

**Comment by xile611** [comment]
@godmar When you use `ResponsiveContianer`, we'll try to calculate the width and height of ResponsiveContainer's parent node. But If the height of parent node is 0, we don't know how to calculate the height of `ResponsiveContainer`.  We have many discussion in #135 .  Maybe you can set a `minHeight` to `ResponsiveContainer`.

**Comment by godmar** [comment]
This worked for me:

```
<ResponsiveContainer width='100%' aspect={4.0/3.0}>
...
</ResponsiveContainer>
```

presumably because it forces a height based on width.

**Comment by NeverSlowDown** [comment]
@xile611  setting min-height to `ResponsiveContainer` worked perfect to me.
also @godmar solution works great

**Comment by NMRayhan** [comment]
i'm using Div with 100% width and height wrap with rechart Example
it's work perfect for me
 `<div className="container" style={{width:"100%", height:"400px"}}>`
`<LineChart
          width={1300}
          height={300}
          data={data}
          margin={{ top: 5, right: 20, bottom: 5, left: 0 }}
        >
          <Line type="monotone" dataKey="Profit" stroke="#8884d8" />
          <Line type="monotone" dataKey="sellingPrice" stroke="#82ca9d" />
          <CartesianGrid stroke="#ccc" strokeDasharray="5 5" />
          <XAxis dataKey="name" />
          <YAxis />
          <Tooltip />
          <Legend />
        </LineChart>`
`</div>`

**Comment by MuhammadBurhanHaseeb** [comment]
in my case chart not work 

<img width="927" height="191" alt="Image" src="https://github.com/user-attachments/assets/5247ae9e-81ca-4a40-865f-8af15f72a907" />

**Comment by ckifer** [comment]
Looks like it's working
