### ISSUE TITLE
Order of items / Order of properties

### ISSUE THREAD

**Issue by pixel-shock** [recharts/recharts#1962]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://recharts.org/en-US/api/BarChart](http://recharts.org/en-US/api/BarChart)

### Steps to reproduce
Just generate a Chart

### What is expected?
The order of objects within the data array items should be exactly the same as in the input object

### What is actually happening?
The order of objects within a data set is not guaranteed through all browsers.

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.10.2 |
| System | All |
| Browser | All |

---
I think to guarantee that the input order of object keys is the same like the displayed output the data format has to be changed from:

```
{
	"name": "Page A",
	"uv": 4000,
	"pv": 2400,
	"amt": 2400
}
```
to
```
{
	"name": "Page A",
	"values": [
		{
			"name": "uv",
			"value": 4000
		},
		{
			"name": "pv",
			"value": 2400
		},
		{
			"name": "amt",
			"value": 2400
		}
	]
}
```

**Comment by antoninklopp** [comment]
Hi @pixel-shock , 

The order of the data only depends on the order you choose to display it with the charts components (<Line />, <Bar/>, ...). It seems like a normal behavior.

**Comment by pixel-shock** [comment]
Hi,

I would say "OK" normally, but I have a setup with NextJS and SSR and the order of the displayed date is not the same on all machines ... the NodeJS versions and all config files are the same across all machines, but not the data display :-/

Maybe you have another suggestion what causes the problem?

Cheers
Tino

**Comment by antoninklopp** [comment]
I actually have no idea. 
You mean that on some machines the 'uv' and 'pv' bars (from the doc example you linked) are not in the same order ?

**Comment by pixel-shock** [comment]
Hi,

ok, let's take a look at your API example in your docs: http://recharts.org/en-US/api/BarChart

The data is ordered like "name, uv, pv, amt" but the chart show the data in the order "pv, uv" ... you know what I mean?

**Comment by antoninklopp** [comment]
Yes of course, if you look carefully at the code, 

``` js
<BarChart width={730} height={250} data={data}>
  <CartesianGrid strokeDasharray="3 3" />
  <XAxis dataKey="name" />
  <YAxis />
  <Tooltip />
  <Legend />
  <Bar dataKey="pv" fill="#8884d8" /> /*first pv*/
  <Bar dataKey="uv" fill="#82ca9d" /> /*second uv*/
</BarChart>
```

The order of the data does not matter, the only thing that matters is the order of your components as I stated above :)

**Comment by pixel-shock** [comment]
Ah sorry, my fault ... OK, then everything looks OK ... but it's still strange in my setup. ;-)
I'm getting my data as JSON and just iterating over the JSON data and render the Bar Element ... but maybe I should implement an "order" prop into my data and order it somehow .... really strange. 

But thank you for your fast reply :-) 👍

**Comment by antoninklopp** [comment]
I think you should just input the data, the way it is shown in the documentation and everything will be fine 😄 

If you are satisfied with the answer please close th issue afterwards 😄

**Comment by pixel-shock** [comment]
I can't do it hardcoded ... but anyways ... I'll find a solution ;)
