### ISSUE TITLE
Unable to click due to Overlapping scatter dots with multiple scatter charts 

### ISSUE THREAD

**Issue by disha31-thaker** [recharts/recharts#1963]
[-](url) [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and  @believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/zhkfg6qn/](https://jsfiddle.net/zhkfg6qn/)

### Steps to reproduce
<this.state.Recharts.ScatterChart
                                      width={500}
                                      height={600}
                                    >
                                      <this.state.Recharts.XAxis
                                        dataKey='date'
                                        type='number'
                                        domain={[contentVengageDetail.contentVengageData.intervalDates[0], contentVengageDetail.contentVengageData.intervalDates[contentVengageDetail.contentVengageData.intervalDates.length - 1]
                                        ]}
                                      />
                                      <this.state.Recharts.YAxis
                                        dataKey='hour'
                                        name='Hour'
                                        orientation='right'
                                        yAxisId='right'
                                        />
                                      <this.state.Recharts.ZAxis
                                        zAxisId='rightz'
                                        type='number'
                                        dataKey='count'
                                        range={[40, 2500]}
                                      />
                                      <this.state.Recharts.Scatter
                                        data={emailData}
                                        name='email'
                                        fill={'red'}
                                        yAxisId='right'
                                        zAxisId='rightz'
                                        onClick={this.clickDot.bind(this)}
                                      />
                                      <this.state.Recharts.Scatter
                                        data={postData}
                                        name='post'
                                        fill={'green'}
                                        yAxisId='right'
                                        zAxisId='rightz'
                                        onClick={this.clickDot.bind(this)}
                                      />
                                    </this.state.Recharts.ScatterChart>

### What is expected?
I want to click on every scatter chart and fetch its value.

### What is actually happening?
two scatter chart (email and post) will be increased the dots by its value (because I gave z-index), at some point email or post have big value then its dots will increase and it will cover all other dots which is on the same place and due to this I am unable to click on other dots.

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.1 |
| React | 15 |
| System | 10.11.6 |
| Browser | chrome 78.0.3904.108 |

**Comment by antoninklopp** [comment]
Hi @disha31-thaker , 

I don't really understand your issue, is your problem with the onClick method?

**Comment by disha31-thaker** [comment]
One big dot will cover other small dots which have the same coordinates and if I want to click on that small dots I am not able to click on that

**Comment by antoninklopp** [comment]
Yes but this seems normal, what other behavior would you expect?

**Comment by timtucker-dte** [comment]
The ordering for SVG elements is based on the order in which they're defined, not zindex.

In the case of the JSFiddle you included, if you swap the order of the <Scatter> plots, you'll see the tooltip for the smaller value in the center and the larger value when you hover over the surrounding area for the larger value.

**Comment by disha31-thaker** [comment]
yes,  The value which is coming is from API so I have changed the order of the value ( bigger count came first and then smaller ) so that I can click on all the dots. it solves my issue. here is the example.

 { 
                         "date":1574899200,
                         "hour":7,
                         "post_identity":"123",
                         "count":1
                      },
                      { 
                         "date":1574899200,
                         "hour":7,
                         "post_identity":"234",
                         "count":0
                      },
