### ISSUE TITLE
YAxis Label not apply transform for `angle` property

### ISSUE THREAD

**Issue by ilsanchez** [recharts/recharts#1964]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/distracted-waterfall-kkx8w)

### Steps to reproduce
Run the example with recharts@1.8.5 and @2.0.0-beta.1

### What is expected?
YAxis label appear rotated when `angle` property is set

### What is actually happening?
`angle`  property is ignored and label appear without transformation

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.1 |
| React | react@16.12.0 |
| System | Ubuntu 16.04 |
| Browser | Chromium  78.0.3904.108 |

**Comment by 8enSmith** [comment]
I too am encountering this issue, same versions, though I'm using Windows 10.

**Comment by antoninklopp** [comment]
Hi @ilsanchez , 

I think that this is indeed a problem from 2.0.0 (still in beta version). If you use the 1.8.5 version, the angle property is used.

**Comment by chrisgzf** [comment]
encountered this exact issue as well on `2.0.0-beta1`. fixed it by reverting recharts back to `1.8.5`

**Comment by navarro-david** [comment]
I found a workaround that does work in `v2.0.0-beta.1`

Pass in a `Text` component with the angle prop
```
<YAxis
padding={{ top: 12 }}
type='number'
domain={[0, "dataMax + 2"]}
yAxisId='hours'
orientation='left'
label={
   <Text
      x={0}
      y={0}
      dx={50}
      dy={150}
      offset={0}
      angle={-90}
   >Hours</Text>
} />
```

**Comment by danielo515** [comment]
Not yet published I guess

**Comment by tanmaybhatt** [comment]
> I found a workaround that does work in `v2.0.0-beta.1`
> 
> Pass in a `Text` component with the angle prop
> 
> ```
> <YAxis
> padding={{ top: 12 }}
> type='number'
> domain={[0, "dataMax + 2"]}
> yAxisId='hours'
> orientation='left'
> label={
>    <Text
>       x={0}
>       y={0}
>       dx={50}
>       dy={150}
>       offset={0}
>       angle={-90}
>    >Hours</Text>
> } />
> ```
Can you think of a way to make this work with orientation='right'?

**Comment by armcknight** [comment]
Updating my `package.json` to use `2.0.0-beta.2` fixed this for me, just released 13 hours ago. Thanks for shipping it!
