### ISSUE TITLE
Sankey Chart Documentation

### ISSUE THREAD

**Issue by fanny** [recharts/recharts#1966]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I need to use the Sankey Chart, but i didn't find the documentation, although there is a demo and the component on the repo

### What does the proposed API look like?
Makes available the demo and how i can use the component

**Comment by hknowlton** [comment]
Maybe you can use this from the source code? I had to reference for another component 
 https://github.com/recharts/recharts/blob/db0f3f254f12d59583052e77a43822163c476c9f/demo/component/Sankey.js

**Comment by fanny** [comment]
Yes, i saw this demo, thanks. But i think that the doc helps more, i can open a pr with the doc, in case of you guys, have interest.

Btw, I can't make this sankey chart, responsive, even adding the `ResponsiveContainer`. Do you know the reason?

**Comment by fanny** [comment]
Hi all, i init the doc here https://github.com/recharts/recharts.org/pull/106
