### ISSUE TITLE
XAxis label cut if the width is not long enough 

### ISSUE THREAD

**Issue by urielz1987** [recharts/recharts#1967]
I found that the the rechart LineChart cut some `XAxis` labels if there is no enough space for them, so I rotated it by -90 degree  - `<XAxis dataKey="name" angle={-90} /> ` and now I want to se all the labels without missing any. 

How could I force the LineChart to draw all the XAxis labels ?  
Here is an example - I want to see in it all the labels from Page A to Page Q
https://jsfiddle.net/rv9wfnpb/2/

Version: 1.7.1

**Comment by antoninklopp** [comment]
Hi @urielz1987 , 

You can do it by changing the interval parameter from the Xaxis component like [this](https://jsfiddle.net/fvnh1q5c/11/): 

``` js
<XAxis dataKey="name" height={60} angle={-90} interval={0}/>
```

**Comment by duongsieu** [comment]
How can my text automatically go to the next line if it's too long ?

**Comment by akashshyamdev** [comment]
@duongsieu do you know how we can prevent that? I don't want my labels to break, they should be displayed fully on a single line.

**Comment by tran-simon** [comment]
I set `overflow: 'visible'` to the chart component and the labels are fully visible:

```
<BarChart
  {...{
     overflow: 'visible'
   }}
>
```

(I used the spread syntax, because else typescript would complain that the overflow prop does not exist)

**Comment by Arhamalii** [comment]
> I set `overflow: 'visible'` to the chart component and the labels are fully visible:
> 
> ```
> <BarChart
>   {...{
>      overflow: 'visible'
>    }}
> >
> ```
> 
> (I used the spread syntax, because else typescript would complain that the overflow prop does not exist)




perfectly worked thanks !
