### ISSUE TITLE
Missing “typings” entry in package.json

### ISSUE THREAD

**Issue by sveyret** [recharts/recharts#1969]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The typings for recharts actually lies in DefinitlyTyped. As you are now using TypeScript, it would be a good idea to add the generated type files (.d.ts) to the delivered files, and add an entry in the package.json. The typings would then always be up-to-date and could be removed from DefinitlyTyped.

### What does the proposed API look like?
package.json
```
…
  "main": "lib/index",
  "module": "es6/index",
  "jsnext:main": "es6/index",
  "typings": "types/index.d.ts",
  "sideEffects": [
    "./*/index.js",
    "./*/polyfill.js"
  ],
…
```

**Comment by JohnForster** [comment]
Especially important as the DefinitelyTyped entry for recharts is missing a lot of info. Trying to create a radial bar chart in typescript is almost impossible.

**Comment by hinsxd** [comment]
Noticing that Recharts has been rewritten in TS in v2.0beta, but cant find a declaration file. This confuses me very much. How can I use the official typings?

**Comment by xile611** [comment]
Please try the latest version 2.0.0-beta.4
Anyway, PR is welcome! We need more contributors.
