### ISSUE TITLE
Cannot use css-in-js approach to customize components

### ISSUE THREAD

**Issue by wrangler53** [recharts/recharts#1971]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tender-waterfall-0n5xb)

### Steps to reproduce
I am using styled-components library v4.4.1 and trying to set my own styles for `recharts` components.
As can be seen in provided link, it is impossible to customize CartesianGrid and all other components (Line, XAxis, YAxis etc.) using CSS-in-JS approach

### What is expected?
Component should be customized (red color should be applied to vertical lines in grid)

### What is actually happening?
Styles to the component are not applied

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.11.0 |
| System | MacOS |
| Browser | Chrome 78.0.0 |

**Comment by Ab-hay** [comment]
use stroke to change colors:
        <XAxis dataKey="name" stroke="#000000"/>
        <YAxis stroke="#000000" />

**Comment by rnarcos** [comment]
Same issue on #2694.
