### ISSUE TITLE
Support for IE 11

### ISSUE THREAD

**Issue by raRaRa** [recharts/recharts#1974]
I noticed that users using IE 11 are getting an error where `.includes` isn't supported. Should be fairly easy to fix. I know it's ridiculous that people are still using IE 11, so I wouldn't be surprised if this issue gets closed without a fix.

```
Error: TypeError: Object doesn't support property or method 'includes' in AreaChart
```

**Comment by timtucker-dte** [comment]
Is this something that would get fixed within the project, or is it just a matter of including polyfills if you need to support IE11?

**Comment by raRaRa** [comment]
I solved the issue from my end by adding a polyfill for `includes`, I guess others can do the same if they want to support IE 11. I use https://polyfill.io/ - highly recommended.
