### ISSUE TITLE
Barchart first bar overflows in y axis.

### ISSUE THREAD

**Issue by totraku** [recharts/recharts#1975]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-95uhh)

### Steps to reproduce
Just look at the rendering on codesandbox

### What is expected?
The expected behaviour would be to have bars which stay inside the Chart and the y-axis scale to include the domain of the highest bar.

### What is actually happening?
In the example in codesandbox there is the first bar with the count of 26 while the scale goes up to 8.

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.1 |
| React | React 16.12.0 |
| System | macOS Catalina 10.15.1 |
| Browser | Chrome Version 79.0.3945.79 (Official Build) (64-bit) |

**Comment by G07cha** [comment]
I had the same, and I've fixed it by manually calculating domain for YAxis.

**Comment by matthewkwong2** [comment]
That because your data are strings instead of numbers.

Original data:
```js
[
  { key: "1", region: "Süd", count_tp: "26" },
  { key: "2", region: "Südwest", count_tp: "5" },
  { key: "3", region: null, count_tp: "6" },
  { key: "4", region: "Nord", count_tp: "5" },
  { key: "5", region: "West", count_tp: "34" },
  { key: "6", region: "Ost", count_tp: "2" }
]
```

What the data should be looked like:
```js
[
  { key: "1", region: "Süd", count_tp: 26 },
  { key: "2", region: "Südwest", count_tp: 5 },
  { key: "3", region: null, count_tp: 6 },
  { key: "4", region: "Nord", count_tp: 5 },
  { key: "5", region: "West", count_tp: 34 },
  { key: "6", region: "Ost", count_tp: 2 }
]
```
