### ISSUE TITLE
How to pass an array of data as datakey

### ISSUE THREAD

**Issue by Atiqullah-Naemi** [recharts/recharts#1976]
I am using Recharts with React and want to pass an array of numbers as datakey but it doesn't work. My data looks like below:

`const data = [
  {
    "name": "Retail",
    "growth": [4000, 3000, 6237, 9383, 3638, 6363],
    "sale": [5252, 6363, 7363, 6363],
     "performance: 7262
  },
  {
   "name": "Fashion",
    "growth": [8589, 52563, 8484, 5252, 9725],
    "sale": [6262, 5363, 7363, 5252],
    "performance: 5252
  },
  {
    "name": "Energy",
    "growth": [3141, 3000, 6237, 5622, 3242, 6363],
    "sale": [5252, 6363, 7363, 6363],
     "performance: 3246
  },
  {
    "name": "Water",
    "growth": [7373, 6363, 9737, 5262, 3638, 6363],
    "sale": [8282, 4252, 7373, 8373],
     "performance: 9385
  }
]`

and my chart looks like below:

`<LineChart width={730} height={250} data={data}>
  <XAxis dataKey="name" />
  <YAxis />
  <Line type="monotone" dataKey="growth" stroke="#8884d8" />
</LineChart>`

but when I pass performance as datakey it works
`<Line type="monotone" dataKey="growth" stroke="#8884d8" />`

I want to pass an array as datakey, is there any option? any help please?

**Comment by G07cha** [comment]
You can transform and pass data directly to line like in [this example](http://recharts.org/en-US/examples/LineChartHasMultiSeries) but I'm not sure how it would reflect on XAxis.

**Comment by jonatan-toba** [comment]
missing double quote. instead of ` "performance: 9385` ->  "performance": 9385
