### ISSUE TITLE
BarChart Bar labels + Brush = label display problems

### ISSUE THREAD

**Issue by gnieutin** [recharts/recharts#1977]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
When playing with the brush in a BarChart, the Bar labels are sometimes displayed, sometimes not. Most of the time, the last 2 bar displayed have a label and others don't.

Here is a demo https://jsfiddle.net/jq6yvphz/ which is based on your doc "BrushBarChart" example (https://jsfiddle.net/alidingling/mc8r7e6p/)
Step to reproduce in my demo:
1. reduce endIndex of brush by moving it toward the start of the brush
2. increase endIndex of brush by moving it toward the end of the brush
=> you ll see that only the last 2 bars shows a label

## What is the expected behavior?
All bars should display their label, the same way it is working without brush.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
* Does not work neither in 1.7.1 nor in 2.0.0-beta.1
* Does not work on Firefox and Chrome

**Comment by gnieutin** [comment]
Any reason for this ticket to be closed ? Already fixed ? Won't fix ? Duplicated ?

**Comment by maykl4iv** [comment]
What is the status of the issue?

**Comment by ckifer** [comment]
Hey @maykl4iv 

I'm not sure the status of this issue and not sure why it's closed but if you can reproduce it in a codesandbox I will re-open
