### ISSUE TITLE
Recharts 2.0 is using not supported core-js 2.6.10. Migration to core-js 3.x

### ISSUE THREAD

**Issue by flesicek** [recharts/recharts#1978]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently recharts 2.0 is still using "core-js": "^2.6.10" but core-js 2.x is not supported anymore.
Is it possible to migrate to core-js 3.x?

### What does the proposed API look like?
There will not be any API change

**Comment by G07cha** [comment]
Duplicates https://github.com/recharts/recharts/issues/1673 and I've fixed it already in https://github.com/recharts/recharts/pull/1954 😉

**Comment by avindra** [comment]
Yep this is fixed and released in the beta. I had a local patch for this problem which I was able to remove after upgrading recharts to the 2.x beta.
