### ISSUE TITLE
syncId keys off of data index, not data value

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#1980]
- [X] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://recharts.org/en-US/examples/SynchronizedLineChart](http://recharts.org/en-US/examples/SynchronizedLineChart)

### Steps to reproduce
In the existing synchronized chart example, copy the data array to data2, and use data2 for the area chart. Remove a few of the items in data2.

### What is expected?
The synchronized chart position should be based on the value of the X-axis, not the data item index.

### What is actually happening?
The synchronized chart position is based on the data item index.

| Environment | Info |
|---|---|
| Recharts | v1.6.2 |
| React | 16.0.0 |
| System | All |
| Browser | All |

---
I don't think this is a new bug. It's likely been there for some time, but I just recently discovered it, by synchronizing two charts that didn't have the same X-axis starting value (i.e. one chart had fewer items than the other).

**Comment by sseira** [comment]
Yeah this would be extremely helpful

**Comment by sseira** [comment]
So I wrote this edit that sets the sync to be value instead of by index

`_this.handleReceiveSyncEvent = function (cId, chartId, data) {
        var _this$props = _this.props,
            syncId = _this$props.syncId,
            layout = _this$props.layout;
        var updateId = _this.state.updateId;

        if (syncId === cId && chartId !== _this.uniqueChartId) {
          var dataStartIndex = data.dataStartIndex,
              dataEndIndex = data.dataEndIndex;
          if (!_isNil(data.dataStartIndex) || !_isNil(data.dataEndIndex)) {
            _this.setState(_objectSpread({
              dataStartIndex: dataStartIndex,
              dataEndIndex: dataEndIndex
            }, _this.updateStateOfAxisMapsOffsetAndStackGroups({
              props: _this.props,
              dataStartIndex: dataStartIndex,
              dataEndIndex: dataEndIndex,
              updateId: updateId
            })));
          } else if (!_isNil(data.activeTooltipIndex)) {
            var chartX = data.chartX,
                chartY = data.chartY

            var _this$state2 = _this.state,
                offset = _this$state2.offset,
                tooltipTicks = _this$state2.tooltipTicks;
            
            // --- custom code start ---
            // Set activeTooltipIndex to the index with the same value as data.activeLabel  
            var activeTooltipIndex;
            var activeValue = parseFloat(data.activeLabel)
            if (activeValue || activeValue === 0) {
              activeValue = activeValue.toFixed(3) // round numeric values to 3 decimals
            }
  
            tooltipTicks.forEach(({value}, index) => {
              var tickValue = parseFloat(value)
              if (tickValue || tickValue === 0) {
                tickValue = tickValue.toFixed(3) // round numeric values to 3 decimals
              }
              if (tickValue === activeValue) {
                activeTooltipIndex = index;
                return;
              }
            })
            
            if (!activeTooltipIndex) {
              return;
            }
            // --- custom code end ---
            if (!offset) {
              return;
            }

            var viewBox = _objectSpread({}, offset, {
              x: offset.left,
              y: offset.top
            }); // When a categotical chart is combined with another chart, the value of chartX
            // and chartY may beyond the boundaries.


            var validateChartX = Math.min(chartX, viewBox.x + viewBox.width);
            var validateChartY = Math.min(chartY, viewBox.y + viewBox.height);
            console.log(tooltipTicks)
            var activeLabel = tooltipTicks[activeTooltipIndex] && tooltipTicks[activeTooltipIndex].value;

            var activePayload = _this.getTooltipContent(activeTooltipIndex);

            var activeCoordinate = tooltipTicks[activeTooltipIndex] ? {
              x: layout === 'horizontal' ? tooltipTicks[activeTooltipIndex].coordinate : validateChartX,
              y: layout === 'horizontal' ? validateChartY : tooltipTicks[activeTooltipIndex].coordinate
            } : originCoordinate;

            console.log(activePayload)
            _this.setState(_objectSpread({}, data, {
              activeLabel: activeLabel,
              activeCoordinate: activeCoordinate,
              activePayload: activePayload
            }));
          } else {
            _this.setState(data);
          }
        }
      };`

Would really appreciate it if it got merged so we dont have to maintain a separate fork of Recharts

**Comment by jabberwo** [comment]
Sync feature is useless the way it is now.  I'm showing time scale charts and basing the syncing on index value versus X data value, it's completely off because of inconsistency in data collection.
![image](https://user-images.githubusercontent.com/20709535/81334896-b970b980-9074-11ea-9d8c-ce93f2d0a3e2.png)

**Comment by isaiahtaylor** [comment]
Can confirm, basing off of X index rather than X value makes sync completely useless for time series.

**Comment by jabberwo** [comment]
Will sseira's idea or any thing else become available soon?  Will have to turn of the sync feature if not.

**Comment by emibcn** [comment]
Comparing the value against each value in data, for every chart in sync, may be enough for some people, but also may be a performance issue.

It might be useful to have a both options (index and value) and a callback to let the user decide:
- `syncMethod`: `"index"` (default), `"value"`, `callback`

`callback` is called with two arguments:
- `index`: The index in the X array of the chart emitting the event
- `data`: the X array of the chart emitting the event

The returning value of the function is used to sync local chart.

This way, if I have 2 graphs with 2 days difference (each day is a value) I can have a light comparing function like that:
```
const handleReceiveSync = (index, data) => {
  const d0 = data[0];    // From emitting chart
  const d1 = myData[0];  // From receiving chart

  // Diff both initial dates (they both exist)
  const diff = new Date(+d1).setHours(12) - new Date(+d0).setHours(12);

  // My granularity is 1 day
  const diffDays = Math.round(diff/8.64e7);

  // I should focus on that index (I have compared 2 dates, just once)
  const myIndex = index - diffDays;
  if (myIndex < 0) {
    return 0;
  }
  else if (myIndex >= myData.length) {
    return myData.length - 1;
  }
  else {
    return myIndex;
  }
}
```

**Comment by Eric24** [comment]
I agree that a straight comparison of each axis value would be a significant performance issue for all but charts with very few values.

@emibcn : Won't your solution fail if there are "uneven" values on the X axis (i.e. one chart has 1, 3, 5, 7, 9 and the other has 1, 4, 5, 9)?

I haven't fully thought this through yet, but since the X-axis values are guaranteed to be sorted, why not a binary search to find the closest matching value? A prop can be set to specify the "maximum difference" between the source and target value for it to still be considered a match.

Of course there are more efficient search algorithms (like trie), but doing a binary search may be a reasonable tradeoff between performance and complexity.

**Comment by emibcn** [comment]
@Eric24 Of course thats an option. In fact, what I propose is the possibility to define our own solution via callback.

**Comment by isaiahtaylorhh** [comment]
> I haven't fully thought this through yet, but since the X-axis values are guaranteed to be sorted, why not a binary search to find the closest matching value? A prop can be set to specify the "maximum difference" between the source and target value for it to still be considered a match.

Our fork of this library includes a binary search to find the nearest point and it works reasonably well. Sometimes there can be lag when there is a ton of data and your mouse swipes across (triggering lots and lots of searches). The next step would be to reduce the granularity of those searches.

**Comment by Eric24** [comment]
@emibcn : Yes, I like the callback idea. That makes it most flexible. So it's non-breaking, the "built-in" callback would just return the index. I'm assuming that your intent is that the callback would always provide the index (including -1 or null, to indicate "no sync"), after doing whatever it needs to do to determine the index, right?

@isaiahtaylorhh : Yes, we see similar results on very large data sets, but I can envision many ways to optimize it (particularly when knowing something about the dataset). I've resisted forking the library, though.

**Comment by emibcn** [comment]
@Eric24 Yes, your idea is good: return `null` for a _don't sync this chart_ is a good addition. This can help also on the @isaiahtaylorhh issue: in your function you can throttle responses returning null when throttled.

**Comment by emibcn** [comment]
If developers agree, I can work on a PR to fulfill https://github.com/recharts/recharts/issues/1980#issuecomment-708109566 , for wich, `syncId` value may be:
- `"index"`: Current behavior (default one with this modification): sync by index value.
- `"value"`: Use spartan solution to find matches by value
- `callback`: Use this function to decide current index. The signature should be `(index, data)`, where `index` is the index in the chart emitting the event (the one with the mouse over), and `data` the data of the same emitting chart. The return value will be the index in the current/receiving chart. If null is returned, no tooltip is activated.

**Comment by Eric24** [comment]
@emibcn : My 2-cents worth: I don't think you can easily use the "value" option for `syncId`. Normally, it's an arbitrary string that defines the "group" of charts that are sync'ed. But I actually think it's best to not implement an internal "by value" function, as this will often be very application specific. With that in mind, allowing `syncId` to be its current string "ID" value or a callback function is a non-breaking change, which also allows the developer to specify the "by value" algorithm.

**Comment by gcourtemanche** [comment]
I'm planning to work on a PR to fix this issue. Unless somebody has it done already, @emibcn or @sseira?

**Comment by almudena-vila-cognito** [comment]
I've just submitted a PR for this. I hadn't seen your comment, @gcourtemanche, until I prepared the PR.
Maybe you want to review it and/or provide comments?
Thanks!

**Comment by shmuel-web** [comment]
hey if reached this thread in the futurte like me :)

this is the demo file
https://github.com/CognitoIQ/recharts/blob/e97c9f4700329076dd9d2e9e8c09d196b7f90222/demo/component/LineChartSyncId.tsx#L32

this is the last PR which changes the syncMethid parameters.
<img width="1090" alt="Screen Shot 2022-03-31 at 11 31 36" src="https://user-images.githubusercontent.com/13344801/161012992-5a076bb4-278f-4020-9692-a13f6c8f9a54.png">
