### ISSUE TITLE
Help - How to have two different tooltips for Line and Bar chart

### ISSUE THREAD

**Issue by temurih** [recharts/recharts#1982]
I want to have two different tooltips when someone hovers the line and the bar. By default `Tooltip` component considers both as same, but they are two different kind of data. That is why I want to have a separate tooltip for each depending on what the user hovers.

I am trying to figure this out for `Line` chart first, and I am sure it will be the same for `Bar` chart. I am using `activeDot` object to know which dot the user is hovering over. Although it triggers the `onMouseOver` function, but it contains no data to know which dot it is. Is there anything I could do to have the data as customized `Tooltip` content has (`CustomizedTooltip` in my code). Such as, `label`, `payload`, `active` and etc.

Here is what I have so far, [CodeSandBox][1]

  [1]: https://codesandbox.io/s/recharts-4g6sf

**Comment by goya-c** [comment]
why this issue is closed?

**Comment by kirill-lalala** [comment]
is there a solution?

**Comment by temurih** [comment]
yeah, I am not too sure why they closed it without answering.

**Comment by Madhurasajjan** [comment]
Why this issue is closed without solution. 

https://github.com/recharts/recharts/issues/2932
 above ticket has same issue can someone please please help me.
