### ISSUE TITLE
itemSorter on tooltip not working

### ISSUE THREAD

**Issue by qenibas** [recharts/recharts#1983]
Bug

- Got a problem with itemSorter in tooltips on stacked barchart.

<Tooltip itemSorter={() => 1} formatter={(value) => new Intl.NumberFormat('da').format(value)}/>
Maybe I got it wrong (the documentation for the itemSorter is missing)

Help! Thanks.

**Comment by hahahatey** [comment]
Probably, you should use itemSorter callback like that.
```
itemSorter={item => item.value}  (for example if you want to sort by the value)
itemSorter={item => item.name} 
...
```
As far as i understand default () => -1 means that order does not matter in Tooltip and payloads will be rendered in that order how they are stored in chart`s state. 
There is a tricky moment if you want to reverse oder then you have to go around it by mutipling over -1 (if you sort by number) or s.charCodeAt() * -1 (if you sort by string)
More detail(https://stackoverflow.com/questions/15137948/how-can-i-do-an-asc-and-desc-sort-using-underscore-js)

**Comment by dohomi** [comment]
Does anyone know a solution how to just inverse the tooltip order? It should follow the actual data and inverse the order, because the tooltip by default is upside down. The itemSorter does not seem to deliver that functionality because the original sort value is not part of the payload
