### ISSUE TITLE
bar chart with scale breaks

### ISSUE THREAD

**Issue by rshahhutch** [recharts/recharts#1985]
I have many bar charts with outliers that have really large values compared to other items in the bar chart.

![barchart](https://user-images.githubusercontent.com/17936265/72009137-23359f80-320a-11ea-8a53-bf2c95351fa3.png)

I would like to crop the long bars, so that the chart takes less space. Something like this: (ignore the orientation)

![barchart_scaleBreak](https://user-images.githubusercontent.com/17936265/72009148-2c267100-320a-11ea-9867-6b9077a4cb03.png)

Does rechart support something like this?

**Comment by rvansa** [comment]
Hi, why was this closed (without explanation)? Is scale-break a won't do or is there an existing functionality for that?

**Comment by willemclarke** [comment]
> Hi, why was this closed (without explanation)? Is scale-break a won't do or is there an existing functionality for that?

I would like to know also, currently working with bar graphs at work via recharts & the ability for scale breaks would be especially helpful.
