### ISSUE TITLE
Ability to customize hover effect on ComposedStack

### ISSUE THREAD

**Issue by Nilegfx** [recharts/recharts#199]
When hovering over a bar on ComposedStack (or actually on all bars), the rectangle/cursor background effect should be customizable.

* a unified and more global approach of doing this is highly appreciated, due to time constraints, I couldn't develop a global utility, I just fixed it on ComposedStack, any other volunteer?

**Comment by xile611** [comment]
@Nilegfx 

You can set the style cursor by customized object like this:

```jsx
<Tooltip cursor={{fill: 'red', fillOpacity: 0.05}} />
```

[Here](http://jsfiddle.net/Lpmwoj9o/) is an example.

**Comment by xile611** [comment]
@Nilegfx I would close this issue and pr temporarily.

**Comment by Nilegfx** [comment]
that's fine, thanks.
