### ISSUE TITLE
[v2.0] [Bug] X-axis tick labels missing when resizing/rotating screen

### ISSUE THREAD

**Issue by matthewkwong2** [recharts/recharts#1990]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x-axis-missing-ticks-when-resizingrotating-screen-hs9f8)

### Steps to reproduce
1. Wrap any charts (e.g. `LineChart`) inside `ResponsiveContainer`
2. Use screen size emulation of the browsers. (e.g. set it to iPad Pro)
3. Rotate the screen

### What is expected?
The x-axis will re-render and recalculate the tick labels when the screen is rotated

### What is actually happening?
The tick labels are simply gone after rotating the screen

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.1 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Firefox, Chrome, codesandbox |

**Comment by matthewkwong2** [comment]
Edit: Double checked with `v1.8.5`, such a problem does not exist in lower versions

**Comment by petetnt** [comment]
This also happens when resizing the browser:

![image](https://user-images.githubusercontent.com/7641760/74046717-b9124500-49d7-11ea-9eb2-3e56f9dcc046.png)

After resize:

![image](https://user-images.githubusercontent.com/7641760/74046746-c7f8f780-49d7-11ea-9f24-827b38904e62.png)

Labels sometimes return too when resizing

**Comment by rasheedk** [comment]
Same issue when i wrapped re chart in ResponsiveContainer.
Any workarounds ?

**Comment by abury** [comment]
Seeing this as well. Haven't been able to find any workarounds. Wonder if providing a custom ticker render would help?

**Comment by xile611** [comment]
Everything works well in v2.0.0-beta.2. Please try the latest version
