### ISSUE TITLE
How to plot Total Return?

### ISSUE THREAD

**Issue by lee-aaron** [recharts/recharts#1993]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-czf5t)

### Steps to reproduce
Just look at the example template

### What is expected?
The formula for total return would be (P1 - P0) / P0. I've tried altering the domain but that did not work. I think I would need to alter what labels are printed on the Y Axis so it displays a percentage change from the beginning of the time frame.

### What is actually happening?
Not sure how to achieve my goal

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.1 |
| React | 16.12.0 |
| System | MacOS Catalina 10.15.2 |
| Browser | Chrome 79.0.3945.117 |

**Comment by lee-aaron** [comment]
I've done the data conversion and have plotted it but it seems like the Y Axis does not scale properly. Any ideas?

**Comment by matthewkwong2** [comment]
Your `dataKey` is `AAPL`, and according to your data, `AAPL` is in `string` format.

**Comment by lee-aaron** [comment]
Thank you
