### ISSUE TITLE
Pie slice too thin to be visible

### ISSUE THREAD

**Issue by Gunner17** [recharts/recharts#1998]
Sometimes when one of the series in a Pie chart has a value which is too low compared to the other series values, it shows up in a way that is too thin to be visible (pics attached below). 

Question: Is there a way to at least have a minimum slice width or something alike, so that whenever there is a slice present in the Pie, no matter of how low the value is, it should be at least prominently visible.

Pic 1: Slice too thin
<img width="456" alt="Screen Shot 2020-01-22 at 2 23 52 PM" src="https://user-images.githubusercontent.com/11354728/72939995-daf6a100-3d22-11ea-82b8-a6f7c67bb51a.png">

Pic 2: Slice too thin on hover
<img width="513" alt="Screen Shot 2020-01-22 at 12 45 49 PM" src="https://user-images.githubusercontent.com/11354728/72939367-94547700-3d21-11ea-9f39-d610a2413d1b.png">

**Comment by matthewkwong2** [comment]
Yes, add `minAngle` props to `<Pie/>`
http://recharts.org/en-US/api/Pie#minAngle

**Comment by Gunner17** [comment]
👍
