### ISSUE TITLE
rename AdaptionWrapper to something more meaninful

### ISSUE THREAD

**Issue by luisrudge** [recharts/recharts#20]
A few options:
`ResizableContainer`, `AutoResizeContainer`, `ResponsiveContainer`

**Comment by arcthur** [comment]
Thanks for great advice! We will change `AdaptionWrapper` to `ResponsiveContainer` just a moment.

**Comment by Cloudo** [comment]
+1 for `ResponsiveContainer`

**Comment by xile611** [comment]
Thanks~ Fixed in version 0.6.0
