### ISSUE TITLE
Tracking of mouseup lost in some cases

### ISSUE THREAD

**Issue by YuJianrong** [recharts/recharts#2000]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://recharts.org/en-US/examples/BrushBarChart](http://recharts.org/en-US/examples/BrushBarChart)

### Steps to reproduce
Click on the Slide or Traveller, keep mouse button down but move outside of the brush, release the mouse button outside the brush in 1 second (or the time set by the prop `leaveTimeOut`), move mouse back to the brush, you'll noticed the Slide/Traveller is still in dragging status even the mouse button is released.

### What is expected?
The dragging status should be stopped once the mouse button is released.

### What is actually happening?
The Slide/Traveller is still in dragging status after the mouse button released outside the brush in 1 second.

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.1 |
| React | 16.9.9 |
| System | OSX |
| Browser | Chrome |

**Comment by GonzalezAnguita** [comment]
Having the same issue here.

**Comment by av-k** [comment]
+1, the same.

**Comment by jonybekov** [comment]
Have you found the issue?
@xile611
