### ISSUE TITLE
Don't import whole lodash please! 

### ISSUE THREAD

**Issue by a-x-** [recharts/recharts#2002]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://n/a](https://n/a)

### Steps to reproduce
N/a

### What is expected?
Import every lodash.module you need 
as a separate dependency 

### What is actually happening?
Bundle size is too big 

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.1 |
| React | Any  |
| System | Any |
| Browser | Any |

---
Try to run webpack with bundle analyzer

**Comment by a-x-** [comment]
![7F3476CD-D5C5-4A94-90E0-5EB6FB7FA83A](https://user-images.githubusercontent.com/6201068/73127209-0224cb00-3fce-11ea-96b8-494adea80924.jpeg)

**Comment by xile611** [comment]
we has use `babel-plugin-lodash` .
![image](https://user-images.githubusercontent.com/6111424/76495357-a628df80-6471-11ea-8119-cf246b434d53.png)

lodash function has been loaded by need

**Comment by HaNdTriX** [comment]
fyi: https://bundlephobia.com/result?p=recharts@1.8.5

**Comment by gaurav5430** [comment]
@HaNdTriX apologies, I am not very clear about the information that should be noticed from the bundle-phobia link.

Is it to show that the size of `lodash` inside `recharts` is less than the size of the full `lodash` library?

https://bundlephobia.com/result?p=lodash@4.17.15 - 70kb total
https://bundlephobia.com/result?p=recharts@1.8.5 - lodash size; 40kb

so there is a saving if about 30kb 
is this understanding correct ?

I think this would also mean that if `Recharts` is tree shaken correctly, say, to only import `LineChart` and `Line`, then the `lodash` import size wouldn't be 40kb but only whatever is required by `Line` and `LineChart`.
