### ISSUE TITLE
webpack build error with recharts 2.0.0-beta.0 onwards

### ISSUE THREAD

**Issue by vinesheg1** [recharts/recharts#2007]
When taking production build using webpack (v4) and recharts 2.0.0-beta.0 onwards, getting build error like below
![image](https://user-images.githubusercontent.com/38239795/73340358-99c13c80-42a0-11ea-8fd8-626ddb60e95a.png)
Build will get success if I remove the flag NODE_ENV = production or disable Uglify plugin in webpack config

**Comment by mabzzz** [comment]
Almost the same problem here using "recharts 2.0.0.beta.1" and uglifyjs:
> Unexpected token: operator (>)
If I disable uglifyjs, the build works fine.
if I keep uglifyjs but use recharts 1.8.5, it works too.

**Comment by xile611** [comment]
Please crate a simple repo to reproduce this issue. Thanks.
