### ISSUE TITLE
onMouseOut not firing when mouse is moved over quickly

### ISSUE THREAD

**Issue by danedavid** [recharts/recharts#2008]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-mouseout-issue-r61n9)

### Steps to reproduce
Quickly hover in and out of the sectors. Sometimes the sectors remain in hovered state. This happens because `mouseEnter` is fired, `mouseOut` is not.

### What is expected?
`mouseOut` must be fired

### What is actually happening?
`mouseOut` not fired

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.1 |
| React | 16.12 |
| System | MacOS |
| Browser | 79 |

**Comment by xile611** [comment]
Use MouseLeave for instand

**Comment by danedavid** [comment]
@xile611 `onMouseLeave` also doesn't work. I've updated the sandbox.

**Comment by iflp** [comment]
@danedavid did you ever find a workaround? I'm having the same issue.

**Comment by dima19972525** [comment]
Any updates?

**Comment by webdevtester1** [comment]
Having the same problem.

**Comment by ckifer** [comment]
@webdevtester1 do you mind making another sandbox? I can't reproduce with the original one - the event seems to always be fired as far as I can tell

**Comment by AndreiGusa** [comment]
Also having the same issue. Any update?

**Comment by ckifer** [comment]
@AndreiGusa can you reproduce in a sandbox?

**Comment by AndreiGusa** [comment]
> @AndreiGusa can you reproduce in a sandbox?

@ckifer simple example here. In my case the issue with these events is that the tooltip remains open when onmouseleave/onmouseout are triggered
https://codesandbox.io/p/sandbox/recharts-tooltip-94f272
https://www.loom.com/share/1cd36616a4fe4a18a6967c1443d581bf?sid=2d5df084-aab0-4e2e-be25-a016b5ef3b17
