### ISSUE TITLE
<rect> attribute height: A negative value is not valid.

### ISSUE THREAD

**Issue by niels-hecquard** [recharts/recharts#2009]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-0fgoy)

### Steps to reproduce
I get

> Error: <rect> attribute height: A negative value is not valid. ("-x")

with the code visible in codesandbox. This error shows up on chrome and chromium but not in firefox. It doesn't affect rendering, but it's annoying to have errors in the console.
It seems to have something to do with the height={43} props passed to ResponsiveContainer but I don't understand what/why.

### What is expected?
No error in the console

### What is actually happening?
Error: <rect> attribute height: A negative value is not valid. ("-x")

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.1 |
| React | 16.8.6 |
| System | Ubuntu 18.04.3 |
| Browser | Chrome 79.0.3945.130  |

**Comment by xile611** [comment]
It works in v2.0.0-beta.3

**Comment by tompeace** [comment]
Hi, I am still getting this error, when my chart is very small. I am rendering the chart inside react-grid-layout. 

**package versions:**
- react: 16.13.1
- recharts: 2.0.0-beta.5

**error:** 
<img width="633" alt="Screenshot 2020-03-28 at 14 26 34" src="https://user-images.githubusercontent.com/6696808/77824173-ff933e80-7100-11ea-9ed5-f843b3deab1a.png">

**html:**
<img width="457" alt="Screenshot 2020-03-28 at 14 26 49" src="https://user-images.githubusercontent.com/6696808/77824181-1043b480-7101-11ea-8fc0-3268869f1225.png">

**my code:**
```
export default function BarChart(props) {
  const data = [
    { name: "Page A", uv: 4000, pv: 2400, amt: 2400 },
    { name: "Page B", uv: 3000, pv: 1398, amt: 2210 },
    { name: "Page C", uv: 2000, pv: 9800, amt: 2290 },
    { name: "Page D", uv: 2780, pv: 3908, amt: 2000 },
    { name: "Page E", uv: 1890, pv: 4800, amt: 2181 },
    { name: "Page F", uv: 2390, pv: 3800, amt: 2500 },
    { name: "Page G", uv: 3490, pv: 4300, amt: 2100 }
  ]

  return (
    <ResponsiveContainer>
      <RechartsBarChart data={data}>
        <CartesianGrid strokeDasharray='3 3' />
        <XAxis dataKey='name' />
        <YAxis />
        <Tooltip />
        <Legend />
        <Bar dataKey='pv' fill='#8884d8' />
        <Bar dataKey='uv' fill='#82ca9d' />
      </RechartsBarChart>
    </ResponsiveContainer>
  )
}
```
I believe this is the line causing it:
https://github.com/recharts/recharts/blob/41f363a3ec2a5d16477e4c96fe9e2153ede6be84/src/chart/generateCategoricalChart.tsx#L1812

This is my first time using recharts and not familiar with the codebase, so I am only going on the format of the clipPath id and the order of the <rect> height/width attributes for my guess!

Hope this helps

**Comment by JavidanDMP** [comment]
same issue is ongoing rechart 2.1.8

**Comment by sumitWebDev** [comment]
I am using rechart 2.1.10 and facing the same issue. Try to add a wrapper around the charts and add a height with vh unit for eg: height: 41vh;

This resolved my issue

**Comment by natBizitza** [comment]
It should be re-open. I am using percentages for charts containers' height and it throws an error: 
`react-dom.development.js:798 Error: <rect> attribute height: A negative value is not valid. ("-52")`

"react": "^18.0.0"
"recharts": "^2.7.3"

**Comment by Elipatra** [comment]
In my case the issue was at the width so same as @sumitWebDev  proposed I created a wrapper and assigned a min-width with the limit I want to see the responsive chart and it doesn't go to negative values.

**Comment by mhmtbsrglu** [comment]
continuing

**Comment by arpitdalal** [comment]
+1

**Comment by ckifer** [comment]
Should be fixed in next minor

**Comment by nikolasrieble** [comment]
Released with https://github.com/recharts/recharts/releases/tag/v2.10
