### ISSUE TITLE
Composed chart not display bars without bar size

### ISSUE THREAD

**Issue by boytsovevg** [recharts/recharts#2010]
Hello. 
I used BarChart which displayed bars responsive, but when i swiched to ComposedChart it is needed to specify barSize to display it. How to use ComposedChart with bars without fixed barSize property?

Composed chart with bars without barSize property
https://jsfiddle.net/j9gL4sbp/

Responsive bars in BarChart
https://jsfiddle.net/3z98Lqyh/

**Comment by brlnr23** [comment]
I faced the same issue after I have upgraded to v2.0.0-beta.1. The bars are not displayed in a composed chart anymore. Following this thread now :)

**Comment by Kaishiyoku** [comment]
Same here.

**Comment by ArpitaSrivas** [comment]
+1
