### ISSUE TITLE
ComposedChart. Bar moves over YAxis

### ISSUE THREAD

**Issue by boytsovevg** [recharts/recharts#2011]
Hello.
In example [http://recharts.org/en-US/examples/LineBarAreaComposedChart](url)
there are gaps between bar and axis
![image](https://user-images.githubusercontent.com/19956536/73592476-f5dbc900-450b-11ea-92f3-33fef16b1f68.png)

But in your reference expample code [https://jsfiddle.net/9d5gc80z/](url)
bar moves over the YAxis, how to save gaps between axis and bar?

**Comment by Xmerr** [comment]
Was experiencing the same issue. Looking through the updates I found this line was changed from `v1.8.5` to `v2.0.0-beta0`. 

https://github.com/recharts/recharts/blob/1fb6934c87549cb753ae51abb318deff6358d621/src/util/ChartUtils.js#L560

Removing ` || chartType.indexOf('ComposedChart') >= 0` fixed the issue. Pinged the original author to see if it can be fixed officially

**Comment by xile611** [comment]
You can use `<XAxis scale="band" />` to change the default behavior of `<ComposedChart />`
