### ISSUE TITLE
Log scale doesn't work if value is 0

### ISSUE THREAD

**Issue by Richard87** [recharts/recharts#2012]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/vq42bekg/4/](https://jsfiddle.net/vq42bekg/4/)

### Steps to reproduce
Set the scale to "log" and domain to auto, auto, and set one value to 0

### What is expected?
the scale should work

### What is actually happening?
no yAxis is drawn, no lines are drawn (tooltip, xaxis and legend works)

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.1 |
| React | 16.12.0 |
| System | Fedora 31 |
| Browser | Chrome and Firefox |

---
null instead of 0 solves the issue, but that changes the data (the value is 0, not null)

**Comment by matthewkwong2** [comment]
That because mathematically, log 0 is undefined.

**Comment by Richard87** [comment]
Huh, nice, I had forgotten that!

Nevertheless, the data includes the value 0, even though the scale is logarithmic etc, so I mean it should be a valid datapoint, and should show in the chart...

Maybe just round it to 1/Infinity?

This example, show 1/Infinity and 0.00000000000001, but the scale is stil broken:
https://jsfiddle.net/z8a2L95p/

**Comment by xile611** [comment]
When you use log scale, it's recommended to handle the data before...

**Comment by korgara** [comment]
> When you use log scale, it's recommended to handle the data before...

Im sorry, do you have some examples how to handle that?
I have a data that contains 0's and I can't remove them, I have to show that it's 0

**Comment by BeHustle** [comment]
Maybe it will save time for someone. To avoid zero and negative values on your logarithmic axis you can use [scaleSymlog](https://github.com/d3/d3-scale/blob/main/README.md#scaleSymlog) from `d3-scale` instead of `scaleLog`.


`import { scaleSymlog } from 'd3-scale';`
`const scale = scaleSymlog();`
...
`<YAxis scale={scale} />`
