### ISSUE TITLE
Warning: componentWillReceiveProps has been renamed, and is not recommended for use

### ISSUE THREAD

**Issue by talwaserman** [recharts/recharts#2015]
The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.

hello when i'm running tests i get this warning for recharts, especially for pie and piechart

`Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for detai
ls.
      
      * Move data fetching code or side effects to componentDidUpdate.
      * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. 
Learn more at: https://fb.me/react-derived-state
      * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
      
      Please update the following components: Pie, PieChart`

do you plan to update these components?

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

**Comment by matthewkwong2** [comment]
Use recharts v2.0

**Comment by mzzfederico** [comment]
Great idea. Where is it?
