### ISSUE TITLE
Responsive container is not working for Radialbarchart in reccarts

### ISSUE THREAD

**Issue by yogesh45** [recharts/recharts#2016]
`<ResponsiveContainer> 
{
this.state.isChartPageFlag === true ? this.state.isPageLoading == true ? 
	<div className="credentialPopupDisplay buttonLoader">
		<div className={"reportloaderCheckList"}>
			<img className="" src="images/visual_loading_data.gif" />
		</div>
	</div>:
	<RadialBarChart width={500} height={300} cx={150} cy={150} innerRadius={20} outerRadius={140} barSize={10} data={this.state.data} dataKey={this.state.dimension}>
		{
			this.state.measure.map((meas,index) => {
				return(<RadialBar minAngle={15}  background clockWise dataKey={meas} />)
			})
		}
		<Tooltip />
		{
			this.state.isChartPageFlag === true
		}
		{
			this.state.isChartPageFlag === true ? <Legend iconSize={10} width={120} height={140} layout="vertical" verticalAlign="middle" wrapperStyle={this.state.style} /> :''
		}
	</RadialBarChart>:
	<RadialBarChart width={500} height={300} cx={150} cy={150} innerRadius={20} outerRadius={140} barSize={10} data={this.state.data} dataKey={this.state.dimension}>
		{
			this.state.measure.map((meas,index) => {
				return(<RadialBar minAngle={15}  background clockWise dataKey={meas} />)
			})
		}
		<Tooltip />
		{
			this.state.isChartPageFlag === true ? <Legend iconSize={10} width={120} height={140} layout="vertical" verticalAlign="middle" wrapperStyle={this.state.style} /> :''
		}
	</RadialBarChart>
}
</ResponsiveContainer>`

**Comment by goodwin64** [comment]
It's not clear what issue are you facing. Please provide a human-readable description and a link to the reproducible case.
