### ISSUE TITLE
Y-axis not displaying all ticks when set domain min and max values and interval 0

### ISSUE THREAD

**Issue by frankrod** [recharts/recharts#2019]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/4ncae6dj/](https://jsfiddle.net/4ncae6dj/)

### Steps to reproduce
use `domain={[minValue, maxValue]}` in your Y-axis and with some values you see that it is correctly displayed but for other don't such as `domain={[0, 165]}` you'll see that 1 tick is missing

### What is expected?
I expect to see my linechart correctly scale always with 4 ticks if that is the case.

### What is actually happening?
1 tick is missing

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.1 |
| React | 16.8.6 |
| System | macOS Catalina 10.15.2 |
| Browser | Chrome 80.0.3987.87 (Official Build) (64-bit) |

---
I've tried added interval={0} to see if that renders all the ticks but that's not happening isn't working.
Thanks in advance

**Comment by xile611** [comment]
Specify `ticks` of <YAxis /> if you want to control the ticks yourself.
