### ISSUE TITLE
want to show week , 2 weeks , 1 month , 3 months , 6 months on  x Axis  based on select option

### ISSUE THREAD

**Issue by danish0313** [recharts/recharts#2020]
i wan to show  1 week , 2 week and 1 month , 3 month duration on  XAxis based on select option 
is therea way to show  week , month , year  dynamically  when i select  week , month or year from select option .
below is my code:
 <div className="ms-Grid" dir="ltr">
                    <div className="ms-Grid-row">
                        <div className="ms-Grid-col ms-u-sm12 ms-u-md12 ms-u-lg8" style={{ textAlign: 'center' }}>
                            <Dropdown
                                label="Select Week , Month , Year for Graph"
                                options={[{ key: 'week', text: 'week' },
                                { key: 'month', text: 'month' },
                                { key: 'year', text: 'year' }]}
                                styles={dropdownStyles}
                                onChange={this.GraphHandler}
                            />
                            <LineChart
                                width={1200}
                                height={650}
                                data={data}
                                margin={{
                                    top: 5, right: 30, left: 20, bottom: 5,
                                }}
                            >
                                <CartesianGrid strokeDasharray="5 5" />
                                <XAxis tickFormatter={this.formatXAxis} tickSize={30} dataKey="date"   height={60} />
                                <YAxis />
                                <Tooltip
                                    content={<CustomTooltip
                                    />}

                                />
                                <Legend />
                                {data.map((lines: Data) => (<Line
                                    key={lines.name}
                                    type="monotone"
                                    name={lines.text}
                                    dataKey={lines.text}
                                    stroke={lines.stroke}
                                    label={<CustomizedLabel />}
                                    strokeWidth={2}
                                    activeDot={{ onClick: this.handleClick, onMouseOver: this.onMouseOver }}
                                    onMouseOver={this.onMouseOver}
                                />))}
                            </LineChart>

below is the  screen shot:

![FireShot Capture 002 - React App - localhost](https://user-images.githubusercontent.com/29385795/73941720-0adea080-48ee-11ea-9ea3-b068945d5c5a.png)

**Comment by VasudevHarshal-123** [comment]
@danish0313 This feature is not available in recharts but this can be achieved by manipulating the data. The X-Axis has a prop called interval where you can divide the interval. Now to achieve what you desire you can have weeks assigns to the data you are sending for example date started from 02-Feb-2020 let's consider this as week 0. Similarly, 09-Feb-2020 must be assigned the value week-1 and so on and the rest of the dates in the middle will not have any week assigned to it. This can be achieved for months and dates in the similar manner and the UI part can follow along. Now, you might say that I want to show the dates as well in the middle of week. That can be achieved via CustomTooltip prop we have on Tooltip component.
