### ISSUE TITLE
Labels do not receive parameters in 2.0.

### ISSUE THREAD

**Issue by petetnt** [recharts/recharts#2023]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-7nd4k)

### Steps to reproduce
1. Add a <Label>
2. Rotate it 270 degress with `angle={270}`

### What is expected?
The label should be rotated 270, so starting from bottom towards up

### What is actually happening?
The label stays horizontal

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.1 |
| React | 16.8 |
| System | MacOS |
| Browser | All |

---
Instead of `transform="rotate(270, 60, 209)"` getting added, you can see `viewBox="[object Object]"` in the DOM

2.0.0 beta:
![image](https://user-images.githubusercontent.com/7641760/74047302-c8de5900-49d8-11ea-942c-bff08e9199bc.png)

1.8.5:
![image](https://user-images.githubusercontent.com/7641760/74047331-d4ca1b00-49d8-11ea-8b0c-aae1554f352e.png)

**Comment by joshvillbrandt** [comment]
I got this today as well. I'm not trying to do anything fancy here... I just want normal labels on the X and Y axes.

Even the x axis label, which shouldn't need to be rotated, has its position all messed up. It too has `viewBox="[object Object]"`.

A fix would be greatly appreciated!

![image](https://user-images.githubusercontent.com/3335568/75203508-166dfc00-5723-11ea-96e5-4a2f89e4afe3.png)

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.

**Comment by vtarelkin** [comment]
@xile611 https://github.com/recharts/recharts/issues/2221
the issue is reproducible
