### ISSUE TITLE
Mutliple Bars don't work in ComposedChart, only one bar is shown

### ISSUE THREAD

**Issue by talentlessguy** [recharts/recharts#2031]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-wqng5)

### Steps to reproduce
Use `<ComposedChart />` with 2 `<Bar />`'s. 

### What is expected?
Two bars should be both displayed like in [SimpleBarChart]() example

### What is actually happening?
Only second bar of 2 will be shown. It will also inherit some properties from the first, like bar width.

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.1 |
| React | preact 10.2.1 |
| System | Manjaro Linux x64 |
| Browser | Firefox 70 |

**Comment by YaroslavnaMatkova** [comment]
As a workaround you can remove `barSize` from the first <Bar> or add `barSize={VALUE}` to the second one then they both are shown
