### ISSUE TITLE
How add other html tags rather than Text to Tick prop in Axis?

### ISSUE THREAD

**Issue by Nilanth** [recharts/recharts#2032]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Need to customize axis tick 

### What does the proposed API look like?
On allowing other html elements i could add icons to it

**Comment by aje** [comment]
Why is this closed? I have the same problem. I can only format the axis in string.
