### ISSUE TITLE
Label Position

### ISSUE THREAD

**Issue by gsadams2** [recharts/recharts#2033]
I am trying to position my label but it keeps overlapping with my data. 

On the y axis, I want "Hash Rate Th/s to not overlap with the data points

<img width="567" alt="Screen Shot 2020-02-18 at 3 50 41 PM" src="https://user-images.githubusercontent.com/30329473/74781080-79185100-5266-11ea-897c-c2409a0386e5.png">

This is my code 

```return (
      <LineChart
        width={1100}
        height={400}
        data={data}
        margin={{
          top: 5, right: 30, left: 100, bottom: 5,
        }}
      >
        <CartesianGrid strokeDasharray="3 3" />
        <XAxis 
        dataKey="x" 
        interval={30} 
        tickFormatter = {(value) => moment.unix(value).format("MM/YY")}
        />
        <YAxis 
        tickFormatter = {(yaxisNum) => new Intl.NumberFormat('en').format(yaxisNum)}
        label={{ value: 'Hash Rate TH/s', angle: -90, position: 'insideLeft'}}   
        />
        <Tooltip 
        formatter={(okay) => new Intl.NumberFormat('en').format(okay)} 
        
        />

      
        <Line type="monotone" dataKey="y" stroke="#8884d8" dot={false} />
      
      </LineChart>
)```

**Comment by xile611** [comment]
@gsadams2 Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.

**Comment by rug1** [comment]
I still have this issue on the latest version
