### ISSUE TITLE
Tooltip Only Show Y Axis Value 

### ISSUE THREAD

**Issue by gsadams2** [recharts/recharts#2034]
In my tooltip visual that is appearing, I only want the y axis value to show. And I don't even want it to say the letter Y.

How can I format a tooltip to only show the y axis value. So I only want to show the number 80,995,832 and nothing else

![IMG_0904](https://user-images.githubusercontent.com/30329473/74781656-7c600c80-5267-11ea-8e4c-72996767afca.jpeg)

Right now here is my code 

```return (
      <LineChart
        width={1100}
        height={400}
        data={data}
        margin={{
          top: 5, right: 30, left: 100, bottom: 5,
        }}
      >
        {/* <CartesianGrid  /> */}
        <CartesianGrid strokeDasharray="3 3" />
        {/* <XAxis dataKey="x" tick={renderCustomAxisTick} /> */}
        <XAxis 
        dataKey="x" 
        interval={30} 
        tickFormatter = {(value) => moment.unix(value).format("MM/YY")}
    
        />
        <YAxis 
        
        tickFormatter = {(yaxisNum) => new Intl.NumberFormat('en').format(yaxisNum)}
        label={{ value: 'Hash Rate TH/s', angle: -90, position: 'insideLeft'}}
        
        />
     

        <Tooltip 
        
        formatter={(okay) => new Intl.NumberFormat('en').format(okay)} 
        
        />

      
        <Line type="monotone" dataKey="y" stroke="#8884d8" dot={false} />
      
      </LineChart>
    )```

**Comment by davidstenz** [comment]
This should work:
` <Tooltip
        labelFormatter={() => undefined}
        formatter={(okay) => [new Intl.NumberFormat('en').format(okay), undefined]} 
  />`

**Comment by gsadams2** [comment]
> This should work:
> ` <Tooltip labelFormatter={() => undefined} formatter={(okay) => [new Intl.NumberFormat('en').format(okay), undefined]} />`

Thanks. This worked!
