### ISSUE TITLE
Charts do not render children custom component that renders svg tags but does render any inline svg tags. 

### ISSUE THREAD

**Issue by dchhetri** [recharts/recharts#2035]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-eo5z6)

### Steps to reproduce
Run the linked code and notice that <MyCustomComponent /> does not render. Note, inlining the definition does cause it to render.

### What is expected?
Charts allow custom children component that render svg tags to also render.

### What is actually happening?
Charts are not rendering children react components that render svg components.

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.1 |
| React | 16.12.0 |
| System | Mac |
| Browser | Chrome |

---
This might be intentional so looking forward to the discussion.

**Comment by walterperez** [comment]
Why is this close without any answer?

**Comment by cichyadam** [comment]
@xile611 how come you closed this without any proper answer?
