### ISSUE TITLE
Tooltip not working on touch devices

### ISSUE THREAD

**Issue by sebastianekstrom** [recharts/recharts#204]
**How to reproduce**
1. Implement a simple LineChart:

```
<LineChart data={data}>
  <XAxis/>
  <YAxis width={12} tick={{strokeWidth: 1}}/>
  <CartesianGrid strokeDasharray="1 5"/>
  <Tooltip />
  <Line type="monotone" dataKey="pv" stroke="#FBC011" dot={{stroke: '#FBC011'}}/>
  <Line type="monotone" dataKey="uv" stroke="#47484A" />
</LineChart>
```
1. Try to click on the dots in the graph
2. No tooltip is showed

**Reproducable in:**
- iOS Safari (latest)
- iOS Simulator via XCode

**Recharts version**
`0.13.4`

---

![unclickable](https://cloud.githubusercontent.com/assets/1921046/18170401/7f0a6a0a-705e-11e6-8ed0-49e86977021e.gif)

**Comment by xile611** [comment]
@sebastianekstrom Yeah, Recharts don't support touch events now.

**Comment by thoqbk** [comment]
I have modified file `chart/generateCategoricalChart.js` to support touch event. Visit my fork at https://github.com/thoqbk/recharts

**Comment by xile611** [comment]
@thoqbk Do you want to submit a PR ?

**Comment by thoqbk** [comment]
I just created a pull request. Can you have a look?
https://github.com/recharts/recharts/pull/402

**Comment by matheusml** [comment]
Can I help in any way so that this PR is accepted?
