### ISSUE TITLE
Can not style X/YAxis anymore

### ISSUE THREAD

**Issue by vashchukmaksim** [recharts/recharts#2040]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/ahx9w8m0/2/](https://jsfiddle.net/ahx9w8m0/2/)

### Steps to reproduce
Add axisLine={{ opacity: 0.2 }} prop to X or Y Axis component

### What is expected?
Axis line has opacity 0.2

### What is actually happening?
Axis line still has opacity 1

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.1 |
| React | 16.12.0 |
| System | Mac OS |
| Browser | Chrome 80.0.3987.122 |

---
I updated to recharts 2.0.0-beta1 and this prop does not work anymore. If I set it to "false" axis disappears but it ignores any styling.

**Comment by xile611** [comment]
I think this issue has been fixed in https://github.com/recharts/recharts/pull/2006
