### ISSUE TITLE
debugger left on the code in TreeMap.js

### ISSUE THREAD

**Issue by melalj** [recharts/recharts#2041]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-p2v98)

### Steps to reproduce
Using the component <TreeMap />

### What is expected?
Componenent to render

### What is actually happening?
Breaking point on the "debugger" in https://github.com/recharts/recharts/blob/master/src/chart/Treemap.tsx#L30

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.1 |
| React | react 16.12.0 |
| System | Mac |
| Browser | Electron 7.1.13 |

**Comment by xile611** [comment]
Fixed in  v2.0.0-beta.2
