### ISSUE TITLE
Legends within parent SVG

### ISSUE THREAD

**Issue by derrickpelletier** [recharts/recharts#205]
Curious if there is a particular reason that the legend is not part of the main chart `<svg>`?

Use-case is that users customize charts within our app, and when done are able to download/export them as either a standalone `.svg` or `.png`. In either case, the legend being separate complicates this.

**Comment by derrickpelletier** [comment]
Maybe even a separate legend component designed to be composed into the main svg, keeping the functionality of both... like an `<SvgLegend>` or something. Just thinking out loud...

**Comment by xile611** [comment]
@derrickpelletier We use dom nodes to render legend because the layout of dom nodes is much simpler than svg nodes. For svg nodes, we must calculate the width of each text.

**Comment by SachaG** [comment]
I'm working on making charts exportable as images (to let people share them as Twitter cards) so I also think this would be useful.

**Comment by derrickpelletier** [comment]
@SachaG I had started a decorator here based on that need: [react-download-svg](https://github.com/derrickpelletier/react-download-svg) for (ideally) use with any svg-based component. It's just a first working pass, open to ideas on a better api for it 👌

**Comment by SachaG** [comment]
This looks really cool! Does it convert the SVG to PNG right in the browser? I didn't even know you could do that!

That being said for Twitter Cards I need to be able to point my meta tag at an image file, so I think I would have to do the conversion server-side first and host the file somewhere.

**Comment by ammmze** [comment]
Anybody try [html2canvas](https://html2canvas.hertzen.com) which I guess can export to PNG? Or maybe this one https://github.com/tsayen/dom-to-image/blob/master/README.md

I'm gonna need this functionality soon, so will be trying it out soon-ish

**Comment by marcramser** [comment]
Any update? We would also need it to export the chart (with the legend) to png. Or does anyone else has a solution?

**Comment by cristianocca** [comment]
> 
> 
> Any update? We would also need it to export the chart (with the legend) to png. Or does anyone else has a solution?
> 
> Update:
> I used https://github.com/tsayen/dom-to-image/blob/master/README.md and it worked perfectly fine.
> 
> ```
>   exportChart = () => {
>     if (this.currentChart && this.currentChart.container) {
>       domtoimage.toPng(this.currentChart.container, { bgcolor: '#ffffff' })
>         .then((dataUrl) => {
>           const download = document.createElement('a');
>           download.href = dataUrl;
>           download.download = `chart.png`;
>           download.dispatchEvent(new MouseEvent('click'));
>         })
>         .catch((error) => {
>           console.error('Something went wrong!', error);
>         });
>     }
>   };
> ```

Do you still use this? Looks like dom-to-image is extremely outdated and not maintained any more.  When trying to use it, I'm having issues with the chart's legend, they do not layout properly and end up cut out in the image.

**Comment by marcramser** [comment]
@cristianocca yes, we still use it. We had a similar problem.
When creating the chart, we do add some pixel to the view box and then remove them after the export is done. A hacky solution but the only thing we found that worked.

`<RechartsBarChart ref={(chartRef) => this.chartRef = chartRef}>`

and in the exportChart function we use this ref 

`
export function downloadChart(chartRef) {
  return () => {
    if (chartRef && chartRef.container) {
      /**
       *  Workaround: Rechart sets the viewBox width to small. If one export line or bar charts with the default
       *  viewBox the last tick of the xAxis will not be fully visible.
       */
      const svg = chartRef.container.children[0];
      svg.setAttribute('viewBox', `${svg.viewBox.baseVal.x} ${svg.viewBox.baseVal.y}
       ${svg.viewBox.baseVal.width + 10} ${svg.viewBox.baseVal.height}`);

      domtoimage
        .toPng(chartRef.container, { bgcolor: '#ffffff' })
        .then((dataUrl) => {
          const download = document.createElement('a');
          download.href = dataUrl;
          download.download = 'chart.png';
          download.dispatchEvent(new MouseEvent('click'));
          svg.setAttribute('viewBox', `${svg.viewBox.baseVal.x} ${svg.viewBox.baseVal.y}
            ${svg.viewBox.baseVal.width - 10} ${svg.viewBox.baseVal.height}`);
        })
        .catch((error) => {
          svg.setAttribute('viewBox', `${svg.viewBox.baseVal.x} ${svg.viewBox.baseVal.y}
              ${svg.viewBox.baseVal.width - 10} ${svg.viewBox.baseVal.height}`);
        });
    }
  };
}
`

**Comment by cristianocca** [comment]
Have you tried manually adding a foreign object instead and exporting the entire SVG?  Another issue I have with the above approach is the quality. The PNG quality depends on the SVG/Chart size, which is small for the browser to look good, but not big enough for the final PNG.

I will try your solution as well, but using an unmaintained library seems like not the best idea. Thanks for the code!

**Comment by kdoda** [comment]
@cristianocca Did you ever find a good solution to this? I also don't want to rely on a library which does not have any activity for the last 5 years.

**Comment by cristianoccazinsp** [comment]
I used dom to image as said above and worked around the cut issues by adjusting dimensions and other settings. Worked fine eventually.
