### ISSUE TITLE
2.0.0-beta.x should not be tagged as latest in NPM

### ISSUE THREAD

**Issue by klangenk** [recharts/recharts#2050]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.npmjs.com/package/recharts](https://www.npmjs.com/package/recharts)

### Steps to reproduce
npm i recharts

### What is expected?
Latest tag in NPM should point to version 1.8.5, because that's the stable version that should get installed with `npm i recharts`

### What is actually happening?
Latest tag in NPM points to version 2.0.0-beta.3

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.3 |
| React | 16 |
| System | MacOS |
| Browser | Chrome Version 80.0.3987.132 |

---
Installed recharts in a new project and had a problem that the bars in the bar chart were missing. Bug is fixed now, but 2.0.0-beta.x is not stable yet.

**Comment by xile611** [comment]
Thanks! Good suggestion. We have changed the latest version to 1.8.5 
![image](https://user-images.githubusercontent.com/6111424/76614538-43ac0e00-655b-11ea-8659-0cdbb315c2f9.png)
