### ISSUE TITLE
Putting children inside <Line> throws a React error #1988

### ISSUE THREAD

**Issue by James-Reed-cognito** [recharts/recharts#2051]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-ror6u)

### Steps to reproduce
Put anything (even a simple empty div) inside a <Line> component - please see the example for details.

### What is expected?
No react error occurs

### What is actually happening?
A react error occurs:
"index.js:27 Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it."

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.3 |
| React | 16.12.0 |
| System | Any |
| Browser | All tried (safari, chrome, edge, firefox) |

---
This clutters up the console and prevents me from having a clean codebase with no errors, and also makes me worry that I'm doing something wrong, and also when I run tests clogs up the output and if I were failing tests on console errors, I would fail my tests even though the act of putting a LabelList inside the Line works. My repro is _exactly_ how the docs say to do LabelLists http://recharts.org/en-US/api/LabelList

- If I dig around in the library code in node_modules/recharts/es6 and remove adaptEventHandlers(this.props) from line 158 inside the render method of shape/Curve, this error goes away
- If I look inside renderByOrder in utils/ReactUtils I can't see any special handling of children of elements to be rendered, and similarly chart/generateCategoricalChart seems to have a map of types it can render as children, but seems to have no specification for any children

**Comment by DylanWard14** [comment]
I am also experiencing this issue.

**Comment by James-Reed-cognito** [comment]
Hi @xile611 - thank you for the quick response on this! What release will this fix be in?
