### ISSUE TITLE
Bar position is invalid using Bar without barSize in ComposedChart

### ISSUE THREAD

**Issue by yizumi1012xxx** [recharts/recharts#2055]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-n9w3d)

### Steps to reproduce
Use <ComposedChart /> with  <Bar /> when not set barSize.

### What is expected?
Correct bar position

### What is actually happening?
Incorrect bar position

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.3 |
| React | preact 10.2.1 |
| System | Manjaro Linux x64 |
| Browser | Firefox 70 |

**Comment by xile611** [comment]
Maybe you just want to change the scale of XAxis to be 'band'.
