### ISSUE TITLE
Funnel chart renders LabelList with unnecessary line breaks

### ISSUE THREAD

**Issue by kaikun213** [recharts/recharts#2056]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-18-funnel-bug-dmodr)

### Steps to reproduce
1) Create a funnel chart 
2) Give it a margin on the right
3) Create LabelList on the right 

### What is expected?
Long labels will be displayed until the end of the margin without line breaks.
Similar to the first one using the full width: 
![Screenshot from 2020-03-17 10-45-17](https://user-images.githubusercontent.com/18282228/76843677-6af52a80-683c-11ea-9b55-53eb68baca62.png)

### What is actually happening?
For the first data entry the label is shown fully, but the label size seems to be related to the funnel size and thus shrinks with each further entry. Thus for the small funnels in the end this can become really messy because the label has line breaks instead of using the width e.g.:
![Screenshot from 2020-03-17 10-42-56](https://user-images.githubusercontent.com/18282228/76843610-587af100-683c-11ea-8d90-fffbeedc8f54.png)

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.3 |
| React | 16.13 |
| System | Ubuntu 18.04 |
| Browser | Firefox |

---
This bug originally was found in v1.8.5 but the error also occurs  in 2.x, there the labels are completely misplaced (inside instead of right) -> simply modify the version in the example. E.g. see picture (same code but version 2.0.0-beta.3): 
![Screenshot from 2020-03-17 10-46-16](https://user-images.githubusercontent.com/18282228/76843804-9a0b9c00-683c-11ea-8a74-cc641a1163a6.png)

**Comment by xile611** [comment]
@kaikun213 I can't get the problem. Can you add more description?

**Comment by kaikun213** [comment]
@xile611 added further description and pictures. The labels could use the full width to avoid messy labels at the bottom when there are many funnel channels, but somehow are related to the funnel-size.
