### ISSUE TITLE
Allow custom labels for radar chart levels instead of just numbers. 

### ISSUE THREAD

**Issue by thedeadline** [recharts/recharts#2057]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to indicate severity levels of a data group: none, mild, moderate, severe, highly severe instead of just values from 1 to 100 

### What does the proposed API look like?
Perhaps a toggle for custom labels that allow you to enter an array of strings that map each level's labels to the index of the array.

**Comment by xile611** [comment]
@thedeadline Please add a demo to reproduce your case.
