### ISSUE TITLE
Combined stacked bar

### ISSUE THREAD

**Issue by AlexHodovas** [recharts/recharts#2058]
Please help me

my dataForChart 
<img width="595" alt="изображение" src="https://user-images.githubusercontent.com/55617181/76956820-6b192700-691d-11ea-9e38-75947cf247be.png">

my JSX

`      {
            dataForChart.map(hour => (
              hour.tasks.map(task => (
                <Bar dataKey={Object.keys(task)[0]} barSize={20} stackId="a" fill={task.taskColor} />  
              )
              )
            ))
          } `

How to build a stacked bar with this dataForChart?

**Comment by xile611** [comment]
Please open a new issue follow the issue guide.
