### ISSUE TITLE
Log scale doesn't with with AreaChart

### ISSUE THREAD

**Issue by goleary** [recharts/recharts#2060]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/21qryp5v/](https://jsfiddle.net/21qryp5v/)

### Steps to reproduce
try to use log scale on any area chart

### What is expected?
log scale should function or report an error if there is one

### What is actually happening?
nothing is displayed on the chart.

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.4 |
| React | 15.6.2 |
| System | windows 10 |
| Browser | chrome |

**Comment by xile611** [comment]
@goleary Please follow the issue guide to create a new issue. jsfiddle is so slow for us. Thanks.

**Comment by goleary** [comment]
I did follow the guide. It might be useful to call out that you don't accept jsfiddle repros in the guide so contributor time isn't wasted in the future.

here is a codesandbox repro: https://codesandbox.io/s/recharts-issue-template-x045u
