### ISSUE TITLE
Log scale doesn't work with AreaChart

### ISSUE THREAD

**Issue by goleary** [recharts/recharts#2061]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-x045u)

### Steps to reproduce
try to use log scale on any area chart

### What is expected?
log scale should function or report an error if there is one

### What is actually happening?
nothing is displayed on the chart.

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.4 |
| React | 15.6.2 |
| System | windows 10 |
| Browser | chrome |

---
same as #2060

**Comment by ckifer** [comment]
Probably looking for `scaleSymLog` instead of `log` - we should probably remove the log type and use symlog instead

https://codesandbox.io/s/recharts-issue-template-forked-mhhk86?file=/src/index.js

You can provide your own symlog function from d3-scale
