### ISSUE TITLE
Switch data by date range

### ISSUE THREAD

**Issue by tengemakers** [recharts/recharts#2063]
Hello. Maybe anyone faced this. I have prev and next buttons, and onclick I want to change current weeks/month. Probably, slicing array can be a good option, but not sure
![image](https://user-images.githubusercontent.com/56729794/77039579-72edcf80-69e0-11ea-9c23-a1b95bcb604e.png)
The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.

---

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

**Comment by xile611** [comment]
Please open an issue follow the issue guide.
