### ISSUE TITLE
Y-axis ticks should start from top instead of center

### ISSUE THREAD

**Issue by sandipgp** [recharts/recharts#2065]
## Do you want to request a feature or report a bug?
Issue
## What is the current behavior?
I have implemented area graph with reponsive container where Y-axis is in left side. 
So if there is only one value to be plottted it alwas start fron center which should start from top.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
I tried various options from the scale property but didnt work.

## What is the expected behavior?
It should start from top
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
^2.0.0-beta.1

**Comment by xile611** [comment]
Please open an issue follow the issue guide.
