### ISSUE TITLE
Feature request: Possibility to treat 0 as null in log scale

### ISSUE THREAD

**Issue by villesau** [recharts/recharts#2066]
- [x ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Often times log scale has 0 values which needs to be handled separately. Would be super helpful if there would be option to treat 0 as nulls in logarithmic scale.

I believe this is very common problem and recharts does not give _any_ help when hitting this problem., it just leaves the chart blank when it probably should fail loudly instead. It's always hours of googling at worst to figure out what is wrong.

### What does the proposed API look like?

```
<YAxis scale="log" zeroAsNull={true} dataKey="datakey" domain={['dataMin', dataMaxValue   10]} unit={' '   t('person') } tick={{ fontSize: 12 }} name={t("cases")} />
```

This could be automated like:

```
<YAxis scale={isLog ? 'log': 'linear'} zeroAsNull={isLog ? true: false} dataKey="datakey" domain={['dataMin', dataMaxValue   10]} unit={' '   t('person') } tick={{ fontSize: 12 }} name={t("cases")} />
```

**Comment by xile611** [comment]
Please open a new issue follow the issue guide.

**Comment by villesau** [comment]
@xile611 I'm sorry if something was missing, but I _did_ open the issue using the guide. What's missing from the issue?
