### ISSUE TITLE
How to create custom cursor(I am looking for cursor similar to one we get when we use bar charts) in Composed Charts

### ISSUE THREAD

**Issue by reactssgcharts** [recharts/recharts#2070]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/test-recharts-barchart-with-brush-and-tilted-x-axis-labels-kvlcw)

### Steps to reproduce
Changing the cursor

### What is expected?
.

### What is actually happening?
No change when custom element is given

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.5 |
| React | 16.8 |
| System | Windows |
| Browser | Chrome |

**Comment by sky172839465** [comment]
Hi, is there have any solution or workaround?
Should we calcuate width when it is inside `ComposedChart` ?

<img width="499" alt="Screen Shot 2020-05-13 at 4 59 22 PM" src="https://user-images.githubusercontent.com/9082423/81792789-1d92f200-953b-11ea-89ce-1e9979110004.png">

<a href="https://codesandbox.io/s/rechart-compose-bar-and-line-demo-gpxbt?file=/src/DemoChart.js:577-590">
<img src="https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667">
</a>
