### ISSUE TITLE
Y-axis labels are incorrect when using "dataMin" and "dataMax"

### ISSUE THREAD

**Issue by jakeleventhal** [recharts/recharts#2073]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-c8dcg)

### Steps to reproduce
All that was added here was the "domain" prop

### What is expected?
The y-axis labels show scale at regular, consistent intervals and not show crazy precision.

### What is actually happening?
The y-axis labels are showing values that scale at irregular intervals and show with way more precision than is necessary.

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.13.1 |
| System | macOS (10.15.4) |
| Browser | Chrome (80.0.3987.149) |

**Comment by xile611** [comment]
@jakeleventhal It's the right behavior. When you specify the domain, the scale will just respect your domain.

**Comment by jakeleventhal** [comment]
Is there not a way to specify precision and have consistent intervals on the y-axis?

**Comment by gaurav5430** [comment]
@xile611 how does this behaviour work with `tickCount` ? 
It seems the `tickCount` is not respected as well, when you specify `domain`
