### ISSUE TITLE
Mistake in the documentation for the Line component strokeWidth property

### ISSUE THREAD

**Issue by carbonid1** [recharts/recharts#2075]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://recharts.org/en-US/api/Line#strokeWidth](http://recharts.org/en-US/api/Line#strokeWidth)

### Steps to reproduce
Open the link, check the documentation for the strokeWith. The format is the same as for the points property.

### What is expected?
 I guess the format should be removed at all.

### What is actually happening?
A user can see the format which confuses.

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.5 |
| React | - |
| System | Ubuntu 19 |
| Browser | Google Chrome Version 80.0.3987.149 (Official Build) (64-bit) |

**Comment by xile611** [comment]
PR of recharts.org is welcome.
