### ISSUE TITLE
Warning when using custom svg in Tooltips cursor prop

### ISSUE THREAD

**Issue by mkaraula** [recharts/recharts#2076]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/floral-shape-fxun9)

### Steps to reproduce
- Using a custom `svg` in  `<Tooltip />`'s `cursor` prop,
- Hover over the chart to make the Tooltip appear

### What is expected?
No warning Message

### What is actually happening?
A warning Message: 
```
Warning: React does not recognize the `brushBottom` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `brushbottom` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in svg (at App.js:35)
    in svg (created by Surface)
    in Surface (created by BarChart)
    in div (created by BarChart)
    in BarChart (at App.js:24)
    in App (at src/index.js:9)
    in StrictMode (at src/index.js:8)
```

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.5 |
| React | 16.12.0 |
| System | OSX 10.14.6 |
| Browser | Firefox 74.0 |

---
I am using a custom svg inside the Tooltips cursor prop (because I could not figure out how to change the color of the box that appears when hovering over a Bar). It seems like that recharts is giving the svg an attribute `brushBottom` which causes a warning in the Browser console.

**Comment by xile611** [comment]
@mkaraula you can use a customized Component to fix this.
