### ISSUE TITLE
Barchart X-axis padding not working

### ISSUE THREAD

**Issue by Tratten** [recharts/recharts#2077]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-1z6vg)

### Steps to reproduce
The issue can be seen directly on the link to the reproduction. It's clearly visible that the spacing between the first vertical grid line and the second grid line is much smaller than the spacing between the second grid line and the third grid line. Adjusting the padding of the X-axis or Cartesian-grid does not change anything.

### What is expected?
I want the graph to have equal spacing between the grid lines inside the entire graph. Now the spacing between the first grid line and the second grid line as well as the second last grid line and the last grid line is smaller than the spacing between the rest of the gridlines. Trying to solve it I added padding to the X-axis/Cartesian-grid but it did not change anything at all. I also thought about using domain but it does not seem applicable when using string data and I also want initial and ending spacing for the graph and therefore don't want to use scale="point".

### What is actually happening?
Nothing. I thought adding padding to the X-axis/Cartesian-grid would move the bars/grid lines sideways.

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.5 |
| React | 16.13.0 |
| System | macOS Catalina Version 10.15.3 |
| Browser | Chrome Version 80.0.3987.149 |

---
I wanted the bar chart graph to have equal spacing between the vertical grid lines and their bars for the entire graph but I don't want bars at the beginner and ending grid lines.

**Comment by xile611** [comment]
It's the default behavior, not a bug.

**Comment by Tratten** [comment]
So there is no solution available for achieving equal spacing?

**Comment by vtarelkin** [comment]
@Tratten have you find the solution?
