### ISSUE TITLE
Enable narrator to read the axis information along with the values

### ISSUE THREAD

**Issue by XianghanWang** [recharts/recharts#2078]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-bn8qc)

### Steps to reproduce
open the site in edge, use narrator scan mode to read the chart, it reads "0 6 12 18 0 ...". 

### What is expected?
It can read more information like x-axis or y-axis on what the values are about.

### What is actually happening?
it only read the values in x-axis or y-axis.

| Environment | Info |
|---|---|
| Recharts | v1.8.3 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | edge |

---
could you help check if there is a way to workaround it? if not, could you help confirm it is an issue in recharts? our policy requires the confirmation to file exclusion. thanks.

**Comment by xile611** [comment]
@XianghanWang It's not a bug of recharts. maybe you can submit a pr to make recharts work better in narrator.
