### ISSUE TITLE
Scatter with type=category X axis does not stack values

### ISSUE THREAD

**Issue by javierjavier** [recharts/recharts#2079]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-fgkpu)

### Steps to reproduce
See minimal repro. Use a Scatter with a type=category axis, and data with multiple points for a category. Also repros in 2.0.0-beta.5 per codesandbox.io.

### What is expected?
values with same category value should be stacked

### What is actually happening?
values with same category value are rendered separately, a new column (with the repeated category name) for each

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.8.6 |
| System | MacOS 10.15.3 |
| Browser | Chrome 80 |

**Comment by xile611** [comment]
![image](https://user-images.githubusercontent.com/6111424/79421541-99a62280-7fed-11ea-95fd-8da555932eff.png)
 
set `allowDuplicatedCategory={false}` to change the default behavior.
