### ISSUE TITLE
Spelling error of AniamtionDecorator

### ISSUE THREAD

**Issue by SachaG** [recharts/recharts#208]
Small typo here: https://github.com/recharts/recharts/blob/dd7b4b19892a22b7bbfec022f701656b67ef8ec6/src/util/AnimationDecorator.js#L5

**Comment by xile611** [comment]
@SachaG  I don't what's the problem?

**Comment by SachaG** [comment]
The spelling of `AniamtionDecorator`.

**Comment by SachaG** [comment]
BTW let me know if you want me to open a PR for this.

**Comment by xile611** [comment]
@SachaG Got it! Thank you!
