### ISSUE TITLE
ReferenceDot not appearing on ScatterChart

### ISSUE THREAD

**Issue by JoeKlimcak** [recharts/recharts#2080]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-uqxdb)

### Steps to reproduce
Adding a ReferenceDot into ScatterChart doesn't work

### What is expected?
ReferenceDot should show

### What is actually happening?
It's missing 

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.5 |
| React | react@16.12.0 |
| System | macOS Catalina 10.15.2 |
| Browser | Firefox 72.0.2 |

**Comment by xile611** [comment]
![image](https://user-images.githubusercontent.com/6111424/79430265-41761d00-7ffb-11ea-98c2-589085138720.png)
when you use a categorical scale, the value should in the domain of this scale .
`2019-01-01` is not a validate value for the scale.
