### ISSUE TITLE
Asynchronously loaded data breaks animation in graph leading to dots not showing up

### ISSUE THREAD

**Issue by no-itsbackpack** [recharts/recharts#2081]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/distracted-villani-qybyx)

### Steps to reproduce
Hover over the graph and no animation is triggered

### What is expected?
- Graph to be animated
- Active and non-active dots to show up on Line
- Tooltip to animate on hover

### What is actually happening?
- Graph does not animate
- Dots do not show up on <Line />
- Active dots are not triggered on <Line />
- Tooltip does not animate

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.5 |
| React | react@16.12.0 |
| System | macOS Catalina 10.15.2 |
| Browser | Version 80.0.3987.149 |

---
- Commenting out `onMouseMove` on the LineGraph seems to fix the animation issue but having async data still breaks the graph
- There are similar issues that have been closed in the past, I was wondering if the main issue was actually fixed or if those issues were closed due to being stage?
  - https://github.com/recharts/recharts/issues/789
  - https://github.com/recharts/recharts/issues/375
  - https://github.com/recharts/recharts/issues/1259
there are a couple others but these should do

**Comment by xile611** [comment]
@no-itsbackpack 

the following behavior is right
* Graph does not animate
* Dots do not show up on
* Tooltip does not animate

but he behavior of active dot is not right.

**Comment by Gekctek** [comment]
I also experience this bug. No dots show up if the chart changes in mid animation. Inital load is fine. Turning off animation, the dots always show up just fine

**Comment by grouls** [comment]
Experiencing this issue also, setting isAnimationActive to false allows the dots to show correctly as mentioned above. 

I did notice that docking Chrome Dev Tools to the right or left position strangely seems to finish the animation. Not sure if that will help in identifying the issue but I thought I'd share anyway.

**Comment by Alastair-L** [comment]
Having this issue too. I noticed that onAnimationStart fires, but never onAnimationEnd, not sure if that's relevant either...

**Comment by xile611** [comment]
Wrong used react! 
every time you update the state `newCount`, the data of chart is a new instance, the chart will be updated.
`Chart` should be updated when needed.

**Comment by PatrickInFrontEnd** [comment]
I have encountered a similar issue. Try to wrap your component via `React.memo()` It worked for me.

**Comment by ckifer** [comment]
this seems fixed when upgrading the sandbox to latest version
https://codesandbox.io/s/silent-microservice-0z2pcz
