### ISSUE TITLE
Focus and keyboard event handlers?

### ISSUE THREAD

**Issue by catherinephamiss** [recharts/recharts#2085]
I'm trying to make charts that are fully keyboard accessible. In addition to the typescript-related  tabIndex/role issue that I've opened (https://github.com/recharts/recharts/issues/2084), I'm running into other problems. Mainly, components only have click and mouse event handlers, but do not have focus or keyboard event handlers. Since recharts does not support wrapping components, I'm currently not able to make my charts keyboard accessible. Any plans to add support for these event handlers in the future? Any workarounds I can use in the mean time?

Using the following versions:
Recharts: 1.8.5
React: 16.10.2
Typescript: 3.6.3

**Comment by mvernier-fuze** [comment]
I'm running into the same issue as @catherinephamiss. 

@xile611, could you please provide more details on why this issue was closed without any further comments? Is keyboard support not planned for Recharts anytime soon? Thanks.

**Comment by scottcarol** [comment]
This is also something that would be valuable for my project. @xile611 would you be open to a PR in the future adding this feature if someone was interested in working on it?

**Comment by ckifer** [comment]
@scottcarol for sure if a PR was opened and being worked on it would be great as this is probably something that @xile611 wasn't planning on working on himself though I can't speak for him at all. I've just kinda been helping respond to and tag issues when I can, but don't have the time to implement something like this either. Not sure why the issue was closed originally.

**Comment by scottcarol** [comment]
@ckifer thanks for the info and quick response!

**Comment by mgifford** [comment]
Just wanted to say that although this is an important accessibility issue, we also need to be thinking about better access for smartphone and tablet users. Hover works great when you have a mouse, but is just one way that we interact with the web these days.
