### ISSUE TITLE
Unnable to install: zlib error

### ISSUE THREAD

**Issue by dmytro-shchurov** [recharts/recharts#2086]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
shell console

### Steps to reproduce
Specify "recharts": "2.0.0-beta.5", in your package.json and Run $npm install

### What is expected?
Beta version to be installed

### What is actually happening?
 silly fetchPackageMetaData error for recharts@2.0.0-beta.5 zlib: unexpected end of file

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.5 |
| React | ^16.12.0 |
| System | Win 10 x64 |
| Browser | Chrome latest |

**Comment by dmytro-shchurov** [comment]
npm cache has been cleaned up

**Comment by xile611** [comment]
Everything is ok for me.
