### ISSUE TITLE
Labellist is automatically left aligned and cannot be customized

### ISSUE THREAD

**Issue by tinkermachine** [recharts/recharts#2088]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://recharts.org/en-US/api/Label](https://recharts.org/en-US/api/Label)

### Steps to reproduce
Execute example code provided in the docs for Label

### What is expected?
Labels on bar chart from the Labellist definition to be aligned correctly

### What is actually happening?
Labels on bar chart are left aligned and not centered. Position is top.

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.5 |
| React | 16.12.0 |
| System | Ubuntu 18.04 |
| Browser | Chrome 80.0.3987.163 |

**Comment by tinkermachine** [comment]
Image below shows the issue.

![React App 4-7-2020 7-41-18 PM](https://user-images.githubusercontent.com/29440958/78739183-941f4d00-7908-11ea-8e5a-2f5c9f703658.png)

**Comment by xile611** [comment]
Please reopen a new issue follow the issue guide, with a reproduce online link.
