### ISSUE TITLE
Extra grid line rendering in AreaChart when YAxis ticks customized 

### ISSUE THREAD

**Issue by cenxky** [recharts/recharts#2089]
Recharts Version: 1.8.5

Screenshot:

![image](https://user-images.githubusercontent.com/10070670/78743369-fde33980-7990-11ea-93d5-e430a2cc55fe.png)

[View on Codesandbox](https://codesandbox.io/s/zealous-feynman-c5wio?file=/src/Chart.js)

**Comment by xile611** [comment]
@cenxky  You should fix the domain to be `[0, 5]`.

**Comment by ersefuril** [comment]
Manually setting the `domain` didn't help, the grid is always adding an extra line.
In this example : 
```domain={[0, 70]}```

![Screenshot 2020-05-06 at 14 35 45](https://user-images.githubusercontent.com/4835854/81177391-e22a7d80-8fa6-11ea-919a-5721c7eddf50.png)

Any idea ?
