### ISSUE TITLE
Ability to position the Pie sectors

### ISSUE THREAD

**Issue by Gunner17** [recharts/recharts#2090]
When I render my pie chart, the biggest slice/sector gets positioned randomly. Example: Please see the **16.9% (in blue)** sector in the screenshot below.

<img width="456" alt="Default rendering" src="https://user-images.githubusercontent.com/11354728/78744637-eff0d280-7916-11ea-86e6-1516dc0fdb52.png">

Instead, can I start this sector from the midpoint of the Pie, like the following screenshot? Is there a way to achieve this through the current API?

<img width="699" alt="Screen Shot 2020-04-07 at 9 26 01 PM" src="https://user-images.githubusercontent.com/11354728/78744723-2af30600-7917-11ea-86da-8817aa5332a0.png">

**Comment by mariopeixoto** [comment]
Sort the data by value descending, and use startAngle={180} endAngle={-180}

**Comment by Gunner17** [comment]
Solved! Thanks @mariopeixoto.
