### ISSUE TITLE
strokeDashArray props isn't mentioned in Line Component API Docs

### ISSUE THREAD

**Issue by MrPeker** [recharts/recharts#2094]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
strokeDashArray props isn't mentioned in Line Component API Docs. I think we need more detailed API Docs for Line component.

### What does the proposed API look like?
strokeDashArray

**Comment by xile611** [comment]
PR for https://github.com/recharts/recharts.org is welcome
