### ISSUE TITLE
Bar radius 

### ISSUE THREAD

**Issue by antonshulyak** [recharts/recharts#2098]
The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.
![image](https://user-images.githubusercontent.com/58746305/79362964-edfac500-7f4f-11ea-9794-55d151d04e74.png)
How i can use 'radius' for my bar, i want to get radius for first and last bar, but if last bar value === 0 i cant do this
---

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

**Comment by Fellhalore** [comment]
I want to put radius to last and first with dynamic data

**Comment by xile611** [comment]
You can use customized `shape` to handle your case.
