### ISSUE TITLE
Latest version of React ?

### ISSUE THREAD

**Issue by checkraiser** [recharts/recharts#21]
I'm using React 0.14.3.
Could you please update the library to meet dependency version ?

**Comment by Cloudo** [comment]
Current version support react 0.14.x version.
Can you provide error message?

**Comment by checkraiser** [comment]
My error is:
```
├── UNMET PEER DEPENDENCY react@^0.14.0
├── UNMET PEER DEPENDENCY react-dom@^0.14.0
└─┬ recharts@0.5.2
  ├── UNMET PEER DEPENDENCY react@^0.14.0
  └── UNMET PEER DEPENDENCY react-dom@^0.14.0
```

**Comment by Cloudo** [comment]
It seems like you specify exact version of react or react-aadons-*:
    "react": "0.14.3",
    "react-dom": "0.14.3"

Try to add caret like so
    "react": "^0.14.3",
    "react-dom": "^0.14.3"

If not, please share your dependencies sections of `package.json`

**Comment by arcthur** [comment]
Hi, @checkraiser 
please share `package.json`, we could be check the problems.
 
Thank @Cloudo for help!

**Comment by checkraiser** [comment]
Thank all. Just my mistake :D. It works fine now.

**Comment by canfiax** [comment]
@checkraiser what was the solution?

**Comment by Ohar** [comment]
@checkraiser How do you fix it?

**Comment by checkraiser** [comment]
@Ohar: As i remember, we should remove the react dependency from recharts, and use react depdency independently.

**Comment by mohitsharma01** [comment]
I resolved this issue saying **requires a peer of react@>=0.14.0 but none was installed.** by uninstalling the react and react-dom and then locally install the react@0.14.0 and react-dom@0.14.0..
after this, I was able to install my module which had react@>=0.14.0 added as "peerDependencies": {
    "react": ">=0.14.0"
  },.
I uninstalled and installed the react with the latest version again, It worked for me.

**Comment by edwin-alvarez** [comment]
I had the same problem wasted few hrs. I after upgrading NONE and NPM it worked. also trying using PowerShell
