### ISSUE TITLE
Option for disabling inline styles?

### ISSUE THREAD

**Issue by SachaG** [recharts/recharts#210]
While I appreciate that Recharts comes with a set of pre-made inline styles to speed up the process, there's some cases where you'll want to customize your chart with your own set of styles. 

So I think it'd be a good idea to always have an option to completely disable inline styles, for components such as `<Legend/>` for example.

**Comment by xile611** [comment]
@SachaG  You can set the style of Legend by overwriting the default style.

**Comment by SachaG** [comment]
It's good that you can do this, but I still think you should be able to disable inline styles altogether. A practical use case is media queries: maybe you want to style the legend (or other elements) differently on mobile and on desktop. You can't do that if these elements have their own inline styles. 

I think as a general best practice, any component that has inline styles should also offer an option to disable them. i.e. something like

```
<MyComponent style={ this.props.disableStyles ? null : inlineStyles } />
```

**Comment by xile611** [comment]
@SachaG We use inline style to style the legend, and the style is most general supported. I don't know the problem of inline style we used now. Can you give a more clear example ?

**Comment by SachaG** [comment]
The problem comes from CSS specificity: 

>Inline styles added to an element (e.g., style="font-weight:bold") always overwrite any styles in external stylesheets and thus can be thought of as having the highest specificity.

https://developer.mozilla.org/en/docs/Web/CSS/Specificity

Practically speaking, this can be a problem if you'd like to overwrite one of the inline styles with a style from your own stylesheet, for a responsive mobile version for example. 

So let's say I want the label to be `position:static` on desktop and `position:absolute` on mobile, with the current system I cannot do that. 

So what I'm suggesting is adding a `disableStyle` option to the `Legend` component that would simply make it have no inline styles at all. I think it would be a relatively easy fix, and I would be happy to submit a PR for it.

**Comment by neekey** [comment]
I total understand the problem that @SachaG brought up, inline styles make it hard to overwrite just using CSS (may need `!important`), but I don't think an API named "disableStyles" is an answer for that. 

@xile611 instead of inline styles, have you thought about using `CSS-Module` ? which should be easier to maintain styles and will not cause overwrite your default style a problem.

**Comment by Eric24** [comment]
+1 for CSS-Modules support.

**Comment by xile611** [comment]
CSS-Modules will bring a lot of webpack configurations, It seems messy.

**Comment by Eric24** [comment]
That could be. I'll think more about it.

**Comment by SachaG** [comment]
It looks like https://github.com/styled-components/styled-components is doing a lot of things right and it was made with theming in mind.

**Comment by Eric24** [comment]
I'm still not sure what the right answer is, but on this same topic, it would be very useful to be able to set the data plot components (area, bar, line, etc.) styles (stroke, fill, stroke-width, etc.) from a style sheet, rather than specifying each attribute in-line.

That way, the config for the components needs only to specify a CSS class (something like "chart-data-series-1"). This would be particularly useful when it comes to themes, where the data plot styles need to be easily modified by the underlying theme, without having to change the component configs.

**Comment by gkatsanos** [comment]
as a follow-up to https://github.com/recharts/recharts/issues/210#issuecomment-285980467 , I also would like to ask if the class that I see generated from the components in the SVG code can be used in the stylesheets to style the individual object of a chart. (the value circles etc).
For example, this seems to work in the inspector: 
![image](https://cloud.githubusercontent.com/assets/1768834/26224116/4ebf0646-3c21-11e7-9d0a-cb26beb22376.png)

**Comment by swbullis** [comment]
For the next guy who is trying to invalidate the position absolute property and place it in a style sheet here is what I used.

`<Legend
          content={legendJSX} {...legend} wrapperStyle={/*
            NOTE: because Recharts doesn't currently support disabling of inline styles we need to
            do some trickery to invalidate the position property 
            https://github.com/recharts/recharts/issues/210 */
          { position: null }}
        />`

and then in your stylesheet your can do 
`@media (min-width: 801px) { 
     .recharts-legend-wrapper {
        position: absolute;
    }
}
@media (max-width: 800px) { 
     .recharts-legend-wrapper {
        position: sticky;
    }
}
`
