### ISSUE TITLE
Hide overlapping labels in Pie chart

### ISSUE THREAD

**Issue by Gunner17** [recharts/recharts#2101]
Is there a way to hide the overlapping labels in Pie chart? My requirement is that if two or more labels are overlapping in Pie, then they should not be shown. 

**I do not want any kind of adjustments and place those overlapping labels in a customized way to avoid overlaps**, simply want to hide them in case of overlap.

<img width="200" alt="Screen Shot 2020-04-20 at 11 52 04 AM" src="https://user-images.githubusercontent.com/11354728/79841434-4248df00-836c-11ea-984d-5fde330570cd.png">

**Comment by xile611** [comment]
You can use customized label to hide the labels when the angle is to small.

**Comment by meghanmullally** [comment]
> Is there a way to hide the overlapping labels in Pie chart? My requirement is that if two or more labels are overlapping in Pie, then they should not be shown.
> 
> **I do not want any kind of adjustments and place those overlapping labels in a customized way to avoid overlaps**, simply want to hide them in case of overlap.
> 
> <img alt="Screen Shot 2020-04-20 at 11 52 04 AM" width="200" src="https://user-images.githubusercontent.com/11354728/79841434-4248df00-836c-11ea-984d-5fde330570cd.png">

I've been looking into this as well and came across this thread, hope it helps! https://github.com/recharts/recharts/issues/490
