### ISSUE TITLE
componentWillReceiveProps

### ISSUE THREAD

**Issue by rymkapro** [recharts/recharts#2102]
Hi. I get a warning:
`Warning: componentWillReceiveProps has been renamed, and is not recommended for use. Please update the following components: Pie, PieChart` and others, I suppose.

Do you plan to update package?

Thanks!

**Comment by saernz** [comment]
Yeah I'm getting the same problem but with the following components: `Bar, BarChart`.

**Comment by Vyctor661** [comment]
I guess it's because it uses old class components methods (componentWillReceiveProps), if react will decide that they no longer want that method in their code, every rechart will probably break. One solution is to update all the components, preferably using functional components in recharts.

**Comment by adamdharrington** [comment]
By the looks of it that will be a major update because it will remove support for React <16 so I wouldn't expect to see it in the v1 branch. The master (v2 beta) branch has fully rewritten many of the components and doesn't seem to have any unsafe lifecycle methods; I don't know when that's on the cards for but that is React 16+ only.

**Comment by githubloverforever** [comment]
Try Reacharts 2.0.0-beta.5

**Comment by rymkapro** [comment]
Thanks for replying!

**Comment by gaurav5430** [comment]
@xile611 @githubloverforever I can still see UNSAFE methods in 2.0.0-beta.6 
I understand why the change to remove UNSAFE methods was reverted (https://github.com/recharts/recharts/pull/1905), but is there a plan to completely get rid of UNSAFE methods in 2.x ? https://github.com/recharts/recharts/issues/1910 does not mention this as part of the roadmap
