### ISSUE TITLE
Bullet Chart

### ISSUE THREAD

**Issue by manobalas** [recharts/recharts#2104]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Actually in Power Bi there is a plug in for bullet chart, and below is the url for that plugin,
most people need in this... 
https://youtu.be/mtvUNl9bMjA

### What does the proposed API look like?
https://youtu.be/mtvUNl9bMjA

**Comment by xile611** [comment]
You can use <BarChart /> to draw bullet chart
this is a [demo](https://codesandbox.io/s/recharts-issue-template-pui3o)

**Comment by Jomimoses** [comment]
> You can use to draw bullet chart this is a [demo](https://codesandbox.io/s/recharts-issue-template-pui3o)

How can we use this chart in a vertical layout like below
![image](https://github.com/recharts/recharts/assets/37336949/df30f933-6e48-4876-ad0b-3fdb3403b0fd)
