### ISSUE TITLE
Draw callback

### ISSUE THREAD

**Issue by acontreras89** [recharts/recharts#2106]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Being able to trigger a callback after initial render of charts finishes, specially useful when working with large datasets (in order to display spinners and whatnot)

### What does the proposed API look like?
Minimal example:
```
<ComposedChart onDraw={() => window.alert('Chart ready!')} />
```

**Comment by stefancon** [comment]
Can we get some info why this has been closed? I was looking for something similar and could only find onAnimationEnd, which is not very useful because it's only available on components and not the charts itself. If you are open to integrate this I am willing to help.

**Comment by NicolasJaussaud** [comment]
Do you have more informations about this feature ?

**Comment by dreit-p** [comment]
@xile611 , you closed this issue, but can you explain what is the best way to get to know when the data was rendered in the chart? A callback for this would be really useful. Currently, I have to make crutches.
