### ISSUE TITLE
Tooltips dont work properly when application zoom is changed

### ISSUE THREAD

**Issue by jakeleventhal** [recharts/recharts#2108]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-c4k1s?file=/public/index.html)

### Steps to reproduce
Drag your mouse along the graph and you will see that the graph thinks the mouse is to the left of where it actually is

### What is expected?
The tooltip should follow the mouse regardless of the zoom

### What is actually happening?
The tooltips are not appearing for the correct data points since the graph thinks the mouse is to the left

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.13.1 |
| System | macOS (10.15.4) |
| Browser | Chrome (80.0.3987.149) |

---
In the sandbox, the only thing i changed from the default recharts fork was add the following to index.html's root id:
```html
style="zoom:75%"
```

**Comment by dkimbriel** [comment]
I have been struggling with this issue too, and ended up using a custom tooltip component with a fixed position that used a custom event listener to detect the mouse position.

You will have to separately track the data to display in the tooltip using the useMouseEnter event handler provided by Recharts, and hide the tooltip using the useMouseLeave event handler.

Basically, use Recharts to track the content and open/close status of the tooltip and your own code to track the mouse position. If anyone is interested in an example, I can spin one up in CodeSandbox.

**Comment by linkTDP** [comment]
@dkimbriel if you can provide a CodeSandbox with an example it would be great :)

**Comment by jakeleventhal** [comment]
@dkimbriel would appreciate this! hopefully this isnt too difficult to get into recharts so no workaround is needed

**Comment by dkimbriel** [comment]
Here is a simplified version of the solution that I have been using in my application:

useMousePosition.jsx is the event listener that I use to detect mouse position. It uses ClientX and ClientY from the document, which has been pretty reliable for me regardless of the zoom as long as your tooltip wrapper is somewhere in the application with access to the full window size.

CustomTooltip.jsx is the CustomTooltip provider that I have been using to pass down the functions openTooltip and closeTooltip to all of my Recharts components. The openTooltip accepts a content function that can translate the synthetic event provided by onMouseOver into the desired content. It also accepts a style argument that can be used to style the tooltip wrapper.

Hope that this helps!

[![Edit Recharts Custom Tooltip](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/silly-lederberg-iz33j?fontsize=14&hidenavigation=1&theme=dark)

**Comment by jakeleventhal** [comment]
Thanks for putting this together @dkimbriel. Unfortunately, when I try this, the tooltips doesn't seem to work properly. It jitters around.
![May-26-2020 22-09-10](https://user-images.githubusercontent.com/15133828/82969392-8cd9fe80-9f9d-11ea-9cde-0ceb7c17e4d6.gif)

**Comment by jakeleventhal** [comment]
bump on this? I am willing to negotiate paying someone to fix this if they can do it with expediency

**Comment by jakeleventhal** [comment]
bump?

**Comment by jakeleventhal** [comment]
is there anyone who can work on this?

**Comment by jakeleventhal** [comment]
bump

**Comment by BogdanH95** [comment]
I have an application zoom of 0.8 applied to the body and this is ruining all charts. The component think the mouse is to the left. 
Does anybody has a working solution for this issue?

**Comment by ckifer** [comment]
As per the mdn docs
, css zoom is a non standard css property https://developer.mozilla.org/en-US/docs/Web/CSS/zoom and should be avoided. Please try transform:scale

**Comment by BogdanH95** [comment]
This was the answer! Thank you, for the solution. By replacing the zoom property with transform scale, it works as expected. 
You rock dude!
