### ISSUE TITLE
Is there a way to add space between the axis and the graph?

### ISSUE THREAD

**Issue by jona-dushi** [recharts/recharts#2110]
See the image: 
![Screenshot from 2020-04-24 09-48-40](https://user-images.githubusercontent.com/54713531/80351362-80fdfe00-8872-11ea-9e75-fdc1aab2d35c.png)

I want to add space between the XAxis and the bars.
------
What I have achieved until now
![image](https://user-images.githubusercontent.com/54713531/80351546-d33f1f00-8872-11ea-9376-bf179d5b1893.png)

**Comment by xile611** [comment]
You can change the `padding` of `<YAxis />`.

[docs](http://recharts.org/en-US/api/YAxis#padding)

**Comment by jona-dushi** [comment]
Thank you.
