### ISSUE TITLE
[PIE-CHART] Keep padding gap parallel

### ISSUE THREAD

**Issue by tienzodi** [recharts/recharts#2111]
Hello guys,
I'm using option `paddingAngle` to set gap between pies. But I can't set gap's border parallel. Please check my image below.
Thank you.

<img width="302" alt="Screen Shot 2020-04-28 at 15 58 00" src="https://user-images.githubusercontent.com/21222786/80468732-c3563680-8969-11ea-9fdc-80f2a093894f.png">

**Comment by xile611** [comment]
`paddingAngle` will has a sector padding, not a parallel gap.
