### ISSUE TITLE
[Feature ask]drill down functionality

### ISSUE THREAD

**Issue by dukemai** [recharts/recharts#2113]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Hi guys, thanks for the great library. I am wondering the best practice to implement this feature drilldown in d3 within recharts

https://observablehq.com/@d3/hierarchical-bar-chart

do you guys have any suggestions if this feature is not yet implemented

### What does the proposed API look like?
https://observablehq.com/@d3/hierarchical-bar-chart

**Comment by xile611** [comment]
You can use `onClick` event to do this.
