### ISSUE TITLE
Composed Chart: Bars outside of x axis bounds

### ISSUE THREAD

**Issue by MarcusNotheis** [recharts/recharts#2114]
- [X] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-9j61q?file=/src/index.js)

### Steps to reproduce
Start the provided code sandbox.

### What is expected?
Bars should not grow outside of x axis bounds (like in `recharts@1.8.5`, if you downgrade to that version everything is working as expected).

### What is actually happening?
First and last bar is growing out of x axis bounds. Same occurs on the y axis if you choose a `vertical` layout.

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.5 |
| React | 16.13.1 (occurs also on older versions, e.g. 16.8.6) |
| System | macOS Catalina 10.15.4 |
| Browser | Chrome 81.0.4044.129 |

**Comment by xile611** [comment]
Please set the `<XAxis scale="band">` to change the default behavior.
![image](https://user-images.githubusercontent.com/6111424/81521719-9b5bcf80-937a-11ea-974e-892c0738ee91.png)

**Comment by Alphavader** [comment]
@xile611  thanks alot - searched an hour for this solution.
