### ISSUE TITLE
FunnelChart, Funnel and Sankey typings are not present in @types/recharts

### ISSUE THREAD

**Issue by salomonMuriel** [recharts/recharts#2115]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/recharts/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/recharts/index.d.ts)

### Steps to reproduce
Try to import any of the mentioned components into a new project.

### What is expected?
To be able to import the components

### What is actually happening?
Cant be imported due to no typing

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.5 |
| React | 16.13 |
| System | Ubuntu 18.04 |
| Browser | Chrome Stable |

**Comment by xile611** [comment]
recharts has use typescript to rewrite all the core code. You can remove the dependence of `@types/recharts` now.

**Comment by salomonMuriel** [comment]
Thanks!
