### ISSUE TITLE
Reference Line breaks when Lines have an assigned axis.

### ISSUE THREAD

**Issue by aflegel** [recharts/recharts#2116]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/alexgflegel/uym7f309/1/](https://jsfiddle.net/alexgflegel/uym7f309/1/)

### Steps to reproduce
Functional:
2 axis graph:
https://jsfiddle.net/alexgflegel/5unx4087/7/
With Line, 1 axis:
https://jsfiddle.net/alexgflegel/nxgduo83/4/
With Bug:
Line has assigned yAxisId:
https://jsfiddle.net/alexgflegel/mwd097sf/
Adding an xAxisId breaks the XAxis component (even if you add a type):
https://jsfiddle.net/alexgflegel/uym7f309/1/

### What is expected?
I expect a reference line to be drawn

### What is actually happening?
React reports a runtime error

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.13 |
| System | windows 10 |
| Browser | chrome@latest |

---
This is more difficult to solve in typescript but the original ticket (https://github.com/recharts/recharts/issues/1688) There were reports of a JavaScript workaround.

**Comment by xile611** [comment]
You can fix this to set the `xAxisId` of `<ReferenceLine>`

**Comment by aflegel** [comment]
Perhaps this a typescript error only then.

If I have an id on my xaxis and a dataKey I receive other errors:

>TypeError: Cannot read property 'type' of undefined

> 901 | if (axis.type === 'category') {

**Comment by PratikLunagaria** [comment]
Yes, I'm using this in TypeScript, too and I faced the same problem. So I tried
`<XAxis dataKey="km" xAxisId="myId" type="category"/>`
I tried giving type prop to XAxis and also tried with `type="number"` no luck so far. 
Needs further investigation there 🤔

**Comment by LuizHAP** [comment]
I'm facing this problem now, but I setted `xAxisId={1}` and `xAxisId="1"`, and in Reference Line

```
<ReferenceLine
  x="2022-01-25T22:25:58.4290008Z"
  xAxisId={1}
  stroke="red"
  label="now"
/>
```

But still get `TypeError: Cannot read properties of undefined (reading 'type')`

**Comment by LuizHAP** [comment]
> Yes, I'm using this in TypeScript, too and I faced the same problem. So I tried `<XAxis dataKey="km" xAxisId="myId" type="category"/>` I tried giving type prop to XAxis and also tried with `type="number"` no luck so far. Needs further investigation there thinking

Have you solved this problem?
