### ISSUE TITLE
Build Error: TS2769: No overload matches this call

### ISSUE THREAD

**Issue by jabberwo** [recharts/recharts#2117]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://See.build.steps](http://See.build.steps)

### Steps to reproduce
Simply followed the build steps under "dev build" on the github page:
$ git clone https://github.com/recharts/recharts.git
$ cd recharts
$ npm install
$ npm run build

### What is expected?
Expected "npm run build" to complete w/o errors and have a something I could demo (a storybook?).

### What is actually happening?
Build fails. 

ERROR in /home/chuck/Development/projects/recharts/src/cartesian/Scatter.tsx
./src/cartesian/Scatter.tsx
[tsl] ERROR in .../recharts/src/cartesian/Scatter.tsx(386,9)
      TS2769: No overload matches this call.

 I can't run demos.  I can't decide if I want to use recharts instead of react-vis in my project.  Needed to make a decision today :-(

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.5 |
| React | 16.8.6 |
| System | Ubuntu 18.04 |
| Browser | No browser |

**Comment by xile611** [comment]
Fixed. Please pull master.
