### ISSUE TITLE
Avoiding label collisions with stacked bar charts

### ISSUE THREAD

**Issue by SachaG** [recharts/recharts#212]
I'm running into the following problem with a stacked bar chart:

![https://d3vv6lp55qjaqc.cloudfront.net/items/1L2j0r220F0z0I2w1i0j/Screen%20Shot%202016-09-06%20at%206.45.26%20PM.png?X-CloudApp-Visitor-Id=01406470cd8cc4d8af4ff992d3ec662f&v=0a778b63](https://d3vv6lp55qjaqc.cloudfront.net/items/1L2j0r220F0z0I2w1i0j/Screen%20Shot%202016-09-06%20at%206.45.26%20PM.png?X-CloudApp-Visitor-Id=01406470cd8cc4d8af4ff992d3ec662f&v=0a778b63)

As you can see the labels overlap each other because the bars are too short. Ideally I would be able to offset a label if the one above is too close, but I'm not sure how to make labels know about each other's positions. 

Even if I used some kind of global array to hold the positions, the chart gets drawn from the bottom up which means the bottom label gets drawn before the top one… Any idea how I can work around this?

**Comment by SachaG** [comment]
OK, I found a solution that works alright. Here's a quick overview in case it helps others.

![https://d3vv6lp55qjaqc.cloudfront.net/items/3m361N3U0x3v371N0N2G/Screen%20Shot%202016-09-07%20at%209.04.49%20AM.png?X-CloudApp-Visitor-Id=01406470cd8cc4d8af4ff992d3ec662f&v=714785e6](https://d3vv6lp55qjaqc.cloudfront.net/items/3m361N3U0x3v371N0N2G/Screen%20Shot%202016-09-07%20at%209.04.49%20AM.png?X-CloudApp-Visitor-Id=01406470cd8cc4d8af4ff992d3ec662f&v=714785e6)

1. Initialize an empty two-dimensional array to hold all label coordinates:

```js
    const bars = 5
    const columns = data.length
    const coords = new Array(columns)
    for (let i = 0; i < columns; i++) {
      coords[i] = new Array(bars)
    }
```

2. Create getter and setter functions and pass them to each custom label component

```js
    const setCoords = (column, bar, coord) => {
      coords[column][bar] = coord
    }
    const getCoords = (column, bar) => coords[column][bar]
```

I'm also manually passing the current bar (i.e. row) number to each label.

3. Inside the component, compare the current label's y coordinate with the previous label's and offset it if needed. 

You can get the previous label by subtracting 1 from the current bar number and calling `getCoords`.

4. Call `setCoords` with the current label coordinates to make them available to the next one. 

I would love to know if there's a simpler way to do this, but for now it seems to work well enough.

**Comment by jochenberger** [comment]
This is also relevant for pie charts.

**Comment by xile611** [comment]
@SachaG Temporarily no simpler solution.

**Comment by SachaG** [comment]
There's actually one issue with my method: as you can see in the last two columns, the line for "1%" goes *behind* the blue bar. This is because of SVG elements stacks in the order they are drawn, and I don't think there's any way around it…

The best solution would be drawing all labels *after* all bars. But that would probably require some changes in the library itself.

**Comment by deadlyfingers** [comment]
@SachaG is the option for the lines pointing to small areas mentioned in the Brush component API or is this a custom format? I also have an issue of horizontal overlap - when using the Recharts Responsive Container the bar widths become too small for the text labels and they start to overlap horizontally.

**Comment by SachaG** [comment]
Sorry I don't use this library anymore. But as I remember it was all custom code back then.
