### ISSUE TITLE
npm run build failed

### ISSUE THREAD

**Issue by anant-k-singh** [recharts/recharts#2120]
The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.

---

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

---

Issue: Build failed
Error: No overload matches this call
Screenshot: ![image](https://user-images.githubusercontent.com/22440924/80914164-74444300-8d67-11ea-89a2-80982e47b9b3.png)

**Comment by 814k31** [comment]
I also received the issue

It doesnt exist in tag: 2.0

**Comment by pistach3** [comment]
Can confirm.

Installing recharts@1.8.5 fixed it for me.
