### ISSUE TITLE
Line chart taking extra height than the defined height of 160px

### ISSUE THREAD

**Issue by ankit-gupta1307** [recharts/recharts#2121]
## Do you want to request a feature or report a bug?
I want to report a bug.
## What is the current behavior?
I am drawing a line chart and gave the height of 160px and width of 437px, half of the graph is visible inside the box only.

## What is the expected behavior?
Expected behaviour is graph must fit inside the defined height and width.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
I am using recharts "1.8.5"
![Screenshot (41)](https://user-images.githubusercontent.com
![Screenshot (42)](https://user-images.githubusercontent.com/17529193/81185850-b8d21780-8fcf-11ea-8810-572844e0e0be.png)
/17529193/81185815-b079dc80-8fcf-11ea-966c-1966708f930f.png)

![Screenshot (38)](https://user-images.githubusercontent.com/17529193/81185639-7577a900-8fcf-11ea-826f-e5b5093f7e4e.png)

**Comment by xile611** [comment]
Please follow the issue guide to create a new issue!
