### ISSUE TITLE
Default padding in ComposedChart with bars is missing

### ISSUE THREAD

**Issue by Luisetelo** [recharts/recharts#2122]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/uyk9em5p/4/](https://jsfiddle.net/uyk9em5p/4/)

### Steps to reproduce
Just open the link you can see Page A column overlapping Y Axis

### What is expected?
[https://jsfiddle.net/tkv0u74L/](https://jsfiddle.net/tkv0u74L/)

To have padding on the columns to see the chart properly

### What is actually happening?
Looks like the padding is missing

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.5 |
| React | 16.12.0 |
| System | macOS Catalina 10.15.4 |
| Browser | Chrome Version 81.0.4044.129 (Official Build) (64-bit) |

**Comment by xile611** [comment]
You can change the `scale="band"` to change this behavior
