### ISSUE TITLE
Tooltip itemSorter is not working

### ISSUE THREAD

**Issue by oicramps** [recharts/recharts#2123]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/67L4tj8c/1/](https://jsfiddle.net/67L4tj8c/1/)

### Steps to reproduce
if I add the `itemSorter` with `() => 1` as a value, nothing happens. As the default value is `() => -1`, It should reverse the payload order, right?

### What is expected?
Tooltip payload with a reversed order

### What is actually happening?
The order still the same

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | ^16.11.0 |
| System | Ubuntu 18.04.4 LTS |
| Browser | Google Chrome 81.0.4044.129 |

**Comment by joselcvarela** [comment]
I was thinking I were having this exact issue but then I dig a little more and found out `itemSorter` doesn't work if `content` is defined.

**Comment by rajadain** [comment]
I'm also seeing this here: https://github.com/recharts/recharts/issues/1241#issuecomment-780330116. I don't have `content` defined anywhere.

**Comment by dohomi** [comment]
I don't think thats currently possible to invert the order, because the itemSorter payload does not include the original order

**Comment by ckifer** [comment]
In the code it looks like `itemSorter` is just the second parameter to Lodash _.sortBy https://www.geeksforgeeks.org/lodash-_-sortby-method/

This is really odd but I can invert the order by doing something like this 
`itemSorter={(item) => -Number(item.value) ?? 1}`

https://codesandbox.io/s/simple-line-chart-forked-fdjbmu?file=/src/App.tsx:993-1040

**Comment by dohomi** [comment]
@ckifer would your example not just sort desc to the item.value but not to the original order of the tooltip items?

**Comment by ckifer** [comment]
Confirming the above. See here https://github.com/recharts/recharts/blob/36f2f879a7908d62b4e6552f1ee5570d145eafd8/src/component/DefaultTooltipContent.tsx#L71-L102

If no itemSorter is specified it just does `payload.map` - I'll have to hunt for what that order is though

**Comment by dohomi** [comment]
@ckifer I use a `<BarChart/>` and the bars have the opposite colors as the tooltip result. Thanks pointing me into the right direction I will append the index value into the original payload that the _.sortBy has an identifier to sort correctly.

**Comment by ckifer** [comment]
Take a look at this issue as well https://github.com/recharts/recharts/issues/209

**Comment by ckifer** [comment]
Going to close this since this is explained above. Not sure what else there is to do
