### ISSUE TITLE
Application with recharts is crushing

### ISSUE THREAD

**Issue by KatDenisenko** [recharts/recharts#2125]
The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.
I am using recharts in my project  and sometimes at all pages where I am using recahrts components I have got an error, my app crushing then I am reinstalling node modules and it's start work. The similar error also appearing when I merge updates from staging branch to production, at staging it work good, but at production crushing. I am using recharts@1.7.1 version. I don't understand why this error is appeared and how to resolve it. How I can resolve this issue?

https://stackoverflow.com/questions/61268885/why-does-app-crush-with-recharts-components?noredirect=1#comment109023208_61268885
---

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
