### ISSUE TITLE
V2: Typescript Error when using angle and textAnchor prop on Cartesian Axis

### ISSUE THREAD

**Issue by mkaraula** [recharts/recharts#2128]
- [ X] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-zheu5)

### Steps to reproduce
1. Try to render `<XAxis dataKey="name" angle={-65} textAnchor="end" />` with Typescript 3.9
2. Observe Error 
```
Type '{ dataKey: string; angle: number; textAnchor: string; }' is not assignable to type 'IntrinsicAttributes & Pick<Props, "ticks" | "minTickGap" | "interval" | "dataKey" | "tick" | "axisLine" | "tickLine" | "tickSize" | "tickFormatter" | ... 4 more ... | "AxisComp"> & Partial<...> & Partial<...>'.
```
3. Be frustrated about it

### What is expected?
It should be possible to use the angle and textAnchor prop in Typescript

### What is actually happening?
I guess these props angle and textAnchor are Missing in the `BaseAxisProps` in `/src/util/types.ts`. If its fine with you I could open a PR for it. 

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.6 |
| React | React 16.13.1 |
| System | macOS Mojave |
| Browser | Firefox 76.01 |

---
Sorry but I could not create a proper minimal reproduction because the provided template for the codesandbox does not support Typescript but I guess the Issue is quite clear.

**Comment by justseeseesee** [comment]
the yAxis missing the prop 'angle'
