### ISSUE TITLE
Area fill by value

### ISSUE THREAD

**Issue by AminAshtiani** [recharts/recharts#2129]
Hi everyone

I want to draw an area chart that fills the area under the stroke with red if data is lower than 1 and file the area under the stroke with green if data is greater than 1

I looked at this example, but it only works with positive/negative data and didn't fill the area under the stroke
http://recharts.org/en-US/examples/AreaChartFillByValue

**Comment by xile611** [comment]
@AminAshtiani I think it's similar to the demo.
