### ISSUE TITLE
Additional clarification using ResponsiveContiner

### ISSUE THREAD

**Issue by reggie3** [recharts/recharts#213]
Preview
Following along the lines of the ResponsiveContainer example at http://recharts.org/api#ResponsiveContainer I substituted a BarChart for the LineChart shown in the example. However, this did not result in a responsive BarChart.

ResposiveContainer creates a ContentContainer element from the react-container-dimensions library. The react-container-dimensions documentation states that "Children component will receive top, right, bottom, left, width, height as props".

It was only after specifying my BarChart's height and width as shown below that the BarChart became responsive.

height={this.props.height}
width={this.props.width}
Is this the correct usage of ResponsiveContainer? Nothing along these lines is mentioned in the example documentation at the recharts.org website.

**Comment by xile611** [comment]
@reggie3 Can you give an jsfiddle example? You can check [#135](https://github.com/recharts/recharts/issues/135) for some discussion of ResponsiveContainer.

**Comment by reggie3** [comment]
I will try to create an example this weekend.  Hopefully, I will have something to show in the next few days.

**Comment by reggie3** [comment]
I'm unable to reproduce the problem I had using jsfiddle.   I'm pretty sure the original problem was due to something on my end so I will close this issue.
