### ISSUE TITLE
activeDot is showing behind the Area chart

### ISSUE THREAD

**Issue by vcojukwu** [recharts/recharts#2131]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/2t3ke0o4/](https://jsfiddle.net/2t3ke0o4/)

### Steps to reproduce
Create a staked area chart were each area has `fillOpacity={1}`. Hover over the chart

### What is expected?
The activeDot should display over the chart

### What is actually happening?
The activeDot is hidden behind the chart

![image](https://user-images.githubusercontent.com/4396576/82171428-23127400-987c-11ea-8968-751eb57c1089.png)

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.6 |
| React | 16.13.0 |
| System | macOS Catalina |
| Browser | Google Chrome Version 81.0.4044.138 (Official Build) (64-bit) |

---
See jsfiddle: https://jsfiddle.net/2t3ke0o4/

**Comment by thatportugueseguy** [comment]
Same issue here. Could not find a workaround or mention of this problem elsewhere.

**Comment by xile611** [comment]
Duplicated with #2295
