### ISSUE TITLE
Partial background on CartesianGrid based on x-axis or y-axis

### ISSUE THREAD

**Issue by devdream123** [recharts/recharts#2134]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to have different colour background based on x-axis. For example.
x-axis has data of hours like 12am, 3am, 6am, 9am ...
I want to make CartesianGrid to be gray color from 12-6am AND white colour from 9am and beyond.

### What does the proposed API look like?
 <CartesianGrid  xAxis={{value: ['3am','6am'] fill: "#555555"}} />

**Comment by devdream123** [comment]
I managed to work this out using referenceArea.

**Comment by bentaly** [comment]
[For people coming here and looking for an example of the above](https://gaurav5430.medium.com/exploring-recharts-reference-area-2fd68bb33ca5)
