### ISSUE TITLE
No tooltip cursor when using scale="time"

### ISSUE THREAD

**Issue by oscar-b** [recharts/recharts#2135]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-kyviw?file=/src/index.js)

### Steps to reproduce
Run example. Hover bars, they should get a grey background.

### What is expected?
Hovered bars should get a grey background.

### What is actually happening?
Tooltip is displayed, but no cursor.

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.12.0 |
| System | macOS |
| Browser | Chrome 81.0.4044.138 |

**Comment by clementprdhomme** [comment]
Same issue with an axis defined like that:
```jsx
<XAxis dataKey="bin" type="number" />
```

**Comment by a-kulbei** [comment]
Also having the same issue with Tooltip cursor missing when `type` and `scale` props provided to the `XAxis` component

**Comment by RileyCKR** [comment]
My team was encountering this same issue with cursor not being respected with a "number" type XAxis.  We were using version `2.0.10`, and we fixed by updating to `2.1.4` so I suspect this can be marked fixed now.
