### ISSUE TITLE
An easy way to specify color of tooltip items for BarChart when Bar has gradient fill color

### ISSUE THREAD

**Issue by sustmi** [recharts/recharts#2137]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have a barchart with two bars with different gradient as the fill colors.
In the tooltip I want distinguish these two values but they both have the same color - black.

Note: In the following example I made one bar with solid fill color to emphasize what works and what not.

Live example: https://jsfiddle.net/paqexs21/1/

Screenshot:
![image](https://user-images.githubusercontent.com/885946/82357766-15ccc500-99f5-11ea-939e-4bf0ea28ac95.png)

I would like to make the "uv : 2000" text green.

#### Details
I found out that the default tooltip item color (https://github.com/recharts/recharts/blob/438a71b8980e9526ace9a77018556a808ad4127e/src/component/DefaultTooltipContent.tsx#L75) is resolved using `getMainColorOfGraphicItem` function (https://github.com/recharts/recharts/blob/438a71b8980e9526ace9a77018556a808ad4127e/src/chart/generateCategoricalChart.tsx#L741) that simply takes `fill` color from `Bar` component (https://github.com/recharts/recharts/blob/438a71b8980e9526ace9a77018556a808ad4127e/src/util/ChartUtils.ts#L158).
However, when the `fill` color is a link to a gradient definition eg. `url(#colorPv)`, then when it is passed to `color` in the `style` property of the `<li>` item in tooltip, it is not a valid color and so default black is used. 

### What does the proposed API look like?
I am not sure if it is the cleanest solution(*) but I suggest to add `tooltipItemColor` property to the `Bar` component (and maybe other components too) that could override value of the `fill` property (or `stroke` in case of some other components) for the tooltip item color.
The implementation could be done in the `getMainColorOfGraphicItem` function: https://github.com/recharts/recharts/blob/438a71b8980e9526ace9a77018556a808ad4127e/src/util/ChartUtils.ts#L142

(*) Because it would introduce coupling between `Bar` and `Tooltip` component. Now, `Bar` component does not know anything about `Tooltip` component.

And the example code would look like this:
```js
<BarChart ...>
  <defs>
    <linearGradient id="colorUv" ...>
      ...
    </linearGradient>
  </defs>
  ...
  <Tooltip/>
  <Bar dataKey="pv" fill="#8884d8" />
  <Bar dataKey="uv" fill="url(#colorUv)" tooltipItemColor="#82ca9d" />
</BarChart>
```

Alternatively, `tooltipItemStyle` property that would be merged to styles of the `<li>` element would be even more versatile.

**Comment by olelivalife** [comment]
Any news on this? Did you find a solution yet @sustmi ?

**Comment by sustmi** [comment]
No, I did not find any workaround.
I only found that `AreaChart` component has `stroke` property that is used as color for the labels in tooltip. However I did not find any solution for `BarChart` (the labels are black).

**Comment by VladislavKsen** [comment]
You need `CustomTooltip`.
[https://codesandbox.io/s/loving-lake-3sh6d?file=/src/App.js](url)

**Comment by ckifer** [comment]
Custom tooltip is the way here. Going to close this as we aren't going to add a prop just for this
