### ISSUE TITLE
Cannot display Shapes

### ISSUE THREAD

**Issue by lzoia-bc** [recharts/recharts#2138]
In the documentation there is the Shape section where some useful components are listed (Cross, Curve, Dot etc..).
Unfortunately, I cannot managed to display any of those.

I tried nested them both under a Container or Chart component without any result.

So the question is, is it possibile to use directly those components ?
If yes could you please provide an example ?

Thanks

**Comment by miraboducpm** [comment]
I tried the same thing. Seems like this part has not been completed? Maybe someone can help us?

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by reliacon-dev** [comment]
The latest version (2.1.6) also didn't work for me when trying to render the `<Cross />` directly, but I found that you can access the cross and other shapes by using the [Symbols](https://github.com/recharts/recharts/blob/master/src/shape/Symbols.tsx) component instead.

Ex. `<Symbols cx={5} cy={5} type="cross" size={20} sizeType="area" />

![Untitled](https://user-images.githubusercontent.com/51715388/177908203-13acfe70-6704-4abc-9bc0-67252630a55c.png)
`
