### ISSUE TITLE
X Axis ticks not spaced evenly

### ISSUE THREAD

**Issue by SCasarotto** [recharts/recharts#2139]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-iz960?file=/src/index.js)

### Steps to reproduce
See Example. I would expect when the xAxis is set to type='number' that it would display ticks just like when the yAxis is set to typeNumber. It distributes ticks evenly without respect to where data is clumped or sparse. I have tried everything to figure this out. I even went as far as start to write a way to calculate my own ticks but of course those don't link deeply with Brush and so I stopped.

### What is expected?
Evenly spaced ticks just like the yAxis

### What is actually happening?
Unevenly spaced ticks, seemingly based upon where the data is. Its like the type='number' has no impact

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.6 |
| React | ^16.13.1 |
| System | mac OSX |
| Browser | Chrome Version 81.0.4044.138 |

---
Check out the example. I think it provides clearly the issue.

**Comment by fstephany** [comment]
If you remove the `scale="time"` for the XAxis, it will evenly space the ticks (I have no idea why by reading the docs). 

But then you'll get into a bug where the next to last ticks won't be displayed unless you use the auto domain on the XAxis. (`domain={["auto", "auto"]}`).

I also don't have any idea why this is the case. I'll fill a bug for it.

**Comment by SCasarotto** [comment]
Yep, I have messed around with this a lot. Evenly spacing number ticks along the xAxis seems like something that should be covered. What I have done since then is simply forward fill my data and not change any props. This results in the intended outcome. Unfortunately this means computing a lot of extra data in memory.

**Comment by vtarelkin** [comment]
> If you remove the `scale="time"` for the XAxis, it will evenly space the ticks (I have no idea why by reading the docs).
> 
> But then you'll get into a bug where the next to last tick won't be displayed unless you use the auto domain on the XAxis. (`domain={["auto", "auto"]}`).
> 
> I also don't have any idea why this is the case. I'll fill a bug for it.

and when you set interval to zero and domain to auto you'll get the last tick cutted

![image](https://user-images.githubusercontent.com/46703134/89450983-296e0900-d764-11ea-98e4-e1a5b1f4d0a5.png)

there is a workaround for the cutting tick on the right side of the chart:
remove last cartesian grid line in css

.recharts-wrapper .recharts-cartesian-grid-vertical line:last-child {
    stroke-opacity: 0;
}

and setting the padding padding={{right: 30}} in x-axis. then the last tick is not cutted

**Comment by vtarelkin** [comment]
@fstephany I haven't found you bug report. Did you do this? 

> If you remove the `scale="time"` for the XAxis, it will evenly space the ticks (I have no idea why by reading the docs).
> 
> But then you'll get into a bug where the next to last tick won't be displayed unless you use the auto domain on the XAxis. (`domain={["auto", "auto"]}`).
> 
> I also don't have any idea why this is the case. I'll fill a bug for it.

**Comment by fstephany** [comment]
@vtarelkin Oops I haven't yet. I've switched to another task for work but I'll have to come back to this graph at some point.

**Comment by vtarelkin** [comment]
@fstephany it still persists

**Comment by AlaaEl-DinAhmed** [comment]
Anyone solved this issue?

**Comment by pavinduLakshan** [comment]
> @fstephany it still persists

I too am facing this issue :(

**Comment by ckifer** [comment]
Try using interval equidistantStartEnd. This will get improved over time
