### ISSUE TITLE
LegendPayload, setting type to 'plainline' causes crash.

### ISSUE THREAD

**Issue by EwoutGelling** [recharts/recharts#2141]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://l0mdg.csb.app/](https://l0mdg.csb.app/)

### Steps to reproduce
Set the payload of a <Legend/> to [{value:"some value", id:"ID01", type:"plainline"}], setting the type to any other value works as intended only 'plainline' errors.

### What is expected?
To display a payload with a plainline icon.

### What is actually happening?
Error: data.payload is undefined 

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.6 |
| React | 6.8.5-canary-297165f1e |
| System | Windows 10 |
| Browser | Mozilla firefox 76.0.1 (64-bits) |

---
The type 'plainline' is defined as an IconType but does not seem to work.

**Comment by thmsim** [comment]
In this case Recharts seems to be looking for a "payload" object defining the strokeDasharray of the line inside the legend payload.

Using  `payload={[{ type: "plainline", id: "ID01", value: "yes", color: "red", payload: { strokeDasharray: "3 3" } }]}` will make it work.

If you are working with TypeScript you can extend the existing type to have a "clean" fix : 
```
interface LegendPayloadWithLine extends LegendPayload {
  payload?: Record<"strokeDasharray", string>;
}
```

**Comment by ckifer** [comment]
Looks like this is resolved - current types match the correct suggestion above. Closing as completed.
