### ISSUE TITLE
Missing Bar Charts Documentation

### ISSUE THREAD

**Issue by reallyTG** [recharts/recharts#2145]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
You're missing a code snippet in the documentation for Bar Charts (see: https://recharts.org/en-US/api/BarChart). In particular, the second bar chart (with the floating bars) has no associated code snippet. Including it would help early users make sense of the API.

### What does the proposed API look like?
See above.

**Comment by xile611** [comment]
Thanks for your suggestion ! PR to  [recharts.org](https://github.com/recharts/recharts.org)  is welcome.
