### ISSUE TITLE
Date format X axis doesn't work

### ISSUE THREAD

**Issue by a007mr** [recharts/recharts#2146]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

I have error with date format in XAxis. It doesn’t display values from 22 and 24 May: 
![Screen Shot 2020-05-24 at 15 13 51](https://user-images.githubusercontent.com/16572739/82755590-39b94d80-9ddd-11ea-8aa0-ebe03efdc2c8.png)

Here is data: 
```
const series = [
    { name: "Page A", color: "#404ff5", data: [{ date: 1590231130051, value: 50 }, { date: 1590323352074, value: 47 }] },
    { name: "Page b", color: "#9740e5", data: [{ date: 1590145086667, value: 42 }, { date: 1590251072199, value: 45 }] }
  ];
```

Here is code: 
```
const formatXAxis = tickItem => {
  return moment(tickItem).format('D MMM');
}
  
  return (
    <div className="chart chart-updates">
      <ResponsiveContainer width = '95%' height = {500} >
        <LineChart width={500} height={300}>
          <CartesianGrid strokeDasharray="3 3" />
          <XAxis dataKey="date" type="date" tickFormatter={formatXAxis} />
          <YAxis dataKey="value" />
          <Tooltip content={<CustomTooltip />} />
          <Legend />
          {series.map(s => (
            <Line dataKey="value" data={s.data} name={s.name} key={s.name} stroke={s.color} activeDot={{ r: 8 }} type="monotone" />
          ))}
        </LineChart>
      </ResponsiveContainer>
    </div>
  );
```

I tried to use `type="number"`, however it makes even worse. Here is the chart with `number` and the same data (for 22, 23, 24 May):
![Screen Shot 2020-05-24 at 15 35 49](https://user-images.githubusercontent.com/16572739/82755601-4dfd4a80-9ddd-11ea-9c11-5892bea7fa71.png)

As I understood the problem in tickFormatter. It seems that it send to formatXAxis wrong time. 

Here is console.logs of tickFormatter:
![Screen Shot 2020-05-24 at 15 39 21](https://user-images.githubusercontent.com/16572739/82755654-b1877800-9ddd-11ea-9d3d-c2c76de393c6.png)

How can I fix it? How to display date in XAxis correctly? 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/admiring-davinci-8vhrv?file=/src/App.js)

### Steps to reproduce
Here is line chart with multiseries. It should display date format in x axis correctly.  
I reproduce the bug on https://codesandbox.io/s/admiring-davinci-8vhrv?file=/src/App.js. 

Just put the data and display date format x axis.

I tried here <XAxis dataKey="date" type="date" tickFormatter={formatXAxis} /> use type="number", but it works even worse. 

### What is expected?
There must be a chart with 3 dates: 22, 23, and 24 May without bugs for page B, which go away from chart.

### What is actually happening?
It doesn’t display values from 22 and 24 May. And one dataset (page B) go away from chart crossing Y axis. Date format in x axis doesn't work as it should be. 

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.6 |
| React | 16.8.6 |
| System | OS X El Capitan 10.11.6 |
| Browser | Chrome Version 81.0.4044.138 |

**Comment by fstephany** [comment]
You can try to set the `domain` for your XAxis. Beware that the type `date` does not exist for XAxis, the docs only mention `number` and `category`.

`<XAxis dataKey="date" type="number" domain={['dataMin', 'dataMax']} tickFormatter={formatXAxis} />`

This gives the following output in your CodeSandbox sample

![Screenshot from 2020-05-25 10-40-10](https://user-images.githubusercontent.com/35817/82795359-302ef480-9e74-11ea-92f1-e086b4559d3b.png)

**Comment by a007mr** [comment]
It works, thank you so much!
 
Probably, it will be useful to mention in Docs that date for XAxis should be set like this. I didn't find any mentions about date format when I was learning Docs.

**Comment by fstephany** [comment]
Beware that the ticks look wrong though. I have no idea why but this seems a recurring bug when displaying time series data (cf all the other issues related to that).
