### ISSUE TITLE
How to contribute efficiently? (Debug without running the build script after every change)

### ISSUE THREAD

**Issue by simonhessner** [recharts/recharts#2148]
I would like to fix a bug that causes tooltips to flicker when the state of the graph changes. I have forked recharts, created my own branch and am now trying to make changes and test those.

What is the recommended way to do so? I was thinking of making a test project that uses my forked version by `npm link`ing it. That works, BUT I have to run `npm run build` after every change and that is pretty slow. I was not able to find a way to use the raw version of the forked recharts library to test my changes.

How can I have a test/debug project that uses the 'raw' forked recharts from the src rather than the lib folder? Should I create the debug project within the forked recharts project itself and just not commit it when I do the PR?

**Comment by xile611** [comment]
YOu can try `npm run demo`
