### ISSUE TITLE
Line goes out of Y-Axis when using domain={['dataMin','dataMax']}

### ISSUE THREAD

**Issue by KashyapCKotak** [recharts/recharts#2149]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-r9v53?file=/src/index.js)

### Steps to reproduce
Please refer the attached codesandbox link including the erroneous output. The same was tried with version 2.0.0-beta.6 but got the same output.

### What is expected?
I was expecting the red line graph to be within the graph bounds. 

### What is actually happening?
Here it has gone out of the graph and is not visible. Hovering over the end of any other line graph will show that greater value exists for red line which is out of the range of Y-Axis.

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Microsoft Edge Beta (Chrome) |

**Comment by KashyapCKotak** [comment]
Can someone please look into this?

**Comment by bhupendragupta** [comment]
Hi, to get a workaround this you can try increasing the bounds of x & y axis by doing 'dataMin+10' or 'dataMax+10', this may not be the most efficient way and am still exploring but i believe this gets the job done.

**Comment by dgarciasarai** [comment]
I have the same problem :( Any updates?

**Comment by KashyapCKotak** [comment]
I found out the max of my data in code and passed it +10 in the range values as this seemed the only workaround when I used it.

**Comment by dgarciasarai** [comment]
I saw that this happens in a specific set of data and it's really weird. My "dataMax" should be 13 (the biggest number) but the `BarChart` apparently thinks that it's 7... 🤷‍♀️  And it's not even the minimum. I don't know why this happens...

**Comment by MaGaKZ** [comment]
Same here, dataMax not working properly and it is not the biggest value in dataset. I think it is the Bug.

**Comment by MaGaKZ** [comment]
> Same here, dataMax not working properly and it is not the biggest value in dataset. I think it is the Bug.

Providing **integer** value to chart fixed an issue for me.

**Comment by mail2bishnoi** [comment]
Providing any Number value fixed the issue for me. 
I have tried parseInt(), parseFloat() and Number() and all works as expected.

**Comment by TiagoPortfolio** [comment]
Hi all!

This issue was raised on May 25th for version **v1.8.5**, recharts is in version **2.0.0-beta.8** and this issue still persists...
Is this project still being maintained and are the issues being actively handled?

Cheers!

**Comment by zachgoll** [comment]
This was happening to me because my axis values were string types.

Since I set my axis type to "number", I would expect these to be typecasted automatically.

My fix was to manually typecast to a number - `Number(value)`

**Comment by malisbad** [comment]
I had the same issue, but it didn't appear consistently. It seemed to appear most often when changing/updating the dataset if there was more than one render between completions. Forcing to `Number` type solved any problems that were encountered though.
