### ISSUE TITLE
Multi tier category axis

### ISSUE THREAD

**Issue by supersteves** [recharts/recharts#215]
Is it possible to create a 2-tier (or more) category axis, such as this?

![image](https://cloud.githubusercontent.com/assets/10280734/18319373/4b2e29ba-751d-11e6-959c-fd3048651b8c.png)
http://peltiertech.com/chart-with-a-dual-category-axis/

I can see I might be able to create a 2 tier by manually specifying a `<Bar />` for each and every grouping value, but it's not ideal.

**Comment by xile611** [comment]
@supersteves  You can create 2 tier ticks by customized `tick`  in `XAxis`.

[Here](http://recharts.org/examples/#CustomizedLabelLineChart) is a demo of customized tick.

**Comment by supersteves** [comment]
Thanks @xile611 it's a good solution although ideally there would be wider gaps between major tiers.

**Comment by raheelshah31** [comment]
Is there any roadmap for this functionality ?

**Comment by raheelshah31** [comment]
@xile611 Your demo link does not navigate to a example of customized event. Could you please provide a example of how to go abt this ?

**Comment by JarLowrey** [comment]
@xile611  your link is dead. I think this is what you mean - http://recharts.org/examples/#/en-US/examples/CustomizedLableLineChart - though it no longer shows 2 tiers. Any updated examples?

**Comment by jseparovic** [comment]
the jsfiddle on CustomizedLableLineChart points to CustomizedDotLineChart jsfiddle.
Anyone know where the  CustomizedLableLineChart jsfiddle is?
How about an example code printed in the docs?

**Comment by gauravsoti1** [comment]
I got the multi tier jsfiddle working, here it is: https://jsfiddle.net/gs120593/86g7r4zx/9/

**Comment by atosh502** [comment]
It is not perfect but maybe can be tweaked to get wider gaps between major tiers. [Link](https://codesandbox.io/s/recharts-playground-forked-e4yvj?file=/index.js)
