### ISSUE TITLE
aria-labels to improbe accessibility

### ISSUE THREAD

**Issue by cjoecker** [recharts/recharts#2155]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Not accessibility on recharts

### What does the proposed API look like?
Create automatically aria-labels for data points with x and y values. 
E.g. in a bar chart with value 5 in x-axis and November in y-axis, the aria-label can be "bar chart November 5"

**Comment by dgarciasarai** [comment]
This would be awesome!

**Comment by xile611** [comment]
PR is welcome.

**Comment by khibma** [comment]
(Sorry, new to  this project) --but it looked like support for aria-labels was added at one point: https://github.com/recharts/recharts/commit/c01eb30a02ee3254fcb486008154dbcab4249058 
However, today, this is gone. Seemingly between an upgrade from .js to .tsx?

**Comment by kgregory** [comment]
@khibma You're right.  

With v1, adding `aria-label` to  `Cell` would render the resulting element with these presentation attributes intact.  They appear to be filtered out in v2.

V1: [Rectangle.js rendering a path element](https://github.com/recharts/recharts/blob/1.x/src/shape/Rectangle.js#L172-L178), but spreading the result of `getPresentationAttributes(this.props)`.

V2: [Rectangle.tsx rendering a path element with filtered props](https://github.com/recharts/recharts/blob/6c692d3919b75c348b9d4a034aca011fb40f0202/src/shape/Rectangle.tsx#L190-L197), via `filterProps(props, true)`, which filters out the props that were previously listed in `PRESENTATION_ATTRIBUTES`.  See [filterProps](https://github.com/recharts/recharts/blob/6c692d3919b75c348b9d4a034aca011fb40f0202/src/util/types.ts#L1098-L1107) restricting props to those listed in the `SVGContainerPropKeys` and `SVGElementPropKeys` arrays.

@xile611 this seems like a regression and I think this needs to be reopened.  I think it might be appropriate to restore `PRESENTATION_ATTRIBUTES` and keep them from being filtered.

**Comment by mabreuortega** [comment]
I noticed this was closed but I'm unable to find documentation on the topic. Can someone help me with that?

**Comment by ericanaughton** [comment]
> @xile611 this seems like a regression and I think this needs to be reopened.

Has this issue been reopened elsewhere?

**Comment by kgregory** [comment]
@ericanaughton doesn't seem like it.  There are only two closed issues mentioning `aria` and we're in one of them.  This was an existing feature announced in [release 1.5.0](https://github.com/recharts/recharts/blob/master/CHANGELOG.md#150feb-15-2019) that disappeared with the next major release.

@xile611 I realize this probably isn't a priority, but at the very least this issue should remain open.
