### ISSUE TITLE
Missing YAxis label

### ISSUE THREAD

**Issue by caseykhuc** [recharts/recharts#2157]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-fl9qf)

### Steps to reproduce
Create Line chart without margin, with width = 800 and data set of 7 items

![image](https://user-images.githubusercontent.com/10876529/83394531-f5ecc680-a422-11ea-8602-8f16d1cdb90b.png)

### What is expected?
All data and labels are shown

### What is actually happening?
The 2nd label from the right is lost

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.12.0 |
| System | macOS (High Sierra) |
| Browser | Chrome 81 |

**Comment by grouls** [comment]
Including the label property in the YAxis works for me, using your example. Like so:
`      <YAxis axisLine={false} tickLine={false} label={{ value: "label here" }} />
`

**Comment by VladislavKsen** [comment]
Add `interval={0}` in XAxis, then all labels are shown.
`<XAxis
        axisLine={false}
        tickLine={false}
        dataKey="label"
        tickMargin={10}
        interval={0}
      />`
 [https://codesandbox.io/s/recharts-issue-template-forked-9yn44?file=/src/index.js:694-828](url)
