### ISSUE TITLE
Possible bug in displaying stacked AreaChart

### ISSUE THREAD

**Issue by oande** [recharts/recharts#216]
Hey! First off, thanks for a great library.

Unless I'm misunderstanding the API, I may have found a bug where AreaCharts don't stack as expected.

Reproduce: 
1) AreaChart
2) Use several yAxis
3) Link the stacked Area chart to any yAxis other than the first one

Example JSFiddle: http://jsfiddle.net/wf2rwcne/

(If you switch `yAxisId={1}` back to `yAxisId={0}` it will properly stack)

**Comment by xile611** [comment]
@oande Only when the areas have the same stackId and yAxisId, these areas can be stacked.  Because different yAxisIds  indicate that these areas have different dimensions, there is no any sense to the sum the values of these areas.

**Comment by oande** [comment]
@xile611 if you look in the JSFiddle, you'll see that exact case not working => same yAxisId and stackId

**Comment by xile611** [comment]
@oande Sorry! It's a bug of stacked chart.
