### ISSUE TITLE
LineChart: Missing YAxis ticks and CartesianGrid horizontal lines for certain data values when YAxis scale is "log"

### ISSUE THREAD

**Issue by dandrei** [recharts/recharts#2161]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/dandrei/a7cqjytv/](https://jsfiddle.net/dandrei/a7cqjytv/)

### Steps to reproduce
Load the chart in the reproduction: https://jsfiddle.net/dandrei/a7cqjytv/

### What is expected?
Y-axis should show ticks, CartesianGrid should have both horizontal and vertical lines.

### What is actually happening?
YAxis ticks are missing and so are the CartesianGrid horizontal lines.

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Firefox, Edge |

---
The exact same configuration works when the data is changed.
For example, the chart looks fine with this data:

```
const data = [
{"q":"201912","DATA":123},
{"q":"202001","DATA":234},
{"q":"202002","DATA":345},
{"q":"202003","DATA":456},
{"q":"202004","DATA":567}
];
```

There is something about the data in the reproduction example that causes the chart to misbehave.
What is it? And how can it be fixed?

**Comment by dandrei** [comment]
Note that I tried to use the CodeSandbox example, but on my system all CodeSandbox `recharts` examples crash with the following message (FF + Edge):

```
Could not find module in path: 'd3-interpolate' relative to '/node_modules/d3-scale/src/continuous.js'
```

**Comment by dgarciasarai** [comment]
@dandrei I think you can add that dependency to your CodeSanbox manually :)

**Comment by Undistraction** [comment]
@dandrei did you manage to resolve this? Seeing the same issue.

**Comment by dandrei** [comment]
> @dandrei did you manage to resolve this? Seeing the same issue.

No, I don't think I ever did.

**Comment by ckifer** [comment]
use `scaleSymlog` instead of `log`
