### ISSUE TITLE
Animate Line type changing when hovering

### ISSUE THREAD

**Issue by bruno2ms** [recharts/recharts#2162]
I'm trying to create an effect of smoothing a LineChart when the user is not hovering it, I've tried to use cardinal and bundle from `d3-shape`.
Cardinal smooths the curve but not much as I desire, and bundle always smooth it too much.

Also even that I'm smoothing it, and changing when hovering the chart, I can't animate the line.

What I'm trying to accomplish: 

![ezgif-4-6d58b4552fb1](https://user-images.githubusercontent.com/1333759/83910650-4f196a80-a741-11ea-97ca-f5ba4fad7c40.gif)

There's a way to animate `<Line />` type changes?

**Comment by ckifer** [comment]
linking an answer to this and closing as stale
https://github.com/recharts/recharts/issues/407#issuecomment-631549245
