### ISSUE TITLE
Percentage passed to `label` function is not a percentage

### ISSUE THREAD

**Issue by jochenberger** [recharts/recharts#217]
I have a `Pie` with a custom `label` function. The props passed to the function contain a `percent` property, but the value is not a percentage (e.g. 50 for 50%) but a decimal (e.g. 0.5).

**Comment by xile611** [comment]
@jochenberger You should format the value yourself, because the format of percent can be very different.

**Comment by jochenberger** [comment]
My point was that the value is wrong, if the property name is "percentage", it should be 50, not 0.5. But I can work around that.

**Comment by xile611** [comment]
@jochenberger I thought the percentage `50%` equals to the decimal `0.5`, and decimal is much simpler to format. So I return the decimal.
