### ISSUE TITLE
How to make the Y-Axis sticky While scrolling

### ISSUE THREAD

**Issue by yogesh45** [recharts/recharts#2170]
How to make the Y-Axis sticky While scrolling
Tried lot of things but nothing is working 

Can any one help me in this
![Recharts-YAXIS](https://user-images.githubusercontent.com/41938654/84667796-72fa5e80-af40-11ea-8a06-4aef43c022dd.PNG)

**Comment by MaGaKZ** [comment]
Try using Brush
https://jsfiddle.net/alidingling/mc8r7e6p/

**Comment by piyushsharma98** [comment]
@yogesh45  Did you find any to stick Y-axis. I am also facing this issue for the mobile view of this graph.

**Comment by yogesh45** [comment]
@piyushsharma98 
https://www.olioapps.com/blog/graph-hacking/#:~:text=Bars%20with%20positive%20values%20should,which%20displays%20the%20bar's%20value.

I have implemented based on the above link
Please refer that

**Comment by thareshjose** [comment]
> @piyushsharma98 https://www.olioapps.com/blog/graph-hacking/#:~:text=Bars%20with%20positive%20values%20should,which%20displays%20the%20bar's%20value.
> 
> I have implemented based on the above link Please refer that

This works only if you take out your CustomYAxis component outside of the chart, which would mean that you could only have static value ranges  on the axis, which is useless when the graph values are dynamic!

**Comment by Alpharis-voosh** [comment]
try changing the .recharts-yAxis styling 
`.recharts-yAxis {
  transform: translate(0, 0);
}`

and then modify it via JS using onScroll event
` onScroll={(e) => {
          let ele = document.getElementsByClassName("recharts-yAxis")[0];
            ele.style = "transform: translateX("+e.target.scrollLeft+"px);";
        }}`

it changes y-axis position dynamically so it appears to be sticky.

**Comment by smaspe** [comment]
why was this closed?

**Comment by ckifer** [comment]
Not sure why a lot of issues were closed in the past but the comments give visibility

I'm actually going to reopen https://github.com/recharts/recharts/issues/1364 though because it has more context

**Comment by nirmalwizzmod** [comment]
You can wrap the bar chart with the parent container then set the width with overflow-x scroll and add some codes in the onscroll event to make y axis sticky and chart to be scroll, see the below code for reference.

const handleScroll = (e) => {
    const yAxisElement = containerRef.current.querySelector('.recharts-yAxis');
    const chartBars = containerRef.current.querySelector('.recharts-layer.recharts-bar');
    const gridLines = containerRef.current.querySelector('.recharts-cartesian-grid-horizontal');
    const xAxisElement = containerRef.current.querySelector('.recharts-xAxis');

    if (yAxisElement && chartBars && gridLines) {
      const { scrollLeft } = e.target;
      yAxisElement.style.transform = `translateX(${scrollLeft}px)`;
      chartBars.style.clipPath = `inset(0 0 0 ${scrollLeft}px)`;
      gridLines.style.clipPath = `inset(0 0 0 ${scrollLeft}px)`;
      xAxisElement.style.clipPath = `inset(0 0 0 ${scrollLeft}px)`;
    }
  };
  
  <div className="verticalBarchart-container" ref={containerRef} onScroll={handleScroll}>
          <BarChart
            width={800}
            height={300}
            data={data}
            className="barchart-verticalBarChart">
            <XAxis
              dataKey="name"
              minTickGap={1}
              interval={0}
              tickMargin={5}
              axisLine={false}
            />
            <YAxis axisLine={false} width={25}/>

            <Tooltip />
            <CartesianGrid horizontal={true} vertical={false} />
            <Bar
              dataKey="uv"
              fill={barColor}
              barSize={40}
              shape={
                <CustomBarShape
                  stopColor={stopColor}
                  barColor={barColor}
                  newBarSize={barSize}
                  newBarRadius={barRadius}
                  charColor={charColor}
                />
              }
            />
          </BarChart>
        </div>

**Comment by nirmalwizzmod** [comment]
You can wrap the bar chart with the parent container then set the width with overflow-x scroll and add some codes in the onscroll event for the parent container that you wrapped the chart to make the y-axis sticky and the chart to scroll, see the below code for reference.


const handleScroll = (e) => {
    const yAxisElement = containerRef.current.querySelector('.recharts-yAxis');
    const chartBars = containerRef.current.querySelector('.recharts-layer.recharts-bar');
    const gridLines = containerRef.current.querySelector('.recharts-cartesian-grid-horizontal');
    const xAxisElement = containerRef.current.querySelector('.recharts-xAxis');

    if (yAxisElement && chartBars && gridLines) {
      const { scrollLeft } = e.target;
      yAxisElement.style.transform = `translateX(${scrollLeft}px)`;
      chartBars.style.clipPath = `inset(0 0 0 ${scrollLeft}px)`;
      gridLines.style.clipPath = `inset(0 0 0 ${scrollLeft}px)`;
      xAxisElement.style.clipPath = `inset(0 0 0 ${scrollLeft}px)`;
    }
  };

**Comment by syedmazharcube** [comment]
> try changing the .recharts-yAxis styling `.recharts-yAxis { transform: translate(0, 0); }`
> 
> and then modify it via JS using onScroll event ` onScroll={(e) => { let ele = document.getElementsByClassName("recharts-yAxis")[0]; ele.style = "transform: translateX("+e.target.scrollLeft+"px);"; }}`
> 
> it changes y-axis position dynamically so it appears to be sticky.

Saved my life thanks

**Comment by mattbf** [comment]
See [this comment](https://github.com/recharts/recharts/issues/1364#issuecomment-2608588147) for a decent solution
