### ISSUE TITLE
how to set date on xaxis 

### ISSUE THREAD

**Issue by mouhamadibrahim** [recharts/recharts#2171]
The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.

how can i make date on xaxis?

i have this data:

const systolicAndDiastolicAndPulseAverage = [
    {
      name:'Systolic Average',
      style:'#FFDA83',
      id:'right',
      category:'Systolic Average',
      data: [
        { day: '23/05/2020 04:50', value: 76 },
        { day: '24/05/2020 04:50', value: 98 },
        { day: '25/05/2020 04:50', value: 63 },
        { day: '26/05/2020 04:50', value: 112 },
        { day: '27/05/2020 04:50', value: 81 },
        { day: '28/05/2020 04:50', value: 81 },
        { day: '29/05/2020 04:50', value: 72 },
        { day: '30/05/2020 04:50', value: 74 },
        { day: '31/05/2020 04:50', value: 124 },
      ]
    },

how can i make the xaxis only day/month format? for example 29/05 
---

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

**Comment by xile611** [comment]
Please open an issue follow the issue guide.
