### ISSUE TITLE
Types for `cursor` on Tooltip component are too restrictive/wrong

### ISSUE THREAD

**Issue by James-Reed-cognito** [recharts/recharts#2178]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-tm5dm?file=/src/index.js)

### Steps to reproduce
Try to use `cursor={{ fill: 'red' }}` in a typescript project

### What is expected?
As this appears to be the only way to colour the hover background on bar charts, I would expect that this would be an allowed prop

### What is actually happening?
This is not an allowed prop - the passed prop of fill works visually, but the props for `cursor` are:
```
cursor?:
    | boolean
    | ReactElement
    | {
        strokeDasharray: ReactText;
        stroke?: string;
      };
```

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.6 |
| React | 16.13.1 |
| System | Any |
| Browser | Chrome |

**Comment by Markus-ipse** [comment]
There seem to be quite a few places where you can pass in SVG props but the types won't let you :(
