### ISSUE TITLE
Label width

### ISSUE THREAD

**Issue by Maxim1905** [recharts/recharts#2179]
![image](https://user-images.githubusercontent.com/37245038/86032784-8f1df580-ba40-11ea-86b1-2b675bf7d9a9.png)

The label is not visible if it is more than a certain length

**Comment by younes6970** [comment]
@Maxim1905  You can use <XAxis tickCount={6} minTickGap={0 or -number} />

**Comment by Maxim1905** [comment]
![image](https://user-images.githubusercontent.com/37245038/86259533-cd442200-bbc4-11ea-92b6-0e4423d6ab54.png)


the question is rather that if the column name is long, then you need to implement line wrapping
