### ISSUE TITLE
How to draw y-axis in bar chart in mid of positive and negative value bars

### ISSUE THREAD

**Issue by tushar-compro** [recharts/recharts#2183]
The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.

Is it possible to somehow render the y-axis in mid of positive and negative value bars in vertical bar chart.
Expected Rendering:
![image](https://user-images.githubusercontent.com/25972844/86484547-14bce080-bd74-11ea-8a44-6176225c617b.png)

Current rendering:
![image](https://user-images.githubusercontent.com/25972844/86484629-46ce4280-bd74-11ea-9ce9-7f8abdbf0848.png)

**Comment by xile611** [comment]
Please open an issue follow the issue guide.
