### ISSUE TITLE
How to change the distance between labels on x axis?

### ISSUE THREAD

**Issue by jasonliao122895** [recharts/recharts#2186]
<img width="566" alt="Screen Shot 2020-07-06 at 9 31 26 AM" src="https://user-images.githubusercontent.com/49352859/86617477-1e109d80-bf6c-11ea-95b0-2cf3db4a8cc0.png">

I want the 00 and 08 to be inside the graph. Right now the 00 and 08 are a bit outside the graph. Is there a way to decrease the distance between the labels? I've tried setting the width of the axis, lowering minTickGap props, messed around with dx, and none of those solved my problem. Does Recharts even allow users to do what I want?

**Comment by xile611** [comment]
Please open an issue follow the issue guide.
