### ISSUE TITLE
Error: <text> attribute transform: Expected number, "scale(NaN)".

### ISSUE THREAD

**Issue by devdream123** [recharts/recharts#2187]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
<img width="1519" alt="Screen Shot 2020-07-07 at 5 02 02 pm" src="https://user-images.githubusercontent.com/17215327/86733110-4388ce80-c074-11ea-9b8b-449fa48e8f8f.png">

### Steps to reproduce
it looks like it happens somewhere within recharts itself

### What is expected?
no error Error: <text> attribute transform: Expected number, "scale(NaN)".

### What is actually happening?
Error: <text> attribute transform: Expected number, "scale(NaN)".

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.13.1 |
| System | MacOS Catalina 10.15.5 |
| Browser | Google Chrome Version 83.0.4103.116 (Official Build) (64-bit) |

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
