### ISSUE TITLE
I have problems  about font thai ,font is broken

### ISSUE THREAD

**Issue by ninew089** [recharts/recharts#2188]
<img width="900" alt="Screen Shot 2563-07-07 at 23 29 28" src="https://user-images.githubusercontent.com/57795422/86813068-ec055580-c0a9-11ea-9dc5-58382a088798.png">

The font is broken
my rechart version
  "recharts": "^1.8.5",

**Comment by Valindo** [comment]
Steps to reproduce the error?

**Comment by ninew089** [comment]
I try to install  the new rechart,try to create new project or change font.
But font still broken.

**Comment by Valindo** [comment]
If you can create a fiddle with the problem, I could better understand it, I am not familiar with Thai font.
If this is with the wrong font being  rendered, you can always override the class  used for label list `.recharts-label-list`

I hope this is helpful.
