### ISSUE TITLE
Customize properties of the last stroke of a LineChart

### ISSUE THREAD

**Issue by Moshyfawn** [recharts/recharts#2189]
I'm trying to customize the last stroke of my LineChart to visualize some important parameters. I've created something similar to the [TinyLineChart](https://recharts.org/en-US/examples/TinyLineChart) example. I need to render the last stroke red or green base on the direction this stroke goes (down/up). How can I achieve something like this?
![chart-example](https://user-images.githubusercontent.com/16290753/86942995-8ae38d80-c14e-11ea-91cb-196b0bada244.png)

I also want to render a dot at the end of the line to represent the last value. I couldn't find a way to do it just for the last one.

**Comment by Valindo** [comment]
For the last line to to be a different color, you can use linear gradients on the line chart.
And to denote the last important point , you can use `ReferenceDot`
I've prepared an example for you here -> https://codesandbox.io/s/hopeful-aryabhata-ui7fn?fontsize=14&hidenavigation=1&theme=dark

**Comment by Moshyfawn** [comment]
Sry for the late reply, @Valindo
Thx, I managed to get the results I needed using your example!
There's this behavior of the `<RefrenceDot />` I can't get round. Is drawing `<XAxis />` and `<YAxis />` the only way to display a `<ReferenceDot />`? I hid them via CSS `display: none` but it feels wrong to draw and hide elements for the sake of another elements reference. I couldn't get `<ReferenceDot />` to display without the axis components

**Comment by Moshyfawn** [comment]
I tried adding xAxis and yAxis config prop with a scale prop set to 'auto' by hand
```
<ReferenceDot
  xAxis={{
    scale: 'auto'
  }}
  yAxis={{
    scale:  'auto'
  }}
/>
```
and via `<XAxis />` and `<YAxis />` props
```
<ReferenceDot
  xAxis={{
    scale: <XAxis />.props.scale
  }}
  yAxis={{
    scale: <YAxis />.props.scale
  }}
/>
```
Didn't work. Is there a bug or am I doing something wrong?

**Comment by xile611** [comment]
Please open an issue follow the issue guide.
