### ISSUE TITLE
Ranged Bar components display unexpected behavior when trying to make them stacked

### ISSUE THREAD

**Issue by tchanias** [recharts/recharts#2192]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
I am trying to create a stack of two bar components that are also ranged bars. Instead of creating a stack on top of each other, a bar that occupies all the height of the y-axis is created.
non-stacked ranged bars:
![rangedbars](https://user-images.githubusercontent.com/26023361/87277734-8ec73500-c4eb-11ea-944a-957e8696473b.png)

stacked ranged bars:
![Screenshot](https://user-images.githubusercontent.com/26023361/87277757-9dade780-c4eb-11ea-8ab7-38fd2b81b6bc.png)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
This is the Recharts stacked bars example with the first three bars displaying the buggy behavior as they are
defined with range values ['valueStart','valueEnd'] instead of just 'value'. 
https://codesandbox.io/s/gifted-mcclintock-utqzh?file=/src/App.js
## What is the expected behavior?
The two bars stacked in the same y-axis on top of each other
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
"recharts": "^1.5.0",

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
