### ISSUE TITLE
How to add pagination to Bar charts

### ISSUE THREAD

**Issue by Srinivasan74** [recharts/recharts#2194]
Hi,

I want to have pagination for Bar chart. At any point of time I want to display only 5 bars. If more than 5 bars a pagination should be added and when NEXT is clicked it should move to next set of bar charts.

When PREVIOUS is clicked it should bring back to previous set of bar chats.

Thanks,
Srini

**Comment by Valindo** [comment]
I would suggest to paginate your data and pass it to the chart, create two buttons that would return the next or previous set of data points and pass it to your chart.
This seems like the easiest way to achieve this.

**Comment by Srinivasan74** [comment]
Thanks for the suggestion
