### ISSUE TITLE
Upgrade to core-js@3

### ISSUE THREAD

**Issue by SpawnAtis** [recharts/recharts#2195]
Hi. Could u ,pls,  make new release with this changes [Migrate to core-js@3](https://github.com/recharts/recharts/commit/33350eae56532d7a5e28b7393977bef9f9fc8fcb#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) ? I can not upgrade my project to core-js@3 without it.

**Comment by avindra** [comment]
You can pin recharts to the beta version that got released https://github.com/recharts/recharts/releases/tag/v2.0.0-beta.7

#2262 is tracking removing `core-js` as a dependency.
