### ISSUE TITLE
Create Tooltips relative to values ("points" / "dots") in a ComposedChart

### ISSUE THREAD

**Issue by talor-hammond** [recharts/recharts#2197]
Want to create more than one Tooltip in a ComposedChart, where the position of the Tooltip is relative to the "points" on the Child charts (in this case: Line and Area)

With the current API, is there a way to achieve this:
![image](https://user-images.githubusercontent.com/35422306/87623974-aff18500-c77a-11ea-92c9-b615d3dfc8af.png)

I've experimented with mouse-events in ComposedChart, but nothing is exposed that gives me the position of the focussed "dot" / "point"

**Comment by xile611** [comment]
Please open an issue follow the issue guide.
