### ISSUE TITLE
chart components don't respect z-index

### ISSUE THREAD

**Issue by chocolaaaaate** [recharts/recharts#2200]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/recharts/recharts/issues/new/choose](https://github.com/recharts/recharts/issues/new/choose)

### Steps to reproduce
i have a semantic UI dropdown above a chart. when the dropdown opens some of the menu items that overlap with the recharts scatter plot below lose mouse events and part of the chart appears through the dropdown menu. 

### What is expected?
the chart should remain beneath the dropdown list that opens 

### What is actually happening?
the charts appears through the dropdown and captures mouse events intended for the dropdown so that you can't select any menu items that overlap the chart when the dropdown is opened

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.6 |
| React | react 16.13.1 |
| System | macOS Catalina |
| Browser | Firefox, Chrome (up to date) |

![image](https://user-images.githubusercontent.com/26353561/87666590-f8ca2d80-c7bc-11ea-99bf-311e1cf58ce6.png)

**Comment by Valindo** [comment]
Hey, is the dropdown part of the chart? or is it outside the chart? i.e outside `<ResponsiveContainer>` or `<ScatterChart>`

**Comment by chocolaaaaate** [comment]
> Hey, is the dropdown part of the chart? or is it outside the chart? i.e outside `<ResponsiveContainer>` or `<ScatterChart>`

Nevermind I figured it out. The issue was that its an SVG which has no z-index. Solved by putting the SVG chart as a child of the component that contains the dropdown.
