### ISSUE TITLE
recharts gives tooltip only for one vertical dot?

### ISSUE THREAD

**Issue by vtarelkin** [recharts/recharts#2202]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackoverflow.com/questions/62912234/recharts-gives-tooltip-only-for-one-vertical-dot](https://stackoverflow.com/questions/62912234/recharts-gives-tooltip-only-for-one-vertical-dot)

### Steps to reproduce
My data for the first one line

0: {x: 1594900560000, y: 0.384}
1: {x: 1594900560000, y: 0.432}
The x is epoch time.

                <LineChart>
                 
                            <Line strokeWidth={3}
                                  dot={{fill: '#4D92F5', r: 5}} activeDot={{
                                onClick: () => {
                                    handleDotClick()
                                }
                            }} dataKey="y"
                                  data={data}/>
                        )
                    })
                    }
                    <CartesianGrid horizontal={false} stroke="rgba(16, 147, 200, 0.08)"/>
                    <XAxis
                        style={{
                            stroke: "rgba(16, 147, 200, 0.08)",
                            fill: 'rgba(12, 134, 184,1)'
                        }}
                        name="Time"
                        scale="time"
                        allowDuplicatedCategory={false}
                        type="number"
                        dataKey="x"/>
                    <YAxis
                        style={{
                            stroke: "rgba(16, 147, 200, 0.08)",
                            fill: 'rgba(12, 134, 184, 1)'
                        }}
                        type="number" dataKey="y"/>
                    <Tooltip
                        cursor={false}
                        labelFormatter={() => undefined}
                        formatter={(okay) => [new Intl.NumberFormat('en').format(okay), undefined]}/>
                </LineChart>

### What is expected?
tooltip for any of vertical dots

### What is actually happening?
tooltip for only one vertical dot

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.6 |
| React | 16 |
| System | OS Ubuntu |
| Browser | Chrome 81 |

**Comment by mrcportillo** [comment]
Having the same issue, did you find some workaround @vtarelkin?

**Comment by mrcportillo** [comment]
I was not able to make it work using the provided tooltip, instead, I attached mouse event listeners(mouseEnter and mouseLeave) to the dot property on the Line and used a custom tooltip..

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
