### ISSUE TITLE
ZAxis domain is missing

### ISSUE THREAD

**Issue by unusual-thoughts** [recharts/recharts#2203]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
`domain` is apparently supported for `ZAxis`, but the docs don't mention it and it is not included in the typescript definition

### What does the proposed API look like?
add a `domain` prop to `ZAxis`, just like `XAxis` and `YAxis`

**Comment by pkmnct** [comment]
This is also true for PolarAngleAxis. The prop works, but Typescript complains.

**Comment by dseliukov** [comment]
Temporary solution for typescript users

```
import React from 'react';
import { ZAxis, ZAxisProps, AxisDomain } from 'recharts';

const ZAxisCustom: React.FC<ZAxisProps & { domain: [AxisDomain, AxisDomain] }> = props => <ZAxis {...props} />;
```
