### ISSUE TITLE
How do i change Radar Chart background color 

### ISSUE THREAD

**Issue by Altimetrik-Rahul** [recharts/recharts#2204]
The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.

How do I can background color in the radar chart? 
and how do add that different line in the cut line see in the below image.

Excepted UI 
![image](https://user-images.githubusercontent.com/36156890/87851624-1b248e00-c918-11ea-8b70-f8c6e203be26.png)
Current UI 
![image](https://user-images.githubusercontent.com/36156890/87851635-3394a880-c918-11ea-8c50-1c4754c7e2d1.png)

---

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

**Comment by xile611** [comment]
Please open an issue follow the issue guide.
