### ISSUE TITLE
<YAxis/> Not Respecting allowDecimals and tickCount Prop when domain is set to non-int values

### ISSUE THREAD

**Issue by martinnov92** [recharts/recharts#2208]
Please reopen this issue as this issue still exists:

https://github.com/recharts/recharts/issues/777

**Comment by KenEucker** [comment]
Echoing this.

I cannot get my LineChart YAxis to respect allowDecimals. 

Can we get help with this, @xile611 @gcourtemanche ?

**Comment by gcourtemanche** [comment]
Sorry @KenEucker, I can't help I don't know the codebase!
