### ISSUE TITLE
referenceArea problem with padding

### ISSUE THREAD

**Issue by vtarelkin** [recharts/recharts#2210]
I want to fill background with color for corresponding values on yAxis with referenceArea for all xAxis 

From 0 to 5 - red
From 5 to 9 - yellow
From 9 to the top - green

And I did it with referenceArea. The trouble is when I set 
                   <XAxis
                                padding={{left: 50, right: 60}}

then reference area is moved too, however I want it to last for the whole xAxis including the padding! How this can be done? The pic clearly shows that reference area lasts only from 1 tick to the last tick on the xAxis.

![image](https://user-images.githubusercontent.com/46703134/88419412-d1dbaf00-cded-11ea-996e-8ba35fb4c979.png)

**Comment by xile611** [comment]
Please open an issue follow the issue guide.
