### ISSUE TITLE
How to align two Y-Axis

### ISSUE THREAD

**Issue by ThibaultWUN** [recharts/recharts#2212]
## I have an areachart with two areas and two Y-Axis. The first area goes from -1500 to 4500. The second goes from 0 to 100. Both areas start from the bottom so the 0 value of the second one is aligned with the -1500 value of the first one.

<img width="814" alt="Screen Shot 2020-07-27 at 15 37 03" src="https://user-images.githubusercontent.com/67957812/88548623-a8a26500-d01f-11ea-9165-011ce43ca000.png">

## Is it possible to align the two y-axis ? Without cheating with the value of domain... I want to see both 0 at the same level.

<img width="794" alt="Screen Shot 2020-07-27 at 15 37 38" src="https://user-images.githubusercontent.com/67957812/88548752-c5d73380-d01f-11ea-8ff1-f9f419902010.png">

**Comment by xile611** [comment]
Thanks for your suggestion, we have added this feature to the plan of 2.0

**Comment by chillitom** [comment]
This look useful, was this implemented in the end?  Is there an example someplace?
