### ISSUE TITLE
Documented propType preventing FunnelChart rendering correctly

### ISSUE THREAD

**Issue by texonidas** [recharts/recharts#2214]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-lufxy)

### Steps to reproduce
Use an array as a value prop in a Funnel

### What is expected?
From the docs, that it would function, presumably only on the last array element and to be used as a final width on the funnel rather than coming to a point

### What is actually happening?
No render, no error

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.6 |
| React | 16.8.5 |
| System | Windows 10 |
| Browser | Chrome@latest |

---
I'm aware this may well just be inaccurate documentation, however the use case I interpreted it as being for seems a valid one. If I've interpreted incorrectly then it's as simple as a doc fix, otherwise it would be very good to have it working as I have described, as most funnel graphs shouldn't come to a point anyway.

**Comment by xile611** [comment]
Thanks! PR to [recharts.org](https://github.com/recharts/recharts.org) is welcome.
