### ISSUE TITLE
Custom ticks of XAxis 

### ISSUE THREAD

**Issue by tuanphan1790** [recharts/recharts#2215]
![image](https://user-images.githubusercontent.com/32637818/88757365-c814cb80-d1a0-11ea-849f-4b1d022b1d9c.png)

I collect data from DB in 7 days. Everyday, there are 60 datas corresponding with 60 hours. But Ticks on XAxis will be duplicate after format. I want to display just only 7 day on XAxis. 
what the solution for this?
Any help would be appreciated!

My code:
![image](https://user-images.githubusercontent.com/32637818/88758417-6144e180-d1a3-11ea-91de-25e8e13bab92.png)

![image](https://user-images.githubusercontent.com/32637818/88758395-4bcfb780-d1a3-11ea-8b69-a3b0a682df94.png)

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

**Comment by xile611** [comment]
Please open an issue follow the issue guide.
