### ISSUE TITLE
How to set a fixed position for the Tooltip

### ISSUE THREAD

**Issue by jochenberger** [recharts/recharts#222]
For my `PieChart`, I want the `Tooltip` to always appear in the lower right corner of the chart, no matter which section i hover over. I've seen that there are `coordinate` and `viewBox` props, but if I set them, they are overwritten.

**Comment by xile611** [comment]
@jochenberger In such case, you can add some click or hover event on the Pie, and display the content in customized divs or svgs.
[Here] is an example of BarChart.

**Comment by jochenberger** [comment]
The link is missing from you post. I assume you mean http://recharts.org/examples#BarChartWithCustomizedEvent.

**Comment by xile611** [comment]
@jochenberger Yeah, Thank you!

**Comment by jasonnathan** [comment]
http://recharts.org/examples/#/en-US/examples/BarChartWithCustomizedEvent. Changed again... an auto-redirect to a default language wouldn't hurt :(

**Comment by sospirited** [comment]
For any others who come across this same requirement, you can set the Tooltip `position` which will get respected and not overriden/transformed dynamically. For example:
```
<Tooltip position: {{ y: 400: x: 0 }} />
```

Via https://github.com/recharts/recharts/commit/31d2b2d367adecaef34c5bb0371f27126dc51d8b

**Comment by breadadams** [comment]
And for anyone copy-pasting the above solution, you'll want:

```jsx
<Tooltip position={{ x: 400, y: 0 }} />
```

**Comment by erosenberg** [comment]
@breadadams  and @sospirited thanks for this! But what if you want to set the position to the x / y of the point and not a fixed value? In other words, since I'm using a Stacked Bar Chart, it would be nice to position the Tooltip directly above each data point and I can't figure out how to do this.

**Comment by dentov13** [comment]
> @breadadams and @sospirited thanks for this! But what if you want to set the position to the x / y of the point and not a fixed value? In other words, since I'm using a Stacked Bar Chart, it would be nice to position the Tooltip directly above each data point and I can't figure out how to do this.

+1

**Comment by kodell** [comment]
It would be great if `position` prop could accept a function, which would receive mouse coordinate or bar coordinate and return the `{x, y}` obj.

**Comment by miljantekic** [comment]
> It would be great if `position` prop could accept a function, which would receive mouse coordinate or bar coordinate and return the `{x, y}` obj.

+1

**Comment by kh-ruslan** [comment]
Set `x` as `auto` and the tooltip will follow the mouse horizontally: `position={{ x: 'auto', y: 100 }}`

**Comment by dsarfati** [comment]
`auto` worked for me, but the TS definitions only allow `x` or `y` to be a number

**Comment by gaurav5430** [comment]
It seems that the prop is renamed to `coordinate` as per the docs ?

https://recharts.org/en-US/api/Tooltip#coordinate

although `position` seems to work and `coordinate` does not

**Comment by gaurav5430** [comment]
I want to position the tooltip at a fixed data point, but it seems the position prop expects the coordinates and not the data values. 
Is there a way to position a tooltip based on a data value ?

**Example**: I want the tooltip to always be positioned on data.x = 500 , but if I pass `position: { x: 500 }` , the tooltip would actually be on x = 500 according to the coordinate system, not according the scaled value of the data.
this can be solved if there is a way to get the computed x coordinate by passing the data.x to the x axis scale function, which is what the tooltip internally does when automatically calculating the x, y coordinates

**Comment by etothepii** [comment]
I wanted to place my tooltip above my chart and aligned with the right edge of the chart like this

<img width="766" alt="image" src="https://user-images.githubusercontent.com/2609402/204900960-d6e5741e-7658-4f14-bffd-c948e63f8323.png">

Reviewing the recharts code an x,y dictionary is specified so the only option I could think of was to override the get parameters on the x and y to be calculated using the refs. A quick review of MDN makes me think that this is safe, but it feels quite hacky.

BE WARNED

```
  let tooltipPosition = {};
  Object.defineProperty(tooltipPosition, "x", {
    get: () => {
      const chartWidth = barChartRef.current?.props?.width;
      const marginRight = barChartRef.current?.props?.margin?.right;
      const boundingRect =
        tooltipRef.current?.wrapperNode?.getBoundingClientRect();
      return chartWidth - boundingRect?.width - marginRight;
    },
  });
  Object.defineProperty(tooltipPosition, "y", {
    get: () => {
      const boundingRect =
        tooltipRef.current?.wrapperNode?.getBoundingClientRect();
      return -boundingRect?.height;
    },
  });
```

Then I can do

```
<BarChart
  ref={barChartRef}
  ...
/>
  ...
  <Tooltip
    ref={tooltipRef}
    position={tooltipPosition}
    isAnimationActive={false}
    ...
  />
</BarChart>
```

**Comment by timduffin** [comment]
> auto worked for me, but the TS definitions only allow x or y to be a number

Omit the coordinate you want auto, and you'll be good to go 👍 
```javascript
<Tooltip position={{ y: 100 }} />
```

**Comment by jithesh-poojari** [comment]
But it will not be responsive. When x:500 set. In smaller screen the label will be shown outside the components.

**Comment by ckifer** [comment]
When 3.0 is out all of this will be easily done with Tooltip portals. 

And
Not sure what you mean by vertical cursor, the cursor is vertical on vertical charts and horizontal on horizontal charts. 

Feel free to open a discussion thread if you have a question

**Comment by jithesh-poojari** [comment]
> And Not sure what you mean by vertical cursor, the cursor is vertical on vertical charts and horizontal on horizontal charts.
 Feel free to open a discussion thread if you have a question

Sorry, Not vertical cursor. It is horizontal. when hovered on points a horizontal line is need. how now vertical lines works

**Comment by ckifer** [comment]
I'm confused sorry. Feel free to open a new issue or discussion since this is unrelated to this issue

**Comment by NarendraKuruva** [comment]
> When 3.0 is out all of this will be easily done with Tooltip portals.
> 
> And Not sure what you mean by vertical cursor, the cursor is vertical on vertical charts and horizontal on horizontal charts.
> 
> Feel free to open a discussion thread if you have a question

@ckifer 

When is `Version 3.0` set to be released??

**Comment by ckifer** [comment]
Sorry man, it's not something that can be estimated because it's based on random spurts of time dedicated to this project.
