### ISSUE TITLE
tooltip hover area

### ISSUE THREAD

**Issue by vtarelkin** [recharts/recharts#2226]
Hi everyone,
in my project I have many line charts with dots that are located differently. And I can't catch values from some dots don't matter how hard I try. Is it possible to increase "hover"area, the area in which can be pointer to show the value? 

On the pic I can't catch value from the violet chart...
![image](https://user-images.githubusercontent.com/46703134/89643659-f0967700-d8be-11ea-9b12-ee9fc4f803b2.png)

**Comment by xile611** [comment]
Please open an issue follow the issue guide.
