### ISSUE TITLE
space between xAxis ticks is uneven and ticks are overlapping.

### ISSUE THREAD

**Issue by NaimSakaamini** [recharts/recharts#2227]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/xL78uvbt/1/](https://jsfiddle.net/xL78uvbt/1/)

### Steps to reproduce
space between xAxis ticks is uneven and ticks overlapping.

### What is expected?
even space between ticks where I can show the details of the ticks at the begging of the xAxis.
![Capture](https://user-images.githubusercontent.com/35412251/89655264-b0af9f80-d87e-11ea-9a8b-00cafeb4e429.JPG)
So the space between 10 and 20 to be similar to the one between 500-1000.

### What is actually happening?
space between xAxis ticks is uneven and ticks overlapping.

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.11.0 |
| System | windows |
| Browser | chrome |

**Comment by ckifer** [comment]
you can work around this a bit by angling the ticks a bit, adjusting font size, and changing the textAnchor
```javascript
<XAxis type="number" ticks={[10,20,50,200,500,1000]} angle={-35} textAnchor="end" tick={{fontSize: 14 }} minTickGap={1000} tickCount={5} unit="LUX" interval={0} scale="sqrt" domain={[0, 1000]}  />
```

svg text doesn't really have a concept of margin or padding so its hard without modifying position or hiding values with `interval`

**Comment by NaimSakaamini** [comment]
> you can work around this a bit by angling the ticks a bit, adjusting font size, and changing the textAnchor
> 
> ```js
> <XAxis type="number" ticks={[10,20,50,200,500,1000]} angle={-35} textAnchor="end" tick={{fontSize: 14 }} minTickGap={1000} tickCount={5} unit="LUX" interval={0} scale="sqrt" domain={[0, 1000]}  />
> ```
> 
> svg text doesn't really have a concept of margin or padding so its hard without modifying position or hiding values with `interval`. Especially on the scale you have.
> 
> https://jsfiddle.net/ar8n5mx2/19/

Thank you for the reply. I was hoping to even out the spaces between the ticks, wanted to make something like this:
https://files.slack.com/files-pri/TKJ74UADB-F01877L3KFW/lig16fe.gif
Do you think this is possible with recharts?

**Comment by ckifer** [comment]
@NaimSakaamini sure thing. Can you post the picture again using a different host or pasting directly, I can’t access your slack org :)

**Comment by NaimSakaamini** [comment]
> @NaimSakaamini sure thing. Can you post the picture again using a different host or pasting directly, I can’t access your slack org :)

Sorry here you go:
![lig16fe (1)](https://user-images.githubusercontent.com/35412251/90168658-456c3e80-dd52-11ea-8f42-b578beb86484.gif)

**Comment by ckifer** [comment]
@NaimSakaamini try this https://jsfiddle.net/zobrwLad/26/
I just tried random scales and `scale="log"` seems to separate the numbers a little more but not quite evenly. I'm not sure you're going to be able to get the even separation you want though.

**Comment by NaimSakaamini** [comment]
> @NaimSakaamini try this https://jsfiddle.net/zobrwLad/26/
> I just tried random scales and `scale="log"` seems to separate the numbers a little more but not quite evenly. I'm not sure you're going to be able to get the even separation you want though.

Thank you very much. I have tried this scale before its just not optimal as the reference dot will mostly be there and it will be over the lines. I'll keep trying but I really appreciate the help :)

**Comment by ckifer** [comment]
@NaimSakaamini sure thing. Yeah I wish it was easier to do something like what you want. Increasing the chart width, angling, or hiding some ticks so they don't overlap are your only options I think.
Tagging some related issues for reference:
#2139 
#148 
#1194

**Comment by alexandr-kazakov** [comment]
@NaimSakaamini did you find a solution for this?
