### ISSUE TITLE
PolarAngleAxis with duplicated categories don't draw radars

### ISSUE THREAD

**Issue by morozovkirill** [recharts/recharts#2228]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://codesandbox.io/s/zen-bartik-qdhjf?file=/src/App.js

### Steps to reproduce
Just look

### What is expected?
Radars areas were drawn

### What is actually happening?
When I use same names with PolarAngleAxis category names, radars stop drawing.

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.6 |
| React | react |
| System | - |
| Browser | chrome |

**Comment by ckifer** [comment]
I'm guessing this is meant to happen, but not sure. Maybe a flag could be added like `allowDuplicateKeys` or something similar.

**Comment by morozovkirill** [comment]
> I'm guessing this is meant to happen, but not sure. Maybe a flag could be added like `allowDuplicateKeys` or something similar.

Yeah, there is flag "allowDuplicatedCategory", but it's enabled by default - http://recharts.org/en-US/api/PolarAngleAxis#allowDuplicatedCategory

**Comment by ckifer** [comment]
@morozovkirill ah yeah thats super weird. when you have duplicated categories the category shows but not the data. When you set it to false the category is removed from the chart altogether and the data shows fine. Definitely a bug.
