### ISSUE TITLE
linearGradient isn't imported correctly when placed as a direct child of a ResponsiveContainer

### ISSUE THREAD

**Issue by Moshyfawn** [recharts/recharts#2229]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-lineargradient-inside-the-responsivecontainer-element-bug-3461s)

### Steps to reproduce
1. Add a linearGradient element inside a ResponsibleContainer as a direct child

### What is expected?
- No error thrown
- Linear gradient applied as a stroke

### What is actually happening?
Unhandled runtime error thrown:
`Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

| Environment | Info |
|---|---|
| Recharts | v1.8.1 |
| React | 16.11.0 |
| System | Windows 10 Pro v.10.0.18362 Build 18362 |
| Browser | Google Chrome v. 84.0.4147.105 (Official Build) (64-bit) |

**Comment by xile611** [comment]
`linearGradient `  should be a child of the `chart`.
