### ISSUE TITLE
Y Axis domain being reset by data beyond the min / max

### ISSUE THREAD

**Issue by cephirothdy2j** [recharts/recharts#223]
Hi, first off, the plugin is great and it's incredibly easy to use.

I am running into one issue: I have a use case where I would like to define a custom domain on an Y Axis and I have data points extending beyond the min or the max value. Example, domain is set as [0, 100] and I have data points [60, 89, 103, 116, 89, 85].

I would expect that my graph would extend out of vision past the Y Axis and the top edge of the chart, but instead, the Y Axis domain is automatically being reset to accommodate all data points.

Is it possible to force the Y Axis domain and not alter it based on the graphed data set?

Thanks!

**Comment by xile611** [comment]
@cephirothdy2j Maybe we can add a props like `domainAccommodate` to decide whether to tweak the domain or not. Do you have some suggestion about the name of this props?

**Comment by cephirothdy2j** [comment]
A prop for affecting the behavior would be perfect. How about `allowDataOverflow` ?

**Comment by xile611** [comment]
@cephirothdy2j I want to know which kind of display do you want when some points is beyond the min or the max value of domain.

1. May display part of the outside point
![image](https://cloud.githubusercontent.com/assets/6111424/18427561/9694d7f0-78fb-11e6-9f02-1d37f201e3d8.png)

2. cut the outside point directly
![image](https://cloud.githubusercontent.com/assets/6111424/18427752/a786cdd8-78fc-11e6-99a6-934100a672d0.png)

**Comment by xile611** [comment]
Fixed in version 0.14.1.
