### ISSUE TITLE
I get "Invalid hook call" inside custom legend on PieChart

### ISSUE THREAD

**Issue by wellyal** [recharts/recharts#2230]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-demo-674i2?file=/src/App.js)

### Steps to reproduce
Use a PieChart with a Legend using its prop "content". Pass a Custom legend component to the content prop and use any hook from react (eg useState) inside your Custom legend component.

### What is expected?
To work properly with hooks

### What is actually happening?
Not working when I use hooks and getting a error from react like 

Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | react 16.9.0 |
| System | macOS high sierra 10.13.6  |
| Browser | chrome 84.0.4147.105 |

**Comment by ckifer** [comment]
@wellyal this should work: https://codesandbox.io/s/recharts-demo-forked-9nk1m

I just used JSX syntax in the content prop
`content={<RenderLegend />}`

Not sure if it is supposed to work with just passing `renderLegend` as a function or not, but that should solve your issue.

**Comment by wellyal** [comment]
> @wellyal this should work: https://codesandbox.io/s/recharts-demo-forked-9nk1m
> 
> I just used JSX syntax in the content prop
> `content={<RenderLegend />}`
> 
> Not sure if it is supposed to work with just passing `renderLegend` as a function or not, but that should solve your issue.

Thanks that just did the trick.
