### ISSUE TITLE
Ineractive legends in radar chart

### ISSUE THREAD

**Issue by Mahathi1112** [recharts/recharts#2233]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In cases where multiple data keys are used, there will always be a chance where the radar charts overlap. It would be great to focus on any one legend at a time. Found this feature in chart.js, however would like to have this in recharts as well. Is there an existing feature that addresses this functionality? 

### What does the proposed API look like?
Something in-built for onClick.

**Comment by xile611** [comment]
Related PR is welcome.
