### ISSUE TITLE
Bar Chart with scale="band" has off center tooltip cursor

### ISSUE THREAD

**Issue by alexmarmon** [recharts/recharts#2234]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/aemarmon/2sbvhr0j/62/](https://jsfiddle.net/aemarmon/2sbvhr0j/62/)

### Steps to reproduce
Add scale="band" to a bar chart XAxis.

### What is expected?
The tooltip cursor should appear behind the bar. 

### What is actually happening?
The tooltip cursor appears on the center of the bar axis line, to the left of the bar that you are trying to focus.\
<img width="267" alt="Screen Shot 2020-08-12 at 1 06 21 PM" src="https://user-images.githubusercontent.com/17775646/90062504-a1748b80-dc9c-11ea-840b-c1fb8cc5b69c.png">

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.6 |
| React | 16.13.1 |
| System | Mac OS Catalina |
| Browser | Lastest Chrome |

**Comment by ckifer** [comment]
@alexmarmon Odd, when I do this with your fiddle what you are describing occurs, but when I do this on a bar chart in my repo it doesn't happen.

**Comment by alexmarmon** [comment]
@ckifer 🤔 Any differences you can see between the fiddle and your repo? What version of recharts are you using?

**Comment by ckifer** [comment]
@alexmarmon I'm using `v2.0.0-beta.6` same as it looks like you are. 

And no, I have a lot of configuration going on but nothing that should effect how the tooltip/cursor is rendered. I am using a custom tooltip component but even if I remove that everything is rendered right. It is that `scale="band"` in the fiddle for sure but me adding the same to my repo does nothing.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by annmarie-switzer** [comment]
@alexmarmon Did you ever find a solution to this? I'm having the same issue using `scale="linear"`.

**Comment by ckifer** [comment]
@annmarie-switzer - I can still reproduce this with `scale="band"` but linear isn't really an option for a BarChart. Can you modify the sandbox to represent your issue https://codesandbox.io/s/stacked-bar-chart-forked-7ly06k?file=/src/App.tsx

**Comment by DiederikvandenB** [comment]
Also running in to this issue. Any news?
