### ISSUE TITLE
interrupted animations can make labels disappear forever

### ISSUE THREAD

**Issue by cainlevy** [recharts/recharts#2235]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

Actually I found a [lot of other issues](https://github.com/recharts/recharts/issues?q=is%3Aissue+label+animation). This has been bugging people for years. Let's fix it!

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/interrupted-animation-makes-labels-disappear-forever-jbrfx)

### Steps to reproduce
Render a pie chart with labels. Interrupt the first animation with any change that creates a new `updateId`, such as a change in the data object equality.

### What is expected?
The labels should appear even if the animation is interrupted.

### What is actually happening?
The labels do not appear because `isAnimationFinished` remains false forever.

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.13.1 |
| System | all |
| Browser | all |

---
My bug was caused by Apollo Client's `cache-and-network` policy, which renders eagerly with the current copy of data while fetching a new copy from the API (which happens to be identical). When this network call finishes before the pie chart animation, labels never appear.

My reproduction uses a frivolous change to `data` in order to trigger a new `updateId`, but my read of the implementation details suggests that the same result could happen due to changes in width, height, layout, stackOffset, or margin.

https://github.com/recharts/recharts/blob/590631e983124db962dad3b33dd4d161411ae31c/src/chart/generateCategoricalChart.tsx#L295-L302

The cause appears to be that `isAnimationFinished` remains false and blocks `renderLabels` from rendering. It's a state management problem.

**Comment by mlaposta** [comment]
Having the same issue. In my case, I have a pie chart on a page, with a modal in the foreground. If the modal is closed while the pie chart is animating, the labels disappear.

What I also find odd though, is that when the modal is closed, the pie chart skips the animation and just redraws fully, but as noted without the labels. So somehow the modal closing is cancelling the chart drawing animation, which results in the chart appearing instantly, but without labels.

**Comment by romgrk** [comment]
This issue has been present for a while, any ETA on the resolution?

**Comment by romgrk** [comment]
This issue has been present for a while, any ETA on the resolution?

**Comment by gknapp** [comment]
Given the lifetime of this issue I've accepted I'll likely end up replacing my recharts Pie with [airbnb visx](https://airbnb.io/visx/pies)

**Comment by domino2** [comment]
This is still an issue with updated environment.

| Environment | Info |
| --- | --- |
| Recharts | v2.1.9 |
| React | 17.0.2 |
| System | all |
| Browser | all |

My workaround is to change the width/height to trigger internal animation again if data structure have been changed.
So in this example, the labels will appear after 5 seconds.
Not an ideal solution!

[![csb](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/interrupted-animation-makes-labels-disappear-forever-forked-nktsy?file=/src/index.js)

**Comment by ckifer** [comment]
Hi all, 

Sorry this issue has been here for so long. Recharts has been without active maintainers for a while.

Taking the original example and upgrading to 2.2.0 the labels now render after the timeout. 

From my testing it looks like this is working 2.1.13+
and from the commit log looks like this fixed it
https://github.com/recharts/recharts/commit/9fb344b1202ac5913f14d8c3e54ad4457c631344

Resolving for now, feel free to comment if this is still not working for you. Thanks!
