### ISSUE TITLE
Area Chart: `stackId` and `null`/`` value don't work correct together

### ISSUE THREAD

**Issue by etuseeva** [recharts/recharts#2236]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-oe9fv?file=/src/index.js)

### Steps to reproduce
1) Use `AreaChart`
2) Add several `Area`s with the same `stackId`
3) Provide `data` with values, that can be `null`

### What is expected?
I expect such chart:
<img width="118" alt="Screenshot 2020-08-13 at 16 03 12" src="https://user-images.githubusercontent.com/14372206/90138861-41efac00-dd80-11ea-8845-f4f3b1fec156.png">

### What is actually happening?
But I got the following chart:
<img width="117" alt="Screenshot 2020-08-13 at 16 04 08" src="https://user-images.githubusercontent.com/14372206/90138874-44ea9c80-dd80-11ea-9e47-5acd61fa385f.png">

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.13.1 |
| System | macOS 10.15.5 |
| Browser | Google Chrome 84.0.4147.105 |

**Comment by ckifer** [comment]
@etuseeva the chart in the codesandbox looks fine to me. If there is a null the value isn't shown on the chart / it appears to go down to 0 and doesn't show in the tooltip anymore. 0 and null look the same but 0 is in the tooltip and null is not.
There is a `connectNulls` flag but that doesn't seem to make a difference for me.

**Comment by etuseeva** [comment]
Hi @ckifer! Thanks for your response, but it looks strange. As for me, we shouldn't have:
1 - this dot, since `value = null` (not `0`) 
2 - these lines, that are connected to `0`, since by default `connectNulls=false`

<img width="788" alt="Screenshot 2020-08-14 at 11 31 22" src="https://user-images.githubusercontent.com/14372206/90230531-58e6da80-de22-11ea-846e-ef6b1712a097.png">

**Comment by ckifer** [comment]
@etuseeva Both of those things make sense. Especially the dot being visible.. I can't speak to either of these things, but just trying to see if I can help in any way. I don't know how to make the chart how you want, but this is good record of an issue for sure. It really depends on if this is how it was supposed to be or not and if anyone wants to take the time to fix it.

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/issues/2316 related/same issue

**Comment by ckifer** [comment]
![image](https://github.com/user-attachments/assets/67af271f-345e-480e-8906-c037980edf58)
this is how this sandbox looks in the latest.

Going to resolve this as fixed
