### ISSUE TITLE
Add props to trigger event when the svg has been created

### ISSUE THREAD

**Issue by ald-pulsar** [recharts/recharts#2238]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
My current problem is that I need to know when the chart with its <svg> tag has been created to make several calculation about the drawing space, differents ticks, etc. Because we use try to use recharts to render a graph with X and Y axis and we use overlay to let the user draw different box that we then want to draw on your charts with ReferenceArea components. To make the conversion between the overlay and recharts coordinates, we need to directly calculate the factors to handle it. 
It should help people who want to add custom interaction features to your library.
If another way to make something similar already exist, i would be interested to know because i already took quite a good time looking in different documentation to find it (including recharts API, examples and doc)

### What does the proposed API look like?
It may be adding a non-mandatory ref props in your ResponsiveContainer or in all the Chart components. And to pass the ref to the svg element you draw with the library. When it would be created, it should trigger events depending on this same ref (like useEffect with this ref in the dependency array)

**Comment by vtarelkin** [comment]
@xile611 stop closing everything. It is not fixed and is not done
