### ISSUE TITLE
PieChart is shown empty with negative values

### ISSUE THREAD

**Issue by andriyloza** [recharts/recharts#2239]
- [ +] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It can be great to use PieChart with negative data, also with negative values in labels and tooltip.
Actually Pie chart is empty with negative values. I have to set Math abs of values, but in that case have positive values  in labels and tooltip.

### What does the proposed API look like?
There is no proposal in API to PieChart,
My way is to reformat data so it has  Math.abs of value, but in that case we have no negative values in labels and tooltip

**Comment by andriyloza** [comment]
problem solved if we use dataKey as abs value, but value stays the same negative

**Comment by m1guer** [comment]
hi, can share how you do this?

**Comment by ckifer** [comment]
I think they mean you just have two values that exist in your data

```
const data = [
  {
    name: "Slice 1",
    value: -90,
    positiveValue: 90
  }
]

...

<PieChart>
  ...
  <Pie dataKey="positiveValue" />
```

Then use `value` in your tooltip/label
