### ISSUE TITLE
ResponsiveContainer: Add maxWidth and maxHeight properties

### ISSUE THREAD

**Issue by connorlindsey** [recharts/recharts#2246]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have a responsive container I want to take 100% of the container width and I want to be able to set the maxHeight. At the moment, I can set minHeight or height. I tried setting it to 100% and adding the maxHeight to a div around the responsive container with no luck. I think maxHeight and maxWidth would be helpful to include to the API. 

### What does the proposed API look like?
`<ResponsiveContainer width="100%" maxHeight={600} />`

**Comment by xile611** [comment]
`maxHeight` is supported.

**Comment by allengordon011** [comment]
`maxHeight` is, but `maxWidth` is not. I second adding `maxWidth`.
Also, `maxHeight` is missing from the Properties at https://recharts.org/en-US/api/ResponsiveContainer

**Comment by patricklittle** [comment]
A solution for your maxWidth issue is to wrap your `ResponsiveContainer` with something with a max width:

```
<div style="max-width:500px">
    <ResponsiveContainer width="100%">
        <Chart/>
    </ResponsiveContainer>
</div>
```

**Comment by allengordon011** [comment]
Thanks @patricklittle. I ended up using `<ResponsiveContainer height={400} width='80%' minWidth='300px'>` and targeting the RECharts responsive container class with 
`.recharts-responsive-container {
    max-width: 800px;
  }`
