### ISSUE TITLE
Dots on the same line are not shown in combination with gradient line

### ISSUE THREAD

**Issue by gnoesiboe** [recharts/recharts#2247]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/vru8sone/39/](https://jsfiddle.net/vru8sone/39/)

### Steps to reproduce
Line between dots is not shown in: https://jsfiddle.net/vru8sone/39/

When I remove the gradient bij removing the `<linearGradient />`, the line is showing:

https://jsfiddle.net/vru8sone/40/

### What is expected?
Expected is that the line is shown between the dots

### What is actually happening?
The line is not showing

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.13.1 |
| System | Ubuntu 20.04 (but also on OSX) |
| Browser | Firefox v79 |

**Comment by sfeast** [comment]
@xile611

Possibly the same issue as https://github.com/recharts/recharts/issues/1234 which was closed, however it is still a problem with the latest versions.

**Comment by EugeneBugor** [comment]
@xile611 

Having same issue - I've tested the behavior with all 2.0.0 beta versions.

**Comment by onikitin03** [comment]
@xile611 the same for me

**Comment by xile611** [comment]
It's the bug of linear gradient when all the points are in a  line. A workaround is change the position of some point a little.

**Comment by gnoesiboe** [comment]
I don't see how that is a solution that closes this issue? You call it a workaround..

**Comment by gtupak** [comment]
This should be reopened as the bug still persists.

**Comment by cam-shaw** [comment]
@xile611 I'd also ask for this to be opened again. 

> A workaround is change the position of some point a little.

For anyone seeing this in the future, an example of how to workaround this is to modify your `y` for the first data point to some extremely minor increase/decrease (e.g. 0.00001). Low enough number depending on how small the Y values are that it won't visually impact.

**Comment by peterklingelhofer** [comment]
Here's another potential [workaround](https://stackoverflow.com/questions/72559003/how-to-show-data-with-no-variation-with-linear-gradient-using-rechart).
