### ISSUE TITLE
Y ticks overlay y label for large values

### ISSUE THREAD

**Issue by johanbook** [recharts/recharts#2248]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-eyke7?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Set a ylabel and use a large value for of a data point.

### What is expected?
Y ticks should not overlay y label

### What is actually happening?
Y ticks do overlay y label

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.6 |
| React | 16.13.1 |
| System | Ubuntu |
| Browser | Chrome |

---
You can add some dynamic padding or perhaps convert it to exponential notation (similar to that is done for small numbers)

**Comment by pedrocardoz0** [comment]
Try to use this ```<YAxis label={{ value: "y", position: "left", offset: 13 }} /> ```

**Comment by johanbook** [comment]
That fixes that particular case, but if a larger number comes along (or there are no large numbers) we get similar problems @pedrocardoz0

**Comment by pedrocardoz0** [comment]
> That fixes that particular case, but if a larger number comes along (or there are no large numbers) we get similar problems @pedrocardoz0

Got your point

**Comment by myyellowshoe** [comment]
same issue here. @pedrocardoz0 fixes is good ok short term, but would be interesting to have a more responsive styling for those labels.
