### ISSUE TITLE
New feature: ability to set y-axis text  value stroke dynamically

### ISSUE THREAD

**Issue by jaybe78** [recharts/recharts#2249]
## Do you want to request a feature or report a bug?
Feature

I'm looking at building what you see below:
y-axis with green text when value > 0, grey when value == 0 and red when value < 0
<img width="66" alt="Screenshot 2020-08-21 at 18 23 58" src="https://user-images.githubusercontent.com/3605098/90918034-e6ef3200-e3db-11ea-9a33-5525728936e9.png">

**Comment by xile611** [comment]
It's recommended to use customized `tick` to handle this case
