### ISSUE TITLE
New Feature: User should be able to add spaces between stacked bars in stacked bar chart

### ISSUE THREAD

**Issue by gblessy** [recharts/recharts#2250]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Users need to be able to create horizontal stacked bar chart and add space between bars. That is applicable when user has 100% of resources and needs to show resource allocation.
Here is an example of such Stacked Bar Chart
<img width="598" alt="Screen Shot 2020-08-21 at 11 39 05 AM" src="https://user-images.githubusercontent.com/16084489/90924185-d8852400-e3a3-11ea-9fef-d63c063a0535.png">

### What does the proposed API look like?
<BarChart width={600} height={200} data={data} layout="vertical" barStackGap={4}>
 Similarly to barGap user should be able to use % or number. Default should be 0.

**Comment by xile611** [comment]
Maybe you can add stroke="#fff" to achieve this feature.
