### ISSUE TITLE
Distribute xAxis labels evenly

### ISSUE THREAD

**Issue by Gunner17** [recharts/recharts#2256]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/gunner17/mjnu25rv/6/](https://jsfiddle.net/gunner17/mjnu25rv/6/)

### Steps to reproduce
Try to render any chart inside the ResponsiveContainer with xAxis interval="preserveStartEnd" and make sure that at least 15 data points are present. See example: https://jsfiddle.net/gunner17/mjnu25rv/6/

### What is expected?
The gap between the xAxis label should always be even at any chart width while using ResponsiveContainer and when xAxis interval is set as "preserveStartEnd".

### What is actually happening?
When using Recharts ResponsiveContainer and setting xAxis interval="preserveStartEnd", the xAxis labels in the charts starts showing uneven spaces between them. Please take a look at this link: https://jsfiddle.net/gunner17/mjnu25rv/6/ and see the gap between the last and the second last labels.

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.13.1 |
| System | MacOS Mojave 10.14.6 |
| Browser | Safari 13.1.2, Chrome 84.0.4147.135 |

---
Can we please get a solution for this behavior as it has become a priority fix for us.

**Comment by ckifer** [comment]
@Gunner17 it looks like what is expected is happening. The start and end ticks are preserved and when there isn't enough room to fit another tick recharts has to remove it or else you start having tick collisions/overlap. In the above example there is no way to evenly space the ticks while still preserving start and end and aligning with a category. The only thing you could do is shift the ticks down one which would create a gap at the beginning instead.

**Comment by Gunner17** [comment]
This would have been nice feature though, i.e. after preserving spaces for the start and end label, Recharts could calculate the remaining xAxis width and only show few labels that can fit the remaining width, with equal spaces between all these labels.

But as it stands, what do you think my best bet would be to resolve this: is there any way to get (only) the xAxis line width? So that I can try to calculate the remaining width (i.e. xAxis line width - (start label width + end label width)) and then place few of the labels on the remaining space in such a way - that these labels can have equal space between them? If you have any alternative idea, please feel free to share.
