### ISSUE TITLE
Stacked barchart with dynamic data error

### ISSUE THREAD

**Issue by whizz5** [recharts/recharts#2257]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-f0t6e?file=/src/index.js)

### Steps to reproduce
Create a stacked barchart with dynamic data using loops

### What is expected?
Stacked bar chart is produced with distinct categories 

### What is actually happening?
Stacked bar charts are produced however some data is mysteriously repeated and causes extra bars to be produced resulting in them fallinf outside of the stack group and causing barchart widths to not take up full category

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome |

---
This may infact be a logic issue on my part however the console logs seem to verify that the correct amount of bars are being produced however extra bars are generated that fall outside of the stack group

**Comment by ckifer** [comment]
@whizz5 It looks like the bars that are grouped together are the ones with the same number of occurrences in your data set. ex: `track53` and `track41` both appear 3 times and are stacked together. You are repeating the `Bar` component more times than is intended I think. 

Is this what you are expecting? https://codesandbox.io/s/recharts-issue-template-forked-r6lic?file=/src/index.js

I think you just need one `stackId` and specify only the changes in `dataKey` as you loop through your items.

**Comment by KevinSig** [comment]
> @whizz5 It looks like the bars that are grouped together are the ones with the same number of occurrences in your data set. ex: `track53` and `track41` both appear 3 times and are stacked together. You are repeating the `Bar` component more times than is intended I think.
> 
> Is this what you are expecting? https://codesandbox.io/s/recharts-issue-template-forked-r6lic?file=/src/index.js
> 
> I think you just need one `stackId` and specify only the changes in `dataKey` as you loop through your items.

Im still seeing duplicates of each track in the b
![Screen Shot 2022-08-19 at 11 34 03 AM](https://user-images.githubusercontent.com/41274608/185685141-b1cbeb3f-5bad-41a3-afa9-2a5ff412c46f.png)
ars?

**Comment by Sholls000** [comment]
@KevinSig How did you resolve this error?

**Comment by willdk3000** [comment]
It has to do with the number of items in the array over which the map function is called to generated the bars
If I understand correctly, you must generate 1 bar stack for each entry
The code above generates 2 bar stacks for each entry
To correct this, add an "if" condition for preventing the map function to map over each entry twice :

        .map((tripId, index) => {
          if (index <= Object.entries(dataObj).length/2) {
          return (
            <Bar
              dataKey={tripId}
              stackId="1"
              fill={hexColourArr[index]}
              name={`${tripId}`}
            />
          );
          }
 
Fixed the issue for me

Sorry I never post so I don't know how to properly format this answer
