### ISSUE TITLE
Retrieve Y value of graph on cursor location

### ISSUE THREAD

**Issue by minamesephy** [recharts/recharts#2258]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Users often want to be able to retrieve what the value under their cursor is, not just where the value at the line is. For example, the image that I provide in this question: https://stackoverflow.com/questions/63585743/recharts-value-at-pointer-to-show-in-tooltip

We would want to be able to retrieve the value of Y at the cursor so we can present it elsewhere on the page. The users said this will be helpful when making predictions.

### What does the proposed API look like?
onMouseMove or something similar on the chart could present the Y value the cursor is on in the chart in the event

**Comment by ckifer** [comment]
@minamesephy I don't think that Y value exists in the chart as anything except for an SVG coordinate. The only points that are accessible are the data points you provide via the `payload` prop being passed to `<Tooltip />`. Giving the hovered x,y coordinates at the scale of the chart would have to be a new feature I think (added this comment to the SOF as well for visibility).

**Comment by minamesephy** [comment]
That seems to be the case - which is why I'm requesting it as a feature here. I had given up on finding or receiving any existing way :) I think Recharts would have to be updated to expose the information.

**Comment by ckifer** [comment]
@minamesephy hopefully the maintainers show some signs of activity soon. I emailed @xile611 a few weeks ago with no response yet.

**Comment by xile611** [comment]
This feature can be implemented by customized tooltip.

**Comment by nielsuit227** [comment]
@xile611 Any direction as to how this can be implemented would be much appreciated. Also don't see a reason why this ticket is closed, is this feature request denied?
