### ISSUE TITLE
Vertical Brush similar to Horizontal Brush

### ISSUE THREAD

**Issue by minamesephy** [recharts/recharts#2259]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Users want to be able to adjust the Y range of their graph the same way that they can for the X axis.
http://recharts.org/en-US/examples/BrushBarChart
http://recharts.org/en-US/api/Brush

### What does the proposed API look like?
Same as existing, but with attributes defining that the bar brush should be along the Y axis and control the range of the Y axis instead of the X axis.

**Comment by xile611** [comment]
Thanks for your suggestion, we have added this feature to the plan of 2.0

**Comment by VladShaluhin** [comment]
Hello
I couldn't find information how to use this feature. 
Could you please help me with this?

**Comment by AlexMayleRdn** [comment]
It doesn't appear that this is in as of 2.0.8. No API change to Brush and the internal code still looks like it makes the x-axis assumption.

**Comment by vignesh-vimana** [comment]
Is it possible to do this with v2+?

**Comment by LauGroupie95** [comment]
Any update about this issue? Is now the feature of brushing both the X and the Y axis available?

**Comment by BeHustle** [comment]
+1

**Comment by jcorevnue2022** [comment]
bump

**Comment by dederomagnolo** [comment]
is this available? Could not make it work as well.

**Comment by ckifer** [comment]
No this never works, reopened. 

Someone tried to add it here https://github.com/recharts/recharts/pull/5934

But the PR is way too much at once
