### ISSUE TITLE
Is there any way to plot points to scale on the X Axis?

### ISSUE THREAD

**Issue by ackerleytng** [recharts/recharts#226]
I've set up a jsfiddle here: http://jsfiddle.net/cw3h29sm/

The x axis is labelled 0, 1.5, 2, 9, 20, and they're equally spaced. Is there any way to have those values plotted to scale? 0 and 1.5 should be closer together, and then 20 should be really far away.

Thanks!

**Comment by ackerleytng** [comment]
Figured it out, it's called scatter! Thanks for an amazing library!!

**Comment by kaiser-naren** [comment]
Could you please post the example/jsfiddle where you solved your issue?

**Comment by ackerleytng** [comment]
Instead of using Line, we should be using Scatter, following something like http://recharts.org/api/#ScatterChart

**Comment by charlyreact** [comment]
![image](https://user-images.githubusercontent.com/32701565/31498577-930741c4-af62-11e7-8f68-18c02974d21a.png)
 I am using scatter but my points are still equally spaced
