### ISSUE TITLE
Label hiding behind Line series

### ISSUE THREAD

**Issue by Gunner17** [recharts/recharts#2261]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/gunner17/39sgzoje/1/](https://jsfiddle.net/gunner17/39sgzoje/1/)

### Steps to reproduce
If you look closely at the 3rd bar with value = 1370, you will see that the series line is appearing on top of the label, I want the label to appear on top of the series line (like a higher z-index behavior). How can I achieve that? Example link: https://jsfiddle.net/gunner17/39sgzoje/1/

### What is expected?
If you look closely at the 3rd bar with value = 1370, you will see that the series line is appearing on top of the label, I want the label to appear on top of the series line (like a higher z-index behavior). How can I achieve that? Example link: https://jsfiddle.net/gunner17/39sgzoje/1/

### What is actually happening?
If you look closely at the 2rd var with value = 1370, you will see that the series line is appearing on top of the label.

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.13.1 |
| System | MacOS Mojave 10.14.6 |
| Browser | Safari 13.1.2, Chrome 84.0.4147.135 |

**Comment by ckifer** [comment]
Hey @Gunner17 
It looks like ComposedChart is rendered based on the order of the chart types defined. I don't think there is a way as it stands to make the labels be rendered on top. This would have to be a future addition/fix.

**Comment by Gunner17** [comment]
Got it, thanks for the reply.
