### ISSUE TITLE
Remove core-js from dependencies

### ISSUE THREAD

**Issue by daveisfera** [recharts/recharts#2262]
- [X] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Current package.json](https://github.com/recharts/recharts/blob/9d4ec579d290fe26e061c18b48e7176d21789f21/package.json#L58)

### Steps to reproduce
yarn install recharts

### What is expected?
`core-js` is not required by `recharts`

### What is actually happening?
`core-js` is installed when `recharts` is installed

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.13 |
| System | macOS 10.15.6 |
| Browser | Safari 13.1.2 |

---
`core-js` should be selected by the user of `recharts` when they use/bundle it and a specific version shouldn't be listed in `dependencies` of `recharts`

**Comment by avindra** [comment]
#2321 open for removing **core-js**, as well as the vestigial polyfill module.

**Comment by avindra** [comment]
ICYMI: #2321 is merged and released in beta 8:

https://github.com/recharts/recharts/releases/tag/v2.0.0-beta.8

The raw bundle size drops by 15KB after that:

https://bundlephobia.com/result?p=recharts@2.0.0-beta.8
