### ISSUE TITLE
How do  you present 1 percent to 1px for the bubble chart in z axis 

### ISSUE THREAD

**Issue by lazarmat** [recharts/recharts#2264]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Being able to present the bubble chart exactly one to one of the pixel and percentage value.

Let say you have 70%, I want to represent that as 70pixel circle on the graph

### What does the proposed API look like?
N/A

**Comment by xile611** [comment]
Please open an issue follow the issue guide.
