### ISSUE TITLE
How to get hovered series name while hovering on a specific series? 

### ISSUE THREAD

**Issue by Gunner17** [recharts/recharts#2265]
Currently I see no way to get the specific series or dataKey name when I hover on particular series on a chart, e.g. Line, Area, Bar etc. 

For example, if you see this chart here: https://jsfiddle.net/alidingling/xqjtetw0/, there are 2 series being plotted:
1. uv (in green)
2. pv (in purple)

What I need is: when I hover on the "uv" series (green), a callback or event that will tell me the exact series name, e.g. "uv". Similarly, when I hover on the purple series, is there a way to know that I have hovered on the "pv" series? 

I know I can get that information by using "activeDot"; As activeDot can tell you the specific "dataKey" that you have hovered on. But the problem is, I want that dataKey/series name while hovering on any part of the series and not limited to activeDot. Is that somehow possible?

**Comment by ckifer** [comment]
It depends on where you want this. You can get it within a custom tooltip component which there are good examples of in #275. You might be able to take what you get from that and do something else with it if that is your intent. You can also get the almost the whole state of the chart by adding an onMouseEnter event to <LineChart />. https://jsfiddle.net/1avod6mz/4/

**Comment by Gunner17** [comment]
> https://jsfiddle.net/1avod6mz/4/

This is useful info. But the payload (CustomTooltip) or activePayload (onMouseEnter event of LineChart) gives me all the series level or payload info corresponding to a specific label. I wanted to further filter on that info and only want to get the name of the series line where the user might have hovered; So basically, if the user is hovering on any point in the "uv" series line (the green line), I want to only get "uv" and exclude "pv". Similarly if user has hovered anywhere on the "pv" line, I would like to get "pv" as a callback. Right now, the payload has all the series level info ("uv" + "pv" + "label" etc.), but there is probably no way to filter out the specific series line name where user might have hovered?

**Comment by ckifer** [comment]
@Gunner17 yeah I'm not sure that's possible at this point because the hover action is getting the index of the x value and not specifically where you hover on the graph in terms of which series you are on. I'm sure there's some way to hack/figure it out.

**Comment by Gunner17** [comment]
> @Gunner17 yeah I'm not sure that's possible at this point because the hover action is getting the index of the x value and not specifically where you hover on the graph in terms of which series you are on. I'm sure there's some way to hack/figure it out.

Yes, just figured it out, since I am passing the dataKey info to individual <Line /> component, I added onMouseOver event to get the name of the hovered series. Thanks for the help 🙏!
