### ISSUE TITLE
An integer stackId causes bars to re-order

### ISSUE THREAD

**Issue by spinnercat** [recharts/recharts#2266]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/e74b9x6s/](https://jsfiddle.net/e74b9x6s/)

### Steps to reproduce
On the <Bar> object add a stackId that is a number. This will cause the bars to appear ordered by stackId - uv comes before pv. Remove the stackId or make it a string (e.g. "3string" instead of "3" and they will appear in the original order (in the same order as the Bars are defined) with pv coming before uv. 

### What is expected?
Bars will appear in the same order as they are defined. StackId, per the documentation (https://recharts.org/en-US/api/Bar#stackId), will only be used for grouping and will not impact ordering of bars if no stacking occurs. 

Or, update the documentation to mention this side-effect - it could be used as a feature for ordering bars. 

### What is actually happening?
Bars appear in order by stackId if and only if the stackId is a number.

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.9.0 |
| System | MacOS 10.15.4 |
| Browser | Chrome v85 |

---
We ran into this when we used to have alphanumeric string data ids and changed to using number ids - we used them for stackId and this caused our bars to appear out of order after this change.

**Comment by xile611** [comment]
It's recommended to use string as `stackId`.
