### ISSUE TITLE
waterfall chart

### ISSUE THREAD

**Issue by ahmedramadan65** [recharts/recharts#2267]
i'm trying to create waterfall chart .. does anyone have an idea ? does library support this chart ?
![CompleteWaterFallChartSSPowerBI](https://user-images.githubusercontent.com/28717922/92096449-30298380-edd7-11ea-9800-afdd86be52da.jpeg)

**Comment by celiaongsl** [comment]
Hi @ahmedramadan65! Hope this tutorial from my blog helps: https://bit.ly/33Q9ox7

**Comment by richardmundell1** [comment]
@JoeVanGundy did you have any success figuring out how to do horizontal lines?
