### ISSUE TITLE
ResponsiveContainer cannot be rendered and hence cannot be tested using react testing library

### ISSUE THREAD

**Issue by adititipnis** [recharts/recharts#2268]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-djx3q?file=/src/index.test.js)

### Steps to reproduce
1. Use ResponsiveContainer to render a chart
2. Render the chart component with react testing library

### What is expected?
The chart should get rendered

### What is actually happening?
 ```
<div class="recharts-responsive-container makeStyles-chart-21" style="width: 100%; height: 300px;">
     <div style="position: absolute; width: 0px; height: 0px; visibility: hidden; display: none;"/>
</div>
```

The chart is hidden with 0 height and width. No dom nodes are created for the chart.

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.13.0 |
| System | macOS Mojave 10.14.6 |
| Browser | React testing library |

---
The chart is rendered while testing if ResponsiveContainer is replaced with a div.

**Comment by shoaibbhimani** [comment]
I faced this same issue I solved it by simple adding div between ResponsiveContainer and Linecharts

<ResponsiveContainer width="100%" height={300}>
        <div>
            <LineChart
        width={600}
        height={300}
        data={data}
        margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
      >
        <XAxis dataKey="name" />
        <YAxis />
        <CartesianGrid strokeDasharray="3 3" />
        <Tooltip />
        <Legend />
        <Line
          type="monotone"
          dataKey="pv"
          stroke="#8884d8"
          activeDot={{ r: 8 }}
        />
        <Line type="monotone" dataKey="uv" stroke="#82ca9d" />
      </LineChart>
        </div>
    </ResponsiveContainer>```

**Comment by Ueland** [comment]
I tested adding a div but that did not change anything for me. Interesting this that it works just fine in the jsfiddle version of the demo code: https://jsfiddle.net/alidingling/9wnuL90w/

**Comment by adititipnis** [comment]
> I faced this same issue I solved it by adding div between ResponsiveContainer and Linecharts
> 
> ```
> <ResponsiveContainer width="100%" height={300}>
>         <div>
>             <LineChart
>         width={600}
>         height={300}
>         data={data}
>         margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
>       >
>         <XAxis dataKey="name" />
>         <YAxis />
>         <CartesianGrid strokeDasharray="3 3" />
>         <Tooltip />
>         <Legend />
>         <Line
>           type="monotone"
>           dataKey="pv"
>           stroke="#8884d8"
>           activeDot={{ r: 8 }}
>         />
>         <Line type="monotone" dataKey="uv" stroke="#82ca9d" />
>       </LineChart>
>         </div>
>     </ResponsiveContainer>
> ```

That worked!

**Comment by Ueland** [comment]
For anybody else ending up here. My problem was that i tried to use ResponsiveContainer on server side rendering, which will not work as it is not supported.

**Comment by krzysu** [comment]
I fixed that by defining fixed width of ResponsiveContainer, just in my tests, ie.

```
<ResponsiveContainer width={700} height={300}>
```

Otherwise `recharts` doesn't know the container size and defaults to return nothing.

**Comment by CaioArg** [comment]
> I fixed that by defining fixed width of ResponsiveContainer, just for my tests, ie.
> 
> ```
> <ResponsiveContainer width={700} height={300}>
> ```
> 
> Otherwise `recharts` doesn't know the container size and defaults to return nothing.

How did you fixed it only for the test? I need to do that but I don't know how..

**Comment by krzysu** [comment]
you mock ResponsiveContainer in your test, something like below:

```
jest.mock('recharts', () => {
  const OriginalResponsiveContainerModule = jest.requireActual('recharts');

  return {
    ResponsiveContainer: ({ height, children }) => (
      <OriginalResponsiveContainerModule.ResponsiveContainer
        width={800}
        height={height}
      >
        {children}
      </OriginalResponsiveContainerModule.ResponsiveContainer>
    ),
  };
});
```

**Comment by joshua-phillips** [comment]
You're a life-saver, @krzysu! This was making me crazy. The only thing I'll add is that I had to return all the other recharts components as-is with spread syntax on the original module.

```
jest.mock('recharts', () => {
    const OriginalModule = jest.requireActual('recharts');

    return {
        ...OriginalModule,
        ResponsiveContainer: ({ height, children }) => (
            <OriginalModule.ResponsiveContainer width={800} height={height}>
                {children}
            </OriginalModule.ResponsiveContainer>
        ),
    };
});
```

Thanks again!

**Comment by jacinyan** [comment]
`import React from "react";
import { BarChart, YAxis, Bar, ResponsiveContainer } from "recharts";

export default function BarGraph({ data, width = 500, height = 500 }) {
  return (
    <ResponsiveContainer width="100%" height={500}>
      <>
        <BarChart
          width={width}
          height={height}
          data={data?.map((value) => ({ y: value }))}
          margin={{ top: 20, right: 20, left: 20, bottom: 20 }}
        >
          <YAxis dataKey="y" />
          <Bar type="monotone" dataKey="y" fill="#ff7300" yAxisId={0} />
        </BarChart>
      </>
    </ResponsiveContainer>
  );
}
`
`import React from "react";

import { cleanup, render, screen, waitFor } from "src/utils/test-utils";

// import Dashboard from "../../views/dashboard/Dashboard";
import BarGraph from "../../views/dashboard/BarGraph";

describe("BarGraph", () => {
  const data = [40, 60];
  const size = { width: 500, height: 1000 };

  let graphContainer;

  beforeEach(() => {
    const { container } = render(
      <BarGraph data={data} width={size.width} height={size.height} />
    );
    graphContainer = container;
  });

  test.each`
    index | height   | x        | y
    ${0}  | ${"640"} | ${"100"} | ${"340"}
    ${1}  | ${"960"} | ${"300"} | ${"20"}
  `("renders rects", async ({ index, height, x, y }) => {
    // waits for rectangles to appear due to animation in graph library
    await waitFor(() => {
      // Hard coding classes is not ideal but best we have to work with
      const bars = graphContainer.querySelectorAll(".recharts-rectangle");
      expect(bars[index].getAttribute("height")).toBe(height);
      expect(bars[index].getAttribute("x")).toBe(x);
      expect(bars[index].getAttribute("y")).toBe(y);
    });
  });

  test.each`
    value   | x       | y
    ${"15"} | ${"72"} | ${"740"}
    ${"30"} | ${"72"} | ${"500"}
    ${"45"} | ${"72"} | ${"260"}
    ${"60"} | ${"72"} | ${"20"}
  `("displays $value in the correct position", ({ value, x, y }) => {
    // By testing the position of the tick we are also testing it existence, it's a two for one deal.
    const textNode = screen.getByText(value).parentNode;
    expect(textNode.getAttribute("y")).toBe(y);
    expect(textNode.getAttribute("x")).toBe(x);
  });
});
`

A fragement or div will do(not sure about SSR)

**Comment by jacinyan** [comment]
> I faced this same issue I solved it by adding div between ResponsiveContainer and Linecharts
> 
> ```
> <ResponsiveContainer width="100%" height={300}>
>         <div>
>             <LineChart
>         width={600}
>         height={300}
>         data={data}
>         margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
>       >
>         <XAxis dataKey="name" />
>         <YAxis />
>         <CartesianGrid strokeDasharray="3 3" />
>         <Tooltip />
>         <Legend />
>         <Line
>           type="monotone"
>           dataKey="pv"
>           stroke="#8884d8"
>           activeDot={{ r: 8 }}
>         />
>         <Line type="monotone" dataKey="uv" stroke="#82ca9d" />
>       </LineChart>
>         </div>
>     </ResponsiveContainer>
> ```

A fragment also works in my case

**Comment by MegaKeegMan** [comment]
Alternatively, you can set width as a prop on your chart component, and pass that value to ResponsiveContainer's width property. Pass "100%" (or whatever percent) to the width prop regularly, and pass it a fixed value, like 1, in your test.

The div solution referenced above does not work for me.

**Comment by cryptic-mystic** [comment]
> Alternatively, you can set width as a prop on your chart component, and pass that value to ResponsiveContainer's width property. Pass "100%" (or whatever percent) to the width prop regularly, and pass it a fixed value, like 1, in your test.
> 
> The div solution referenced above does not work for me.

Love this solution, because it promotes inversion of control. Worked great for me!

**Comment by joshua-phillips** [comment]
I was previously using this work-around inspired by @krzysu 's [comment](https://github.com/recharts/recharts/issues/2268#issuecomment-819295199)

> You're a life-saver, @krzysu! This was making me crazy. The only thing I'll add is that I had to return all the other recharts components as-is with spread syntax on the original module.
> 
> ```
> jest.mock('recharts', () => {
>     const OriginalModule = jest.requireActual('recharts');
> 
>     return {
>         ...OriginalModule,
>         ResponsiveContainer: ({ height, children }) => (
>             <OriginalModule.ResponsiveContainer width={800} height={height}>
>                 {children}
>             </OriginalModule.ResponsiveContainer>
>         ),
>     };
> });
> ```
> 
> Thanks again!

and it worked great, but I also ended up with a bunch of warnings in the console log when running tests...
```
console.warn node_modules/recharts/lib/util/LogUtils.js:23
      The width(800) and height(500) are both fixed numbers,
             maybe you don't need to use a ResponsiveContainer.
```

I'm now using a manual mock in Jest to mock the recharts module that removes the `ResponsiveContainer` when testing and just renders the child component (which is one of the charts e.g. `BarChart`, `LineChart`, etc.) with a fixed width (height is already fixed in my usages), so no more warnings in the console and the chart is rendered in the DOM for testing.

```
import { cloneElement } from 'react';

// re-export everything from recharts
export * from 'recharts';

// export override of ResponsiveContainer component
export const ResponsiveContainer = ({ children, height }) => cloneElement(children, { width: 500, height });
```

**Comment by HagenKaprykowsky** [comment]
Setting the aspect and a fixed width (or height) worked for me to make the warning disappear, i.e.

jest.mock('recharts', () => {
    const OriginalModule = jest.requireActual('recharts');

    return {
        ...OriginalModule,
        // eslint-disable-next-line react/display-name, react/prop-types
        ResponsiveContainer: ({ children }) => (
            <OriginalModule.ResponsiveContainer width={100} aspect={1}>
                {children}
            </OriginalModule.ResponsiveContainer>
        )
    }
})

Just another dirty hack, but it works at least for me...

**Comment by Cleysond10** [comment]
> Alternatively, you can set width as a prop on your chart component, and pass that value to ResponsiveContainer's width property. Pass "100%" (or whatever percent) to the width prop regularly, and pass it a fixed value, like 1, in your test.
> 
> The div solution referenced above does not work for me.

I used this props solution and that was very helpful thanks to @MegaKeegMan, but the warning in the console terminal was still there because of **ResponsiveContainer**.

`console.warn node_modules/recharts/lib/util/LogUtils.js:23
      The width(800) and height(500) are both fixed numbers,
             maybe you don't need to use a ResponsiveContainer.`

I've found another way to solve this problem using a boolean function to render the **ResponsiveContainer** or not depending if the type of width prop is string. For example:

`const isWidthString = () => typeof props.width === 'string';`

Inside the render method be like this:

`render() {
     return (
     <>
      { isWidthString() ? (
        <ResponsiveContainer width={props.width} height={400}>
          <LineChart data={data} >
            {/* { INSERT CHART CODE HERE } */}
          </LineChart >
        </ResponsiveContainer>
      ) : (
        <LineChart width={800} height={400} data={data} >
          {/* { INSERT CHART CODE HERE } */}
        </LineChart >
      )}
    </>
     )
}`

If you want a responsive chart, just pass `width="100%"` on props. In the test file, just pass a fixed value on width property like `width={100}` and the warning console will disappear.

This is just a quick fix, but I think it’ll do.

**Comment by wamujlb** [comment]
This solutions worked perfectly fine for me:

```js
jest.mock('recharts', () => {
  const OriginalRechartsModule = jest.requireActual('recharts');

  return {
    ...OriginalRechartsModule,
    ResponsiveContainer: ({ height, children }: any) => (
      <div className="recharts-responsive-container" style={{ width: 800, height }}>
        {children}
      </div>
    ),
  };
});
```

**Comment by scottgratton** [comment]
While adding the wrapping `<div>` worked to fix my tests, it also prevented the responsive container from actually responding in the browser. I just added an optional `width` prop to my parent component and then passed it in from the tests - defaulting to `100%` otherwise:
```
<ResponsiveContainer width={width || "100%"} height={300}>
```

**Comment by luancardosolc** [comment]
> This solutions worked perfectly fine for me:
> 
> * replace ResponsiveContainer by simple `<div>` element with fixed `width`;
> * it also removes the `warning` message you get when you try to use  `OriginalRechartsModule.ResponsiveContainer`;
> 
> ```js
> jest.mock('recharts', () => {
>   const OriginalRechartsModule = jest.requireActual('recharts');
> 
>   return {
>     ...OriginalRechartsModule,
>     ResponsiveContainer: ({ height, children }: any) => (
>       <div className="recharts-responsive-container" style={{ width: 800, height }}>
>         {children}
>       </div>
>     ),
>   };
> });
> ```

Thank you so much, this is the only approach that worked in my case!

**Comment by ckifer** [comment]
We use ResizeObserver directly now, if you mock that you shouldn't have any problems rendering in tests
