### ISSUE TITLE
Tooltip "cursor" appears outside of chart when allowDataOverflow: true

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#2273]
The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.
---

Note the blue dot below the 16:51 in the screen shot below. The value on the Y-axis is below the chart, but the tooltip still renders its "cursor":

![image](https://user-images.githubusercontent.com/685316/92659105-5ced0780-f2bd-11ea-8cce-9d32d33a7bd5.png)

The Y-Axis is set to use `allowDataOverflow: true` (the issue can't happen without this, because the data point will always be within the chart).

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
