### ISSUE TITLE
Issue with rendering the pie chart for puppeteer pdf with ReactDOMServer.renderToStaticMarkup

### ISSUE THREAD

**Issue by codyphan90** [recharts/recharts#2274]
`ReactDOMServer.renderToStaticMarkup( <ReactComponent>) `seem not render the piechart, I did a research and it seem like I need to set `isSsr` for rechart but I don't know how to enable that
Could your provide details how to make the chart  work with `renderToStaticMarkup`?

**Comment by codyphan90** [comment]
Here is my pie chart component
`<ResponsiveContainer height={300} width="100%">
        <PieChart width={50} height={30}>
          <Pie
            data={data}
            dataKey="value"
            outerRadius={100}
            label={renderLabel}
          >
            {data.map((entry, i) => (
              <Cell key={i} fill={COLORS[i]} />
            ))}
          </Pie>
        </PieChart>
      </ResponsiveContainer>`

this was not render in  `renderToStaticMarkup`

**Comment by TheDynomike** [comment]
Make sure to pull in the beta build 
`npm i recharts@2.0.0-beta.7 --save`

Then import the global component
`import { Global } from 'recharts'`

And turn it on
`Global.isSsr = true`

**Comment by codyphan90** [comment]
The caused problem is: ResponsiveContainer with width="100%" thats in my case getting from parent div which is 0px so 
it will not render the chart at all, resolve the issue with to hard code width="{300}"
