### ISSUE TITLE
Issue with ResponsiveContainer while using react-router

### ISSUE THREAD

**Issue by harshjv** [recharts/recharts#228]
When ResponsiveContainer is used with react-router, it's not showing anything.

    import React from 'react'
    import { AreaChart, ComposedChart, Line, Area, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts'

    import Navbar from './common/Navbar.jsx'

    const data = [
          {name: 'Page A', uv: 4000, pv: 2400, amt: 2400},
          {name: 'Page B', uv: 3000, pv: 1398, amt: 2210},
          {name: 'Page C', uv: 2000, pv: 9800, amt: 2290},
          {name: 'Page D', uv: 2780, pv: 3908, amt: 2000},
          {name: 'Page E', uv: 1890, pv: 4800, amt: 2181},
          {name: 'Page F', uv: 2390, pv: 3800, amt: 2500},
          {name: 'Page G', uv: 3490, pv: 4300, amt: 2100}
    ]

    export default class App extends React.Component {
      render () {
        return (
          <div className='react-wrapper'>
            <Navbar />
            <div className='container'>
              <ResponsiveContainer>
                <AreaChart data={data}>
                  <XAxis dataKey='name' />
                  <YAxis />
                  <CartesianGrid strokeDasharray='3 3' />
                  <Tooltip />
                  <Area type='monotone' dataKey='uv' stroke='#8884d8' fill='#8884d8' />
                </AreaChart>
              </ResponsiveContainer>
            </div>z
          </div>
        )
      }
    }

**Comment by xile611** [comment]
@harshjv Can your problem fixed by setting a aspect (mentioned in [#135](https://github.com/recharts/recharts/issues/135)) or minHeight, minWidth of container?

**Comment by harshjv** [comment]
Yes, `aspect` worked for me! Thanks @xile611

**Comment by xile611** [comment]
OK!
