### ISSUE TITLE
The line of "CartesianGrid" is coveing on the X-axis and Y-axis

### ISSUE THREAD

**Issue by woaiwodib107** [recharts/recharts#2281]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/alidingling/xqjtetw0/](https://jsfiddle.net/alidingling/xqjtetw0/)

### Steps to reproduce
https://jsfiddle.net/alidingling/xqjtetw0/

### What is expected?
https://recharts.org/zh-CN/examples/SimpleLineChart

### What is actually happening?
https://jsfiddle.net/alidingling/xqjtetw0/

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.7 |
| React | ReactDOM v15.6.2 |
| System | Windows |
| Browser | Chrome |

---
On the homepage of Recharts, the line of "CartesianGrid" is not showed on the X-axis and Y-axis.
But int the "jsfiddle", the line of "CartesianGrid" is coveing on the X-axis and Y-axis
![image](https://user-images.githubusercontent.com/14672095/93191698-696ad780-f777-11ea-8550-1c6c5cec8cda.png)
![image](https://user-images.githubusercontent.com/14672095/93191724-712a7c00-f777-11ea-94e2-f49a8cc6c805.png)

**Comment by Valindo** [comment]
Hey @woaiwodib107 , Recharts renders each component it provides into an SVG, so the ordering of the elements are important.
In this case the CartesianGrid is rendering over XAxis and YAxis.

So fix this problem, please render your XAxis and YAxis after the Grid.
Here is an example

```jsx
<CartesianGrid strokeDasharray="3 3"/>
<YAxis/>
<XAxis dataKey="name"/>
```

Hopefully this should solve your problem.

**Comment by Kaiyrgali** [comment]
Really "... rendering over XAxis and YAxis.." doesnt work (
