### ISSUE TITLE
Pie chart activeShape text hiding behind Pie slices

### ISSUE THREAD

**Issue by Gunner17** [recharts/recharts#2284]
## Do you want to request a feature or report a bug?
Bug.

## What is the current behavior?
When the activeShape text is slightly longer than the diameter of the Pie chart, the text start hiding behind the Pie chart slices. Please look at this jsFiddle: https://jsfiddle.net/gunner17/1z8vfxr5/1/

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
Here is the jsFiddle: https://jsfiddle.net/gunner17/1z8vfxr5/1/

## What is the expected behavior?
The activeShape text should appear on top of the Pie slices and not hide behind it. Otherwise it is causing readability issue.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts version: 1.8.5
OS: macOS Mojave
Browser: Chrome 85.0.4183.102, Safari 13.1.2

**Comment by xile611** [comment]
It's recommended to add ellipsis to the text when text is too long.

**Comment by chr15stevens** [comment]
FYI as an alternative to this you can display a text element within the root of the PieChart element. This will get rendered last and always be on top.
