### ISSUE TITLE
Recharts in ResponsiveContainer not printed at 100%

### ISSUE THREAD

**Issue by FranzThomsen1089** [recharts/recharts#2285]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-cuqeg)

### Steps to reproduce
Create a new react app and paste the code from above code sandbox. 
Add dependencies
Do a yarn start and print the page with e.g. CTRL+P
Above code sandbox is only there because the issue generator here forced me to

### What is expected?
I am expecting the recharts to fill 100% of the width

### What is actually happening?
The responsive container does not seem to be rerendering to the width of the printed doc.

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.13.1 |
| System | WIndows 10 |
| Browser | Chrome |

**Comment by Sheldonfrith** [comment]
I believe I am having the same issue, when width is set to "100%" the inner element that holds the chart is set to 'display: none, width: 0, height: 0' etc.

**Comment by Sheldonfrith** [comment]
Nevermind, I fixed my issue with the solutions from issue #854
