### ISSUE TITLE
Want to display Tooltip even if the payload is empty

### ISSUE THREAD

**Issue by seiyab** [recharts/recharts#2287]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to show the reason why no data is there in the Tooltip if users point where data lack.

### What does the proposed API look like?
something like
```jsx
<Tooltip displayNoData content={<CustomTooltip />} />
```
or
```jsx
<Tooltip content={<CustomTooltip />} noDataContent={<NoDataTooltip />} />
```

**Comment by guilhermeoalima** [comment]
@seiyab I was able to get this behaviour using tooltip's props `filterNull`. Check this API [reference](https://recharts.org/en-US/api/Tooltip).

**Comment by seiyab** [comment]
@guilhermeoalima 
Thank you very much.
It's what I wanted.

**Comment by Kpa6i** [comment]
@guilhermeoalima Thanks, man!
