### ISSUE TITLE
[BUG] Tooltip not appearing even though mouse is still on top of Line Dot

### ISSUE THREAD

**Issue by Gunner17** [recharts/recharts#2288]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/gunner17/akj3cqxf/16/](https://jsfiddle.net/gunner17/akj3cqxf/16/)

### Steps to reproduce
Once you visit my jsFiddle link, you will see that I have increased the red dot radius of the purple colored line series (dataKey="pv"). Now if you hover on this specific red dot on category "Page B", you will notice that the Tooltip only appears when you are hovering on the part of the red dot which is inside the plot area, but the tooltip does not appear when the mouse pointer in on the part of the red dot which is slightly outside chart area (tip: try hovering on the bottom part of the red Dot on category "Page B"). 
I assume there may be some internal check which prevents the Tooltip from appearing when the mouse is not inside the plot area; But the issue here is that the users will think they are hovering on the line series dot and and in some part of the dot the tooltip is showing up and in some part it is not. It will confuse the users to think that it is a bug. Is there a workaround to ensure that the Tooltip gets triggered always for dots that are lying on the edge of the chart (like the one shown in the example: Category "Page B").

Screenshot 1: Tooltip not showing up
![image](https://user-images.githubusercontent.com/11354728/94305965-f60b5780-ff26-11ea-8774-01012d991dab.png)

Screenshot 2: Tooltip shows up
![image](https://user-images.githubusercontent.com/11354728/94305991-04f20a00-ff27-11ea-98f6-83cf2ef2ba8e.png)

### What is expected?
Tooltip should always show up even when hovering on line series dots that are partially falling outside the chart plot area.

### What is actually happening?
Tooltip not showing up when hovering on line series dots that are partially falling outside the chart plot area.

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.13.1 |
| System | MacOS Mojave 10.14.6 |
| Browser | Safari 13.1.2, Chrome 84.0.4147.135 |

---
NA

**Comment by Gunner17** [comment]
Please let me know if there is a workaround for this issue, as I will be utilizing this feature for showing annotations in my charts.

**Comment by Gunner17** [comment]
Any plan to fix this bug?

**Comment by xile611** [comment]
It's the right behavior, tooltip will show when your mouse point is inner the coordinate
