### ISSUE TITLE
Tick prop for XAxis and YAxis component typescript

### ISSUE THREAD

**Issue by ls-miles-rostami** [recharts/recharts#2293]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-n7lxj?file=/src/index.js)

### Steps to reproduce
When using the tick props for XAxis and YAxis in a typescript project, there is no way to set the typing for the props being passed to the custom component.

### What is expected?
Being able to set the typing for the props passed

### What is actually happening?
You have to set `any` for the props passed to the custom tick render component

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.13.1 |
| System | MacOS Catalina v.10.15.6  |
| Browser | Chrome 85 |

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
