### ISSUE TITLE
How to apply different colors to different Sankey chart nodes?

### ISSUE THREAD

**Issue by Gunner17** [recharts/recharts#2296]
As per the [documentation](https://recharts.org/en-US/api/SankeyChart) we can apply a stroke color to the entire Sankey chart using the "**link**" attribute of Sankey:

```
<Sankey
  ...
  link={{ stroke: '#77c878' }}
>
  <Tooltip />
</Sankey>
```

But if I want to apply different color to each Sankey node (e.g. Visit -> Page Click one color, Page Click -> Detail-Favorite another color), how can I do that? Can someone please post an example?

**Comment by kunalshewale** [comment]
Have you found any solution for it?

**Comment by acesaft** [comment]
Hey, i have found a way to customise the colors

you basically render your own components for the nodes and links.

have a look at this jsfiddle https://jsfiddle.net/Lygwmx6u/
