### ISSUE TITLE
When using log scale, last scale value (max value) on yAxis does not render.

### ISSUE THREAD

**Issue by saurabhiam** [recharts/recharts#2297]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-oyp57x](https://stackblitz.com/edit/react-oyp57x)

### Steps to reproduce
Use YAxis with following options `<YAxis scale="log" domain={[1, 'auto']} allowDataOverflow/>`

### What is expected?
Max value on the YAxis scale should have been visible and have the value equal or greater than max value in data

### What is actually happening?
At the moment, max value on YAxis scale is never rendered when scale="log" is used

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.9.0 |
| System | MacOS 10.14.6 |
| Browser | Microsoft Edge Version 85.0.564.70  |

**Comment by xile611** [comment]
Maybe you can use customized ticks.

**Comment by saurabhiam** [comment]
Customised ticks doesn't work in this case.
I didn't think you understood the issue. If you check the example, the top most tick is not visible.
