### ISSUE TITLE
LineChart: plotted data non aligned with x-axis with scale="linear"

### ISSUE THREAD

**Issue by gariggio** [recharts/recharts#2299]
https://jsfiddle.net/qso3zcje/

**Comment by iamyogik** [comment]
I can replicate this, but this only seems to happen when you set x-axis scale as "linear".

**Comment by gariggio** [comment]
Exactly!

**Comment by xile611** [comment]
That's the right behavior

**Comment by KevinPoole** [comment]
Can anyone explain how this is the right behavior? I am having a hard time understanding
