### ISSUE TITLE
Legend is not responsive

### ISSUE THREAD

**Issue by Cloudo** [recharts/recharts#23]
I cant make horizontal legend to be responsive for LineChart.
I mean it would be nice to set height for LineChart and then chart would be use that height to recalculate height of Surface and Legend so `height(Surface) + height(Legend) == props.height`

For now Legend is just overlapping.
http://jsfiddle.net/fxtwg1k7/1/

**Comment by xile611** [comment]
Initially I think the calculation of the with and height of the legend is very troublesome and expensive. so, I left part of location task to the user.Just like your example, adjusting the value of margin to {top: 5, right: 30, left: 20, bottom: 35} can fix the problem.

But this's really not too convenient.
How do you look on this problem?

**Comment by xile611** [comment]
Legend has been refactor in version 0.6.3

**Comment by Cloudo** [comment]
Thanks!
It works fine now.
Your approach of calculating height for `Legend` is a bit tricky, but it works ;)

Before your commits I have solved problem another way similar to what `react-dimensions` does with a few additions (recalculating dimensions in wrapper's componentDidUpdate and rerender children only if it changed):
https://github.com/digidem/react-dimensions/pull/12/files

**Comment by Cloudo** [comment]
I mentioned that if I pass specific `wrapperStyle` to `Legend` (whatever?), the chart will not show:
`wrapperStyle={{ fontSize: '12px', bottom : '10px' }}/>`
http://jsfiddle.net/fxtwg1k7/2/

It happens due assumption that such attributes like bottom, top ... will be numbers, not strings.
Not so serious, but for now I think it may be fixed by changing PropType of `wrapperStyle` from object to shape.

**Comment by xile611** [comment]
Yeah, I  just want to get the width and height of `Legend` before the `Legend` will be rendered, so that it can avoid the change in size of a chart.

`Recalculating` like `react-dimensions` may bring a lot of callbacks. Is that right?

**Comment by xile611** [comment]
I think most users should know that the `PropType` of `wrapperStyle` is consistent width `style` in `React`.  so I didn't add any format requirement in `PropType`.
It's repetitive  to add the `PropType` of all the css properties.
Remove 'px' in your example, the chart show normally.

http://jsfiddle.net/fxtwg1k7/3/

I wonder why no warning when the value of `bottom` and `fontSize` is wrong.

**Comment by Cloudo** [comment]
The problem is still exists for PieChart. @xile611 Could you fix this in next version?

**Comment by xile611** [comment]
@Cloudo 
Can you give me an example in  jsfiddle ? Or you can paste you code here.

**Comment by Cloudo** [comment]
Sure:
[http://jsfiddle.net/xtned4bj/3/](url)

**Comment by xile611** [comment]
I know you problem.
```jsx
<PieChart width={300} height={300}>
  <Pie isAnimationActive={false} data={data01} fill="#8884d8" label/>
  <Tooltip/>
  <Legend/>
</PieChart>
```
The default value of props `cx` in Pie is `'50%'`, the default value of props `cy` in Pie is `'50%'`, and the default value of props `outerRadius` in Pie is `'80%'`.
When `cx`, `cy`, `outerRadius` are not specified, default values are used.
If I add a lot of restrictions of `cx`, `cy`, `outerRadius` internally, it will affect the flexibility of `PieChart`.

Maybe this problem can be solved by adjusting some parameters.
