### ISSUE TITLE
Responsive container is not working for RadarChart

### ISSUE THREAD

**Issue by sanehab** [recharts/recharts#2301]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-spider-graph-bug-qgjvu?file=/src/charts/RadarChart.js:317-320)

### Steps to reproduce
- Wrap a Radar graph with a ResponsiveContainer
- Provide some data to the radar chart
- Preview the graph in a small screen
- You will find that the graph does not get smaller its just get centered, graph legends will be cut off
- The graph starts to get smaller on really really tiny screens

### What is expected?
The graph should start to get smaller once text becomes invisible, and maybe text should become little smaller

### What is actually happening?
Graph does not get smaller, starts getting smaller maybe on screens less than 200px (but at that time almost all legends are not visible)

Here is an image showing the situation with code, notice how text is cut off
![](https://i.imgur.com/f6kRnm5.png)

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.3.2 |
| System | OS X 10.15.6 |
| Browser | Chrome 86 |

**Comment by sanehab** [comment]
Guys first i wanna thank you for the amazing library, also i wanna add that i know you are busy with 2.x release, and this might be a low priority bug but please don't close and keep open for visibility.
As a workaround i have been reducing innerRadius for the RadarGraph and making text smaller on smaller screens, however it's not a scalable solution, so if we can fix this it will be awesome.
Thanks

**Comment by wmhartl** [comment]
+1 on this - radar charts are great and we really need responsiveness here also.

**Comment by xile611** [comment]
Responsive tick is not implemented now. It's recommended to implement this feature by customized tick, or PR is welcome.

**Comment by lazycipher** [comment]
@xile611, I didn't get it. What you referred by a customized tick?
It'll be great if you can post some references to this.

Thank you

**Comment by terriiii** [comment]
The issue is still persistent; are there any steps to resolve this issue?

**Comment by renaudmenard** [comment]
Just found out it's not responsive on small screen after finishing the whole integration ...
<img width="397" alt="image" src="https://github.com/recharts/recharts/assets/33551651/7f0fb915-2380-4442-975a-f3ec0d5c62d9">

**Comment by ckifer** [comment]
Looks like that just needs a little more margin and make sure you're using percentages for cx and cy if you have them set
