### ISSUE TITLE
Improve ResponsiveContainer behavior while printing

### ISSUE THREAD

**Issue by goodwin64** [recharts/recharts#2303]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Printing problem:
https://github.com/recharts/recharts/issues/1114#issuecomment-713686147

### What does the proposed API look like?
The same as in rendered web app

**Comment by goodwin64** [comment]
Related:
https://github.com/recharts/recharts/issues/1114

**Comment by xile611** [comment]
@goodwin64  PR is welcome. We have little time to cover all the useage environment.

**Comment by goodwin64** [comment]
A possible solution may be to manually set several container widths based on breakpoints:

Instead of:
```jsx
    <div className="container">
      <ResponsiveContainer id={id}>
        <BarChart
          data={data}
        >
          {/* chart config */}
        </BarChart>
      </ResponsiveContainer>
    </div>
```

write this:
```jsx
    <div className="container">
      <BarChart
        width={/* either static or dynamic based on media query */}
        data={data}
      >
        {/* chart config */}
      </BarChart>
    </div>
```
