### ISSUE TITLE
Dots are clipped at the sides for allowDataOverflow YAxis

### ISSUE THREAD

**Issue by Retribution98** [recharts/recharts#2304]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nostalgic-buck-7ph3s?file=/src/App.js)

### Steps to reproduce
1. Use LineChart or AreaChart with dots
2. Use YAxis with allowDataOverflow

### What is expected?
Points are only clipped vertically or not clipped 

### What is actually happening?
Dots are clipped both vertically and horizontally

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | react 16.9.0 |
| System | Windows 10 |
| Browser | Google Chrome Version 80.0.3987.87 |

---
I use graphs to display real-time sensor data and use a fixation for Y Axis. But I don't want the dots on the graph to be clipped for X Axis

**Comment by xile611** [comment]
This seems to be be right behavior.

**Comment by ckifer** [comment]
merged in #3602
