### ISSUE TITLE
Y-Axis linearGradient stroke color

### ISSUE THREAD

**Issue by navot-eloomina** [recharts/recharts#2305]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.sport5.co.il](http://www.sport5.co.il)

### Steps to reproduce
create y-axis and try to give this y-axis a linear gradient stroke color, 

### What is expected?
a linear gradient stroke color

### What is actually happening?
the stroke is disappear

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.14.0 |
| System | Catalina mac os |
| Browser | chrome |

**Comment by dillonreedy** [comment]
That isn't a link to a JS Fiddle.
