### ISSUE TITLE
Stacked BarChart: stackOffset "sign" does not work anymore

### ISSUE THREAD

**Issue by Lukas742** [recharts/recharts#2306]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pensive-fermi-p0oy2?file=/src/Example.jsx)

### Steps to reproduce
1. Implement a stacked BarChart
2. Add negative values to one of your data entries.
3. Add `stackOffset="sign"` to the chart.
4. See that only the positive bars are displayed and the negative bars are hidden

### What is expected?
Also display bars with negative values.

### What is actually happening?
Bars with negative value are rendered without `path` and dimensions of `0px`.

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.7 |
| React | 17.0.1 |
| System | macOs 10.15.6 |
| Browser | Chrome 85.0.4183.121 |

---
In `2.0.0-beta.3` it was working as intended:
https://codesandbox.io/s/exciting-blackwell-ge817?file=/src/Example.jsx:1364-1384

**Comment by dbertella** [comment]
I was going to post the same issue, and thanks to point out that it works as expected in beta.3 can the regression be related to this commit?
https://github.com/recharts/recharts/commit/e458cb59043f79626ff60d1ecf033c0562876a24

**Comment by Lukas742** [comment]
Gonna close this issue as it has been fixed in [v2.0.0-beta.8](https://github.com/recharts/recharts/releases/tag/v2.0.0-beta.8).
Thanks all.
