### ISSUE TITLE
Adding ResponsiveContainer in barchart with custom shape breaks chart

### ISSUE THREAD

**Issue by Shaivpidadi** [recharts/recharts#2307]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://gist.github.com/Shaivpidadi/88accdfb697801af34f131fda17f0d4a](https://gist.github.com/Shaivpidadi/88accdfb697801af34f131fda17f0d4a)

### Steps to reproduce
Code to reproduce the error is provided. Chart is working fine without adding `ResponsiveContainer`, but with this container it breaks chart and throwing me "Received NaN for the `y` attribute" and "Received NaN for the `height` attribute".

### What is expected?
Should display chart with full width and provided height.

### What is actually happening?
Throwing me these errors: "Received NaN for the `y` attribute", "Received NaN for the `height` attribute" and <rect> attribute y: Expected length, "NaN".

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | react |
| System | Ubuntu |
| Browser | Version 86.0.4240.111  |

**Comment by xile611** [comment]
just remove the <svg /> tag

**Comment by eyaltrustedpartners** [comment]
what tag ? does this fix the issue ?
