### ISSUE TITLE
Problem view tooltip in Charts with overflow

### ISSUE THREAD

**Issue by s-kobets** [recharts/recharts#2308]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/s_kobets/tchvwuba/5/](https://jsfiddle.net/s_kobets/tchvwuba/5/)

### Steps to reproduce
I use block with `overflow: hidden` and my tooltip from chart hidden.

### What is expected?
Normal view Tooltip.
Need remove css property `position: 'relative' ` with `generateCategoricalChart` for correct work.

### What is actually happening?
Tooltip don't correct view.

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.7 |
| React | ^16.10 |
| System | MacOS |
| Browser | Chrome 86 |

**Comment by xile611** [comment]
You can use css to overlap the default behavior

**Comment by s-kobets** [comment]
How?
