### ISSUE TITLE
New Feature Ability to add spacing between stacked bars in StackedBarChart

### ISSUE THREAD

**Issue by tipantaz** [recharts/recharts#2309]
## Do you want to request a feature or report a bug?
New feature

## What is the current behavior?
There is no possibility for having space between stacks in a stack bar like bellow (that I know of or can find)
![image](https://user-images.githubusercontent.com/52921554/97593315-da9ddb80-1a01-11eb-8e01-636e589cc15b.png)

 
## What is the expected behavior?
We need to be able to add spacing between parts of a stacked bar

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
version 1.8.5

Similar ask was made in the past
https://github.com/recharts/recharts/issues/2244
but I don't think that the workaround is enough.

**Comment by xile611** [comment]
You can add white stroke to the rectangles.

**Comment by Haraldson** [comment]
@xile611 I’m not actually rendering any rectangles, only `<Bar />`s. A bit more in-depth answer wouldn’t hurt.

**Comment by dillonreedy** [comment]
I believe he's saying you might be able to add a bar in-between your colored bars that is colored transparent.
