### ISSUE TITLE
ResponsiveContainer: Making a chart expand to accomodate its contents

### ISSUE THREAD

**Issue by SachaG** [recharts/recharts#231]
Here are two JSFiddles that are the same except that the second one has twice as many data points:

- http://jsfiddle.net/1b5qv2Ld/1/
- http://jsfiddle.net/1b5qv2Ld/2/

As you can see, when you double the amount of data points the chart stays the same height, but the bars become twice as small. 

What I would like to do is the opposite: keep the bars **the same size**, but make the chart **twice as big**. 

I still want the chart's width to adapt to its parent though. So how can I do that using `ResponsiveContainer`?

**Comment by xile611** [comment]
@SachaG You can set the `barSize` of `Bar`.

**Comment by SachaG** [comment]
Sorry, setting the `barSize` by itself doesn't make the chart taller, it makes the bars closer together:

- http://jsfiddle.net/twzLm0he/
- http://jsfiddle.net/zvr2qa90/1/

I tried setting `barGap` too but that doesn't seem to do anything.

**Comment by xile611** [comment]
Yeah. ResponsiveContainer can't do this now, because ResponsiveContainer don't know anything about the data. Do you have any idea about how to adapt to the length of data ? A workaround is to update the value of height by the length of data in your code.

**Comment by SachaG** [comment]
Here's a temporary solution I found:

```js
    const rowCount = this.props.data.length -1
    const aspect = 15 / rowCount
    return (
      <ResponsiveContainer aspect={aspect} width="100%" >
          ...
```

I want the container to stay responsive, so that's why I'm using `aspect` instead of setting the `height` or `width`. It'd be great if aspect was documented by the way, I couldn't find much info about it apart from reading the source.

**Comment by jameskennethrobinson** [comment]
@SachaG Thanks!

**Comment by revathi-pumex** [comment]
@SachaG Thanks !!
