### ISSUE TITLE
Vertical X-Axis index ?

### ISSUE THREAD

**Issue by WeakCookie** [recharts/recharts#2314]
Hi is there any way to make the index of the x-axis vertical like this ? I can't find any method

<img width="947" alt="Screen Shot 2020-11-02 at 23 00 18" src="https://user-images.githubusercontent.com/43299094/97889649-2f718700-1d5f-11eb-94cf-56a722def075.png">

Maybe I am missing something, but if I am not it would be great to support.Thanks!

**Comment by Tooluloope** [comment]
`<XAxis dataKey="myxaxis" angle={-180} textAnchor="end" />`

I think this is what you're asking for?
