### ISSUE TITLE
Radar chart polarAngles are not removed when providing empty array

### ISSUE THREAD

**Issue by henkvhest** [recharts/recharts#2323]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/clever-tdd-7rhgs?file=/src/App.js)

### Steps to reproduce
Add polarAngles as prop to PolarGrid with [] as value

### What is expected?
The lines that go from the center to each corner of the polygon should not be displayed when providing an empty array as value for the polarAngles prop of the <PolarGrid />

### What is actually happening?
The lines are still visible

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 17.0 |
| System | osx |
| Browser | Chrome Version 86.0.4240.111 (Official Build) (x86_64) |

**Comment by xile611** [comment]
Please try the latest version, this feature works in v2.x

**Comment by dillonreedy** [comment]
I've attempted removing the radial lines through the polarAngles prop in this codesandbox [here](https://codesandbox.io/s/quiet-pine-smcux) on v2.0.8 and the radial lines still exist. @xile611 Is there some different way to be using polarAngles?

**Comment by rafaelkallis** [comment]
for anyone that is looking for this, the referenced pull request #2352 has an example mentioned to remove the lines:

```jsx
<RadarChart>
...
<PolarGrid radialLines={false} /> // radialLines can be set to true or false, but defaults to true
...
</RadarChart>
```
