### ISSUE TITLE
Layout vertical is not working in Area charts

### ISSUE THREAD

**Issue by Minoli** [recharts/recharts#2325]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/dur9k37q/8/](https://jsfiddle.net/dur9k37q/8/)

### Steps to reproduce
Add area chart and set layout attribute to vertical

### What is expected?
The chart to be drawn vertically

### What is actually happening?
The chart is not drawn vertically and the data points disappear

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.12.0 |
| System | Mac |
| Browser | Chrome |

**Comment by Minoli** [comment]
Worked after changing the axis values.

**Comment by jonmiles-mms** [comment]
@Minoli Please can you share what you changed in axis values to fix the issues?
