### ISSUE TITLE
Clicking on PieChart doesn't return the correct Cell data

### ISSUE THREAD

**Issue by norayr93** [recharts/recharts#2326]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/qetf2yhw/2/](https://jsfiddle.net/qetf2yhw/2/)

### Steps to reproduce
Click on a different Cell. PieChart's onClick handlers parameter returns wrong Cell's data

### What is expected?
Clicking on different Cells must return the appropriate Cell data

### What is actually happening?
PieChart's onClick handlers parameter returns wrong Cell's data

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.10.2 |
| System | Ubuntu 18.04 |
| Browser | Chrome Version 86.0.4240.75 (Official Build) (64-bit) |

**Comment by dillonreedy** [comment]
Bind the onClick event to the Pie component, not the PieChart component.

**Comment by norayr93** [comment]
@dillonreedy Thanks a lot, that solved a problem. Closing this.
