### ISSUE TITLE
Event object for onTouchMove is null

### ISSUE THREAD

**Issue by AlexCat** [recharts/recharts#2329]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/heuristic-feistel-nrkg1?file=/src/App.js)

### Steps to reproduce
1. Open on mobile device
2. Try to fire onTouchMove event (swipe)
3. Event object for onTouchMove will be null

### What is expected?
1. Event object contains relevant data

### What is actually happening?
1.Event object for onTouchMove is null

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 17 |
| System | codesandbox.io |
| Browser | Google Chrome Version 87.0.4280.66 |

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by nikolasrieble** [comment]
Released fix with https://github.com/recharts/recharts/releases/tag/v2.10
