### ISSUE TITLE
Option for disabling animation

### ISSUE THREAD

**Issue by digorydoo** [recharts/recharts#233]
Is there an easy way to disable the animation that will slowly draw the chart when it is first rendered? If there isn't, please add an option. Or better, add an option to specify the maximum delay in milliseconds (0 would completely disable the animation).

**Comment by xile611** [comment]
@digorydoo 

 You can set the props `isAnimationActive` of  [Area](http://recharts.org/api#Area), [Bar](http://recharts.org/api#Bar), [Line](http://recharts.org/api#Line), [Scatter](http://recharts.org/api#Scatter), [Pie](http://recharts.org/api#Pie), [Radar](http://recharts.org/api#Radar), [RadialBar](http://recharts.org/api#RadialBar) to be `false`.

**Comment by digorydoo** [comment]
Works like a charm. It would be more intuitive if the property existed on AreaChart, BarChar, LineChart, etc as well, though.

**Comment by xile611** [comment]
@digorydoo In some case, there are two lines in a LineChart, maybe we want one of the lines can animate, and disable the animation of another line. So we think the animation is related the the graphical elememt.

**Comment by digorydoo** [comment]
Makes sense. But you could also allow it on the parent for the default behaviour, and override that default on the child element.

**Comment by loris** [comment]
+1 for adding the props at the chart (parent) level

**Comment by msgill1989** [comment]
Hi All, I am trying to make the area chart real time using socket.io , The problem is every time it get new data, it gets re drawn. Tried setting  "isAnimationActive" property to "false", but did not help. Any idea how can I stop this redrawn/animation?

**Comment by ethan-deng** [comment]
I think there is currently a bug with the Customized Label. If you go to http://recharts.org/#/en-US/examples/PieChartWithCustomizedLabel directly, the customized label will be drawn. But if you go to any other link first such as http://recharts.org/#/en-US/examples/SimpleScatterChart then click on "PieChartWithCustomizedLabel", then the customized label won't be drawn.

**Comment by cnadolny2s** [comment]
Unfortunately, `isAnimationActive` doesn't work anymore for at least `Line`
