### ISSUE TITLE
Dot false ignored on radar chart with tooltip

### ISSUE THREAD

**Issue by Tam** [recharts/recharts#2332]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dot-false-radar-tooltip-l10xe)

### Steps to reproduce
Create a radar chart with a tooltip, set dot to false on the radar.

### What is expected?
The dot shouldn't appear

### What is actually happening?
The dot is still showing

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 17.0.0 |
| System | MacOS |
| Browser | Firefox 84.0b5 |

**Comment by dillonreedy** [comment]
On the Radar component, there is a boolean prop "dot" for setting static dots on all the polygon points, and then there is a boolean prop "activeDot" that makes a polygon point dot appear depending upon whether a users' mouse is hovering or not.

So set "activeDot" to false if you don't want the active dot to appear.

**Comment by Tam** [comment]
@dillonreedy That worked, thanks!
