### ISSUE TITLE
Start including JSDocs for interface properties

### ISSUE THREAD

**Issue by dillonreedy** [recharts/recharts#2334]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I've noticed more than a few issues on github, where a developer is asking "Why does this prop not work for this component?".

I think including JSDocs on at least the interface properties, so that developers can understand what the props are doing for a component, will help them immensely.

The tsconfig.json already specifies to remove all comments when building to production, so there should not be an increase to build size.

I'd be happy to be apart of pull requests to implement this if you need the help.

### What does the proposed API look like?
I am not proposing an API.

**Comment by xile611** [comment]
@dillonreedy PR is welcome !
