### ISSUE TITLE
Line activeDot onClick does not work

### ISSUE THREAD

**Issue by TAMAJJJ** [recharts/recharts#2336]
## Do you want to request a feature or report a bug?
report a bug
## What is the current behavior?
no reaction after clicking dots at all

## What is the expected behavior?
I want to click the dot and trigger some action. However, activeDot does not work for me. i have looked for many similar question, they all say using activeDot but I don't know why it does not work.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.8.5

`
<ResponsiveContainer>
      <LineChart
        width={750}
        height={100}
        data={props.data}
        margin={{
          top: 20,
          right: 30,
          left: 20,
          bottom: 45,
        }}
      >
        <Line
          activeDot={{
            onClick: (e) => console.log("onClick Line ActiveDot: ", e)
          }}
          type="monotone"
          dataKey="brand_conversion_rate"
          stroke="#F3722C"
          dot={<CustomizedDot />}
        />
       <XAxis dataKey="start_date" interval={0} angle={-30} />
        <Legend />
      </LineChart>
    </ResponsiveContainer>`

**Comment by chandjenAC** [comment]
Hi, could you make it work ?..if so please share ...thank you
