### ISSUE TITLE
The prop id is not passed to Line component

### ISSUE THREAD

**Issue by yrokhlin** [recharts/recharts#2339]
Setting the `id` prop does not pass it to the line component path, making it impossible to access it with certain `<svg>` things like `<use>`

**Comment by dillonreedy** [comment]
Could you make a Code Sandbox demonstrating the issue?

**Comment by ckifer** [comment]
Shown here: https://jsfiddle.net/0tofh6r2/19/ although this is 1.8.5 to ensure the fiddle is works.

JSX ids aren't getting passed to the SVG in the Recharts components. Should at least be getting set on `Line` and `Bar` according to the docs.

**Comment by dillonreedy** [comment]
@yrokhlin Using codesandbox and recharts v2.0.2 I was able to assign the "id" prop to a custom value, and then use a SVG use afterwards.

Here's the codesandbox:
[![Edit Recharts: Line (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-line-forked-51uh8?fontsize=14&hidenavigation=1&theme=dark)

**Comment by ckifer** [comment]
Looks like either fixed in latest versions or another JS fiddle issue, but looks to be all good in 2.0.2. Thanks @dillonreedy.
