### ISSUE TITLE
Vertical bar chart not rendering unless axis are provided

### ISSUE THREAD

**Issue by wojtekmaj** [recharts/recharts#2340]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-vertical-bar-chart-not-working-qqbb7)

### Steps to reproduce
1. Create working bar chart without axes
2. Change layout to vertical

### What is expected?
Vertical bar chart to be rendered

### What is actually happening?
Empty chart is rendered

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.8 |
| React | react 17.0.0 |
| System | macOS X |
| Browser | Chrome |

---
I'm aware that adding 
```js
          <XAxis type="number" />
          <YAxis type="category" dataKey="a" />
``` 
as discussed in #90 would render the chart. HOWEVER, in this particular case I simply don't want axes to be rendered. As such, this workaround is not an option for me.

**Comment by dillonreedy** [comment]
Would using the hide prop with the X and Y axes achieve what you want to do?

```   TypeScript     
    <XAxis type="number" hide={true} />
    <YAxis type="category" dataKey="a" hide={true} />
```

**Comment by wojtekmaj** [comment]
Yes! Thank you. This is still quite confusing - I think if recharts is smart enough to figure out the axes in horizontal mode, it should be able to do so in vertical mode.
