### ISSUE TITLE
Problem with payload=[] for Tooltip when allowDuplicatedCategory={false} in XAxis

### ISSUE THREAD

**Issue by VladislavKsen** [recharts/recharts#2344]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
Adding `allowDuplicatedCategory={false}` to` XAxis` component in `BarChart` makes the `Tooltip` stop working. The `Tooltip` just don't show when hovering over a bar and `payload = []`;
http://prntscr.com/w5fron
 
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net.
In demo https://jsfiddle.net/cxuLgdp4/ just hovering over a bar and open console.
The `Tooltip` don't show and `payload = []`. 

If just change this line:
`<XAxis dataKey="name" allowDuplicatedCategory={false} />`
 
for this one
 
`<XAxis dataKey="name" allowDuplicatedCategory={true} />`

The `Tooltip` show and `payload = [{
  color: "#ff7300",
  dataKey: "count",
  fill: "#ff7300",
  formatter: undefined,
  name: "count",
  payload: {
    count: 32,
    sum: [12, 16]
  },
  type: undefined,
  unit: undefined,
  value: 32
}]. `
 
## What is the expected behavior?
The `Tooltip` should be displayed when hovering over a bar and payload have array with data.
http://prntscr.com/w5fvw4
 
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
My current version:  `"recharts": "1.8.5"`
On  version: `"recharts": "1.8.3"` don't work too.

Browser: Google Chrome (87.0.4280.88)
OS: Windows 10

**Comment by xile611** [comment]
Please open an issue follow the issue guide.
