### ISSUE TITLE
Big file size

### ISSUE THREAD

**Issue by alexandermirzoyan** [recharts/recharts#2345]
After installing the package with **npm install recharts** file size after the build has increased by **91.34KB**. What do you think about it, is it ok?

I'm using
"react": "^16.9.0",
"react-scripts": "^3.3.0",
"recharts": "^1.8.5",
The project was created with **create-react-app**

**Comment by avindra** [comment]
@alexandermirzoyan maybe you can try the v2 beta, it is a bit smaller in terms of raw size before compression.

https://bundlephobia.com/result?p=recharts@2.0.0-beta.8
