### ISSUE TITLE
Log scaling is not working

### ISSUE THREAD

**Issue by SlachmuyldersStefaan** [recharts/recharts#2356]
We want to plot transfer functions on the screen. For this we using ScatterCharts, but we are not able to use log-scaling on the X-axis and Y-axis.
We found examples in the document to use the d3-scaling library, but using this, give an empty plot. This is the same behavior then <XAxis scale="log"/> and this is also not working.

We are using Recharts 1.8.5 and d3-scale 3.2.2.

My code:
import React from 'react';
import {
  ScatterChart,
  CartesianGrid,
  XAxis,
  YAxis,
  ZAxis,
  Scatter,
  Legend
} from 'recharts';
import { scaleLog } from 'd3-scale';

interface IPlotAmplPhase {
  freqs: number[];
  ampls: number[][];
  phases: number[][];
  plotName: string[];
  width: number;
  height: number;
}

const PlotAmplPhase: React.FC<IPlotAmplPhase> = ({
  freqs,
  ampls,
  phases,
  plotName,
  width,
  height
}) => {
  const scale = scaleLog().base(Math.E);

  const tf = ampls.map((a, i) =>
    freqs.map((fr, j) => ({ fr: fr, am: ampls[i][j], ph: phases[i][j], z: 1 }))
  );
  const zero = [{ fr: 0, am: 0, ph: 0, z: 4 }];
  const color = [
    '#0088FE',
    '#00C49F',
    '#FF8042',
    '#8884d8',
    'red',
    'green',
    'pink',
    'yellow'
  ];
  return (
    <>
      <ScatterChart
        width={width}
        height={height / 2}
        margin={{ top: 20, right: 20, bottom: 20, left: 20 }}
      >
        <CartesianGrid strokeDasharray="3 3" />
        <XAxis scale={scale} type="number" dataKey={'fr'} />
        <YAxis type="number" dataKey={'am'} />
        <ZAxis dataKey={'z'} range={[1, 20]} />
        {tf.map((t, i) => (
          <Scatter data={t} fill={color[i]} line />
        ))}
        <Scatter data={zero} fill={'black'} />
      </ScatterChart>
      <ScatterChart
        width={width}
        height={height / 2}
        margin={{ top: 20, right: 20, bottom: 20, left: 20 }}
      >
        <CartesianGrid strokeDasharray="3 3" />
        <XAxis type="number" dataKey={'fr'} />
        <YAxis type="number" dataKey={'ph'} />
        <ZAxis dataKey={'z'} range={[1, 20]} />
        <Legend />
        {tf.map((t, i) => (
          <Scatter
            name={plotName[i]}
            data={t}
            fill={color[i % color.length]}
            line
          />
        ))}
        <Scatter data={zero} fill={'black'} legendType="none" />
      </ScatterChart>
    </>
  );
};

export default PlotAmplPhase;

**Comment by xile611** [comment]
Please open an issue follow the issue guide.

**Comment by chickenwing** [comment]
same problem here
