### ISSUE TITLE
Issues are facing after prod build

### ISSUE THREAD

**Issue by sumantaparida** [recharts/recharts#2357]
# This version are used
React :`"react": "16.7.0"`
Rechart : `"recharts": "^1.8.5"`

# After the build, I have to face these issues
`TypeError: (intermediate value)(intermediate value)(intermediate value).map is not a function`
`TypeError: i.filter is not a function`

**Comment by avindra** [comment]
Not enough info, you should use the issue template or else your issue will be closed.

**Comment by sumantaparida** [comment]
after `npm run build`

facing this `TypeError: i.filter is not a function`

`if ("number" === n) {
                var o = i.filter(function(e) {
                    return C(e) || parseFloat(e, 10)
                });
                return o.length ? [ft()(o), st()(o)] : [1 / 0, -1 / 0]
            }`

**Comment by xile611** [comment]
Please open an issue follow the issue guide.

**Comment by avindra** [comment]
@wanghanzhen @sumantaparida  are you able to reproduce this issue with version `2.x` ?

**Comment by wanghanzhen** [comment]
@avindra my recharts version is `^1.7.1`. Can I  upgrade to 2.x withou any change?  I am will to try it.

**Comment by wanghanzhen** [comment]
@avindra Confusingly, when I was in dev, the bug never came up. When I build, the bug came up occasionally, and then I had to randomly change the code and rebuild it to make the bug go away.
