### ISSUE TITLE
Inconsistencies in between Scatter and other charts wrt data passing and events.

### ISSUE THREAD

**Issue by kujon** [recharts/recharts#236]
Most of the charts can have the data and event handlers passed at the top-most level (`{Type}Chart`). Then, it's basically a pass-through. ScatterChart is different, as the data can't be passed as props to `ScatterChart`. Also, events passed at that level get bound to the recharts-wrapper div, instead of being a passthrough.

It'd be grand if this could be consolidated, however it could be a breaking change.

Turning `ScatterChart` into this pass-through model probably wouldn't break much (unless some people are relying on `currentTarget` heavily). Then one could either allow other charts to take data at `{Type}Chart` or `{Type}` level (how do you take care of drawing axes/tooltips etc when 2 instances of `{Type}` have got different data sets) or one could deprecate passing data at `{Type}` level (breaking change for the ScatterChart).

**Comment by xile611** [comment]
This has been fixed in recharts@1.x
