### ISSUE TITLE
Failed to compile : "export 'Props' (reexported as 'AreaProps') was not found in './cartesian/Area'

### ISSUE THREAD

**Issue by bisnard29** [recharts/recharts#2360]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
1) update package.json from "recharts": "^2.0.0-beta.8" to "recharts": "^2.0.0".
2) npm build

### What is expected?
Build successfull 

### What is actually happening?
Creating an optimized production build...
Failed to compile.

./node_modules/recharts/es6/index.js
"export 'Props' (reexported as 'AreaProps') was not found in './cartesian/Area'

| Environment | Info |
|---|---|
| Recharts | v2.0.0 |
| React | 16.14.0 |
| System | Ubuntu 20.04 |
| Browser | Chrome |

---
I had the issue both on Linux and Windows. Re-updating to  "recharts": "^2.0.0-beta.8" worked on my windows instance (not on linux one)

**Comment by Lappintade** [comment]
Also has this issue on OSX.

**Comment by goelkinshuk** [comment]
I also got this and i just installed recharts in my project . what's the fix ?

**Comment by studiojms** [comment]
I am having the same issue with recharts 2.0.0 and react 17.0.1

**Comment by mehrdadrafiee** [comment]
having the same issue here. ```react 17.0.1``` and ```recharts 2.0.0-beta.5```. I also tested on ```recharts 2.0.0``` and got the same error.

**Comment by tactycadmin** [comment]
Same issue here  with `recharts 2.0.0-beta.6 `and `recharts 2.0.0-beta.8` as well.

**Comment by avindra** [comment]
What version of Typescript are you guys using? I pulled `master` and the project still builds. At the moment recharts is using:

```sh
❯ tsc --version
Version 3.9.7
```

**Comment by studiojms** [comment]
Not using typescript here, the project is only js

**Comment by Skitelman** [comment]
This appears to be the problem commit https://github.com/recharts/recharts/commit/62636887336f1267017e06a3d23b89ec69066a0a#diff-1496ed5301e625b1e310643256ed6b2af380dd919af777f25d65beecac8f7b22

**Comment by gruvin** [comment]
Same issue -- not using TypeScript. MacOS 10.15, React 16.13.1. Thanks ;-)

**Comment by barbalex** [comment]
I just updated to v2.0.0 and am getting a lot more of these warnings in dev:

```
warn "export 'Props' (reexported as 'AreaProps') was not found in './cartesian/Area'
warn "export 'Props' (reexported as 'BarProps') was not found in './cartesian/Bar'
warn "export 'Props' (reexported as 'BrushProps') was not found in './cartesian/Brush'
warn "export 'Props' (reexported as 'CartesianAxisProps') was not found in './cartesian/CartesianAxis'
warn "export 'Props' (reexported as 'CartesianGridProps') was not found in './cartesian/CartesianGrid'
warn "export 'Props' (reexported as 'CellProps') was not found in './component/Cell'
warn "export 'Props' (reexported as 'CrossProps') was not found in './shape/Cross'
warn "export 'Props' (reexported as 'CurveProps') was not found in './shape/Curve'
warn "export 'Props' (reexported as 'CustomizedProps') was not found in './component/Customized'
warn "export 'Props' (reexported as 'DotProps') was not found in './shape/Dot'
warn "export 'Props' (reexported as 'ErrorBarProps') was not found in './cartesian/ErrorBar'
warn "export 'Props' (reexported as 'FunnelProps') was not found in './numberAxis/Funnel'
warn "export 'Props' (reexported as 'LabelListProps') was not found in './component/LabelList'
warn "export 'Props' (reexported as 'LabelProps') was not found in './component/Label'
warn "export 'Props' (reexported as 'LayerProps') was not found in './container/Layer'
warn "export 'Props' (reexported as 'LegendProps') was not found in './component/Legend'
warn "export 'Props' (reexported as 'LineProps') was not found in './cartesian/Line'
warn "export 'Props' (reexported as 'PieProps') was not found in './polar/Pie'
warn "export 'Props' (reexported as 'PolarAngleAxisProps') was not found in './polar/PolarAngleAxis'
warn "export 'Props' (reexported as 'PolarGridProps') was not found in './polar/PolarGrid'
warn "export 'Props' (reexported as 'PolarRadiusAxisProps') was not found in './polar/PolarRadiusAxis'
warn "export 'Props' (reexported as 'PolygonProps') was not found in './shape/Polygon'
warn "export 'Props' (reexported as 'RadarProps') was not found in './polar/Radar'
warn "export 'Props' (reexported as 'RadialBarProps') was not found in './polar/RadialBar'
warn "export 'Props' (reexported as 'RectangleProps') was not found in './shape/Rectangle'
warn "export 'Props' (reexported as 'ReferenceAreaProps') was not found in './cartesian/ReferenceArea'
warn "export 'Props' (reexported as 'ReferenceDotProps') was not found in './cartesian/ReferenceDot'
warn "export 'Props' (reexported as 'ReferenceLineProps') was not found in './cartesian/ReferenceLine'
warn "export 'Props' (reexported as 'ResponsiveContainerProps') was not found in './component/ResponsiveContainer'
warn "export 'Props' (reexported as 'ScatterProps') was not found in './cartesian/Scatter'
warn "export 'Props' (reexported as 'SectorProps') was not found in './shape/Sector'
warn "export 'Props' (reexported as 'SurfaceProps') was not found in './container/Surface'
warn "export 'Props' (reexported as 'SymbolsProps') was not found in './shape/Symbols'
warn "export 'Props' (reexported as 'TextProps') was not found in './component/Text'
warn "export 'Props' (reexported as 'TrapezoidProps') was not found in './shape/Trapezoid'
warn "export 'Props' (reexported as 'XAxisProps') was not found in './cartesian/XAxis'
warn "export 'Props' (reexported as 'YAxisProps') was not found in './cartesian/YAxis'
warn "export 'Props' (reexported as 'ZAxisProps') was not found in './cartesian/ZAxis'
warn "export 'TooltipProps' was not found in './component/Tooltip'
```

**Comment by avindra** [comment]
I'm guessing this is from some conflict around the default exports. I would try changing all of the interal default exports to named exports. This should be do-able without impacting the user-facing API.

https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/
https://basarat.gitbook.io/typescript/main-1/defaultisbad
https://blog.neufund.org/why-we-have-banned-default-exports-and-you-should-do-the-same-d51fdc2cf2ad

**Comment by mehrdadrafiee** [comment]
I don't use TS either, it's just JS. Interesting that it happened after I removed ```yarn.lock``` & ```node_modules``` and installed the dependencies again using ```yarn``` without any changes to any dependencies.

**Comment by haresh6x** [comment]
I had the same problem. Tried beta versions but no help 

Solution: revert back to version 1.8.5. Tried and tested until this issue is solved in latest version.

**Comment by Skitelman** [comment]
Update: updating the node version from 12 to 14 fixes this issue.

**Comment by studiojms** [comment]
It seems like it is not related to node version... I am using node 14.15.1 and I am still having the issue

**Comment by m2mathew** [comment]
Same issue for me using:
- macOS 10.15.7
- node 12.18.3
- recharts 2.0.0
- react 16.13.1

**Comment by lachlanjc** [comment]
Yep, same issue. recharts 2.0.0, react 17, node 12.4, macOS 11.1, next.js 10.0.4.

**Comment by bilwit** [comment]
had to go all the way back to `1.8.5` to get past it, not ideal since now all my custom tooltips are broke/not supported but it'll do for now

**Comment by jvaclavik** [comment]
In my case, it's not working in `2.0.0.` but fine in `2.0.0-beta.8`
But be aware that you have to use it in `package.json` without `^`:

```
...
"dependencies": {
  "recharts": "2.0.0-beta.8",
  ...
}
...
```

instead of:

```
...
"dependencies": {
  "recharts": "^2.0.0-beta.8",
  ...
}
...
```
The second one will also use `2.0.0.`.

**Comment by shabkhaiz1** [comment]
same issue with **recharts** 2.0.0-beta.1 on **Ubuntu 20.04.1** Solved with a downgrade to  **recharts** 1.8.5

**Comment by PascalPixel** [comment]
This is because the es6 compile folder's index.js imports types that are not left in the actual files after compilation. 

A temporary hack is to use the `src` folder directly for TypeScript, or the `umd` version for JS.

So instead of:
```js
import { Area } from "recharts";
```

JS users should use:
```js
import * as Recharts from "recharts/umd/Recharts";
const Area = Recharts.Area;
```

And for TS users:
```js
import { Area } from "recharts/src";
```
(Make sure you enable transpiling node_modules/recharts in whatever setup you have.)

I'm sure 2.0.1 will easily fix this oversight.

**Comment by sambabib** [comment]
> I had the same problem. Tried beta versions but no help
> 
> Solution: revert back to version 1.8.5. Tried and tested until this issue is solved in latest version.

hey, what is the command to revert to 1.8.5 trying npm install recharts v1.8.5, no luck

**Comment by avindra** [comment]
Thanks for sharing @PascalPixel. Since we might expect Babel to erase the type exports, I reproduced the issue and opened an issue upstream with Babel.

https://github.com/avindra/babel-ts-export-type-bug
https://github.com/babel/babel/issues/12578

**Comment by avindra** [comment]
Updated #2367 with the suggested workaround from Babel (mark exports with `export type`, which is the only way Babel "knows" about the type exports right now.)

**Comment by ronniery** [comment]
This worked for me:

```
export const Surface = require('recharts/es6/container/Surface.js')?.default;
export const Layer = require('recharts/es6/container/Layer.js')?.default;
export const Legend = require('recharts/es6/component/Legend.js')?.default;
export const Tooltip = require('recharts/es6/component/Tooltip.js')?.default;
export const ResponsiveContainer = require('recharts/es6/component/ResponsiveContainer.js')?.default;
export const Cell = require('recharts/es6/component/Cell.js')?.default;
export const Text = require('recharts/es6/component/Text.js')?.default;
export const Label = require('recharts/es6/component/Label.js')?.default;
export const LabelList = require('recharts/es6/component/LabelList.js')?.default;
export const Customized = require('recharts/es6/component/Customized.js')?.default;
export const Sector = require('recharts/es6/shape/Sector.js')?.default;
export const Curve = require('recharts/es6/shape/Curve.js')?.default;
export const Rectangle = require('recharts/es6/shape/Rectangle.js')?.default;
export const Polygon = require('recharts/es6/shape/Polygon.js')?.default;
export const Dot = require('recharts/es6/shape/Dot.js')?.default;
export const Cross = require('recharts/es6/shape/Cross.js')?.default;
export const Symbols = require('recharts/es6/shape/Symbols.js')?.default;
export const PolarGrid = require('recharts/es6/polar/PolarGrid.js')?.default;
export const PolarRadiusAxis = require('recharts/es6/polar/PolarRadiusAxis.js')?.default;
export const PolarAngleAxis = require('recharts/es6/polar/PolarAngleAxis.js')?.default;
export const Pie = require('recharts/es6/polar/Pie.js')?.default;
export const Radar = require('recharts/es6/polar/Radar.js')?.default;
export const RadialBar = require('recharts/es6/polar/RadialBar.js')?.default;
export const Brush = require('recharts/es6/cartesian/Brush.js')?.default;
export const ReferenceLine = require('recharts/es6/cartesian/ReferenceLine.js')?.default;
export const ReferenceDot = require('recharts/es6/cartesian/ReferenceDot.js')?.default;
export const ReferenceArea = require('recharts/es6/cartesian/ReferenceArea.js')?.default;
export const CartesianAxis = require('recharts/es6/cartesian/CartesianAxis.js')?.default;
export const CartesianGrid = require('recharts/es6/cartesian/CartesianGrid.js')?.default;
export const Line = require('recharts/es6/cartesian/Line.js')?.default;
export const Area = require('recharts/es6/cartesian/Area.js')?.default;
export const Bar = require('recharts/es6/cartesian/Bar.js')?.default;
export const Scatter = require('recharts/es6/cartesian/Scatter.js')?.default;
export const XAxis = require('recharts/es6/cartesian/XAxis.js')?.default;
export const YAxis = require('recharts/es6/cartesian/YAxis.js')?.default;
export const ZAxis = require('recharts/es6/cartesian/ZAxis.js')?.default;
export const ErrorBar = require('recharts/es6/cartesian/ErrorBar.js')?.default;
export const LineChart= require('recharts/es6/chart/LineChart.js')?.default;
export const BarChart= require('recharts/es6/chart/BarChart.js')?.default;
export const PieChart= require('recharts/es6/chart/PieChart.js')?.default;
export const Treemap= require('recharts/es6/chart/Treemap.js')?.default;
export const Sankey= require('recharts/es6/chart/Sankey.js')?.default;
export const RadarChart= require('recharts/es6/chart/RadarChart.js')?.default;
export const ScatterChart= require('recharts/es6/chart/ScatterChart.js')?.default;
export const AreaChart= require('recharts/es6/chart/AreaChart.js')?.default;
export const RadialBarChart= require('recharts/es6/chart/RadialBarChart.js')?.default;
export const ComposedChart= require('recharts/es6/chart/ComposedChart.js')?.default;
export const Funnel= require('recharts/es6/numberAxis/Funnel.js')?.default;
export const FunnelChart= require('recharts/es6/chart/FunnelChart.js')?.default;
export const Trapezoid= require('recharts/es6/shape/Trapezoid.js')?.default;
export const Global= require('recharts/es6/util/Global.js')?.default;
```

My env is `react ^17.0.1`, `ts ^4.0.3` and `recharts 2.0.0` . In other words I reexport `recharts`, we lost typedefinitions but at least the code is now running.

**Comment by rafipiccolo** [comment]
gj, can the fix be pushed on npm please ?

**Comment by mehrdadrafiee** [comment]
@PascalPixel thanks for the workaround solution! I'm not using webpack, I'm just using npm scripts. would that still work? if so, how would I enable transpiling node_modules/recharts in my environment?

**Comment by AlexPauloVieira** [comment]
Got the same problem, I'm using "typescript": "^4.0.3", "react": "^17.0.1", "recharts": "^2.0.0",

**Comment by ericmadureira** [comment]
Same here, using "react": "^16.14.0", "recharts": "^2.0.0", "next": "^10.0.3",

**Comment by NShahri** [comment]
Exported `Props types` are included in the final package in `es6/index.js` and `lib/index.js` which causes this issue.
By using `import type`, babel can make better assumptions about the exported modules/types.

PR:
https://github.com/recharts/recharts/pull/2374

**Comment by dgiacco** [comment]
Hi!

This is a bug in version 2.0.0, it happened the same to me. Try installing the previous version of recharts:
**npm install recharts@1.8.5**

This worked for me, at least until they fix the bug.

**Comment by TimFL** [comment]
> Hi!
> 
> This is a bug in version 2.0.0, it happened the same to me. Try installing the previous version of recharts:
> **npm install recharts@1.8.5**
> 
> This worked for me, at least until they fix the bug.

I went back to 2.0.0-beta.8 instead of 1.8.5.

**Comment by ParrotStone** [comment]
Same issue here. 
I'm on version recharts@2.0.0 and TypeScript version 4.0.3.

**Comment by pankajsanam** [comment]
> This is because the es6 compile folder's index.js imports types that are not left in the actual files after compilation.
> 
> A temporary hack is to use the `src` folder directly for TypeScript, or the `umd` version for JS.
> 
> So instead of:
> 
> ```js
> import { Area } from "recharts";
> ```
> 
> JS users should use:
> 
> ```js
> import * as Recharts from "recharts/umd/Recharts";
> const Area = Recharts.Area;
> ```
> 
> And for TS users:
> 
> ```js
> import { Area } from "recharts/src";
> ```
> 
> (Make sure you enable transpiling node_modules/recharts in whatever setup you have.)
> 
> I'm sure 2.0.1 will easily fix this oversight.

This fixes the problem but prints a lot of console logs which are left in the recharts/umd/Recharts.js file.

**Comment by santilp95** [comment]
I have the same problem, but when I change to version 1.8.5 it does not work and the console says this

`react-dom.development.js:67 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: LineChart`

And therefore nothing is shown

**Comment by afholderman** [comment]
I encountered this same issue and 2.0.0-beta.8 got me up and running. To those who are saying you had to downgrade all the way to 1.8.5 make sure your package.json does not include any semver modifiers and ONLY lists `"recharts": "2.0.0-beta.8"`. Remove yarn.lock or package-lock.json and your node_modules before doing a clean install. After the install pull up node_modules/recharts/package.json and ensure the correct version is listed.

**Comment by tams2429** [comment]
This is not fixed, can this thread be reopened until the latest version is fixed? Thanks

**Comment by KrisGerhard** [comment]
@tams2429 check again, now the versions containing the fixes have been released on github and npm.
We no longer encounter this issue using version 2.0.2

Thank you, contributors!

**Comment by ParrotStone** [comment]
> @tams2429 check again, now the versions containing the fixes have been released on github and npm.
> We no longer encounter this issue using version 2.0.2
> 
> Thank you, contributors!

Finally :+1:

**Comment by joshuarobs** [comment]
Updating to 2.0.2 only didn't work for me, but when I updated the typescript/recharts package too, then it worked
