### ISSUE TITLE
Remove  console.log

### ISSUE THREAD

**Issue by QoobIY** [recharts/recharts#2363]
https://github.com/recharts/recharts/blob/98ddefb28e057a5ca8c01504ae11330e72eca91f/src/component/Text.tsx#L88

Remove  console.log, please :)

**Comment by fengpei0114** [comment]
recharts/src/component/Text.tsx: Line 172 
`console.log(textProps.x, textProps.y, this.props.children, wordsByLines, this.props);`


Please remove this console.log, too :)

**Comment by avindra** [comment]
Included this on #2361

**Comment by avindra** [comment]
Fixed in 984c7d867ee6eb1335804cd0e6110392324c41ae

(Release pending)
