### ISSUE TITLE
React 17

### ISSUE THREAD

**Issue by cujarrett** [recharts/recharts#2368]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Is there a roadmap to update the peerDependency to react 17 (released in October 2020).

### What does the proposed API look like?
N/A

**Comment by rafipiccolo** [comment]
could u change this in the package.json to allow react v17 ?

i can confirm that it works for me with react 17, if i force install, but it would be better to just install without force.
```
"peerDependencies": {
    "react": "^16.0.0",
    "react-dom": "^16.0.0"
},
```
it could be

```
"react": "^16.0.0 || ^17.0.0",
"react-dom": "^16.0.0 || ^17.0.0"
```

**Comment by rafipiccolo** [comment]
pull request done. could you merge it please ?
