### ISSUE TITLE
Line chart `strokeDasharray` does not apply if `isAnimationActive` is `false` from the start and set to `true` in `componentDidMount`

### ISSUE THREAD

**Issue by a-pachkov** [recharts/recharts#2373]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-examples-forked-bjyc4?file=/src/LineChart/index.js)

### Steps to reproduce
Add Line component with `strokeDasharray` set and `isAnimationActive` set to `false` from the start and set to `true` in `componentDidMount`

### What is expected?
The line should be dashed from the start.

### What is actually happening?
The line is solid from the start.

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.14.0 |
| System | Linux |
| Browser | Chrome version  87.0.4280.88 |

---
Video example - https://share.getcloudapp.com/12uKlDNE
Related source code - https://github.com/recharts/recharts/blob/v1.8.5/src/cartesian/Line.js#L152-L155

**Comment by dillonreedy** [comment]
Unless I'm misunderstanding correctly, to achieve the effect where:
1. The animation is not in effect at the start
2. The animation is effective after every "Update" button click

You should be setting the animate state on the button click event, not on the componentDidMount lifecycle method.

So your button click will now become this:
```html
        <button
          onClick={() =>
            this.setState({
              list: list.map((item) => ({
                ...item,
                Dashed: item.Solid,
                Solid: item.Dashed
              })),
              animate: true
            })
          }
        >
```

I've made a fork off your original codesandbox doing it here:
[![Edit Recharts Examples (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-examples-forked-ypwlo?fontsize=14&hidenavigation=1&theme=dark)

**Comment by a-pachkov** [comment]
@dillonreedy thank you a lot for your replay and example!
I need this feature to prevent slow render in case with too many charts on the page.
But the real code does not have an "update" button, so I'll need to make a deep equal of new and old data, right?
Thank you again!
