### ISSUE TITLE
None of the jsfiddle samples from the website are working

### ISSUE THREAD

**Issue by arunrmatwork** [recharts/recharts#2375]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/alidingling/rnywhbu8/](https://jsfiddle.net/alidingling/rnywhbu8/)

### Steps to reproduce
Go to https://recharts.org/en-US/examples/CustomShapeBarChart
click on the jsfiddle link which will take you to https://jsfiddle.net/alidingling/rnywhbu8/ 

### What is expected?
on "run" the page should show the chart

### What is actually happening?
the chart is not rendered.

| Environment | Info |
|---|---|
| Recharts | v2.0.0 |
| React | latest |
| System | Mac  |
| Browser | chrome, safari |

**Comment by dillonreedy** [comment]
The latest version 2 release has caused this to happen. Fixes are currently in progress.

If you use CodeSandbox instead you can rollback to the beta versions or v1.8.5

**Comment by avindra** [comment]
There is a problem with `jsfiddle`'s compilation pipeline. I see this error in console:

```
Uncaught TypeError: _ is undefined
    render Text.tsx:207
    React 55
    <anonymous> (index):50
    run babel.js:60802
    check babel.js:60868
    loadScripts babel.js:60909
    runScripts babel.js:60936
    transformScriptTags babel.js:324
Text.tsx:207:6
    render Text.tsx:207
    React 55
    <anonymous> Inline Babel script:58
    run babel.js:60802
    check babel.js:60868
    loadScripts babel.js:60909
    runScripts babel.js:60936
    transformScriptTags babel.js:324
```

I moved your example to [codesandbox](https://codesandbox.io/s/optimistic-tu-o4yeu?file=/src/App.js) and it works there with 2.0.2. Codesandbox makes it very easy to add dependencies in tests, and more importantly seems to be working.

**Comment by avindra** [comment]
@arunrmatwork just noticed this affected core examples, I created a new issue against the site repo:

https://github.com/recharts/recharts.org/issues/156
