### ISSUE TITLE
Failed to compile : "export 'Props' (reexported as 'AreaProps') was not found in './cartesian/Area' (Previous issue #2360 not fixed)

### ISSUE THREAD

**Issue by tams2429** [recharts/recharts#2378]
Just trying to bring to light that the error caused by the latest recharts version is still not fixed.

Error:
'Failed to compile : "export 'Props' (reexported as 'AreaProps') was not found in './cartesian/Area''

**Comment by soulchainer** [comment]
I just wanna add that I'm getting several warnings in my stories in Storybook (for now I'm only rendering the charts there), in the JavaScript Browser console and logs, about the same, as example:

```
WARNING in ./node_modules/recharts/es6/index.js 50:0-82
"export 'Props' (reexported as 'TrapezoidProps') was not found in './shape/Trapezoid'
```

It doesn't came out as an error, but a warning, but there are a bunch of them and they clutter the log. This is just an example, obviously. There are a bunch of WARNING errors about that, also in `./cartesian`, as @tams2429 already told.

Also it seems there is some `console.log` in the wild there (in last version), but that's another issue.

**Comment by avindra** [comment]
New version isnt out yet. @xile611 publishing soon?

**Comment by meatnordrink** [comment]
This is my first time using Recharts, and it seems that it's totally unusable due to this bug. Is there some workaround that others know about? Or an older version I should jump back to? (It sounds like it was present in the previous version as well, from the first comment.)

**Comment by avindra** [comment]
@meatnordrink  If you revert to the beta, you should be able to build: ([2.0.0-beta8](https://github.com/recharts/recharts/releases/tag/v2.0.0-beta.8)).

2.0.1/the next version # should contain the fix (#2367).

**Comment by PaulPCIO** [comment]
I'm having the same issue, i also tried the `2.0.0-beta8` but got the same results

**Comment by xile611** [comment]
try v2.0.2

**Comment by nperichSYKES** [comment]
Ok, I tried 2.0.2 (and 2.0.3). But there's still the same error here. `2.0.0-beta8` also works for me.

My error is for Bar, not Area though. `Attempted import error: 'recharts/es6/cartesian/Bar' does not contain a default export (imported as 'Bar').`

fyi, I also tried deleting node_modules before install to be extra sure, and there's no yarn.lock/etc in this project.
