### ISSUE TITLE
XAxis and YAxis Style Prop

### ISSUE THREAD

**Issue by bbbryan14** [recharts/recharts#2381]
The docs on XAxis and YAxis do not currently mention that `style` is a prop for XAxis and YAxis, but based on this 

https://github.com/recharts/recharts/blob/master/src/cartesian/XAxis.tsx#L31

It should be an available prop of `SVGElement`. 

Requesting to update the docs
https://recharts.org/en-US/api/XAxis
https://recharts.org/en-US/api/YAxis

**Comment by xile611** [comment]
style is not encourage to use.

**Comment by bbbryan14** [comment]
imho: the docs should still say that these components extends the same interface as `SVGElement` so others know that they could be used.
