### ISSUE TITLE
Creating a chart in an invisible container raises an error

### ISSUE THREAD

**Issue by DrNixx** [recharts/recharts#2383]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-mkh0o?file=/src/index.js)

### Steps to reproduce
If a chart in a responsive container is created on an invisible component, we will get an error when switching the visibility

### What is expected?
Click button, show chart 

### What is actually happening?
Error message

| Environment | Info |
|---|---|
| Recharts | v2.0.0 |
| React | 16.8.6 |
| System | Any |
| Browser | Any |

**Comment by ckifer** [comment]
Related to #2385 in `calculateActiveTickIndex` this should be resolved soon.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
