### ISSUE TITLE
Showing Value of X-Axis in Tooltip on LineChart (by cursor position on chart)

### ISSUE THREAD

**Issue by jakubprogramming** [recharts/recharts#2384]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When using tooltips in a LineChart the value of the Y-Axis is shown by default the popover overlay. 
I would like to be able to also see the value of the X-Axis. 

I am certain that this must be possible somehow, but I am unable to achieve this. 

I have created and edited screenshot that explains exactly what I want to achieve:
https://ibb.co/59pMW8k

### What does the proposed API look like?
<Tooltip showX={true}/>

**Comment by ckifer** [comment]
Hi @jakubprogramming,
You'll be able to do this using a custom tooltip component or formatter function. Check out #275 for good examples on how it has been implemented by others.

**Comment by jakubprogramming** [comment]
Thank you for your response @ckifer 
With your tip I have been able to achieve my goal.

**For reference see the code snippets below:**

`renderCustomToolTip(data){
    return (
      <div>
        <span>{data.payload[0].payload.dateTime}</span>
      </div>
    )
  }`


`<XAxis dataKey="dateTime"/>`
`<Tooltip content={this.renderCustomToolTip.bind(this)}/>`
