### ISSUE TITLE
TypeScript Error when putting Chart inside of ResponsiveContainer

### ISSUE THREAD

**Issue by Rabter1** [recharts/recharts#2385]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-typescript-error-4mtpq)

### Steps to reproduce
Put a Chart inside of a ResponsiveContainer - see also codesandbox

--> TypeScript Error in `ChartUtils.js:86` at `calculateActiveTickIndex`

### What is expected?
No Error

### What is actually happening?
I really cant tell because i am new to recharts. I tried with version 2.0.0, 2.0.1 and 2.0.2
I cant even run the examle codes provided on recharts.org inside of a ResponsiveContainer
I get a TypeError:  Cannot read property 'length' of undefined

| Environment | Info |
|---|---|
| Recharts | v2.0.2 |
| React | tested with 16.14 and 17.0.0 |
| System | Windows 10 |
| Browser | Chrome |

---
I made a very short codesandbox to reproduce: https://codesandbox.io/s/recharts-typescript-error-4mtpq

**Comment by ckifer** [comment]
@xile611 this resolves React 17 support but there is still an issue in strict mode with `ResponsiveContainer` and `ResizeObserver`.

[![Edit Recharts TypeScript Error (forked) - Strict Mode](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-typescript-error-forked-8dehc?fontsize=14&hidenavigation=1&theme=dark)
 
`javascript Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of ResizeDetector which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at div
    at ResizeDetector (https://8dehc.csb.app/node_modules/react-resize-detector/lib/esm/components/ResizeDetector.js:152:5)
    at div
    at ResponsiveContainer (https://8dehc.csb.app/node_modules/recharts/lib/component/ResponsiveContainer.js:56:5)
    at div
    at App
 `
 
Also seems to be an issue for setting strings for heights and widths.

@Rabter1 
[![Edit Recharts TypeScript Error (forked) Not in strict mode](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-typescript-error-forked-gfr6x?fontsize=14&hidenavigation=1&theme=dark)

Your issue should be solved in 2.0.3, but you must disable React strict mode for now.

**Comment by boxdox** [comment]
@ckifer I just updated to recharts@2.0.3 (with React 17.0.1). The issue still persists. Removing strict mode is not an option. Here's how I am using it:

```js
<ResponsiveContainer width="100%" height={400}>
```

**Comment by ckifer** [comment]
@boxdox yeah looks like responsive container still doesn't like percentages in strict mode. Hopefully can get a fix soon!

**Comment by boxdox** [comment]
@ckifer looks like it's an issue with react-resize-detector, and can be fixed by attaching `targetRef` prop. Let me see if I can pull a PR for this (if no open PR)

**Comment by xile611** [comment]
It seems better to use react 16.x now.

**Comment by raRaRa** [comment]
Same issue here. Was hoping to be able to use Recharts inside a Material-UI grid system.

```
TypeError: Cannot read property 'length' of undefined
calculateActiveTickIndex
/recharts/es6/util/ChartUtils.js:86
  83 | }
  84 | export var calculateActiveTickIndex = function calculateActiveTickIndex(coordinate, ticks, unsortedTicks, axis) {
  85 |   var index = -1;
> 86 |   var len = ticks.length;
```

**Comment by marnixhoh** [comment]
I am having the same issue as @raRaRa. The error appears to be coming from calculateActiveTickIndex...
Note: for me it only appears in my Jest tests when after the component has mounted I change the ticks using setProps().

It appears as if this causes ticks passed to calculateActiveTickIndex to be undefined. Note that my tests used to pass on 1.8.5. It stopped working after upgrading to 2.0.3.

**Comment by ferdingler** [comment]
+1, removing `<ResponsiveContainer>` doesn't change anything. The issue still appears in our Jest tests

**Comment by aceamarco** [comment]
> Same issue here. Was hoping to be able to use Recharts inside a Material-UI grid system.
> 
> ```
> TypeError: Cannot read property 'length' of undefined
> calculateActiveTickIndex
> /recharts/es6/util/ChartUtils.js:86
>   83 | }
>   84 | export var calculateActiveTickIndex = function calculateActiveTickIndex(coordinate, ticks, unsortedTicks, axis) {
>   85 |   var index = -1;
> > 86 |   var len = ticks.length;
> ```
> 
> Update: Ah, seems like the container needs a specific width or height set.

@raRaRa Were you able to get it working with the Material UI Grid system? I'm trying to do that currently and nothing renders... I've tried everything from not wrapping the `ResponsiveContainer` in a `Grid item` component, to adding aspect ratios, hard coded width and lengths, and nothing changes ... this is what I currently have:

```
function HealthDataLineChart({ dataToShow, xAxisField, yAxisField }) {
  return (
    <ResponsiveContainer width="90%" height="400px">
      <LineChart data={dataToShow}>
        ...
      </LineChart>
    </ResponsiveContainer>
  );
}

...
<Grid container>
  <Grid item xs={12}>
          <HealthDataLineChart
            dataToShow={dataToShow}
            xAxisField={xAxisField}
            yAxisField={yAxisField}
          />
   </Grid>
</Grid>

```

**Comment by ckifer** [comment]
@aceamarco can you make a sandbox?
