### ISSUE TITLE
Images as Axis Ticks

### ISSUE THREAD

**Issue by Moeface** [recharts/recharts#239]
I'm looking to create a custom tick component that takes a URL and returns an image for each tick on the X-Axis.

When I pass an image URL (e.g. `http://example-cdn.domain.com.au`) to the component, the custom tick is not rendered at all. 

When I removed the dashes in the URL the component is rendered and the URL is passed through.

Is this intended or a known issue?

Thanks for the great library.

**Comment by xile611** [comment]
@Moeface Can you support a jsfiddle demo ?

**Comment by Moeface** [comment]
This example does not use dashes, but it has the same issue, so it may not be related specifically to the dashes: http://jsfiddle.net/344uh0ax/8/

**Comment by xile611** [comment]
The image doesn't display because the we calculate the width of each tick to decide whether the tick will displayed.  Because the width of the first companyUrl is too large, so this tick is hidden. So you can set the props `interval` to be 0 to force all the ticks showed.

```jsx
 <XAxis dataKey="companyUrl" interval={0} tick={<CustomXAxisLabel/>} />
```

**Comment by Moeface** [comment]
That's done the trick, thanks a lot for your help!
