### ISSUE TITLE
How to set svg image instead of the standard <rect /> in brush traveller?

### ISSUE THREAD

**Issue by antondankov93** [recharts/recharts#2390]
The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.

---

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

**Comment by ckifer** [comment]
@antondankov93 can you give a better description of what you are looking for?
You want an image as the slider for brush?

**Comment by antondankov93** [comment]
Here is a example of what I need

![Screenshot_1](https://user-images.githubusercontent.com/51218279/104832183-e216a780-58c1-11eb-81d3-ce0d6e2e36df.png)
