### ISSUE TITLE
Attempted import error: 'recharts/es6/cartesian/Bar' does not contain a default export (imported as 'Bar')

### ISSUE THREAD

**Issue by nperichSYKES** [recharts/recharts#2391]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://recharts.github.io/](https://recharts.github.io/)

### Steps to reproduce
npm start

### What is expected?
That it import and compile

### What is actually happening?
CRA fails at compilation

| Environment | Info |
|---|---|
| Recharts | v2.0.3 |
| React | 17.0.1 |
| System | MacOS, Create React App |
| Browser | n/a |

---
related to another closed issue regarding Area importing I assume. There is no yarn.lock in my project and I deleted node_modules before installing to be extra careful. 2.0.0-beta8 works for me.

**Comment by avindra** [comment]
Hi @nperichSYKES if you are using:

```js
import Bar from "recharts/es6/cartesian/Bar";
```

try instead:

```js
import { Bar } from "recharts/es6/cartesian/Bar";
```

**Comment by nperichSYKES** [comment]
Ah, yeah that works. I must have just been unusual in importing using default from the component path rather than destructuring from the top level.

In that case, no bug here! Just before closing perhaps update the Changelog release notes for 2.0 with this breaking change warning and the new import assumptions for the next person who runs into it. 

Thanks!

**Comment by avindra** [comment]
No problem. For added context,  #2361 brought up eslint to 7 and prettier to 2, and they seem to agree about not using any default exports. So in #2367 I replaced all of the default exports with named exports. There is further discussion online in various places about why named exports are more portable.

> Just before closing perhaps update the Changelog release notes for 2.0 with this breaking change warning and the new import assumptions for the next person who runs into it.

Yes, actually there is a stack of a dozen or so things that are undocumented. I'm closing the issue for now and adding the tag so we don't miss it.
