### ISSUE TITLE
LineChart exceeds graph when value is above the y-axis domain values

### ISSUE THREAD

**Issue by acejusto11** [recharts/recharts#2393]
Hi, 

I'm wondering if there's a current way to prevent the Line Chart from exceeding the graph container when the value is above the max y-axis domain value?

This is what it looks like currently

![image](https://user-images.githubusercontent.com/32895751/104623307-3442a780-56cd-11eb-8ba8-d19da6c63540.png)

**Comment by ckifer** [comment]
Hi @acejusto11,
What is the desired behavior? 
You should be able to set the max y-axis value to your max data point to resolve this.

**Comment by acejusto11** [comment]
> Hi @acejusto11,
> What is the desired behavior?
> You should be able to set the max y-axis value to your max data point to resolve this.
Hi @ckifer, the desired behavior is to just clip the line to max data point if the current value exceeds the max data point. 
But I already found the solution by setting allowDataOverflow to true
