### ISSUE TITLE
Tooltip content receive payload with undefined

### ISSUE THREAD

**Issue by SashaShostyr** [recharts/recharts#2394]
## What is the current behavior?
When I move mouse over the chart sometimes function that I pass as a content prop for Tooltip component receive payload equals to undefined.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/). 
Example from official docs https://codesandbox.io/s/recharts-tooltip-bug-wtstn?file=/src/App.js.

## What is the expected behavior?
I think payload should be equals array.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts? 
v2.0.3

**Comment by VladislavKsen** [comment]
You can add check for payload. http://prntscr.com/woah1z
https://codesandbox.io/s/recharts-tooltip-bug-forked-ems4w

**Comment by SashaShostyr** [comment]
> You can add check for payload. http://prntscr.com/woah1z
> https://codesandbox.io/s/recharts-tooltip-bug-forked-ems4w

Yeah, I do it, but if it's correct behaviour I think docs should be updated.

**Comment by jukkahuuskonen** [comment]
The official demo, mentioned above, is also crashing for this. I think this is some kind of bug in the code. 

V.2.0.0-beta6 worked fine without that extra check. So it has been introduced after that. Docs and demo should be updated or payload parameter should be fixed. Either one is fine with me.

**Comment by PhishyFish** [comment]
The bug where the payload returns `undefined` or `[]` was introduced in `v2.0.3`, specifically, when they replaced `UNSAFE_componentWillReceiveProps` with `getDerivedStateFromProps` and updated the logic within those calls.

**Comment by timbonicus** [comment]
This causes tooltip flickering with a custom renderer:

![tooltip-flicker](https://user-images.githubusercontent.com/556258/107460328-29850200-6b15-11eb-9f2a-05af7fddc102.gif)

It appears to happen most commonly when mousing along where the active dot appears, as shown above.

Another [code sandbox reproduction](https://codesandbox.io/s/recharts-issue-template-forked-5nr84). With the sandbox I can confirm that this was introduced in 2.0.3 as @PhishyFish mentions.
