### ISSUE TITLE
Some ticks missing from XAxis with NaN error when interval={0}

### ISSUE THREAD

**Issue by brendan-limpide** [recharts/recharts#2395]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-r2ih0?file=/src/prices.js)

### Steps to reproduce
1. Create LineChart
2. Add `ticks={[/* Array of strings */]} interval={0}` props to `XAxis`

### What is expected?
You should see every single tick in the array on the XAxis

### What is actually happening?
The x axis is missing some ticks. There are now ticks with x value: `NaN`. Which causes them to display outside of the chart (to the left, the vertical line). There are also errors in console like:
```bash
Warning: Received NaN for the `x2` attribute. If this is expected, cast the value to a string.
```

| Environment | Info |
|---|---|
| Recharts | v2.0.3 |
| React | 16.10.2 |
| System | macOS Catalina 10.15.7 |
| Browser | FF Dev Edition 85.0b7 (64-bit) |

**Comment by xile611** [comment]
You ticks should be validate.

**Comment by brendan-limpide** [comment]
> Your ticks should be validate.

@xile611 Can you explain what you mean? What kind of validation is required here?

**Comment by cbreezier** [comment]
I'm seeing the same issue, on the YAxis.

This happens even when I don't add a `ticks` parameter.

When I set `interval={0}`, all the ticks show up but I get an error: `Received NaN for the `y2` attribute. If this is expected, cast the value to a string.`

If I don't set `interval={0}` then I don't get the `NaN` error but I get some ticks missing.
