### ISSUE TITLE
Separate library and/or disable animation by default

### ISSUE THREAD

**Issue by katopz** [recharts/recharts#240]
Hi,

Thanks for great library, I like everything except animation here's why.
1. Not useful for static render e.g. SSR or exporter tools.
2. Increase library file size, useless for static render purpose only.
3. Not so nice animation, see separated [stackbar](http://recharts.org/examples/#StackedBarChart) for example, look weird to me.
4. Wasting time waiting for it playing animation, I'm not sure why I'm so hate it but yes it  annoying me more than impress.

Would be nice if animation can be separated inject only when need.
BTW, I just thinking out loud so you can just say no and close this issue right away. :)

Thanks

**Comment by RobiFerentz** [comment]
👍
