### ISSUE TITLE
Cannot read property 'length' of undefined at calculateActiveTickIndex

### ISSUE THREAD

**Issue by essencient** [recharts/recharts#2402]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-lvh5t?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Update to v2.0.3 from v2.0.0

### What is expected?
Was getting the stackOffset issue so updated to v2.0.3 as issue was reported as fixed in v.2.0.0-beta.8 and later

### What is actually happening?
App now crashes with error message Cannot read property 'length' of undefined at calculateActiveTickIndex. Issue appears to be in ChartUtils.js

| Environment | Info |
|---|---|
| Recharts | v2.0.3 |
| React | 16.13.1 |
| System | Window 10 64-bit |
| Browser | Chrome |

---
Tried rolling back to v2.0.0 but problem persisted

**Comment by essencient** [comment]
Have discovered this only happens when your wrap the chart in a <ResponsiveContainer>

**Comment by vladimirvolek** [comment]
I have the same problem :/

**Comment by ckifer** [comment]
#2385

**Comment by essencient** [comment]
Tried the fix suggested by @MarcusNotheis in ChartUtils.ts but not sure if I did it right as didn't work. Seems like it would fix the issue though.
