### ISSUE TITLE
Bar component goes out of char lines when used inside ComposedChart

### ISSUE THREAD

**Issue by ovidijusr** [recharts/recharts#2403]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-90xxt?file=/package.json)

### Steps to reproduce
- Create a Bar component and wrap around with ComposedChart
- Use 2.0.3 version of recharts
- bars overlaps the chart
- Change version to 1.8.5
- bars does not overlap

### What is expected?
The most left and right bars should not go out of chart, but stay inside.
(like in 1.8.5 or wrapping in BarChart)

### What is actually happening?
The most left and right bars goes out of chart.

| Environment | Info |
|---|---|
| Recharts | v2.0.3 |
| React | 16.13.1 |
| System | Mac os big sur |
| Browser | Google chrome 87 |

**Comment by datnguyen14** [comment]
Same issue with me.
![image](https://user-images.githubusercontent.com/67571368/104978360-46f20f00-5a34-11eb-8f2c-174cc0d42d59.png)

**Comment by ckifer** [comment]
@ovidijusr @datnguyen14 
You can add padding to either side of the XAxis for now, but that will also move your lines. Agreed that this needs addressed.
`<XAxis dataKey="name" padding={{ right: 60, left: 60 }} />`

**Comment by ovidijusr** [comment]
Yeah, but the issue is when you have different data on same graph, then the margins needs to be different

**Comment by badbod99** [comment]
Same issue here, but with Composed chart with vertical bar.

![image](https://user-images.githubusercontent.com/7858558/107933057-2c994b80-6f76-11eb-89c8-a4e51adc4bc8.png)

**Comment by KlonD90** [comment]
I research this bug. It related to parseScale function and ComposedChart type. What's the right way to fix it? @xile611

**Comment by KlonD90** [comment]
Possibile temporarily decision add to XAxis: scale="band"
