### ISSUE TITLE
Broken/single data visualization in Line chart (Recharts)

### ISSUE THREAD

**Issue by Bhagtana13** [recharts/recharts#2411]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
On broken Line chart when we disable dots then we don't see any dots on the line but we are expecting to see a dot on a data point where line is broken for the better data visualization in Line chart

### What does the proposed API look like?
The API will give a prop which will enable dots for broken line chart to display on missing data point and not show dots on data points where data is not missing and line is not broken

**Comment by ckifer** [comment]
Hi @Bhagtana13,

You want to see a data point where there is no data? Can you give some more detail? It seems as though there wouldn't be anywhere to put the datapoint if there is no data there.

**Comment by xile611** [comment]
Please open an issue follow the issue guide.
