### ISSUE TITLE
Piechart onMouseEnter notWorking

### ISSUE THREAD

**Issue by incrusio21** [recharts/recharts#2414]
- [x] I have searched the issues of this repository and believe that this is not a duplicate.

after I update version 2.0.3 the onMouseEnter function doesn't work

https://codesandbox.io/s/wispy-https-s6sb5

**Comment by beatrizdominguez** [comment]
I have the same issue, both in versions 2.0.3 and 2.0.4

**Comment by Andrewwelton** [comment]
I've noticed the same problem with `LineChart` and `BarChart` as well.

**Comment by alxkat** [comment]
Have the same issue
