### ISSUE TITLE
Draw a chart using points

### ISSUE THREAD

**Issue by hamboomger** [recharts/recharts#2417]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Is it possible for recharts.js to draw a line by specifying both x and y axis for each point? I need that feature in order to create phase space graphs.

### What does the proposed API look like?
-

**Comment by xile611** [comment]
Please open an issue follow the issue guide.
