### ISSUE TITLE
Percentile (low-frequent) marks in a bar charts 

### ISSUE THREAD

**Issue by AselToktogulova** [recharts/recharts#2418]
Hello dear recharts community,

my question is whether it is possible to mark bars in a bar chart that are in percentile rank or low frequent data.

thank a lot!

**Comment by dillonreedy** [comment]
@AselToktogulova do you want to use  use the `label` prop?

```html
<Bar dataKey="value" label />
<Bar dataKey="value" label={{ fill: 'red', fontSize: 20 }} />
<Bar dataKey="value" label={<CustomizedLabel />} />
```

**Comment by AselToktogulova** [comment]
> ```
> <Bar dataKey="value" label />
> <Bar dataKey="value" label={{ fill: 'red', fontSize: 20 }} />
> <Bar dataKey="value" label={<CustomizedLabel />} />
> ```

do you have an example? Is it dynamically?
