### ISSUE TITLE
ScatterChart raises exception when left margin is not set

### ISSUE THREAD

**Issue by digorydoo** [recharts/recharts#242]
Margins should be optional, some kind of default margin should apply, e.g. 0.
In fact, this seems to be the case with LineChart.
ScatterChart, however, will raise an exception if the left margin is missing.
http://jsfiddle.net/digorydoo/ww51Ln0u/
This is quite counter-intuitive, it took me almost an hour to find the problem.

**Comment by xile611** [comment]
@digorydoo The default margin of ScatterChart is 5.

[ScatterChart.js#L56](https://github.com/recharts/recharts/blob/master/src/chart/ScatterChart.js#L56)

```js
  static defaultProps = {
    style: {},
    margin: { top: 5, right: 5, bottom: 5, left: 5 },
  };
```
Any suggestion?

**Comment by digorydoo** [comment]
I'm pretty sure the defaultProps does not allow you to specify the defaults of individual members of an object. So, if I define margin, I'll override your defaultProps, so the property 'left' will be undefined.
