### ISSUE TITLE
React 17 install problem!

### ISSUE THREAD

**Issue by Stunext** [recharts/recharts#2425]
Cannot install in a React 17 project.

package.json:

```
"dependencies": {
        "axios": "^0.21.1",
        "react": "^17.0.1",
        "react-dom": "^17.0.1",
        "react-redux": "^7.2.2",
        "react-scripts": "^4.0.2",
        "react-router-dom": "^5.2.0",
        "react-helmet-async": "^1.0.7",
        "redux": "^4.0.5",
        "redux-thunk": "^2.3.0",
        "redux-logger": "^3.0.6",
        "socket.io-client": "^3.1.1"
    },
    "devDependencies": {
        "@craco/craco": "^6.1.1",
        "compression-webpack-plugin": "6.1.1",
        "webpack-bundle-analyzer": "^4.4.0"
    },
```

Error:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   peer react@">= 16" from react-scripts@4.0.2
npm ERR!   node_modules/react-scripts
npm ERR!     peer react-scripts@"^4.0.0" from @craco/craco@6.1.1
npm ERR!     node_modules/@craco/craco
npm ERR!       dev @craco/craco@"^6.1.1" from the root project  
npm ERR!     react-scripts@"^4.0.2" from the root project       
npm ERR!   react@"^17.0.1" from the root project
npm ERR!   1 more (recharts)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-resize-detector@5.2.0  
npm ERR! node_modules/recharts/node_modules/react-resize-detector
npm ERR!   react-resize-detector@"^5.2.0" from recharts@2.0.4
npm ERR!   node_modules/recharts
npm ERR!     recharts@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by avindra** [comment]
```
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   peer react@">= 16" from react-scripts@4.0.2
```

Given react 17 satisfies react >= 16, I'm guessing this is an `npm` bug. You might want to try the suggested fix:

```
npm ERR! ...  retry
npm ERR! this command with...  --legacy-peer-deps
```

**Comment by avindra** [comment]
Or, you could try yarn. Yarn is able to resolve the the `package.json` as-is from your original post. It doesn't throw any errors about peer dep conflicts, which further indicates that this is an `npm` bug. It may be equivalent to: https://github.com/npm/cli/issues/2553 

FWIW, here are the versions I tested:

```sh
$ npm --version
7.3.0
$ yarn --version
1.22.4
```

**Comment by idastambuk** [comment]
Part of OP's error is regarding react-resize-detector, which isn't an NPM bug, since the version in recharts for resize-detector doesn't include major versions. I'm currently facing the same issue and, even though --legacy-peer-deps works, it would be ideal that the dependency is updated in recharts. 

Should I open another ticket for this or reopen this one?
 
`Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-resize-detector@5.2.0
npm ERR! node_modules/recharts/node_modules/react-resize-detector
npm ERR!   react-resize-detector@"^5.2.0" from recharts@2.0.6
npm ERR!   node_modules/recharts
npm ERR!     recharts@"^2.0.3" from the root project
`

**Comment by avindra** [comment]
@idastambuk I bumped `react-resize-detector` on my  abandoned PR #2426 https://github.com/recharts/recharts/pull/2426/commits/18b0aa69d993d26846c29eacde5ad15eaefb9092 and it seemed well.

Thanks for pointing out the issue, I opened #2431 with the detail.

**Comment by kerams** [comment]
Is it just me or do others still have a problem with this because of the dependency on v1.0.6 of react-smooth (v2 was released a couple of days ago and it is compatible with React 17)?

**Comment by Nnenna-udefi** [comment]
> Is it just me or do others still have a problem with this because of the dependency on v1.0.6 of react-smooth (v2 was released a couple of days ago and it is compatible with React 17)?
It's not just you
