### ISSUE TITLE
Missed type definition of tickMargin in XAxis, YAxis

### ISSUE THREAD

**Issue by havenchyk** [recharts/recharts#2427]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com](https://github.com)

### Steps to reproduce
<img width="512" alt="image" src="https://user-images.githubusercontent.com/1291032/107272702-26c7d580-6a5f-11eb-9fe2-fb4ca1aa50ab.png">

```
<YAxis
    type='number'
    tickLine={TICK_LINE}
    axisLine={AXIS_LINE}
    minTickGap={MIN_TICK_GAP}
    tickMargin={TICK_MARGIN}
    width={Y_AXIS_WIDTH}
    ticks={ticks}
    domain={[ticks[0], ticks[ticks.length - 1]]}
  />
```

### What is expected?
`tickMargin` is defined on the XAxis, YAxis 

### What is actually happening?
tickMargin is not defined

| Environment | Info |
|---|---|
| Recharts | v2.0.3 |
| React | 16 |
| System | macOS |
| Browser | any |

---

**Comment by havenchyk** [comment]
@xile611 amazing, thanks 😄 

would you like to setup automatic releases with semantic release?

**Comment by kodermax** [comment]
I have the same error.
v2.0.6

**Comment by havenchyk** [comment]
@xile611 would you mind releasing the next version please?
