### ISSUE TITLE
Allow types to accept accessibility related HTML attributes when using with Typescript

### ISSUE THREAD

**Issue by equinusocio** [recharts/recharts#2429]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[htto://none.com](htto://none.com)

### Steps to reproduce
Add the `role="graphics-document"` HTML attribute to any recharts element.

### What is expected?
No warning by Typescript about missing `role` property

### What is actually happening?
Typescript throws an error due to "missing role property on the element"

| Environment | Info |
|---|---|
| Recharts | v2.0.6 |
| React | 17.0.1 |
| System | macOS Big Sur |
| Browser | None |

**Comment by xile611** [comment]
Please open an issue follow the issue guide.

svg element don't support role attribute now.

**Comment by mgifford** [comment]
Adding some documentation for this https://blog.tenon.io/accessible-charts-with-aria/

**Comment by equinusocio** [comment]
@mgifford I don't think they care about a11y at all.
