### ISSUE TITLE
Update react-resize-detector for react 17 compatibility

### ISSUE THREAD

**Issue by avindra** [recharts/recharts#2431]
Originally reported to #2425. When using react 17 and npm, the following peer dependency error is thrown:

```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-resize-detector@5.2.0  
npm ERR! node_modules/recharts/node_modules/react-resize-detector
npm ERR!   react-resize-detector@"^5.2.0" from recharts@2.0.4
npm ERR!   node_modules/recharts
npm ERR!     recharts@"*" from the root project
npm ERR!
```

**Comment by manleyw-lattice** [comment]
i'm still getting npm install failure when using react 17, even after the version bump

**Comment by harleylang** [comment]
The latest version bump is throwing an error for me (React `^16.14.0`), I think it is due to an issue with `react-resize-detector@6.6.0`: https://github.com/maslianok/react-resize-detector/issues/141

I was able to temporarily avoid this issue by downgrading recharts to `2.0.7`.

**Comment by maslianok** [comment]
Hey, I'm a `react-resize-detector` author 👋

 
> i'm still getting npm install failure when using react 17, even after the version bump

@manleyw-lattice  
`reat-resize-detector` [supports React@16-17](https://github.com/maslianok/react-resize-detector/blob/master/package.json#L51). Can you please double check that you use the most recent version of `recharts` and that the error you get comes from `react-resize-detector`



> The latest version bump is throwing an error for me (React `^16.14.0`), I think it is due to an issue with `react-resize-detector@6.6.0`: [maslianok/react-resize-detector#141](https://github.com/maslianok/react-resize-detector/issues/141)

No, these are not connected issues. I added a comment to the issue you are referencing to. Let me know if you have any additional questions.


---

Please, create issues in the [react-resize-detector](https://github.com/maslianok/react-resize-detector) repo. I'll do my best to resolve them asap.

**Comment by harleylang** [comment]
Thank you @maslianok, you were correct! I'm glad you mentioned polyfills in your other comment. Turns out my version of firefox was 10 versions behind! Updating fixed my issue.
