### ISSUE TITLE
Bar lays on top of tickLine(baseline) on BarChart xAxis

### ISSUE THREAD

**Issue by isaconsid** [recharts/recharts#2432]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://recharts.org/en-US/examples/SimpleBarChart](https://recharts.org/en-US/examples/SimpleBarChart)

### Steps to reproduce
* Go to the recharts site and view the bar chart
* Zoom in on the bar's bottom to see it and the base line (x axis)
* Look at the bottom of the bar / look at the base line (x axis)

### What is expected?
Expected that the bar is not laying itself over the base line, rather it should be above it. It would also be desirable to be able to add some margin between the bars and the base line itself for the x axis.

### What is actually happening?
The bar is "overflowing" the baseline slightly.

| Environment | Info |
|---|---|
| Recharts | v2.0.6 |
| React | React 17.0.1 |
| System | Windows 10 |
| Browser | Chrome v 88.0.4324.150, Firefox 85.0.2 (64-bit), Edge 88.0.705.63 |

---
I am using recharts in our application to view a bar chart, and in our design we wanted to have just a few pixels of space between the baseline and the start of the bar itself, and that's when I saw that this is how it renders out of the box.

**Comment by badbod99** [comment]
This is actually worse on horizontal bar charts and is a new issue since 2.0.0.  1.8.6 does not exhibit this issue.  See image.
![image](https://user-images.githubusercontent.com/7858558/107930227-a0395980-6f72-11eb-9211-b71035275f7f.png)

**Comment by xile611** [comment]
You can change the order of `<Bar />` and `<XAxis />` to handle this case.

**Comment by LuisValgoi** [comment]
Solved for me to @xile611. How did come up with this solution?

**Comment by wal-nagama** [comment]
I kept surfing and landed the solution here. @xile611 Thank you 🙏
