### ISSUE TITLE
Enable dependabot

### ISSUE THREAD

**Issue by Himadu2000** [recharts/recharts#2433]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Recharts contain large number of dependencies and they are falling behind with time. Therefore it would be best to enable dependabot.

### What does the proposed API look like?
This can be enabled at https://dependabot.com/

**Comment by ckifer** [comment]
Dependabot has been enabled for a while, resolving this
