### ISSUE TITLE
Typo in the SankeyChart example code

### ISSUE THREAD

**Issue by ryinyang** [recharts/recharts#2435]
## Do you want to request a feature or report a bug?
Bug (technically a typo)
## What is the current behavior?
Example code looks like:

```
<Sankey
  width={960}
  height={500}
  data={data0}
  node={<MyCustomNode />}
  nodePading={50} <-- typo here, should be nodePadding
  margin={{
   left: 200,
    right: 200,
    top: 100,
    bottom: 100,
  }}
  link={{ stroke: '#77c878' }}
>
  <Tooltip />
</Sankey>

```
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
N/A
## What is the expected behavior?
Example code should look like:
```
<Sankey
  width={960}
  height={500}
  data={data0}
  node={<MyCustomNode />}
  nodePadding={50} <-- typo corrected
  margin={{
   left: 200,
    right: 200,
    top: 100,
    bottom: 100,
  }}
  link={{ stroke: '#77c878' }}
>
  <Tooltip />
</Sankey>
```
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
N/A

**Comment by xile611** [comment]
Thanks for your suggestion ! PR  is welcome.
