### ISSUE TITLE
no way to do a percent BarChart

### ISSUE THREAD

**Issue by UnsungHero97** [recharts/recharts#244]
I'd like to get something similar to the `PercentAreaChart` example:

http://recharts.org/examples#PercentAreaChart

However, I'd like it to be a `BarChart`... a `PercentBarChart`. I haven't been able to get this to work since the value passed into `tickFormatter` for `YAxis` is the value of the bar, and I don't have access to the total.

Suggestions?

**Comment by xile611** [comment]
@UnsungHero97 [Here](http://jsfiddle.net/quaph8w8/) is a demo of PercentBarChart. When you set the props `stackOffset="expand"`, `YAxis` will receive a percentage value.

**Comment by UnsungHero97** [comment]
Thanks, @xile611. Follow up question... how do you set the y-axis ticks to be in 10% increments? If I set `tickCount` to 10, the y-axis goes all the way up to 135%. I've tried playing with `ticks` and `domain` and `interval`, and I have't been able to make it work.

**Comment by UnsungHero97** [comment]
Hmmm... this seems to work:

```
const domain = [0, 1];
const ticks = [
  0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1
];
<YAxis domain={domain} ticks={ticks} tickCount={10} tickFormatter={toPercent} />
```
