### ISSUE TITLE
xAxis overlapping with chart legend

### ISSUE THREAD

**Issue by Gunner17** [recharts/recharts#2440]
The issue is very difficult to reproduce in jsfiddle, so instead I will post some snippets and screenshot.

The chart legend is overlapping with the xAxis labels:
<img width="914" alt="Screen Shot 2021-02-16 at 12 02 43 AM" src="https://user-images.githubusercontent.com/11354728/108034432-5d1acd00-6fea-11eb-9ff4-b16fa32f242f.png">

And on hovering over the chart, the chart height re-adjusts and corrects itself.
I am using Recharts version 1.8.5

Below is the structure of my chart:

```
<div style={{ width: '100%', height: customHeight }}>
	{
		config.title
		&& (
			<Title title={config.title} />
		)
	}
	{
		allowZoom
		&& (
			<ZoomButtons
				props={props}
			/>
		)
	}
	<ResponsiveContainer>
		<LineChart
			data={dataToPlot()}
			margin={{
				right: 25,
				left: showYLabel ? 0 : leftMargin,
				top: CHART_MARGIN_TOP,
				bottom: 10,
			}}
			onMouseDown={(e) => {
				// some logic
			}}
			onMouseUp={() => {
				// some logic
			}}
			onMouseEnter={() => {
				// some logic
			}}
			onMouseMove={(e) => {
				// some logic
			}}
			onMouseLeave={() => {
				// some logic
			}}
		>
			<XAxis
				{...commonXAxisConfigs}
			/>
			<YAxis
				{...commonYAxisConfigs}
			/>
			{renderTooltip()}
			{
				!config.hideLegends
					? (
						<Legend
							wrapperStyle={{
								paddingTop: 20,
							}}
							content={(
								<CustomLegend
									props={props}
								/>
							)}
						/>
					)
					: null
			}

			{renderLines()}
		</LineChart>
	</ResponsiveContainer>
</div>

```

Any idea what could be going wrong? Again sorry for not being able to post a jsfiddle link as it's only happening while fetching the data from server. Difficult to reproduce with hardcoded data.

**Comment by Arlien** [comment]
+1

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Comment by Yeshwanthi** [comment]
Also this worked for me. Setting the legend wrapper style property. I am using recharts version 2.0.6.
wrapperStyle={{ position: 'relative' }}

**Comment by quandaica** [comment]
I'm facing this issue on the latest version v2.1.1.
![image](https://user-images.githubusercontent.com/54837034/133929962-49f5d097-3ace-4ac9-a275-e9e82b64f6b9.png)

**Comment by pandu98** [comment]
Adding ResponsiveContainer to the lineChart fixed for me
