### ISSUE TITLE
Add possibility of position ReferenceDot in pixels, not only chart values

### ISSUE THREAD

**Issue by jvaclavik** [recharts/recharts#2443]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I'm trying to render `ReferenceDot` based on mouse move position, but `onMouseMove` event (from `Area`) returns area point coordinates in pixels, not in chart values (I mean values according to my axis). Problem is that `ReferenceDot` expects only the chart values, so I don't know how to reflect position of ReferenceDot according to mouse move event.

I could do it with custom SVG element, but in my case, it's quite specific because I want to have X coordinate according to chart values and Y coordinate according to the position of my pointer (which means pixels).

### What does the proposed API look like?
It looks like `ReferenceDot` re-calculates real "canvas" coordinates in `getCoordinate` function. So there could be a possibility of adding coordinates directly. It should be possible to combine canvas coordinates and the axis values. Maybe something like:

```
<ReferenceDot
  directX={300}
  y={500}
/>
```

**Comment by xile611** [comment]
You can use customized `shape` of `<ReferenceDot />` to handle this. just return the `directX` when you render customized elements.

**Comment by vtarelkin** [comment]
@jvaclavik Have you done that issue? Can't find an answer(

**Comment by Toko-Omnium** [comment]
@xile611 Instructions are bit unclear, can you provide more info or example please? thanks.

**Comment by bzbetty** [comment]
```
  <ReferenceDot
                y={yValue} x={category} r={4} xAxisId={0} fill="#3E66FB" stroke="none"
                shape={(props) =><Dot {...props} cx={78} cy={props.cy} className="recharts-reference-dot-dot" />}
             />
```
