### ISSUE TITLE
Don't show bars with value of 0

### ISSUE THREAD

**Issue by neagle** [recharts/recharts#245]
I have a bar graph where there are frequently instances of 0 values, as seen in this image:

![image](https://cloud.githubusercontent.com/assets/176993/18588237/a0c6ee0c-7bf3-11e6-9a8a-e3299d6038e7.png)

Is it possible with an existing option or custom function not to show bars with a value of 0?

**Comment by xile611** [comment]
@neagle Do you mean to remove the 'line' of bar?

**Comment by neagle** [comment]
That's correct, yeah. Ideally, even, I'd love to get rid of the space apportioned for that bar, or be able to set it to a minimum amount. But I'm not exactly trying to create a feature request here, I was mostly trying to see if it was currently possible.

I was able to get something that was close enough to what I wanted by using custom React elements for both the bar and the label that test for value:

```
const CustomBar = (props) => {
	const { stroke, fill, x, y, width, height } = props;

	if (height > 0) {
		return <rect
			x={x}
			y={y}
			width={width}
			height={height}
			stroke={stroke}
			fill={fill}
		/>
	} else {
		return <path d={getPath(x, y, 0, 0)} stroke="none" fill={fill}/>;
	}
};
```

```
const BarLabel = (props) => {
	const {
		payload,
		textAnchor,
		fill,
		x,
		y,
		width,
		height
	} = props;

	if (payload.value > 0) {
		return (
			<text
				textAnchor={textAnchor}
				fill="hsla(0, 100%, 100%, 0.8)"
				x={x}
				y={y}
				width={width}
				height={height}
				className="recharts-bar-label">
				{payload.value}
			</text>
		);
	} else {
		return <text></text>;
	}
};
```

...and then use them with `<Bar shape={<CustomBar/>} label={<BarLabel/>}/>`.

![image](https://cloud.githubusercontent.com/assets/176993/18632074/92c47b92-7e43-11e6-8740-9530f070b644.png)

**Comment by CatalinaCampos** [comment]
@neagle where 'getPath' comes from?

**Comment by billy-ogilvie** [comment]
> @neagle where 'getPath' comes from?

Appreciate it has been 5 years... but getPath will likely be from this section of the docs
https://recharts.org/en-US/examples/CustomShapeBarChart

```js
const getPath = (x, y, width, height) => {
  return `M${x},${y + height}C${x + width / 3},${y + height} ${x + width / 2},${y + height / 3}
  ${x + width / 2}, ${y}
  C${x + width / 2},${y + height / 3} ${x + (2 * width) / 3},${y + height} ${x + width}, ${y + height}
  Z`;
};
```
