### ISSUE TITLE
RadarChart label not responsive - cut when width not long enought

### ISSUE THREAD

**Issue by Audelweiss** [recharts/recharts#2450]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-c0cmt?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1. Resize the browser width until the label are cut (under 570px~)

### What is expected?
Resize the width and the chart auto adjust so we can still see the chart and labels

### What is actually happening?
No auto resize 
I had to set a fixed height so the "ResponsiveContainer" displays the chart. But I had to add custom CSS (see style.js) to resize the height and font-size one smaller screen... and labels are cut when the width is not long enought

| Environment | Info |
|---|---|
| Recharts | v2.0.7 |
| React | react 17.0.1 / next 10.0.6 |
| System | Windows 10 |
| Browser | Chromr / Chrome Canary |

---
Thank you in advance for your help

large screen OK
![152102110_241616234240938_5727744770664230230_n](https://user-images.githubusercontent.com/17007867/108375908-b3faef00-7202-11eb-9117-5db18971eab1.png)

responsive... not OK 
![151835261_909449743218679_5374126410252186036_n](https://user-images.githubusercontent.com/17007867/108375917-b52c1c00-7202-11eb-8a53-523cdf7b2d7e.png)

**Comment by xile611** [comment]
This feature is not easy. we have no plan to support this feature temporarily

**Comment by Fefedu973** [comment]
same issue

**Comment by ckifer** [comment]
This shouldn't have been closed like it was, but the original response is technically correct this is tough.

SVG text needs to exist inside an SVG, making it "responsive" isn't really a thing without a lot of calculations.

In lieu of a solution for this add more margin, make your text wrap, measure the bounds of the container. I'll look at reopening this

**Comment by ckifer** [comment]
You can try using a custom label with recharts `Text` and do `scaleToFit`
https://recharts.org/en-US/api/Text#scaleToFit

You can try using `textBreakAll` on Label
https://release--63da8268a0da9970db6992aa.chromatic.com/?path=/docs/api-component-label--docs#properties
