### ISSUE TITLE
Can't force break lines in axis dataKey

### ISSUE THREAD

**Issue by angelod1as** [recharts/recharts#2455]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-j8pev?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
- Add a `<br/>` tag to a "name" attribute in order to break text.
- See it prints the `<br/>` without breaking. 
- I also tried `&NewLine;` and other unicode line breaks.

### What is expected?
- The text renders `<br/>` tag, giving me a two-line text 

### What is actually happening?
- The text prints `<br/>` as string.

| Environment | Info |
|---|---|
| Recharts | v2.0.7 |
| React | 16.12.0 |
| System | Pop!_OS 20.04 LTS x86_64 |
| Browser | Chrome 88.0.4324.182 |

**Comment by xile611** [comment]
svg <text /> don't support <br/>
