### ISSUE TITLE
Guide example on recharts.org breaks page 

### ISSUE THREAD

**Issue by EliasTouil** [recharts/recharts#2456]
## Do you want to request a feature or report a bug?

Report a bug

## The bug is about :
https://recharts.org/en-US/guide/customize
section 3. The content of tooltip can be customized

## What is the current behavior?
When I hover on the graph, then I can see the tooltip for a split second, then the page becomes white and empty.

div id="app"></div is empty

Error on the console
```
react_devtools_backend.js:2430 TypeError: Cannot read property '0' of undefined
    at or (CustomTooltip.js:31)
    at Qo (react-dom.production.min.js:153)
    at zs (react-dom.production.min.js:175)
    at Ca (react-dom.production.min.js:263)
    at bl (react-dom.production.min.js:246)
    at ml (react-dom.production.min.js:246)
    at al (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Kr (react-dom.production.min.js:122)
```

## If the current behavior is a bug, please provide the steps to reproduce 

https://recharts.org/en-US/guide/customize
Go to section 3. The content of tooltip can be customized
Hover on the graph

## What is the expected behavior?

I want to know too 🥺

## Which versions of the browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Mac Os Catalina 10.15.7

I was able to reproduce the issue on : 

Google Chrome is up to date
Version 88.0.4324.182 (Official Build) (x86_64)

Firefox Version 85.0.2 (64 bit)
Firefox is up to date

Cheers 👨🏽‍💻

**Comment by EliasTouil** [comment]
duplicate of #2461 closed by @wshrews https://github.com/recharts/recharts/issues/2461#issuecomment-788067143

**Comment by ckifer** [comment]
Looks like this is fixed, resolving
