### ISSUE TITLE
No LineChart drawn when receive Live Data

### ISSUE THREAD

**Issue by HashDot** [recharts/recharts#246]
Hi,

has someone a live data example? I try to use recharts with redux and websocket. I get all the new data, but my chart does nothing.

**Comment by xile611** [comment]
@HashDot How about the data you received from server? And can you support your code about Recharts ?

**Comment by HashDot** [comment]
My code looks like this:

```
<ResponsiveContainer height={ 200 }>
  <LineChart data={props.data}
                   margin={{ top: 10, right: 20, left: 20, bottom: 0 }}
                   syncId="anyId">
         <XAxis
           height={ 30 }
           dataKey="created"
           stroke={ text }
           style={{ fontSize: '12px' }}
           tickLine={ false }
           axisLine={ false }
           padding={{ top: 10 }}
          />
         <YAxis
           width={ 20 }
           stroke={ text }
           style={{ fontSize: '12px' }}
           tickLine={ false }
           axisLine={ false }
          />
    <Tooltip content={<CustomTooltip />} />
    <Legend />
    <Line type="natural" dataKey="max" stroke={ red } dot={{ r: 0 }} activeDot={{ r: 4, strokeWidth: 0 }} isAnimationActive={ false }/>
    <Line type="natural" dataKey="usage" stroke={ green } dot={{ r: 0 }} activeDot={{ r: 4, strokeWidth: 0 }} isAnimationActive={ false }/>
  </LineChart>
</ResponsiveContainer>
```

The component lives in a stateless component. The data comes from a redux store which is dispatched by a websocket connection. I tried to deliver the data directly from the store in a component. Both gave me the same result.

**Comment by xile611** [comment]
@HashDot 

I copy your code and create a [demo](http://jsfiddle.net/10gthLf1/), it works.
Maybe you can check the following points:
1. The data received by LineChart is empty ?
2. The entry of data has attributes "max" and "usage" ?
3. What are the values of `text`, `green`, `red` ?

**Comment by HashDot** [comment]
1. The data is correct
2. Yep
3. Color variables

The problem is not to draw a chart. I get initial data from a redux store. A websocket connection updates the store every 10 seconds. If the store receives a update, the chart does not rerender but the chart receives the new data.

I've tried victory charts and it works. I think recharts ignore new data or something. Any idea?

**Comment by xile611** [comment]
@HashDot Sorry! I have no idea. I have used Recharts to render live data, It works. 
Do you get some logs in console ?
Or can you create a repo with your problem easily reproducible?

**Comment by HashDot** [comment]
Everything seems to be fine. I try to provide an example later today.

**Comment by xile611** [comment]
@HashDot OK! it'll be helpful.

**Comment by CapCap** [comment]
Any update on this?

**Comment by jdbence** [comment]
@HashDot  [Live Example](http://jsfiddle.net/ca1g5Lrf)

Most of the time people forget to use **this.setState()**

**Comment by jgentes** [comment]
I found a workaround by adding key={Math.random()} to the LineChart element, which forces React to redraw the chart when the component re-renders. I also had to use isAnimationActive={false} on the Line component.
