### ISSUE TITLE
BarChart CustomTooltip causes the page to crash

### ISSUE THREAD

**Issue by wshrews** [recharts/recharts#2461]
## Do you want to request a feature or report a bug?

Bug

## What is the current behavior?

When a <CustomTooltip /> is used hovering over one of the bars in the BarChart component will cause React to crash leaving empty whitespace.

## Steps to reproduce

This can be reproduced using example #3 ("The content of tooltip can be customized") from the Recharts customization demo page. Hover over any of the bars.

https://recharts.org/en-US/guide/customize

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Recharts 2.0.6

Chrome on macOS

This feature worked prior to updating from 2.0.0-beta (edit: appears to be working as recently as 2.0.2)

**Comment by wshrews** [comment]
Appears to be fixed with the release of 2.0.8

**Comment by EliasTouil** [comment]
@wshrews the issue is still present on the website, do you mean it also was a bug in Recharts but the website still needs an update?

**Comment by wshrews** [comment]
@EliasTouil that's right - this bug appeared to be in Recharts 2.0.3 through 2.0.7. I can't reproduce it locally in 2.0.8 so I'm guessing the website must be using an older version.
