### ISSUE TITLE
Chart children inside of a fragment aren't visible

### ISSUE THREAD

**Issue by Ayub-Begimkulov** [recharts/recharts#2462]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/headless-https-yc3v6?file=/src/App.js)

### Steps to reproduce
open a codesandbox and wait until it's loaded

### What is expected?
Expected to have x- and y-axis in the line chart

### What is actually happening?
they aren't recognized, because they are wrapped inside of the fragment

| Environment | Info |
|---|---|
| Recharts | v2.0.7 |
| React | 17.0.1 |
| System | Ubnuntu 20.04 |
| Browser | Chrome/88.0.4324.150 |

---
Was addressed in #1264 but still isn't fixed. Happens because `findAllByType` doesn't account for children inside of a fragment.

**Comment by joritochip** [comment]
I am still experiencing this issue. When I try to put things into a Fragment, they do not render on the graph. The Tooltip and Legend in particular seem to still work, but everything else (that I tried to use) don't render when placed into a Fragment.

[![Edit nameless-tree-ooigy](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nameless-tree-ooigy?file=/src/App.js)

**Comment by Ayub-Begimkulov** [comment]
@joritochip yes, you are right. It seems that I didn't test the fix properly. I'll try to open a PR that solves this issue.

**Comment by forresthopkinsa** [comment]
Bug has regressed with React 19. [Repro](https://codesandbox.io/p/sandbox/hardcore-hooks-vpck78)

**Comment by ckifer** [comment]
Works fine for me - make sure that your react is version exactly matches your react and react-dom versions. 

Also works if you upgrade to 3.0 alpha

**Comment by ckifer** [comment]
Makes sense that it would fail here, reading props directly off of elements is not good and thats exactly what this is doing https://github.com/recharts/recharts/blob/master/src/util/ReactUtils.ts#L95

Probably the source of the issue and tbh not sure if it can be fixed in 2.x. That check fails even when react-is matches versions correctly.

**Comment by forresthopkinsa** [comment]
Unfortunate. Thanks for investigating.

**Comment by ckifer** [comment]
I'll double check when I get a chance but that is the point of failure. 

I'm sure it's not just as easy as removing your elements from a fragment though that's what I'd suggest here at the moment. Will get back later

**Comment by ckifer** [comment]
@forresthopkinsa actually, this works fine. You need to have your react, react-dom, and react-is versions 100% match. The sandbox doesn't apply overrides correctly.

with 2.15.1
```
  "dependencies": {
    "react": "19.0.0",
    "react-dom": "19.0.0",
    "react-is": "19.0.0",
    "recharts": "2.15.1"
  },
  "overrides": {
    "react": "19.0.0",
    "react-dom": "19.0.0",
    "react-is": "19.0.0",
    "recharts": "2.15.1"
  }
```

**Comment by nisharg-codal** [comment]
Thanks for the comment, save my day :)

**Comment by forresthopkinsa** [comment]
Thanks, looks like my issue was a combination of yarn using a different override syntax + vite silently caching old modules. Can confirm, looks like this is working now with 2.15.1 🚀
