### ISSUE TITLE
Documentation can't be read

### ISSUE THREAD

**Issue by EdsonAlcala** [recharts/recharts#2468]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://recharts.org/en-US/api/XAxis#domain](https://recharts.org/en-US/api/XAxis#domain)

### Steps to reproduce
Just go to https://recharts.org/en-US/api/XAxis#domain and check the main content, there is an overlap with the main content and the side menu and can't be fully read. 

<img width="887" alt="Screenshot 2021-02-26 at 13 29 04" src="https://user-images.githubusercontent.com/3077635/109306645-5cc6d100-7837-11eb-8547-b882961e9d16.png">

### What is expected?
I should be able to read the documentation but now it looks like: [this](https://res.cloudinary.com/key-solutions/image/upload/v1614346309/Screenshot_2021-02-26_at_13.29.04_hm7amg.png)

As you see there is an overlap with the main content and the side menu

### What is actually happening?
there is an overlap with the main content and the side menu

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | react |
| System | Linux, Mac |
| Browser | Firefox, Chrome, Safari |

**Comment by angelod1as** [comment]
Possible solution: on `.content` div, increase `padding-left` to `300px`.

Is this page in this repo? If so, I can make the PR. If not, well have to wait the devs.

**Comment by dillonreedy** [comment]
@EdsonAlcala and @angelod1as I'm re-doing the recharts website documentation in Storybook [here](https://dillonreedy.github.io/recharts-storybook/?path=/story/introduction-welcome--page) and I could use help building it out further. I only just started it about a week ago.
