### ISSUE TITLE
Allow passing of downsampling functions.

### ISSUE THREAD

**Issue by cbaker** [recharts/recharts#2473]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Charts provided with a large number of data points have poor performance, a solution to this is to allow us to pass in a function for downsampling that is ran when points are generated internally.

### What does the proposed API look like?
add prop to cartesian charts to specify a downsampling function. 
eg: <LineChart data={data} downsample={points => blah} />

**Comment by timtucker** [comment]
Why not just reduce the size of your data object that you're passing in?

i.e.:
```
data = data.filter((value, index) => { return index % 3 === 0 });
```

**Comment by cbaker** [comment]
> Why not just reduce the size of your data object that you're passing in?
> 
> i.e.:
> 
> ```
> data = data.filter((value, index) => { return index % 3 === 0 });
> ```

The inherent problem with this is that you miss peaks in data that you're trying to get an accurate overview of.
For example, if I have the data set with Y values [1, 2, 2, 6, 8, 2, 2, 8, 7, 2] I'm not going to see peaks in the data. Whereas a proper downsampling algorithm would preserve highs & lows.

**Comment by timtucker** [comment]
The idea of filtering before you pass in your data still holds even if you use a dedicated downsampling algorithm, though.

https://github.com/janjakubnanista/downsample looks like one possible option.

For your example it would just look like:
```
<LineChart data={downsampleAlgorithm(data, numberOfPoints)} />
```

**Comment by cbaker** [comment]
> The idea of filtering before you pass in your data still holds even if you use a dedicated downsampling algorithm, though.
> 
> https://github.com/janjakubnanista/downsample looks like one possible option.
> 
> For your example it would just look like:
> 
> ```
> <LineChart data={downsampleAlgorithm(data, numberOfPoints)} />
> ```

Yes & no. IIRC recharts internally turns them into x&y points which is easier to run an algorithm on than your raw data which is typically an array of objects with properties.

**Comment by cbaker** [comment]
I feel like this is duplicated by #1356
