### ISSUE TITLE
React console warnings 

### ISSUE THREAD

**Issue by annslittleflower** [recharts/recharts#2475]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-mk80m)

### Steps to reproduce
1. Just run the sandbox and check chrome console

### What is expected?
Not getting red console errors 

### What is actually happening?
React does not recognize the `chartHeight` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `chartheight` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

And also few more different errors like this one

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 17.0.1 |
| System | ubuntu 20.04 |
| Browser | Chrome 87.0.4280.141 |

---
Maybe i'm actually doing something wrong, but please help guys, how to get rid of this unwanted errors? Seems like code has somewhere '...props' on DOM element or something like that. Cool and useful package thought. Thanks in advance!

**Comment by ckifer** [comment]
Not sure exactly the errors are happening but it looks like you are defining your props incorrectly.

```jsx
 const legendProps = {
    iconType: "circle",
    content: getLegendContent()
  };
```
should be
```jsx
 const legendProps = {
    iconType: "circle",
    content: getLegendContent
  };
```
without the `()` call to the function. With the parenthesis you are calling the function as soon as you render and not passing any of the required parametersto the `content` prop. This makes the function run in unintended ways without the data it needs. Recharts should make this more visible by "not allowing anything to happen" or throwing an error if it doesn't have the props it needs. Labeling this as an enhancement but your issue should be resolved

**Comment by ckifer** [comment]
Going to close this since this was due to the above  where props are being defined incorrectly
