### ISSUE TITLE
Vertical Legend does not render properly with ResponsiveContainer

### ISSUE THREAD

**Issue by SachaG** [recharts/recharts#248]
See: http://jsfiddle.net/L5ygpk51/

The fact that the legend is absolutely positioned and overlaid on top of the chart also makes it hard to reposition it generally. 

I feel like since it's an HTML element anyway, it might be easier to just keep it in the flow of the document and get rid of the padding at the bottom of the chart? Is there a way to do that?

**Comment by fgiarritiello** [comment]
I'm having the same problem. How was this resolved?
