### ISSUE TITLE
Cannot install because of over-restrictive peer dependencies

### ISSUE THREAD

**Issue by StoneCypher** [recharts/recharts#2482]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://irrelevant](http://irrelevant)

### Steps to reproduce
install react 17.0.1.  attempt to install recharts.

### What is expected?
recharts is installed.

### What is actually happening?
recharts fails on a peer dependency.  recharts has react-smooth as a dependency.  react-smooth is gated to react 15/16 instead of 16/17.

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 17.0.1 |
| System | irrelevant |
| Browser | irrelevant |

---
hyper-vigilant version pinning is bad.  floors are good.  ceilings are not.

**Comment by StoneCypher** [comment]
I don't use `create-react-app` or any other generators.  It's merely a victim.  This will happen with anything offering React >16 or <15 as a peer.  In the latter case, it's correct; in the former case, it isn't.

You can reproduce this simply by installing `typescript`-current (which is at v17) then installing `recharts`-current, or even just the dependency `react-smooth`.

**Comment by moona3k** [comment]
Here is a temporary fix to override the error in `npm install recharts` until recharts peer dependencies are bumped to allow React 17.

In `package.json`, manually add the `recharts` dependency and save.

`"dependencies": {
  "react": "^17.0.1",
  "react-dom": "^17.0.1",
  "recharts": "^2.0.8",
  ...
}`

Delete `node_modules` and `package-lock.json`
Run `npm install --legacy-peer-deps`

Again, this is only a temporary workaround to override the error.
The peer deps should be bumped up.

**Comment by homanp** [comment]
I'm stumbling across this as well, any updates on a fix?

**Comment by StoneCypher** [comment]
I stopped using this library when I realized that they won't bump a version
number to unblock users for weeks

I'm not getting version locked on react over some charts

**Comment by gausie** [comment]
`react-smooth` has now updated to v2 so this should be ready to go

**Comment by gausie** [comment]
@arcthur I think this was fixed in v2.0.9

**Comment by miles-1** [comment]
@moona3k's suggestion worked for me, but of course, it would be nice to not have to downgrade React from 18.0.0 to 17.0.1. Are there any plans to update things so using the latest React version will not be restricted?

**Comment by ckifer** [comment]
Recharts is now able to be used with React 16, 17, and 18. Closing this as completed
