### ISSUE TITLE
Please update react-resize-detector to the last version 6.6.1, there is an important fix

### ISSUE THREAD

**Issue by dmitresco** [recharts/recharts#2486]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/maslianok/react-resize-detector/issues/141](https://github.com/maslianok/react-resize-detector/issues/141)

### Steps to reproduce
Please take a look on the `react-resize-detector` issue linked, there is quite clear obvious case explained

### What is expected?
A chart renders correctly

### What is actually happening?
A chart crushes with a runtime error, causing a website crush

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 17.0.1 |
| System | iOS 13 |
| Browser | Safari |

---
The issue was already fixed with the new release. Please update the package to the `6.6.1` version
https://github.com/maslianok/react-resize-detector/issues/141

**Comment by Semigradsky** [comment]
@dmitresco version is not fixed, just update your dependencies
https://github.com/recharts/recharts/blob/c80648534ffabf0a85807f418b42ee3d52aea870/package.json#L65

**Comment by ckifer** [comment]
at 7.1.2 now, resolving this issue
