### ISSUE TITLE
Missing "data" prop on "Area" component, but chart still works (v2.x and v1.8.x)

### ISSUE THREAD

**Issue by bennettdams** [recharts/recharts#2487]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-composed-chart-ey71i?file=/src/App.tsx:1476-1726)

### What is expected?
The `Area` component has no `data` prop. As you can see in the example, the chart still works when using that prop nevertheless.

### What is actually happening?
I want to dynamically show areas in my composed chart. For that I'm splitting up the data and "map" in the render:

**Example data**
```tsx
const areas = [
  {
    id: "area1",
    data: [
      { ts: 1, value: 5 },
      { ts: 2, value: 10 }
    ]
  },
  {
    id: "area2",
    data: [
      { ts: 1, value: 9 },
      { ts: 2, value: 16 }
    ]
  }
];
```

**Render**
```tsx
<ComposedChart ...>
  ...
  <XAxis dataKey="ts" type="number" />
  ...
  {areas.map((area) => (
    <Area
      // @ts-ignore
      data={area.data}
      dataKey="value"
      key={area.id}
      ...
    />
  ))}
  ...
</ComposedChart>
```
This works perfectly fine and the chart renders correctly, but TypeScript says there's no `data` prop on an `Area` component (hence the `// @ts-ignore` in my example).

**Is this just a missing type definition or is this somehow working because of other circumstances?**

Please see my CodeSandbox for a working example.

---

This is also the case for earlier versions (v1.8.x).

---

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | v17.0.1 |
| System | any |
| Browser | any |

**Comment by ckifer** [comment]
Fixed in #3443

Will be released in next minor version
