### ISSUE TITLE
Warning Error Message when using ResponsiveContainer

### ISSUE THREAD

**Issue by 10n6** [recharts/recharts#249]
Hi,

I'm using the ResponsiveContainer around my area chart and I get this:

> Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.

However if I remove the ResponsiveContainer wrap the error goes away. Any Idea whay I should be getting this. Could well be user error which I apologise for in advance if that's the case. 

Setup is as follows:

`import {  ResponsiveContainer, XAxis, Area, YAxis, CartesianGrid, Tooltip, Legend, AreaChart } from 'recharts';

...

render () {

```
return (
    <div style={{height: '250px'}}>
    <ResponsiveContainer>
    <AreaChart width={500} height={300} data={data} margin={{top: 5, right: 20, left: 20, bottom: 5}}>
        <defs>
            <linearGradient id="colorUv" x1="0" y1="0" x2="0" y2="1">
              <stop offset="5%" stopColor="#8884d8" stopOpacity={0.5}/>
              <stop offset="95%" stopColor="#8884d8" stopOpacity={0}/>
            </linearGradient>
            <linearGradient id="colorPv" x1="0" y1="0" x2="0" y2="1">
              <stop offset="5%" stopColor="#82ca9d" stopOpacity={0.5}/>
              <stop offset="95%" stopColor="#82ca9d" stopOpacity={0}/>
            </linearGradient>
        </defs>
       <XAxis dataKey="name" axisLine={false} tickLine={false}/>


       <CartesianGrid strokeDasharray="3 3" vertical={false} horizontal={false}/>
       <Tooltip/>
        <Area type="linear" dataKey="uv" stroke="#8884d8" fillOpacity={1} fill="url(#colorUv)" activeDot={{r: 8}}/>
        <Area type="linear" dataKey="pv" stroke="#82ca9d" fillOpacity={1} fill="url(#colorPv)" activeDot={{r: 8}} />

    </AreaChart>
    </ResponsiveContainer>
    </div>
);
```

  }
`

**Comment by xile611** [comment]
@10n6 It's a bug of react-container-dimensions. I have create an [issue](https://github.com/okonet/react-container-dimensions/issues/7) in react-container-dimensions.

**Comment by okonet** [comment]
Please see this discussion: https://github.com/okonet/react-container-dimensions/issues/7#issuecomment-240769079

**Comment by xile611** [comment]
We use `react-resize-detector` to refactor ResponsiveContainer. I think this has been fixed.
