### ISSUE TITLE
Improve mobile view of documents site 

### ISSUE THREAD

**Issue by danielo515** [recharts/recharts#2495]
- [X] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://recharts.org](https://recharts.org)

### Steps to reproduce
Visit the docs from a mobile phone 

### What is expected?
To hide some elements like the data panel

### What is actually happening?
Everything is just scrambled 

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 16.X |
| System | Android  |
| Browser | Chrome |

---
The mobile version of the docs is unusable.
The data is more visible than the charts themselves. The data in mobile is not that critical to show, please consider hiding it

**Comment by ckifer** [comment]
There is an open issue in the recharts.org repo for this. Feel free to contribute
