### ISSUE TITLE
A problem with scrollbar on the site recharts.org

### ISSUE THREAD

**Issue by Litvinov-Serge** [recharts/recharts#2497]
A site scrollbar crosses over the content: https://recharts.org/en-US/api/Tooltip
The problem appears in Chrome (88.0.4324.190) both on Windows 10 and Linux Ubuntu 20.04.
(I'm not sure if I should post this issue here, but I did not find a feedback form on the site).
![recharts](https://user-images.githubusercontent.com/36899925/111148329-8ce2d380-859c-11eb-8d3f-ddba32af4d0c.png)

**Comment by stevenbixby** [comment]
Same here -- Ubuntu 20.04, Chrome 89.0.4389.82  and Firefox 86.0

**Comment by ckifer** [comment]
Issue should be resolved - please create a new issue over at https://github.com/recharts/recharts.org if it persists
