### ISSUE TITLE
Implement axes labels

### ISSUE THREAD

**Issue by Cloudo** [recharts/recharts#25]
Seems like there is now way to set label for axis, which logically would mean 'units of measurement'.
Example:
http://c3js.org/samples/axes_label.html

**Comment by xile611** [comment]
Have implemented in v0.7.0.
<http://recharts.org/examples#ComposedChartWithAxisLabels>

**Comment by Cloudo** [comment]
Thanks a lot!

**Comment by andy-d** [comment]
I don't see that among the examples and I'm not sure how to implement units for the axes, can you please help? Thanks!
