### ISSUE TITLE
site recharts.org broken, CSS for API part of https://recharts.org/, 

### ISSUE THREAD

**Issue by DmitriyKochergin** [recharts/recharts#2501]
incorrect padding-left for ".page>.content", can't read API info

.page>.content {
    min-width: 1200px;
    padding-left: 260px; --------> 290px
}

**Comment by rjerue** [comment]
There's a fix here that's been open for... awhile... https://github.com/recharts/recharts.org/pull/161

This has been driving me so nuts I also put up a mirror with the fix here: https://recharts-org-rjerue.vercel.app/en-US/
