### ISSUE TITLE
Scatter Chart example on Website is incorrect

### ISSUE THREAD

**Issue by b-steel** [recharts/recharts#2502]
## Do you want to request a feature or report a bug?
Report a Bug
## What is the current behavior?
The scatter chart on the website [here](http://recharts.org/en-US/api/ScatterChart) is missing a prop on the X axis.  There should be a type='number' prop on the Xaxis component.  If you copy/paste the code from the demo on the website the chart does not look the same at all (since XAxis default type is 'category').

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via 
[Expo Snack](https://snack.expo.io/@b_steel/recharts-scatter-chart)  You can toggle the 'which' constant to show the two versions. 

## What is the expected behavior?
Copy/Pasting the code from the example reproduces the same graph that is shown in the example

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Using recharts 2.0.8 on expo SDK 40.0.0 for the demo. 
I have not used prior versions of recharts, unsure if the Xaxis.type default has changed at some point

**Comment by ckifer** [comment]
Looks like this is fixed
http://recharts.org/en-US/api/ScatterChart
https://codesandbox.io/s/simple-line-chart-forked-9b63x2?file=/src/App.tsx
