### ISSUE TITLE
Can't put a bar over the other (not stack)

### ISSUE THREAD

**Issue by angelod1as** [recharts/recharts#2503]
- [X] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
N/A

### Steps to reproduce
N/A

### What is expected?
I should be able to put two bars one in front of the other, not stacked nor side by side. The image below illustrates it:

![image](https://user-images.githubusercontent.com/13950513/112066167-a491fd00-8b44-11eb-93bf-d86868d2d7a7.png)

The yellow bar is the bar in front. The green bar is behind it, not stacked. It can also be a `background` but I couldn't find how to apply height to the background.

You can see it's possible for the green bar to not appear after all, if the value of yellow is equal or bigger.

### What is actually happening?
I can't find a way to do the described above.

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 16.12.0 |
| System | Pop!_OS 20.04 LTS x86_64 |
| Browser | Chrome 89.0.4389.90 |

**Comment by jacobedawson** [comment]
You can do this, here's a full example:

```
// A single point of data, fill the array with more to see it in action
const data = [
  {
    name: "7.5%",
    volume: 5000,
    borrowed: 4000,
    tick: 7.5,
  },
]

    <BarChart data={data}>
          <CartesianGrid />
          <XAxis dataKey="name" xAxisId={1} /> // note the axis id
          <XAxis dataKey="borrowed" xAxisId={0} hide /> // hidden x axis
          <YAxis />
          <Tooltip />
          <Legend />
          {/* in order of appearance in z-index */}
          <Bar xAxisId={1} dataKey="volume" fill="#339EA7" barSize={30} /> // each bar corresponds to an axis
          <Bar xAxisId={0} dataKey="borrowed" fill="#00FFFF" barSize={30} /> // they will now overlap
        </BarChart>
```

**Comment by nyanyani** [comment]
@jacobedawson 
> You can do this, here's a full example:
> ```
> ...
>           <XAxis dataKey="name" xAxisId={1} /> // note the axis id
>           <XAxis dataKey="borrowed" xAxisId={0} hide /> // hidden x axis\
> ...
> ```

Nice example, but the first `<XAxis />` should have a `xAxisId={0}` , and the second should have `xAxisId={1}`.
See https://github.com/recharts/recharts/issues/1476#issuecomment-1028152619.
