### ISSUE TITLE
ReferenceLine with segment not drawing correctly when using BarChart 

### ISSUE THREAD

**Issue by lhkraus** [recharts/recharts#2506]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/musing-ptolemy-5i9vs?file=/src/App.js)

### Steps to reproduce
In a BarChart using strings as the XAxis value, create a ReferenceLine using the segment prop.

### What is expected?
To the reference line draws at the entire XAxis.

### What is actually happening?
The reference line stops drawing at the beggining of the last XAxis point configured on the segment prop.

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 17.0.2 |
| System | any |
| Browser | any |

**Comment by ckotyan** [comment]
I too stumbled upon this one and was going crazy trying to get it working. Is there a work around for this?

**Comment by ckotyan** [comment]
> I too stumbled upon this one and was going crazy trying to get it working. Is there a work around for this?
> using position={'end'} on the ReferenceLine does not work either.

I found the the reason why this is happening. There is a line of code in CartesianUtils.js that is not passing the position attribute while calculating the endpoints for the line. I can fork a PR for this change if that is preferred.

**Comment by MLazarevic36** [comment]
The issue still persists, does anyone have solution?

**Comment by lukask-proxora** [comment]
@MLazarevic36 Does the issue still persist with the current version(2.4.3)?
I just forked the original code box and updated the version to 2.4.3 and it seems to work as expected now: https://codesandbox.io/s/modest-wind-56086u
