### ISSUE TITLE
Brush component support for mobile devices (small touchscreen) 

### ISSUE THREAD

**Issue by vipertechofficial** [recharts/recharts#2510]
- [X] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The problem solved by this feature is a better support for mobile devices when interacting with the Brush component, the left and right resizeable svg component are too small to be used correctly from a touchscreen.

### What does the proposed API look like?
<Brush forMobile/>

**Comment by shahinlotfi** [comment]
You could try setting a larger `travellerWidth` for mobile devices.

**Comment by vipertechofficial** [comment]
> You could try setting a larger `travellerWidth` for mobile devices.
> ![mobile-brush](https://user-images.githubusercontent.com/1726765/114145531-cba74780-9916-11eb-9317-1c54ede300e2.png)

Of course! Thanks, my bad, I didn't read the API methodically, meanwhile I was thinking about an overlay.
Well, for now it's perfectly fine, no one needs an overlay.
