### ISSUE TITLE
Please tag v2.0.9

### ISSUE THREAD

**Issue by stephencattaneo** [recharts/recharts#2517]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/recharts/recharts/tags](https://github.com/recharts/recharts/tags)

### Steps to reproduce
n/a

### What is expected?
(Version should be 2.0.9 but thats not an option in `recharts-issue-helper`.)

I was very confused for a bit when I realized my install of recharts was running an unpublished version (2.0.9); The version has been published, but the requisite git bookkeeping was not. Turns out a handful of days ago 6c692d39 was published as 2.0.9. Please tag 6c692d39 as v2.0.9

### What is actually happening?
github lists 2.0.8 as latest release

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | n/a |
| System | n/a |
| Browser | n/a |

**Comment by hblunck** [comment]
It appears to me (not a JS expert) that this has consequences in a number of areas. An application where I was using the UMD build was now failing, because [https://unpkg.com/recharts/umd/Recharts.min.js](https://unpkg.com/recharts/umd/Recharts.min.js) currently gives a 404 error.

**Comment by ckifer** [comment]
Resolving this as completed
