### ISSUE TITLE
Display x axis (date) ticks with missing data

### ISSUE THREAD

**Issue by kaiser-naren** [recharts/recharts#252]
Hello,

I am trying to create a time series chart for a date range which has data missing for a few dates in range.  But I am only seeing labels in the x-axis which have data for the y-axis, even though I have manually generated ticks for the missing data.  I have an example here:

http://jsfiddle.net/t9cpxoc7/

I have a 48 day range and I have data for only 6 of the days.  I can see only 6 points corresponding to 6 days which have data.  What must I do to get the chart to show all 48 days on the axis, with 0 being the default value for missing data?

Thanks,
Naren.

**Comment by jamesremuscat** [comment]
This relates to https://github.com/recharts/recharts/issues/63 - the last comment on that thread describes  a workaround.

It would be nice if it were possible to have first-class date support in Recharts though!

**Comment by kaiser-naren** [comment]
I did see that issue, but I thought Recharts would have added that feature by now.  I did create a jsfiddle with the workaround, in case anyone runs into the same issue again:

http://jsfiddle.net/1vzc18qt/

**Comment by TooTallNate** [comment]
👍 It would be really nice if Recharts implemented `timeScale` natively

**Comment by imWildCat** [comment]
Yes. Currently it looks silly when there is no data point right at the tick:

![image](https://user-images.githubusercontent.com/2396817/34445643-070d2b60-ec8a-11e7-903b-5c14f60f03a6.png)
