### ISSUE TITLE
Line type definition is missing label property.

### ISSUE THREAD

**Issue by mpycio** [recharts/recharts#2520]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-n8nks?file=/src/index.tsx)

### Steps to reproduce
Looking at the sandbox one can clearly see <Line /> component having an error in line 43 "Property 'label' does not exist on type..." 

### What is expected?
I expect to be able to define a label for the line.

### What is actually happening?
Compilation error.

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 17.0.2 |
| System | OSX |
| Browser | any |

**Comment by trailblazer2006** [comment]
v2.0.9 still have this issue

**Comment by trailblazer2006** [comment]
Guys, any comments?

**Comment by chiester** [comment]
+1

**Comment by chiester** [comment]
@middiu What would `labelOptions` be in your workaround above?

**Comment by middiu** [comment]
> @middiu What would `labelOptions` be in your workaround above?

Just a label string, for example:
````
<Line
	key={props.componentId + '-line-' + idx}
	type="monotone"
	dataKey={b}
	stroke={props.chartInfo.colors[idx]}
	activeDot={{ r: 8 }}
	isAnimationActive={false}
	strokeWidth={props.reportCompChartComps.lineSize ?? 1}
	{...{ label: 'test label' }}
/>
````

you can ignore the rest of the properties
