### ISSUE TITLE
LineChart inside of ResponsiveContainer doesn't work

### ISSUE THREAD

**Issue by williamsgobi** [recharts/recharts#2523]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/responsive-container-recharts-zwu2s?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Open in small screens lower than 730px, the Graph inside of ResponsiveContainer isn't showing, but, if you remove the ResponsiveContainer, the graph is show

### What is expected?
I expect the same behavior as on large screen, where the graph is shown

### What is actually happening?
The graph doesnt show at screen

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 17.0.2 |
| System | Windows 10 OS Version 1909 |
| Browser | Google Chrome: 89.0.4389.114 |

---
The version of recharts is 2.0.9, but it isn't in the list to choose.

**Comment by linliTian** [comment]
Not works for the BarCharts either. 
 
[reproduce it](https://codesandbox.io/s/simple-bar-chart-forked-31evm?file=/src/App.tsx)

**Comment by reinos** [comment]
That's because you have to set the `height`

```
<ResponsiveContainer height={300}>
...
</ResponsiveContainer>
```

@linliTian in your case you can set the height to `100vh` 

```
<ResponsiveContainer height="100vh" width="100%">
...
</ResponsiveContainer>
```

**Comment by alex-page** [comment]
Setting a `height` worked for me. I was passing `300px` and changed it to `300`. This issue can probably be closed with some documentation.
