### ISSUE TITLE
Unable to create a floating Bar Chart with a stackId

### ISSUE THREAD

**Issue by Fullchee** [recharts/recharts#2524]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stacked-bar-chart-forked-x2574?file=/src/App.tsx)

### Steps to reproduce
1. Create a BarChart where one Bar has a stackId
2. Have the data for another chart be a range (eg: [3, 4]) instead of a number

### What is expected?
I expect that Column 2 should have a floating bar from 6 to 10

### What is actually happening?
Column 2 takes up the whole height of the chart

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 17.0.1 |
| System | MacOS Big Sur 11.2.3 (20D91) |
| Browser | Chrome Version 89.0.4389.114 (Official Build) (x86_64) |

---
I posted some more info on StackOverflow

https://stackoverflow.com/questions/67039510/recharts-floating-bar-chart-when-another-bar-has-a-stackid

**Comment by piaseckimaks** [comment]
I find some workaround for you. I edited your "codesandbox". I hope that this can be useful for you. 

https://codesandbox.io/s/stacked-bar-chart-forked-gxlgu?file=/src/App.tsx

**Comment by Fullchee** [comment]
@piaseckimaks Thank you!
I didn't think of creating a transparent bar underneath!

Does recharts want to support ranges though with stackIds?

I might be able to take a look.

Do you know which files I should look at?

**Comment by piaseckimaks** [comment]
Sorry but I'm not from rechart team.
I just casualy looking in the issue sections of open source projects.

**Comment by phattnh** [comment]
Hi, you shouldn't use this trick because the date will show not correct by YAxis
You can reference my codes. Here recharts supplied for you data format like 
```
[{ name: 'a', value: 12 }]
[{ name: 'a', value: [5, 12] }]
```
then you need config domain for YAxis 
Ex: ` domain={[90, 100]}`

<img width="759" alt="image" src="https://user-images.githubusercontent.com/39791881/204969874-1640530d-5d8b-4e9b-9afb-a2aeee12f6e3.png">


type IDataItemFromAPI = {
  date: string;
  min: number;
  max: number;
};

type ChartItem = {
  timestamp: number;
  dateFormatted: string;
  range: [number, number];
} & IDataItemFromAPI;

const data: IDataItemFromAPI[] = [
  {
    date: '2022-08-31T17:00:00.000Z',
    min: 91,
    max: 95,
  },
  {
    date: '2022-09-01T17:00:00.000Z',
    min: 93,
    max: 94,
  },
  {
    date: '2022-09-02T17:00:00.000Z',
    min: 92,
    max: 94,
  },
  {
    date: '2022-09-03T17:00:00.000Z',
    min: 91,
    max: 95,
  },
  {
    date: '2022-09-04T17:00:00.000Z',
    min: 93,
    max: 95,
  },
  {
    date: '2022-09-05T17:00:00.000Z',
    min: 92,
    max: 95,
  },
  {
    date: '2022-09-06T17:00:00.000Z',
    min: 91,
    max: 95,
  },
];

const BloodOxygenChart = () => {
  const { dataResource, dateTicks, dateFormatter, dateDomain } = React.useMemo(() => {
    const dates: string[] = data.map((d) => d.date);
    const minDate: string = min(...dates);
    const maxDate: string = max(...dates);
    const startDate = new Date(minDate);
    const endDate = new Date(maxDate);
    const domain = [startDate.getTime(), endDate.getTime()];
    const formatter = (value: any, index: number) => {
      const result = formatDateString(new Date(value), 'DD/MM/YY');
      return result;
    };
    const resource: ChartItem[] = data.map((d) => ({
      ...d,
      timestamp: new Date(d.date).getTime(),
      dateFormatted: formatDateString(new Date(d.date), 'DD/MM/YY'),
      range: [d.min, d.max],
    }));
    return {
      dataResource: resource,
      startDate,
      endDate,
      dateDomain: domain,
      dateFormatter: formatter,
      dateTicks: [resource[0].timestamp, resource[resource.length - 1].timestamp],
    };
  }, []);
  return (
    <BarChart width={730} height={250} data={dataResource} margin={{ top: 15, right: 30, left: 20, bottom: 5 }}>
      <XAxis
        dataKey="timestamp"
        type="number"
        scale="time"
        ticks={dateTicks}
        tickFormatter={dateFormatter}
        domain={dateDomain}
        padding={{ left: 50, right: 50 }}
      />
      <YAxis dataKey="range" domain={[90, 100]} hide />
      <Tooltip
        labelFormatter={(label, payload) => `Date: ${formatDateString(label, DateConstant.DATE.DATE_SLASH_SHORT)}`}
        formatter={([minValue, maxValue]: [number, number], name) => [`${minValue}% - ${maxValue}%`, 'Percent']}
      />
      <Bar dataKey="range" fill={GREEN_COLOR} radius={[10, 10, 10, 10]} />
      <Legend formatter={(value, entry, index) => 'Blood Oxygen Chart'} />
    </BarChart>
  );
};

export default React.memo(BloodOxygenChart);

**Comment by abhishekram404** [comment]
@phattnh Thank you so much for this answer. It worked for me.
