### ISSUE TITLE
Line component color can't be changed with css

### ISSUE THREAD

**Issue by danielbahesage** [recharts/recharts#2526]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-line-color-bug-9z2wd)

### Steps to reproduce
1 Create a chart with a "Line" Component
2 Create a css class with a stroke color different to default line color
3 Delete property stroke in Line Component
4 Add property className with the name of the css class you've created at step 2

### What is expected?
To change the color to the css color

### What is actually happening?
it's ignoring the css class and use default color

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | react 17.0.1 |
| System | windows |
| Browser | All |

**Comment by ManaliKatkar** [comment]
Please find below available props to Line Chart. So bcoz of that u r not able to apply className to stroke.
defaultProps: {
        xAxisId: number;
        yAxisId: number;
        connectNulls: boolean;
        activeDot: boolean;
        dot: boolean;
        legendType: string;
        stroke: string;
        strokeWidth: number;
        fill: string;
        points: LinePointItem[];
        isAnimationActive: boolean;
        animateNewValues: boolean;
        animationBegin: number;
        animationDuration: number;
        animationEasing: string;
        hide: boolean;
    };
