### ISSUE TITLE
ReferenceArea does not work with x="hh:mm:ss"

### ISSUE THREAD

**Issue by phileba** [recharts/recharts#2529]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-basic-referencearea-forked-gyz4o)

### Steps to reproduce
Open this link above, you will see the following does not work:
```
<ReferenceArea x1="00:00:05" x2="00:00:20" label="an important period" />
```
It works if x has value is number or normal string likes "abc"... 

### What is expected?
I want it to work as expected.

### What is actually happening?
The `ReferenceArea` does not work if `x1="00:00:05"`

| Environment | Info |
|---|---|
| Recharts | v1.6.2 |
| React | 15.4.2 |
| System | macOS Big Sur 11.1 |
| Browser | Chrome version 90.0.4430.85 |

**Comment by phileba** [comment]
I found the root cause is the data has duplicate field time with value `00:00:00`
```
{
    cpu: 47.65,
    time: "00:00:00"
  },
  {
    cpu: 100,
    time: "00:00:00"
  },
```
does it an issue and need to be fixed?

**Comment by master117** [comment]
Yes, all datapoints need to be unique for referencearea to work.
