### ISSUE TITLE
Having a maxBarSize prop would be useful

### ISSUE THREAD

**Issue by SachaG** [recharts/recharts#253]
I like the fact that bar sizes adapt to the number of bars in a chart, but bars can become too wide when you have only have a few bars.

I could set barSize but then I would have the opposite problem, bars become too wide when you have *a lot* of bars. 

Setting a `maxBarSize` prop would mean the bar size can adapt while being capped at a certain width.

**Comment by SachaG** [comment]
Awesome, thanks so much for adding this!

**Comment by ArQuel** [comment]
Hey, how u use it ? maxBarSize doesn't change anything for me

**Comment by TooMuchLagWillKillYou** [comment]
> Hey, how u use it ? maxBarSize doesn't change anything for me

I had the same issue then I noticed that in the <BarChart /> component I had the barSize prop enabled, if you don't set this prop you should be able to use the maxBarSize in the <Bar /> component.
