### ISSUE TITLE
How to move YAxis content above bar lines

### ISSUE THREAD

**Issue by narayan-khanna** [recharts/recharts#2530]
I've created like this : 
![image](https://user-images.githubusercontent.com/19723905/116500628-8bf7ce00-a8cc-11eb-9891-9b69d508dfa3.png)

I want like this 

![image](https://user-images.githubusercontent.com/19723905/116500849-0a547000-a8cd-11eb-8d78-f931f793ec33.png)

I want text to be above the bar lines 

Can anyone help ?

Code I'm using :

  ```
 <BarChart
          data={props.data}
          layout="vertical"
          barSize={40}
          width={1400}
          height={300}
          margin={{ bottom: 5, left: 40, right: 30, top: 5 }}
        >
          <YAxis type="category" width={50} dataKey="location" axisLine={false} />
          <XAxis type="number" hide />

          <Bar radius={[8,8, 8, 8]} dataKey="hits" fill="#0A76CB" label={<CustomizedLabel />} />
          <Tooltip cursor={false} />
        </BarChart>
```

**Comment by code-scavenger-007** [comment]
Code I'm using 

<BarChart
          data={data}
          layout="vertical"
          barSize={40}
          width={1400}
          height={300}
          margin={{ bottom: 5, left: 40, right: 30, top: 5 }}
        >
          <YAxis type="category" width={50} dataKey="location" axisLine={false} />
          <XAxis type="number" hide />

          <Bar radius={[8,8, 8, 8]} dataKey="hits" fill="#0A76CB" label={<CustomizedLabel />} />
          <Tooltip cursor={false} />
        </BarChart>

**Comment by code-scavenger-007** [comment]
- [ ] @andy128k @maiis @qnighy @dlindahl   can anyone look into this

**Comment by qnighy** [comment]
Please don't spam me, a mere one-line contributor. And I guess you're multiposting the same problem [here](https://stackoverflow.com/questions/67317422/rechart-xaxis-and-yaxis-text-in-react)? Then I think you should just be a bit more patient to wait for an answer there (but the maintainer may have a different opinion, I don't know).

**Comment by code-scavenger-007** [comment]
@qnighy : There is always an option of ignoring it don't you feel that ?
Your name is popping out from the list that's why I added you.

**Comment by ckifer** [comment]
This is possible with individual BarCharts and your own code for the labels. Otherwise this is a feature request
