### ISSUE TITLE
Cell element NaN console warnings 

### ISSUE THREAD

**Issue by lidkxx** [recharts/recharts#2532]
In our React app we're drawing a chart using [Scatter](https://recharts.org/en-US/api/Scatter) component. One of the Scatter cells needs to be coloured differently to show which percentile of the data the corresponding data item falls in.

Demo: https://codesandbox.io/s/hungry-mendeleev-kyp6u?file=/src/App.js

The Cell element keeps giving the below console warnings for `x`, `y`, `width` and `height` Cell attributes.

Warning: Received NaN for the `x` attribute. If this is expected, cast the value to a string.
    at path  
    at Symbols  
    at g  
    at Layer
    at g
    at Layer
    at Animate
    at g
    at Layer
    at g
    at Layer 
    at Scatter
    at svg
    at Surface
    at div
    at CategoricalChartWrapper
    at div
    at ResizeDetector
    at ResponsiveContainer

Currently my workaround is to pass all of these props as zeroes. However it looks like this could be fixed in the library?

Let me know if you need any more details.

Recharts: v2.0.9
Chrome: v90.0.4430.93
React: v17.0.2

**Comment by TakanashiOuken** [comment]
Same issue here. Can you show how you walked around?

**Comment by lidkxx** [comment]
Sure, I am just creating some dummy props like so:

```
const cellDummyProps = {
  width: 0,
  height: 0,
  x: 0,
  y: 0,
};
```

and then in the `<Cell>` element:

```
<Cell
//existing code
{...cellDummyProps}
/>
```

Hope it helps!

**Comment by havit1** [comment]
Same here. Using Sankey diagram with custom Link and Node components and for some datasets this error appears and it breaks the diagram. For some reason, in my case, "y" property that is passed to custom Node is NaN and "targetY" for custom Link element is NaN as well

**Comment by ckifer** [comment]
This should be resolved
