### ISSUE TITLE
PieChart vs Pie onClick events

### ISSUE THREAD

**Issue by tobia** [recharts/recharts#254]
I noticed that PieChart's onClick attribute works as expected, but Pie's onClick does not seem to be called.

I'm just wondering if this is a bug in the documentation (which lists onClick along with a number of other events for the Pie object) or in the implementation.

It could be an issue for other events and other chart types as well. (I can check all combinations if that would be useful.)

**Comment by xile611** [comment]
@tobia The `onClick` event of `Pie` works. But It will be overwrote by `onClick` of `PieChart`. So It seems strange now.
