### ISSUE TITLE
LabelList misses `formatter`-property definition

### ISSUE THREAD

**Issue by uncaught** [recharts/recharts#2540]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/recharts/recharts](https://github.com/recharts/recharts)

### Steps to reproduce

```js
import {LabelList} from 'recharts';
<LabelList formatter={() => ''}/>;
```

### What is expected?
No typescript error.

### What is actually happening?
Typescript error is displayed: "Property 'formatter' does not exist on type..."

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | react@17.0.2 |
| System | Typescript 4.2.4 |
| Browser | Node 14 |

---
According to the [documentation](https://recharts.org/en-US/api/LabelList#formatter) the property should exist.

**Comment by Pawel-Janik** [comment]
Hey, this has been fixed in v.2.3.2.

**Comment by ckifer** [comment]
Closing as completed
