### ISSUE TITLE
Unble to x-axis bar value if garph with is less than 287px;

### ISSUE THREAD

**Issue by govindba** [recharts/recharts#2542]
The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.

I am adding date value in the x-axis and showing 3 bars upfront,

but when I am reducing graph width below 287px, one of the x-axis value gets hidden.

<img width="304" alt="Screenshot 2021-05-13 at 11 49 24 AM" src="https://user-images.githubusercontent.com/84119251/118086271-4dd8cf00-b3e1-11eb-8d42-304b8a7e863c.png">

**Comment by krnlde** [comment]
Shorten your Date then. What do you expect? Overlapping Dates?

**Comment by ckifer** [comment]
Going to close this as stale/unplanned. 

We're working on making ticks better, but as stated above once the graph is small the ticks are hidden. You can rotate the ticks to show more
