### ISSUE TITLE
Allow axis units to be positioned

### ISSUE THREAD

**Issue by amyb-hiveit** [recharts/recharts#2544]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently units are shown after the value, this works for things like percentages but is wrong for some currencies, for example 100£ should be displayed as £100.

### What does the proposed API look like?
```
<XAxis unitPosition="..." />

interface XAxis {
  unitPosition "start" | "end";
}
```

**Comment by krnlde** [comment]
How about using a custom formatter that solves it how you want?
```tsx
<XAxis dataKey="someKey" tickFormatter={(label: number) => formatCurrency(label)} />
```

**Comment by amyb-hiveit** [comment]
That works, thanks @krnlde!
