### ISSUE TITLE
Mouse enter event not triggering on Line Chart

### ISSUE THREAD

**Issue by ritwikvd** [recharts/recharts#2546]
## Do you want to request a feature or report a bug?

Bug

## What is the current behavior?

mouse enter not working for line charts

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

https://codesandbox.io/s/synchronized-line-charts-forked-xvqpl?file=/src/App.tsx

event handlers have been added to LineChart component that log to console.

## What is the expected behavior?

mouse enter should work

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

2.0.6 and Latest. Not sure.

**Comment by Harukisatoh** [comment]
I'm having this bug as well, but for me sometimes it works, and I don't know why. I'd appreciate if this bug get fixed

**Comment by ckifer** [comment]
Going to close this as stale. It's difficult because lines are small targets. OnMouseMove of the chart might be a better bet
