### ISSUE TITLE
Error after import recharts

### ISSUE THREAD

**Issue by ahmedch1** [recharts/recharts#2548]
Hello 
After I have installed recharts  and imported it 
`import {PieChart,Pie,Sector,Cell} from "recharts";`
, I got this problem
Failed to compile 
```
./node_modules/recharts/es6/index.js
Module not found: Can't resolve 'C:\lab\ProjectPath\node_modules\react-scripts\node_modules\babel-loader\lib\index.js' in 'C:\lab\ProjectPath'
```

**Comment by brendonco** [comment]
Need more information.  I'm guessing you might forgot to install react-scripts in your project.

**Comment by ckifer** [comment]
Going to close this as not enough information, please try again with most recent version of recharts
