### ISSUE TITLE
change drop down line thickness and other attributes

### ISSUE THREAD

**Issue by kaldown** [recharts/recharts#2554]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Want to have control over the drop down line. Make it blue and thick

### What does the proposed API look like?
downLineWidth= 8
for example

**Comment by ckifer** [comment]
Going to close this as stale, it isn't clear what is being asked here
