### ISSUE TITLE
Can't use a ForEach (simple returns a map over data with render props) component to render Cells in the PieChart

### ISSUE THREAD

**Issue by vidjuheffex** [recharts/recharts#2555]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pie-chart-with-customized-label-forked-uxp0y?file=/src/App.tsx)

### Steps to reproduce
introduce a functional component to return the mapped array

### What is expected?
at the ends of the day [Cell, Cell, Cell] should end up the direct child with the functional component (containing no JSX, falling away)

### What is actually happening?
no idea, but it breaks the render and no Cells render at all

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 17.0.1 |
| System | windows 10 |
| Browser | edge chromium |

**Comment by ckifer** [comment]
This is related to some other issues regarding rendering components in custom component wrappers. This is being worked on in v3, going to close this one as a duplicate for now
