### ISSUE TITLE
ResponsiveContainer with aspect only shrinks, never expands

### ISSUE THREAD

**Issue by tobia** [recharts/recharts#256]
Using a ResponsiveContainer with aspect (and no other attribute) has a bug, wherein its width and height shrink as you shrink the window, but do not expand as you expand the window.

I fixed it by changing the following code:

    if (aspect && aspect > 0) {
      // Preserve the desired aspect ratio
      if (calculatedHeight > 0 &&
          (calculatedWidth === 0 || calculatedWidth / calculatedHeight > aspect)) {
        calculatedWidth = calculatedHeight * aspect;
      } else if (calculatedHeight === 0 || calculatedWidth / calculatedHeight < aspect) {
        calculatedHeight = calculatedWidth / aspect;
      }
    }

into just this:

    if (aspect && aspect > 0) {
      // Preserve the desired aspect ratio
      calculatedHeight = calculatedWidth / aspect;
    }

I think this makes sense: if you specify aspect, you want your height to depend on the container's width, and that's it. 

What do you think?

**Comment by xile611** [comment]
@tobia  If just so, the height of chart may exceed the boundary of container node.

**Comment by tobia** [comment]
Maybe we mean different things, but usually in a "responsive" layout, such as the widely used Twitter Bootstrap library, the width is fixed (either the device width or a fraction of it, say 3/12) and the height is free.

**Comment by xile611** [comment]
@nickpalmer Any thoughts?

**Comment by techniq** [comment]
I'm running into this as well and support @tobia's proposal (only affect the height)

**Comment by xile611** [comment]
Yeah, In most case, we just want the height to fit the width.
