### ISSUE TITLE
Cannot read property 'parse' of undefined in LineChart

### ISSUE THREAD

**Issue by taily-khucnaykhongquantrong** [recharts/recharts#2561]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-3gy24?file=/src/index.js)

### Steps to reproduce
- Using LineChart
- Using Vite to build project.

### What is expected?
- Chart should be rendered.

### What is actually happening?
- App crashed with error message: "Cannot read property 'parse' of undefined" from production codes.

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | v17.0.1 |
| System | Linux |
| Browser | Microsoft Edge (Chromnium Based) |

---
It works fine on local, no error thrown. It's only happened on Production. I cannot provide you the URL of this app because it's a secret domain.

**Comment by tranthaison1231** [comment]
I have same error like you also using Vite to build project

**Comment by tranthaison1231** [comment]
You can add this script above the body to bypass.

```
<script>
    if (require === undefined) var require = {}
    if (exports === undefined) var exports = {}
  </script>
```

**Comment by sunilhari9** [comment]
Any solution fo this?

**Comment by young666** [comment]
> You can add this script above the body to bypass.
> 
> ```
> <script>
>     if (require === undefined) var require = {}
>     if (exports === undefined) var exports = {}
>   </script>
> ```

That bypass is just a workaround, so I have switched to AntChart. It doesn't have a good documentation but it worths a try 😄

**Comment by ckifer** [comment]
This is resolved in newer versions
