### ISSUE TITLE
Chart data is not accessible through keyboard

### ISSUE THREAD

**Issue by ninjadev123** [recharts/recharts#2565]
Details on line chart is not accessible through keyboard. 

![image](https://user-images.githubusercontent.com/10661254/120805215-6036bc00-c4fa-11eb-8ca7-12524c8c06f1.png)

**Comment by mgifford** [comment]
I think we should just mark this as redundant and close this issue. It's an important accessibility issue but better described by https://github.com/recharts/recharts/issues/2085
