### ISSUE TITLE
Open a modal on click of scatter points

### ISSUE THREAD

**Issue by shibinjohn009** [recharts/recharts#2568]
## Do you want to request a feature or report a bug? 
Yes

## What is the current behavior? 
Currently the onclick event on the Scatter component does not seems to work. It does not return the mapped data but a click event.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
In the demo link I need to open a modal on clicking on the scatter points.
https://codesandbox.io/s/scatter-chart-of-three-dimensions-w2cwd?file=/src/App.tsx

## What is the expected behavior?
On click on the points it should return the cordinate at which the point is

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
latest

**Comment by ckifer** [comment]
this definitely happens now. Closing
