### ISSUE TITLE
Bar minPointSize does not work for falsy values

### ISSUE THREAD

**Issue by cephirothdy2j** [recharts/recharts#257]
The minPointSize property on <Bar /> components fixes a problem I'm having, where I need to differentiate between values of 0 and undefined values. However, if the value is 0, a bar does *not* render at the defined minPointSize. Any other value (0.0000000001 for example) will render the bar.

**Comment by cephirothdy2j** [comment]
Thanks for merging, @xile611. Any idea when this will be pushed to a release?

**Comment by xile611** [comment]
Done in version 0.15.0
