### ISSUE TITLE
How to extend Bar, or other components ?

### ISSUE THREAD

**Issue by 80avin** [recharts/recharts#2574]
Hello.
I'm trying to write a component which extends Bar component to provide some defaults. But the traditional approach is failing.

I need a way to read animation state from html attribute, and for that, I'm writing an element which extends Bar, but this fails.
My approach is something like this.
```javascript
const NewBar = React.forwardRef((props, ref) => {
  const [animating, setAnimating] = useState(false)

  const onAnimationStart = useCallback(
    (...args) => {
      setAnimating(true)
      return props.onAnimationStart?.(...args)
    },
    [props.onAnimationEnd]
  )

  const onAnimationEnd = useCallback(
    (...args) => {
      setAnimating(false)
      return props.onAnimationEnd?.(...args)
    },
    [props.onAnimationEnd]
  )

  props = {
    ...props,
    onAnimationStart,
    onAnimationEnd,
  }
  return <Bar data-cy-animating={animating} ref={ref} {...props} />
})

```

**Comment by 80avin** [comment]
The solution was to use class component and set `NewBar.displayName` to `'Bar'`

**Comment by ckifer** [comment]
going to close this as a duplicate and stale
https://github.com/recharts/recharts/issues/2788
