### ISSUE TITLE
Line gap in LineChart

### ISSUE THREAD

**Issue by DDiscua** [recharts/recharts#2577]
The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.

Hello guys,

I'm trying to increase the GAP between lines in a LineChart Graph but I don't know how to make it. See the following image 

![image](https://user-images.githubusercontent.com/31171755/123345627-bdc79280-d513-11eb-9c18-6aef97c24269.png)
I want to have more "space" between Lines, so users can see more clearly the graph. Everything is being built dynamically.

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

**Comment by pkang0316** [comment]
Try changing the Y-Axis domain

**Comment by ckifer** [comment]
+1 a closer in y domain will give you a zoomed in chart. The closer your domain to your actual values the larger your values will look in relation to each other
