### ISSUE TITLE
BarChart orientantion="vertical" has invisible bottom spacing after 2.0.0-beta.3

### ISSUE THREAD

**Issue by Akuukis** [recharts/recharts#2579]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/amazing-cdn-hxc3n)

### Steps to reproduce
See the repro link

```js
import React from "react";
import ReactDOM from "react-dom";

import { BarChart, Bar, XAxis, YAxis } from "recharts";

const data = [{ name: "a", a: 3, b: 4, c: 5 }];

function App() {
  return (
    <BarChart
      width={500}
      height={100}
      data={data}
      barGap={0}
      barCategoryGap={0}
      layout="vertical"
      margin={{ bottom: 0, left: 0, right: 0, top: 0 }}
    >
      <XAxis type="number" hide />
      <YAxis type="category" hide />
      <Bar stackId="s" label dataKey="a" fill="#0FF" />
      <Bar stackId="s" label dataKey="b" fill="#FF0" />
      <Bar stackId="s" label dataKey="c" fill="#F0F" />
    </BarChart>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

Do not edit code, just change `recharts` versions (and refresh in-browser browser when it crashes). Noteworthy versions:
- `1.8.5` - good
- `2.0.0-beta.2` - good
- `2.0.0-beta.3` - good, except an unrelated misaligned label
- `2.0.0-beta.4` - same ^^
- `2.0.0-beta.5` - bad (and unrelated misaligned label still there)
- `2.0.9` - still bad (although the unrelated misaligned label was fixed at some point)

### What is expected?
I expect to be able to remove all spacing and be left with only a horizontal stacked bar. It seems possible until `2.0.0-beta.4` including.

![image](https://user-images.githubusercontent.com/7459419/123558746-9507fd00-d7a0-11eb-9b9d-1d3dab2e3963.png)

### What is actually happening?
Since `2.0.0-beta.5` and still at `2.0.9` including, there's a significant bottom spacing that I can't get rid off. The size of it changes with height.

![image](https://user-images.githubusercontent.com/7459419/123558755-a224ec00-d7a0-11eb-9ae9-bf1e53240f80.png)

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 17.0.2 |
| System | Ubuntu 20.04 |
| Browser | Firefox 89.0.1 |

---
I have data for several stacked bar charts, but instead of displaying them all at once as in classic chart and then to write a essay  referencing back to it, I want to have a separate minimalistic stacked bar right where it's mentioned.

**Comment by ckifer** [comment]
![image](https://github.com/user-attachments/assets/b73ea680-0fbe-4df0-af32-6ac07e8dd144)
this was fixed at some point, working in the latest 2.12.7. Resolving
