### ISSUE TITLE
allowDataOverflow lines spill over x axis

### ISSUE THREAD

**Issue by cephirothdy2j** [recharts/recharts#258]
Not sure if I'd call it a bug, but it's at least unexpected behavior for me.

In the attached screenshot, I have a yAxis domain set as [-8,8] and my data points range from -10 to 10. At the top of the graph, the data points disappear as the line extends above 8. At the bottom, the line overlays the X axis and is visible until reaching the bottom of the container.

I would expect the line to disappear at the bottom when it reaches the X axis, not when it reaches the container edge.

<img width="664" alt="screen shot 2016-09-20 at 2 50 01 pm" src="https://cloud.githubusercontent.com/assets/881769/18684306/bb1b3ece-7f41-11e6-8490-fe254337eb7e.png">

**Comment by xile611** [comment]
@cephirothdy2j As mentioned in [#223](https://github.com/recharts/recharts/issues/223). In your case, do you want to cut the lines inner the coordinate system?

**Comment by cephirothdy2j** [comment]
That is the behavior I would expect. But if others feel differently I defer to their opinion.
