### ISSUE TITLE
Chart does not display points correctly (when more than 2 objects share the same X)

### ISSUE THREAD

**Issue by Joakeim** [recharts/recharts#2583]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/simple-line-chart-forked-lfoc9 )

### Steps to reproduce
The issue we are facing is that the (line) chart tooltip cannot display more than 3 objects with the same X coordinate. As an example when we feed the chart with these data
const data = [ {
  {
    name: 3,
    uv: 2000,
    pv: 7000    
  },
  {
    name: 3,
    uv: 2500,
    pv: 7500    
  }
]
moving just before the vertical line where x = name = 3 displays a tooltip with only the first object (y1= uv = 2000, y2 = pv = 7000) while moving just after the vertical line displays the second object. 

In case 3 or more objects share the same X coordinate then all in-between objects are not displayed. Only the first one and the last one are correctly displayed as seen in the example here: https://codesandbox.io/s/simple-line-chart-forked-lfoc9 (in the example hover over point in x=3 coordinate)

### What is expected?
Ideally all points (6 per the example) should be displayed in the tooltip or only one - the one closest to the mouse cursor.

### What is actually happening?
In between points cannot be displayed in the tooltip

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | react 16.6.3 |
| System | windows 10 |
| Browser | chrome, firefox, edge |

**Comment by jeghers** [comment]
We have a similar issue: we need the tooltip data to tell us exactly which data point (if any) we are hovering over.

**Comment by ckifer** [comment]
Closing this in favor of other duplicate issues
