### ISSUE TITLE
ResponsiveContainer crashes and does not render. v2.0.9

### ISSUE THREAD

**Issue by amoghcv** [recharts/recharts#2584]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/responsivecontainer-zc4we?file=/src/MixedCharts.js)

### Steps to reproduce
Run App, See Crash

### What is expected?
Chart should render

### What is actually happening?
Error

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 17.0.2 |
| System | N/A |
| Browser | Safari, Chrome |

---
Trying to centre chart on page using ResponsiveContainer

**Comment by amoghcv** [comment]
I think I figured out what I was doing wrong ...

**Comment by drhumlen** [comment]
@amoghcv What was the problem? I have the same problem

**Comment by drhumlen** [comment]
After being stuck on this problem for many hours, I finally found the error:

ResponsiveContainer must have exactly _one_ child element (the chart). We actually _did_ only have one child, but since we're using React without JSX, the container was called like  this:

```
e(Recharts.ResponsiveContainer, {width:700, height:'80%'}, [ ourAreaChart ])
```

but after changing it to:
```
e(Recharts.ResponsiveContainer, {width:700, height:'80%'}, ourAreaChart)
```

it finally started working. A very frustrating problem since every other React element accepts arrays as input for children.

**Comment by eduardoacskimlinks** [comment]
We have migrated from `1.3.4` to `2.1.9`. However, according to the documentation, we have encountered an error by rendering the UI, which doesn't make any sense to us.

<img width="1403" alt="Screenshot 2022-03-07 at 13 27 36" src="https://user-images.githubusercontent.com/74052373/157044178-5e88f20c-fbc6-4fb3-bbd5-574f3ba77161.png">

Do you know what may be the cause?

**Comment by evbo** [comment]
@amoghcv will you reopen this issue? @drhumlen I think has caught a very subtle bug! Never have I seen an "import" error due to passing more than 1 child component to a react component.

I think a more useful error should be shown. This is very painful to catch.

**Comment by eduardoacskimlinks** [comment]
@evbo did you manage to solve it? We are waiting for the fix to upgrade the package, so If you know a way, I would much appreciate it if you could share.

**Comment by evbo** [comment]
@eduardoacskimlinks the answer was given by @drhumlen. Depending on your programming language the fix will vary wildly.

For instance, I am using scalajs so my exact fix would probably not help you. But basically, you need to ensure there is a single child ReactElement passed, not a list.

...but... to be honest... I am no longer using this library and have switched to Plotly.js. Very happy with it :)
