### ISSUE TITLE
Linear gradient not working if dataset values are same

### ISSUE THREAD

**Issue by BeroBurny** [recharts/recharts#2587]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/simple-line-chart-bug-bb1-lx2i9?file=/src/App.tsx)

### Steps to reproduce
Use LinearGradient and all data points contain the same value (like [24, 24, 24, 24])

### What is expected?
to display line

### What is actually happening?
line is invisible

| Environment | Info |
|---|---|
| Recharts | v2.0.6 |
| React | React |
| System | Linux. MacOS |
| Browser | Chrome, Firefox, Electron |

---
if in any situation value changes to not to be same as previous fields line will render

**Comment by FabianR3P** [comment]
I have the same problem :c

**Comment by ckifer** [comment]
This is an svg problem not a recharts problem. 

https://stackoverflow.com/a/21639059
