### ISSUE TITLE
Is there a way to handle overflow/word-breaking within a pie?

### ISSUE THREAD

**Issue by patryk0605** [recharts/recharts#259]
Using the [CustomActiveShapePieChart](http://recharts.org/examples#CustomActiveShapePieChart) example, is it possible to handle overflow when a label exceeds the container size as seen below:

![image](https://cloud.githubusercontent.com/assets/7227636/18686474/0aab2348-7f4a-11e6-96db-d09a451c78a7.png)

**Comment by techniq** [comment]
@patryk0605 maybe soon once https://github.com/recharts/recharts/pull/243 lands

**Comment by patryk0605** [comment]
@techniq perfect! Hope it gets merged soon!

**Comment by patryk0605** [comment]
Closing as there is pull request to address the issue.
