### ISSUE TITLE
Dependencies medium-severity vulnerability | d3-color

### ISSUE THREAD

**Issue by beltranrengifo** [recharts/recharts#2590]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://snyk.io/test/npm/recharts/2.0.8?tab=issues](https://snyk.io/test/npm/recharts/2.0.8?tab=issues)

### Steps to reproduce
Our IT security team, troughthout snyk, is reporting and requiring us to update Recharts package in order to resolve this security vulnerability. It seems mandatory to update d3-color, used in d3-intepolate and d3-scale, to its last version:
https://snyk.io/vuln/SNYK-JS-D3COLOR-1076592 (Upgrade d3-color to version 3.0.0 or higher)

Also d3-interpolate and d3-scale must be updated to its @3.0.0 and @4.0.0 versions.

### What is expected?
Not to have security issues in a security check. Updated packages.
Currently Recharts uses: 
* d3-interpolate@2.0.1
* d3-scale@3.3.0

Both of them depend on 
* d3-color@2.0.0

### What is actually happening?
We find security issues and outdated packages.
Hopefully Recharts could use: 
* d3-interpolate@3.0.0
* d3-scale@4.0.0

That will depend on
* d3-color@3.0.1

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 16.12.0 |
| System | OSX |
| Browser | Chrome |

**Comment by ckifer** [comment]
Closing this in favor of https://github.com/recharts/recharts/issues/3012

https://github.com/recharts/recharts/pull/3120 should be merged soon
