### ISSUE TITLE
AreaChart dot does not become active when hovered outside of area

### ISSUE THREAD

**Issue by alexey-kozlenkov** [recharts/recharts#2591]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/line-chart-width-xaxis-padding-sujqi)

### Steps to reproduce
0. Enable activeDot in any way
1. Start hovering onto the most left/the most right dot by dragging mouse outside of area towards dot.

### What is expected?
1. Dot becomes active whenever mouse hovers over the dot

### What is actually happening?
1. Dot does not become active during half of the path and only activates once mouse enter chart area itself

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 17.0.2 |
| System | MacOS |
| Browser | Chrome 91.0.4472.114 |

https://user-images.githubusercontent.com/8117458/125096003-66155380-e0dd-11eb-8c5d-4d42dd2dc6fa.mov

**Comment by Primerz** [comment]
This is not a bug, meanwhile you can extend the domain of the first and last lines of the X axis by 100 px: `<XAxis type="number" domain={['dataMin - 100', 'dataMax + 100']} />
`
