### ISSUE TITLE
Not displayed when component is split

### ISSUE THREAD

**Issue by mrskiro** [recharts/recharts#2595]
hi.

If you split the contents of ResponsiveContainer into other components, it will not be displayed.
Is there a way to solve this problem?

sandbox
https://codesandbox.io/s/eager-feynman-ff3mx?file=/src/App.tsx

**Comment by monkeyDvrus** [comment]
Hey,
I have the same problem.
Did you find a solution?

**Comment by uvarov-frontend** [comment]
Duplicate of the discussion: https://github.com/recharts/recharts/issues/412

**Comment by ckifer** [comment]
This is on purpose as there is only meant to be one child within responsive container as a part of the recharts api
