### ISSUE TITLE
generateCategoricalChart() throws error after upgrading from 2.0.9 to 2.0.10

### ISSUE THREAD

**Issue by marnixhoh** [recharts/recharts#2596]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-vz7e4?file=/src/index.js)

### Steps to reproduce
Pass undefined to the BarChart `data` prop.

### What is expected?
This should not cause Recharts to crash

### What is actually happening?
Recharts (generateCategoricalChart()) throws the following error:

`Cannot read property 'map' of null`

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 16.14.0 |
| System | MacOS |
| Browser | Chrome |

---
In version 2.0.9 passing undefined did not cause the error, but in 2.0.10 it does... (I was unable to change the version in the dropdown to 2.0.10)

Why pass undefined? This happens in my application while the data is fetched.

**Comment by ckifer** [comment]
This is fixed
