### ISSUE TITLE
Implement tooltip for PieChart

### ISSUE THREAD

**Issue by Cloudo** [recharts/recharts#26]

**Comment by xile611** [comment]
Have implemented In v0.7.0
<http://recharts.org/examples#TwoSimplePieChart>

**Comment by Cloudo** [comment]
Awesome, thanks!

**Comment by JuanGaray93** [comment]
There is no tooltip in that example

**Comment by fatemehqasemkhani** [comment]
you can set custom tooltip or default tooltip.
`const PieChart = ({
  data,
  colors,
  fill,
  dataKey,
  innerRadius,
  outerRadius,
  cx,
  cy,
  paddingAngle,
  label,
  labelLine,
  payload,
}) => {
  const CustomTooltip = ({ payload }) => {
    console.log('payload', payload);
    return (
      <div>
        <div className="ant-popover-arrow" />
        <div className={s.customTooltip}>
          <b>{payload?.[0]?.payload?.name}</b>
          <span className={s.info}>
            <p className="desc">
              <small>{payload?.[0]?.payload?.totalCurrentPrice}</small>{' '}
              <small>ریال</small>
            </p>
            <p>{payload?.[0]?.payload?.profitInPercentage} %</p>
          </span>
        </div>
      </div>
    );
  };

  return (
    <Chart width={150} height={150}>
      <Pie
        data={data}
        cx={cx}
        cy={cy}
        innerRadius={innerRadius}
        outerRadius={outerRadius}
        fill={fill}
        paddingAngle={paddingAngle}
        dataKey={dataKey}
        labelLine={labelLine}
        label={label}
      >
        {data.map((entry, index) => (
          <Cell key={entry.key} fill={colors[index % colors.length]} />
        ))}
      </Pie>
      <Tooltip content={<CustomTooltip />} />
    </Chart>
  );
};`

if you omit content props in Tooltip, rechart default tooltip will be applied.
