### ISSUE TITLE
Animation disable not working

### ISSUE THREAD

**Issue by Beyazatli** [recharts/recharts#2616]
## Do you want to request a feature or report a bug?
isAnimationActive, animationDuration and other props not working on NextJS

## What is the current behavior?
Even though i add props (isAnimationActive etc. for stopping animation any solution), it doesn't work, it doesn't have any effect. Since there is no CSS animation, I cannot make a mandatory intervention. I've looked through other issues but any solution didn't work for me, it doesn't work at all

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
![image](https://user-images.githubusercontent.com/39380337/127742364-b52db95b-136d-4ce2-b9d7-8cb6106792ef.png)

## What is the expected behavior?
Completely disable animation

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
All up to date browsers, Recharts: ^2.0.10, NextJS: 11.0.1, React: 17.0.2

**Comment by Beyazatli** [comment]
Any solution?

**Comment by max-sym** [comment]
I'm facing this issue too. Any news?

**Comment by ckifer** [comment]
Disabling animation works with a regular codesanbox, can someone reproduce this?

https://codesandbox.io/s/simple-area-chart-forked-8xk2d6?file=/src/App.tsx

**Comment by ckifer** [comment]
disabling animation seems to work fine in next 13+ and the latest recharts. Tested with both Line and Area. Resolving this
