### ISSUE TITLE
Brush cuts/hides data + too slow to pan

### ISSUE THREAD

**Issue by timurcatakli** [recharts/recharts#2617]
If you review the app below
https://codesandbox.io/s/unruffled-river-8jvxv?file=/src/App.js

You will notice that brush is not very performant. Plus changing start and end index cuts/hides series data...

Is this something I did, or is it expected?
Thanks...

**Comment by talhaiqbalti** [comment]
do you find any solution for this?

**Comment by ckifer** [comment]
Sandbox above seems broken, this seems to be okay? The point of the brush is to cut and hide data, but I might be missing something

https://codesandbox.io/s/bar-chart-with-brush-forked-gksy9v

**Comment by ckifer** [comment]
Closing this due to no response
