### ISSUE TITLE
Datakey value on top of the bar

### ISSUE THREAD

**Issue by email2vimalraj** [recharts/recharts#262]
I would like to display the value of the datakey on top of every bar on the bar chart. I am not able to find anything related to this in the documentation. I'm not sure we have the capability to show that are not too.

```
<Bar dataKey="mydatakey" label />
```

But it shows the label (I understood this is working as expected), but I was expecting to show the actual y axis value.

**Comment by xile611** [comment]
@email2vimalraj You can check this [demo](http://jsfiddle.net/ez3x3z4k/). It just show the actual y axis value by default. What's the problem?

**Comment by damianobarbati** [comment]
@email2vimalraj did you solve this? @xile611 the fiddle is not working anymore :\

**Comment by damianobarbati** [comment]
Found here. http://recharts.org/en-US/api/Label
