### ISSUE TITLE
Responsive Container for recharts version 2.1.0 not fills free space

### ISSUE THREAD

**Issue by pwnuk** [recharts/recharts#2620]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/area-chart-in-responsive-container-forked-wyn3k?file=/src/App.tsx)

### Steps to reproduce
Change the displayed browser width. 

### What is expected?
Width of responsive container will fit.

### What is actually happening?
Width of responsive container is still the same.

| Environment | Info |
|---|---|
| Recharts | v2.1.0 |
| React | 17 |
| System | osx Catalina |
| Browser | chrome |

---
Its related to recharts version 2.1.0.

**Comment by mohamedmansour** [comment]
After upgrade to v2.1.0 I found the same regression in ResponsiveContainer, does not fill free space.

**Comment by akornatskyy** [comment]
a slightly related issue with v2.1.0 and `react-bootstrap v1.6.1`: when `ResponsiveContainer` used on `Tab.Container` inactive tab, it does not display chart when `Tab.Pane` becomes active. It works as expected with v2.0.10.

**Comment by plxmargaux** [comment]
Same here, I switched back to v2.0.10 and everything's working as expected

**Comment by dsldsl** [comment]
I am having the same issue, and switching back to v2.0.10 doesn't fix it.  Anyone have other suggestions?
