### ISSUE TITLE
Custom Y Axis category ticks changing as data propagates 

### ISSUE THREAD

**Issue by Corey-Wademan** [recharts/recharts#2621]
I am trying to set the Y axis to display the strings in the image in order as they are set in the ticks prop. But as the data changes the order of the ticks change. 

I am aiming to display the ticks along the axis as they appear in the Y-Axis ticks prop.

<img width="1435" alt="Screen Shot 2021-08-12 at 8 51 00 AM" src="https://user-images.githubusercontent.com/67563215/129199754-7ca55aec-a209-44ef-b13d-be7813949ff5.png">
<img width="819" alt="Screen Shot 2021-08-12 at 8 50 45 AM" src="https://user-images.githubusercontent.com/67563215/129199760-52ba5f0a-6ebd-4bee-8f4d-02fa4d1b2bb6.png">

**Comment by ckifer** [comment]
Closing this as stale
