### ISSUE TITLE
Bar chart become smaller

### ISSUE THREAD

**Issue by vadim080617** [recharts/recharts#2623]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/young-wave-f0dc8?file=/src/App.js)

### Steps to reproduce
Chart become smaller with next data `  {
    name: "test",
    a: 69.4,
    b: 30.18,
    c: 0.4,
    d: 0.02
  }`, but if i change property **_b_** to 30.1, it become normal.

### What is expected?
chart will be full width with correct line part sizes 
<img width="552" alt="correct" src="https://user-images.githubusercontent.com/29286349/129346387-a7264ad6-2e06-43ce-86b8-e23893d08fa7.png">

### What is actually happening?
width of chart become smaller
<img width="553" alt="wrong" src="https://user-images.githubusercontent.com/29286349/129346383-4ec13a55-376b-4f84-9737-2ec25423ffc9.png">

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 17.0.1 |
| System | macOs 11.4 |
| Browser | Chrome 92.0.4515.131 |

---

Is it a bug, or im do something wrong? Thank you

**Comment by ckifer** [comment]
set your `domain` on your `XAxis` to `[0, 100]` to prevent the domain from auto adjusting

closing as stale/answered
