### ISSUE TITLE
Show both Lines with same data

### ISSUE THREAD

**Issue by gauravgupta98** [recharts/recharts#2624]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/simple-line-chart-forked-27ohf?file=/src/App.tsx)

### Steps to reproduce
We have a use case where data comes from server dynamically and sometimes we encounter two different data points with exact same data (Similar to what I've shared in replication link).

The problem now is that we can't see the purple line chart and it is at times confusing whether data exists for other data point or not.

Is there any way we can fix this by adding some weight to each line or any way by which we can show both lines?

### What is expected?
Both the data lines should be displayed

### What is actually happening?
One one line is getting displayed

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 17.0.2 |
| System | Mac |
| Browser | All |

---
REPLICATION LINK = https://codesandbox.io/s/simple-line-chart-forked-27ohf?file=/src/App.tsx

**Comment by gsteja2307** [comment]
try passing strokeWidth={2} to first line component

**Comment by gauravgupta98** [comment]
Tried this but didn't fix the issue. Still getting only one line

**Comment by sabrinamokerji** [comment]
> Tried this but didn't fix the issue. Still getting only one line

You could set one of the lines to have lower opacity and a more visible stroke width. This way you'll be able to see the other line through the wider one - [example](https://codesandbox.io/s/simple-line-chart-forked-5zgru?file=/src/App.tsx).

**Comment by gauravgupta98** [comment]
Thanks @sabrinamokerji, this helped :)
