### ISSUE TITLE
Tooltip property: Remove dot from line graph

### ISSUE THREAD

**Issue by humleflue** [recharts/recharts#2625]
- [Y] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
That the dot on the line graph is displayed on hover. 

I do not want the dot to be displayed, as the user is not able to drag this chart, but is able to drag other charts on the page, which has dots on it. This results in a confusing user experience.

### What does the proposed API look like?
<Tooltip lineDot={false} />

**Comment by joefreeman** [comment]
Hi @humleflue. Does this do what you want?

```javascript
<Line ... activeDot={false} />
```

**Comment by parrytowsh** [comment]
Hi @humleflue you may try <Line .... dot={{ r: 0 }}>

**Comment by humleflue** [comment]
> Hi @humleflue. Does this do what you want?
> 
> ```js
> <Line ... activeDot={false} />
> ```

Hi @joefreeman,
This did the job! 
Cheers!
