### ISSUE TITLE
Fix direction: rtl problem

### ISSUE THREAD

**Issue by morajabi** [recharts/recharts#263]
Numbers and texts are not clear and tooltip opens in wrong place.
![screen shot 2016-09-21 at 1 44 58 pm](https://cloud.githubusercontent.com/assets/12202757/18707150/a34bfa2a-8001-11e6-9f1a-58c276f0112a.png)

**Comment by xile611** [comment]
@morajabi Can you support a jsfiddle demo ?

**Comment by morajabi** [comment]
http://jsfiddle.net/morajabi/2nry4psq/

**Comment by xile611** [comment]
@morajabi The demo you created seems no problem.

**Comment by dola** [comment]
the example is missing the line

    direction: rtl;

as css property for `#container`

**Comment by morajabi** [comment]
Sorry for wrong demo, I think it's correct now. Check it up!

**Comment by yctercero** [comment]
@morajabi Using an extra div to wrap my LineChart I was able to avoid the issue with the tooltip being in the wrong place when using ```direction: rtl;``` So my css looks something like: 
```
  .chartWrapper {
    position: relative;
    width: 1050px;
    height: 400px;
    overflow-x: scroll;
    direction: rtl;
  }

  .chartAreaWrapper {
    direction: ltr;
  }
```
And made sure to add a width to ```.chartedAreaWrapper``` inline since, at least in my case, the width will vary.

Hope that helps!

**Comment by jordanpicaso** [comment]
If your index.html is set to `dir="rtl"` , the only quick solution for this problem is to wrap the parent component with an extra div and give it a `style={{direction: "ltr"}}`  or a className
e.g:
 `
<div style={{direction: "ltr"}}>
<AreaChart>
//other child components
</AreaChart/>
</div>
` 
Happy Hacking!

**Comment by jordanpicaso** [comment]
If your index.html is set to dir="rtl" , the only quick solution for this problem is to wrap the parent component with an extra div and give it a style={{direction: "ltr"}} or a className
e.g:

`
<div style={{direction: "ltr"}}>
<LineChart>
//child component
</LineChart/>
</div>
`

Happy Hacking!

**Comment by jordanpicaso** [comment]
If your index.html is set to dir="rtl" , the only quick solution for this problem is to wrap the parent component with an extra div and give it a style={{direction: "ltr"}} or a className
e.g:
`<div style={{direction: "ltr"}}><LineChart> // child component </LineChart> </div>`
Happy Hacking!

**Comment by HTFDev** [comment]
As I understood from the properties of the newly updated YAxis, you can use the `orientation` prop to change its direction. Although it wouldn't really change the the chart's direction, but helps with the UI as the XAxis doesn't need to be redirected at all
```
<YAxis orientation={locale.startsWith("fa") ? "right" : "left"} />
```
