### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by tbntdima** [recharts/recharts#2633]
Hi I'm getting `Each child in a list should have a unique "key" prop.` everytime I'm using `Customized` component.
[codesandbox repro](https://codesandbox.io/s/stupefied-germain-l9wst?file=/src/App.js)

**Comment by loudmouth** [comment]
I am seeing this with `LineChart` and `Line` on the latest version, `2.1.2`

```
Check the render method of `Line`. See https://reactjs.org/link/warning-keys for more information.
    at svg
    at Line (eval at ES6ProxyComponentFactory (http://localhost:8080/vendors-node_modules_css-loader_dist_runtime_api_js-node_modules_style-loader_dist_runtime_in-93f1c7.7894d0177b09b3aa31b6.js:132547:10), <anonymous>:14:7)
    at svg
    at Surface (http://localhost:8080/vendors-node_modules_css-loader_dist_runtime_api_js-node_modules_style-loader_dist_runtime_in-93f1c7.7894d0177b09b3aa31b6.js:153029:24)
    at div
    at LineChart (eval at ES6ProxyComponentFactory (http://localhost:8080/vendors-node_modules_css-loader_dist_runtime_api_js-node_modules_style-loader_dist_runtime_in-93f1c7.7894d0177b09b3aa31b6.js:132547:10), <anonymous>:14:7)
```

**Comment by therealbluepandabear** [comment]
I am also seeing this with `Area` (`AreaChart`).

**Comment by ckifer** [comment]
@therealbluepandabear can you give a reproduction?

**Comment by leo-castro** [comment]
getting the same warning using Area
![Untitled](https://github.com/recharts/recharts/assets/37127887/32517e66-4f97-45cb-950c-f4ececb66239)

**Comment by ckifer** [comment]
@leo-castro can you give an example of the data that causes that, or a codesandbox repro?

**Comment by leo-castro** [comment]
> @leo-castro can you give an example of the data that causes that, or a codesandbox repro?

so my data had a dummy field named "show", removing (or renaming) it got rid of the warning.

**Comment by ckifer** [comment]
@leo-castro can you give an example? Your data had a field named "show" and that field had what values?

In order to reproduce this I need the exact data that causes it.

**Comment by leo-castro** [comment]
@ckifer It wasn't actually the data... the problem was using a custom dot which didn't have a key:

` 
const renderCustomDot = useCallback(props => {
  const { cx, cy, payload } = props;
  if (payload?.display){
      return (
          <g key={`dot-${JSON.stringify(payload)}`}> // THIS WAS THE MISSING KEY
              <text x={cx - 50} y={cy - 15} textAnchor="middle" fill={theme.palette.text.primary} fontSize={10}>
                  {t('general:today')} ${payload.amount.toFixed(2)}
              </text>
              <circle cx={cx} cy={cy} r={13} fill={theme.palette[palette].light} fillOpacity={0.3} />
              <circle cx={cx} cy={cy} r={6} fill={theme.palette[palette].light} stroke={theme.palette.text.primary} strokeWidth={2} />
          </g>
      );
  } else return null;
}, [i18n.language, theme.palette, palette, t]);

return (
  <AreaChart data={data}>
      <Area 
          type="monotone" 
          dataKey="amount" 
          strokeWidth={2} 
          dot={renderCustomDot}
      />
  </AreaChart>
);
`

This is the data if you still need it:

`[
    {
        "date": "Thu Feb 22 2024 01:19:11 GMT-0500 (Eastern Standard Time)",
        "amount": 65.74,
        "trend": "up",
        "display": false
    },
    {
        "date": "Thu Feb 22 2024 01:19:11 GMT-0500 (Eastern Standard Time)",
        "amount": 51.43,
        "trend": "down",
        "display": false
    },
    {
        "date": "Thu Feb 22 2024 01:19:11 GMT-0500 (Eastern Standard Time)",
        "amount": 125.64,
        "trend": "up",
        "display": false
    },
    {
        "date": "Thu Feb 22 2024 01:19:11 GMT-0500 (Eastern Standard Time)",
        "amount": 107.82,
        "trend": "down",
        "display": false
    },
    {
        "date": "Thu Feb 22 2024 01:19:11 GMT-0500 (Eastern Standard Time)",
        "amount": 29.96,
        "trend": "down",
        "display": false
    },
    {
        "date": "Thu Feb 22 2024 01:19:11 GMT-0500 (Eastern Standard Time)",
        "amount": 57.27,
        "trend": "up",
        "display": false
    },
    {
        "date": "Thu Feb 22 2024 01:19:11 GMT-0500 (Eastern Standard Time)",
        "amount": 57.59,
        "trend": "up",
        "display": false
    },
    {
        "date": "Thu Feb 22 2024 01:19:11 GMT-0500 (Eastern Standard Time)",
        "amount": 75.86,
        "trend": "up",
        "display": false
    },
    {
        "date": "Thu Feb 22 2024 01:19:11 GMT-0500 (Eastern Standard Time)",
        "amount": 101.29,
        "trend": "up",
        "display": false
    },
    {
        "date": "Thu Feb 22 2024 01:19:11 GMT-0500 (Eastern Standard Time)",
        "amount": 77.8,
        "trend": "down",
        "display": false
    },
    {
        "date": "Thu Feb 22 2024 01:19:11 GMT-0500 (Eastern Standard Time)",
        "amount": 64.79,
        "trend": "down",
        "display": false
    },
    {
        "date": "Thu Feb 22 2024 01:19:11 GMT-0500 (Eastern Standard Time)",
        "amount": 64.79,
        "trend": "up",
        "display": false
    },
    {
        "date": "Thu Feb 22 2024 01:19:11 GMT-0500 (Eastern Standard Time)",
        "amount": 125.64,
        "trend": "up",
        "display": true
    },
    {
        "date": "Thu Feb 22 2024 01:19:11 GMT-0500 (Eastern Standard Time)",
        "amount": 19,
        "trend": "up",
        "display": false
    },
    {
        "date": "Thu Feb 22 2024 01:19:11 GMT-0500 (Eastern Standard Time)",
        "amount": 16,
        "trend": "up",
        "display": false
    }
]`

**Comment by ckifer** [comment]
@leo-castro really appreciate the response! So in this case internal recharts was not responsible.

Thanks!
