### ISSUE TITLE
ResponsiveContainer makes legend overlapping with chart when re-rendering

### ISSUE THREAD

**Issue by plxmargaux** [recharts/recharts#2636]
## Do you want to request a feature or report a bug?
Report a bug

## What is the current behavior?
I'm using the `<AreaChart />` component for a project and I added a custom content component into the `<Legend />` component itself. I have a button that is meant to switch between a Table view and a Chart view, however, It seems like it interferes with the `<ResponsiveContainer />`. Each time the chart is re-rendered, it takes the whole height of the responsive container without considering the `<Legend/>`, which leads to overlapped components (see video attached)

For now, the `<Legend />` component is in `position: absolute`, which matched the desired design, but even if I switch the component to a `relative` position, the chart is still taking into account the `<Legend />` within its height. 

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

https://user-images.githubusercontent.com/29457898/130966017-228cc4e4-76df-45da-9a44-2df5df6ea3d7.mp4

## What is the expected behavior?
`<AreaChart />` should always have the defined height when re-rendering, no matter If there is a Legend or not. 

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
recharts@2.1.2 - Chrome, Firefox, Safari

**Comment by middiu** [comment]
this is still an issue in 2.1.6, please see below:
https://codesandbox.io/s/simple-line-chart-forked-hb7l9?file=/src/App.tsx
![image](https://user-images.githubusercontent.com/428032/139517321-2f6465cd-2814-45f6-b593-ed6692b122ad.png)

**Comment by middiu** [comment]
can you please re-open the issue @arcthur
