### ISSUE TITLE
YAxis does not respect `domain`

### ISSUE THREAD

**Issue by johanbook** [recharts/recharts#2639]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-j3okd?file=/src/index.js)

### Steps to reproduce
When setting the domain of the YAxis to numeric values, those values are not respected if there is datapoints outside the domain.

### What is expected?
If domain is specified, it should be respected no matter what.

### What is actually happening?
Domain is not respected.

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | React v17.0.2 |
| System | Archlinux |
| Browser | Brave, Firefox |

**Comment by julesair** [comment]
Having the same issue with the YAxis both lower and upper limit. E.g. `domain={[0, 100]`

| Environment | Info   |
|----------|---------|
| recharts | 2.1.1   |
| react    | 16.13.1 |
| browser    | Firefox, Chrome |

**Comment by benschwarz** [comment]
Confirming, this is still a bug on the most recent release.

**Comment by ckifer** [comment]
Updated sandbox with latest recharts version 
[![Edit recharts-issue3839-yaxis](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/recharts-issue-template-forked-63ndtf)

The key here is `allowDataOverflow` needs to be set to true

When it is not, the domain will not cut off any parts of the chart if it can help it.

(this is a legacy thing not implemented by me)

The docs need to be better, but this does work

**Comment by benschwarz** [comment]
@ckifer Thank you for confirmation. I just submitted a PR to the docs site to highlight how to use it 👍

If anyone wants to see `allowDataOverflow` in action, [see my codesandbox fork](https://codesandbox.io/p/sandbox/recharts-issue-template-forked-f56ddw?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluvy8npw00072e66n6pcc36x%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluvy8npw00032e66z65u0htp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluvy8npw00042e66e0xqcqox%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluvy8npw00062e66m4ewdtee%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluvy8npw00032e66z65u0htp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluvy8npw00022e66ju8yxorr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A34%252C%2522startColumn%2522%253A14%252C%2522endLineNumber%2522%253A34%252C%2522endColumn%2522%253A14%257D%255D%257D%255D%252C%2522id%2522%253A%2522cluvy8npw00032e66z65u0htp%2522%252C%2522activeTabId%2522%253A%2522cluvy8npw00022e66ju8yxorr%2522%257D%252C%2522cluvy8npw00062e66m4ewdtee%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluvy8npw00052e668xk18jsr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cluvy8npw00062e66m4ewdtee%2522%252C%2522activeTabId%2522%253A%2522cluvy8npw00052e668xk18jsr%2522%257D%252C%2522cluvy8npw00042e66e0xqcqox%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cluvy8npw00042e66e0xqcqox%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) ✌️
