### ISSUE TITLE
Events: possible memory leak warning

### ISSUE THREAD

**Issue by jozsi** [recharts/recharts#264]
Hello,

I am using tens of Recharts on a page and I get the following warning:
`(node) warning: possible EventEmitter memory leak detected. 21 listeners added. Use emitter.setMaxListeners() to increase limit.`

I noticed that the [eventCenter maxListeners are raised to 20 from the default 10](https://github.com/recharts/recharts/blob/master/src/util/Events.js#L6). While many libraries set the value to `0` (unlimited; no warning), the best approach I've seen so far is [dynamically setting the limits](http://www.jongleberry.com/understanding-possible-eventemitter-leaks.html).

Any other idea?

**Comment by xile611** [comment]
@jozsi It's a good idea to dynamically set the maxListeners. And I wonder how many synchronized charts you created in a page ?

**Comment by jozsi** [comment]
@xile611 - none of them are synchronized.

**Comment by xile611** [comment]
@jozsi So, many charts in a single page?

**Comment by jozsi** [comment]
@xile611 - right, that's my use case. Many, unsynced charts on one page.

**Comment by xile611** [comment]
😀 OK! I'll fix this. And only add listener when the chart has props `syncId` which means to be synchronized with some other charts.
