### ISSUE TITLE
Bar chart not rendering bars with single data point

### ISSUE THREAD

**Issue by euvs** [recharts/recharts#2640]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-hc3kd?file=/src/index.js)

### Steps to reproduce
see sandbox

### What is expected?
Single bar is displayed

### What is actually happening?
Bar is not displayed 

| Environment | Info |
|---|---|
| Recharts | v2.1.2 |
| React | 1 |
| System | mac |
| Browser | chrome |

---
Broken in v2.1.2. 
Works in v2.0.8.

**Comment by ckifer** [comment]
This is fixed in the latest
