### ISSUE TITLE
Is it possible to apply a 'shadow' or hover CSS to a pie chart when mouse enter?  I want to show that the chart is selectable?

### ISSUE THREAD

**Issue by bhutchison** [recharts/recharts#2643]
Basically title,

I want to show that the pie chart is selectable when the user hovers over it but there doesnt seem to be an option for this?

The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.

---

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

**Comment by bnmcintosh** [comment]
Recharts is built on SVGs which you can apply drop shadows to. You could perhaps do something like this:
`.recharts-pie:hover {
  -webkit-filter: drop-shadow(10px 10px 4px #9e41b1);
  filter: drop-shadow(10px 10px 4px #9e41b1);
}`

Drop shadow isn't supported in IE though, so I would recommend looking at the specs for it before using.

**Comment by cacode-euan** [comment]
> Recharts is built on SVGs which you can apply drop shadows to. You could perhaps do something like this: `.recharts-pie:hover { -webkit-filter: drop-shadow(10px 10px 4px #9e41b1); filter: drop-shadow(10px 10px 4px #9e41b1); }`

Is it possible to apply the drop shadow to a specific sector of the pie?
