### ISSUE TITLE
AreaChart - area is not filled to the bottom when domain dataMin is negative

### ISSUE THREAD

**Issue by ryancrunchi** [recharts/recharts#2644]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/simple-area-chart-forked-vu0ls)

### Steps to reproduce
- Create an AreaChart

- Add YAxis with negative domain dataMin

- Add Area to fill bellow curve

### What is expected?
Area is filled to the bottom of the chart (until XAxis) and should take into account dataMin domain

### What is actually happening?
Area is filled only to 0. If dataMin < 0, the area between 0 and dataMin is not filled.

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 17.0.1 |
| System | macOS 11.3 |
| Browser | Chrome 93.0.4577.63 |

**Comment by akamfoad** [comment]
You can set `baseValue` prop on `AreaChart` to desired base value, and it'll work. Look at this Fork of your [CodeSandbox
](https://codesandbox.io/s/simple-area-chart-forked-tds0l)

Found out by digging into the source code
https://github.com/recharts/recharts/blob/1a452a291b0f5b95ff0e11bed3f0143210e4495f/src/cartesian/Area.tsx#L121
