### ISSUE TITLE
set font weight / color of one specific Label on X or Y Axis differently?

### ISSUE THREAD

**Issue by ToJuHB** [recharts/recharts#2645]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
At the moment I struggle with marking Labels of an "active item", which are displayed alongside Labels of inactive items, differently with different color and font weight in the X (or Y) Axis.

For Example in the first Bar Chart Example I would like to display "Page A" bold and red, but "Page B", "Page C" and the rest normal and grey.
https://recharts.org/en-US/api/BarChart

How would it be able to achieve that?
And if it would not be supported at the moment could there be a feature using payload similar to the Legend Component?

### What does the proposed API look like?
Add a payload prop to X and Y Axis Components to iterate through items and set styles individually.

**Comment by ckifer** [comment]
This can be done by getting the active index from a mouse event and saving it in state then passing it to a custom tick
