### ISSUE TITLE
Charts within React.Fragment not rendered

### ISSUE THREAD

**Issue by ymoon715** [recharts/recharts#2647]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
For Line component, if rendered within a react fragment, it is not rendered
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

To reproduce, contain the Line or Area within a react.fragment

## What is the expected behavior?

Charts not rendering

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Most recent recharts version, 2.1.2, and having issues on google chrome

**Comment by ckifer** [comment]
This should work in 3.0, going to resolve for now
