### ISSUE TITLE
ReDoS vulnerability introduced with d3-color@2.0.0

### ISSUE THREAD

**Issue by ktomascz** [recharts/recharts#2648]
The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.

Hi, 
our system reports ReDoS vulnerability introduced with d3-color@2.0.0.
Would it be possible to update the dependency to d3-color@3.0.0, in which this is supposedly solved?

Can we override this dependency locally? 

Thank you. 
-Kamil

---

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

**Comment by trmpowell** [comment]
Hi, @arcthur. You look pretty active on this repo. Has anyone had a chance to review this issue?

**Comment by superwesker1988** [comment]
Can someone take a look at this issue? It is causing quite a lot of issue if some of the upstream packages are using `rechart`

**Comment by ktomascz** [comment]
Forcing resolutions can be used as a possible workaround, however it is not an ideal one.
Updating all risky dependencies would be.

**Comment by superwesker1988** [comment]
@ktomascz I think it would work if the consumers would do that manually. If we would like to publish a package with rechart as a dependency, then all our consumers would need to do that and that is the challenge we are facing unless there is a workaround for that I didn't know of.

**Comment by ckifer** [comment]
Closing this in favor of https://github.com/recharts/recharts/issues/3012

https://github.com/recharts/recharts/pull/3120 should be merged soon
