### ISSUE TITLE
Tooltip crashing Chrome.

### ISSUE THREAD

**Issue by RobiFerentz** [recharts/recharts#265]
Apparently, after the first few tooltips are shown on hover, the next hover (in my case usually the 8th or 9th time) will get the 'Aww, snap' crash.

**Comment by RobiFerentz** [comment]
Example code: 
`import React, { Component } from 'react';
import { LineChart, Line, YAxis, XAxis, Tooltip } from 'recharts';

export default class StatisticsView extends Component {
  data = [
    {
      "hash": 4,
      "day": "1"
    },{
      "hash": 5,
      "day": "2"
    },{
      "hash": 6,
      "day": "3"
    },{
      "hash": 4,
      "day": "4"
    },{
      "hash": 3,
      "day": "5"
    },{
      "hash": 7,
      "day": "6"
    },{
      "hash": 11,
      "day": "7"
    },{
      "hash": 5,
      "day": "8"
    },{
      "hash": 6,
      "day": "9"
    },{
      "hash": 4,
      "day": "10"
    }, {
      "hash": 1,
      "day": "11"
    },
  ];
  render() {
    return (
      <LineChart data={this.data} width={1280} height={300}>
        <Line dataKey="hash" stroke="#000000" />
        <YAxis/>
        <XAxis dataKey="day"/>
        <Tooltip/>
      </LineChart>
    );
  }
}`

**Comment by xile611** [comment]
@RobiFerentz How about the version of chrome ?

**Comment by RobiFerentz** [comment]
Right, sorry. 
54.0.2840.34 beta (64-bit)

On OSX.

Does the same thing on canary.

**Comment by xile611** [comment]
Ok!

**Comment by SpaceK33z** [comment]
Can confirm, I'm also having this problem in Chrome 54 beta (OSX).

**Comment by guzmonne** [comment]
I am also having the same problem with Chrome Version 54.0.2840.59 (64-bit).

This is the component that causes issues:

```javascript
<LineRechart 
  width={WIDTH} 
  height={HEIGHT} 
  data={data}
  margin={{top: 10, right: 30, left: 0, bottom: 0}}
>
  <XAxis dataKey="name"/>
  <YAxis/>
  <CartesianGrid strokeDasharray="3 3"/>
  <Tooltip/>
  <Line type='monotone' dataKey='pv' stroke='#82ca9d' fill='#82ca9d' />
</LineRechart>
```

If I remove the `<Tooltip />` component the error goes away.

**Comment by ArnoBuschmann** [comment]
Same here, Chrome version is 54.0.2840.50 beta (64-bit) on Ubuntu 16.04.1 LTS.
Aside of that I just want to say, this is an awesome project, thanks for creating it!

**Comment by marknv** [comment]
We also just find this problem today on my chrome version is 54.0.2840.59 (OSX). Another guy uses
 firefox on linux as the below black boxes lag issue.

![screenshot from 2016-10-19 17_09_17](https://cloud.githubusercontent.com/assets/3892004/19573208/e29c8d18-96ca-11e6-9d0c-0721f0c76e26.png)

**Comment by richardgoater** [comment]
Fwiw, the crash happens for me on a line chart but not a scatter chart, where there is no tooltip animation. `animationActive={false}` didn't seem to have any effect, so granting the ability to disable animation on a line chart tooltip would really help me out.

**Comment by xiaody** [comment]
Same issue for me on Chrome 54.0.2840.71 (64-bit) mac OS. I'm sure it was good on Chrome 53.

Boot Chrome with `--enable-logging --v=1` and I see the following error in terminal:

```
#
# Fatal error in ../../v8/src/compiler/representation-change.cc, line 796
# RepresentationChangerError: node #367:NumberSign of kRepFloat64 ((MinusZeroOrNaN | Range(-1, 1))) cannot be changed to kRepWord32
#

==== C stack trace ===============================

    0   Google Chrome Framework             0x000000010852df63 ChromeMain + 15502163
    1   Google Chrome Framework             0x000000010852c8ed ChromeMain + 15496413
    2   Google Chrome Framework             0x0000000107fd8bfa ChromeMain + 9910250
    3   Google Chrome Framework             0x0000000107fd9cd0 ChromeMain + 9914560
    4   Google Chrome Framework             0x0000000107ff73f0 ChromeMain + 10035168
    5   Google Chrome Framework             0x0000000107ff5e3d ChromeMain + 10029613
    6   Google Chrome Framework             0x0000000107fe6e0c ChromeMain + 9968124
    7   Google Chrome Framework             0x0000000107fe6d8b ChromeMain + 9967995
    8   Google Chrome Framework             0x0000000107fbc5b6 ChromeMain + 9793958
    9   Google Chrome Framework             0x0000000107fbaeb8 ChromeMain + 9788072
    10  Google Chrome Framework             0x0000000107fba79d ChromeMain + 9786253
    11  Google Chrome Framework             0x0000000107ed2110 ChromeMain + 8834304
    12  Google Chrome Framework             0x0000000107ed4953 ChromeMain + 8844611
    13  Google Chrome Framework             0x0000000107ed3b44 ChromeMain + 8841012
    14  Google Chrome Framework             0x0000000108355532 ChromeMain + 13566242
    15  ???                                 0x00000ca435d063a7 0x0 + 13899417019303
```

So it seems a Chrome/V8 regression bug.

**Comment by istarkov** [comment]
The problem is not in Tooltip source, even we set an empty component with `displayName='Tooltip'` instead of current Tooltip it break the page.

**Comment by istarkov** [comment]
As a fast dirty fix, debouncing this code part https://github.com/recharts/recharts/blob/master/src/chart/generateCategoricalChart.js#L536-L537
with 100ms delay makes crash possibility very low.

**Comment by rogeliog** [comment]
I'm having the same issue. I have a `<BarChart />` and a custom tooltip.

* It only crashes in Chrome, I'm using (v54.0.2840.71)
* It only crashes when I'm in development mode, if I do a "release" build I can't make it crash.

**Comment by istarkov** [comment]
I also can't reproduce it in release mode and in any mode on Canary Chrome

**Comment by rogeliog** [comment]
Is there a workaround for this?

**Comment by arajajyothibabu** [comment]
I'm getting the same crash not only for Tooltip but also for resizing window.

**Comment by rogeliog** [comment]
@xile611 We really want to use recharts in production, but this crash is preventing us from doing so .:( Do you have any recommendations?

**Comment by xile611** [comment]
@rogeliog I can't reproduce the crash in both local examples and online examples. My chrome is 54.0.2840.71 (64-bit) (OSX). Do you have any idea to reproduce the crash ?

**Comment by magalhini** [comment]
Came here also looking for a solution, it seems that most charts are crashing for me after hovering/clicking around the charts for a few seconds. Looking at the timeline in DevTools, I'm thinking this is due to some memory leak somewhere, but since it crashes, I've been unable to trace it down!

Currently crashing on Chrome 54.0.2840.71 (64-bit), at least. Anyone has any leads?

**Comment by rhurkes** [comment]
I would recommend trying 0.15.3, as it contains a pr/fix to prevent CPU spikes with tool-tips.

https://github.com/recharts/recharts/pull/277

**Comment by magalhini** [comment]
@rhurkes I was running 0.15.3 already, but I actually found something interesting here. It seems that this behaviour only happens whenever I'm running in development mode, my fully compiled build seems to perform well and I can't get it to crash.

Looking at the `Tooltip.js` implementation, I see some checks for server side rendering, which are probably being checked on the development environment. Thinking this might be related, but I'll a bit more of a spike once I can get to this.

**Comment by xiaody** [comment]
Play with v0.16.0 and it no longer crashes for me.

**Comment by ArnoBuschmann** [comment]
Can't confirm, still crashing here with v0.16.0 :(

**Comment by matthewberkompas** [comment]
I just updated to version 0.16.1 and it's working fine.

**Comment by ArnoBuschmann** [comment]
Yay, 0.16.1 works great for me now as well. Thanks for the fix, whoever did it! :) :+1:

**Comment by StefanSchwartze** [comment]
Still experiencing this issue in v0.16.2.

**Comment by konstantin24121** [comment]
0.16.1 fix problem

**Comment by StefanSchwartze** [comment]
Okay, completely reinstalled recharts, now works fine. Thank you!

**Comment by elnygren** [comment]
after installing `0.17.1` from npm this problem actually got **worse**.

Also, it is not just the "tooltip" that crashes chrome, just quickly changing the data source and redrawing the graph alone is enough to crash chrome. Before updating from `0.13.4` this problem was pretty hard to reprocude (had to redraw the graphs a lot until crash) - now switching the data just a couple times is enough for a crash.

A screenshot of my use case: 

![Image of Dashboardh](https://i.imgur.com/XNoFcb3.png)

Clicking daily will almost surely crash the current tab as there are a lot of data points.

MacOS 10.12.1
Chome Version 54.0.2840.71 (64-bit)

**Comment by xile611** [comment]
@elnygren I want to confirm if the crash only happens in your local development mode ? I create a [jsfiddle demo](http://jsfiddle.net/jnz2pvze/)  which render a large number of points. But it never crash.

**Comment by elnygren** [comment]
@xile611 I'm using `NODE_ENV=production webpack` for building my project and the problem is still there. I'm gonna try adding the minified version directly without going throuh my own webpack build pipeline.

This is how I init the charts:

```
<div style={{display: 'block', marginTop: '20px'}}>
  <LineChart data={data} height={220} width={graphWidth} margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
    <XAxis dataKey="name" />
    <YAxis/>
    <CartesianGrid stroke="#eee" strokeDasharray="5 5"/>
    <Legend />
    <Line type="monotone" dataKey="credits" stroke="#8884d8" />

  </LineChart>
</div>
```

**Comment by xile611** [comment]
@elnygren My chrome crashed sometimes in my local development mode. So I deleted `--hot` of webpack, chrome never crashed then.  I doubt the crash may cause by the hot updating of webpack.

**Comment by konstantin24121** [comment]
@xile611 true, without hot components works fine, but i have this problem only at Win, in Linux all fine with --hot too

**Comment by magalhini** [comment]
I've also experienced the issue on development mode only, especially with `--hot` enabled. Unfortunately, since I was using `react-create-app` for this, I had basically no control over the development execution :(

**Comment by xile611** [comment]
@konstantin24121 @magalhini I found several [memery leak](https://github.com/webpack/webpack/issues/1724) issues of webpack. For the crash problem, we can remove hot component of webpack temporarily, and wait for webpack developers to fix it.

**Comment by konstantin24121** [comment]
@xile611 I do not feel strong discomfort when i remove --hot because project on which I'm working on it is poorly configured and there is no hot-updated correctly. I think we can try webpack 2.*, maybe here this problem solved

**Comment by xile611** [comment]
@konstantin24121 Yeah, looking forward to stable webpack 2.x.

**Comment by elnygren** [comment]
Seems like the tooltip issue has been fixed... I've set up a new issue with an example project that demoes the crash. https://github.com/recharts/recharts/issues/341

**Comment by evisong** [comment]
I've met similar crash issue on Chrome for Mac Version 54.0.2840.71 (64-bit). In my case the hot-reload of webpack was never turned on, but it's still solved by adjusting webpack configuration.

My changes to webpack configuration (for production build): 
```js
devtool: false,
plugins: [
  new webpack.optimize.OccurenceOrderPlugin(),
  new webpack.DefinePlugin({
    'process.env': { 'NODE_ENV': JSON.stringify('production') }
  }),
  new webpack.optimize.DedupePlugin(),
  new webpack.optimize.UglifyJsPlugin({compress: {warnings: false, drop_console: true, dead_code: true}}),
  new webpack.optimize.AggressiveMergingPlugin(),
// ...
]
```
