### ISSUE TITLE
Hello! Maybe someone can help me

### ISSUE THREAD

**Issue by HelloWorld537** [recharts/recharts#2652]
Hello. I must make this chart

![image](https://user-images.githubusercontent.com/60060857/133088436-85205171-4b0c-4ed0-bfff-1a14d72cad80.png)

now i have this

![image](https://user-images.githubusercontent.com/60060857/133088498-ce4f5da4-63bd-4931-b58c-9a7119694cd7.png)

1) How i can decrease space between bottom month text
2) How i can  shift the origin for points without moving the line. To start the first point with an indent, for example, 20 pixels
3) How i can customize vertical line

Thank you very much for any information

**Comment by ckifer** [comment]
Closing this as stale. Please comment back if you need answers to these questions
