### ISSUE TITLE
d3-shape => Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by alithecodeguy** [recharts/recharts#2658]
I used recharts regularly before but since this morning , i got this error when i try to build the nextjs app : 

> Build error occurred
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/**/**/node_modules/d3-shape/src/index.js
require() of ES modules is not supported.
require() of /Users/**/**/node_modules/d3-shape/src/index.js from /Users/**/**-

I updated node and nextjs but there is no luck.

node version : 14.17.6
nextjs version : 11.1.2
recharts version : 2.1.3

update : downgrade to 2.1.2 resolved the issue

**Comment by apancutt** [comment]
See thread [here](https://github.com/recharts/recharts/commit/3115b4d869042f7daf94a267117f75adc5049e23#r56692229)

**Comment by arcthur** [comment]
https://github.com/d3/d3-format/issues/114 you can see this

**Comment by brc-dd** [comment]
Literally none of things mentioned in that thread or the linked issue are working on Next.js `v11.1.3-canary.24`. Here is all that I have tried (and in almost every sensible combination):

* Update `browserslist` to `["> 0.5%", "not dead"]` (earlier had `[">0.3%", "not ie 11", "not dead", "not op_mini all"]`, don't know how switching to `0.5` would have even worked).

* Update webpack config to [this](https://github.com/d3/d3-format/issues/114#issuecomment-826338584) (although it needs to be modified for webpack-5).

* Used `next-transpile-modules` for both `recharts` and `d3-shape`.

* Set `experimental.esmExternals` to `'loose'`.

The only thing that's left is using `next/dynamic`. But for importing `Bar, BarChart, CartesianGrid, Legend, Tooltip, XAxis, YAxis`, I'll have to write 7 dynamic imports. 😕 Downgrading to `2.1.2` appears as the only feasible option.

**Comment by arcthur** [comment]
I'm revert d3 version, and try again.

**Comment by apancutt** [comment]
Fixed now. Thanks.

**Comment by apancutt** [comment]
PR #2707 reintroduces this issue.

**Comment by apancutt** [comment]
Fixed in 2.1.8

**Comment by rohasplit** [comment]
`2.1.13` re-introduces this. Reverting to `2.1.12` fixes the issue.

**Comment by MauricioHernanCabrera** [comment]
> `2.1.13` re-introduces this. Reverting to `2.1.12` fixes the issue.

This work for me although I recommend to remove ^

**Comment by talha-ah** [comment]
> `2.1.13` re-introduces this. Reverting to `2.1.12` fixes the issue.

Worked for me too!

**Comment by monsieurnebo** [comment]
Same issue with `2.1.13` over here.

Downgrading to `2.1.12` is fixing the issue, but awaiting for a fix in future version :)

**Comment by Mehmet-Erdem-Akin** [comment]
I changed the version to `2.1.13 => 2.1.12`  and it worked for next.js.

**Comment by agos** [comment]
this should be reopened, 2.1.13 has an unintended breaking change!

**Comment by debarshi-banerjee01** [comment]
Same here adding a snippet of package.json
```
{
  "name": "recharts-example",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "12.2.5",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "recharts": "^2.1.13"
  },
  "devDependencies": {
    "eslint": "8.23.0",
    "eslint-config-next": "12.2.5"
  }
}
```

**Comment by dariolongo** [comment]
`2.1.14` also have the problem.

**Comment by ax0n-pr1me** [comment]
also fixed by reverting to 2.1.12 for now.

**Comment by nyg** [comment]
I'm also having this issue with my Next.js app.

```
error - Error [ERR_REQUIRE_ESM]: require() of ES Module /myproject/node_modules/d3-shape/src/index.js from /myproject/node_modules/recharts/lib/shape/Symbols.js not supported.
Instead change the require of index.js in /myproject/node_modules/recharts/lib/shape/Symbols.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/myproject/node_modules/recharts/lib/shape/Symbols.js:14:16)
    at Object.<anonymous> (/myproject/node_modules/recharts/lib/component/DefaultLegendContent.js:16:16)
    at Object.<anonymous> (/myproject/node_modules/recharts/lib/component/Legend.js:16:29)
    at Object.<anonymous> (/myproject/node_modules/recharts/lib/index.js:317:15)
    at Object.recharts (/myproject/.next/server/pages/index.js:800:18)
    at __webpack_require__ (/myproject/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./components/yield/yield-chart.js:13:66)
    at Function.__webpack_require__.a (/myproject/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./components/yield/yield-chart.js:1:21)
    at Object../components/yield/yield-chart.js (/myproject/.next/server/pages/index.js:132:1)
    at __webpack_require__ (/myproject/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.js:10:87)
    at Function.__webpack_require__.a (/myproject/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./pages/index.js:1:21)
    at Object../pages/index.js (/myproject/.next/server/pages/index.js:352:1)
    at __webpack_require__ (/myproject/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/myproject/.next/server/pages/index.js:821:39)
    at /myproject/.next/server/pages/index.js:822:28
    at Object.<anonymous> (/myproject/.next/server/pages/index.js:825:3)
    at Object.requirePage (/myproject/node_modules/next/dist/server/require.js:58:12)
    at /myproject/node_modules/next/dist/server/load-components.js:56:50
    at runMicrotasks (<anonymous>)
    at async Promise.all (index 2)
    at async Object.loadComponents (/myproject/node_modules/next/dist/server/load-components.js:53:49)
    at async DevServer.findPageComponents (/myproject/node_modules/next/dist/server/next-server.js:451:36) {
  code: 'ERR_REQUIRE_ESM',
  page: '/'
}
```

**Comment by kodermax** [comment]
the same!

**Comment by wottpal** [comment]
same issue

**Comment by RishikeshDarandale** [comment]
With `2.1.12` - `npm audit` is failing...

```
node_modules/d3-color
  d3-interpolate  0.1.3 - 2.0.1
  Depends on vulnerable versions of d3-color
  node_modules/d3-interpolate
    d3-scale  0.1.5 - 3.3.0
    Depends on vulnerable versions of d3-interpolate
    node_modules/d3-scale
      recharts  0.2.0 - 2.1.6 || 2.1.8 - 2.1.12
      Depends on vulnerable versions of d3-interpolate
      Depends on vulnerable versions of d3-scale
      node_modules/recharts

4 high severity vulnerabilities
```

When we can expect a fix?

**Comment by RishikeshDarandale** [comment]
@semoal Can you please reopen this one?

**Comment by luckyxhu** [comment]
same issue in remix app.

**Comment by RishikeshDarandale** [comment]
@arcthur , Can you please take look at this issue? Thanks.

**Comment by talatkuyuk** [comment]
I suffered with the same issue (using recharts@^2.1.4 with Next.js v12.3.1)

I solved it by using dynamic import.

**Before:** I would imported the component which uses **recharts**
```js
import Chart from "features/dashboard/Chart";
```
**Now:** Using `dynamic import`
```js
import dynamic from "next/dynamic";

const Chart = dynamic(() => import("features/dashboard/Chart"), { ssr: false });
```
(_I did not add webpack configuration into the config file._)

This solved my problem; hope helps you.

**Comment by ckifer** [comment]
This change was reverted in 2.1.15, please upgrade to the latest. 

Please watch for the merging and release of #3120 for a non breaking change that will resolve the d3 security vulnerability. 

Going to close this as completed since this change was reverted.
