### ISSUE TITLE
Barchart x/yAxis label/unit not displaying?

### ISSUE THREAD

**Issue by patryk0605** [recharts/recharts#266]
Using the following snippet:

``` jsx
<BarChart data={initialData} >
   <XAxis dataKey="name" label="Devices"/>
   <YAxis unit="MB"/>
   <CartesianGrid strokeDasharray="3 3"/>
   <Tooltip/>
   <Legend />
   <Bar dataKey="used" stackId="a" fill="#8884d8" unit=" MB" />
   <Bar dataKey="available" stackId="a" fill="#82ca9d" unit=" MB" />
</BarChart>
```

`label` on the `XAxis` is not rendering and neither is `unit` on the `YAxis`. Am I doing something wrong? The following is an example render: 

![image](https://cloud.githubusercontent.com/assets/7227636/18751544/6db1d9e6-80ad-11e6-94ac-b00fd940269e.png)

**Comment by xile611** [comment]
@patryk0605 `unit` is only used to render `Tooltip` now.

**Comment by patryk0605** [comment]
@xile611 Thanks for your response. What about the `label` in the `XAxis`?

**Comment by xile611** [comment]
`label` of `XAxis` just display the content you passed to.

**Comment by patryk0605** [comment]
`label` of `XAxis` is not working as expected here. For example, in the [ComposedChartWithAxisLabels](http://recharts.org/examples#ComposedChartWithAxisLabels) example: **Pages** is showed on the `XAxis` and **Index** is showed on the `YAxis`. In my initial post, I want my `XAxis` to show the label **Devices** at the end, however nothing is showing. Does `label` on the `XAxis` not work with a `BarChart`?

**Comment by xile611** [comment]
@patryk0605 Can you create a jsfiddle demo ?

**Comment by patryk0605** [comment]
In this example: http://jsfiddle.net/patryk0605/akpt76jg/

I set `label="Devices"` in `<XAxis dataKey="name" label="Devices"/>`, however there is no label showing on the x-axis.

**Comment by kenhoff** [comment]
Was able to make some progress by adding `margin={{top: 20, right: 80, bottom: 20, left: 20}}` to my `<BarChart>` component, similar to how the ComposedChartWithAxisLabels does it above. Def not ideal, but at least it's a start.

**Comment by patryk0605** [comment]
Seems like this issue is related with #308 where the right is being cut off.

**Comment by xile611** [comment]
@patryk0605  Maybe you can change the position of label to insure the label to be showed.

**Comment by muhgumus** [comment]
<XAxis dataKey="name"  tick={<CustomizedAxisTick />} interval={0} />

set interval={0}
