### ISSUE TITLE
Documentation styling bug on small width screens

### ISSUE THREAD

**Issue by Shannanigans** [recharts/recharts#2671]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
Vertical monitor
[https://recharts.org/en-US/examples](https://recharts.org/en-US/examples)

Docked on ultra
![image](https://user-images.githubusercontent.com/15245035/135107899-754acb0d-c656-40a0-b04a-bd5a25aee262.png)

### Steps to reproduce
One of my monitors is vertically aligned, another is an ultra wide. The documentation site is a poor viewing experience on both. The issue is only present on the ultra when the browser display the documentation is docked to one side. Either way the documentation site handling of medium viewport widths can be improved.

![image](https://user-images.githubusercontent.com/15245035/135107810-61830c61-4052-4eb1-ae9a-3239baad9c80.png)

### What is expected?
I would expect that the recharts site is better able to make use of the available space on medium viewports.

### What is actually happening?
The example code block is consuming all available space, which collapses the chart example. The chart and code also at times overflow into the left hand nav items list. The github and locale options need to be scrolled horizontally in order to access them, the top appbar does not extend fully and so the links are rendered in the overflow outside of the navbar.

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | NA |
| System | Ubuntu |
| Browser | Chrome |

---
Thanks for the clean and simple lib it is generally a pleasure to work with.

**Comment by jarodsim** [comment]
We also have this issue.

**Comment by ckifer** [comment]
its not perfect but this currently looks a lot better than it did on a vert monitor 
![image](https://github.com/recharts/recharts/assets/25180830/79f78c06-de36-4119-85b0-cbb3495f5892)


Going to close this - if adjustment is still needed please open a new issue over at https://github.com/recharts/recharts.org
