### ISSUE TITLE
Variable Radius Pie Chart

### ISSUE THREAD

**Issue by catmando** [recharts/recharts#2676]
Is it possible to make a variable radius pie chart?

I.e. where each segment has a different radius?

I tried using the Cell component and setting outerRadius in each cell.  Did not work.

I guess this is the same as #1873, but its not clear how the solution works or if it even works for a static area

**Comment by jdnichollsc** [comment]
It looks like we need to use Victory lib instead: https://formidable.com/open-source/victory/docs/victory-pie#labelradius

**Comment by ckifer** [comment]
implemented here https://github.com/recharts/recharts/pull/5244 will be released in 3.x

closing in favor of https://github.com/recharts/recharts/issues/5224
