### ISSUE TITLE
Recharts Line dot not working properly with type="basis"

### ISSUE THREAD

**Issue by Imran-S-heikh** [recharts/recharts#2680]
"recharts": "^2.1.4"
"react": "^17.0.
![Screenshot from 2021-10-11 01-43-11](https://user-images.githubusercontent.com/52422304/136710881-6e8c50a3-9e02-4296-9368-162a6b243f4a.png)
2"

**Comment by uvarov-frontend** [comment]
Looks like a bug, but it's the correct behavior for this type. Yesterday I was puzzled. You can read here:https://github.com/d3/d3-shape/blob/main/README.md#curveBasis

**Comment by ckifer** [comment]
closing as this is not a bug
