### ISSUE TITLE
After upgrading from 2.1.4 to 2.1.5 "eslint-plugin-import" reports an "import/no-unresolved" error

### ISSUE THREAD

**Issue by doberkofler** [recharts/recharts#2688]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/doberkofler/sr-recharts](https://github.com/doberkofler/sr-recharts)

### Steps to reproduce
npm i
npm test

### What is expected?
No eslint errors like when using 2.1.4

### What is actually happening?
/Users/doberkofler/MyDev/doberkofler/sr-recharts/src/index.ts
  1:25  error  Unable to resolve path to module '			'  import/no-unresolved

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 17.0.2 |
| System | macOS 11.6 |
| Browser | Chrome 94 |

**Comment by Semigradsky** [comment]
I think `tsc` npm script should be added to `build`.

**Comment by mmakarin** [comment]
@Semigradsky do you plan to release this any time soon?

**Comment by Philipp91** [comment]
Thanks for the release! It works (pinging this thread so that others know it's done).
