### ISSUE TITLE
Clip high values plotted to only showing top area

### ISSUE THREAD

**Issue by 10n6** [recharts/recharts#269]
I'm not sure if there is functionality in already but I don't understand it. I have a section of figures in an array that start at say 380,000 and range to 410,000. The graph needs to fit into a small area but when I plot it the line looks almost flat. Is there a way of clipping the display start point so the graph does not look like a flat line and can show the top portion of the data in the graph and any fluctuation within that top area?

**Comment by xile611** [comment]
@10n6 You can set the domain of `YAxis`  to be `['dataMin', 'dataMax']` which have default value `[0, `auto`]`.

[Here](http://recharts.org/api#YAxis) is the document of YAxis.

**Comment by 10n6** [comment]
Thanks very much will give that a try today. Love the module btw.

**Comment by 10n6** [comment]
Works a treat thanks :)
<img width="355" alt="screenshot 2016-09-26 14 54 20" src="https://cloud.githubusercontent.com/assets/5984529/18836772/53a073ec-83f9-11e6-907c-68acbe43d491.png">
