### ISSUE TITLE
Charts error when Axis used  styled-components

### ISSUE THREAD

**Issue by Krong1997** [recharts/recharts#2694]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/charts-error-when-axis-used-styled-components-wd8vv?file=/src/barChart.js:196-1071)

### Steps to reproduce
1. import styled-components
2. import recharts
3. use styled-components try to change XAxis or YAxis style
like as follow
```js
import styled from "styled-components";
import { BarChart, Bar, XAxis, YAxis } from "recharts";

const BarChartStyled = styled(BarChart)``; // styled components can use
const XAxisStyled = styled(XAxis)``; // Axis collocation styled components maybe have some error
const YAxisStyled = styled(YAxis)``;

export const CustomBarChartError = (props) => {
  const { width, height, data } = props;
  return (
    <BarChartStyled width={width} height={height} data={data} layout="vertical">
      <XAxisStyled type="number" dataKey="value" />
      <YAxisStyled type="category" dataKey="title" width={100} />
      <Bar dataKey="value" fill="#8884d8" />
    </BarChartStyled>
  );
};

```
4. chart will error when used XAxisStyled  or YAxisStyled 

### What is expected?
styled-components can change Axis style and normal render charts

### What is actually happening?
In normal circumstances, the bar chart will show 5 bar cells (There are 5 data items).
After I used bar chart and styled-components try to change Axis style.
The bar chart only show the lasted bar cell and Axis can't display

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 17.0.2 |
| System | WIN10 |
| Browser | Microsoft Edge V 94.0.992.50 |

**Comment by rnarcos** [comment]
Recharts has it's own way to determine / mapping through the children recharts' components (**findAllByType**). It does that by filtering using the desired Recharts' components **_displayName_** property.

If you want to use styled-components with your Recharts components, you should use it like this:

```jsx
import styled from "styled-components";
import { BarChart, Bar, XAxis, YAxis } from "recharts";

const BarChartStyled = styled(BarChart)``; // styled components can use
BarChartStyled.displayName = BarChart.displayName;

const XAxisStyled = styled(XAxis)``; // Axis collocation styled components maybe have some error
XAxisTyled.displayName = XAxis.displayName;

const YAxisStyled = styled(YAxis)``;
YAxisTyled.displayName = YAxis.displayName;

export const CustomBarChartError = (props) => {
  const { width, height, data } = props;
  return (
    <BarChartStyled width={width} height={height} data={data} layout="vertical">
      <XAxisStyled type="number" dataKey="value" />
      <YAxisStyled type="category" dataKey="title" width={100} />
      <Bar dataKey="value" fill="#8884d8" />
    </BarChartStyled>
  );
};
```

**Comment by rnarcos** [comment]
Although that does work in some cases, I did not find it to work using **Line** and **ReferenceLine** components.

**Comment by OmarOmeiri** [comment]
Fala @rnarcos, beleza? 

I have discovered a little workaround that could styles lines with `styled-components`.
Check it [here](https://codesandbox.io/s/funny-mountain-zlo54o).

**Comment by ckifer** [comment]
Going to close this, upcoming macro plans should resolve these issues
