### ISSUE TITLE
Please add hyperlinks to issues/PRs in CHANGELOG.md

### ISSUE THREAD

**Issue by bobaekang** [recharts/recharts#2696]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/recharts/recharts/blob/master/CHANGELOG.md](https://github.com/recharts/recharts/blob/master/CHANGELOG.md)

### What is expected?
All referred issue/PR numbers are hyperlinked to the corresponding issues/PRs.

### What is actually happening?
No hyperlinks--only numbers. See image below:

<img width="680" alt="image" src="https://user-images.githubusercontent.com/22449454/138352460-e0cee988-c022-44a0-86cf-42981a1da475.png">

**Comment by ckifer** [comment]
Moved everything into GH releases

Closing this https://github.com/recharts/recharts/releases
