### ISSUE TITLE
Could not find a declaration file for module 'recharts'

### ISSUE THREAD

**Issue by botre** [recharts/recharts#2698]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/botre/recharts-repro](https://github.com/botre/recharts-repro)

### Steps to reproduce
Install the latest version in a Typescript project and try to compile to JS

### What is expected?
The type-checking/compilation happens without any errors

### What is actually happening?
TS7016: Could not find a declaration file for module 'recharts'. ' Try `npm i --save-dev @types/recharts` if it exists or add a new declaration (.d.ts) file containing `declare module 'recharts';`

| Environment | Info |
|---|---|
| Recharts | v2.1.5 |
| React | React 17.0.2 |
| System | Windows |
| Browser | Any |

---
Does not happen on v2.1.4, only since v2.1.5

**Comment by cle-skov-dk** [comment]
Fixed in v2.1.6 https://github.com/recharts/recharts/blob/master/CHANGELOG.md#216-oct-26-2021
