### ISSUE TITLE
LineChart switch curved 

### ISSUE THREAD

**Issue by bkniffler** [recharts/recharts#27]
Hey, 
I'm wondering if there is / will be a possibility to choose if lines are curved between points. 
The default behaviour now seems to be true for horizontal and false for vertical.

**Comment by xile611** [comment]
You can set the props `type` to be `monotone `, just like the following example

```
   <Line type="monotone" dataKey="pv" stroke="#8884d8" />
```

The props `type` of Line means the interpolation used to generate the curve.
We will optimize the api document in the few days.

**Comment by bkniffler** [comment]
Strange, it didn't work at first, but after the change and a server restart it does. 
Indeed, the API documentations need a bit of improvement, I've found the `formatter` prop that some components got very useful, though these are not documented. 

But I understand recharts is still young, can't wait to see it become more mature. Keep it up! Recharts already is a great library!

**Comment by findela** [comment]
Is there any
![FireShot Capture 343 - Coronavirus Outbreak in India - covid19india org - www covid19india org](https://user-images.githubusercontent.com/8926058/89321860-147c7180-d6a1-11ea-98be-eef7d03fe2d4.png)
 way to have this likewise which doesn't solves by monotone prop?
