### ISSUE TITLE
Show only x-y bullet Tooltip

### ISSUE THREAD

**Issue by QuevedoIB** [recharts/recharts#2700]
- *[x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://recharts.org/en-US/examples](https://recharts.org/en-US/examples)

### Steps to reproduce
Hover topside of the chart where there are no lines/bullets. (X: Page F / Y: 10000)

### What is expected?
Tooltip shouldn't appear

### What is actually happening?
Tooltip is appearing selecting line points.

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 17.0.2 |
| System | Windows  |
| Browser | Chrome 95.0.4638.54 |

---
This behaviour difficults working with scatter charts, many chart use cases require tooltip only to show when the bullet is hovered. (Prevent missleading information calculated automatically).

**Comment by ckifer** [comment]
closing in favor of other duplicate issues
