### ISSUE TITLE
Tooltip active state doesn't work properly

### ISSUE THREAD

**Issue by usahai** [recharts/recharts#2703]
- [x ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tooltip-position-recharts-forked-lvvsk?file=/src/App.js)

### Steps to reproduce
Hover over a bar, then move the mouse to just being on top of the bar. Then move the mouse to a smaller adjacent bar

https://user-images.githubusercontent.com/2849176/139423068-9ce9603e-d85b-4e9c-9d33-6d8459ab7d9e.mp4

.

### What is expected?
The active state is being toggled by the application (controlled) - when the mouse goes out of the immediate bar area, the onMouseLeave handler is fired, and the tooltip position data is set to undefined. If there is no data in the posData, the active state is set to false, which should hide the tooltip. This way, I can show the tooltip only when I am hovering over the actual bar

### What is actually happening?
The tooltip still shows, and as I hover on top of the other bars (not on the bars themselves, but in the grey area above it), the active state is still being fired, so the tooltip still shows. Moreover, it shows the data of the new bar that the mouse is hovering over, but since the onMouseEnter/onMouseOver is not fired, it shows the data on top of the old bar

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 17.0.2 |
| System | Windows |
| Browser | Chrome |

---
The controlled state of active should not allow the component to switch it internally. If the active state is not passed, then it should default to the internal workings

**Comment by HHongSeungWoo** [comment]
It seems like this issue has been resolevd

**Comment by ckifer** [comment]
closing as resolved
