### ISSUE TITLE
ResponsiveContainer - legend overlapping with chart when re-rendering

### ISSUE THREAD

**Issue by middiu** [recharts/recharts#2704]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/simple-line-chart-forked-hb7l9?file=/src/App.tsx)

### Steps to reproduce
Open the codesanbox attached.

The problem seems to be when the component status changes and the chart needs to refresh.
If the re-render is disabled than the legend is positioned correctly.

```
  useEffect(() => {
    setTest("");
  }, []);
```

### What is expected?
Legend position should be correct

### What is actually happening?
Legend overlapping with chart when re-rendering

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | reactjs 17 |
| System | all |
| Browser | all |

---
seems to be similar to issue https://github.com/recharts/recharts/issues/2636

But I'm using rechart 2.1.6 and the issue is still there

**Comment by leicht-io** [comment]
We also have this issue.

**Comment by jarodsim** [comment]
We also have this issue.

**Comment by Prior99** [comment]
I also have this issue.

**Comment by middiu** [comment]
any comment or feedback team?

**Comment by martindkayser** [comment]
We are also experiencing this issue.

**Comment by kfrane** [comment]
I've been bisecting through releases and it seems that the 2.0.3 release introduced this bug.
I hope this helps maintainers find the issue.

**Comment by semoal** [comment]
Yes, confirmed the bug was introduced in the 2.0.3 release where we migrated UNSAFE react methods to derivedState.

https://github.com/recharts/recharts/commit/29b793b33ea0c2c545b56710c4a82581c9a89831

Will mark it as a bug, and if someone wants to take a look, go ahead!

**Comment by hansott** [comment]
@semoal I might have a look at this later (probably in the coming days), was noticing this in our product. Thanks for your work on this library! ❤️

**Comment by arvidede** [comment]
I'm not entirely sure why or if it's the right way to go, but #2752 seems to fix it.

**Comment by ckifer** [comment]
This is fixed as of v2.1.9 - resolving as completed

**Comment by jarodsim** [comment]
> This is fixed as of v2.1.9 - resolving as completed

Thankssssss
