### ISSUE TITLE
<rect> attribute width: A negative value is not valid. ("-11")

### ISSUE THREAD

**Issue by shreyshreyansh** [recharts/recharts#2708]
Why recharts sets the width attribute of the chart to be negative whenever I hide a div which is containing the chart. It result it in throwing an error in react-dom.

**Comment by angelete1992** [comment]
I have the same problem when use css rotate. Anyone can help us? Thank you

**Comment by ckifer** [comment]
would need a reproduction in order to help with this

going to close as stale for now
