### ISSUE TITLE
Bug wrapping long axis labels

### ISSUE THREAD

**Issue by matthewberkompas** [recharts/recharts#271]
In `0.15.0`, there is a bug with wrapping long axis labels (**[Example on JSFiddle](http://jsfiddle.net/kca9npkg/44/)**):

<img width="585" alt="screen shot 2016-09-23 at 3 25 53 pm" src="https://cloud.githubusercontent.com/assets/7084294/18803100/1a30a996-81a2-11e6-812a-0413da972cc0.png">

Also note that the x-axis labels are incorrectly positioned.

#### Update:
Looks like the second issue has already been reported [here](https://github.com/recharts/recharts/issues/268).

The first problem is that Y-axis labels are positioned too high (the bottom of the label is at the tick mark instead of being centered).

**Comment by techniq** [comment]
Alignment issue will be resolved once https://github.com/recharts/recharts/pull/270 is merged

**Comment by matthewberkompas** [comment]
Fixed. Thanks a lot!
