### ISSUE TITLE
YAxis ticks are not equally spaced when using logarithmic scaling.

### ISSUE THREAD

**Issue by iamShashi** [recharts/recharts#2710]
### When using scale with logarithmic scaling as 
`scaleLog().domain([1, getHighestCord()]).range([0, 600]);`
### getHighestCord() returns a simple highest nth digit number.

Also using :
`domain={['auto', highestCordinateinDataset]} //highestCordinateinDataset returns the highest cordinate in the dataset.`

### The graphs yAxis should be equally spaced but is not spaced equally with unequal tickLine widths.

Recharts: '2.1.2'

**Comment by ckifer** [comment]
Closing this as stale

Please try using `scaleSymlog`
