### ISSUE TITLE
Stacked barChart- X axis label gets hidden if length of label text is higher

### ISSUE THREAD

**Issue by blueeDeveloper** [recharts/recharts#2712]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mixed-bar-chart-forked-gjuri)

### Steps to reproduce
1. Check the codesandbox link. I have named first label in Xaxis as 'Page A23' Due to the length of this label, the label is not displayed on screen. If i reduce the name of label to 'Page A', it displays fine. 
2. The same issue happens if we add angle={-50} to the `Xaxis`. 

### What is expected?
Expected to show all the labels irrespective of their length 

### What is actually happening?
clipping off or hiding the label whose length is higher. 

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 17.0.1 |
| System | MacBookPro14,3 |
| Browser | Chrome - Version 95.0.4638.69 |

**Comment by blueeDeveloper** [comment]
Can someone pls update on this

**Comment by nikolasrieble** [comment]
Not showing labels when they overlap is a feature. The bug that I see here is that the rotation does not affect the label visibility, i.e. when labels are rotated, they should be shown if they do not overlap.

**Comment by leomunizq** [comment]
nothing yet ?

**Comment by ckifer** [comment]
To add to this, there has been some changes that do take angle into account now. 

https://codesandbox.io/s/mixed-bar-chart-forked-msfmvc?file=/src/App.tsx

**Comment by karanVR** [comment]
just add interval = {0} in XAxis:

`<XAxis
            className="mt-8"
            dataKey={"name"}`

**Comment by Fanoflix** [comment]
@karanVR Ty, that worked for me.

**Comment by ckifer** [comment]
Solution for this has always been `interval={0}`. Recharts tries to do collision detection and avoid rendering things that will overlap with reach other. `interval={0}` forces everything to render.

Other `interval` values and adjusting with `angle` are also valid ways of handling this. 

Resolving this since I think `interval={0}` handles the spirit of this report

**Comment by sovetski** [comment]
For me the `interval` is not the solution, as you can see it just crop the text

![image](https://github.com/user-attachments/assets/f1b32f4b-448b-4617-9acd-8e8239c4b3a7)

**Comment by ckifer** [comment]
You need to add more margin right, its cutting off because the text is rendering outside the bounds of the svg

**Comment by Yurex12** [comment]
padding={{ left: 20, right: 20 }}

try this it should work
