### ISSUE TITLE
It was very hard to get to your website

### ISSUE THREAD

**Issue by ObadaElSharbatly** [recharts/recharts#2714]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I really like your npm it's amazing for me .. I think you duplicated the GitHub link inside recharts pkg in npm website then I was trying to figure out how to use your app but couldn't find the docs unlis I watched a youtube video and found your website link in the description

so I think it's better for you to put your website link in the Homepage field in npm website .. happy coding

### What does the proposed API look like?
great

**Comment by leicht-io** [comment]
Hi @ObadaElSharbatly,

It already exists in the package.json:
![image](https://user-images.githubusercontent.com/3056379/141977625-3e415a36-e66d-4db5-b414-d15d98372c39.png)

**Comment by ObadaElSharbatly** [comment]
![image](https://user-images.githubusercontent.com/15058781/141983878-43f4ed5e-a4f2-461c-9891-4ca7dc3ec092.png)

yeah great, but I meant this. I am still a junior actually that's why I didn't focus on GitHub .. so I think it's better for all beginners like me to be on npm itself if you can.

anyway good work and thanks
