### ISSUE TITLE
Add line to label and text to the center

### ISSUE THREAD

**Issue by abhigk** [recharts/recharts#2715]
I am working on the pie charts however I am not able to find anything in API to add
1. SVG line to label 
2. Text in the center

Current code in sandbox:
https://codesandbox.io/s/pie-chart-of-two-levels-forked-fld2m?file=/src/App.tsx
![Screen Shot 2021-11-16 at 2 11 05 pm](https://user-images.githubusercontent.com/9884510/141889059-a97311a7-892c-4ee3-afed-d582fa9610f9.png)

I want it like this
![WhatsApp Image 2021-11-16 at 10 34 00 AM](https://user-images.githubusercontent.com/9884510/141889338-caf26db8-491b-4559-8574-06f00224ca14.jpeg)

**Comment by celiaongsl** [comment]
Hey there! Hope I'm not too late to help, but this example might help you out: [https://recharts.org/en-US/examples/CustomActiveShapePieChart](https://recharts.org/en-US/examples/CustomActiveShapePieChart). You'll probably need to remove some lines of code depending on what you want your end goal to look like :)

**Comment by Suyama-Daichi** [comment]
refer this https://github.com/recharts/recharts/issues/191#issuecomment-314055792
