### ISSUE TITLE
How to add value as dataKey to XAxis

### ISSUE THREAD

**Issue by sayjeyhi** [recharts/recharts#2724]
I couldn't find a way to draw a regular XY chart using recharts, something like this:

<img width="290" alt="Screen Shot 1400-09-01 at 03 24 20" src="https://user-images.githubusercontent.com/6254009/142934546-c86079c5-f4f3-46e3-953c-ed054453dcae.png">

which has a `<XAxis>` with stepped values, instead of only labels.

**Comment by ckifer** [comment]
You can use `<XAxis type="number" allowDecimals />`

Resolving this as stale
