### ISSUE TITLE
The Graph can not display all the lines when the gap between min and max value is very large

### ISSUE THREAD

**Issue by SylvanasGone** [recharts/recharts#2727]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-efwf4?file=/src/index.js)

### Steps to reproduce
See the reproduce link

### What is expected?
The graph can show the whole lines

### What is actually happening?
It does not

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 17.0.2 |
| System | macOS 11.6 |
| Browser | Chrome 96.0.4664.55 |

**Comment by sakutaro220** [comment]
That's because value is a string.
It should be in number format.

**Comment by ckifer** [comment]
+1, please convert the values to numbers. Closing ad answered
