### ISSUE TITLE
Custom label in <ReferenceLine> is rendered inside SVG elements

### ISSUE THREAD

**Issue by jasonslyvia** [recharts/recharts#273]
``` javascript
<ReferenceLine
  key={index}
  label={<span>123</span>}
  stroke="#f2be35"
  x={key}
  isFront
/>
```

results in following dom structure:

![image](https://cloud.githubusercontent.com/assets/1336484/18890852/8adbbc94-8535-11e6-8f50-eceb900eeda4.png)

which is not allowed by SVG specs, and got wrong positioning at all.

**Comment by xile611** [comment]
When the `label` is a react element, we have no idea to check whether the element is a svg node or a dom node. Do you have any idea?
