### ISSUE TITLE
charts doesn't fill recharts surface

### ISSUE THREAD

**Issue by amapic** [recharts/recharts#2732]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://68.183.74.150:3001/planet](http://68.183.74.150:3001/planet)

### Steps to reproduce
Go to the link and search for RadialBarChart in React debugging menu, and check the code of the component in the additional comments

### What is expected?
The chartshould fill the space given to it

### What is actually happening?
The chart is small

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 17.0.2 |
| System | windows 20H2 |
| Browser | chrome 96.0.4664.45 |

---
Here's the code of the chart :
<ResponsiveContainer aspect={0.5}>
            <RadialBarChart  startAngle={270} endAngle={150} cx={"70%"} cy={"50%"}  barSize={"90%"} innerRadius={"10%"} outerRadius={"100%"}  data={items}>
                <RadialBar label={{ position: 'insideStart', fill: '#fff' }} dataKey="uv" />
            </RadialBarChart>
        </ResponsiveContainer >

AS you see, there's no absolute dimension but the aspect of the responsive container is for me not applied

**Comment by amapic** [comment]
Please ask me when you want to check the reproduction link, I will open it up

**Comment by semoal** [comment]
Please create a codesandbox where we can try to reproduce the issue and debug it.
