### ISSUE TITLE
Codesandbox examples and live editor not working properly

### ISSUE THREAD

**Issue by joeyfigaro** [recharts/recharts#2737]
- [X] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://recharts.org/en-US/examples](https://recharts.org/en-US/examples)

### Steps to reproduce
Update the source for SimpleLineChart and hit 'run' or visit any codesandbox example. The codesandbox examples are running into CORS issues.

### What is expected?
Hitting run after editing the source for a visualization should re-render/update the visualization properly. Codesandbox examples should render as expected.

### What is actually happening?
Examples in docs never update/render after an edit, and Codesandbox examples never render.

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | N/A |
| System | N/A |
| Browser | N/A |

**Comment by semoal** [comment]
Thanks for the issue. Will look at it as soon as possible :)

**Comment by Yilun-Sun** [comment]
Closes https://github.com/recharts/recharts.org/pull/239
