### ISSUE TITLE
Is it possible to create a chart from series of data?

### ISSUE THREAD

**Issue by tusharkhatiwada** [recharts/recharts#274]
Hi there,
I have a series of data that needs to be plot in a chart. The Y-Axis will be the `speed` of vehicle and the X-Axis will be the `time`. The data I have is the speed of the vehicle for every few seconds. What I want is to have X-Axis with 1 hour difference and Y-Axis to be the speed.

Something similar like this: 
http://www.highcharts.com/demo/line-time-series

Is it possible to create a one?

Thanks.

**Comment by sunny-g** [comment]
I'm attempting something very similar - I'd like to create a `BarChart` that'll render a variable number of bars on an x-axis that will always have 12 ticks (one for every month). Is this what a `CartesianAxis` is for?

**Comment by xile611** [comment]
I think we should support different scale functions of axis, like timeScale, logScale, etc, just similarly to [issue#305](https://github.com/recharts/recharts/issues/305).

So I'll close this issue temporarily.

**Comment by aesopwolf** [comment]
@xile611 I see over in https://github.com/recharts/recharts/issues/305 that you released a `scale` prop for the Axis components.

Would you mind sharing how that can be used to achieve a line chart of time series data?

Given the following data, how would we configure the x-axis to display only 2 labels (one for each month), but still plot each data point for each individual day?

```js
const data = [
  {name: 'Jan 01 2016', value: 2400},
  {name: 'Jan 02 2016', value: 2210},
  // etc...
  {name: 'Jan 31 2016', value: 2290},
  {name: 'Feb 01 2016', value: 2000},
  {name: 'Feb 02 2016', value: 2181},
  // etc...
  {name: 'Feb 28 2016', value: 2500},
];
```
