### ISSUE TITLE
No legend renderer on Dom after surcharging component with useLongPress package

### ISSUE THREAD

**Issue by SebFox2011** [recharts/recharts#2743]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-8hs74?file=/src/index.js)

### Steps to reproduce
Creating a LongPressLegend component with useLongPress hook componenent.
Following this lnk to implement a surcharged version of Legend rechart component: https://www.npmjs.com/package/use-long-press call as Legend in main file import

Finaly, inside a ResponsiveContainer and a ComposedChart, adding  this :
<Legend
onLongClick={()=>console.log('longClick')}
onClick={()=>console.log('Click')}/>

### What is expected?
The legend should be render like the version before implementing useLongPress wrapping

### What is actually happening?
The legend is not loading in the Dom

| Environment | Info |
|---|---|
| Recharts | v2.1.4 |
| React | 16.14.0 |
| System | Windows 10 |
| Browser | Chrome - Electron |

**Comment by semoal** [comment]
Any issue without reproduction repository/codesandbox or similar will be closed.

**Comment by SebFox2011** [comment]
I will update issue with a codeSand box demonstration. Please wait and don't delete issue

**Comment by SebFox2011** [comment]
Any news about ? Functionnality required for my dev.

**Comment by ckifer** [comment]
closing this as stale
