### ISSUE TITLE
Type 'null' is not assignable to type 'Record<string, (e?: Event | undefined) => any>' if tsconfig strict: true

### ISSUE THREAD

**Issue by zaandr** [recharts/recharts#2745]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/recharts/recharts/blob/master/src/util/types.ts#L1112](https://github.com/recharts/recharts/blob/master/src/util/types.ts#L1112)

### Steps to reproduce
src/util/types.ts - adaptEventHandlers, getEventHandlerOfChild, adaptEventsOfChild

### What is expected?
Correct types

### What is actually happening?
Error

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | react^17.0.2 |
| System | Windows 10,  PhpStrorm |
| Browser | - |

**Comment by ckifer** [comment]
this seems to be stale, going to resolve for now
