### ISSUE TITLE
YAxis scale=log not working when any value is 0

### ISSUE THREAD

**Issue by eduardcotmrf** [recharts/recharts#2748]
- [ x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-playground-forked-yohnq)

### Steps to reproduce
Create a graph that has values at zero in some field:
```js
const data2 = [
    {
      name: "Page A",
      uv: { value: 200, errors: [100, 200] },
      pv: { value: 2400, errors: [200, 100] }
    },
    {
      name: "Page B",
      uv: { value: 0, errors: [0, 0] }, // change value to something to render
      pv: { value: 4200, errors: [50, 200] }
    },
    {
      name: "Page C",
      uv: { value: 1600, errors: [50, 100] },
      pv: { value: 3200, errors: [100, 100] }
    }
  ];
```

And try to render with scale=log:

```js
<LineChart
      width={600}
      height={300}
      data={props.data}
      margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
    >
      <XAxis dataKey="name" />
      <YAxis domain={["auto", "auto"]} scale="log" />
      <CartesianGrid strokeDasharray="3 3" />
      <Tooltip />
      <Legend />
      <Line
        type="monotone"
        dataKey="pv.value"
        stroke="#8884d8"
        activeDot={{ r: 8 }}
        connectNulls={false}
      >
        <ErrorBar dataKey={`pv.errors`} width={4} strokeWidth={1.5} />
      </Line>
      <Line
        type="monotone"
        dataKey="uv.value"
        stroke="#82ca9d"
        connectNulls={false}
      >
        <ErrorBar dataKey={`uv.errors`} width={4} strokeWidth={1.5} />
      </Line>{" "}
    </LineChart>

```

### What is expected?
To render the line chart. 

### What is actually happening?
The line chart is not rendered when scale log and some values at 0.
Error in console `Warning: Received NaN for the `y1` attribute. If this is expected, cast the value to a string.` is being printed.

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | react 16 |
| System | any |
| Browser | any |

---
In the example attached you can find one grpah and one not working. The difference: a 0 value in PageB 'u' field.

**Comment by eduardcotmrf** [comment]
Actually fins a closed issue similar to this but not solved: https://github.com/recharts/recharts/issues/1107

**Comment by kraussian** [comment]
I can understand a log scale not displaying 0 values, since log(0) is infinity. So I was trying a workaround through a "pseudo-log" function, but I can't figure out how to use custom functions with the scale option.

https://github.com/recharts/recharts/issues/305#issuecomment-1001510752

**Comment by danatemple** [comment]
I would not consider this a bug. If you want to display data with a log scale, none of your values should be zero.
They also need to be of the same polarity, as a log scale can only show values with one sign, e.g. 

   0.001, 0.01, 0.1, 1, 10 ....

You can see that you will never get a zero or a negative value to fit on this scale. You probably need to re-think your visualization, if the values really are zero, filter them out, or put in some pre-checks.

**Comment by uazure** [comment]
That probably might be helpful as '[pseudo-log](https://github.com/recharts/recharts/issues/1107#issuecomment-1142259291)' solution

> I can understand a log scale not displaying 0 values, since log(0) is infinity. So I was trying a workaround through a "pseudo-log" function, but I can't figure out how to use custom functions with the scale option.
> 
> [#305 (comment)](https://github.com/recharts/recharts/issues/305#issuecomment-1001510752)

**Comment by ckifer** [comment]
This is due to the log function used by d3

use `scale="symlog"` to allow zero

https://d3js.org/d3-scale/symlog

> Unlike a [log scale](https://d3js.org/d3-scale/log), a symlog scale domain can include zero.
