### ISSUE TITLE
Way to add more data in tooltip

### ISSUE THREAD

**Issue by PavanKu** [recharts/recharts#275]
Hi,

I am using scatter chart and want to display some values which are present in scatter component's data props. Right now, it seems that tooltip's payload is constructed based on X Axis, Y Axis, Z Axis value. 

Will it be possible to show additional data in tooltip. It will be good if we get data of active scatter in tooltip so that we can write custom tool tip to show additional values.

**Comment by peterholmberg** [comment]
I'm also having an issue with this. Need to format the payload value into different currencies.

**Comment by sdoomz** [comment]
Seems like you can use custom renderer for [tooltip content](http://recharts.org/api/#Tooltip)
```
<Tooltip content={this.renderTooltip} />
```
and 
```
renderTooltip() {
  return (
   <div>Custom content</div>
  )
}
```

**Comment by peterholmberg** [comment]
Yes, but I want to add more props to a tooltip. 

 <Tooltip content={<PriceGraphTooltip product={product} />} />

The product object holds the currency, and I'd like to access it in the PriceGraphToolip

 return (
                <div className="custom-tooltip">
                    <p className="intro">{payload[0].value product.currency}</p>
                    <p className="intro">({label}) </p>
                </div>
            );

**Comment by sdoomz** [comment]
@peterholmberg You can add as much props as you need and access all with `this.props.propName` [example](http://jsfiddle.net/sdoomz/zefmfeks/)

If you don't know what kind of currency should be rendered for this dot just add `currency` property for each object in your `data` array. And display it with `payload[0].currency`

If your issue still is not resolved please create jsfiddle example

**Comment by SimiMilton** [comment]
I'm also having this issue with my barchart. My data format is as follows:
`const data = [{timestamp: '09:00', level: 0.4, height: 600, hasValue: true},];` 
The Bar's datakey is height and XAxis datakey is timestamp. While creating custom tooltip, I need to have access to level and hasValue info too. How could I do that? Inside the CustomTooltipClass render, I need something like this:
`const { payload, label } = this.props;
      return (
        <div className="custom-tooltip">
          <p className="intro">{this.getToolTipDesc(payload[0].value, label, timestamp, hasValue)}</p>
        </div>
      );`

**Comment by sdoomz** [comment]
@SimiMilton Hmm maybe you'r looking for something like this:
```
console.log(payload[0].payload.timestamp,  payload[0].payload.hasValue)
```

But to have payload inside payload array is not clear for me too.

**Comment by SimiMilton** [comment]
Awesome, that's what I was looking for. Thanks @sdoomz

**Comment by AriaFallah** [comment]
So I wanted to do the above, but keep the default tooltip. Here's how:

```js
// recharts doesn't export the default tooltip,
// but its located in the package lib so you can get to it anyways
import DefaultTooltipContent from 'recharts/lib/component/DefaultTooltipContent';

const CustomTooltip = props => {
  // payload[0] doesn't exist when tooltip isn't visible
  if (props.payload[0] != null) {
    // mutating props directly is against react's conventions
    // so we create a new payload with the name and value fields set to what we want
    const newPayload = [
      {
        name: 'Legislator Name',
        // all your data which created the tooltip is located in the .payload property
        value: props.payload[0].payload.name,
        // you can also add "unit" here if you need it
      },
      ...props.payload,
    ];
    return <DefaultTooltipContent {...props} payload={newPayload} />;
  }
  return <DefaultTooltipContent {...props} />;
};
```

This way, you still get everything the default tooltip has to offer (which is a lot), but still can add data to the payload.

**Comment by tommilligan-plutoflume** [comment]
Thanks @AriaFallah, this is just what I was after to remove a trendline from my tooltip.

This could be nicely encapsulated in a `payloadFormatter` prop, that would remove the need for an internal lib import. Following the same style as the more specific `labelFormatter`:

```js
const payloadFormatter = payload => {
  // remove series we want to be hidden
  return payload.filter(d => d.name !== 'y0');
};

<Tooltip payloadFormatter={payloadFormatter} />
```

I'll work up a PR this weekend.

**Comment by superhawk610** [comment]
Hopefully I can save some headache for anyone else who ends up here - @AriaFallah has the correct solution, but its naming is a bit unclear, since you're overriding the tooltip's *content*, not the entire tooltip. To use his solution, you need to apply it to your `Tooltip`'s `content` prop, like so

```js
// CustomTooltipContent.js
import DefaultTooltipContent from 'recharts/lib/component/DefaultTooltipContent';

const CustomTooltipContent = () => (/* @AriaFallah's solution */);

export default CustomTooltipContent;


// MyLineChart.js
import { LineChart } from 'recharts';
import CustomTooltipContent from './CustomTooltipContent';

const MyLineChart = () => (
  <LineChart>
    {/* ... */}
    <Tooltip content={<CustomTooltipContent />} />
  </LineChart>
);
```

**Comment by ike76** [comment]
fwiw, when you create a custom Tooltip like this:
`
<Tooltip content={ <MyCustomTooltip/> }/>
`

`
function MyCustomTooltip(props){
  console.log(props)
  return <div>{...your custom stuff}</div>
}
`
if you find that MyCustomTooltip's props.payload is an empty array, you're probably looking at it as it **Unmounts**.  (i.e. props.active === false)

**Comment by erosenberg** [comment]
@iketown - this is awesome because I was stuck on this too. Is there a good way to test this?

**Comment by mamal72** [comment]
The provided solution by @AriaFallah works perfect but it can be improved a bit both in coding style and correct use of provided props. Here's a simple improved version of the provided example:

```js
// recharts doesn't export the default tooltip,
// but it's located in the package lib so you can get to it anyways
import DefaultTooltipContent from 'recharts/lib/component/DefaultTooltipContent';

const CustomTooltip = props => {
  // we don't need to check payload[0] as there's a better prop for this purpose
  if (!props.active) {
    // I think returning null works based on this: http://recharts.org/en-US/examples/CustomContentOfTooltip
    return null
  }
  // mutating props directly is against react's conventions
  // so we create a new payload with the name and value fields set to what we want
  const newPayload = [
    {
      name: 'Name',
      // all your data which created the tooltip is located in the .payload property
      value: props.payload[0].payload.name,
      // you can also add "unit" here if you need it
    },
    ...props.payload,
  ];

  // we render the default, but with our overridden payload
  return <DefaultTooltipContent {...props} payload={newPayload} />;
};
```

**Comment by Vansompel** [comment]
I'm having an issue when importing DefaultTooltipContent with Typescript.
The error says: Could not find a declaration file for module 'recharts/lib/component/DefaultTooltipContent'. Installing @types for recharts didn't solve the problem. Anyone know how this can be fixed?

**Comment by burhanrashid52** [comment]
If I just need to concate the text then we can simply use this.
```javascript
<Tooltip formatter={(label) => label + " %"}/>
```

**Comment by hubertokf** [comment]
I'm trying to import `DefaultTooltipContent` from `import DefaultTooltipContent from 'recharts/lib/component/DefaultTooltipContent';`
But it is undefined. It was working until i upgraded recharts version

Now: 2.0.8
Before: 1.8.5

**Comment by hubertokf** [comment]
To anyone running through this. Just import like this:
```
import { DefaultTooltipContent } from 'recharts/lib/component/DefaultTooltipContent';
```

**Comment by lalosh** [comment]
### To edit only the values, use the `formatter` props

```js
<Tooltip formatter={(value, name, props) => transformNumberWithCommas(Number(value))} />
```

To check for the latest props names and options, check the API https://recharts.org/en-US/api/Tooltip

**Comment by omarryhan** [comment]
I ran into so much trouble trying to use the internal `DefaultTooltipContent` component. Also the fact that it's not a pubic API is a bit worrying. I ended up manually overriding it as such:

```
                  <Tooltip
                    content={(props) => (
                      <div style={{
                        border: '#bbb 1.5px solid',
                      }}>
                        <p style={{
                          margin: '0 0',
                          padding: '3px 7.5px',
                          backgroundColor: 'white',
                        }}>
                          {props.payload && props.payload[0] != null && props.payload[0].payload.Name}
                        </p>
                        <p style={{
                          margin: '0 0',
                          padding: '3px 7.5px',
                          backgroundColor: 'white',
                          color: '#007AFF',
                        }}>
                          Read:
                          {' '}
                          {
                            props.payload && props.payload[0] != null && props.payload[0].payload.Read
                          }
                        </p>
                      </div>
                    )}
                  />
```

**Comment by HunterSides** [comment]
@omarryhan Thank you, this is by far the easiest solution proposed and should be higher up.

**Comment by cnaez** [comment]
Try the easiest way.

```
const CustomTooltip = ({ active, payload, label }) => {
    if (active && payload && payload.length) {
      payload[0].chartType = "AreaChart";
      return (
        <div className="custom-tooltip">
          <p className="label">{payload[0].value}</p>
          <p className="user-number">
            {payload[0].payload.number}
          </p>
          <p className="time">{label}</p>
        </div>
      );
    }

    return null;
  };
.
.
.
<ToolTip content={<CustomTooltip />} />
```
console.log(payload[0]) can help you
