### ISSUE TITLE
export 'ResponsiveContainer' (imported as 'ResponsiveContainer') was not found in 'recharts' (module has no exports)

### ISSUE THREAD

**Issue by theotzen** [recharts/recharts#2750]
I have look up at the issues but this one (for this version of recharts) is not a duplicate, I believe.

Everything was working really well until I added a new package to my app using yarn (font icons).

Now, I got the issue 

> export 'ResponsiveContainer' (imported as 'ResponsiveContainer') was not found in 'recharts' (module has no exports)
> export 'BarChart' (imported as 'BarChart') was not found in 'recharts' (module has no exports)
> export 'XAxis' (imported as 'XAxis') was not found in 'recharts' (module has no exports)

And so on.

I use :
> "recharts": "^2.1.8"
>  "yarn": "^1.22.17"
> "react": "^17.0.2"
> Mac OS

---

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

**Comment by ckifer** [comment]
Hi, I don't think `yarn` itself should be in your package.json

Either way, everything seems to be working with the latest version of recharts - please comment back on this issue if you still are having problems.
