### ISSUE TITLE
YAxis "DataMin" value of domain does not work when used with interval "preserveStart"

### ISSUE THREAD

**Issue by jaekunchoi** [recharts/recharts#2751]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-qyvw0?file=/src/index.js:741-772)

### Steps to reproduce
Use
<YAxis axisLine={false} reversed={true} type="number" domain={[1, 'auto']} interval="preserveStart" />

for YAxis and you can see "0" is still displayed.

### What is expected?
I want "1" instead of "0" or whatever I have specified as "DataMin" under "domain" option

### What is actually happening?
"DataMin" is not respected and "0" is still displayed.

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 16.12 |
| System | Mac OS |
| Browser | Chrome |

**Comment by ckifer** [comment]
Looks good to me in the latest, resolving

https://codesandbox.io/p/sandbox/recharts-issue-template-forked-qyvw0
