### ISSUE TITLE
Chart zooming flickers/blanks if rendered in functional component

### ISSUE THREAD

**Issue by phaag** [recharts/recharts#2757]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rechart-func-component-dwt6n?file=/src/App.js)

### Steps to reproduce
The line chart code is refracted into its own function. If you now zoom the chart, it flickers or blanks completely. If you put the DrawLineChart code directly into the return() statement it does not show this behaviour. 

### What is expected?
Smooth zooming if code is refracted in its own function

### What is actually happening?
Depending on where the linechart code is put,  zooming the line chart behaves different

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 17.0.2 |
| System | any |
| Browser | Chrome |

---
The version selector in this form does not allow to select version 2.1.8

**Comment by vtarelkin** [comment]
@phaag you should remove example 2 links in your codesandbox to make it run ;-)

BTW do you mind the missing tick on the x-axis? 

![image](https://user-images.githubusercontent.com/46703134/149078039-034b15c1-5c3e-4971-b5ec-91bb837a780c.png)

and on max zoom there is only one line)
![image](https://user-images.githubusercontent.com/46703134/149078107-3af8d7d4-fe4b-4779-b48d-bd75ab3fd04d.png)

**Comment by phaag** [comment]
> @phaag you should remove example 2 links in your codesandbox to make it run ;-)
> 
> BTW do you mind the missing tick on the x-axis? that annoying shitty bug is soo old but they can't fix it
> 
> ![image](https://user-images.githubusercontent.com/46703134/149078039-034b15c1-5c3e-4971-b5ec-91bb837a780c.png)
> 
> and on max zoom there is only one line) ![image](https://user-images.githubusercontent.com/46703134/149078107-3af8d7d4-fe4b-4779-b48d-bd75ab3fd04d.png)

Thanks! - Fixed. I am aware of the missing tick. I fixed that in my code with my own code and supplied ticks manually. The same for the max zoon etc. For the example, I wanted to keep the code as small as possible - just to show the behaviour.

**Comment by ckifer** [comment]
Unsure why this particular example isn't working but in general this works fine with function components
https://codesandbox.io/p/sandbox/highlight-zoom-line-chart-rrj8f4

Seems like a bug in the sandbox code
