### ISSUE TITLE
Mouse down event didn't return mouse button right or left click

### ISSUE THREAD

**Issue by SebFox2011** [recharts/recharts#2759]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/highlight-zomm-line-chart-v77bt)

### Steps to reproduce
Add a console.log(e) in the mouseDown function of the LineChart component and try to guess if its right or left clic/

### What is expected?
It could be easy to see on mouseEvent if it's a right or left click.

### What is actually happening?
We have to guess if the user has clilck on the left or right mouse click

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 16.8 |
| System | Windows 10 |
| Browser | Chome |

---
THXs

**Comment by ckifer** [comment]
```
          onMouseDown={(data: any, event) => {
            console.log(event);
            this.setState({ refAreaLeft: data.activeLabel });
          }}
```
this is the form of `onMouseDown` where data is recharts data and `event` is the browser event that you should be able to get this information from. Resolving
