### ISSUE TITLE
add a new language and there is a grammar mistakes in the docs

### ISSUE THREAD

**Issue by zourdyzou** [recharts/recharts#2760]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Developers who do not speak english and chinese will be able to understand properly, and also there are a few words in the docs which I found a little bit confusing.

### What does the proposed API look like?
Language / Internationalization?

**Comment by ckifer** [comment]
Feel free to contribute over at https://github.com/recharts/recharts.org
Going to close this here
