### ISSUE TITLE
The the tick before last is missing

### ISSUE THREAD

**Issue by vtarelkin** [recharts/recharts#2761]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/highlight-zomm-line-chart-v77bt)

### Steps to reproduce
open the link 

### What is expected?
all ticks are shown

### What is actually happening?
some ticks are missing

![image](https://user-images.githubusercontent.com/46703134/149191453-108a9580-3b37-4ccb-8120-be4dcebd8c1f.png)

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | ^16.13.0 |
| System | OS Ubuntu 18 |
| Browser | Version 96.0.4664.45 (Official Build) (64-bit) |

---
please fix this annoying bug

**Comment by lachlanjc** [comment]
Possibly related: #1783
