### ISSUE TITLE
Performance improvement by short-circuiting axis map creation with specified domain

### ISSUE THREAD

**Issue by bennettdams** [recharts/recharts#2762]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
There's an easy/small change to hugely improve performance when the user provides a specified domain.

The creation of an axis map is really expensive ([see the function docs of `updateStateOfAxisMapsOffsetAndStackGroups`](https://github.com/recharts/recharts/blob/2a3405ff64a0c050d2cf94c36f0beef738d9e9c2/src/chart/generateCategoricalChart.tsx#L846)).
Right now, no matter if a specified domain is provided via props, the chart data is always used to calculate the axis map. This is done to automatically extend the axis when the data is smaller/bigger than a specified domain value.
This can be prohibited via the `allowDataOverflow` prop. In my case, I set `allowDataOverflow` to `true` and also provide the domain start and the domain end. For this scenario, the chart data never has to be taken into account when creating the axis map.

### What does the proposed API look like?
[There are two ways to create the axis map](https://github.com/recharts/recharts/blob/2a3405ff64a0c050d2cf94c36f0beef738d9e9c2/src/chart/generateCategoricalChart.tsx#L481), `getAxisMapByItems` and `getAxisMapByAxes`. Let's take `getAxisMapByAxes` as an example. Right now, `domain` is filled based on the calculation with the chart data ("step 1") and then `domain` is overwritten via the specified domain ("step 2").

We could short-circuit the domain creation in one scenario:
- `allowDataOverflow` is set to `true`
- the specified domain (start AND end) was provided via props with two values

I'm not sure where to do this, because I'm missing the knowledge of how the code flow and `domain` variable is used. Instead of multiple variables, the one `domain` variable is reused in different situations in the code, so I can't really follow the needed values.

To test the proposal out, I modified [`getAxisMapByAxes`](https://github.com/recharts/recharts/blob/2a3405ff64a0c050d2cf94c36f0beef738d9e9c2/src/chart/generateCategoricalChart.tsx#L266) and **even before "step 1"** (see text above), I set the domain via the specified domain:

```ts
const getAxisMapByAxes = (
  props: CategoricalChartProps,
  { axes, graphicalItems, axisType, axisIdKey, stackGroups, dataStartIndex, dataEndIndex }: any,
) => {
  ...
    if (!result[axisId]) {
      let domain, duplicateDomain, categoricalDomain;

      /*
       * We short-circuit the domain creation here to enhance performance.
       * Usually, the data is used to determine the domain, but when the user specifies
       * a domain upfront (via props), there is no need to calculate the domain start and end,
       * which is very expensive for a larger amount of data.
       * The only thing that would prohibit short-circuiting is when the user doesn't allow data overflow,
       * because the axis is supposed to ignore the specified domain that way.
       */
      const specifiedDomain: AxisDomain[] = child.props.domain;
      if (allowDataOverflow === true && type === 'number' && !!specifiedDomain?.[0] && !!specifiedDomain?.[1]) {
        domain = parseSpecifiedDomain(specifiedDomain, null, allowDataOverflow);
      } else {
        // "step 1" as described above
        if (dataKey) {
          // has dataKey in <Axis />
          domain = getDomainOfDataByKey(displayedData, dataKey, type);
        } ...
  ...
}
```

This small change hugely improves the performance for my use case.

# Without the change : 1.7 seconds

![image](https://user-images.githubusercontent.com/29319414/149194182-2c3b7e59-1fae-4a3a-a935-2aa841a85081.png)

# With the change: 890 ms
![image](https://user-images.githubusercontent.com/29319414/149194455-e4fafc62-1baa-4898-81b7-7bf8dd35b466.png)

## By the way
Did you already investigate whether the axis map creation is optimized based on the input data? I can't really tell why, but I feel like it is executed too often, because the results are not saved/reused.

**Comment by ckifer** [comment]
Merged in  #3293, will be out with next minor release
