### ISSUE TITLE
Linear Gradient for Pie Chart Cells

### ISSUE THREAD

**Issue by elCarlosSantiago** [recharts/recharts#2764]
- [X] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Better design and viewing experience. Linear gradients are a feature on all other types of charts. Would be nice to have something simillar for Pie Chart Cells.

### What does the proposed API look like?
<Cell key={`cell-${i}`} fill={pColors[i]}/>

 const pColors = ["#FF9A86", "#FEB475", "#FCEC62", "#8BFF89", "#88FCCF", "#7BF3E6", "#74E7FE", "#77C5FD", "#C292FF", "#5C94FF", "#FF80B4"];

Would be nice to have linear gradients instead of single hex values:

i.e.:

 pColors = ["linear-gradient(238.93deg, #FF9A86 20.25%, rgba(255, 154, 134, 0.42) 82.65%)", "#FEB475", "#FCEC62", "#8BFF89", "#88FCCF", "#7BF3E6", "#74E7FE", "#77C5FD", "#C292FF", "#5C94FF", "#FF80B4"];

cell[0] would have a gradient to it.

**Comment by samaritanz** [comment]
i also want to know how  the issue is solved

**Comment by othneildrew** [comment]
Check out this example guys. Someone was able to get this to work using svg props... Works for me and many others.
@elCarlosSantiago @samaritanz 

https://codesandbox.io/s/friendly-minsky-k1rje?file=/src/pieChartDiagram.js
