### ISSUE TITLE
Doesn't work with typescript without JSX.

### ISSUE THREAD

**Issue by wclr** [recharts/recharts#2768]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/recharts/recharts/issues/](https://github.com/recharts/recharts/issues/)

### Steps to reproduce
```ts
import * as R from "recharts"
import React from "react"


export const renderLineChart = () => {
  return React.createElement(R.LineChart, {}, [    
    React.createElement(R.Line, {},  null),
  ])
}
```
![image](https://user-images.githubusercontent.com/736697/151225558-44bc6815-cecf-4ce5-a978-203dfcd22991.png)

Try the code (where R.Line) and see the error create.

### What is expected?
No error and working typings (like for `LineChart`).

### What is actually happening?
The error and not working typings. Not a big expert on React typings to say what is wrong.

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 17.0.2 / 17.0.38 (@types) |
| System | Windows |
| Browser | VScodd |

**Comment by ckifer** [comment]
Going to close this as stale, recharts works fine with TS/JSX
