### ISSUE TITLE
Bar graph staying on top of legends.

### ISSUE THREAD

**Issue by jarodsim** [recharts/recharts#2769]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/simple-bar-chart-forked-eqthv?file=/src/App.tsx)

### Steps to reproduce
Just enter the page, passing some data via props

### What is expected?
It's waiting for the graph to be displayed normally, along with the subtitles, which also have a margin-bottom, precisely to prevent the graph from getting too "glued" to the subtitles

### What is actually happening?
The graph bars are getting collapsed with the legends, they are on top of the legend and it only returns to normal when we perform a resize in the browser window.

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | v17.0.2 |
| System | Windows 10 |
| Browser | Chrome  97.0.4692.99, Firefox 96.0.2 64bit, Edge 97.0.1072.69 |

**Comment by jarodsim** [comment]
https://ibb.co/VYwSgNz

image to bug

**Comment by ckifer** [comment]
reproduction given does not render in codesandbox, going to closet his as stale
