### ISSUE TITLE
Full width of horizontal bar is not shown when longer than first bar

### ISSUE THREAD

**Issue by terryroe** [recharts/recharts#2772]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-clipped-xaxis-1ivzr)

### Steps to reproduce
Run the code in the codesandbox above, repeated here for reference:
```
import React from "react";
import ReactDOM from "react-dom";
import { Bar, BarChart, LabelList, ResponsiveContainer, XAxis, YAxis } from 'recharts';
import "./styles.css";

const data = [{
  name: '',
  count: ' ',
}, {
  name: 'None',
  count: 11,
}, {
  name: 'Low',
  count: 83,
}, {
  name: 'Medium',
  count: 25,
}, {
  name: 'High',
  count: 47,
}];

function App() {
  const formatLabel = (value) => (value !== ' ' ? `${value}%` : ' ');
  
  return (
    <ResponsiveContainer height={150} width="100%">
    <BarChart data={data} layout="vertical" margin={{ left: 20, right: 40 }}>
      <XAxis
        axisLine={false}
        dataKey="count"
        hide={true}
        scale="linear"
        tickLine={false}
      />
      <YAxis
        axisLine={false}
        dataKey="name"
        minTickGap={0}
        reversed={true}
        tickLine={false}
        type="category"
        width={65}
      />
      <Bar dataKey="count">
        <LabelList dataKey="count" position="right" formatter={formatLabel} fill="#5e5e5e" fontSize="12px" />
      </Bar>
    </BarChart>
  </ResponsiveContainer>  );
}

const rootElement = document.getElementById("root");

ReactDOM.render(<App />, rootElement);
```

### What is expected?
All of the bars should be fully displayed along with the label at the end.

### What is actually happening?
The bar that has a value of '83' in the sample code is clipped.  

| Environment | Info |
|---|---|
| Recharts | v2.0.9 |
| React | 16.9.0 |
| System | macOS Mojave |
| Browser | Chrome Version 97.0.4692.99 |

---
If the first (top) bar has a value that is higher than all the others, all the bars will be fully displayed.  However, it seems the first bar is being used to "scale" the other bars after it.  Any bars with a higher value get clipped at the length of the first bar.

**Comment by dp-hebbia** [comment]
@terryroe  did u figure out a solution for this?

**Comment by terryroe** [comment]
@dp-hebbia No, I did not.  I think it's a bug in the library, but I don't know TypeScript.

**Comment by fagom** [comment]
Hi @terryroe, the below code worked for me. Not sure if this is what you are looking for. Was a CSS level change though :)
```
<ResponsiveContainer height={150} width='100%'>
<BarChart data={data} layout="vertical" margin={{ left: 20, right:270 }}>
```

**Comment by ckifer** [comment]
removing `scale="linear"` and changing `type="number"` will do it for the provided codesandbox

when you make a vertical chart you need to swap the axis type as it defaults to cateogory
