### ISSUE TITLE
Warning: setState(...): Can only update a mounted or mounting component....Please check the code for the ContainerDimensions component.

### ISSUE THREAD

**Issue by tomsue** [recharts/recharts#278]
Hi,

I get a warning when i **# **fast**** switch some page(the page use ResponsiveContainer  ).

environment：
recharts@^0.13.3
react: ^15.3.0,
ref:  ContainerDimensions of react-container-dimensions@1.2.0

public code:

     _<ResponsiveContainer width="100%" height="100%">
                        <BarChart data={data}
                                    margin={{top:20, right:0, left:0, bottom:3}}
                        >
                            <XAxis dataKey={xkey} tickLine={false}/>
                            <YAxis tickLine={false} tickFormatter={this.tickFormatter.bind(this.state, "L")}/>
                            <Bar dataKey={defaultY} barSize={20}
                                 fill={this.context.muiTheme.fuelBarChart.barFill} stroke=
                              {this.context.muiTheme.fuelBarChart.barStroke}>
                            </Bar>
                        </BarChart>
    </ResponsiveContainer>_ 

error info:
warning.js:36 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ContainerDimensions component.

printWarning	@	warning.js:36
warning	@	warning.js:60
getInternalInstanceReadyForUpdate	@	ReactUpdateQueue.js:49
enqueueSetState	@	ReactUpdateQueue.js:201
ReactComponent.setState	@	ReactComponent.js:64
onResize	@	index.js:65
callListenerProxy	@	element-resize-detector.js:153
utils.forEach	@	collection-utils.js:14
onResizeCallback	@	element-resize-detector.js:152
onElementDetectable	@	element-resize-detector.js:245
ready	@	scroll.js:555
process	@	batch-processor.js:124
processBatch	@	batch-processor.js:37

**Comment by tomsue** [comment]
![image](https://cloud.githubusercontent.com/assets/5195809/18984772/f6f3c230-8726-11e6-8c25-604f6d3215e4.png)

I add the _isMounted to controller onresize then , I can normal fast switch.

**Comment by xile611** [comment]
@tomsue This is duplicated with [#249](https://github.com/recharts/recharts/issues/249).
