### ISSUE TITLE
Responsive Container not resizing (using react-router)

### ISSUE THREAD

**Issue by truenorthcreative** [recharts/recharts#279]
I'm using the following code for an AreaChart within a Responsive Container: 

```
<ResponsiveContainer aspect={2}>
    <AreaChart
        data={data}
        margin={{top: 5, right: 30, left: 20, bottom: 5}}>
    <XAxis dataKey="name" stroke="#bbb"/>
    <YAxis stroke="#bbb"/>
    <CartesianGrid strokeDasharray="3 3"/>
    <Tooltip/>
    <Legend />
    <Area type="monotone" dataKey="ingress" stroke="#8884d8" fillOpacity={0.2} fill="#8884d8" activeDot={{r: 8}}/>
    <Area type="monotone" dataKey="egress" stroke="#82ca9d" fillOpacity={0.2} fill="#82ca9d" />
    </AreaChart>
</ResponsiveContainer>
```

Any ideas why this isn't resizing?  I've tried the setting min-height, height, etc.  It only initially renders if I provide an `aspect`

Any thoughts would be helpful

Initial view:
![image](https://cloud.githubusercontent.com/assets/612747/18985010/69573e40-86bb-11e6-8cb9-cf0dafe954b9.png)

Resized: 
![image](https://cloud.githubusercontent.com/assets/612747/18985016/76ec677e-86bb-11e6-9699-443d9c235dcf.png)

**Comment by techniq** [comment]
@truenorthcreative try setting `width="100%"` as well
```js
<ResponsiveContainer width="100%" aspect={2}>
...
```

This is what I'm using with react-router / bootstrap.

**Comment by truenorthcreative** [comment]
@techniq That doesn't work for me.  I've tried all of the solutions provided in the threads on here

**Comment by pierre-b** [comment]
Same problem here, @truenorthcreative how did you fixed this please?

**Comment by michaelfreund** [comment]
This one worked for me

```html
<div className="simple-line-chart">
	<ResponsiveContainer className="simple-line-chart__container">
		<AreaChart>
```

```css
.simple-line-chart {
  height: 400px;
  position: relative;
}

.simple-line-chart__container {
  position: absolute;
  left: 0;
  right: 0;
  height: 400px;
}
```
