### ISSUE TITLE
Colors in pie chart

### ISSUE THREAD

**Issue by Riddhi1622** [recharts/recharts#2792]
I am trying so hard to add different colors to each slice in a single pie chart. However, I am not finding any single tutorial for that. Please add that

**Comment by faridsh69** [comment]
same problem here.  there is style in src\assets\icons\logo.svg that cause this problem. please fix it!

**Comment by nikolasrieble** [comment]
The https://recharts.org/en-US/examples/PieChartWithCustomizedLabel example shows how to add different colors to each slice.

**Comment by ckifer** [comment]
Going to close this as there are plenty of examples of how to do this on the website and the storybook
https://release--63da8268a0da9970db6992aa.chromatic.com/?path=/story/examples-pie-piewithneedle--pie-with-patterns
