### ISSUE TITLE
Using Recharts with next@12.0.7 and typescript 4.5.2 fails to build due to type issues

### ISSUE THREAD

**Issue by rdjpalmer** [recharts/recharts#2796]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `recharts@2.1.9` in order to get my project to build correctly.

It fails due to the types used in DefaultTooltipContent and DateUtils. I believe the issue is due to the types being too loose, and the fact that typescript is unable to parse the checks the lib does using lodash vs native JS code. Replacing the checks with native equivalents works a treat.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/recharts/src/component/DefaultTooltipContent.tsx b/node_modules/recharts/src/component/DefaultTooltipContent.tsx
index 5c1d838..133b2b3 100644
--- a/node_modules/recharts/src/component/DefaultTooltipContent.tsx
+++ b/node_modules/recharts/src/component/DefaultTooltipContent.tsx
@@ -6,12 +6,18 @@ import React, { PureComponent, CSSProperties, ReactNode } from 'react';
 import classNames from 'classnames';
 import { isNumOrStr } from '../util/DataUtils';
 
-function defaultFormatter<T>(value: T) {
-  return _.isArray(value) && isNumOrStr(value[0]) && isNumOrStr(value[1]) ? value.join(' ~ ') : value;
+type Value = number | string;
+export type ValueType = Value | [Value, Value];
+
+function defaultFormatter<T extends ValueType>(value: T) {
+  if (Array.isArray(value) && isNumOrStr(value[0]) && isNumOrStr(value[1])) {
+    return value.join(" ~ ");
+  }
+
+  return value;
 }
 
 export type TooltipType = 'none';
-export type ValueType = number | string | Array<number | string>;
 export type NameType = number | string;
 export type Formatter<TValue extends ValueType, TName extends NameType> = (
   value: TValue,
diff --git a/node_modules/recharts/src/util/DataUtils.ts b/node_modules/recharts/src/util/DataUtils.ts
index 49708a8..ebee084 100644
--- a/node_modules/recharts/src/util/DataUtils.ts
+++ b/node_modules/recharts/src/util/DataUtils.ts
@@ -11,7 +11,7 @@ export const mathSign = (value: number) => {
   return -1;
 };
 
-export const isPercent = (value: string | number) => _.isString(value) && value.indexOf('%') === value.length - 1;
+export const isPercent = (value: string | number) => typeof value === "string" && value.indexOf('%') === value.length - 1;
 
 export const isNumber = (value: any) => _.isNumber(value) && !_.isNaN(value);
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by jsonreeder** [comment]
I was seeing similar behavior.

I was importing type definitions from the recharts source code:

```ts
import {
  ValueType,
  NameType,
} from 'recharts/src/component/DefaultTooltipContent';
```

This hack was part of using Recharts types for custom tooltips. It was inspired by https://stackoverflow.com/questions/65913461/typescript-interface-for-recharts-custom-tooltip.

When I removed that import, I was able to run `tsc` without errors. I just copied the `ValueType` and `NameType` definitions to my codebase.

**Comment by based64-eth** [comment]
still broken. does no one use recharts with typescript?

**Comment by SerhBess** [comment]
try to import   ValueType and NameType like this
import { NameType, ValueType } from 'recharts/types/component/DefaultTooltipContent';

**Comment by ckifer** [comment]
Going to close this as it not longer seems to be an issue. Either use the above import or try not to import these types from locations that may break.
