### ISSUE TITLE
Display tooltip on radar points

### ISSUE THREAD

**Issue by signaturecoder** [recharts/recharts#2798]
How to display tooltip in radar charts on hovering over radar points?

**Comment by celiaongsl** [comment]
Hi @signaturecoder!

If you are talking about adding a simple Tooltip, you can just import <Tooltip /> and add it into your <RadarChart />! 

If you require more customization to your Tooltip, I might suggest looking through [this example](https://recharts.org/en-US/examples/CustomContentOfTooltip).

**CodeSandbox Example**
[![Edit simple-radar-chart (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/simple-radar-chart-forked-or6pmx?fontsize=14&hidenavigation=1&theme=dark)

**For Simpler Referencing**
```
import "./styles.css";
import React from "react";
import {
  Radar,
  RadarChart,
  PolarGrid,
  PolarAngleAxis,
  PolarRadiusAxis,
  **Tooltip**
} from "recharts";

const data = [
  // Put your data here
];

export default function App() {
  return (
    <RadarChart
      // Add whichever props you require
      data={data}
    >
      <Radar
        name="Mike"
        dataKey="A"
        stroke="#8884d8"
        fill="#8884d8"
        fillOpacity={0.6}
      />
      **<Tooltip />**
    </RadarChart>
  );
}
```

Happy coding :)

**Comment by signaturecoder** [comment]
Thank you. I have already got the idea. I forgot to close the issue.
