### ISSUE TITLE
Show label on ReferenceLine

### ISSUE THREAD

**Issue by bkniffler** [recharts/recharts#28]
Hey, 
Having labels on xAxis, yAxis, Line etc. is very nice, but what about ReferenceLine? This would be important to have it work as an indicator with a text like 'Peek' or 'Maximum' or 'ROI' or whatever.

**Comment by xile611** [comment]
Thanks! It's really a good idea.
We will add label of ReferenceLine in the next version.

**Comment by xile611** [comment]
Fixed in v0.7.0.
<http://recharts.org/api#ReferenceLine>

**Comment by bkniffler** [comment]
Wow, thats great, thank you for all the efforts and keep it up!
