### ISSUE TITLE
Is it possible to change the Bar fill color based on a value in the data set? 

### ISSUE THREAD

**Issue by gplatt** [recharts/recharts#280]
I'd like to make the fill color for the column "Current" to be different to the other bars. Would appreciate any help for doing this.  Note that the data gets sorted so the order of the bars changes.

Many thanks.

This is what my data looks like.  

`export default ({coverAmount, rates, current}) => {
  const data = sortData([
    {years: 'Current', premium: parseFloat(current), buffer: 0},
     {years: 'R10,000', premium: 10000 * rates[0], buffer: Math.round((10000 * rates[1])/3)},
     {years: 'R20,000', premium: 20000 * rates[0], buffer: Math.round((20000 * rates[1])/3) },
     {years: 'R30,000', premium: 30000 * rates[0], buffer: Math.round((30000 * rates[1])/3) }
 ]);`

and the Bar statements
      `<Bar stackId="a" dataKey="premium" fill="#005599"  />
       <Bar stackId="a" dataKey="buffer" fill="#007700" label/>
      `

**Comment by billneff79** [comment]
The individual data elements are passed into the props, so you have acces to those in a custom bar shape.  You should be able to create a custom bar, and in that custom bar set the a css class or explicit fill color to do what you want:

````
const CustomBar = (props) => {
  const {years, fill} = props;
  //business logic here to update fill color explicitly
  if(years === 'Current') {
      fill='#NewFillColor';
  }

  //use explicit fill here, or use the additional css class and make a css selector to update fill there
  return <Rectangle {...props} fill={fill} className=`recharts-bar-rectangle ${years}` />
};

...later on

<Bar shape={CustomBar} />

````

**Comment by gplatt** [comment]
Thank you. This helped me better understand things. 

I came across an example using the Cell component and now have it close to what I want with the following code:

```
<Bar stackId="a" dataKey="premium" >
                {
                  data.map((entry, index) => (
                    <Cell fill={data[index].years === "Current" ? '#290a0a' : '#005599' }/>
                  ))
                }
 </Bar>
     <Bar stackId="a" dataKey="buffer" fill="#007700" label/>
  </BarChart>
```

**Comment by rawsyntax** [comment]
Your example was helpful to me -- Thanks!

**Comment by GGAlanSmithee** [comment]
@gplatt thanks for the example. There is one additional simplification available:

```js
<BarChart>
    <Bar stackId="a" dataKey="premium" >
        {data.map((entry, index) => (
            <Cell fill={entry.years === "Current" ? '#290a0a' : '#005599' }/>
        ))}
    </Bar>
</BarChart>
```

**Comment by Berad** [comment]
I used the trick by gplat (thx) and it works fine, but now i can't see the lable with position insideLeft - it's hidden under the Cell. Can anyone tell me if I can draw label myself or reveal it somehow from under the Cell?

I tried to create Label inside the Cell, but it didn't help or maybe I did it incorrect.

Here is the code sample with cell and label property of Bar.

```
<Bar dataKey="utilized" name="Utilized, %" stackId="a" label={{ position: 'insideLeft' }}>
{
  data.map((entry, index) => (
    <Cell fill={entry.utilized <= 25 
        ? '#089c19' // green
        : entry.utilized <= 50 
            ? '#d4bb02'  //yellow
            : entry.utilized <= 75
                ? '#d48402' //orange
                : '#d41002' }/> //red
))}
</Bar>
```

And here is what i see in real life if I use it
![hiddenLabel](https://user-images.githubusercontent.com/1056568/77228346-b3437e00-6b97-11ea-91fd-6a40174b9e52.png)

**Comment by Anurag690** [comment]
how can one make relative gradient using this approach like color changing in each bar with values.

**Comment by mschreib28** [comment]
I know this thread is old, but in case it would help anyone:
```
<Bar dataKey="group" barSize={8}>
  {teams.map((entry, index) => (
    <Cell fill={getColor(entry.group)} />
  )}
</Bar>
```
where `getColor()` is:
```
const green = "#58C0A1"
const teal = "#53C2E2"
const blue = "#5597DE"
const orange = "#F2B35B"
const red = "#F16D64"
    
const getColor = (p: number) => {
        if (p >= 90) { return green; }
        if (p < 90 && p >= 80) { return teal; }
        if (p < 80 && p >= 70) { return blue; }
        if (p < 70 && p >= 60) { return orange; }
        if (p < 60) { return red; }
}
```

**Comment by shamilsdq** [comment]
I've taken a different approach here. Hope this helps someone.

Sample data:

```
const data = [
    {
        name: "car",
        sale: 3500,
        cellProps: { fill: "#FF8888" },
    },
    {
        name: "bike",
        sale: 9000,
        cellProps: { fill: "#00FFFF" },
    },
];
```

```
<Bar dataKey="sale">
    {teams.map((entry, index) => (
        <Cell {...entry.cellProps} />
    )}
</Bar>
```

I've actually set the props for each cell in a property named cellProps for each entry. I then spread it on the Cell component.
