### ISSUE TITLE
[Area] when scale is "log", and stackId is set, then nothing is displayed

### ISSUE THREAD

**Issue by ivan-aksamentov** [recharts/recharts#2800]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stacked-area-chart-forked-eqebsl)

### Steps to reproduce
1. Take the StackedAreaChart example from the docs
https://recharts.org/en-US/examples/StackedAreaChart

2. Set Y axis to log, and define domain:
<YAxis scale="log" domain={["auto", "auto"]} />

3. Observe that `Area` components are not displayed

4. Comment-out the `stackId` props in `Area` components

5. Observe that `Area` components are now visible and in log scale, but are not stacked

6. Undo the changes in 4, then set scale to linear:
<YAxis scale="linear" domain={["auto", "auto"]} />

7. Observe that `Area` components are now visible, and stacked, but are not in log scale

### What is expected?
`stackId` prop should not break plots when in log scale mode. Different scaling types and stacking should not affect each other.

### What is actually happening?
Setting `stackId` breaks plots when in log scale mode

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 17.0.1 |
| System | Ubuntu 20.04 |
| Browser | Chromium 99.0.4844.51 |

**Comment by abdulrahmancz** [comment]
Hey @ivan-aksamentov , what I've observed is that you need to specify the domain to start from 1 so it would be `domain={[1, "auto"]}`. Also for me it only works when I enabled `allowDataOverflow` on yaxis.
You can see the demo here https://codesandbox.io/s/stacked-area-chart-forked-eoky0k?file=/src/App.tsx:1023-1040.
But as you can see the render of such areachart is broken, I've created separate bug for it.

**Comment by ivan-aksamentov** [comment]
@abdulrahmancz Thanks!

For future readers, the new issue Said opened is https://github.com/recharts/recharts/issues/2804

**Comment by ckifer** [comment]
closing this in favor of https://github.com/recharts/recharts/issues/2804

**Comment by ckifer** [comment]
https://d3js.org/d3-scale/symlog

use scale="symlog"
