### ISSUE TITLE
Area stacked chart is broken when it's used with log scale

### ISSUE THREAD

**Issue by abdulrahmancz** [recharts/recharts#2804]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stacked-area-chart-forked-eoky0k)

### Steps to reproduce
1. have a basic stacked area chart (I used for the repro the area chart example from the docks)
2. change the yaxis to use log scale, also adjust the domain to start from 1 and enable allowDataOverflow, otherwise the chart won't work at all
3. observe broken are chart, the area of the most bottom series doesn't start form the yaxis as it should, instead it is weirdly above the line

### What is expected?
The area part of the series should start at the yaxis and should end with the actual line of the series.

### What is actually happening?
The area is rendered weirdly above the series line and it is straight between first and second point of the line.

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 17.0.1 |
| System | Mac OS 12.3 |
| Browser | Chrome 99.0.4844.74 (Official Build) (x86_64) |

**Comment by ckifer** [comment]
Use `<YAxis scale="symlog" />`

None of the said extra parameters are needed when you do this and it doesn't have the 0 problem. its 99% of the time the log scale you want to use for charts

https://d3js.org/d3-scale/symlog

**Comment by vschoener** [comment]
Hi, we had this issue in the team but our linter raised an error since `symlog` is not available in the type (union) when we ant to use it. It's not referred in the [documentation](https://recharts.org/en-US/api/YAxis#scale) as well.

Do you think these parts could be improved?
