### ISSUE TITLE
chart not working properly

### ISSUE THREAD

**Issue by karthic-keyan** [recharts/recharts#2806]
chart line not appearing properly

![image](https://user-images.githubusercontent.com/58414583/159416994-4a0906cc-db90-4740-820b-3ff8cfcb5ba5.png)
---

**Comment by calumx** [comment]
Hey @karthiktrp, I had a similar issue that was caused by feeding the graph string values instead of numbers. Could this be your problem?

**Comment by karthiktrp** [comment]
i am using number only @calumx

**Comment by calumx** [comment]
Can you post some code?

**Comment by ckifer** [comment]
Going to close this as stale
