### ISSUE TITLE
Area: Warning: Invalid value for prop `type` on <path> tag.

### ISSUE THREAD

**Issue by dreamboyx1** [recharts/recharts#2809]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate. There are some similar, but unrelated issues.

### Reproduction link
[https://github.com/dreamboyx1/recharts](https://github.com/dreamboyx1/recharts)

### Steps to reproduce
Run the Area Charts demo as specified in the README. In the console output you will see:

```
react-dom.development.js:88 Warning: Invalid value for prop `type` on <path> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://fb.me/react-attribute-behavior
    in path (created by Curve)
    in Curve (created by Animate)
    in g (created by Layer)
    in Layer (created by Animate)
    in g (created by Layer)
    in Layer (created by Animate)
    in g (created by Layer)
    in Layer (created by Animate)
    in Animate (created by Area)
    in g (created by Layer)
    in Layer (created by Area)
    in Area (created by AreaChartDemo)
    in svg (created by Surface)
    in Surface (created by AreaChart)
    in div (created by AreaChart)
    in AreaChart (created by AreaChartDemo)
    in div (created by AreaChartDemo)
    in div (created by AreaChartDemo)
    in AreaChartDemo (created by App)
    in div (created by App)
    in App (created by Context.Consumer)
    in Route
    in Router (created by BrowserRouter)
    in BrowserRouter
```

### What is expected?
No console warnings.

### What is actually happening?
Console warnings

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 17.0.2 |
| System | MacOS 12.1 |
| Browser | Chrome Version 99.0.4844.74 (Official Build) (arm64) |

---
The issue is that Area, among other charts, are passing the props.type down to the SVG components via a spread operator. This prop is not intended for the SVG components but because SVG components do accept a property that is also named 'type' the property is not filtered out via the filterProps function. The SVG components only accept the prop type as an optional string. In my example, I'm passing type as a function to Area which in turn is passing that function to the type prop of the SVG component. React then checks the validity of the SVG component type. Since the SVG component does not accept functions on the type prop, it prints this warning. It's an annoyance more than anything. I've not yet found a good workaround.

**Comment by Jaeyong-seo** [comment]
I found this issue at each Chart Component's type props.
I using `type={curveCardinal.tension(curveValue)}`
curveValue is  useState.

``` javascript
<Line
	type={curveCardinal.tension(curveValue)}
	dataKey="pv"
/>
```

**Comment by ckifer** [comment]
This issue has been resolved for a while. Closing
