### ISSUE TITLE
I want to change the CartesianGrid of my Line Chart

### ISSUE THREAD

**Issue by monu-2311** [recharts/recharts#2812]
It's my Line Chart.

![new](https://user-images.githubusercontent.com/84042194/161377343-e5ad8b61-9d9a-4c84-a4e5-3da5a4146517.jpg)

And want to customize it like the below image.
What can I do to make It like that?

![Screenshot 2022-04-02 015258](https://user-images.githubusercontent.com/84042194/161377312-e3da9af8-4740-4e78-bad1-870cb08906f9.jpg)

Code.
![Screenshot 2022-04-02 151451](https://user-images.githubusercontent.com/84042194/161377542-8b8178be-d0cb-478b-9273-14d7b27ed202.jpg)

![Screenshot 2022-04-02 151355](https://user-images.githubusercontent.com/84042194/161377547-6baf1a35-6514-491b-b03f-a4a5ac5bf11f.jpg)

**Comment by monu-2311** [comment]
Please Help me.

**Comment by plxmargaux** [comment]
Hi @monu-2311 

You have everything you need in the docs, here https://recharts.org/en-US/api/CartesianGrid#strokeDasharray, you could use the `strokeDasharray` props to get what you need. 

Hope this helps!

**Comment by monu-2311** [comment]
Hii @plxmargaux  I appreciate your help so much.

**Comment by dillonreedy** [comment]
@monu-2311 I have a storybook [here](https://dillonreedy.github.io/recharts-storybook/?path=/story/recharts-line-chart--simple&args=strokeDashArray:5+5;type:!undefined) where you can play around with the different stroke values in the line chart.

![image](https://user-images.githubusercontent.com/3454995/162801071-a0028a20-1353-4f53-815c-0b680ba3de8d.png)

![image](https://user-images.githubusercontent.com/3454995/162801216-9f0c0a90-d9e8-460f-9549-68d55ac0413e.png)
