### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by staevs** [recharts/recharts#2813]
First of all, thanks for all your hard work, I'm kinda impressed and grateful for such an amazing and easily customizable library for building charts

- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Allow projects that use recharts to upgrade to the latest React core version

### What does the proposed API look like?
https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html

**Comment by semi4ka** [comment]
Will thankful too. When I create a new project and try to install recharts: "Could not resolve dependency:
npm ERR! peer react@"^16.0.0 || ^17.0.0" from recharts"

**Comment by mrsolis93** [comment]
Also looking for react 18 support! Looking forward to trying out these charts!

**Comment by madsadi** [comment]
cant install this library with react 18;



While resolving: bacoina@0.1.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project

**Comment by Nefcanto** [comment]
Any idea when this will be ready? Any ETA?

**Comment by Alphavader** [comment]
+1

**Comment by oliver021** [comment]
Hi, I try to install recharts and I get the message error because my project using 18 and recharts using the 17; is it a good idea using `--legacy-peer-deps` flags to force installation?

**Comment by mpcen** [comment]
+1

**Comment by HypeNeutron** [comment]
> You can try this command while the library gets updated: `npm install recharts --force`
> 
> This works but you may enconuter some bugs, the other option is to continue using the previous version of **react 17.0.2**
> 
> `npm uninstall react react-dom` `npm install react@17.0.2 react-dom17.0.2`
> 
> This version is totally compatible with recharts so you wont have any problem using this library with this version Hope it helps!

That Work!!

**Comment by RubenMoraVargas** [comment]
> with
`npm install react@17.0.2 react-dom**@**17.0.2`
Need add the @, thanks

**Comment by hansfpc** [comment]
any update about this?

**Comment by vromaniv-liaison** [comment]
Hey guys, any update on this?

**Comment by Semigradsky** [comment]
PR was merged, try `2.1.11`

**Comment by Bartel-C8** [comment]
For full React 18 "support" (without warnings), this peer dependency should still be updated: https://github.com/recharts/react-smooth/issues/57

```
warning "recharts > react-smooth@2.0.0" has incorrect peer dependency "react@^15.0.0 || ^16.0.0 || ^17.0.0".
warning "recharts > react-smooth@2.0.0" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0 || ^17.0.0".
```

**Comment by hansfpc** [comment]
thank you guys!
