### ISSUE TITLE
`minPointSize` to accept a function instead of just a number?

### ISSUE THREAD

**Issue by markhicken** [recharts/recharts#2819]
- [X] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When a `<Bar>` chart has very small and very large values, the small values don't get rendered. Using `minPointSize={1}` fixes this, but if the point value is `0`, the bar is still rendered at 1 pixel high. It would be ideal if `minPointSize` could ignore `0` values. 

In the following image, May has `0` values, but June and July have small values. In this case, May (the `0` values) should be rendered without the `minPointSize` prop or with it set to `0` while the others should use a value of `1`. 

<img width="392" alt="Screen Shot 2022-04-06 at 1 31 29 PM" src="https://user-images.githubusercontent.com/849930/162054414-689bf2f4-c636-4855-9792-e9001bf2e8c6.png">

One less-than-ideal workaround is to set `0` values to `null`, but this prevents the bar from rendering which means the tooltip also won't work. 

### What does the proposed API look like?
`minPointSize={(dataPoint) => dataPoint === 0 ? 0 : 1}`

**Comment by lenzi-erickson** [comment]
I would also like to hide the bar when 0 or null, but otherwise have a minimum height. This would solve my problem as well. +1

**Comment by sam-chatrlyst** [comment]
+ 1 for this feature, would be a great benefit in applying a fully circular radius

**Comment by smaspe** [comment]
@fluffybone I see you're using a stackId, do you have `minPointSize` working with stacked bars?

**Comment by sam-chatrlyst** [comment]
@smaspe - I managed to get something working with a custom `shape` prop where I built a rectangle. the way I did it was for each bar, work out if the previous bars that are being stacked onto are bigger or smaller than the minPointSize and then manually adjust the x coordinate to account for the minPointSize. I used the background. you can use `x - background.x` to workout the width.

![image](https://github.com/recharts/recharts/assets/130265631/78033037-a01b-4997-b3d6-d190f3a94345)

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/pull/4099 🚀 

Thanks for the comments, helps with visibility. Hopefully can get this in soon

**Comment by rstreefland** [comment]
Hi @ckifer, when do you expect this feature to be released? I came across it in the [documentation](https://recharts.org/en-US/api/Bar#minPointSize) and it's exactly what I need to avoid the workaround posted above. Thanks in advance!

**Comment by ckifer** [comment]
Next minor release most likely. Been trying to release ~monthly and the last release happened about 2 weeks ago.

**Comment by ckifer** [comment]
Released in 2.12!
