### ISSUE TITLE
exact Y position of a cartesian grid

### ISSUE THREAD

**Issue by vtarelkin** [recharts/recharts#2822]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently we have only x position on a cartesian grid obtained by activeLabel

### What does the proposed API look like?
maybe activeLabelX, activeLabelY

**Comment by ckifer** [comment]
Going to close this as stale, please comment back with more details if this is still needed. Y position of what exactly? The grid is over the whole chart
