### ISSUE TITLE
Add line trailing icon

### ISSUE THREAD

**Issue by khalidahmed1101** [recharts/recharts#2824]
![image](https://user-images.githubusercontent.com/78547959/162629030-55e26292-6769-4849-8acf-fd611f126146.png)

Hi all , I want to add this line charts line trailing icon as you can see,
Can anyone help me in this?
thanks

**Comment by khalidahmed1101** [comment]
Thank you so much

**Comment by nktnet1** [comment]
FYI - the JS file has been renamed with the `.jsx` extension.

- https://github.com/dillonreedy/recharts-storybook/blob/819052f95356a324be0ab624cba14455823d044f/src/stories/recharts/linechart/subcomponents/LineTrailingDot.stories.jsx
- https://github.com/dillonreedy/recharts-storybook/blob/819052f95356a324be0ab624cba14455823d044f/src/stories/recharts/linechart/subcomponents/LineTrailingDotComponent.jsx 

> @khalidahmed1101
> 
> So I made a storybook of what you're trying to do which can be found [here](https://dillonreedy.github.io/recharts-storybook/?path=/story/recharts-line-chart-customized-dots--trailing-dot), by adding a 2nd line: ![image](https://user-images.githubusercontent.com/3454995/162798873-22d963f5-a6f0-4991-9ad2-c828d6da6cbc.png)
> 
> I just calculate the last value in the data, and just add a 'lastDot' property to the data entered in for the entire line chart. Then add a 2nd line into the line chart, and key that 2nd line in to the last dot data.
> 
> The code for this can be found [here](https://github.com/dillonreedy/recharts-storybook/blob/main/src/stories/recharts/linechart/subcomponents/LineTrailingDot.stories.js) and [here](https://github.com/dillonreedy/recharts-storybook/blob/main/src/stories/recharts/linechart/subcomponents/LineTrailingDotComponent.js)

**Comment by ckifer** [comment]
We can add this example to the official storybook if it isn't there already. @nikolasrieble FYI or @nktnet1 if you'd like to contribute it

**Comment by nikolasrieble** [comment]
Lets reopen this issue to create a storybook entry.
