### ISSUE TITLE
Cursor position is offset when using zoom/ transform scale

### ISSUE THREAD

**Issue by MS-Zapata** [recharts/recharts#2829]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/recharts/recharts/issues/1829](https://github.com/recharts/recharts/issues/1829)

### Steps to reproduce
Use zoom/ transform scale on parent container

### What is expected?
Correct position of cursor on hover

### What is actually happening?
I encounter this error by using transform: scale(0.8) css style on parent container.
Because of this I can't use Recharts's tooltip.
Any solution/counter measure is appreciated. Thanks.

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 16.14.0 |
| System | windows |
| Browser | chrome |

---
I am using recharts 2.1.7

**Comment by VuTan115** [comment]
i have same issue while using lastest ver 
## "recharts": "^2.1.12"

**Comment by Edaran123** [comment]
Has anyone had any luck with this problem? I'm having the same problem and I'm not really sure what the above commenter meant.

**Comment by ckifer** [comment]
Also unsure what the above commented meant, but can you provide a codesandbox of your issue so we can have a reproduction here?

Also see this comment from me here https://github.com/recharts/recharts/issues/3441#issuecomment-1456289721

**Comment by Edaran123** [comment]
I do not have access to the code right now but it was pretty identical to the reproduction in #3441 - just wrapped in a parent element with scale: 1.3 in the CSS. Interestingly, whether the scale is above or below 1 seems to change the direction that the cursor is off by.

**Comment by ckifer** [comment]
This should work as of https://github.com/recharts/recharts/pull/3748 in 2.9
