### ISSUE TITLE
UMD build includes all of React

### ISSUE THREAD

**Issue by jochenberger** [recharts/recharts#283]
There is something wrong about the Webpack configuration, that makes Webpack include React in the UMD build (see https://unpkg.com/recharts@0.15.1/umd/Recharts.js). I'm trying to find a way to solve this and I believe it is caused by react-smooth. Maybe https://github.com/recharts/react-smooth/pull/6 will help.

**Comment by lorenzos** [comment]
I still see ReactDOM in the UMD build. Is this ok?
