### ISSUE TITLE
Responsive container does not work for React 18 and all other used features does

### ISSUE THREAD

**Issue by pkawula** [recharts/recharts#2831]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dank-sun-5kqkri?file=/src/App.tsx)

### Steps to reproduce
When you open the code sandbox just change react version to 18 and in index file uncomment the react 18 wrapper

### What is expected?
ResponsiveContainer to properly measure height and width

### What is actually happening?
ResponsiveContainer width and height (in state) is undefined

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 18 |
| System | Linux/MacOS/Windows |
| Browser | Any |

**Comment by pkawula** [comment]
I have discovered after installing `react-resize-detector` by myself, that the `<ReactResizeDetector>` component is not rendered somehow, and is not applying the observers; I have also found that `useResizeDetector` works just fine. Maybe it's time to upgrade to hooks?

**Comment by pkawula** [comment]
I figured out why this was happening and I've already made a PR with fix in `react-resize-detector`.
https://github.com/maslianok/react-resize-detector/issues/208

**Comment by michaelbull** [comment]
To work around this I redeclared my own responsive container by referencing rechart's [`ResponsiveContainer`](https://github.com/recharts/recharts/blob/master/src/component/ResponsiveContainer.tsx) but replaced the `ReactResizeDetector` with the [`use-resize-observer`](https://www.npmjs.com/package/@react-hook/resize-observer) hook.

Here's an example below until this bug is addressed. It's hardcoded to only work with 100% width+height, you can refer to the original `ResponsiveContainer` implementation if you need to support more of the original.

```typescript
import useResizeObserver from '@react-hook/resize-observer';
import clsx from 'clsx';
import React, {
    cloneElement,
    CSSProperties,
    isValidElement,
    PropsWithChildren,
    useLayoutEffect,
    useState
} from 'react';

const STYLE: CSSProperties = {
    width: '100%',
    height: '100%'
};

export interface ResponsiveContainerProps {
    readonly className?: string;
}

export function ResponsiveContainer(props: PropsWithChildren<ResponsiveContainerProps>) {
    const {
        className: classNameProp,
        children
    } = props;

    const className = clsx('recharts-responsive-container', classNameProp);
    const [container, setContainer] = useState<HTMLDivElement | null>(null);
    const containerSize = useSize(container);

    const renderChart = () => {
        if (isValidElement(children)) {
            return cloneElement(children, {
                width: containerSize?.width ?? '',
                height: containerSize?.height ?? ''
            });
        } else {
            return null;
        }
    };

    return (
        <div className={className} style={STYLE} ref={setContainer}>
          {renderChart()}
        </div>
    );
}

function useSize(target: HTMLElement | null): DOMRect | null {
    const [size, setSize] = useState<DOMRect | null>(null);

    useLayoutEffect(() => {
        setSize(target?.getBoundingClientRect() ?? null);
    }, [target]);

    useResizeObserver(target, entry => {
        setSize(entry.contentRect);
    });

    return size;
}
```

**Comment by chamce** [comment]
If you just need responsive container to work again and don't need react 18, give your index.js the appearance of a react 17 index.js and your app will behave as if it is running react 17.
![react-17-index-js](https://user-images.githubusercontent.com/78002428/168425570-6f7025f0-2182-456a-9702-63527b573dbc.PNG)
You will get this console warning that confirms your app is running react 17 instead.
![console](https://user-images.githubusercontent.com/78002428/168425874-330657b5-2517-4666-aab4-924570fe5204.PNG)

**Comment by maslianok** [comment]
react-resize-detector v7.1.1 is updated to support React 18.

Thank you everyone for your patience. I was a bit off from my OS projects according to the russian invasion to Ukraine. 
Missles are still flying around, but I'll try to return to normal life.

✌️

**Comment by ealmiladi** [comment]
> react-resize-detector v7.1.1 is updated to support React 18.
> 
> Thank you everyone for your patience. I was a bit off from my OS projects according to the russian invasion to Ukraine. Missles are still flying around, but I'll try to return to normal life.
> 
> ✌️

Slava Ukraine.

**Comment by pkawula** [comment]
Any updates here?

**Comment by ckifer** [comment]
@pkawula 
https://codesandbox.io/s/nervous-framework-rjoyf5?file=/src/App.tsx

Took the codesandbox and updated to latest recharts/react/etc.

Is there still an issue? resize detector version is up to date

**Comment by pkawula** [comment]
Great, closing
