### ISSUE TITLE
tooltip payload is empty until hovered

### ISSUE THREAD

**Issue by aquibbaig** [recharts/recharts#2841]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/boring-stallman-7uphgz?file=/src/App.tsx:548-553)

### Steps to reproduce
The payload is empty unless you hover on any of the pie chart subitems

### What is expected?
I am trying to make the tooltip always show when the chart is generated

### What is actually happening?
The custom tooltip appears only on hover

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | ^17.0.2 |
| System | Mac OS Monterey 12.1 |
| Browser | Chrome Version 100.0.4896.127 (Official Build) (arm64) |

**Comment by ckifer** [comment]
This issue contains everything you should need (though I know this is old)
https://github.com/recharts/recharts/issues/855

Closing as duplicate
