### ISSUE TITLE
Data point not being rendered

### ISSUE THREAD

**Issue by dcox1776** [recharts/recharts#2848]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gracious-feynman-xt0zvd?file=/src/App.js)

### Steps to reproduce
The minimal reproduction illustrates that the last point in the data set is not being rendered when creating a scatter plot with a z-axis. In the reproduction I use 3 data points. But only 2 data points are displayed. If I add a fourth data point, then only 3 are displayed. And so forth.

### What is expected?
Expect the scatter plot to display all the points in the data set.

### What is actually happening?
The last data point is not being dispalyed.

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Chrome 100.0.4896.127  |

**Comment by dcox1776** [comment]
After some more trial and error, it might be that I misunderstand the range property for the z-axis. I find that when I increase the minimum value for the range, the missing data point appears. Can someone provide an explanation about how the range property works? Thank you. For the minimal reproduction that I submitted, if the minimum range is increased to say 200, the missing data point appears.

**Comment by ckifer** [comment]
Reproduction link doesn't have a reproduction. Going to close this as stale
