### ISSUE TITLE
Reference area?

### ISSUE THREAD

**Issue by digorydoo** [recharts/recharts#285]
I'm using ReferenceLine to render an upper and lower limit of some reference range in the y domain of a ScatterChart. This works fine, but can look a bit messy, especially when there is a lot of data on the plot. Filling a rectangle with a slightly darker background starting from the lower y ref line to the upper y ref line and extending the full x width would look much more clean and would also be very intuitive if one of the reference lines is missing (i.e. when the reference range is "open", such as "< 2 mg").

Is it possible to render a filled rectangle on the chart? If not, that would be a great addition to this awesome library.

**Comment by digorydoo** [comment]
Here's how this would look like. I now have:

`<ScatterChart {...chartProps}>
    <ReferenceLine {...lowerRefLineProps} />
    <ReferenceLine {...upperRefLineProps} />
    <XAxis {...xAxisProps} />
    <YAxis {...yAxisProps} />
    <Scatter {...myData} />
</ScatterChart>`

What I'd like to do:

`<ScatterChart {...chartProps}>
    <Rectangle y1="0.5" y2="7.1" bgColor="#f0f0f0" />
    <XAxis {...xAxisProps} />
    <YAxis {...yAxisProps} />
    <Scatter {...myData} />
</ScatterChart>`

**Comment by xile611** [comment]
@digorydoo Recharts has added component `ReferenceArea` in version 0.13.4. But the documentation  is backward. I'll update the documentation of  `ReferenceArea`.

You can use `ReferenceArea` like the following:

```jsx
<ScatterChart width={400} height={400} margin={{ top: 20, right: 20, bottom: 0, left: 20 }}>
   ....         
   <ReferenceArea x1={250} x2={300} alwaysShow />
 </ScatterChart>
```

```jsx
<ScatterChart width={400} height={400} margin={{ top: 20, right: 20, bottom: 0, left: 20 }}>
   ....         
   <ReferenceArea y1={250} y2={300} alwaysShow />
 </ScatterChart>
```

```jsx
<ScatterChart width={400} height={400} margin={{ top: 20, right: 20, bottom: 0, left: 20 }}>
   ....         
   <ReferenceArea x1={0} x2={100} y1={250} y2={300} alwaysShow />
 </ScatterChart>
```

**Comment by xile611** [comment]
[Here](http://recharts.org/api#ReferenceArea) is the api of `ReferenceArea`.
