### ISSUE TITLE
Prop `strokeDasharray` did not match. Server: "null" Client: "0px 0px"

### ISSUE THREAD

**Issue by MarkWasfy00** [recharts/recharts#2850]
first its was giving me Prop 'id' did not match the server then when i give the chart (id="test") it show that error 
![WM-Screenshots-20220502150248](https://user-images.githubusercontent.com/76422492/166238049-4fb90192-66c3-4647-ab53-c6bccaeb28b6.png)

**Comment by ckifer** [comment]
This seems like a next issue due to randomization in recharts - next tries to pre-render everything on the server but then it doesn't match what happens in the client

https://stackoverflow.com/a/66374800/8050147 should help you solve the issue. Closing this for now
