### ISSUE TITLE
Support double click events

### ISSUE THREAD

**Issue by GittiHab** [recharts/recharts#2853]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Charts can already handle multiple mouse events (e.g. `onMouseEnter` or `onClick`), however the documentation does not list `onDoubleClick`. This would be a nice functionality for building charts with advanced interactivity.

My use case was that I am trying to build a chart where the user can zoom in (similar to the [HighlightAndZoom example](https://recharts.org/en-US/examples/HighlightAndZoomLineChart)). I want to allow the user to reset the zoom by double clicking anywhere in the chart.

### What does the proposed API look like?
Add a prop to charts `onDoubleClick` analogously to `onClick` (`onMouseEnter`, and so on).

**Comment by Jaeyong-seo** [comment]
I really really want this function for same reason.

**Comment by ckifer** [comment]
This will be added in 3.x
https://github.com/recharts/recharts/pull/5255

Closing in favor of https://github.com/recharts/recharts/issues/5254

**Comment by ckifer** [comment]
released in 2.14.0
