### ISSUE TITLE
Fixing cursor

### ISSUE THREAD

**Issue by seiyab** [recharts/recharts#2854]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I usually want to fix cursor in charts on some events.
However, AFAIK, it is extremely difficult to achieve with current recharts.
Now, I implement it by diving internal implementation of recharts rather than its public API.

Following sandbox partially shows what I want to do.
https://codesandbox.io/s/silly-beaver-km4yzh?file=/src/App.tsx
Though fixing Tooltip require little hack, fixing Dot seems to require hard hack and will be extremely fragile.

Related Issues
- https://github.com/recharts/recharts/issues/1467
    - It was closed without any solution.
- https://github.com/recharts/recharts/issues/2072 
    - Perhaps it might seem to be duplicated, it is not, in my understand.
    - #2072 says stop Tooltip position and keep cursor move.
    - My suggestion is fixing cursor. (As a result, Tooltip and Dot will be stopped.)

### What does the proposed API look like?
```tsx
<LineChart fixCursor={true}>{...}</LineChart>
<AreaChart fixCursor={true}>{...}</AreaChart>
<BarChart fixCursor={true}>{...}</BarChart>
<ComposedChart fixCursor={true}>{...}</ComposedChart>
```

**Comment by ckifer** [comment]
This has gotten a lot easier recently using the `active` and `defaultIndex` props

[![Edit adoring-rui-l68jc7](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/adoring-rui-l68jc7?file=%2Fsrc%2FApp.tsx%3A17%2C26)

Closing
