### ISSUE TITLE
incorrect prop for Treemap in docs

### ISSUE THREAD

**Issue by rahul-desai3** [recharts/recharts#2857]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://recharts.org/en-US/api/Treemap](https://recharts.org/en-US/api/Treemap)

### Steps to reproduce
see the examples mentioned in https://recharts.org/en-US/api/Treemap and also https://recharts.org/en-US/examples/SimpleTreemap

### What is expected?
Use prop `aspectRatio` instead of `ratio`

### What is actually happening?
incorrect prop `ratio` is being used

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 17.0.2 |
| System | Mac |
| Browser | Chrome |

**Comment by ckifer** [comment]
this is fixed, closing
