### ISSUE TITLE
Rendering CartesianAxis and CartesianGrid is a blocking task that take too much time

### ISSUE THREAD

**Issue by fxdave** [recharts/recharts#2861]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-qj5djv?file=/src/index.js)

### Steps to reproduce
Open with react's profiler and see the times

### What is expected?
I expect fast rendering that will not freeze the site during that time. Note that 60FPS is 16ms. The render function should be completed under 16ms.

### What is actually happening?
The chart's render function took 90ms.

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | ^17.0.2 |
| System | Arch |
| Browser | Chromium |

---
If it cannot be done faster then it is needed to be split into multiple smaller asynchronous tasks. Otherwise the page will be lagging.

![image](https://user-images.githubusercontent.com/12275699/171742843-b8df7349-1ab7-4ae0-9b43-8557cabe25a7.png)

**Comment by ckifer** [comment]
This completes in 6ms in the current version of recharts. resolving as stale
