### ISSUE TITLE
Single tooltip and its value are not going to be shown in the bar chart

### ISSUE THREAD

**Issue by arburhan** [recharts/recharts#2867]
![image](https://user-images.githubusercontent.com/90565640/172812825-052860c8-9616-4bcd-b8e7-26e6fc0fd737.png)

I want to show the tooltip of the bar chart in a single way but it is not happening.
How do I show a tooltip and its value in a single bar like the one above?

**Comment by ckifer** [comment]
Sorry for not answering this in a reasonable amount of time - you can mess around with a custom tooltip (https://codesandbox.io/s/tooltip-with-customized-content-forked-7cn9p9?file=/src/App.tsx:1398-1451)

but currently there is no separation between x axis data keys when using the Tooltip - all items for that x axis key will be rendered in the same tooltip item

**Comment by ckifer** [comment]
There are other tracking issues for this so going to close this one
