### ISSUE TITLE
The legend and its value are not going to be shown together in the pie chart

### ISSUE THREAD

**Issue by arburhan** [recharts/recharts#2868]
![image](https://user-images.githubusercontent.com/90565640/172814164-ecf3bbe9-4c78-4b95-8919-65c1bcc107d2.png)

Using a legend in a pie chart only shows its name but I want the legend to show the data name and its value together as I mentioned in the picture.
How do I do this?

**Comment by ckifer** [comment]
Going to close this as stale, but you would make a custom Legend component - at least until value support is added to Legend by default. Many times for other charts it doesn't make sense to add values to the Legend (line chart) and at the moment there is no special handling for Pie
