### ISSUE TITLE
Real-time chart

### ISSUE THREAD

**Issue by sdoomz** [recharts/recharts#287]
Hi! 
I'am trying to figure out how to connect rechart with async data without full re-rendering. 
Every second I receive new point for area chart and then call setState() with new data collection. That triggers re-rendering :( 

But my questions are:
1. How to keep previously focused tooltip in opened state after new data was added?
2. How to apply only new data without full re-rendering? 
3. How to move xAxis smoothly? [d3 example](https://bost.ocks.org/mike/path/)

Seems like solving the second issue may solve first automatically, or? 
http://jsfiddle.net/sdoomz/y6dw0fgh/

**Comment by xile611** [comment]
@sdoomz 

For your questions:

1. Tooltip is triggered by mouse event now, may be you can use other method to display the new data, for example an `position: absolute;` div or a customized label of `Area`.

2. Temporarily no idea.

3.D3 use path animation to switch path, I have no idea how to add path transition animation when path update now.

**Comment by sdoomz** [comment]
@xile611 Currently it is possible to solve issue with [dynamic charts](http://jsfiddle.net/sdoomz/ams3jyj2/) using Highcharts.js and [react-highcharts](https://github.com/kirjs/react-highcharts) package. But it would be great to see same functionalities in next versions of Recharts.

**Comment by xile611** [comment]
@sdoomz Thanks for great suggestions! We'll try to implement this functionality, maybe through a wrapper component.

**Comment by akvanhar** [comment]
I would like to add another vote for this feature.
I've been experimenting with it on my own by using AnimateGroup from react-smooth as a wrapper to my recharts components.

**Comment by SpaceK33z** [comment]
I'm also looking to implement realtime data, but there are major frame rate issues at the moment. PR #277 will probably fix some of these issues.

**Comment by akvanhar** [comment]
@xile611 would love to hear an update about this enhancement.

**Comment by xile611** [comment]
@akvanhar Yeah, We're trying to refactor the animation part. But it may take some time.

**Comment by akvanhar** [comment]
Thanks for the update. I'll stay tuned and will try to implement a work-around in the meanwhile.

**Comment by xile611** [comment]
OK! Both PR and suggestions are welcome. @akvanhar

**Comment by ruaanvds** [comment]
Is there any known workaround for this at the moment?

**Comment by diegocasmo** [comment]
This is clearly a hack, but given you have a flag variable ``isAnimationActive`` with default to ``true``, you could then listen in for``componentWillReceiveProps()`` (when more data is added to the chart) and set  a ``isAnimationActive=false``. This will cause the animation to only be executed when the component is mounted (the first time the chart is rendered). 

As a down side, when new data-points are added to the chart, no animation from the last point known to the newest one added will be executed (it will just suddenly appear in the chart).

**Comment by msgill1989** [comment]
Is there any update on this please! Would love to implement :)

**Comment by Hrafnkellos** [comment]
+1 for this one!

**Comment by ludobouan** [comment]
Would be nice to have this. I have huge memory leaks when using live data with recharts.

**Comment by jgentes** [comment]
I found a workaround by adding `key={Math.random()}` to the LineChart element, which forces React to redraw the chart when the component re-renders. I also had to use `isAnimationActive={false}`

**Comment by hueitan** [comment]
Here's a workaround hacking solution to simulate the streaming data graph, but you need to tune _the width, padding size, margin and more_, making sure all the configuration fit so it does the animate smoothly.

jsfiddle : http://jsfiddle.net/5fwefg90/
showcase gif :
![stream-example-gif](https://user-images.githubusercontent.com/2560096/32657994-33651986-c618-11e7-9833-583a71ccda1c.gif)

let me know if you have any question related to this hacking solution, but I deeply feel the animation mechanism should be refactored so it can do the **real** smooth animation.

**Comment by ljwagerfield** [comment]
@hueitan great work! The Chrome memory profiler indicates it leaks about 100KB on every update, so 70MB per hour.

Not the end of the world, but not good either.

Any idea how to prevent this?

**Comment by komorebi-san** [comment]
Any update on this feature?

**Comment by NathanCH** [comment]
Animation is a big problem in this library when using ResponsiveContainer or when swapping the dataset.

![bad-animation](https://user-images.githubusercontent.com/1985888/39546727-3f4dd24a-4e0a-11e8-8e20-7a45a0cc2496.gif)

Currently the best thing you can do is disable animations unfortunately.

**Comment by bilaltahseen** [comment]
You can use my version , its simple and yet effective,

`
import {useState,useEffect, useRef} from 'react'
// import socketIOClient from "socket.io-client";
import {LineChart,
  CartesianGrid,
  YAxis,
  Tooltip,
  Legend,
  Line} from 'recharts'


// const ENDPOINT = "http://127.0.0.1:4001"; 


function Chart() {
  const [response, setResponse] = useState([]);
  const [time,setTime] = useState('');
  const [arr,setArr] = useState([{X:0},{X:0},{X:0},{X:0},{X:0},{X:0},{X:5},{X:5},{X:5},{X:5},{X:5},{X:5},{X:0},{X:0},{X:0},{X:0},{X:0},{X:0},{X:0},{X:0},{X:0},{X:0},{X:0},{X:5},{X:5},{X:5},{X:5},{X:5},{X:5},{X:0},{X:0},{X:0},{X:0},{X:0},{X:0},{X:0},{X:0},{X:0},{X:0},{X:0},{X:5},{X:5},{X:5},{X:5},{X:5},{X:5},{X:0},{X:0},{X:0},{X:0},{X:0},{X:0},{X:0},{X:0},{X:0},{X:0},{X:0},{X:5},{X:5},{X:5},{X:5},{X:5},{X:5},{X:0},{X:0},{X:0},{X:0},{X:0}]);
  const timeoutRef = useRef(null);
  function validate() {
    setArr((prevState)=>[...prevState,{X:(Math.random()>=0.5)? 5 : 0}].slice(1))
  }

  useEffect(() => {
    if (timeoutRef.current !== null) {
      clearTimeout(timeoutRef.current);
    }
   let interval = 6000;
   let speed = 100;
   for(let i=0;i<interval;i++){
    timeoutRef.current = setTimeout(()=> {
      timeoutRef.current = null;
      validate()
    },i*speed);
   }
  },[]);
  return (
    <div>
        <h1>{time}</h1>
        <LineChart width={730} height={250} data={arr}
  margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
  <CartesianGrid strokeDasharray="3 3" />
 
  <YAxis />
  <Tooltip />
  <Legend />
  <Line type="monotone" dataKey="X" stroke="#8884d8" />

</LineChart>
 
    </div>
  );
}

export default Chart;


`

Example:
![captured](https://user-images.githubusercontent.com/46894582/97808454-c6b7db00-1c88-11eb-877f-eed7018bbff3.gif)

**Comment by komorebi-san** [comment]
@bilaltahseen Cool! However, have you stress test it for memory leak?

**Comment by bilaltahseen** [comment]
Yeah I did that, it was okay for me

**Comment by abhijeet1995** [comment]
How to implement web socket for moving graph

**Comment by aditya5chiku** [comment]
How do I implement A realtime Moving Graph like above when I have to handle Realtime Data thoroght socketio

**Comment by bilaltahseen** [comment]
Call socket on method with data in this function 
function validate() {
    setArr((prevState)=>[...prevState,{X:(Math.random()>=0.5)? 5 : 0}].slice(1))
  }
Replacing Math.random witb data from socket

**Comment by aditya5chiku** [comment]
Please share your mail id i need to ask one daubt

**Comment by PavelVanecek** [comment]
Here's a preview of new feature in 3.9 that will allow this: https://recharts.github.io/recharts/pr-7215/www/en-US/examples/AnimatedTimeSeriesExample/
