### ISSUE TITLE
Bar - Tooltip with background gray when hover

### ISSUE THREAD

**Issue by dkrefta** [recharts/recharts#2870]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/simple-bar-chart-forked-2ll5vw?file=/src/App.tsx)

### Steps to reproduce
Hover the bar and the tooltip will be all gray :(

### What is expected?
when I hover over the bar I presume that is a problem to not see the bar because of the gray background

### What is actually happening?
is showing a solid gray background

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by denisknk** [comment]
Hi! Just  put a <Tooltip /> Component before your <Bar/> component,  this all renders by layers, so what what is first in the code, will be the most far layer. Here is an image with your example being as you want 
<img width="1293" alt="Screen Shot 2022-06-10 at 10 39 19 PM" src="https://user-images.githubusercontent.com/77339624/173154675-826833e3-59af-459c-b0d7-6dd1ae2dcbfc.png">
s

**Comment by dkrefta** [comment]
@denisknk hey dude, thanks very much, that solved the problem 👍
