### ISSUE TITLE
[Doc] ScatterChart example missing type="number" on Scatter components

### ISSUE THREAD

**Issue by leocrapart** [recharts/recharts#2874]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-2ejc6k?file=/src/index.js)

### Steps to reproduce
copy paste the documentation example
fix the import statements so that it works

### What is expected?
Same plot than documentation here https://recharts.org/en-US/api/ScatterChart

### What is actually happening?
 The ScatterChart on screen is not same as documentation one, x axis isn't sorted.

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | react version 16.8.6 |
| System | Windows 10 |
| Browser | Brave Version 1.39.111 Chromium: 102.0.5005.61  |

---
Easy fix : adding type="number" on the XAxis component fixes the issue.
Just need to add it to the documentation if that's something missed. 
Else it could be a real bug if <Scatter> is expected to be type="number" by default.

**Comment by ckifer** [comment]
Thanks!

Closed by https://github.com/recharts/recharts.org/pull/251
