### ISSUE TITLE
Move zoomed chart with the help of the mouse / keyboard

### ISSUE THREAD

**Issue by vtarelkin** [recharts/recharts#2876]
I dare to make zoom by the square user selects in a chart, but now I want to implement the possibility to move chart left or right, upper or lover similar to drag function. Anyone did that stuff? I think I should do some domain / ticks recalculations....

**Comment by ckifer** [comment]
Hi @vtarelkin 

It would be helpful if you could provide a reproduction - since your code is custom we have no knowledge of your drag implementation. This isn't supported in recharts as it stands. Thanks!

**Comment by ckifer** [comment]
Going to close this as stale until more details are added
