### ISSUE TITLE
ResponsiveContainer does not resize when using React.StrictMode

### ISSUE THREAD

**Issue by robcaldecott** [recharts/recharts#2878]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/boring-kalam-xilq36?file=/src/App.tsx)

### Steps to reproduce
Run the sandbox and resize the browser window. The chart will not resize.
Edit `index.tsx` to remove `React.StrictMode` and the chart will resize correctly.

### What is expected?
Resizing the window should resize charts inside a `ResizeContainer` when `React.StirctMode` is enabled.

### What is actually happening?
When using `React.StrictMode` with a chart inside a `ResponsiveContainer`, the chart will not resize when the browser window size changes.
Removing `React.StrictMode` will make the container work as expected.

| Environment | Info |
|---|---|
| Recharts | v2.1.10 |
| React | 18.0.0 |
| System | MacOS 12.3.1 |
| Browser | Chrome |

---
Recharts is v2.1.10
This issue is easily reproduced using codesandbox (see link above)
Observed in both NextJS and Vite apps.

**Comment by YannLeon** [comment]
Same problem here since switching to React 18

**Comment by baxri** [comment]
Any updates here? have the same problem also.

**Comment by ckifer** [comment]
Upgrading to the latest v2.2.0+ fixes this issue with the resize-detector upgrade. Closing this as resolved
