### ISSUE TITLE
Release Recharts 1.8.6

### ISSUE THREAD

**Issue by hislopzach** [recharts/recharts#2879]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://github.com/recharts/recharts/pull/2775 was merged 2022/02/10, fixing a typo in the prop-types definition for rechart's Tooltip component. However, this change was never released officially (behind a 1.8.6 tag). This failure is causing my project's storybook build step to fail. The code is already merged, please release this fix as version 1.8.6

### What does the proposed API look like?
recharts `1.x` branch at sha `60b62e4f52c33657489cb66470adea17210b2049` released as a 1.8.6 tag to NPM

**Comment by ckifer** [comment]
If you want to solve the issue you best best is probably upgrading to 2.x.x right now. One person currently has npm publish permissions and until we get a better process in place for releases upgrading to 2.x.x is easier to unblock yourself. Thanks for understanding - I'll leave this open as a reminder for us

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/releases/tag/v1.8.6

1.8.6 is released and recharts@1 is even with the 1.x branch. Closing as completed
