### ISSUE TITLE
onChange function provided to Brush doesn't get called

### ISSUE THREAD

**Issue by abpai** [recharts/recharts#288]
An `onChange` function provided to Brush as a prop does not get called. 

Here is an example: http://jsfiddle.net/xtdssj96/6/

If the `onChange` prop is called `onUpdate` instead, this resolves the issue. If that change is acceptable, I'm happy to open a pull request and update the corresponding documentation.

Thanks for the great work on this library! Cheers!

**Comment by xile611** [comment]
@abpai  The `onChange` of Brush is overwrote by internal event handler in [generateCategoricalChart](https://github.com/recharts/recharts/blob/master/src/chart/generateCategoricalChart.js#L726). Maybe we should refactor  generateCategoricalChart to not simply overwrite.

**Comment by abpai** [comment]
Got it. Thanks! I'll open a PR.
