### ISSUE TITLE
Recharts v2.10.0 and Rollup - ResponsiveContainer/ResizeObserver issue

### ISSUE THREAD

**Issue by JoeVanGundy** [recharts/recharts#2880]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackoverflow.com/questions/72723322/recharts-and-rollup-responsivecontainer-resizeobserver-issue](https://stackoverflow.com/questions/72723322/recharts-and-rollup-responsivecontainer-resizeobserver-issue)

### Steps to reproduce
I tested Recharts v2.10.0 and got the error (the issue ui won't let me choose 2.10.0 btw).
However, I pulled down v1.8.5 and the error was not present.

1. Setup a rollup build 
2. Have a plot/component that uses ResponsiveContainer
3. Build the package
4. Import the package and attempt to use a component that uses ResponsiveContainer

### What is expected?
For ResponsiveContainer to work after being built with Rollup on.
I'm going to continue with v1.8.5, but hope this is something I'm doing or a bug that can be fixed so we can move to v2!

### What is actually happening?
When I go to render my plot that was built with Rollup, I get the following error. I only seem to be having issues with the ResponsiveContainer component. If I remove that from the project, everything works as expected.

The only thing I could find is some people are suggesting a polyfill, but there should be no reason I need one since I'm not really doing anything out of the ordinary?

TypeError: Failed to construct 'ResizeObserver': 
Please use the 'new' operator, this DOM object constructor cannot be called as a function.

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 16.11.0 |
| System | Mac OS |
| Browser | Chrome |

---
Here is how I'm using the component
    <div style={{ width: '300px', height: '300px', userSelect: 'none' }}>
      <ResponsiveContainer width={700} height="80%">
        <AreaChart
          width={500}
          height={300}
          data={data}
          margin={PLOT_MARGIN}>
          ...
        </AreaChart>
      </ResponsiveContainer>
    </div>

Here is my Rollup config
  // // UMD
  {
    input,
    output: {
      file: packageJSON.browser,
      format: 'umd',
      sourcemap: true,
      name: 'my-package-name',
      globals: {
        react: 'React',
      },
    },
    plugins: [
      babel({
        exclude: 'node_modules/**',
      }),
      external(),
      nodeResolve({ extensions: ['.mjs', '.js', '.jsx', '.json', '.node'] }),
      commonjs(),
    ],
  },

**Comment by JogiPrasadPakki** [comment]
Yes i had faced same error when using **vite build** it's work well on dev mode but not in production mode. It throws **TypeError: ResizeObserver constructor: 'new' is required** 

### My environment
| Environment  | Info |
| ------------- | ------------- |
| react  | 18.2.0 |
| recharts  | 2.1.8 |
| vite | 3.0.0 |
| @vitejs/plugin-react | 2.0.0 |
| OS | Ubuntu |

**Comment by konradkalemba** [comment]
@JogiPrasadPakki For anyone still having this issue with `vite build` like me: it's been resolved on the latest version of recharts - update the package and it should work correctly.

**Comment by gordonlau** [comment]
@konradkalemba 

Same in my case. Upgrading to the latest version solves the issue.

**Comment by ckifer** [comment]
Closing this since its resolved in the most recent version of recharts
