### ISSUE TITLE
Bar chart Y axis first key is not showing valid bar 

### ISSUE THREAD

**Issue by sonu-c247** [recharts/recharts#2890]
In bar chart Y-axis first key is not showing at correct place

![image](https://user-images.githubusercontent.com/33275626/176458254-7c7f33a9-60fa-47f8-8ad7-ce027c2ebd18.png)

Line chart version of same

![image](https://user-images.githubusercontent.com/33275626/176459118-6b722ee3-429e-4e79-b1d3-34d6e555b479.png)

In line chart both Y-axis and X-axis key showing at same intersection point but in bar chart it does not showing like that.

    Sample data
    const data = [
    {
        "cca2a517_19a8_4765_8cf0_4ddb482b0092": "Mechanical",
        "timestamp": "2022-06-29T12:16:16.000Z",
        "extra_timestamp_field": 1656504976000
    },
    {
        "cca2a517_19a8_4765_8cf0_4ddb482b0092": "Electrical",
        "timestamp": "2022-06-29T12:16:17.000Z",
        "extra_timestamp_field": 1656504977000
    }
]

Sample Code
           `   <BarChart
            data={data}
            margin={{ top: 0, right: 20, bottom: 0, left: 20 }}
          >
            <XAxis
              dataKey={"extra_timestamp_field"}
              type="number"
              scale="time"
              domain={[1656504976000, 1656504977000]}
              allowDataOverflow
            />
            <YAxis type={"category"} />
            <CartesianGrid />
            <Bar
              key={"cca2a517_19a8_4765_8cf0_4ddb482b0092"}
              dataKey={"Mechanical"}
              name={"Connector"}
            />
          </BarChart>
    `

   Is this is default behaviour of bar chart with category type axis?

**Comment by ckifer** [comment]
Unsure of what you are trying to do here. Can you please attempt a reproduction here? https://codesandbox.io/s/nice-aj-9r0dk7?file=/src/App.js

It seems there are a few incorrect specifications in the sample code, but its hard to tell you what you need without knowing the intention.

**Comment by ckifer** [comment]
Going to close this as stale until more details are added
