### ISSUE TITLE
Upgrade d3-color to version 3.1.0 or higher.

### ISSUE THREAD

**Issue by aalejandromr** [recharts/recharts#2891]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Snyk has reported a medium severity security issue with the d3-color used by d3-scale. Please update this package so it loads the latest d3-color package.

### What does the proposed API look like?
For more information please visit https://security.snyk.io/vuln/SNYK-JS-D3COLOR-1076592

**Comment by wojtekmaj** [comment]
recharts 2.1.13 accepts d3-color 3.1.0 now.

**Comment by aalejandromr** [comment]
@wojtekmaj I can confirm upgrading to `2.1.13` resolves the security alert by Snyk.

Thanks for looking into this!
