### ISSUE TITLE
Recharts XAxis not functioning as expected

### ISSUE THREAD

**Issue by vanshreddy** [recharts/recharts#2901]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/spring-river-gldlle?file=/src/App.js)

### Steps to reproduce
Check the sandbox link out and you can see the issue is straighforward. For each X axis value it is rendering more times than needed.

### What is expected?
All the data I get here is dynamic. Expected behaviour is `test0` key in data should only graph out one bar with 7 ( 2 5) and `test1` should only chart one bar with 2 (1 1). Additionally data key inside `test0` or `test1` will have other keys like `t1` which need to be stacked on top of each respective bar.

### What is actually happening?
For each x axis value it is rendering twice.

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 16.8.61 |
| System | Mac |
| Browser | Chrome |

---
New to the whole recharts environment so might be a small issue but frustrated and annoyed that I cant see it. Thanks in advance

**Comment by ckifer** [comment]
Hi @vanshreddy 

Not sure what you mean by this, everything seems to be rendering fine. The given example is confusing and the issue is not clear. Can you give a contrived example that makes the reproduction easier to understand?

This seems like a data structuring issue that isn't on recharts as a library

**Comment by ckifer** [comment]
Going to close this as stale until more details are added
