### ISSUE TITLE
Fix for d3-color vulnerability issue

### ISSUE THREAD

**Issue by nandeshwarshubh** [recharts/recharts#2908]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-k2xqp)

### Steps to reproduce
-

### What is expected?
Fix for vulnerability scanned by Snyk - https://app.snyk.io/test/npm/recharts/2.1.6

### What is actually happening?
-

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 17.0.2 |
| System | Mac |
| Browser | Chrome 103.0.5060.114 |

---
Vulnerable module: d3-color
Introduced through: d3-interpolate@2.0.1 and d3-scale@3.3.0
Detailed paths
Introduced through: recharts@2.1.6 › d3-interpolate@2.0.1 › d3-color@2.0.0
Remediation: Upgrade to recharts@2.1.7.
Introduced through: recharts@2.1.6 › d3-scale@3.3.0 › d3-interpolate@2.0.1 › d3-color@2.0.0
Remediation: Upgrade to recharts@2.1.7.
Overview
d3-color is a Color spaces! RGB, HSL, Cubehelix, Lab and HCL (Lch).

Affected versions of this package are vulnerable to Regular Expression Denial of Service (ReDoS) via the rgb() and hrc() functions.

**Comment by wojtekmaj** [comment]
recharts 2.1.13 accepts d3-color 3.1.0 now.

**Comment by nandeshwarshubh** [comment]
> recharts 2.1.13 accepts d3-color 3.1.0 now.

Great! Thanks @wojtekmaj !!!
