### ISSUE TITLE
Custom Legend's props is missing in Typescript

### ISSUE THREAD

**Issue by leadq** [recharts/recharts#2909]
I render custom Legend component and using Typescript. When I log payload data of CustomLegend I can see that "dataKey" property is there, but Payload type which comes from "DefaultLegendContent.d.ts" does not include that property. Is there here wrong or am I wrong? I am providing screenshots but not the code, because I can't open codesandbox or smth from my laptop.

![image](https://user-images.githubusercontent.com/16306521/179730437-3d56464d-e1b6-48d8-8a7f-b5b5b40ee2f3.png)

![image](https://user-images.githubusercontent.com/16306521/179730651-9a100f77-2d8e-4b1f-83de-d7c0d5f840bd.png)

After this issue, I tried to find a solution but couldn't do. Also I saw that "Payload" in "DefaultTooltipContent.d.ts", it takes TValue and TName as a generic type and passes to "value" and "name" type, but Legend not. Maybe the payload property should be same on both

DefaultTooltipContent.d.ts
![image](https://user-images.githubusercontent.com/16306521/179738228-5fc24e25-fcf0-4494-bc22-23fe6948f3a8.png)

EDIT:
By the way, you can see that there is one more "payload" property in nested object (in chrome devtools screenshot), I can see that it also has dataKey property, but Payload type in DefaultLegendContent does not include it. It  is like this: 

```
interface Payload {
  ... // some props
  ...
  type?: LegendType;
  color?: string;
  payload?: {
    strokeDasharray: ReactText;  // here
  }
  ... // some props
  ...
 }
```

**Comment by TooMuchLagWillKillYou** [comment]
dataKey has the **?** sign on its declaration, that means it could be null. If you're sure that dataKey would never be null, just add the **!** like this:
`<li key={`item-${entry.dataKey!}`}>`

**Comment by leadq** [comment]
no , it is not there are 2 nested payloads as you can see. One starting with "interface Payload" and another is its property . I wrote // here in that code above. Your answer for parent Payload. Yes, parent payload has dataKey? property but it is not the case. Inner payload property has only strokeDashArray property without extending any html type

**Comment by SharonGrossman** [comment]
👍 for this, any insights?

**Comment by ckifer** [comment]
If we can get a simple reproduction of this someone can take a look

**Comment by ckifer** [comment]
Yeah I think this issue is mostly from the fact that recharts used to be JS only and the refactor to TS wasn't 100% completed and then the fact that that was true got lost when things were handed off to other people, etc.

The differences need analyzed and things need to be updated to what is currently true. This shouldn't be a huge effort if someone wants to take it on!
