### ISSUE TITLE
Documentation missing: Fill background for CartesianGrid component

### ISSUE THREAD

**Issue by sdoomz** [recharts/recharts#291]
Hi!
I'am trying to customise my chart and fill background in this way:
`<CartesianGrid strokeDasharray='5 5' fill='red' />`
This code doesn't work for me, background still transparent. Any ideas?

**Comment by xile611** [comment]
@sdoomz CartesianGrid only render some lines now. So the props `fill` can the grid of  `CartesianGrid`.

And would you like to fill all the grid by `red`?

**Comment by sdoomz** [comment]
@xile611 I want to change background color of AreaChart and I thought that CartesianGrid is good way to do this. 
`.recharts-cartesian-grid` is direct area what I want to fill with new background color.

**Comment by xile611** [comment]
OK! It'll be a feature in the next version.

**Comment by raph90** [comment]
Hi, is this added? It's exactly what I'm looking for!

**Comment by nikolasrieble** [comment]
While this feature has been implemented, it is not yet documented. Thus I am reopening this, just to keep track of the last thing left to be done. 

Document "fill" and "fill-opacity" on the CartesianGrid.

<img width="1198" alt="Screenshot 2023-02-26 at 08 05 46" src="https://user-images.githubusercontent.com/27995606/221397121-34d32b5c-dd00-4306-9a68-e8afb10b6bc8.png">

**Comment by nikolasrieble** [comment]
Related https://github.com/recharts/recharts/issues/2856
