### ISSUE TITLE
tick count is not working for  type category ... may i know how can i set tick count.. can someone help me

### ISSUE THREAD

**Issue by TajSaida** [recharts/recharts#2912]
<XAxis
                                className="firstXaxis"
                                domain={['dataMin', 'dataMax']}
                                id="name"
                                type="category"
                                xAxisId="0"
                                // domain={['auto', 'auto']}
                                tickLine={false}
                                axisLine={false}
                                dataKey="date"
                                stroke={'#414141 !important'}
                                interval={0}
                                tickCount={8}
                            />

**Comment by aashutoshshr** [comment]
@TajSaida `tickCount` doesn't apply if the type is a category. you can see it in detail in this [doc](https://recharts.org/en-US/api/XAxis#tickCount)

**Comment by ckifer** [comment]
Closing this as completed since the docs have been pointed to. tick count doesn't apply to `category` axes.
