### ISSUE TITLE
Order of Bars not depending on React Code Order

### ISSUE THREAD

**Issue by andrewdoro** [recharts/recharts#2913]
I am trying to display multiple bars for the category using this data. Data is ordered by the financial year. And every object has a unique id as string.  I can't change the order in the object because Chrome (and other V8 env) sort the object keys in ascending form.
In the following image you can see the order of bars is depending on the keys order in the object.

As you can see in the example the items in the tooltip render in a different order (the right one)
![image](https://user-images.githubusercontent.com/17547035/180432528-c1ab2253-f1a1-4fed-bc1f-abdc5a3188e1.png)

```
//data that I use for the chart
{
    "29": {
        "Concepts within a chain": 3.26,
        "Independent concepts": 9.18
    },
    "88": {
        "Concepts within a chain": 1.75,
        "Independent concepts": 7.19
    },
    "95": {
        "Concepts within a chain": 21.95,
        "Independent concepts": 27.08
    },
    "financialYear": "2015"
}
```
```
//object used to map and display bars
[
    {
        "id": 95,
        "color": "blue"
    },
    {
        "id": 29,
        "color": "red"
    },
    {
        "id": 88,
        "color": "yellow"
    }
```
 ```
]
{areasId.map((area) => {
          return (
            <Fragment key={area.id + 'id'}>
              <Bar
                dataKey={`${area.id}.${t('area_profile.competitive.chain.chained')}`}
                fill={
                  mode.type === 'compare'
                    ? addAlpha(theme.palette.common[area.color], 0.5)
                    : '#D1D9DF'
                }
                stackId={area.id}
              />
              <Bar
                dataKey={`${area.id}.${t('area_profile.competitive.chain.independent')}`}
                fill={mode.type === 'compare' ? theme.palette.common[area.color] : '#44526C'}
                stackId={area.id}
                style={{ transform: 'translate(0,-1px)' }}
                radius={[4, 4, 0, 0]}
              />
            </Fragment>
          )
        })}


```

**Comment by TooMuchLagWillKillYou** [comment]
Have you tried to render a custom tooltip? You can do so by using the **content** prop (https://codesandbox.io/s/tooltip-with-customized-content-lyxvs). Plus, I think you should provide a code snippet for better understanding and increasing the chance to find the right solution

**Comment by andrewdoro** [comment]
I don't want to change the order in the tooltip, I will add codepen for this.

**Comment by frangte** [comment]
@andrewdoro  did you find any solution?
