### ISSUE TITLE
Release 2.1.13

### ISSUE THREAD

**Issue by nypinstripes** [recharts/recharts#2915]
The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.

Please tell us what is in v2.1.13 on the changelog , thanks.
---

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

**Comment by SferaDev** [comment]
Seems to be a broken release, very weird...

https://cdn.skypack.dev/recharts@2.1.12
https://cdn.skypack.dev/recharts@2.1.13

**Comment by WolfyUK** [comment]
At the very least it seems to include https://github.com/recharts/recharts/pull/2893 which has caused us some issues

**Comment by fyoung-cpi** [comment]
**After upgrading to 2.1.13, my Jest tests started failing:**

`Jest encountered an unexpected token`

`Details:

    /Users/frank.young/Documents/chargepoint/repos/fleet-platform/frontend/node_modules/d3-shape/src/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export {default as arc} from "./arc.js";
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'`
`

This confirms issue with #2893

**Comment by derekeder** [comment]
also getting this error after upgrading to 2.1.13:

```
/app/node_modules/d3-scale/src/index.js:1
export {
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

**Comment by WolfyUK** [comment]
Hopefully @jmfrancois is aware of the above. I had the same issue as @fyoung-cpi which I did manage to workaround using [this solution](https://stackoverflow.com/a/54896569/504477), but to me a patch version upgrade should not mean I need to make any other configuration changes.

```json
"scripts": {
  "test": "jest --transformIgnorePatterns \"node_modules/(?!d3-shape)/\"",
},
```

**Comment by jmfrancois** [comment]
Yes we have the same on our side. I was not aware at the time of the PR (tests are ok on the repository), but fixing the CI is quite easy. You have three options like discribed here

use `moduleNameMapper`

```
moduleNameMapper: {
		'^d3$': path.join(require.resolve('d3'), '../../dist/d3.min.js'),
		'^d3-shape$': path.join(require.resolve('d3-shape'), '../../dist/d3-shape.min.js'),
		'^d3-path$': path.join(require.resolve('d3-path'), '../../dist/d3-path.min.js'),
		'^d3-scale$': path.join(require.resolve('d3-scale'), '../../dist/d3-scale.min.js'),
		'^d3-array$': path.join(require.resolve('d3-array'), '../../dist/d3-array.min.js'),
		'^d3-interpolate$': path.join(
			require.resolve('d3-interpolate'),
			'../../dist/d3-interpolate.min.js',
		),
		'^d3-color$': path.join(require.resolve('d3-color'), '../../dist/d3-color.min.js'),
		'^d3-format$': path.join(require.resolve('d3-format'), '../../dist/d3-format.min.js'),
		'^d3-time$': path.join(require.resolve('d3-time'), '../../dist/d3-time.min.js'),
		'^d3-time-format$': path.join(
			require.resolve('d3-time-format'),
			'../../dist/d3-time-format.min.js',
		),
```
you can generalized it.

Option :two:  is to use `transformIgnorePatterns` to stop ignore d3 packages [`/node_modules/(?!d3|d3-x|d3-y|...)`],
The issue I have with this one is I have also to add to do it with some d3 deps which are also on es6.

Option :three: is to stop ignore all node_modules because more and more deps start to use es6 imports in apcakage.json main

Complete PR on my side https://github.com/Talend/ui/pull/4081#issuecomment-1198054707

**Comment by klausbadelt** [comment]
#2919 doesn't help with NextJS build errors though. Don't really know what to do here.

`next build` results in
```
> Build error occurred
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/kb/src/filmhub/web/node_modules/d3-shape/src/index.js from /Users/kb/src/filmhub/web/node_modules/recharts/lib/shape/Symbols.js not supported.
Instead change the require of index.js in /Users/kb/src/filmhub/web/node_modules/recharts/lib/shape/Symbols.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/kb/src/filmhub/web/node_modules/recharts/lib/shape/Symbols.js:14:16)
    at Object.<anonymous> (/Users/kb/src/filmhub/web/node_modules/recharts/lib/component/DefaultLegendContent.js:16:16)
    at Object.<anonymous> (/Users/kb/src/filmhub/web/node_modules/recharts/lib/component/Legend.js:16:29)
    at Object.<anonymous> (/Users/kb/src/filmhub/web/node_modules/recharts/lib/index.js:317:15)
```

**Comment by nypinstripes** [comment]
@arcthur just giving a heads up, thanks

**Comment by jmfrancois** [comment]
@klausbadelt could you please provide an example on which i can help ?
It seems pretty common I found many results around nextjs with this error and also with d3

**Comment by monsieurnebo** [comment]
Hello,

Thanks for your work on `recharts`.

Could you update the changelog with `2.1.13` please? It's pretty sensitive to update dependencies without knowing what contains the new version (and if it is breaking).

**Related to:**
https://github.com/recharts/recharts/issues/2658
https://github.com/recharts/recharts/issues/2918

**Comment by klausbadelt** [comment]
@jmfrancois we have `recharts": "2.1.13"` in `package.json`, and our code simply imports from recharts like this
```js
import {
  XAxis, YAxis, BarChart, Bar, Tooltip, CartesianGrid, ResponsiveContainer, Legend,
} from 'recharts'
```
When running `next build` we get the error posted above. Hope this helps!
