### ISSUE TITLE
Tooltip border issue in Recharts v2.1.13

### ISSUE THREAD

**Issue by Pe5h4** [recharts/recharts#2920]
**I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.**

**Reproduction link**

https://codesandbox.io/s/pedantic-butterfly-fo30ni?file=/src/App.tsx

**Steps to reproduce**

1. Take Recharts Simple Bar chart example and open it in the codesandbox https://recharts.org/en-US/examples/SimpleBarChart

2. Upgrade recharts to `v2.1.13` in package.json

**What is expected?**

Chart tooltip should not have a visible border if not defined.

**What is actually happening?**

The tooltip border appears. In Firefox browser its solid `red` color, in Chromium its solid `black` color. The border appears randomly and there is no way how to remove it with CSS.

![tooltip-issue](https://user-images.githubusercontent.com/45622755/181775559-cf060ccb-5ba4-4119-997d-f544fbbd49b0.png)

**Comment by DaylAppReactNative** [comment]
Having the same issue, anyone find a fix?

**Comment by carvares** [comment]
Same issue here, using a previously version does not fix it.

**Comment by kahx** [comment]
Solved with installing 2.1.10 version...

**Comment by carvares** [comment]
Using version 2.1.10 do not solved for me....

**Comment by qls6649** [comment]
add property wrapperStyle={{ outline: "none" }}  at Tooltip
<Tooltip wrapperStyle={{ outline: "none" }} />

**Comment by carvares** [comment]
> add property wrapperStyle={{ outline: "none" }} at Tooltip <Tooltip wrapperStyle={{ outline: "none" }} />

It solved for me, thanks a lot!

**Comment by mautini** [comment]
Hi same problem here. Adding `outline: "none"` partially solve the problem because the border disappear but the bug also cause the page to scroll automatically when the tooltip appeared and it's still there with `outline: "none"`.

For now I downgrade to 2.1.12

**Comment by ryancrunchi** [comment]
I have the same issue. I think wrapper style should be `outline: 'none'` by default

**Comment by digivorefr** [comment]
Possible common issue between this one and #2959

**Comment by aikewoody** [comment]
Totally agree that the proposed behaviour should be the default!

**Comment by ckifer** [comment]
Hi all,

Sorry this issue has been hanging. I believe that this is because of `tabIndex="-1"` being set on the tooltip. Meaning that the border is actually set by default browser behavior when you hover over the tooltip it focuses and hence the border seen (though mine is always blue)

This commit https://github.com/recharts/recharts/commit/fbf387bf538890b5b0d0e5fa60628a8565662810#diff-c3c6e68951cf74127c73a53cfaae21fb64812dbcafbbc54f85b38fd30b85f54b

Added `tabIndex="0"` and since then the browser auto-focuses the tooltip causing the appearance of an outline.

Related #3063 #2914

I'm not an accessibility person, but it seems to me the approach taken in #2914 did not consider side effects of the change

**Comment by aushwin** [comment]
@ckifer should we add the default styles as outline: none ?

**Comment by ckifer** [comment]
@aushwin I don't think that fixes the broader issue.

**Comment by snowcoder10** [comment]
> add property wrapperStyle={{ outline: "none" }} at Tooltip <Tooltip wrapperStyle={{ outline: "none" }} />

I am seeing this issue using a custom component for the tooltip as well. This does fix the issue for now, but would be nice if the custom component's styling was used as an override.

**Comment by ninezero90hy** [comment]
@dlog6649 Thanks! Bro 💜

**Comment by ckifer** [comment]
Fixed in 2.6!

**Comment by 9alex12** [comment]
> add property wrapperStyle={{ outline: "none" }} at Tooltip <Tooltip wrapperStyle={{ outline: "none" }} />

works for me, thanks
