### ISSUE TITLE
Piechart Layout=vertical not applying/working

### ISSUE THREAD

**Issue by DenysAshikhin** [recharts/recharts#2921]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-k19gpo?file=/src/index.js)

### Steps to reproduce
Run the repro codesandbox?

### What is expected?
The legend is listed vertically, as per parameters

### What is actually happening?
The legend is listed horizontally

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | ReactJS v 17.0.2 |
| System | Windows 10 |
| Browser | Google Chrome (latest Update) |

---
N

**Comment by llnathanll** [comment]
The code appears to be rendering the `<Legned layout="horizontal | vertical"/>` in the correct orientation:

![image](https://user-images.githubusercontent.com/273450/182257764-fb92bb00-1fac-45d0-9c4e-0ec9cc83a553.png)

![image](https://user-images.githubusercontent.com/273450/182257631-24b5dbec-b8e5-41cd-9ead-644ab437750a.png)

**Comment by DenysAshikhin** [comment]
Apologies, the code pen didn't save when I originally had it broken. However, now I cannot recreate the issue in the codepen at all. The codepen has been updated with essentially all of the relevant css + jsx as far as I can tell.

It **IS** happening on my end though.
![image](https://user-images.githubusercontent.com/10791321/182417505-714941cd-d561-4670-86d2-e200118ff00e.png)

As you can see, it's only happening for the PIE chart for some reason, the others are perfectly fine.

![image](https://user-images.githubusercontent.com/10791321/182417604-bc2eb8f5-1a62-4788-932c-5ce7076b5546.png)
Just another screenshot of the relevant html -> this has been replicated in the codepen.

I'm not sure where to go from here to replicate the issue or troubleshoot - any advice? I am on recharts 1.8.1 on my local machine

**Comment by DenysAshikhin** [comment]
Never mind, I apologize for wasting anyone's time - I had a stray bit of CSS being applied the legend itself because of a typo. Once I fixed that it's now working as intended!
