### ISSUE TITLE
Vertical Stacked Bar Charts Not Rendering

### ISSUE THREAD

**Issue by hiltonjp** [recharts/recharts#2927]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://playcode.io/936273/](https://playcode.io/936273/)

### Steps to reproduce
Try flipping the bar chart between horizontal and vertical layouts. I've tried flipping the axes, setting minimum widths, etc, but haven't been able to get it to render on the stacked bar chart.

### What is expected?
I'd expect a reflection of the same chart you'd expect with a horizontal arrangement, just going from top to bottom instead of left to right.

### What is actually happening?
No bars are being rendered at all. The axes are still present.

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 18.0 |
| System | Windows 11 |
| Browser | Chrome 103.0.5060.134 |

**Comment by qls6649** [comment]
you should add type correctly
<YAxis type={"category"} dataKey='name'/>
<XAxis type={"number"} hide />

**Comment by ckifer** [comment]
As stated above this is done via the `type` prop. 

Reproduced and added a toggle between views as an example:

https://codesandbox.io/s/simple-bar-chart-forked-n9tigr?file=/src/App.tsx

Closing this as completed
