### ISSUE TITLE
Could recharts components support customized animation?

### ISSUE THREAD

**Issue by huozhi** [recharts/recharts#293]
For example the component `Line`，there is a `<Animate>` component wrapped it and the animation only works on curve's length changes.

I suggest that we could pass `animationProps` liked names to the `Line` component.

``` js
<Line animationProps={{
     from: { opacity: 0 },
     to: { opacity: 0 },
   }}>
</Line>
```

Just exposed the animation control out, then developers could control the animation easily. Wish you could follow my suggestion. : )

**Comment by xile611** [comment]
@huozhi It's a good idea, we'll try to refactor these components. Meanwhile PR is welcome.

**Comment by huozhi** [comment]
Nice! Repo forked already, I' ll start at once! : )
