### ISSUE TITLE
"className" does not pass through to the underlying SVG elements (bug?)

### ISSUE THREAD

**Issue by dsldsl** [recharts/recharts#2939]
### Discussed in https://github.com/recharts/recharts/discussions/2917

<div type='discussions-op-text'>

<sup>Originally posted by **dsldsl** July 27, 2022</sup>
Hello!  (No responses to my discussion post, so posting here)

I'm looking to use CSS classes instead of fill/stroke properties directly for the coloring of chart elements to help standardize the designs with the rest of my app.

For example, I'd prefer to replace 

`<ReferenceLine y={0} stroke="#F26464" width={2} />` 

with 

`<ReferenceLine y={0} className="stroke-crimson" width={2} />` 

and

`.stroke-crimson{
  stroke: #F26464;
}
`

It seems like this is intended to be supported since the class is passed through from the `<ReferenceLine..>` element down to the underlying SVG code.  The problem I'm seeing is that it doesn't go to the right place.  

My intended recharts code renders down to this:

```html
<g class="recharts-layer recharts-reference-line stroke-crimson">
  <line y="0" class="recharts-reference-line-line" width="2" fill="none" stroke="#ccc" fill-opacity="1" stroke-width="1" x1="50" y1="5" x2="580" y2="5"></line>
</g>
```

Note that the "stroke-crimson" class has been applied to the `<g>` tag and not to the `<line>` element.

Manually changing the code with browser inspect and moving the class down to the `<line>` element produces the desired effect.

```html
<g class="recharts-layer recharts-reference-line">
  <line y="0" class="recharts-reference-line-line stroke-crimson" width="2" fill="none" stroke="#ccc" fill-opacity="1" stroke-width="1" x1="50" y1="5" x2="580" y2="5"></line>
</g>
```

Is this a bug, or is there another way I am supposed to be doing what I want to, or is what I want to do not supported?

I'm using tailwindcss if that somehow matters.

Thanks for any feedback!
</div>

**Comment by dsldsl** [comment]
Hi.  Just wanted to bump this and see if anyone had feedback or suggestions on using my CSS class colors as stroke and fill colors so I dont need to use hexcodes in my charts.  Thank you!

**Comment by ckifer** [comment]
One thing to note @dsldsl is that if you remove the `fill="none" stroke="#ccc" fill-opacity="1" stroke-width="1"`

on the line element that set explicit properties the CSS will take over from the parent `g`

another thing that works is if you specify the element underneath the `g`
```css
.stroke-crimson line { 
   stroke: #F26464;
} 
```

One more thing that works is providing your own svg line via the `shape` prop
```jsx
  <ReferenceLine
        y={4000}
        className="stroke-color"
        shape={<line></line>}
  />
```

I'm not sure what an enhancement to this would look like, does it make sense (and would it more importantly be non-breaking) to add the classes [here](https://github.com/recharts/recharts/blob/master/src/cartesian/ReferenceLine.tsx#L57).

**Comment by ckifer** [comment]
going to close this and track with https://github.com/recharts/recharts/issues/2169
