### ISSUE TITLE
Scatter Plot documentation example graph points to wrong location. Also, it is broken. 

### ISSUE THREAD

**Issue by dwjohnston** [recharts/recharts#2941]
- [X] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://recharts.org/en-US/examples/SimpleScatterChart](https://recharts.org/en-US/examples/SimpleScatterChart)

### Steps to reproduce
Click the 'try the demo in code sandbox link' 

### What is expected?
You will see the example scatter plot in code sandbox.

### What is actually happening?
You see a line graph. 

Also, if you copy paste all the example code, you don't see anything. Changing the response container to 

```
      <ResponsiveContainer width={500} height={500}>

```

solves this. 

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | documentation only |
| System | documentation only |
| Browser | documentation only |

**Comment by alexander-vashchuk** [comment]
Just noticed it as well, I planned to create a GitHub issue
Funny it's not fixed yet

**Comment by ckifer** [comment]
Should be resolved now with the merging of https://github.com/recharts/recharts.org/pull/229, please check if out and let me know if the example/new sandbox is working correctly!

**Comment by alexander-vashchuk** [comment]
It looks like it does point to the right example right now
