### ISSUE TITLE
Page jumps when recharts tries to render tooltip that doesn't fit into view

### ISSUE THREAD

**Issue by liubko** [recharts/recharts#2943]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tooltip-2-1-13-jumping-88q51f?file=/src/App.tsx)

### Steps to reproduce
scroll to the bottom so that the chart is barely visible, then move your mouse to the chart

### What is expected?
I would expect the tooltip to render outside of the view, without page jumping

### What is actually happening?
Once you hover on a chart, recharts tries to render the tooltip and scrolls view to make the tooltip fit into the view

![Untitled](https://user-images.githubusercontent.com/4257937/185380069-0eca235e-0618-4c5d-b1a8-683640e46bdb.gif)

| Environment | Info |
|---|---|
| Recharts | v2.1.13 |
| React | 17.0.1 |
| System | macOS Montrey 12.4 |
| Browser | Chrome Version 104.0.5112.79 (Official Build) (x86_64) |

---

**Comment by ns4style** [comment]
Got a similar issue. Solved by downgrade recharts to 2.1.12

**Comment by liubko** [comment]
Yeah, same here. looks like this issue was introduced in 2.1.13

**Comment by ns4style** [comment]
Wasn't be fixed in 2.1.14

**Comment by ns4style** [comment]
I found a root of this problem. https://github.com/recharts/recharts/commit/fbf387bf538890b5b0d0e5fa60628a8565662810#diff-c3c6e68951cf74127c73a53cfaae21fb64812dbcafbbc54f85b38fd30b85f54bR143

**Comment by ckifer** [comment]
Same as closed issue https://github.com/recharts/recharts/issues/3002

Looks like this is fixed as of 2.1.15 as well as the latest version

PR: #3006 

Closing as resolved
