### ISSUE TITLE
Bar, Line and Area ordering within a ComposedChart

### ISSUE THREAD

**Issue by mehdivk** [recharts/recharts#295]
Hey guys, 
Thanks for the `<Recharts />` module, it's really easy and pleasant to draw charts using Recharts. I'm using `Composed Chart` to render a chart that is consist of an Area and a bar, something like:

``` jsx
<ComposedChart>
    <Bar />
    <Area />
</ComposedChart>
```

Our design guy wants the "Bar" chart to be underneath the "Area" whereas "Recharts" behaviour is reverse, it always put an Area underneath the Bar due to this code in `./src/chart/ComposedChart.js`

``` jsx
<AreaChart {...this.props} graphicalItems={areaItems} isComposed />
<BarChart {...this.props} graphicalItems={barItems} isComposed />
<LineChart {...this.props} graphicalItems={lineItems} isComposed />
```

Is there any option that allows consumer to define ordering ? If not can we have a prop like `chartOrder` with default value of `['Area', 'Bar', 'Line']` that allows consumer to decide about ordering? I'm more than happy to send a PR for it . Keen to hear about alternative solutions for ordering charts

One more time thanks for this awesome library.

**Comment by mehdivk** [comment]
@xile611 thanks for this one

**Comment by rantibi** [comment]
@xile611 can you please explain how it works? I still get mixed order in the default behavior.
![Screen Shot 2020-01-30 at 16 58 17](https://user-images.githubusercontent.com/6207948/73460903-f0527780-4381-11ea-8033-952ab06ae7d1.png)
