### ISSUE TITLE
How to add a custom pentagon SVG for line chart

### ISSUE THREAD

**Issue by Madhurasajjan** [recharts/recharts#2950]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/line-chart-with-customized-label-hs5b7)

### Steps to reproduce
Pentagon svg icon is not rendering in line charts

### What is expected?
we want to render Pentagon SVG icon to be rendered iin line chart

### What is actually happening?
Pentagon svg icon is not rendering and not visible in line charts

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | v2.1.6 |
| System | v2.1.5 |
| Browser | chrome |

---
We want to solve this issue ASAP. Please help us to achieve this.

Thanks in advance

**Comment by ckifer** [comment]
Hi, 

Sorry this wasn't answered quickly. I was able to add a custom Polygon demonstrated in the following CodeSandbox
https://codesandbox.io/s/line-chart-with-customized-label-forked-ib6wig?file=/src/App.tsx

```jsx
      <g>
        <Polygon
          points={[
            { x: 100, y: 150 },
            { x: 350, y: 200 },
            { x: 400, y: 150 },
            { x: 250, y: 50 },
            { x: 100, y: 100 }
          ]}
          stroke="#111"
          fill="none"
        />
      </g>
```
You need to wrap the `Polygon` with `g`

Closing this as answered, please comment back if this isn't satisfactory
