### ISSUE TITLE
Treemap error: "Warning: Received `true` for a non-boolean attribute `z`."

### ISSUE THREAD

**Issue by alextenb** [recharts/recharts#2952]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/simple-treemap-r5o4e)

### Steps to reproduce
Render the Treemap with any data and note the following error logged to the console:

Treemap error: "Warning: Received `true` for a non-boolean attribute `z`."

### What is expected?
No console errors should be generated by the component.

### What is actually happening?
An console error is generated by the component.

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 17.0.1   |
| System | linux ubuntu |
| Browser | firefox |

---
I am seeing the issue when using Recharts version 2.1.13 with React version 17.0.2, but it also happens with the CodeSandbox link provided in the "Examples" section of the docs (Treemap example), which uses Recharts version 2.0.6. This is the repro link which I have provided.

**Comment by Babadzhanov** [comment]
Hi 👋 I'm experience the same issue 👀 however the error disappears if you add "content" property as per this example https://recharts.org/en-US/examples/CustomContentTreemap. Hope this helps 👍

**Comment by alextenb** [comment]
So it does! Thanks for the heads up.

**Comment by ckifer** [comment]
Not sure what exactly this is but looks like the error is here:

https://github.com/recharts/recharts/blob/master/src/chart/Treemap.tsx#L112,L141

**Comment by ckifer** [comment]
Will be fixed by #3228 on next release.`z` attribute is only valid on elements we will never use
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/z

Closing this issue

**Comment by ckifer** [comment]
Should be fixed in 2.4.0
