### ISSUE TITLE
Multiple synchronized charts twitch the page

### ISSUE THREAD

**Issue by Kitketovsky** [recharts/recharts#2959]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/optimistic-tdd-drldhd?file=/src/App.js)

### Steps to reproduce
Hover over any graph, try scrolling the page and move cursor a bit so it doesn't stay in the same position. 

### What is expected?
To be at the same place without page twitching or scrolling up or down.

### What is actually happening?
It scroll down to the end and in case you want to go up, moving your cursor on any hovered graph makes it scroll down to the end again.

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | v18.0.0 |
| System | Windows 11 Home Single Language, v21H2 |
| Browser | Google Chrome, v104.0.5112.102 |

**Comment by stblain** [comment]
Having the same issue.
| Environment | Info |
| --- | --- |
| Recharts | v2.1.14 |
| React | v18.2.0 |
| System | MacOS v12.5.1 |
| Browser | Safari v15.6.1 |

**Comment by digivorefr** [comment]
Having the same issue as well.
| Environment  | Info |
| ------------- | ------------- |
| Recharts  | v2.1.14  |
| React  | v18.2.0  |
| System | Ubuntu 22.04.1 LTS |
| Browser | Brave v1.43.89 |

Also tested in Firefox 104.0.2.

**Comment by Kitketovsky** [comment]
@digivorefr Thank you for mentioning! I checked solutions in your issue and simply **downgrading to 2.1.12 version** of Recharts made it work!

**Comment by ckifer** [comment]
Code sandbox is broken but I think this is same as #2920. This is due to `tabIndex="0"`  in 2.1.13 and `tabIndex="-1"` in 2.1.14+

It "auto focuses" the tooltip taking focus away from anything else and therefore scroll to that element

**Comment by ckifer** [comment]
After testing for this in a codesandbox it looks like this has been resolved for a while - even more so in the latest after merging the last mentioned PR ^. Closing as resolved!
