### ISSUE TITLE
CartesianGrid correct TypeScript ref type

### ISSUE THREAD

**Issue by alexander-vashchuk** [recharts/recharts#2962]
### Steps to reproduce
I have a basic ScatterChart with CartesianGrid

```typescript
<ScatterChart width={400} height={400}>
  <CartesianGrid ref={scatterRef} />
</ScatterChart>
```

I'm using a React reference to connect to the component

```typescript
const scatterRef = useRef<any>(null);
```

To access the following property:
```typescript
scatterRef.current.props.width
```

Well, it does work, except I don't have correct TS types

How to type it correctly instead of passing "any" ?

### What is expected?
I have VSCode intellisense to help me complete code

### What is actually happening?
I don't have intellisense, and don't like the error below 😐
![image](https://user-images.githubusercontent.com/86713661/188864685-d30eae79-f74f-4c65-ad9a-b8803d898746.png)

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 17 |
| System | Windows |
| Browser | Chrome |

**Comment by ckifer** [comment]
Related / duplicates #2709 #2665 

With the way current things are set up the `ref` prop is passed implicitly so the type that comes back could be a lot of things.

Your best bet would be something like this:

```
  const ref = useRef<any>(null);
  const [props, setProps] = useState<CartesianGridProps | null>(null);
  useEffect(() => {
    if (ref.current && "width" in ref.current?.props) { // or use another property to assure the type
      console.log(ref.current?.props);
      setProps(ref.current?.props);
    }
  }, [ref.current]);
```
Still a workaround as you should be able to specify one type in `useRef` and have it work correctly but

**Comment by ckifer** [comment]
Closing in favor of #2665 for the enhancement request
