### ISSUE TITLE
Incorrect type of IconType

### ISSUE THREAD

**Issue by rongsen-intuit** [recharts/recharts#2963]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.typescriptlang.org/play?#code/C4TwDgpgBAMhDmEB2ATAKuaBeAUFKAPlAORgA2AhgJZJk0TF6El1INNHEDOAjgK4UATu3ydhAY2CNRJcVUHiyI5sXGCA9ly7SVKKhQC261Ds5dgQ0yWCD9SeEqvEA7iGWckxhgG4cOUJBQAJLixhiBWFAA8gZUwAA8cIio4RAANCSebMQAfL4A9Pn4UAB6APx AdAhYZgATFCRAKIAHop8KBCJCMjomBnEWQx5OIXF5ThAA](https://www.typescriptlang.org/play?#code/C4TwDgpgBAMhDmEB2ATAKuaBeAUFKAPlAORgA2AhgJZJk0TF6El1INNHEDOAjgK4UATu3ydhAY2CNRJcVUHiyI5sXGCA9ly7SVKKhQC261Ds5dgQ0yWCD9SeEqvEA7iGWckxhgG4cOUJBQAJLixhiBWFAA8gZUwAA8cIio4RAANCSebMQAfL4A9Pn4UAB6APx AdAhYZgATFCRAKIAHop8KBCJCMjomBnEWQx5OIXF5ThAA)

### Steps to reproduce
1. Go to https://www.typescriptlang.org/play?#code/C4TwDgpgBAMhDmEB2ATAKuaBeAUFKAPlAORgA2AhgJZJk0TF6El1INNHEDOAjgK4UATu3ydhAY2CNRJcVUHiyI5sXGCA9ly7SVKKhQC261Ds5dgQ0yWCD9SeEqvEA7iGWckxhgG4cOUJBQAJLixhiBWFAA8gZUwAA8cIio4RAANCSebMQAfL4A9Pn4UAB6APx AdAhYZgATFCRAKIAHop8KBCJCMjomBnEWQx5OIXF5ThAA
1. You should see that IconType is using the wrong utility type to exclude 'none' from LegendType and the end result is not what we expect.

### What is expected?
1. IconType should list all other values except 'none'
2. Use Exclude instead of Omit in union types

### What is actually happening?
1. IconType does not list all possible values excluding 'none'
2. Wrong use of Omit in a union type

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 16.9.0 |
| System | macOS 12.5.1 |
| Browser | Chrome 105 |

---
This is the permalink for the incorrect typing: https://github.com/recharts/recharts/blob/fbb6d6cbd8cfbbc322b4201489bdcf6d2052ef28/src/component/DefaultLegendContent.tsx#L19

**Comment by ckifer** [comment]
@rongsen-intuit 

Thanks! Agreed this should use `Exclude` rather than `Omit`

**Comment by ckifer** [comment]
merged in https://github.com/recharts/recharts/pull/3122

closing - we should see this in the next release
