### ISSUE TITLE
PolarRadiusAxis props type definitions don't allow 'reversed' even though it works

### ISSUE THREAD

**Issue by karlkovaciny** [recharts/recharts#2966]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/simple-radar-chart-forked-j7tlzo?file=/src/App.tsx)

### Steps to reproduce
Add or remove the prop "reversed" from the PolarRadiusAxis on line 62 of App.tsx. This was forked from the demo SimpleRadarChart with this one change.

### What is expected?
I expected `reversed` to work because it works in my existing JavaScript. But TypeScript expects it not to work: it says "No overload matches this call" since there is no "reversed" prop defined in https://github.com/recharts/recharts/blob/master/src/polar/PolarRadiusAxis.tsx

### What is actually happening?
The axis is reversed (easy to see visually) because https://github.com/recharts/recharts/blob/6c692d3919b75c348b9d4a034aca011fb40f0202/src/util/PolarUtils.ts still handles that prop.

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 17.0.1, 18.2.0 |
| System | MacOS (Monterey) |
| Browser | Chrome 105 |

---
The interface should be updated to include the `reversed` prop and it should be added to the API at https://recharts.org/en-US/api/PolarRadiusAxis.

**Comment by ckifer** [comment]
This should be able to be closed on the next release, thanks!

**Comment by ckifer** [comment]
Released initially in 2.3.0-alpha releases. 

Closing this but it will be in the 2.3.0 regular release.
