### ISSUE TITLE
RadarChart for type="number" data rendering wrongly

### ISSUE THREAD

**Issue by vileanco** [recharts/recharts#2969]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hardcore-danny-odzium)

### Steps to reproduce
See CodeSandbox.

```
import {
  PolarAngleAxis,
  PolarGrid,
  PolarRadiusAxis,
  Radar,
  RadarChart
} from "recharts";

const data = [
  { angle: 0, r: 1 },
  { angle: 90, r: 2 },
  { angle: 180, r: 3 },
  { angle: 270, r: 4 }
];

export default function App() {
  return (
    <RadarChart data={data} width={360} height={360}>
      <PolarGrid gridType="circle" />

      <PolarRadiusAxis type="number" dataKey="r" />

      <PolarAngleAxis
        dataKey="angle"
        axisLineType="circle"
        type="number"
        domain={[0, 360]}
      />

      <Radar
        type="number"
        name="r"
        dataKey="r"
        fillOpacity={0}
        stroke={"#000"}
      />
    </RadarChart>
  );
}
```

### What is expected?
The drawn graph should match the data.

### What is actually happening?
The angle degrees do not match the graph. Eg. angle 90 is drawn with radius 3 even though it should be drawn with radius 2.

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 18.2.0 |
| System | macOS Monterey 12.3.1 |
| Browser | 105.0.5195.102 |

---
Trying to use RadarChart for non-categorical data for polar coordinate graphs.

**Comment by tran-simon** [comment]
I have the same issue https://github.com/recharts/recharts/issues/3937

It seems like the whole graph is rotated counter clockwise

**Comment by akamfoad** [comment]
Hi @vileanco @tran-simon 

Looks like removing `type="number"` on `PolarAngleAxis` fixes the issue, here I forked and applied this change, the Chart looks correct now, let us know if this fixes your issue

https://codesandbox.io/s/solitary-wave-3jqdwv?file=/src/App.js:401-482

**Comment by ckifer** [comment]
+1 - no need to specify number type on these charts. Ideally you wouldn't be able to, but until then you can just remove it

**Comment by tran-simon** [comment]
> Looks like removing `type="number"` on `PolarAngleAxis` fixes the issue

Then the chart is of type category, and the ticks might not be at the right angles!

it only works if all the points are at the same angle distance from eachother

**Comment by ckifer** [comment]
@tran-simon 
Okay so what you want is to set the domain on the axis instead of on the chart
https://codesandbox.io/s/long-sunset-x5pkgf?file=/src/App.js

![image](https://github.com/recharts/recharts/assets/25180830/e5c7e502-5137-4157-90de-6d56d3a7001a)

**Comment by akamfoad** [comment]
Agreed @ckifer , I explored the code a lot couldn't find the path that leads to this behavior, I'll pick it up again if no one submitted a fix.

**Comment by ckifer** [comment]
Unfortunately it's probably in the generate function

**Comment by ckifer** [comment]
Should be fixed in next minor

**Comment by nikolasrieble** [comment]
Released with https://github.com/recharts/recharts/releases/tag/v2.10
