### ISSUE TITLE
Recharts does not render in jest tests 

### ISSUE THREAD

**Issue by peter-coastpay-com** [recharts/recharts#2971]
Issue:

Recharts does not render in jest tests 

expected results:

It should render in jest tests.

**Comment by ckifer** [comment]
Hi @peter-coastpay-com 

Recharts does render in jest tests. If you are referring to the ESM issue in 2.1.13/14 please update to the latest recharts version.

Please check this issue for some examples of testing with jest
https://github.com/recharts/recharts/issues/2982
