### ISSUE TITLE
Transform svg to base64 for reuse purposes on report

### ISSUE THREAD

**Issue by BentiPab** [recharts/recharts#2975]
How can I convert SVG to base64? The issue I am facing is that when I transform the SVG to base64 some data is lost. 

Examples: 
original chart before base64
![image](https://user-images.githubusercontent.com/69325366/191093145-26f9dfa4-13d2-444a-bce0-3b53f0947bfc.png)
chart parsed to base64
![image](https://user-images.githubusercontent.com/69325366/191093254-e2be9c04-ebc0-47b6-ae6d-b373dcb03ea6.png)

Code: 
`<ComposedChart
				data={graphData}
				margin={margin || { top: 15, right: 30, left: 20, bottom: 15 }}
				width={100}
				ref={ref => convertChart(ref)}
			>...`
`const convertChart = (ref: any) => { 
			if (ref && ref.container) {
				const svg = ref.container.firstChild as Node
				const xml = new XMLSerializer().serializeToString(svg)
				const base64 = btoa(xml)	
				handleGraphToReport(base64)
			}
}
	)`

I see that only 1 layer of the chart is being passed to base64, is there a way to target the whole svg?

I also see that all "path" elements are being lost in the serializer step

Thanks!

**Comment by ckifer** [comment]
Exporting via base64 isn't something that is necessarily supported by Recharts. I'm not entirely sure, but you might be able to set a ref for each child and get the individual parts. This could be a feature request to support export to image formats and base64.

There are a few examples out there on SoF that export to png, etc. Might be worth seeing if [this](https://stackoverflow.com/a/65691876) answer works or taking a look at the implementation of [recharts-to-png](https://github.com/brammitch/recharts-to-png/blob/main/lib/src/index.tsx).

**Comment by ckifer** [comment]
Going to close this as stale, feel free to comment back to continue discussion
