### ISSUE TITLE
ResponsiveContainer still not working with React 18

### ISSUE THREAD

**Issue by didje251** [recharts/recharts#2977]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![CodeSandbox Link](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/recharts-issue-template-forked-i08bvu?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1. Install React 18
2. Install Recharts
3. Create a simple React project in your favourite IDE (for example VSCode)
4. Copy the code from https://recharts.org/en-US/examples/SimpleAreaChart to create an example Simple Area Chart
5. NPM start

### What is expected?
Expected to see a beautiful simple area chart.

### What is actually happening?
Nothing happend on screen - it is blank. Console error in browser refer to an error the following error

Uncaught TypeError: Cannot read properties of null (reading 'useState')
    at useState (react.development.js:1622:1)

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | React 18 |
| System | Mac OS Monterey 12.2.1 |
| Browser | Brave Version 1.41.100 |

---
This error seems to have been documented before.

**Comment by ckifer** [comment]
Hi, it looks like your project doesn't have an index file which means that nothing within React will get rendered (including the chart). I modified your sandbox to add the index file which renders the chart with React 18.

https://codesandbox.io/s/responsivecontainerissue-forked-sk1gm4?file=/src/App.tsx
