### ISSUE TITLE
Error bars overflow chart area

### ISSUE THREAD

**Issue by starcin** [recharts/recharts#2978]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-g5tb46?file=/src/index.js)

### Steps to reproduce
Create a bar chart with defined YAxis domain and set the YAxis allowDataOverflow to true.
Add Bar and ErrorBar components.
Set the error value so that it exceeds the minimum YAxis domain limit.

### What is expected?
ErrorBar shouldn't be rendered outside of the chart area.

### What is actually happening?
ErrorBar is overflowing.

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | v17.0.2 |
| System | Windows 10 |
| Browser | Chrome 105.0.5195.102 |

---
If you ask why I set Y axis domain smaller than my error bar, the answer is I've implemented zoom and changing the domain causes this.

**Comment by starcin** [comment]
I am actually using version 2.1.9 but the form didn't let me to choose it.

**Comment by ckifer** [comment]
Is there a reason you need `allowDataOverflow` to be true? If I remove that it looks okay (not great but okay). What do you expect it to look like?

**Comment by starcin** [comment]
@ckifer If I don't set `allowDataOverflow`, the domain of Y axis is overwritten by the actual data. The whole idea is being able to zoom in to a specific part of a data, in other words being able to define axis domains without the graphics being overflowed.

**Comment by ckifer** [comment]
Makes sense - I wish I could help, but without the maintainers its tough to get changes through on the repo. Labeled this for a future look.

**Comment by pdavid31** [comment]
I am encountering the same problem using a line chart. I just modified the [ErrorBar](https://recharts.org/en-US/api/ErrorBar) example from the documentation to see if it also appears there, but this does not seem to be an issue for the ScatterChart.

https://codesandbox.io/s/recharts-issue-template-forked-v2bwqf?file=/src/index.js

**Comment by ckifer** [comment]
Fixed in #﻿﻿3300 - will be released with next minor version

**Comment by ckifer** [comment]
Should be fixed in 2.4.0
