### ISSUE TITLE
How to test if BarChart renders with Jest?

### ISSUE THREAD

**Issue by urstrangersarah** [recharts/recharts#2982]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-kzikoz?file=/src/chart.test.tsx)

### Steps to reproduce
Run test suite to see output from test

### What is expected?
The testId on BarChart is found by the test after rendering the chart 

### What is actually happening?
BarChart doesn't appear in the rendered output of the test and it's unable to find the testId. 

| Environment | Info |
|---|---|
| Recharts | v2.1.4 |
| React | 18.2.0 |
| System | macOS Monterey |
| Browser | Chrome 105.0.5195.125 |

---
I'm trying to test that BarChart appears on the page with a simple test case. When I look at the rendered output from the failed test, I don't see the BarChart. Is there a way to test if BarChart or other Recharts components render correctly on a page?

**Comment by ckifer** [comment]
Hi, it looks like the BarChart is being rendered in the test output but `data-testid` isn't being passed down to the parent container. [Looking at the code](https://github.com/recharts/recharts/blob/0417cb84096f1f2eccaee1a1cde060f5cef0076a/src/chart/generateCategoricalChart.tsx#L715-L751) recharts doesn't spread props down to the the parent of the Bar or any other chart.
You could wrap the chart in a div
```jsx
<div data-testid="bargraph">
    <BarChart width={730} height={250} data={data} id="bargraph">
     ....
</div>
```
or you could use the `id` instead of `data-testid` and something like
```ts
const result = render(<Bar id="bargraph" />);
const someElement = result.container.querySelector("#bargraph");
```

Hope that helps!

**Comment by nikolasrieble** [comment]
You might find useful examples here. https://github.com/dillonreedy/recharts-jest

**Comment by ckifer** [comment]
Closing this as answered. Please comment back if more info is needed!

**Comment by shuwei1122** [comment]
@urstrangersarah 

you just need to add this to the top of the test file, it has to be top of the test file, not the test block.
Reference: https://jskim1991.medium.com/react-writing-tests-with-graphs-9b7f2c9eeefc

```
jest.mock('recharts', () => {
    const OriginalModule = jest.requireActual('recharts')
    return {
        ...OriginalModule,
        ResponsiveContainer: ({ children }) => (
            <OriginalModule.ResponsiveContainer width={800} height={800}>
                {children}
            </OriginalModule.ResponsiveContainer>
        ),
    }
})

```

**Comment by charlieforward9** [comment]
Strange how the component shows up properly in my vitest browser tests but still when I enact a click event on the bar chart I get an empty event...

```
  const onChartChange = (e: CategoricalChartState) => {
      console.log(e) //prints {}
    };
  
  ...
  
 <BarChart
      aria-label="bar-chart"
      height={300}
      width={300}
      onClick={onChartChange}
      ...
    >
```
