### ISSUE TITLE
Jest Testing SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by mitrotasios** [recharts/recharts#2987]
Jest is throwing the following error when testing if the Charts are rendering, resulting that the test are failing:
```
/<path>/node_modules/d3-shape/src/index.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export {default as arc} from "./arc.js";
                                                                                ^^^^^^

SyntaxError: Unexpected token 'export'

at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
at Object.<anonymous> (node_modules/recharts/lib/shape/Symbols.js:14:16)
```

**Comment by bjmendezsena** [comment]
It seems that the version of emc is older than the version you are using and it gives an error when doing the export.
In my case I was using the following library components:

`import {
  PieChart,
  Pie,
  Legend,
  Tooltip,
  ResponsiveContainer,
  Label,
} from "recharts";`


In the setupTests file I added the following:

`jest.mock("recharts", () => ({
  ResponsiveContainer: jest.fn().mockImplementation(({ children }) => children),
  PieChart: jest.fn().mockImplementation(({ children }) => children),
  Pie: jest.fn().mockImplementation(({ children }) => children),
}));
`

I understand that if you are using other components you should mock your components just like I did.

I hope that helps you.

**Comment by DrewLandgraveCbsi** [comment]
This worked for me. Thanks!

**Comment by nandeshwarshubh** [comment]
> 

I am getting when I add the mocks -

Error: Uncaught [Error: mockConstructor(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.]

**Comment by ckifer** [comment]
This is due to ESM only in d3 v3+. Track the upgrade in #3012 - we'll use `victory-vendor` to do it in a non-breaking fashion. For now, upgrading to the latest fixes these issues.

Closing as completed.
