### ISSUE TITLE
Line chart show all data in xaxis

### ISSUE THREAD

**Issue by MohammedJaffar** [recharts/recharts#299]
Hi,
How to show all the page in x Axis like, from Page A to Page m. 
because they grouped the pages like below
Output:
![captusre](https://cloud.githubusercontent.com/assets/8073735/19419163/4056440a-93ef-11e6-983d-9b4662361cff.JPG)
My data code : 
const data = [
      {name: 'Page A', uv: 4000, pv: 2400, amt: 2400},
      {name: 'Page B', uv: 3000, pv: 1398, amt: 2210},
      {name: 'Page C', uv: 2000, pv: 9800, amt: 2290},
      {name: 'Page D', uv: 2780, pv: 3908, amt: 2000},
      {name: 'Page E', uv: 1890, pv: 4800, amt: 2181},
      {name: 'Page F', uv: 2390, pv: 3800, amt: 2500},
      {name: 'Page G', uv: 3490, pv: 4300, amt: 2100},
      {name: 'Page h', uv: 4000, pv: 2400, amt: 2400},
      {name: 'Page i', uv: 3000, pv: 1398, amt: 2210},
      {name: 'Page j', uv: 2000, pv: 9800, amt: 2290},
      {name: 'Page k', uv: 2780, pv: 3908, amt: 2000},
      {name: 'Page l', uv: 1890, pv: 4800, amt: 2181},
      {name: 'Page m', uv: 2390, pv: 3800, amt: 2500},
   
Please help me and Thanks in advance.

**Comment by xile611** [comment]
@MohammedJaffar You can set 
```
<XAxis interval={0} />
```

to show all the ticks.

**Comment by MohammedJaffar** [comment]
Thanks you @xile611 .
