### ISSUE TITLE
Changing order of elements inside AreaCharts

### ISSUE THREAD

**Issue by Yoshihide-Nishimoto** [recharts/recharts#2990]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Our app have a AreaChart with multiple Area.In default, the element oder inside svg is like this

```
<g class="recharts-layer recharts-area">...</g>
<path stroke="#ccc" pointer-events="none" width="576" height="260" points="[object Object],[object Object]" class="recharts-curve recharts-tooltip-cursor" type="linear" d="M159.73913043478262,10L159.73913043478262,270"></path>
<g class="recharts-layer recharts-area">...</g>
<g class="recharts-layer recharts-active-dot">...</g>
<g class="recharts-layer recharts-area">...</g>
<g class="recharts-layer recharts-active-dot">...</g>
```

What's the problem is that a part of first dot disappeared from view behind the second recharts-area and the tooltip cursor as well.

So I'd like to re-order the elements like this.
```
<g class="recharts-layer recharts-area">...</g>
<g class="recharts-layer recharts-area">...</g>
<g class="recharts-layer recharts-area">...</g>
<g class="recharts-layer recharts-active-dot">...</g>
<g class="recharts-layer recharts-active-dot">...</g>
<path stroke="#ccc" pointer-events="none" width="576" height="260" points="[object Object],[object Object]" class="recharts-curve recharts-tooltip-cursor" type="linear" d="M159.73913043478262,10L159.73913043478262,270"></path>
```

I know making patch like this works fine, but I don't like to use patch.

```
const _children = [...children]
        _children.sort((a,b) => {
          if(a.type.displayName === "Tooltip") return 1
          return -1
        })
```

### What does the proposed API look like?
add ordering properties to AreaChart like this.

```
<AreaChart
                data={data}
                height={300}
                margin={{ top: 10, right: 10, left: -40, bottom: 0 }}
                tooltipXXX={true}
                dotsXXX={true}
              >
```

Or tell me other work arounds.

**Comment by ckifer** [comment]
Hi @Yoshihide-Nishimoto 

Do you mind creating a reproduction of the original issue or pasting a screenshot so we can see the disappearing elements?

Thanks!

**Comment by ckifer** [comment]
Going to close this as stale until more details are added
