### ISSUE TITLE
React Testing Library doesn't work  when using Recharts 

### ISSUE THREAD

**Issue by RajB07** [recharts/recharts#2991]
### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-k2xqp)

### Steps to reproduce
-

### What is expected?
Bug to be fixed soon 

### What is actually happening?
***/**/node_modules/d3-shape/src/index.js:1

({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export {default as arc} from "./arc.js";
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1796:14)
      at Object.<anonymous> (node_modules/recharts/lib/shape/Symbols.js:14:16) 

| Environment | Info |
|---|---|
| Recharts | v2.1.1 |
| React | 17 |
| System | - |
| Browser | - |

---
Jest version - 28.1.2
react testing lib version - 12.1.4

**Comment by DrewLandgraveCbsi** [comment]
Happening for me too

**Comment by alanjonesa4** [comment]
Downgrading recharts to 2.1.12 fixed this for me. There was a related issue that I can't find anymore (may have been on the jest repo), but it seems this was introduced in 2.1.13

**Comment by ckifer** [comment]
If this is on Recharts don't expect a fix anytime soon as the maintainers are not around. I would fix if I could but only have permissions to issues. Duplicate of #2987

**Comment by dsldsl** [comment]
@arcthur can you pls open project permissions to some new contributors?

**Comment by ckifer** [comment]
@arcthur @xile611 +1000000 - please, we have people desperate to help

**Comment by ax0n-pr1me** [comment]
Also breaks NextJS app, downgrading to anything less than 2.1.14 appears to introduce vulnerabilities... pointing towards d3.js however.

https://github.com/advisories/GHSA-36jr-mh4h-2g58


```
# npm audit report

d3-color  <3.1.0
Severity: high
d3-color vulnerable to ReDoS - https://github.com/advisories/GHSA-36jr-mh4h-2g58
fix available via `npm audit fix --force`
Will install recharts@2.1.14, which is outside the stated dependency range
node_modules/d3-color
  d3-interpolate  0.1.3 - 2.0.1
  Depends on vulnerable versions of d3-color
  node_modules/d3-interpolate
    d3-scale  0.1.5 - 3.3.0
    Depends on vulnerable versions of d3-interpolate
    node_modules/d3-scale
      recharts  0.2.0 - 2.1.6 || 2.1.8 - 2.1.12
      Depends on vulnerable versions of d3-interpolate
      Depends on vulnerable versions of d3-scale
      node_modules/recharts
```

**Comment by ryanolson-aumni** [comment]
Broke our tests too.

**Comment by ryanolson-aumni** [comment]
Documented but do you realize you've broken TypeScript types AND tests in simply 2 patch releases. **"patch releases"**

**Comment by jmfrancois** [comment]
Me ? there is a review process, usage and tests. I have tested all my changes in the repository env and in my cie repository. Please do not blame me to push for upgrades, answers to people issues with them in this repository and over the owner who has review them.
Contribute to it and stop blame this is a bad behavior. Are you not able to achieve fixes on your side ?

**Comment by ryanolson-aumni** [comment]
I think it's a reasonable response to call people out when they do these sort of things.

**Comment by jmfrancois** [comment]
it seems latest release is back on d3 6. So just update it will fix your issue @RajB07. It was due to how d3 7.x release as esm.
nextjs, jest and other tools which do not support lib published as esm but only cjs is the issue behind it.
Let see if someone is pushing for a major release of recharts with d3 7

**Comment by ckifer** [comment]
Closing this as completed as jest should work with all versions besides 2.1.13 and 2.1.14

Track the above issue (#3012) for a non-breaking fix to the security vulnerability
