### ISSUE TITLE
Type error in recharts source

### ISSUE THREAD

**Issue by bdwain** [recharts/recharts#2997]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/bdwain/recharts-type-issue](https://github.com/bdwain/recharts-type-issue)

### Steps to reproduce
run "npm install && npm test"

### What is expected?
no type errors

### What is actually happening?
a type error 

```
node_modules/recharts/types/component/LabelList.d.ts:21:70 - error TS2344: Type 'T' does not satisfy the constraint 'Data'.

21 export declare type Props<T> = SVGProps<SVGElement> & LabelListProps<T>;
                                                                        ~

  node_modules/recharts/types/component/LabelList.d.ts:21:27
    21 export declare type Props<T> = SVGProps<SVGElement> & LabelListProps<T>;
                                 ~
    This type parameter might need an `extends Data` constraint.

Found 1 error in node_modules/recharts/types/component/LabelList.d.ts:21
```

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | any |
| System | any |
| Browser | any |

---
This is also true on the latest version of recharts.

This is not causing issues when building recharts itself because its own tsconfig does not set strict to true, but a strict project should be able to use recharts without setting skipLibCheck to true, which skips checks for ALL libraries.

There is an open PR to fix this already, but it has not gotten any attention. https://github.com/recharts/recharts/pull/2954

**Comment by builat** [comment]
Temp solution could be using of [patch-package](https://github.com/ds300/patch-package).
At least works for me.
