### ISSUE TITLE
Require() of ES Module /lib/shape/Symbols.js not supported.

### ISSUE THREAD

**Issue by simPod** [recharts/recharts#2998]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
I've got these imports

```
import { Area, AreaChart, ResponsiveContainer, Tooltip, TooltipProps } from 'recharts';
import { NameType, ValueType } from 'recharts/types/component/DefaultTooltipContent';
```

### What is expected?
v2.1.12 was ok, 2.1.13 got broke

### What is actually happening?
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /builds/projects/app/249311/node_modules/recharts/node_modules/d3-shape/src/index.js from /builds/projects/app/249311/node_modules/recharts/lib/shape/Symbols.js not supported.
Instead change the require of index.js in /builds/projects/app/249311/node_modules/recharts/lib/shape/Symbols.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/builds/projects/app/249311/node_modules/recharts/lib/shape/Symbols.js:14:16)
    at Object.<anonymous> (/builds/projects/app/249311/node_modules/recharts/lib/component/DefaultLegendContent.js:16:16)
    at Object.<anonymous> (/builds/projects/app/249311/node_modules/recharts/lib/component/Legend.js:16:29)
    at Object.<anonymous> (/builds/projects/app/249311/node_modules/recharts/lib/index.js:317:15)
```

| Environment | Info |
|---|---|
| Recharts | v2.1.13, v2.1.14 |
| React | v18 |
| System | debian bullseye |
| Browser | n/a |

**Comment by letops** [comment]
This does not happen with version 2.1.10 (I am too lazy to search the latest version that works correctly). I just downgraded the library to that version and everything works perfectly.

**Comment by unnimona** [comment]
same error 
any fix?

**Comment by j0hannr** [comment]
Here as well, running on Nextjs `12.1.0`.

**Comment by jmfrancois** [comment]
solved here: https://github.com/recharts/recharts/issues/2918#issuecomment-1263033336

**Comment by simPod** [comment]
Yes I do.

Can you explain why it must be fixed on the client side and not lib side?

**Comment by jmfrancois** [comment]
it seems latest release is back on d3 6. So just update it.

**Comment by ckifer** [comment]
Updating to the latest should fix everyone here for now

Tracking the vulnerability in #3012 

Closing this as completed, continue to track progress for non-breaking upgrade to latest d3 in the issue above
