### ISSUE TITLE
Reduce size - don't depend on complete lodash lib

### ISSUE THREAD

**Issue by bkniffler** [recharts/recharts#30]
Recharts is currently the biggest library in my project. Its size could possibly be reduced by explicitly importing only those functions of lodash that are used.

See here: https://github.com/lodash/lodash/tree/npm
```jsx
// Load a single method for smaller builds with browserify/rollup/webpack.
var chunk = require('lodash/chunk');
var extend = require('lodash/fp/extend');
```
Here is the stats for recharts (in my case)
```
recharts: 790.74 KB (24.7%)
  d3-scale: 126.08 KB (15.9%)
    d3-time-format: 27.13 KB (21.5%)
      <self>: 27.13 KB (100%)
    d3-array: 16.59 KB (13.2%)
      <self>: 16.59 KB (100%)
    d3-format: 14.26 KB (11.3%)
      <self>: 14.26 KB (100%)
    d3-color: 13.5 KB (10.7%)
      <self>: 13.5 KB (100%)
    d3-interpolate: 12.13 KB (9.62%)
      <self>: 12.13 KB (100%)
    d3-time: 10.38 KB (8.23%)
      <self>: 10.38 KB (100%)
    <self>: 32.1 KB (25.5%)
  lodash: 112.91 KB (14.3%)
    <self>: 112.91 KB (100%)
  d3-shape: 53.82 KB (6.81%)
    d3-path: 4.57 KB (8.50%)
      <self>: 4.57 KB (100%)
    <self>: 49.24 KB (91.5%)
  react-smooth: 42.3 KB (5.35%)
    raf: 2.61 KB (6.17%)
      performance-now: 886 B (33.1%)
        <self>: 886 B (100%)
      <self>: 1.75 KB (66.9%)
    pure-render-decorator: 722 B (1.67%)
      react-addons-shallow-compare: 53 B (7.34%)
        <self>: 53 B (100%)
      <self>: 669 B (92.7%)
    <self>: 38.98 KB (92.2%)
  recharts-scale: 16.34 KB (2.07%)
    <self>: 16.34 KB (100%)
  oui-dom-utils: 13.85 KB (1.75%)
    <self>: 13.85 KB (100%)
  core-js: 10.95 KB (1.38%)
    <self>: 10.95 KB (100%)
  invariant: 1.48 KB (0.187%)
    <self>: 1.48 KB (100%)
  classnames: 1.08 KB (0.136%)
    <self>: 1.08 KB (100%)
  ima.js-babel6-polyfill: 301 B (0.0372%)
    <self>: 301 B (100%)
  <self>: 411.65 KB (52.1%)
```

**Comment by arcthur** [comment]
Actually, recharts didn't depend on whole lodash. The build config include [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash). That could be transformed the lodash import. The whole lodash file size is 400k+.

But the file size of recharts is really the problem. We will check the built file, and check d3-scale and lodash import. I planed create babel plugin like babel-plugin-babel to reduce the size. It will do after 1.0 release.

**Comment by bkniffler** [comment]
Ah, cool, didn't know of https://github.com/lodash/babel-plugin-lodash
You want to rename this issue or open a new one for your plans?

**Comment by arcthur** [comment]
The recharts ver 0.7.0 has reduced the lodash filesize, but the whole library size is bigger ;-) 
Now the webpack don't support ES2015 modules. Otherwise, we will reduce the smaller size.
I will take that to 1.0 release plan for new issue.

**Comment by SaphuA** [comment]
@arcthur will this ever be reconsidered? I think the libraries size is still pretty large.
