### ISSUE TITLE
Chart keeps redrawing

### ISSUE THREAD

**Issue by truenorthcreative** [recharts/recharts#300]
Not sure if this is a bug or perhaps something in my code, but I I'm using the ResponsiveContainer and AreaChart and if I update the state of the parent component or even click on a menu above the chart, it redraws the chart.  The data is static, so it's not changing anything.  Any thoughts?

**Comment by hi-bazinga** [comment]
The same problem when using BarChart, but the PieChart works well.

**Comment by Jareechang** [comment]
@truenorthcreative, isn't React.js supposed to re-render when you update state on components ? 
it would be nice if you could post some code or jsfiddle to demonstrate

**Comment by truenorthcreative** [comment]
@jareechang yes, of course. But the re-render will only affect the changed element, etc. my point is the state changing for *anything* in the parent will re-render, as will clicking sibling components (even if you want to remove the state argument)

**Comment by xile611** [comment]
@truenorthcreative  Can you give an online example ?

**Comment by konstantin24121** [comment]
@xile611 in site examples. When we resize render-area (right bottom), сhart is not repainted upon resize only when new data is provided. @truenorthcreative  meant that Pie chart repaining when we resize block and using ResponsiveContainer, but all the other charts don't behave in such away.
http://jsfiddle.net/znqLLdev/1/?utm_source=website&utm_medium=embed&utm_campaign=znqLLdev

**Comment by konstantin24121** [comment]
@xile611 if you want i can add width and height into componentWillReceiveProps and make PR, but i don't know how it feature will affect performance

**Comment by Jareechang** [comment]
@xile611, I was playing around with demo (Adding ResponsiveContainer to charts) and after investigation on the `react-container-dimensions` library, it seems that the library sets a new state **on resize** which is why it redraws (or re-render the child elements). 

**src/component/ResponsiveContainer.js, line 83-85**

```javascript 
<ContainerDimension>
  ...
</ContainerDimension>
```
Function called on **resize** and **componentDidMount** in `<ContainerDimension>` component [(library reference)](https://github.com/okonet/react-container-dimensions/blob/master/src/index.js):

```javascript
onResize() {
   const clientRect = ContainerDimensions.getDomNodeDimensions(this.parentNode)
   this.setState({
       initiated: true,
       ...clientRect
   })
}
```
We might have to fork the lib to make changes or investigate alternatives such as [digidem/react-dimensions](https://github.com/digidem/react-dimensions) which looks quite promising. However, that might require significant change to source code. Let me know what you think.

**Comment by konstantin24121** [comment]
@Jareechang charts are rerender. But they not recalculate points for charts

**Comment by truenorthcreative** [comment]
Why did this close?

**Comment by xile611** [comment]
@truenorthcreative Can you support online demo? Your problem can't be reproduced.

**Comment by noahnu** [comment]
@truenorthcreative Are you generating the data from a function like so: http://jsfiddle.net/h449h9oe/ ?

**Comment by Sunil6591** [comment]
What is the fix for this?

**Comment by truenorthcreative** [comment]
I found a component that was forcing the parent to re-render the page. Hope this helps.

**Comment by mimiron8080** [comment]
@Sunil6591 Just see @noahnu 's posted code

**Comment by tiaaaa123** [comment]
I'm using a `PieChart` in a `ResponsiveContainer` and each time it set the state of the container, the pie is rerender. Anyone found a solution?

Example
https://gyazo.com/4d402ff81dd628a37b740da40e0903bd

**Comment by truenorthcreative** [comment]
@tiaaaa123 it looks like the data is changing, so what do you want the experience to be?

**Comment by tiaaaa123** [comment]
Nvm. Found the issue!

**Comment by NathanCH** [comment]
This is definitely an issue. If your component rerenders (say because of a Redux state change), ReCharts redraws the chart even when the props supplied to the chart (the data) has not changed. All the animations retrigger unessecarily. 

Best hack I've come up with is to disable animations. Definitely takes away from the UX though.

**Comment by jzillmann** [comment]
Facing the same issue...

If i copy and paste the LegendEffectOpacity example (http://jsfiddle.net/z9orjuww/?utm_source=website&utm_medium=embed&utm_campaign=z9orjuww) into my project (exporting SimpleLineChart and use it in another component), then on hovering the legend, the chart is re-drawn (animations kick in again).

**Comment by nicokiva** [comment]
Is someone planning to fix it? It's annoying...

**Comment by raph90** [comment]
Having the same issue...

**Comment by linweigao** [comment]
Any update? Facing the same issue in the FunnelChart.

**Comment by mahmoudafer** [comment]
Why is this closed with no solution? Still facing it

**Comment by franciscofabian** [comment]
This also happens to me, but only when I have a `<Tooltip/>` component on the chart and only since v2.0.0-beta.8

**Comment by DylDevs** [comment]
> Best hack I've come up with is to disable animations. Definitely takes away from the UX though.

Yep, this is the only thing that fixes it for me as well even though the data does not change. For anyone wondering how to do that, you can set the prop isAnimationActive of [Area](http://recharts.org/api#Area), [Bar](http://recharts.org/api#Bar), [Line](http://recharts.org/api#Line), [Scatter](http://recharts.org/api#Scatter), [Pie](http://recharts.org/api#Pie), [Radar](http://recharts.org/api#Radar), [RadialBar](http://recharts.org/api#RadialBar) to be false

**Comment by ckifer** [comment]
This should only happen if something changes that should cause a re-animation which isn't much. 

If you have an updated codesandbox reproduction that would be helpful

**Comment by ckifer** [comment]
Can you make a reproduction?

**Comment by DylDevs** [comment]
Yeah, I'll have it in a couple minutes

**Comment by amanda-yosh** [comment]
For me, it worked when I removed the ResponsiveContainer and added isAnimationActive false after rendering the first time with a module scoped flag that survives component unmount/remount.
