### ISSUE TITLE
write down the data within <linechart> instead data={data}

### ISSUE THREAD

**Issue by hesnoh** [recharts/recharts#3000]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I don't know if you can do it, but I have complex code where I have to put the data within <linechart>, can you do it?

### What does the proposed API look like?
data={
[
{
name: 1,
x: 3,
y: 8
},
{
name: 2,
x: 5,
y: 3,
},
.
.
.
}

**Comment by ckifer** [comment]
Hi @hesnoh,

Its unclear from this issue what your request is. Do you mind rephrasing and reformatting to be a bit more clear? 

Thanks!

**Comment by hesnoh** [comment]
so instead it read data={data}
can I write the data down for example:
             <LineChart
                          width={500}
                          height={300}
                          data={[                                                       //example instead of data={data}
                                                {x=1, y=2},                                 
                                                {x=3, y=7},
                                                {x=4, y=3}
                                     ]}
                          margin={{
                            top: 5,
                            right: 30,
                            left: 20,
                            bottom: 5
                          }}
                        >
                          <CartesianGrid strokeDasharray="3 3" />
                          <XAxis dataKey="x"/>
                          <YAxis />
                          <Tooltip />
                          <Legend />
                          <Line
                            type="monotone"
                            `dataKey="y"`
                            stroke="#8884d8"
                            activeDot={{ r: 8 }}
                          />
                        </LineChart>
<img width="809" alt="Screen Shot 2022-10-07 at 3 40 17 PM" src="https://user-images.githubusercontent.com/77089461/194640926-87146a24-a17b-4534-95eb-38ce1614f9db.png">

**Comment by ckifer** [comment]
That should work just fine, but I would question that over storing your data in a variable, storing it in state, and/or getting it from an API. An example of providing data inline can be found here

[![Edit recharts-issue-template (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-kebziu?fontsize=14&hidenavigation=1&theme=dark)

**Comment by hesnoh** [comment]
it worked beautifully, thank you
