### ISSUE TITLE
Page gets auto scroll when hover on chart (bottom)

### ISSUE THREAD

**Issue by bhushan-msys** [recharts/recharts#3002]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/flamboyant-poincare-u0kn47?file=/src/App.js)

### Steps to reproduce
Scroll the page till position where only XAxis will show now try to hover on it, Page will scroll to top 

### What is expected?
On hover chart must not auto scroll

### What is actually happening?
Page is auto scrolling, When you scroll the page till position where only XAxis will show now try to hover on it, it will scroll to top 

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 18 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by bhushan-msys** [comment]
Check the video for better understanding [Recording_1665384116234 (1).webm](https://user-images.githubusercontent.com/113992376/194813949-860c4487-56da-4c3f-812a-fd9400dfb499.webm)

**Comment by dreamboyx1** [comment]
PR #3006 seems to have fixed it for me. Looks like that is in 2.1.15 now. Thanks to all involved.

**Comment by paul-dao-FHR** [comment]
That fixed what I was encountering as well

**Comment by ckifer** [comment]
Closing this as completed!
