### ISSUE TITLE
when i click on graph dots i want one text filed to be appear where i can write some thing which will be displayed only graph

### ISSUE THREAD

**Issue by virajvaghasia** [recharts/recharts#3003]
---

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

**Comment by ckifer** [comment]
@virajvaghasia This issue doesn't make any sense - if you can comment more details I'd be happy to label this a feature request, but from what I can tell this isn't something that internal recharts should concern itself with
