### ISSUE TITLE
Highest Line Point rendered outside the chart

### ISSUE THREAD

**Issue by ariona** [recharts/recharts#3007]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

<img width="431" alt="Screen Shot 2022-10-11 at 1 19 49 PM" src="https://user-images.githubusercontent.com/752483/195014592-29064f79-b669-44e7-a666-6638173fffd5.png">

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dawn-tree-scs3qg?file=/src/App.js)

### Steps to reproduce
Create line chart with data with high gap for each poin

### What is expected?
- The chart line point all rendered inside the chart,
- YAxis includes all min and max value available

### What is actually happening?
- The highest value is rendered ouside the chart
- YAxis does no include highest/max value

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 17.0.2 |
| System | macOS Monterey |
| Browser | Google Chrome 106.0.5249.103 (Official Build) (x86_64) |

**Comment by ckifer** [comment]
Hi @ariona 

It looks like the `raihan` key in your data is a string. If you change those values to numbers before passing the data to recharts your chart will render correctly.
![image](https://user-images.githubusercontent.com/25180830/209914779-31ea58ab-193d-4a5c-881b-32ecb3a32eb5.png)

Closing this as completed unless it is re-opened/commented on
