### ISSUE TITLE
Is the library still maintained

### ISSUE THREAD

**Issue by ortonomy** [recharts/recharts#3015]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Looking for a d3-based alternative to Chart.js and I've experimented with Recharts and seems to really fit the bill, but 400 open issues and no release since last year has me worried...

### What does the proposed API look like?
N/A

**Comment by zavan** [comment]
There have been several releases this year (last one was yesterday), they just stopped using GitHub releases. Check the [changelog](https://github.com/recharts/recharts/blob/master/CHANGELOG.md) instead.

A lot (not all of course) of the issues are people seeking help, not real bug reports. That always happens with this kind of library.

**Comment by ortonomy** [comment]
Thanks for the help answering this @zavan - it was a little confusing.

**Comment by ortonomy** [comment]
Thanks for the help answering this @zavan - it was a little confusing.
