### ISSUE TITLE
How to make an areachart line that repeats data line but a little lower than origin data line

### ISSUE THREAD

**Issue by Metallistener** [recharts/recharts#3031]
Hello! Did someone make an areachart like on screenshots? I have areachart data line, but also I would like to repeat this line with opacity a little lower than the origin data line. Is there any solution to do it?
<img width="815" alt="Снимок экрана 2022-10-22 в 13 53 42" src="https://user-images.githubusercontent.com/33493261/197330543-a4576518-937e-4f5c-8897-bd2f03368bda.png">

<img width="597" alt="Снимок экрана 2022-10-22 в 13 54 41" src="https://user-images.githubusercontent.com/33493261/197330582-2d26e199-7233-4144-b46c-2bf456a99d66.png">

**Comment by ckifer** [comment]
Hi @Metallistener 

You would have to decrease your second areas Y value. This doesn't seem like a standard chart library feature for any other support other than duplicating an area that has a different opacity and an offset in the data.

**Comment by ckifer** [comment]
Going to close this as stale until some more detail can be added
