### ISSUE TITLE
 lines and hover dots doesnt sync with bars

### ISSUE THREAD

**Issue by rebequi** [recharts/recharts#3032]
hey guys i was wondering if there's a way that lines can match the bars, in this example looks like they are pointing between them. but i want them to be exactly in the top-centered of each bar, it seems that some of the lines and bars doesnt touch, like there is a gap
 im attaching a screen recording to show how it looks
 
https://user-images.githubusercontent.com/68568910/197421089-e0d2b3b5-b3f9-4d18-b1e9-fcb42aedc54d.mov

code looks something like this 
```
const LinearBarChart = ({
  data,
  width,
  height,
  linesProps,
  barsProps,
  strokeDashArray
}: ILinearBarChart) => {
  const formattedData = format(data);
  return (
    <ResponsiveContainer width="100%" height="80%">
      <ComposedChart width={width} height={height} data={formattedData} >
        <CartesianGrid strokeDasharray={strokeDashArray} />
        <XAxis
          fontFamily={'Lato, sans-serif'}
          color={colors.$grayChart}
          dataKey="name"
          scale="band"
          stroke={colors.$grayChart}
        />
        <YAxis fontFamily={'Lato, sans-serif'} color={colors.$grayChart} stroke={colors.$grayChart} />
        <Tooltip
          contentStyle={{
            fontSize: '0.625rem',
            fontFamily: 'Lato, sans-serif',
          }}
        />
        {barsProps.map((bar: Props, index: number) => (
          <Bar
            key={`bar-${index}`}
            dataKey={bar.dataKey}
            barSize={10}
            fill={bar.stroke}
          />
        ))}

        <Legend
          formatter={(value) => (
            <span style={{ fontFamily: 'Lato, sans-serif' }}>{value}</span>
          )}
        />
        {linesProps.map((line: Props, index: number) => (
          <Line
            key={`line-${index}`}
            type="monotone"
            dataKey={line.dataKey}
            stroke={line.stroke}
            dot={false}
            strokeWidth={3}
            legendType="rect"
          />
        ))}
      </ComposedChart>
    </ResponsiveContainer>
  );
};


```

**Comment by leadq** [comment]
Similar question from me,

When mouse hovering on the chart, active dots rendered while mouse not exactly hovering the "dot". I want "activeDots" should be rendered while mouse hovers over the "dot", not the entire column of data.  You can see the behaviour from @rebequi 's video. Is there any easy solution for it ?

**Comment by ckifer** [comment]
@rebequi - The lines are rendered at the directly above the X-Axis category (March for example). Your eye can go from the tick directly up to the line and the dot.

If we look at the functionality while the charts are separate a line chart will show the tooltip and points directly above the tick, a barchart will show the tooltip while hovering within the cursor for that bar/bars. It makes sense why they behave this way when put together.

In order for this to work how you would like we would need a reference for the position of the bar, we'd also need to know which bars/lines are connected.

If I were to look at any other charting library they behave the same way
(chart.js)
![image](https://user-images.githubusercontent.com/25180830/209750248-3b0d05f8-05c7-47d5-85c9-e33f8b4f73fe.png)

(highcharts)
![image](https://user-images.githubusercontent.com/25180830/209750626-9d436e4b-f6f3-4459-bc34-e3ab77641920.png)

I will go with the rest of the charting libraries here and say that the current behavior is how things should behave.

@leadq your question is confusing and multi-part, do you mind making a new issue? It seems it is separate from this one

**Comment by ismail0946** [comment]
<CartesianGrid strokeDasharray="2 2" horizontal={false} opacity={0.4}/>
<Tooltip cursor={{ strokeDasharray: 2, opacity: 1 }} />

**Comment by ckifer** [comment]
Going to close this as stale until some more detail can be added/questions answered

There are other issues addressing the 2nd question asked here around single point interactions
