### ISSUE TITLE
Reference line with ifOverflow="visible" is not visible

### ISSUE THREAD

**Issue by devnguy** [recharts/recharts#3038]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-f2n72f?file=/src/index.js)

### Steps to reproduce
Notice the ReferenceLine is not visible, even though it is given the `ifOverflow="visible"` prop

### What is expected?
Reference line is visible at the max y value without extending the domain

### What is actually happening?
Reference line is not visible

| Environment | Info |
|---|---|
| Recharts | v2.1.1 |
| React | 16.12.0 |
| System | mac 11.6.8 |
| Browser | Chrome Version 106.0.5249.119 |

**Comment by ckifer** [comment]
Hi @devnguy 

I think what you're looking for is `ifOverflow="extendDomain"` here. This prop needs documented as `alwaysShow` is deprecated. 

Code reference - https://github.com/recharts/recharts/blob/master/src/cartesian/ReferenceLine.tsx#L121

Will leave this open as an issue to update docs

**Comment by lukask-proxora** [comment]
While writing the docs and playing around with the reference objects I found a bug and opened an issue: https://github.com/recharts/recharts/issues/3379

**Comment by hongsoohyuk** [comment]
any updates for this issue??

**Comment by ckifer** [comment]
@hongsoohyuk this issue is closed. Do you mean the linked issue that's still open?

**Comment by hongsoohyuk** [comment]
ah it was closed, i didn't see that.
yeah i have the same issue just as @devnguy described.

Or, is there any way that I can render ReferenceLine with the greater value(y-axis) than the graph data's value(y-axis) without extending the domain?

**Comment by ckifer** [comment]
@hongsoohyuk  not sure what you mean? Why would you render a line that you can't see? You have to extend the domain to see it

**Comment by hongsoohyuk** [comment]
![Screenshot 2024-05-23 at 3 26 44 PM](https://github.com/recharts/recharts/assets/130728103/13e59e23-1391-45eb-88bb-ebefedf54362)
this graph shows the cumulative traffic data, and its cumulative value is about 130GB.

and i want to draw a line for the threshold values that can be set by the users.
![Screenshot 2024-05-23 at 3 26 54 PM](https://github.com/recharts/recharts/assets/130728103/dd8e3a02-8a7a-4352-a6e0-6ff2b2300101)
for example, i set the threshold line at 10.00TB, which is far greater than 130GB.

and this is where i have the problem of using 'extendDomain' prop.
as the chart is extended to 10TB, it gets so hard for the user to notice the change of the data at the graph.

i want to draw 10TB ReferenceLine at the top of the chart without "extending domain".
i think this was the point of this issue.

**Comment by ckifer** [comment]
Oh, I must've missed that in the original description. But you can't just "not extend the domain" you still have to extend the domain in order to show the line. 

What the ask is is for something like a chart break? Where you go from 150 GB to where your line is at 10 GB (+ or - a few so you can see it)

Like this (except a ref line ofc)

![image](https://github.com/recharts/recharts/assets/25180830/acbb9698-96cb-4168-98ae-4281ffe5334b)

Am I understanding correctly?

**Comment by hongsoohyuk** [comment]
sorry for taking so long.
chart break would be another good option, but what i was expecting is drawing reference line at the very top of the chart.
so the user would be able to see the graph and the threshold value clearly at the same time.

this is the figma design for the feature.
<img width="1096" alt="Screenshot 2024-05-27 at 1 58 33 PM" src="https://github.com/recharts/recharts/assets/130728103/f102c9f9-077b-46a3-a82f-c5800eb601c1">
