### ISSUE TITLE
gaps with area and positive-negative values

### ISSUE THREAD

**Issue by cralfaro** [recharts/recharts#3040]
The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.

---

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

Great plugin btw, but i am facing one issue not sure how can i solve.

I am trying to render an AreaChart with multiple areas with the same stackId, then i am using stackOffset=sign, because i want the negative values down of Y-axis. The problem is when some area is mixing negative and positive values, then start appearing some white gaps and not sure why or how can get ride of them...

Example:

https://codesandbox.io/s/rechart-area-chart-forked-6xktp0?file=/index.js:276-1889

**Comment by ckifer** [comment]
Hi @cralfaro - Looks like this codesandbox is using a really old version of recharts and it doesn't seem to reflect the issue you are describing.

Do you mind recreating the codesandbox to match the issue described with the latest version of recharts?

**Comment by ckifer** [comment]
Going to close this as stale until some more detail can be added
