### ISSUE TITLE
Highlight and Zoom with React Hooks

### ISSUE THREAD

**Issue by nwoodr94** [recharts/recharts#3042]
The ReCharts `Highlight and Zoom` feature is both 1) kind of low quality, and 2) doesn't utilize React Hooks.

https://recharts.org/en-US/examples/HighlightAndZoomLineChart

I've spent about an hour refactoring, but it doesn't seem to work as expected.

It should look something like this:

```
let [zoom, setZoom] = useState({
   left: "dataMin",
   right: "dataMax"
});

<LineChart 
   data={acceleration}
   onMouseDown={(e) => setZoom({ ...zoom, left: e.activeLabel })}
   onMouseUp={(e) => setZoom({ ...zoom, right: e.activeLabel })}
>
   <Line dataKey={"measurement"} />
   <XAxis dataKey={"timestamp"} domain=[left, right]/>
   <YAxis dataKey={"measurement"}/>
</LineChart>
```

**Expected Results**: The chart zooms in to the selected domain.
**Actual Results**: Nothing

The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.

---

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

**Comment by ckifer** [comment]
Hi @nwoodr94,

It looks like you need to call `setZoom` with the old state value provided from the callback of `useState` rather than the `zoom` value from you `let`. 

For example:
```ts
let [zoom, setZoom] = useState({
   left: "dataMin",
   right: "dataMax"
});

<LineChart 
   data={acceleration}
   onMouseDown={(e) => setZoom((oldZoom) => ({ ...oldZoom, left: e.activeLabel }))}
   onMouseUp={(e) => setZoom((oldZoom) => ({ ...zoom, right: e.activeLabel }))}
>
   <Line dataKey={"measurement"} />
   <XAxis dataKey={"timestamp"} domain=[left, right]/>
   <YAxis dataKey={"measurement"}/>
</LineChart>
```

Please see the React docs for why this is: https://beta.reactjs.org/reference/react/useState#updating-state-based-on-the-previous-state

We are working on improving the website docs slowly but surely. One of our goals for 3.0 is to revamp things with function components and hooks. Closing this for now but feel free to comment back with questions.

**Comment by danthzz** [comment]
### Hi, i´m problaby having the same problem.
I've refatoring from hook component but dont work how it should 

`    const initialData = [accelerationRmsGraph, speedRmsGraph];

    const getAxisYDomain = (from, to, ref, offset) => {
        const refData = initialData?.slice(from - 1, to);
        let [bottom, top] = [refData[0][ref], refData[0][ref]];
        refData.forEach((d) => {
            if (d[ref] > top) top = d[ref];
            if (d[ref] < bottom) bottom = d[ref];
        });

        return [(bottom | 0) - offset, (top | 0) + offset];
    };

    const initialState = {
        data: initialData,
        left: 'dataMin',
        right: 'dataMax',
        refAreaLeft: '',
        refAreaRight: '',
        top: 'dataMax+1',
        bottom: 'dataMin-1',
        top2: 'dataMax+20',
        bottom2: 'dataMin-20',
        animation: true,
    };

    const [zoomGraphs, setZoomGraphs] = useState(initialState,{
        left: "dataMin",
        right: "dataMax"
    });

    const zoom = () => {
        let { refAreaLeft, refAreaRight } = zoomGraphs;
        const { data } = zoomGraphs;

        if (refAreaLeft === refAreaRight || refAreaRight === '') {
            setZoomGraphs({
                refAreaLeft: '',
                refAreaRight: '',
            });
            return;
        };

        // xAxis domain
        if (refAreaLeft > refAreaRight) [refAreaLeft, refAreaRight] = [refAreaRight, refAreaLeft];

        // yAxis domain
        const [bottom, top] = getAxisYDomain(refAreaLeft, refAreaRight, 'cost', 1);
        const [bottom2, top2] = getAxisYDomain(refAreaLeft, refAreaRight, 'impression', 50);

        setZoomGraphs({
            refAreaLeft: '',
            refAreaRight: '',
            data: data?.slice(),
            left: refAreaLeft,
            right: refAreaRight,
            bottom,
            top,
            bottom2,
            top2,
        });
    };

    const zoomOut = () => {
        const { data } = zoomGraphs;
        setZoomGraphs({
            data: data?.slice(),
            refAreaLeft: '',
            refAreaRight: '',
            left: 'dataMin',
            right: 'dataMax',
            top: 'dataMax+1',
            bottom: 'dataMin',
            top2: 'dataMax+50',
            bottom2: 'dataMin+50',
        });
    };


    const { left, right, refAreaLeft, refAreaRight, top, bottom, top2, bottom2 } = zoomGraphs;
                    {accelerationRmsGraph && speedRmsGraph
                        ? (
                            <div style={{ width: '100%', flex: '1 1 auto' }}>
                                <ResponsiveContainer mt="2">
                                    <LineChart
                                        data={rmsSelector === "acceleration" ? accelerationRmsGraph : speedRmsGraph}
                                        onMouseDown={(e) => setZoomGraphs((zoomGraphs) => ({ ...zoomGraphs, left: e.activeLabel }))}
                                        onMouseMove={(e) => setZoomGraphs((zoomGraphs) => ({ ...zoomGraphs, right: e.activeLabel }))}
                                        // eslint-disable-next-line react/jsx-no-bind
                                        onMouseUp={zoom.bind()}

                                    >
                                        <CartesianGrid strokeDasharray="3 3" />

                                        <XAxis allowDataOverflow scale="time" domain={[left, right]} type="number" dataKey="name" angle="0" tickFormatter={(tick) => format(tick, 'dd/MM HH:mm')} />

                                        <YAxis allowDataOverflow domain={[bottom, top]} type="number" yAxisId="1" />

                                        <YAxis orientation="right" allowDataOverflow domain={[bottom2, top2]} type="number" yAxisId="2" />

                                        <Tooltip labelFormatter={(label) => format(label, "dd/MM/yy HH:mm:ss")} formatter={(value) => value.toFixed(4)} />
`

stay somenthing like that
