### ISSUE TITLE
Chart margins on left/right with axis type number

### ISSUE THREAD

**Issue by AAZANOVICH** [recharts/recharts#3045]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/simple-composed-chart-forked-qkq1n9?file=/src/App.tsx)

### Source file in case you can't access link above
https://gist.github.com/AAZANOVICH/d13d0da1e2a0698a03ecde915c036609

### Steps to reproduce
I'm trying to create distance/elevation chart for track. When type="number" is used, chart will have left and right margins.
See the link https://codesandbox.io/s/simple-composed-chart-forked-qkq1n9?file=/src/App.tsx

### What is expected?
No margins should appear.  

### What is actually happening?
Margins on the left and right

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 17 |
| System | MacOS |
| Browser | Chrome latest |

**Comment by AAZANOVICH** [comment]
Setting scale={'linear'} on XAxis will "fix" right part but, not left. Also, lets say distance unit is 1 km, how to set ticks with interval 1 km ?

**Comment by AAZANOVICH** [comment]
Just in case you can't access the link
import "./styles.css";
import React from "react";
import {
  ComposedChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer
} from "recharts";

const data = [
  {
    dist: 0.8,
    alt: 70.1
  },
  {
    dist: 0.3,
    alt: 75.1
  },
  {
    dist: 1.3,
    alt: 80.5
  },
  {
    dist: 4.3,
    alt: 85.5
  },
  {
    dist: 5.3,
    alt: 91.5
  },
  {
    dist: 10.3,
    alt: 102.5
  },
  {
    dist: 18.3,
    alt: 112.123
  },
  {
    dist: 25.3,
    alt: 127.2
  }
];

const divStyle = {
  height: "200px",
  width: "600px"
};

export default function App() {
  return (
    <div style={divStyle}>
      <ResponsiveContainer>
        <ComposedChart
          data={data}
          margin={{
            top: 20,
            right: 20,
            bottom: 20,
            left: 20
          }}
        >
          <CartesianGrid stroke="#f5f5f5" />
          <XAxis dataKey="dist" type="number" />
          <YAxis dataKey="alt" type="number" />
          <Tooltip />
          <Legend />
          <Area type="monotone" dataKey="alt" fill="#8884d8" stroke="#8884d8" />
        </ComposedChart>
      </ResponsiveContainer>
    </div>
  );
}

**Comment by ckifer** [comment]
You can get rid of the margin by using `domain={['dataMin', 'dataMax']}` on both the X and Y axis. This won't however address your second question of setting an interval of 1km. If you use `allowDecimals={false}` you will get whole numbers, but only if the domain is `domain={['auto', 'dataMax']}` which will bring back the margin you don't want.

You can use the `ticks` prop and create the ticks yourself from your max datapoint.
```
let ticks: number[] = [];
for (let i = 1; i <= 25; i++) {
  ticks.push(i);
}
```
`ticks={ticks}`

Should result in a chart like
<img width="619" alt="image" src="https://user-images.githubusercontent.com/25180830/209624694-9e7bc494-c7ca-4866-b731-b8023f83b9fa.png">


Closing this as completed for now, feel free to comment back if this didn't solve your issue
