### ISSUE TITLE
Recharts how to convert Y axis to int and ignore 0 and float value

### ISSUE THREAD

**Issue by NavroO** [recharts/recharts#3046]
Hi Tries to generate a position chart using rechart.

![image](https://user-images.githubusercontent.com/42099711/200178083-8eaae077-892e-4445-8f5d-0629eeb9e2d9.png)

I would like the chart not to show a float value of 1.5 etc and that the line has the right padding relative to the top.

As for the padding itself, I noticed that it is enough to get rid of domain={['auto', 'auto']} then the graph is in the middle. But it appears 0 over 1

Position 1 is the highest point on my chart. I would like the Y-axis not to show a floating point value and 0 and at the same time for the greyhound to have a slight padding at the top

Example data array

`{
    date: "2022-11-09T23:00:00.000Z"
    position: 1
},
{
    date: "2022-12-09T23:00:00.000Z"
    position: 2
}`

Custom function

`const parseValue = (dataArray: any) => {
        const positions = dataArray.map((item: any) => item.position);
        const filteredPositions = positions.filter((item: any) => item !== 0 && item % 1 === 0);
        const stringPositions = filteredPositions.map((item: any) => item.toString());
        return stringPositions;
    };`

Y axis

`<YAxis
                            allowDataOverflow
                            type='number'
                            dataKey={parseValue(dataArray)}
                            domain={['auto', 'auto']}
                            yAxisId='1'
                            label={showLabel ? { value: 'Position', angle: -90, position: 'insideLeft' } : ''}
                            reversed={reversed || false}
                        />`

Full code

`
<ResponsiveContainer
                    width='100%'
                    height={385}
                    className='mt-5'
                >
                    <LineChart
                        width={500}
                        height={300}
                        data={dataArray}
                        margin={{
                            top: 5,
                            right: 30,
                            left: 20,
                            bottom: 5,
                        }}
                    >
                        <CartesianGrid
                            strokeDasharray='3 3'
                            opacity={0.4}
                        />
                        <XAxis
                            allowDataOverflow
                            dataKey='date'
                            interval={calculateInterval(dataArray)}
                            tickFormatter={(unixTime) => moment(unixTime).format('DD MMM')}
                            display={displayXAxis ? 'block' : 'none'}
                            label={showLabel ? { value: 'Date', position: 'insideBottomRight', offset: 0 } : ''}
                        />
                        <Tooltip
                            content={
                                <CustomTooltip
                                    active={true}
                                    customText={dataKey}
                                />
                            }
                        />
                        <YAxis
                            allowDataOverflow
                            type='number'
                            domain={['auto', 'auto']}
                            yAxisId='1'
                            label={showLabel ? { value: 'Position', angle: -90, position: 'insideLeft' } : ''}
                            reversed={reversed || false}
                        />
                        <Line
                            type='monotone'
                            dataKey={dataKey || 'subscriptions'}
                            stroke='#0023FF'
                            strokeWidth={4}
                            yAxisId='1'
                            animationDuration={300}
                            activeDot={{ r: 8 }}
                        />
                    </LineChart>
                </ResponsiveContainer>
`

![image](https://user-images.githubusercontent.com/42099711/200178184-2aafae5f-198c-4dde-b271-4cb0c9da35ae.png)

**Comment by ckifer** [comment]
Hi @NavroO,

Its tough to tell what you are asking for without a working example. Can you please move this code into a working codesandbox to reproduce the issue so we can help triage?
