### ISSUE TITLE
Feature: logarithmic (or pluggable) scale for YAxis and XAxis

### ISSUE THREAD

**Issue by mike-marcacci** [recharts/recharts#305]
There are obviously many applications where a logarithmic is preferable to a linear scale. It would be really cool to be able to pass a `scale` function to the `YAxis` and `XAxis` components, which could optionally accept a number to use as a "base" in a logarithmic function (defaulting to a base of 1 for linear):

``` jsx
// linear
<YAxis {...props} />

// base10
<YAxis scale={10} {...props} />

// natural log
<YAxis scale={Math.E} {...props} />

// snap to increments of 5
<YAxis scale={(y) => Math.round(y % 5) * 5} {...props} />
```

**Comment by Eric24** [comment]
+1

**Comment by xile611** [comment]
Done in version 0.18.0.

<img width="761" alt="wangwang20161118150525" src="https://cloud.githubusercontent.com/assets/6111424/20421688/8890a056-ada0-11e6-9c7f-af04697caad7.png">

**Comment by JarLowrey** [comment]
Is it possible to keep linear scaling but utilize [scale-breaks](https://ux.stackexchange.com/questions/36408/how-to-visualize-data-with-extreme-value-differences)?

**Comment by pablocarreraest** [comment]
is posible add a example?

**Comment by kraussian** [comment]
> Done in version 0.18.0.
> 
> <img alt="wangwang20161118150525" width="761" src="https://cloud.githubusercontent.com/assets/6111424/20421688/8890a056-ada0-11e6-9c7f-af04697caad7.png">

Is there some documentation on how the "function" option works? I want to use a "pseudo-log" function based on this method: https://win-vector.com/2012/03/01/modeling-trick-the-signed-pseudo-logarithm

This is what I tried, but it doesn't work:
```javascript
function pseudoLog(x) {
    return asinh(x/2) / log(10);
}
...
    <YAxis type='number' dataKey='value' scale={pseudoLog} />
...
```

**Comment by jackson-sandland** [comment]
How do you incorporate min and max for linear?
