### ISSUE TITLE
X axis with constant values

### ISSUE THREAD

**Issue by LouisMuriuki** [recharts/recharts#3052]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
when i want to plot events happening over time i.e. from start of day to end of day(12am-11:59pm) and i receive the time stamp from my data i.e 6.30am,8:00am,12:00am... and their corresponding values. such that the time stamp i receive should align accordingly on the values on the axis (12am-11:59pm) ...therefore showing a clean plot of the events based on the timestamp over a period time

### What does the proposed API look like?
i believe the recharts should have inbuilt props for basic stuff like time of day,days of month,month in a year that can be passed in either axis as most people use this to plot the graphs..

**Comment by ckifer** [comment]
Hi @LouisMuriuki,

You can create a time series following the recommendations in this issue - https://github.com/recharts/recharts/issues/956#issuecomment-339279600. Is there any issues with doing something like that? Recharts shouldn't necessarily be responsible for being able to parse time strings. Unix timestamps as a number type with a tickFormatter should work fine to solve this problem.

**Comment by nikolasrieble** [comment]
Please checkout my PR and the example I provided. Does that solve your use case?
