### ISSUE TITLE
Line doesn't render for same data if we use gradient

### ISSUE THREAD

**Issue by IchabodCrow** [recharts/recharts#3055]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tiny-line-chart-forked-4183yd?file=/src/App.tsx)

### Steps to reproduce
Get same data,  use stroke={`url(#my_id)`} 

### What is expected?
Render one color line

### What is actually happening?
LIne dont render

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 18.2.0 |
| System | Ubuntu |
| Browser | Chrome, Mozila, Safary |

**Comment by milorue** [comment]
We are having this same issue on some charts I did find a workaround which is less than ideal where we checked our chart data and if it would produce a straight line just conditionally changed the line color to a solid color between our gradient. Its a dirty hack  but works since no change is a very rare edge case for us.

**Comment by ckifer** [comment]
What version of recharts did this work on?

**Comment by ckifer** [comment]
Hi @IchabodCrow @milorue 

This works as expected. If change your example to use `amt` the line will render with the correct color.

Please read this stackoverflow post about why horizontal or vertical lines don't render when using `linearGradient`
https://stackoverflow.com/a/73043947/8050147

This isn't a limitation of recharts but rather a limitation of `linearGradient`. The adding a small decimal to any of your `pv` datapoints causes the line to render.

**Comment by IchabodCrow** [comment]
HI @ckifer!

Thx for your answer. It is fix my problem. But i am really sad that it is not solution just hack.

**Comment by ckifer** [comment]
Hi @milorue 

Me too!

Unfortunately this is a browser limitation though - for some reason browsers can't render flat SVGs.

**Comment by nikolasrieble** [comment]
@ckifer Is this something that we should extend the documentation on?

**Comment by ckifer** [comment]
Totally, we can call it out in docs somewhere.

**Comment by BenjaBobs** [comment]
Sorry for the necro-post, but I recently ran into this issue, and manually inserting the work-around posted [here](https://stackoverflow.com/a/19709615) (prepending a move `M-10,-10`  in the path without actually drawing anything), directly from the DOM-inspector seems to work.
Maybe this is something that could happen internally?

**Comment by ckifer** [comment]
Hm maybe. I can probably give it a shot at some point. I don't want to add something that might break in the future and this is doesn't seem to be the most stable of things in the world

**Comment by BenjaBobs** [comment]
In the mean time, my current work-around is a mutation observer that manually patches the `d` attributes:
```typescript
const pathPatchingObserver = new MutationObserver(mutationsList => {
  mutationsList.forEach(mutation => {
    patchPath(mutation.target);

    mutation.addedNodes.forEach(node => {
      patchPath(node);
    });
  });
});

function patchPath(node: Node) {
  if (node.nodeType !== Node.ELEMENT_NODE || node.nodeName !== 'path') return;
  const path = node as SVGPathElement;

  const d = path.getAttribute('d');

  if (d && !d.startsWith('M-10,-10')) {
    path.setAttribute('d', `M-10,-10 ${d}`);
  }
}
```

It works somewhat decently.
