### ISSUE TITLE
How to group several ReferenceLine into <g></g>?

### ISSUE THREAD

**Issue by morozovkirill** [recharts/recharts#3060]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I use several horizontal and vertical ReferenceLine and want to group them. But if add <g></g> outside them, they don't render. I have this error:
ReferenceLine.js:138 Uncaught TypeError: Cannot read properties of undefined (reading 'scale')

code for example:

```
<ScatterChart>
<XAxis />
<YAxis />
<ZAxis />
          <g id="Grid">
            {grid.gridVert && ticks.x
              ? ticks.x.map((elem, i) => (
                  <ReferenceLine
                    key={"gridXRefLine"   i}
                    x={elem}
                    stroke={grid.gridColor}
                  />
                ))
              : null}
            {grid.gridHoriz && ticks.y
              ? ticks.y.map((elem, i) => (
                  <ReferenceLine
                    key={"gridYRefLine"   i}
                    y={elem}
                    stroke={grid.gridColor}
                  />
                ))
              : null}
          </g>
<Scatter />
</ScatterChart>
```

I tried to make component through <Customized />, and get the same result.

```
<Customized
            component={(d) => (
              <CustomizedGrid {...d} ticks={ticks} grid={grid} />
            )}
/>
```

...

```
export const CustomizedGrid = (props) => {
  const { ticks, grid } = props;

  return (
    <g id="Grid">
      {ticks.x
        ? ticks.x.map((elem, i) => (
            <ReferenceLine
              key={"gridXRefLine"   i}
              x={elem}
              stroke={grid.gridColor}
              {...props}
            />
          ))
        : null}
      {ticks.y
        ? ticks.y.map((elem, i) => (
            <ReferenceLine
              key={"gridYRefLine"   i}
              y={elem}
              stroke={grid.gridColor}
              {...props}
            />
          ))
        : null}
    </g>
  );
};
```

### What does the proposed API look like?
Any ideas, how to solve it?

**Comment by ckifer** [comment]
@morozovkirill can you provide a reproduction in CodeSandbox? This is most likely due to recharts expecting a certain parent component.

Can you not just use `CartesianGrid` as your grid here?

**Comment by morozovkirill** [comment]
Yep. The start issue was with CartesianGrid component. It renders additional lines besides ticks. Maximum and Minimum values (check getCoordinatesOfGrid function in ChartUtils.ts). So, chart has has border with them, even if you don't want it. I tried to hide it with css, it works, but a bit tricky. So, then I tried to replace CartesianGrid with my own grid using ReferenceLine component. This issue is about this attempt.

Now I found a better solution. CartesianGrid can receive horizontalCoordinatesGenerator and verticalCoordinatesGenerator props as arrays with ticks coordinates. And in this case getCoordinatesOfGrid is not executed. Unfortunately these props are not documented, so I spend a lot of time. And, of course, you need to calculate ticks coordinates yourself. I copied and now use getTicksOfAxis ChartUtils.ts for that.

Hope, it'll help somebody.

**Comment by ckifer** [comment]
Interesting, thanks for the detailed explanation @morozovkirill 

I will change this to a documentation issue for those props when I look at it tomorrow. Glad you found a solution using CartesianGrid. The reference line approach seems pretty hacky.

**Comment by ckifer** [comment]
Docs merged and deployed :)
