### ISSUE TITLE
Hovering to show a tooltip blurs other fields

### ISSUE THREAD

**Issue by roelvdwater** [recharts/recharts#3063]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tooltip-with-customized-content-forked-8v9bmi?file=/src/App.tsx)

### Steps to reproduce
1. Focus the input textfield
2. Hover over the chart

### What is expected?
The input textfield remains focused.

### What is actually happening?
The focus of the input textfield is lost.

| Environment | Info |
|---|---|
| Recharts | >=v2.1.13 |
| React | 18.2.0 |
| System | Any OS |
| Browser | Any browser |

---
I've been playing around with the version numbers and noticed that it broke starting from version 2.1.13 because of the change in [this PR](https://github.com/recharts/recharts/pull/2914).

**Comment by henrywoody** [comment]
Same issue here. Autofocusing the tooltip feels like it harms accessibility, which is in direct contrast to the goal of making the tooltips dismissible.

Seems like [colinmorelli's suggestion](https://github.com/recharts/recharts/pull/2914#issuecomment-1284703302) would work:

> I think we can still keep the same accessibility behavior here by just binding an event listener to document.body when the tooltip is opened, and not capturing focus in the tooltip element itself.

**Comment by ckifer** [comment]
Make sense, if someone (or @colinmorelli) wants to make a PR I think this is reasonable

**Comment by JoeVanGundy** [comment]
This fix would be super appreciated :)

**Comment by ckifer** [comment]
Personally don't have time to take this, though we were planning on releasing a new minor version tomorrow morning. 

I hear everyone in the n issues that have been created against this one and I'll definitely try to think up a solution if no one else does in the next bit.

**Comment by ArkaFred** [comment]
I opened this [PR](https://github.com/recharts/recharts/pull/3515). If you have sometime to look at it it would be great :) Hope I'm respecting the guidelines!

**Comment by ckifer** [comment]
Fixed in 2.6!
