### ISSUE TITLE
The second to last tick is not shown

### ISSUE THREAD

**Issue by PointSingularity** [recharts/recharts#3064]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-3l5ff0?file=/src/index.js)

### Steps to reproduce
Just load the reproduction link.

### What is expected?
180 tick to be shown on the Y axis.
![image](https://user-images.githubusercontent.com/56246797/202722624-f55a5225-ee05-412d-acfa-c423cbe8e7e7.png)

### What is actually happening?
Y ticks are in increments of 20, but the penultimate tick is skipped.

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 18.2.0 |
| System | Windows 11 Pro 22H2 |
| Browser | Chrome 107.0.5304.107 |

---
I've seen similar issues. Many people are suggesting using "interval={0}", but as you can see it doesn't work (neither does "preserveStartEnd").

**Comment by MadThad762** [comment]
I am having this problem too. I want to display three ticks but the middle one is missing.

**Comment by ckifer** [comment]
@PointSingularity remove the `domain` on your YAxis and then the issue goes away. If you set your domain to a value divisible by 20 it also works `domain={[0, 200]}`. The issue is that `dataMax` here is 190 meaning recharts will try to use that as the top point in the graph always.

**Comment by PointSingularity** [comment]
> @PointSingularity remove the `domain` on your YAxis and then the issue goes away. If you set your domain to a value divisible by 20 it also works `domain={[0, 200]}`. The issue is that `dataMax` here is 190 meaning recharts will try to use that as the top point in the graph always.

This does indeed solve it, thank you!

**Comment by X7Becka** [comment]
> @PointSingularity remove the `domain` on your YAxis and then the issue goes away. If you set your domain to a value divisible by 20 it also works `domain={[0, 200]}`. The issue is that `dataMax` here is 190 meaning recharts will try to use that as the top point in the graph always.

This is not solves the problem! 
Let's guess my Y is 0...100, but another graph could be -15...150, so. To right display two graphs i need to set domain is not to 0...100, but to -15...150.
So i get the same problem, because i cannot even set domain={['dataMin', 'dataMax']}

**Comment by ckifer** [comment]
@X7Becka we can reopen the issue to check the behavior of dataMin, dataMax if you'd like. Can you explain what you mean more? It's an issue because if the data changes your domain has to change?

**Comment by X7Becka** [comment]
> @X7Becka we can reopen the issue to check the behavior of dataMin, dataMax if you'd like. Can you explain what you mean more? It's an issue because if the data changes your domain has to change?

Nah. It's an issue because yAxis skips the tick.
Normally it should look like:
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/51074290/208293473-79d9aaee-a560-42d4-a253-86f858c294d3.png">
but unfortunately i just manually set yTicks on screen.
Without setting ticks manually:
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/51074290/208293538-02471d5e-c86a-4057-8f36-eebaf02b0577.png">
I want to say that i should manually calculate yTicks to pass it in yAxis.
