### ISSUE TITLE
XAxis number cutoff on vertical bar chart

### ISSUE THREAD

**Issue by patryk0605** [recharts/recharts#308]
The following chart: 

``` jsx
<ResponsiveContainer width="100%" height="100%">
  <ComposedChart layout="vertical" data={data} >
    <XAxis type="number"/>
    <YAxis dataKey="name" type="category" width={200}/>
    <CartesianGrid stroke="#f5f5f5"/>
    <Tooltip/>
    <Legend />
    <Bar dataKey="OS" barSize={20} fill="#8884d8" />
  </ComposedChart>
</ResponsiveContainer>
```

is cutting off the number on the `Xaxis` like so: 

![image](https://cloud.githubusercontent.com/assets/7227636/19653064/1adbdad0-99e1-11e6-89dd-ded2c1151f3f.png)

The standard barchart with same dataset was not cutting off the labels on `XAxis`.

**Comment by hi-bazinga** [comment]
You can set the `margin` property of the `ComposedChart` like this: `margin={{right: 10}}`

**Comment by patryk0605** [comment]
@hi-bazinga The margin does the trick, however it would be preferable if something more dynamic could be added to handle this scenario.

**Comment by RoarkeRandall** [comment]
Yeah this has been a pain point for me. When charting a customers spend, some will be spending $10 while others could be in the $100,000 range.
