### ISSUE TITLE
Rounded End Strokes

### ISSUE THREAD

**Issue by alelepd** [recharts/recharts#309]
Hello there,

Recharts seems pretty awesome, I wonder if it is possible to set a rounded end strokes for lines on a radial bar or everywhere where lines are drawn (like most bar charts).

To be precise, here what I am trying to do:

<img width="168" alt="radial_bar_chart_with_rounded_end_strokes" src="https://cloud.githubusercontent.com/assets/6024473/19768653/cda6b960-9c2e-11e6-814b-f8c14e6c790d.png">

Hope some of you could give a clue on how to do this with recharts. I already took a look at the API without luck.

**Comment by xile611** [comment]
@alelepd  
Maybe we can add a new chart to display a single percentage.

**Comment by Eric24** [comment]
Actually, better yet, this would just be an option on a pie chart. The pie chart can already do the visual representation of this, but the ends are flat instead of curved. I think adding an 'end-radius' attribute is all that would be needed.

**Comment by Eric24** [comment]
This might be useful: https://bl.ocks.org/mbostock/aff9e559c5c9968b7ac6

**Comment by danielMensah** [comment]
I still don't understand how to create a pie chart like this (below). It would be nice to include it in the docs.
<img width="168" alt="cda6b960-9c2e-11e6-814b-f8c14e6c790d" src="https://cloud.githubusercontent.com/assets/20041230/25062119/add655ea-21bd-11e7-95bb-3f3a5914948e.png">

**Comment by VrajSolanki** [comment]
@Eric24 Is there support for the  rounded end strokes ??

**Comment by Eric24** [comment]
@VrajSolanki Yes, it was added on 26DEC16. The prop that controls the end-radius of bars on a Radial Bar chart is cornerRadius.

**Comment by oancius** [comment]
Can you use the RadialChart for a progress/percentage chart? if you have only one entry in data object you get a full circle.. i want to set somehow the maximum value of the chart, so if i have only one item in data the fill has to be scaled according to the maximum value setted.

**Comment by Charlesdoiron** [comment]
+1

**Comment by dydokamil** [comment]
> Can you use the RadialChart for a progress/percentage chart? if you have only one entry in data object you get a full circle.. i want to set somehow the maximum value of the chart, so if i have only one item in data the fill has to be scaled according to the maximum value setted.

https://github.com/recharts/recharts/issues/1100

**Comment by aleksfront** [comment]
There is one possible workaround for this. You can add styles to corresponding svg paths (parts of circle).
```
.recharts-sector {
  stroke-linejoin: round;
  stroke-width: 7px;
}
```
`Pie` component should be declared similar to this
```
<Pie
  data={data}
  innerRadius={37}
  outerRadius={37} 
/>
```
and `data` should contain `stroke` field with color value.

**Comment by flyupstudio** [comment]
Hi!
If u need put one rounded stroke u can put on start line circle and on end second circle
example of initialization

const fakeTotalRevenue = [
  { name: 'Potential revenue', value: 520342, delta: 18 },
  { name: 'Total revenue', value: 50342, delta: -10 },
];


import { useTranslation } from 'react-i18next';
import { fakeTotalRevenue } from '../fakedata';
import { COLORS } from '../constants';
import { Cell, Pie, PieChart, Sector } from 'recharts';
import cn from 'classnames';
import { numberWithCommas } from '../../../../utils/adminv2';
import React from 'react';
import DeltaInfo from './deltaInfo';

const TotalRevenue = () => {
  const onPieEnter = () => {};
  const { t, i18n } = useTranslation();
  const allRequests = fakeTotalRevenue.reduce(
    (all, { value }) => all + value,
    0
  );

  const renderActiveShape = (props) => {
    const RADIAN = Math.PI / 180;
    const {
      cx,
      cy,
      midAngle,
      innerRadius,
      outerRadius,
      startAngle,
      endAngle,
      fill,
      payload,
      percent,
      value,
    } = props;

    const sin = Math.sin(-RADIAN * (startAngle - endAngle));
    const cos = Math.cos(-RADIAN * (startAngle - endAngle));

    const x1 = cx + (outerRadius - 5) * cos;
    const y1 = cy + (outerRadius - 5) * sin;

    return (
      <g>
        <circle
          cx={x1}
          cy={y1}
          r="5"
          stroke={COLORS[1]}
          stroke-width={0}
          fill={COLORS[1]}
        />
        <circle
          cx={cx + outerRadius - 5}
          cy={cy}
          r="5"
          stroke={COLORS[1]}
          stroke-width={0}
          fill={COLORS[1]}
        />

        <Sector
          cx={cx}
          cy={cy}
          innerRadius={innerRadius}
          outerRadius={outerRadius}
          startAngle={startAngle}
          endAngle={endAngle}
          fill={fill}
        />
      </g>
    );
  };

  return (
    <div className={cn(`graphValues`, `shadowBox`)}>
      <div className={`pieChart`}>
        <PieChart width={180} height={180} onMouseEnter={onPieEnter}>
          <Pie
            activeIndex={1}
            activeShape={renderActiveShape}
            data={fakeTotalRevenue}
            cx={85}
            cy={85}
            innerRadius={70}
            outerRadius={80}
            fill="#8884d8"
            paddingAngle={0}
            dataKey="value"
          >
            {fakeTotalRevenue.map((entry, index) => (
              <Cell
                key={`cell-${index}`}
                fill={COLORS[index % COLORS.length]}
              />
            ))}
          </Pie>
        </PieChart>

        
      </div>
      
    </div>
  );
};

export default TotalRevenue;

**Comment by jeghers** [comment]
If a segment is very small, where the width of the "slice" is smaller than the radius, then they work poorly, and the forceCornerRadius hack property makes them malfunction badly (appearing at different radii)

**Comment by beinoriusju** [comment]
`cornerRadius` works, but not documented https://recharts.org/en-US/api/Pie

**Comment by jeghers** [comment]
Tried it but it is flaky and handles corner cases poorly.
