### ISSUE TITLE
Multiple area's fail with stackID

### ISSUE THREAD

**Issue by 2hansen** [recharts/recharts#3098]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
If I add "stackId" to Area recharts fails with:
Uncaught TypeError: Cannot read properties of undefined (reading '1')
    at eval (Area.js:539:51)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via 

`const data = [
    {
        "name": "A",
        "data": [
            {
                "value": 847,
                "epoch": 1670799600000,
            },
            {
                "value": 844,
                "epoch": 1670886000000,
            },
            {
                "value": 838,
                "epoch": 1670972400000,
            }
        ]
    },
    {
        "name": "B",
        "data": [
            {
                "value": 11,
                "epoch": 1670799600000,
            },
            {
                "value": 11,
                "epoch": 1670886000000,
            },
            {
                "value": 9,
                "epoch": 1670972400000,
            }
        ]
    }
]
`
`<ResponsiveContainer width='99%' height={ defaultBarChartHeight }>
	<AreaChart data={ data } margin={ {top: 5, right: 30, left: 20, bottom: 5} }>
		{ data.map( statusData => <Area type="monotone" stackId="1" key={ statusData.name }  data={ statusData.data } dataKey="value" name={ statusData.name } connectNulls={ true } isAnimationActive={ false } />) }
	</AreaChart>
</ResponsiveContainer>`

## What is the expected behavior?
Show a stacked AreaChart

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
2.2 (tried also in 2.1.5 with same result)

**Comment by ckifer** [comment]
Hi @2hansen,

I don't have time to reproduce this right now, but if you'd want to a code sandbox reproduction would be awesome. Thank you!

**Comment by 2hansen** [comment]
Hi @ckifer 

Made a fiddle here: https://jsfiddle.net/so92g8nL/2/

If you uncomment stackId="1" in line 27 it fails

**Comment by Yilun-Sun** [comment]
Hi @2hansen , it is not able to use data in a stacked area chart like that.

If you want to have a ranged area chart similar to the api example:
![image](https://user-images.githubusercontent.com/43896664/215446896-978ab134-1873-4d8a-9e97-ffcaba5a6971.png)
Please follow the example code: https://recharts.org/en-US/api/AreaChart.

If you would like a stacked area chart, you will have to change your data to a format that the value is only type of number but not an array of number. Please see the example here: https://recharts.org/en-US/examples/StackedAreaChart

Mixing the range type data but a stacked-style renderer will break it down.
