### ISSUE TITLE
Server side rendering - ReferenceError: window is not defined

### ISSUE THREAD

**Issue by bkniffler** [recharts/recharts#31]
Server side rendering of ResponsiveContainer doesn't currently work because of oui-dom-utils. I've filed an issue there https://github.com/oneuijs/oui-dom-utils/issues/1

Maybe we can leave this one open, until the other one is resolved to keep track of it.

Here is a trace:
```
ReferenceError: window is not defined
 [app]/[recharts]/[oui-dom-utils]/build/index.js:10:29
ResponsiveContainer.js:24 Object.<anonymous>
[app]/[recharts]/lib/component/ResponsiveContainer.js:24:20
```

**Comment by bkniffler** [comment]
Okay, the author just released https://github.com/oneuijs/oui-dom-utils/releases/tag/v0.3.6
A little version bump should fix this.

**Comment by xile611** [comment]
Fix in 0.7.0

**Comment by timowevel1** [comment]
Same issue, using Tooltip on Barchart

**Comment by ckifer** [comment]
@timowevel1 this was closed 8 years ago and the offending dependency isn't used in recharts anymore. 

Can you make a new issue? Imo you shouldn't need to render the tooltip on the server since it's interactive and requires the browser to work
