### ISSUE TITLE
Documentation on Customized component

### ISSUE THREAD

**Issue by talyh** [recharts/recharts#3102]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://recharts.org/en-US/api/Customized has very limited (and to some extent, conflicting) information about adding custom components to charts.

The copy indicates `Cell can be wrapped by Pie, Bar, or RadialBar` (potentially leftover from using https://recharts.org/en-US/api/Cell as basis for this page)
The parent component section indicates pretty much all chart types accept this as a child.

And the actual API just indicates `components` with no clear guidance on how to actually incorporate this into a chart (i.e how it can leverage chart data, how to position it in relationship to other chart elements, etc).

It'd be great if this page could be revised AND if something could be added to https://recharts.org/en-US/examples to display `<Customized>` being used

### What does the proposed API look like?
Just documentation requested, no code changes.

**Comment by ckifer** [comment]
Hey @talyh 

Sorry for the lacking documentation, recharts hasn't had anyone actively working on it in a while. https://github.com/recharts/recharts.org is the docs site. Will open an issue over there linking this. Feel free to make a PR if you want to contribute!

**Comment by talyh** [comment]
Thanks for the super quick answer @ckifer !

I actually couldn't get `<Customized/>` to work, so I don't feel very confident in opening a PR to update the documentation. I'm half-suspicious there's actually a bug preventing it to render correctly, but it may be just me not knowing how to use it (hence the ask for documentation and examples 😄 )

I'll try to dig through the code to at least try and isolate if there's a bug or not (and, if there is, open a separate report for it)

**Comment by ckifer** [comment]
Sweet sounds good. I opened the issue above in the docs repo - if anything I'll make the change for the misleading `Cell` reference.

**Comment by ckifer** [comment]
@talyh 

https://recharts.org/en-US/examples/CustomizedContent

Hopefully this helps! Basically you should be able to render any SVG content but have access (in a component or a function) to the properties that are computed/used to compute chart positions and more.

Super basic example to start, we'll add more in the future I'm sure.

**Comment by ckifer** [comment]
Going to close this for now, please comment back if this doesn't help!

**Comment by nikitawagner** [comment]
https://recharts.org/en-US/examples/CustomizedContent
Hello the content of this link is empty. i have the same problem. i try to render a customized component like this:
<AreaChart>
...
<Customized
      component={
          <Dropdown options={[xxx]} />
      }
  />
  <AreaChart />
  
  but the dropdown does not appear and there is no documentation on the website on it
  
  
![image](https://github.com/user-attachments/assets/cdfbc499-e266-408c-9fc1-5802aecd6c2e)

it would be cool if one could integrate it in the chart without wrapping the chart in another component to add buttons etc

**Comment by ckifer** [comment]
Here is the link you are looking for 

https://recharts.org/en-US/examples/CustomizedCrossContent

But no unfortunately that's not not how customized works. You can add buttons outside your chart, Customized is for custom graphical elements. Anything rendered within it must be svg content.
