### ISSUE TITLE
How to give gap in betwwen sector in piechart ? PadAngle not give the straight line .

### ISSUE THREAD

**Issue by MohdAnas23** [recharts/recharts#3104]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This feature need for a gap between sector in the piechart in a straight line.

### What does the proposed API look like?
Gap

**Comment by MohdAnas23** [comment]
![Screenshot 2022-12-16 181052](https://user-images.githubusercontent.com/102280221/208100585-f4e278e9-3a96-4ddf-97a0-071721fd1b34.png)

**Comment by ckifer** [comment]
Hi @MohdAnas23 

`paddingAngle` seems to do this just fine.
![image](https://user-images.githubusercontent.com/25180830/208159400-1835b66f-2af1-4fa6-94b2-c32591a7d48a.png)
What is the difference between this and what you want to achieve?

**Comment by MohdAnas23** [comment]
By using the PaddingAngle they don't give a straight line or gap between sectors. I need to give the spacing between sectors.
PaddingAngle is fine if sectors are more than 4 or 5 sectors.

**Comment by ckifer** [comment]
Can you provide a screenshot of what you'd want it to look like?

**Comment by MohdAnas23** [comment]
![Screenshot 2022-12-16 181052](https://user-images.githubusercontent.com/102280221/208174835-fb06d1ef-3894-48ff-bc00-da5a16fcb7b7.png)
A straight line between these sectors.

**Comment by ckifer** [comment]
Those lines are straight. You mean you want them to be explicitly parallel to each other?

**Comment by MohdAnas23** [comment]
Yes

**Comment by ckifer** [comment]
This isn't really how a circle works, how would it maintain parallel if the gap was bigger? It wouldn't be able to. Is there another charting library that works like this?
