### ISSUE TITLE
Security vulnerability in d3-interpolate

### ISSUE THREAD

**Issue by dmytro-podolianskyi-ew** [recharts/recharts#3105]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-x7vfd7?file=/package.json)

### Steps to reproduce
run command npm i recharts

### What is expected?
I expected that installation without vulnerability

### What is actually happening?
I got vulnerability for d3-color

https://github.com/advisories/GHSA-36jr-mh4h-2g58

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | react |
| System | windows/linux/macos |
| Browser | Chrome |

---
d3-color uses as deps in d3-interpolate. Could you please update d3-interpolate @types/d3-interpolate to the latest version to fix vulnerability issue. Thanks.

**Comment by wmhartl** [comment]
https://github.com/recharts/recharts/issues/3012

**Comment by ckifer** [comment]
Hi @dmytro-podolianskyi-ew ,

Please read the discussion in #3012. Please track progress there as we can't merge this upgrade without breaking changes.

As this is a duplicate issue, I will close this.
