### ISSUE TITLE
x Axis to always show start and end tick

### ISSUE THREAD

**Issue by sdevidi** [recharts/recharts#312]
Is there a way to always show the start and end ticks for X Axis? (For example, to show the start and end time of a time series)
I am using dates on the X Axis (day), and I notice that the end tick is always missing in my case.
I saw in the docs that I could pass the ticks manually, but wanted to check if there is a simpler way to force this behavior.

Aside from that, thanks for the awesome library.

**Comment by xile611** [comment]
@sdevidi  Fixed in version 0.17.1. But some middle ticks may be hidden. Do you have any suggestion about this behavior ?
