### ISSUE TITLE
[Jest Migration] BarChart.spec.jsx -> BarChart.spec.tsx

### ISSUE THREAD

**Issue by ckifer** [recharts/recharts#3124]
As part of the jest migration we want to move all current jest tests to typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor  BarChart.spec.jsx -> BarChart.spec.tsx` and any existing bar chart tests from karma

Acceptance criteria: 

* All bar chart tests are in TS + RTL + Jest at ` BarChart.spec.tsx`
* `BarChart.spec.jsx` is deleted
* All tests pass

**Comment by turculaurentiu91** [comment]
Hi, I would like to contribute. Can I work on this issue ?

**Comment by ckifer** [comment]
@turculaurentiu91 absolutely, please do!

**Comment by turculaurentiu91** [comment]
There are no Typescript errors or warnings after converting the file to tsx. Looks like for this one, all I had to do is to rename the file.

**Comment by ckifer** [comment]
Sweet - I wrote these issues without knowing exactly how involved each refactor was. Some of them are definitely more involved than others (PieChart was a pain when I did it). Closing this as resolved!
