### ISSUE TITLE
[Jest Migration] LineChart.spec.js -> LineChart.spec.tsx 

### ISSUE THREAD

**Issue by ckifer** [recharts/recharts#3125]
As part of the jest migration we want to move all current jest tests to typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor `LineChart.spec.js -> LineChart.spec.tsx` and any existing bar chart tests from karma

Acceptance criteria: 

* All bar chart tests are in TS + RTL + Jest at ` LineChart.spec.tsx`
* `LineChart.spec.js` is deleted 
* All tests pass

**Comment by turculaurentiu91** [comment]
Since the last issue was easy, I would like to work on this one too. Can you assign it to me?

**Comment by ckifer** [comment]
@turculaurentiu91 all you!

**Comment by ckifer** [comment]
Closed by #3141
