### ISSUE TITLE
[Jest Migration] AreaChart.spec.jsx -> AreaChart.spec.tsx

### ISSUE THREAD

**Issue by ckifer** [recharts/recharts#3126]
As part of the jest migration we want to move all current jest tests to typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor `AreaChart.spec.jsx -> AreaChart.spec.tsx` and any existing bar chart tests from karma

Acceptance criteria: 

* All bar chart tests are in TS + RTL + Jest at `  AreaChart.spec.tsx`
* ` AreaChart.spec.jsx` is deleted
* All tests pass

**Comment by Yilun-Sun** [comment]
working on it

**Comment by ckifer** [comment]
Closed by #3151 

@Yilun-Sun can you create a follow up issue to migrate `AreaChartSpec.js`, uncomment the skips, etc? Thanks!

**Comment by Yilun-Sun** [comment]
> Closed by #3151
> 
> @Yilun-Sun can you create a follow up issue to migrate `AreaChartSpec.js`, uncomment the skips, etc? Thanks!

Yes, #3161 is the one.

TODOs:
- [ ] brush move test
- [ ] add more test

**Comment by Yilun-Sun** [comment]
all related PRs:
- #3151 
- #3161 
- #3163
