### ISSUE TITLE
[Jest Migration] FunnelChart.spec.jsx ->FunnelChart.spec.tsx

### ISSUE THREAD

**Issue by ckifer** [recharts/recharts#3127]
As part of the jest migration we want to move all current jest tests to typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor `FunnelChart.spec.jsx ->FunnelChart.spec.tsx` and any existing bar chart tests from karma

Acceptance criteria: 

* All bar chart tests are in TS + RTL + Jest at ` FunnelChart.spec.tsx`
* ` FunnelChart.spec.jsx` is deleted
* All tests pass

**Comment by marcalexiei** [comment]
I would like to work on this issue.
