### ISSUE TITLE
[Jest Migration] ComposedChart.spec.js ->ComposedChart.spec.tsx

### ISSUE THREAD

**Issue by ckifer** [recharts/recharts#3128]
As part of the jest migration we want to move all current jest tests to typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor `ComposedChart.spec.js ->ComposedChart.spec.tsx` and any existing bar chart tests from karma

Acceptance criteria: 

* All bar chart tests are in TS + RTL + Jest at ` ComposedChart.spec.tsx`
* ` ComposedChart.spec.js` is deleted
* All tests pass

**Comment by turculaurentiu91** [comment]
Can I work on this issue? is anybody else working on this ?

**Comment by ckifer** [comment]
Assigned!
