### ISSUE TITLE
[Jest Migration] util/DataUtils

### ISSUE THREAD

**Issue by ckifer** [recharts/recharts#3134]
We want to move all tests to jest, RTL, and typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor `test/specs/util/DataUtilsSpec.js -> test-jest/util/DataUtilsSpec.spec.ts`. 

https://github.com/recharts/recharts/blob/master/test/specs/util/DataUtilsSpec.js

Acceptance criteria: 

* All tests are in TS + RTL + Jest at `DataUtilsSpec.spec.ts`
* ` DataUtilsSpec.js` is deleted
* All tests pass

**Comment by marcalexiei** [comment]
I would like to work on this issue.

**Comment by ckifer** [comment]
Closed by #3147
