### ISSUE TITLE
Animation running after component is unmounted

### ISSUE THREAD

**Issue by pcmaffey** [recharts/recharts#314]
`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Animate component.`

Happens when I leave the page while an animation timer is still running. Need kill the timer in componentWillUnmount().

**Comment by xile611** [comment]
@pcmaffey I think this problem has been fixed in the latest version of React-Smooth, and version 0.16.0  has used the latest React-Smooth.
