### ISSUE TITLE
[JestMigration] Cell.spec.tsx

### ISSUE THREAD

**Issue by nikolasrieble** [recharts/recharts#3149]
We want to move all tests to jest, RTL, and typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/component/CellSpec.js -> test-jest/component/Cell.spec.ts.

Acceptance criteria:

All tests are in TS + RTL + Jest at Cell.spec.ts
 CellSpec.js is deleted
All tests pass

**Comment by ckifer** [comment]
Closed by #3150
