### ISSUE TITLE
"iteratee is not a function"

### ISSUE THREAD

**Issue by alexanderatallah** [recharts/recharts#315]
Error being thrown when first calling `render` on any graph. All the jsfiddles on the website look like they're affected. Looks like a regression in 0.16.0

**Comment by xile611** [comment]
@alexanderatallah Thank you! I should add some options in LodashModuleReplacementPlugin.

[lodash-webpack-plugin #9](https://github.com/lodash/lodash-webpack-plugin/issues/9)

**Comment by VaskaDogana** [comment]
@xile611 
 Hi, what option you added in LodashModule Replacement Plugin? I have problem like yours

**Comment by JimVercoelen** [comment]
Same
