### ISSUE TITLE
Jest Migration: Label and LabelList

### ISSUE THREAD

**Issue by nikolasrieble** [recharts/recharts#3155]
We want to move all tests to jest, RTL, and typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/components/LabelSpec.js -> test-jest/components/Label.spec.ts.
Refactor test/specs/component/LabelList.spec.tsx

Acceptance criteria:

All tests are in TS + RTL + Jest at Label.spec.ts and LabelList.spec.tsx
 LabelSpec.js is deleted
All tests pass

**Comment by ckifer** [comment]
closed by #3154
