### ISSUE TITLE
[Jest Migration]: AreaChart

### ISSUE THREAD

**Issue by nikolasrieble** [recharts/recharts#3158]
As part of the jest migration we want to move all current jest tests to typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/cartesian/AreaSpec.js -> test-jest/cartesian/Area.spec.ts and any existing bar chart tests from karma

Acceptance criteria:

All bar chart tests are in TS + RTL + Jest at Area.spec.ts
AreaSpec.js is deleted
All tests pass

**Comment by Yilun-Sun** [comment]
closed by #3180
