### ISSUE TITLE
[Jest Migration]: Bar

### ISSUE THREAD

**Issue by nikolasrieble** [recharts/recharts#3159]
As part of the jest migration we want to move all current jest tests to typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/cartesian/BarSpec.js -> test-jest/cartesian/Bar.spec.ts and any existing bar chart tests from karma

Acceptance criteria:

All bar chart tests are in TS + RTL + Jest at Bar.spec.ts
BarSpec.js is deleted
All tests pass

**Comment by akib22** [comment]
Hi @nikolasrieble, I want to work on this issue. Can you please assign me to this issue?

**Comment by nikolasrieble** [comment]
Sure, it is yours! ❤️ Feel free to tag me for review.

**Comment by akib22** [comment]
Hi @nikolasrieble, I have created a pull request. Not running the workflow because of first-time contributor approval, and I'm not able to make a review request. Can you please check it?

**Comment by ckifer** [comment]
Closed by #3179

@akib22 feel free to make another PR with the small changes suggested
