### ISSUE TITLE
Could 'Area' in AreaChart accept a range value, that the lower curve not start from zero?

### ISSUE THREAD

**Issue by BOZ88** [recharts/recharts#316]

**Comment by xile611** [comment]
@doublelduob Can you give an example of your chart ?

**Comment by supersteves** [comment]
I'm interested in this also. I want to be able to create confidence intervals for a timeseries prediction, for example:

![image](https://cloud.githubusercontent.com/assets/10280734/20179961/535ed1ce-a750-11e6-8210-9acd98e1bbc9.png)

**Comment by Eric24** [comment]
+1 (for exactly the same purpose--confidence intervals). Specifically, it would be an area component with two values, "high" and "low", with a line component drawn over it.

**Comment by BOZ88** [comment]
like @supersteves 's chart, usually used for confidence interval demonstration.
Just wondering if there is a way that we write our own widget like RangeArea that can integrated into AeaChart.

**Comment by supersteves** [comment]
@BOZ88 Some ideas - we were able to customise a *ScatterChart* by passing a custom renderer to the Scatter "line" prop, which augmented the existing props with additional points. This is quite a lot of work when out-of-the-box is so close to being able to do this.

We've also experimented with using (hacking) a ReferenceDot or other similar component - also within Scatter - which happens to expose the axis scales such that coordinates can be mapped between the real data range and pixels. In https://github.com/recharts/recharts/issues/365 we suggested including the d3.scale objects for each axis as part of the props of other customisable renderers to allow more sophisticated customisation - such as this.

**Comment by igorbpf** [comment]
Hello, guys!
Has this feature been implemented yet?

**Comment by jabberwo** [comment]
Last comment was a reversion of the feature?  So we don't have something like react-vis's AreaSeries where you can set y AND y0, so fill the space between the two?

**Comment by wanthalf** [comment]
This was implemented and then removed again?? Why?

**Comment by satejsoman** [comment]
hi! could we get more context on why the commit implementing this was reverted?

**Comment by Eric24** [comment]
This is possible to do by simply passing your datakey as a two-item array: `[low, high]`

**Comment by satejsoman** [comment]
got it, thank you!

**Comment by dmp359** [comment]
@satejsoman Did you have to do anything special than before? In my JSFiddle here, https://jsfiddle.net/038914fb/2/, everything is fine. But when I go to my codebase, the areas do not show up if I attempt to graph a two-item array. (If I just use one value, it works). The JSFiddle and my codebase are on Recharts 1.8.5 so i'm not sure what's going on

**Comment by jasiene** [comment]
Hi, could someone point me in the right direction to achieve what @supersteves posted a picture of

**Comment by RodKik** [comment]
> This is possible to do by simply passing your datakey as a two-item array: `[low, high]`

To everyone still struggling with this: the solution proposed by Eric24 works!
To clarify: use a single "dataKey", but corresponding data should be an array, like this:
`
export type MyDataType = {
  xValue: number;
  yValue: number;           // Contains the y values for a Line
  yRange: number[];       // Contains the [min, max] values for an Area
};

 const chartData: MyDataType [] = [];

// Fill data as needed by your app

// Rendering...
<div className="chart_content">
          <ResponsiveContainer width="100%" height="100%">
            <ComposedChart data={chartData}>
              <Area
                  type="monotone"
                  dataKey="yRange"
              />
              <Line
                  type="monotone"
                  dataKey="yValue"
              />
            </ComposedChart>
          </ResponsiveContainer>
</div>
`

**Comment by Dugyu** [comment]
also you can use 2 <Area> and set the bottom one fill to transparent.

import React, { PureComponent } from 'react';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

const data = [
  {
    name: 'Page A',
    uv: 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: 'Page B',
    uv: 3000,
    pv: 1398,
    amt: 2210,
  },
  {
    name: 'Page C',
    uv: 2000,
    pv: 9800,
    amt: 2290,
  },
  {
    name: 'Page D',
    uv: 2780,
    pv: 3908,
    amt: 2000,
  },
  {
    name: 'Page E',
    uv: 1890,
    pv: 4800,
    amt: 2181,
  },
  {
    name: 'Page F',
    uv: 2390,
    pv: 3800,
    amt: 2500,
  },
  {
    name: 'Page G',
    uv: 3490,
    pv: 4300,
    amt: 2100,
  },
];

export default class Example extends PureComponent {
  static demoUrl = 'https://codesandbox.io/s/stacked-area-chart-ix341';

  render() {
    return (
      <ResponsiveContainer width="100%" height="100%">
        <AreaChart
          width={500}
          height={400}
          data={data}
          margin={{
            top: 10,
            right: 30,
            left: 0,
            bottom: 0,
          }}
        >
          <CartesianGrid strokeDasharray="3 3" />
          <XAxis dataKey="name" />
          <YAxis />
          <Tooltip />
          <Area type="monotone" dataKey="pv" stackId="2" stroke="#ffc658" fill="rgba(0, 0, 0, 0)" />
          <Area type="monotone" dataKey="amt" stackId="2" stroke="#ffc658" fill="#ff6a00" />
        </AreaChart>
      </ResponsiveContainer>
    );
  }
}
