### ISSUE TITLE
[Jest Migration]: Brush

### ISSUE THREAD

**Issue by nikolasrieble** [recharts/recharts#3160]
As part of the jest migration we want to move all current jest tests to typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/cartesian/BrushSpec.js -> test-jest/cartesian/Brush.spec.ts and any existing bar chart tests from karma

Acceptance criteria:

All bar chart tests are in TS + RTL + Jest at Brush.spec.ts
BrushSpec.js is deleted
All tests pass

**Comment by tharitRT** [comment]
You must have your react code(JSX) in `.tsx` file. I try change `BrushSpec.js` to `BrushSpec.tsx` and it's working fine. If this is ok I will proceed with creating a PR.

**Comment by ckifer** [comment]
Closed by  #3183
