### ISSUE TITLE
BarChart is not working for one value of data with tooltip

### ISSUE THREAD

**Issue by daturon** [recharts/recharts#3172]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-ycmdew?file=/src/index.js:579-590)

### Steps to reproduce
Uncomment line 24: <Tooltip />

### What is expected?
We can see the bar with a tooltip

### What is actually happening?
The app is crushed with an error: TypeError Cannot read properties of undefined (reading 'coordinate')

| Environment | Info |
|---|---|
| Recharts | v2.3.1 |
| React | 18.2.0 |
| System | Mac |
| Browser | Chrome Version 107.0.5304.121 (Official Build) (arm64) |

**Comment by ckifer** [comment]
Sorry about this - on it

**Comment by ckifer** [comment]
@daturon thanks for the report - fixed in v2.3.2 and published https://github.com/recharts/recharts/releases/tag/v2.3.2

**Comment by daturon** [comment]
It was super fast, thanks!
