### ISSUE TITLE
[JestMigration] ReferenceAreaSpec.js

### ISSUE THREAD

**Issue by nikolasrieble** [recharts/recharts#3189]
As part of the jest migration we want to move all current tests to typescript + RTL + jest. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/cartesian/ReferenceAreaSpec.js -> test-jest/cartesian/ReferenceArea.spec.tsx

Acceptance criteria:

- [ ] All tests are in TS + RTL + Jest
- [ ] Previous test is deleted
- [ ] All tests pass

**Comment by ckifer** [comment]
Closed by #3205
