### ISSUE TITLE
API Clarification

### ISSUE THREAD

**Issue by Mannaio** [recharts/recharts#319]
I am studying your API and i have posted a question in stackoverflow on how on the x and y-coordinate values of center of the dots are calculated

I would really appreciate your explanation

http://stackoverflow.com/questions/40410094/calculation-the-x-and-y-coordinate-of-center-in-recharts

**Comment by xile611** [comment]
@Mannaio The coordinate of dots are calculated in [LineChart](https://github.com/recharts/recharts/blob/master/src/chart/LineChart.js#L35). In brief, we would calculate the scale function of x-axis and y-axis first, then calculate the coordinate by scale function.
