### ISSUE TITLE
[JestMigration] ScatterSpec.js

### ISSUE THREAD

**Issue by nikolasrieble** [recharts/recharts#3192]
As part of the jest migration we want to move all current tests to typescript + RTL + jest. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/cartesian/ScatterSpec.js -> test-jest/cartesian/Scatter.spec.tsx

Acceptance criteria:

- [ ] All tests are in TS + RTL + Jest
- [ ] Previous test is deleted
- [ ] All tests pass

**Comment by akib22** [comment]
Sorry, I mistakenly linked this #3223.

**Comment by ckifer** [comment]
Closed by https://github.com/recharts/recharts/pull/3220
