### ISSUE TITLE
[Jest Migration] chart/RadarChartSpec

### ISSUE THREAD

**Issue by proke03** [recharts/recharts#3209]
We want to move all tests to jest, RTL, and typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/chart/RadarChartSpec.js -> test-jest/chart/RadarChart.spec.ts.

https://github.com/recharts/recharts/blob/master/test/specs/chart/RadarChartSpec.js

Acceptance criteria:

All tests are in TS + RTL + Jest at RadarChart.spec.ts
RadarChartSpec.js is deleted
All tests pass

**Comment by ckifer** [comment]
Closed by #3216
