### ISSUE TITLE
[Jest Migration] chart/TreemapSpec

### ISSUE THREAD

**Issue by proke03** [recharts/recharts#3210]
We want to move all tests to jest, RTL, and typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/chart/TreemapSpec.js -> test-jest/chart/Treemap.spec.ts.

https://github.com/recharts/recharts/blob/master/test/specs/chart/TreemapSpec.js

Acceptance criteria:

All tests are in TS + RTL + Jest at Treemap.spec.ts
TreemapSpec.js is deleted
All tests pass

**Comment by ckifer** [comment]
Closed by #3211
