### ISSUE TITLE
[Jest Migration] component/CustomizedSpec

### ISSUE THREAD

**Issue by proke03** [recharts/recharts#3212]
We want to move all tests to jest, RTL, and typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/component/CustomizedSpec.js -> test-jest/component/Customized.spec.ts.

https://github.com/recharts/recharts/blob/master/test/specs/component/CustomizedSpec.js

Acceptance criteria:

All tests are in TS + RTL + Jest at Customized.spec.ts
CustomizedSpec.js is deleted
All tests pass

**Comment by ckifer** [comment]
closed by  #3218
