### ISSUE TITLE
[Jest Migration] component/LegendSpec

### ISSUE THREAD

**Issue by proke03** [recharts/recharts#3213]
We want to move all tests to jest, RTL, and typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/component/LegendSpec.js -> test-jest/component/Legend.spec.ts.

https://github.com/recharts/recharts/blob/master/test/specs/component/LegendSpec.js

Acceptance criteria:

All tests are in TS + RTL + Jest at Legend.spec.ts
LegendSpec.js is deleted
All tests pass

**Comment by ckifer** [comment]
Closed by  #3217
