### ISSUE TITLE
[Jest Migration] component/TextSpec

### ISSUE THREAD

**Issue by proke03** [recharts/recharts#3214]
We want to move all tests to jest, RTL, and typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/component/TextSpec.js -> test-jest/component/Text.spec.ts.

https://github.com/recharts/recharts/blob/master/test/specs/component/TextSpec.js

Acceptance criteria:

All tests are in TS + RTL + Jest at Text.spec.ts
TextSpec.js is deleted
All tests pass

**Comment by ckifer** [comment]
Closed by  #3286
