### ISSUE TITLE
[Jest Migration] component/TooltipSpec

### ISSUE THREAD

**Issue by proke03** [recharts/recharts#3215]
We want to move all tests to jest, RTL, and typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/component/TooltipSpec.js -> test-jest/component/Tooltip.spec.ts.

https://github.com/recharts/recharts/blob/master/test/specs/component/TooltipSpec.js

Acceptance criteria:

All tests are in TS + RTL + Jest at Tooltip.spec.ts
TooltipSpec.js is deleted
All tests pass

**Comment by ckifer** [comment]
Closed by #3267
