### ISSUE TITLE
[Jest Migration] chart/ScatterChartSpec

### ISSUE THREAD

**Issue by proke03** [recharts/recharts#3219]
We want to move all tests to jest, RTL, and typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/chart/ScatterChartSpec.js -> test-jest/chart/ScatterChart.spec.ts.

https://github.com/recharts/recharts/blob/master/test/specs/chart/ScatterChartSpec.js

Acceptance criteria:

All tests are in TS + RTL + Jest at ScatterChart.spec.ts
ScatterChartSpec.js is deleted
All tests pass

**Comment by ckifer** [comment]
Closed by #3221
