### ISSUE TITLE
[Jest Migration] polar/PieSpec

### ISSUE THREAD

**Issue by proke03** [recharts/recharts#3227]
We want to move all tests to jest, RTL, and typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/polar/PieSpec.js -> test-jest/polar/Pie.spec.ts.

https://github.com/recharts/recharts/blob/master/test/specs/polar/PieSpec.js

Acceptance criteria:

All tests are in TS + RTL + Jest at Pie.spec.ts
PieSpec.js is deleted
All tests pass

**Comment by ckifer** [comment]
Closed by #3229
