### ISSUE TITLE
[Jest Migration] polar/PolarAngleAxisSpec

### ISSUE THREAD

**Issue by proke03** [recharts/recharts#3230]
We want to move all tests to jest, RTL, and typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/polar/PolarAngleAxisSpec.js -> test-jest/polar/PolarAngleAxis.spec.ts.

https://github.com/recharts/recharts/blob/master/test/specs/polar/PolarAngleAxisSpec.js

Acceptance criteria:

All tests are in TS + RTL + Jest at PolarAngleAxis.spec.ts
PolarAngleAxisSpec.js is deleted
All tests pass

**Comment by ckifer** [comment]
Closed by #3231
