### ISSUE TITLE
[Jest Migration] polar/PolarGridSpec

### ISSUE THREAD

**Issue by proke03** [recharts/recharts#3232]
We want to move all tests to jest, RTL, and typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/polar/PolarGridSpec.js -> test-jest/polar/PolarGrid.spec.ts.

https://github.com/recharts/recharts/blob/master/test/specs/polar/PolarGridSpec.js

Acceptance criteria:

All tests are in TS + RTL + Jest at PolarGrid.spec.ts
PolarGridSpec.js is deleted
All tests pass

**Comment by ckifer** [comment]
Closed by #3233
