### ISSUE TITLE
[Jest Migration] polar/PolarRadiusAxisSpec

### ISSUE THREAD

**Issue by proke03** [recharts/recharts#3234]
We want to move all tests to jest, RTL, and typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/polar/PolarRadiusAxisSpec.js -> test-jest/polar/PolarRadiusAxis.spec.ts.

https://github.com/recharts/recharts/blob/master/test/specs/polar/PolarRadiusAxisSpec.js

Acceptance criteria:

All tests are in TS + RTL + Jest at PolarRadiusAxis.spec.ts
PolarRadiusAxisSpec.js is deleted
All tests pass

**Comment by ckifer** [comment]
Closed by #3235
