### ISSUE TITLE
[Jest Migration] polar/RadialBarSpec

### ISSUE THREAD

**Issue by proke03** [recharts/recharts#3237]
We want to move all tests to jest, RTL, and typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/polar/RadialBarSpec.js -> test-jest/polar/RadialBar.spec.ts.

https://github.com/recharts/recharts/blob/master/test/specs/polar/RadialBarSpec.js

Acceptance criteria:

All tests are in TS + RTL + Jest at RadialBar.spec.ts
RadialBarSpec.js is deleted
All tests pass

**Comment by ckifer** [comment]
Closed by  #3238
