### ISSUE TITLE
[Jest Migration] shape/CrossSpec

### ISSUE THREAD

**Issue by proke03** [recharts/recharts#3239]
We want to move all tests to jest, RTL, and typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/shape/CrossSpec.js -> test-jest/shape/Cross.spec.ts.

https://github.com/recharts/recharts/blob/master/test/specs/shape/CrossSpec.js

Acceptance criteria:

All tests are in TS + RTL + Jest at Cross.spec.ts
CrossSpec.js is deleted
All tests pass

**Comment by ckifer** [comment]
Closed by #3252
