### ISSUE TITLE
[Jest Migration] shape/CurveSpec

### ISSUE THREAD

**Issue by proke03** [recharts/recharts#3240]
We want to move all tests to jest, RTL, and typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/shape/CurveSpec.js -> test-jest/shape/Curve.spec.ts.

https://github.com/recharts/recharts/blob/master/test/specs/shape/CurveSpec.js

Acceptance criteria:

All tests are in TS + RTL + Jest at Curve.spec.ts
CurveSpec.js is deleted
All tests pass

**Comment by ckifer** [comment]
Closed by #3241
