### ISSUE TITLE
[Jest Migration] shape/DotSpec

### ISSUE THREAD

**Issue by proke03** [recharts/recharts#3243]
We want to move all tests to jest, RTL, and typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/shape/DotSpec.js -> test-jest/shape/Dot.spec.ts.

https://github.com/recharts/recharts/blob/master/test/specs/shape/DotSpec.js

Acceptance criteria:

All tests are in TS + RTL + Jest at Dot.spec.ts
DotSpec.js is deleted
All tests pass

**Comment by ckifer** [comment]
Closed by #3244
