### ISSUE TITLE
[Jest Migration] shape/PolygonSpec

### ISSUE THREAD

**Issue by proke03** [recharts/recharts#3245]
We want to move all tests to jest, RTL, and typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/shape/PolygonSpec.js -> test-jest/shape/Polygon.spec.ts.

https://github.com/recharts/recharts/blob/master/test/specs/shape/PolygonSpec.js

Acceptance criteria:

All tests are in TS + RTL + Jest at Polygon.spec.ts
PolygonSpec.js is deleted
All tests pass

**Comment by ckifer** [comment]
Closed by #3246
