### ISSUE TITLE
[Jest Migration] shape/RectangleSpec

### ISSUE THREAD

**Issue by proke03** [recharts/recharts#3247]
We want to move all tests to jest, RTL, and typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/shape/RectangleSpec.js -> test-jest/shape/Rectangle.spec.ts.

https://github.com/recharts/recharts/blob/master/test/specs/shape/RectangleSpec.js

Acceptance criteria:

All tests are in TS + RTL + Jest at Rectangle.spec.ts
RectangleSpec.js is deleted
All tests pass

**Comment by ckifer** [comment]
Closed by #3255
