### ISSUE TITLE
[Jest Migration] shape/SymbolsSpec

### ISSUE THREAD

**Issue by proke03** [recharts/recharts#3249]
We want to move all tests to jest, RTL, and typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/shape/SymbolsSpec.js -> test-jest/shape/Symbols.spec.ts.

https://github.com/recharts/recharts/blob/master/test/specs/shape/SymbolsSpec.js

Acceptance criteria:

All tests are in TS + RTL + Jest at Symbols.spec.ts
SymbolsSpec.js is deleted
All tests pass

**Comment by ckifer** [comment]
closed by #3257
