### ISSUE TITLE
[Jest Migration] shape/TrapezoidSpec

### ISSUE THREAD

**Issue by proke03** [recharts/recharts#3250]
We want to move all tests to jest, RTL, and typescript. Issues will be made to encourage small chunks of refactoring done at once.

Refactor test/specs/shape/TrapezoidSpec.js -> test-jest/shape/Trapezoid.spec.ts.

https://github.com/recharts/recharts/blob/master/test/specs/shape/TrapezoidSpec.js

Acceptance criteria:

All tests are in TS + RTL + Jest at Trapezoid.spec.ts
TrapezoidSpec.js is deleted
All tests pass

**Comment by ckifer** [comment]
Closed by  #3251
