### ISSUE TITLE
X axis with many dates overflow issues

### ISSUE THREAD

**Issue by vitali-duckma** [recharts/recharts#3262]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://recharts.org/en-US/api](https://recharts.org/en-US/api)

### Steps to reproduce
Create many dates inside the X axises and you will see overflow of dates
https://ibb.co/rwRXkgL

### What is expected?
Responsive dates group

### What is actually happening?
It creates overflow

| Environment | Info |
|---|---|
| Recharts | v2.3.2 |
| React | 18 |
| System | mac |
| Browser | chrome |

---
https://ibb.co/rwRXkgL

**Comment by ckifer** [comment]
Hi @vitali-duckma - to me it just looks like you need additional right margin on your chart, but I can't tell entirely based on the image.

Another solution would be to rotate your labels 45 degrees so they are always visible no matter how long they are. If these things don't work please add a reproduction to this issue. 

Thanks!

**Comment by ckifer** [comment]
Going to close this as stale until some more detail can be added/response is received
