### ISSUE TITLE
3.0 proposal: Remove deprecated `alwaysShow`  prop 

### ISSUE THREAD

**Issue by marcalexiei** [recharts/recharts#3274]
During #3269 I noticed some deprecated warnings issued by the use of `alwaysShow` prop

I would like to propose the removal of this deprecated prop as part of the [`3.0` release](https://github.com/recharts/recharts/milestone/2).

**Comment by nikolasrieble** [comment]
I added it, the whole project so far is a proposal, thus feel free to simply add it. Please do write a bit more about it though, adding context and reason as to why this should be removed and how a user could achieve the same result in another manner.

**Comment by marcalexiei** [comment]
Reference  components 

- ReferenceArea
- ReferenceDot
- ReferenceLine

accept  a `alwaysShow` but when  used a warning  is displayed in console:

> The alwaysShow prop is deprecated. Please use ifOverflow="extendDomain"

The prop has been deprecated in  all  3 components  and can be safely removed since an alternative (`ifOverflow="extendDomain`) is already available.

**Comment by aushwin** [comment]
@ckifer Let me know if I can start working on this 😄

**Comment by ckifer** [comment]
@aushwin you can see via the referenced PR that @marcalexiei has already completed this work

**Comment by marcalexiei** [comment]
@ckifer I haven't worked on the removal because @proke03 already created a PR after I opened the issue.  
At the moment it has some conflicts with the base branch. Do I need to create a new  PR?

**Comment by aushwin** [comment]
@marcalexiei did you try rebasing with the base pr? I think. That will resolve the conflicts .

**Comment by ckifer** [comment]
It's fine for now because we won't merge it for a while

**Comment by marcalexiei** [comment]
> did you try rebasing with the base pr? I think. That will resolve the conflicts .

@aushwin I haven't created the PR so I can't perform  any actions to that branch

**Comment by proke03** [comment]
@marcalexiei
How can I fix it?

**Comment by ckifer** [comment]
Oh oops. I just referenced the wrong person. This is fine as is with the PR from @proke03   sorry sent on mobile

**Comment by proke03** [comment]
@ckifer 
The fix by @marcalexiei seems to be enough. I closed the PR #3277.

**Comment by ckifer** [comment]
@proke03 your PR is fine to remain open, no one else has done this change. This thread is confusing me 😅 .

I will re-open your PR and keep it open until we can create a 3.x.x branch or figure out a strategy for contributing to 3.x.x

**Comment by ckifer** [comment]
Merged into 3.x
