### ISSUE TITLE
Change defaultProps in ReferenceArea and ReferenceLine to use Javascript default parameters

### ISSUE THREAD

**Issue by AlexMcClay** [recharts/recharts#3278]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
React will remove support for default props in a future major release, so it's best to change it to use Javascript default parameters instead. There are already some errors that show up when using these features in React, so it would remove the errors and warnings.

### What does the proposed API look like?
changing defaultProps to Javascript default parameters is pretty self-explanatory.

**Comment by ckifer** [comment]
Thanks @AlexMcClay 

Labeled and ready to go

**Comment by aushwin** [comment]
@ckifer can I pick this up  ?

**Comment by ckifer** [comment]
Absolutely - assigned

**Comment by aushwin** [comment]
@ckifer Could you please guide me here as it's my first time contributing. I have refactored and pushed the changes.

**Comment by ckifer** [comment]
@aushwin Looks good. Fix the build/test failure and we should be good to go

**Comment by aushwin** [comment]
Should I refactor more such that instead of combining the destructured values back to an object, it can be passed into the functions wherever needed ?  How can I resolve this one  @ckifer 
Thanks 
![image](https://user-images.githubusercontent.com/54993680/214925246-85fd69b7-1023-4d59-b7b4-b4f92df0f50b.png)

**Comment by aushwin** [comment]
> Should I refactor more such that instead of combining the destructured values back to an object, it can be passed into the functions wherever needed ? How can I resolve this one @ckifer Thanks ![image](https://user-images.githubusercontent.com/54993680/214925246-85fd69b7-1023-4d59-b7b4-b4f92df0f50b.png)

got the error fixed

**Comment by ckifer** [comment]
just an `npm install` should install cross-env. Try to delete node_modules

**Comment by aushwin** [comment]
@ckifer please re-review

**Comment by ckifer** [comment]
closed by  #3283

**Comment by leo-terrier** [comment]
Hello, I've seen that this commit has been reverted and that defaultProps is back. 

I was wondering what could be the impact of defaultProps usage (other than the console warning), since its going to be deprecated on functional component. Thanks for your reply and for the great lib!

**Comment by ckifer** [comment]
Please see https://github.com/recharts/recharts/issues/3438#issuecomment-1467419256

**Comment by ckifer** [comment]
Options to move forward on this are essentially:

1. Remove the use of React.cloneElement from recharts (high effort, high change of introducing breaking changes, architecture changes needed)
2. Revert back to a class component (not at all ideal but at least deprecation isn't an issue)
