### ISSUE TITLE
Fill PieChart with multiple colors

### ISSUE THREAD

**Issue by mlallenAxpe** [recharts/recharts#3279]
### What problem does this feature solve?
It allows an user to draw a pie chart with each slice in different colors.

### What does the proposed API look like?
Like he normal Pie chart, but with each slice in different colors.

### How would I do it?
I would add that the fill element could also be an array of strings, and in the command to draw each sector fill it with the corresponding color.

**Comment by ckifer** [comment]
Hi @mlallenAxpe 

I'm confused by this feature request since this is already possible. 

https://recharts.org/en-US/examples/PieChartWithCustomizedLabel

Is that what you are asking for?

**Comment by mlallenAxpe** [comment]
Yes, that's what I was asking about.

**Comment by ckifer** [comment]
Sounds good, closing this as answered
