### ISSUE TITLE
Curve is getting unknown style prop

### ISSUE THREAD

**Issue by vanthiyathevan** [recharts/recharts#328]
Hello,
I was getting `CSSPropertyOperations.js:187 Uncaught TypeError: Cannot assign to read only property 'length' of object '#<CSSStyleDeclaration>'` when a chart is updated. On trying to debug I came across that the `Curve` component is getting this prop `{style:{length:'277px'}}` I can't seem to figure out where this prop is coming from. I will try to post the problem linechart config I have soon.

This doesn't happen when `isAnimationActive` is `false`

**Comment by xile611** [comment]
@vanthiyathevan Can you create a jsfiddle demo ? I don't know how to reproduce this problem now.

**Comment by xile611** [comment]
I think this issue has been fixed. Please check the latest version.
