### ISSUE TITLE
Monorepo: Integrate the website into the main repository

### ISSUE THREAD

**Issue by nikolasrieble** [recharts/recharts#3302]
Having separate repositories increases effort for keeping the documentation in sync with feature development. 

A mono repo enables us to change documentation and code in a single PR. 

Acceptance criteria: recharts.org is integrated and deployed from the recharts/recharts repo.

**Comment by akamfoad** [comment]
https://turbo.build/repo Seems promising, it can be tried, if it was as advertised, it might be possible to integrate other dependencies of recharts into the monorepo too, in the future, such as https://github.com/recharts/react-smooth

**Comment by nikolasrieble** [comment]
Great idea @akamfoad.
We currently changed out idea, and are considering to simply replace the website completely with storybook. Thus I shall close this specific issue. 

There still might be need for monorepo tooling.
