### ISSUE TITLE
onClick only triggers on area with a value

### ISSUE THREAD

**Issue by patryk0605** [recharts/recharts#331]
I am currently using the `onClick` for `Bar` and `RadialBar`. One issue is that the `onClick` only triggers when a user clicks on the value and not the bar itself. I made an [example fiddle](https://jsfiddle.net/patryk0605/ydycdLpx/) to demo the issue. 

Can the functionality be extended to trigger when the bar is clicked anywhere and not just on the value? The problem with only having the `onClick` on the value is that when you have one value at **1** and another at **100**, it becomes very hard to click on that value with a **1**.

**Comment by xile611** [comment]
@patryk0605 `onClick` on `ComposedChart` can be triggered on the *band* of bar. But it seems some bug happens here, the event will be triggered twice. Please check [this demo](https://jsfiddle.net/xbwwwxfw/).

**Comment by patryk0605** [comment]
@xile611 Your solution resolves my issue for `ComposedChart`, however `RadialBarChart` does not seem to support the same `onClick`. Any method I can use for the whole `RadialBar` to support `onClick` and not just the area with a value?
