### ISSUE TITLE
How can I add gradient drop shadow in line chart  and change color of cursor

### ISSUE THREAD

**Issue by vishalmanjrekar** [recharts/recharts#3316]
![7kwHr](https://user-images.githubusercontent.com/46892861/216466245-9f008e33-c2fe-4cbf-9967-224b2b697548.png)

**Comment by ckifer** [comment]
Can you please give more details than this? What exactly do you want to change? What exactly do you want to change it to/want it to look like?

**Comment by vishalmanjrekar** [comment]
I want to change cursor color and want drop shadow with gradient color

**Comment by ckifer** [comment]
The cursor can be customized using the `cursor` prop of the `Tooltip`
```
<Tooltip cursor={{ stroke: 'red', strokeWidth: 2 }} />
```
https://recharts.org/en-US/api/Tooltip

https://codesandbox.io/s/simple-line-chart-forked-yths8i
Just use CSS to add a drop-shadow like the above Codesandbox.

Lots of references to these solutions when searching the internet

drop-shadow - https://stackoverflow.com/questions/71071901/how-can-i-add-shadow-on-piechart-in-recharts
custom cursor - https://github.com/recharts/recharts/issues/1816

**Comment by ckifer** [comment]
Closing this as answered
