### ISSUE TITLE
Add support for a minimum delta between low and high ends of auto-calculated axis domains

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#3317]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
For example, if the calculated auto-domain for a temperature chart was 1 degree (0 to 1 or 19 to 20, for example), the range of the calculated axis may be too small to be meaningful (i.e. the chart would show what appeared to be a lot of fluctuations, while the actual change was a fraction of a degree).

### What does the proposed API look like?
I'm not sure when (or how often) the domain is recalculated. If this happens every time dataMin or dataMax is updated, then I can see how to implement this in the function version of the domain declaration. But if not, this would need to be done internally. If so, I would propose an optional third item in the domain array, which when supplied, would be the minimum domain range.

**Comment by ckifer** [comment]
Hi @Eric24 

I get what you mean... kind of, but not really sure what you're suggesting. 

Can you give a codesandbox example of when this is a problem?

**Comment by Eric24** [comment]
It's not really something that can be specifically demonstrated with a code example. The issue is simply that if we leave the auto-domain calculation to its own devices, the range can get very narrow when the actual values aren't changing much. My temperature example is probably the easiest way to understand this. If the temperature value is fluctuating between 23.2 and 23.8 degrees, the auto-domain will make those the high and low values of the axis domain. In some cases, that might be fine, but in many cases, that level of "precision" is just too high. The proposed "min domain range" value could be set to 6, for example, so the auto-domain would instead range from 20.2 and 26.8 (divide the min-range value of 6 by 2 to get 3, then subtract 3 from the low value and add 3 to the high value). This will place the values in the middle of that ~6-degree range, which for outdoor temperature (for example) would be much more useful and customary than a temperature chart with a less-than-one-degree range.

**Comment by ckifer** [comment]
Could you not just add and subtract from the dataMin and dataMax of the domain?

For example, this is the problem - https://codesandbox.io/s/simple-line-chart-data-min-max-ex-uvlori

Solution: https://codesandbox.io/s/simple-line-chart-data-min-max-plus-minus-three-uvlori?file=/src/App.tsx

**Comment by Eric24** [comment]
You are absolutely right! This (even simpler) syntax does exactly what I was looking for: `['dataMin - 3', 'dataMax + 3']`. Thank you!

**Comment by ckifer** [comment]
Glad to hear it! No problem :)
