### ISSUE TITLE
"Can only update a mounted or mounting component."

### ISSUE THREAD

**Issue by colshacol** [recharts/recharts#332]
I have 10 square components in my view. Each square has a child that holds 15 graphs that feed off of a global data source that is updated once every second. When a square is hovered, the graphs container is rendered. When the square is un-hovered, the graphs container is removed completely from the DOM. This is an error that I am getting thrown randomly when I am alternating from hovered/not hovered.

```
VM31752:20 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ContainerDimensions component.
```

Example: https://drive.google.com/file/d/0B4YUcg2HBSIvNXVUZXV0X3Q1VWM/view

```
// Chart code.
<ResponsiveContainer>
  <AreaChart data={Array.from(LocationsStore.data)} width={AuxStore.locationOverviewsWidth} height={50}>
    <Area  isAnimationActive={false} type="monotone" dataKey="stars" stroke="#ffffff"/>
  </AreaChart>
</ResponsiveContainer>
```

**Comment by colshacol** [comment]
I've figured out that it happens when I activate a hover on a different graph before the previously hovered one has unmounted. Still don't know how to fix it, though.

**Comment by xile611** [comment]
@colshacol This is duplicated with #249 .
