### ISSUE TITLE
onResize for ResponsiveContainer

### ISSUE THREAD

**Issue by maHu5** [recharts/recharts#3326]
i need a  onResize callback prop in ResponsiveContainer to get informed, if the Size of the component changes. 
With this feature i get the ability to adjust my Charts.
Like to center the title or adjust x-axis.

`export interface Props {`
`...`
`   onResize?: (size: { containerWidth: number; containerHeight: number }) => void;`
`}`

**Comment by nikolasrieble** [comment]
In the meantime, we achieved the same functionality, by using https://www.npmjs.com/package/@rehooks/component-size

on the ref that we pass to the ResponsiveContainer. 
Note that we only got this to work correctly with a debounce={1} and height="99%".

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/pull/3361

**Comment by maHu5** [comment]
Thank you very much 👍 :)

**Comment by nikolasrieble** [comment]
@maHu5 Thank you for filing this issue! You made a great suggestion and your input helped us find a valuable improvement. 🚀 If you have any more ideas, let us know.

**Comment by ckifer** [comment]
Will be released in next minor version

**Comment by ckifer** [comment]
Released in 2.5!
