### ISSUE TITLE
want to hide the tooltip unit

### ISSUE THREAD

**Issue by moeyashi** [recharts/recharts#3330]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Tooltip units can be hidden.

### What does the proposed API look like?
Add hideUnit property in Tooltip, and DefaultTooltipContent can hide unit.

```
<Tooltip hideUnit />
```

**Comment by moeyashi** [comment]
Please assign me

**Comment by ckifer** [comment]
Hi, this is what the formatter function is for. We should't take more props than without decent consideration. Is the reason you need to hide units that can't be solved via the formatter function or a custom tooltip?

**Comment by ckifer** [comment]
Going to close this as answered - please comment back if you have any concerns.

**Comment by moeyashi** [comment]
I want to show a rate with a denominator and a numerator, ex `80% (8/10)`.
I tried to use formatter function, but it showed `80% (8/10)%`.
I can use custom tooltip to solve this, but I think it's overkill.

**Comment by ckifer** [comment]
Hi @moeyashi,

You can accomplish this with Tooltip formatter if you don't specify a `unit`

**Comment by moeyashi** [comment]
Thank you example.
I need unit for YAxis tick and Bar label.
In such a case, it would be convenient to set the unit for the whole and opt out only for the tooltip.

**Comment by ckifer** [comment]
I'll reopen and see what the others think

**Comment by ckifer** [comment]
@nikolasrieble  thoughts?

**Comment by ckifer** [comment]
@Yilun-Sun @proke03 tagging for visibility just to see what you think.

**Comment by proke03** [comment]
How about making the axis tick and labels formattable like the tooltip?

**Comment by ckifer** [comment]
Right, they are in the API currently. The question is do we want to make it easier to remove the unit from the formatter. 

What if we don't append the unit to the end if the formatter function is used? That's a breaking change but it would be clean

**Comment by nikolasrieble** [comment]
That is a good suggestion. Extending the API with another boolean does not seem like a good idea.
Disregarding the unit if a formatter is used makes sense and is an improvement.

**Comment by nikolasrieble** [comment]
Given that this would change existing behaviour, I suggest to consider this for 3.0

**Comment by giorgiveego** [comment]
+1 we should be able to format unit also

**Comment by ckifer** [comment]
`unit` starts as `undefined` and a unit will not get rendered if one isn't specified.

What if the user just uses a the formatter function and doesn't specify a unit. I think that resolves the concern in this issue without requiring knowledge of a "secret handshake" as it were within the API where the `unit` is hidden under certain conditions.

I can do 
```jsx
 <Tooltip formatter={(value: number) => `${value}% (${value * 100}/100)`} />
```

Without a `unit` and get the desired result. 

[![Edit simple-area-chart (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/simple-area-chart-forked-9qxwrr?file=%2Fsrc%2Findex.tsx)

Going to close this with this solution as I think its reasonable. Please comment if there are any huge arguments for hiding the unit when using a formatter function

**Comment by moeyashi** [comment]
@ckifer Thank you! lgtm.
