### ISSUE TITLE
Nothing displayed when data array is empty

### ISSUE THREAD

**Issue by FabioFleitas** [recharts/recharts#334]
Currently nothing gets rendered if `data` is an empty array. Is there a way to have it either display an empty chart or have a chart with a message such as "No data to display"?

**Comment by xile611** [comment]
@FabioFleitas Such empty message could be very different. So It's recommended to write the message yourself, because you can judge whether the data is empty.

**Comment by FabioFleitas** [comment]
Fair enough, but what about nothing rendering when the data array is empty?
Wouldn't it be better to render an empty graph?

**Comment by xile611** [comment]
@FabioFleitas  The problem is that nothing can be rendered.
