### ISSUE TITLE
Can't change the color of the areachart if true or false

### ISSUE THREAD

**Issue by imnotremi** [recharts/recharts#3340]
I can't make the color of the Areachart changing. 

The charts are mapped in an other component. `pricesData` return either true or false for each time the charts is mapped. Depending on whether the chart is true or false, its color should change. I don't understand what I'm doing wrong.

The `picesData` is working because it's return the value, the error should be in the return or in the way i try to change the color. Could you help me please ? 

Here's the code :

```
const ChartComponentM = ({data, pricesData}) => {
        console.log("Price data", pricesData)

        return (
            <div className="place-self-center">
                <AreaChart width={200} height={50} data={data}>

                    <defs>
                        <linearGradient id="colorUv" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="1%" stopColor={pricesData ? "#17ff00": "#ff0000"} stopOpacity={0.8}/>
                        <stop offset="100%" stopColor={pricesData ? "#17ff00": "#ff0000"} stopOpacity={0}/>
                        </linearGradient>
                    </defs>

                    <Area fill="url(#colorUv)" dot={false} type="category" dataKey="prices" stroke="#000" strokeWidth={"1px"} />
                    <XAxis dataKey="date" hide />
                    <YAxis dataKey="prices" hide domain={["auto", "auto"]}/>
                </AreaChart>
            </div>
        )
    }
```

**Comment by ckifer** [comment]
There are some known issues while using gradients. I'll look deeper shortly.

**Comment by ckifer** [comment]
Related issue https://github.com/recharts/recharts/issues/3055#issuecomment-1363669539

Relevant SOF https://stackoverflow.com/questions/73043945/why-does-a-svg-line-disappear-when-i-apply-a-svg-lineargradient/73043947#73043947

**Comment by ckifer** [comment]
Going to close this as stale until some more detail can be added/response is received
