### ISSUE TITLE
Recharts pie chart not rendering properly

### ISSUE THREAD

**Issue by damjanvucina** [recharts/recharts#3345]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/epic-herschel-w6j7se?file=/src/App.js)

### Steps to reproduce
```
const data = [
    {
      name: 'Cash',
      value: 6000,
      percentage: '18%',
      fill: '#3333FF',
    },
    {
      name: 'Pension',
      value: 4000,
      percentage: '25%',
      fill: '#FF9933',
    },
    {
      name: 'Real-state',
      value: 10000,
      percentage: '31%',
      fill: '#FF3333',
    },
    {
      name: 'Business',
      value: 12000,
      percentage: '13%',
      fill: '#00FF00',
    },
  ];

  const renderLabel = useCallback((piePiece) => {
    return piePiece.name;
  }, []);

  return (
    <ResponsiveContainer width={1000} height={1000}>
      <PieChart style={{ cursor: 'pointer' }}>
        <Pie
          dataKey="value"
          data={data}
          label={renderLabel}
          cx="300"
          cy="300"
          outerRadius={200}
          nameKey="name"
        >
          <LabelList
            dy={-3}
            fill="white"
            dataKey="percentage"
            position="inside"
            stroke="none"
          />
        </Pie>
      </PieChart>
    </ResponsiveContainer>
```

### What is expected?
This very code works in the codesandbox(https://codesandbox.io/s/epic-herschel-w6j7se?file=/src/App.js), but in my app it looks like a weird tiny black blob. Any idea what's going on?

### What is actually happening?
A weird little black blob as on this image https://i.stack.imgur.com/yBJbO.png is rendering.

| Environment | Info |
|---|---|
| Recharts | v2.1.16 |
| React | 17.0.2 |
| System | MacOs Monterey |
| Browser | Chrome Version 109.0.5414.119 |

**Comment by ckifer** [comment]
Hmm I have no clue, but it looks like something to do with height and width of containers.

Does it work without `ResponsiveContainer`?
