### ISSUE TITLE
Add arrow to chart

### ISSUE THREAD

**Issue by vaeum** [recharts/recharts#335]
Hello, a use recharts 0.17.1 and how add this arrow to chart. And add growth/decrease label
![ott hub - reporting requirements v1 0 2016-11-10 16-49-36](https://cloud.githubusercontent.com/assets/6481202/20179176/e57e4fd4-a765-11e6-9910-e1343421e973.png)

**Comment by xile611** [comment]
@vaeum 

You can check [this demo](http://jsfiddle.net/tbs7f59s/) for detail.
