### ISSUE TITLE
Could not find a declaration file for module recharts 2.4.0

### ISSUE THREAD

**Issue by mboor** [recharts/recharts#3353]
**Error Encountered**
> Failed to compile. 
> 
> TS7016: Could not find a declaration file for module 'recharts'.
> Try `npm i --save-dev @types/recharts` if it exists or add a new declaration (.d.ts) file containing `declare module 'recharts';`
> 5 | import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

****When encountered****
during npm run build --if-present

When I force version back to 2.3.2, the npm build runs without error.

Thanks

---

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

**Comment by ckifer** [comment]
Thanks for the report. 

Looking into it

**Comment by ckifer** [comment]
Any other system info?

What TS version, what React version, do you have @types/recharts installed or not (if you do try uninstalling them)

**Comment by ckifer** [comment]
I found it, thank you! Patch release coming shortly

**Comment by mboor** [comment]
Not installing @types/recharts. Using typescript version: 4.9.5, react version: 17.0.2.

**Comment by mboor** [comment]
> I found it, thank you! Patch release coming shortly

Thank you for the quick responses!

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/actions/runs/4139731210 release running...

**Comment by ckifer** [comment]
2.4.1 released - try again and let me know 🙏🏼 

thank you!

**Comment by ckifer** [comment]
Looks good to me now.

Error in 2.4:
![image](https://user-images.githubusercontent.com/25180830/217972546-e5797840-f9c3-4846-a6c6-bb4da695ad1f.png)

After 2.4.1 type check succeeded:
![image](https://user-images.githubusercontent.com/25180830/217972633-d3f43f67-77cb-49d0-9725-94cc96f3011e.png)

**Comment by ckifer** [comment]
Closing as resolved, will open back up if its not resolved for you

**Comment by mboor** [comment]
@ckifer yep, it's building perfectly now. Thank you!
