### ISSUE TITLE
AreaChart leaves white space with intermittent values and connectNulls prop looks awful

### ISSUE THREAD

**Issue by Ian-Bright** [recharts/recharts#3358]
I am having issues with the stacked area chart. There are values in the data that don't exist across the entire time range and they are causing holes to appear in the chart:

<img width="689" alt="Screen Shot 2023-02-11 at 11 47 34 AM" src="https://user-images.githubusercontent.com/66142236/218275853-e9d7b198-5a1f-4f04-80d2-31f7dbb52870.png">

<img width="700" alt="Screen Shot 2023-02-11 at 11 47 26 AM" src="https://user-images.githubusercontent.com/66142236/218275856-8829bbc1-b7a6-4b24-9635-a893d202a905.png">

I tried using the connectNulls prop but the rendering looks horrendous:

<img width="686" alt="Screen Shot 2023-02-11 at 11 51 55 AM" src="https://user-images.githubusercontent.com/66142236/218275892-f71fe479-7613-4973-82a5-ed8d9434e8e9.png">

<img width="689" alt="Screen Shot 2023-02-11 at 11 52 02 AM" src="https://user-images.githubusercontent.com/66142236/218275895-2b8df211-e8fa-4875-8120-0686422842e3.png">

Any clue how this can be corrected?

**Comment by nikolasrieble** [comment]
The approach that first comes to mind is to preprocess the data and fill in the gaps with whatever logic you see fit before passing it to recharts. 

Independently, this seems to be a bug with the behaviour of the stacked AreaChart and connectNulls.

It would greatly help us, if you could provide a toy dataset (i.e. as few data points as possible) and some code to reproduce this issue.

**Comment by ckifer** [comment]
+1 to the above, a codesandbox would be awesome

**Comment by nikolasrieble** [comment]
Released a fix with https://github.com/recharts/recharts/releases/tag/v2.10
