### ISSUE TITLE
Can not view recharts website

### ISSUE THREAD

**Issue by hootbah** [recharts/recharts#336]
There seems to be an issue on the recharts website.
When viewing the page at http://recharts.org

The error is: Failed to load resource: the server responded with a status of 404 (Not Found) http://recharts.org/vendors.js

**Comment by LoriKarikari** [comment]
Same here can't access the website

**Comment by joyguy55** [comment]
Dido

**Comment by sburns** [comment]
For the record you can clone [the repo](https://github.com/recharts/recharts.org) and host it locally.

**Comment by nwhitmont** [comment]
The Website is Down!

**Comment by nwhitmont** [comment]
@arcthur @hootbah @LoriKarikari @joyguy55 @sburns  Looks like CloudFlare issue, could be down 24-48hrs...

**Comment by arcthur** [comment]
thank you for @nwhitmont . It's true that the website will down 48h.
you could pull down the code from recharts/recharts.org, and `npm install`, the `npm run start`. That will start the local host.

**Comment by andremuller** [comment]
The vendor.js file is throwing a 404.

**Comment by xile611** [comment]
Fixed.

**Comment by nwhitmont** [comment]
Thank you @arcthur & @xile611 for the quick response!
