### ISSUE TITLE
OnClick is not working in customised legend of line chart but working for barchart 

### ISSUE THREAD

**Issue by rahuloo5** [recharts/recharts#3363]
## Do you want to request a feature or report a bug?
Bug: onClick is not working in customised legend of line chart

## What is the current behavior?
 It is not firing when we use onClick event.
## What is the expected behavior?
OnClick will work when we click on legend

**Comment by ckifer** [comment]
Can you please make a reproduction using codesandbox?

**Comment by ckifer** [comment]
Going to close this as stale until some more detail can be added/response is received
