### ISSUE TITLE
Highlight & Zoom Broken in v2.4

### ISSUE THREAD

**Issue by swively** [recharts/recharts#3369]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://recharts.org/en-US/examples/HighlightAndZoomLineChart](https://recharts.org/en-US/examples/HighlightAndZoomLineChart)

### Steps to reproduce
Check out the recharts.org example page for Highlight and Zoom Line Chart, its broken there as well.
Once you zoom in any amount, all inner data points are no longer highlightable (tooltip or click), only the first and last data points, so you can no longer interact with the charts and tooltips are broken

### What is expected?
You should be able to further zoom, as well as see a tooltip for each datapoint in the frame.

### What is actually happening?
All inner datapoints are no longer accessible

| Environment | Info |
|---|---|
| Recharts | v2.4.1 |
| React | 18.2 |
| System | OSX |
| Browser | Chrome |

**Comment by ckifer** [comment]
Thanks for the report, I see what you mean - will take a look as soon as I can

**Comment by ckifer** [comment]
Here is a more up to date codesandbox using hooks - https://codesandbox.io/s/highlight-zomm-line-chart-forked-holzzh?file=/src/App.tsx

Same behavior though

**Comment by ckifer** [comment]
Added an example in the storybook here - https://master--63da8268a0da9970db6992aa.chromatic.com/?path=/story/examples-linechart-highlightandzoom--highlight-and-zoom

Will use this to debug (@Yilun-Sun @nikolasrieble @proke03 also feel free to use this to debug if you want to help before I can get around to it)

**Comment by ckifer** [comment]
Somewhere after https://github.com/recharts/recharts/commit/d8ea0c8a9203779d388a4de43fbc74901c8491a3 and before https://github.com/recharts/recharts/commit/322c4b6b8a3a8d678ed0d901af5269c9fbc67674

**Comment by ckifer** [comment]
Between https://github.com/recharts/recharts/commit/2732d71809a866338750fe64396a0e86d49c7b9e and https://github.com/recharts/recharts/commit/322c4b6b8a3a8d678ed0d901af5269c9fbc67674

**Comment by ckifer** [comment]
Winner winner I believe https://github.com/recharts/recharts/commit/642dd59f802adf05f0b65ad878bbf4bd9b29ee16

or PR 

https://github.com/recharts/recharts/pull/3293

**Comment by ckifer** [comment]
`tooltipTicks` go from 20 to 2 here https://github.com/recharts/recharts/blob/62bdd660529ec077c89922da97e22041cc4e76ed/src/chart/generateCategoricalChart.tsx#L263 after zoom 

![image](https://user-images.githubusercontent.com/25180830/218931651-f3114e7c-7938-4acc-a0e1-4de697844c06.png)
Makes sense why the issue occurs

**Comment by ckifer** [comment]
if `allowDataOverflow` is set to false for the `XAxis` only then the Y axis behaves as it should. Issue is with tick calculation when `allowDataOverflow` is true on the `XAxis`

This is even called out in the PR desc

>We could short-circuit the domain creation in one scenario:
>
> * allowDataOverflow is set to true
> * the specified domain (start AND end) was provided via props with two values

Action item will be to look at the PR diff to figure out why exactly this isn't behaving as it should. Probably a larger issue :/

**Comment by ckifer** [comment]
Released 2.4.2 - check out https://codesandbox.io/s/highlight-zomm-line-chart-forked-holzzh?file=/src/App.tsx and let me know if you have any other issues.

Thanks @swively
