### ISSUE TITLE
Prop `domain` is not default `[0, "auto"]` for `<YAxis />`

### ISSUE THREAD

**Issue by nyanyani** [recharts/recharts#3377]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/simple-line-chart-kec3v)

### Steps to reproduce
1. Choose package `recharts@^2.4.0`
2. Set `<YAxis tickCount={2} />`
![2_2_4_0](https://user-images.githubusercontent.com/11475482/219349537-7ed67e91-2121-41dd-9264-958fb9b6fc48.png)
3. Set `<YAxis tickCount={2} domain={[0, "auto"]}/>`
![2_domain_2_4_0](https://user-images.githubusercontent.com/11475482/219349647-61ecbe27-7289-45a4-830a-91332c689659.png)

### What is expected?
![2_2_3_2](https://user-images.githubusercontent.com/11475482/219349880-c5e5efaf-99bb-40a4-8a2e-4a7e920f6179.png)
Should behave like [document](https://recharts.org/en-US/api/YAxis#domain) said .

### What is actually happening?
Omitted prop `domain` brokes `tickCount` since v2.4.0.

| Environment | Info |
|---|---|
| Recharts | v2.4.2 |
| React | 17.0 |
| System | Windows |
| Browser | Chrome |

**Comment by ckifer** [comment]
Found the fix.. will address but going to take more time to add tests

**Comment by ckifer** [comment]
@nyanyani released fix in patch 2.4.3. Thanks for the report!
