### ISSUE TITLE
Problem using Recharts as UMD lib

### ISSUE THREAD

**Issue by git-toni** [recharts/recharts#338]
Hi,

While loading Recharts via `https://unpkg.com/recharts@0.17.1/umd/Recharts.js`  , on page load I encounter these issues:

```js
Uncaught TypeError: Cannot read property 'TransitionGroup' of undefined`
Uncaught TypeError: Cannot read property 'LineChart' of undefine
```

This is webpack's `externals` entry for recharts:
```js
externals: {
...
    recharts: {
      commonjs: 'recharts',
      commonjs2: 'recharts',
      amd: 'recharts',
      root: 'Recharts'
    }
...
}
```

Any ideas?

**Comment by xile611** [comment]
@git-toni Check the jsfiddle [demo](http://jsfiddle.net/x1yoboc7/48/) for detail. You should reference 
 some others js files.

![image](https://cloud.githubusercontent.com/assets/6111424/20218065/c3815a2c-a85d-11e6-98af-0ab4532d402f.png)
