### ISSUE TITLE
cannot assign ref to Legend component

### ISSUE THREAD

**Issue by sKopheK** [recharts/recharts#3381]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-k322t6)

### Steps to reproduce
assing ref to Legend

### What is expected?
ref is assigned, Legend element accessible via ref.current 

### What is actually happening?
ref.current is always null

| Environment | Info |
|---|---|
| Recharts | v2.4.3 |
| React | 18.2.0 |
| System | W11Home 10.0.22000 Build 22000 |
| Browser | indifferent |

---
i'm trying to get legend height so i can resize it's container so it always fits no matter what content is there. as ResponsiveContainer is doing quite opposite of what I'd expected (should be responsive according it's content, not according parent). if there's another solution to the actually responsive graph container, i'll be happy with that as well :)
also, i cannot assign ref created by `useRef<Legend>(null)` to the component, TS cries like a baby when i do that, same for `<Pie>` and other components maybe as well

**Comment by nikolasrieble** [comment]
It seems that indeed the ref is not used or passed anywhere for the Legend.

As this seemingly never worked, I am suggesting this as an enhancement.

**Comment by HHongSeungWoo** [comment]
It seems like this issue has been resolved in the latest version.

**Comment by ckifer** [comment]
yeah looks good to me, not really sure how this was an issue in 2023 since the change looks fixed ~3 years ago

[this sandbox](https://codesandbox.io/p/sandbox/recharts-issue-template-forked-6nthls?file=%2Fsrc%2Findex.js) works fine though

Going to close
