### ISSUE TITLE
Storybook: Create stories for the Bar component

### ISSUE THREAD

**Issue by nikolasrieble** [recharts/recharts#3382]
For the Line component we have a story that does not even use a chart, but shows the Line all alone within a Surface.

Lets follow the same pattern for the Bar

Acceptance criteria: 
- storybook/stories/API/cartesian/Bar.stories.tsx

Create stories for:
- Simple
- Stacked/Grouped Bars (exposing stackID as controls for two bar groups)
- Bar with Labels
- Bar with Background
- Bar with custom shape
- Bar with animation

Each story should only expose the minimal controls relevant to the story

**Comment by Yilun-Sun** [comment]
Closes #3435
