### ISSUE TITLE
Storybook: Create stories for the Area component 

### ISSUE THREAD

**Issue by nikolasrieble** [recharts/recharts#3383]
For the Line component we have a story that does not even use a chart, but shows the Line all alone within a Surface.

Lets follow the same pattern for the Area

Acceptance criteria:

storybook/stories/API/cartesian/Area.stories.tsx
Create stories for:
- Simple (exposing as control: dataset and dataKey)
- Type (exposing as control: type, baseline, connectNulls, stroke, strokeWidth)
- Stacked Area (exposing stackID as controls for two area groups)
- Area with custom dot
- Area with label
- Area with fillGradient
- Area with animation (exposing all animation controls)

Each story should only expose the minimal controls relevant to the story

**Comment by Yilun-Sun** [comment]
Closes #3398
