### ISSUE TITLE
Composed Chart Overflow

### ISSUE THREAD

**Issue by thuynh** [recharts/recharts#3389]
We currently have an compose chart component but it seems they're overflow. Was wondering if there's a fix for this or is this a known bug?

![Screen Shot 2023-02-21 at 7 21 34 PM](https://user-images.githubusercontent.com/28160/220496286-bdecbda3-f5be-41ae-a23d-b22be8d309d4.png)

**Comment by ckifer** [comment]
Can you make a codesandbox? There are settings that allow overflow and settings that prevent it - it's hard to know or help without knowing how your setup looks. 

Thanks!

**Comment by thuynh** [comment]
@ckifer I can't get it to run properly but here's the link https://codesandbox.io/s/long-bird-48ccfo. I think the issue here is the value on the left yAxis needs to be increased to accommodate the very tall line chart. Is there a way to tell it to use values from the highest data point to create the yAxis?

**Comment by thuynh** [comment]
@ckifer I see where the issue here is. Those data points were represented as strings that's why it wasn't able to properly create those yAxis.

**Comment by ckifer** [comment]
For the sandbox you just needed to set a height.

But yeah it won't calculate the right domain if you're using string values. You can set the domain on the axis using
`domain={['dataMin', 'dataMax']}`

**Comment by thuynh** [comment]
Got it! thank you!
