### ISSUE TITLE
Custom Module To Display Results/Values

### ISSUE THREAD

**Issue by um-cle** [recharts/recharts#3395]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Allows a custom component to display the dynamic data as the cursor is moved. For my specific usage, I want to have a stacked area chart that has a tooltip moving along with the cursor showing the month and year of the x axis with a component below the chart displaying the values of the 3 area charts.

![Screenshot 2023-02-22 at 16 28 52](https://user-images.githubusercontent.com/121683600/220763630-3b986d4d-cd21-4d1b-be68-12286e61e39d.png)

### What does the proposed API look like?
It could be a simple component with the payload data passed in so that we can display the dynamic data as the cursor is moving around.

**Comment by um-cle** [comment]
@ckifer I would love to but didn't know how. How can I access the dynamic data outside of Recharts? Those 3 amounts at the bottom would need to change to show the values at the cursor.

**Comment by ckifer** [comment]
Try this out

https://codesandbox.io/s/stacked-area-tooltip-data-p4x8fh?file=/src/App.tsx

**Comment by um-cle** [comment]
That is just what I'm looking for. Thank you so much! I was trying to use the Tooltip to set the state, but because it's being rendered it put the setState in an infinite loop.

**Comment by ckifer** [comment]
Glad to hear it.

Yeah that's something that needs fixed for sure. Since this issue is specific and that issue is more general I will close this and open a new issue for the infinite loop problem.

Thanks @um-cle
