### ISSUE TITLE
ReferenceLine getting rendered out of the domain

### ISSUE THREAD

**Issue by vanthiyathevan** [recharts/recharts#34]
When a reference line is present, the yaxis domain should include the `ReferenceLine` value. Right now the reference line get rendered out side the domain. See the screenshot where the goal value is at 10%

![image](https://cloud.githubusercontent.com/assets/1296183/13154813/ccd5f142-d648-11e5-9086-2f75304e5857.png)

**Comment by xile611** [comment]
Thanks!
This bug related to two problems:
1. A warning should be given when the value of `ReferenceLine` is not within the domain of axis. 
2. The domain of a numeric types axis which has positive values should be minimum 0 by default. 

So I plan to change the default value of domain in `XAxis` and `YAxis` to `[0, 'auto']`. If the domain is specified as `['dataMin', 'dataMax']`, than the max of the axis is the maximum value of the input data, and  the min of the axis is the minimum value of the input data. And if the domain is specified as `['auto', 'auto']`, comprehensible scale ticks will be calculated, and the final domain of axis is generated by the ticks.

**Comment by vanthiyathevan** [comment]
If I may suggest to add an option if you are using `[auto, auto ]`, have a bool property like alwaysShowReferenceLine

**Comment by xile611** [comment]
Good idea! A `alwaysShow` props can be added to `ReferenceLine`.

**Comment by vanthiyathevan** [comment]
Also it shouldn't render if its out of the domain.

**Comment by xile611** [comment]
Yeah. Of course.

**Comment by xile611** [comment]
Fixed in v0.8.0

**Comment by peterbartos** [comment]
Updated fix at the time writing this comment:

> The alwaysShow prop is deprecated. Please use `ifOverflow="extendDomain"` instead.
