### ISSUE TITLE
Recharts crashes Chrome (when redrawing on props change?)

### ISSUE THREAD

**Issue by elnygren** [recharts/recharts#341]
**Note**: Previous discussion at https://github.com/recharts/recharts/issues/265, however, the tooltip problem seems fixed. Some background in: https://github.com/recharts/recharts/issues/265#issuecomment-259397616.

Quickly changing a recharts graph's input data making recharts redraw the graph seems to crash Chrome due to an unknown (SVG?) bug. This seems to happen easier when there are a lot of data points involved.

**Steps to reproduce:**
1. setup & run https://github.com/elnygren/recharts-crash-test
2. click the "monthly", "weekly" and "daily" toggles until you see Chrome's "Aw, Snap!" page.

<hr>

A screenshot of my use case (a bit different from the repo above): 

![Image of Dashboardh](https://i.imgur.com/XNoFcb3.png)

Clicking daily will almost surely crash the current tab as there are a lot of data points.

MacOS 10.12.1
Chome Version 54.0.2840.87 (64-bit)

**Comment by xile611** [comment]
@elnygren 

I try to create a jsfiddle [demo](http://jsfiddle.net/32ekyL48/) similar to your demo. And switch different datas quickly, it never crash in chrome. Can you try ?

**Comment by elnygren** [comment]
@xile611 I did try to make the jsfiddle you provided earlier crash but was not successful :/

However, I wouldn't prefer jsfiddle over an actual real-life project when testing this library. Something's making Chrome crash in my demo project and it might have something to do with how Webpack bundles your library (in production, not in hot reload/dev mode).

Anyway, I'd really like to use recharts so I will let you know immediately if I figure out what's happening.

**Comment by xile611** [comment]
Yeah, jsfiddle is the simplest environment. I use it to confirm whether the crash  happens online.

And I found it's really strange. I clone your project and run it, chrome crash every time when I click *Daily*. But after I restart my mac, the crash never happen.

**Comment by elnygren** [comment]
@xile611 I can confirm too that restart solved this problem - did you ever find a way to get the crash happen again after restart?

Would still be nice to find out the underlying reason as I can't really tell all chrome users to restart their macbook before using the site :p 

It might be though that only a small portion of Chrome users are actually affected... hard to say.

**Comment by xile611** [comment]
@elnygren It's hard to find the real reason.

**Comment by xile611** [comment]
@elnygren I find that my chrome was updated to the version 54.0.2840.98 (64-bit) after restart my mac. Maybe some bug of old chrome cause the crash.
