### ISSUE TITLE
Please update `react-resize-detector` to 8.x

### ISSUE THREAD

**Issue by Semigradsky** [recharts/recharts#3410]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Have one version of `react-resize-detector` in bundle.

### What does the proposed API look like?
See breaking changes: https://github.com/maslianok/react-resize-detector/releases/tag/v8.0.0

**Comment by ckifer** [comment]
Released in 2.5!
