### ISSUE TITLE
piechart tooltip some are downward and other is upward

### ISSUE THREAD

**Issue by linaffilomania** [recharts/recharts#3414]
hi i'm doing piechart with tooltip and in the 2 top pictures its look good. but in the bottom picture the tooltip goes upward and not upward like the other 2 pictures. can we fix this ?
![image](https://user-images.githubusercontent.com/122976282/221870329-15e17e37-0a64-4d3b-8d3a-70490087f1e1.png)

**Comment by ckifer** [comment]
Hi! The tooltip needs to stay generally within the area of the SVG so once the Tooltip content gets larger it has to expand in both directions in order to do that

**Comment by linaffilomania** [comment]
> Hi! The tooltip needs to stay generally within the area of the SVG so once the Tooltip content gets larger it has to expand in both directions in order to do that

I can make it start below the number like the two in the pictures above?And expand down and not up

**Comment by ckifer** [comment]
This customization isn't currently easily possible. 

You could try to see if `allowEscapeViewbox` helps your case.

`allowEscapeViewBox={{ x: true, y: true }}`

**Comment by linaffilomania** [comment]
its work, thank you :)
