### ISSUE TITLE
StoryBook : Adding Tooltip customisation examples

### ISSUE THREAD

**Issue by CoffeeGeek101** [recharts/recharts#3415]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
- The storybook of reCharts currently do not have any story related to tooltip customisation. 
- The default tooltip can be a problem for the UI requirement, if user can't able to customise it accordingly to their needs.
- The default tooltip can also be too big for small charts in given use cases.
- Adding the tooltip customisation on the storybook of reCharts' API section, can make it easy and accessible to the end user to use the tooltip APIs more freely.

### What does the proposed feature look like?
The **Tooltip Customisation** to added within the **API** section of the storybook.
The folder structure can be like this :
```
  API
     - Tooltip Customisation
                 -Single DataKey Value
                 -Multiple DataKey Value
   ```
- The code for single **DataKey** value tooltip can be found here for reference : https://codesandbox.io/s/pensive-gould-dcojxz?file=/src/App.js
- The code for multiple **DataKey** value tooltip can be found here for reference: https://codesandbox.io/s/unruffled-napier-pzbdld?file=/src/PerformanceBreakdownChart.js

**Comment by ckifer** [comment]
Hey @CoffeeGeek101  (nice username btw, relatable)

Thanks for raising this! The storybook is currently a work in progress as we move existing documentation there.

Feel free to raise a PR if you'd like to contribute these stories!

**Comment by ckifer** [comment]
I'd recommend just making making the folder structure like so

```
Examples
   - Tooltip
         - Custom Tooltip
```

Personally I don't think there is much need for more than one example using a custom tooltip. Once the structure if is in place, users should be able to refactor example code based on their specific use-case. Not against leaning towards the side more examples though.

CC @nikolasrieble  who is handling a lot for storybook organization

**Comment by nikolasrieble** [comment]
We collected our thoughts for storybook organisation in the [README](https://github.com/recharts/recharts/blob/master/storybook/README.md) for reference, best start there. 

Ideally we would first want to have a set of stories for the Tooltip in the API folder, following the best practice there. 

The Example section is supposed to be used for extraordinary usage and combination of components.

Thus if you would like to write stories for the Tooltip, that would be very appreciated. Please start with the API stories following the best practice example of the Line component https://github.com/recharts/recharts/blob/master/storybook/stories/API/cartesian/Line.stories.tsx

**Comment by CoffeeGeek101** [comment]
@nikolasrieble I have updated the issue, and moved it to API section. I'll happy to be working on the PR for this, currently starting with the best practices example you have mentioned, will be updating along the way.

**Comment by CoffeeGeek101** [comment]
Closing this issue, as the Tooltip and it's customisation has been added to the storybook.
