### ISSUE TITLE
Allow `<Bar />` components to be wrapped in `<Customized />`

### ISSUE THREAD

**Issue by justinsunho** [recharts/recharts#3416]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Because recharts components cannot [be wrapped ](https://github.com/recharts/recharts/issues/2788)in a custom component on its own, `<Customized component={CustomComponent} />` is used as a workaround. I would like to be able to customize my `<Bar />` components (and other higher level components) in this manner.
Right now it is only possible to customize more primitive components like `<Rectangle />` or `<Line />`.

### What does the proposed API look like?
Example: 
```
const CustomizedBar = (props) => {
     ...

     return <Bar {...props} />
}

<Customized component={CustomizedBar} ... />
```

**Comment by ckifer** [comment]
Does this example solve your case? https://recharts.org/en-US/examples/CustomizedRectangleContent

Rectangle is primitive yes, but you're able to accomplish a bar without too much work

**Comment by ckifer** [comment]
Going to close this as stale, feel free to comment back to continue discussion
