### ISSUE TITLE
Feature Request: Default tooltip has no formatting for data key label

### ISSUE THREAD

**Issue by RoarkeRandall** [recharts/recharts#342]
The default tooltip is very helpful and meets the minimum features for most people. It has a labelFormatter option and a formatter for the value. It's unfortunately missing a formatter for the axis name. An example:

Lets say we're measuring leads per day. Our object may be:

`{
     leads: 42,
     day: '2016-11-14'
}`

If day is the x axis, and leads is the y axis, we can format '2016-11-14' with the labelFormatter prop and we can format 42 with the formatter prop. The resulting tool tip will be `leads : formatter(42)`, meaning you cannot format `leads :`. This is a little annoying as the backend business term may be different to what the users use. Also, following JS conventions, properties are lower camel case. 

Work around is to use a custom tooltip, but that's a bit annoying considering I just want to uppercase the first letter.

**Comment by xile611** [comment]
@RoarkeRandall `Line`, `Area`, `Bar`, `Scatter` , etc, have a props `name`, If you have specified props `name`, the `name` will be used to display in `Legend` and `Tooltip`.

[Document of Area](http://recharts.org/api#Area)
[Document of Line](http://recharts.org/api#Line)

...

**Comment by ktabori** [comment]
I have the same problem and I don't think that name prop solve this, because I can only have static content in `name` but just like @RoarkeRandall I would like to format my dynamic content, before I set it in as a label.
