### ISSUE TITLE
Storybook: YAxis - ArgsTable

### ISSUE THREAD

**Issue by nikolasrieble** [recharts/recharts#3426]
Following the example set by Line.stories.tsx

- Add descriptions and correct types to the ArgTable 
- Make sure to reuse shared descriptions (see `storybook/stories/API/props/Legend.ts`

Acceptance critera: 
- All descriptions and types of the properties as currently exist in https://recharts.org/en-US/api/YAxis are found in the Storybook arg table of the YAxis or the CartesianAxis.
- All props are grouped in categories as done for Line.stories.tsx
- Only the properties that specific to YAxis are found in the ArgsTable. Additionally the doc links to the CartesianAxis doc which contains documentation for all props shared across Axes.

**Comment by wao218** [comment]
@nikolasrieble I'd like to take this over
