### ISSUE TITLE
Charts within containers transformed through CSS - Broken tooltip behaviour

### ISSUE THREAD

**Issue by petii** [recharts/recharts#3441]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-ei8d2s?file=/src/index.js)

### Steps to reproduce
Wrap a chart in a div with `style={{transform: 'scale(0.5)}}`.
Hover over the chart to observe tooltip behaviour.

### What is expected?
The tooltip hover follows the mouse pointer.

### What is actually happening?
The tooltip hover does not appear all the time or shows up at the wrong data point.

| Environment | Info |
|---|---|
| Recharts | v2.4.3 |
| React | ^16.14.0 |
| System | - |
| Browser | - |

---
Some initial exploration revealed that the mouse events' calculated `chartX` and `chartY` are transformed according to the scale, but the chart SVG's coordinate system is still using the original sizes.

**Comment by petii** [comment]
I also have a branch on my fork reproducing the error https://github.com/petii/recharts/tree/scaled.container

**Comment by HHongSeungWoo** [comment]
I cannot reproduce it in version 2.9.0.

**Comment by ckifer** [comment]
Yeah this works now as of https://github.com/recharts/recharts/pull/3748
