### ISSUE TITLE
RadarChart. <g  class="recharts-polar-grid-concentric">. <path> render order for styling possibilities (fill and stroke for each figures, not only for last one)

### ISSUE THREAD

**Issue by antoivanov** [recharts/recharts#3442]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This brings possibility to style individually polar grid figures by passing colors to stroke and fill properties. At the moment last biggest figure of group <g  class="recharts-polar-grid-concentric"> cover smaller ones and prevent see them because of it size and fill color.
From:
![image](https://user-images.githubusercontent.com/122439215/223381667-253b3ba3-d8d2-47f4-8beb-5f73636cbcb0.png)
To:
![image](https://user-images.githubusercontent.com/122439215/223381433-5a697846-42d4-4f0b-a03d-a285ff7cc092.png)

### What does the proposed API look like?
Smth like this:
const parent = document.querySelector('.recharts-polar-grid-concentric') as HTMLElement
      Array.from(parent.childNodes)
        .reverse()
        .forEach((el: HTMLElement) => parent.appendChild(el)) 
    }, 0)

**Comment by ckifer** [comment]
Going to close this as stale until some more detail can be added/response is received
