### ISSUE TITLE
Tooltip flickering when hover the mouse on the bottom of StackedBarChart.

### ISSUE THREAD

**Issue by JinHe-PerkinElmer** [recharts/recharts#3444]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stacked-bar-chart-forked-in8woq?file=/src/App.tsx)

### Steps to reproduce
If there are multiple bars, scale the height of the browser to a certain height, and when the mouse slides in from the bottom of the chart, the tooltip will flicker and hide

### What is expected?
Properly display tooltips when mouse hover.

### What is actually happening?
Sorry that In the demo above, It's not easy to reproduce the problem. But basically it must appear on our own website. It seems that there is a problem with the positioning calculation of the tooltip. The height of the tooltip is greater than the height of the chart, and a vertical scroll bar appears on the page, and then disappears, and the tooltip also disappears at the same time

| Environment | Info |
|---|---|
| Recharts | v2.4.3 |
| React | 16.9.0 |
| System | Win10 |
| Browser | Chrome Version 110.0.5481.178 (Official Build) (64-bit) |

**Comment by JinHe-PerkinElmer** [comment]
> @JinHe-PerkinElmer what do you mean by "scale the height of the browser to a certain height"? This example has a fixed height

It means to adjust the size of the browser through the "restore down" button in the upper right corner of the browser. And I have a question: I noticed that when it is adjusted to a certain size, the tooltip is displayed, and the **page scroll bar is displayed first and then hidden**. Why is there such an effect? In my question, when the page scroll bar disappears, the tooltip also disappears. So I think it is possible not to set the hidden effect？

**Comment by ckifer** [comment]
@JinHe-PerkinElmer were you able to resolve this?

**Comment by JinHe-PerkinElmer** [comment]
> @JinHe-PerkinElmer were you able to resolve this?

Sorry, this problem seems to be caused by the fact that when the package was updated to the latest version, version 1.8.5 was used before, and the local code was not repackaged. When I rerun the code today, everything is normal.

**Comment by ckifer** [comment]
Cool, thanks!
