### ISSUE TITLE
Storybook: Recharts Style in Storybook.

### ISSUE THREAD

**Issue by nikolasrieble** [recharts/recharts#3446]
The storybook should fit in better with the website. https://recharts.org/en-US/

Change it such that it better fits with the brand.
This issues does not have explicit acceptance criteria but might require multiple smaller changes. 

https://storybook.js.org/docs/react/configure/theming

**Comment by keshavjha018** [comment]
Hi, can you please elaborate on the issue, I want to work on this.

**Comment by nikolasrieble** [comment]
Great @keshavjha018, help would be very appreciated! 

Acceptance critera: 

(1) Create a storybook theme for the recharts storybook, as described in https://storybook.js.org/docs/react/configure/theming#create-a-theme-quickstart

(2) Use the theme in storybook

(3) Adapt the theme to resemble the recharts website theme / style, see 
https://github.com/recharts/recharts.org

Does that make sense?

**Comment by ayushjnv1** [comment]
can pick this issue?

**Comment by nikolasrieble** [comment]
@ayushjnv1 Sure, please do pick it. There is no existing PR / work done here.

**Comment by gurungsandesh** [comment]
Hello, any one doing this issue?

**Comment by gurungsandesh** [comment]
If not can i do it? @nikolasrieble

**Comment by ckifer** [comment]
No one has done any work on it - feel free

**Comment by nikolasrieble** [comment]
@gurungsandesh So far people only asked whether this is free. If you want it, please do submit a PR. Nobody is working on this to my best knowledge. I would be very happy to review. Let me know if I can help.

**Comment by csdiehl** [comment]
Hi @nikolasrieble I'm new to contributing to this library, but this seems like a good open first issue. I can take it if nobody has addressed already?

**Comment by ckifer** [comment]
No one has worked on it @csdiehl - all you!

**Comment by csdiehl** [comment]
sounds good - i'll take it on then
