### ISSUE TITLE
Empty Chart Display Possible?

### ISSUE THREAD

**Issue by FabioFleitas** [recharts/recharts#345]
Is it possible to display an empty chart (such as [this](http://i.stack.imgur.com/9ImRB.png)) with recharts?

**Comment by xile611** [comment]
@FabioFleitas When the data is empty, we have no information to show in the chart. When the data is not empty, we can show a empty chart like [this demo](http://jsfiddle.net/qh81naqm/).

**Comment by FabioFleitas** [comment]
Thanks for the answer @xile611. One more quick follow-up question: is it possible to display the Y-Axis range when the Lines are not rendered?

**Comment by xile611** [comment]
@FabioFleitas Only when you specify the `dataKey` of `YAxis` like [this demo](http://jsfiddle.net/qh81naqm/1/).
Otherwise `YAxis` doesn't know what to show, or just some fixed numbers.

**Comment by FabioFleitas** [comment]
@xile611 Perfect! That's exactly what I was looking for. Thank you

**Comment by LACoderDeBH** [comment]
I made a const array of dummy data for the x-axis const dummyData = [{value: ''}, {value: ''}, {value: ''},]  to conditionally render an empty graph when when my relevant data is empty. That worked for me!
