### ISSUE TITLE
treemap not showing all labels

### ISSUE THREAD

**Issue by 0Lucifer0** [recharts/recharts#3450]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://recharts.org/en-US/examples/SimpleTreemap](https://recharts.org/en-US/examples/SimpleTreemap)

### Steps to reproduce
create a treemap and notice only some labels show up or just visit the example page https://recharts.org/en-US/examples/SimpleTreemap

### What is expected?
to display all labels 

### What is actually happening?
it only display some of the labels

| Environment | Info |
|---|---|
| Recharts | v2.4.3 |
| React | 18 |
| System | node |
| Browser | brave |

**Comment by ckifer** [comment]
Hey @0Lucifer0 

This is intentional - the labels that are hidden cannot fit in the treemap boxes that are created. There is a measurement of the text and measurement of the box - if the text doesn't fit it isn't displayed.

**Comment by 0Lucifer0** [comment]
is there anyway to force it to display then ? In my case it does not ellipse at all and i'm pretty sure their is a bit of placeholder (padding) I can afford to overflow

**Comment by ckifer** [comment]
What I meant was that other libraries have an ellipse functionality but the recharts tree map does not yet. 

As far as I know there isn't a way out of the box but if you dig there may be a way to hack it

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/blob/master/src/chart/Treemap.tsx#L584-L591 for reference - doesn't look like there is currently a way to hack around that

**Comment by ckifer** [comment]
@0Lucifer0 I'm going to close this issue. If you want, please open a new issue as a feature request to allow for showing all/custom labels
