### ISSUE TITLE
Module not found: Error: Can't resolve 'recharts' in '/vercel/path0/src/page'

### ISSUE THREAD

**Issue by kolaade271** [recharts/recharts#3453]
Using recharts failed on vercel 
Module not found: Error: Can't resolve 'recharts' in '/vercel/path0/src/page'

**Comment by ckifer** [comment]
Hi,

I need some more information to be able to help. I can't gather anything except that this seems like a deployment issue? 

Can you give recharts version, react version, next version, and where this fails? Anything more than this helps

**Comment by kolaade271** [comment]
It is version    "recharts": "^2.4.3",
"react": "^18.2.0",




19:15:12.879 | Failed to compile.
19:15:12.879 |  
19:15:12.879 | Module not found: Error: Can't resolve 'recharts' in '/vercel/path0/src/page'
19:15:12.880 |  
19:15:12.880 |  
19:15:12.910 | Error: Command "react-scripts build" exited with 1
19:15:13.250 | BUILD_FAILED: Command "react-scripts build" exited with 1

**Comment by kolaade271** [comment]
It work on aws amplify but failed on vercel  
https://vercel.com/guides/how-do-i-resolve-a-module-not-found-error

**Comment by ckifer** [comment]
This doesn't really seem like a recharts issue as much as a vercel setup issue. Seems like your recharts dependency is not where vercel expects it

**Comment by kolaade271** [comment]
Thanks for your support,
I have resolved this by installing the package on vercel command.

**Comment by kolaade271** [comment]
solved
