### ISSUE TITLE
RadialBar label

### ISSUE THREAD

**Issue by AshworthHub** [recharts/recharts#346]
The documentation says the label accepts a function but I can't get it to run.  

I created a solid circle chart w/ a value in the middle based off the circle chart; to create the center label I used label={this.renderCustomizedLabel} off Pie. I then tried the same with RadialBar and the function doesn't get called.  

Any ideas?

```
renderCustomizedLabel({cx, cy, midAngle, innerRadius, outerRadius, value, name, index}){
   	const radius = innerRadius + (outerRadius - innerRadius) * 0.5;
    const RADIANx = Math.PI / 360;
    const RADIANy = Math.PI / 180;
    const x = cx + radius * Math.cos(-midAngle * RADIANx);
    const y = cy + radius * Math.sin(-midAngle * RADIANy);

    return (
      <text
        x={x}
        y={y}
        fill="white"
        textAnchor="middle"
        dominantBaseline="central"
        style={{fontSize: '26pt'}}>
          {value}
      </text>
    );
  };
```

**Comment by xile611** [comment]
@PeteAshworth The label of `RadialBar` was missed.

**Comment by AshworthHub** [comment]
Thanks for pushing fix for the RadialBar; however, I still can't it it to work and now all my charts are no longer rendering custom label.  I attached a version where I use the Pie chart to build a circle with a number in the middle, which with 0.19 it's no longer working.

0.18
![screen shot 2016-11-23 at 7 48 30 am](https://cloud.githubusercontent.com/assets/7296078/20566209/784c4d12-b151-11e6-861a-f4a15d11e81c.png)

0.19
![screen shot 2016-11-23 at 7 47 32 am](https://cloud.githubusercontent.com/assets/7296078/20566595/db4eb656-b152-11e6-87d2-bf7eee243d6c.png)


```
class CircleChart extends Component {
  static defaultProps = {
    data: {
      value: '2.65',
    },
    color: '#60b990',
    tooltip: 'Test | 2.65',
    tooltipY: 0,
  }
  static propTypes = {
    data: PropTypes.shape({
      value: PropTypes.string,
    }),
    color: PropTypes.string
  }

  renderCustomizedLabel = (data) => {
    const value = data.payload.display;
    return (
      <Text
        x="50%"
        y="55%"
        fill="white"
        fontSize="3em"
        textAnchor="middle"
      >
        {value}
      </Text>
    );
  };

  render() {
    const { color, tooltipY } = this.props;
    const { tooltipX } = this.state;
    const tooltipPosition = {
      x: tooltipX,
      y: tooltipY,
    };
    const fixdata = [{
      value: 1,
      display: this.props.data.value,
    }];

    return (
      <ResponsiveContainer>
        <PieChart>
          <Pie
            data={fixdata}
            isAnimationActive={false}
            fill={color}
            strokeWidth={0}
            labelLine={false}
            label={this.renderCustomizedLabel}
          />
        </PieChart>
      </ResponsiveContainer>
    );
  }
}

export default CircleChart;
```

**Comment by AshworthHub** [comment]
Got it working with using text vs Text as the customized label.

**Comment by xile611** [comment]
@AshworthHub Thanks!  `Text` only show when `x` and `y` are number in 19.0. I should fix it.
