### ISSUE TITLE
AreaChartFillByValue used in a loop causes strange "offset" behavior

### ISSUE THREAD

**Issue by RicardoPBarbosa** [recharts/recharts#3461]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-86mivo)

### Steps to reproduce
- Run the reproduction given in codesandbox
- Confirm the wrong positive/negative separation on the 2nd and 3rd chart
- To check that it (might) be because of the loop situation, comment 1 (or 2) of the 3 entries of the "data" constant and see the correct positive/negative separation for the 1st chart.

### What is expected?
Expected each chart component to use the offset calculated on the component mount without interference from other charts on the page

### What is actually happening?
The offset of the consequent charts seems to be affected by the previous one

| Environment | Info |
|---|---|
| Recharts | v2.4.3 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Brave |

**Comment by ckifer** [comment]
Hey there @RicardoPBarbosa 

This makes sense as you are referencing the first `linearGradient` by id in all three of the charts. `id="splitColor"` has no differentiator so chart 2 and three will always reference the first created linearGradient.

https://codesandbox.io/s/recharts-issue-template-forked-5twm3y

Appending your data `id` to the `id` (and references to the id) of the `linearGradient` should fix your issue

**Comment by RicardoPBarbosa** [comment]
Wow thank you! I totally missed that one 🙈

**Comment by ckifer** [comment]
No worries! Glad it wasn't an internal state thing :D
