### ISSUE TITLE
Custom axis tick questions

### ISSUE THREAD

**Issue by Moeface** [recharts/recharts#347]
1. Is it possible to use HTML/React components that are HTML/JSX (i.e. not SVG elements) for custom ticks?
1. Is it possible to pass an object to the tick as the dataKey, rather than just a single key (string/number). I'm hoping to create a custom tick that contains a URL to an image that is rendered and then links to another URL.

Thanks for the great library!

**Comment by xile611** [comment]
@Moeface You should use svg React components, and svg elements can support link too. 

[svg link](https://www.w3.org/TR/SVG/linking.html)

And dataKey should be a string or a number. I don't know why you want to pass an object to the `dataKey`.
I create a simple [demo](http://jsfiddle.net/vLspjuo2/) of svg linking. You can check whether your demand can be filled.

**Comment by Moeface** [comment]
My use case is that I would like to use a link react component that I have created as a custom tick. This component has variations based on props that it receives, In addition to that, I'd like to show an image above each of the buttons.

I'd need to pass an object as the dataKey because in this case, I would need:

- The image URL
- The link URL
- Props that the button (button text, colour, etc)

All of these are within the realm of SVG (though being able to provide a non-SVG component would be ideal), but being locked into using a plain string or a number prevents this.

**Comment by xile611** [comment]
@Moeface As you know,html elements can't be rendered in the svg elements, so we can't support non-SVG component.

**Comment by Moeface** [comment]
Sure, but even if I used SVG to recreate the look of the button, I'm still unable to pass the `href` to the button __and__ the image URL, because `dataKey` doesn't support objects.

**Comment by xile611** [comment]
@Moeface In your case, you can pass `href` of button and `url` of image in the `data`, and add a customized `tick` of `XAxis` which can get the original data to display what you need.

**Comment by NathanCH** [comment]
And if you need each bar to have dynamic content which matches just pass data as a prop to your custom tick and use props.index to retrieve it `const userData = props.data[props.index]`

**Comment by KrisGerhard** [comment]
You can use `<foreignObject>´ tag which allows you to use any html inside your svg.
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject

**Comment by gaurav5430** [comment]
Do you have an example of the foreignobject tag working with recharts ?

**Comment by KrisGerhard** [comment]
The winner prediction chart displays the picture and name using foreignObject on my website: https://wrcfan.com/statistics

PS! It does not work on mobile Chrome due to  https://bugs.chromium.org/p/chromium/issues/detail?id=972732.
