### ISSUE TITLE
BarChart animates from zero instead of old values when redrawn

### ISSUE THREAD

**Issue by godmar** [recharts/recharts#348]
I have a BarChart whose data changes from, say: [2 0] to [1 1]. Instead of the 2-bar shrinking and the 0-bar growing, recharts starts both bars at 0 and grows them to 1 in the animation when the graph is redrawn.

Is there a way to change this behavior?

**Comment by xile611** [comment]
@godmar Thanks! We're trying to refactor animation.

**Comment by dsmalicsi** [comment]
A similar behavior happens as well with PieChart. I have data on a state, and when it updates, the animation restarts from 0.

**Comment by Eric24** [comment]
This is probably a subset of #375.

**Comment by xile611** [comment]
The feature has been done in 1.0.0+
