### ISSUE TITLE
Add Open-high-low-close and Candlestick Charts

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#349]
One of the few "common" charts that can't be done with ReCharts, but something that is almost indispensable when displaying financial data (among others). Really just a chart with up to four data values, displayed in two typical ways:

- https://en.wikipedia.org/wiki/Open-high-low-close_chart
- https://en.wikipedia.org/wiki/Candlestick_chart

**Comment by xile611** [comment]
Duplicated with #267 .
