### ISSUE TITLE
Ability to draw reference line to the end of last bars in bar chart

### ISSUE THREAD

**Issue by silviutugulan** [recharts/recharts#3490]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I'm trying to have a reference line for each bar group, but there is no way to specify a segment for the last bars.

Here is a Code Sandbox (scroll down to line 128) https://codesandbox.io/s/simple-bar-chart-forked-lgt0x0?file=/src/App.tsx

I found an example online where the X axis is of type `number`: https://codesandbox.io/s/recharts-multiple-disjointed-reference-lines-huelk?from-embed=&file=/index.js

This works because you can give numeric values for the beginning and end of the reference line. However, the problem with this implementation is that if you have only one set of bars (on line 16, change `i < 4` to `i < 1`) the chart breaks. I've discovered you need to specifically set the `barSize` on `<Bar />` in order to get the bars to show. This looks like a potentially separate bug.

### What does the proposed API look like?
Have something like:

```
<ReferenceLine
  stroke="red"
  strokeDasharray="3 3"
  segment={[
    { x: "Page G", y: 3000 },
    { x: "END_OF_AXIS_VALUE", y: 3000 }
  ]}
/>
```

**Comment by silviutugulan** [comment]
I just realised those two sandboxes contain old versions of `recharts`, sorry. If you update the first sandbox to the latest version, the reference lines will start from the actual X-axis tick values, which is even further than what I am after.

**Comment by silviutugulan** [comment]
In the end, we discovered there was the `position` prop, and we can just use that: https://codesandbox.io/s/simple-bar-chart-forked-lgt0x0?file=/src/App.tsx

**Comment by ckifer** [comment]
Thanks for documenting this here. If there are any documentation improvements or if you'd like to add this example to the storybook please feel free!
