### ISSUE TITLE
A simple adjustment in the documentation

### ISSUE THREAD

**Issue by NycolasSM** [recharts/recharts#3493]
simple adjustment in the documentation on the API page, when you reduce the screen and try to scroll horizontally, the content is mixing in the navigation bar

[https://i.imgur.com/0C2OHAT.png](url)

**Comment by rajeshpoojari39** [comment]
@NycolasSM , @ckifer . I have made the necessary changes that will fix the issue https://github.com/recharts/recharts.org/pull/268.

**Comment by ckifer** [comment]
Thanks for the contribution @rajeshpoojari39 - merged that PR and built the website. Should be fixed in a bit -- closing this!
