### ISSUE TITLE
Area chart has a display issue when working with the brush range picker

### ISSUE THREAD

**Issue by winterhood** [recharts/recharts#3495]
If the dataset in the area chart contains both positive and negative values, and if you pick a range using the brush. the positive region will stack on top of the negative region. see sandbox and screenshot

Sandbox: https://codesandbox.io/s/area-chart-filled-by-sign-forked-8emdhw

Before selecting the brush range
<img width="584" alt="Screen Shot 2023-04-03 at 12 49 59 PM" src="https://user-images.githubusercontent.com/3734135/229612398-65b6ca6b-a1b6-4b00-bd65-820bb9f57066.png">

After selecting the brush range (Page C - Page G)
<img width="748" alt="Screen Shot 2023-03-28 at 3 41 03 PM" src="https://user-images.githubusercontent.com/3734135/229611252-ab212b6d-967e-4fdc-bba7-ece5bcb70759.png">

**Comment by ckifer** [comment]
Makes sense to me. The gradient is specified by the user, the chart is updated (the gradient is not), now the gradient needs updated by the user. Is that your understanding @HHongSeungWoo ?

**Comment by ckifer** [comment]
Yep - looks like offset here just needs to be kept and state and re-calculated on every brush change @winterhood 

Here is a working example
https://codesandbox.io/s/area-chart-filled-by-sign-forked-mnm42q?file=/src/App.tsx

Going to close this
