### ISSUE TITLE
Q : Brush and Y Domain

### ISSUE THREAD

**Issue by clementdevos** [recharts/recharts#350]
Hey, 

I've been trying Recharts for some charts, looks great and easy to use. 
However, is it possible to keep the domain (let's say  0-max) when using the brush?

My data goes from 0 to 4000 and when reducing the view, i'd like to keep the Y domain at 0-3800 not 0-[max brush displayed dataset]

Cheers !

**Comment by xile611** [comment]
@clementdevos  You can set the `domain` of `YAxis` to be `[0, 3800]`.  
[document of YAxis](http://recharts.org/api#YAxis)

**Comment by clementdevos** [comment]
My bad, i had undefined values in my array and Math.max returned NaN, not the max value...

Cheers!

**Comment by xile611** [comment]
@clementdevos Maybe there is some bug about `undefined`, I'll check it.
