### ISSUE TITLE
Show round numbers instead of decimal in Y axis

### ISSUE THREAD

**Issue by GehanPasindhu** [recharts/recharts#3500]
Is there any way to show only round numbers, instead of decimal numbers in bar charts Y axis

![image](https://user-images.githubusercontent.com/54250592/230609336-5858bb77-4558-446c-9912-dbc82536eb23.png)

I don't want to show 0.5 or any other decimal values on the Y-axis.  I tried setting interval ={1} but it did not fix the issue.

`  const DataFormater = (number) => {
    if (number > 1000000000) {
      return (number / 1000000000).toString() + "B";
    } else if (number > 1000000) {
      return (number / 1000000).toString() + "M";
    } else if (number > 1000) {
      return (number / 1000).toString() + "K";
    } else {
      return number.toString();
    }
  }`

`<YAxis
                tickFormatter={DataFormater}
                width={20}
                axisLine={{ stroke: "none" }}
                tickLine={false}
                interval={1}
              />`

Any solution for this

**Comment by ckifer** [comment]
You can define your ticks as a set of fixed numbers. From 1 to n generate a list of the places you want ticks, interval will then apply to those numbers.

```
<YAxis tickFormatter={DataFormater} width={20} axisLine={{ stroke: "none" }} tickLine={false} interval={1} ticks={[1, 2, 3, 4...]} />
```

**Comment by XDinuka** [comment]
This should be resolved by using `allowDecimals={false}` for YAxis

**Comment by GehanPasindhu** [comment]
> This should be resolved by using `allowDecimals={false}` for YAxis.

@XDinuka It works. Thank you

**Comment by ckifer** [comment]
Whoops, thanks @XDinuka
