### ISSUE TITLE
formatter error, No overloads matches

### ISSUE THREAD

**Issue by Marcos-Iorio** [recharts/recharts#3510]
Hi, i'm trying to make a hoverUpdater on formatter but i only receive a error:

```
No overload matches this call.
  Overload 1 of 2, '(props: TooltipProps<ValueType, NameType> | Readonly<TooltipProps<ValueType, NameType>>): Tooltip<...>', gave the following error.
    Type '(tooltipValue: ValueType, name: NameType, props: Payload<ValueType, NameType>) => Element' is not assignable to type 'Formatter<ValueType, NameType>'.
      Type 'Element' is not assignable to type 'ValueType | [ValueType, NameType]'.
  Overload 2 of 2, '(props: TooltipProps<ValueType, NameType>, context: any): Tooltip<ValueType, NameType>', gave the following error.
    Type '(tooltipValue: ValueType, name: NameType, props: Payload<ValueType, NameType>) => Element' is not assignable to type 'Formatter<ValueType, NameType>'.
```

![image](https://user-images.githubusercontent.com/65930894/231612200-0151de78-ad5e-4b7b-9f2f-9bf6d36ec0a7.png)
![image](https://user-images.githubusercontent.com/65930894/231612230-4cfea56d-e132-42b0-91c6-d9b390a766ce.png)

I'm using recharts 2.4.0 also i try using a older version like 2.0.6 but doesn't change

I anybody wants more detail about the code just let me know!

---

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

**Comment by Yilun-Sun** [comment]
Hi @Marcos-Iorio ! Please see this example: https://recharts.org/en-US/examples/CustomContentOfTooltip
I think you could use `content` property to reach that:

```JSX
const CustomTooltip = ({ active, payload, label, setHoverValue }: any) => {
  if (active && payload && payload.length) {
    setHoverValue(payload?.[0].value);

    return (
      <div className="custom-tooltip">
        <p className="label">{`${label} : ${payload[0].value}`}</p>
      </div>
    );
  }

  return null;
};

export default function App() {
  const [hoverValue, setHoverValue] = useState(0);

  return (
    <div>
      <div>hover value: {hoverValue}</div>
      <BarChart
        width={500}
        height={300}
        data={data}
        margin={{
          top: 5,
          right: 30,
          left: 20,
          bottom: 5
        }}
      >
        <CartesianGrid strokeDasharray="3 3" />
        <XAxis dataKey="name" />
        <YAxis />
        <Tooltip content={<CustomTooltip setHoverValue={setHoverValue} />} />
        <Legend />
        <Bar dataKey="pv" barSize={20} fill="#8884d8" />
      </BarChart>
    </div>
  );
}

```

Here is the CodeSandbox link: https://codesandbox.io/s/tooltip-with-customized-content-forked-72m3mq?file=/src/App.tsx

**Comment by Marcos-Iorio** [comment]
> Hi @Marcos-Iorio ! Please see this example: https://recharts.org/en-US/examples/CustomContentOfTooltip `formatter` is not a valid property of `Tooltip`, I think you could use `content` to reach that:
> 
> ```js
> const CustomTooltip = ({ active, payload, label, setHoverValue }: any) => {
>   if (active && payload && payload.length) {
>     setHoverValue(payload?.[0].value);
> 
>     return (
>       <div className="custom-tooltip">
>         <p className="label">{`${label} : ${payload[0].value}`}</p>
>       </div>
>     );
>   }
> 
>   return null;
> };
> 
> export default function App() {
>   const [hoverValue, setHoverValue] = useState(0);
> 
>   return (
>     <div>
>       <div>hover value: {hoverValue}</div>
>       <BarChart
>         width={500}
>         height={300}
>         data={data}
>         margin={{
>           top: 5,
>           right: 30,
>           left: 20,
>           bottom: 5
>         }}
>       >
>         <CartesianGrid strokeDasharray="3 3" />
>         <XAxis dataKey="name" />
>         <YAxis />
>         <Tooltip content={<CustomTooltip setHoverValue={setHoverValue} />} />
>         <Legend />
>         <Bar dataKey="pv" barSize={20} fill="#8884d8" />
>       </BarChart>
>     </div>
>   );
> }
> ```
> 
> Here is the CodeSandbox link: https://codesandbox.io/s/tooltip-with-customized-content-forked-72m3mq?file=/src/App.tsx

Hi, thanks for answering, I already fix this after hours of trying, I downgrade to version 2.0.4 and then update to the latest, that fix the problem, i don't know what causes that.

**Comment by Yilun-Sun** [comment]
> Hi, thanks for answering, I already fix this after hours of trying, I downgrade to version 2.0.4 and then update to the latest, that fix the problem, i don't know what causes that.

Great! I checked again for the code, `formatter` is a valid property, sorry for the incorrect previous comment.
