### ISSUE TITLE
Stacked bars performance

### ISSUE THREAD

**Issue by supersteves** [recharts/recharts#354]
I'm using stacked bars, but the set of stacks is different per bar. I think this is not the use case the current design is for.

I have about 20 bars, and 20 stacks per bar. There are about 400 unique stack values, since this is a categorical hierarchy (e.g. bars are countries, stacks are cities).

So for every bar+stack combination (400x) I'm rendering a `<Bar>`. After rendering, each of those further contains an `<Animate><g>` for every bar (20x), despite only one per bar+stack combination actually containing anything graphical inside that `<g>` (`<Rectangle><Animate><Animate><path>`).

So that's unnecessarily complex for React to manage, and is unsuitable for this kind of data breakdown.

The data model per object is:
* name (the unique key on the X axis) e.g. "France"
* stack_Paris (the height of stack for Paris)
* stack_Marseille
* stack_LeMans
* etc.

I've considered remapping the data values such that I assign a number (from zero) for each per-bar stack, and giving Recharts just the indexes, and custom renderers for labelling and colouring rectangles. It's a bit messy but should reduce the complexity significantly (down to 400x rather than 400x20x)

Before I press on with this somewhat dirty workaround, I'd be interested to hear if there are any other ways I can structure this.

I'd like to raise the issue that Recharts is creating unnecessary `<Animate><g>` elements for missing (either null or absent) object atttributes for dataKey. It would be better if it we could skip them altogether, removing the 20x part of the complexity here.

Also, why two `Animate` in `<Rectangle><Animate><Animate><path>`?

(Also, the `<Animate>` elements are adding overhead to React (I've not measured how much), and would like to be able to drop them when animation isn't in use.)

**Comment by xile611** [comment]
@supersteves  
I arrange your issues:

## A rectangle is rendered for each value of a stacked bar

 Each stacked bar may have different attributes, so we need a node for each value.  I wonder how to colour the rectangle when only draw a single rectangle for all the stacked value ?

##  Render `<Animate>` for empty value

It'll be fixed.

##  Duplicated `Animate` for rectangles of `Bar` 

It'll be fixed

##  Render `<Animate>` even when `isAnimationActive` is `false`

It'll be fixed.

**Comment by supersteves** [comment]
Fantastic!

Not sure I understand the first point. I think of stacked bars as a hierarchy: bars (columns) then stacks (cells). You have effectively the inverse, stacks (plots) then bars (cells), which becomes inefficient where stack keys are unique per bar.

I look forward to the fixes, and perhaps it will be sufficiently improved in performance in this scenario.

Thanks!

**Comment by xile611** [comment]
@supersteves Do you mean that the calculation (done by [`getStackGroupsByAxisId`](https://github.com/recharts/recharts/blob/master/src/util/CartesianUtils.js#L98)) is inefficient when each `Bar` has unique `stackId`?

It's recommended to remove `stackId` in such case, because no bars need to be stacked.

And the stack will effect the domain of `YAxis`, so *stack* must done before *bars*.

**Comment by supersteves** [comment]
See here
http://jsfiddle.net/kca9npkg/6/?utm_source=website&utm_medium=embed&utm_campaign=kca9npkg

This simple example has 6 visual elements (bar x stack combinations), but demonstrates some issues that arise when you have 500 visual elements (e.g. 25 bars, 20 stacks, possibly unique to each bar).

(I think I was objecting to the need for `<Bar>` per visual element - but I'm not sure that it's a problem, now I look at it again. Instead, I'll give more detail on the other points you've already answered.)

Both the React tree and the DOM tree have significant inefficiencies in number of DOM/React elements. 

For example in pure DOM (I can't see the React debugger via Jsfiddle), this simple 6 (bar x stack) view results in 7 DOM elements per visual element = 42 DOM elements ('g', 'path'), but it should ideally be at most 2 'g' and 1 'path' per (bar x stack) = 18 DOM elements.  

E.g. with 500 visual elements, currently 3500 DOM elements, beyond acceptable performance for SVG, this would become 1500 DOM elements.

If (by removing all 'g' and using 'path' geometry directly) it could collapse further to just a 'path' element per visual element, performance would be further improved e.g. for 500 visual elements, just 500 DOM elements.

I feel that there are common cases where you have around 500 visual elements, but not dramatically more (stacking would become a riot of tiny coloured slices).

I know you've already answered some of these issues above. But this serves as a good example for this issue.

(Also note, the tooltip isn't stack-specific.)

**Comment by supersteves** [comment]
(link updated)

**Comment by xile611** [comment]
@supersteves 
Thanks.  It seems strange in your demo, I'll think about your case.

And I'll try to remove some needless nodes (like g), still more optimization need to done for large amount of data.

**Comment by dmk255** [comment]
Hey - sorry for commenting on such an old issue. I've recently noticed some very bad performance for stacked bar graph animation for similar reasons as above.

Line graphs do not appear to have this problem.

**Comment by mchong-teal** [comment]
Also running into performance issues for stacked bar graphs with unique stack categories across bars.  Haven't profiled it too deeply yet, but looks like a similar issue to above.
