### ISSUE TITLE
converting the radius property in dot and active from pixels to rem.

### ISSUE THREAD

**Issue by Rohianon** [recharts/recharts#3542]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I realized that the whenever I try to convert the r property in the dot to rem, this does not work. 
I would request someone to help me in come up with this conversion, just like how the strokeWidth property can be converted in between rem and pixels. 

### What does the proposed API look like?
activeDot={{ r: "0.25rem" }}  or 
dot: { r: '0.08rem', stroke: 'green', strokeWidth: '0.25rem' }

**Comment by ckifer** [comment]
Hi, these properties are direct SVG properties

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/r#circle
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-width#usage_notes

Please see https://developer.mozilla.org/en-US/docs/Web/SVG/Content_type#length for the exact units that can be used with SVG measurements - these are not 1:1 with CSS

```
length ::= number ("em" | "ex" | "px" | "in" | "cm" | "mm" | "pt" | "pc" | "%")?
```

`em` can be used but not `rem`

**Comment by ckifer** [comment]
Going to close this as SVGs do not support rem

>  just like how the strokeWidth property can be converted in between rem and pixels

confused about this mention, I don't think this is possible or is currently taken care of in recharts
