### ISSUE TITLE
Why ResponsiveContainer not work with RadialBarChart but work with other chart

### ISSUE THREAD

**Issue by thomasop** [recharts/recharts#3545]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/recharts-issue-template-forked-vgq8ft?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
I try to create responsive radialBarChart but I cannot.

I have a component : 
```
import React from "react";
import {
  RadialBarChart,
  RadialBar,
  Legend,
  ResponsiveContainer,
  TooltipProps,
  PolarAngleAxis,
  PieChart,
  Pie,
} from "recharts";
import { mainType } from "../../Type/data/UserMain";
import {
  ValueType,
  NameType,
} from "recharts/types/component/DefaultTooltipContent";

interface proptype {
  data: mainType | null;
}

const CustomizedLegend = ({ payload }: TooltipProps<ValueType, NameType>) => {
  if (payload && payload.length) {
    return (
      <div className="custom-legend">
        <div className="score-title">Score</div>
        <h2 className="paddinglegend legend">{payload[0].value   "%"}</h2>
        <span className="paddinglegend">de votre</span>
        <span className="paddinglegend">objectif</span>
      </div>
    );
  }
  return null;
};

const DisplayRadial: React.FC<proptype> = ({ data }) => {
  let scorePercent = 0;
  data?.todayScore!
    ? (scorePercent  = data?.todayScore! * 100)
    : (scorePercent  = data?.score! * 100);
  let angle = 360 / (100 / scorePercent)   90;
  const value = [{ value: scorePercent, fill: "#ff0000" }];
  return (
    <>
      {data && (
        <>
          <ResponsiveContainer width="100%" height="100%">
            <RadialBarChart
            cx="50%" cy="50%"
              innerRadius="170%"
              outerRadius="140%"
              barSize={12}
              data={value}
              startAngle={90}
              endAngle={angle}
            >
              <PolarAngleAxis type="number" domain={[0, 1]} tick={false} />
              <RadialBar dataKey="value" cornerRadius={10}  />
              <Legend
                iconSize={10}
                layout="vertical"
                verticalAlign="top"
                align="center"
                payload={value}
                content={<CustomizedLegend />}
              />
              <circle cx="50%" cy="50%" fill="white" r="20%"></circle>
            </RadialBarChart>
          </ResponsiveContainer>
        </>
      )}
    </>
  );
};

export default DisplayRadial;
```

### What is expected?
I would like to have a RadialBarChart reponsive

### What is actually happening?
Actually my RadialBar is not responsive 

| Environment | Info |
|---|---|
| Recharts | v2.5.0 |
| React | "react": "^18.2.0" |
| System | Mac, vs code |
| Browser | Google Chrome |

---
I display this chart in a div. And I display also another chart like line or bar chart in the same div and this chart is responsive. For all my chart all my div who display chart are the same. 
For example my structure is :
```
<div>
     <div>lineChart</div>
     <div>barChart</div>
     <div>radialChart</div>
</div>
```
So why my radialBarChart is not responsive ?

**Comment by thomasop** [comment]
I add image for show you. When I resize my browser screen, the circle grow but the radial not grow
<img width="178" alt="Capture d’écran 2023-04-21 à 19 51 38" src="https://user-images.githubusercontent.com/62988861/233709842-ab4c977f-9993-41de-a1e5-c11a302ff1e5.png">
<img width="136" alt="Capture d’écran 2023-04-21 à 19 51 50" src="https://user-images.githubusercontent.com/62988861/233709856-c890ede4-14f0-4c3f-92ff-5b2b34b49393.png">

**Comment by ckifer** [comment]
Hey @thomasop - sorry this isn't working for you. Its most likely a similar issue to https://github.com/recharts/recharts/issues/1136#issue-287820416

**Comment by ckifer** [comment]
Also, this seems to be responsive - https://codesandbox.io/s/recharts-issue-template-forked-0w8ozx?file=/src/index.js

**Comment by thomasop** [comment]
yes I see this but I feel like it has a maximum width when I shrink its responsive but when I grow width stop at a time.
I’ll go over it from the beginning I’ll come back here if I can’t
thank you

**Comment by thomasop** [comment]
I solved the problem, it was the height of the responsive container that didn’t fit, I put like you a size in px (300). And it became responsive, maybe because my container is too small for this graphic, I then center this
Thank you
