### ISSUE TITLE
ScatterChart: Custom Tooltip Text

### ISSUE THREAD

**Issue by komplexb** [recharts/recharts#355]
I didn't see a formal way to do this, so I passed `status` as the `ZAxis` value. 
![Custom Tooltip](https://cloud.githubusercontent.com/assets/3874813/20497404/f8c44366-aff6-11e6-933b-8bdff158d6e1.png)

```
<ScatterChart width={400} height={400} margin={{ top: 20, right: 20, bottom: 20, left: 20 }}>
        ...
        <ZAxis dataKey={'status'} name='status' />
        <CartesianGrid />
        <Tooltip cursor={{ strokeDasharray: '3 3' }} content={<CustomTooltip />} />
</ScatterChart>
```
then retrieved it as a payload value.

```
export function CustomTooltip(props) {
  if (props.active) {
    const { payload } = props;
    // console.log(payload);

    return (
      <div className='custom-tooltip'>
        <p className='desc'>{`${beingAsEmoji(payload[2].value)}`}</p>
      </div>
    );
  }

  return null;
}
```

Of course this prevents me from using the ZAxis value as intended. 
If there really is no formal way to do this, I'd like to take a shot at a PR, to add an optional string/object to the payload like so:
```
<ScatterChart width={400} height={400} margin={{ top: 20, right: 20, bottom: 20, left: 20 }}>
        <XAxis dataKey={'x'} name='x' allowDecimals={true} />
        ...
        <Custom dataKey={'status'} name='status' />
        ...
</ScatterChart>
```

It looks like the payload values are set in [/chart/ScatterChart.js](https://github.com/recharts/recharts/blob/master/src/chart/ScatterChart.js).
I'd like to confirm if the changes would be localized there (in addition to tests).

Please advise.

**Comment by xile611** [comment]
@komplexb Thanks for great advice. It's a workaround to add a `ZAxis` to parse additional information. And I intend to add more information in [payload of Tooltip](https://github.com/recharts/recharts/blob/master/src/chart/ScatterChart.js#L231).

**Comment by komplexb** [comment]
Hey @xile611 I see your commit, but I'm not clear on how I would make use of the changes. MInd adding an example here?

**Comment by xile611** [comment]
@komplexb You can get more `props` in `CustomTooltip` without `ZAxis`. Maybe you can console `props` to see detail.
