### ISSUE TITLE
Add screen reader support for chart values

### ISSUE THREAD

**Issue by julianna-ciq** [recharts/recharts#3555]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Screen reader users have no access to the data underlying a chart without the chart author making it available separately.

### What does the proposed API look like?
One possible solution to this problem would be to make the tooltip into a [live region](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions), so that as the tooltip content changed, the screen reader will read out the updates.

**Comment by ckifer** [comment]
Released in 2.12!
