### ISSUE TITLE
Multiple y-axes breaks chart when plotting only single datum

### ISSUE THREAD

**Issue by millerized** [recharts/recharts#356]
See fiddle for example: http://jsfiddle.net/millerized/r19hetwn/7/
You can uncomment line 6 and rerun to see the chart plot correctly.

**Comment by jamesremuscat** [comment]
This was working in v0.13.4 - looks like it was broken in either 0.14.0 or 0.14.1, the former seems to have disappeared from npm.

**Comment by millerized** [comment]
Yeah, we found it was broken in v0.15.1. We are now using the latest v0.18.0 build.

**Comment by jamesremuscat** [comment]
I think the issue I'm encountering is slightly different to yours (though possibly related); https://github.com/recharts/recharts/commit/2b07adff1c92bc7d1cacdd4324b151228475538a#diff-c72854427dea8d1e41e88ad1f5fad89dL189 changes the behaviour of the chart such that when you have multiple datapoints but null/undefined values for all but one of a series attached to a secondary y-axis, that axis is broken.
e.g. with y2 bound to a second Y-axis and data

`[ {x: 1, y:1, y2: 1}, {x: 2, y: 2} ]`

`y` datapoints display fine, but the `y2` series and second Y-axis aren't displayed.

Reverting the change to that line solves my issue, but I don't _think_ it would make a change to yours. I'm also not sure that doing so gives the correct behaviour elsewhere...

**Comment by millerized** [comment]
Confirmed 6537a85 (v0.19.0) does fix this in our implementation.

💯🍻 +10 @xile611
