### ISSUE TITLE
Dashed line with animationDuration={ 0 } kills the page

### ISSUE THREAD

**Issue by simonenkoav** [recharts/recharts#3565]
Try to uncomment 
```
// animationDuration={ 0 }
```
in this code sample: https://codesandbox.io/s/dashed-line-chart-forked-zt1nu0?file=/src/App.tsx

**Comment by ckifer** [comment]
Looks good to me https://codesandbox.io/s/dashed-line-chart-forked-bjirie?file=/src/App.tsx

**Comment by ckifer** [comment]
@simonenkoav PR for the fix downstream here https://github.com/recharts/react-smooth/pull/77

Feel free to review
