### ISSUE TITLE
Tooltip formatter per yAxis

### ISSUE THREAD

**Issue by jlubeck** [recharts/recharts#357]
It seems like there is no way to use different formatters per axis inside the Tooltip.

I have a LineChart with 2 Y axis, left is money and right is regular number. So I made a formatter to show the $ symbol, but it is displaying for both labels. 

Is there a way to make one formatter for each axis?

Thanks

**Comment by xile611** [comment]
@jlubeck You can specify `formatter` for each `Line`, and the formatter will be used to format value in `Tooltip` like this [demo](http://jsfiddle.net/s0kne60e/).

**Comment by jlubeck** [comment]
Ahh, awesome. Thanks!
