### ISSUE TITLE
ResponsiveContainer ability to set maxHeight

### ISSUE THREAD

**Issue by truenorthcreative** [recharts/recharts#358]
@xile611 I added a maxHeight definition to `lib/component/ResponsiveContainer.js` that might be helpful for others.  I didn't see a way to contribute to the npm recharts, so I apologize if this isn't the venue for that.  

**Added** `maxHeight = _props.maxHeight,` line 125

**Added**: `if(maxHeight && (calculatedHeight > maxHeight)) calculatedHeight = maxHeight;` after `calculatedHeight = calculatedWidth / aspect;` on line 138

**Usage**
`<ResponsiveContainer width="100%" aspect={ 2 } maxHeight={ this.props.maxHeight || 400 }>`

Hope this helps someone.

**Comment by xile611** [comment]
@truenorthcreative You can fork recharts in github, add create a PR.

**Comment by truenorthcreative** [comment]
Thanks @xile611 -- I submitted a PR.
