### ISSUE TITLE
Axis size changes between the server side and the client side rendering

### ISSUE THREAD

**Issue by huozhi** [recharts/recharts#359]
I setup a simple demo with react ssr. 

```js
import React from 'react'
import {
  LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend
} from 'recharts'

const data = [
  {name: 'Page A', uv: 4000, pv: 2400, amt: 2400},
  {name: 'Page B', uv: 3000, pv: 1398, amt: 2210},
  {name: 'Page C', uv: 2000, pv: 9800, amt: 2290},
  {name: 'Page D', uv: 2780, pv: 3908, amt: 2000},
  {name: 'Page E', uv: 1890, pv: 4800, amt: 2181},
  {name: 'Page F', uv: 2390, pv: 3800, amt: 2500},
  {name: 'Page G', uv: 3490, pv: 4300, amt: 2100},
]

const width = 600
const height = 300

export default class Chart extends React.Component {
  render() {
    return (
      <div style={{width: `${width}px`, height: `${height}px`}}>
        <LineChart width={width} height={height} data={data}
          margin={{left: 0, top: 0, right: 0, bottom: 0}}>
          <XAxis dataKey="name" />
          <YAxis stroke="#666" />
          <Line
            type="monotone"
            dataKey="pv"
            stroke="#8884d8"
            strokeDasharray="5 5"
            isAnimationActive={false}
          />
        </LineChart>
      </div>
    )
  }
}
```

But the browser always throw the Warning:

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. 
This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. 
React injected new markup to compensate which works but you have lost many of the benefits of server rendering. 
Instead, figure out why the markup being generated is different on the client or server:
 (client) 540" height="30" x="573.3359375" y="276"
 (server) 540" height="30" x="600" y="276" stroke=printWarning
```

I refresh the browser many time seeing that, the last tick of the x and y axises always move positions when rendering changes. Looks like the axises was recalculated in the client rendering.

The client rendering was correct

![image](https://cloud.githubusercontent.com/assets/4800338/20531973/59cbf312-b113-11e6-8074-891b06ceeed1.png)

The server rendering wasn't

![image](https://cloud.githubusercontent.com/assets/4800338/20532046/8e49123c-b113-11e6-8c42-7cb0912c78e3.png)

**Comment by xile611** [comment]
@huozhi In  CSR, we'll calculate the width / height of ticks, and adjust the position of tick If no enough space to display the whole tick. But this calculation can't be done in SSR.

**Comment by huozhi** [comment]
@xile611 Thanks for explanation! I' ll just ignore the warnings.

By the way, I was trying to generate a SVG graph by SSR. Now I just render the `<LineChart>` and got the structure like `<div ...><svg /></div>`. And then erase the string of `<div/>`, send SVG content to the client. Is there any other way to get it work better or easier ? : )

**Comment by xile611** [comment]
@huozhi Temporarily no better way, unless all the components can be implemented by svg elements. Now `Tooltip` and  `Legend` are implemented by html. We'll discuss this question. Thanks.

**Comment by huozhi** [comment]
@xile611 Thanks!

I found that `src/chart/generateCategoricalChart.js` rendered a div wrapped `<Surface />`. I guess you could provide a way only render the chart SVG without the container, Tooltip and Legend. SVGs usually are regarded as static image, they don't need too much interaction.

Thanks a lot for replying my questions. : )

**Comment by huozhi** [comment]
Same question with @Havret ，replace string from `<div>` to `<svg>` is really a hack.

**Comment by mhuggins** [comment]
I'm curious about this too.

**Comment by ferociousfox** [comment]
I am as well

**Comment by FBosler** [comment]
I am also :D
