### ISSUE TITLE
className not propagated to axis components

### ISSUE THREAD

**Issue by mitrotasios** [recharts/recharts#3591]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently, passing a className to the axis components is not possible, since the className is not appended in the `renderAxis` method when the `axisOptions` are forwarded to the `CartesianAxis` component [here](https://github.com/recharts/recharts/blob/master/src/chart/generateCategoricalChart.tsx#L1831).

This behaviour prohibits styling axis components with CSS classes.

### What does the proposed API look like?
There are no changes to the API, the className would merely be appended to the `CartesianAxis` component.

**Comment by severinlandolt** [comment]
+1

**Comment by ckifer** [comment]
this is merged and released in the latest alpha version. Will be included with next release, resolving!
