### ISSUE TITLE
Pie Label type definition does not allow SVGProps

### ISSUE THREAD

**Issue by timbonicus** [recharts/recharts#3593]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-pie-label-type-60mtn8)

### Steps to reproduce
Load the codesandbox; observe the type error but functioning SVG prop

### What is expected?
SVG props are allowed for label types

### What is actually happening?
TypeScript error when defining an object with SVG props

| Environment | Info |
|---|---|
| Recharts | v2.6.2 |
| React | 17 |
| System | macOS Ventura 13.3.1 |
| Browser | Chrome 113.0.5672.92 |

**Comment by ckifer** [comment]
Released in 2.7
