### ISSUE TITLE
Ticks on XAxis changes position depending on container size

### ISSUE THREAD

**Issue by sepruda** [recharts/recharts#3598]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elastic-fermat-q5w1ty?file=/src/App.js)

### Steps to reproduce
Change the size of the window, notice that all regions except AMERICAS change relative position compared to the other x axis.

### What is expected?
The region ticks should have the same relative position, no matter screen size. Otherwise it's impossible to calculate a position where they are in the middle of a 4-week group.

### What is actually happening?
They slide right and left relative to the week axis, when changing screen size. 

| Environment | Info |
|---|---|
| Recharts | v2.6.2 |
| React | 18.2.0 |
| System | Mac OSx 13.3.1 (a)  |
| Browser | Chrome Version 113.0.5672.92 (Official Build) (arm64) |

---
I've found aligning ticks extremely hard using this library.

**Comment by ckifer** [comment]
Probably going to close this in favor of https://github.com/recharts/recharts/issues/3562#issue-1692345429 as it is the same issue

In the meantime @Yilun-Sun @nikolasrieble any suggestions for making this implementation of 2 x-axes better in the codesandbox?

**Comment by sepruda** [comment]
@ckifer Thanks for replying, it's not a duplicate of that issue, since I'm already using two X axises to get the effect, and the other issue reads like an enchancement suggesiton for grouping items on one x axis.

**Comment by ckifer** [comment]
I think both issues would be solved by implementing a feature that does that though right?

In the other issues case your solution was given as a workaround. If there was a default way of grouping x axis items then you wouldn't need the second axis. (Unless you're relying on it for something else I guess)

**Comment by sepruda** [comment]
No for sure, adding that enhancement would definitely solve my issue, but I'm ok with a workaround for now :-)

**Comment by sepruda** [comment]
Do you have any ideas for a workaround, I fail to see one myself..

**Comment by nikolasrieble** [comment]
I have implemented a workaround, which basically reimplements the feature on the outside. I am planning to migrate that solution into recharts. 
I measure all ticks in width, given the font settings, and I measure the axis width. Then, I find the smallest number N for which every nTH tick would not lead to overlapping ticks. 
The result I then set to the interval.

**Comment by nikolasrieble** [comment]
@sepruda Not without a lot of effort. Instead I will prefer to just fix the feature and implement it correctly. I admit though that it is not high priority for me.

**Comment by ckifer** [comment]
Closing in favor of #3562

**Comment by sepruda** [comment]
Still not fixed :-(

**Comment by ckifer** [comment]
Still tracking in the other issue. Please feel free to contribute if you'd like to get something through faster
