### ISSUE TITLE
ResponsiveContainer improvement

### ISSUE THREAD

**Issue by Cloudo** [recharts/recharts#36]
I found a quite interesting implementation of component, which provide width and height to its children.
[https://github.com/bvaughn/react-virtualized/blob/master/docs/AutoSizer.md](url)

Its based on https://github.com/sdecima/javascript-detect-element-resize and as the docs say...

> it not only detects javascript generated resize changes but also changes made from CSS pseudo classes e.g. :hover, CSS animations, etc.

You can see it in action here in `Autosizer` tab:
[https://bvaughn.github.io/react-virtualized/](url)

So i already have used `AutoSizer` in my project and it works perfectly!
I think I can make a PR a bit later.
What do you think?

**Comment by xile611** [comment]
PR is welcome!
`AutoSizer` is more perfect than ResponsiveContainer. 
 But I am worried about the size of Recharts.js now.
You can run  `npm run bundle-analyse` after improvement.

**Comment by vanthiyathevan** [comment]
Also it shouldn't render if its out of the domain.

**Comment by xile611** [comment]
Fixed in 0.8.6
