### ISSUE TITLE
Bar Tooltip

### ISSUE THREAD

**Issue by AshworthHub** [recharts/recharts#362]
With the 0.19 release; the tooltip when using bar is acting strange.  Before, I was using onMouseEnter of BarChart to get data.x (which would set/position the tooltip in the middle of a sized bar).  But now, it seems it doesn't matter what I set for position or coordinate, the tooltip doesn't move. Its stuck in the top-left corner.

In addition; the data passed changes depending where I hover over (from top, left, etc) - see 2nd screen capture below.

![screen shot 2016-11-23 at 9 23 32 am](https://cloud.githubusercontent.com/assets/7296078/20569768/809174d6-b15e-11e6-8b49-dd1e87a79e16.png)
![screen shot 2016-11-23 at 9 23 24 am](https://cloud.githubusercontent.com/assets/7296078/20569773/82a86090-b15e-11e6-9542-babfc79785eb.png)

**Comment by xile611** [comment]
@AshworthHub The  `payload` in some charts diffs, so I unify the `payload` to be the original `data` or `entry`. Can you support your case more detail ?

**Comment by AshworthHub** [comment]
But wouldn't the unfied payload be the same regardless where the mouse enters the chart?  The log above was using the exact same chart; however, the X/Y changed based on if I hovered **from** the top,left,etc of the chart.

**Comment by xile611** [comment]
Yeah, the `activePayload` is the `entry` that your mouse in. So I can't get what's the problem ?
