### ISSUE TITLE
Two typescript error in recharts/src/component/DefaultTooltipContent.tsx on TSC compilation

### ISSUE THREAD

**Issue by gabgagnon** [recharts/recharts#3620]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.studentsinwarsaw.com/wp-content/uploads/2018/02/no-time-sorry.png](https://www.studentsinwarsaw.com/wp-content/uploads/2018/02/no-time-sorry.png)

### Steps to reproduce
1. Build a typescript project using tsc compiler from typescript.
2. Added "import { ValueType, NameType } from 'recharts/src/component/DefaultTooltipContent';" in app.tsx.
3. Run tsc compiler
4. Failed because of typescript errors in DefaultTooltipContent.tsx

### What is expected?
The typing should be good

### What is actually happening?
The typing in this file is not good anymore and fails the compilation.

| Environment | Info |
|---|---|
| Recharts | v2.6.2 |
| React | 17.0.2 |
| System | macOS Monterey |
| Browser | Chrome |

---
Command line: tsc

1: TYPESCRIPT ERROR TS2322 -------

../../../node_modules/recharts/src/component/DefaultTooltipContent.tsx:96:58 - error TS2322: Type '{}' is not assignable to type 'ReactNode'.
96             <span className="recharts-tooltip-item-unit">{entry.unit || ''}</span>
                                                            ~~~~~~~~~~~~~~~~~~
  node_modules/@types/react/index.d.ts:1373:9
    1373         children?: ReactNode | undefined;
                 ~~~~~~~~
    The expected type comes from property 'children' which is declared here on type 'DetailedHTMLProps<HTMLAttributes<HTMLSpanElement>, HTMLSpanElement>'



2: TYPESCRIPT ERROR TS2322 -------

../../../node_modules/recharts/src/component/DefaultTooltipContent.tsx:137:11 - error TS2322: Type 'string | ReactElement<unknown, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
  Type 'ReactElement<unknown, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
    Property 'children' is missing in type 'ReactElement<unknown, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.
137           {React.isValidElement(finalLabel) ? finalLabel : `${finalLabel}`}
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  node_modules/@types/react/index.d.ts:181:9
    181         children: ReactNode;
                ~~~~~~~~
    'children' is declared here.
  node_modules/@types/react/index.d.ts:1373:9
    1373         children?: ReactNode | undefined;
                 ~~~~~~~~
    The expected type comes from property 'children' which is declared here on type 'DetailedHTMLProps<HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>'

**Comment by ckifer** [comment]
`src` is no longer included in recharts as all of the compiled files are in `lib` or `es6` directories

https://github.com/recharts/recharts/blob/master/package.json#L10-L16

**Comment by ckifer** [comment]
```
import {
  ValueType,
  NameType,
} from "recharts/types/component/DefaultTooltipContent";
```
will work to get the types. Though this isn't a sanctioned import path and is subject to change.

These components will be exported by default in the next release https://github.com/recharts/recharts/pull/3604

**Comment by gabgagnon** [comment]
Okay! Sorry for my mistakes! And thanks alot for the quick response!

**Comment by ckifer** [comment]
No worries, things are a bit tricky
