### ISSUE TITLE
npm audit error for yaml

### ISSUE THREAD

**Issue by julianna-langston** [recharts/recharts#3628]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/advisories/GHSA-f9xv-q969-pqx4](https://github.com/advisories/GHSA-f9xv-q969-pqx4)

### Steps to reproduce
Run `npm audit`

You will see the following details:

```
yaml  2.0.0-5 - 2.2.1
Severity: high
Uncaught Exception in yaml - https://github.com/advisories/GHSA-f9xv-q969-pqx4
fix available via `npm audit fix`
node_modules/lint-staged/node_modules/yaml

1 high severity vulnerability
```

### What is expected?
No NPM audit failures

### What is actually happening?
recharts is using an outdated version of lint-staged, and that version is using an insecure version of yaml. Recharts should update to the latest version of lint-staged, which would address this security audit issue.

| Environment | Info |
|---|---|
| Recharts | v2.7.1 |
| React | any |
| System | any |
| Browser | any |

**Comment by ckifer** [comment]
Closing as completed, thanks!
