### ISSUE TITLE
React Dom Server 15.4.0

### ISSUE THREAD

**Issue by earthinferno** [recharts/recharts#363]
Given that your library has a dependency on react-dom-server and that the good folks at React state 'We don't recommend using React DOM Server on the client in most cases'; are there any plans to remove this dependency or separate it out into a second library?

**Comment by xile611** [comment]
@earthinferno Yeah, of course. But no good solution now.

**Comment by xiaokekeT** [comment]
https://github.com/recharts/recharts/blob/master/src/component/Legend.js#L5

remove this line ?

**Comment by xile611** [comment]
Yeah! It should be removed.
