### ISSUE TITLE
Two identical charts, one renders correctly, the other does not

### ISSUE THREAD

**Issue by nwoodr94** [recharts/recharts#3642]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/simple-line-chart-forked-lt2n97?file=/src/App.tsx)

### Steps to reproduce
Create two identical LineCharts, and use the above data. The data structures are identical, except one has different values than the other, of course. It's from a different data source, but produces a similar chart.

One renders correctly, while the other does not.

### What is expected?
The charts should render correctly

### What is actually happening?
One of the charts has a messed up interpretation of the Y axis domain

![image](https://github.com/recharts/recharts/assets/46133948/a5219871-81f2-4e0b-a464-3eb608298b85)

| Environment | Info |
|---|---|
| Recharts | v2.7.2 |
| React | ^18.1.0 |
| System | Windows 10 |
| Browser | Chrome - Version 114.0.5735.134 (Official Build) (64-bit) |

**Comment by ckifer** [comment]
Hi - it looks like you're trying to render string data as numbers which isn't going to work

**Comment by podenborg** [comment]
I had a similar issue and can confirm that parsing my string data into numeric values resolve the issue. Using `parseInt` I'm converting my strings into JavaScript ints and now it works like a charm!

Thanks for the help @ckifer

**Comment by ckifer** [comment]
Sweet! @nwoodr94 I'm going to close this. Feel free to reply here if you have any more issues
