### ISSUE TITLE
Mobile Tooltip not being presented on Piechart

### ISSUE THREAD

**Issue by zachbugay** [recharts/recharts#3644]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://recharts.org/en-US/examples/PieChartWithCustomizedLabel](https://recharts.org/en-US/examples/PieChartWithCustomizedLabel)

### Steps to reproduce
Replace all of the code with the following

```import React, { PureComponent } from 'react';
import { PieChart, Pie, Sector, Cell, ResponsiveContainer, Tooltip } from 'recharts';

const data = [
  { name: 'Group A', value: 400 },
  { name: 'Group B', value: 300 },
  { name: 'Group C', value: 300 },
  { name: 'Group D', value: 200 },
];

const COLORS = ['#0088FE', '#00C49F', '#FFBB28', '#FF8042'];

const RADIAN = Math.PI / 180;
const renderCustomizedLabel = ({ cx, cy, midAngle, innerRadius, outerRadius, percent, index }) => {
  const radius = innerRadius   (outerRadius - innerRadius) * 0.5;
  const x = cx   radius * Math.cos(-midAngle * RADIAN);
  const y = cy   radius * Math.sin(-midAngle * RADIAN);

  return (
    <text x={x} y={y} fill="white" textAnchor={x > cx ? 'start' : 'end'} dominantBaseline="central">
      {`${(percent * 100).toFixed(0)}%`}
    </text>
  );
};

export default class Example extends PureComponent {
  static demoUrl = 'https://codesandbox.io/s/pie-chart-with-customized-label-dlhhj';

  render() {
    return (
      <ResponsiveContainer width="100%" height="100%">
        <PieChart width={400} height={400}>
          <Pie
            data={data}
            cx="50%"
            cy="50%"
            labelLine={false}
            label={renderCustomizedLabel}
            outerRadius={80}
            fill="#8884d8"
            dataKey="value"
          >
            {data.map((entry, index) => (
              <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
            ))}
          </Pie>
          <Tooltip/> {/* All we did was add a Tool Tip*/}
        </PieChart>
      </ResponsiveContainer>
    );
  }
}
```

Open up the dev tools.
Enable "Responsive Design Mode."
Set the screen size to "iPhone" (any will do)
Click on any slice of the Pie Chart. 

### What is expected?
The tooltip will be properly displayed. 

### What is actually happening?
Nothing is happening.

| Environment | Info |
|---|---|
| Recharts | v2.7.2 |
| React | 17 |
| System | Windows |
| Browser | Firefox, Edge |

---
The PieChart Tooltip component is not being activated on iPhone size responsiveness.

**Comment by ckifer** [comment]
Hmm, it seems to be working here https://codesandbox.io/s/pie-chart-with-customized-label-forked-34qh67?resolutionWidth=244&resolutionHeight=675&file=/src/App.tsx

**Comment by ckifer** [comment]
Going to close this as stale until more details / reproduction are added
