### ISSUE TITLE
We need to customize the html tag of wrapper

### ISSUE THREAD

**Issue by imyuanx** [recharts/recharts#3649]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I need add Recharts to tooltip at `<p></p>`, but default the html tag of wrapper is `<div>`, I think we need provide a api for customize html tag

### What does the proposed API look like?
Be like:
```
<AreaChart width={730} height={250} data={data} wrapper="span" ></AreaChart>
```

**Comment by ckifer** [comment]
Hi, 

This issue does not make much sense to me, can you expand on what you mean? Nothing should depend on which HTML elements are used

**Comment by imyuanx** [comment]
OK, I will change <p> to <div>. Thanks
