### ISSUE TITLE
Tooltip Hover Effect has offset in a Date-BarChart

### ISSUE THREAD

**Issue by Markus1812** [recharts/recharts#3650]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-6k28wt?file=/src/index.js)

### Steps to reproduce
see CodeSandbox Example, using a Bar Chart with dates. 

### What is expected?
The hover effect on the bars should be centered on the bar. The last (most right one) should be inside the bounds of the chart (allowDataOverflow just cuts it off).

### What is actually happening?
When moving the cursor over the bars, the hover effect is always shifted half a bar to the left. The last bar is out of bounds.

| Environment | Info |
|---|---|
| Recharts | v2.7.2 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome 114 |

**Comment by Markus1812** [comment]
Just found out, you can fix it by adding `type={"number"} domain={[min => min - 1000*3600*24, max => max + 1000*3600*24]}` to the xAxis-Element. The `type="number"` fixes the offset on the hover effect and setting the domain sets the bounds correct. 

Updated CodeSandbox: https://codesandbox.io/s/recharts-issue-template-forked-659h3h?file=/src/index.js

**Comment by ckifer** [comment]
Hi - yep this makes sense because `XAxis` defaults to a categorical chart which this is not. Glad you made it to a resolution. Going to resolve this
