### ISSUE TITLE
Server side rendering warning with useLayoutEffect

### ISSUE THREAD

**Issue by sieroaoj** [recharts/recharts#3656]
When rendering a chart with server side render we get this warning in version 2.7.2:

> Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
>     at Rectangle (app/node_modules/recharts/lib/shape/Rectangle.js:81:35)
> 

Switching to useEffect seems to solve the problem and the chart renders well without any warnings.

It seems that "useLayoutEffect is put forward as the safest upgrade path for class components":
https://medium.com/@alexandereardon/uselayouteffect-and-ssr-192986cdcf7a

Could we update the code to use useEffect instead?
https://github.com/search?q=repo%3Arecharts%2Frecharts%20useLayoutEffect&type=code

**Comment by ckifer** [comment]
yeah I think this is fine

seems like the guidance from the react team is that most of the time it isn't needed. Difference in visual performance is negligible if any in this case

**Comment by ckifer** [comment]
released in 2.8
