### ISSUE TITLE
Drop the classnames

### ISSUE THREAD

**Issue by supersteves** [recharts/recharts#366]
Recharts is injecting className into many of its React rendered elements. Out of the box Recharts doesn't need classnames, but they're added presumably as a convenience for those who want to use CSS to style or customise their charts or to add custom CSS based animation.

Given that the DOM is far and away the biggest cause for poor performance in SVG based charts, and React itself will add some overhead, I suggest making it possible to disable classnames altogether, certainly on the elements that are repeated (e.g. Bar, Cell in a stacked bar chart). This would reduce an additional DOM attribute that needs to be reconciled by React and interpreted by the browser, and might lead to a few percent better performance.

As discussed here:
https://github.com/recharts/recharts/commit/e2957375b20ac6864212aae037a6bf1fa1d297e1#commitcomment-19952106

This is currently theoretical. I haven't tried it to measure the actual benefit.

**Comment by xile611** [comment]
@supersteves We need more performance data. `className` is absolutely no problem for normal data. For huge size data, we'll do more optimization to omit some nodes,  not just remove `className`.
