### ISSUE TITLE
[TypeError]: Super expression must either be null or a function

### ISSUE THREAD

**Issue by MenaiAla** [recharts/recharts#3664]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-3h2gsm?file=/src/index.tsx)

### Steps to reproduce
npm install recharts.

Create Chart.tsx component.

```tsx
import { LineChart, Line, CartesianGrid, XAxis, YAxis } from "recharts";
import { IProps } from "./type";

const Chart = <T extends {[key: string]: number | string }>({
  data,
}: IProps<T>) => {
  return (
    <LineChart
      width={600}
      height={300}
      data={data}
    >
      <Line
        type="monotone"
        stroke="#8884d8"
      />
      <CartesianGrid stroke="#ccc" />
      <XAxis dataKey="name" />
      <YAxis />
    </LineChart>
  );
};

export default Chart;


```

Define  typescript type:

```ts
export interface IProps<T> {
  data: T[];
}
```

### What is expected?
Display the Chart component

### What is actually happening?
error node_modules/recharts/lib/component/DefaultLegendContent.js (22:112) @ _inherits
- error Error [TypeError]: Super expression must either be null or a function
    at _inherits (webpack-internal:///(sc_server)/./node_modules/recharts/lib/component/DefaultLegendContent.js:122:15)
    at eval (webpack-internal:///(sc_server)/./node_modules/recharts/lib/component/DefaultLegendContent.js:219:5)
    at eval (webpack-internal:///(sc_server)/./node_modules/recharts/lib/component/DefaultLegendContent.js:351:2)
    at (sc_server)/./node_modules/recharts/lib/component/DefaultLegendContent.js (/home/alaeddine/Desktop/gersthofen-app/.next/server/app/components/chart/page.js:2932:1)
    at __webpack_require__ (/home/alaeddine/Desktop/gersthofen-app/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(sc_server)/./node_modules/recharts/lib/component/Legend.js:17:29)
    at (sc_server)/./node_modules/recharts/lib/component/Legend.js (/home/alaeddine/Desktop/gersthofen-app/.next/server/app/components/chart/page.js:2976:1)
    at __webpack_require__ (/home/alaeddine/Desktop/gersthofen-app/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(sc_server)/./node_modules/recharts/lib/index.js:325:15)
    at (sc_server)/./node_modules/recharts/lib/index.js (/home/alaeddine/Desktop/gersthofen-app/.next/server/app/components/chart/page.js:3042:1) {
  digest: undefined
}
null
redux-persist failed to create sync storage. falling back to noop storage.
A non-serializable value was detected in an action, in the path: `register`. Value: [Function: register] 
Take a look at the logic that dispatched this action:  {
  type: 'persist/PERSIST',
  register: [Function: register],
  rehydrate: [Function: rehydrate]
} 
(See https://redux.js.org/faq/actions#why-should-type-be-a-string-or-at-least-serializable-why-should-my-action-types-be-constants) 
(To allow non-serializable values see: https://redux-toolkit.js.org/usage/usage-guide#working-with-non-serializable-data)

| Environment | Info |
|---|---|
| Recharts | v2.7.2 |
| React | 18 |
| System | Ubuntu 22.04 |
| Browser | Chrome ( latest ) |

**Comment by ckifer** [comment]
Hi - it looks like your repro is using an old version of recharts

**Comment by MenaiAla** [comment]
I installed the package using the command: `npm install recharts`.

**Comment by ckifer** [comment]
I wasn't able to get your reproduction working (loading slowly in the VM for codesandbox) but I duplicated everything here and upgraded the recharts version to the latest (2.7.2)
https://codesandbox.io/s/simple-line-chart-reproduction-forked-qxtv9k

**Comment by MenaiAla** [comment]
I tried `npm install recharts` but I got the same error. I'll try to delete the npm packages, verify the cache and reinstall all modules.

Would you share a NextJS reproduction? may this will help me find the bug.

**Comment by ckifer** [comment]
Can you share your TS version and TS config?

**Comment by MenaiAla** [comment]
Of course:

Pckage.json:

```typescript

{
  "name": "credium-gersthofen-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@reduxjs/toolkit": "^1.9.5",
    "@types/node": "20.4.0",
    "@types/react": "18.2.14",
    "@types/react-dom": "18.2.6",
    "classnames": "^2.3.2",
    "eslint": "8.44.0",
    "eslint-config-next": "13.4.8",
    "next": "13.4.8",
    "normalize.css": "^8.0.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-icons": "^4.10.1",
    "react-redux": "^8.1.1",
    "recharts": "^2.7.2",
    "redux-persist": "^6.0.0",
    "sharp": "^0.32.3",
    "swr": "^2.2.0",
    "typescript": "5.1.6"
  },
  "devDependencies": {
    "prettier": "3.0.0"
  }
}


```

ts.config:
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts", "src/app/[id]/(gersthofen)/page.jsx", "src/components/core/BackToTop/index.jsx"],
  "exclude": ["node_modules"]
}

```

**Comment by ckifer** [comment]
reproduced but only in next

unfortunately I don't have capacity to dive further into the issue at this time, I'll try to look into it soon. In the meantime 

Looks like its happening with quite a few components other than just DefaultLegendContent. It may be a latest next version thing... I don't like next :/. I added a new next specific label because I feel there will be more of these in the future...

**Comment by MenaiAla** [comment]
I really liked rechart but I need to implement the MVP as soon as possible, I 'll use reach-chart2, and when I fix the issue, I'll switch to recharts.

**Comment by ckifer** [comment]
Oh, this is a nextjs thing

you need to add `use client`; to the top of your file

**Comment by MenaiAla** [comment]
Yes. Exactly. It works only on client components. Damn NextJS, I don't know how I forgot about that.

**Comment by ckifer** [comment]
Yeah I don't use next so I had no idea 

Going to close this!

**Comment by MenaiAla** [comment]
I'll use recharts ❤️ .

**Comment by VSupunK** [comment]
Adding use client worked for me.

'use client'  - top of you code that you use the rechart component imported.
