### ISSUE TITLE
Margins in composed charts with just line and area

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#367]
I believe a composed chart automatically leaves room for bar charts, even if none are defined (extra space to the left and right side, extra-wide cursor, etc.). That makes sense if the chart was going to contain a bar, but not if it only contains lines and areas. Is there a recommended way to eliminate the extra "bar" room from the composed chart?

**Comment by xile611** [comment]
@Eric24 

You can specify the `scale` of `XAxis` to be `point`( the default scale is `band` )  which'll use scalePoint of [d3-scale](https://github.com/d3/d3-scale).  

```jsx
<ComposedChart 
  width={600} 
  height={400} 
  data={data}
  margin={{top: 20, right: 20, bottom: 20, left: 20}}
>
  <XAxis dataKey="name" scale="point" />
  <YAxis />
  <Tooltip/>
  <Legend/>
  <CartesianGrid stroke='#f5f5f5'/>
  <Area type='monotone' dataKey='amt' fill='#8884d8' stroke='#8884d8'/>
   <Line type='monotone' dataKey='uv' stroke='#ff7300'/>
</ComposedChart>
```

Then the margin will be eliminated.

**Comment by Eric24** [comment]
Well, yes, "point" works as described, but: a) It only works if the axis type=category (my use-case is type=number); and b) with scale=point (and type=category), the "bars" in my composed chart are not rendered at all.

**Comment by xile611** [comment]
@Eric24 

About question a:
  When the `XAxis` of `ComposedChart` is numerical axis, the scale of `XAxis` is linear scale, no extra space for *bars* will produce. 

About question b:
 What kind of `bars` are not rendered? I create a [demo](http://jsfiddle.net/z3wx6zm3/), it works fine even when I have `Bar` in the composed chart.

So would you please create an online demo?

**Comment by chriscain** [comment]
Hi @xile611 - I ran into the same problem @Eric24 had/has, and it seems that removing the `barSize` prop from `Bar` makes the bars in the composed chart no longer render.

Updated fiddle [here](http://jsfiddle.net/z3wx6zm3/1/). Is this intended? Thanks so much!

**Comment by Malachi-M** [comment]
@Eric24 I also am experiencing this issue. Were you able to find a workable strategy for a composed chart with `Line` and `Area` components  and no `Bar` components?

**Comment by Eric24** [comment]
@Malachi-M : I ended up using the type=point suggestion from @xile611 and that worked for my use-case.
