### ISSUE TITLE
Question: is it possible to calculate the points of connectNull line?

### ISSUE THREAD

**Issue by abdul-insync** [recharts/recharts#3672]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/connectnulls-point-calculation-tntvn4)

### Steps to reproduce
create a line chart with null values and try to read the points to pass it to the tooltip.

### What is expected?
connectNulls point values to be displayed on the tooltip

### What is actually happening?
if data value is null then tooltip doesn't display any data when hovered  

| Environment | Info |
|---|---|
| Recharts | v2.7.2 |
| React | 17.0.2 |
| System | macOS |
| Browser | Safari |

**Comment by nikolasrieble** [comment]
It is not in scope of the charting library to handle arbitrary preprocessing. Preprocessing of data will always be domain specific and does not make sense for a general purpose charting library. 

That being said, the naive solution to your problem, is to preprocess data before passing it to recharts in the first place. You could use https://d3js.org/d3-interpolate/value#interpolateNumber
