### ISSUE TITLE
Yaxis ticks value while rendering

### ISSUE THREAD

**Issue by anshika1422** [recharts/recharts#3679]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I need to fetch the yaxis ticks value , is there a way to achieve it ? and everytime the chart is zoomed in or dragged or zoomed i need to fetch the new set of y ticks value. how could that be achieved in recharts ?

### What does the proposed API look like?
some api through which we can fetch the plotted yaxis ticks everytime the chart is changed

**Comment by ckifer** [comment]
Hi, can you explain what you are trying to accomplish with the tick values?

**Comment by anshika1422** [comment]
We need to find the maximum of the tick value s plotted on the yaxis . We need that maximum yaxis value to compute some data

**Comment by ckifer** [comment]
The max Y value is set by your data, the max Y axis tick is an internal detail. If you want to compute the ticks yourself you can use `ticks` or `ticksGenerator`.

You can also hack `tickFormatter` to calculate the max tick value from. 
See https://codesandbox.io/s/simple-line-chart-forked-d4g3gf?file=/src/App.tsx

**Comment by ckifer** [comment]
Sure, just move the console log inside the useEffect and/or guard it with an if

**Comment by nikolasrieble** [comment]
If you need to compute stats based on the domain, you could consider to pass the domain yourself as a result of your computation. You can also pass the scale.

This example uses a custom scale. https://master--63da8268a0da9970db6992aa.chromatic.com/?path=/story/examples-timeseries--with-d-3-scale

This might help you.

**Comment by ckifer** [comment]
Going to close this as I don't think recharts will expose a way to get the plotted y-axis values, it seems the question has been addressed with the other suggested solutions. Thanks!
