### ISSUE TITLE
Omit specified line/bar/area/etc. from legend and tooltip

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#368]
Is there a way to omit a specific line/bar/area/etc. from the legend and tooltip, other than using a custom content for these? It would be desirable to be able to control what data series appear in the legend and tooltip at the data series component level.

**Comment by xile611** [comment]
@Eric24 Can you give a detail example about how to control the content in payload?  Whatever, It's hard for *recharts* to meets all the needs, so customized `content` is needed.

**Comment by Eric24** [comment]
Yes, I understand that no SDK can possibly meet all needs without customization, but this seems fairly trivial. All I'm looking for is a way to "hide" a child component from appearing in the legend and tooltip. So for example, a Line chart with several Line components where I don't one one or two of those components to appear in the legend/tooltip; by default, all components would appear as they do now, but if I were to set "hide" to true, it would be omitted. As the internal code that builds the legend or tooltip goes through the list of child components, it simply skips any with "hide" set to true.

**Comment by xile611** [comment]
@Eric24 Maybe we can export `DefaultTooltipContent` and `DefaultLegendContent`, then you can do the filter yourself, and use `DefaultTooltipContent` and `DefaultLegendContent` to render tooltip and legend.

**Comment by Eric24** [comment]
Sounds interesting; it would be more flexible overall, but I still think a simple boolean include/omit prop on the child component itself would be useful as well.

**Comment by xile611** [comment]
@Eric24 Any suggestion for the props name ?

**Comment by Eric24** [comment]
Two possible thoughts:

1) Use the existing 'legendType' prop, and omit the data component from both tooltip and legend if it is set to false.

2) Add a new prop called 'legendMode', with options:
true (default) - Include in both tooltip and legend
false - Omit from both tooltip and legend
'tooltip' - Include in tooltip only
'legend' - Include in legend only

Option 1 is probably simpler (and works fine for my use case); option 2 is more flexible (and might work for more use cases).

**Comment by dcousens** [comment]
+1,  recently had this when showing basic error margins around a line,  of similar colour.
Not sure how to remove these margins from the legend.

**Comment by Eric24** [comment]
Any possibility to see this in the next release? Even option 1 ("legendType"=false) would be a tremendous help, and doing that wouldn't preclude the possibility of adding the more flexible "legendMode" option in the future.

**Comment by wuxudong** [comment]
here is some options used in other native framework, like MpAndroidChart:

the Line itself has a prop named "highlightEnabled", if it is set to false, it still has legend, but not displayed in tooltip. And most important. it is not selectable.

like pic in  #563  , data in refer line is very very dense, and user data is sparse.  In current recharts, it is impossible to select x of user line dot.  if refer line 's 'highlightEnabled' is false,  then it will make it very easy to highlight user line's dot.

**Comment by IanVS** [comment]
I also need this, and am willing to submit a PR if we can agree on an approach.  My suggestion would be to add `none` to the options available to `legendType`.  If `legendType='none'`, the legend would be omitted for that component.  That's what I intuitively tried without checking if it was possible, and I was sad when it didn't work.  ;)

**Comment by Eric24** [comment]
@IanVS : legendType='none' is probably fine, although there is a precedent for legendType=false (lots of other props use false to mean "do not render", like line.dot, line.label, etc.)

**Comment by IanVS** [comment]
I'm not picky.  I'd be willing to implement whatever the project maintainers are willing to accept.  What do you think, @xile611?

**Comment by olelivalife** [comment]
Recharts v1.8.5: I have a Composed chart of Line and Area rendering the same value. I only want to display the value once in tooltip so I set legendType="none" in Area chart. But it's still included in the tooltip payload and shown in tooltip. Is this a bug?

**Comment by jakeleventhal** [comment]
@olelivalife have you found a solution to this? I am experiencing the same issue

**Comment by thorbjorn444** [comment]
@olelivalife @jakeleventhal did either one of you solve it? i'm right there with ya

**Comment by zsidnam** [comment]
@olelivalife @jakeleventhal @thorbjorn444 did you try adding the `tooltipType={'none'}` to either the Line or Area component per 73f367f ? I had that same issue but this worked for me. (Was confusing at first because tooltipType has not yet been added to the API docs).

**Comment by SimonSomlai** [comment]
```tsx
  legendType="none"
tooltipType="none"
```

Worked for me

**Comment by olelivalife** [comment]
`tooltipType="none"` hasn't still been added to docs... Anyways, it's not working for me.

I made a custom Legend renderer using the `content` property like this:
```
<ComposedChart>
<Line
  legendType="circle"
/>
<Area
  legendType="none"
/>
{data.length ? (
 <Legend
              // Key needs to be random so that a dot is rendered every time the chart is re-rendered
              // See issue: https://github.com/recharts/recharts/issues/511
              key={Math.random()}
              verticalAlign="top"
              align="right"
              wrapperStyle={{
                left: 0,
                top: 0,
                paddingBottom: 10,
              }}
              iconSize={10}
              content={
                <ChartLegend
                  translations={translations}
                  chartConfig={config}
                  legendKeys={legendKeys}
                />
              }
            />
          ) : null}
<ComposedChart>
```

ChartLegend receives a prop `payload` with data from each legend item.  Here I filter away the items with `legendType="none"` and renders the rest.

**Comment by cle-skov-dk** [comment]
legendType="none" is working but tooltipType="none" is not so this issue should be reopened.

**Comment by natBizitza** [comment]
` legendType='none'` works for me when I add it to the `Line` itself as a prop. Thank you!
