### ISSUE TITLE
can Recharts build boxplot and scatters mixed graph like G2?

### ISSUE THREAD

**Issue by nilyang** [recharts/recharts#369]
I recently want to build a graph with boxplot and scatters graph mixed like G2 did.
[https://g2.alipay.com/demo/01-point/jitter.html](url)

Can Rechats build that ?

**Comment by xile611** [comment]
@nilyang Recharts don't support box-plot now.

**Comment by yezhi780625** [comment]
Is it supported now ?

**Comment by m-apsolon** [comment]
+1 for box plot ones

**Comment by oliverfoster** [comment]
Boxplot is one of those essential data science charts. It's somewhat of a barrier to using this otherwise lovely library that boxplot is not included.

**Comment by DanielWFrancis** [comment]
Also +1 on boxplot

**Comment by programmist** [comment]
+1

**Comment by soconnor-bscs** [comment]
+1

**Comment by TiagoJeronimo** [comment]
+1 for box-plot

**Comment by GavinThomas1192** [comment]
+1 for box-plot.

**Comment by erikhuck** [comment]
+1 for box-plot

**Comment by dimitrispassas** [comment]
+1 for box-plot (with jittered data)

**Comment by just-Bri** [comment]
+1 from me

**Comment by Necrelox** [comment]
+1 box-plot :pleading_face:  all that's missing for me

**Comment by Ger-sh-win** [comment]
+1 from me

**Comment by anantaw81** [comment]
+1 for me pleasee...

**Comment by nikolasrieble** [comment]
At the very least, we should add the above example to the website to document and help others find it easily.

**Comment by nikischin** [comment]
Might be also a case in which https://github.com/recharts/recharts/issues/2788 might be super helpful using a custom component like in the example above!

**Comment by bobmk2** [comment]
@nikolasrieble 

It is a very good idea. 👍 
Is there anything I can  help?

**Comment by ckifer** [comment]
Hey @bobmk2, sure!

You could start by putting the example into a working CodeSandbox. Once we have that its easy enough to copy over to the docs

**Comment by bobmk2** [comment]
Hi, @ckifer 

I made an example boxplot graph in CodeSandbox. 
Please check it. 

[recharts-boxplot-graph - CodeSandbox](https://codesandbox.io/s/recharts-boxplot-graph-lgcixf?file=/src/App.tsx)

 If there is anything missing, please let me know. 🙏

**Comment by nikolasrieble** [comment]
https://github.com/recharts/recharts/pull/3357

**Comment by oliverfoster** [comment]
Thanks for picking this up. Much appreciated. Lovely to see.

**Comment by ckifer** [comment]
https://master--63da8268a0da9970db6992aa.chromatic.com/?path=/story/examples-composedchart-boxplot--box-plot-chart

**Comment by nikolasrieble** [comment]
With the example in this thread and in storybook, we can close the issue.

**Comment by jefersonprediza** [comment]
stoker are not boxplots. This suggested workaround doesn't work because you need the median and error in addition to the error bars in a boxplot.

**Comment by ckifer** [comment]
@jefersonprediza those attributes are present in the example https://github.com/recharts/recharts/blob/master/storybook/stories/data/BoxPlot.ts#L3-L28

https://github.com/recharts/recharts/blob/master/storybook/stories/Examples/ComposedChart/BoxPlot.stories.tsx#L54-L94

**Comment by jefersonprediza** [comment]
Hi,

Where are the outliers? 

See "Complications" on page https://web.pdx.edu/~stipakb/download/PA551/boxplot.html

**Comment by ckifer** [comment]
@jefersonprediza Taking a look here https://d3-graph-gallery.com/boxplot.html (your link as well)

I think we've satisfied the most basic of cases, as well as having multiple plots. Outliers however, do not exist in the current example except as 1 single data point (the average in this case).

I think this example could be modified to account for many outliers
For example (this is me just hacking, but it works well enough)
https://codesandbox.io/s/recharts-boxplot-graph-outlier-support-5ggw86
![image](https://github.com/recharts/recharts/assets/25180830/a683b605-4100-4925-9374-fa5775b94ca7)

**Comment by nikischin** [comment]
@ckifer thank you so much again for the example also from my side! However to me this feels super hacky and nothing I would want to rely on. We actually do intend a very similar implementation of a chart, though will most likely go for Plotly for our Multi Boxplot Chart although using Recharts on all our other Charts already. 

I think the custom components again could change my mind here, though I do understand that this is something requiring more work to put in.

**Comment by ckifer** [comment]
@nikischin sure! and... I totally agree 😅. Here I'm just trying my best to get to some sort of solution with what we currently have - a new chart type isn't going to be able to be on the radar any time soon (unless someone contributes it). This is because of many factors, but mostly because the few that contribute to recharts are doing it in their spare time which comes in spurts or not at all.

There are some more pressing macro issues that need time and attention to address and in the meantime I'll do my best to give workarounds like this one where I can.

What I will do is re-open #2302 and use it to track a new chart type specific to box plot. If someone wants to contribute that as a feature, I am happy to review and merge it in

**Comment by akjacaranda** [comment]
Since this issue was still helpful to finding and adapting the box plot example in 2025, here's a hack using a `Scatter` to get a more consistent median line

```js
const MedianBar = (props) => {
  const { cx, cy, yAxis } = props;
  if (cx == null || cy == null || yAxis == null) {
    return null;
  }
  return (
    <line x1={cx} y1={cy - yAxis.bandSize / 2} x2={cx} y2={cy + yAxis.bandSize / 2} stroke={#000} strokeWidth={3} />
  );
}
```

^For a vertical chart

Drop the middle `HorizonBar` and prior to the average `Scatter` add
`<Scatter dataKey="median" shape={<MedianBar />} />`

If `barCategoryGap` is known the "divide by 2" can be tweaked to make the line fit the bar width. Hey, it's a hack!

**Comment by ranjith-pl** [comment]
Hi,

Where are the outliers?

**Comment by ranjith-pl** [comment]
Hi @ckifer ,

Can you please explain how to use outliers in box plot?

**Comment by ghost** [comment]
Hi @ckifer

Can you please explain how to use outlier in box plot. codeSandbox link is not work 
https://codesandbox.io/s/recharts-boxplot-graph-outlier-support-5ggw86

**Comment by ckifer** [comment]
The code here should help https://github.com/recharts/recharts/blob/main/storybook/stories/Examples/ComposedChart/BoxPlot.stories.tsx

Same code as the sandbox

**Comment by ghost** [comment]
@ckifer , I have tried many ways but scatter outlier dots properly not fit in repective vertical line. 

Please check this ref image - https://prnt.sc/awCqz39Ckvrf

**Comment by ckifer** [comment]
the example probably only takes into account a single bar for each category. If you provide a working reproduction I can try to help at some point
