### ISSUE TITLE
Sankey Charts highlight the node and link

### ISSUE THREAD

**Issue by aryanbhatt-clvt** [recharts/recharts#3695]
How can we highlight the link upon hovering over a node. I want to see the links highlighted of a particular node when I hover over that node.

**Comment by aryanbhatt-clvt** [comment]
Something like this:
https://jsfiddle.net/stevenclarkclarivate/q6moazub/48/

**Comment by ckifer** [comment]
Here is a sandbox with a setup to try and solve this without library changes (I don't have time to try atm)
https://codesandbox.io/s/simple-line-chart-forked-xvzxxf?file=/src/App.tsx

But essentially you would create custom components for Node and Link and pass the currently hovered index to that component, then change the styles of each accordingly.

Will label this as a feature request though

**Comment by aryanbhatt-clvt** [comment]
Okay, meanwhile I will try to implement some fix.

**Comment by aryanbhatt-clvt** [comment]
Is there a way we can apply different colors per name?

**Comment by ckifer** [comment]
https://codesandbox.io/s/simple-line-chart-forked-xvzxxf?file=/src/App.tsx

**Comment by aryanbhatt-clvt** [comment]
I was able to apply Highcharts like in the above link.
