### ISSUE TITLE
Overflow issue outside the graphics area.

### ISSUE THREAD

**Issue by Rtoprakci** [recharts/recharts#3699]
Hello, in the image provided below, the data is overflowing outside the graphics area. How can I solve this issue? The code I'm using is provided below. My current Recharts version is v2.7.3

          {
            chartData[0].deflection &&
            <ResponsiveContainer className="mt-10" width="100%" height={500}>
              <LineChart
                data={chartData} margin={{ top: 5, right: 5, left: 15, bottom: 50, }}
              >
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis tickCount={10} dataKey="date" angle={-45} textAnchor="end"
                  tickFormatter={(tick) => {
                    const date = new Date(tick);
                    const year = date.getFullYear();
                    const month = String(date.getMonth() + 1).padStart(2, "0");
                    const day = String(date.getDate()).padStart(2, "0");
                    return `${year}-${month}-${day}`;
                  }}
                />
                <YAxis tickCount={10} tickFormatter={(value) => value.toFixed(1)} type="number" unit="mm" domain={[0, 'auto']} />
                <Tooltip />
                <Legend formatter={() => "Sapma"} align="right" verticalAlign="top" />
                <Line type="linear" dot={false} name="Sapma" dataKey="deflection" unit="mm" stroke="#00bfff" />
              </LineChart>
            </ResponsiveContainer>
          }

![image](https://github.com/recharts/recharts/assets/93008706/16ac1e3e-deed-4ea8-a710-d19222fa46d9)

**Comment by nikolasrieble** [comment]
Sure, you can fix it by not defining the domain to start at 0. `domain={[0, 'auto']}`

How about just not defining it?

**Comment by Rtoprakci** [comment]
> Sure, you can fix it by not defining the domain to start at 0. `domain={[0, 'auto']}`
> 
> How about just not defining it? Or try `domain={['auto', 'auto']}` alternatively.

Even when I select this option, the issue of overflowing outside the graph area still persists.

**Comment by nikolasrieble** [comment]
I can not reproduce the problem. Please create a toy reproduction including a dataset, such as
https://codesandbox.io/s/simple-line-chart-forked-dlggry?file=/src/App.tsx

**Comment by ckifer** [comment]
Going to close this as unreproduceable/no response
