### ISSUE TITLE
div inside custom LabelList

### ISSUE THREAD

**Issue by SamyZog** [recharts/recharts#3703]
Is is possible to render a custom LabelList using tags not specific to svg? When I use a div it just disappears?

**Comment by ckifer** [comment]
You can only render non-svg  element types within a `foreignObject` tag
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject

So at the end of the day things still need positioned with SVG properties
https://codesandbox.io/s/line-chart-with-customized-label-forked-xp26ky?file=/src/App.tsx

**Comment by ckifer** [comment]
Going to close this as answered, please comment back if you have any questions
