### ISSUE TITLE
Testing Recharts: Jest --> Vitest 

### ISSUE THREAD

**Issue by nikolasrieble** [recharts/recharts#3704]
We have in the past introduced victory-vendor to import d3, fixing a critical security issue with the lowest possible effort. 

Now we want to properly fix it, reverting the initial change, and upgrading d3. 

One of the major issues we are facing after the upgrade is most of the jest tests fail, 
https://github.com/recharts/recharts/actions/runs/5860401123/job/15888379614?pr=3702

We found a [blog](https://blog.isquaredsoftware.com/2023/08/esm-modernization-lessons/) describing both vitest as a solution as well as the ease of migration. 

Lets verify that vitest solves the problem, and if yes, lets switch to vitest.

**Comment by ckifer** [comment]
Caveat to this is that a lot of our consumers will continue to use jest and aren't going to switch just to solve test execution problems. If we do release an update to vitest, we need a dummy project that builds in our CI/CD and runs Jest tests that import (basic rendering) of recharts components. This sounds like a pain but it will for sure come up as a pain point for our consumers

**Comment by ckifer** [comment]
I mean vitest is objectively faster and a better user experience. I would advocate for it either way. But if it's easier for us to mitigate risk by sticking with jest then that's probably okay (just a pain)
