### ISSUE TITLE
Isomorphic rendering crashes when document is available in the backend.

### ISSUE THREAD

**Issue by gartz** [recharts/recharts#371]
We have `document` available in the backend, th `isSrv` check for that and them renders and give a bad checksum because of the animations probably.

Ex:
```
(client) d="clipPath1480374909864" data-reactid=" (server) d="clipPath1480374908124" data-reactid="
```

Would be nice if we could pass a prop or context to tell it's being rendered by the server. That way anyone can patch the way they want to tell that is a server rendering.

This is with animations disabled, I'm using pie chart.

**Comment by xile611** [comment]
@gartz `isSsr` is called at many places. It's strange to initialize this function. Any suggestion for safe `isSsr` ?

**Comment by gartz** [comment]
detect the environment is not a responsibility of recharts, any implementation you do will fail over time with different environments contexts.

This is a good use-case for React Context:

```
RechartsComponent.contextTypes = {
  rechartsServerRendering: React.PropTypes.bool
};
```

In your component you can get using:
```
this.context.rechartsServerRendering
// or pure functions
function RechartsComponent(props, context) {
  context.rechartsServerRendering
}
```

Let the developer implement their logic to detect the server side.

If you want to launch a version that deprecates your isSsrv implementation without breaking the current implementation, check if that context variable is `undefined` if it's, uses the old implementation otherwise trust in the boolean from `context.rechartsServerRendering`.

I suggest a long name, because contexts will transverse the whole application, and if you use `serverRendering` it might conflict with other projects implementations.

More info at: https://facebook.github.io/react/docs/context.html

A good example in how contexts are implemented correctly is react-router, they use to transport their router instance over to the children components of `<Router>`.

You can use the same approach creating a context element called `<Recharts>` where the dev can add to the root of his react structure and define global configs such as `serverRendering`, ex:

```
<Recharts serverRendering={ myLogicReturnsBoolean() }>
  <MyProject structure>
    ... other recharts components anywhere here will know if is server rendering
  </MyProject>
</Recharts>
```
