### ISSUE TITLE
LineChart not rendering for safari(v16.5) on mac and not on chrome,brave and safari on iPhone OS(v16.6)

### ISSUE THREAD

**Issue by anmol5varma** [recharts/recharts#3710]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://64e225bce1a5b46f4f02c972--netlify-thinks-anmol5varma-is-great.netlify.app/](https://64e225bce1a5b46f4f02c972--netlify-thinks-anmol5varma-is-great.netlify.app/)

### Steps to reproduce
One this link on chrome and then on safari on mac or open it on iPhone in any browser. It only works on chrome in mac where it'll show a simple line chart between 2 points

### What is expected?
The same line chart should render on all browsers and platforms

### What is actually happening?
The line chart is not rendering in iPhone and safari in mac.

| Environment | Info |
|---|---|
| Recharts | v2.7.3 |
| React | "react": "^18.2.0", |
| System | mac OS 13.4, iPhone OS 16.6 |
| Browser | chrome,brave,safari |

**Comment by ckifer** [comment]
Can you modify this sandbox to add some example data/to reproduce? https://codesandbox.io/s/simple-line-chart-browser-issue-ylm4hp

Firefox, etc. throws these errors while chrome does not - if we can find where then I'll be able to tell if its a code issue or a recharts browser support issue

**Comment by ckifer** [comment]
Going to close this as stale, feel free to comment back to continue discussion

**Comment by schienieder** [comment]
I am using shadcn charts which just uses recharts https://ui.shadcn.com/charts. Using it on chrome, firefox and any other browser/environment work fine except on ios/mac. 

The issue is that it is not correctly aligned vertically.
Using IPad:
![60101f06-c067-40f8-8032-6dca0d8f69de](https://github.com/user-attachments/assets/ddfb1d25-a79b-465e-982d-aff12ae616c0)


Web Browser (Chrome):
![26693d90-05c6-4956-8105-77b1d5fc7fe0](https://github.com/user-attachments/assets/94403d38-63e3-4623-96b7-f077a93c3eff)

**Comment by schienieder** [comment]
I can't seem to replicate it in sandbox, but here's the code:

```
"use client";

import {
	Label,
	PolarGrid,
	PolarRadiusAxis,
	RadialBar,
	RadialBarChart,
} from "recharts";
import { ChartConfig, ChartContainer } from "@/components/ui/chart";

const chartConfig = {
	visitors: {
		label: "Visitors",
	},
} satisfies ChartConfig;

export function CircularProgress() {
	const chartData = [
		{
			visitors: 27, // Dynamic progress value
			fill: "#f1592a", // Background color for the progress
		},
	];

	return (
		<ChartContainer
			config={chartConfig}
			className="aspect-square max-h-[250px] w-full flex items-center justify-center">
			<RadialBarChart
				data={chartData}
				startAngle={90} // Start angle for the radial bar
				endAngle={90 + (360 * 27) / 100} // Calculate end angle based on progress
				innerRadius={80}
				outerRadius={110}>
				<PolarGrid
					gridType="circle"
					radialLines={false}
					stroke="none"
					className="first:fill-muted last:fill-background"
					polarRadius={[86, 74]}
				/>
				<RadialBar dataKey="visitors" cornerRadius={10} />
				<PolarRadiusAxis tick={false} tickLine={false} axisLine={false}>
					<Label
						content={({ viewBox }) => {
							if (viewBox && "cx" in viewBox && "cy" in viewBox) {
								const { cx, cy } = viewBox;
								return (
									<text
										x={cx}
										y={cy}
										textAnchor="middle"
										dominantBaseline="middle"
										className="fill-foreground text-4xl font-bold">
										<tspan>{`${10}/${35}`}</tspan>
										<tspan
											x={cx}
											dy="1.8em"
											className="fill-muted-foreground text-sm font-normal">
											You Scored
										</tspan>
									</text>
								);
							}
						}}
					/>
				</PolarRadiusAxis>
			</RadialBarChart>
		</ChartContainer>
	);
}
```

**Comment by ckifer** [comment]
If you resize your chart in the browser does it cause the same issue?
