### ISSUE TITLE
Consistent interface: Line / Bar - activeDot/ activeBar

### ISSUE THREAD

**Issue by nikolasrieble** [recharts/recharts#3723]
The Line exposes activeDot, which enables the user to customise how the tooltip interaction is rendered. 
Naively I would expect the Bar to have a similar interface for activeBar.

Suggestion: 
- Align the interface across components, and add to the bar the identical functionality and interface as exists for the Line, see https://recharts.org/en-US/api/Line#activeDot

**Comment by andrewangelle** [comment]
@nikolasrieble I'm taking a stab at this if you want to assign it to me.

**Comment by ckifer** [comment]
merged #3756 - will be released next minor barring no issues

**Comment by ckifer** [comment]
released in 2.9
