### ISSUE TITLE
labels/ticks on axis are not evenly spaced

### ISSUE THREAD

**Issue by christopherkindl** [recharts/recharts#3725]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://user-images.githubusercontent.com/53372002/265078572-dbc52b4d-faa7-453e-9ddf-3c49370f829a.png](https://user-images.githubusercontent.com/53372002/265078572-dbc52b4d-faa7-453e-9ddf-3c49370f829a.png)

### Steps to reproduce
n/a

### What is expected?
ticks/labels should be evenly spaced

### What is actually happening?
There are some cases in which the gap between two labels is larger than the rest of it. This also happens on the y-axis. See image -> https://user-images.githubusercontent.com/53372002/265078572-dbc52b4d-faa7-453e-9ddf-3c49370f829a.png

| Environment | Info |
|---|---|
| Recharts | v2.8.0 |
| React | 18.0.0 |
| System | Mac |
| Browser | Chrome |

**Comment by ckifer** [comment]
hey @christopherkindl, can you check out this issue from yesterday and see if any of those options help?

https://github.com/recharts/recharts/issues/3724

But in order to help more we'll need more details like what your XAxis looks like, etc

**Comment by ckifer** [comment]
Going to relate this to https://github.com/tremorlabs/tremor/issues/647

**Comment by christopherkindl** [comment]
@ckifer This issue can be closed, relates to this one as suggested by you: https://github.com/recharts/recharts/issues/3724

Can give updates here if we get some helpful hints in our open issue.
