### ISSUE TITLE
Tooltip Story

### ISSUE THREAD

**Issue by d-gottlieb** [recharts/recharts#3735]
Create Tooltip story for Storybook following `Line.stories.tsx`.

Using the [old API documentation](https://recharts.org/en-US/api/Tooltip) as a guide, create the Tooltip story.

Acceptance Criteria:

All information regarding the Tooltip in the old API docs should be used to create the Story.
All props and their respective categories should either be taken from or added to the props constants.

**Comment by ckifer** [comment]
@Nkiriobasi we'll assign things one at a time. Feel free to take the first one assigned and after a PR from that one we'll assign the next.

**Comment by Nkiriobasi** [comment]
Alright

**Comment by ckifer** [comment]
Thanks @PavelVanecek - closing this!
