### ISSUE TITLE
Text Story

### ISSUE THREAD

**Issue by d-gottlieb** [recharts/recharts#3737]
Create Text story for Storybook following `Line.stories.tsx`.

Using the [old API documentation](https://recharts.org/en-US/api/Text) as a guide, create the Text story.

Acceptance Criteria:

- All information regarding the Text in the old API docs should be used to create the Story.
- All props and their respective categories should either be taken from or added to the props constants.

**Comment by Nkiriobasi** [comment]
Please, can I take this up?

**Comment by wanisramdani** [comment]
Would love to work on this

**Comment by ckifer** [comment]
Assigned

**Comment by ckifer** [comment]
Closed by #3751
