### ISSUE TITLE
Customized Story

### ISSUE THREAD

**Issue by d-gottlieb** [recharts/recharts#3740]
Create Customized story for Storybook following `Line.stories.tsx`.

Using the [old API documentation](https://recharts.org/en-US/api/Customized) as a guide, create the Customized story.

Acceptance Criteria:

- All information regarding the Customized component in the old API docs should be used to create the Story.
- All props and their respective categories should either be taken from or added to the props constants.

**Comment by Nkiriobasi** [comment]
Please, can I take this up?

**Comment by Shashangbhagat** [comment]
Hi @d-gottlieb 
Can I take this one, Please ?

**Comment by ckifer** [comment]
Assigned
