### ISSUE TITLE
RadialBar Polar Story

### ISSUE THREAD

**Issue by d-gottlieb** [recharts/recharts#3741]
Create RadialBar story for Storybook following `Line.stories.tsx`.

Using the [old API documentation](https://recharts.org/en-US/api/RadialBar) as a guide, create the RadialBar story.

Acceptance Criteria:

- All information regarding the RadialBar in the old API docs should be used to create the Story.
- All props and their respective categories should either be taken from or added to the props constants.

**Comment by Nkiriobasi** [comment]
Please, can I take this up?

**Comment by samtmorgan** [comment]
Hi @d-gottlieb
I'd like to work on this.
Can you please assign me please?

**Comment by ckifer** [comment]
Assigned

**Comment by nikolasrieble** [comment]
Just landed
