### ISSUE TITLE
Chart is not updating with useState or other hooks. I have some initial values at chart datas and it renders succesfully but when I am trying to update chart datas, chart is not updating.

### ISSUE THREAD

**Issue by FlyingTurkman** [recharts/recharts#3747]
I must convert datas to chart data so I am using useState and useEffect hooks for updating and converting datas bu rechart is not updating with new datas.

```tsx
//example for hooks
const [paymentList, setPaymentList] = useState<paymentType[]>(payments || [])
const [data, setData] = useState<dataMonthType[]>([])
useEffect(() => {
    convertPaymentsToChartData()
}, [paymentList])

//example function for update data
async function convertPaymentsToChartData() {
     const resData = await fetch('.....')
     const res = await resData.json()
     let newData = res.map((r) => {
           //converting datas here
            return convertedData
      })
      setData(newData)
}
```

**Comment by ckifer** [comment]
@FlyingTurkman are you able to give a codesandbox reproduction? There are a lot of examples of state changes resulting in correct re-rendering of charts.

it looks like you aren't awaiting your `convertPaymentsToChartData` function in your useEffect?

**Comment by FlyingTurkman** [comment]
> @FlyingTurkman are you able to give a codesandbox reproduction? There are a lot of examples of state changes resulting in correct re-rendering of charts.
> 
> it looks like you aren't awaiting your `convertPaymentsToChartData` function in your useEffect?

Somehow its working on codesandbox. I will response when I figure it out.

**Comment by FlyingTurkman** [comment]
I figured it out. If I convert data out of component and send it as prop its working my bad.
