### ISSUE TITLE
Use lodash individual packages imports instead of the entire thing

### ISSUE THREAD

**Issue by ckifer** [recharts/recharts#3752]
## Do you want to request a feature or report a bug?
Bundle Size Improvement

We currently have `lodash` as a dependency. `lodash` is known to be large and not have great tree-shaking.
https://lodash.com/per-method-packages

Instead of relying on all of `lodash`, how about we use the lodash individual packages such as `lodash.groupBy`, etc.

## Acceptance Criteria 

1. Remove all `import _ from lodash`
2. Identify what functions are used in the project 
3. import all individual functions directly like `import isFunction from 'lodash/isFunction'`
4. Replace all instances of `_` with the equivalent function from individual packages
5. Run tests and confirm behavior where needed

**Comment by hamzaM98** [comment]
Hello, Can I take this?

**Comment by hmza98** [comment]
Hello, Can i take this?

**Comment by nikolasrieble** [comment]
It is not clear whether this effort would result in a large gain as to https://www.blazemeter.com/blog/import-lodash-libraries

> The smallest bundle size could also be reached by using the babel-plugin-lodash together with lodash-webpack-plugin for cherry-picking only the used functions.

**Comment by nikolasrieble** [comment]
It seems that there are a few caveats though: https://www.npmjs.com/package/lodash-webpack-plugin

> DISCLAIMER: Using this plugin without enabling the proper feature sets may cause lodash functions to behave in unexpected ways. Methods may appear to work, however they might return incorrect results.

**Comment by ckifer** [comment]
It should amount to roughly the same gain. 

The issue with the plugin is that consumers attempt to use it and leave out functions that we use internally causing breakage for them. If we only include the packages we use then no one has to do anything special to get bundle size reduction

**Comment by nikolasrieble** [comment]
I am looking into it, and will start with deprecating lodash for native functions where possible / reasonable. 

See https://www.npmjs.com/package/lodash.isarray for example

**Comment by ckifer** [comment]
Sounds good, would much rather not have lodash at all except for specific and complex things (groupBy is something I always use in my projects for example)

**Comment by nikolasrieble** [comment]
Reading more into this, it seems importing lodash from different packages is discouraged. https://lodash.com/per-method-packages

Instead, the suggest way to go, is to import specific methods by path, as in 
```
import capitalize from 'lodash/capitalize';
```

That can nicely be done in a single PR, since it merely is a change of import.

**Comment by ckifer** [comment]
Oh, RIP 😅. I should have researched more. 

Cool! Much easier then

**Comment by ckifer** [comment]
Updated issue

**Comment by nikolasrieble** [comment]
Released with https://github.com/recharts/recharts/releases/tag/v2.10

**Comment by tomtom94** [comment]
Not working I am having typescript issues now

<img width="566" alt="image" src="https://github.com/recharts/recharts/assets/262550/9a38d9cd-e8cc-4017-8685-3a2442aead7a">

<img width="540" alt="image" src="https://github.com/recharts/recharts/assets/262550/1a46975a-6f7a-4c39-b1d8-501827f05e74">

**Comment by tomtom94** [comment]
I am sorry but direct import doesn't work

<img width="576" alt="image" src="https://github.com/recharts/recharts/assets/262550/88efd864-1ab4-4b1b-b38e-476bb2873ea6">

<img width="538" alt="image" src="https://github.com/recharts/recharts/assets/262550/ed7a227d-0521-4fdf-b2da-b931fff6140e">

I am using the latest recharts' version 
`"recharts": "^2.12.7"`

**Comment by ckifer** [comment]
I don't think that ever worked. This issue is about lodash which is unrelated

**Comment by tomtom94** [comment]
Would it be possible to do such an import in the future ?

`import Bar from 'recharts/Bar'`

**Comment by ckifer** [comment]
Sure once we add exports for ESM. As of right now having that import style wouldn't help anything though because everything always goes through the same generator function which unfortunately brings in almost everything. 

Once 3.x is out we'll try to go after bundle size. For now it is what it is
