### ISSUE TITLE
<Legend/> should warn users to pass a name to a chart's cartesian components when a function is used as a dataKey.

### ISSUE THREAD

**Issue by chris-mcdonald-dev** [recharts/recharts#3757]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-h5mxx9)

### Steps to reproduce
See https://github.com/recharts/recharts/issues/3749

### What is expected?
Need to prevent callback function from being called without the payload as a parameter. Instead, it should prompt API users to use the `name` property on the cartesian component being used and render and empty string instead.

### What is actually happening?
See https://github.com/recharts/recharts/issues/3749

| Environment | Info |
|---|---|
| Recharts | v2.8.0 |
| React | 18.2 |
| System | Ubuntu 22.04 |
| Browser | Edge 116 |

**Comment by chris-mcdonald-dev** [comment]
Have PR fix ready. Pushing soon.

**Comment by ckifer** [comment]
Fixed! Closing this up
