### ISSUE TITLE
Add animation to Bars on BarChart

### ISSUE THREAD

**Issue by matthewberkompas** [recharts/recharts#376]
@xile611 I have a bar chart and I want each bar to grow bigger when someone hovers their mouse over it. Is there any easy way to do this currently with CSS or JS that I missed? I wasn't able to find anything after looking through the issues and docs.

**Comment by xile611** [comment]
@matthewberkompas For simple style change, you can use css. But for transform, you can use customized events like [this demo](http://jsfiddle.net/fwh9Lmg3/).

**Comment by matthewberkompas** [comment]
Awesome! That's exactly what I'm looking for. Thanks for taking the time to do this @xile611.

**Comment by matthewberkompas** [comment]
@xile611 Just to clarify, this will work or a stacked bar chart too, right?

**Comment by matthewberkompas** [comment]
One more question: is there a way to change the _color_ of a bar when you hover over it @xile611?

**Comment by xile611** [comment]
@matthewberkompas  You only need to add some css like the following:

```
.recharts-bar .recharts-bar-rectangle .recharts-rectangle:hover {
  fill: red;
}
```
[demo](http://jsfiddle.net/fwh9Lmg3/16/)

**Comment by matthewberkompas** [comment]
@xile611 I have a _stacked_ bar chart so I'm looking to make the _whole_ bar change color when I hover over one part of it and not just that single part of the bar like it does [in this example](http://jsfiddle.net/matthewberkompas/wa87o60f/). Is that possible?

**Comment by xile611** [comment]
@matthewberkompas In such case, you should use customized events, It can't be done only by css.
In your demo, you only need to add `fill` in `Rectangle`.

```
<Rectangle {...others} x={x - 2} width={width + 4} y={y - sign * 2} height={height + sign * 2} fill="red" />
```

[demo](http://jsfiddle.net/wa87o60f/2/)

**Comment by matthewberkompas** [comment]
@xile611 This answers my questions. Thanks a ton for your help here!
