### ISSUE TITLE
Consistent interface: Line / Bar / Funnel - activeDot / activeBar / activeShape

### ISSUE THREAD

**Issue by andrewangelle** [recharts/recharts#3765]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-ms3vpd?file=/src/index.js)

### Steps to reproduce
Hover over a section of the funnel. Notice activeShape prop is ignored

### What is expected?
I'd expect the customized active shape to render according to the active tooltip the same way that activeDot/Line and activeBar/Bar work respectively.

### What is actually happening?
The activeShape prop is being ignored

| Environment | Info |
|---|---|
| Recharts | v2.8.0 |
| React | 18.2.0 |
| System | macOS Ventura 13.5.2 |
| Browser | Chrome v116.0.5845.179 |

**Comment by andrewangelle** [comment]
I'm working on a fix for this if you want to assign it to me. @ckifer @nikolasrieble

**Comment by ckifer** [comment]
🚀
