### ISSUE TITLE
export 'curveBumpX' (imported as 'curveBumpX') was not found in 'victory-vendor/d3-shape' 

### ISSUE THREAD

**Issue by DominicTobias** [recharts/recharts#3779]
Hi, I've installed 2.8.0 and it produces the following warning:

```
Compiled with problems:
×
WARNING in ../node_modules/recharts/es6/shape/Curve.js 24:14-24
export 'curveBumpX' (imported as 'curveBumpX') was not found in 'victory-vendor/d3-shape' (possible exports: arc, area, areaRadial, curveBasis, curveBasisClosed, curveBasisOpen, curveBundle, curveCardinal, curveCardinalClosed, curveCardinalOpen, curveCatmullRom, curveCatmullRomClosed, curveCatmullRomOpen, curveLinear, curveLinearClosed, curveMonotoneX, curveMonotoneY, curveNatural, curveStep, curveStepAfter, curveStepBefore, line, lineRadial, linkHorizontal, linkRadial, linkVertical, pie, pointRadial, radialArea, radialLine, stack, stackOffsetDiverging, stackOffsetExpand, stackOffsetNone, stackOffsetSilhouette, stackOffsetWiggle, stackOrderAscending, stackOrderDescending, stackOrderInsideOut, stackOrderNone, stackOrderReverse, symbol, symbolCircle, symbolCross, symbolDiamond, symbolSquare, symbolStar, symbolTriangle, symbolWye, symbols)
WARNING in ../node_modules/recharts/es6/shape/Curve.js 25:14-24
export 'curveBumpY' (imported as 'curveBumpY') was not found in 'victory-vendor/d3-shape' (possible exports: arc, area, areaRadial, curveBasis, curveBasisClosed, curveBasisOpen, curveBundle, curveCardinal, curveCardinalClosed, curveCardinalOpen, curveCatmullRom, curveCatmullRomClosed, curveCatmullRomOpen, curveLinear, curveLinearClosed, curveMonotoneX, curveMonotoneY, curveNatural, curveStep, curveStepAfter, curveStepBefore, line, lineRadial, linkHorizontal, linkRadial, linkVertical, pie, pointRadial, radialArea, radialLine, stack, stackOffsetDiverging, stackOffsetExpand, stackOffsetNone, stackOffsetSilhouette, stackOffsetWiggle, stackOrderAscending, stackOrderDescending, stackOrderInsideOut, stackOrderNone, stackOrderReverse, symbol, symbolCircle, symbolCross, symbolDiamond, symbolSquare, symbolStar, symbolTriangle, symbolWye, symbols)
```

Doesn't break but does cause a big warning overlay in React:

<img width="1062" alt="Screenshot 2023-09-22 at 4 42 47 PM" src="https://github.com/recharts/recharts/assets/760314/56f24adc-477c-47d3-9ce5-5112886ecfb4">

I'm not using anything special just tried the LineChart demo:

```jsx
<LineChart
  width={730}
  height={250}
  data={data}
  margin={{ top: 25, right: 30, left: 20, bottom: 5 }}
>
  <CartesianGrid strokeDasharray="3 3" />
  <XAxis dataKey="name" />
  <YAxis />
  <Tooltip />
  <Legend />
  <Line type="monotone" dataKey="pv" stroke="#8884d8" />
  <Line type="monotone" dataKey="uv" stroke="#82ca9d" />
</LineChart>
```

I think victory-vendor does some build time stuff to create a subset of d3 (didn't look deep) and I have d3 `4.13.0` as a dep in my project don't know if that makes a diff.

**Comment by ckifer** [comment]
Thanks for the report. Are you by chance forcing ESM with "type": "module" in your package.json?

@nikolasrieble fyi

**Comment by DominicTobias** [comment]
> Thanks for the report. Are you by chance forcing ESM with "type": "module" in your package.json?
> 
> @nikolasrieble fyi

No I'm not

**Comment by ckifer** [comment]
But yeah that's exactly what victory-vendor does. Can you try downgrading d3 to 3.x once? Just to see if it makes the issue go away

**Comment by DominicTobias** [comment]
Ah yeah I tried with d3 `3.5.16` and the warning went away

**Comment by ckifer** [comment]
The current version of Victory vendor we're using tracks 3.x so there might be a conflict in the breaking change between d3 3.x and 4.x

**Comment by DominicTobias** [comment]
Ok cool, latest version is 7 so might have a few with this issue. Might help if 3x is a peerDepedency to get a warning and make it more obvious. Anyway feel free to close if using v3 is the supported way!

**Comment by ckifer** [comment]
Oh yeah thats what it looks like - I'd try upgrading d3 to whatever d3 version uses 3.x of d3-shape

**Comment by DominicTobias** [comment]
I've upgraded to d3 v7 which matches the dep and it works now, thanks for the help!
