### ISSUE TITLE
onClick for Axes 

### ISSUE THREAD

**Issue by patryk0605** [recharts/recharts#378]
Referencing the following example:

```jsx
<ComposedChart layout="vertical" data={data} onClick={::this.requestTagsWithPattern} >
  <XAxis type="number"/>
  <YAxis dataKey="name" type="category" width={300} onClick={::this.requestTagsWithPattern}/>
  <CartesianGrid stroke="#f5f5f5"/>
  <Tooltip/>
  <Legend />
  <Bar dataKey="OS" barSize={20} fill="#8884d8" />
</ComposedChart>
```

Does  `onClick` work for `XAxis` and `YAxis`? When `onClick` is set on `ComposedChart`, it triggers when `Bar` is clicked and I am able to obtain the values from element returned, but none of the other components under `ComposedChart` seem to trigger the handler. I put the `onClick` event on `YAxis` and that does cause the handler to trigger, however `YAxis` only returns `null`. Is there  a way I can get the value of the `YAxis` on click? For example, if the label on `YAxis` **A** is clicked - return element containing value **A**.

**Comment by xile611** [comment]
@patryk0605 Events  are not supported in `XAxis` and `YAxis`. It'll be done in next version.

**Comment by patryk0605** [comment]
@xile611 Super! Thanks for the continued great support.
