### ISSUE TITLE
Recharts 3.0.0: Upgrade d3 - Enable running jest

### ISSUE THREAD

**Issue by nikolasrieble** [recharts/recharts#3780]
This is the sister issue to: https://github.com/recharts/recharts/issues/3781

We need one of the two solutions.

One of the larger goals of Recharts 3.0.0 is to revert the usage of victory-vendor and instead upgrade d3-scale. I started this endeavour on this branch https://github.com/recharts/recharts/pull/3702

The problem I met was that I could not get jest to run. One solution could be to use vitest instead, and while that seems to (partially) work, it does lead to new issues / challenges. 

The goal of this issues is to instead get jest to work. 

Acceptance critera: 

- Branch off of this branch https://github.com/recharts/recharts/pull/3702
- Make `npm run test` work 😅

**Comment by ckifer** [comment]
this might be better said that we need to make sure consumers can run jest with recharts components once/if we move victory-vender to d3@latest

**Comment by ckifer** [comment]
Actually thats covered in https://github.com/recharts/recharts/issues/3897

Going to close this one
