### ISSUE TITLE
Recharts 3.0.0: Upgrade d3 - Migrate the last tests to vitest

### ISSUE THREAD

**Issue by nikolasrieble** [recharts/recharts#3781]
This is the sister issue to: https://github.com/recharts/recharts/issues/3780

We need one of the two solutions. 

One of the larger goals of Recharts 3.0.0 is to revert the usage of victory-vendor and instead upgrade d3-scale. I started this endeavour on this branch https://github.com/recharts/recharts/pull/3702

The problem I met was that I could not get jest to run. One solution could be to use vitest instead, and while that seems to (partially) work, it does lead to new issues / challenges.

In this branch, I have migrated most tests to vitest, quite swiftly. Only a few tests are remaining. The goal of this issue is to migrate the last tests as well. 

Acceptance critera:

- [ ] Branch off of this branch https://github.com/recharts/recharts/pull/3705
- [ ] Make npm run test

**Comment by ckifer** [comment]
this is done, closing
