### ISSUE TITLE
Warnings when data is aray of arays

### ISSUE THREAD

**Issue by vyachekg** [recharts/recharts#379]
Simple example with a **Scatter** 
```
<ScatterChart width={600} height={400} margin={{ top: 20, right: 20, bottom: 20, left: 20 }}>
      	<XAxis dataKey={0} name="stature" unit="cm" />
      	<YAxis dataKey={1} name="weight" unit="kg" />
        <CartesianGrid />
      	<Tooltip cursor={{ strokeDasharray: '3 3' }} />
      	<Scatter name="A school" data={**test**} fill="#8884d8" line shape="cross" />
</ScatterChart>
```

Where **test** is array of arrays
const test = [[0, 0], [1, 1], [2, 2]];

It works, but I get Warnings

> Failed prop type: Invalid prop `points[0].payload` of type `array` supplied to `AnimationDecorator(Scatter)`, expected `object`.
>     in AnimationDecorator(Scatter) (created by FocusChart)
>     in ScatterChart

and 

> Failed prop type: Invalid prop `points[0].payload` of type `array` supplied to `Scatter`, expected `object`.
>     in Scatter (created by AnimationDecorator(Scatter))
>     in AnimationDecorator(Scatter)

As it works with array of arrays properly  it would be good if in TypeProps will be both array and object

**Comment by xile611** [comment]
@vyachekg Thanks! I'll fix it.

**Comment by Cattpot** [comment]
same Warning at AreaChart
