### ISSUE TITLE
Consistent interface: Pie - activeShape

### ISSUE THREAD

**Issue by andrewangelle** [recharts/recharts#3793]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-4thsnj?file=/src/index.js)

### Steps to reproduce
Hover over any of the sections. Notice activeShape prop is ignored

### What is expected?
I'd expect the customized active shape to render according to the active tooltip the same way that activeDot/activeBar/activeShape work with Line/Bar/Funnel

### What is actually happening?
The activeShape prop is being ignored

| Environment | Info |
|---|---|
| Recharts | v2.8.0 |
| React | 18.2.0 |
| System | macOS Ventura 13.5.2 |
| Browser | Chrome v116.0.5845.179 |

**Comment by andrewangelle** [comment]
Assign me please!

**Comment by ckifer** [comment]
Thanks!
