### ISSUE TITLE
Typescript for BarChart - touchEvent

### ISSUE THREAD

**Issue by KyoungWan** [recharts/recharts#3796]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When I am using 'BarChart' there is only limited type. `CategoricalChartProps`
So I cannot set any touch event handler in BarChart.

### What does the proposed API look like?
I want to manipulate BarChart with touch event. 

for example I want to set two ReferenceLine left and right in the bar chart,
And by touching that Reference line, I filter my data with some range.

for this feature, there should be touch event in props type of BarChart.

**Comment by nikolasrieble** [comment]
![image](https://github.com/recharts/recharts/assets/27995606/bf75e15a-13df-4af7-9b18-2837449e960e)

We do have onTouchXX handlers on the bar object themselves. Could you implement your solution with those? See storybook for more details. 

https://master--63da8268a0da9970db6992aa.chromatic.com/?path=/docs/api-cartesian-bar--docs

**Comment by ckifer** [comment]
Well.. all/most SVG props are technically accepted and spread down onto the base element at the moment so we do not explicitly specify these as accepted props. As such they could be subject to change or minimization (down to the most used touch handlers). But for now and without a new major version release they'll be the same

**Comment by KyoungWan** [comment]
@nikolasrieble Thank you for your response. 
For now, I'm in a hurry, so I'll implement it with the type ignored and add the type when I have more time.

**Comment by ckifer** [comment]
Going to close this as stale, feel free to comment back to continue discussion
