### ISSUE TITLE
I'm facing issues in Y-axis values

### ISSUE THREAD

**Issue by sehrishbashir** [recharts/recharts#3799]
I have created custom y-axis ticks values with the help of a custom function that returns an array of numbers based on min or max value, but when I pass this array into Recharts BarChart Y-axis ticks in the frontend it missed some values and show space into there

**Comment by ckifer** [comment]
Can you give an example or a codesandbox? It's hard to tell what you mean

**Comment by sehrishbashir** [comment]
this is code,
this is data
const graphData = [
    {
        "key": "Oct-2023",
        "value": "1017.74",
        "yAxisKey": "0"
    },
    {
        "key": "Nov-2023",
        "value": "1035.79"
    },
    {
        "key": "Dec-2023",
        "value": "1054.17"
    },
    {
        "key": "Jan-2024",
        "value": "1072.87"
    },
    {
        "key": "Feb-2024",
        "value": "1091.91"
    },
    {
        "key": "Mar-2024",
        "value": "1111.28"
    },
    {
        "key": "Apr-2024",
        "value": "1131.00"
    },
    {
        "key": "May-2024",
        "value": "1151.06"
    },
    {
        "key": "Jun-2024",
        "value": "1171.48"
    },
    {
        "key": "Jul-2024",
        "value": "1192.27"
    },
    {
        "key": "Aug-2024",
        "value": "1213.42"
    },
    {
        "key": "Sep-2024",
        "value": "1234.95"
    }
]

here is my component
const RechartAreaChart = () => {

    const maxYValue = graphData?.length && Math.max(...graphData?.map((item: any) => item?.value));    //only use this for err handling if portfolio < contributionAmount
    const minYValue = 0;
    const tickCount = 6;
    const diffYValue = maxYValue - minYValue;
    // Calculate the raw interval between values
    const rawTickInterval = diffYValue / tickCount;
    const tickValues: number[] = [];
    const domainEnd = Math.floor(maxYValue + rawTickInterval / 15);

    const getYAxisTicks = () => {
        const divisibleBy = 100;
        const tickInterval = Math.ceil(rawTickInterval / divisibleBy) * divisibleBy
        const endingValue = Math.ceil(maxYValue / divisibleBy) * divisibleBy;

        for (let i = 0; i <= tickCount; i++) {
            const tickValue = endingValue - tickInterval * i;
            if (tickValue >= 0) {
                tickValues.push(tickValue);
            }
        }
        // Check if the last item in tickValues is not 0 and add 0 if necessary
        if (tickValues[tickValues.length - 1] !== 0) {
            tickValues.push(0);
        }
        return tickValues
    }
    
    return (
    <ResponsiveContainer width="100%" height={350} className='projectionChart'>
                    <AreaChart
                        data={graphData}
                        margin={{ top: 10, right: 30, left: 0, bottom: 0 }}
                        onMouseMove={e => { setHoveredDot(e.activeTooltipIndex) }}
                        onMouseLeave={() => setHoveredDot(-1)}
                    >
                        <XAxis
                            dataKey="key" axisLine={false} tickLine={false} mirror={false} padding="no-gap" tickCount={13} interval={xAxisInterval() || "preserveStartEnd"}
                        />
                        <YAxis
                            axisLine={false}
                            interval={'preserveStartEnd'}
                            tickCount={8}
                            tickFormatter={(value, index) => formatYAxis(value, index)}
                            type='number'
                            domain={[0, domainEnd]}
                            ticks={getYAxisTicks()}
                        />
                        <Tooltip
                            cursor={false}
                            content={<CustomTooltip />}
                        />
                        <Legend />
                        <Area dataKey={'value'} stroke="#6739D2" fill="#E1D6F9" activeDot={{ stroke: '#403081', fill: '#fff', r: 6.5, strokeWidth: 2.5, strokeDashoffset: 3 }} />
                    </AreaChart>
                </ResponsiveContainer>
    
    )
}

in this case "getYAxisTicks()" function return this array [ 1300, 1000, 700,  400, 100, 0 ], but this chart not show the 100 in frontend,
here is a screenshot
![areaChart](https://github.com/recharts/recharts/assets/49878787/883ef44b-b617-46bf-ba32-7288401315df)

**Comment by ckifer** [comment]
Try setting interval to 0 on your y axis

**Comment by sehrishbashir** [comment]
It's working, thank you
