### ISSUE TITLE
Server Side Rendering - nothing renders when using ResponsiveContainer 

### ISSUE THREAD

**Issue by isilweo** [recharts/recharts#38]
Hey, 

i've been testing Recharts recently and jumped into few problems with server side rendering. I've tested a lot of different charting libraries for React and I would love to stop my search on recharts. Hope that we can fix SSR problems. I have very simple script with Simple Line Chart from example and use renderToString from react-dom/server. If you wish i can post it here or somewhere as a gist.

When adding ResponsiveContainer wrapper around LineChart it doesn't produce any output.

```<div class="recharts-responsive-container" style="width:100%;height:100%;" data-reactid=".1zgxrmyubk0" data-react-checksum="1605641647"></div>``` this is all I have. 

I believe I should have same output for server and client.

my code
```
      <ResponsiveContainer>
      	<LineChart width={600} height={300} data={data}
              margin={{top: 5, right: 30, left: 20, bottom: 5}}>
           <Line type="monotone" dataKey="pv" stroke="#8884d8" />
           <Line type="monotone" dataKey="uv" stroke="#82ca9d" />
        </LineChart>
      </ResponsiveContainer>
```

**Comment by xile611** [comment]
`ResponsiveContainer ` will calculate the width and height of parent node after `componentDidMount` or   resize of window. If width or height of parent node is 0, or the props `width` for `height` is `0%`, then no chart will be rendered.

So you have to set the `width` and `height` of the parent node in style or css.
