### ISSUE TITLE
Custom tooltip on hover of each cell in StackedBar chart

### ISSUE THREAD

**Issue by ashutoshjha1409** [recharts/recharts#380]
Hi 
Is there a way to add a custom tooltip on hover of each cell in StackedBar chart? 
Using the code below we can hover over each stacked bar but not on each cell
`<Bar dataKey='uv' onClick={this.handleClick}>
            {
              data.map((entry, index) => (
                <Cell cursor="pointer" fill={index === activeIndex ? '#82ca9d' : '#8884d8' } key={`cell-${index}`}/>
              ))
            }
           </Bar>`

**Comment by xile611** [comment]
@ashutoshjha1409   Do you mean different event for each `Rectangle` in the `Bar` ?

**Comment by ashutoshjha1409** [comment]
yes

**Comment by ashutoshjha1409** [comment]
We can do something like this

`
<Bar dataKey='uv' }> { data.map((entry, index) => ( <Cell cursor="pointer" onClick={this.handleClick.bind(this, entry, 'uv')/> )) } </Bar>`


//console
Object {name: "Page A", uv: 4000, pv: 2400, amt: 2400} "pv"

once we have the cell object and datakey, we can easily map. This could be one solution. Any other suggestion, do let us know. Thanks

**Comment by xile611** [comment]
@ashutoshjha1409 When you bind click event on `Bar`, you can get the payload of each `Rectangle` when you click it. It means that the event of `Bar` is  actually binded in each `Rectangle` of `Bar`. 

Please check [this demo](http://recharts.org/examples#BarChartWithCustomizedEvent).

**Comment by ashutoshjha1409** [comment]
@xile611 Thanks a lot

**Comment by xile611** [comment]
Ok!
