### ISSUE TITLE
Do you think it's possible to do an animated donut chart like this with recharts?

### ISSUE THREAD

**Issue by jlubeck** [recharts/recharts#381]
http://jsbin.com/ukaxod/144/embed?js,output

Please excuse me if this is not the place to do this kind of question. Let me know and I'll delete it.
Thanks

**Comment by xile611** [comment]
@jlubeck This kind of pie animation can be done by customized `shape` of `Pie`. Here is a [demo](http://jsfiddle.net/fvcc6m14/).

**Comment by jlubeck** [comment]
That demo was awesome! Works like a charm. Thanks!

**Comment by mhuggins** [comment]
That demo doesn't seem to work anymore unfortunately.  Does anyone have a working example?
