### ISSUE TITLE
Data overflowing on the sides when implementing highlight and zoon

### ISSUE THREAD

**Issue by anshika1422** [recharts/recharts#3830]
<img width="1015" alt="image" src="https://github.com/recharts/recharts/assets/46922316/ee887d9f-905c-4109-92fe-c169759b4cd0">

Hi , When i am trying to implement highlight and zoom the data points on my chart area is overflowing . Could anyone help me in solving this issue . 
This is happening when i am setting allowDataOverflow property as true. 
And when i remove this property , highlight and zoom is not working . Could anyone help me in solving this overflowing issue with hightlight and zoom

**Comment by ckifer** [comment]
Hi @anshika1422 

Can you provide a codesandbox as a starting place?

**Comment by anshika1422** [comment]
Here is the example link : https://recharts.org/en-US/examples

In this example if you see the data points are complete circles in plotted in the charts for Xaxis point 0 
<img width="360" alt="image" src="https://github.com/recharts/recharts/assets/46922316/f58be899-0d04-481d-964a-6eb502e8dddf">


As soon as in give Xaxis property 'allowDataOverflow' the circles are cut to half 
<img width="354" alt="image" src="https://github.com/recharts/recharts/assets/46922316/8a2f7aa6-0e35-4e8b-b8c0-e9283720eb48">

I don't want the this cutting into half to happen in my scenario. I need full data points with the allowDataOverflow property as true
