### ISSUE TITLE
Support for custom-shaped Funnel components

### ISSUE THREAD

**Issue by codebreaker-v2-0** [recharts/recharts#3832]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I'm currently working on a project where the design of the Funnel Chart is in the shape of a perfect funnel which has varying bar sizes proportionate to the number of customers at that given stage. At present, the Funnel component doesn't support custom shapes for Funnel chart. And also the customisation is also very limited. I'm just curious to know why the customisation is kept very limited in the case of Funnel Chart as compared to Bar/Line/Pie charts

### What does the proposed API look like?
Providing additional prop like **shape={//customShape}** 
```
<FunnelChart >
    <Funnel data={data} dataKey="value" shape={//customShape} >
        <LabelList dataKey="name" fill="#000" />
    </Funnel>
    <Tooltip />
</FunnelChart>
```

**Comment by ckifer** [comment]
Probably just because funnel was added later than the other components and shape was never added as a feature. 

If one doesn't already exist we can use this as a feature request

**Comment by nikolasrieble** [comment]
@andrewangelle As you have already solved a big of challenges around (active)Shapes, and API alignment - would you consider picking this up as well?

**Comment by andrewangelle** [comment]
@nikolasrieble of course! assign me.

**Comment by nikolasrieble** [comment]
Released with https://github.com/recharts/recharts/releases/tag/v2.10
