### ISSUE TITLE
How to get only hovered item instead of all items of y axis?

### ISSUE THREAD

**Issue by PrabhuPuredla95** [recharts/recharts#3840]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to display the data of Attendance only when hovered on attendance line.

<LineChart width={500} height={300} data={formatChartData()}>
        <XAxis dataKey="week" />
        <YAxis />

        <Line
          type="linear"
          dataKey="overall_attendance"
          stroke="#82ca9d"
          strokeWidth={3}
          label="Attendance"
        />
        <Line
          type="linear"
          dataKey={
            isBlendedProgram
              ? 'total_residency_rating_percentage'
              : 'total_online_rating_percentage'
          }
          strokeWidth={3}
          label="Rating"
        />
        <Line
          type="linear"
          dataKey="avg_assessments_percentage"
          strokeWidth={3}
          label="Assignment"
        />
        <Line
          type="linear"
          dataKey="video_watched_percentage"
          strokeWidth={3}
          label="Video Watched"
        />

        <Tooltip content={<CustomTooltip />} shared={false} />

        <Legend
          iconSize={20}
          iconType="rect"
          formatter={(value, entry: any, index) => {
            return (
              <span style={{ color: entry.color }}>{entry.payload?.label}</span>
            )
          }}
        />
      </LineChart>

const CustomTooltip = ({ active, payload, label }: any) => {
  console.log('payload ', payload)
// I want this payload to the respective line, instead of all lines for the same X axis value

  return null
}

### What does the proposed API look like?
Send the respective line item to payload of tooltip when hovered?

MUI does something like this
'item' —when the user's mouse hovers over an item on the chart, the tooltip will display data about this specific item. 'axis' —the user's mouse position is associated with a value of the x-axis. The tooltip will display data about all series at this specific x value.

https://mui.com/x/react-charts/tooltip/#interactions

**Comment by ckifer** [comment]
Hi, there are a lot of issues asking for this so this may get closed as a duplicate. I'll link related issues in a bit, currently on mobile. Thanks

**Comment by ckifer** [comment]
Related:
https://github.com/recharts/recharts/issues/3763
https://github.com/recharts/recharts/issues/3613
https://github.com/recharts/recharts/issues/2583
https://github.com/recharts/recharts/issues/2447
https://github.com/recharts/recharts/issues/1775
https://github.com/recharts/recharts/issues/488

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/issues/488 is the longest open so will probably track there, going to close this as a duplicate

**Comment by eudalag** [comment]
How did you do the unit test?
