### ISSUE TITLE
Sunburst Charts

### ISSUE THREAD

**Issue by manishsharma004** [recharts/recharts#3842]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If it's not a blocker, recharts team can choose to add it to charts list which seems to be only popular chart type missing from library.

Example provided in earlier issue: [Sunburst Chart](https://nivo.rocks/sunburst/)

### What does the proposed API look like?
```tsx
interface ISunburstData {
  name: string,
  value?: number,
  children?: ISunburstData[]
}

const child1: ISunburstData = {
  name: 'Child1',
  value: 60,
  children: [
    {
      name: 'Child1 > Child1',
      value: 30
    },
    {
      name: 'Child1 > Child2',
      value: 20
    },
    {
      name: 'Child1 > Child3',
      value: 20
    }
  ]
}
const child2: ISunburstData = {
  name: 'Child2',
  value: 40
}

<SunburstChart width={512} height={512}>
  <SunburstPie data={child1} />
  <SunburstPie data={child2} />
</SunburstChart>
```

**Comment by csdiehl** [comment]
@ckifer  if nobody is doing this and this feature is still desired, I can take this on!

**Comment by ckifer** [comment]
@csdiehl feel free to give it a shot! Maybe try to do it without generateCategorialChart if at all possible

**Comment by csdiehl** [comment]
sounds good - working on it
