### ISSUE TITLE
Width of bars in barchart

### ISSUE THREAD

**Issue by ShridharAware** [recharts/recharts#3845]
I've been trying to add different width to each bars but any of solution not worked for me. I had also tried using rectangle shape for this. It helped me to add width to the shape but unfortunately I was unable to remove the gap between two adjacent shapes. If there is already a solution for this case please provide link to the solution.

Refer this image - 
![image](https://github.com/recharts/recharts/assets/130430834/584c898f-41f5-41f8-b6c2-ad9d57c2f952)

**Comment by ckifer** [comment]
@ShridharAware can you provide a sandbox of what you've tried? I don't think this behavior is currently supported

**Comment by ShridharAware** [comment]
@ckifer Yes sure! [https://codesandbox.io/p/sandbox/keen-cohen-ykpzx7](url)

**Comment by ShridharAware** [comment]
@ckifer I want to remove gaps between these shapes  [](https://codesandbox.io/p/sandbox/keen-cohen-ykpzx7)

**Comment by ShridharAware** [comment]
[https://codesandbox.io/p/sandbox/keen-cohen-ykpzx7](url)

**Comment by ShridharAware** [comment]
@ckifer https://codesandbox.io/p/sandbox/keen-cohen-ykpzx7

**Comment by ckifer** [comment]
closing in favor of https://github.com/recharts/recharts/issues/1199
