### ISSUE TITLE
Centering Bar Labels

### ISSUE THREAD

**Issue by matthewberkompas** [recharts/recharts#385]
I have a stacked bar chart and I would like to center the bar labels on each bar. However, it doesn't look like you guys are using CSS to do this so I'm unsure how to go about it. Is it _possible_ to do this and if so, would someone be willing to show me an example? I would really appreciate it!

**Comment by xile611** [comment]
@matthewberkompas  Now you can center the labels of `Bar` like this [demo](http://jsfiddle.net/wa87o60f/3/).
But the callback parameters of `label` seems strange now,  the `width` and `height` are width and height of `rectangle` in `Bar`, the `x` and `y` is the coordinate of `label` .

**Comment by matthewberkompas** [comment]
Sweet! Thanks again @xile611. This is a huge help.
