### ISSUE TITLE
How about removing support for ES5?

### ISSUE THREAD

**Issue by HHongSeungWoo** [recharts/recharts#3858]
Browsers that don't support ES6 are no longer in use.
Removing support for ES5 with simple modifications can significantly reduce bundle size.

**Comment by ckifer** [comment]
Recharts is used by a lot of people, we have consumers that will break if we stop vending cjs

**Comment by HHongSeungWoo** [comment]
Let's remove support for ES5, not for cjs

**Comment by ckifer** [comment]
Oh sorry I misread 😅 

Yeah I think that would be fine, but needs to be in the next major version

**Comment by HHongSeungWoo** [comment]
I don't think this will be a breaking change at all, in my opinion. I'll create a simple PR and investigate the bundle size. Could you please review it?

**Comment by ckifer** [comment]
Sure lets see what the results are and we'll go from there. Even if we can assume no users are on browsers that don't support ES6 (we probably can), in principle this is still a breaking change if someone were to be. I'd rather err on the side of caution but lets see what the reward will be for doing it and we can discuss the nature of the change later

Thanks for jumping on this

**Comment by nikolasrieble** [comment]
@HHongSeungWoo Just for your context, we are already working on the branches for 3.0.0 

https://github.com/recharts/recharts/pull/3701
https://github.com/recharts/recharts/pull/3702
https://github.com/recharts/recharts/pull/3705

**Comment by ckifer** [comment]
This is merged in the 3.x branch!
