### ISSUE TITLE
Using custom label with <Bar /> generates the label twice into the DOM

### ISSUE THREAD

**Issue by ilanus** [recharts/recharts#386]
I've made a custom label for the bar chart, I ended up with the following result:

![pasted image at 2016_12_03 02_09 pm](https://cloud.githubusercontent.com/assets/9677898/20859538/2e60270a-b962-11e6-9380-85439069cc91.png)

The label is displayed at the top of the bar and at the bottom:

![pasted image at 2016_12_03 02_06 pm](https://cloud.githubusercontent.com/assets/9677898/20859548/41105f14-b962-11e6-9dee-82b1688c2e01.png)

However If I pass plain object to the label prop, the label wont be displayed twice.
My custom label:
```
export const InnerBarTooltip = ({ x, y, width, height, textAnchor, sold }) =>
  <text
    className="recharts-text recharts-bar-label"
    fill="red" x={x} y={Math.round(y + 20)} width={width} height={height} fontSize={20} textAnchor={textAnchor}
  >
    <tspan x={x} dy="0" style={{ fontWeight: 400 }}>{sold}</tspan>
  </text>;

InnerBarTooltip.propTypes = {
  x: PropTypes.number,
  y: PropTypes.number,
  width: PropTypes.number,
  height: PropTypes.number,
  textAnchor: PropTypes.string,
  sold: PropTypes.number,
};
```

**Comment by xile611** [comment]
@ilanus Can you create a simple online example ? It seems you have added two `Bar`, so two groups of labels are rendered.

**Comment by xile611** [comment]
I'll reopen it if demo is submited.
