### ISSUE TITLE
Stacked bar chart does not behave as expected when it contains positive and negative values in a bar

### ISSUE THREAD

**Issue by bsshetty17** [recharts/recharts#3876]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bar-chart-with-positive-negative-forked-8pywml)

### Steps to reproduce
when the numbers are positive and negative one color gets hidden. if the difference is high, both colors are displayed

### What is expected?
all the stacked bars should be displayed with specified color irrespective of whether the value is positive or negative

### What is actually happening?
One bar is overriding the otther instead of stacking

| Environment | Info |
|---|---|
| Recharts | v2.7.2 |
| React | react |
| System | NA |
| Browser | chrome/firefox |

**Comment by Enwebb** [comment]
We have the same problem. In a stacked barchart the expected behaviour (generated by another chart tool) is:
<img width="326" alt="image" src="https://github.com/recharts/recharts/assets/43937793/638f007e-e5f0-46bd-a2d8-6613d92a57b4">

But the actual behaviour in recharts is:
 
<img width="365" alt="image" src="https://github.com/recharts/recharts/assets/43937793/e02eceef-34f6-44da-a0d7-cc1bed9a494e">

**DATA**

"transformedChartData":{
   "objects":[
      {
         "xAxisDataKey":"15 000 kr/mån",
         "Alliansens sänkningar (2009-2014)":883,
         "S/MP:s sänkningar (2016-2018)":356,
         "Övergångsregeringens förslag (2019)":0
      },
      {
         "xAxisDataKey":"20 000 kr/mån",
         "Alliansens sänkningar (2009-2014)":1001,
         "S/MP:s sänkningar (2016-2018)":340,
         "Övergångsregeringens förslag (2019)":123
      },
      {
         "xAxisDataKey":"30 000 kr/mån",
         "Alliansens sänkningar (2009-2014)":1033,
         "S/MP:s sänkningar (2016-2018)":120,
         "Övergångsregeringens förslag (2019)":567
      },
      {
         "xAxisDataKey":"40 000 kr/mån",
         "Alliansens sänkningar (2009-2014)":760,
         "S/MP:s sänkningar (2016-2018)":0,
         "Övergångsregeringens förslag (2019)":618
      },
      {
         "xAxisDataKey":"50 000 kr/mån",
         "Alliansens sänkningar (2009-2014)":851,
         "S/MP:s sänkningar (2016-2018)":0,
         "Övergångsregeringens förslag (2019)":734
      },
      {
         "xAxisDataKey":"60 000 kr/mån",
         "Alliansens sänkningar (2009-2014)":922,
         "S/MP:s sänkningar (2016-2018)":0,
         "Övergångsregeringens förslag (2019)":478
      },
      {
         "xAxisDataKey":"130 000 kr/mån",
         "Alliansens sänkningar (2009-2014)":933,
         "S/MP:s sänkningar (2016-2018)":0,
         "Övergångsregeringens förslag (2019)":**_-433_**
      }
   ],
   "series":[
      {
         "seriesNumber":1,
         "name":"Alliansens sänkningar (2009-2014)"
      },
      {
         "seriesNumber":2,
         "name":"S/MP:s sänkningar (2016-2018)"
      },
      {
         "seriesNumber":3,
         "name":"Övergångsregeringens förslag (2019)"
      }
   ]
},

**Comment by HHongSeungWoo** [comment]
Try using stackOffset='sign'.

**Comment by ckifer** [comment]
Ah nice yeah, `stackOffset='sign'` works well https://codesandbox.io/s/bar-chart-with-positive-negative-forked-l5ssv9?file=/src/App.tsx

**Comment by bsshetty17** [comment]
Thank you. it worked
