### ISSUE TITLE
React build is failing when trying to upgrade rechart

### ISSUE THREAD

**Issue by Avhishek05** [recharts/recharts#3898]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.jenkins.io/](https://www.jenkins.io/)

### Steps to reproduce
Upgrade rechart to 2.9.0 and build is failing with error

### What is expected?
Build should complete

### What is actually happening?
Build is failing with below error

ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL]: ENOENT: no such file or directory, open '/var/lib/jenkins/workspace/web_react_app_wall_build/dashboard/node_modules/recharts/src/index.js' (While processing: /var/lib/jenkins/workspace/web_react_app_wall_build/dashboard/node_modules/babel-plugin-recharts/lib/index.js)

| Environment | Info |
|---|---|
| Recharts | v2.9.0 |
| React | 18.0.0 |
| System | MacOs |
| Browser | any |

**Comment by ckifer** [comment]
@Avhishek05 what version are you upgrading from?

**Comment by ckifer** [comment]
https://github.com/recharts/babel-plugin-recharts/issues/25

**Comment by Avhishek05** [comment]
@ckifer I think you can close it. After removing babel-plugin-recharts(it was causing issue) it seems to be working.
