### ISSUE TITLE
Risky code in getStrokeDasharray leads to infinite loop when strokeDasharray is '0'

### ISSUE THREAD

**Issue by vjohansen** [recharts/recharts#3899]
I was using strokeDasharray='0' to disable dashed lines (maybe incorrect) but it leads to an infinite loop in getStrokeDasharray .

I suggest the code is changed so infinite loops do not happen even on incorrect user input. From a code style perspective it should be obvious that an infinite loop does not happen (maybe : if (i>10) {console.warn .. ; break}) . 

![image](https://github.com/recharts/recharts/assets/634765/671094b3-019e-4baa-ac3b-3fd6f486681a)

**Comment by vjohansen** [comment]
This may explain why setting isAnimationActive={false} in #1812 fixes hangs.

There seem to be a relation with strokeDasharray and isAnimationActive 

"Line chart strokeDasharray does not apply if isAnimationActive is false from the start and set to true in componentDidMount" #2373

**Comment by ckifer** [comment]
Thanks for the report, will get this fixed. A lot of this is an inherited legacy so I never would've known that line existed or these things are related. 

Agreed that code is incredibly risky and we shouldn't trust human input ever (especially in loops) 😅

**Comment by ckifer** [comment]
Should be resolved by #3904 - will be fixed in next release. Thanks!

**Comment by ckifer** [comment]
released in 2.9.1
