### ISSUE TITLE
Display (tooltip's) cursor via prop

### ISSUE THREAD

**Issue by ZephD** [recharts/recharts#390]
Hi,

Suppose I additionally have a table of the graphed XY data and an 'onHover' function which gets the X value of the table row.

Is there a way to pass this X value to a Rechart for it to display the cursor (similar to the one for the tooltip) at that given value?

Thanks

**Comment by xile611** [comment]
@ZephD It's recommended to add a `ReferenceLine` like this [demo](http://jsfiddle.net/b1Lb3kuk/).

**Comment by ZephD** [comment]
This works well.
However, it does clash with the tooltip when using the prop "isFront".

Thank you very much.

**Comment by ZephD** [comment]
@xile611 

Two things:
 - The RefLine interrupts the tooltip selection - you either get one or the other
 - Every new render of the RefLine seems to toggle the line's state, so it shows, hides, shows, hides...

Any idea why these occurs?

**Comment by xile611** [comment]
@ZephD It works well in my broswer.

![refline](https://cloud.githubusercontent.com/assets/6111424/21211210/9ac465ec-c2bc-11e6-91f5-5e39f1d44a42.gif)

**Comment by ZephD** [comment]
I think mine is a special case.

On mouse over the graph, update a redux store of the selected X value.
This is then mapped from state to props, which renders the RefLine.
(It also updates another graph/map, hence the reason for it).

What I think is happening is the first time you mouse-over a value, the tooltip is rendered as expected.
However, it triggers a redux store update, which updates the props, which causes a re-render of the graph in order to render the RefLine.

I believe the tooltip is not rendered on this second render (as it already responded to it's update), making it disappear.

If you were to move the mouse on the same x-value, the tooltip does render (but this is because I do not update the redux store if the value has not changed).

Interesting, no? :)

**Comment by xile611** [comment]
@ZephD Every time you update the wrapper component of `LineChart`, the children instances of `LineChart` will change. Maybe this's the reason for your case. But in your first description, you mean to click another `table` to interact width `LineChart`, so I don't know why the `tooltip` will hide and show.

**Comment by ZephD** [comment]
http://jsfiddle.net/b1Lb3kuk/3/

Try that.

You'll see a comment saying "replace this with null". Do that, and the problem is 100% of the time, rather than only the first mouse over (tricky to do, move from one section to the next a pixel at a time).

**Comment by xile611** [comment]
@ZephD Why set `curSelected` to be `null` ?

**Comment by ZephD** [comment]
To see the problem 100% of the time, ie the tool tip will never display.

And that's the thing. A second render occurs which resets the tooltip to not shown. Similar problem to #401.

**Comment by xile611** [comment]
@ZephD Every time we update the state, the reference of children changes. So I'll refactor the comparison of children in [generateCategoricalChart.js#L93](https://github.com/recharts/recharts/blob/master/src/chart/generateCategoricalChart.js#L93). This's also the reason of #401 . 

It's recommended to not bind `onMouseMove` in `LineChart` to update `ReferenceLine`, this action is conflict with tooltip.

**Comment by ZephD** [comment]
I understand your recommendation fully! I'm trying to link a map of locations with a graph of time-based data. The link between the data is the timestamp, or the X-value of the graph.
Unfortunately, I would like mouse over on a **map** or the **graph** to update a single state value, and that value is mapped as props which updates the map and graph with a **marker** and **RefLine**.

**Comment by xile611** [comment]
@ZephD I understand your demands now. You can wait for updating of recharts, I have done some optimization.  And a workaround is to add two state, one state to show `ReferenceLine` when hover the map and another state to show `marker` when hover the chart.

**Comment by ZephD** [comment]
Oh exciting :)
Good stuff :D

**Comment by xile611** [comment]
@ZephD Can you check the latest version ?

**Comment by ZephD** [comment]
Any chance it can be used with http://jsfiddle.net/b1Lb3kuk/3/ ?

**Comment by ZephD** [comment]
Tried with 20.2. This issue is _not_ solved. :(

**Comment by xile611** [comment]
@ZephD Check the latest [demo](http://jsfiddle.net/b1Lb3kuk/12/). I just use a variable `margin` and `activeDot` to keep the static value of margin and activeDot. you know, every time you change the state, a new margin and a activeDot will be parsed to `LineChart`, then the `shallowEqual` of two children will return `false`.

Maybe you can check this [article](https://medium.com/@esamatti/react-js-pure-render-performance-anti-pattern-fb88c101332f#.p7fc9cflz) for detail.

**Comment by ZephD** [comment]
The problem still exists:

Move your cursor VERY slowly (pixel by pixel) from one to the other.
Note that the very first update to the next value does not render the tooltip (but it does render the RefLine).

This effect is very obvious when you have many many data points, ie they are all one pixel wide.

See http://jsfiddle.net/b1Lb3kuk/13/
Move your curser side-to-side over the graph, note there is no tooltip.
Move your curser up and down (which is similar to re-render of the same data point) and it renders the tool tip.

**Comment by ZephD** [comment]
Still not fixed with 0.22.
