### ISSUE TITLE
Remove bar labels when bar is too small

### ISSUE THREAD

**Issue by matthewberkompas** [recharts/recharts#391]
I have a stacked bar chart and I'm dealing with an issue where the bar labels are being cut off when the bars are really short: 
<img width="295" alt="screen shot 2016-12-08 at 3 19 07 pm" src="https://cloud.githubusercontent.com/assets/7084294/21031740/eca113aa-bd59-11e6-882c-8c508ed92fb0.png">

Is there a way to make the labels disappear when the bar is a certain size or when there is only a certain amount of room on each side of the label inside the bar?

**Comment by xile611** [comment]
@matthewberkompas You can return null when the width of bar is smaller than a specified number.

**Comment by matthewberkompas** [comment]
@xile611 Like this? 
```jsx
const { width } = props;

if (width < 25) {
    return '';
  } else {
    return (
      <Text
        {...props}
        key={key}
        className='recharts-bar-label'
        style={{ fill: '#fff' }}
        textAnchor='middle'
        x={x - width / 1.98}
        y={y}
      >
        { label }
      </Text>
    )
  }
```

**Comment by xile611** [comment]
@matthewberkompas Yeah! Just like your demo.

**Comment by matthewberkompas** [comment]
Thanks @xile611!
