### ISSUE TITLE
Width on custom shape produces jumping bars on hover

### ISSUE THREAD

**Issue by klassm** [recharts/recharts#3913]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/klassm/recharts-bar-chart-repro/tree/hover_bug](https://github.com/klassm/recharts-bar-chart-repro/tree/hover_bug)

### Steps to reproduce
* Add a custom shape
* Set a width on it, e.g. by calculating it from a maximum - so in general a dynamic width

### What is expected?
* The width adapts - which it initially does.

### What is actually happening?
* When hovering over the bar, it suddenly has the full width

| Environment | Info |
|---|---|
| Recharts | v2.9.0 |
| React | 18.2 |
| System | MacOS Sonoma |
| Browser | Chrome latest |

**Comment by klassm** [comment]
Thank you so much, then I'll try that one. Just wondering: Wouldn't it be sensible to have this as a default then, so to avoid the breaking behaviour?

**Comment by ckifer** [comment]
Yeah we use semver and ideally never break on a minor or patch version. In practice, we don't have enough manpower or good enough tests to cover every case before we release and that can lead to the occasional breaking change. So we had no idea this was breaking else we wouldn't have released it - we can patch but I don't have an ETA

**Comment by akamfoad** [comment]
@klassm 

I don't think so, when you pass a shape you're starting to customize what recharts has given you by default.

I think the docs can do a better job explaining the anatomy of the charts so this would be more clear to the users.

**Comment by klassm** [comment]
This worked out perfectly fine - I just pass false for the activeBar, which restores the original behaviour. Thank you so much for the quick response and for the hint! Really appreciate that.
