### ISSUE TITLE
Bad type on activeDot onClick

### ISSUE THREAD

**Issue by cplprince** [recharts/recharts#3922]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-sz6kpd?file=/src/index.tsx)

### Steps to reproduce
Your onClick fuction on activeDot on Line is badly typed. If you use the type which is written in the onClick, then there's not a payload attribute on 2. position of the onClick.

https://pasteboard.co/DAYWcO1i0xa7.png

https://pasteboard.co/BYM0L0t2XByp.png

### What is expected?
Have at least :any type on the second position for the payload.

### What is actually happening?
We have a TS error 

| Environment | Info |
|---|---|
| Recharts | v2.9.1 |
| React | 17.0.2 |
| System | Windows 11 |
| Browser | Version 118.0.5993.118 (Official Build) (64-bit) |

**Comment by ckifer** [comment]
Did this just happen in 2.9.1 or was it like this previously?

**Comment by ckifer** [comment]
@andrewangelle 😅. Sorry to keep tagging you but fyi. Not sure if it's my latest change for 2.9.1 yet or not

**Comment by cplprince** [comment]
we were on the 2.3.2 before. The payload type was missing but at least it was usable.

**Comment by cplprince** [comment]
If you want, I can check if it works differently on different version?

**Comment by cplprince** [comment]
btw we are using "typescript": "^4.6.2", if it makes any difference 🙂

**Comment by ckifer** [comment]
>  I hate the types 

Can you explain why you hate the types 😅? The goal is to make them better, more accurate - not worse.

**Comment by andrewangelle** [comment]
> Sorry to keep tagging you but fyi. Not sure if it's my latest change for 2.9.1 yet or not

@ckifer Please feel free to continue to do so. I have a fix. I'll have it up today.

**Comment by ckifer** [comment]
@andrewangelle 🙌 appreciate you!

**Comment by ckifer** [comment]
Fixed in 2.9.2, resolving this

**Comment by cplprince** [comment]
@ckifer look better but payload.payload does not exist, would it be possible to have it in such a way that Required<DotProps>['onClick']<T> where the T is a generic for the payload.payload? if non is provided then the payload.payload is any?

**Comment by andrewangelle** [comment]
I'm not an official maintainer, just a contributor. But throwing in my two cents:

I'm sure it's possible, but I believe that would be an enhancement. While I agree it's incorrect, this is consistent with the behavior prior to the types change in `v2.9.0`.

<img width="1440" alt="Screenshot 2023-11-01 at 8 58 24 AM" src="https://github.com/recharts/recharts/assets/24420033/a219d4d8-f5bc-481b-b902-cd9dcea71c4b">

**Comment by ckifer** [comment]
Yeah +1, the goal for the fix was to get back to where we were before we broke you in the simplest way. Adding anything else to the type has potential to add more issues rather than resolve the one that needed fixed. 

Feel free to open a new issue or contribute though!
