### ISSUE TITLE
Remove adaptEventHandlers from generateCategoricalChart

### ISSUE THREAD

**Issue by HHongSeungWoo** [recharts/recharts#3927]
Many DOM event handlers in the current chart are performing altered behavior due to adaptEventHandlers.
For instance, `onClikc={(mouseInfo, event) => {...}} `is being transformed, but there seems to be no reason to alter the default event handler behavior.
If desired, end users can achieve the same functionality with `onClick={(event) => {chart.getMouseInfo(e)}}.`

**Comment by HHongSeungWoo** [comment]
@ckifer @nikolasrieble How do you think about this??

**Comment by nikolasrieble** [comment]
This would be a large breaking change to many customer applications, requiring a rewrite of custom handlers. We would need to see a large benefit, to do this. 

What would be the benefit besides simpler code?

**Comment by HHongSeungWoo** [comment]
It can improve performance and reduce complexity.
By resolving a few more issues, we can also remove objects such as EventKeys existing in types.ts
Of course, we should export the CategoricalChartWrapper type first and alert the users, but I believe it is a worthwhile task

**Comment by HHongSeungWoo** [comment]
Hmm... come to think of it, with ongoing refactoring, I'm not sure what will become of getMouseInfo. 
it seems like it could potentially interfere with the refactoring process. :cry:

**Comment by ckifer** [comment]
Mostly the events are adapted to pass the chart data back to the consumer - I think that is certainly something that is reasonable to support
