### ISSUE TITLE
Tooltip shows wrong values when using Brush

### ISSUE THREAD

**Issue by shb** [recharts/recharts#3929]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-zvw7xr?file=/src/index.js)

### Steps to reproduce
Hover on first data point; tooltip shows "Page A / value: 2400". Move the brush so that "Page A" is not visible any more on the x axis. Hover on first data point again; tooltip now shows "Page B / value: 2400"

### What is expected?
Tooltip should show "Page B / value: 2210"

### What is actually happening?
Tooltip show "Page B" which is correct, but the value is "value: 2440" which is the first value in the dataset, not the first value visible in the chart.

| Environment | Info |
|---|---|
| Recharts | v2.9.2 |
| React | 16.14.0 |
| System | maxOS Ventura 13.4 (arm64) |
| Browser | Chrome 118.0.5993.117 |

---
This works in version 2.8.0

**Comment by ckifer** [comment]
It looks like the example given does not include brush

**Comment by ckifer** [comment]
No idea what broke this but @nikolasrieble @andrewangelle @PavelVanecek @akamfoad  - another patch that needs done from 2.9

**Comment by ckifer** [comment]
@andrewangelle https://github.com/recharts/recharts/pull/3733

This one I believe

**Comment by ckifer** [comment]
released in 2.9.3
