### ISSUE TITLE
Object #<Object> has no method 'sign'

### ISSUE THREAD

**Issue by southnan0** [recharts/recharts#393]
When I use CartesianGrid or XAxis on android 4.4.2 or other lower version , show the error  Object #<Object> has no method 'sign' . But  android 6.0+ is ok.

**Comment by xile611** [comment]
@southnan0 How about the version of recharts ? And do you use `babel-plugin-recharts` ?

**Comment by southnan0** [comment]
0.19.0  ,and I use babel-plugin-recharts, also  call this error

**Comment by vaeum** [comment]
Hello i use polyfill-service, and my snippet in app entry.

https://www.npmjs.com/package/polyfill-service

```
import 'polyfill-service/polyfills/Math/sign/polyfill';
```

**Comment by xile611** [comment]
@southnan0 I think the version of `babel-plugin-recharts` is out of date.  You should update the version of `babel-plugin-recharts` to `1.1.0`.

**Comment by xile611** [comment]
@vaeum Recharts have imported polyfills too.  [polyfill](https://github.com/recharts/recharts/blob/master/src/index.js#L1)

**Comment by southnan0** [comment]
It's already the latest version.   I use the android 4.4.2 open demo the club's official website, also can't open the chart. Android 6.0 can open.  You have tried using android machine?

**Comment by xile611** [comment]
@southnan0  No. Because recharts works well in IE10, IE11, and we have imported necessary polyfills.

**Comment by southnan0** [comment]
I solved it for import core-js/es6/math.  
Because I use  `import XAxis from "recharts/lib/cartesian/XAxis"`    instead of   `import {XAxis} from "recharts"`.  
 Thank you for your patiently.

**Comment by xile611** [comment]
@southnan0 OK! You can use `babel-plugin-recharts` too.
