### ISSUE TITLE
Radar chart with a PolarAngleAxis with type "number" does not properly align points with the ticks

### ISSUE THREAD

**Issue by tran-simon** [recharts/recharts#3937]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-896dvj?file=/src/index.js)

<img width="347" alt="image" src="https://github.com/recharts/recharts/assets/8755930/9ab10a4b-75c9-4c46-b416-490e9c0718ce">

### Steps to reproduce
Have a Radar Chart that uses a PolarAngleAxis with type="number". The data is an array of objects containing the angle and the value

### What is expected?
Points on the chart should be aligned with the axis ticks at the correct angle

### What is actually happening?
The whole polygon seems to be rotate about 45 degrees counterclockwise

| Environment | Info |
|---|---|
| Recharts | v2.9.2 |
| React | 18.2.0 |
| System | codesandbox |
| Browser | Chrome |

**Comment by ckifer** [comment]
Going to close this in favor of https://github.com/recharts/recharts/issues/2969 since its pre-existing. Example will still be linked from there

**Comment by ckifer** [comment]
Should be fixed in next minor
