### ISSUE TITLE
Margins between X-Axis, brush and legend

### ISSUE THREAD

**Issue by batjko** [recharts/recharts#394]
Hi there,

We are trying to get the labels on a simple time series line chart to be centered left of and below the axes (apparently industry conventions).

Unfortunately, we are unable to move the brush and legend down, to make space for the label, resulting in this squishy situation:

![selection_039](https://cloud.githubusercontent.com/assets/7287076/21108159/1668821a-c08c-11e6-93be-e4f1b6dde266.png)

We have tried adding css margins to the classes we can see of the components via the chrome devtools (e.g. class `recharts-brush`), but that seems to have no effect.

So does anyone have an idea how I can create the needed margin below the X-axis?

**Comment by xile611** [comment]
@batjko You can change the value of  `XAxis`'s props `height` which have default value 30.

**Comment by batjko** [comment]
@xile611 Ah thanks. Works well for the space around the x-axis. 
Since the legend appears to be outside the svg, I'll try handling that one directly with css.

**Comment by CodingToBeWithHer** [comment]
thx @xile611 - solved my problem

**Comment by sparshgupta3** [comment]
nice @xile611

**Comment by Haraldson** [comment]
Just a hacky workaround again – does not work with `<Legend verticalAlign="top" />` for instance.
