### ISSUE TITLE
Is it possible to do this with PieChart? 

### ISSUE THREAD

**Issue by lucaspieran** [recharts/recharts#3942]
I want to know if its possible todo something like this, i 've already read all the documentation and check issues but y dosent found anything
this is what i  want to do 
![Screenshot from 2023-11-08 16-49-33](https://github.com/recharts/recharts/assets/67299584/fd2bd903-3b74-4c8f-8338-0fb4cc83625b)

and this is what i did it till now , i tried with cornerRadius but look weird
![Screenshot from 2023-11-08 16-51-02](https://github.com/recharts/recharts/assets/67299584/5074dbe8-3843-4d67-8e49-9d21af1991ed)

```javascript
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip } from 'recharts'

const CPieChart = () => {
  const data = [
    { name: 'a', value: 33, color: '#58D8F5' },
    { name: 'b', value: 33, color: '#A162F7' },
    { name: 'c', value: 33, color: '#1CC306' },
  ]
  const cx = 90
  const cy = 80
  const iR = 45
  const oR = 80
  const RADIAN = Math.PI / 180

  const renderCustomizedLabel = ({
    cx: cX,
    cy: cY,
    midAngle,
    innerRadius,
    outerRadius,
    percent,
  }: any) => {
    const radius = innerRadius + (outerRadius - innerRadius) * 0.5
    const x = cX + radius * Math.cos(-midAngle * RADIAN)
    const y = cY + radius * Math.sin(-midAngle * RADIAN)

    return (
      <text x={x} y={y} fill="white" textAnchor="middle" dominantBaseline="central">
        {parseFloat((percent * 100).toFixed(0)) > 0 && `${(percent * 100).toFixed(0)}%`}
      </text>
    )
  }

  return (
    <ResponsiveContainer width="100%" height="100%">
      <PieChart width={50} height={50}>
        <Pie
          dataKey="value"
          startAngle={200}
          endAngle={-20}
          data={data}
          innerRadius={iR}
          outerRadius={oR}
          cx={cx}
          cy={cy}
          label={renderCustomizedLabel}
          fill="#8884d8"
          labelLine={false}
          stroke="none"
          // cornerRadius={12}
        >
          {data.map((entry) => (
            <Cell key={`cell-${entry.name}`} fill={entry.color} />
          ))}
        </Pie>
      </PieChart>
    </ResponsiveContainer>
  )
}

export default CPieChart
```

**Comment by nikolasrieble** [comment]
I looked into it, and could not get it to work. I am rather surprised by the behaviour of the cornerRadius, which seems to by default only affect slices with a certain size, see image. 

While looking into it, I saw that our storybook story for the Pie is not fully functional and will fix it.

<img width="442" alt="Screenshot 2023-11-08 at 22 29 53" src="https://github.com/recharts/recharts/assets/27995606/fa40aaf1-b008-4830-bf04-f0b1319f4222">

As far as I can see, we would have to extend the API here to enable this feature.

**Comment by zsoltmar** [comment]
cornerRadius also creates rather unwanted behavior when used with an animation. It will snap back to 0 if the shape is not large enough 
![pie-rounding](https://github.com/recharts/recharts/assets/9203999/46e708c8-74cb-4e20-9cd1-bb0f47557e17)

**Comment by zsoltmar** [comment]
Sector has a `forceCornerRadius` prop apparently for this reason, though it also produces weird stuff on small size animations.

**Comment by zsoltmar** [comment]
@lucaspieran To your question, it should be possible, you just need to treat each section as its own cell, round the corners and adjust the start and end angles to account for the rounding
