### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'x')

### ISSUE THREAD

**Issue by kvkto** [recharts/recharts#3947]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tooltip-inside-treemap-zpxvzs)

### Steps to reproduce
Make sure the codesandbox canvas has focus.
Press "escape" button.
Move a cursor over the chart.
Click on the chart to make sure the chart is focused.
Press the "escape" button to close a tooltip.
Move the cursor out of the chart. 

### What is expected?
The chart should work without any issues or errors.

### What is actually happening?
Every time the "escape" button is clicked, there is an error in the console: "Uncaught TypeError: Cannot read properties of null (reading 'x')"

After leaving a cursor out, the chart crashes with the same error.

| Environment | Info |
|---|---|
| Recharts | v2.9.3 |
| React | 17.0.2 |
| System | MacOS Monterey 12.6.9  |
| Browser | Chrome 117.0.5938.62 |

---
In version 2.7.3 there was a check if the coordinate was null before reading x and y fields inside "handleKeyDown" function (src/component/Tooltip.tsx). Since 2.8.0 there is no more this check and in the case described above it fails.

**Comment by HHongSeungWoo** [comment]
It will probably be fixed in the next version! :smile:

**Comment by nikolasrieble** [comment]
Released with https://github.com/recharts/recharts/releases/tag/v2.10
