### ISSUE TITLE
Is there a way  to combine svg and text in recharts tick label ?

### ISSUE THREAD

**Issue by bettafish15** [recharts/recharts#3954]
According to the documentation, ticks label can only be text or svg . Is there a way to show both svg and text right next to them in ticks label, like this ?

![image](https://github.com/recharts/recharts/assets/40290448/3f68000d-b317-4ea0-b969-d12c3eb5bd95)

**Comment by nikolasrieble** [comment]
Did you try combining the flag with svg text directly? https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text

That should work. SVG supports text.

**Comment by bettafish15** [comment]
@nikolasrieble  thanks for your suggestion. I got it working correctly with svg and text.
