### ISSUE TITLE
how to move tick labels on the YAxis further to the left ?

### ISSUE THREAD

**Issue by bettafish15** [recharts/recharts#3958]
## What is the current behavior?
I am using padding property on the XAxis : padding={{left: 120}} but this padding property is not affect the grid and the bar focused by the tooltips.

Am I using the wrong tool for the job ?
![image](https://github.com/recharts/recharts/assets/40290448/c973fa68-6534-4902-9c7d-5e765a398687)

**Comment by nikolasrieble** [comment]
Please provide actual code for reproduction, such as https://codesandbox.io/s/recharts-issue-template-forked-kyp695?file=/src/index.js

Please try to use height or width on the axis.
