### ISSUE TITLE
Problem with space between chart in SynchronizedLineChart

### ISSUE THREAD

**Issue by MateuszGHE** [recharts/recharts#3966]
In SynchronizedLineChart exists some strange behavior that exists space between charts, that when cursor hover it than looks like that we are not on chart. Any possibilities how to solve it that will not be a gap between charts.

**Steps to reproduce**
When you create a SynchronizedLineChart with more than one chart with no gap between is possible to hover a pixel that we losing tooltip and this synchronization on chart. Below I attach a screen
 
![image](https://github.com/recharts/recharts/assets/150913941/436202e2-0ff3-40ea-8b30-7fff5e7db2f4)

**What is expected?**
I suppose that will not exists a gap and I hover first chart and when I move mouse pointer to the second chart will not be a space that will losing a information regarding charts in tooltip.

**Comment by ckifer** [comment]
Does this exist in all recharts versions or only the latest few?

**Comment by MateuszGHE** [comment]
I saw it in Example and in version 2.8.0.

**Comment by ckifer** [comment]
@MateuszGHE can you provide this in a codesandbox? I'm not sure what you're doing here to reproduce

**Comment by MateuszGHE** [comment]
> @MateuszGHE can you provide this in a codesandbox? I'm not sure what you're doing here to reproduce https://codesandbox.io/s/synchronized-area-chart-forked-tn4qnw

You have to just remove:
- margin: 10 (should be 0) 
- hide XAxis in first chart
- text which is between charts "Maybe some other content"

Then you will have 2 charts with no distance between and than is possible to set mouse pointer that you lost focus on chart

**Comment by dawidowski** [comment]
> Sorry, no. We're working on 3.x right now which will make improvements such as hunting this down easier going forward.
> 
> I can try to find a temporary solution at some point though.

@ckifer, I would also like to use this temporary solution, if there is any.

**Comment by ckifer** [comment]
https://codesandbox.io/p/sandbox/synchronized-area-chart-forked-2jcfml

Updated link, I still cannot reproduce this issue. Hovering between the two does not cause the tooltip to go away at any position. Going to close as stale.

**Comment by MateuszGHE** [comment]
> https://codesandbox.io/p/sandbox/synchronized-area-chart-forked-2jcfml
> 
> Updated link, I still cannot reproduce this issue. Hovering between the two does not cause the tooltip to go away at any position. Going to close as stale.
@ckifer 
It is possible to reproduce in this sandbox
![Charts issue with tooltip](https://github.com/user-attachments/assets/608d5b0e-52a6-4e7d-8fe1-37c93fe2e195)

**Comment by ckifer** [comment]
Hmm this doesn't happen for me. 

What browser are you using?

**Comment by MateuszGHE** [comment]
That is Chrome in Version 131.0.6778.86.

**Comment by ckifer** [comment]
Got it, I can reproduce in chromium browsers only then. Firefox is fine.

I'm still hesitant to re-open. there isn't much that recharts can do about this.

We have two svgs that are not overlapping. When you go out of one svg and into another the browser can interpret the space between them (even if there is none) as whatever it wants to. I dove into this a little and removed every element I possibly could without removing the SVG itself - this still happens.

My suggestion would be to add -1 top or bottom margin (depending on which chart its added to) to cause a tiny bit of overlap between the charts.
