### ISSUE TITLE
Some XAxis not showing

### ISSUE THREAD

**Issue by matheusml** [recharts/recharts#397]
I have a simple BarChart, with a XAxis. In some cases, some of the labels are simply not showing up. In the image below, only the middle label is appearing.

![http://i.imgur.com/MRFaXJP.png](http://i.imgur.com/MRFaXJP.png)

Here's the code:

```javascript
<BarChart data={data} barSize={SIZE} width={WIDTH} height={HEIGHT} margin={{ top: 80 }}>
   <XAxis dataKey="name" tick={<CustomizedAxisTick />} />
   <Tooltip formatter={formatTooltip} />
   <Bar dataKey="local" fill="#1f40e6" label={<CustomizedLabel />} />
   <Bar dataKey="global" fill="rgba(30, 63, 230, 0.6)" label={<CustomizedLabel />} />
</BarChart>
```

and

```javascript
const CustomizedLabel = props => {
  // eslint-disable-next-line react/prop-types
  const { x, y, payload } = props;

  return (
    <Text
      x={x}
      y={y + 3}
      fill="#002960"
      fontSize={11}
      textAnchor="middle"
    >{truncate(payload.value)}</Text>
  );
};
```

**Comment by xile611** [comment]
@matheusml By default, we'll hide some ticks of `XAxis` when no enough space. 

[related code](https://github.com/recharts/recharts/blob/master/src/cartesian/CartesianAxis.js#L74)

If you want to show all the ticks, you can set the props `interval` of `XAxis` to be `0`.

**Comment by matheusml** [comment]
Hmm, I think that will do. 
Thanks!

**Comment by Wei-1** [comment]
The link mentioned by @xile611 is changed to:
https://github.com/recharts/recharts/blob/master/src/cartesian/CartesianAxis.tsx

**Comment by gabrielpramos** [comment]
My problem was the wrong date format, I solve it using moment.utc(date).valueOf() instead of new Date(date).getTime()
using Date I had the wrong date so when recharts/es6/util/ChartUtils.js was about o calculate the coordinate attribute to sum with the offset, it's returning NaN. I guess the reason was the milliseconds and a big float offset number.

**Comment by roushanraj** [comment]
I was also facing the same issue. Following is the snippet which worked for me:
`<XAxis dataKey="name" textAnchor= "end" sclaeToFit="true" verticalAnchor= "start"  interval={0} angle= "-40" stroke="#8884d8" />`

**Comment by Brayve-Pancake** [comment]
<XAxis dataKey="name" interval={0}/>

This ensures that every vertical and associated tick is displayed. It resolved the  bug where lines disappear for me!

Docs:
https://recharts.org/en-US/api/XAxis#interval

Usage:
https://recharts.org/en-US/examples/LineChartAxisInterval
