### ISSUE TITLE
Incorrect X-axis when using multiple datasets 

### ISSUE THREAD

**Issue by VaZark** [recharts/recharts#3970]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-nhc59l?file=/src/index.js)

### Steps to reproduce
fetch data from multiple data sources with the same key. When using tow separate Line elements within the LineChart, the X-axis repeats for each dataset (but the the data is mapped to the first copy)

### What is expected?
Recharts must detect and merge the X-axis ticks when multiple datasets exist. Or accept a method to resolve it

### What is actually happening?
Ticks from first and second datasets are rendered in the order they are discovered

| Environment | Info |
|---|---|
| Recharts | v2.9.3 |
| React | 18 |
| System | Linux |
| Browser | Firefox |

---
I'm trying to compare data across two time periods which have a common key 01/10/2023-31/10/2023 and 1/11/2023-30/11/2023

**Comment by ckifer** [comment]
on your x axis `allowDuplicatedCategory={false}` should fix this
