### ISSUE TITLE
Tooltip displays wrong values when there are 2 `Line`s in the chart

### ISSUE THREAD

**Issue by MartinXPN** [recharts/recharts#3971]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/recharts-issue-template-forked-cdsntt?welcome=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp28ypuk00073b6hv3jgcvro%2522%252C%2522sizes%2522%253A%255B59.655831866052054%252C40.344168133947946%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp28ypuk00033b6hfjhtwjvi%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp28ypuk00053b6hufeu2g59%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp28ypuk00063b6htja9namj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp28ypuk00033b6hfjhtwjvi%2522%253A%257B%2522id%2522%253A%2522clp28ypuk00033b6hfjhtwjvi%2522%252C%2522activeTabId%2522%253A%2522clp28ypuk00023b6h7iwb0jdw%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp28ypuk00023b6h7iwb0jdw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clp292jjt00sb3b6h3wqmmc6e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clp28ypuk00063b6htja9namj%2522%253A%257B%2522id%2522%253A%2522clp28ypuk00063b6htja9namj%2522%252C%2522activeTabId%2522%253A%2522clp28zvg000ei3b6hcimffr33%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clp28zvg000ei3b6hcimffr33%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clp28ypuk00053b6hufeu2g59%2522%253A%257B%2522id%2522%253A%2522clp28ypuk00053b6hufeu2g59%2522%252C%2522activeTabId%2522%253A%2522clp28zril00cw3b6h1qualblj%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp28ypuk00043b6howt9nemy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clp28yq250008egjefgccb0uo%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clp28zril00cw3b6h1qualblj%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clp290ffh00kc3b6hfmpppou7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clp290fkv000degje83b16ckv%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce
Have 2 line charts => the tooltip will show wrong values.

### What is expected?
It should show correct values but seems like the payload is populated incorrectly.

### What is actually happening?
Seems like the payload is populated incorrectly before passing to Tolltip. After the first value, all the rest have the same values, even though the lines are different.

| Environment | Info |
|---|---|
| Recharts | v2.9.3 |
| React | ^18.2.0 |
| System | MacOS |
| Browser | Chrome |

**Comment by ckifer** [comment]
Does this work in older recharts versions?

This probably works if data is specified on ComposedChart rather than individual Line components. 

CC: @nikolasrieble @PavelVanecek  this data on each Line, Area, etc. approach seems to be causing a lot of problems 😅

**Comment by MartinXPN** [comment]
Yes, this used to work fine in the previous versions (before I upgraded to the latest one).

**Comment by ckifer** [comment]
@MartinXPN this should be fixed by #3972

I can't 100% say when this will get released though

**Comment by MartinXPN** [comment]
Perfect! Thanks for the great work!

**Comment by nikolasrieble** [comment]
Released with https://github.com/recharts/recharts/releases/tag/v2.10
