### ISSUE TITLE
Chore: increase code coverage of FunnelUtils & DefaultTooltipContent

### ISSUE THREAD

**Issue by imagineLife** [recharts/recharts#3976]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Increase code coverage

### What does the proposed API look like?
no api changes

**Comment by nikolasrieble** [comment]
The related change landed. Closing this. Thank you @imagineLife ❤️
