### ISSUE TITLE
Broken types in v2.10 as "types/index.d.ts" does not exist in package

### ISSUE THREAD

**Issue by amatissart** [recharts/recharts#3978]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/recharts-issue-template-forked-3srh82?file=%2Fpackage.json%3A22%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp5szxue00062067lwoogaux%2522%252C%2522sizes%2522%253A%255B47.7666999%252C52.2333001%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp5szxue00032067qzsvrrbm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp5szxue000420674ywvcuux%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp5szxue000520670crwtxuf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B67.29115164105012%252C32.70884835894988%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp5szxue00032067qzsvrrbm%2522%253A%257B%2522id%2522%253A%2522clp5szxue00032067qzsvrrbm%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp5szxue00022067ygd9ap5r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522id%2522%253A%2522clp5tqqav031s2067cuavuec4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp5szxue00022067ygd9ap5r%2522%257D%252C%2522clp5szxue000520670crwtxuf%2522%253A%257B%2522id%2522%253A%2522clp5szxue000520670crwtxuf%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clp5tye3401gh2067xj6hj6st%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp5tye3401gh2067xj6hj6st%2522%257D%252C%2522clp5szxue000420674ywvcuux%2522%253A%257B%2522id%2522%253A%2522clp5szxue000420674ywvcuux%2522%252C%2522activeTabId%2522%253A%2522clp5ttot3007t2067lrn8yjw4%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp5ttot3007t2067lrn8yjw4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clp5ttou80011egesbx4g8rjm%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522tsc%2522%252C%2522id%2522%253A%2522clp5twnec00fp2067tcind1no%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce
1. Install "recharts==2.10.0" in the Recharts Issue Template repository with Typescript configured.
2. Run "tsc"

### What is expected?
Typechecking works out of the box. The "recharts" package provides types.

### What is actually happening?
error TS7016: Could not find a declaration file for module 'recharts'.

| Environment | Info |
|---|---|
| Recharts | v2.10 |
| React | 17 |
| System | Linux Fedora 38 |
| Browser | Firefox  |

---
The release contains "types/src/index.d.ts", whereas package.json points to "types/index.d.ts"

**Comment by nikolasrieble** [comment]
@HHongSeungWoo Could this have to do with the Typescript upgrade?

**Comment by nikolasrieble** [comment]
No, I found the root cause in this line in the tsconfig. 


```
  "include": ["./src/**/*", "types.d.ts", "./test/**/*"]
```

The causing PR was https://github.com/recharts/recharts/issues/3890

Thank you for finding this, i will try to find time to do a patch release tomorrow.

**Comment by nikolasrieble** [comment]
I just did a patch release 2.10.1. I locally verified that this worked me. Can you please confirm it also worked for you, @amatissart? Thank you for your help.

**Comment by amatissart** [comment]
I can confirm it's fixed in v2.10.1. Thanks!

**Comment by ckifer** [comment]
Thanks for the patch Niko - we need a test against this
