### ISSUE TITLE
Can't change X and Y axis font size in v2.10

### ISSUE THREAD

**Issue by kbeeveer46** [recharts/recharts#3979]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-8zvjrd?file=/src/index.js)

### Steps to reproduce
The fontSize property was removed from XAxis and YAxis. Try setting the font size by either using label={{ fontSize: "30px" }} or label={{ className: "largeFont" }}. Maybe I'm just not doing it correctly in v2.10? I don't see any other way to do it.

### What is expected?
I would expect to to change the font size

### What is actually happening?
The default font size is used.

| Environment | Info |
|---|---|
| Recharts | v2.10 |
| React | 17.0.1 |
| System | Windows? |
| Browser | Chrome latest |

**Comment by kbeeveer46** [comment]
Here are a few other breaking changes. Not sure if they were on purpose or not...

- "fontFamily" was removed from YAxis and XAxis 
- "wrapperClassName" was removed from Tooltip

**Comment by nikolasrieble** [comment]
<img width="1088" alt="Screenshot 2023-11-19 at 21 31 38" src="https://github.com/recharts/recharts/assets/27995606/06502df4-02a0-4db0-9d33-94dde7224b55">

Not sure I understand the problem. You need to also pass a value for the label, otherwise everything else will not take effect. 

This works: 

```
    <YAxis label={{fontSize: 30, value: 'test'}} />
```

**Comment by kbeeveer46** [comment]
@nikolasrieble Maybe I didn't explain it correctly. I want to change the font size of 10,000, 7,500 etc. on the Y axis (and the values on the X axis). There used to be a fontSize property but it was removed in v2.10. Here is what I mean

`<XAxis dataKey={this.props.xAxisValue}  fontSize={11}>`

**Comment by nikolasrieble** [comment]
We certainly did not intend to do breaking changes in this release. 😓 
I believe the confusion here stems from ticks vs label. 
The label is a unique name for the axis. You can set the tick fontSize and fontFamily etc as such: 

```
  <YAxis tick={{ fontSize: "30px" }} />
```

<img width="1088" alt="Screenshot 2023-11-19 at 21 50 31" src="https://github.com/recharts/recharts/assets/27995606/8a62145a-8e65-4ddd-9883-6e334d4e3994">

**Comment by kbeeveer46** [comment]
@nikolasrieble Thanks! That was my bad for using the wrong terminology. I figured there would be another way to do it but just in case that property was removed on accident I wanted to make a post on here. There were a few other properties that were removed that I posted above (I recently edited it to add another). If that was on purpose then you can ignore that comment.

**Comment by nikolasrieble** [comment]
We will follow up here. If this was on purpose, we should have communicated it better. I will not close this issue until we have clarification. Thank you for your help! ❤️

**Comment by ckifer** [comment]
We need to find the PR this change came from and see if it's a type problem, a prop spreading problem, or both.

I suspect it's due to every component inheriting all SVGProps in types and then types being adjusted because they weren't accurate

**Comment by kbeeveer46** [comment]
Did you change anything regarding this in 2.10.1? All of the properties that gave me errors are working now. I swear they didn't work in 2.10 lol. It threw like 40 errors after I tried to build my project after upgrading to 2.10.0 and I went through and commented them all out. I tried using one of them now and I don't get any errors.

**Comment by ckifer** [comment]
Ah it's because there was an accidental exclusion of all of recharts types in the 2.10, which explains why nothing was working 😅

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/issues/3978

**Comment by nikolasrieble** [comment]
Thank you for confirmation, happy that this is solved.
