### ISSUE TITLE
Using stackId prop breaks charts with only 1 Bar

### ISSUE THREAD

**Issue by RoarkeRandall** [recharts/recharts#398]
Using the StackedBarChart http://jsfiddle.net/kca9npkg/6/?utm_source=website&utm_medium=embed&utm_campaign=kca9npkg

Try removing one of the bars in the stack and keeping `stackId={'a'}` and it will not render. 

Not a huge issue, but it's nice to be able to use the stackId prop whether or not you have multiple series.

**Comment by xile611** [comment]
@RoarkeRandall Thanks! It should be fixed.
