### ISSUE TITLE
LabelList offset prop

### ISSUE THREAD

**Issue by flammajl** [recharts/recharts#3986]
There was a PR to fix [this issue](https://github.com/recharts/recharts/issues/3938) that included an Omit to remove the offset prop, so now it's screaming there's a type error when building the app. I had to downgrade recharts to v2.9.3 to solve this issue, was the change really intended ?

**Comment by ckifer** [comment]
Hey thanks for the report, this was intentional but I could've overlooked something

Can you provide a code snippet with how you are using `offset`?

**Comment by ckifer** [comment]
LabelList with `offset` doesn't seem to do anything even in 2.9.3 
https://codesandbox.io/s/simple-line-chart-labellist-offset-96vwq7?file=/src/App.tsx

**Comment by flammajl** [comment]
I guess it only does something when coupled with de position prop ( didn't know it worked like that )

https://codesandbox.io/p/sandbox/simple-line-chart-labellist-offset-forked-h493py

**Comment by flammajl** [comment]
> Hey thanks for the report, this was intentional but I could've overlooked something
> 
> Can you provide a code snippet or sandbox with how you are using `offset`?

Sorry for the delay, this is roughly the use case

https://codesandbox.io/p/sandbox/simple-bar-chart-forked-qggpmj?file=%2Fsrc%2FApp.tsx

I have to display two `LabelList` on one `Bar`, the real use case is like the amount on one LabelList and the % on the other one

**Comment by ckifer** [comment]
I didn't know it worked like that either 😅

Just FYI I may be slow to respond this week due to the US holiday. Thanks!

**Comment by ckifer** [comment]
should be fixed in next patch release

**Comment by ckifer** [comment]
fixed in 2.10.2
