### ISSUE TITLE
 Delete pie chart border values ​​or change color

### ISSUE THREAD

**Issue by squll1** [recharts/recharts#400]
![Alt text](http://cfile30.uf.tistory.com/image/25685C3558534FA834ECE1)
Is there a way to remove the border value or change the color of the pie chart?
There is no option for the border value when viewing the document.

**Comment by xile611** [comment]
@squll1  

```jsx
  <Pie stroke="none" fill="red" />
   
   <Pie stroke="none" fill="red">
      <Cell fill="red" />
      <Cell fill="green" />
      <Cell fill="blue" /> 
   </Pie>
```

Just like svg elements. You can change the color of `Pie` by changing the `fill` of `Pie` or `Cell`.

[demo](http://recharts.org/examples#PieChartWithCustomizedLabel)

**Comment by FBosler** [comment]
@xile611  is there a documentation on all the properties somewhere?
