### ISSUE TITLE
Chart re-render does not respect Brush bounds

### ISSUE THREAD

**Issue by ZephD** [recharts/recharts#401]
Changing the brush bounds causes a render, which respects the bounds provided by the brush and therefore updates the graph to display the data within the brush bounds.

However, if something _else_ causes an update, the bounds are not respected, and the full graph is rendered, despite the brush bounds being set.

**Comment by xile611** [comment]
@ZephD Yeah, the brush will be updated to default props when chart receives a new props.

**Comment by xile611** [comment]
Can you create a demo about your case ?

**Comment by ZephD** [comment]
Try http://jsfiddle.net/b1Lb3kuk/10/

Set the brush to be zoomed in
then hover over an item in the table
The view is re-rendered fully zoomed out, as the brush bounds are ignored.

**Comment by ZephD** [comment]
Tried with 20.2. This issue is _not_ solved. :(

**Comment by ashutoshjha1409** [comment]
@ZephD Did you get any solution for this?

**Comment by ZephD** [comment]
Nope. 3339d6b did not solve this issue.

**Comment by Billy-** [comment]
Also having this issue, any fix planned? @xile611

**Comment by ZephD** [comment]
27b2d33 solved it!

**Comment by ZephD** [comment]
@xile611 
I'm using 1.0.0-beta.10 and this issue seems to be back.
When my chart re-renders, the set brush range is reset to encompass all data.
