### ISSUE TITLE
label for only parts of the pie- label-line Not deleted

### ISSUE THREAD

**Issue by linaffilomania** [recharts/recharts#4010]
hi i am try to give just to part of the pie label and when i no give label the label-line no delete 
i give example
          <Pie   data={dataPie}  label={renderLabel}  cx="55%"  cy="52%" outerRadius="70%" innerRadius={75} >
            <Label fill="black" value={label} position="center" />
            <LabelList dy={-1}  fill="white" dataKey={renderCount} position="inside" angle="0" stroke="none" />
          </Pie>
     const renderLabel = (data) => {
    if(data.value > ((parseInt(label)*5)/100)){
      return data.name;
    }
  }
  const renderCount = (data) => {
    if(data.value > ((parseInt(label)*5)/100)){
      return data.value;
    }
  }
![Screenshot from 2023-12-04 10-52-18](https://github.com/recharts/recharts/assets/122976282/dd74096b-f45b-4564-b814-b79ae0816c60)

**Comment by linaffilomania** [comment]
<Pie   data={dataPie}  label={renderLabel}  cx="55%"  cy="52%" outerRadius="70%" innerRadius={75} >
            <Label fill="black" value={label} position="center" />
            <LabelList dy={-1}  fill="white" dataKey={renderCount} position="inside" angle="0" stroke="none" />
          </Pie> 
          this my piechart

**Comment by ckifer** [comment]
@linaffilomania Can you give a codesandbox reproduction?

[![Edit pie-chart-of-two-levels (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/pie-chart-of-two-levels-gor24)

**Comment by ckifer** [comment]
You can do similarly to what you do now with your label

[![Edit pie-chart-of-two-levels (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/pie-chart-of-two-levels-gor24)

```tsx
const dataPie = [
  { name: "A1", value: 100 },
  { name: "A2", value: 300 },
  { name: "B1", value: 100 },
  { name: "B2", value: 80 },
  { name: "B3", value: 40 },
  { name: "B4", value: 30 },
  { name: "B5", value: 4000 },
  { name: "C1", value: 5000 },
  { name: "C2", value: 200 },
  { name: "D1", value: 150 },
  { name: "D2", value: 50 }
];
const label = "10000"

const renderLabel = (data) => {
  if(data.value > ((parseInt(label)*5)/100)){
  return data.name;
  }
}
const renderCount = (data) => {
  if(data.value > ((parseInt(label)*5)/100)){
  return data.value;
  }
}
const renderLabelLine = (data) => {
  if(data.value > ((parseInt(label)*5)/100)){
    return <Line points={data.points} dot={false} />;
  }
}

export default function App() {
  return (
    <PieChart width={400} height={400}>
      <Pie   data={dataPie}  label={renderLabel} labelLine={renderLabelLine}  cx="55%"  cy="52%" outerRadius="70%" innerRadius={75} >
        <Label fill="black" value={label} position="center" />
        <LabelList dy={-1}  fill="white" dataKey={renderCount} position="inside" angle="0" stroke="none" />
      </Pie> 
    </PieChart>
  );
}
```
