### ISSUE TITLE
RadialBar background={{ className }} ignored

### ISSUE THREAD

**Issue by nik-webdevelop** [recharts/recharts#4011]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/rechart-radial-bar-classname-bug-cl3ll5?file=%2Fsrc%2FApp.tsx)

### Steps to reproduce
Check if RadialBar gets 'custom-class' in background's class list

### What is expected?
background={{ className }} to be merged with background svg element's classes

### What is actually happening?
background={{ className }} ignored 

| Environment | Info |
|---|---|
| Recharts | v2.10.3 |
| React | react 18.2.0 |
| System | Win 10 x64 |
| Browser | Google Chrome Version 119.0.6045.160 (Official Build) (64-bit) |

**Comment by ckifer** [comment]
Hey @nik-webdevelop 

This should be pretty easy to fix - would you like to contribute?

https://github.com/recharts/recharts/blob/master/src/polar/RadialBar.tsx#L370

Just take `backgroundProps.className` and append it to that string using `clsx` there

```jsx
clsx('recharts-radial-bar-background-sector', backgroundProps.className)
```

**Comment by ckifer** [comment]
This should be fixed on next release 

Going to close for now

**Comment by nik-webdevelop** [comment]
@ckifer Sorry I forgot about this issue. Thank you very much for the fix!
