### ISSUE TITLE
Barchart bars not being generated in chrome sometimes

### ISSUE THREAD

**Issue by Impactly-Emil-Georgi** [recharts/recharts#4014]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/recharts-issue-template-k2xqp)

### Steps to reproduce
I dont know what causes it

### What is expected?
the bar to be showing

### What is actually happening?
the bars is not showing

| Environment | Info |
|---|---|
| Recharts | v2.10.3 |
| React | 18.0.0 |
| System | windows 11 22H2 |
| Browser | Chrome 120.0.6099.71 |

**Comment by ckifer** [comment]
Hi, the given example isn't for a barchart. Can you give any more information? BarCharts seem to be working fine in chrome

**Comment by ckifer** [comment]
Going to close this since we haven't gotten a response - feel free to respond again with an example and we can re-open
