### ISSUE TITLE
Creating a wrapper for XAxis and YAxis will fail to render the chart

### ISSUE THREAD

**Issue by zeroliu** [recharts/recharts#4017]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/rechart-axis-wrapper-fzhjzm?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq1jy2qb00063b6jgasoyaeq%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq1jy2qb00023b6jgntqdbem%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq1jy2qb00033b6jpg9lsto1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq1jy2r8000i3b6jxld5c466%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq1jy2qb00053b6j6mzpcvag%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq1jy2qb00023b6jgntqdbem%2522%253A%257B%2522id%2522%253A%2522clq1jy2qb00023b6jgntqdbem%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clq1jy2qb00053b6j6mzpcvag%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq1jy2qb00043b6jlyrpnr2d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clq1jy2qb00053b6j6mzpcvag%2522%252C%2522activeTabId%2522%253A%2522clq1jy2qb00043b6jlyrpnr2d%2522%257D%252C%2522clq1jy2qb00033b6jpg9lsto1%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clq1jy2qb00033b6jpg9lsto1%2522%257D%252C%2522clq1jy2r8000i3b6jxld5c466%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SANDBOX_ONBOARDING%2522%252C%2522id%2522%253A%2522sandbox-onboarding%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522id%2522%253A%2522clq1jy2r8000i3b6jxld5c466%2522%252C%2522activeTabId%2522%253A%2522sandbox-onboarding%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce
- Create a wrapper component for either XAxis or YAxis component
- Use the wrapper component as Axis component

### What is expected?
The axis should continue to render correctly

### What is actually happening?
The axis is not rendered at all

| Environment | Info |
|---|---|
| Recharts | v2.10.3 |
| React | 18 |
| System | MacOS |
| Browser | Chrome 119 |

**Comment by ckifer** [comment]
This is known. Recharts has some interesting logic that relies closely on the component structure of the components. Trying to work on addressing that a bit in the next major version, but for now you can do like in the s[andbox here](https://codesandbox.io/p/sandbox/rechart-axis-wrapper-fzhjzm?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq1jy2qb00063b6jgasoyaeq%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq1jy2qb00023b6jgntqdbem%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq1jy2qb00033b6jpg9lsto1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq1jy2qb00053b6j6mzpcvag%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq1jy2qb00023b6jgntqdbem%2522%253A%257B%2522id%2522%253A%2522clq1jy2qb00023b6jgntqdbem%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clq1jy2qb00053b6j6mzpcvag%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq1jy2qb00043b6jlyrpnr2d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clq1jy2qb00053b6j6mzpcvag%2522%252C%2522activeTabId%2522%253A%2522clq1jy2qb00043b6jlyrpnr2d%2522%257D%252C%2522clq1jy2qb00033b6jpg9lsto1%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clq1jy2qb00033b6jpg9lsto1%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

Pass your wrapper component to `AxisComp` prop of `XAxis` and provide props as normal

```jsx
 `<XAxis AxisComp={CustomXAxis} dataKey="name" />
```

**Comment by ckifer** [comment]
Closing as known, this will be addressed in the future

**Comment by zeroliu** [comment]
The same problem happens to other Recharts components such as Tooltip too

**Comment by ckifer** [comment]
Yep - same reason and same solution

You can make a custom tooltip using the `content` prop
https://recharts.org/en-US/api/Tooltip#content 

Examples here
https://github.com/recharts/recharts/blob/master/storybook/stories/Examples/Tooltip.stories.tsx#L178-L212

**Comment by zeroliu** [comment]
Thanks for the context. My goal for the wrapper is to share the configurations for the axis and tooltip since I'm building several types of charts that share the same structure. I end up using a function that returns the props as an object and it works well. A future version that allows custom component wrappers will be cool.
