### ISSUE TITLE
Setting a tickCount for YAxis does not show a tick as much as that count.

### ISSUE THREAD

**Issue by dbstjddbwls** [recharts/recharts#4019]
I set up YAxis, but I don't see as much tick as the value of tickCount. 

If I don't set domain to min,max, it will show as much as the value of count, but this is not what I want.

There is no problem with how the data is structured, and when used with the image, the tickCount is 3, but only two ticks of YAxis are shown.

![image](https://github.com/recharts/recharts/assets/37412832/45017fcd-959b-4dfd-8454-043c2d5e82a2)

**Comment by nikolasrieble** [comment]
Some of the magic of recharts is how props are interacting - this is not documented well. 

The key to the ticks that are shown is the `interval`. The interval props defines the collision handling strategy, when two ticks are too close to each other. 

If you set `interval={0}` you will see every tick. 
Consider looking into the story in storybook that explains tick positioning https://master--63da8268a0da9970db6992aa.chromatic.com/?path=/story/examples-cartesian-cartesian-axis-tick-positioning--tick-positioning

Does this answer your question?
