### ISSUE TITLE
Area chart starts go upper sooner then it should do 

### ISSUE THREAD

**Issue by simpy25** [recharts/recharts#4022]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://no-link.com](https://no-link.com)

### Steps to reproduce
``` 
const transformedData= [
    {
        "time": "00:00",
        "amount": 1
    },
    {
        "time": "17:00",
        "amount": 100
    },
    {
        "time": "20:00",
        "amount": 100
    },
    {
        "time": "23:59",
        "amount": 1
    }
]
<AreaChart width={600} height={300} data={transformedData}>
                    <XAxis dataKey="time"/>
                    <YAxis domain={[0, 'dataMax']}/>
                    <Tooltip/>
                    <Area
                        type="step"
                        dataKey="amount"
                        stroke="#00A4A6"
                        fill="#66B34D"
                        strokeWidth={4}
                        strokeOpacity={1}
                    />
                </AreaChart>
```

### What is expected?
https://github.com/recharts/recharts/assets/105854603/1084914d-71fa-4859-9a29-29cc63801020

### What is actually happening?
https://github.com/recharts/recharts/assets/105854603/9678dcbf-6b4d-462c-9883-8e941ccab30d

| Environment | Info |
|---|---|
| Recharts | v2.10.3 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome |

**Comment by nikolasrieble** [comment]
What is an axis scale? This is a great documentation to understand the problem better. https://d3js.org/d3-scale

Recharts can not magically treat your xAxis values as timestamps - since they are strings.
The data you provided could as well be 
```
{
        "time": "Hi",
        "amount": 1
    },
    {
        "time": "I am a string",
        "amount": 100
    },
...
``` 

If you instead want to plot it as a time series, make sure to pass an actual numeric value, such as unix time. 

Please look into our documentation or into storybook to find actual example of time series charts.

**Comment by ckifer** [comment]
[![Edit simple-area-chart (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/simple-area-chart-forked-7ltnc8)

**Comment by ckifer** [comment]
Going to close this as stale, feel free to comment back if this needs re-opened
