### ISSUE TITLE
Set the maximum height of bar

### ISSUE THREAD

**Issue by matthewberkompas** [recharts/recharts#403]
@xile611 Is there a way to set the maximum height of a bar? I'm trying to make the bar labels show up on the chart but I run into problems when only one bar is showing (e.g. when there isn't any data for the other bars). In this case, that bar goes all the way to the top and the label gets hidden ([see demo](http://jsfiddle.net/matthewberkompas/n5re8vcq/5/)). Even if the label didn't get hidden, I would prefer to set a maximum height on the bar so it doesn't ever go to the top of the chart. I looked through all the props on the `Bar` component but couldn't find anything that would solve this issue.

**Comment by xile611** [comment]
@matthewberkompas It's a workaround to set the `domain` of `YAxis` like the following:

```jsx
  <YAxis domain={[0, 'dataMax + 600']} />
```

You can also check the api of [`domain`](http://recharts.org/api#YAxis) and [demo](http://jsfiddle.net/3gdz149g/).

Meanwhile I'll try to optimize this case. Thoughts and suggestions are welcome.

**Comment by matthewberkompas** [comment]
@xile611 This workaround should fix the issue for now, thanks! In future, it would be nice if the max bar height could be set by a `maxBarHeight` prop or something similar to that.
