### ISSUE TITLE
ResponsiveContainer Bug 

### ISSUE THREAD

**Issue by vaeum** [recharts/recharts#404]
Hello, if i use ResponsiveContainer and BarChart, and render many bars, bars not visible.

Check this demo
http://jsfiddle.net/vaeum/7z05b3yj/

Try delete ResponsiveContainer and re run demo.

**Comment by konstantin24121** [comment]
@vaeum try to set width: 100% for ResponsiveContainer, and remove width and heigth for BarChart.
ResponsiveContainer set width and heigth to his children.
http://jsfiddle.net/ywy068f2/
