### ISSUE TITLE
Linear Gradient   Negative chart values do not work as shoud.

### ISSUE THREAD

**Issue by BiosBoy** [recharts/recharts#4044]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/Sviatoslav_FrontEnd/pen/MWxeBqb?editors=1111](https://codepen.io/Sviatoslav_FrontEnd/pen/MWxeBqb?editors=1111)

### Steps to reproduce
Use the codesandbox link above. Add more negative values if needed to the chart.

### What is expected?
 - With negative values in mind chart should be filled up to the bottom line with a gradient (e.g. to the lowest possible value).
Screenshot:
<img width="950" alt="Screenshot 2024-01-09 at 18 54 15" src="https://github.com/recharts/recharts/assets/30953392/af4ae1ec-2f11-4afe-9eea-b86dd4a754d7">

### What is actually happening?
 - When I use negative values in my chart dataset it does not work well with filling all the space with gradient. You can find here that the gradient always returns to the 0 point and I don't sure why.
Screenshot:
<img width="604" alt="Screenshot 2024-01-09 at 18 51 44" src="https://github.com/recharts/recharts/assets/30953392/b7bf247a-675f-4a25-9b64-e77cafbb164d">

| Environment | Info |
|---|---|
| Recharts | v2.10.3 |
| React | 18 |
| System | macOS |
| Browser | Chrome 120.0.6099.109 |

---
Thanks!

**Comment by ckifer** [comment]
I can't get your codepen to run. Do you mind porting it over to codesandbox?
[![Edit simple-area-chart (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/simple-area-chart-4ujxw)

**Comment by BiosBoy** [comment]
Sure, here you go https://codesandbox.io/p/sandbox/reachart-bug-test-ntzfm5 @ckifer

**Comment by BiosBoy** [comment]
I have tried set `domain=[min, max]`, to override 0 as a base, however, it did not solve the issue.

**Comment by ckifer** [comment]
Your API call doesn't work because of XSRF protection, you may need to adjust the example a bit

**Comment by BiosBoy** [comment]
Try to use in incognito mode or another browser. Both examples work fine. Not sure why they don't work on your side and what could I adjust. This is a public API with shared code from another example that I just forked myself. I'm using Chrome Latest.

**Comment by ckifer** [comment]
Also using Chrome latest / Firefox latest. No response from the API - failing with `ERR_NAME_NOT_RESOLVED` like it doesn't exist

**Comment by BiosBoy** [comment]
Okay, so I gathered data in a static file for you. No API at all. Please take a look once you have a moment. Same link - https://codesandbox.io/p/sandbox/reachart-bug-test-ntzfm5 @ckifer thanks!

**Comment by ckifer** [comment]
@BiosBoy this is less about the linear gradient and more about how area charts work in general. 

If you take a look at other charting libraries they do the same thing 
Highcharts for example: https://www.highcharts.com/demo/highcharts/area-negative

They all use 0 as the basis point since the shaded area is either showing how much is added to 0 or how much is taken away from 0. What is the assumption you're using with this linear gradient? Does the user know or expect the area to represent the amount from the minimum value on the chart?

**Comment by ckifer** [comment]
Other APIs to allow a `threshold` option which would give modification of the 0 point to some other arbitrary number.

See https://api.highcharts.com/highcharts/plotOptions.area.threshold 

Recharts does not currently allow this though

**Comment by BiosBoy** [comment]
Got it. Thank you

**Comment by ckifer** [comment]
actually, it does! Try setting `baseValue` on `Area` to your minimum tick

```
baseValue={-50000}
```

**Comment by ckifer** [comment]
@BiosBoy gets you the chart you want but... that is the tick value and not your actual data so not sure how you'd set it dynamically. Maybe you could use some assumptions and get a good value for it
<img width="739" alt="image" src="https://github.com/recharts/recharts/assets/25180830/7a00bb73-094e-477d-9460-5621980f5763">

**Comment by BiosBoy** [comment]
oh, Lord! Thank you sir! You saved my day :)

**Comment by ckifer** [comment]
Glad to be able to help 🚀
