### ISSUE TITLE
Radar: dot props event handler onMouseOver does not work.

### ISSUE THREAD

**Issue by nikolasrieble** [recharts/recharts#4049]
# Summary
The Radar component exposes `dot` props, which can take event handlers such as onMouseOver. 
In other components, such as the line, these do work. 

```
      <Radar
        dataKey="pv"
        fill="none"
        dot={{ onMouseEnter: (e) => console.log(e) }}
        strokeWidth={2}
        stroke="blue"
      />
```

Expected behaviour: Logs created when hovering over the dots. 

Actual behaviour: Nothing happens. 

# Reproduction

https://codesandbox.io/p/sandbox/recharts-issue-template-forked-hp9rs3

**Comment by AnujSharma141** [comment]
hi @ckifer .. in `Radar.tsx` there is a `renderDots` function in which we have `const customDotProps = filterProps(dot);` ... filterProps has a `includeEvents` parameter which is type boolean... 
![image](https://github.com/recharts/recharts/assets/16597292/1db81863-40fa-46c3-8c4d-52a3b7f6accc)
.. now if we do `const customDotProps = filterProps(dot, true);` the events works the way it should

**Comment by ckifer** [comment]
Sounds good!
