### ISSUE TITLE
Tooltip: Payload props are missing className 

### ISSUE THREAD

**Issue by nikolasrieble** [recharts/recharts#4050]
Reproduction: https://codesandbox.io/p/sandbox/recharts-issue-template-forked-v2fsqd

The payload contains the className of the elements related to each payload. 
<img width="1032" alt="Screenshot 2024-01-11 at 21 54 07" src="https://github.com/recharts/recharts/assets/27995606/a8af7acc-5205-4454-b111-d45f4c542262">

The Tooltip payload type itself was not correctly updated, when the className was added in the first place. That is why it is possible to log out a className, but still get a TS error, such as

<img width="648" alt="Screenshot 2024-01-11 at 21 53 09" src="https://github.com/recharts/recharts/assets/27995606/36689fcf-4256-4b37-927a-5082ca267601">

Acceptance criteria: Add optional className to type of the Payload

**Comment by Nikhilh26** [comment]
Hey ! I am new in OSS can you elaborate on the problem and assist me a little

**Comment by Nikhilh26** [comment]
you want to add className property on payload or entry? @nikolasrieble

**Comment by ckifer** [comment]
added in https://github.com/recharts/recharts/pull/4069
