### ISSUE TITLE
Application zoom makes chart detect mouse position more to the left than it actually is ( for zoom 0.8  )

### ISSUE THREAD

**Issue by BogdanH95** [recharts/recharts#4051]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/p/sandbox/recharts-issue-template-forked-6lylzy?file=%2Fsrc%2Fstyles.css)

### Steps to reproduce
On any chart using tooltips will be visible when changing the css zoom property of body parent. 

### What is expected?
Mouse position to be read exactly where is on the chart

### What is actually happening?
For zoom < 1 mouse position is read more to the left than actually is

| Environment | Info |
|---|---|
| Recharts | v2.10.4 |
| React | 18.2.0 |
| System | Windows 10  |
| Browser | Chrome last version /Edge last version |

---
No workaround found

**Comment by ckifer** [comment]
Try using transform: scale instead of css zoom, it has better browser support and behaves more predictably

**Comment by ckifer** [comment]
As per the mdn docs 
, css zoom is a non standard css property https://developer.mozilla.org/en-US/docs/Web/CSS/zoom

**Comment by BogdanH95** [comment]
Thank you dude! This was the solution. it works as expected now.

**Comment by jeffshaver** [comment]
I just ran into this exact problem pretty much. but when i go to https://developer.mozilla.org/en-US/docs/Web/CSS/zoom it doesn't seem non-standard anymore?

**Comment by ckifer** [comment]
Looks like you're right. I'd keep using transform: scale because it works. No idea why Zoom doesn't work but unless someone wants to deep dive we have a good working alternative that shouldn't affect anything

**Comment by jeffshaver** [comment]
@ckifer i tried switching to trnasform:scale for my use-case, but it doens't work the same, this paragraph from mdn kind of explains the issue that i have switching to transform:scale

![2024-08-01_10:29:14](https://github.com/user-attachments/assets/119eee4d-350f-4f4a-8544-9580d7d45400)

**Comment by jeffshaver** [comment]
also, im not sure if its because im using ResponsiveContainer, but it seems as though transform scale is definitely not workable. it always ends up way too large

**Comment by ckifer** [comment]
Can you make a codesandbox that represents the issue?

**Comment by jeffshaver** [comment]
@ckifer in this codesandbox (https://codesandbox.io/p/sandbox/simple-line-chart-forked-qfdp6c), if you hover over in order to get the tooltips, you can see that it doesn't really work correctly. if you hover over any given point, you probably wont get the correct tooltip to show up.

**Comment by ckifer** [comment]
So it looks like transform: scale "works", but it doesn't do what you want. Got it.

Can you make a new feature request to support CSS zoom? I don't really want to re-open this since the issue is solved for the original creator.

I don't see this as a bug, but rather something unsupported by recharts at this time.

**Comment by jeffshaver** [comment]
@ckifer sorry, i went on vacation last week. i made a new issue for this: https://github.com/recharts/recharts/issues/4884
