### ISSUE TITLE
Keyboard navigation with accessibilityLayer can break

### ISSUE THREAD

**Issue by dahlie** [recharts/recharts#4052]
Could not easily reproduce the error in Codesandbox, but we run into a bug where keyboard navigation with accessibility layer didn't work correctly if we used `setState()` in our `onMouseMove()` event handler.

After some investigation, I think the bug was caused because:

1. We had defined margins for our chart using inline object as a prop: `margin={{ top: ... }}`
2. We called `setState()` in our event handler, which caused the component to re-render itself
3. https://github.com/recharts/recharts/blob/70f730083bd8e06b44d5449e0aae68301336d885/src/chart/generateCategoricalChart.tsx#L1202 was trigged due to object references being different
4. Resulting `setDetails()` call only sets `offset` prop which means `coordinateList = []` default parameter in `AccessibilityManager` which effectively resets the previously set coordinates
5. This condition prevents keyboard navigation working https://github.com/recharts/recharts/blob/70f730083bd8e06b44d5449e0aae68301336d885/src/chart/AccessibilityManager.ts#L54 

We could fix the navigation by using stable object reference for `margin` props, but a proposed fix for this issue would be to either always provide `coordinateList`, `layout` and `offset` props when calling `setDetails()` or perhaps updating the `setDetails()` function to something like this:

```
public setDetails({
    coordinateList = null,
    container = null,
    layout = null,
    offset = null,
    mouseHandlerCallback = null,
  }: InitiableOptions) {
    this.coordinateList = coordinateList ?? this.coordinateList ?? []; // Use default array here instead
    this.container = container ?? this.container;
    this.layout = layout ?? this.layout;
    this.offset = offset ?? this.offset;
    this.mouseHandlerCallback = mouseHandlerCallback ?? this.mouseHandlerCallback;

    // Keep activeIndex in the bounds between 0 and the last coordinate index
    this.activeIndex = Math.min(Math.max(this.activeIndex, 0), this.coordinateList.length - 1);
  }
```

**Comment by ckifer** [comment]
Thanks for the details and looking into it @dahlie! Do you want to open a PR for this? 

I probably prefer the second approach here but I'm confused on how it fixes the issue? Wouldn't `coordinateList` still have a length of 0 with using an empty array?

**Comment by ckifer** [comment]
@julianna-langston fyi

**Comment by dahlie** [comment]
Sure, I'll try to create a PR for the fix 👍🏻

**Comment by julianna-langston** [comment]
Let me know if there's anything I can do to help
