### ISSUE TITLE
Docs: animationBegin prop is not available for Tooltip component

### ISSUE THREAD

**Issue by beltranrengifo** [recharts/recharts#4053]
Hi there!

As stated in [the docs page](https://recharts.org/en-US/api/Tooltip#animationBegin), Tooltip should have enabled an `animationBegin` prop to delay the animation. However I find that's not the case:
![image](https://github.com/recharts/recharts/assets/19485114/91f6db15-19e7-4647-aa0f-553302f9e63a)

Indeed it does not exist in `Tooltip.d.ts`.
I wonder if this is a matter with documentation or with code.

Thanks for your support 😃

**Comment by ckifer** [comment]
Hi, it looks like this is a documentation problem - the Tooltip does not have a `animationBegin` property. `animationBegin` seems to be used by some/most charts though.

See duplicate issue
https://github.com/recharts/recharts/issues/1794

https://master--63da8268a0da9970db6992aa.chromatic.com/?path=/docs/api-chart-areachart--docs#properties
In the storybook there, there is a `throttleDelay` property on each chart type. Give that a shot see if it fits your case

Example: [![Edit simple-line-chart (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/simple-line-chart-kec3v?file=%2Fsrc%2FApp.tsx)

`animationBegin` should be removed and `throttleDelay` should be added to the website

**Comment by beltranrengifo** [comment]
> Hi, it looks like this is a documentation problem - the Tooltip does not have a `animationBegin` property. `animationBegin` seems to be used by some/most charts though.
> 
> See duplicate issue #1794
> 
> [master--63da8268a0da9970db6992aa.chromatic.com/?path=/docs/api-chart-areachart--docs#properties](https://master--63da8268a0da9970db6992aa.chromatic.com/?path=/docs/api-chart-areachart--docs#properties) In the storybook there, there is a `throttleDelay` property on each chart type. Give that a shot see if it fits your case
> 
> Example: [![Edit simple-line-chart (forked)](https://camo.githubusercontent.com/97cbe82b1619b42e1f78fce9db09104b932a9da1fd37751f4d9c41f4fe350241/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/p/sandbox/simple-line-chart-kec3v?file=%2Fsrc%2FApp.tsx)
> 
> `animationBegin` should be removed and `throttleDelay` should be added to the website

good to know! I tried with `throttleDelay` in `Treemap` but that chart does not seem to have that prop. Am I right?
 
![image](https://github.com/recharts/recharts/assets/19485114/89ca2ee9-31e0-4088-a980-8811d01165d0)


thanks for your support

**Comment by nikolasrieble** [comment]
Sadly, our storybook transition is still not done. The motivation remains: The docs page is horribly outdated and misleading. Please use (and maybe even extend) our storybook instead.

**Comment by ckifer** [comment]
Storybook still has the misrepresented property in this case

**Comment by ckifer** [comment]
@beltranrengifo treemap has a separate implementation from the rest so yeah the prop isn't included there unfortunately

**Comment by beltranrengifo** [comment]
Good to know, thank you all. I'll try to find the way to collaborate, at least with the Storybook 🙂

**Comment by ckifer** [comment]
`animationBegin` removed from website https://recharts.org/en-US/api/Tooltip

also removed from storybook https://github.com/recharts/recharts/commit/1c834634334f6779a05026eff43dac8cbf053878

Going to close this as resolved
