### ISSUE TITLE
devops: Run Chromatic snapshots on PR creation to help catch regressions earlier

### ISSUE THREAD

**Issue by ckifer** [recharts/recharts#4063]
## Do you want to request a feature or report a bug?

Devops feature

## What is the current behavior?

Chromatic gets run at build time after merge to the repo but not after PR creation. This means a merge must be done in order to find those regressions. See https://github.com/recharts/recharts/pull/4062

## Acceptance Criteria 

* Chromatic snapshots are generated on every PR with the code from that PR

**Comment by nikolasrieble** [comment]
It might simply be too expensive to run chromatic on every commit, or after PR creation. 
If we were to automatically create github issues following a failed run on master, that imho would suffice as well. 

I do not care so much about when it runs but rather about us being notified.

**Comment by ckifer** [comment]
Nothing ever fails right? It's just if we approve changes or not. We can somehow notify that there are unreviewed changes, but how to we enforce it being reviewed previous to a release happening and breaking something?

**Comment by ckifer** [comment]
Not sure if its possible, but maybe there is such a thing where we approve a run of an action that would do a chromatic deployment when we go to review / merge a PR?

**Comment by nikolasrieble** [comment]
I activated the review (it was disabled before)

<img width="1319" alt="Screenshot 2024-01-25 at 06 31 00" src="https://github.com/recharts/recharts/assets/27995606/f9ff9389-9324-4a4d-85c0-ece311592fcd">

We would likely also want to setup Turbosnap. 

<img width="671" alt="Screenshot 2024-01-25 at 06 30 32" src="https://github.com/recharts/recharts/assets/27995606/d2be3d4d-dcaa-474d-8b1c-8af08223361e">

**Comment by ckifer** [comment]
@nikolasrieble nice find! Knew they had to have something along these lines

**Comment by ckifer** [comment]
> Build required for forked branch
>
> We'd love to show you visual changes, but we don't have a build for the head (source) branch of this pull request.
>
> Because this PR originates from a fork, it means we need a build for the polarRadiusAxis-story branch on the forked > repository Shrenika123/recharts. Here's how you can create that build manually:

We can build them manually but unless the branches are on the repo I don't think this works

**Comment by ckifer** [comment]
FYI @PavelVanecek

**Comment by PavelVanecek** [comment]
I thought our Chromatic account is free? What's expensive?

**Comment by PavelVanecek** [comment]
So the PR build only works for branches pushed in the recharts repository but not forks? Let's do that then

**Comment by ckifer** [comment]
We're good in terms of our cost, but we probably shouldn't run a chromatic workflow on anyone creating a PR (even if its not expensive for us we could get flooded from external contributors 😅).


> So the PR build only works for branches pushed in the recharts repository but not forks? 

Yep, see https://www.chromatic.com/review?appId=63da8268a0da9970db6992aa&number=4082&type=linked&view=changes


I'll try and find some time to mess with it!

**Comment by PavelVanecek** [comment]
<img width="620" alt="image" src="https://github.com/recharts/recharts/assets/1100170/4db63e56-7c3d-466a-b79e-7174add34beb">

We already run snapshots after every merge, right? So if we run snapshots on every PR too, the amount will double. If there's some comments and feedback and requested changes (there usually is) then this triples. So we're looking at, estimate, 15000 snapshots per month? Still well below the limit. If we go crazy and run ten builds on every PR then we're over limit. I say we're fine.

**Comment by PavelVanecek** [comment]
Some months are busier than otherts

<img width="338" alt="image" src="https://github.com/recharts/recharts/assets/1100170/490ee706-9c66-463f-975f-da53d3b16581">

**Comment by PavelVanecek** [comment]
I remember that some github repositories only start running builds after maintainer approval. Was it recharts that does that? Or storybook repository? Can we do the same?

**Comment by ckifer** [comment]
![image](https://github.com/recharts/recharts/assets/25180830/a63b9507-9c65-4a83-b3e3-fc70107d20b8)

I can change to the last option? imo thats fine to require approval for every outside contributor

**Comment by ckifer** [comment]
It'll run automatically for all three of us since we're in the org, but anyone not in the org it will wait for an approval. I think thats fair / fine

**Comment by PavelVanecek** [comment]
Okay and even then it requires branch on main repository, not a fork? So whoever wants Chromatic builds in their PR needs to remember that detail.

A little bit convoluted but good enough for Recharts I say. Definitely improvement of what we have now

**Comment by ckifer** [comment]
I'm going to mess around with the PR workflow a little and see if I can't get it to happen on every PR workflow. But won't sink too much time into it. @PavelVanecek you should have push rights now, added you to maintainers 🙌🏼

**Comment by ckifer** [comment]
lol

> GitHub secrets work at a repository level. Forked repositories will not have access to them. If you want to run Chromatic on cross-repository (forked) PRs, you’ll have to expose the projectToken by including it as plaintext in your chromatic.yml workflow file. Be aware that anyone with access to this file will be able to run Chromatic builds on your project, consuming your snapshot quota. You can reset the project token on the Manage > Configure screen at any time if you think it may have been compromised.

Lets maybe stick to running intra-repo with ^ that being said. If we have a "scary" PR that needs to be snapshotted we can push it to a branch or run the chromatic command manually

**Comment by ckifer** [comment]
With that said, I think this already works - I'll close this and we can start doing larger changes on branches. Just make sure to clean your branches up after PR merge
