### ISSUE TITLE
Change Line color depending on value

### ISSUE THREAD

**Issue by belgac** [recharts/recharts#407]
Hello,

First of all thank you for this great library!

I was looking for the ability to change the color of a Line in a LineChart depending on the value of the current point (for example a price history chart becomes green when it's cheaper than initial price and red when it's more expensive than initial price)

Is it possible with the actual state of the library ? If not is someone already working on this ?

**Comment by xile611** [comment]
@belgac Do you mean to update the `stroke` of the whole line? or just a part of the line?

**Comment by belgac** [comment]
Just from a part of the line depending on the value. Something similar to applying a radial two color gradiant to the stroke (see the first part of http://www.d3noob.org/2013/01/applying-colour-gradient-to-graph-line.html?m=1)

**Comment by xile611** [comment]
@belgac Recharts support linear gradient too, maybe you can try create a linear gradient dynamically and use the gradient to stroke the `Line`.

[Here](http://recharts.org/api) is a demo of linear gradient.

**Comment by belgac** [comment]
Thank you a lot!

It works: [demo](http://jsfiddle.net/rntqd24h/)!

You can close this issue, thank you again

**Comment by xile611** [comment]
@belgac  OK! Thanks for your demo! I'll add it to recharts.org.

**Comment by no-mercy** [comment]
Hi guys, sorry for necroposting, but this is only related to my needs topic that i've found.
I need to draw  LineChart which contains only one line with dots, each segment of this line(between two dots) should be be related to value on chart, and also one of the points should be the same color of it. Is there other, than gradient, way to customize line color?

**Comment by mrinmoydas3011** [comment]
Hi, this is a great library to work with.

But I have been trying to change the color of the line chart based on its value dynamically. How to achieve this? The above comments show the task to have been achieved but the demo link is broken.

Please help.

**Comment by dydokamil** [comment]
> Hi, this is a great library to work with.
> 
> But I have been trying to change the color of the line chart based on its value dynamically. How to achieve this? The above comments show the task to have been achieved but the demo link is broken.
> 
> Please help.

https://codesandbox.io/s/q79rrrkmy6

**Comment by kentrh** [comment]
To get a line with different colors for positive and negative values you can have a look at this fiddle https://jsfiddle.net/alidingling/64v6ocdx/ from the recharts examples. Just swap the `fill` with `stroke` in a `<Line />` element instead of `<Area />` element.

**Comment by swetha2** [comment]
Hi, How can i change line color based on values?

**Comment by qboot** [comment]
**Warning:** with `linearGradient` a perfect horizontal / vertical line path will not be drawn.

According to [this thread](https://stackoverflow.com/questions/21638169/svg-line-with-gradient-stroke-wont-display-straight/21639059#21639059), fixes are:
- change the default gradientUnits (which is `objectBoundingBox`) to `gradientUnits="userSpaceOnUse"`, **or**
- add a tiny amount to the values (example: 0.0001 instead of 0).

But for my use case, neither of the two fits really well. 😕

**Comment by jabberwo** [comment]
So far non the examples seem to provide a way of coloring the markers by value: e.g. the color range in react-vis.  Currently I'm looking at the CustomedDot example but rendering an svg circle myself just so that the color can be specified seems awfully overkill.  If someone has a better way I'd love to hear it.

**Comment by gaurav5430** [comment]
Is it possible to pass in a function to decide the stroke, which gets the value for each point and decides the color based on that ?

For example:
`<Line dataKey="name" stroke={(data) => data > 5 ?  "red" : "blue"} />`

**Comment by arianitu** [comment]
@gaurav5430 trying to do the same thing, did you find any solution?

**Comment by gaurav5430** [comment]
@arianitu yeah I figured something for my use case, might be helpful in general as well. I ended up using gradients as I only had the requirement to change color after a certain value. 

What exactly are you trying to achieve?

**Comment by arianitu** [comment]
> @arianitu yeah I figured something for my use case, might be helpful in general as well. I ended up using gradients as I only had the requirement to change color after a certain value. 
> 
> What exactly are you trying to achieve?

I want to highlight the line a different color based on where you are hovering on the line.

For example, if you were hovering in the middle, half the line would be green and the other half would be red.

If you were hovering at 80% of the line, the first 80% would be green and the other 20% would be red. 

How do gradients world?

**Comment by gaurav5430** [comment]
> > @arianitu yeah I figured something for my use case, might be helpful in general as well. I ended up using gradients as I only had the requirement to change color after a certain value.
> > What exactly are you trying to achieve?
> 
> I want to highlight the line a different color based on where you are hovering on the line.
> 
> For example, if you were hovering in the middle, half the line would be green and the other half would be red.
> 
> If you were hovering at 80% of the line, the first 80% would be green and the other 20% would be red.
> 
> How do gradients work?

Here is an example solving a similar problem as yours:
https://codesandbox.io/s/recharts-change-gradient-on-hover-gomt6

I am calculating gradients dynamically on hover.

<img width="561" alt="Screenshot 2020-05-20 at 8 58 02 PM" src="https://user-images.githubusercontent.com/12510548/82465401-db3e5780-9adc-11ea-9e2e-04dad33f27d0.png">

**Comment by arianitu** [comment]
@gaurav5430 that's exactly what I was looking for, thank you!

**Comment by JulianLang** [comment]
> @belgac Do you mean to update the `stroke` of the whole line? or just a part of the line?

Is it possible to update the stroke of the whole line? That's exactly my use case.

**Comment by gaurav5430** [comment]
Updating the stroke of the whole line is simpler than updating parts of the line you can decide that based on some state value which gets updated whenever you want to change the color.

Ofcourse this would re-render the whole chart possibly.

What is your exact use case, when do you want to change the color of the whole line?

**Comment by JulianLang** [comment]
In my case I get data from backend which contains multiple Lines with defined colors:

```
const dataFromBackend = {
    line1: {
       data: [{x: 1, y: 2 }, /*...*/],
       color: '#ff0000',
   },
   line2: { ... }
};

return (
   <LineChart data={extractDataProperties(dataFromBackend)} ... >
         Object.keys(dataFromBackend).map(lineName => 
           (
             <Line dataKey={lineName} stroke={/* set color here */} />
           ));
   </LineChart>
);
````

It might be an Anti-Pattern but I really had no idea how to solve it in a cleaner way. Maybe you have an idea?

**Comment by gaurav5430** [comment]
you can do:

```
 <LineChart data={extractDataProperties(dataFromBackend)} ... >
         Object.keys(dataFromBackend).map(lineName => 
           (
             <Line dataKey={lineName} stroke={dataFromBackend[lineName].color} />
           ));
   </LineChart>
```

**Comment by JulianLang** [comment]
> you can do:
> 
> ```
> <LineChart data={extractDataProperties(dataFromBackend)} ... >
>      Object.keys(dataFromBackend).map(lineName => 
>      (
>       <Line dataKey={lineName} stroke={dataFromBackend[lineName].color} />
>      ));
> </LineChart>
> ```
> 
> @JulianLang

Oh great, I will try it out! Thank you! :)

**Comment by gaurav5430** [comment]
For reference, I have written about my findings here: 
https://medium.com/@gaurav5430/exploring-recharts-line-chart-with-different-colored-segments-8e77f13ffeb2?source=friends_link&sk=36a7b95669b24354e762ca8e3457acf6

**Comment by VladislavAmbrosevich** [comment]
Hey!
Nice solution, thanks, @gaurav5430. But what if I need to make a part of the line dashed? E.g. if for the domain start of the line shows actual data and the rest part show predicted data. It's really good to make this dashed and not just change the color.

**Comment by vnikonov63** [comment]
@gaurav5430, hello! But how to deal with the case, when each line needs to have separate coloring? As I understand the solution with the gradients only works within the LineChart Component?

**Comment by gaurav5430** [comment]
> @gaurav5430, hello! But how to deal with the case, when each line needs to have separate coloring? As I understand the solution with the gradients only works within the LineChart Component?
> 

If there are multiple lines and If each line needs to be a seaparate color, you can just assign a different stroke prop to each line.

The gradient solution would work wherever you specify stroke, because the stroke color is specified by the gradient. So no, not specific to LineChart

**Comment by gaurav5430** [comment]
> Hey!
> Nice solution, thanks, @gaurav5430. But what if I need to make a part of the line dashed? E.g. if for the domain start of the line shows actual data and the rest part show predicted data. It's really good to make this dashed and not just change the color.

Hmm, yeah, I guess for this use case you would need to use 2 different lines one with dashed stroke amd another with regular stroke. wouldn't be perfect, but that is what I can think of right now.

**Comment by rahulnagcodes** [comment]
> @arianitu yeah I figured something for my use case, might be helpful in general as well. I ended up using gradients as I only had the requirement to change color after a certain value.
> 
> What exactly are you trying to achieve?

hi @gaurav5430 
i want to achieve similar to yours, can you please help me here.
i want to color the line of linechart with red if value is <100 and if value in >100 then i want to color the line as green in the same LineChart

**Comment by gaurav5430** [comment]
> > @arianitu yeah I figured something for my use case, might be helpful in general as well. I ended up using gradients as I only had the requirement to change color after a certain value.
> > 
> > What exactly are you trying to achieve?
> 
> hi @gaurav5430 
> i want to achieve similar to yours, can you please help me here.
> i want to color the line of linechart with red if value is <100 and if value in >100 then i want to color the line as green in the same LineChart
> 

is this not helpful 

https://github.com/recharts/recharts/issues/407#issuecomment-647135045

**Comment by rahulnagcodes** [comment]
> > > @arianitu yeah I figured something for my use case, might be helpful in general as well. I ended up using gradients as I only had the requirement to change color after a certain value.
> > > What exactly are you trying to achieve?
> > 
> > 
> > hi @gaurav5430
> > i want to achieve similar to yours, can you please help me here.
> > i want to color the line of linechart with red if value is <100 and if value in >100 then i want to color the line as green in the same LineChart
> 
> is this not helpful
> 
> [#407 (comment)](https://github.com/recharts/recharts/issues/407#issuecomment-647135045)

Hi, did some twist and its working for me now, 
took some reference from your article.

Thanks a lot :)

**Comment by tech-maven** [comment]
> > > > @arianitu yeah I figured something for my use case, might be helpful in general as well. I ended up using gradients as I only had the requirement to change color after a certain value.
> > > > What exactly are you trying to achieve?
> > > 
> > > 
> > > hi @gaurav5430
> > > i want to achieve similar to yours, can you please help me here.
> > > i want to color the line of linechart with red if value is <100 and if value in >100 then i want to color the line as green in the same LineChart
> > 
> > 
> > is this not helpful
> > [#407 (comment)](https://github.com/recharts/recharts/issues/407#issuecomment-647135045)
> 
> Hi, did some twist and its working for me now, took some reference from your article.
> 
> Thanks a lot :)

Hi @rahulnagcodes,
I am looking to do something similar, color the line a different color above a threshold. Could you share how you went about doing this ?

Thanks for your help

**Comment by peterklingelhofer** [comment]
> For reference, I have written about my findings here: https://medium.com/@gaurav5430/exploring-recharts-line-chart-with-different-colored-segments-8e77f13ffeb2?source=friends_link&sk=36a7b95669b24354e762ca8e3457acf6

This helped a lot, thank you for this @gaurav5430.

Does anyone have any ideas as to how to make sure the stroke on the line is a linear gradient, but uses the _delta_ or _trend_ of the data rather than the data itself? We already know its value because of the Y-axis of our chart, so using the _delta_ for this could better accentuate dramatic changes over time. If maintainers have recommendations as to where this would best be implemented/modified I'd be happy to work on a pull request if it's not currently possible.

**Comment by ckifer** [comment]
Not sure I get the use-case @peterklingelhofer 

Why would the color of a line not use data from the line?

The delta of what?

**Comment by peterklingelhofer** [comment]
Hi @ckifer, thank you for your response, sorry if I was unclear. By delta I'm referring to this definition of delta: [the the change in a variable, and it is also used to represent the difference between two numbers.](https://www.learner.com/blog/what-is-a-delta-in-math#:~:text=What%20Does%20Delta%20Mean%20in,the%20change%20in%20a%20variable.).

Right now, you can feed in a linear gradient with a lower color and an upper color and it seems Recharts automatically reads the data you're putting in and picks colors on the lower end of the linear gradient for lower data values and upper ends of the linear gradients for upper values. My proposition wouldn't necessarily be build out an entire switch prop to tell the Recharts to compute the delta and use that for the color, instead I think it should just be an optional alternate data set the user can send in (in my case, I would compute the deltas for each point and send that in for prop). I would be happy to do the math of building out a linear gradient and computing the color of each point myself, but as it stands now it seems that Recharts automatically _picks_ points on the linear gradient you send in in the range between min and max based on the data you're sending in (this is the aspect I'd appreciate being disabled so I have more granular control over my gradient).

And the justification here would be because a user can already see what the highest and lowest value is on the chart by seeing the Y-axis, and yes they can look at the slope of the line to roughly determine more and less extreme delta values, but its inherently a bit less clear to a user than merely seeing a point that is the highest one on the Y-axis for example (examining line slopes can be a bit harder to see). I hope that makes sense.

**Comment by ckifer** [comment]
Recharts doesn't read the linear gradient at all - a pre-calculated linear gradient is just added to to the stroke of a line. This is native-SVG behavior. You could use other data to calculate the offset and the stops of the gradient but at the end of the day it's still being set in the original line. 

This being said, there isn't anywhere internally in recharts where you'd be able to change the current behavior. A linear gradient can be calculated from whatever data you have external from recharts.

**Comment by skahmerali** [comment]
> > > @arianitu yeah I figured something for my use case, might be helpful in general as well. I ended up using gradients as I only had the requirement to change color after a certain value.
> > > What exactly are you trying to achieve?
> > 
> > 
> > hi @gaurav5430
> > i want to achieve similar to yours, can you please help me here.
> > i want to color the line of linechart with red if value is <100 and if value in >100 then i want to color the line as green in the same LineChart
> 
> is this not helpful
> 
> [#407 (comment)](https://github.com/recharts/recharts/issues/407#issuecomment-647135045)

hello @gaurav5430 , 
in my case i want to change the color of each line according to the value of yaxis , right now i implement this code but not doing well :
  title == 'Uses' ?
                <Bar stroke={strokeColor} fill={(finalData)=> finalData > 7 ? fillColor : '#090979'} type="monotone" dataKey="frequency" />
                :
                <Bar stroke={strokeColor} fill={fillColor} type="monotone" dataKey="frequency" />

**Comment by huangchaofei** [comment]
@gaurav5430 hey guy, I find when some data is zero, the line gradient is wrong
just like: 
import React from 'react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer,ReferenceLine } from 'recharts';

const data = [
  {
    name: 'Page A',
    uv: 0,
    pv: 500,
    amt: 2400,
  },
  {
    name: 'Page B',
    uv: 3000,
    pv: 0,
    amt: 2210,
  },
  {
    name: 'Page C',
    uv: 0,
    pv: 9800,
    amt: 2290,
  },
  {
    name: 'Page D',
    uv: 2780,
    pv: 1000,
    amt: 2000,
  },
  {
    name: 'Page E',
    uv: 1890,
    pv: 2000,
    amt: 2181,
  },
  {
    name: 'Page F',
    uv: 0,
    pv: 3800,
    amt: 2500,
  },
  {
    name: 'Page G',
    uv: 0,
    pv: 4300,
    amt: 2100,
  },
];
const colorBreakPoint = 8000;
const Example = () => {
  const { min, max } = data.reduce((result, dataPoint) => ({
    min: (dataPoint.pv < result.min || result.min === 0) ? dataPoint.pv : result.min,
    max: (dataPoint.pv > result.max || result.max === 0) ? dataPoint.pv : result.max,
  }), { min: 0, max: 0 });
  console.log(max);
  const colorBreakPointPercentage = `${(1 - ((colorBreakPoint - min) / (max - min))) * 100}%`;
  console.log(colorBreakPointPercentage);
  return (
    <ResponsiveContainer width="100%" height="100%" >
      <LineChart width={300} height={100} data={data} margin={{ right: 25, top: 30 }}>
        <defs>
          <linearGradient id="colorUv" x1="0%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" stopColor="red" />
            <stop offset={colorBreakPointPercentage} stopColor="red" />
            <stop offset={colorBreakPointPercentage} stopColor="green" />
            <stop offset="100%" stopColor="green" />
          </linearGradient>
        </defs>
        <Line type="monotone" dataKey="pv" stroke='url(#colorUv)' dot={false} strokeWidth={2} />
        <ReferenceLine ifOverflow='extendDomain' y={8000} stroke="red" strokeDasharray="3 3" />
        <YAxis domain={[0,'auto']} />
      </LineChart>
    </ResponsiveContainer>
  );
};

**Comment by rcrogers** [comment]
> Nice solution, thanks, @gaurav5430. But what if I need to make a part of the line dashed? E.g. if for the domain start of the line shows actual data and the rest part show predicted data. It's really good to make this dashed and not just change the color.

This is my exact use case!  Rendering two separate `Line`s is better than nothing, but the combined line contains a kink/corner (slope discontinuity) because the two lines are smoothed separately.
