### ISSUE TITLE
errors in react when trying to dynamically add bars based on data object

### ISSUE THREAD

**Issue by 10n6** [recharts/recharts#408]
`<ResponsiveContainer>
  <BarChart width={500} height={300} data={ plots } margin={{top: 35, right: 45, left: 45, bottom: 10}}>
  <XAxis dataKey="name" axisLine={false} tickLine={false} />
{keys.map(
(item, i) => {
return ( <Bar stackId="a" dataKey={item} key={i} /> )
})}
</BarChart>
</ResponsiveContainer>`

I am getting errors plotting this sort of setup where keys = an array of string values of the datakeys to look for in the data object. I am not sure if this is just me and my react abilities (lack of) or if there's another way to dynamically build bars into the chart as no bar chart will be the same for it to be statically coded in a react js file. 

In terms of the data object an example could be:
[{name:"name1",a:0,b:0},{name:"name2",a:3,b:3}]
  or
[{name:"name1",a:0,b:0,c:1},{name:"name2",a:3,b:3,c:0}]

In terms of an example of the keys array this could be:
['a','b'] or ['a','b','c'] or unlimited keys

Any help you can offer would be greatly appreciated. thanks.

**Comment by 10n6** [comment]
It is falling over at line 176 of BarChart.js with sizeList undefined. not sure why though.

**Comment by xile611** [comment]
@10n6 How about the version of recharts ?

**Comment by 10n6** [comment]
Sorry my bad. version 0.14.2

**Comment by xile611** [comment]
@10n6 The latest version is 0.19.1.

**Comment by 10n6** [comment]
Fixed by removing the XAxis. Something in there seemed to be throwing it off and causing a null and breaking the chart.

**Comment by xile611** [comment]
@10n6 Can you create a demo in jsfiddle ?

**Comment by 10n6** [comment]
I got it all working fine after upgrading to the latest version and running an update in npm. Also removed the XAxis with the params and started again. hey presto all worked. Not sure if it was just a perfect storm of things that combined as I can't replicate it now. Thanks for your help though.
