### ISSUE TITLE
I have installed the Recharts trying to render scatter chart and imported ResponsiveContainer but getting "TypeError: clsx__WEBPACK_IMPORTED_MODULE_0___default(...) is not a function" error

### ISSUE THREAD

**Issue by Darshan-Gowda97** [recharts/recharts#4080]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
I have imported the ResponsiveContainer from Recharts, but getting the below error.
it is throwing that error initially without rendering scatter chart

import { CartesianGrid, Label, ResponsiveContainer, Scatter, ScatterChart, XAxis, YAxis } from 'recharts';
<ResponsiveContainer width="100%" height={400}>
   ...Rest of the code
 </ResponsiveContainer>
                            
 Error:
 TypeError: clsx__WEBPACK_IMPORTED_MODULE_0___default(...) is not a function
(anonymous function)
C:/Users/U1132466/Projects/project3/com.rxcorp.gss.whsnlpt.webapp/node_modules/recharts/es6/component/ResponsiveContainer.js:296
  293 | /*#__PURE__*/
  294 | React.createElement("div", {
  295 |   id: id ? "".concat(id) : undefined,
> 296 |   className: clsx('recharts-responsive-container', className),
      | ^  297 |   style: _objectSpread(_objectSpread({}, style), {}, {
  298 |     width: width,
  299 |     height: height,
                             
## What is the expected behavior?
Need to render the scatter chart of Recharts

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
latest Recharts V2.10.4
React V16

**Comment by ckifer** [comment]
Is there any more info you can give? This sounds like something specific to your configuration. What webpack settings are you using?

**Comment by Darshan-Gowda97** [comment]
Thanks for the response.
I am using the react with typescript and I dont have the webpack config in my react project

**Comment by ckifer** [comment]
What do you use to build your app? Create react app? Vite? NextJs?

**Comment by Darshan-Gowda97** [comment]
I am using create react app
I have updated react version to 17 and dom version to 17, still facing the same issue

**Comment by ckifer** [comment]
Create react app uses webpqck under the hood. 

Can you paste your package.json and TS config?

**Comment by Darshan-Gowda97** [comment]
Sure

package.json:
{
  "tenant": "whsnlpt",
  "name": "com.rxcorp.gss.whsnlpt.webapp",
  "group": "com.rxcorp.gss.whsnlpt.webapp",
  "version": "0.1.0-SNAPSHOT",
  "private": true,
  "dependencies": {
    "@babel/polyfill": "^7.4.4",
    "@types/classnames": "^2.3.1",
    "@types/enzyme": "3.1.15",
    "@types/enzyme-adapter-react-16": "1.0.3",
    "@types/exceljs": "^0.5.3",
    "@types/hoist-non-react-statics": "^3.3.1",
    "@types/html2canvas": "0.0.35",
    "@types/js-base64": "^2.3.1",
    "@types/js-cookie": "^2.2.2",
    "@types/jspdf": "^2.0.0",
    "@types/react": "^16.8.0",
    "@types/react-bootstrap": "^0.32.15",
    "@types/react-router-dom": "^4.3.1",
    "@types/react-slick": "^0.23.5",
    "@types/react-sortable-tree": "^0.3.5",
    "@types/react-test-renderer": "^16.0.3",
    "@types/xlsx": "0.0.36",
    "axios": "^0.21.1",
    "babel-core": "^6.26.3",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-preset-env": "^1.7.0",
    "babel7-jest": "^1.0.1",
    "bootstrap": "^4.4.1",
    "chart.js": "^2.7.3",
    "classnames": "^2.3.1",
    "clsx": "^2.1.0",
    "enzyme": "^3.8.0",
    "enzyme-adapter-react-16": "^1.9.1",
    "enzyme-to-json": "^3.3.5",
    "es6-object-assign": "^1.1.0",
    "es6-promise": "^4.2.6",
    "exceljs": "^4.2.0",
    "file-saver": "^2.0.5",
    "formik": "^1.5.8",
    "html2canvas": "^1.0.0-rc.1",
    "i18next": "^13.1.1",
    "i18next-browser-languagedetector": "^2.2.4",
    "i18next-xhr-backend": "^1.5.1",
    "identity-obj-proxy": "^3.0.0",
    "isomorphic-fetch": "^3.0.0",
    "jest-cli": "^23.6.0",
    "js-base64": "^2.5.2",
    "js-cookie": "^2.2.0",
    "jsonata": "^1.8.4",
    "jspdf": "^2.4.0",
    "jspdf-autotable": "^3.5.12",
    "leaflet": "^1.7.1",
    "multiselect-react-dropdown": "^2.0.25",
    "pptxgenjs": "^3.12.0",
    "primeicons": "^1.0.0",
    "primereact": "^3.4.0",
    "rc-slider": "^9.3.1",
    "react": "^17.0.0",
    "react-bootstrap": "^0.32.4",
    "react-confirm-alert": "^2.7.0",
    "react-dropdown": "^1.6.2",
    "react-google-charts": "^3.0.15",
    "react-i18next": "^9.0.2",
    "react-leaflet": "^2.7.0",
    "react-multi-select-component": "^4.2.9",
    "react-number-format": "^4.5.5",
    "react-panelgroup": "^1.0.12",
    "react-router-breadcrumbs-hoc": "^2.3.2",
    "react-router-dom": "^4.3.1",
    "react-scripts": "^4.0.0",
    "react-scripts-ts": "^4.0.8",
    "react-slick": "^0.28.1",
    "react-sortable-tree": "^2.3.0",
    "react-svg": "^14.1.6",
    "recharts": "^2.10.4",
    "slick-carousel": "^1.8.1",
    "xlsx": "^0.14.2",
    "yup": "^0.32.9"
  },
  "scripts": {
    "git-info": "git rev-parse --verify HEAD>src/gitInfo.txt",
    "start": "npm run git-info && react-scripts-ts start",
    "build": "npm run git-info && react-scripts-ts --max_old_space_size=4096 build",
    "test": "jest",
    "eject": "react-scripts-ts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "devDependencies": {
    "@types/file-saver": "^2.0.5",
    "@types/jest": "^23.3.12",
    "@types/node": "^10.12.18",
    "@types/react-dom": "^16.8.0",
    "@types/react-leaflet": "^2.5.2",
    "babel-jest": "^23.6.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^23.6.0",
    "react-dom": "^17.0.0",
    "react-test-renderer": "^16.6.3",
    "ts-jest": "^23.10.5",
    "typescript": "^3.2.2"
  },
  "jest": {
    "moduleNameMapper": {
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga|txt)$": "<rootDir>/src/components/__mocks__/fileMock.js",
      "\\.(css|less|scss|sass)$": "<rootDir>/src/components/__mocks__/styleMock.js"
    }
  }
}

tsconfig.json:

{
  "compilerOptions": {
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "baseUrl": ".",
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es6",
    "lib": ["es6", "dom", "es2017"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "importHelpers": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "skipLibCheck": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
  ]
}

**Comment by ckifer** [comment]
@Darshan-Gowda97 looks like many of your dependencies are pretty outdated. Any reason you're using `react-scripts-ts` over `react-scripts`? Can you try upgrading `react-scripts` to v5?

**Comment by Darshan-Gowda97** [comment]
it is building fine but I got the error when running on localhost

**Comment by ckifer** [comment]
You don't need `react-scripts-ts` for TypeScript. Out of the box react-scripts supports TS

![image](https://github.com/recharts/recharts/assets/25180830/c70911c9-fe88-4cdb-95d5-16cb64b2af26)
and its very out of date

**Comment by Darshan-Gowda97** [comment]
sure, I will try using react-scripts.
Thanks

**Comment by ckifer** [comment]
@Darshan-Gowda97 any luck?

**Comment by ckifer** [comment]
Going to close this for now, feel free to comment back
