### ISSUE TITLE
Tooltip sometimes re-appears after cursor leaves chart

### ISSUE THREAD

**Issue by mrcljx** [recharts/recharts#4093]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/recharts-issue-template-forked-84t5pf)

### Steps to reproduce
- Move your mouse quickly from left (outside of the charts) to the right (outside of the charts)
- Notice how the tooltip suddenly appears

### What is expected?
- Tooltip should stay hidden

### What is actually happening?
- Tooltip is visible

| Environment | Info |
|---|---|
| Recharts | v2.11 |
| React | React 18.2 |
| System | macOS 14.2 |
| Browser | Firefox 122.0 |

---
(I increased `throttleDelay` so that this is easier to reproduce.)

What seems to be happening is:

1. `handleMouseMove` is called -> will schedule `triggeredAfterMouseMove` in 16.6ms (60fps)
2. `handleMouseLeave` is called -> `isTooltipActive = false`
3. `triggeredAfterMouseMove` is called -> `isTooltipActive = true`

`triggeredAfterMouseMove` should probably not modify `isTooltipActive`

**Comment by ckifer** [comment]
relevant line of code https://github.com/recharts/recharts/blob/master/src/chart/generateCategoricalChart.tsx#L1534 if someone wants to pick this up.

This might be an easy change but there might also be consequences of removing that state change which will need to be tested.

Thanks for the report

**Comment by ckifer** [comment]
Should be resolved in next minor or patch release

**Comment by ckifer** [comment]
released in 2.12
