### ISSUE TITLE
Is it possible let two Bar in one line?

### ISSUE THREAD

**Issue by momolly1024** [recharts/recharts#4096]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/recharts/recharts](https://github.com/recharts/recharts)

### Steps to reproduce
-

### What is expected?
Is it possible let two Bar in one line?

### What is actually happening?
Is it possible let two Bar in one line?

| Environment | Info |
|---|---|
| Recharts | v2.11 |
| React | "react": "^18.1.0", |
| System | windows |
| Browser | Chrome |

---
                <ComposedChart width={730} height={250} data={data1}>
                    <XAxis dataKey='name' />
                    <YAxis />
                    <Tooltip />
                    <Legend />
                    <CartesianGrid stroke='#f5f5f5' />

                    <Bar dataKey='hr' barSize={20} fill='#413ea0' />
                    <Bar
                        dataKey='rr'
                        barSize={20}
                        stroke='#ff7300'
                        name='aaaa'
                        stackId='a'
                        fill='#9e2608'
                    />
                </ComposedChart>

Is it possible let two Bar in one line?
I wonder if is there any way to let the Bar in one line?

![image](https://github.com/recharts/recharts/assets/61406208/cad68c86-1fe4-42a9-b674-bd021b82372f)

like this 

![image](https://github.com/recharts/recharts/assets/61406208/dc3e9598-12f4-4e66-93b3-ce0c0bce470e)

Thank you.

**Comment by ckifer** [comment]
@momolly1024 Can you make a sandbox with data that represents the issue? https://codesandbox.io/p/sandbox/mixed-bar-chart-forked-jfxwd9

From first glance I don't think this is possible out of the box, but it might be with some custom code

**Comment by ckifer** [comment]
Yep its possible with `Customized`

[![Edit mixed-bar-chart (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/mixed-bar-chart-forked-jfxwd9?file=%2Fsrc%2FApp.tsx%3A82%2C21)

**Comment by ckifer** [comment]
<img width="579" alt="image" src="https://github.com/recharts/recharts/assets/25180830/875b4e68-41b9-43f2-af04-e6163a3633d4">

**Comment by ckifer** [comment]
Going to close this as stale with no response, feel free to comment back
