### ISSUE TITLE
Custom components

### ISSUE THREAD

**Issue by rrag** [recharts/recharts#41]
Author of [react-stockcharts](https://github.com/rrag/react-stockcharts/) here

I came across recharts a couple of weeks ago, and just today had a chance to read some source and play with the examples. When I looked at the API, it looked very similar to my project and was excited. Looking at the code of the different `XXXChart` I saw that you are limiting to a set of types you have created.

Take an example of http://jsfiddle.net/1n97rmsy/ where I have added a `circle` and `rect` on line 20 and 21, those are not displayed. It could be as simple as the user wanting a background text on the chart.

I believe it is essential to be able to support composition of custom components, at least for all the cartesian charts.

**Comment by arcthur** [comment]
Great idea! Thanks for @rrag. What do you think? @xile611
react-stockcharts is awesome probject too. Maybe we will be worth to join forces, borrow the ideas. :-)

**Comment by xile611** [comment]
Thanks for @rrag .

I also thought about what you said when I started recharts.Then in the process of implementation, I began to doubt in what scenario user want to draw a circle, a line or a rectangle with specified coordinates.

So I implement `ReferenceLine` which accept a value as input and draw a line whose coordinates are calculated internally. `ReferenceDot` is similar.

Anyway, limit child type is really not flexible enough.I will consider about the implementation.

**Comment by rrag** [comment]
the 2 projects are very similar, not only in the way the chart composition works. the variable exposed to `window` on the UMD build of `react-stockcharts` is `ReStock`. This similarity is just too cool to pass :)

stockcharts has gone through a few iterations of api changes.

When I started with it, I was using the `cloneElement` of all the children, then started to use the react `context` (and still do) and checking the type of children for certain props. Now with the yet to be released version (0.4). There is just one type check, and the parent passes props down via context. 

Using custom components, and svg elements on a chart is a solution for many problems that are hard to imagine initially. For me it was essential, since there are so many types of financial indicators that the api had to be capable to accommodate new types.

There is duplication of logic between the different children of `CartesianChart` which can be reduced by using `context`. In any case I believe the api you currently expose is at the right abstraction, offering flexibility to improve upon later..

I also draw inspiration from [d3fc](https://github.com/ScottLogic/d3fc) very nice charting library (not just for financial charting) with different renderers and indicators.
