### ISSUE TITLE
Flat area charts like Google Analytics

### ISSUE THREAD

**Issue by kaatt** [recharts/recharts#410]
Is there any option to make the area charts more like Google Analytics? Flat lines instead of smooth?

More like:
<img width="356" alt="a" src="https://cloud.githubusercontent.com/assets/10688522/21470638/a3b9a9ca-cab7-11e6-9855-6b0d19365b7c.png">

Instead of:
<img width="534" alt="" src="https://cloud.githubusercontent.com/assets/10688522/21470643/b641b51a-cab7-11e6-9b61-ed9fa7c342aa.png">

If not, I'd like to suggest this feature. This is something people would very much want to have.

**Comment by xile611** [comment]
@kaatt You can set the props `type` to be `linear` which is also the default value of `type`.

[Api for Area](http://recharts.org/api#Area) .

**Comment by kaatt** [comment]
Thanks for the quick reply. I knew it would be in the API and read it earlier but didn't know which option it was.

Is there an option to get the dots always visible and the top border/outline thicker just like Google Analytics?

**Comment by xile611** [comment]
@kaatt  Like this [demo](http://jsfiddle.net/n8y3e0ko/) ?

**Comment by kaatt** [comment]
Yeah, only remaining piece – can the top border be made thicker like Google Analytics? I looked at the docs for other styles and border width but didn't find that.

**Comment by xile611** [comment]
@kaatt 

Just use `strokeWidth` like svg elements.

```jsx
<AreaChart width={600} height={400} data={data}
            margin={{top: 10, right: 30, left: 0, bottom: 0}}>
  <XAxis dataKey="name"/>
  <YAxis/>
  <CartesianGrid strokeDasharray="3 3"/>
  <Tooltip/> 
  <Area dataKey='uv' dot={dotStyle} stroke='#8884d8' strokeWidth={3} fill='#8884d8' /></AreaChart>
```

[demo](http://jsfiddle.net/n8y3e0ko/1/)
