### ISSUE TITLE
BarChart with stacked bars and Tooltip with shared={false} break bars color

### ISSUE THREAD

**Issue by yonatandb** [recharts/recharts#4101]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/recharts-bar-stacked-tooltip-r7f4qp?file=%2Fsrc%2FApp.tsx%3A76%2C11&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls1hueab00063b6icnwe8dwz%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls1hueab00023b6iijborjac%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls1hueab00033b6ib8482rgy%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls1hueab00053b6i5v01n5c4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls1hueab00023b6iijborjac%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls1hueab00013b6i3jl5y1qd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cls1ie36100023b6iulsicigv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A76%252C%2522startColumn%2522%253A11%252C%2522endLineNumber%2522%253A76%252C%2522endColumn%2522%253A11%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cls1hueab00023b6iijborjac%2522%252C%2522activeTabId%2522%253A%2522cls1ie36100023b6iulsicigv%2522%257D%252C%2522cls1hueab00053b6i5v01n5c4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls1hueab00043b6il9tcd7sv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cls1hueab00053b6i5v01n5c4%2522%252C%2522activeTabId%2522%253A%2522cls1hueab00043b6il9tcd7sv%2522%257D%252C%2522cls1hueab00033b6ib8482rgy%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls1hueab00033b6ib8482rgy%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce
any simple stacked bars chart with tooltip with the prop shared set to false

### What is expected?
show tooltip without chainring the bar color

### What is actually happening?
when hovering the bars, all others bar fill color change to the same color as the hovered one

![recharts-tooltip](https://github.com/recharts/recharts/assets/87268464/58814cfc-787d-4e38-9d85-e756bdb59ffe)

| Environment | Info |
|---|---|
| Recharts | v2.11 |
| React | 18 |
| System | mac sonoma 14.3 |
| Browser | chrome 121 |

**Comment by ckifer** [comment]
Did this break in 2.11 or has it always been like this?

**Comment by ckifer** [comment]
FYI @PavelVanecek

**Comment by Pave91** [comment]
I can confirm, it happened to be after updating next to 14.0.4, may it relate?

**Comment by ckifer** [comment]
@Pave91  did recharts update too or just next?

**Comment by Pave91** [comment]
We didn't update recharts, I'm not sure where exactly it showed, I thought it could be related to some other update a noticed where project setup changed, but now I can't say it was with next with certainity.
Version of recharts we are working with is 2.3.2

**Comment by ckifer** [comment]
I found the bug and have a PR out for it so no worries

**Comment by ckifer** [comment]
fixed in 2.12!

**Comment by yonatandb** [comment]
@ckifer Thank you!
