### ISSUE TITLE
Chart height increasing when removing element and the legend is present

### ISSUE THREAD

**Issue by simod** [recharts/recharts#4105]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3pft78.csb.app/](https://3pft78.csb.app/)

### Steps to reproduce
Make a list of categories, add the option to select which of those should be visible on the chart. Add bars/lines like { enabledProds.map(cat => (
          <Line key={cat} dataKey={cat} strokeWidth={2} stroke={productColorPalette[cat]}/>
        ))}
Add a legend layout vertical

### What is expected?
The Chart height is preserved when categories are added/removed

### What is actually happening?
In a chart I have checkboxes that let me control which categories are displayed or not. But when the legend is present and a category is removed, the charts expands to the bottom by 30px or so, for each category removed. Re-adding a category shrinks it back for the same amount. Tested with both Line and Bar charts

| Environment | Info |
|---|---|
| Recharts | v2.11 |
| React | 18.2 |
| System | all |
| Browser | all |

**Comment by ckifer** [comment]
@PavelVanecek regression maybe

**Comment by PavelVanecek** [comment]
I tried to open the codesandbox link, the website doesn't load at all in Firefox and shows a 404 error in Chrome (even after I logged in).

I will try to reproduce myself but @simod if you can copy-paste your code here that would help too!

**Comment by simod** [comment]
@PavelVanecek sorry! I left it in draft mode! This should be good now https://codesandbox.io/p/sandbox/recharts-dynamic-legend-3pft78?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls2z0n9800063b6d1yxjgic9%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls2z0n9800023b6d25ls1a02%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls2z0n9800033b6dyf6cnbch%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls2z0n9800053b6dtvzjfjx1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls2z0n9800023b6d25ls1a02%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls2z0n9800013b6dh8du2cpx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A16%252C%2522startColumn%2522%253A50%252C%2522endLineNumber%2522%253A16%252C%2522endColumn%2522%253A50%257D%255D%257D%255D%252C%2522id%2522%253A%2522cls2z0n9800023b6d25ls1a02%2522%252C%2522activeTabId%2522%253A%2522cls2z0n9800013b6dh8du2cpx%2522%257D%252C%2522cls2z0n9800053b6dtvzjfjx1%2522%253A%257B%2522id%2522%253A%2522cls2z0n9800053b6dtvzjfjx1%2522%252C%2522activeTabId%2522%253A%2522cls2z0n9800043b6dqoi1eiau%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls2z0n9800043b6dqoi1eiau%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522cls2znext00oy3b6edyzk269i%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cls2z0n9800033b6dyf6cnbch%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls2z0n9800033b6dyf6cnbch%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by PavelVanecek** [comment]
Aha! Much longer link but I can confirm I see it now, thank you. Let me have a closer look.

**Comment by PavelVanecek** [comment]
Okay so first observation: the codesandbox uses 1.8.1 - so I think it's safe to say this is not a regression. I can reproduce the same in sandbox on master.

**Comment by PavelVanecek** [comment]
I think this shows better what's going on:
<img width="680" alt="image" src="https://github.com/recharts/recharts/assets/1100170/3a2626f6-71f5-48e3-9061-2141d48f1292">

Recharts tries to make space for the legend as if it was rendered down below the chart. The legend comes with `position: default` but Rechart tries anyway. I will see if I can find some prop to turn the autoresing off.

**Comment by simod** [comment]
@PavelVanecek super, thanks!

**Comment by PavelVanecek** [comment]
Okay I found out that the `verticalAlign="middle"` prop turns off the auto-offseting, like this:

```
<Legend
          layout={"vertical"}
          verticalAlign="middle"
          wrapperStyle={{
            top: 15,
            left: 85,
            background: "white",
            border: "1px solid lightgrey",
            padding: 5,
          }}
        />
```

Does this do what you are after @simod ?

**Comment by PavelVanecek** [comment]
No worries! The documentation is quite unclear on this topic, I will try to update that too.
