### ISSUE TITLE
Invert X and Y axis

### ISSUE THREAD

**Issue by smitreverie** [recharts/recharts#411]
I could not find any example of inverted bar chart in the documentation.
Basically I want horizontal bars because my x-axis datakeys are more in number and the chart becomes to wide. Is it possible to customise like this?

**Comment by smitreverie** [comment]
Documentation should mention that type props are required when using vertical layout. I used the following code and it worked.

<XAxis type="number"/>
<YAxis type="category" dataKey="name"/>

**Comment by xile611** [comment]
@smitreverie OK! PR is welcome! You can submit PR is [recharts.org](https://github.com/recharts/recharts.org).
