### ISSUE TITLE
Dot at the end

### ISSUE THREAD

**Issue by Ilya3dev** [recharts/recharts#4124]
I wanna make a dot at the end of line, I use area chart and this line has to be animated, that I did, but during animation, where line of chart appearing, it without any dot at the end, for example 10px height, 10px width and rounded 100%, can you help me please, how to do it

**Comment by nikolasrieble** [comment]
It is considered best practice to provide a reproduction in your issue. That reduces the effort it takes for us to help you. 
Please help us help you.

**Comment by Ilya3dev** [comment]
![Screenshot from 2024-02-03 12-46-41](https://github.com/recharts/recharts/assets/148476912/bae2d5eb-a874-4751-8b70-9f2ca7e04aeb)
I need the graph to have a dot at the end of its line when it starts rendering, just like in the screenshot. The dot should not disappear; it should be there from the beginning, and its color should match the line
Thanks

**Comment by Ilya3dev** [comment]
![Screenshot from 2024-02-03 12-51-04](https://github.com/recharts/recharts/assets/148476912/639f5149-5293-46c0-845f-e71c7b610f72)
Right now, the end of the graph looks like this; it is animated and appears gradually. I need a dot at the end of the line from the moment it starts appearing. Thanks again for your response
