### ISSUE TITLE
End of line

### ISSUE THREAD

**Issue by Ilya3dev** [recharts/recharts#4125]
I need the graph to have a dot at the end of its line when it starts rendering, just like in the screenshot. The dot should not disappear; it should be there from the beginning, and its color should match the line
Thanks 
![Screenshot from 2024-02-03 12-46-41](https://github.com/recharts/recharts/assets/148476912/0ea490b7-8be7-4208-ac81-18657d9a406e)

**Comment by Ilya3dev** [comment]
Right now, the end of the graph looks like this; it is animated and appears gradually. I need a dot at the end of the line from the moment it starts appearing. Thanks again for your response
![Uploading Screenshot from 2024-02-03 12-51-04.png…]()

**Comment by ckifer** [comment]
You should be able to use ReferenceDot at the last point in your line

**Comment by Ilya3dev** [comment]
I did it, but I can't see a dot that I need 
![Screenshot from 2024-02-05 09-51-01](https://github.com/recharts/recharts/assets/148476912/443ff90a-126b-4dc8-b522-ebd64db17706)
![Screenshot from 2024-02-05 09-50-32](https://github.com/recharts/recharts/assets/148476912/e76527f9-dbe4-4810-8d40-b8bbe9fdcbab)

**Comment by ckifer** [comment]
Can you reproduce this in codesandbox please? Its hard to help with screenshots

**Comment by Ilya3dev** [comment]
Yes,[, I can't see reference dot at the end of line
Thanks for help
](https://codesandbox.io/p/devbox/46djf7?file=%2Fsrc%2FApp.jsx%3A3%2C18&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls9l0x1z00062v6y5zg9gyhr%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls9l0x1z00022v6yp1ar02i1%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls9l0x1z00032v6y4bwbvfbw%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls9l9l5a00cp2v6yqysxynju%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls9l0x1z00052v6yd799c14n%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50.06130620533747%252C49.93869379466253%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls9l0x1z00022v6yp1ar02i1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls9l0x1z00012v6yy5lgsoc6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cls9lh6lk00022v6y0fupb6sx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A3%252C%2522startColumn%2522%253A18%252C%2522endLineNumber%2522%253A3%252C%2522endColumn%2522%253A18%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cls9l0x1z00022v6yp1ar02i1%2522%252C%2522activeTabId%2522%253A%2522cls9lh6lk00022v6y0fupb6sx%2522%257D%252C%2522cls9l0x1z00052v6yd799c14n%2522%253A%257B%2522id%2522%253A%2522cls9l0x1z00052v6yd799c14n%2522%252C%2522activeTabId%2522%253A%2522cls9l2wii00682v6yfs6ro51k%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522cls9l2wii00682v6yfs6ro51k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cls9l0x1z00032v6y4bwbvfbw%2522%253A%257B%2522id%2522%253A%2522cls9l0x1z00032v6y4bwbvfbw%2522%252C%2522activeTabId%2522%253A%2522cls9l2ty6004m2v6yd3k4llx2%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cls9l2ty6004m2v6yd3k4llx2%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cls9l9l5a00cp2v6yqysxynju%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls9l9j7z00cl2v6ytrc0jx2u%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cls9l9l7g000odie73cb4ebdn%2522%257D%255D%252C%2522id%2522%253A%2522cls9l9l5a00cp2v6yqysxynju%2522%252C%2522activeTabId%2522%253A%2522cls9l9j7z00cl2v6ytrc0jx2u%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by ckifer** [comment]
```jsx
          <Area
            type="monotone"
            dataKey="uv"
            fill="url(#gradientId)"
            stroke="url(#gradientId2)"
            strokeWidth={3}
            // animationDuration={20000}
            // animationEasing="linear"
          ></Area>
          <ReferenceDot
            x={data[data.length - 1].x}
            y={data[data.length - 1].uv}
            r={5}
            // alwaysShow
            ifOverflow="extendDomain"
            // alignmentBaseline="after-edge"
            // width={5}
            // height={5}
            fill="#111"
          />
          <XAxis dataKey="x" hide />
```

**Comment by ckifer** [comment]
Going to close this, comment back if this doesn't address your issue
