### ISSUE TITLE
No payload in activeDot

### ISSUE THREAD

**Issue by belgac** [recharts/recharts#413]
Hello,

Is there a way to get the value of the current active dot in a custom active dot component? I receive no payload prop and index is always equal to 0.

Thank you for your help.

**Comment by damianobarbati** [comment]
I have the same problem, I see no more the "payload" in the activeDot onClick event, how did you solve @xile611 ?

**Comment by Dannzzor** [comment]
@damianobarbati I just noticed this too, however you can just move your `onClick` handler up to the chart element wrapper, and get the payload from the event like so:

FROM:
```
<LineChart ...>
  <Line
    activeDot={{
      onClick: ({payload}) => {...}
    }}
    ...
  />
</LineChart>
```

TO:
```
<LineChart onClick={(e, {payload}) => {...}} ...>
  <Line ... />
</LineChart>
```

**Comment by damianobarbati** [comment]
@Dannzzor thanks, I managed to solve it with your hint.
Moving the handler on LineChart I can find the payload in `event.activePayload[0].payload`, it sucks but better than a broken component.
