### ISSUE TITLE
irregular time series

### ISSUE THREAD

**Issue by smmoosavi** [recharts/recharts#414]
How I can draw irregular time series like this:
http://www.highcharts.com/demo/spline-irregular-time

**Comment by xile611** [comment]
@smmoosavi Don't support now.

**Comment by OracPrime** [comment]
I'd also be very interested in this.  Or to put it another way, ability to have date as an axis type on a Scatter chart.

**Comment by windsome** [comment]
@xile611  Is there a solution? how to add this feature.

**Comment by windsome** [comment]
ok, I found it is related with #154 . axis is number, but let axis displayName generated by a function, can solve this.

**Comment by whphhg** [comment]
I'm having a similar issue, trying to use Scatter chart with y = time in 24h format and x = MM/DD. Any suggestions on how to achieve this?

I've tried using y = Math.round(moment(time).format('HHmmss') and x = Math.round(moment(time).format('YYMMDD') but it doesn't seem to work (Math.round() to convert the string to number).

**Comment by txgruppi** [comment]
@windsome I'm not sure I get your problem but if you can pre-process the data and set the axis labels as strings and the the axis as category it should work.
