### ISSUE TITLE
iOS8.3: TypeError: undefined is not a function (evaluating 'Math.sign(u[1].coordinate-u[0].coordinate)')

### ISSUE THREAD

**Issue by MofeLee** [recharts/recharts#418]
![image](https://cloud.githubusercontent.com/assets/5069410/21520936/54680848-cd33-11e6-9d5d-d921b69ea1ef.png)

**Comment by MofeLee** [comment]
Does we need polyfill on recharts internal?

**Comment by MofeLee** [comment]
We need manually import 'recharts/libs/polyfill'...´😂

**Comment by xile611** [comment]
@MofeLee Do you use `babel-plugin-recharts` ? You can use this plugin and import components of recharts like this:

```jsx
import { Line } from 'recharts';
```
