### ISSUE TITLE
`ResponsiveContainer` component doesn't have a `width` property, causing uncovered lines of code during tests

### ISSUE THREAD

**Issue by atanasivanovv** [recharts/recharts#4195]
### Reproduction link
[https://github.com/atanasivanovv/recharts-line-chart-issue/blob/master/src/__mocks__/recharts.js](https://github.com/atanasivanovv/recharts-line-chart-issue/blob/master/src/__mocks__/recharts.js)

### Steps to reproduce
Create a React component that consists of the problematic `<LineChart />` component setting it a width property, here is an example:

```jsx
<LineChart
   {...(!responsive && { width: 300, height: 300 })}
   data-testid={testIds.chart}
   margin={{ ...defaultMargin, ...margin }}
>
    <div>...</div>
</LineChart>
```

Instead of the div itself, have the component render some data as it is shown in the example snippet of the LineChart component itself (example https://codesandbox.io/p/sandbox/recharts-issue-template-k2xqp?file=%2Fsrc%2Findex.js%3A15%2C1-23%2C3).

Due to ResponsiveContainer which is used underneath not having a width property a lot of the chart's lines are not rendered during snapshot checks and that causes tests a lot of lines of code not to be.

You can see the link to minimal reproduction and what we have for the tests to pass and cover more lines.

### What is expected?

No snapshot deletion when ResponsiveContainer is passed a width property (in our case 330px)

### What is actually happening?

Snapshots have decreased lines of code, due to most line charts not being rendered. 

![Screenshot 2024-02-16 101245](https://github.com/recharts/recharts/assets/46419163/6a2b907d-b970-48ef-93e7-bb27cc2b294a)

| Environment | Info |
|---|---|
| Recharts | v2.12.0 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome 121 |

**Comment by ckifer** [comment]
The linked repo doesn't exist. 

I'm confused though, why should you be testing recharts from your code? I get that you want to snapshot to make sure things aren't going to break but is this something that happened on upgrade or has it always been like this? If it's always been like this there's no reason to change now...

responsive container needs at least a width or a height specified. If that width or a height is 100% then it needs a container to take 100% of. It looks like in this case nothing is specified.

**Comment by atanasivanovv** [comment]
Apologies, I have made the repository public - now it should be seen. It shows the "hacky way" we gat around that.
Also related to you question - the things that do not get covered are the functions such as `tooltipLabelFormatter` and `xAxisTickFormatter`. Again due to the `<ResponsiveContainer>`.

**Comment by ckifer** [comment]
There is no ResponsiveContainer being used in this example https://github.com/atanasivanovv/recharts-line-chart-issue/blob/master/src/App.js#L16-L34 so I'm still confused. 

This may be a JS dom problem? initial dimentions are not set, they are computed by the size of your container. In `ResponsiveContainer` use the `initialDimentions` prop to set height and width for your test https://github.com/recharts/recharts/blob/3.x/src/component/ResponsiveContainer.tsx#L29-L32

**Comment by ckifer** [comment]
Going to close this as I think the above response should solve your issue, feel free to comment back if it doesn't
