### ISSUE TITLE
ES6 Module Issue/ Add ES6 tutorial

### ISSUE THREAD

**Issue by geoffdavis92** [recharts/recharts#420]
**Build process:** Webpack via `create-react-app`
**Modules:** ES6
**Issue:** I'm having some issues getting Recharts to work with my ES6 configuration. This is the module import statement ([image](http://image.prntscr.com/image/62981871d2b9400583ad27dd9e8d59b6.png)), and this is the component using Recharts ([image](http://image.prntscr.com/image/c81f0d3b0db54377ba6ceb61010cf3ed.png)). I'm getting this output([image](http://image.prntscr.com/image/2542654d300742eaaf2694f0efb0734e.png)) that appears to show a library component with an erroneous element name. It is also not showing any output in the DOM.

It would also be nice if there was a more robust getting started guide on your site. Currently, it just gives one example without showing how you import the given components, and does not indicate for ES6 users that you need to import each chart/element module individually. (even the examples just show ES5 implementations) ES6/Webpack is the *de facto* way to write React apps nowadays, so there really isn't a good reason why this has been overlooked.

**Comment by xile611** [comment]
[API for LineChart](http://recharts.org/api#LineChart)
[API for ResponsiveContainer](http://recharts.org/api#ResponsiveContainer)

Please check the api of `LineChart`, `LineChart` can't parse percentage `width`.
If you want to use a percentage `width`, please wrapper `LineChart` with `ResponsiveContainer`.

I'll try to enhance the getting started guide. Meanwhile, PR is welcome. You can submit PR in [recharts/recharts.org](https://github.com/recharts/recharts.org).

**Comment by geoffdavis92** [comment]
Thank you @xile611.

I also noticed that I did not receive any Javascript errors; is this normal? I thought an erroneous value set by a dev should throw an error, which added to my confusion of the actual problem.

**Comment by xile611** [comment]
@geoffdavis92 Please check your configuration. You props does not meet he PropTypes of `LineChart`. You should receive the following error message.  

Warning: Failed prop type: Invalid prop `width` of type `string` supplied to `AnimationDecorator(ComposedDataDecorator(LineChart))`, expected `number`.
    in AnimationDecorator(ComposedDataDecorator(LineChart)) (created by LineChartDemo)
    in LineChartDemo (created by App)
    in div (created by App)
    in App (created by RouterContext)
    in RouterContext (created by Router)
    in Router
