### ISSUE TITLE
Single Points Surrounded By Null Values Do Not Render

### ISSUE THREAD

**Issue by zquestionsdaf** [recharts/recharts#4206]
- [X] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/lpy9cz?file=%2Fsrc%2FApp.jsx)

### Steps to reproduce
1.) Use a area graph

2.) Setup the data points so a value is surrounded by nulls. Example below.
```
[
    {
        time: 1708123800000,
        device_two: null,
    },
    {
        time: 1708123800000,
        device_two: 1.5,
    },
    {
        time: 1708123800000,
        device_two: null,
    },
];
```

3.) Hover over the graph and see that the tooltip shows the data for device_two (1.5), but does not render anything on the graph
 
4.) Example image of tooltip but no area chart
![Screen Shot 2024-02-18 at 1 40 11 PM](https://github.com/recharts/recharts/assets/160423079/135734df-6b1f-4944-84c1-cd613b7cb762)

### What is expected?
That single point is visible on the graph

### What is actually happening?
The data point is not being rendered into the UI

| Environment | Info |
|---|---|
| Recharts | v2.12.0 |
| React | 16.14 |
| System | Mac |
| Browser | Chrome |

**Comment by ckifer** [comment]
Hi, by default Area does not have dots shown when not hovering. To enable this just set `dot` to true on Area and you should see the point. If you'd like to differentiate the always visible dots with the active dot, you can set styles on activeDot

[Sandbox here](https://codesandbox.io/p/devbox/recharts-single-point-bug-forked-y42djs?workspaceId=7a1754d3-b261-47b1-9339-2aca93020961&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsrusubi00093b87ekmztbmo%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsrusubi00033b87bukmkm2h%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsrusubi00063b87jvl0nrce%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsrusubi00083b87talsqz8k%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsrusubi00033b87bukmkm2h%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsrusubi00023b87ivnxyzsl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clsrusubi00033b87bukmkm2h%2522%252C%2522activeTabId%2522%253A%2522clsrusubi00023b87ivnxyzsl%2522%257D%252C%2522clsrusubi00083b87talsqz8k%2522%253A%257B%2522id%2522%253A%2522clsrusubi00083b87talsqz8k%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsrusubi00073b87dqpuzhlz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsrusubi00073b87dqpuzhlz%2522%257D%252C%2522clsrusubi00063b87jvl0nrce%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsrusubi00043b87tb1egpey%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%257D%252C%257B%2522id%2522%253A%2522clsrusubi00053b87p8jrf526%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clsru76h30016d9f85kjz15ug%2522%257D%255D%252C%2522id%2522%253A%2522clsrusubi00063b87jvl0nrce%2522%252C%2522activeTabId%2522%253A%2522clsrusubi00043b87tb1egpey%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by ckifer** [comment]
Other libraries behave similarly, see highcharts as an example https://jsfiddle.net/uoewLr3p/3/ 

Going to close this, please comment back with any questions

**Comment by zquestionsdaf** [comment]
> Other libraries behave similarly, see highcharts as an example https://jsfiddle.net/uoewLr3p/3/
> 
> Going to close this, please comment back with any questions

That makes sense, thank you for the example and information!

**Comment by ckifer** [comment]
Sure thing!
