### ISSUE TITLE
Adding lines dynamically

### ISSUE THREAD

**Issue by geoffreyvd** [recharts/recharts#421]
I would like to know if it's possible to create lines dynamically.

So this is my chart:
```
<LineChart data={this.data}>
            <XAxis dataKey="name"/>
            <YAxis/>
            <CartesianGrid strokeDasharray="3 3"/>
            <Tooltip/>
            <Legend />
            <Line type="monotone" dataKey="uv" stroke="#82ca9d" />
</LineChart>
```

And my data looks like this:
[{"channel_id":1,"date_time":"2016-08-12 10:22:04","value":43,"created_at":"2016-10-19 12:26:05","updated_at":"2016-10-19 12:26:05"},
{"channel_id":2,"date_time":"2016-08-12 08:49:04","value":14,"created_at":"2016-10-19 12:26:05","updated_at":"2016-10-19 12:26:05"},
{"channel_id":2,"date_time":"2016-08-12 07:44:04","value":29,"created_at":"2016-10-19 12:26:05","updated_at":"2016-10-19 12:26:05"}]

But than a 1000 more.
Now the thing is that I have to create a line for every unique channel_id. But I don't know the amount of unique channel_id's on forehand. 
Side note: The x-axis is for the value and the y-axis is for the date_time.

Your answers are appreciated.

**Comment by geoffreyvd** [comment]
<LineChart data={this.data}>
            <XAxis dataKey="name"/>
            <YAxis/>
            <CartesianGrid strokeDasharray="3 3"/>
            <Tooltip/>
            <Legend />
            <Line type="monotone" dataKey="uv" stroke="#82ca9d" />
          </LineChart>

**Comment by xile611** [comment]
@geoffreyvd 
Of course.  But you should format the data first, and get the formatted data like the following :

```js
const formattedData = [
  { "data_time": '2016-08-12 10:22:04', 'timestamp': +(new Date('2016-08-12 10:22:04')),  '1_value': 43,}
  { "data_time": '2016-08-12 08:49:04', 'timestamp': +(new Date('2016-08-12 08:49:04')),  '2_value': 14,}
  { "data_time": '2016-08-12 07:44:04', 'timestamp': +(new Date('2016-08-12 07:44:04')),  '2_value': 14,}
];
```
And meanwhile you should get an array of channel_ids like `const channelIds = ['1', '2']`. Then you can create the chart:

```jsx
<LineChart data={formattedData} layout="vertical">
  <XAxis type="number"  />
  <YAxis dataKey="timestamp" type="number" />
  <CartesianGrid strokeDasharray="3 3"/>
  <Tooltip/>
  <Legend />
  {
    channelIds.map((id) => {
      return (<Line key={`line_${id}`} dataKey={`${id}_value`} />)
    })
  }
</LineChart>
```

**Comment by geoffreyvd** [comment]
Thank you for your respone, so the only way to do this is format my data.
I will see if that is possible.

**Comment by FJunior225** [comment]
I was able to get the `<LineChart>` to render dynamically. Can I change the color of those different line charts dynamically too?

**Comment by xile611** [comment]
@FJunior225 Yeah. Of course.

**Comment by zifnab87** [comment]
why not derive the line names directly from data?

**Comment by yashmiRajamanthrie** [comment]
Can we get the hover  out of the chart container ?

**Comment by jabbowaki** [comment]
Do you have any suggestions on how to have the dynamically created lines be different colors?

**Comment by nurgasemetey** [comment]
@jabbowaki  you can add `stroke`

```
<LineChart data={formattedData} layout="vertical">
  <XAxis type="number"  />
  <YAxis dataKey="timestamp" type="number" />
  <CartesianGrid strokeDasharray="3 3"/>
  <Tooltip/>
  <Legend />
  {
    channelIds.map((id) => {
      return (<Line key={`line_${id}`} stroke="#8884d8" dataKey={`${id}_value`} />) //some random color
    })
  }
</LineChart>
```

**Comment by parassikka77** [comment]
@nurgasemetey This solution gives all the lines the same color. Is there a way to give them a different color for each line?

**Comment by sulzh** [comment]
You can made array of colors and get them by index in map

**Comment by nurgasemetey** [comment]
@parassikka77 I've done following, previous wasn't working

```js
<LineChart width={400} height={300} data={this.props.regionData}
                                // margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
                                >
                                <XAxis dataKey="name" />
                                <YAxis />
                                <CartesianGrid strokeDasharray="3 3" />
                                <Tooltip />
                                <Legend />
                                {/* <Line type="monotone" dataKey="pv" stroke="#8884d8" activeDot={{ r: 8 }} />
                                <Line type="monotone" dataKey="uv" stroke="#82ca9d" />
                                <Line type="monotone" dataKey="amt" stroke="#82ca9d" /> */}
                                {
                                    this.props.regions.map((region) => {
                                        return (<Line  name={region.name} key={`line_${region.name}`} stroke={region.color} dataKey={`${region.name}_value`} />)
                                    })
                                }
                            </LineChart>
```
As you can see in line where `this.props.regions.map`, i create `Line` and assign color(you can randomize)

**Comment by TopicosAvanzados1** [comment]
My question is similar, can I add lines dynamically when I have the next array:

`const data = [
  {
    indicador1: [
      { time: 1636318175, AguaCo2: 17.4 },
      { time: 1636310975, AguaCo2: 5 },
      { time: 1636303775, AguaCo2: 12 },
      { time: 1636296575, AguaCo2: 29 },
    ],
  },
  {
    indicador2: [
      { time: 1636318175, Co2O3: 10 },
      { time: 1636310975, Co2O3: 2 },
      { time: 1636303775, Co2O3: 19 },
      { time: 1636296575, Co2O3: 25 },
    ],
  },
];`

I need a different Line for each indicador, this array have two items, but I can have an array with 100 items and that will be hard. How can I fix this issue, because I have the problem that I can do a map function and add lines but I can't se how to add the correct property to xAxis.

Thanks.
