### ISSUE TITLE
Wrapper and SVG got continuously style changes

### ISSUE THREAD

**Issue by imollm** [recharts/recharts#4215]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/imollm/laliga](https://github.com/imollm/laliga)

### Steps to reproduce
Open https://laliga-sigma.vercel.app/ an click on a player, then in "Estadísticas" section you will see that the chart is growing (height is increased continuously)

### What is expected?
See the chart with a constant height.

### What is actually happening?
The chart wrapper and svg are increasing their max-height and height.

| Environment | Info |
|---|---|
| Recharts | v2.12.1 |
| React | @astrojs/react: 3.0.9 |
| System | MAC OSX Sonoma 14.2.1 |
| Browser | Brave v 1.62.165 |

**Comment by imollm** [comment]
Please check this video for more clarification.


https://github.com/recharts/recharts/assets/31571394/eb105954-5b87-49cd-b6fb-882463fba879

**Comment by ckifer** [comment]
It looks like your changes are currently on your local machine, the repo does not hold any usage of recharts. Can you push your code or create a reproduction in code sandbox?

**Comment by ckifer** [comment]
[![Edit simple-radar-chart (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/simple-radar-chart-forked-rjjjjk)

Saw your example ^ here is a better reproduction than the one above. Without your added styles, this works fine. Recharts requires either a static width or height in responsive container (i.e. your parent at some point must have a static height. This might be why its continuously expanding.
https://recharts.org/en-US/api/ResponsiveContainer

**Comment by imollm** [comment]
I've deployed player's stats page with chart, could you please test it again? Thanks for the fast answers!

**Comment by ckifer** [comment]
The last response above has a code sandbox which "re-creates" your issue but without Tailwind. It looks like something in your tailwind styles are causing this.

If you can re-create the issue in the sandbox without Tailwind then I can take a look

**Comment by imollm** [comment]
I've tested a lot of things and finally it doesn't work, I can't waste more time with this issue, I will use another dependency. Thanks for all @ckifer ❤️

**Comment by ckifer** [comment]
Apologies that it didn't work for you! There are a few issues out there regarding ResponsiveContainer improvements and I'll keep this in mind when we get there
