### ISSUE TITLE
When 2 objects in the data have 0 value and using label in Pie chart it causes duplicate keys

### ISSUE THREAD

**Issue by nadavsol** [recharts/recharts#4219]
When 2 objects in the data have 0 and using label in Pie chart it causes duplicate keys because the key generation is based on start/end angle and they both get the same values.
Removing those objects from the data solves the issue.

**Comment by ckifer** [comment]
This shouldn't be a problem anymore in the latest version. What recharts version are you on?

**Comment by ckifer** [comment]
There are other issues that track key issues and this shouldn't be an issue anymore. If it is feel free to comment back but going to close this as a duplicate for now

**Comment by nadavsol** [comment]
> This shouldn't be a problem anymore in the latest version. What recharts version are you on?

"recharts": "^2.12.0",

**Comment by ckifer** [comment]
Thanks, I'll try to reproduce

**Comment by nadavsol** [comment]
Thanks, if you'll need more information I'll be happy to provide it.

**Comment by ckifer** [comment]
Got it, its the label not the sector that throws the key error 
https://github.com/recharts/recharts/blob/3.x/src/polar/Pie.tsx#L467

We've had a lot of issues addressing key problems with data, so I guess its back to using indexes. I'll take care of this, appreciate the report

**Comment by ckifer** [comment]
Fixed in 2.12.2

**Comment by nadavsol** [comment]
Thank you for your great work!
