### ISSUE TITLE
Can't access viewBox attribute when define PieChart (any) component

### ISSUE THREAD

**Issue by guybensh** [recharts/recharts#422]
recharts components are representing svg elements.
The props of recharts components are only allow to access width and height svg attributes.
There is so prop for viewBox attribute.

Any thoughts or ideas?

Thanks

**Comment by xile611** [comment]
@guybensh By default, we use width and height to create viewbox ([related code](https://github.com/recharts/recharts/blob/master/src/container/Surface.js)).

**Comment by alexliu-github** [comment]
if I would like to change the viewbox values of piechart, currently we don't have a props to do that. Any ideas to work around that?

**Comment by lbai001** [comment]
any updates on this?

**Comment by KelvinPaul** [comment]
try createRef

```export class MyComponent extends Component {
  svgRef = void 0;
  constructor(props) {
    super(props);
    this.svgRef = createRef();
  }

  componentDidMount = () => {
    console.log(this.svgRef.current.current.getElementsByTagName('svg')); //get the svg
  };

  render() {
    return (
      <ResponsiveContainer width="100%" height={300} ref={this.svgRef}>
        ...
      </ResponsiveContainer>
    );
  }
}
```
