### ISSUE TITLE
Trying to figure out proper Typing for a Legend

### ISSUE THREAD

**Issue by roger-tbg** [recharts/recharts#4221]
What i'm trying to sort out is this:
```
<Legend
	content={renderLegend}
	iconSize={0}
	align="right"
	verticalAlign="top"
	offset={-5}
/>
```
What is the TYPING of the renderLegend function:
```
const renderLegend = (props: LegendProps) => {
	const { payload } = props

	return (
		<ul className="mb-4 ml-12 flex justify-between text-xs">
			{payload!.map((entry, index) => {
				return (
					<li key={`item-${index}`} className={`text-[${entry.color}]`}>
						{entry.value}
					</li>
				)
			})}
		</ul>
	)
}
```
I can't seem to find anything for the return type of the function, that makes the content function on Legend happy.

For some reason Webstorm and VSCode want to use: : ContentRenderer<LegendProps> but that isn't an actual valid exported type :)

**Comment by ckifer** [comment]
Thanks for making a new issue 

https://github.com/recharts/recharts/blob/3.x/src/component/DefaultLegendContent.tsx#L21

Looks like the Legend `content` expects a `ReactNode` when using a function to render. Looking over this it should probably be 

```
ReactNode | (props: LegendProps) => ReactNode
```

But that should work

**Comment by roger-tbg** [comment]
> Thanks for making a new issue
> 
> https://github.com/recharts/recharts/blob/3.x/src/component/DefaultLegendContent.tsx#L21
> 
> Looks like the Legend `content` expects a `ReactNode` when using a function to render. Looking over this it should probably be
> 
> ```
> ReactNode | (props: LegendProps) => ReactNode
> ```
> 
> But that should work

Hrm. -- sorry, maybe this is my challenge w/ proper TypeScript syntax. 

I don't see how to take:
```ReactNode | (props: LegendProps) => ReactNode```

and put that into my actual code:
```
const renderLegend = (props: LegendProps) => {
	const { payload } = props

	return (
		<ul className="mb-4 ml-12 flex justify-between text-xs">
			{payload!.map((entry, index) => {
				return (
					<li key={`item-${index}`} className={`text-[${entry.color}]`}>
						{entry.value}
					</li>
				)
			})}
		</ul>
	)
}
```

**Comment by ckifer** [comment]
```tsx
  renderLegend = (props: LegendProps): ReactNode => {
    const { payload } = props;

    return (
      <ul className="mb-4 ml-12 flex justify-between text-xs">
        {payload!.map((entry, index) => {
          return (
            <li key={`item-${index}`} className={`text-[${entry.color}]`}>
              {entry.value}
            </li>
          );
        })}
      </ul>
    );
  };
```

**Comment by roger-tbg** [comment]
Yeah, that does not resolve the typescript error unfortunately.  
![CleanShot 2024-02-22 at 13 25 13](https://github.com/recharts/recharts/assets/141795220/0c2e8411-7b75-48c2-a40d-6d23985aaea0)

**Comment by ckifer** [comment]
The issue isn't with the return type but rather with the parameter type. "Types of parameters props and props are incompatible"

this is unfortunate but "Props" of `DefaultLegendContent` are what is expected here rather than the type of `LegendProps`. This is confusing and needs fixed.

Until then you'll need to import `DefaultLegendContentProps` instead of `LegendProps`

https://github.com/recharts/recharts/blob/3.x/src/index.ts#L14

**Comment by roger-tbg** [comment]
Ahh brilliant!  And thank you, I read the typescript error wrong obviously.

I'm going to file one more too, around the typing for supplying a custom shape for a <Bar
