### ISSUE TITLE
ResponsiveContainer/ReactResizeDetector wrong calculated size in firefox

### ISSUE THREAD

**Issue by bali182** [recharts/recharts#423]
I have a flexbox card layout, in which I'm trying to display some rechart charts. It works perfectly in chrome, but in firefox I'm having this issue:

![peek 2017-01-02 17-37](https://cloud.githubusercontent.com/assets/3879181/21593777/c5c7ca7c-d112-11e6-80bc-2770ab5471eb.gif)

I could track it down to `ResponsiveContainer` or `ReactResizeDetector` (I suspect the later), but basically size is correctly calculated when the page is growing, but not when shrinking. In `ReactResizeDetector` detector seem to rapidly notify the component about **growth** instead of shrinking. 

Meanwhile I'm trying to put together a fiddle, but I'm not sure what are the critical factors to reproduce this.

Btw, thanks for this awesome library :wink:

**Comment by bali182** [comment]
A simpler repro on fiddle:

http://jsfiddle.net/bali182/mv73f30q/1/

**Comment by bali182** [comment]
Looking a bit further it seems like `flex-basis` causes somehow the bogus width values, since without it  the problem doesn't occur:

http://jsfiddle.net/mv73f30q/5/

**Comment by bali182** [comment]
Adding `min-width: 0` to the css class `card` also solves the issue. This definitely is a firefox issue. Closing this jira, since it's not rechart's fault.

**Comment by ggregoire** [comment]
I had a similar issue on **Chrome**, the width of the `ResponsiveContainer` was increasing infinitely. Adding `min-width: 0` to the parent of `ResponsiveContainer` solved the issue (not sure why though, looks like a hack).
