### ISSUE TITLE
The chart shrinks when I apply a larger scale on it's parent container

### ISSUE THREAD

**Issue by zhonglin94** [recharts/recharts#4246]
Hi Recharts experts!

The chart shrinks when I apply a larger scale on the parent container. The following is a video demonstrating the issue.

Thank you so much if you could take a look and give me some suggestions!

https://github.com/recharts/recharts/assets/32061513/e8619a28-5653-4621-b2fd-b11569e8f6d2

**Comment by ckifer** [comment]
It looks like things are just adjusting from the margin on the chart. You could try reducing margin on the fly maybe or starting off with less?

**Comment by zhonglin94** [comment]
> It looks like things are just adjusting from the margin on the chart. You could try reducing margin on the fly maybe or starting off with less?

Hi Ckifer, I did not see any margin that has been applied to the chart when I adjust the parent container's scale. I can reproduce this in the recharts official website.

https://github.com/recharts/recharts/assets/32061513/581fa470-fa65-4071-bafd-abe32ca5af08

**Comment by ckifer** [comment]
These things do not look the same. Here with `scale` or `transform: scale` there is no movement in the chart size and the margin of the chart is unchanged. This is correct behavior. 

The first video is different than the second - what are you using for scale in the first video?

**Comment by zhonglin94** [comment]
> These things do not look the same. Here with `scale` or `transform: scale` there is no movement in the chart size and the margin of the chart is unchanged. This is correct behavior.
> 
> The first video is different than the second - what are you using for scale in the first video?

The chart is placed inside the react flow's node and the transform of react flow view port is "**transform: translate(-3447.32px, -1646.51px) scale(2.85055)**" for example.

**Comment by ckifer** [comment]
Unless you are using an old version of recharts, which may have this issue

**Comment by RrYusheng** [comment]
I set the composedchart prop like this：
![code](https://github.com/recharts/recharts/assets/31916244/a21753f7-41f6-4601-a81e-7c6020ac7736)
but it seems still not working properly：
<img width="613" alt="image" src="https://github.com/recharts/recharts/assets/31916244/3d749a57-79b9-4398-9b4c-80c8ab47f72d">

**Comment by RrYusheng** [comment]
looks like Yaxis is been compressed

**Comment by ckifer** [comment]
You have static heights and widths on some of your components, those might be causing issues

**Comment by zhonglin94** [comment]
> Unless you are using an old version of recharts, which may have this issue

Hi Ckifer, I think that I have found the root cause for this issue: the [legend size(height and width)](https://github.com/okonet/react-container-dimensions/issues/5) provided by the `getBoundingClientRects` is changed if it's parent container is transformed using scale. If the container scale is 3x, then the legend height is significantly smaller than usual, which makes the chart content significant smaller than expected.

Consequently, I propose to fix this issue as following:
![截屏2024-03-08 下午11 10 19](https://github.com/recharts/recharts/assets/32061513/1e9c7bbe-6457-40d5-b76c-02d8fe8bf080)

**Comment by ckifer** [comment]
Thanks for the find. Please feel free to contribute the fix if you'd like!

**Comment by ckifer** [comment]
released in 2.12.3
