### ISSUE TITLE
Brush startIndex not updating

### ISSUE THREAD

**Issue by raviteja83** [recharts/recharts#425]
setting `startIndex` has no effect on the brush,it does not move to the particular index.

**Comment by xile611** [comment]
@raviteja83 I think it was covered by [parent component](https://github.com/recharts/recharts/blob/master/src/chart/generateCategoricalChart.js#L925).

How about your use case ?

**Comment by raviteja83** [comment]
i am passing startIndex as props to brush  and the dataStartIndex is not taken from props of brush or parent(composedchart in my case).it is created in state.The startIndex is always 0.
