### ISSUE TITLE
Hide yAxis, keep first item on xAxis

### ISSUE THREAD

**Issue by giuseppepaul** [recharts/recharts#428]
Hi guys, I'm not sure if I'm missing something but I've been looking at this for a while, I'm hoping to be pointed in the right direction. I'm trying to create a Line Chart with days of the week across the x axis:

MON TUES WED THU FRI SAT SUN

The yAxis is just simple numbers, the data looks like this (from your example):

const data = [
    {name: 'Mon', uv: 5, pv: 7},
    {name: 'Tue', uv: 10, pv: 4},
    {name: 'Wed', uv: 8, pv: 16},
    {name: 'Thu', uv: 13, pv: 14},
    {name: 'Fri', uv: 4, pv: 4},
    {name: 'Sat', uv: 2, pv: 6},
    {name: 'Sun', uv: 3, pv: 0},
];

I'm trying to hide the yAxis ticks and spacing (padding etc..) so you only see the number when you hover over the chart via the tooltip. Unfortunately when I set hide or just remove the yAxis component:

<YAxis hide={true} />

...the first item disappears, the data is correct on the chart but the 'MON' name goes missing from the bottom along the xAxis.

I've attached a screenshot to show what I mean, is there any way to stop this?

Thanks!
<img width="334" alt="screen shot 2017-01-04 at 16 59 39" src="https://cloud.githubusercontent.com/assets/1936183/21651092/466df272-d29f-11e6-9660-9fe52d4a84e3.png">

**Comment by xile611** [comment]
@giuseppepaul  

You can use `interval={0}` to force all the ticks to be shown. By default, we'll calculate the width of tick and hide some ticks when no enough space. But the calculation may be inaccurate in some cases. We'll try to fix it.

```jsx
<XAxis interval={0} />
```

**Comment by detautama** [comment]
> @giuseppepaul
> 
> You can use `interval={0}` to force all the ticks to be shown. By default, we'll calculate the width of tick and hide some ticks when no enough space. But the calculation may be inaccurate in some cases. We'll try to fix it.
> 
> ```js-jsx
> <XAxis interval={0} />
> ```

I think better to use 
`<XAxis interval="preserveStartEnd" dataKey="name" />`
