### ISSUE TITLE
Tooltip doesn't work

### ISSUE THREAD

**Issue by francescabassi** [recharts/recharts#429]
Hi guys,
I have an issue with Tooltip

This is my chart:

<ResponsiveContainer height={500} width={'100%'}>
  <LineChart  data={chart}  margin={{ top: 5, right: 30, bottom: 20, left: 5 }}>
    <XAxis dataKey="date"/>
    <YAxis />
    <CartesianGrid strokeDasharray="3 3" />
    <Tooltip />
    <Line name="Amount In" type="monotone" dataKey="amount_in" stroke="#8884d8" unit={' €'}/>
    <Line name="Amount Out" type="monotone" dataKey="amount_out" stroke="#82ca9d" unit={' €'} />
    <Legend verticalAlign="bottom" height={36} />
    <Brush />
  </LineChart>
</ResponsiveContainer>

The tooltip doesn't appear and in the console I have this error:
Tooltip.js:173 Uncaught TypeError: Cannot read property 'x' of undefined.

Anyone can help me? 
Thanks

**Comment by xile611** [comment]
@francescabassi I think it has been fixed in version 0.20.2.
