### ISSUE TITLE
In a scroll or render multiple charts, graphs will be flashing

### ISSUE THREAD

**Issue by raisezhang** [recharts/recharts#431]
HI guys:

In the process of using found some bugs
1、Chart of initializing render slants big, resulting in overlapping ```Legend``` on the chart
Screenshots:  http://recordit.co/bQtdUpjyv8
2、In a scroll or render multiple charts, graphs will be flashing
Screenshots:  http://recordit.co/fNVfbJky2n    （in 10 ~ 12 seconds）

Unfortunately, No repetition of this kind of problem in JSFiddle, don't know to have similar problems can under reference

```jsx
<ResponsiveContainer height={360}>
  <LineChart data={data}>
    <XAxis dataKey="date"/>
    <YAxis/>
    <CartesianGrid strokeDasharray="3 3"/>
    <Tooltip/>
    <Legend/>
    <Line name="PV" type="monotone" strokeWidth={2} dataKey="pv" stroke="#31d6c5" activeDot={{
      r: 8
    }}/>
    <Line name="UV" type="monotone" strokeWidth={2} dataKey="uv" stroke="#aea9fd"/>
  </LineChart>
</ResponsiveContainer>
```

Thanks ~

**Comment by xile611** [comment]
@raisezhang The crash may be caused by hot-loader.

**Comment by xile611** [comment]
I'll try to optimize problem 1.
But problem 2 seems very strange. what's the purple block?

And If problem 2 only happens in development environment, you can try to remove hot-loader and check whether this problem can be reproduced.

**Comment by raisezhang** [comment]
Thank you for reply~

Purple block is the parent container background image,
Online and development environment are the same problem.

**Comment by xile611** [comment]
@radarhere Can you create a jsfiddle demo ?

**Comment by radarhere** [comment]
@xile611 I believe you meant @raisezhang

**Comment by xile611** [comment]
@radarhere Yeah! sorry...

**Comment by xile611** [comment]
I think problem 1 has been fixed. About problem 2, let me know if you can reproduce it in an online demo.
