### ISSUE TITLE
reduce the offset provided

### ISSUE THREAD

**Issue by raviteja83** [recharts/recharts#432]
The graph is offset by some default values which leaves so much blank space around the graph.how to reduce the offset.I am using composedchart with bar and line and i would like to reduce the offset between svg container start and the graph start.

**Comment by xile611** [comment]
@raviteja83 You can update margin of chart and adjust the width of `YAxis`, height of `XAxis`.

**Comment by ackvf** [comment]
I don't have XAxis in my chart and I set margin-left to -40 to make out for the unnecessary blank space.
