### ISSUE TITLE
The first hover over a Scatter chart point displays the custom tooltip in an incorrect position

### ISSUE THREAD

**Issue by qnpbgood** [recharts/recharts#4338]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/9mr9qt?file=%2Fpackage.json&layout=%7B%22sidebarPanel%22%3A%22EXPLORER%22%2C%22rootPanelGroup%22%3A%7B%22direction%22%3A%22horizontal%22%2C%22contentType%22%3A%22UNKNOWN%22%2C%22type%22%3A%22PANEL_GROUP%22%2C%22id%22%3A%22ROOT_LAYOUT%22%2C%22panels%22%3A%5B%7B%22type%22%3A%22PANEL_GROUP%22%2C%22contentType%22%3A%22UNKNOWN%22%2C%22direction%22%3A%22vertical%22%2C%22id%22%3A%22clu462c0m0006356j8dnze50e%22%2C%22sizes%22%3A%5B75.74361800745693%2C24.25638199254307%5D%2C%22panels%22%3A%5B%7B%22type%22%3A%22PANEL_GROUP%22%2C%22contentType%22%3A%22EDITOR%22%2C%22direction%22%3A%22horizontal%22%2C%22id%22%3A%22EDITOR%22%2C%22panels%22%3A%5B%7B%22type%22%3A%22PANEL%22%2C%22contentType%22%3A%22EDITOR%22%2C%22id%22%3A%22clu462c0m0002356je6xsw9ub%22%7D%5D%7D%2C%7B%22type%22%3A%22PANEL_GROUP%22%2C%22contentType%22%3A%22SHELLS%22%2C%22direction%22%3A%22horizontal%22%2C%22id%22%3A%22SHELLS%22%2C%22panels%22%3A%5B%7B%22type%22%3A%22PANEL%22%2C%22contentType%22%3A%22SHELLS%22%2C%22id%22%3A%22clu462c0m0004356jl13j3ph1%22%7D%5D%2C%22sizes%22%3A%5B100%5D%7D%5D%7D%2C%7B%22type%22%3A%22PANEL_GROUP%22%2C%22contentType%22%3A%22DEVTOOLS%22%2C%22direction%22%3A%22vertical%22%2C%22id%22%3A%22DEVTOOLS%22%2C%22panels%22%3A%5B%7B%22type%22%3A%22PANEL%22%2C%22contentType%22%3A%22DEVTOOLS%22%2C%22id%22%3A%22clu462c0m0005356ju0p77sq6%22%7D%5D%2C%22sizes%22%3A%5B100%5D%7D%5D%2C%22sizes%22%3A%5B50%2C50%5D%7D%2C%22tabbedPanels%22%3A%7B%22clu462c0m0002356je6xsw9ub%22%3A%7B%22id%22%3A%22clu462c0m0002356je6xsw9ub%22%2C%22tabs%22%3A%5B%7B%22id%22%3A%22clu46zs1g0002356ju3ergioa%22%2C%22mode%22%3A%22permanent%22%2C%22type%22%3A%22FILE%22%2C%22filepath%22%3A%22%2Fpackage.json%22%2C%22state%22%3A%22IDLE%22%7D%5D%2C%22activeTabId%22%3A%22clu46zs1g0002356ju3ergioa%22%7D%2C%22clu462c0m0005356ju0p77sq6%22%3A%7B%22id%22%3A%22clu462c0m0005356ju0p77sq6%22%2C%22activeTabId%22%3A%22clu462pqc00df356jlesdnu59%22%2C%22tabs%22%3A%5B%7B%22type%22%3A%22TASK_PORT%22%2C%22taskId%22%3A%22Development%22%2C%22port%22%3A5173%2C%22id%22%3A%22clu462pqc00df356jlesdnu59%22%2C%22mode%22%3A%22permanent%22%2C%22path%22%3A%22%2F%22%7D%5D%7D%2C%22clu462c0m0004356jl13j3ph1%22%3A%7B%22id%22%3A%22clu462c0m0004356jl13j3ph1%22%2C%22activeTabId%22%3A%22clu462l61009n356j7x9ncsan%22%2C%22tabs%22%3A%5B%7B%22id%22%3A%22clu462c0m0003356jct00130n%22%2C%22mode%22%3A%22permanent%22%2C%22type%22%3A%22TERMINAL%22%2C%22shellId%22%3A%22clu462cc4000bdbf83benh2h0%22%7D%2C%7B%22type%22%3A%22TASK_LOG%22%2C%22taskId%22%3A%22Development%22%2C%22id%22%3A%22clu462l61009n356j7x9ncsan%22%2C%22mode%22%3A%22permanent%22%7D%5D%7D%7D%2C%22showDevtools%22%3Atrue%2C%22showShells%22%3Atrue%2C%22showSidebar%22%3Atrue%2C%22sidebarPanelSize%22%3A15%7D)

### Steps to reproduce
Point at any point for the first time

### What is expected?
Tooltip must be in the correct position after hovering over the point

### What is actually happening?
Tooltip is displayed in the top left point of the chart

| Environment | Info |
|---|---|
| Recharts | v2.12.3 |
| React | 18.2.0 |
| System | Windows 11 Pro |
| Browser | Chrome v123.0.6312.59 |

---
As I see it, the tooltip is initially located in the top left corner of the chart with the CSS property visibility: hidden. When hovering over it, the visibility property changes to visible and the transform property with the value translate(x, y) should be added, but this does not happen. However, when hovering over the points later, everything works as it should.

**Comment by ckifer** [comment]
This must be specific to when there is a custom Tooltip and it looks to be specifically because of this line 

```
if (!active || !payload || !payload.length) return null;
```

Remove that and everything works normally

**Comment by qnpbgood** [comment]
Thanks for the quick response. In my case, I need to check the availability of payload because further logic for outputting data to Tooltip depends on this. As an alternative to returning null, I return any tag with insignificant content and this fixes my problem but seems a bit clunky. Could it be possible to return some default tooltip behavior?
```tsx
export const CustomizedTooltip: React.FC<TooltipProps<ValueType, NameType>> = ({
  payload,
  active,
}) => {
  if (active && payload && payload.length) {
    // Some logic that depends on payload
    return <div> Tooltip content </div>;
  } else {
    // It's works fine but looks ugly
    return <span>.</span>;
  }
};
```
Empty tag not work here

**Comment by ckifer** [comment]
what do you mean it looks ugly? The code looks ugly? The functionality looks the same as it does by default.

I think ideally, we would change the tooltip behavior to not "fly in" like it currently does and just have it appear at the first point and animate from there.

For now you can do this
```tsx
export const CustomizedTooltip: React.FC<TooltipProps<ValueType, NameType>> = ({
  payload,
  active,
  ...props
}) => {
  if (active && payload && payload.length) {
    // Some logic that depends on payload
    return <div> Tooltip content </div>;
  } 
  return <DefaultTooltipContent payload={payload} {...props} />
};
```

**Comment by qnpbgood** [comment]
```ts
return <DefaultTooltipContent payload={payload} {...props} />
```
Thank you! That's what I was looking for.
