### ISSUE TITLE
Accessibility issue with Brush component

### ISSUE THREAD

**Issue by anshika1422** [recharts/recharts#4343]
Hi Team ,
We are using Brush element in our application 
As we could check in our app as well as in this example https://recharts.org/en-US/examples/BrushBarChart  the brush traveller is accessible on tabbing and if we use space+ arrow keys we can increase or decrease the values. 
But its not reading the index values through screen reader and coming as undefined. 

Is there a way to make it accessible to screen reader and read out the values.

Thanks & Regards!!

**Comment by ckifer** [comment]
Are you on the latest version and using accessibilityLayer?

**Comment by anshika1422** [comment]
We are on version "recharts": "^2.5.0"

I am not sure about what you mean by accessibility layer here .
Could you please help me with some examples of how to add this layer or what is the way

**Comment by ckifer** [comment]
Please upgrade to the latest version 2.12.3 - there have been a few accessibility improvements since between the two releases. 

After that I can add more about what I mean, I'm currently replying from my phone so it's hard to give examples.

**Comment by ckifer** [comment]
Going to close this. Feel free to comment back if there is still an issue
