### ISSUE TITLE
 Support for defaultProps will be removed from function components in a future major release.

### ISSUE THREAD

**Issue by sailchou** [recharts/recharts#4349]
The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.

---app-index.js:35 Warning: XAxis: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

**Comment by ckifer** [comment]
Please see https://github.com/recharts/recharts/issues/3615#issuecomment-2018091669
