### ISSUE TITLE
Cannot customize recharts-active-dot

### ISSUE THREAD

**Issue by 15077693d** [recharts/recharts#4359]
The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.
![Screenshot 2024-03-28 at 15 12 37](https://github.com/recharts/recharts/assets/51513183/9b59c8e8-af99-4f59-b70d-a412a05e785e)
I can set display none but not style the dot
---

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

**Comment by ckifer** [comment]
Closing as this is a question - see answer in duplicate discussion https://github.com/recharts/recharts/discussions/4358
