### ISSUE TITLE
Customize ticks in Radar Chart based on their representing values

### ISSUE THREAD

**Issue by with0out** [recharts/recharts#436]
I'm wondering if it's possible to customize the ticks in such a way, for example, in the [RadarChart](http://recharts.org/#/en-US/examples/SimpleRadarChart), style History to red, because the student have low score.

So far I can only style all ticks with same color, is there a way to achieve this? Thanks!

**Comment by xile611** [comment]
@with0out You can use customized `tick` like this [demo](http://jsfiddle.net/dpvqmgf2/).

**Comment by with0out** [comment]
@xile611 Thanks, it works like a charm, really appreciate your demo!

**Comment by rishabh-uabler-100** [comment]
I want SVG to be rendered in tick, any idea on how to do that?

**Comment by jhanzuro** [comment]
Update: `payload.angle` is now `payload.coordinate`. Demo is still working, just needed to change that.
