### ISSUE TITLE
Richer payload for custom labels/tooltips

### ISSUE THREAD

**Issue by OracPrime** [recharts/recharts#437]
I like the ability to customize tooltips for points on the charts.  However it would be nice if the payload represented the data that corresponded to the point originally.  e.g. if my data consisted of objects such as
{ x: 2005, Score: 30, When:new Date(2005,1,6)  }
and I'm graphing x vs Score, then it would be nice to get hold of this whole object as the payload so that I could use When in my tooltip.  At present the payload only includes the fields used in drawing the chart (so x and Score).

**Comment by xile611** [comment]
@OracPrime Which chart ?

**Comment by OracPrime** [comment]
Scatter -  I'm looking at this as a work around for no data axes in scatter charts.  Thinking of having numeric years as the axis and the date as a tool tip on each point

**Comment by dnorth** [comment]
+1 on this. It seems like the payload is inconsistent across the board. 

For example, the `<Bar />` payload represents the entire object but `<XAxis />` payload seems to only represent the fields used in drawing the chart.

**Comment by jseparovic** [comment]
+1 here too. I was quite surprised that the value passed to a custom label on a bar only returns the second array element. So, I can't represent both min/max labels at present.
having access to the payload would be perfect. (I actually want to represent min/avg/max values as labels on the bar)

**Comment by jseparovic** [comment]
For a workaround, I did the following:
```
<BarChart
    layout="vertical"
    data={this.props.data}
>
    <Bar
        dataKey={(x) => this.getData(0, x)}
        fill={COLORS[0]}
        barSize={15}
        minPointSize={2}
        isAnimationActive={this.props.isAnimationActive}
        label={(x) => this.getCustomLabel(0, x, this.props.data)}
    />
    <Bar
        dataKey={(x) => this.getData(1, x)}
        fill={COLORS[1]}
        barSize={15}
        minPointSize={2}
        isAnimationActive={this.props.isAnimationActive}
        label={(x) => this.getCustomLabel(1, x, this.props.data)}
    />
```

and using function like:
```
    getCustomLabel(ix, props, data)
    {
        const {x, y, fill, value, index, offset, width, height} = props;
        const d = data[index].data[ix];
        return <text
            x={x+3}
            y={y+16}
            dy={-4}
            fontSize='12'
            fontFamily='sans-serif'
            fill='white'
            textAnchor="left">${d.min} / ${d.avg} / ${d.max}</text>
    }
```

I still need to update this so the min, avg and max are positioned properly on the X axis, but am able to get chart data into the label function.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue guide.
