### ISSUE TITLE
Reference bar / overlay bar 

### ISSUE THREAD

**Issue by mmmdreg** [recharts/recharts#439]
Is there a way to overlay bars on top of each other so they start from the baseline y and are centered on the same point on the x axis? Currently they can be stacked on be side by side. 

The width and color would be specified in order to differentiate the bars at each point. 

This is useful to have a reference (or multiple) at each point. For example, visualising the current value against historical peak and historical average.

**Comment by xile611** [comment]
@mmmdreg Thanks! Great suggestion!

**Comment by xile611** [comment]
@mmmdreg  How about this [demo](http://jsfiddle.net/k971to6h/) ?

**Comment by mmmdreg** [comment]
Demo is perfect once I set barSize on each bar. Thanks a lot!

**Comment by nahushf** [comment]
The fiddle does not seem to be working. On copying the same code from the fiddle to codepen, it doesn't look like the bars are overlapping. How do I get about this?

**Comment by aakashrshah** [comment]
@xile611 So far all your comments have been really brief and little less informative. I mean no offence to you. I apologize in advance but your comments are very important to choose a direction further while using recharts. Thanks. 

Just a reference of context - [react - Issues](https://github.com/facebook/react/issues/15896#issuecomment-502481158)
