### ISSUE TITLE
Tooltip deprecation

### ISSUE THREAD

**Issue by YuvalPeretz** [recharts/recharts#4405]
The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.

---

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

![image](https://github.com/recharts/recharts/assets/73059247/35fee3e2-9fe6-4a25-a3ed-fb5f88692167)
![image](https://github.com/recharts/recharts/assets/73059247/9426cfb9-5872-439c-a300-e18636c9f8b4)

The tooltip is deprecated and probably needs to be updated soon.

What can I do in the meantime?

**Comment by ckifer** [comment]
Hey there! Tooltip is not deprecated and I'm not sure why it's saying that. One of the props might be, but the whole component is not.
