### ISSUE TITLE
Radial Bar: Text same color as fill

### ISSUE THREAD

**Issue by patryk0605** [recharts/recharts#443]
In the [SimpleRadialBarChart](http://recharts.org/#/en-US/examples/SimpleRadialBarChart), the text of the value within each radial bar use to be visible, but now the text is the same color as fill - masking the value. For example, if the `uv` value is reduced from **6.67** to **0.67** like so: `{name: 'unknow', uv: 6.67, pv: 4800, fill: '#ffc658'}` to `{name: 'unknow', uv: 0.67, pv: 4800, fill: '#ffc658'}`, then the value can be seen partially: 

![image](https://cloud.githubusercontent.com/assets/7227636/21821579/10acdf0c-d742-11e6-86f1-97699133b4cd.png)

Is there another value to specify the color of text? Can it be defaulted to white or it's previous behavior?

**Comment by xile611** [comment]
[demo](http://jsfiddle.net/j6n54k0r/)

@patryk0605 You can specify the color of text by `label={{ fill: '#fff' }}`.

**Comment by patryk0605** [comment]
Super, thanks!
