### ISSUE TITLE
Some issues with building on Windows

### ISSUE THREAD

**Issue by OracPrime** [recharts/recharts#445]
I'm attempting to get this project building/running on my system with a view to making some contributions.   I may be doing something stupid, but I'm having a few issues.

1) [I'll submit this fix when I've got everything working] package.json needs to make use of cross-env in some of the script entries to make it work on Windows (and have a dev dependency of cross-env).

2) Demo/index.html contains a reference to  <script src="bundle.js"></script> whereas the webpack is putting bundle.js into the build subfolder.  So at least on my system I need  <script src="build/bundle.js"></script>.  I just wanted to check whether a) I've missed the point b) non-Windows systems somehow look in build/  c) it's a bug.

**Comment by OracPrime** [comment]
OK I now understand how 2 is works using npm run-script demo.  Although I'm not yet sure how it works - I *think* that webpack is serving its in-memory copy of bundle.js (because the name, if not the path, matches) and so it doesn't notice that the path is wrong.  I still suspect that the reference in index.html should be build/bundle.js  - which works with webpack-dev-server and also with visual studio.

If we want to encourage windows developers, it might be worth adding a note to the readme as to how to fire up the demos?

**Comment by OracPrime** [comment]
And I think I've got the stage where I have some minor changes on my fork to commit, but the lint rules are insisting on LF linebreaks, whereas git has pulled CRLF style files because I'm on windows, and  I've got 12252 lint errors :(   

Any suggestions?  I hesitate to hack the lint rules for the project on my first commmit!

**Comment by xile611** [comment]
@OracPrime Can you submit a PR ? We have no windows computer...

**Comment by OracPrime** [comment]
Done.  That's my first ever GitHub pull request, so I hope I've got it right.  I'm from a Windows+SVN background...

**Comment by xile611** [comment]
Fixed in 0.20.3.
