### ISSUE TITLE
Question on exporting `useChartWidth` and similar api 

### ISSUE THREAD

**Issue by prtmwrkr** [recharts/recharts#4452]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

It will make possible for Recharts users to customise the charts even further.

### My use case

This is a scatterplot based on this [demo](https://recharts.org/en-US/examples/SimpleScatterChart).

![v1](https://github.com/recharts/recharts/assets/93121229/a03a85c5-e49f-4257-93fe-485915fa6e32)

This is what I need to implement.

![v2](https://github.com/recharts/recharts/assets/93121229/209ad0ec-3a48-4e04-9023-215870bcb39d)

Since Recharts doesn't support this visualization out of the box (correct me if I'm wrong), I thought to implement something similar to `<CartesianGrid />`. To do it properly I need to access the data in the React's context of the chart, similarly to how the `<CartesianGrid />` component does internally.

Problem is that `useChartWidth()` and similar apis are not publicly exported at the moment.

**My question is: would you be open to the idea of making this api public?** 
 If the answer is yes, I would also be willing to contribute to the project to make this happen. Please let me know.

### What does the proposed API look like?
No changes on the API - just make some of the existing private APIs publicly available.

**Comment by ckifer** [comment]
These APIs aren't even used at the moment! This only exists in the 3.x branch which has not been released yet.

Exporting these hooks is part of the plan though!

You can currently use the <Customized /> (which gives access to the entire recharts state) component to do some interesting custom work, but this _will_ break and be removed in 3.x

You can see chart width/offset being used in this sandbox a bit
https://codesandbox.io/p/sandbox/simple-line-chart-forked-j5jyjw?file=%2Fsrc%2FApp.tsx%3A79%2C11

Going to close this, as it is planned for 3.x

**Comment by prtmwrkr** [comment]
@ckifer Thank you - i will have a look.
