### ISSUE TITLE
BarChart : Without BarSize bug, with BarSize another Bug

### ISSUE THREAD

**Issue by matiassemelman** [recharts/recharts#4454]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/blissful-volhard-89rlm8?file=%2Fsrc%2FApp.tsx)

### Steps to reproduce
Link

### What is expected?
When I have one value to represent, the barSize is at the center and narrow. When I have 2 values to represent, bars are narrow and together.

### What is actually happening?
When I have one value to represent, the barSize is at the end of the chart and extra wide, and I'm unable to center it. When I have 2 values to represent, bars are wide and separated, and I cannot join them.

| Environment | Info |
|---|---|
| Recharts | v2.12.6 |
| React | react/18.2 |
| System | Ubuntu |
| Browser | Chrome |

**Comment by ckifer** [comment]
this is the result of having more than one series. It centers the bar groups  - so in this case you have two `Bar` components and it splits the distance between the two, even if there is no data for one of them. If you add another <Bar /> it will split the distance in the middle of 3 bars, etc.

One option for when there is only one datapoint is just to not render the <Bar /> for the other series

[![Edit modest-hertz-zgzdph](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/modest-hertz-zgzdph?file=%2Fsrc%2FApp.tsx%3A164%2C40-164%2C46)

**Comment by ckifer** [comment]
I'm going to close this because it is unclear what is desired. If the issue could be re-written as a feature request or enhancement we can re-open it! Otherwise if you just need help, feel free to keep responding here and I'll try to help the best I can. Thanks!
