### ISSUE TITLE
Display data in Brush

### ISSUE THREAD

**Issue by ZephD** [recharts/recharts#446]
Is it possible to display graphable data in the brush?

For example, the dataKey is the x-axis key, but can we also have show one (or more) of our y-axis data in the brush?

[Like this](https://i.stack.imgur.com/JYBwS.png)

**Comment by GregPhyn** [comment]
Has this been implemented?
Is usage like 
<Brush dataKey="the_dataKey" /> ?

**Comment by xile611** [comment]
@GregoryPotdevin Not yet.

**Comment by Eric24** [comment]
+1

**Comment by evisong** [comment]
Hi, I've created a PR #586 for this ticket, could you please help review it when you have some time? Thanks.

**Comment by xile611** [comment]
Fixed in version 0.22.0

**Comment by gknapp** [comment]
This capability is available from 0.22.0? In a later issue (#792) @xile611 said it's not implemented yet?

https://github.com/recharts/recharts/issues/792

I'm confused, can this be achieved with recharts as per #586 ?
