### ISSUE TITLE
Area Chart - Edge Case for Visual Display of One Value

### ISSUE THREAD

**Issue by GregPhyn** [recharts/recharts#447]
Hello recharts team,

I've noticed that when there is only 1 value to display for AreaChart, it messes up the look. To illustrate,

This is how data looks with multiple values (good):
<img width="323" alt="screen shot 2017-01-11 at 11 34 52 am" src="https://cloud.githubusercontent.com/assets/22822404/21863362/00154f98-d7f2-11e6-82ea-2293f822700b.png">

This is how data looks with only 1 value:
<img width="332" alt="screen shot 2017-01-11 at 11 36 05 am" src="https://cloud.githubusercontent.com/assets/22822404/21863389/1c725a50-d7f2-11e6-995c-f30821ad9d3e.png">

How do you guys display one value and get around this?

**Comment by xile611** [comment]
@GregPhyn When we have just one value, only one point can be displayed.

**Comment by caseychoiniere** [comment]
I understand the idea of only having one value so only showing a point but it seems like it should still fill the chart. 

Like this: 
![screen shot 2018-02-07 at 2 58 59 pm](https://user-images.githubusercontent.com/10411174/35946467-b774622c-0c18-11e8-8211-050db22088e5.png)

Or this:
![screen shot 2018-02-07 at 2 56 27 pm](https://user-images.githubusercontent.com/10411174/35946477-c1b96dc2-0c18-11e8-9dc0-94a6284c669e.png)
