### ISSUE TITLE
Add padding between axis and tick

### ISSUE THREAD

**Issue by chin-idean** [recharts/recharts#448]
Hi, i would like to add some padding between Axis and Tick, read some comment on #201 
But unfortunately can not add padding-top, padding right did work.

Is there any part of doc or code sample for customtick component and tick props ?

**Comment by xile611** [comment]
@chin-idean 

You can use [`transform` of tick](http://jsfiddle.net/e6r4bxf5/) or [customized tick](http://jsfiddle.net/yhp9esbs/).

**Comment by chin-idean** [comment]
@xile611 
![screen shot 2017-01-13 at 11 28 51](https://cloud.githubusercontent.com/assets/23170550/21924858/898fc98c-d983-11e6-8410-06fb246bb58d.png)

Increase width of tick ?
