### ISSUE TITLE
Points property not generating for Area Chart in v2.12.6

### ISSUE THREAD

**Issue by Millian-22** [recharts/recharts#4480]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/simple-area-chart-forked-mqrs6z?file=%2Fsrc%2FApp.tsx%3A59%2C33-59%2C36)

### Steps to reproduce
1. Navigate to provided [link](https://codesandbox.io/p/sandbox/simple-area-chart-forked-mqrs6z?file=%2Fsrc%2FApp.tsx%3A59%2C33-59%2C36)

2. Open console and view a "props" log 
3. See that no [points property](https://recharts.org/en-US/api/Area#points) is being generated

### What is expected?
Points property is being generated by Area chart. Customized Dots appear on Area Chart

### What is actually happening?
No points property is being generated by area chart. No dots appear.

| Environment | Info |
|---|---|
| Recharts | v2.12.6 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Chrome Version 124.0.6367.119 (Official Build) (arm64) |

---
This works in earlier releases of Recharts (tested up to version 2.1.15) but it stopped working sometime after that.

**Comment by ckifer** [comment]
Looks like between 2.2.0 and 2.3.0 to me.

https://github.com/recharts/recharts/compare/v2.2.0...v2.3.0
A lot to compare there

**Comment by Millian-22** [comment]
@ckifer thanks for the quick response! Looking forward to the update

**Comment by ckifer** [comment]
Cool, it'll be fixed in the next patch (undetermined eta, but at least a week or so)

**Comment by ckifer** [comment]
Fixed in v2.12.7
