### ISSUE TITLE
How to inherit the css style from the parent label

### ISSUE THREAD

**Issue by cambwang** [recharts/recharts#450]
For example, the type "width" and "height" property in <PieChart> is number. 
When I use <PieChart width={400} height={400}>, it works.
But when I use <PieChart width={'100%'} height={'100%'}> or 
<PieChart width={'inherit'} height={'inherit'}>, the component does not work.
How to inherit the css style from the parent label?

**Comment by xile611** [comment]
@cambwang You can use a [`ResponsiveContainer`](http://recharts.org/#/en-US/api/ResponsiveContainer) to wrapper the chart component.
