### ISSUE TITLE
BarChart dataKeys that include brackets don't work

### ISSUE THREAD

**Issue by jenn-chan** [recharts/recharts#4503]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
DataKeys with a bracket in the name doesn't show any data (e.g. `Users [test]`). Bar's height is at 0 but chart knows that it isn't 0%. I assume there's some string parsing issue because once I remove the brackets (e.g. `Users test`), data shows up fine.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
2.1.14 but also seeing this issue with the latest version

**Comment by ckifer** [comment]
this works fine for me https://codesandbox.io/p/sandbox/simple-bar-chart-forked-z84fy4

**Comment by jenn-chan** [comment]
sorry I should have specified that the data itself is also an object. was able to reproduce here:
https://codesandbox.io/p/sandbox/simple-bar-chart-forked-hzfyyp?file=%2Fsrc%2FApp.tsx%3A8%2C17

**Comment by ckifer** [comment]
In that case you'll have to use a function to access your data instead of a string. Dot access in strings isn't supported

**Comment by jenn-chan** [comment]
ah got it thanks, that worked!
