### ISSUE TITLE
Warning about defaultProps Support in XAxis

### ISSUE THREAD

**Issue by Tchano-Py** [recharts/recharts#4508]
### Hello,

I'm currently using the Recharts library in my application and I've been receiving the following warning when using the XAxis component:

## Warning: XAxis: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

I'm using version `^2.12.7` of the Recharts library.

I would like to know if this warning is known by the Recharts development team and if there are any plans to address it in future releases of the library.

If possible, I would like to understand if there is any action I can take to resolve this warning or if there is any recommended mitigation while awaiting an official fix.

## My Code

```javascript
import { PureComponent } from 'react';
import { LineChart, Line, XAxis, Tooltip, Legend, ResponsiveContainer } from 'recharts';

export default class LineChartDashboard extends PureComponent {
  render() {
    const { data } = this.props;
    return (
      <ResponsiveContainer width="100%" height="90%">
        <LineChart
          width={500}
          height={300}
          data={data}
          margin={{
            top: 0,
            right: 0,
            left: 0,
            bottom: 0,
          }}
        >
          <XAxis dataKey="name" />
          <Tooltip />
          <Legend />
          <Line type="monotone" dataKey="Por_Ativar" stroke="#018ABE" activeDot={{ r: 8 }} />
          <Line type="monotone" dataKey="Ativas" stroke="#EDB374" />
          <Line type="monotone" dataKey="Vencidas" stroke="#ED5652" />
        </LineChart>
      </ResponsiveContainer>
    );
  }
}
```

## Error

![Captura de ecrã 2024-05-08 155353](https://github.com/recharts/recharts/assets/144934533/40be0da5-2fd3-44f2-9ae6-a0978bbc03d9)

**Comment by ckifer** [comment]
See the (very large) thread here

https://github.com/recharts/recharts/issues/3615

But yeah TLDR we know and we're working on a new major version. We won't be able to support react 19 until we fix it but it's more complicated than it seems due to some hard to refactor code in recharts. 

Going to close this as a duplicate, thanks

**Comment by ckifer** [comment]
See the thread for ideas on workarounds, there aren't any true fixes at the moment. This error shouldn't show in production though as far as I understand

**Comment by Tchano-Py** [comment]
"Great, I'll wait for future updates from the team."

**Comment by thangvaduc5** [comment]
Do you have solution for this bug. Iam waiting...

**Comment by Ilanraws100** [comment]
npm i recharts@2.13.0-alpha.3

**Comment by ckifer** [comment]
Yep, the linked duplicate issue should be resolved with the release of the latest alpha versions. Will release when R19 comes out stable
