### ISSUE TITLE
Bar Chart animation not working in Internet Explorer

### ISSUE THREAD

**Issue by AyushSharma91190** [recharts/recharts#451]
It is working fine in chrome, but not for Internet explorer 11, 

http://recharts.org/#/en-US/examples/SimpleBarChart

**Comment by AyushSharma91190** [comment]
Anyone with any solution???

**Comment by xile611** [comment]
@AyushSharma91190 IE11 don't support the transform of svg elements. So no animation in IE11.

**Comment by pschreibs85** [comment]
I don't know if this is enough of a description where they are the same issue, but I also had an issue with animations in ie11 and it was because the recharts library uses Array.prototype.find which isn't supported in ie11. The solution was to just include a polyfill in my codebase.
