### ISSUE TITLE
responsive container infers the parent div height [low priority]

### ISSUE THREAD

**Issue by MiguelG97** [recharts/recharts#4519]
[Just posting it as it's something I struggled with but everything is working fine when setting fixed height values]

It would be comfortable to set the div parent of a responsive container to take the remaining space of another div parent element:

Example: here I'm using the flex-1 short cut from tailwind to take the remaining space from the parent div. Apparently with this setup, the chart does not show up. 
```
      <div
        className="flex flex-row justify-between items-center
        flex-1 w-full"
      >
<ResponsiveContainer>...</ResponsiveContainer>
</div>
```
![image](https://github.com/recharts/recharts/assets/78984964/9285be45-4ac9-4869-9d08-b13818ac0954)

Instead I needed to explicitly type the height class name as h-[230px] in the nearest div parent to show up the chart
```
      <div
        className="flex flex-row justify-between items-center
        h-[230px] w-full"
      >
        <ResponsiveContainer
        >
         ...
        </ResponsiveContainer>
      </div>
```
![image](https://github.com/recharts/recharts/assets/78984964/c022ada3-4262-441a-af48-d88da06dc9b4)

"recharts": "^2.12.6",

[Just posting it as it's something I struggled with but everything is working fine when setting fixed height values]

**Comment by ckifer** [comment]
Hi! It's documented that the responsive container requires one of width or height to be a static value (usually height). Understood that this isn't always ideal but I don't think there's a way to make things happy otherwise. If you have any ideas feel free to mention them here or contribute!

**Comment by ckifer** [comment]
Going to closet this as this is known. Generally recommend a chart having its own wrapping div if you'd like ResponsiveContainer to take up remaining space rather than all of the space
