### ISSUE TITLE
Axis tick size calculation incorrect

### ISSUE THREAD

**Issue by BTMPL** [recharts/recharts#452]
The bounding box of the axis `tick` elements appears to be calculated not based on the custom `tick` provided to the `<XAxis />` element, resulting in either overlapping or too few labels.

Demo of the issue: http://jsfiddle.net/rgbt5ktv/

Is there a way to force recalculation of the tick size / spacing I am missing, or is this an issue?

**Comment by mustangore** [comment]
For information:
Using width properties for word wrapping (see https://github.com/recharts/recharts/pull/243) has also no effect on bouding box calculation.

It looks like the bounding box calculation is based only on text length.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
