### ISSUE TITLE
How to make hover tooltip for each individual cell instead of XAxis column

### ISSUE THREAD

**Issue by ngohuytrieu** [recharts/recharts#4529]
## Do you want to request a feature or report a bug?
Hi guys, I am new to recharts and I am using recharts in my recent web app for generating charts
I am running into one issue that can not set hover tooltip for each individual cell but XAxis column hover only

Like this example: https://recharts.org/en-US/examples
Whenever I hover to XAxios column like Page B, Page C, It will display all pv and uv values on that column. But what I want is when I hover to Page C column top dot, only show tooltip for that dot only
<img width="696" alt="image" src="https://github.com/recharts/recharts/assets/54321995/c5edfdbc-4b60-4bdc-88bf-5ea35998e31c">

## What is the current behavior?
Only show tooltip for entire XAxis column

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via codesandbox or similar (template: https://codesandbox.io/p/sandbox/simple-line-chart-v25dl4).
https://codesandbox.io/p/sandbox/line-chart-width-xaxis-padding-8v7952

## What is the expected behavior?
Can show tooltip to each individual cell

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
v2.12.7

**Comment by ckifer** [comment]
Hi, this isn't currently easily possible without some custom code and even then it might not be that reliable. 

We're working on 3.0 and hopefully this will become a really easy feature to add at that point. 

There's a few related issues that I'll link here tomorrow. I'll also try to see if I can throw something custom together that works with the current version. 

Sorry for the inconvenience!

**Comment by ngohuytrieu** [comment]
Hi @ckifer , how about clicking on the tooltip content?
I did implement my custom tooltip element, but I can't catch a click event on it because every time my cursor moves the tooltip moves

**Comment by ckifer** [comment]
Clocking on tooltip content is generally not good for accessibility reasons. Users using a keyboard cannot easily access those elements. 


But you can use the click trigger / the active flag

**Comment by ckifer** [comment]
[![Edit line-chart-width-xaxis-padding (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/line-chart-width-xaxis-padding-forked-7srgcd)

**Comment by ngohuytrieu** [comment]
Hi @ckifer,

I am trying to add box-shadow css effect to references line to my chart
<img width="157" alt="image" src="https://github.com/recharts/recharts/assets/54321995/695ef862-cde5-49af-a056-6c977021f0a3">

Is there any way for me to do it, I do try style or className attribute on ReferenceLine component but not working
```
<ReferenceLine
          yAxisId={temperatureId}
          x={2}
          stroke="white"
          className="box-shadow"
          strokeWidth={30}
          style={{
            boxShadow: "0 0.5rem 1rem rgba(0, 0, 0, 0.05)",
            border: "10 px solid red"
          }}
        />
```

**Comment by ckifer** [comment]
These components are SVGs, any styles added to them must be compatible with SVGs

**Comment by ckifer** [comment]
```
        style={{
          filter: "drop-shadow(0 0.5rem 1rem rgba(0, 0, 0, 0.05))",
          outline: "10px solid red",
        }}
```

**Comment by ckifer** [comment]
Going to close this since I think the original question was answered? Feel free to use Discussions if you have questions
