### ISSUE TITLE
Rectangles with negative heights do not apply radius

### ISSUE THREAD

**Issue by duro** [recharts/recharts#453]
I am creating a custom Bar shape and using the Rectangle component to render the bar shape. The bar chart I creating has the possibility of negative values. When I apply a radius property to the Rectangle shape renderer, it works fine for any of the bars that have positive values, but not for any that have negative values.

**Comment by duro** [comment]
Here is a JSFiddle of the issue: http://jsfiddle.net/1vq6jhbx/1/

**Comment by xile611** [comment]
Fixed in 0.20.3.

**Comment by myangsc** [comment]
@xile611  can you indicate what change you make to fix it?

**Comment by myangsc** [comment]
find it nvm, thanks https://github.com/recharts/recharts/commit/4bbed677410b51329e3fe344971d45df954557b6
