### ISSUE TITLE
BarChart onMouseLeave()'s returned object only contains isTooltipActive?

### ISSUE THREAD

**Issue by xuerion** [recharts/recharts#454]
I have an event handler function setup for onMouseLeave in BarChart. The object passed in used to contain things like "bucket" and "value", which are pretty important for functionalities that need to know which bar of the bar graph was interacted with. Now only "isTooltipActive" is provided. Did this get removed intentionally, or is it a bug, or is there a new way to access the other properties (since it used to work)? PieChart's onMouseLeave still has everything (bucket, value, stroke, innerRadis, etc).

**Comment by xile611** [comment]
@xuerion You can bind event on `Bar` instead of `BarChart`.  `onMouseLeave` bound to `BarChart` is trigged when mouse leave the box of BarChart.

**Comment by xuerion** [comment]
Thank you @xile611, that worked. I've moved the one on PieChart to the Pie component as well, and it returned the samething. Still don't know why Bar vs BarChart is different but Bar works so all good!
