### ISSUE TITLE
3.0 Bug: Brush internal state

### ISSUE THREAD

**Issue by PavelVanecek** [recharts/recharts#4546]
How to reproduce:
- Open storybook `http://localhost:6006/?path=/story/examples-linechart--with-brush` on 3.x branch
- Drag the brush handles, observe how the label ("Page A") inside the brush doesn't update - it should update
- Click outside of the chart, observe how the Brush handle jumps - it should stay where it was

Compare to 2.x behaviour:
- https://master--63da8268a0da9970db6992aa.chromatic.com/iframe.html?args=&id=examples-linechart--with-brush&viewMode=story

**Comment by ckifer** [comment]
3.x link to compare to
https://63da8268a0da9970db6992aa-cfehtsenpg.chromatic.com/?path=/story/examples-linechart--with-brush

Still broke
