### ISSUE TITLE
Refactor getComposedData

### ISSUE THREAD

**Issue by PavelVanecek** [recharts/recharts#4550]
Each graphical item component (Area, Bar, Pie, and the like) expose a static function `getComposedData`. This is later called in `generateCategoricalChart`. This works fine but it has two problems:
1. Because each component requires different data, this solution does not allow strong typing in `generateCategoricalChart` state
2. This relies on direct DOM access and blocks #2788

Refactor to something else. Perhaps each graphical component can read the required dependencies from Redux and then call its own `getComposedData`?

**Comment by ckifer** [comment]
Think we can close this one 🎉
