### ISSUE TITLE
Think about using fixed deps versions to avoid upstream updates that break things

### ISSUE THREAD

**Issue by emmenko** [recharts/recharts#457]
At the moment all deps use `^` as version range. While this is good for getting upstream changes for free, sometimes it breaks because of that.

Latest example: https://github.com/recharts/react-smooth/issues/9

I think it might be worth considering removing version ranges wherever possible to avoid such problems, specially if broken versions are released by mistake or simply because people don't properly follow semver versioning.

Thanks ;)

**Comment by germanattanasio** [comment]
In the meantime you can do

```
npm shrinkwrap
```

And change the react-smooth version to be 0.1.17

```
"react-smooth": {
  "version": "0.1.17",
  "from": "react-smooth@>=0.1.15 <0.2.0",
  "resolved": "https://registry.npmjs.org/react-smooth/-/react-smooth-0.1.17.tgz"
}
```
