### ISSUE TITLE
BarChart not rendering inside ResponsiveContainer

### ISSUE THREAD

**Issue by masterjanic** [recharts/recharts#4586]
Might be related to #4558 

## What is the current behavior?

When wrapping the BarChart inside a ResponsiveContainer and a parent element with defined height, the BarChart is not shown.

timeseries-chart.tsx

```
    <ResponsiveContainer width="100%" height="100%">
      <BarChart
        data={[
          { date: "1", count: 1 },
          { date: "2", count: 10 },
          { date: "3", count: 20 },
        ]}
      >
        <Bar dataKey="count" className="fill-primary" minPointSize={1} />
      </BarChart>
    </ResponsiveContainer>
```

timeseries.tsx

```
      <CardContent className="h-[200px]">
          <TimeseriesChart />
      </CardContent>
```

## What is the expected behavior?

The BarChart component is expected to be shown. It is only showing when having a defined width and height and not wrapped inside a ResponsiveContainer.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Not working with both react compiler enabled and disabled.

`    
"react": "19.0.0-rc-4c2e457c7c-20240522",
"react-dom": "19.0.0-rc-4c2e457c7c-20240522",
"next": "14.3.0-canary.80",
"recharts": "^2.13.0-alpha.1",
`

**Comment by ckifer** [comment]
This should also be the case pre-react 19

Something needs to have a static height. Either the container the chart is in, or a container above it. Else it doesn't know how to give the SVG child a height because there is none to give.

**Comment by masterjanic** [comment]
Hey @ckifer, I know thats why I added the height of 200px to the above container. Here is an image from my site that shows that the bar chart has the correct height, but is not rendering:

![image](https://github.com/recharts/recharts/assets/68118279/081a5aae-682f-4a87-b251-a56e0d4e5bc3)

**Comment by ckifer** [comment]
Do you have react-is@19 installed?

**Comment by masterjanic** [comment]
Yes I do, I have tested it with and without react-is@19.

Here is my complete package.json

{
  "dependencies": {
    "@auth/drizzle-adapter": "^1.1.0",
    "@hookform/resolvers": "^3.4.2",
    "@paralleldrive/cuid2": "^2.2.2",
    "@radix-ui/react-dialog": "^1.0.5",
    "@radix-ui/react-icons": "^1.3.0",
    "@radix-ui/react-label": "^2.0.2",
    "@radix-ui/react-navigation-menu": "^1.1.4",
    "@radix-ui/react-separator": "^1.0.3",
    "@radix-ui/react-slot": "^1.0.2",
    "@radix-ui/react-toast": "^1.1.5",
    "@react-email/components": "^0.0.19",
    "@react-email/render": "^0.0.15",
    "@simplewebauthn/browser": "9.0.1",
    "@simplewebauthn/server": "9.0.3",
    "@t3-oss/env-nextjs": "^0.10.1",
    "@tanstack/react-query": "^5.37.1",
    "@trpc/client": "11.0.0-rc.374",
    "@trpc/react-query": "11.0.0-rc.374",
    "@trpc/server": "11.0.0-rc.374",
    "babel-plugin-react-compiler": "0.0.0-experimental-592953e-20240517",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.1",
    "drizzle-orm": "^0.30.10",
    "fakefilter": "^0.1.847",
    "lucide-react": "^0.379.0",
    "next": "14.3.0-canary.80",
    "next-auth": "^5.0.0-beta.18",
    "postgres": "^3.4.4",
    "react": "19.0.0-rc-4c2e457c7c-20240522",
    "react-dom": "19.0.0-rc-4c2e457c7c-20240522",
    "react-email": "^2.1.4",
    "react-hook-form": "^7.51.5",
    "react-is": "^19.0.0-rc-f994737d14-20240522",
    "recharts": "^2.13.0-alpha.1",
    "server-only": "^0.0.1",
    "sharp": "^0.33.4",
    "sonner": "^1.4.41",
    "superjson": "^2.2.1",
    "tailwind-merge": "^2.3.0",
    "zod": "^3.23.8"
  },
  "devDependencies": {
    "@ianvs/prettier-plugin-sort-imports": "^4.2.1",
    "@tailwindcss/typography": "^0.5.13",
    "@types/eslint": "^8.56.10",
    "@types/node": "^20.12.12",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "@typescript-eslint/eslint-plugin": "^7.10.0",
    "@typescript-eslint/parser": "^7.10.0",
    "drizzle-kit": "^0.21.4",
    "eslint": "8.57.0",
    "eslint-config-next": "^14.2.3",
    "eslint-plugin-drizzle": "^0.2.3",
    "pg": "^8.11.5",
    "postcss": "^8.4.38",
    "prettier": "^3.2.5",
    "prettier-plugin-tailwindcss": "^0.5.14",
    "schema-dts": "^1.1.2",
    "tailwind-scrollbar": "^3.1.0",
    "tailwindcss": "^3.4.3",
    "tailwindcss-animate": "^1.0.7",
    "typescript": "^5.4.5"
  },
  "packageManager": "pnpm@9.1.2"
}

**Comment by ckifer** [comment]
I don't think this is react 19 specific. Use onResize of the responsive container and log what is in the height and width that get returned. See if it has value

**Comment by masterjanic** [comment]
![image](https://github.com/recharts/recharts/assets/68118279/9e297ffa-15fc-4f77-a995-4e8d26bb5186)

I have added an onResize listener to the container and the Bar itself. Only the container resize gets called. But the values seem to be correct.

**Comment by ckifer** [comment]
I can reproduce now. Will look into it

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/blob/3.x/src/component/ResponsiveContainer.tsx#L165

This no longer evaluates to true in R19, not sure why. @eps1lon any ideas?

**Comment by ckifer** [comment]
@masterjanic try recharts@2.13.0-alpha.2

**Comment by masterjanic** [comment]
@ckifer I am still getting the same results. The chart is not rendering at all

**Comment by ckifer** [comment]
Wild, it was working locally 😅. Thanks for checking!

Now this `isElement` isn't working https://github.com/recharts/recharts/blob/master/src/component/ResponsiveContainer.tsx#L177

**Comment by ckifer** [comment]
In React 18

```
child.$$typeof -> Symbol("react.element") 
```

React 19
```
child.$$typeof -> Symbol("react.transitional.element") 
```
🤔

**Comment by ckifer** [comment]
https://github.com/facebook/react/pull/28813

**Comment by ckifer** [comment]
@masterjanic run `npm ls react-is` (or however you do the same in pnpm) - you'll realize that react-is needs to be overridden everywhere. So I had to do and now its working

```
  "overrides": {
    "react-is": "^19.0.0-beta-26f2496093-20240514"
  }
```

**Comment by masterjanic** [comment]
Perfect, thank you 🙏

For pnpm it is:

```
  ...
  "pnpm": {
    "overrides": {
      "react-is": "19.0.0-beta-26f2496093-20240514"
    }
  },
```

This one was driving me crazy!

**Comment by eps1lon** [comment]
> This no longer evaluates to true in R19, not sure why. @eps1lon any ideas?

This is why I [moved `react-is` to a peer dependency](https://github.com/recharts/recharts/pull/4541). The version of `react-is` needs to match the version of React.

**Comment by izakfilmalter** [comment]
I am running into this issue even with overriding `react-is`.
![CleanShot 2024-06-14 at 11 02 04](https://github.com/recharts/recharts/assets/5874330/4ac6ce26-b6dc-4993-a4e0-78fdbd094e4a)
![CleanShot 2024-06-14 at 11 04 24](https://github.com/recharts/recharts/assets/5874330/bc719e47-09c1-4b51-9358-df4b111805ec)
Looks like `y="NaN"` is the issue

**Comment by izakfilmalter** [comment]
Nvm, this was an issue with Tremor: https://github.com/tremorlabs/tremor/pull/1075
