### ISSUE TITLE
Ehancement: Step Line

### ISSUE THREAD

**Issue by cemremengu** [recharts/recharts#460]
As can be seen [here](http://www.highcharts.com/stock/demo/step-line)

It would be great when showing binary values.

**Comment by cemremengu** [comment]
Already supported with `stepBefore` and `stepAfter` curve options: http://recharts.org/#/en-US/api/Curve

**Comment by ELI7VH** [comment]
Hi @cemremengu, how do we implement this? The link on recharts is not working :(
