### ISSUE TITLE
<Brush/> ariaLabel not showing

### ISSUE THREAD

**Issue by anshika1422** [recharts/recharts#4604]
Hi Team , 
We have a <Brush/> component in our application.
We wanted to update the ariaLabel property to improve accessibility but the property is not showing up .
here is the code 
`  <Brush
                    dataKey="index"
                    ariaLabel={`Min Value: ${
                      props.xaxis.dataGranularity === "week"
                        ? "week" +
                          data.kpiData[brushValues.start].week +
                          "year" +
                          data.kpiData[brushValues.start].year
                        : Utils.dateFormatter(
                            data.kpiData[brushValues.end].demandStartDateTime
                          )
                    } Max Value: ${
                      props.xaxis.dataGranularity === "week"
                        ? "week" +
                          data.kpiData[brushValues.start].week +
                          "year" +
                          data.kpiData[brushValues.start].year
                        : Utils.dateFormatter(
                            data.kpiData[brushValues.end].demandStartDateTime
                          )
                    }`}
                    startIndex={brushValues.start}
                    endIndex={brushValues.end}
                    x={92}
                    y={props.dimension.height - 77}
                    height={brushHeight}
                    width={
                      legendVisibility
                        ? 0.8 * props.dimension.width - 180
                        : props.dimension.width - 180
                    }
                    stroke="#556B82"
                    onChange={(data) => {
                      setBrushValues({
                        start: data.startIndex,
                        end: data.endIndex,
                      });
                    }}
                    tickFormatter={formatTickForBrush}
                  />`
                  
  versions:
 "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "recharts": "2.5.0"

**Comment by ckifer** [comment]
Hi! You'll need to update recharts to be closer to the latest. I know in recent versions this is possible

**Comment by ckifer** [comment]
Support for this was added in 2.10.2

https://github.com/recharts/recharts/releases/tag/v2.10.2

Going to close this
