### ISSUE TITLE
Enhancement: Area Range

### ISSUE THREAD

**Issue by cemremengu** [recharts/recharts#461]
As can be seen [here](http://www.highcharts.com/demo/arearange-line)

Very good when showing how the line approaches the boundaries.

And also, thanks everyone for absolutely amazing work and dedication! :heart: 

I have looked into many charting libs for react but none of them comes close to recharts

**Comment by Eric24** [comment]
I believe this is a dup of #316

**Comment by cemremengu** [comment]
Yes, it looks like it @Eric24 . Closing to continue discussion there
