### ISSUE TITLE
Chart disappears when trying to get a bar chart with logarithmic yAxis

### ISSUE THREAD

**Issue by pioneer32** [recharts/recharts#462]
It's easy to reproduce. I've just tried to use link to JSFiddle on demo page http://jsfiddle.net/kca9npkg/6/?utm_source=website&utm_medium=embed&utm_campaign=kca9npkg
 
Then I added YAxis prop "scale", so the chart is visible when scale="auto" is shown, when I set any other value, e.g. scale="log", the chart disappears.

The question is what I should do to have a bar chart with logarithmic yAxis? or that's a bug?

Any information would be much appreciated! Cheers!

**Comment by xile611** [comment]
@pioneer32 

When the bars are stacked, the minimum value of domain is 0 by default. But log(0)  is invalidate, so the bars disappear.

You should set the `domain` of `YAxis` like the following:

```jsx
<YAxis scale="log" domain={[0.01, 'auto']} allowDataOverflow />
```

[demo](http://jsfiddle.net/kca9npkg/117/)

**Comment by pioneer32** [comment]
Thank you for the reply. I've just had a quick look at http://jsfiddle.net/kca9npkg/117/ and it doesn't seem to be working properly. uv bars aren't visible and pv bars stick to the top of the chart.

**Comment by saurabh-sharma** [comment]
This issue doesn't seems to be fixed. `scale="log"` doesn't work for stacked charts.

**Comment by GiovanniGiampaolo** [comment]
> @pioneer32
> 
> When the bars are stacked, the minimum value of domain is 0 by default. But log(0) is invalidate, so the bars disappear.
> 
> You should set the `domain` of `YAxis` like the following:
> 
> ```js-jsx
> <YAxis scale="log" domain={[0.01, 'auto']} allowDataOverflow />
> ```
> 
> [demo](http://jsfiddle.net/kca9npkg/117/)

Thanks a lot you helped me!
