### ISSUE TITLE
Change X-Axis and Y-Axis colors ?

### ISSUE THREAD

**Issue by cemremengu** [recharts/recharts#463]
Is there a way to change the x and y axes colors to something else ?

**Comment by cemremengu** [comment]
I will ask about it in chart but if anyone has answers, feel free to post it here. Thanks!

**Comment by ospfranco** [comment]
@cemremengu Would you mind sharing how did you solved this?

**Comment by cemremengu** [comment]
@ospfranco  You can just set stroke="white" on the axis components. (#548)

Example:

```
<XAxis dataKey="name" stroke="red"/>
<YAxis stroke="blue"/>
```

**Comment by MiLeung** [comment]
I don't even know why this isn't even in the docs...

**Comment by dkulakowska** [comment]
hi, how would I go about changing the Xaxis line colour? when I set it to e.g. stroke='red' it changes the  Xaxis labels colors, not the line itself. 

<img width="1107" alt="screen shot 2018-09-28 at 09 50 08" src="https://user-images.githubusercontent.com/31188583/46195335-5cdbe300-c304-11e8-9cdb-eccd8b1706bf.png">

**Comment by dkulakowska** [comment]
hi, I'm setting stroke='red' to Xaxis, but it's only changing the labels color, the Xaxis line is unchanged. When I set stroke='blue' on Yaxis, it changes both the line and the labels color.

Any idea how I can add a color to Xaxis line and Yaxis line only?? 

My code: 
```
<XAxis dataKey='name' scale='point' tickLine={false} stroke='red' />
<YAxis tickLine={false} unit=' €' stroke='blue' />
```


<img width="320" alt="screen shot 2018-09-28 at 09 56 14" src="https://user-images.githubusercontent.com/31188583/46195513-d5db3a80-c304-11e8-8716-909a3d3d8fb4.png">

**Comment by pulgaroja** [comment]
Just in case anyone is looking for a way to change just the axis line color and not the label(text) color as well:

```
<XAxis axisLine={{ stroke: '#EAF0F4' }} />
<YAxis axisLine={{ stroke: '#EAF0F4' }} />
```

**Comment by coreybyrum7** [comment]
Any way to change a particular tick's stroke color? Similar to changing a bar's stroke/fill using the <Cell /> component..

**Comment by sarahbanashek** [comment]
> Any way to change a particular tick's stroke color? Similar to changing a bar's stroke/fill using the component..

Pretty much the same way you change the axis color:
`<XAxis tickLine={{ stroke: '#EAF0F4' }} />

**Comment by sarahbanashek** [comment]
> Any way to change a particular tick's stroke color? Similar to changing a bar's stroke/fill using the component..

Pretty much the same way you change the axis color:
`<XAxis tickLine={{ stroke: '#EAF0F4' }} />`

**Comment by akashshyamdev** [comment]
For those who are trying to change the color of the label, I found this is useful:

```
<XAxis label={{ fill: "red" }} />
```

**Comment by alexpeev9** [comment]
For me those solutions didn't work, since I am using the Chakra UI extension of this dependency. I made it to work with custom css style.
```
.recharts-cartesian-axis-tick text tspan": {
            stroke: "green !important",
            strokeWidth: 0.5,
            fontWeight: 300,
}
```
