### ISSUE TITLE
How to export charts ?

### ISSUE THREAD

**Issue by cemremengu** [recharts/recharts#464]
Is there a way to export/download the charts currently ? Or any known way to implement it if it does not exist ?

**Comment by arcthur** [comment]
recommend use npm and webpack to import or export charts.

**Comment by JoshMoreno** [comment]
>recommend use npm and webpack to import or export charts.

Can you please elaborate @arcthur ? 

I need to export charts clientside. ie. Save as image or pdf.

**Comment by Chris-Petty** [comment]
This should definitely be open - is there any built in methods in recharts that supports client side downloading of a rendered rechart in any format? Say SVG, PNG, JPG, XLS, PDF...

**Comment by HunterEl** [comment]
@Chris-Petty I definitely agree with you, I see an open issue https://github.com/recharts/recharts/issues/1027 in which we should ask for more clarification or a path to add this as a feature.

**Comment by khwaja-abdul-ahad** [comment]
use **react-csv**, it takes the data in your graph and downloads it into a csv file.

You just need to import **CSVLink** from it and provide it the same data you have on your graph.

`<CSVLink data={graphData}>Export to CSV</CSVLink>`

**Comment by khwaja-abdul-ahad** [comment]
use **react-csv**, it takes the data in your graph and downloads it into a csv file.

You just need to import **CSVLink** from it and provide it with the same data you have on your graph.

`<CSVLink data={graphData}>Export to CSV</CSVLink>`
