### ISSUE TITLE
ScatterChart does not expose activePayload in onMouseMove events like other charts do. Required for a very customized tooltip. 

### ISSUE THREAD

**Issue by ArthurRuxton-DY** [recharts/recharts#4644]
## Do you want to request a feature or report a bug?
Request a feature

## What is the current behavior?
onMouseMove(e) for other charts (BarChart, AreaChart) etc includes 'activePayload' which is useful for building CustomTooltips with 'active' behaviour that is not dictated by recharts. ScatterChart onMouseMove doesn't include activePayload, making it very difficult if not impossible to get the tooltip payload for my bespoke Tooltip (which I built to avoid the 'active' restrictions built into the recharts tooltip even when passing a custom compoent as its content prop). 

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via codesandbox or similar (template: https://codesandbox.io/p/sandbox/simple-line-chart-v25dl4).
I believe this is a missing feature rather than a bug. 

## What is the expected behavior?
I would expect ScatterChart onMouseMove events to include activePayload as other charts  (Line, Area, Bar etc) do. 

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
I'm on recharts 2.7.2

**Comment by ckifer** [comment]
Hi! Can you try upgrading to the latest first?

There was definitely some effort to align the activeShape interface across all charts. It may not solve this particular issue but it might help something else in your set up.

**Comment by ArthurRuxton-DY** [comment]
Hi @ckifer thanks for getting back to me. It's the same in the latest version, the ScatterChart onMouseMove event gives: { chartX, chartY, xValue, yValue }   whereas other charts (Bar, Area, Line etc) has this shape: { chartX: 624, chartY: 85, activeTooltipIndex: 3, activeLabel: 3, activePayload: (24) […], activeCoordinate: {…} }. 

I think the activePayload exposed by other charts must be created under the hood by transforming the data object closest the cursor; mapping the object keys into an array with one item per key:value (one per <Line /> || <Bar/> etc)

Please correct me if I'm completely missing the point. 

Thank you

**Comment by ckifer** [comment]
This is correct because Scatter can't reliably use indices since the points are, well, scattered. 

Can you give more details on what values you actually need/what you are trying to do? You can use activeShape to change what is shown on hover and the x and y values are provided in the event.

**Comment by ckifer** [comment]
Going to close this as stale due to no response
