### ISSUE TITLE
Tooltips for TreeMap doesn't have label

### ISSUE THREAD

**Issue by hugo-levet** [recharts/recharts#4648]
## Do you want to request a feature or report a bug?

Bug report

## What is the current behavior?

When I use Tooltips on a TreeMap, Tooltips doesn't show label
![image](https://github.com/recharts/recharts/assets/49909831/44602fd3-e329-468f-86f0-db13e2b28fa4)
```tsx
<ResponsiveContainer width="100%" height="100%">
    <Treemap
        width={400}
        height={200}
        data={data}
    >
        <Tooltip />
    </Treemap>
</ResponsiveContainer>
```

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

[See the bug in CodeSandbox](https://codesandbox.io/p/sandbox/simple-line-chart-forked-k9nwzd?file=%2Fsrc%2FApp.tsx)

### Steps
1. Go to the CodeSandbox
2. hover over an item on the displayed chart

## What is the expected behavior?

The label should appear before the ":"

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Reschart 2.12.6 and chrome modern version

**Comment by ckifer** [comment]
Hi! 

https://codesandbox.io/p/sandbox/simple-line-chart-forked-k9nwzd?file=%2Fsrc%2FApp.tsx

TreeMap has a `nameKey` prop which allows you to set a label with an arbitrary key in your data

This should exist in the website docs but does not, tagging this as needs documentation

**Comment by ckifer** [comment]
Thanks foot contributing!

**Comment by ckifer** [comment]
For* lol
