### ISSUE TITLE
Q: What is the 'amt' property being used in all example data sets ?

### ISSUE THREAD

**Issue by cemremengu** [recharts/recharts#467]
The data sets have a property called `amt` which I couldn't find any info about. It looks like a value point but not shown on charts:

`{name: 'Page G', uv: 3490, pv: 4300, amt: 2100},`

What exactly is it for ? Is it something special ?

**Comment by evilucifero** [comment]
Aha, nothing special :-)

 'amt' is abbr. of word 'amount'. You can definite any property name you like.

**Comment by corinnebrady** [comment]
@evilucifero 

On the example that @cemremengu is referencing, `amt` is no shown on the chart.  The data comes from the Stacked Bar Chart example http://recharts.org/#/en-US/examples/StackedBarChart

The bar shows displays that `uv` is `3490` and that `pv` is `4300`, but where is `amt` shown? Is it suppose to be a third stack? Is it another data point that is needed but isn't shown?

Basically, where is `amt` on the example chat? And is it necessary to product the chart?

**Comment by cemremengu** [comment]
@corinnebrady it's not something necessary/required. It is another data point but in the example they did not add something like

```
<Bar dataKey="amt" stackId="a" fill="#ff0000" />
```

so that's why it is not shown as a third stack. Nothing to worry about :)

**Comment by dagumak** [comment]
@cemremengu  Thanks for clearing that up. That was really confusing.

**Comment by giorgi-m** [comment]
@dagumak Yep, it is confusing, I agree.

**Comment by dmdque** [comment]
Super confusing. I also thought `uv` and `pv` had to be named as such.

**Comment by colshacol** [comment]
I had these same questions.

uv, pv, and amount seem like required properties. And amt is never referenced anywhere in the example code, so it seems like it is something that recharts needs underneath.

**Comment by AlexanderKolomiytsev** [comment]
> Super confusing. I also thought `uv` and `pv` had to be named as such.

**Comment by Diercohen** [comment]
It's so simple...
`amt` = **am**oun**t**
`pv` = **P**age**V**iew
`uv` = **U**nique**V**isitor

**Comment by Alex-Anev** [comment]
> It's so simple...
> `amt` = **am**oun**t**
> `pv` = **P**age**V**iew
> `uv` = **U**nique**V**isitor

Yeah but what do all those things mean. What is 'page view' and what do I need it for.

**Comment by lumenwrites** [comment]
I pretty much guessed that uv and pv can be arbitrary names, but was also super confused by amt. No way I would've guessed it if not for finding this thread.

I think docs should definitely be clearer on that - remove amt, and rename uv and pv to something more obvious and descriptive.

Incredible library by the way, I'm so happy I found it, thank you SO much for such a great project!

**Comment by fhrryDeveloper** [comment]
Can I remove amt in data?

**Comment by benobab** [comment]
@fhrryDeveloper yep you can (try it there : https://codesandbox.io/s/simple-bar-chart-forked-ed9urk?file=/src/App.tsx )

The doc should definitely be updated since amt seems really confusing for everyone and is useless for the examples.

**Comment by fhrryDeveloper** [comment]
Thanks for your response.
I have one more question related to recharts.
There is loading screen option until graph datas loading?

**Comment by benobab** [comment]
@fhrryDeveloper 

I don't see any on the documentation, but I can be wrong.
I don't think the library should handle the loading state, you should. And load all the charts once your data is ready.
It's a good practice to have a nice placeholder (fake data, an image or a small gif) while you load your data.

**Comment by LovaSalema** [comment]
I removed it
