### ISSUE TITLE
ClipDot doesn't work in the latest version

### ISSUE THREAD

**Issue by anasmi** [recharts/recharts#4671]
## Do you want to request a feature or report a bug?
Bug report

## What is the current behavior?
`clipDot:false` doesn't prevent a dot cut off when allowDataOverflow is set for Y axis (dots on xAxis are cut off)
(updating property value doesn't have any effect). Also, example ins storybook for the feature doesn't seem to work either (there dots are not shown in full on yAxis)
Original fix was introduced here https://github.com/recharts/recharts/commit/91801b1386698be4522ca5077455f3b812c99f95#diff-1dee178d6dc13ab8722aca748856acfb8062f660e9c1fe17edda38f8e5953168
## Code to reproduce : 

```
import React from "react";
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
  Line,
  LineChart
} from "recharts";

const data = [
  {
    name: "Page A",
    uv: 4000,
    pv: 2400,
    amt: 2400
  },
  {
    name: "Page B",
    uv: 3000,
    pv: 1398,
    amt: 2210
  },
  {
    name: "Page C",
    uv: 2000,
    pv: 9800,
    amt: 2290
  },
  {
    name: "Page D",
    uv: 0,
    pv: 3908,
    amt: 2000
  },
  {
    name: "Page E",
    uv: 1890,
    pv: 0,
    amt: 2181
  },
  {
    name: "Page F",
    uv: 0,
    pv: 3800,
    amt: 2500
  },
  {
    name: "Page G",
    uv: 3490,
    pv: 4300,
    amt: 2100
  }
];

const SimpleLineChart = () => (
  <LineChart
    width={600}
    height={300}
    data={data}
    margin={{
      top: 5,
      right: 30,
      left: 20,
      bottom: 5
    }}
  >
    <CartesianGrid strokeDasharray="3 3" />
    <XAxis dataKey="name" />
    <YAxis domain={[0, 7500]} allowDataOverflow />
    <Tooltip />
    <Legend />
    <Line
      type="monotone"
      dataKey="pv"
      stroke="#8884d8"
      dot={{clipDot:false}}
    />
    <Line type="monotone" dataKey="uv" stroke="#82ca9d" 
      dot={{clipDot:false}}/>
  </LineChart>
);

export default function App() {
  return <SimpleLineChart />;
}

```
![dots_cut_off](https://github.com/recharts/recharts/assets/15248706/e93d6b23-e085-4a25-be02-2969b7ff75b6)

## What is the expected behavior?
`clipDot:false` preserves dots on xAxis
> 
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
latest affected, doesn't work in earliest either. Chrome browser

**Comment by ckifer** [comment]
Do you have a version that you know it was working as expected in?

**Comment by ckifer** [comment]
Looks like this only worked for a brief time (on the X axis at least). It was fixed in 2.7.1 but broke in 2.8 🙃

**Comment by ckifer** [comment]
lol it seems I broke it in the next patch with https://github.com/recharts/recharts/pull/3637/files

https://codesandbox.io/p/sandbox/line-chart-width-xaxis-padding-forked-2jjwxk

My typeguard made some incorrect assumptions. You can re-add these props to your dot to get this to work in newer versions until a fix comes out 
     `dot={{ clipDot: false, r: 10, cx: 0, cy: 0 }}`

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/pull/4674

**Comment by anasmi** [comment]
@ckifer apologies for the late reply! I just want to express my gratitude for the workaround and quick fix for the issue. <3 Thank you very much for your work and support!
P.S To tackle this locally I had created a custom hook to recalculate the clipPath that was not always working and now I can drop it. Thanks again :)

**Comment by ckifer** [comment]
Sure thing, this will be fixed in the next release. 

Was holding off on that until React 19 comes out though.. for now looks like the workaround should allow you to avoid custom work

**Comment by anasmi** [comment]
@ckifer yes, it does. Works like a charm. Thanks again :)

**Comment by ckifer** [comment]
Cool, I'm going to close this for now since it's resolved in the code but I'll comment back here when it's included in a release. 

Thanks!

**Comment by ckifer** [comment]
released in alpha https://www.npmjs.com/package/recharts/v/2.13.0-alpha.5
