### ISSUE TITLE
How do I color the background on a <Label/>?

### ISSUE THREAD

**Issue by dnjsgur0629** [recharts/recharts#4679]
I would like to color the background of the Label for better visibility. 
Like this:
![image](https://github.com/recharts/recharts/assets/65391273/e4e2b6d2-d8f4-4bc5-9f7c-57fac6195f28)
I thought I would have to use the content prop because the Label without the content prop is a wrapper for <text/>, but when I tried to use the content, the Label disappeared.

When not using the content prop:
![image](https://github.com/recharts/recharts/assets/65391273/e78fc95d-7c86-4812-aee1-a81b335fa679)

When using the content prop:
![image](https://github.com/recharts/recharts/assets/65391273/035cc33c-6142-46a7-a508-ebac1542535c)

```jsx
<ReferenceLine
  yAxisId={leftKey}
  y={lastY}
  stroke="#fff"
  strokeWidth={2}
  isFront={true}
  ifOverflow={'extendDomain'}
>
  <Label
    style={{ fill: 'white' }}
    value={lastY}
    position={'left'}
    fontSize={11}
    fontWeight={700}
    formatter={formatNumber}
    content={<div style={{ backgroundColor: 'red' }}>{formatNumber(lastY)}</div>}
  />
</ReferenceLine>
```

**Comment by jjjrmy** [comment]
Just leaving this here - I was able to accomplish something similar: https://gaurav5430.medium.com/exploring-recharts-using-foreignobject-to-render-custom-html-5c6b75d6207e
