### ISSUE TITLE
Bug with stackOffset="expand"

### ISSUE THREAD

**Issue by vaeum** [recharts/recharts#468]
Recharts v0.20.5

Hello, bug not resolve ((

Please, check
http://jsfiddle.net/vaeum/dmeaodhc/4/

**Comment by xile611** [comment]
@vaeum Which bug ?

**Comment by vaeum** [comment]
Hello, @xile611 a thing BarChart thith stackOffset="expand", should be

![img-2017-02-13-16-58-45](https://cloud.githubusercontent.com/assets/6481202/22886157/b7c01cd8-f20d-11e6-9185-6eec2c3f7460.png)
