### ISSUE TITLE
Using deprecated "defaultProps" and React throws error when using with 18.3.1

### ISSUE THREAD

**Issue by jurosh** [recharts/recharts#4686]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?

Recharts is using deprecated "defaultProps" and React `18.3.1` throws error.

```
chunk-YLIFYLWR.js:7410 Warning: YAxis: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
  at YAxis2 (/node_modules/.vite/deps/recharts.js?v=fd96cf71:27145:22)
    at svg
    at Surface (/node_modules/.vite/deps/recharts.js?v=fd96cf71:5068:24)
    at div
    at ChartLayoutContextProvider2 (/node_modules/.vite/deps/recharts.js?v=fd96cf71:23647:28)
    at CategoricalChartWrapper (/node_modules/.vite/deps/recharts.js?v=fd96cf71:28361:7)
    at div
```

It's saying that it's WARNING but in reality it's reported by React as as `console.error` so it clutters console a lot.

## Codesandbox

https://codesandbox.io/p/sandbox/simple-line-chart-forked-zqr6t4?file=%2Fpackage.json

## What is the expected behavior?

Do not use deprecated property to prevent warnings in console.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

```
"react": "^18.3.1",
"recharts": "^2.12.7",
```
It worked with previous version of React - had no warning.

Seems like it's something what could be in works for React19 https://github.com/recharts/recharts/issues/4558 but reporting this separately as it's affecting current v18 version.

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/issues/3615#issuecomment-2135955727

This is taken care of. Please upgrade to the latest alpha version (or wait until 2.13 is released). Thanks!
