### ISSUE TITLE
How can I do the stroke thicker?

### ISSUE THREAD

**Issue by BrunoQuaresma** [recharts/recharts#469]

**Comment by evilucifero** [comment]
Can you provide any code or case? Usually, you can just set props to Recharts components as svg component. ex. `<Line strokeWidth={2} />`

**Comment by BrunoQuaresma** [comment]
This not work for area charts 😞

**Comment by evilucifero** [comment]
It should works fine in AreaChart.
Maybe you can try to pass a prop `strokeWidth` to Area component like `<Area strokeWidth={10} />`.

**Comment by evilucifero** [comment]
If still not work, would you like to show me your code? I'll help you figure out it.

**Comment by BrunoQuaresma** [comment]
It works. Sorry.

**Comment by simpsons310** [comment]
> It should works fine in AreaChart.
> Maybe you can try to pass a prop `strokeWidth` to Area component like `<Area strokeWidth={10} />`.

Hi, I tried your code and it worked, but i couldn't find it in [api document](http://recharts.org/en-US/api/Area). I think it should be updated. :D

**Comment by its-kayes** [comment]
> If still not work, would you like to show me your code? I'll help you figure out it.I

> Can you provide any code or case? Usually, you can just set props to Recharts components as svg component. ex. `<Line strokeWidth={2} />`

It works for me. Many Many thanks!
