### ISSUE TITLE
YAxis: Support for defaultProps will be removed from function components in a future major release.

### ISSUE THREAD

**Issue by eltmon** [recharts/recharts#4691]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
On loading console generates:
YAxis: Support for defaultProps will be removed from function components in a future major release.

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/issues/3615#issuecomment-2135955727

This is taken care of. Please upgrade to the latest alpha version (or wait until 2.13 is released). Thanks!

**Comment by eltmon** [comment]
Thank you!
