### ISSUE TITLE
Scrollable charts with fixed y-axis

### ISSUE THREAD

**Issue by saurabhraj123** [recharts/recharts#4692]
## Do you want to request a feature or report a bug?
Yes
## What is the current behavior?
We can make the charts scrollable by making the outer div having a fixed width..but then the entire chart scrolls, even the y-axis.. Also, the position of legends and all is not appropriate.
## What is the expected behavior?
When I scroll y-axis should not scroll. I don't know why no one is working on it, it is such a necessity. Anyone who wants to pick it up, I am open to discussions.

**Comment by PavelVanecek** [comment]
Thank you for your thoughtful comment @saurabhraj123. This project is run by volunteers and we welcome new contributors! We're open to pull requests and we're looking forward to working with you :)

**Comment by ckifer** [comment]
closing this as a duplicate of https://github.com/recharts/recharts/issues/1761
