### ISSUE TITLE
Area printing a dot when having only one point

### ISSUE THREAD

**Issue by nfroidure** [recharts/recharts#4697]
We have charts with an Area showing min/max values that looks like this:
![Screenshot from 2024-06-25 11-24-45](https://github.com/recharts/recharts/assets/229633/2975474f-68e3-4020-b40e-f95309cfabcd)

But due to the following condition:
https://github.com/recharts/recharts/blob/bfd179194d77d6a46ba265681e9cad705ee56921/src/cartesian/Area.tsx#L669

Instead of just not print anything when there is only one point, it prints a dot:
![Screenshot from 2024-06-25 11-24-24](https://github.com/recharts/recharts/assets/229633/c7c4b839-4a19-4b55-969b-34a09c8371ab)

It feels strange for our users since it looks like there is a max value but no min one which is wrong.

The condition seems introduced in this commit but it is very old and I'm not confident in saying what it does and if it is safe to juste remove the condition to avoid this problem:
https://github.com/recharts/recharts/commit/ab452bcbc77b75ea76632a2a293abd98dcfba98c

I can create a PR for its removal if you think it is safe to or maybe add a prop named `noSingleDotFallback` to avoid this behavior in cases like mine.

**Comment by ckifer** [comment]
You can just use dot={false} conditionally. 

We've had issues cut with users confused as to why nothing is rendered with a single data point. So a single dot is rendered so something is rendered.

Other libraries and charting solutions do this by default as well. I don't think it's going to be something we'll want to change the default on

**Comment by nfroidure** [comment]
It works with:
```js
                dot={() => {
                  return null;
                }}
```

**Comment by ckifer** [comment]
ah right. If you don't want any dots at all that will work. If you wanted a dot when there is more than one datapoint then what I had will work

**Comment by ckifer** [comment]
I'm going to close this since the API change isn't super ideal, if we get more requests we can revisit.

Returning null from a custom `dot` solution is the current answer for anyone looking at this issue in the future

```
                dot={() => {
                  return null;
                }}
```
