### ISSUE TITLE
Areas in stacked Area Chart overlap

### ISSUE THREAD

**Issue by BastienGenin** [recharts/recharts#4698]
## Do you want to request a feature or report a bug?
Yes

## What is the current behavior?
Areas overlap in a stacked area chart when dataKey values strongly differs.
![image](https://github.com/recharts/recharts/assets/132348029/87141285-645c-4920-be7f-4c2f0cd0bd0c)

Example:
[![Edit simple-stackedArea-chart](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/simple-stackedarea-chart-rrl28t?file=%2Fsrc%2FApp.tsx%3A22%2C15)

reCharts version: `^2.12.7`

**Comment by ckifer** [comment]
Hi, it looks like this chart is not set up to be stacked. If you use the stackId prop with the same value on both of your Area components then they will stack on top of each other.

**Comment by BastienGenin** [comment]
Sorry i gave the wrong Code Sandbox link, my bad ^^
I set each area with the same stackId in my example.
![image](https://github.com/recharts/recharts/assets/132348029/cf1e0b46-be62-456c-84c3-6d47c2e20e1e)

**Comment by ckifer** [comment]
Ah, thanks for fixing the link!

Ok so I don't quite see what is in your screenshot 

<img width="549" alt="image" src="https://github.com/recharts/recharts/assets/25180830/43247980-7f65-41f9-8547-bc8c00c8a6f8">

They seem to be stacked correctly

**Comment by BastienGenin** [comment]
My bad again, I didn't realize that i saved modification on this code sandbox ^^ sorry for the inconvenience ...

I updated the code sandbox with this dataset: 
```ts
const data = [
  {
    abscissa: "13:00:00",
    "1": 8000,
    "2": 36000,
    "3": 0,
  },
  {
    abscissa: "14:00:00",
    "1": 31000,
    "2": 2700,
    "3": 0,
  },
  {
    abscissa: "15:00:00",
    "1": 0,
    "2": 0,
    "3": 54000,
  },
];
```

You should see the overlapping now

**Comment by ckifer** [comment]
Ah yeah, it saves everything unless you make a new fork.

Got it now, thanks!

Okay so this is due to `type="monotone"`. If you remove that you'll see that the lines are straight and no longer overlap (linear). The `monotone`. Monotone is based off of the d3 function `curveMonotone` - see the docs here to understand it more https://d3js.org/d3-shape/curve#curveMonotoneX

We can't change this behavior in recharts since it isn't ours to change. This is based off of pre-existing math formulas to create a cubic spline

**Comment by ckifer** [comment]
Linking a duplicate issue just for traceability. https://github.com/recharts/recharts/issues/785 (that one was closed without a reason though 🙃)

**Comment by ckifer** [comment]
We could however, apply a mask like this SOF answer suggests 
https://stackoverflow.com/questions/51467541/javascript-d3-overlapping-of-color-areas

**Comment by BastienGenin** [comment]
Thank you so much, you are a life saver <3

**Comment by ckifer** [comment]
No problem!
