### ISSUE TITLE
ResponsiveContainer invariant blows up tests

### ISSUE THREAD

**Issue by dlindahl** [recharts/recharts#47]
I am in the process of swapping out `react-d3` in favor of `recharts` and everything has gone well up until the point that my tests ran.

When `ResponsiveContainer` is rendered with `renderIntoDocument` in my Karma tests (with `karma-chrome-launcher`), the [`invariant` warning](https://github.com/recharts/recharts/blob/e296ba602703176e8f744d35d5c2f82a928607f8/src/component/ResponsiveContainer.js#L60-L64) is thrown and my test blows up.

After digging in to it a bit, it appears that `getComputedStyles`, called from `OuiDomUtils.width`, is returning an object where all values are blank strings. This means that the `width` of the container element is essentially `0` which in turns causes the `invariant` to fail.

While I see why it would be desirable to want a container with a width greater than `0`, is that any reason to blow up the render path?

AFAIK, having a `0`-width (or -height) container element won't cause any errors to be thrown, so maybe it'd be better to go with a softer `console.warn` rather than a hard stop?

Short of removing the `invariant`, the only way I was able to get my tests to run was to re-write the test to use `shallowRender` (which is not something I really wanted to be forced to do :confused:)

 I was unable to find any way to get `getComputedStyles` to _not_ return empty values so I have a feeling like the logic for `ResponsiveContainer` simply won't work in the context of Karma + Chrome. I even looked at your own tests and noted that you are using `shallowRender` (via `enzyme`) so you are likely not seeing this particular "feature"

Sorry if it seems like I'm complaining. Its a corner case (albeit a confusing one) and the rest of this lib seems pretty :100:. Thanks!

**Comment by xile611** [comment]
Thanks! Maybe `invariant` is not suitable to be used here. We will add a log util to output some warning messages.

**Comment by xile611** [comment]
Fixed in 0.8.4
