### ISSUE TITLE
how to use different color in pie chart ?thank you

### ISSUE THREAD

**Issue by Ai01** [recharts/recharts#470]
<img width="115" alt="2017-01-21 5 10 54" src="https://cloud.githubusercontent.com/assets/18245929/22173405/9b7a9ea4-dffc-11e6-97ee-57a5056e5903.png">

**Comment by aseemevari** [comment]
Hi,

There is a example in the Recharts examples section that demonstrates your requirements, 
http://recharts.org/#/en-US/examples/PieChartWithPaddingAngle

Basically you take each Cell component and fill with your desired color
`<Pie
          data={data} 
          cx={120} 
          cy={200} 
          innerRadius={60}
          outerRadius={80} 
          fill="#8884d8"
          paddingAngle={5}
        >
        	{
          	data.map((entry, index) => <Cell fill={COLORS[index % COLORS.length]}/>)
          }
        </Pie>`

**Comment by Ai01** [comment]
thank you very much!

**Comment by Thabares** [comment]
Hi, I am using piechart with sector,[https://recharts.org/en-US/examples/CustomActiveShapePieChart](url) 

<img width="323" alt="Capture" src="https://user-images.githubusercontent.com/34962171/93428939-f3cd4b80-f8dd-11ea-812b-c33fc4506067.PNG">

I want to apply colors for the sectors, passing the cell but it was not working.

`import React, { PureComponent } from 'react';
import { PieChart, Pie, Sector,cell } from 'recharts';

const data = [
  { name: 'Group A', value: 400 },
  { name: 'Group B', value: 300 },
  { name: 'Group C', value: 300 },
  { name: 'Group D', value: 200 },
];
const COLORS = ['#0088FE', '#00C49F', '#FFBB28', '#FF8042'];


const renderActiveShape = (props) => {
  const RADIAN = Math.PI / 180;
  const {
    cx, cy, midAngle, innerRadius, outerRadius, startAngle, endAngle,
    fill, payload, percent, value,
  } = props;
  const sin = Math.sin(-RADIAN * midAngle);
  const cos = Math.cos(-RADIAN * midAngle);
  const sx = cx + (outerRadius + 10) * cos;
  const sy = cy + (outerRadius + 10) * sin;
  const mx = cx + (outerRadius + 30) * cos;
  const my = cy + (outerRadius + 30) * sin;
  const ex = mx + (cos >= 0 ? 1 : -1) * 22;
  const ey = my;
  const textAnchor = cos >= 0 ? 'start' : 'end';

  return (
    <g>
      <text x={cx} y={cy} dy={8} textAnchor="middle" fill={fill}>{payload.name}</text>
      <Sector
        cx={cx}
        cy={cy}
        innerRadius={innerRadius}
        outerRadius={outerRadius}
        startAngle={startAngle}
        endAngle={endAngle}
        fill={fill}
      />
      <Sector
        cx={cx}
        cy={cy}
        startAngle={startAngle}
        endAngle={endAngle}
        innerRadius={outerRadius + 6}
        outerRadius={outerRadius + 10}
        fill={fill}
      />
      <path d={`M${sx},${sy}L${mx},${my}L${ex},${ey}`} stroke={fill} fill="none" />
      <circle cx={ex} cy={ey} r={2} fill={fill} stroke="none" />
      <text x={ex + (cos >= 0 ? 1 : -1) * 12} y={ey} textAnchor={textAnchor} fill="#333">{`PV ${value}`}</text>
      <text x={ex + (cos >= 0 ? 1 : -1) * 12} y={ey} dy={18} textAnchor={textAnchor} fill="#999">
        {`(Rate ${(percent * 100).toFixed(2)}%)`}
      </text>
    </g>
  );
};


export default class Example extends PureComponent {
  static jsfiddleUrl = 'https://jsfiddle.net/alidingling/hqnrgxpj/';

  state = {
    activeIndex: 0,
  };

  onPieEnter = (data, index) => {
    this.setState({
      activeIndex: index,
    });
  };

  render() {
    return (
      <PieChart width={400} height={400}>
        <Pie
          activeIndex={this.state.activeIndex}
          activeShape={renderActiveShape}
          data={data}
          cx={200}
          cy={200}
          innerRadius={60}
          outerRadius={80}
          fill="#8884d8"
          dataKey="value"
          onMouseEnter={this.onPieEnter}
        >
{data.map((entry, index) => (
              <Cell key={`cell-${index}`} fill={COLORS[index % 20]} />
            ))}
</Pie>
      </PieChart>
    );
  }
}
`

**Comment by CaledoniaProject** [comment]
Are you planning to add a builtin color palate array in the future?

**Comment by ckifer** [comment]
@CaledoniaProject I doubt it. We may add one default color or color array so it's better than black by default, but d3-scale-chromatic works well for this in general outside of recharts.

**Comment by twi05** [comment]
Thanks a lot for this!

**Comment by turbomatrixxxl** [comment]
Thank You very much !
