### ISSUE TITLE
Custom icon in Legend component

### ISSUE THREAD

**Issue by wojciechAdaszynski** [recharts/recharts#471]
First of all, thank you for creating such awesome library! I didn't manage to find a way to modify default icons for `Legend` component (e.g. line without a dot). Creating custom component with styling to pass it in `content` prop seems to be overkill for such simple task. Would it be possible to provide `legendIcon` prop to pass function rendering svg icon in future release? Another way would be to export ```DefaultLegendContent``` component for overriding methods like `renderIcon`. Thanks!

**Comment by evilucifero** [comment]
You can modify icon by pass payload to Legend. Like the code below,
```
<Legend
  payload={
    [
      { id: 'pv', value: 'pppv', type: 'diamond', color: '#8884d8'},
      { id: 'uv', value: 'uuuv', type: 'diamond', color: '#82ca9d'},
    ]
   }
/>
```
(http://jsfiddle.net/n8cysgrj/)[http://jsfiddle.net/n8cysgrj/]

**Comment by evilucifero** [comment]
We offer some icons which you can use it by change `type` in payload.

`['line', 'square', 'rect', 'circle', 'cross', 'diamond','star', 'triangle', 'wye']`

**Comment by evilucifero** [comment]
If you want to highly customized, I guess the best way is still to write your own icon by passing content.

**Comment by gauravsoti1** [comment]
@xile611 Documentation for payload (http://recharts.org/en-US/api/Legend) section of legend is this: [{ value: 'item name', type: 'line', id: 'ID01' }]
It doesn't show that we can provide color as well. Can we update the documentation to avoid clarity to other developers in the future?
