### ISSUE TITLE
YAxis's default values are not in proper order

### ISSUE THREAD

**Issue by apoorv-x12** [recharts/recharts#4710]
## 
<img width="947" alt="recharts-bug-yaxis" src="https://github.com/recharts/recharts/assets/76410421/34e59ef6-9bd1-4708-9a9e-6354309623b7">

Just use AreaChart as prescribed in official docs then bug will show up probably.

Expected- values on the YAxis should be in increasing order 

I am using  "recharts": "^2.12.7"

**Comment by ckifer** [comment]
Hi, I'm not sure what you mean. Is this a categorical chart or a numerical chart? If your axis has not been changed to `type="number"` it will be treated as categorical and just render in the order of the data. That looks like the case here

**Comment by apoorv-x12** [comment]
I'm using the ReCharts library to visualize npm package downloads over time. The x-axis is for dates and the y-axis for downloads (numerical type). The y-axis values which are displayed as 600000,200000....etc in image below
<img width="959" alt="hib" src="https://github.com/recharts/recharts/assets/76410421/9fb84e06-a7aa-4ca3-90f2-494f93b5e413">
are not displayed in increasing order.

another example of a different bug in another graph:
<img width="913" alt="habi" src="https://github.com/recharts/recharts/assets/76410421/2c0460d5-19fa-413d-b86b-36f5bfece12b">

I tried using the domain property as per the official docs, but it didn't help. Hovering over the graph shows the correct download numbers, but the y-axis values appear out of order (e.g., 60,000 below 20,000 etc.). This contradicts the basic principle that y-axis values should increase as we move upwards.

Any insights or solutions to ensure the y-axis values display correctly would be appreciated.

**Comment by charpeni** [comment]
Are you able to reproduce on [CodeSandbox](https://codesandbox.io/)?

**Comment by ckifer** [comment]
+1, thanks @charpeni. we'll need to be able to reproduce to be able to help. This usually works as intended and we'll need to know what we're working with in order to help.

thanks!

**Comment by ckifer** [comment]
Going to close this as stale until we get a response
