### ISSUE TITLE
"Total" bar label for stacked bar chart

### ISSUE THREAD

**Issue by matthewberkompas** [recharts/recharts#472]
Below is a screenshot of my stacked bar chart:
<img width="1127" alt="screen shot 2017-01-23 at 2 47 57 pm" src="https://cloud.githubusercontent.com/assets/7084294/22226334/ff247072-e17a-11e6-9d61-c2580e6c9452.png">

I would like to add a **bold** `label` to the end of each bar which would show the combined total of each section in that bar. Is there a way to do this currently? Thanks in advance!

**Comment by xile611** [comment]
Try the component [<LabelList />](http://recharts.org/#/en-US/api/LabelList).

**Comment by kamarajuPrathi** [comment]
Why is this issue closed , and @xile611 what do you mean by try component

**Comment by cmoad** [comment]
I had the same problem and was able to accomplish the goal by adding two separate LabelLists.

This code is straight from my project but should explain the idea.

1. The first LabelList only returns a number from the valueAccessor for the last entry. This avoids showing the rolling sum labels, and possibly rendering multiple labels at the end if you have data of value zero.
1. The second LabelList shows the raw value inside each stacked bar.

```
<Bar
  key={bucket.key}
  animationDuration={200}
  animationEasing="ease-in-out"
  dataKey={`${bucket.key}_calls`}
  fill={analytics.paletteBrand[idx % analytics.paletteBrand.length]}
  name={templateLabel(props.getTemplate, bucket.key)}
  stackId="a"
>
  <LabelList
    fill="#000"
    position="top"
    valueAccessor={(entry: *): ?number =>
      (idx === templateBuckets.length - 1 ? entry.value[1] : null)}
  />
  <LabelList
    dataKey={`${bucket.key}_calls`}
    fill="#FFF"
    position="center"
  />
</Bar>
```

**Comment by gennaroanesi** [comment]
@cmoad , i'm getting the same label on every rectangle of the stacked chart... any ideas?
``` entry.D ``` holds the sum of my data (the value i want to display)

```
{combinations.map(v => (
                <Bar
                  key={v}
                  dataKey={v}
                  name={formatKeyName(v)}
                  fill={getKeyColor(v)}
                  stackId="monthStack"
                >
                  <LabelList
                    position="top"
                    valueAccessor={entry => entry.D}
                    formatter={formatCurrencyValue}
                  />
                </Bar>
              ))}
```
Result:

<img width="122" alt="captura de tela 2018-03-16 as 15 55 54" src="https://user-images.githubusercontent.com/9158216/37539479-95bdbce6-2932-11e8-9f2f-75a4d132406a.png">

**Comment by gennaroanesi** [comment]
got it working with
```
{combinations.map((v, idx) => (
                <Bar
                  key={v}
                  dataKey={v}
                  name={formatKeyName(v)}
                  fill={getKeyColor(v)}
                  stackId="monthStack"
                >
                  {idx === combinations.length - 1 ?
                    <LabelList
                      position="top"
                      valueAccessor={entry => entry.D}
                      formatter={formatCurrencyValue}
                    /> : null}
                </Bar>
              ))}
```

**Comment by fstivicic** [comment]
Hi, can anyone suggest a solution when there are multiple stackId used?

**Comment by AskSkivdal** [comment]
Just in case somebody else discovers this issue and needs a soulution this is how i managed to get it to work:

I got it working by adding a transparent bar on top of the stack and added the label to that.

```tsx
<>
<Bar dataKey={"waiting"} stackId={"a"} fill={"gray"} />
<Bar dataKey={"approved"} stackId={"a"} fill={"green"} />
<Bar dataKey={"rejected"} stackId={"a"} fill={"red"} />
<Bar 
    dataKey={() => 0} // Use zero as the value of the bar
    stackId={"a"} // The id of the stack the label should be added to
    minPointSize={1} // Set a minimum size of the bar so it does not get culled for having a value of zero
    fill="transparent" // Hide the background of the bar. 
    >
        <LabelList 
            dataKey={(d) => d.waiting+d.approved+d.rejected} // The function to create the total
            position={"top"} // Place the label above the 1px large invisible bar
            stroke="white" // Optional set text color
            formatter={(v) => `${formatNumber(v as number / 1000, 2)} km`} // Optional apply formatting to the total.
            />
</Bar>
</>
```

This should work just fine places where multiple stack ids is used.
It should also work on horizontal bars as long as you change the position in the LabelList to be right.

## Result

<img width="922" height="673" alt="Image" src="https://github.com/user-attachments/assets/7e26c168-0b28-4a5f-91d8-285be090b1ed" />
