### ISSUE TITLE
Tooltip per stacked bar in the StackedBarChart

### ISSUE THREAD

**Issue by hyunwoona** [recharts/recharts#474]
I need a StackedBarChart with a tooltip per each stacked bar that displays the value of the stacked bar that is hovered over.

<img width="503" alt="screenshot 2017-01-23 22 56 52" src="https://cloud.githubusercontent.com/assets/3788978/22237223/428618c2-e1bf-11e6-8712-23c83a28c36d.png">

For example, if the violet and blue rectangles each represents 20 people from team A, and 10 people from team B, I want the tooltip to say **Team A: 20** when the mouse is over the violet rectangle, and **Team B: 10** when over the blue rectangle.

I could only find https://github.com/recharts/recharts/issues/380 where @xile611 points to the BarChartWithCustomizedEvent example, but it is not a stacked bar chart, and I couldn't figure out how to do this from the conversation or example in the issue 380.

I logged the data on onClick event of two stacked rectangles in one bar, to see what information I could use to build the kind of custom tooltip that I wanted.

However, the only different fields in the two payloads were _x_, _y_, and _width_, and I am not sure how I can achieve what I want without implementing it from scratch.

I couldn't find any out-of-box solution for this.

How can I do this? Is there a relatively simple way to do this?
Thank you so much.

**Comment by RobiFerentz** [comment]
I think you can simply add an onMouseOver property with a handler that will show a tooltip.
Something like: 
`<Bar dataKey="someKey" stackId="a" fill="#000" onMouseOver={()=>showTooltip()} />`

This will probably require you to also add an onMouseOut prop+handler to hide the tooltip.

**Comment by hyunwoona** [comment]
Thank you. That really helped.
I solved this by keeping a state (in my case in Redux store) and setting, on a onMouseover event, it to the id of the bar the mouse cursor is on, and on a onMouseLeave event setting it to null.
Then I made my custom tooltip component subscribe to this state, so that it accordingly re-renders to changes in this state.

If rendering a separate tooltip for each stacked bar is a desired feature that is not implemented yet, I would love to help.

**Comment by shubhi101** [comment]
Hi @hyunwoona ,

I tried to do the same but the event of Bar is tied to the entire rectangle rather than the individual stack. How did you get the id of the individual stack? Can you please share your code?

Thanks

**Comment by VincentNewkirk** [comment]
> Hi @hyunwoona ,
> 
> I tried to do the same but the event of Bar is tied to the entire rectangle rather than the individual stack. How did you get the id of the individual stack? Can you please share your code?
> 
> Thanks

You should be able to pass an ```id``` prop to the bar.

http://recharts.org/en-US/api/Bar

**Comment by GeoChivas99s** [comment]
show
