### ISSUE TITLE
Tooltip issue in React

### ISSUE THREAD

**Issue by Vijaykumarparelli** [recharts/recharts#4745]
## Tooltip is not hide

Hey team, We have an issue in barchart. when we have multiple bars and moving the cursor randomly. The tooltip does not disappear when the cursor is off the bar.

![image](https://github.com/recharts/recharts/assets/46016592/762cd620-4a46-4b8f-b689-7d52bca5515b)

**Comment by ckifer** [comment]
Under what case does this happen? There are a few open issues tracking similar things so if it's the same I will probably close this

**Comment by ckifer** [comment]
Also by default as long as the cursor is in the chart boundary (even if outside of a bar) the tooltip will still show

**Comment by Vijaykumarparelli** [comment]
we have to show the bar chart in the table, here we have 20 rows for each row we render the bar chart. chart boundary is restricted to the particular cell it selt. this toolip issue coming when cell to cell cursor moving. and this is not consistent

**Comment by ckifer** [comment]
Hi, yeah if you could reproduce in a codesandbox that would be great. It's hard to be able to help without knowing exactly what all of your settings are, etc. 

Thanks!

**Comment by Vijaykumarparelli** [comment]
https://s9t5n8-5173.csb.app/ After updating to latest verstion its working.

thank you.

**Comment by ckifer** [comment]
Cool thanks!
