### ISSUE TITLE
Bug: Brush - initial x-axis range different between synced charts

### ISSUE THREAD

**Issue by yann-combarnous** [recharts/recharts#4750]
## Do you want to request a feature or report a bug?

Bug.

We have 2 charts in sync, with a brush on second. On initial rendering, the x-axis range is different between the 2 charts. When moving brush, both x-axis are then aligned.

## Steps to reproduce
See this [code sandbox](https://codesandbox.io/p/sandbox/simple-line-chart-forked-hcr8qf?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyftgc3m00063p6mipbf23c8%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyftgc3m00023p6m9htzgqrv%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyftgc3m00033p6mgrcjbcin%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyftgc3m00053p6mjlv0v9f5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyftgc3m00023p6m9htzgqrv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyftgc3m00013p6m3fx3dur7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clyfulzbe00023p6nrg0m4eu5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A79%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A80%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clyftgc3m00023p6m9htzgqrv%2522%252C%2522activeTabId%2522%253A%2522clyfulzbe00023p6nrg0m4eu5%2522%257D%252C%2522clyftgc3m00053p6mjlv0v9f5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyftgc3m00043p6m6pxl91wj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clyftgc3m00053p6mjlv0v9f5%2522%252C%2522activeTabId%2522%253A%2522clyftgc3m00043p6m6pxl91wj%2522%257D%252C%2522clyftgc3m00033p6mgrcjbcin%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clyftgc3m00033p6mgrcjbcin%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

On initial render, x-axis range (min/max x) is different.

Once you move the brush, then x-axis range start being in sync.

## What is the expected behavior?
Both x-axis min and max are aligned with Brush startindex / endIndex.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Recharts version: 2.12.7. 
Chrome 126

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/issues/4722

Looks like this is a duplicate. Going to close this one in favor of that
