### ISSUE TITLE
Bar in Bar does not work for vertical layout

### ISSUE THREAD

**Issue by necronet** [recharts/recharts#4755]
## Do you want to request a feature or report a bug?

Hi I was looking into [Bar in Bar](https://master--63da8268a0da9970db6992aa.chromatic.com/?path=/story/api-chart-barchart--bar-in-bar) example from the storybook, I was trying to flip it to the horizontal axis an realized that is not working as expected instead it seem the calculation are not right

| Horizontal | Vertical |
|--------|--------|
|  <img width="528" alt="Screenshot 2024-07-10 at 17 56 10" src="https://github.com/recharts/recharts/assets/99554/319b69aa-be39-4ac0-882e-3aef95ea6ec3"> | <img width="695" alt="Screenshot 2024-07-10 at 17 57 00" src="https://github.com/recharts/recharts/assets/99554/e0f4d045-9144-4a18-9e17-0db489f28a77"> |

**Comment by ckifer** [comment]
Hi! this works - you just have to change some of the defaults.

All XAxes become YAxis and an XAxis is needed so you can change the default from type category to type number

https://codesandbox.io/p/sandbox/simple-bar-chart-forked-t5d8xw?file=%2Fsrc%2FApp.tsx%3A73%2C1

**Comment by ckifer** [comment]
Going to close this. Feel free to comment back with any questions
