### ISSUE TITLE
ThreeDimScatter with string values on axes

### ISSUE THREAD

**Issue by cemremengu** [recharts/recharts#476]
I am trying to create a punch card chart like shown below but the scatter axes won't let me give string values to axes.

Is there any way to achieve this ?

![punch](https://cloud.githubusercontent.com/assets/1297759/22250571/77fcca66-e258-11e6-969d-59f9a5ad8df4.PNG)

**Comment by xile611** [comment]
@cemremengu You should format the data. Or you can create 7 ScatterChart to create such charts.

**Comment by henrinormak** [comment]
How would the data formatting approach look like? I've created a JSFiddle with an ideal case I would like to make work (notice that both X and Y axis use type 'category')

This is a fiddle for an example:
http://jsfiddle.net/897gh2pp/

If this is something that is never going to be supported, then I believe this behaviour should be documented, as of right now there is nothing in any of the Axis saying that type `category` can only be used per one axis of a single chart.

**Comment by xile611** [comment]
@cemremengu Check [this demo](http://recharts.org/#/en-US/examples/BubbleChart).
