### ISSUE TITLE
Cannot re-export helper components. Invariant failed error

### ISSUE THREAD

**Issue by jonathanhuang13** [recharts/recharts#4764]
## What is the current behavior?

I'm creating many charts and want them all to use the same style. For example, I want all the charts' YAxis to have no tickLine and I want the label to be angled at -90 degrees. I tried creating a wrapper YAxis component like so: 

```
import * as Recharts from 'recharts';

interface Props {
  label: string;
}

export default function YAxis({ label }: Props) {
  return (
    <Recharts.YAxis tickLine={false} tickMargin={10} axisLine={false}>
      <Recharts.Label
        value={label}
        angle={-90}
        offset={0}
        position="insideLeft"
      />
    </Recharts.YAxis>
  );
}
```

Using this YAxis component results in the following error:

```
Error: Invariant failed: Specifying a(n) yAxisId requires a corresponding yAxisId on the targeted graphical component Bar
```

Copying and pasting the contents of my custom YAxis component, however, will work.

For example:

```
<BarChart accessibilityLayer data={data}>
    <YAxis label="My label" /> // custom component
    <Bar dataKey="key" />
</BarChart>
```
will not work, but 
```
<BarChart accessibilityLayer data={data}>
    <Recharts.YAxis tickLine={false} tickMargin={10} axisLine={false}>
      <Recharts.Label
        value={'My label}
        angle={-90}
        offset={0}
        position="insideLeft"
      />
    </Recharts.YAxis>

    <Bar dataKey="key" />
</BarChart>
```
will work. Setting the ID explicitly in both the YAxis and Bar components doesn't work either

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via codesandbox or similar (template: https://codesandbox.io/p/sandbox/simple-line-chart-v25dl4).

Reproduced [here](https://codesandbox.io/p/sandbox/recharts-bug-wl64zs?file=%2Fsrc%2FApp.tsx%3A1%2C1-105%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clykkv52u00063b6k7hfviwy7%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clykkv52u00023b6kac2avy8z%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clykkv52u00033b6k4ko5i5tq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clykkv52u00053b6kj38sjx0q%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clykkv52u00023b6kac2avy8z%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clykkv52u00013b6kpq2qw1pg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clykkwq94003g3b6komi9gd12%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A105%252C%2522endColumn%2522%253A1%257D%255D%257D%255D%252C%2522id%2522%253A%2522clykkv52u00023b6kac2avy8z%2522%252C%2522activeTabId%2522%253A%2522clykkwq94003g3b6komi9gd12%2522%257D%252C%2522clykkv52u00053b6kj38sjx0q%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clykkv52u00043b6kapnrv8b4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clykkv52u00053b6kj38sjx0q%2522%252C%2522activeTabId%2522%253A%2522clykkv52u00043b6kapnrv8b4%2522%257D%252C%2522clykkv52u00033b6k4ko5i5tq%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clykkv52u00033b6k4ko5i5tq%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

## What is the expected behavior?

Writing a wrapper component should work

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
2.12.7

**Comment by ckifer** [comment]
This is known and will be fixed in 3.0. Not much we can do about it for now. If you make a wrapper function instead of a wrapper component it will work. 

You can also try adding a display name of "YAxis" to your wrapper component. 

YAxis.displayName = "YAxis"

That might fix this. 

Can't check the sandbox right now but will follow up. 

Thanks

**Comment by jonathanhuang13** [comment]
Got it thanks, the wrapper function worked. The display name didn't though (just FYI for anyone else who sees this).

**Comment by cini9** [comment]
Hey @ckifer, I have a similar use case for my XAxis. What's the current ETA on version 3.0 ?

**Comment by cini9** [comment]
Alright thanks for the update. Good luck to you guys !
