### ISSUE TITLE
[Suggestion] Add more details to API docs

### ISSUE THREAD

**Issue by chipit24** [recharts/recharts#477]
I'm going through the [API documentation](http://recharts.org/#/en-US/api) and it looks like useful details are missing.

For example, the docs for the [`Tooltip`](http://recharts.org/#/en-US/api/Tooltip) `formatter` prop only state that it's an optional function; there is no information on what arguments are provided and what the function should return.

By providing such details, it will save users from digging through the [source code](https://github.com/recharts/recharts/blob/master/src/component/DefaultTooltipContent.js#L62).

**Comment by xile611** [comment]
@chipit24 It's welcome to submit PR in [recharts.org](https://github.com/recharts/recharts.org)
