### ISSUE TITLE
Can't render Bar In Bar component in my project

### ISSUE THREAD

**Issue by maor-landau** [recharts/recharts#4796]
Hi Im trying to render the according chart in my project - 
https://master--63da8268a0da9970db6992aa.chromatic.com/?path=/story/api-chart-barchart--bar-in-bar

with the following code
![Screenshot 2024-07-21 at 17 29 14](https://github.com/user-attachments/assets/d2bd74a6-3be3-4cac-969d-c0b0776a1239)
![Screenshot 2024-07-21 at 17 30 02](https://github.com/user-attachments/assets/cfef824c-7346-4df4-94eb-22a793517d8e)
![Screenshot 2024-07-21 at 17 30 16](https://github.com/user-attachments/assets/51e891b8-5eb4-41af-a626-878c27e1f77e)

Nothing is happen on my screen, can someone tell me if I need some styling file or something else?
Thanks.

**Comment by ckifer** [comment]
data={data} instead of spreading your data array?

**Comment by maor-landau** [comment]
@ckifer That's the first thing I suspected but unfortunately it didn't fix the problem

**Comment by maor-landau** [comment]
@ckifer This is the first thing I suspected and it didn't fix the problem, but you gave me an interesting way of thinking and made me try the next thing
<img width="727" alt="Screenshot 2024-07-21 at 17 45 08" src="https://github.com/user-attachments/assets/31765fa2-eea9-466a-ada4-146d46a6fc28">

And now I can see the chart on the screen, thanks!

**Comment by ckifer** [comment]
Sounds good!
