### ISSUE TITLE
ReferenceArea doesn't cover along y-axis and x-axis if x2 and y2 are missing

### ISSUE THREAD

**Issue by liubko** [recharts/recharts#480]
> From Docs:
> A boundary value of the area. If the specified y-axis is a number axis, the type of y must be Number. If the specified y-axis is a category axis, the value of y must be one of the categories. If one of y1 or y2 is invalidated, 

Demo: http://jsfiddle.net/liubkoliubko/rk119osf/3/
expected that this code will cover all chart area
```
<ReferenceArea
  x1={0}
  y1={0}
  fill="green" />
```
or like this
```
<ReferenceArea fill="green" />
```

----

_What I'm actually trying to do is to add background to the chart, using `<ReferenceArea>` is as close as I can get, but maybe there another approach?_

**Comment by xile611** [comment]
@liubko 

You can set the background color by specify `fill` of `CartesianGrid`:

```jsx
<CartesianGrid 
  strokeDasharray="3 3" 
  fill="green"
/>
```

[demo](http://jsfiddle.net/mbd91kf8/)

**Comment by liubko** [comment]
Thanks! I will definitely use that. 

_But I still think that there is an issue with `ReferenceArea`_

**Comment by DanilloCorvalan** [comment]
I do agree with @liubko, I'm trying to draw a ReferenceArea in a BarChart that starts in the x1={0}, or beginning of the chart up until the first X value, not in the middle of it but the the bar ends.
