### ISSUE TITLE
[Typescript] Bar prop `label` is missing type for `dataKey`

### ISSUE THREAD

**Issue by Amethystix** [recharts/recharts#4805]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
When using a `Bar` component, you can specify the label via the prop, like so:
```
<Bar dataKey="Visits" fill="#5851af" label={{ position: "top", dataKey: "Earnings" }}/>
```
This works properly and outputs the expected graph:
<img width="632" alt="Screenshot 2024-07-23 at 11 57 44 PM" src="https://github.com/user-attachments/assets/5799d631-2a18-43cf-a2e3-eb65e06f42ea">
However, the type is not defined on the label prop type, giving me the Typescript `No overload matches this call` error.

## What is the expected behavior?
Type should be supported. I know I can use `LabelList`, but if this works on the `Bar` as well it should be typed as such.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
2.12.7

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/pull/5034
