### ISSUE TITLE
LabelList is disappearing on Chrome for IOS 

### ISSUE THREAD

**Issue by lober-io** [recharts/recharts#4808]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?

Full or Parts of the LabelList disappear after a short time when opened on Chrome on an iPhone.
They are briefly there and then disappear. 
This is also happening on the example: https://recharts.org/en-US/examples/CustomizedLabelLineChart
I'm using a similar code for the bar chart. I tried removing the animation, etc. but nothing helped. 

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via codesandbox or similar (template: https://codesandbox.io/p/sandbox/simple-line-chart-v25dl4).

Either [CustomizedLabelLineChart](https://recharts.org/en-US/examples/CustomizedLabelLineChart) or use a similar code like below. 

``` const renderCustomizedLabel = (props) => {
      const { x, y, width, height, value } = props;
      const radius = 10;
    
      let color = "#fff";
      if (x + width / 2 > width + 50) {
        color = "#051540";
      }
    
      return (
        <text
          x={x + width / 2 + 50}
          y={y + height / 2}
          fill={color}
          className="fw-bold"
          textAnchor="middle"
          dominantBaseline="middle"
        >
          {value}
        </text>
      );
    };

 <ResponsiveContainer width="100%" height={300}>
                <BarChart
                  layout="vertical"
                  width={500}
                  height={400}
                  data={data}
                  margin={{
                    left: 30,
                  }}
                >
                  <Tooltip />

                  <XAxis type="number" name="Count" hide />
                  <YAxis
                    width={90}
                    dataKey="name"
                    type="category"
                    name="Count"
                    tick={{ fontSize: "0.8rem" }}
                  />
                  <Bar
                    dataKey="count"
                    name="Count"
                    fill="#757575"
                    label={renderCustomizedLabel}
                  >
                    {data.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % 20]} />
                    ))}
                  </Bar>
                </BarChart>
```

## What is the expected behavior?

Label are staying there. 

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

recharts 2.12.7
Chrome for IOS 127.0.65.33.56

**Comment by ckifer** [comment]
I can see them fine, chrome for iPhone

**Comment by lober-io** [comment]
Strange, I just tried a colleague's iPhone, and it is working as well.

**Comment by lober-io** [comment]
You can see the behavior here. The BarChart below on the same page is working, but I have the issue in one other LineChart and another BarChart. 

https://github.com/user-attachments/assets/b3fc4545-fc27-4d43-a163-6b7d406ae2a2

**Comment by ckifer** [comment]
It's going to be really hard to debug and fix if we cant reproduce it reliably

**Comment by ckifer** [comment]
Tagging this as needs reproduction because its going to be almost impossible to debug without something more

**Comment by ckifer** [comment]
Still cannot reproduce this on chrome/ios, going to close it as stale. Please comment if anyone runs into it and we can reopen

**Comment by xcy1231** [comment]
It might be caused by this https://stackoverflow.com/questions/78207646/how-do-i-disable-chrome-annotation-tags
