### ISSUE TITLE
Y-Axis Fixed Position Area Chart

### ISSUE THREAD

**Issue by ghost** [recharts/recharts#481]
How would one make the y-axis position:fixed as in cases where chart data gets loaded in mobile device and user needs to scroll to right I'd like the y-axis to stay fixed.

Thanks

**Comment by Poirette** [comment]
This feature would be really nice. I need this too. On Y and X axis.

Is there any way to accomplish this until Recharts support this feature ?

**Comment by lukepighetti** [comment]
I am running into this same issue. Has anyone found a solution?

**Comment by FengHuangDong** [comment]
I am running into this same issue. Has anyone found a solution?

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
