### ISSUE TITLE
PROPS LIKE HEIGHT, X ARE passing as null in shape prop for Bar

### ISSUE THREAD

**Issue by jackvik** [recharts/recharts#4836]
## Do you want to request a feature or report a bug?
No
## What is the current behavior?
props like x, height, background:{height} are coming as null when we try to access custom shape in the shape prop or Bar. Bar is part of ComposedChart which is further chiled of responsive container.
## What is the expected behavior?
The values of height, x and background props should come.
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
It's not coming in version 2.12.7 v but coming correctly in version 1.8.5.

Code Snipped:
` <ResponsiveContainer width='100%' height={250} id={id}>
        <ComposedChart data={data} height={250} width='100%'>
          <XAxis dataKey={XAxisKey} tickFormatter={XAxisFormatter} />
          <YAxis domain={[yAxisDomain[0], yAxisDomain[1] || 'auto']} tickFormatter={YAxisFormatter} />
          <Bar dataKey={"x"} height={250}
            shape={<CustomizedBar dataKeys={dataKeys} colors={colors} maxValue={yAxisDomain[1]} />}
          />
        </ComposedChart>
      </ResponsiveContainer>`

I am trying to access x, background:{height} and height in CustomizedBar component

**Comment by jackvik** [comment]
@ckifer can you please look into this if possible. Thanks

**Comment by ckifer** [comment]
As this may have been this way for a long time (since 1.x) this issue isn't a huge priority. There will be new ways to get these values in 3.x

If you could look into the exact version it broke that would go a long way helping address it.

**Comment by ckifer** [comment]
https://codesandbox.io/p/sandbox/simple-bar-chart-forked-nkc262

I'm going to close this because `height`, `width`, and `x` are all coming back as normal in the `shape` prop.

The sandbox should demonstrate that - feel free to comment if there is something missing

You probably need to treat it like a function and do

```ts
  shape={(props) => <CustomizedBar {...props} {...customProps} />}
```
