### ISSUE TITLE
Band chart

### ISSUE THREAD

**Issue by gusdaud** [recharts/recharts#484]
Is there a way to draw a chart line the one bellow ?

![image](https://cloud.githubusercontent.com/assets/13708461/22384841/4492728c-e4b7-11e6-841d-d5d2dac80fe4.png)

I believe its called a "band chart". 
In case there isn't a predefined way, can I draw it using the Polygon component ?

Any help will be appreciated. Thanks,

**Comment by xile611** [comment]
Done in version 0.21.0
