### ISSUE TITLE
Rechart throws invariant on unmatched axisId in production

### ISSUE THREAD

**Issue by han-clearstreet** [recharts/recharts#4841]
## Do you want to request a feature or report a bug?
Rechart throws invariant on unmatched axisId in production.

## What is the current behavior?
See https://github.com/recharts/recharts/blob/3.x/src/chart/generateCategoricalChart.tsx#L841
```text
tell the user in dev mode that their configuration is incorrect if we cannot find a match between axisId on the chart and axisId on the axis. zAxis does not get passed in the map for ComposedChart, leave it out of the check for now.
```
based on comments, this invariant is meant for dev, but do not see any env splitting here.

## What is the expected behavior?
Based on comment, invariant should only be applicable to dev

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Any version after `2.9.0` where the invariant is added. See original PR https://github.com/recharts/recharts/pull/3720/files#diff-aa1b4fbed632e1bdab786e0521346d3a1a2386c633f22f5778d4bcbc47581a65R857

**Comment by ckifer** [comment]
Ah yeah when these were added there was a misunderstanding of what invariant actually does, I thought it took care of env splitting itself.

I guess I don't see anything wrong with this other than the comment is incorrect and that it was added in a minor version so it's technically breaking. 

If it doesn't work in dev it doesn't work in production and that's true whether there is an invariant or not. One will just be louder than the other.

**Comment by ckifer** [comment]
Checking the output of the build 
`process.env.NODE_ENV !== "production"` is in place for every invariant check using `babel-plugin-dev-expression`

These shouldn't throw in production, make sure your `NODE_ENV` env variable is set correctly.

Going to close this
