### ISSUE TITLE
TypeError: Constructor Map requires 'new'

### ISSUE THREAD

**Issue by amansadhwani** [recharts/recharts#4855]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?

After updating recharts from 1.8.5 to 2.12.7 getting an error 
```
Constructor Map requires 'new'
TypeError: Constructor Map requires 'new'
```
I t works fine with 1.8.5 version I even tried taking current example from recharts but that too doesn't work

If I remove **ResponsiveContainer** than at least I don;t get the error but than chart is not displayed

I can't replicate the issue on CodeSandbox because everything works fine there. I suspect that a different version of a package in the `package.json` file is causing the problem, but I haven't been able to identify which version is responsible.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Typescript 5.5.4
recharts 2.12.7 
Mac
Google Chrome Version 127.0.6533.89

<img width="1504" alt="Screenshot 2024-08-05 at 1 06 18 PM" src="https://github.com/user-attachments/assets/92696ff3-d80c-401e-810e-f6c5a25b4adb">

**Comment by ckifer** [comment]
Without a reproduction there isn't much I can help with. Version 1.8.5 does not use typescript, so this is most likely a TSConfig issue. Recharts code contains no use of the "Map" constructor anywhere in the code at any point

**Comment by amansadhwani** [comment]
@ckifer  Yes it was tsconfig issue had to change target from es5 to es6

Thanks a lot for your help.
