### ISSUE TITLE
Error when migrating npm project to pnpm

### ISSUE THREAD

**Issue by Zzzdy-code** [recharts/recharts#4859]
## What is the current behavior?
Error when migrating npm project to pnpm
![image](https://github.com/user-attachments/assets/fde7c536-6839-473b-946e-f9ac384b42da)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via codesandbox or similar (template: https://codesandbox.io/p/sandbox/simple-line-chart-v25dl4).
```
pnpm import
pnpm install
pnpm start
```
This is node_modules
![image](https://github.com/user-attachments/assets/5da9f44a-78af-413d-942c-2920f0853404)
![image](https://github.com/user-attachments/assets/b66458f9-512b-4530-ab5b-ef557e91adda)
![image](https://github.com/user-attachments/assets/ad9d2051-8078-4d17-8e41-cc708567022a)

![image](https://github.com/user-attachments/assets/1cf8ef8b-f7ab-4354-a14f-a64b1441675a)

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
"recharts": "^2.1.12",

**Comment by ckifer** [comment]
Looks like you just need to delete your node modules folder and reinstall. 

Also try upgrading to the latest

**Comment by mistervaibhav** [comment]
is there any workaround guys ? 
seems like this is still an issue in 2026

**Comment by PavelVanecek** [comment]
We're going to need more details @mistervaibhav . Like a lot more details than no details.
