### ISSUE TITLE
onClick prop on Line isn't being invoked

### ISSUE THREAD

**Issue by akonwi** [recharts/recharts#486]
According to the docs, the Line component has an `onClick` property but the method I'm providing isn't getting invoked. With that said, the LineChart element's `onClick` property works as expected.

I have a [jsfiddle](http://jsfiddle.net/x1yoboc7/339/) set up here.

**Comment by xile611** [comment]
@akonwi The `Line` was just too thin to be clicked. Please check [this demo](http://jsfiddle.net/wzpf21f1/).

**Comment by infacq** [comment]
it would not look good if I'm going to make a TinyLine chart
