### ISSUE TITLE
React does not recognize the `dataKey` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `datakey` instead.

### ISSUE THREAD

**Issue by k-lombard** [recharts/recharts#4861]
## Do you want to request a feature or report a bug?
Report a bug

## What is the current behavior?

Getting errors in my React component:
```
const CustomLegend = (props: any) => {
    const { payload } = props;

    return (
      <div className="flex w-full flex-row justify-between pb-6">
        <h2 className="text-lg font-semibold uppercase text-gray-700">
          METRICS
          </h2>
        <div className="flex flex-row items-center space-x-4 align-middle">
          {payload.map((entry: any, index: number) => (
            <div key={`item-${index}`} className="flex items-center space-x-2">
              <div
                style={{ backgroundColor: entry.color }}
                className="h-3 w-3 rounded-full"
              ></div>
              <span className="text-gray-700">{entry.value}</span>
            </div>
          ))}
          <h2 className="border-l border-gray-300 pl-4">
            <button className="text-blue-500">See More</button>
          </h2>
        </div>
      </div>
    );
  };

  return (
    <div className="flex w-[60%] flex-col space-y-4 bg-white p-[24px] shadow-md">
      <ResponsiveContainer width="100%" height="100%">
        <BarChart
          width={500}
          height={300}
          data={data}
          margin={{
            top: 5,
            right: 30,
            left: 20,
            bottom: 5,
          }}
        >
          <CartesianGrid strokeDasharray="3 3" />
          <XAxis dataKey="name" />
          <YAxis />
          <Tooltip />
          <Legend
            content={<CustomLegend />}
            verticalAlign="top"
            align="right"
          />
          <Bar
            dataKey="Revenue"
            fill="#B3CDAD"
            activeBar={<Rectangle fill="pink" stroke="blue" />}
          />
          <Bar
            dataKey="Expenses"
            fill="#FF5F5E"
            activeBar={<Rectangle fill="gold" stroke="purple" />}
          />
        </BarChart>
      </ResponsiveContainer>
    </div>
  );
}
```

Errors: 

```
React does not recognize the `dataKey` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `datakey` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
```
react-dom.development.js:86 Warning: React does not recognize the `Expenses` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `expenses` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
```
React does not recognize the `Revenue` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `revenue` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
```
react-dom.development.js:86 Warning: React does not recognize the `tooltipPayload` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `tooltippayload` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

## What is the expected behavior?

I shouldnt be getting these errors when my charts render and function as expected.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

React in Chrome browser with "recharts": "^2.13.0-alpha.4",

**Comment by ckifer** [comment]
Does this affect versions previous to the latest alpha? 

(Out rn so won't be able to check for a bit)

**Comment by k-lombard** [comment]
Yes I believe it does, I switched to alpha in an attempt to see if the issues would be fixed

**Comment by ckifer** [comment]
Ok, will check it when I can

**Comment by ckifer** [comment]
I cannot reproduce this, would you be able to make a codesandbox?

**Comment by ckifer** [comment]
I still can't reproduce this, please respond if this is still an issue. For now going to close as stale

**Comment by dcchuck** [comment]
Should someone else stumble upon this - I thought the error was from my use of the `dataKey` prop at first glance. However, in my case, it's the custom component (in the example `const CustomLegend = (props: any) => {`) where the props are being parsed.

If you're explicit about this interface (i.e. don't use the any) the issue shouldn't arise.

**Comment by ckifer** [comment]
@dcchuck this shouldn't be related to types at all, as it's a talking about an attribute spread onto an element that that it attempting to be rendered into the DOM. Can you reproduce this?

**Comment by dcchuck** [comment]
@ckifer No, though in attempting to repro, reading my comment, and yours again - I'll say I agree with you more than I do my post.

In my case, I was updating a custom `dot` for a line chart. The component had some custom props that were meant to be passed down, so the props were being spread. I fixed the issue - but at the time I was also getting the `React does not recognize the `dataKey` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `datakey` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

Checking out the code again and attempting to reproduce, I only see the error about the props being spread.

Thank you for the comment, I'll be sure to follow up if it comes up again

**Comment by PavelVanecek** [comment]
Yeah this is kind of expected as Recharts likes to spread props everywhere without checking what's inside. Some of the JSX props end up in the DOM. They don't do anything but React complains about it.

This should be safe to ignore.
