### ISSUE TITLE
Pie Chart Slice Colors

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#487]
Is there a simpler/cleaner way to add colors to pie chart slices? The current example (like this [PieChartWithPaddingAngle](http://recharts.org/#/en-US/examples/PieChartWithPaddingAngle)) seems overly convoluted for something that really should be "built in". Maybe just an attribute on the "pie" component that allows you to set an array of colors, which are then selected in order, like in the example?

**Comment by xile611** [comment]
Maybe when the props `fill` of `Pie` is an array, we can use the fill the slices in order. But how about other props, like `stroke`, `strokeWidth`, .etc ?

**Comment by Eric24** [comment]
Yes, but to your point, maybe not the cleanest solution. I know that Pie (and Bar) will pick up and override the component settings for fill, stroke, and strokeWidth from the underlying data array (although it isn't always possible to set it there). What other attributes do these components look for in the data?

**Comment by xile611** [comment]
@Eric24 Yeah, these components will pick up all the [presentation attributes](https://github.com/recharts/recharts/blob/master/src/util/ReactUtils.js#L6).

**Comment by Eric24** [comment]
Wow. That's a lot of attributes! OK. How about this? Since the components can already pick up these attributes from the data array, why not have a separate "style" array. That array is simply a list of objects, each with one or more presentation attributes. The first item in the style array is applied to the first item in the data array (with the data array taking precedence), the second style to the second data, and so on, but MOD the length of the style array, so it gets reused from the beginning when there are more data items than style items.

**Comment by xile611** [comment]
@Eric24 It seems a good idea!

**Comment by charly37** [comment]
This ticket seems related to this one https://github.com/recharts/recharts/issues/986 that help me find the solution for the color. @xile611 your like is very usefull. THX. I did not see it in the documentation (I just had a quick look) so maybe it could be added.
