### ISSUE TITLE
Passing data to each Line chart makes the charts display half of the canvas

### ISSUE THREAD

**Issue by tuongaz** [recharts/recharts#4904]
I want to display Lines chart that have different X, Y . The lines chart are displayed but just half of the canvas. 

<img width="521" alt="Screenshot 2024-08-20 at 10 53 22 am" src="https://github.com/user-attachments/assets/6d159678-987a-4924-9bb3-7cdcd6caca60">

<img width="512" alt="Screenshot 2024-08-20 at 10 55 34 am" src="https://github.com/user-attachments/assets/ecbb74c6-6a55-4496-be3a-c3880a3a9927">

Here's the code https://codesandbox.io/p/sandbox/line-chart-width-xaxis-padding-forked-qwzxjs

The X axis are displaying strangely

**Comment by ckifer** [comment]
try `allowDuplcatedCategory={false}` on your x axis

<img width="632" alt="image" src="https://github.com/user-attachments/assets/9aa2b9cb-add1-411a-bb9a-a48f755b7ef0">

**Comment by tuongaz** [comment]
Oh that works. Thanks
