### ISSUE TITLE
Not possible to create a rounded stacked bar chart if some bars only contain one value

### ISSUE THREAD

**Issue by valdemarrolfsen** [recharts/recharts#4905]
## Do you want to request a feature or report a bug?
I am requesting a feature / reporting an issue with the current implementation

## What is the current behavior?

If you want to create a stacked bar chart with rounded corners where some of the bars only have one value the corners will look wankey.

![Screenshot 2024-08-20 at 09 27 45](https://github.com/user-attachments/assets/ff767dd6-98b1-43fe-9675-3e07f69d8086)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via codesandbox or similar (template: https://codesandbox.io/p/sandbox/simple-line-chart-v25dl4).

```
<ResponsiveContainer width="100%" height={300}>
    <BarChart layout="vertical" width={500} height={300} data={data}>
        <CartesianGrid strokeDasharray="3 3" horizontal={false} />
        <XAxis type="number" hide domain={[0, "dataMax + 1000"]} />
        <YAxis dataKey="name" type="category" axisLine={false} tickLine={false} tickMargin={10} />
        <Tooltip />
        <Legend iconType="circle" />
        <Bar dataKey="contracted" stackId="a" fill="#075884" radius={[8, 0, 0, 8]} />
        <Bar dataKey="notContracted" stackId="a" fill="#38BCF7" radius={[0, 8, 8, 0]} />
    </BarChart>
</ResponsiveContainer>
```
## What is the expected behavior?

It would be great if there was a way of creating this:
![Screenshot 2024-08-20 at 09 28 02](https://github.com/user-attachments/assets/a29c5761-7265-4879-8b3b-96d04c72b612)

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
`"recharts": "^2.12.7"`

**Comment by ckifer** [comment]
+1 to the above response - this is how you would do it for now

**Comment by ckifer** [comment]
Going to close this as stale
