### ISSUE TITLE
X-axis label overflow

### ISSUE THREAD

**Issue by jlarso11** [recharts/recharts#491]
If the label is longer then what it has room for, then it is placed at the very top of the screen and taken out of the axis markup.  Is there a way that will just chop off the edge of the text but put as much as possible in the right place?

**Comment by xile611** [comment]
@jlarso11  Can you submit a jsfiddle demo ?

**Comment by jlarso11** [comment]
http://jsfiddle.net/jlarso11/rzhrLogy/

Here is the basic problem.  We have applied some extra styling to ours to make four out of five show up but this gives the basic idea

**Comment by xile611** [comment]
@jlarso11 You can specify `ticks` of `XAxis` to set the ticks. Or you can change `interval` of `XAxis`.
