### ISSUE TITLE
ComposedChart recharts-active-dot and recharts-tooltip-cursor offset deviation

### ISSUE THREAD

**Issue by LukeAntarctic** [recharts/recharts#4910]
<img width="815" alt="image" src="https://github.com/user-attachments/assets/bbee9f6a-7fc3-43d1-84b0-75806c94dcb7">

  <ResponsiveContainer width="100%" height="100%" className="border-x border-b border-line_color">
          <ComposedChart
            data={_data}
            margin={{
              top: 0,
              right: 0,
              bottom: 0,
              left: 0,
            }}
          >
            <CartesianGrid stroke="#202540" vertical={false} />
            <XAxis
              dataKey="time"
              stroke="var(--text_color_01)"
              scale="band"
              tick={{ fontSize: 10 }}
              axisLine={false}
              tickLine={false}
              tickFormatter={_time => {
                return getTime(dateType, _time)
              }}
            />
            <YAxis
              tick={{ fontSize: 10 }}
              axisLine={false}
              tickLine={false}
              stroke="var(--text_color_01)"
              tickFormatter={_val => {
                return `${_val}%`
              }}
            />
            <Tooltip content={<CustomTooltip />} />
            <Legend verticalAlign="bottom" height={36} content={renderLegend} />
            {/* card_background_color */}
            {/* MA7 */}
            <Line type="linear" dot={false} dataKey="MA7" strokeWidth={2} stroke="var(--auxiliary_01_color)" />
            {/* MA14 */}
            <Line type="linear" dot={false} dataKey="MA14" strokeWidth={2} stroke="var(--sell_down_color)" />
            {/* AVERAGE */}
            <Line
              type="linear"
              dot={false}
              dataKey="AVERAGE"
              stroke="var(--buy_up_color)"
              strokeWidth={2}
              strokeDasharray="6 4"
            />
            <Area
              type="linear"
              dot={false}
              dataKey={currentType}
              fill="var(--auxiliary_01_color_trans_bg)"
              strokeWidth={2}
              stroke="var(--auxiliary_01_color_animate)"
            />
            {/* <Bar dataKey="pv" barSize={20} fill="#413ea0" /> */}
            {/*  */}
            {/* <Scatter dataKey="cnt" fill="red" /> */}
          </ComposedChart>
        </ResponsiveContainer>
        
        const data=[
    {
        "AVERAGE": -68.43747916666668,
        "MA7": -60.83331428571428,
        "MA14": -60.833307142857144,
        "time": 1724047200000,
        "apy": -121.6667
    },
    {
        "AVERAGE": -68.43747916666668,
        "MA7": -69.52380000000001,
        "MA14": -65.17855,
        "time": 1724050800000,
        "apy": -121.6667
    },
    {
        "AVERAGE": -68.43747916666668,
        "MA7": -78.21428571428571,
        "MA14": -69.52379285714285,
        "time": 1724054400000,
        "apy": -121.6667
    },
    {
        "AVERAGE": -68.43747916666668,
        "MA7": -86.90477142857142,
        "MA14": -73.86903571428572,
        "time": 1724058000000,
        "apy": -121.6667
    },
    {
        "AVERAGE": -68.43747916666668,
        "MA7": -95.59525714285714,
        "MA14": -78.21427857142858,
        "time": 1724061600000,
        "apy": -60.8333
    },
    {
        "AVERAGE": -68.43747916666668,
        "MA7": -95.59525714285715,
        "MA14": -78.21427857142858,
        "time": 1724065200000,
        "apy": -60.8333
    },
    {
        "AVERAGE": -68.43747916666668,
        "MA7": -86.90477142857142,
        "MA14": -78.21427857142858,
        "time": 1724068800000,
        "apy": -60.8333
    },
    {
        "AVERAGE": -68.43747916666668,
        "MA7": -78.21428571428571,
        "MA14": -78.21427857142858,
        "time": 1724072400000,
        "apy": -60.8333
    },
    {
        "AVERAGE": -68.43747916666668,
        "MA7": -69.52380000000001,
        "MA14": -78.21427857142858,
        "time": 1724076000000,
        "apy": -60.8333
    },
    {
        "AVERAGE": -68.43747916666668,
        "MA7": -60.83331428571429,
        "MA14": -78.21427857142858,
        "time": 1724079600000,
        "apy": -60.8333
    },
    {
        "AVERAGE": -68.43747916666668,
        "MA7": -52.14282857142857,
        "MA14": -78.21427857142858,
        "time": 1724083200000,
        "apy": -60.8333
    },
    {
        "AVERAGE": -68.43747916666668,
        "MA7": -52.14282857142857,
        "MA14": -78.21427857142858,
        "time": 1724086800000,
        "apy": -60.8333
    },
    {
        "AVERAGE": -68.43747916666668,
        "MA7": -52.14282857142857,
        "MA14": -78.21427857142858,
        "time": 1724090400000,
        "apy": -60.8333
    },
    {
        "AVERAGE": -68.43747916666668,
        "MA7": -52.14282857142857,
        "MA14": -73.86903571428572,
        "time": 1724094000000,
        "apy": -60.8333
    },
    {
        "AVERAGE": -68.43747916666668,
        "MA7": -52.14282857142857,
        "MA14": -69.52379285714287,
        "time": 1724097600000,
        "apy": -60.8333
    },
    {
        "AVERAGE": -68.43747916666668,
        "MA7": -52.14282857142857,
        "MA14": -65.17855,
        "time": 1724101200000,
        "apy": -60.8333
    },
    {
        "AVERAGE": -68.43747916666668,
        "MA7": -52.14282857142857,
        "MA14": -60.83330714285715,
        "time": 1724104800000,
        "apy": -60.8333
    },
    {
        "AVERAGE": -68.43747916666668,
        "MA7": -52.14282857142857,
        "MA14": -56.48806428571429,
        "time": 1724108400000,
        "apy": -60.8333
    },
    {
        "AVERAGE": -68.43747916666668,
        "MA7": -52.14282857142857,
        "MA14": -56.48806428571429,
        "time": 1724112000000,
        "apy": -60.8333
    },
    {
        "AVERAGE": -68.43747916666668,
        "MA7": -52.14282857142857,
        "MA14": -56.48806428571429,
        "time": 1724115600000,
        "apy": -60.8333
    },
    {
        "AVERAGE": -68.43747916666668,
        "MA7": -52.14282857142857,
        "MA14": -56.48806428571429,
        "time": 1724119200000,
        "apy": -60.8333
    },
    {
        "AVERAGE": -68.43747916666668,
        "MA7": -52.14282857142857,
        "MA14": -56.48806428571429,
        "time": 1724122800000,
        "apy": -60.8333
    },
    {
        "AVERAGE": -68.43747916666668,
        "MA7": -52.14282857142857,
        "MA14": -56.48806428571429,
        "time": 1724126400000,
        "apy": -60.8333
    }
]

**Comment by LukeAntarctic** [comment]
<ResponsiveContainer width="100%" height="100%" className="border-x border-b border-line_color">
          <ComposedChart
            data={_data}
            margin={{
              top: 0,
              right: 0,
              bottom: 0,
              left: 0,
            }}
          >
            <CartesianGrid stroke="#202540" vertical={false} />
            <XAxis
              dataKey="time"
              stroke="var(--text_color_01)"
              scale="band"
              tick={{ fontSize: 10 }}
              axisLine={false}
              tickLine={false}
              tickFormatter={_time => {
                return getTime(dateType, _time)
              }}
            />
            <YAxis
              tick={{ fontSize: 10 }}
              axisLine={false}
              tickLine={false}
              stroke="var(--text_color_01)"
              tickFormatter={_val => {
                return `${_val}%`
              }}
            />
            <Tooltip content={<CustomTooltip />} />
            {/* 底部线条归类分析 */}
            <Legend verticalAlign="bottom" height={36} content={renderLegend} />
            {/* card_background_color */}
            {/* MA7 */}
            <Line type="linear" dot={false} dataKey="MA7" strokeWidth={2} stroke="var(--auxiliary_01_color)" />
            {/* MA14 */}
            <Line type="linear" dot={false} dataKey="MA14" strokeWidth={2} stroke="var(--sell_down_color)" />
            {/* AVERAGE */}
            <Line
              type="linear"
              dot={false}
              dataKey="AVERAGE"
              stroke="var(--buy_up_color)"
              strokeWidth={2}
              strokeDasharray="6 4"
            />
            <Area
              type="linear"
              dot={false}
              dataKey={currentType}
              fill="var(--auxiliary_01_color_trans_bg)"
              strokeWidth={2}
              stroke="var(--auxiliary_01_color_animate)"
            />
            {/* 柱状图 */}
            {/* <Bar dataKey="pv" barSize={20} fill="#413ea0" /> */}
            {/*  */}
            {/* <Scatter dataKey="cnt" fill="red" /> */}
          </ComposedChart>
        </ResponsiveContainer>

**Comment by LukeAntarctic** [comment]
As the screen scales and drags, the offset becomes increasingly noticeable

**Comment by ckifer** [comment]
Hi, would you be willing to create a reproduction in codesandbox?

**Comment by LukeAntarctic** [comment]
@ckifer look this https://codesandbox.io/p/devbox/rechartsdemo-j9yzr6?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm04pie8x00073b79cufpce04%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm04pie8w00023b79t09t4lg8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm04pie8w00043b79y9wrr6ea%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm04pie8x00063b795umv2imq%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm04pie8w00023b79t09t4lg8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm04pie8w00013b799cobqiga%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522cm04pie8w00023b79t09t4lg8%2522%252C%2522activeTabId%2522%253A%2522cm04pie8w00013b799cobqiga%2522%257D%252C%2522cm04pie8x00063b795umv2imq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm04pie8w00053b79wgmeyngl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%257D%255D%252C%2522id%2522%253A%2522cm04pie8x00063b795umv2imq%2522%252C%2522activeTabId%2522%253A%2522cm04pie8w00053b79wgmeyngl%2522%257D%252C%2522cm04pie8w00043b79y9wrr6ea%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm04pie8w00033b79eyfqjw6v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522cm04pie8w00043b79y9wrr6ea%2522%252C%2522activeTabId%2522%253A%2522cm04pie8w00033b79eyfqjw6v%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by ckifer** [comment]
Sorry I haven't had time to look at this yet but ill try to check it today

**Comment by ckifer** [comment]
Hi, your codesandbox does not exist or does not have its permissions set to public

```
Error: Error: (404) Not found
Version: 0.0.355
Environment: production
```

**Comment by LukeAntarctic** [comment]
@ckifer look this https://codesandbox.io/p/devbox/rechartsdemo-j9yzr6?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm04pie8x00073b79cufpce04%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm04pie8w00023b79t09t4lg8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm04pie8w00043b79y9wrr6ea%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm04pie8x00063b795umv2imq%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm04pie8w00023b79t09t4lg8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm04pie8w00013b799cobqiga%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm04pie8w00023b79t09t4lg8%2522%252C%2522activeTabId%2522%253A%2522cm04pie8w00013b799cobqiga%2522%257D%252C%2522cm04pie8x00063b795umv2imq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm04pie8w00053b79wgmeyngl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%257D%255D%252C%2522id%2522%253A%2522cm04pie8x00063b795umv2imq%2522%252C%2522activeTabId%2522%253A%2522cm04pie8w00053b79wgmeyngl%2522%257D%252C%2522cm04pie8w00043b79y9wrr6ea%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm04pie8w00033b79eyfqjw6v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522cm04pie8w00043b79y9wrr6ea%2522%252C%2522activeTabId%2522%253A%2522cm04pie8w00033b79eyfqjw6v%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by ckifer** [comment]
this is because of `scale="band"` on your XAxis. Remove that and everything has the correct offset

**Comment by LukeAntarctic** [comment]
@ckifer Its OK Thanks bro !
