### ISSUE TITLE
Warning XAxis, Warning: YAxis

### ISSUE THREAD

**Issue by Lenur29** [recharts/recharts#4916]
React shows these warnings in the browser console in development mode. Are you going to fix it in the future release?

"Warning: XAxis: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead."
Warning: YAxis: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead

**Comment by ckifer** [comment]
Please upgrade to the latest alpha version

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/issues/3615

Going to close this as a duplicate

**Comment by Lenur29** [comment]
@ckifer Hi. Thank you for your response. Is the latest alpha version this one - https://www.npmjs.com/package/recharts/v/2.13.0-alpha.4

**Comment by ckifer** [comment]
Yes
