### ISSUE TITLE
How to fix the tooltip near the highest point?

### ISSUE THREAD

**Issue by svidskiy** [recharts/recharts#4919]
How can I position the tooltip near the highest point? And it's important that the tooltip doesn't extend beyond the chart boundaries.

![image](https://github.com/user-attachments/assets/c35f81d8-7b22-49f6-a164-f74c18e623a7)

**Comment by ckifer** [comment]
What do you mean by the highest point? Whichever line has the higher value at a given X value? Or just just at the max Y of the chart container?

**Comment by svidskiy** [comment]
> What do you mean by the highest point? Whichever line has the higher value at a given X value? Or just just at the max Y of the chart container?

The highest point by value, yes. In the screenshot, you can see that the highest point is marked in blue. I want to implement the logic so that the tooltip appears fixed near this point within the chart, allowing it to adapt accordingly. Any changes to the position with a custom setting break the **allowEscapeViewBox** logic. Additionally, there's a small issue: the coordinates of the points are missing in the tooltip's content props, and they can only be obtained through the **activeDot** in the **Line**. This leaves me unsure of how to position the tooltip near the point.

**Comment by ckifer** [comment]
> allowEscapeViewBox logic

If you are providing custom tooltip positions, there is no allowEscapeViewBox logic. That only applies when calculating tooltip positions automatically.

>  do so using chartRef.current.state.formattedGraphicalItems. However, its type is any...

This is dangerous, unsupported territory which won't exist in 3.x. This library was written originally without TS and some types never got correctly implemented, such as `formattedGraphicalItems`. Its also internal state, which generally you shouldn't be able to access.

You'll have to either be ok with accessing something that is potentially unstable, or not do this.

---

From my perspective, for the current state recharts is in what you have is the best you're going to be able to get.

In 3.0 we plan to expose hooks that will easily give you information such as `points`, `offset`, etc. so you don't have to reach into our internal state and risk relying on something that will break.

**Comment by svidskiy** [comment]
Thank you, so I had to coordinate at work to have this task postponed for now
