### ISSUE TITLE
Question: aligning graphs in a composed chart

### ISSUE THREAD

**Issue by sonofjack** [recharts/recharts#492]
Is it possible within composed charts to align points with an `area` chart and a `bar` chart.
The following screenshot illustrates the points I am trying to align.

![image](https://cloud.githubusercontent.com/assets/323731/22486029/f07776a4-e85b-11e6-9d5a-296aa6da1871.png)

Does anyone know if this is possible with recharts, or could point me in right direction of how to achieve a similar result.

Love the project, many thanks.

**Comment by xile611** [comment]
@sonofjack  Maybe you can use customized shape of `Bar.
