### ISSUE TITLE
Change styles of a Brush component

### ISSUE THREAD

**Issue by matheusml** [recharts/recharts#493]
After reading the DOCs of the Brush Component, [http://recharts.org/#/en-US/api/Brush](http://recharts.org/#/en-US/api/Brush)
I did not find a way to change the styles of the component, even with pure CSS.

Is there a way to do that?

Thanks!

**Comment by xile611** [comment]
@matheusml You can change the `stroke`  of `Brush` like [this example](http://recharts.org/#/en-US/examples/BrushBarChart). Or you can change the style of `Brush` by css.

**Comment by micktg** [comment]
How can you style the background of the stroke? I tried `fill `but it does change the background and the foreground of the brush. `fillOpacity `does not have any effect. 
Any hints for me?
