### ISSUE TITLE
Strict Type Constraint on `AxisDomain` in `YAxis` and `XAxis` Components

### ISSUE THREAD

**Issue by emrecancorapci** [recharts/recharts#4937]
## Do you want to request a feature or report a bug?

Request a feature

## What is the current behavior?

The `domain` property in `YAxis` and `XAxis` components allows values like `[0, 'dataMax+5']`, but the `AxisDomain` type currently prevents this usage by causing type errors.

## What is the expected behavior?

The `AxisDomain` type should be flexible enough to accept expressions like `[0, 'dataMax+5']` without triggering type errors, allowing developers to define more dynamic domains.

_Also, I would like to be assigned to this issue if possible._

**Comment by ckifer** [comment]
Hi! As far as I know this should work today.. what error are you getting?

**Comment by emrecancorapci** [comment]
@ckifer This error: 
```
Type '(string | number)[]' is not assignable to type 'string[]'.
```

**Comment by ckifer** [comment]
![image](https://github.com/user-attachments/assets/5233b3eb-aa70-42aa-887e-1159ee2c5e73)

this should be satisfied by the AxisDomainItem prop. Are you using the latest version of recharts?

Sandbox here with no error https://codesandbox.io/p/sandbox/line-chart-width-xaxis-padding-forked-222227

**Comment by PavelVanecek** [comment]
Ha I suspect that this is because the AxisDomainItem is a tuple. @emrecancorapci if you add `as const` does that help?

**Comment by emrecancorapci** [comment]
Yes it is the latest.

![image](https://github.com/user-attachments/assets/71856cd7-9d52-4c61-b9a1-641b1b2902f9)

This works but without `as [AxisDomainItem, AxisDomainItem]` it gives the error. Or if I change the type like this error dissappear:

```
export type AxisDomain = (number | string)[] | [AxisDomainItem, AxisDomainItem] | (([dataMin, dataMax]: [number, number], allowDataOverflow: boolean) => [number, number]);
```

**Comment by PavelVanecek** [comment]
Hm our stories have this and it works without errors: `<XAxis type="number" domain={[0, 'dataMax + 1000']} />`. Can you please share your typescript version, and your tsconfig?

**Comment by PavelVanecek** [comment]
Hold on, this is `yAxisDomain` and not `domain`. Where are you passing this property?

**Comment by emrecancorapci** [comment]
@PavelVanecek Typescript is 5.5.4

tsconfig.json

```json
{
  "compilerOptions": {
    "lib": ["ESNext", "DOM", "DOM.Iterable"],
    "target": "ESNext",
    "module": "ESNext",
    "moduleDetection": "force",
    "useDefineForClassFields": true,
    "skipLibCheck": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",

    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noUncheckedIndexedAccess": true,
    "noFallthroughCasesInSwitch": true,
    "noPropertyAccessFromIndexSignature": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    },
  },
  "include": ["src", "vite.config.ts", "tsconfig.node.json", "tailwind.config.ts"],
  "references": [{ "path": "./tsconfig.node.json" }]
}

```

tsconfig.node.json

```json
{
  "compilerOptions": {
    "composite": true,
    "skipLibCheck": true,
    "module": "ESNext",
    "moduleResolution": "bundler",
    "allowSyntheticDefaultImports": true
  },
  "include": ["vite.config.ts"]
}
```

This is the component:

```tsx
import { useState } from 'react';
import { CartesianGrid, Label, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

import mockData from '@/assets/mock_data.json';
import sensors from '@/assets/mock-sensors';
import ChartTooltip from '@/components/ui/chart-tooltip';
import { useChartControllerStore } from '@/stores/chart-controller-store';

const formattedData = mockData
  .map((data) => ({
    ...data,
    time: new Date(data.time).toUTCString(),
    timeAxis: new Date(data.time).toLocaleTimeString('tr-TR', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: false,
    }),
  }))
  .sort((a, b) => a.time.localeCompare(b.time));

const initialState = {
  chartMarigin: {
    top: 5,
    right: 30,
    left: 20,
    bottom: 20,
  },
  xAxisDomain: ['dataMin', 'dataMax'],
  yAxisDomain: [0, 'dataMax+5'],
};

const strokes = ['#82ca9d', '#8884d8', '#823afd', '#f88488', '#c2ca5d', '#7ab4f8'];

export default function Chart() {
  const visibleValues = useChartControllerStore((state) => state.visibleValues);

  const [chartState] = useState(initialState);

  return (
    <ResponsiveContainer>
      <LineChart width={1200} height={600} data={formattedData} margin={chartState.chartMarigin}>
        <CartesianGrid fill="#222" opacity={0.2} />
        <XAxis domain={chartState.xAxisDomain} dataKey="timeAxis">
          <Label value="Time" position="insideBottom" offset={-10} />
        </XAxis>
        <YAxis domain={chartState.yAxisDomain} />
        <Tooltip content={<ChartTooltip />} />
        <Legend verticalAlign="top" height={42} />

        {sensors.map((sensor, index) => (
          <Line
            key={sensor.id}
            type="monotone"
            hide={!visibleValues.has(sensor.short)}
            dataKey={sensor.short.toLowerCase()}
            name={sensor.name}
            stroke={strokes[index]}
            strokeWidth={2}
            unit={sensor.unit}
          />
        ))}
      </LineChart>
    </ResponsiveContainer>
  );
}

```

**Comment by ckifer** [comment]
I can reproduce 
https://codesandbox.io/p/sandbox/line-chart-width-xaxis-padding-forked-222227

The domain is being passed as configuration which makes the type be inferred as 
`(string | number)[]` rather than a tuple. 

Since we allow explicit domain of all strings or all numbers TS can't tell the difference here.

If you add your domain explicitly to the XAxis, it works fine.

Imo you should type your state rather than having it be implicit

```tsx
type InitialState = {
  yAxisDomain: [number, string]
}

const initialState: InitialState = {...}
```

From there you can do what you'd like with that type as long as its within the bounds of `AxisDomainItem`

**Comment by PavelVanecek** [comment]
I will add that the `as const` doesn't work because Recharts requires that the domain is mutable array (even though it never actually tries to mutate it) which is another improvement we should make.

**Comment by ckifer** [comment]
It looks like we started to do that in 3.x
https://github.com/recharts/recharts/blob/3.x/src/util/types.ts#L1097-L1101

**Comment by emrecancorapci** [comment]
I saw types changed to ReadyonlyArray in 3.x.

**Comment by ckifer** [comment]
I'll leave this open until `AxisDomainItem` is also made readonly in 3.x (as this is where the error shows when using `as const`
