### ISSUE TITLE
Grouping components

### ISSUE THREAD

**Issue by alexggordon** [recharts/recharts#494]
Hello, 

So I've been evaluating recharts, and after browsing through the code and the documentation, I've been unable to find anything about grouping components. I was curious if there was any way to do this, especially with a bar chart. 

Essentially I'd just like to be able to group bar elements, so you could have:

```
| 123   456   789 | 123   456   789 |
|_________________|_________________|
```

Really, all this would require is the ability to pad each bar element differently from the center tick mark, so this may exist, but I couldn't find anything about it. Any thoughts on how to do this, or if it can be accomplished?

**Comment by xile611** [comment]
@alexggordon I can't quite understand your demands now. Can you provide an example?

**Comment by alexggordon** [comment]
Sorry for the slow response. In the event of grouped data, say car types, I'd like to display them together, but a little separated. 

E.G, Cars Purchased
Honda = { accord: [{x: Tuesday, y: 4}, {x: Wednesday, y: 9}], civic: [{x: Tuesday, y: 2}, {x: Wednesday, y: 7}] }
Ford = { explorer: [{x: Tuesday, y: 2}, {x: Wednesday, y: 9}], {focus: [{x: Tuesday, y: 2}, {x: Wednesday, y: 9}] }
Toyota = { camry: [{x: Tuesday, y: 18}, {x: Wednesday, y: 19}], prius: [{x: Tuesday, y: 2}, {x: Wednesday, y: 19}] }

Below is a silly photoshop example of roughly what I'm asking for. Kind of a group for a single x-axis day. 

![image](https://cloud.githubusercontent.com/assets/2700571/23382088/ee297344-fd0e-11e6-8c77-0b219a25f536.png)

Does this clarify the needs?

**Comment by xile611** [comment]
@alexggordon 

If you want to group the ticks, you can use customized tick of `XAxis` like [this demo](http://jsfiddle.net/o0ag2nz3/);

And in your case, I think you can format the data and render the charts like [this demo](http://jsfiddle.net/zh3z3znq/).

<img width="591" alt="2017-02-28 2 28 20" src="https://cloud.githubusercontent.com/assets/6111424/23394108/33ed552c-fdc2-11e6-8670-9e88cb7ef8d2.png">

**Comment by alexggordon** [comment]
Yeah, I think that should work. Thanks!
