### ISSUE TITLE
Plot two time series with differing time frames

### ISSUE THREAD

**Issue by alexanderwhatley** [recharts/recharts#495]
Is there a way to plot multiple time series with differing time frames? For example:

```
const ts1 = [{x: "01/07/17", y: 20}, {x: "01/14/17", y: 30}, {x: "01/21/17", y: 40}]
const ts2 = [{x: "01/20/17", y: 60}, {x: "01/27/17", y: 20}, {x: "02/03/17", y: 100}]
```

**Comment by xile611** [comment]
@alexanderwhatley You can create two `XAxis`.

**Comment by alexanderwhatley** [comment]
Sorry, could you be more explicit please? Right now, there does not appear to be a way to pass differing data elements into two different X-axes. Do you think you could give an example using the above data? Thank you.

**Comment by alexanderwhatley** [comment]
I tried the following code, but all I got was a blank grid:

```
			<ScatterChart width={600} height={400} margin={{top: 20, right: 20, bottom: 20, left: 20}}>
				<XAxis xAxisId={0} dataKey='x'/>
				<XAxis xAxisId={1} dataKey='x'/>
				<YAxis dataKey='y'/>
				<CartesianGrid />
				<Tooltip cursor={{strokeDasharrasales: '3 3'}}/>
				<Legend/>
				<Line xAxisId={0} name={"Hi1"} data={ts1} dataKey={'y'} fill={'#8884d8'}/>
				<Line xAxisId={1} name={"Hi2"} data={ts2} dataKey={'y'} fill={'#8884d8'}/>
			</ScatterChart>
```

**Comment by AdamU34** [comment]
@xile611 @alexanderwhatley I have similar issue in composedChart (see the issue here: https://github.com/recharts/recharts/issues/2983). Have you resolved this issue?
