### ISSUE TITLE
TimeScale data rendering wiggles

### ISSUE THREAD

**Issue by ceyxasm** [recharts/recharts#4957]
## Do you want to request a feature or report a bug?
Report a bug.

## What is the current behavior?
Timescale data rendering is wiggling. Something like this: https://bost.ocks.org/mike/path/
```
                {chartData.length > 0 && (
                    <ResponsiveContainer width="100%" height={400}>
                        <LineChart data={chartData}>
                            <CartesianGrid strokeDasharray="3 3"/>
                            <XAxis dataKey="time"/>
                            <YAxis/>
                            <Tooltip/>
                            <Legend/>
                            <Line type="linear" dataKey="valence" stroke="#A6A6A6"/>
                            <Line type="linear" dataKey="arousal" stroke="#2975B0"/>
                        </LineChart>
                    </ResponsiveContainer>
                )}  
```
My chartData gets updated every second.

## What is the expected behavior?
The solution I want is already explained here: `https://bost.ocks.org/mike/path/`
But how should I apply that solution to recharts.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
OS/Browser: agnostic
Recharts version:     "recharts": "^2.12.7",

**Comment by bragle** [comment]
This issue is already tracked at #1961

**Comment by ckifer** [comment]
Sounds good, closing as a duplicate
