### ISSUE TITLE
Render different content on ScatterChart's tooltip

### ISSUE THREAD

**Issue by lucasbento** [recharts/recharts#497]
Is there a way to render a different content on ScatterChart's tooltip? I want to show a simple `name` there.

If there isn't, would you like a PR to add a solution for it? Something like a method passed through a prop to return a simple `<div />`.

**Comment by methodmain** [comment]
@lucasbento Here's what I have done. First, when creating my chart data I add the necessary data - the x,y values - but you can also include anything like an object.
`data: [
{
x: 1,
y: 2,
obj: {foo:bar}
}
]`

Then I have:
`<Tooltip content={ this.renderTooltip }/>`

renderTooltip is passed params that include a payload, which will contain x,y, and obj.

**Comment by lucasbento** [comment]
@methodmain: that's great, didn't see that prop, thank you!
