### ISSUE TITLE
[Bug] Chart shows nothing when XAxis type is number and there is only 1 item in data array

### ISSUE THREAD

**Issue by anthonyma94** [recharts/recharts#4974]
When using `type="number"` on the x axis, the bar graph doesn't generate bars when there is only 1 item in the data array.

Code taken and changed from [simple bar chart example](https://recharts.org/en-US/examples/SimpleBarChart) on Recharts website.

```tsx
import React, { PureComponent } from 'react';
import { BarChart, Bar, Rectangle, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';

const data = [
  {
    name: 1,
    uv: 4000,
    pv: 2400,
    amt: 2400,
  }
];

export default class Example extends PureComponent {
  static demoUrl = 'https://codesandbox.io/p/sandbox/simple-bar-chart-72d7y5';

  render() {
    return (
      <ResponsiveContainer width="100%" height="100%">
        <BarChart
          width={500}
          height={300}
          data={data}
          margin={{
            top: 5,
            right: 30,
            left: 20,
            bottom: 5,
          }}
        >
          <CartesianGrid strokeDasharray="3 3" />
          <XAxis dataKey="name" type="number" /> /** remove type="number" and it shows the bars */
          <YAxis />
          <Tooltip />
          <Legend />
          <Bar dataKey="pv" fill="#8884d8" activeBar={<Rectangle fill="pink" stroke="blue" />} />
          <Bar dataKey="uv" fill="#82ca9d" activeBar={<Rectangle fill="gold" stroke="purple" />} />
        </BarChart>
      </ResponsiveContainer>
    );
  }
}
```

**Comment by ckifer** [comment]
I'm confused, this is because your XAxis dataKey "name" is not numerical data

**Comment by anthonyma94** [comment]
@ckifer sorry I forgot to change the value, the example has been updated.

**Comment by ckifer** [comment]
Generally, the XAxis of a bar chart should be categorical data. In the case that it isn't, you need to adjust what scale is being used.

Try changing scale to `scale="band"`

https://codesandbox.io/p/sandbox/simple-bar-chart-forked-ww5wpm

**Comment by ckifer** [comment]
Feel free to contribute if you'd like! Theres also the storybook
https://master--63da8268a0da9970db6992aa.chromatic.com/?path=/docs/api-cartesian-xaxis--docs
