### ISSUE TITLE
Series data for BarChart with multiple X-Axis

### ISSUE THREAD

**Issue by ledfordtj** [recharts/recharts#4975]
## Do you want to request a feature or report a bug?
report a bug (possible feature request)

## What is the current behavior?
Using the BarChartWithMultiXAxis example, if you update the dataset to be a series (like in LineChartHasMultiSeries example) then the second X-axis component (the one that creates the quarter split) is no longer rendered. I saw in a previous issue you mentioned to use an XAxisId on each bar to correspond with the X-Axis component, this works, but this requires two bars for the same dataset to have an id for each X-Axis component. This duplicates the dataset in the tooltip as well as the legend. You can disable duplicate categories in the legend, but not in the tooltip (that I found). 

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via codesandbox or similar (template: https://codesandbox.io/p/sandbox/simple-line-chart-v25dl4).
https://codesandbox.io/p/sandbox/bar-chart-with-double-xaxis-forked-y42st4

## What is the expected behavior?
My goal is to have something exactly like the BarChartWithMultiXAxis example except I am wanting multiple bars for each x-axis data point. For the example in the sandbox, I have the two bars from the series but the second x-axis component is not being rendered. I want to it render.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
2.12.6^, Chrome, not that I am aware of.

**Comment by ckifer** [comment]
hi

`Bar` does not support data on the individual `Bar` items at this point.

For now I would combine your data to be of the shape

```
{
  "pv": 100,
  "amt: 200,
  "date": "2000-07"
}
```

And then you'll be able to do exactly as in the example

**Comment by ledfordtj** [comment]
Unfortunately, I am needing the series dataset so I can elegantly name the bar for each split. Would love to see this possible in the bar chart, but I am not sure that it will be a feature that can be implemented in time for me to use. You can consider this closed. Thanks @ckifer 

> hi
> 
> `Bar` does not support data on the individual `Bar` items at this point.
> 
> For now I would combine your data to be of the shape
> 
> ```
> {
>   "pv": 100,
>   "amt: 200,
>   "date": "2000-07"
> }
> ```
> 
> And then you'll be able to do exactly as in the example

Unfortunately, I am needing the series dataset so I can elegantly name the bar for each split. Would love to see this possible in the bar chart, but I am not sure that it will be a feature that can be implemented in time for me to use. You can consider this closed. Thanks @ckifer

**Comment by ckifer** [comment]
Thanks for trying! We're undergoing a ton of refactoring right and that makes making changes like this one difficult until it's over. 

This may still be possible, just not straightforward. I'll leave it open for a bit and see if anyone else has any suggestions

**Comment by ckifer** [comment]
I am mistaken on the `data` support that I mentioned above. `data` only does not work on `Bar` if there is not `data` on `BarChart`

You could just make a custom tooltip to unique your payload. But you've probably moved on by now, going to close this
