### ISSUE TITLE
<XAxis> does not show end domain value when 'preserveStartEnd'

### ISSUE THREAD

**Issue by oluckyman** [recharts/recharts#498]
Here is the data:
```
const A = -4.52;
const B = 6.34;
const data = [
  { name: 'Page G', uv: A, pv: B, },
];
```
Here is example of `render` with redundant code removed:
```
    return (
      <BarChart
        width={width}
        height={height}
        margin={margin}
        data={data}
        stackOffset='sign'
        layout='vertical'
      >
        <XAxis
          domain={[A, B]}
          type='number'
          interval='preserveStartEnd'
        />
        <Bar
          dataKey='pv'
          stackId='stack'
        />
        <Bar
          dataKey='uv'
          stackId='stack'
        />
      </BarChart>
```
`interval` prop with `preserveStart` and `preserveStartEnd` works as expected for `A` value of domain. But `B` value of domain is always missing regardless of `interval` setting.
![image](https://cloud.githubusercontent.com/assets/642673/22602676/71ed6f38-ea44-11e6-9874-c8625030da1d.png)

What I expect on the picture above is that on the far right `$6.34` tick will be shown.
How can I ensure that both `A` and `B` values of domain are presented on the chart?

**Comment by xile611** [comment]
@oluckyman Can you create a jsfiddle demo ?

**Comment by oluckyman** [comment]
here http://jsfiddle.net/xx835b1o/7/

**Comment by xile611** [comment]
[demo](http://jsfiddle.net/6eawhfvr/)

When you specify the `domain` and [`tickCount`](https://github.com/recharts/recharts/blob/master/src/cartesian/YAxis.js#L75) of  `YAxis`, we can't calculate evenly distributed ticks, so no `end` tick here.

@oluckyman You can check the [documentation of d3-scale](https://github.com/d3/d3-scale#continuous_ticks).

**Comment by oluckyman** [comment]
thanks. But how to configure the chart to show begin and end values of the domain so that           `interval='preserveStartEnd'` works as expected?

**Comment by xile611** [comment]
@oluckyman You can change the `tickCount` of `YAxis`.
