### ISSUE TITLE
TickCount in XAxis doesnt'w work

### ISSUE THREAD

**Issue by michalg42** [recharts/recharts#50]
Hello
When modifying tickCount nothing changes - there are always 6 ticks. Also as I checked code - default value for tickCount is 5, but it displays 6 ticks.

**Comment by xile611** [comment]
When `XAxis` is a category axis, `tickCount` won't affect the count of ticks.

**Comment by itsdeezy** [comment]
@xile611 
Can we remove `tickCount` from the API doc for `XAxis` then?

**Comment by tommilligan** [comment]
@itsdeezy PR https://github.com/recharts/recharts.org/pull/66 submitted if you want to add anything.
