### ISSUE TITLE
errors in math-expression-evaluator

### ISSUE THREAD

**Issue by mvolkmann** [recharts/recharts#501]
Just importing from recharts gives me lots of errors from node_modules/math-expression-evaluator/src/lexer.js. All the errors are about the variables "i", "x", and "y" being undefined. Is anyone else seeing this? Maybe that dependency is currently broken.

**Comment by xile611** [comment]
@mvolkmann Please show more informations.

**Comment by mvolkmann** [comment]
I can't reproduce this now, so I'm closing it. Sorry for the noise.
