### ISSUE TITLE
Brush component styling

### ISSUE THREAD

**Issue by adearmas** [recharts/recharts#502]
After customizing the x axis bar "labels" to turn them on an angle, as shown [here](http://recharts.org/#/en-US/examples/CustomizedLabelLineChart) , the brush is rendered on top of some portion of the longer labels.

Unfortunately there is no way that I have come across to move the brush down, or even placing it on top of the chart. How can I do this?

If i update the "y" in the developer tools of the browser, it seems to move the brush, however, changing the "y" prop for the brush component does not have the same results.

I have to say, I really do love this library for ease of use. However, the custom styling of most of these components is a nightmare, and should possibly be rethought, and reworked, as style should not be forced to be the way the creator of the library thinks it should be. 

I updated the fiddle in your example to show the [issue](http://jsfiddle.net/97oecp4k/)

**Comment by xile611** [comment]
@adearmas Yeah, customized components of some components, like label, shape, .etc, seems to be complex now. But it's a necessary part to implement complex charts, we'll try to simplify some simple styling. 

About your case, you can use an object to style the ticks:

```jsx
<XAxis dataKey="name" height={60} tick={{ angle: -35, textAnchor: 'end' }} />
```

And you can move the brush down by adjusting the `height` of `XAxis` which have default value 30.

[api of XAxis](http://recharts.org/#/en-US/api/XAxis)
[demo](http://jsfiddle.net/97oecp4k/2/)
