### ISSUE TITLE
`ResponsiveContainer` does not make `<.*Chart />` inherit of parent size

### ISSUE THREAD

**Issue by younes101020** [recharts/recharts#5023]
## Do you want to request a feature or report a bug?

Yes

## What is the current behavior?

Hello, i have to explicitly specify a width + height to the BarChart component for it to appear, otherwise it won't even appear in the DOM

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via codesandbox or similar (template: https://codesandbox.io/p/sandbox/simple-line-chart-v25dl4).

https://codesandbox.io/p/devbox/sad-jackson-7hzp4x?workspaceId=6446d276-4670-4ba1-991e-87820b582250

## What is the expected behavior?

BarChart component should inherit from parent div size

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

DEP: 
* rechart: 2.12.7, alpha.(2 to 5)
* next: 15.0.0-rc.0
* react: 19.0.0-rc-a99d8e8d-20240916
* react-dom: 19.0.0-rc-a99d8e8d-20240916

OS: 
* Distributor ID: Ubuntu
* Description:    Ubuntu 22.04.3 LTS
* Release:        22.04
* Codename:       jammy

> **_NOTE:_** Im also using shadcn ChartContainer container as parent in which i've set min-h-[200px] + w-full

**Comment by ckifer** [comment]
You will have to specify either a static height or a static width as mentioned in the docs. SVGs need absolutes in order to know how to render. 

ResponsiveContainer should allow you to specify "100%" for width and your chart will still show up. 

On mobile for the moment but I'll check your sandbox in a bit, thanks

**Comment by younes101020** [comment]
Set width to 100% on ResponsiveContainer change nothing :/

**Comment by ckifer** [comment]
Ah then this most likely has nothing to do with `ResponsiveContainer`

It looks like you didn't override your `react-is` version. `react-is` dependencies need to match the React version in R19 
see https://github.com/recharts/recharts/issues/4558#issuecomment-2135604065

**Comment by ckifer** [comment]
Looks like that was the issue 
https://codesandbox.io/p/devbox/objective-pine-kpqwkj?workspaceId=7a1754d3-b261-47b1-9339-2aca93020961

**Comment by ckifer** [comment]
Going to close this as resolved - let me know if you have any questions. Alpha releases are unstable and undocumented which makes idiosyncrasies like this one hard to find/know about in advance. Will try to make it clear in the 2.13 release!

Thanks

**Comment by younes101020** [comment]
i had already tried to override the react-is package locally but nothing happened

small mistake on my part when setting up the codesandbox I didn't correctly reflect my local package.json, the only difference being the version of nextjs I have on “15.0.0-canary.152” locally and it's on the rc in the codesandbox

https://codesandbox.io/p/devbox/objective-pine-kpqwkj

**Comment by ckifer** [comment]
canary releases are inherently unstable and are not guaranteed to be supported by recharts or any other library.

But I'll take a look. It looks like you linked my sandbox back to me. Do you have a different link?

**Comment by ckifer** [comment]
Updated the same sandbox (https://codesandbox.io/p/devbox/objective-pine-kpqwkj) to the canary release mentioned and the chart still renders.

I would try deleting `node_modules` and re-installing, you could have something cached

**Comment by younes101020** [comment]
deleting the `package-lock.json` reproduce the issue, since im using pnpm i have no need of this file :/

**Comment by ckifer** [comment]
`overrides` is a package manager specific feature

please see https://github.com/recharts/recharts/issues/4558#issuecomment-2258530049

> for pnpm use https://pnpm.io/package_json#pnpmoverrides rather than overrides

**Comment by younes101020** [comment]
Thats works, skill issue thank you for your time
