### ISSUE TITLE
Get value of X axis on hover.

### ISSUE THREAD

**Issue by ceyxasm** [recharts/recharts#5028]
Hey I want to get the value of X axis of the current point I am hovering on in a variable. 
![image](https://github.com/user-attachments/assets/a5189f16-894d-4151-b9c6-2793ef18e4ab)
Here the value of X axis at the point is **18:56:48** but I want to be able to update and set a variable with this value; (for generating and displaying further information I have for the given instance).
How can I do this?

Great work btw.

**Comment by ckifer** [comment]
You can use the onMouseOver event on the graphical element to get most information

**Comment by ckifer** [comment]
let me know if this didn't answer the question but I'm going to close this for now
