### ISSUE TITLE
Legend styling

### ISSUE THREAD

**Issue by adearmas** [recharts/recharts#503]
Unfortunately, again, styling seems to be an issue with this library. I will have an extremely long legend in some cases, and would like to have the legend to the right of the chart, and listed vertically. However, using the "align" => right and "verticalAlign" => middle props for the legend the legend appears to the right, and in the middle. However, its ON THE CHART, when I would expect it to be OFF the chart to the right. 

Here is the updated fiddle to show my [issue](http://jsfiddle.net/8a0rttnL/)

**Comment by WalkOffEarth** [comment]
here you go ithink you want this http://jsfiddle.net/8a0rttnL/1/

**Comment by adearmas** [comment]
Well, thank you! This seems to work.
