### ISSUE TITLE
XAxis & YAxis: Support for defaultProps will be removed from function components in a future major release.

### ISSUE THREAD

**Issue by LerchT** [recharts/recharts#5033]
##Updating report for AxisX and AxisY

Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

I work with Nextjs 14.2.13 and Electron.

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/issues/3615#issuecomment-2135955727

Please install the latest alpha version. 

Closing as a duplicate
