### ISSUE TITLE
Reference Area does not cover the correct range in the Scatter Plot when a String Value is provided.

### ISSUE THREAD

**Issue by reshmarevi-kv** [recharts/recharts#5046]
Bug Report:
In the scatter plot, when configuring a reference area, providing a string value (instead of a number) for either the x or y axis results in incorrect behavior. The reference area is not rendered correctly on the chart. This issue has been tested in a line chart, where it works as expected.

Demo:
Check out this demo to see the issue in action: [CodeSandbox](https://codesandbox.io/p/sandbox/ghw3nt)

In this example, the x1 as '120' and x2 as '140' , but the reference area extends beyond that specified value.

Expected behaviour:

The reference area should be rendered correctly based on the specified x and y ranges, whether the values are strings or numbers.

**Comment by ckifer** [comment]
Can I ask why you are using strings when your strings are numbers?

**Comment by reshmarevi-kv** [comment]
That's just an example only, basically for category values it's not working

**Comment by reshmarevi-kv** [comment]
There will come the cases where the axis have category values, instead of
numeric values right. In that case it's breaking. Hope it's clear now

**Comment by ckifer** [comment]
you need to change the scale of the `XAxis`

Scatter charts are not generally made with categorical data so the auto scale does not necessarily behave how you would like in this case. Changing the scale to point works

```
<XAxis type="category" dataKey="x" scale="point" />
```

**Comment by ckifer** [comment]
Going to close this as resolved, let me know if there are issues
