### ISSUE TITLE
<Text> component and custom label

### ISSUE THREAD

**Issue by kennyx46** [recharts/recharts#505]
Hi, I am trying to add custom labels into the bar chart near the bars.
[http://www.clipular.com/c/6279233242660864.png?k=JETXTDXXrS_rtX3aBNQXtDKhqCk](http://www.clipular.com/c/6279233242660864.png?k=JETXTDXXrS_rtX3aBNQXtDKhqCk)
I have tried to add <Text> element but the  text does not appear. ([http://jsfiddle.net/t4t5rx16/16/](http://jsfiddle.net/t4t5rx16/16/))
 Also I want to place text near the end of each bar, so the x and y position shoud be relative to bar length.  How can I accomplish that?

**Comment by xile611** [comment]
@kennyx46 Please use the `label` props of `Bar` to render labels. [Here] is a demo.
