### ISSUE TITLE
"defaultIndex" out of range throws "Cannot read properties of undefined (reading 'coordinate')"

### ISSUE THREAD

**Issue by Lechevallier** [recharts/recharts#5050]
## Do you want to request a feature or report a bug?

Report a bug

## What is the current behavior?

When affecting to `defaultIndex` an index out of range, I get 

> Cannot read properties of undefined (reading 'coordinate')

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via codesandbox or similar (template: https://codesandbox.io/p/sandbox/simple-line-chart-v25dl4).

minimal demo :

https://codesandbox.io/s/recharts-issue-template-forked-67tgfx?file=/src/index.js

`defaultIndex={0}` won't fail
`defaultIndex={1}` fail

## What is the expected behavior?

Not throwing any error.

Or at least a more understandable one, because I copied/pasted a template from https://ui.shadcn.com/charts, inserted my data, and struggled 1 hour to find where the error were coming from.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

2.12.7

**Comment by ckifer** [comment]
Sorry about this, we should've guarded that little better (and I think we already do). I'll double check

Thanks

**Comment by ckifer** [comment]
Ah this logic is just off by one, but we did try to guard for it

https://github.com/recharts/recharts/blob/106f4631b804a24c06e079ea2dc972add8094eb5/src/chart/generateCategoricalChart.tsx#L1094

CC @julianna-langston

**Comment by ckifer** [comment]
PR up to fix this

**Comment by ckifer** [comment]
Fixed in 2.13
