### ISSUE TITLE
More Interactivity in the charts

### ISSUE THREAD

**Issue by piyushyadav1617** [recharts/recharts#5051]
## What is the expected behavior?
There should be some interactivity like hiding a certain section of chart or in case of composite charts the ability to hide and show a particular chart when we click or hover on legends. Just like how APEXCHARTS provides: [Check here](https://apexcharts.com/react-chart-demos/mixed-charts/multiple-yaxis/)

**Comment by ckifer** [comment]
Hi, this is currently possible with event handlers and the "hide" prop on graphical elements

**Comment by piyushyadav1617** [comment]
> Hi, this is currently possible with event handlers and the "hide" prop on graphical elements

Got it. I think we should add some more examples on such interactions using event handlers.
