### ISSUE TITLE
Add new line to chart during runtime

### ISSUE THREAD

**Issue by ezrnew** [recharts/recharts#5062]
Hey, I have a chart which will initially always have two values like this:

![image](https://github.com/user-attachments/assets/a5932b4d-3890-4585-a80c-27c9ba98db16)

As a user I would like to add new lines (benchmarks) from some predefined dropdown list - Ideally i would only fetch that new benchmark data and append it to the chart - is it possible:
(1) to achieve this behavior on frontend without modifying already existing chart data?
(2) to merge this data at all if benchmarks would have a little bit different timestamps than initial two values (same day but different minutes,seconds)?

**Comment by ckifer** [comment]
Hi, what have you tried and what are your blockers? This is certainly possible.

1. No matter what you'll have to modify the existing data because you'll have to add to it to your data array. This shouldn't cause any disruption to the chart, not sure I understand the concern.

But you can also use `data` on the `Line` item itself.

2. This seems out of scope for `recharts`. It would be your responsibility to merge your own data if it needs to be merged.

**Comment by ckifer** [comment]
Here is an example of adding a new line on click https://codesandbox.io/p/sandbox/line-chart-width-xaxis-padding-forked-n6qwqq

**Comment by ezrnew** [comment]
Hey, the sandbox example only adds line metadata to the chart (dataKey,color), while i need to append actual data (and metadata aswell). The way i asked second question may be misleading, i don't care if data is merged, i just want it to be displayed on the same chart along with the initial data - i managed to achieve that by passing new data to `<Line> `instead of` <LineChart> `as you suggested, and it seems to be displayed correctly on the X axis timestamp, but the tooltip doesnt work properly now because it displays values based on their index. Is it possible to make tooltip "aware" of its timestamp and display most recent values from all lines for a given point (dot)? I added the code below

![image](https://github.com/user-attachments/assets/373680f7-6c08-43e4-9311-1c2cc2af7c36)

```
import moment from 'moment';
import React, { useState } from 'react'
import { Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'



const initialData = [
    {timestamp:"2024-09-01T12:32:57.004Z",value1:1,value2:2,},
    {timestamp:"2024-09-02T12:32:57.004Z",value1:2,value2:3,},
    {timestamp:"2024-09-03T12:32:57.004Z",value1:3,value2:3,},
    {timestamp:"2024-09-04T12:32:57.004Z",value1:4,value2:5,},
    {timestamp:"2024-09-05T12:32:57.004Z",value1:5,value2:6,},

  ]
// @ts-ignore
  initialData.forEach(item => item.timestamp = new Date(item.timestamp).getTime())
  
  const newData = [
      
      {timestamp:"2024-09-01T12:00:00.000Z",benchmark1:5},
      {timestamp:"2024-09-03T12:00:00.000Z",benchmark1:7},
      {timestamp:"2024-09-07T12:00:00.000Z",benchmark1:6},
    ]
 // @ts-ignore   
    newData.forEach(item => item.timestamp = new Date(item.timestamp).getTime())


  interface RechartsLines {
    dataKey: string;
    color: string;
  }

  const intialLines: RechartsLines[] = [
    { dataKey: "value1", color: "#8884d8" },
    { dataKey: "value2", color: "#82ca9d" },
  ];
  

export const RechartsLineChart = () => {

    const [lines, setLines] = useState<RechartsLines[]>(intialLines);
    const [newLines, setNewLines] = useState<any>(null);
    const [data, setData] = useState<any[]>(initialData);


    const addLine = () =>{

        setNewLines((prev:any)=>{


            return           <Line
            key={'benchmark1'}
            type={"monotone"}
            dataKey={"benchmark1"}
            stroke={"blue"}
            dot={false}
            data={newData}
          />
    
          })
    


    }

    const renderLines = () => {
        return lines.map((line) => (
          <Line
            key={line.dataKey}
            type={"monotone"}
            dataKey={line.dataKey}
            stroke={line.color}
            dot={false}
          />
        ));
      };

      const renderNewLines = () => {
        return newLines
      };


  return (
<>
    <button onClick={addLine}>ADD LINE</button>

    <ResponsiveContainer 
    className={"p-6"}
    width="100%"
    height="95%"
    >
    <LineChart data={data}>
      {renderLines()}

      {renderNewLines()}

      <XAxis
        dataKey = 'timestamp'
        domain = {['auto', 'auto']}
        name = 'Time'
        tickFormatter = {(unixTime) => moment(unixTime).format('DD-MM-YYYY')}
        type = 'number'
      />
      <YAxis />


      <Tooltip  />
      <Legend />
    </LineChart>
  </ResponsiveContainer>
      </>
  )
}

```

**Comment by ckifer** [comment]
https://codesandbox.io/p/sandbox/line-chart-width-xaxis-padding-forked-n6qwqq

Adjusted the code to be similar to yours.

The tooltip issue is known but isn't possible to fix right now. We're working on v3 where we're trying to solve things like this.

**Comment by ezrnew** [comment]
Well my main issue has been resolved anyways, for now I think  I will be able to workaround this tooltip by getting same amount of records for benchmark1 as for value1 and value2, as their quantity will always be the same in my case. Thank you Coltin
