### ISSUE TITLE
Conditional Inner and Outer Radius on Pie Cell sections

### ISSUE THREAD

**Issue by JamesTreap** [recharts/recharts#5063]
## Do you want to request a feature or report a bug?
Feature request

## Request
Add the ability to conditionally scale the width of cell sections for pie charts. E.g below I want the red section of the pie chart to be conditionally be larger than the blue and green sections, as seen below:
![image (2)](https://github.com/user-attachments/assets/0f6d1483-b3c3-4f1b-94ad-1186b642bf18)

**Comment by ckifer** [comment]
You should be able to accomplish this using the same approach as this example

https://codesandbox.io/p/sandbox/pie-chart-with-customized-active-shape-forked-lrvrlt

**Comment by ckifer** [comment]
Or, a simplified version of that 
https://codesandbox.io/p/sandbox/pie-chart-with-customized-active-shape-forked-yhmlvt?workspaceId=d53913d8-85a8-463b-9dc1-f7770946ba51

**Comment by JamesTreap** [comment]
> Or, a simplified version of that https://codesandbox.io/p/sandbox/pie-chart-with-customized-active-shape-forked-yhmlvt?workspaceId=d53913d8-85a8-463b-9dc1-f7770946ba51

Ah, thank you! Much appreciated! I just wish the API documentation at https://recharts.org/en-US/api/PieChart included the `activeIndex` and `activeShape` fields. After doing further digging, it seems the WIP storybook component showcases these fields, so it seems the developers are aware of this.

Marking as closed. Have a great day ^^

**Comment by ckifer** [comment]
Yeah, we're working on 3.0 and then we'll work on updating the docs. Sorry for the confusion!
