### ISSUE TITLE
Is there a mirror config on Y axis?

### ISSUE THREAD

**Issue by gabrielfnogueira** [recharts/recharts#507]
I set the orientation of the Y axis to "right" and now I wanna display the tick values inside the chart. I know it is possible on d3, but I did not see any config on the API page (http://recharts.org/#/en-US/api/YAxis).

I know I could create a custom tick component and change the dx value to negative, but this is quite a lot of work to a simple functionality that already exists on d3.

**Comment by xile611** [comment]
@gabrielfnogueira Recharts don't support this feature now.
