### ISSUE TITLE
Text component renders parts with same key 

### ISSUE THREAD

**Issue by dapie** [recharts/recharts#5072]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
If a Text component is rendering a list of words where some words appear multiple times, and each word is assigned as the key for the rendered components, this will cause a React warning because keys must be unique. For example, consider the sentence “Some test line with test behavior,” which is split into individual words: “Some”, “test”, “line”, “with”, “test”, “behavior”. Since the word “test” appears twice, it will result in duplicate keys, causing a console warning in React.

<img width="1320" alt="example" src="https://github.com/user-attachments/assets/6e450a91-8f76-43cd-a8ac-651782a69c77">

After small research I have found that the error comes after this PR https://github.com/recharts/recharts/commit/336d15b9d483fcadd35e2eb73ec0619b68b77f2b, after you started to use words as keys

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via codesandbox or similar.
https://codesandbox.io/p/sandbox/simple-line-chart-forked-jgw8wl

## What is the expected behavior?
There is no error
`Warning: Encountered two children with the same key, '*'. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.`

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Starting from v2.10.2

**Comment by ckifer** [comment]
Yeah its definitely not worth the resulting bugs to make any attempts to keep indexes out of these react keys. That said, adding index back is the fix here for now

**Comment by ckifer** [comment]
PRs merged for this in both branches

**Comment by ckifer** [comment]
fixed in 2.13
