### ISSUE TITLE
Question: how to create Overlapping Bar Chart?

### ISSUE THREAD

**Issue by CMCQuangVo** [recharts/recharts#5073]
![Screenshot 2024-10-03 165538](https://github.com/user-attachments/assets/7e4ea4c1-aa87-4038-89b1-e887ae355612)

**Comment by ckifer** [comment]
You would need to use custom bar `shape` props similar to 
https://recharts.org/en-US/examples/CustomShapeBarChart

**Comment by ckifer** [comment]
Actually even better you can use `barGap` on the `BarChart`
https://codesandbox.io/p/sandbox/simple-bar-chart-forked-hrttgs
<img width="509" alt="image" src="https://github.com/user-attachments/assets/f2c18414-903a-48aa-af9a-c02727ca3fc4">


Going to close this as answered
