### ISSUE TITLE
Cannot test with imported charts

### ISSUE THREAD

**Issue by leggomymeggos** [recharts/recharts#508]
I'm working on a project that's testing with jest and skin-deep. We're trying to test that we've passed the correct data to AreaChart. 

However, when we call `sd.shallowRender(<OurComponent />`, we're seeing that the included `AreaChart` component is fully rendered. This makes it impossible to test, since we don't know exactly where our data will end up. 

Is it possible to not fully render the charts with `sd.shallowRender()`?

**Comment by xile611** [comment]
@leggomymeggos I can't get what do you mean. `AreaChart` is only a normal react component. If `sd.shallowRender(<OurComponent />` return a fully rendered component, It should be the bug of `sd.shallowRender`, not the bug of `AreaChart`.
