### ISSUE TITLE
grafica de maximos y minimos 

### ISSUE THREAD

**Issue by Desetres** [recharts/recharts#5080]
import React from 'react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';

const data = [
  { name: 'Ene', min: 50, max: 80 },
  { name: 'Feb', min: 55, max: 85 },
  { name: 'Mar', min: 60, max: 90 },
  { name: 'Abr', min: 65, max: 95 },
  { name: 'May', min: 70, max: 100 },
  { name: 'Jun', min: 75, max: 105 },
  { name: 'Jul', min: 80, max: 110 },
  { name: 'Ago', min: 85, max: 115 },
  { name: 'Sep', min: 80, max: 110 },
  { name: 'Oct', min: 75, max: 105 },
  { name: 'Nov', min: 70, max: 100 },
  { name: 'Dic', min: 65, max: 95 },
];

const ContaminacionPlasticosChart = () => (
  <ResponsiveContainer width="100%" height={400}>
    <LineChart data={data} margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
      <CartesianGrid strokeDasharray="3 3" />
      <XAxis dataKey="name" />
      <YAxis label={{ value: 'Toneladas de plástico', angle: -90, position: 'insideLeft' }} />
      <Tooltip />
      <Legend />
      <Line type="monotone" dataKey="min" stroke="#8884d8" name="Mínimo" />
      <Line type="monotone" dataKey="max" stroke="#82ca9d" name="Máximo" />
    </LineChart>
  </ResponsiveContainer>
);

export default ContaminacionPlasticosChart;

**Comment by ckifer** [comment]
Hola!

It is unclear what you are asking. What do you need help with?

**Comment by ckifer** [comment]
I'm going to close this because its unclear what the ask is. Please feel free to comment back with more info and I'll see it
