### ISSUE TITLE
XAxis doesn't work with server side rendering

### ISSUE THREAD

**Issue by michalg42** [recharts/recharts#51]
Hello
With client side - everything is working as it should, but when trying to render server side only part that was rendered is horizontal line - labels aren't visible.
Of course because of above problem there is also react warning in console that server side code is different than client side code.

**Comment by xile611** [comment]
Fixed in v0.8.6.
And SSR and CSR is unlikely to be completely consistent. 
For example when you want to render legend in a line chart. The width and height of legend can be calculated in client side, but such calculation can't be done in server side.

**Comment by amnsss** [comment]
SSR and CSR is unlikely to be completely consistent. 
This has fixed？
Weather sometimes there are some warnings: different on server or client, that is Unavoidable?

**Comment by amnsss** [comment]
```
    <LineChart
        width={600}
        height={300}
        data={verData}
        margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
      >
        <XAxis dataKey="time" />
        <YAxis />
        <CartesianGrid strokeDasharray="3 3" />
        <Tooltip />
        <Legend />
        {
          versions && versions.map(ver => (
            <Line type="monotone" dataKey={ver} stroke="#8884d8" activeDot={{ r: 8 }} key={ver} />
          ))
        }
      </LineChart>
```
warning: different on server or client
 (client) idth="490" height="245" stroke="#ccc" fi
 (server) idth="490" height="260" stroke="#ccc" fi
