### ISSUE TITLE
A prop on XAxis and YAxis to enable and disable zooming

### ISSUE THREAD

**Issue by piyushyadav1617** [recharts/recharts#5134]
## What is the current behavior?
no prop for enabling and disabling zooming

## What is the expected behavior?
It would be great and helpful if there was a prop on XAxis and YAxis components for zoom.
currently it requires a lot of manual effort to do this.

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/issues/710

Going to close this as a duplicate
