### ISSUE TITLE
Broken examples links on Pie API page

### ISSUE THREAD

**Issue by coreylenertz** [recharts/recharts#514]
Steps to reproduce:
1. visit the [Pie API page](http://recharts.org/#/en-US/api/Pie)
2. Inspect or click any of the "Example" links.

**A pie chart with customized label**
`http://recharts.org/#/en-USexamples#PieChartWithCustomizedLabel`

It looks like the hash path is missing "/" separators. This issue might also be on other pages.

**Comment by xile611** [comment]
@coreylenertz Thanks! It has been fixed.
