### ISSUE TITLE
Sankey Chart Example?

### ISSUE THREAD

**Issue by alfi-dim** [recharts/recharts#5145]
## What is the expected behavior?
Could you provide an example of a Sankey Chart with custom nodes or links in the documentation?

Thanks!

**Comment by ckifer** [comment]
here you go https://63da8268a0da9970db6992aa-gmkblfiymk.chromatic.com/?path=/story/api-chart-sankey--custom-node-and-link

**Comment by ckifer** [comment]
If someone wants to port that story to the documentation website feel free, but the storybook has more/better examples and may soon replace the examples section on the website (note that this link is the 3.x storybook which is not released, this example should still work though)

**Comment by alfi-dim** [comment]
> here you go https://63da8268a0da9970db6992aa-gmkblfiymk.chromatic.com/?path=/story/api-chart-sankey--custom-node-and-link

Thanks!
