### ISSUE TITLE
feature: add state when hover to Area chart

### ISSUE THREAD

**Issue by HoangVD2** [recharts/recharts#5152]
### What is the expected behavior?
Currently, Area chart is filled with one color. Can we add a state where, when the user hovers over the chart, the left side changes to one color and the right side to another color (as shown in the image)?

| currently | expected |
| - | - |
| <img width="380" alt="Screenshot 2024-10-24 at 10 29 58" src="https://github.com/user-attachments/assets/4dee4b7c-723c-4b0e-9f08-b5137c383ade"> | <img width="409" alt="Screenshot 2024-10-24 at 10 30 17" src="https://github.com/user-attachments/assets/7dbda15b-4981-4126-8c66-da42652ccb6c"> |

**Comment by ckifer** [comment]
You can try to use a linear gradient but positioning might be difficult. Right now that is the only way other than duplicating the chart and trying to manipulate the data points in a way that works for this but that would be a lot of work

**Comment by HoangVD2** [comment]
Thanks!
