### ISSUE TITLE
How can change the active state of an LineChart ? 

### ISSUE THREAD

**Issue by Furkangunduz** [recharts/recharts#5160]
[video example](https://youtu.be/OrrUw9HXZz0)

# QUESTION

I have a web application [live link](https://racedata.ai/demo/segments/demo?s1=66da1dba3844d42eb04f626d&s2=66da1dbb3844d42eb04f6c6a&sc=1&t=66bf5c463d3d278986a16491&rl=66da1dbd3844d42eb04f728f&cl=66da1dbe3844d42eb04f72a1) where I have successfully synchronized an SVG element with the hover state on a line chart. Hovering over the line chart updates the SVG content accordingly.

Now, I want to achieve the reverse: instead of hovering, I want to control the active state of the line chart using buttons. My goal is to keep the tooltip visible and update the active index of the line chart when the button is clicked. This should work as if the user is hovering over a specific point on the chart, but triggered programmatically through buttons.

Question
How can I programmatically control the active state and index of the line chart using buttons, while keeping the tooltip visible and updating as the index changes?

**Comment by ckifer** [comment]
You can try using the active prop on Tooltip combined with defaultIndex.

**Comment by ckifer** [comment]
It may not behave exactly as you want it to which is why I say try. The defaultIndex as it stands is explicitly for the default state of the tooltip. As you hover it goes back under user control and may not be able to be changed programmatically until the next re-render. This isn't really ideal but it's what we can do without breaking changes. It should behave differently in 3.0 or soon after

**Comment by Furkangunduz** [comment]
Thanks a lot! The default index works fine for me. I did some index calculations and added it to the Tooltip component. I am also showing two separate tooltips for two situations for now: the first one is for hovering, and the other one is controlled with buttons. With the help of this solution, I am able to control my chart easily. Thank you for your help!

**Comment by ckifer** [comment]
Sounds good! Going to close this
