### ISSUE TITLE
Specifying Y-Axis ticks without a domain

### ISSUE THREAD

**Issue by pstatix** [recharts/recharts#5168]
## Do you want to request a feature or report a bug?

Feature/Insight?

## What is the current behavior?

Currently, if I want to specify ticks on the Y-Axis, it is not possible to directly set the ticks, equidistant to each other, to fill the height of the Y-Axis and to plot data accordingly. 

For example, below I specify there must be 4 ticks and list out the ticks, yet the chart will only render 3 ticks (unless I force interval to `{0}` which is not desired). There is plenty of space on the Y-Axis to display these 4 ticks and do so in an equidistant manner:

```
<ResponsiveContainer width="100%" height="100%">
	<LineChart
	  width={500}
	  height={300}
	  data={data}
	  margin={{
		top: 5,
		right: 30,
		left: 20,
		bottom: 5,
	  }}
	>
	  <CartesianGrid strokeDasharray="3 3" />
	  <XAxis dataKey="name" />
	  <YAxis tickCount={4} ticks={[10, 11, 27, 42]}/>
	  <Tooltip />
	  <Legend />
	</LineChart>
</ResponsiveContainer>
```

![image](https://github.com/user-attachments/assets/72a4bd71-76eb-4dda-b9ac-a829ba73705e)

Similarly, if I were to just use 3 ticks and have 2 ticks that are close in their value (such as `5` and `11`) and one tick far in value (such as `42`), the former 2 ticks will be placed close together while the latter will be placed far away:

```
<ResponsiveContainer width="100%" height="100%">
	<LineChart
	  width={500}
	  height={300}
	  data={data}
	  margin={{
		top: 5,
		right: 30,
		left: 20,
		bottom: 5,
	  }}
	>
	  <CartesianGrid strokeDasharray="3 3" />
	  <XAxis dataKey="name" />
	  <YAxis tickCount={3} ticks={[5, 11, 42]}/>
	  <Tooltip />
	  <Legend />
	</LineChart>
  </ResponsiveContainer>
  ```
  
![image](https://github.com/user-attachments/assets/aba3d9c7-a697-41d6-9541-2173b609b6ec)

## What is the expected behavior?

It appears that internally, some sort of Y-Axis domain is being enforced, when I would expect that specifying ticks would ignore a domain and plot what it is I am explicitly setting as the ticks. This could be a result of setting ticks simply being a formatting action and not one that determines how data is rendered? I am unsure.

But the ability to specify the Y-Axis ticks, and have data plot to that would be desired. For example, I may want to have 5 ticks of various values that have differing degrees of separation (numerically) away from each other, but show up on the axis as equidistant plots. This allows for charting time series by possible UUID (which numerically are unrelated by scale/domain).

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

I am using the latest stable release of the library

**Comment by pstatix** [comment]
> Not really sure what you mean about the UUID use-case

For example, imagine a horizontal stacked bar chart where the values on the Y-Axis are numeric values representing unique assets (5, 7, 22, 23, 29, 35, etc.). If those values were plotted and automatically treated as "domain" numbers, they would not be equally represented (spatially) along the height of Y-Axis. However, if they were plotted along the X-Axis of a bar chart, they would indeed be plotted equally, as the X-Axis would just be labels of grouped data by a unique ID (in this case some number represent an asset).

The reason a horizontal bar chart could not be used for this problem is because the X-Axis would represent time, and for some of Y-Axis values, there might be a gap of data within some timeframe. So unless the BarChart component supports "gaps" in the bar, a LineChart must be used.

If you'll indulge me, consider a chart where the Y-Axis represents the ID (numerically) of a particular TV channel, the X-Axis represents time. On each line of the Y-Axis, you want to show a solid line, across time, where the station was "on", and no line when the station was "off" (in terms of being viewed). Your chart might look something like this:

![image](https://github.com/user-attachments/assets/fdf13a16-35fb-4ea9-a1ec-c7ad99c882f6)

This is a very abstract example, but along the Y-Axis, for each of these lines, image the "values" would be 5, 7, 28, 59. Because the Y-Axis would treat the domain as [5, 59], there is no way to display the lines equally, as 5 and 7 would be placed close together (as they are close between 5 and 59, then 28 further away and 59 even further.

I would like to show data in LineCharts, similar to a horizontal BarChart, but require the ability to have gaps, indicating no data within that timeframe along the X-Axis.

Does this improve the problem/question?

**Comment by pstatix** [comment]
Following up as I forgot to read your strikeout:

> If you want to plot things that need to be equidistant and do not rely upon numeric value to do so then you can treat your YAxis as categorical. This would work for the UUID use-case for example. - nevermind on that, it would need a number in order to render anything meaningful of course. Not really sure what you mean about the UUID use-case

I would in fact like to treat my Y-Axis data as categorial, where the categories are in fact numbers (we call them UUIDs but they will always be unique numbers as discussed in my example above). I cannot seem to make such a configuration work though as the default behavior is to treat the Y-Axis values (even though they represent categories/individual things) as values within some domain and get unevenly distributed based upon where their value falls within that domain.

**Comment by ckifer** [comment]
Is this what you are after except for horizontal?

https://github.com/recharts/recharts/issues/4038#issuecomment-2211605944

**Comment by pstatix** [comment]
It is certainly closer, yes, 4038 moreso than 1510.

If 4038 could be enhanced where there might be multiple lines, above other lines, for each day, then yes. For example, looking at this chart:

![image](https://github.com/user-attachments/assets/6a41b4b0-74b4-49ca-aa5a-abab76c27dc0)

Having another bar above the current bar on Wed that starts at 2pm and goes until 10pm, indicating multiple segments.

**Comment by ckifer** [comment]
Cool - I think ranged bar charts are a better solution to your problem then trying to hack the domain then.

But alas, it still isn't super possible at the moment as per the issues still being open.

**Comment by ckifer** [comment]
Its essentially a ganntt chart - i.e. https://www.highcharts.com/demo/gantt/resource-management

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/issues/2847

**Comment by pstatix** [comment]
Correct. We currently have it working, but I have to show all elements of my domain, which creates a dense (if height is low) or tall chart if I want spacing. There might even be values on the domain that have no lines on them, so I was trying to avoid populating them at all. I have an idea and I will post it here shortly when I have a moment to try it.

**Comment by ckifer** [comment]
Yeah I attempted something here without much success

https://codesandbox.io/p/sandbox/stacked-bar-chart-forked-nt6xvm
 
 Treating the YAxis as a category does give you the even spacing but it seems it still wants to connect the numbers. I forget what the code actually does but it might see one categorical axis and automatically treat the other as numeric

**Comment by ckifer** [comment]
You could take a stab at using the Customized component like this. A bigger pain to build and maintain though (and also going away in 3.0)

https://codesandbox.io/p/sandbox/customized-line-chart-76fvmv

**Comment by pstatix** [comment]
Late reply, got busy with work yesterday.

Here is the snippet direct on the examples page (didnt have time to setup a codesandbox):

```
import React, { PureComponent } from 'react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';

const categories = [1, 2, 3, 4]
const data = [
  {
    name: 'Page A',
    cat_2: 2,
    cat_3: 3
  },
  {
    name: 'Page B',
    cat_2: 2,
    cat_3: 3
  },
  {
    name: 'Page C',
    cat_3: 3
  },
  {
    name: 'Page D',
    cat_4: 4,
  },
  {
    name: 'Page E',
    cat_2: 2,
    cat_4: 4,
  },
  {
    name: 'Page F',
    cat_2: 2,
    cat_4: 4,
  },
];

const lines = categories.map((v, idx) => <Line key={idx} isAnimationActive={false} dot={false} type="monotone" dataKey={`cat_${v}`} />)

export default class Example extends PureComponent {
  static demoUrl = 'https://codesandbox.io/p/sandbox/line-chart-width-xaxis-padding-8v7952';

  render() {
    return (
      <ResponsiveContainer width="100%" height="100%">
        <LineChart
          width={500}
          height={300}
          data={data}
          margin={{
            top: 5,
            right: 30,
            left: 20,
            bottom: 5,
          }}
        >
          <XAxis type="category" dataKey="name" />
          <YAxis type="category" padding={{ top: 20, bottom: 20}}/>
          <Tooltip />
          <Legend />
          {lines}
        </LineChart>
      </ResponsiveContainer>
    );
  }
}
```

![image](https://github.com/user-attachments/assets/4e01d137-31e8-4f49-9a08-54545ab453aa)

This data is clearly not massaged, as you'd need to ensure you're only generating lines for categories within the data. So you'd want to do a pass over the data before each render, to determine what categories are present. If your system is setup in such a way that the provider of that data tracks that internally, you'll save some cycles as well. Or, you can just hide the legend and not care about lines that are determined but not drawn (in this case there is no data with Category 1).

**Comment by ckifer** [comment]
Sandbox https://codesandbox.io/p/sandbox/stacked-bar-chart-forked-nt6xvm

**Comment by ckifer** [comment]
Going to close this in preference to ganntt chart support. Numeric tick values aren't meant to be equidistant since numeric values are interpolated. Categorical ticks are as equidistant as can be.

Anything outside of ganntt chart support will be custom and subject to change
