### ISSUE TITLE
Option to hide specific values from tooltip

### ISSUE THREAD

**Issue by Cameron-Asdf** [recharts/recharts#5169]
## Do you want to request a feature or report a bug?

Feature request.

## What is the current behavior?

In a tooltip's formatter there is no way to format a value out of existance.
You can return `null` for both the name and the value, but that still leaves a bit of a gap where the value should've been.

## What is the expected behavior?

It should be possible to return something like null or undefined to indicate that this value should be omitted entirely.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

I think it's all of them.

**Comment by ckifer** [comment]
You can make a custom Tooltip which should allow you to return whatever content (or lack of content) that you'd like

**Comment by Cameron-Asdf** [comment]
> You can make a custom Tooltip which should allow you to return whatever content (or lack of content) that you'd like

Yes, but I'd also need to recreate all of the features of the default tooltip.

**Comment by ckifer** [comment]
Why is that? You can provide a component to the content prop of the Tooltip component and it should give you all of the features/data. You just need to specify how you want that data to be rendered. I'm on my phone but I'll send an example in a bit

**Comment by ckifer** [comment]
https://release--63da8268a0da9970db6992aa.chromatic.com/?path=/story/examples-tooltip--custom-content-example

Pasting this from my phone but this should be the right example

**Comment by ckifer** [comment]
PR for this was merged

**Comment by Cameron-Asdf** [comment]
> Why is that? You can provide a component to the content prop of the Tooltip component and it should give you all of the features/data. You just need to specify how you want that data to be rendered. I'm on my phone but I'll send an example in a bit

Sorry, I got busy.
This worked, thanks.
Though it also feels like a roundabout way of doing this so I'm glad the change got merged in now.

**Comment by PavelVanecek** [comment]
Hello everyone who's watching this issue! We have released an alpha version `3.0.0-alpha.2` which fixes this problem.

Here is a migration guide: https://github.com/recharts/recharts/wiki/3.0-migration-guide

As of now we have fixed all the new 3.x bugs we are aware of so, and are ready for your feedback. Please feel free to try `recharts: 3.0.0-alpha.2` in a test build and let us know how it went!
