### ISSUE TITLE
Stacked bar chart radius is not working for some bars

### ISSUE THREAD

**Issue by kaaviya-min** [recharts/recharts#5170]
## Do you want to request a feature or report a bug?
Is there any solution for rounding the corner bars in a stacked bar chart? The value of the bar that doesn't apply radius is less than 1%.

<img width="463" alt="Screenshot 2024-10-29 at 3 25 54 pm" src="https://github.com/user-attachments/assets/d0a1cef0-21ad-450e-b459-4e680e11c31d">

Refer to this image, For August, the green bar doesn't apply the radius as the others. 

## What is the expected behavior?
No matter the values, the styles should work for all scenarios

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Rechart version: 2.12.4
OS: Mac
Browser: Chrome

**Comment by ckifer** [comment]
Can you make a reproduction in codesandbox or paste the code you are using to accomplish this?

**Comment by ckifer** [comment]
Does the content of this issue help at all? 

https://github.com/recharts/recharts/issues/3887

**Comment by kaaviya-min** [comment]
Thanks for the response. I have tried the above content, but it's not working. 

Here is the code I am using to acheive this

`<ResponsiveContainer
      width="100%"
      height={height - 1}
    >
      <BarChart
        layout="vertical"
        data={[data]}
        margin={{ top: 0, right: 0, left: 0, bottom: 0 }}
      >
        <XAxis type="number" axisLine={false} hide />
        <YAxis type="category" hide />
        <Tooltip
          isAnimationActive={false}
          shared={false}
          content={<CustomTooltip />}
        />
        {availableKeys.map((stackKey, index) => {
          const isFirst = index === 0;
          const isLast = index === availableKeys.length - 1;
          return (
            <Bar
              key={stackKey.key}
              dataKey={stackKey.key}
              stackId="a"
              fill={stackKey.color}
              radius={[
                isFirst ? 10 : 0, // Top-left corner radius for first bar
                isLast ? 10 : 0, // Top-right corner radius for last bar
                isLast ? 10 : 0, // Bottom-right corner radius for last bar
                isFirst ? 10 : 0, // Bottom-left corner radius for first bar
              ]}
            />
          );
        })}
      </BarChart>
    </ResponsiveContainer>`

**Comment by ckifer** [comment]
Can you also provide a simple dummy data point? How small does the value need to be to cause the issue?

**Comment by kaaviya-min** [comment]
`data = {awaiting_data: 86, processing: 10, action_required: 0, complete: 4}`
```
availableKeys = [
    {
        "key": "complete",
        "color": "#039855",
        "label": "Emissions ready"
    },
    {
        "key": "processing",
        "color": "#FDB022",
        "label": "Processing"
    },
    {
        "key": "awaiting_data",
        "color": "#D0D5DD",
        "label": "Awaiting data"
    }
]
```

**Comment by ckifer** [comment]
What isn't working here? 

https://codesandbox.io/p/sandbox/stacked-bar-chart-forked-gxcwzq

It looks like radius is taking effect as expected?

**Comment by kaaviya-min** [comment]
Thanks for the codesandbox. If the height is `15px` and the value is less than 2 then the border radius is working weird

**Comment by bryantebeek** [comment]
@kaaviya-min did you find a solution to this problem? We're experiencing the same thing. If the last cell is really small, the border radius is not visible at all.

![Image](https://github.com/user-attachments/assets/a9c6e74a-b038-4607-a6a2-c627374cff09)

**Comment by ckifer** [comment]
@bryantebeek feel free to make a reproduction and I can take a look
