### ISSUE TITLE
Recharts does not work in React 19 RC and Nextjs 15

### ISSUE THREAD

**Issue by Irere123** [recharts/recharts#5172]
## What is the current behavior?
When use install nextjs 15 together with react 19 the svg to render the charts does not appear in the container 

## Steps to reproduce the bug 
Install recharts inside a nextjs 15 project together with react 19

## What is the expected behavior?

The expected behaviour is that the charts should render on the page

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

1.  Recharts version 2.13.0

**Comment by ckifer** [comment]
Hello,

Yes it does


Please see https://github.com/recharts/recharts/issues/5146

You need to override your version of react-is to match your version of react which is mentioned in the release notes. 

Going to close this as a duplicate

**Comment by Irere123** [comment]
Thanks for the information. it was a pain the whole day

**Comment by ckifer** [comment]
Sorry for the pain, there's not much we can do about it until we release a new major version. Also R19 isn't released yet so it is difficult to support
