### ISSUE TITLE
Warning about defaultProps in XAxis and YAxis

### ISSUE THREAD

**Issue by zabpetrus** [recharts/recharts#5175]
I'm encountering the following warnings when using the XAxis and YAxis components from Recharts with Vite and Typescript:

`Warning: XAxis: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`

`Warning: YAxis: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`

**Environment:**

    Recharts: version 2.0.0
    React: version 17.0.2
    Vite: version 2.6.0
    Browser: Chrome 95

 Also Mozilla Firefox, Edge and Brave

**Example Code:**

import React, { PureComponent } from 'react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';

const data = [
  {
    name: 'Page A',
    uv: 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: 'Page B',
    uv: 3000,
    pv: 1398,
    amt: 2210,
  },
  {
    name: 'Page C',
    uv: 2000,
    pv: 9800,
    amt: 2290,
  },
  {
    name: 'Page D',
    uv: 2780,
    pv: 3908,
    amt: 2000,
  },
  {
    name: 'Page E',
    uv: 1890,
    pv: 4800,
    amt: 2181,
  },
  {
    name: 'Page F',
    uv: 2390,
    pv: 3800,
    amt: 2500,
  },
  {
    name: 'Page G',
    uv: 3490,
    pv: 4300,
    amt: 2100,
  },
];

export default class Example extends PureComponent {
  static demoUrl = 'https://codesandbox.io/p/sandbox/line-chart-width-xaxis-padding-8v7952';

  render() {
    return (
      <ResponsiveContainer width="100%" height="100%">
        <LineChart
          width={500}
          height={300}
          data={data}
          margin={{
            top: 5,
            right: 30,
            left: 20,
            bottom: 5,
          }}
        >
          <CartesianGrid strokeDasharray="3 3" />
          <XAxis dataKey="name" />
          <YAxis />
          <Tooltip />
          <Legend />
          <Line type="monotone" dataKey="pv" stroke="#8884d8" activeDot={{ r: 8 }} />
          <Line type="monotone" dataKey="uv" stroke="#82ca9d" />
        </LineChart>
      </ResponsiveContainer>
    );
  }
}

I believe this might impact the future functionality of the library, and I would like to contribute to a resolution!

 Thanks a lot

**Comment by ckifer** [comment]
Hi, this is fixed in 2.13.0. Please upgrade and this will resolve. 

Thanks!

**Comment by ckifer** [comment]
Going to close this, comment back if you have any issues

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/issues/3615#issuecomment-2135955727

**Comment by zabpetrus** [comment]
wrong. I just created a new react project in visual studio 2022. I disagree with this argument. This is saying that visual studio and browsers are out of date. Everything is in the latest version and I confirm the error in updated browsers.

**Comment by ckifer** [comment]
I'm confused. You say in the issue what you are using version 2.0.0 which is not the latest version

**Comment by ckifer** [comment]
If you can reproduce the issue in the latest recharts version I will gladly look into it

**Comment by zabpetrus** [comment]
So, wait, can I show you my Packages.json before closing? I asked chatgpt to create a template and he wrote nonsense,  

{
  "name": "vel",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc -b && vite build",
    "lint": "eslint .",
    "preview": "vite preview"
  },
  "dependencies": {
    "@reduxjs/toolkit": "^2.2.7",
    "@testing-library/jest-dom": "^6.5.0",
    "@testing-library/react": "^16.0.1",
    "@testing-library/user-event": "^14.5.2",
    "@types/jest": "^29.5.13",
    "@types/node": "^22.7.4",
    "@types/react": "^18.3.9",
    "@types/react-dom": "^18.3.0",
    "@types/redux": "^3.6.31",
    "axios": "^1.7.7",
    "bootstrap": "^5.3.3",
    "bootstrap-icons": "^1.11.3",
    "boxicons": "^2.1.4",
    "jwt-decode": "^4.0.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-redux": "^9.1.2",
    "react-router-dom": "^6.26.2",
    "recharts": "^2.12.7",
    "redux": "^5.0.1",
    "typescript": "^5.6.2",
    "web-vitals": "^4.2.3"
  },
  "devDependencies": {
    "@types/jwt-decode": "^3.1.0",
    "@types/react": "^18.3.10",
    "@types/react-dom": "^18.3.0",
    "@vitejs/plugin-react": "^4.3.1",
    "globals": "^15.9.0",
    "typescript": "^5.6.2",
    "typescript-eslint": "^8.7.0",
    "vite": "^5.4.8"
  },
  "browserslist": {
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ],
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ]
  }
}

**Comment by zabpetrus** [comment]
![Capturar](https://github.com/user-attachments/assets/21a02537-a259-4d2f-893d-a8947e6601c2)
Are you able to see the message in the browser? I just want permission to change the code and see what I can do to make this error disappear.

**Comment by ckifer** [comment]
Your recharts version is 2.12.7. Please update it to 2.13.1 and the issue will resolve

**Comment by zabpetrus** [comment]
> Your recharts version is 2.12.7. Please update it to 2.13.1 and the issue will resolve

This latest update saved my neck. Thanks

**Comment by ckifer** [comment]
I'm sorry if me closing the issue right away came off as unkind, there's been a lot of the same issue and I knew for a fact that it was fixed in the latest version. 

I'm glad upgrading resolved the problem. Best of luck 🚀
