### ISSUE TITLE
Props dy of `Text` not work

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#520]
In this example: [http://recharts.org/#/en-US/examples/CustomizedLabelLineChart](http://recharts.org/#/en-US/examples/CustomizedLabelLineChart)

No labels are shown.

**Comment by thibautRe** [comment]
They are, it's the XAxis labels : they are a bit tilted and not horizontal.

**Comment by xile611** [comment]
@Eric24 Thanks! It's not a bug, I forgot to update the example.

**Comment by Eric24** [comment]
Ah, OK. So I can almost accomplish the same thing like this:

`{fill:"#82ca9d", stroke:false, fontSize:10, dy:-4}`

But dy doesn't work. Is there a way to control the offset of the label (without a custom function)?

**Comment by xile611** [comment]
@Eric24 Yeah! You can specify the `label` of `Line` to be a object:

```jsx
const LABEL = { fill:"#82ca9d", stroke:false, fontSize:10, dy:-4 };

...
  <Line  label={LABEL} />
...
```

**Comment by Eric24** [comment]
I've tried this every which way, but dy still has no effect on the position of the label. Can you show me in a jsfiddle (I essentially did that, using the CustomizedLabelLineChart example as a starting point)?

**Comment by xile611** [comment]
@Eric24 `Text` don't receive `dy` now. I'll fix it. Thanks!

Do you have any thoughts about new components `Label` and `LabelList` ?

[Discussion about Label and LabelList](https://github.com/recharts/recharts/issues/522)
