### ISSUE TITLE
Transform payload of legend

### ISSUE THREAD

**Issue by super-cache-money** [recharts/recharts#521]
It would be really cool if you could pass in a function to `<Legend/>` which transforms the payload. I want to just effect a subtle change to it and don't want to have to recompute all the other properties which are fine by default.

Even if we could just transform the `value`, that's what I need most.

**Comment by super-cache-money** [comment]
For example, it would be useful in [http://jsfiddle.net/xpegg70o/2/](this JSFiddle) from #323. 

Now the Legend payload has a custom `value`, but it looks uglier because it's missing the rest of the default properties.

**Comment by xile611** [comment]
@super-cache-money How about add a props `formatter` which can be called format the values ?

**Comment by super-cache-money** [comment]
@xile611 Sounds great and exactly what I'd like. Is that already possible as is?

**Comment by xile611** [comment]
@super-cache-money  It's a new feature.

**Comment by super-cache-money** [comment]
@xile611 By new feature, do you mean a new feature that's recently been added, or new feature that ought to be added? 💩

**Comment by xile611** [comment]
@super-cache-money Sorry! It's a new feature that ought to be added!

**Comment by super-cache-money** [comment]
So shall we add the enhancements tag?
