### ISSUE TITLE
Not able to use linearGradient that fills the whole range of AreaChart

### ISSUE THREAD

**Issue by raRaRa** [recharts/recharts#5216]
## Do you want to request a feature or report a bug?
Likely a feature request, unsure if it's a bug.

## What is the current behavior?
Imagine an AreaChart with Y-axis that ranges from -30 to 30. I want to have gradient yellow to red below 0 to -30 and gradient green above 0 to 30.
Example that is correct (and only works if I have data filling that range):
<img width="114" alt="image" src="https://github.com/user-attachments/assets/23a8d7e8-5286-43b4-a86c-31066525936e">

Now, if the data in the Area is only utilizing the range 20 to -10, then it will fill that range with the linear gradient, which is not what I want, in that case I only want the yellow/green to show, but this is what happens:
<img width="144" alt="image" src="https://github.com/user-attachments/assets/1a47f991-af26-4e79-bee6-55611613c41a">

When I inspected the element, it seems like the gradient is only filling the used space:
<img width="130" alt="image" src="https://github.com/user-attachments/assets/a36a4989-fdba-4efc-b0c9-87037659bc09">

Is there a way to have the linearGradient always use the whole range, so that the gradient color is always correct on the data? It only looks correct now if I have data ranging from -30 to 30 in the Area:

Here's my linearGradient:

```
        <linearGradient id="test2" x1="0%" y1="0" x2="0" y2="1">
          <stop offset={0} stopColor="green" stopOpacity={1} />
          <stop offset={0.4} stopColor="green" stopOpacity={1} />
          <stop offset={0.5} stopColor="yellow" stopOpacity={1} />
          <stop offset={1} stopColor="red" stopOpacity={1} />
        </linearGradient>
```

Any help in the right direction would be much appreciated! Thanks.

**Comment by ckifer** [comment]
I guess I'm a little confused. Can you add your example to a codesandbox so I can play around with it? Thanks!

**Comment by raRaRa** [comment]
@ckifer Yeah I've created a sandbox here: https://codesandbox.io/p/sandbox/5klpq5

So basically the gradient only fills from the highest (y-axis) data point to the lowest data point, skewing the colors. I want it to always fill based on the whole Y range (-30 to 30) so that the colors are always correct, e.g. always green above 0. You can see two examples in the Sandbox that explains it better.

**Comment by ckifer** [comment]
Does something like this work?

https://codesandbox.io/p/sandbox/recharts-issue-forked-vdj98h

![image](https://github.com/user-attachments/assets/41e8fe58-dfe7-4c2a-8721-b587abcbdd0d)

**Comment by raRaRa** [comment]
@ckifer Yeah it's a good start, but it will never be as smooth as pure gradient. Additionally the red part will be visible around -10 as well, while that range should just be yellow. Think about 30 to 0 always being green, 0 to -10 yellow, -10 to -20 orange and -20 to -30 red. It just feels like Recharts is missing something for this use case

**Comment by ckifer** [comment]
adjusted the examples and added one for all negatives. They should look better.
<img width="746" alt="image" src="https://github.com/user-attachments/assets/ec390db7-dd98-4541-a556-34f39bbdf2d5">
<img width="716" alt="image" src="https://github.com/user-attachments/assets/d8883d4c-18c4-4d63-81d3-c5aafa480037">

**Comment by raRaRa** [comment]
@ckifer I think this will be my best option, I really appreciate the effort you put into finding a solution for me ❤️
Perhaps I could instead look into having the background as gradient and the Area chart not filled. I wonder if that's even possible 🤔 At least I could not find any element where I could apply gradient to.

something like this:
<img width="366" alt="image" src="https://github.com/user-attachments/assets/f310d3b2-6c69-4c2c-9b80-d0e39e61f3df">

**Comment by ckifer** [comment]
@raRaRa sure thing.

https://codesandbox.io/p/sandbox/recharts-issue-forked-5vx895?workspaceId=7a1754d3-b261-47b1-9339-2aca93020961

you use CartesianGrid for that I think?

This can obviously be made better, this was just a quick attempt, I'm not the best at gradients

![image](https://github.com/user-attachments/assets/27fa22ea-13ce-4cce-95fc-6181b663bb44)

**Comment by ckifer** [comment]
Going to close this due to no response, feel free to comment back if we need to reopen
