### ISSUE TITLE
For each pie data, provide different/variable inner radius according to the pie-data.

### ISSUE THREAD

**Issue by ajay-studio137** [recharts/recharts#5224]
## Do you want to request a feature or report a bug?
Feature

## What is the current behavior?
As of now, a static innerRadius can be provided to Pie component.

## What is the expected behavior?
I expect to provide a different innerRadius for each cell shown inside Pie.

Let me know if we need more information in here.

**Comment by ckifer** [comment]
Can you give an example of what this will allow you to do? Genuinely curious

**Comment by ajay-studio137** [comment]
Hi Coltin,

This would allow me to show Pie according to the % of its applicability in another dimension than the usual one.

Something similar would be fine. 

<img width="326" alt="Screenshot 2024-11-11 at 10 31 46 AM" src="https://github.com/user-attachments/assets/326e2d38-564a-4b28-9551-d5622053aea8">

For now, using multiple Pie Charts and showing only the one which is applicable for that particular Pie. With this approach, I am unable to pick up the mouse hover for Pie chart. Hope it makes sense.

**Comment by ckifer** [comment]
I see, this is possible to change on hover with activeSector (might be called something else I forget). But yeah this is different. 

I labeled as a feature request. I'm not sure when this will be able to be picked up.
