### ISSUE TITLE
Labelling points on Scatter Chart

### ISSUE THREAD

**Issue by super-cache-money** [recharts/recharts#524]
How do I do something like this?

![image](https://cloud.githubusercontent.com/assets/1463145/23098770/89bf9eac-f65f-11e6-9f8a-b3e551d40231.png)

**Comment by fabien88** [comment]
Maybe you can try to create custom shapes
```
const CustomizedShape = (props) => {
  const {cx, cy, fill, riderName} = props;
  return (
    <g>
      <Dot cx={cx} cy={cy} r={5} fill={fill} />
      <g transform={`translate(${cx},${cy})`}>
        <text x={10} y={0} dy={4} textAnchor="left">{riderName}</text>
      </g>
    </g>
   );
};
```

```
<Scatter 
  name='Riders with doping allegations' 
  data={data} 
  fill='#EC7C6D' 
  shape={<CustomizedShape />}  
/>
```

<img width="1039" alt="screenshot" src="https://cloud.githubusercontent.com/assets/279377/26001907/32eeb67a-372e-11e7-937a-d2189d42d3ca.png">

**Comment by xile611** [comment]
This feature can be implemented by <LabelList /> in 1.0+.

[Doc about LabelList](http://recharts.org/#/en-US/api/LabelList)

[Demo of ScatterChart labels](http://recharts.org/#/en-US/examples/ScatterChartWithLabels)

**Comment by daveabes** [comment]
Fabians post is awesome.
For those looking for an example of LabelList:
http://recharts.org/en-US/examples/BarChartWithMinHeight

**Comment by ajaybandi14** [comment]
> Maybe you can try to create custom shapes
> 
> ```
> const CustomizedShape = (props) => {
>   const {cx, cy, fill, riderName} = props;
>   return (
>     <g>
>       <Dot cx={cx} cy={cy} r={5} fill={fill} />
>       <g transform={`translate(${cx},${cy})`}>
>         <text x={10} y={0} dy={4} textAnchor="left">{riderName}</text>
>       </g>
>     </g>
>    );
> };
> ```
> 
> ```
> <Scatter 
>   name='Riders with doping allegations' 
>   data={data} 
>   fill='#EC7C6D' 
>   shape={<CustomizedShape />}  
> />
> ```
> 
> <img alt="screenshot" width="1039" src="https://cloud.githubusercontent.com/assets/279377/26001907/32eeb67a-372e-11e7-937a-d2189d42d3ca.png">

Animation not working when using custom shape

**Comment by rahulsawlanivcbay** [comment]
How can I solve the issue of label overlapping if the data points are really close to each other?

**Comment by ckifer** [comment]
There's only so much space on a chart. You can choose to show labels or not in the custom implementation example above based on whatever condition you see fit.

Recharts doesn't resolve collisions (except with axes)
