### ISSUE TITLE
Add documentation for the entire bar behind a set of bars under the hover and its related events and customization

### ISSUE THREAD

**Issue by Nefcanto** [recharts/recharts#5243]
Look at this chart:

![Screenshot from 2024-11-13 17-26-15](https://github.com/user-attachments/assets/2d351a71-95e1-45f7-9c82-871ab3212df3)

I can't find out two things in the docs:

- How can I format this box on hover (the column behind all bars)?
- How can I attach a click handler to it?

Please update the docs and give us an example for that thing (active bar's full-height background). Please include the customization and event handling in that example.

**Comment by Nefcanto** [comment]
The point is that the click handler for each bar only works when we click that bar exactly. This is not a good UX to expect the user to move the mouse over a bar, especially for small bars. It's better to have a click handler for the entire column (including the bars and the background). For example the user want to click and navigate to a list related to that data.

**Comment by ckifer** [comment]
A lot of people actually feel opposite of this. Onclick/hover/etc. of a bar should be just that. 

However, I hear you. You can try adding an event handler to the overall chart which should still give you the information you need if you are close to a specific bar.

**Comment by Nefcanto** [comment]
@ckifer, Thank you so much. I spent hours in the docs and could not find it. It's easy for you because you already know it. But it's not easy for someone who does not know it to find out. I never thought that it was something related to the Tooltip. I deduced it has to be related to the bars. Maybe a <TotalBar /> component or something.

Please add a sample for this in the Bars chart.

**Comment by Nefcanto** [comment]
@ckifer, also you're right about the click handler/hover/etc. That has meaning when bars are not related to each other. Sometimes bars are related. For example, they might be the "To do, in progress, done" of a person. In that case it's also logical to navigate to the tasks of that person when we click it.

**Comment by ckifer** [comment]
Makes sense. 

I can't get to this now but I labeled it so it can be picked up later. Thanks!

**Comment by ckifer** [comment]
See this PR for an example https://github.com/recharts/recharts/pull/5249

**Comment by ckifer** [comment]
Link to example in code https://github.com/recharts/recharts/blob/eb866a3f358543281893f7ea7208bf83d4c220ca/storybook/stories/Examples/BarChart/BarChart.stories.tsx#L806-L839

Link to storybook with the rendered code https://63da8268a0da9970db6992aa-xvfiifzjcb.chromatic.com/?path=/story/examples-barchart--custom-cursor-bar-chart

Cursor is not the place for event handlers to be attached as right now they get filtered out, onMouseEnter or onMouseMove of the main chart should get you what you need.

Going to resolve this, thanks!

**Comment by Nefcanto** [comment]
@ckifer, thank you so much for the code and the sample. Very clear and informative.
Regarding the event, `onMouseEnter` or `onMouseMove` won't help because those events are not explicit. Click is explicit. I will bind the same event handler to the cursor and bars. I think that would solve the problem.
