### ISSUE TITLE
PieChart render animation is not working correctly when using with Tooltip content

### ISSUE THREAD

**Issue by doublebuzzwoo** [recharts/recharts#5246]
From the topic title, you can check it out here on this template page https://material-kit-pro-react.devias.io/dashboard/analytics

In the section **Devices** when you reach the **analytics** page by parsing the link or you can try to stay in the link and refresh the page you will see the PieChart in **Devices** is not showing the render animation. But in case you reach the **analytics** page when using the navbar the render animation will work properly.

These problems occur only when we use the _content_ props of <Tooltip> component. 

Here is the screen recorder

https://github.com/user-attachments/assets/42d210a6-0ef6-458f-9271-dd5e16d91ad6

**Comment by ckifer** [comment]
Can you create a reproduction in code sandbox so we can rule out that this isn't only in your environment? This isn't really enough information to confirm that this is a bug with recharts

**Comment by doublebuzzwoo** [comment]
@ckifer Thanks for the quick reply, It's weird because I tried from the source code from the template website that I mentioned in this issue and it's working properly but as you can see in the video on their production website the bugs are still there, I tried within my work project that using Devias template the bugs still showing, And I also tried on the fresh project but I could not reproduce it anymore.

So let's ignore it then.

Thank you🙏

**Comment by ckifer** [comment]
Of course. If you can reproduce, I'm happy to take a look!

Things it could be:

* Your CSS interacting with animations
* Scroll
* Having multiple charts on the same page

I can't say that it isn't a recharts issue for sure. But it's hard to spend time on something which looks like it's in your env only at first place. 

Again, let me know if you find anything and reopen the issue if you do. 

Thanks!

**Comment by ckifer** [comment]
Also @doublebuzzwoo it looks like this issue only happens on chrome. Try firefox and see that the animation always renders correctly

**Comment by doublebuzzwoo** [comment]
@ckifer Oh, Thank you for checking this out. 🙏

I already fixed it by rendering the <Tooltip /> after the onMouseEnter event is active on <PieChart /> and the problems are solved.
