### ISSUE TITLE
last Label not aligned to middle.

### ISSUE THREAD

**Issue by sayshark75** [recharts/recharts#5257]
## What is the current behavior?
- the last X axis label misbehaves, moves inside from the last tick
![image](https://github.com/user-attachments/assets/8b8da3b1-c7ba-4404-abe0-e4e70c361275)

## What is the expected behavior?
- the last label should be aligned properly with the last tick or dash or point.
- Official Example from the Docs
![image](https://github.com/user-attachments/assets/fd9a32d9-c369-4371-b41f-8b3ad9d7e84f)

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
- Current version: `"recharts": "^2.13.3"`
- Browser: Chrome latest
- Windows 12 Home
- Not checked in previous versions. 
- Using Nextjs 14 App Router + Chakra UI V2 + framer motion

**Comment by ckifer** [comment]
Can you reproduce outside of the context of your app?

Can you make a codesandbox?

**Comment by sayshark75** [comment]
> Can you reproduce outside of the context of your app?
> 
> Can you make a codesandbox?

- Here is the Codesandbox Link
https://codesandbox.io/p/devbox/65p2yp

**Comment by ckifer** [comment]
Thanks! I'll take a look when I can. 

Mostly likely this is just recharts trying to keep your text within bounds of the svg. 

You can try using other options for "interval" on your XAxis and see if any of those help in the meantime.

**Comment by ckifer** [comment]
Also try to see if adding more right margin helps

**Comment by ckifer** [comment]
https://codesandbox.io/p/devbox/65p2yp

Yep, please add more right margin via 

`<AreaChart data={data} margin={{ right: 50 }}>`

And the label will align itself to the middle.

This is because the SVG is out of space and svg text cannot exist outside of the svg.

Going to resolve this

**Comment by sayshark75** [comment]
- Hey great, Thanks @ckifer, 
- I was just focused on XAxis component, doesn't thought about the parent components 😄
