### ISSUE TITLE
buildOutput test fails on Windows

### ISSUE THREAD

**Issue by Cameron-Asdf** [recharts/recharts#5280]
## Do you want to request a feature or report a bug?

Report a bug

## What is the current behavior?

When building the repo in its current state on Windows, the buildOutput tests fail because the file snapshots care about the order that the files are in and use `/` as the separator.
On Windows, the `globSync` it uses gives the paths with a `\` if not explicitly told otherwise and the order in which they're listed is also a bit different.

## If the current behavior is a bug, please provide the steps to reproduce.

1. Follow the [dev build steps](https://github.com/recharts/recharts?tab=readme-ov-file#dev-build) in the readme while on Windows.

## What is the expected behavior?

The test should only care about what files there are, not what order which OS is reporting them in.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

latest 3.x branch on Windows, I do not know if this used to work.

**Comment by ckifer** [comment]
Feel free to fix this if you'd like. I don't have a windows computer to test on and CI runners are usually going to be Linux.

**Comment by ckifer** [comment]
Thanks! Going to close this
