### ISSUE TITLE
Styled-Components & Label

### ISSUE THREAD

**Issue by ledfordtj** [recharts/recharts#5285]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
When using styled-components on top of the label component, the component is no longer a React.JSX.Element and no longer renders. I believe this is occurring because styled-components is taking the 'namespace' export instead of the 'function' export.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via codesandbox or similar (template: https://codesandbox.io/p/sandbox/simple-line-chart-v25dl4).
Comment the regular Label component, watch the StyledLabel not render. Comment StyledLabel, uncomment Label and watch the label render.

https://codesandbox.io/p/sandbox/funny-mountain-zlo54o

## What is the expected behavior?
StyledLabel to render in the exact same way Label does.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
2.0.6 & 2.13.0-alpha.4. Chrome (have not tried other browsers). No it did not work in previous versions.

**Comment by ledfordtj** [comment]
Screenshot to show the expected output (StyledSurface) after using styled-components versus incorrect output (StyledLabel)

<img width="517" alt="Screenshot 2024-11-28 at 11 22 18 AM" src="https://github.com/user-attachments/assets/3844cf4e-c64f-4baa-a40f-a7c67f0bcef8">

<img width="499" alt="Screenshot 2024-11-28 at 11 25 10 AM" src="https://github.com/user-attachments/assets/edec64c5-f079-4e91-a128-d900127d2ef3">

**Comment by ckifer** [comment]
Would suggest trying the latest version if you haven't yet. Still the same issue with 2.13.3?

**Comment by ckifer** [comment]
I might be missing something but I don't see any labels in the sandbox. I will look in more detail when I can

**Comment by ledfordtj** [comment]
@ckifer whoops, thats my bad. The link is the sandbox before I forked it. Below should be the correct one.

https://codesandbox.io/p/sandbox/recharts-css-in-js-forked-3hhshv

**Comment by ledfordtj** [comment]
> Would suggest trying the latest version if you haven't yet. Still the same issue with 2.13.3?

I am seeing the issue in 2.13.3 as well

**Comment by ckifer** [comment]
Ok. Support for libraries such as styled components can't be guaranteed since we're not going to test for compatibility or anything. 

Today is a holiday in the US, so will look into this maybe Monday

**Comment by ckifer** [comment]
Here you are https://codesandbox.io/p/sandbox/recharts-css-in-js-forked-8jgjl7

Recharts reads components `displayName` attributes to verify that they actually are what recharts thinks they are so

`StyledLabel.displayName = 'Label'` lets your styled label render correctly

**Comment by ckifer** [comment]
Going to close this as answered, this may or may not go away in future versions
