### ISSUE TITLE
Brush Displaying Data?

### ISSUE THREAD

**Issue by GregPhyn** [recharts/recharts#529]
Is it possible to make the Brush itself display data?

Attached is what I am trying to accomplish; The problem is with attached I'm just using CSS to move a second AreaChart inside of the Brush which makes the Brush Traveler not work.

is there a way to put data directly within the Brush component?

![screen shot 2017-02-21 at 10 37 04 am](https://cloud.githubusercontent.com/assets/22822404/23179161/cb341e44-f821-11e6-82b6-dee56bd5cb3d.png)

**Comment by xile611** [comment]
Duplicated with #446

**Comment by GregPhyn** [comment]
Has this been implemented?
Is usage like 
<Brush dataKey="the_dataKey" /> ?

**Comment by xile611** [comment]
@GregoryPotdevin Not yet!

**Comment by GregoryPotdevin** [comment]
@xile611 you keep sending notifications to the wrong Greg 😉

**Comment by xile611** [comment]
@GregoryPotdevin So sorry! 😁
