### ISSUE TITLE
Eventemitter3 previous version has been installed

### ISSUE THREAD

**Issue by mfialko** [recharts/recharts#5291]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
When installing the latest version of Recharts (2.13.3), version 4 of eventemitter was installed instead of version 5, despite what is specified in the package.json.

Here is link to reproducible example: https://stackblitz.com/edit/solidjs-templates-6c4vnz

## What is the expected behavior?
Version 5.0.1 should be installed

## Did this work in previous versions of Recharts?
Didn't observe before. Need to check

<img width="548" alt="Screenshot 2024-12-02 at 00 50 33" src="https://github.com/user-attachments/assets/c99374c8-4087-4ea0-8337-322e27d41e97">
<img width="458" alt="Screenshot 2024-12-02 at 00 50 57" src="https://github.com/user-attachments/assets/81404e93-9bf0-4037-ac88-804518b23640">
<img width="424" alt="Screenshot 2024-12-02 at 00 54 50" src="https://github.com/user-attachments/assets/acdf9817-7843-4416-8d3d-54ba3505a32b">

**Comment by ckifer** [comment]
The master branch is current 2.x and has eventemitter 4 in the package.json file. 

We can't upgrade in 2.x in case of breaking changes

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/blob/master/package.json#L70

**Comment by ckifer** [comment]
Going to close this
