### ISSUE TITLE
Tooltip payload for stacked data

### ISSUE THREAD

**Issue by H3katonkheir** [recharts/recharts#530]
Is it possible to add a payload to a Tooltip for charts that used stacked data such as BarChart and AreaChart? Looking at the source it doesn't appear that it can, but I could be very wrong. There also appear to be no examples to check.

Assuming that I've not made a horrible mistake; It would be nice if the payload could take an array of arrays of objects, or alternatively, take a string which points to a property in the data.

**Comment by xile611** [comment]
@H3katonkheir You can render customized tooltip by specify the props `content` of `Tooltip` to be a customized react component element or a function.

[Here](http://recharts.org/#/en-US/examples/CustomContentOfTooltip) is an example.

**Comment by H3katonkheir** [comment]
Thanks, I'm currently using this. However, I was specifically asking about the payload, since I quite like the default behaviours.

**Comment by xile611** [comment]
@H3katonkheir The payload of Tooltip is calculated internally, not allowed to be set by develops.

**Comment by H3katonkheir** [comment]
Alright, sorry. I thought I could set it through the payload property ([Tooltip API](http://recharts.org/#/en-US/api/Tooltip))

**Comment by malte1989** [comment]
Then please adjust the API Documentation. 
Payload exactly was what we were looking for. But it doesn't work.
