### ISSUE TITLE
Bar props missing correct onClick types

### ISSUE THREAD

**Issue by dapie** [recharts/recharts#5308]
## Do you want to request a feature or report a bug?
bug

## What is the current behavior?
Types of onClick event for Bar component is incorrect. It has only AdaptChildMouseEventHandler while for Pie component the type is correct `(data: any, index: number, e: React.MouseEvent) => void;`

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via codesandbox or similar.
https://codesandbox.io/p/sandbox/simple-line-chart-forked-ccqw55

## What is the expected behavior?
The types should be correct for Bar onClick event

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
recharts@2.14.1

**Comment by ckifer** [comment]
This was a bug fix where the previous types were incorrect. The adapted event types are correct and contain the correct parameters (data and event).

**Comment by dapie** [comment]
@ckifer why is it correct if `<Bar dataKey="uv" fill="#8884d8" onClick={({ uv }, _i, _e) => console.log(uv)} />` works fine, but typescript show error `Property 'uv' does not exist on type 'BarRectangleItem'`. The first argument should have information about bar data, but it has only value. Btw, If it it works fine, how I should add types here ?

**Comment by ckifer** [comment]
I'll take another look when I get a chance

**Comment by ckifer** [comment]
fixed in 2.15.0
