### ISSUE TITLE
Responsive Container doesnt support Server Side Rendering

### ISSUE THREAD

**Issue by Mohendran** [recharts/recharts#531]
If I remove the ResponsiveContainer .... I get Server Side Rendered Graph.... But If I use ResponsiveContainer... The Graph is rendered in the client side alone....

**Comment by Mohendran** [comment]
`<div id="canvas_dahs" className="demo-placeholder" style={{ width: '100%', height: '270px' }} >
        <ResponsiveContainer width='100%' height='100%' minWidth={100} minHeight={100}>
          <LineChart width={600} height={300} data={data} margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
            <XAxis dataKey="name" />
            <YAxis />
            <CartesianGrid strokeDasharray="3 3" />
            <Tooltip />
            <Legend />
            <Line type="monotone" dataKey="pv" stroke="#8884d8" activeDot={{ r: 8 }} />
            <Line type="monotone" dataKey="uv" stroke="#82ca9d" />
          </LineChart>
        </ResponsiveContainer>
      </div>`

**Comment by xile611** [comment]
@Mohendran In SSR, we can't get the width and height of parent node, so no chart is rendered.

**Comment by Mohendran** [comment]
Is there a workaround for this? @xile611

**Comment by xile611** [comment]
@Mohendran If the size of chart is fixed, you can remove `ResponsiveContainer `.

**Comment by Mohendran** [comment]
@xile611  but it is not fixed( As per my requirement ).... the graph has to adjust its width depending on the browser size....

**Comment by xile611** [comment]
@Mohendran 

I really can't get your point! 
Because we need calculate all the related coordinates (in pixels) of points, rectangles, and so on, so we need the width and height ( in pixels) of chart. SSR only render chart into a html string, so we can't get the width and height of chart. So we can only render charts after the component is mount.

I wonder why the charts must be rendered in the SSR ? 
If so, you should give a initial width and height of the chart.( New feature)

**Comment by Mohendran** [comment]
A chart can be in percentages too... Not only in pixels(If that is the case, then what is the use of ResponsiveContainer in recharts then? )... Recharts creates an svg.  SSR can also append svg into html and also, svg can be in percentages... What Iam asking is to use percentages for width and height for the generated svg.

**Comment by xile611** [comment]
@Mohendran   When you specify the width or height of `ResponsiveContainer` to be a percentage, It only means that:

the width of chart = the width of chart * the percentage

or

the height of chart = the height of chart * the percentage

**Comment by Mohendran** [comment]
100% true.... that is what is needed.... and that is what responsive container does.... and that is what bootstrap or foundation does for us (SSR also) ..... If bootstrap or foundation can use percentages to make an html element responsive... Why cant an svg be responsive... ? when SSR is used?

**Comment by xile611** [comment]
@Mohendran Sorry! We can't use percentages to calculate the coordinates of all the shapes.

**Comment by phiresky** [comment]
It would be great if you could add initial size props to ResponsiveContainer, and in constructor do:

```
this.state = {
	containerWidth: props.initialWidth || -1,
	containerHeight: props.initialHeight || -1,
}
```

That way, the graph can render server side and then readjust client side

**Comment by Mohendran** [comment]
@phiresky  Wont there be a jerk in the app... ?

**Comment by phiresky** [comment]
Yes, but there will be anyways because SSR of recharts looks different than client side render (no word wrap etc). Here's where I use it: https://phiresky.github.io/blog/2019/rga--ripgrep-for-zip-targz-docx-odt-epub-jpg/ . The graph is fairly low on the page (not the first thing you look at) so I think the graph moving a bit is ok.

**Comment by Mohendran** [comment]
@phiresky  In your page... It does seem ok... But in some scenarios like a Dashboard... Where the first thing you look at... and which contains many charts... Sure is a problem. IMHO.
