### ISSUE TITLE
Grey lines across wide chart

### ISSUE THREAD

**Issue by TommyMac15** [recharts/recharts#5312]
Any idea why this chart is being displayed with these grey lines?

I am able to zoom in on this chart and the grey lines disappear so I suspect it is due to the length of the graph. I did not have this issue before but then I decided to make any values above 20,000 be removed. Are these null values a factor?

![bad_chart](https://github.com/user-attachments/assets/c9d34929-469c-4c39-a765-2fa313aaf247)

Here is the bad chart after I zoom in on a section:
![bad_chart_zoom](https://github.com/user-attachments/assets/da1541af-18af-4cff-9f65-f04c9f87273f)

Here is the chart with different data which renders without those grey bars:
![good_chart](https://github.com/user-attachments/assets/3cf687b0-c798-4a2c-9166-779e1b5b673d)

import { LineChart, Line, CartesianGrid, XAxis, YAxis, Label, ReferenceLine, Tooltip, ReferenceArea, ResponsiveContainer } from 'recharts';
"recharts": "^2.12.7"

**Comment by ckifer** [comment]
can you make a reproduction in codesandbox?
