### ISSUE TITLE
Function-driven Reference Lines

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#532]
Any thoughts on adding the ability to drive the position of a ReferenceLine with an aggregate function calculated across all samples of a particular datakey? In other words, for a horizontal ReferenceLine, instead of declaring "y" as a static value, specify "datakey" and a new "function" prop to calculate the position of the line in real-time. Potential (easy) functions would be "average", "min", "max", "mean", "mode", etc. Some more elaborate functions could be supported by passing a user-defined function in the "function" prop, where the function is passed a reference to the data array and key, and returns a single value used to set the line position.

**Comment by Eric24** [comment]
As a follow-up to this, just allowing "x" or "y" props to be set to a user-defined function (that returns the single value for the line) would be an even simpler enhancement.

**Comment by xile611** [comment]
@Eric24 When you specify the `x` or `y` to be a function, what about the parameters received ?

**Comment by Eric24** [comment]
I think parameters passed into the function, if any, would be very specific to the function and so would need to be supplied by the user as arguments to the function in its declaration. I don't see any need for any "dynamic" parameters to be sent.

**Comment by xile611** [comment]
@Eric24 If so, I think It's almost same to specify the `x` or `y`  to be a calculated value or a calculating function.

**Comment by xile611** [comment]
@Eric24 

In this [demo](http://jsfiddle.net/dnstf91y/), we calculate the mean value of 'pv' outside.
If `y` can receive a function, the only difference is that you'll need to bind data outside, and this function will be called inside like the following:

```jsx
function calculateMeanValue(list, key) {
	const cnt = list.length;
  	
  if (cnt <= 0) { return 0; }
  
  return list.reduce((sum, entry) => (sum + (entry[key] || 0) ), 0) / cnt;
}

<ReferenceLine y={calculateMeanValue.bind(null, data, 'pv')} label="Mean" stroke="red"/>
```

So I think It's more flexible to calculate the value outside if  the calculation does not need any  dynamic parameter.

**Comment by Eric24** [comment]
Yes, that's exactly what I had in mind. Thank you!

**Comment by Eric24** [comment]
PS - Not a big deal, but if you ever think about enhancing this, it would be nice to pass the data (as defined in the chart) to the function.
