### ISSUE TITLE
Pie labelRadius prop

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#533]
I know it's possible to use a custom label formatter to do labels inside pie "slices", but that seems like such a common thing to do that a simple labelRadius prop (which would work the same way as inner/outerRadius, except that it sets the radius that the labels are drawn at (anchor:middle/baseline:middle).

As a bonus, you might consider an "angle" prop that would control the rotation of the individual labels, with a value of 0 meaning "no rotation" and a value of "radial" meaning rotation based on the angle of the text location (i.e. radial lines extending from the center of the pie would be perpendicular to the baseline of each label's text).

**Comment by xile611** [comment]
@Eric24 You can specify the radius of label by an object `{ offsetRadius: 10 }`. About the `angle` props, I think the labels of `angle 0` is easier to read than `radial` labels.
And for recharts, not all the features are  appropriate to implemented internally, so It's recommended to implement the radial label by customized labels.

**Comment by Eric24** [comment]
Interesting, but it doesn't quite work:
![image](https://cloud.githubusercontent.com/assets/685316/23393139/44a4de7a-fd46-11e6-9fb0-216223eff8cc.png)

I suspect the text alignment/baseline is off (I tried setting these in the object, but I could not find a combination that had any effect). Also, While inner/outerRadius can be set as a percentage (thus creating a size-responsive pie chart), offsetRadius seems to only accept a numeric fixed pixel value.

Regarding angle, that's fine, I realize not everything can or should be a built-in feature. And I agree that angle 0 is easiest to read, but we have seen some use cases where radial alignment around a partial pie/donut is desirable.

**Comment by xile611** [comment]
@Eric24 
Eh! It's recommended to use customized label for some special cases.
And for the text alignment/baseline, I'll refactor `Pie` to calculate internally.

**Comment by Eric24** [comment]
Sounds good. For simple stuff like putting the label inside the pie/donut slice, that shouldn't require external code. I agree that the "base library" can't possible cover all use-cases, the trick is sometimes to figure out where that line is.

**Comment by Eric24** [comment]
PS - This may get fixed with the alignment/baseline fix, but notice that there is a significant difference in label position between offsetRadius:0 (or omitted) and offsetRadius:1 (or -1).

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
