### ISSUE TITLE
CartesianGrid in foreground

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#534]
Is there currently a way to get the CartesianGrid to show in front of the data series? For area and some bar charts, a CartesianGrid that's drawn behind the data series isn't very useful.

**Comment by xile611** [comment]
@Eric24 I can't agree with your point. CartesianGrid is an auxiliary element in charts. It'll disturb the display of area or bars to put the CartesianGrid. Can you give an example of online chart which need to show CartesianGrid foreground?

**Comment by Eric24** [comment]
Our specific use-case was with a "100%" area chart, where the area plots completely cover the background (and the grid). I know we could reduce the opacity of the areas to have the grid show through, but it seemed like support for an "isFront" prop on the grid would have been better/easier in this case.

**Comment by xile611** [comment]
@Eric24 Props `isFront` is not a good idea. Maybe someday someone would want the CartesianGrid to be in the front of a `Line`, but to be in the back of an `Area`,

But I'm curious about the `100%` area chart. Is that just a background rectangle of chart ?

**Comment by Eric24** [comment]
Perhaps mine is an edge case. I ended up going with semi-transparent area plots with the grid behind.

And yes, the 100% area chart is one where the various area plots are forced to fill the entire chart rectangle (so without going semi-transparent, the grid is completely hidden).

**Comment by xile611** [comment]
@Eric24 OK! If so, I would close this issue temporarily.
