### ISSUE TITLE
Multiple bar charts with Animation amongst them.

### ISSUE THREAD

**Issue by ajay-studio137** [recharts/recharts#5347]
## Do you want to request a feature or report a bug?
I want to animate bar chart from zero.

## What is the current behavior?
We are showing multiple bar chart with dynamic bars with only one bar graph visible to the user at a time. When toggling from one bar graph to another, the bar chart animates and bar moves in the air. 
<img width="619" alt="bar" src="https://github.com/user-attachments/assets/a9527e11-9da5-4d0f-8a27-62d07c8f43e5" />

## What is the expected behavior?
I want the bar to move from 0.

```
<Bar dataKey="value" fill="#2AAD8F" barSize={30} radius={[4, 4, 4, 4]} background={<CustomBackground />} isAnimationActive={true} animationBegin={0} animationDuration={1500} animationEasing="linear" >
</Bar>
```

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Latest version of recharts on MacOS.

**Comment by ajay-studio137** [comment]
Hi Coltin,

Thank You for your response.

Here is the working URL:- https://playcode.io/2191244

**Comment by ckifer** [comment]
You can turn animation off onAnimationEnd https://codesandbox.io/p/sandbox/line-chart-width-xaxis-padding-forked-cc52fd?workspaceId=ws_G5Rnj5KjeM4fNQbHpKaCKS

**Comment by ajay-studio137** [comment]
Opening a different barchart for each option made it work.
