### ISSUE TITLE
Feature Request - Radar Chart Tooltips

### ISSUE THREAD

**Issue by tsnevillecom** [recharts/recharts#536]
I am layering quite a few radars on a radar chart The tooltips display data of the active (or top) layer, ignoring the data below. It would be nice to have an option to display the data within the active "wedge" or axis of the radar chart. Similar to the tooltip cursor attribute for Bar Charts... allow a hover state and data display for the active wedge or axis, instead of radar layer.

**Comment by xile611** [comment]
This feature has been released in 1.0.0-alpha.0.
