### ISSUE TITLE
Tooltip cursor set <Cross /> not work

### ISSUE THREAD

**Issue by Viciivodka77** [recharts/recharts#5363]
## Do you want to request a feature or report a bug?

i want to change the Tooltip cursor default line style in the LineChart.
<img width="491" alt="image" src="https://github.com/user-attachments/assets/ed71bf8d-4648-439c-8ed3-3b309b33c690" />

and i find the ScatterChart tooltip default style is what i want, like cross line.
<img width="463" alt="image" src="https://github.com/user-attachments/assets/b2d317c8-f7ff-4323-bc98-fa31eb4a72ae" />

finally,  i set `<Tooltip cursor={<Cross />} />` but not work.

<img width="641" alt="image" src="https://github.com/user-attachments/assets/2be0a6dc-8a7c-479e-8e18-fc2c5f66a595" />

btw, the documentation is not detailed enough, :(

**Comment by Viciivodka77** [comment]
https://codesandbox.io/p/sandbox/tooltip-cursor-set-cross-not-work-kvs8gw

**Comment by ckifer** [comment]
The storybook might help you a bit in term of the docs. 
https://master--63da8268a0da9970db6992aa.chromatic.com

This is not possible as the 
Line tooltip does not yet support targeting an individual item. It only supports the whole index of an X axis as seen in your screenshot. You could, if props were passed in correctly, use Cross as a cursor component but it would not do what you expect it to as it would only have the needed x position, not the y. 

Scatter requires both X and Y which is how it can render like it does.

**Comment by Viciivodka77** [comment]
thank ur reply,and has any props or component like Echarts's axisPointer that can allow the y line follow the pointer ?
<img width="538" alt="image" src="https://github.com/user-attachments/assets/a711162a-0bb3-4284-a67a-afb11fb2e0f1" />

**Comment by ckifer** [comment]
Sure, you can do that with some custom work
https://codesandbox.io/p/sandbox/tooltip-cursor-set-cross-not-work-forked-vjttdr
