### ISSUE TITLE
Yaxis labels failed

### ISSUE THREAD

**Issue by bigearsenal** [recharts/recharts#537]
Follow this link, my data is normal, but the label for YAxis is failed when I use domain={['auto', 'auto']}.
http://jsfiddle.net/bigearsenal/6hcfzj37/
I tried to remove an object
` {
      "currency": 22,
      "date": "2017-02-15T21:00:00.000Z",
      "value": 39.9156
    },`
and it works well again.
http://jsfiddle.net/bigearsenal/6hcfzj37/3/
So what is the problem?
Thank you

**Comment by bigearsenal** [comment]
The problem is still there
http://jsfiddle.net/bigearsenal/6hcfzj37/4/

**Comment by xile611** [comment]
@bigearsenal Sorry! It has been fixed in 0.21.1.

**Comment by xile611** [comment]
@bigearsenal FIxed in 0.21.2

**Comment by bigearsenal** [comment]
@xile611 I've checked. Thanks for awesome work! (y)
