### ISSUE TITLE
add stackId to <Line /> trigger the Y axis to have as max value the sum of the data

### ISSUE THREAD

**Issue by BenjaminLesne** [recharts/recharts#5391]
## Do you want to request a feature or report a bug?
feature request

## What is the current behavior?
When adding `stackId="1"` to all my `<Line />` elements, the Y-axis max value becomes the sum of all values in the data, as it would for a stacked graph. This create a huge gap between the biggest value and the top of the graph.

No type errors or warnings appear in the IDE when using the spread operator on an object to pass the stackId prop to the `<Line />` components.

## Minimal demo of the problem:

https://codesandbox.io/p/sandbox/xypl57

## What is the expected behavior?
I don't know, I guess the current behavior is expected but I wish the consequences of adding the stackId prop were more obvious, or maybe ignore the stackId prop for Line graphs since stacked Line charts are not a thing right? 

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
2.12.7 is affected.
I don't know if it worked in previous versions.

**Comment by ckifer** [comment]
Line components do not support stackId, if it exists in the types then it needs removed. Will check that. 

Only Area and Bar can be stacked.

**Comment by ckifer** [comment]
https://codesandbox.io/p/sandbox/line-chart-width-xaxis-padding-forked-j3s43l

Looks like there is a type error here when stackId is provided to Line.
Your sandbox is using Javascript, which will not throw type errors of any kind.

I don't see this as a feature request or a bug.

What are you hoping to achieve with a stacked line graph?

**Comment by BenjaminLesne** [comment]
@ckifer I think the types are good, I get a type error here:

```tsx
<Line stackId="1" />
```

But if I do this I don't:
```tsx
const myProps = {
stackId: "1"
}

<Line {...myProps} />
```

> Your sandbox is using Javascript

Oops, sorry, I found this behavior in my codebase which use typescript

> What are you hoping to achieve with a stacked line graph?

I had a sharedProps variable for my graphs (2 stacked graphs, 1 line graph). 
The sharedProps variable included the stackId (oopsie) and it took me a while to understand why my Line graph Y axis max value was so high.

Sorry for being so confusing :pray:

**Comment by ckifer** [comment]
yeah - ideally `stackId` being set does not effect anything. I think this should be the case in 3.0.

In the meantime, no type error with the spread operator is just a typescript thing - nothing I can do about that unfortunately.

**Comment by ckifer** [comment]
Going to close this, thanks!
