### ISSUE TITLE
Button inside tooltip not working.

### ISSUE THREAD

**Issue by ajay-studio137** [recharts/recharts#5395]
## Do you want to request a feature or report a bug?
Button inside tooltip is not clickable.

## What is the current behavior?
On clicking over button, nothing happens. If I add `pointer-events: all` to button, on hovering over tooltip, its getting hidden.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via codesandbox or similar (template: https://codesandbox.io/p/sandbox/simple-line-chart-v25dl4).
```
const BarTooltip = ({ active, payload, label }) => {
    if (active && payload && payload.length) {
      return (
        <div
          className="bar-tooltip"
        >
          <p>We are testing out the button</p>
          <button onClick={(event) => { event.stopPropagation(); console.log("Create Circle")}}>Circle</button>
        </div>
      );
    }
  
    return null;
};
```
## What is the expected behavior?
I expect the button to clickable and show some output on console.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Latest versions are used for both.

Thanks for reading this.

**Comment by ckifer** [comment]
Was it you and I who talked about this already? I forget. 

Either way, first of all buttons inside tooltips are an accessibility concern and generally not recommended. 

Pointer events all will allow the button to be clickable but will also trigger the click event of the element behind it. 
https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events#all

I'm not really sure how to keep both here. You need the event on the button click, you also need the event on the chart.

**Comment by ajay-studio137** [comment]
After adding `pointer-events: all` to button, on hovering over tooltip, the tooltip is getting hidden. Thank You.

**Comment by ckifer** [comment]
Sure thing
