### ISSUE TITLE
Bug: Tooltip shared=false coordinate in bar chart

### ISSUE THREAD

**Issue by PavelVanecek** [recharts/recharts#5399]
See Storybook > Examples > BarChart > Stacked

```
        <BarChart {...args}>
          <CartesianGrid strokeDasharray="3 3" />
          <XAxis dataKey="name" />
          <YAxis />
          <Legend />
          <Bar dataKey="pv" stackId="a" fill="#8884d8" activeBar={{ fill: 'gold' }} />
          <Bar dataKey="uv" stackId="a" fill="#82ca9d" activeBar={{ fill: 'silver' }} />
          <Tooltip shared={false} />
        </BarChart>
```

Tooltip coordinates are always 0,0 and it does not follow mouse movement. This is new, it worked fine in 2.x

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

Updated the Tooltip component to correctly handle coordinate updates and follow mouse movement. This fix addresses the issue where the Tooltip was stuck at (0,0) in the BarChart example.

You can review changes in this commit: https://github.com/mark-addams001881/recharts-recharts-5399/commit/7c10298f301eacd18e336fe3b5ba1c35d6c55e43.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by PavelVanecek** [comment]
Oh nice. Not exactly the fix we were looking for but it might be useful for some other problems.

**Comment by ckifer** [comment]
I think that account is a bot 😅

**Comment by PavelVanecek** [comment]
I figured. If we can get the robot to fix some smaller problems then I would be happy.
