### ISSUE TITLE
Unique key problem in <ComposedChart /> render

### ISSUE THREAD

**Issue by kasasi** [recharts/recharts#540]
Since the new version i'm getting this:
"Each child in an array or iterator should have a unique "key" prop. Check the render method of `ComposedChart`."

Am I missing something? This is the code i'm using to create the chart:

![image](https://cloud.githubusercontent.com/assets/18700777/23399729/9d53f74e-fda1-11e6-9319-c25569a86472.png)

I was able to fix it by adding a random key as a prop to the `Chart` component in the mapping function of the render method in the ComposedChart class.
But now the lines always rerender and animate while hovering.

**Comment by xile611** [comment]
@kasasi It's seems that `lineKey` has duplicated value.

**Comment by kasasi** [comment]
Thanks for the fast answer.

I checked these keys. They are all unique and if I don't add them i'm getting the unique key warning twice.
I even get this warning if I use the code of the documentation.

![image](https://cloud.githubusercontent.com/assets/18700777/23401926/c740a018-fda9-11e6-9bc6-8938a495e273.png)

**Comment by kasasi** [comment]
Sorry wasting your time. I just got that little f***!
Sometimes npm is a true devil. Told me i had installed the newest version but had an old one. After a totally new installation everything works fine.
Thanks for the help anywas ;)
