### ISSUE TITLE
AreaChart: v0.20.7 broke domain setting

### ISSUE THREAD

**Issue by loris** [recharts/recharts#541]
Here is a simple AreaChart (not sure if other charts are affected) with a `domain={['auto', 'auto']}` prop on the `YAxis`.
- `v0.20.7`: http://jsfiddle.net/c6kvLkn2/
- `v0.20.6`: http://jsfiddle.net/7feeL86k/

As you can see, the Y axis on the chart running 0.20.7 starts at 0 instead of 1800. Same issue if using `dataMin`, etc.
I'm not sure what the issue is, but having a quick look at the diff (https://github.com/recharts/recharts/compare/v0.20.6...v0.20.7) hints this is a regression introduced by the `mirror` setting.
Thanks.

**Comment by xile611** [comment]
@loris 
Before 0.20.6, when only one `Bar` has `stackId`, it'll be treated as not stacked bar.
After 0.20.7, event if only one `Bar` has `stackId`, it'll be treated as a stacked bar to fix some bug. 
And stacked bars are stacked from  0, so make the difference.

It's recommended to remove `stackId` in your case.
