### ISSUE TITLE
Add brush to Y-Axis

### ISSUE THREAD

**Issue by houseofaragon** [recharts/recharts#542]
Is it possible to scale Y-axis when using the Brush component? Here's a d3 example:
http://bl.ocks.org/davidshinn/7903976

**Comment by matepaiva** [comment]
@houseofaragon did you find your answer? could you tell us how did you solve this?

**Comment by abarandica** [comment]
Any idea?

**Comment by petr-stepanek** [comment]
I haven't found any way to add a brush to the Y-axis, but it is possible to change (to limit) the domain of the Y-axis using this trick: 
~~~ js
domain={[ 0, dataMax => (10) ]}  
~~~
I found it here: https://stackoverflow.com/questions/53751564/can-i-set-the-recharts-axis-domain-max-lower-than-datamax and here is a simple example with Y-axis data limited to `[0, 5000]`, even though the underlining data are bigger: https://jsfiddle.net/yek0Ln1b/
