### ISSUE TITLE
Barsize doesnt work when updated to this new version 0.21.2

### ISSUE THREAD

**Issue by kadariyp** [recharts/recharts#543]
Barsize doesnt work when updated to this new version 0.21.2.  It does not accept the bar size and calculates it internally. Can you please check?

**Comment by kadariyp** [comment]
It works in 0.20.2, the last version i was using. whebn i updated it, the barSize doesnt take effect at all. Any idea why?

**Comment by xile611** [comment]
@kadariyp Can you create an online demo ?

**Comment by xile611** [comment]
@kadariyp You can reopen this issue if an online demo is created.

**Comment by eranimo** [comment]
Can confirm this is still the case
