### ISSUE TITLE
ReferenceLine not appearing when returned from inside component

### ISSUE THREAD

**Issue by Arrow7000** [recharts/recharts#544]
I think I've found a bug. I am trying to create a ScatterChart with a ReferenceLine. I want to put the ReferenceLine inside a Redux connected component, which means I have to put it in a separate custom component. 

The problem is that unless I explicitly place the ReferenceLine inside the chart it doesn't appear in the chart at all. Even if I put it in a simple wrapper component the ReferenceLine disappears.

Here is a JSFiddle: http://jsfiddle.net/9xjjuwkk/27/

**Chart**
```
class Chart extends Component {
    render() {
        const { now } = this.props;
        return (
            <ResponsiveContainer width="100%" height={400}>
                <ScatterChart >
                    <CartesianGrid strokeDasharray="3 3" />
                    <Scatter name="vector" data={data} fill='#8884d8'
                        line
                        shape={shape} />
                    <XAxis dataKey="time" name="time" unit="seconds" label="seconds" domain={[0, 1]} />
                    <YAxis dataKey="vector" unit="g" name="acceleration" />
                    <ReferenceLine x={0.5} stroke="red" strokeDasharray="3 3" label="Crash" />
                    <NowLine now={now} /> {/* should also return ReferenceLine */}
                </ScatterChart>
            </ResponsiveContainer>
        )
    }
}
```

**Component that returns a ReferenceLine**

```
class NowLine extends Component {
    render() {
        const { now } = this.props;
        return (
            <ReferenceLine x={now} stroke="blue" strokeDasharray="3 3" label="Current" />
        )
    }
}
```

There should be two reference lines inside the chart, a red one which is placed inside the chart explicitly, and a blue one which should be returned through the NowLine component. However the blue one doesn't appear. Why is this the case?

I am using recharts v0.20.8 on Chrome 55/Windows 7.

This could be related to #41 but I'm not 100% sure. 

Any help would be appreciated!

**Comment by xile611** [comment]
@Arrow7000   

You must use component `ReferenceLine` not a customized component.
Check the [code](https://github.com/recharts/recharts/blob/master/src/chart/generateCategoricalChart.js#L1040) for detail.

When we render `ScatterChart`, we'll check the `type` of children to find out the `ReferenceLine` instances and append some props to the instances. So If you add a customized component to the `ScatterChart`, we can't identify it as a `ReferenceLine` element.

```jsx
              <ResponsiveContainer width="100%" height={400}>
                <ScatterChart >
                    <CartesianGrid strokeDasharray="3 3" />
                    <Scatter name="vector" data={data} fill='#8884d8'
                        line
                        shape={shape} />
                    <XAxis dataKey="time" name="time" unit="seconds" label="seconds" domain={[0, 1]} />
                    <YAxis dataKey="vector" unit="g" name="acceleration" />
                    <ReferenceLine x={0.5} stroke="red" strokeDasharray="3 3" label="Crash" />
                    <ReferenceLine x={now} stroke="blue" strokeDasharray="3 3" label="Current" />
                </ScatterChart>
            </ResponsiveContainer>
```

**Comment by Arrow7000** [comment]
Right... Ok I understand. But can't something be done about this? 

The reason I want to put it inside a customised component is that I my graph displays a ton of data, and forcing React to recompute the component tree on change of a single prop (`now`) is making the whole chart slow down - hence why I need to put the ReferenceLine inside of a redux connected component, to avoid an entire component rerender.

Hm. What if in addition to checking if the inside component is a ReferenceLine , the chart also checked for the presence of a special prop to indicate that that component returns a reference component? 

Eg something like `<CustomComponent isReference={true} />`?

**Comment by Arrow7000** [comment]
I suppose my real question is: how can I change a ReferenceLine without forcing the entire chart recompute? That's what I'm really struggling with. When you have a few hundred/thousand of data points the entire page starts going janky - especially if you're trying to update a prop several times a second.

That's the reason why I want to put the ReferenceLine inside a connected component, so it connects directly to a redux store, bypassing the prop chain, thereby avoiding a chart recompute. 

However if the ReferenceLine actually just adds props onto the parent chart then does that mean avoiding a recompute is not possible?

**Comment by xile611** [comment]
@Arrow7000 

The chart will update every time the value of `ReferenceLine` change.
I've no idea now...

**Comment by Arrow7000** [comment]
Ok... can you at least reopen this issue then so someone else can find it?

**Comment by xile611** [comment]
@Arrow7000 But even when recharts can receive a customized component, your problem can't be resolved.  Every time the props `now` update, the chart'll update.

**Comment by Arrow7000** [comment]
Exactly - which is a problem. Maybe it would be possible for someone to create a pull request with some code refactors that would allow one part to update without the other? 

Either way the problem still exists; it may not be a bug as such, but it's still a problem.

**Comment by LR-brendan** [comment]
Is there any solution to this problem yet?
I am trying to do the same thing as @Arrow7000, i.e create a Redux connected ReferenceLine which is required to only re-render this the reference line and not entire graph.

**Comment by dmitryvmin** [comment]
I was having the same issue trying to componentizing different chart components, e.g.: Tooltip, YAxis, XAxis, etc. 

My solution was to call the FCs as a fucntion instead of using JSX / React.createElement().

Instead of
```
<AverageLine
    key={}
    axisOrientation={orientation}
    average={average}
/>
```

````
...return AverageLine({
    key: `averageLine-${axis}-${orientation}`,
    axisOrientation: orientation,
    average: average,
});
```

When called explicitly, the "type" property gets correctly - `ƒ ReferenceLine()`.

**Comment by warrenha** [comment]
For recharts 2.1.10, the ReferenceLine is a function component (unlike in v1.8.5). I found you can trick it rendering your wrapper for ReferenceLine by setting "displayName" and "defaultProps"...

```
import * as React from 'react';
import { ReferenceLine } from 'recharts';
import type { Props as ReferenceLineProps } from 'recharts/src/cartesian/ReferenceLine';

type Props = ReferenceLineProps;

const MyReferenceLine = (props: Props) => {
    console.info('MyReferenceLine | RENDER');
    return (
        <ReferenceLine {...props} />
    );
};

// Without the following, recharts will not render the component!
MyReferenceLine.displayName = ReferenceLine.displayName;
MyReferenceLine.defaultProps = ReferenceLine.defaultProps;

export default MyReferenceLine;
```

**Comment by jdthorpe** [comment]
Just to add to @warrenha's answer, and add motivation as to why this matters, I had a little app with 15 charts (in a 3x5 matrix) each of which took ~0.5 seconds to update the indicator line because the entire chart re-renders when passing the `x` into the chart label in the usual way for an awful 7.5 second re-render time.  Switching to a context manager like this dropped the render time to 0.8ms for a 10,000x performance boost:

```tsx
export const myLineContext = createContext<[string, (x: string) => void]>(["", () => { }])

const ActiveWeekLabel: typeof ReferenceLine = (props) => {
  const xlabel = useContext(myLineContext)[0]
  if (!xlabel) return <></>
  return <ReferenceLine {...props} x={xlabel} />
}

ActiveWeekLabel.displayName = ReferenceLine.displayName;
ActiveWeekLabel.defaultProps = ReferenceLine.defaultProps;
```

**Comment by michaelwooley** [comment]
Adding on to @warrenha's answer, you want any non-default/custom props to be listed _after_ the default `...props`:

```ts
import * as React from 'react';
import { ReferenceLine } from 'recharts';
import type { Props as ReferenceLineProps } from 'recharts/src/cartesian/ReferenceLine';

type Props = ReferenceLineProps;

const MyReferenceLine = ({stroke,...props}: {stroke:string} & Props) => {
    console.info('MyReferenceLine | RENDER');
    return (
        <ReferenceLine 
              {...props}  // First auto-filled props
              stroke={stroke} // Then custom props
          />
    );
};

// Without the following, recharts will not render the component!
MyReferenceLine.displayName = ReferenceLine.displayName;
MyReferenceLine.defaultProps = ReferenceLine.defaultProps;

export default MyReferenceLine;
```

**Comment by equinusocio** [comment]
FYI `defaultProps` is deprecated since React 15, and also `displayName` is gone..

**Comment by ckifer** [comment]
You don't need to rely on either once 3.0 comes out
