### ISSUE TITLE
How to use Dots with LineChart and ComposedChart?

### ISSUE THREAD

**Issue by dadamssg** [recharts/recharts#546]
I would like to know how to  render arbitrary dots representing events over a line chart. Is this possible and if so, how? 

[I tried this with no luck. ](http://jsfiddle.net/x1yoboc7/484/)

I'm trying to achieve this:

![screen shot 03-02-17 at 02 34 pm](https://cloud.githubusercontent.com/assets/881986/23527485/bfccc498-ff5b-11e6-9b49-27c866f75ffb.PNG)

**Comment by xile611** [comment]
@dadamssg Use component `ReferenceDot`.

[API](http://recharts.org/#/en-US/api/ReferenceDot)

**Comment by dadamssg** [comment]
@xile611 thank you! Can you point me to an example that uses the `label` prop of a `ReferenceDot`? I'm trying to use it within a `ComposedChart` but it's not working. 

![screen shot 03-03-17 at 08 39 am](https://cloud.githubusercontent.com/assets/881986/23555033/f798da74-ffec-11e6-8b0c-48ec1592f90c.PNG)
![screen shot 03-03-17 at 08 39 am 001](https://cloud.githubusercontent.com/assets/881986/23555035/fa56fba6-ffec-11e6-96e5-70268b1e51e4.PNG)
