### ISSUE TITLE
Line area only composed chart without extra space from Bar

### ISSUE THREAD

**Issue by chin-idean** [recharts/recharts#547]
Do you want to request a feature or report a bug?

feature

What is the current behavior?

The only way to remove extra space from Bar in Composed Chart is using scale=point in Xaxis, but i don't want to have any axis exist (chart only, no space around). Even if i remove axis line, ticks, tick, Xaxis itself still reserve some empty space below the chart

What is the expected behavior?

Line area only composed chart without extra space from Bar, no axis

**Comment by Eric24** [comment]
@chin-idean : I don't find that this is the case. If you don't include any axis components in your definition and you're still seeing space around the chart, you may need to set the margin property of the chart.

**Comment by chin-idean** [comment]
@Eric24 
Notice space cause by Bar on left and right edge
http://jsfiddle.net/vfnmdp53/52/

**Comment by Eric24** [comment]
@chin-idean : Try this:
`<XAxis hide={true} scale="point" />`

**Comment by chin-idean** [comment]
It worked 👍  Thanks @Eric24
