### ISSUE TITLE
Is there a way to set color on XAxis, YAxis.

### ISSUE THREAD

**Issue by atompie** [recharts/recharts#548]
_Do you want to request a feature or report a bug?_
REQUEST

_What is the current behavior?_

Could not set white color on XAxis, YAxis. Therefore could not make charts that has dark background.
Or maybe I am missing something.

**Comment by Eric24** [comment]
@atompie : You can just set stroke="white" on the axis components.

**Comment by Chris-Petty** [comment]
This appears to have come up a few times, I am here after trying to find the this solution. Naturally the first place I had looked was [the docs for the axis components](http://recharts.org/#/en-US/api/XAxis), but they don't actually mention stroke as a prop at all. Nor do any other components by the looks.

It might be worth adding it to docs, or making a summary page of styling props if it applies to all recharts components and it's felt that it'd bloat the docs to add them everywhere.
