### ISSUE TITLE
React 15.0 support

### ISSUE THREAD

**Issue by portons** [recharts/recharts#55]
In React 15 you can now use native SVG properties, which means **className** becomes **class**, etc..

Current version of Recharts throws these warnings:
`Warning: SVG property className is deprecated. Use the original attribute name class for SVG tags instead.`

**Comment by xile611** [comment]
Thanks. Recharts will support React 15.0 in next version

**Comment by arcthur** [comment]
we already support react 15.0 in v0.9.2
