### ISSUE TITLE
Warning: You are manually calling a React.PropTypes validation function for the ...

### ISSUE THREAD

**Issue by sisiguo** [recharts/recharts#550]
Do you want to request a feature or report a bug?
Bug report

What is the current behavior?
Console logs hundreds of the same errors when trying use Recharts:
```jsx
<LineChart width={400} height={400} data={data}>
    <Line type="monotone" dataKey="uv" stroke="#8884d8" />
</LineChart>
```
<img width="558" alt="screen shot 2017-03-03 at 10 22 58 pm" src="https://cloud.githubusercontent.com/assets/8635054/23576650/0069a1ba-0060-11e7-84d4-c92b6fd3b369.png">

What is the expected behavior?
No errors logged

Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts version 0.21.2 on Chrome browser and OS X El Capitan

**Comment by xile611** [comment]
@sisiguo I can't reproduce this problem. Please check your dependencies, maybe you have used some third-party PropTypes library.
