### ISSUE TITLE
Mirrored YAxis tick labels are hidden on mouseOver

### ISSUE THREAD

**Issue by kaelhem** [recharts/recharts#551]
I've got a BarChart with mirrored ticks on YAxis and Tooltip.
When, the mouse is over a Bar, the corresponding tick label is hidden by the "mouse-over background effect".

The fiddle will be more understandable I hope!
http://jsfiddle.net/u8udorvy/196/

Does this behavior can be avoided?

**Comment by xile611** [comment]
Change the order of <YAxis /> and <Tooltip /> can resolve this.

[Check this demo](http://jsfiddle.net/bbuktzo8/).
