### ISSUE TITLE
ReferenceLine label shows on side opposite the assigned axis

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#552]
Do you want to request a feature or report a bug?
Maybe a bug, but maybe just a question.

What is the current behavior?
A ReferenceLine with a label, assigned to a particular axis, the label always shows on the side opposite of the axis. For example, if the ReferenceLine is assigned to the Y-Axis on the left side of the chart, the label appears on the right side of the chart. I suppose this is "good" behavior if there is only one visible Y axis, but when there are two (one on each side), it's confusing to have the label appear "inside" the other axis.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/9y45ut13/).

What is the expected behavior?
Ideally, the label would have a way to choose its position.

Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Latest ReCharts; any browser.

**Comment by xile611** [comment]
Try the latest version 1.0.0-beta.1. And try the label has different ["position"](http://recharts.org/#/en-US/api/Label).
