### ISSUE TITLE
Tooltip Behavior

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#553]
Do you want to request a feature or report a bug?
Feature (unless there is a way to handle this now)

What is the current behavior?
If the user moves the mouse inside the chart area and triggers the tooptip, it will disappear as soon as the chart is updated (i.e. receives new data). That may be fine for static charts, but for charts that are receiving new data in real-time, it's very annoying. As a possible workaround, we had considered "pausing" the data updates when the tooltip is shown (although this isn't the best solution), but there is no event that lets us know if the tooltip is visible or not. But in any case, the better behavior would be for the tooltip to remain visible even if the chart is updated.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/9y45ut13/).

What is the expected behavior?
Ideally, the tooltip would remain visible until the user moves the mouse outside the chart area.

Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Latest ReCharts; any browser.

**Comment by gvaldambrini** [comment]
Same issue here. I made a fix (not extensively tested to be honest) for the 0.22.4 version here:
https://github.com/develersrl/recharts/commit/b5fa5c2cc6690d34b90693e0f5c2e15d90d9defd

**Comment by dmr** [comment]
Another behavior that we noticed is that the tooltip disappears after a short while if the user doesn't move the cursor --> Is this configurable somehow?

**Comment by WeeJeWel** [comment]
+1

**Comment by James-E-Adams** [comment]
Same issue here. This is how it manifests for me:

![tooltip](https://user-images.githubusercontent.com/9067274/36246998-61d3fbd8-1286-11e8-9b33-34b7c2eb3b64.gif)

**Comment by simonhessner** [comment]
I have the same issue in the newest version (1.8.5). Why was this closed?

Related:
https://github.com/recharts/recharts/issues/1220
https://github.com/recharts/recharts/issues/2143

**Comment by simonhessner** [comment]
I made a pull request that fixes the problem: https://github.com/recharts/recharts/pull/2150
