### ISSUE TITLE
How to customise the X-axis and Y-axis labels?

### ISSUE THREAD

**Issue by bhupendra-nitt** [recharts/recharts#555]
I am working on ReactJs app and want to show some historical data of 3 years with entries as big thousands in number, I want to plot the entire points but the X-axis labels I want to be on monthly basis.

**Comment by mknabe** [comment]
check out the `tickFormatter` property on the `XAxis`

**Comment by xile611** [comment]
@bhupendra-nitt You can specify the `ticks` of `XAxis`  and `YAxis`.
