### ISSUE TITLE
When zoomed in via Brush a non-Brush interaction rerenders the whole data

### ISSUE THREAD

**Issue by dudel** [recharts/recharts#558]
When a chart is zoomed in by having used the Brush and then a non-Brush interaction rerenders the chart the whole data is used to render the chart instead of only the data specified by the brush. 

As example I used the LegendEffectOpacity example and just added a brush: http://jsfiddle.net/4mgLq2tk/1/. Use the brush and then hover over a legend item to see the chart reset.

**Comment by ZephD** [comment]
Probably the same problem as #401 .

**Comment by ZephD** [comment]
Checking my fiddle: http://jsfiddle.net/b1Lb3kuk/10/ (which is auto updated to latest recharts v0.22)
It DOES seem to be fixed! Well done Xile611! Thank you :D
