### ISSUE TITLE
Area Chart animation - Bottom to top

### ISSUE THREAD

**Issue by cesargdm** [recharts/recharts#559]
**Feature** - Area chart animation

Add area chart animation to grow from bottom to top, this would be a better approach when animating when data decreases and charts just low their height.

**Comment by xile611** [comment]
@cesargdm Try the latest version 1.0.0-beta.1

**Comment by mac-s-g** [comment]
@cesargdm Was this implemented?  I don't see a way to do it in the docs, but I would love to use this type of animation in my app.
AWESOME project btw! :100:

**Comment by PavelVanecek** [comment]
This will be possible in 3.9, here is a preview: https://recharts.github.io/recharts/pr-7215/www/en-US/examples/RangeAreaChartCustomAnimation/
