### ISSUE TITLE
Server Side rendering

### ISSUE THREAD

**Issue by NoWay1201** [recharts/recharts#56]
When Rendering Charts Server-Side, it's showing all ticks on scale, but when rendering Client-Side, it's cutting them to about 7-8 ticks. Which version is broken? And, maybe it's possible to give a possibility to choose if you want to cut ticks, or maybe you want to draw them all?

**Comment by xile611** [comment]
The default value of props `interval` in  `XAxis` and `YAxis` is `'auto'`, then we will calculate the width and height of each tick to determine whether there is enough space to display a certain tick. But the calculation can't be done on server side, so led the such inconsistencies. 
Maybe you can set the value of props `interval` in `XAxis` or `YAxis` to be a number, just like the following example. When you set the `interval` to be 0, then all the ticks will be drawn.
```jsx
  <LineChart data={data} width={400} height={400}>
     <XAxis dataKey="name" interval={0}/>   
     <Line dataKey="a"/>
   </LineChart>
```
