### ISSUE TITLE
onClick dot of Line

### ISSUE THREAD

**Issue by summersb** [recharts/recharts#560]
Do you want to request a feature or report a bug?
New feature

What is the current behavior?
You can only add an onClick event to the line portion of a line chart not the actual data point.  You can get the x axis data label but not the line value that was clicked.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/9y45ut13/).

What is the expected behavior?
I would like to subscribe to dot click events on each line and get the value of the dot.

<Line onDotClick={(xvalue, yvalue) => } >

Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
I am using 0.21.2 on MacOS 10.12.3 with Chrome 57

**Comment by MaheshIBM** [comment]
I also need this change, mostly its needed for drill down type of charts, where user clicks on a data point and then we need to load more data based on the point.

**Comment by jarodccrowe** [comment]
I would like the same, but also to be able to access any other data in that points' object if that's possible.

Use case would be to click a point that contains an id which I can then use in another api call.

**Comment by xile611** [comment]
Try the latest version 1.0.0-beta.3.

```jsx
<Line  dot={{ onClick: ... }} />
```

**Comment by andypotts** [comment]
`<Line activeDot={{onClick:this.handleClick}} />` worked for me.

**Comment by Anand25021998** [comment]
@andypotts I am using recharts v0.22.5 but <Line activeDot={{ onClick:this.handleClick }} /> is not working in my case. Can you tell me what version of recharts you are using ?

**Comment by kiranvj** [comment]
> `<Line activeDot={{ onClick:this.handleClick }} />` worked for me.

This worked for me in recharts v1.1.0

`activeDot={{onClick: ()=> {alert("clicked")} }}`

**Comment by icecoldmax** [comment]
Is it possible to have an activeDot handling function (that does a setState for example) but then also continue as if I'd just returned true?

 i.e. when I do:
`activeDot={this.handler}`

...the function gets the right payload, but then the tooltip doesn't show up. Nor does the gridline get highlighted, nor does the dot.

How can I get the active dot payload but also continue the default? I've tried returning true from the function but it doesn't work.

**Comment by swetha2** [comment]
Can anyone give an example of a function for activeDot attribute?

**Comment by swetha2** [comment]
i mean the return value of the function

**Comment by francisco4challenge** [comment]
Managed to get it working like this: 
`<Line type='monotone' dataKey='x' stroke='#ff7300' activeDot={{ onClick: (event, payload) => console.log(payload) }} />`

**Comment by simonhessner** [comment]
If I have defined a `onClick` event on the active dot and on the `LineChart` itself, both are fired on click. Is there something like `preventDefault` for these events?

**Comment by vemuez** [comment]
> If I have defined a `onClick` event on the active dot and on the `LineChart` itself, both are fired on click. Is there something like `preventDefault` for these events?

You can event.stopPropagation()

**Comment by kevinlinxc** [comment]
When I know the index of the dot that was clicked, how can I make the dot persistently active (as if it was being hovered over consistently)?

**Comment by severinlandolt** [comment]
Hi @kevinlinxc, did you manage to make the dot persistently active? Would love to see your solution :)

**Comment by kevinlinxc** [comment]
@severinlandolt I never figured it out, sorry
