### ISSUE TITLE
ErrorBars may fall off chart.

### ISSUE THREAD

**Issue by tkohlman** [recharts/recharts#561]
A chart with error bars, where the error is large enough to fall off the chart's axis:

![errorbarsoffchart](https://cloud.githubusercontent.com/assets/2357824/23808652/33928d60-0590-11e7-8aa0-378da33d0cd8.jpg)

Axis calculations need to consider error bars in min/max calculations.

**Comment by xile611** [comment]
@tkohlman It's resolved in 1.0.0.
