### ISSUE TITLE
How to implement only highlight specified lines? 

### ISSUE THREAD

**Issue by wuxudong** [recharts/recharts#563]
Just like the pic show, there is reference line, and a user line.

Is there any way to configure that only user line can be highlighted. and displayed in tooltip.

the reference line, behave just like background or [ReferenceLine](http://recharts.org/#/en-US/api/ReferenceLine)

![android-time-series-line](https://cloud.githubusercontent.com/assets/1391101/23832887/b1448cf6-0778-11e7-984a-f326cf585e4f.png)

**Comment by Eric24** [comment]
This is essentially a duplicate of #368
