### ISSUE TITLE
GroupBar chart with Secondary Axis

### ISSUE THREAD

**Issue by karna41317** [recharts/recharts#564]
Need simple example with Group Bar chart with secondary axis, Is it possible to render chart with existing chart components

I see these two examples so far

http://jsfiddle.net/millerized/r19hetwn/7/
http://jsfiddle.net/zh3z3znq/

and i am trying to acheive something like this 

<img width="1839" alt="screen shot 2017-03-14 at 17 56 32" src="https://cloud.githubusercontent.com/assets/840111/23912468/f66a4ef2-08df-11e7-838c-81502bc80893.png">

**Comment by xile611** [comment]
See [example](http://recharts.org/#/en-US/examples/BiaxialBarChart).
