### ISSUE TITLE
Bars with one data point do not display if XAxis and YAxis types are both 'number'

### ISSUE THREAD

**Issue by cephirothdy2j** [recharts/recharts#565]
If a data series only has one point, AND both the X axis and Y Axis are of the type 'number', AND the data is being displayed as a <Bar />, the bar fails to render. A tooltip shows that the data is there, and it does float to where the bar should render on the graph.

Fiddle - 
http://jsfiddle.net/1nu5d264/3/

This is only a problem with bar charts. Lines and areas behave as expected, and if the X Axis type is set as "category", the bar also displays.

**Comment by popadi** [comment]
Any updates on this? The bug still seems to be there.

**Comment by Bruledamien** [comment]
You can try adding a `barSize` to the `<Bar/>`. But you will loose the auto scaling of the bar size.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.

**Comment by Mudassar045** [comment]
@xile611 , above mention issue `still exists`. As I'm working with graphs using `recharts: ^1.8.5` which is latest, facing this problem.

**Comment by Mudassar045** [comment]
@xile611 I also tried with `recharts: 2.0.0-beta.4`, but not working.

**Comment by Mudassar045** [comment]
> You can try adding a `barSize` to the `<Bar/>`. But you will loose the auto scaling of the bar size.

this doesn't solve the problem.

**Comment by jukkahuuskonen** [comment]
This seems to be a problem still. on v.2.0.0-beta.6. This should be re-opened.

**Comment by Mudassar045** [comment]
> This seems to be a problem still. on v.2.0.0-beta.6. This should be re-opened.

Yes, it should be re-opened

**Comment by jukkahuuskonen** [comment]
made a new issue on this #2127
