### ISSUE TITLE
Generating Line Charts without the Circle Dot

### ISSUE THREAD

**Issue by velociwabbit** [recharts/recharts#568]
I am not sure whether this is a feature enhancement or there is a way to do it easily.
I am trying to create a chart like this: 

![image](https://cloud.githubusercontent.com/assets/9357805/23877159/32a6af92-07fe-11e7-9daa-76ed9f9662a1.png)

but the default for LineCharts has this code in it (that i disable) in order to **not** render the circles

```

 //     if (hasDot && activeDot && activePoint) {
 //       const dotProps = {
 //         index: activeTooltipIndex,
 //         dataKey,
 //         cx: activePoint.x, cy: activePoint.y, r: 4,
 //         fill: stroke, strokeWidth: 2, stroke: '#fff',
 //         payload: activePoint.payload,
 //         value: activePoint.value,
 //         ...getPresentationAttributes(activeDot),
 //       };
 //       dotItems.push(this.renderActiveDot(activeDot, dotProps, i));
 //     }
```
I am using the latest version and would prefer to use the library without custom mods.

Any help would be appreciated

**Comment by Eric24** [comment]
Add dot={false} to your Line component

**Comment by velociwabbit** [comment]
cheers it worked beautifully!
