### ISSUE TITLE
Question: Bar within a bar or "overlayed" bars

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#570]
Question: Is it possible to configure a bar chart so that one of the bars appears within/on-top-of another bar (or a bar stack)? Something like this:

![image](https://cloud.githubusercontent.com/assets/685316/23881102/323ab4cc-0826-11e7-92f6-2ddfe61afa48.png)

**Comment by xile611** [comment]
@Eric24 You can add two `XAxis` to render this kind of charts.

[Similar issue](https://github.com/recharts/recharts/issues/439)

**Comment by nahushf** [comment]
I've been looking for a similar feature, I tried using two X axes, but it doesn't seem to produce the desired effect: https://codepen.io/nahushf/pen/mgZgoG

**Comment by dustryder** [comment]
FYI: the barGap property of <BarChart> can be set to a negative value to overlap the bars. Haven't seen an example for this nor was it immediately obvious, so thought I'd mention it here.

https://codepen.io/dustryder/pen/qBNMgLJ

**Comment by Vansun0088** [comment]
Yeah it is good but what if we have dynamic number of bars and because of that we cannot set const value of barsize and gapsize?

**Comment by ckifer** [comment]
Probably some simple math can be done to determine bar gap based on the number of bars. Might not be perfect but will make it close enough and dynamic. also wonder if bar gap can be a percentage

**Comment by tropotorres** [comment]
In case anyone comes looking for this, I found out that you can get there by using the Composed Chart and setting the same X-axis, and then using a custom rectangle to get a wider one while maintaining responsiveness-

<img width="735" height="468" alt="Image" src="https://github.com/user-attachments/assets/14fd7e87-95db-4a57-a5b1-05cab9cc493e" />


```
import {
  ComposedChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  BarProps,
} from 'recharts';

// #region Sample data
const data = [
  {
    name: 'Page A',
    uv: 590,
    pv: 800,
    amt: 1400,
  },
  {
    name: 'Page B',
    uv: 868,
    pv: 967,
    amt: 1506,
  },
  {
    name: 'Page C',
    uv: 1397,
    pv: 1098,
    amt: 989,
  },
  {
    name: 'Page D',
    uv: 1480,
    pv: 1200,
    amt: 1228,
  },
  {
    name: 'Page E',
    uv: 1520,
    pv: 1108,
    amt: 1100,
  },
  {
    name: 'Page F',
    uv: 1400,
    pv: 680,
    amt: 1700,
  },
];

const ShadowBarShape = (props: BarProps) => {
  const { x, y, width, height, fill } = props;
  const adjustedWidth = (width as number) + 10;
  const adjustedX = (x as number) - 5;
  return (
    <rect
      x={adjustedX}
      y={y}
      width={adjustedWidth}
      height={height}
      fill={fill}
    />
  );
};

// #endregion
const OverlapComposedChart = () => {
  return (
    <ComposedChart
      style={{
        width: '100%',
        maxWidth: '700px',
        maxHeight: '70vh',
        aspectRatio: 1.618,
      }}
      responsive
      data={data}
      margin={{
        top: 20,
        right: 0,
        bottom: 0,
        left: 0,
      }}
    >
      <CartesianGrid stroke="#f5f5f5" />
      <XAxis dataKey="name" scale="band" />
      <YAxis width="auto" />
      <Tooltip />
      <Legend />
      <Bar dataKey="pv" fill="#213ea0" shape={ShadowBarShape} />
      <Bar xAxisId={1} dataKey="uv" fill="#00ffff" />
    </ComposedChart>
  );
};

export default OverlapComposedChart;
```
