### ISSUE TITLE
the pieChart don't show when then data 's  value is all zero

### ISSUE THREAD

**Issue by maryxi** [recharts/recharts#572]
![image](https://cloud.githubusercontent.com/assets/9864748/23883257/c50cef2a-08a0-11e7-99ac-41766002bd48.png)

![image](https://cloud.githubusercontent.com/assets/9864748/23883279/e351c4a6-08a0-11e7-8ca4-a691b633ed0c.png)

like this

**Comment by xile611** [comment]
@maryxi Yeah, because we can't calculate the percentage of each items when the denominator is 0.
When I such case, It's recommended to render some message in your project.
