### ISSUE TITLE
Question: Line Graph with Different data model

### ISSUE THREAD

**Issue by groy** [recharts/recharts#573]
Is it possible to get an example with a nested set of data? 

My data for example is formatted as follows:
`{reportData: [{
key: 2010,
values: [{
reportMonth: 1,
data: value
}, {
reportMonth: 2,
data: value2
}...]},{
key: 2011,
values: [{
reportMonth: 1,
data: value
}...]}
]`

Where I want to display a LineChart with a line corresponding to each key. and the XAxis spanning the 12 months of the year. Been struggling to figure out how to pass the data / dataKey into the library.

I have also tried with my data formatted like:
`{reportData: [{reportMonth: 1, data: value1, reportYear: 2010}, {reportMonth: 2, data: value2, reportYear: 2010}..., {reportMonth: 1, data: value1, reportYear: 2011}...,]}`

But was unable to get the graph to display as I desired...

**Comment by Eric24** [comment]
Can you post a sketch/mockup of the chart you're trying to achieve?

**Comment by groy** [comment]
Here is the graph I am trying to draw. Currently I have it written in d3 native, but I want to utilize re-charts to make it easier for anyone coming in after me to manage.

![image](https://cloud.githubusercontent.com/assets/467939/23953382/2de22e3e-0973-11e7-8f2c-73746619bb82.png)

**Comment by Eric24** [comment]
I see. I'm not sure you can achieve this using either of your example data structures. The trick is that both lines would try to access the same data ("data"). But if you can reformat the data, it should be easy. Try this:

`{reportData: [{reportMonth: 1, data2010: value1, data2011: value1}, {reportMonth: 2, data2010: value2, data2011: value2}...}
`

Then it's just like the Simple Line Chart example, with two Line components, each referencing the appropriate dataXXXX, and an X axis referencing reportMonth (although you can either convert that prop to month names while you're doing your transform or add a tick formatter function to do that conversion on-the-fly).

**Comment by groy** [comment]
The issue is that there is more than just the graph being rendered from the same data. And there is more than just the 1 value for each set of values. (eg: datax and datay for each report month each year...) I simplified the structure to get my point across.

It seems data structure flexibility is lacking. Unfortunately I don't have time to look into it currently much deeper.

I have already managed to get the X axis displaying properly from a bar chart I am rendering with different data. But it appears the data I am receiving for my line chart needs to be manipulated before passing in.

**Comment by Eric24** [comment]
In our use of ReCharts, we have always "massaged" the data before passing it in. ReCharts has a simple, if not super-flexible, expectation of what it wants to see, but that isn't much different than any other charting package we looked at. But we've always found that doing that extra step was fairly straightforward, since you can easily insert a "transform" function in between ReCharts and the underlying data.

**Comment by groy** [comment]
Managed to get it all sorted out. 
`[{reportMonth: 1, label1: 2010, data1: value1, label2: 2011, data2: value2}, ... ]`

Is there a way to set the Line name = to the label?

**Comment by Eric24** [comment]
Yes, but it will require a custom label function that returns the value of labelx.
