### ISSUE TITLE
scale = 'log' is not working

### ISSUE THREAD

**Issue by ramandeepjain** [recharts/recharts#575]
Do you want to request a feature or report a bug?

What is the current behavior?

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/9y45ut13/).

What is the expected behavior?

Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

**Comment by eranimo** [comment]
Confirmed -- the log scale is broken

**Comment by cwebbdesign** [comment]
From what I can tell, the domain needs to be set above zero or to  'auto'. Example:
<YAxis scale="log" domain={['auto', 'auto']} />
