### ISSUE TITLE
Feature: Sunburst Chart (essentially a round Treemap)

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#576]
Something to consider...

![image](https://cloud.githubusercontent.com/assets/685316/23953019/5de3cdf2-0961-11e7-90c9-e84af1624088.png)

These are getting more popular, and personally, I feel they are a better visual way to see hierarchical data than a Treemap.

Also: http://nivo.rocks/#/sunburst

**Comment by dangreenisrael** [comment]
+1

**Comment by tashiscool** [comment]
👍

**Comment by smilexu** [comment]
+1

**Comment by rjancewicz** [comment]
+1

**Comment by theUnicornGod** [comment]
+1

**Comment by becwatson** [comment]
+1

**Comment by manasovdan** [comment]
as I see it can be done with Pie charts - https://jsfiddle.net/wm74uq1s/

**Comment by Eric24** [comment]
@manasovdan: It's pretty good, but what about labels and different colors per slice vs per ring?

**Comment by manasovdan** [comment]
@Eric24 [Child](http://recharts.org/en-US/api/Cell) for slice color and [Custom Label](http://recharts.org/en-US/examples/PieChartWithCustomizedLabel) for labels. I could work on example component if you provide me requirements.

**Comment by damianobarbati** [comment]
+1

**Comment by damianobarbati** [comment]
@xile611 this feature is not in the roadmap neither considered. Correct?

**Comment by rahulpsd18** [comment]
It should be. 
It would be awesome if we could create something like: https://codesandbox.io/s/v3x0yw11q5

**Comment by manishsharma004** [comment]
Opened a new issue since this one seems to be closed without any explanation.
https://github.com/recharts/recharts/issues/3842
