### ISSUE TITLE
Chart click event with "mapped" X and Y

### ISSUE THREAD

**Issue by rvangsgaard** [recharts/recharts#578]
Thanks for a great library.

Do you want to request a feature or report a bug?
Feature request: I would like to click the chart in order to add more data points to the source array.

What is the current behavior?
Currently X and Y are pixels.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/9y45ut13/).

What is the expected behavior?
I would like and Y to be mapped/translated into values from the chart point I clicked. In addition of getting the pixel X and Y, I would like to have access to mapped X and Y.

Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Latest Recarts.

**Comment by xile611** [comment]
Duplicated with #365
