### ISSUE TITLE
Responsive Clickable Treemap

### ISSUE THREAD

**Issue by nikolayg** [recharts/recharts#579]
Hi,

I just came across this library and it seems great!

I'm trying to use the Treemap component. However, in the example the width and height are fixed. I'm working on a responsive app and don't want to hardcode chart dimensions. Can I somehow make the size dynamic - e.g. 90% by 90%?

Also, is it possible to handle the click events on the treemap?

**Comment by xile611** [comment]
@nickpalmer You can check [this demo](http://jsfiddle.net/xht7qwbj/).

`Treemap` is still very simple now.  Suggestion is welcome.
