### ISSUE TITLE
customed payload is not word while Legend is in a Chart

### ISSUE THREAD

**Issue by p2227** [recharts/recharts#58]
http://jsfiddle.net/urt1d7v5/

I want to set `payload={data1}` but is doesn't work.

but this spec is work

https://github.com/recharts/recharts/blob/master/test/specs/component/LegendSpec.js

**Comment by xile611** [comment]
Thanks!
The customized payload is overwritten by the legend data calculated in `LineChart`, but the data won't be overwritten in the test file.
Maybe the `payload` should not be overwritten when you have set a customized `payload` in a `Legend`.

**Comment by xile611** [comment]
Fixed in v0.8.7
