### ISSUE TITLE
Changing the number of Lines in LineChart always redraws the last Line

### ISSUE THREAD

**Issue by eanders-MS** [recharts/recharts#581]
Thanks for this awesome library. I think I might have found a bug. I have a LineChart with three Lines. I pass the Lines to LineChart via an array: `{lines}`. When populating the lines array, if I skip any of the lines in the array, when I later re-include the skipped Line, the last Line in the array will reanimate back in.

Repro on JsFiddle: http://jsfiddle.net/dimetrodon/hhg4a89q/

**Comment by skvale** [comment]
@eanders-MS It looks like LineChart doesn't use the keys you are passing in on the `<Line />` component.  Instead it is computing keys on the `<LineChart />` children by index.  What initially seems off here is that the newly added `<Line />` is becoming the first index.

So the newly added one gets a key of `line-0` and the last one goes from `key=line-1` to `key=line-2`, causing the re-render.

As a quick work-around, see JsFiddle http://jsfiddle.net/4z48g1bL/, which clears up the poorly computed keys by reversing the lines before the render. (:eyes: Line 19)

**Comment by eanders-MS** [comment]
Thanks so much @skvale !
