### ISSUE TITLE
Bar Chart doesn't render without width/height

### ISSUE THREAD

**Issue by Billy-** [recharts/recharts#583]
I haven't tested this with any of the other graphs, but if you don't supply height/widths, or nest in a `ResponsiveContainer`, the bar chart doesn't render at all.

I understand this is most likely expected behaviour, however a) it is not documented and b) there are no warnings in the console. If such a scenario occurs where the component must unexpectedly abort rendering, you should throw an error/warning.

example: http://jsfiddle.net/swu74nsx/

**Comment by xile611** [comment]
@Billy- You can get warning when `process.env.NODE_ENV !== 'production'`.
