### ISSUE TITLE
isSsr does not work when using jsdom for testing

### ISSUE THREAD

**Issue by imontiel** [recharts/recharts#584]
When using recharts in a test suite like jest with jsdom to mock out the DOM, isSsr is false, which makes it so that `text.getComputedTextLength` fails.

It would be nice if we could override the behavior of `isSsr` with a global like `global.isSsr = true;`. 

I am using version 0.19.0 of recharts, but it looks like this is still an issue with the current version of recharts.

I currently implemented a workaround by hijacking the import to `ReactUtils`:

```js
var requireHijack = require('require-hijack');
var reactUtils = require('recharts/lib/util/ReactUtils');

const fakeReactUtils = {
  ...reactUtils,
  isSsr: () => true,
};

requireHijack.replace('recharts/lib/util/ReactUtils').with(fakeReactUtils);
```

**Comment by xile611** [comment]
We'll add a global config to change isSsr
