### ISSUE TITLE
the ticks are not fully displayed when they are aligned vertically

### ISSUE THREAD

**Issue by iambalajive** [recharts/recharts#585]
I am trying to display the ticks vertically . The ticks are not getting displayed fully . they appear truncated .Can someone help or is it a bug

import React, { Component } from 'react';
import propTypes from './proptypes';

export default class CustomizedTick extends Component {

 static propTypes = propTypes;

 render() {
   const { x, y, payload } = this.props;
   return (
     <g transform={`translate(${x},${y})`}>
       <text x={0} y={0} dy={16} textAnchor="end" fill="#666" transform="rotate(-90)">{payload.value}</text>
     </g>
   );
 }

}

import { PropTypes } from 'react';

export default {
 x: PropTypes.number,
 y: PropTypes.number,
 payload: PropTypes.shape({
   value: PropTypes.string,
 }),
};

**Comment by xile611** [comment]
@iambalajive You can change the `height` of `XAxis` which has a default value 30.

**Comment by kesha-antonov** [comment]
@xile611 Thanks!
