### ISSUE TITLE
Lines and Scatter?

### ISSUE THREAD

**Issue by martintyler** [recharts/recharts#587]
I've tried various forms of Line charts and Scatters etc and can't find a way to do what I want, hoping there is a solution or a possible enhancement to help.

I would like a single chart with 2 lines. X being datetime, each with their own numeric Y axis. This part I have done, not a problem.

Now I want to be able to add dots (or some kind of shape) at various points - using the same x-axis, ie a datetime, a y-axis on the same scale as one of the existing ones, and a size (a z-axis?). Preferably this data would come from a separate dataset as the 2 lines - but merging the data beforehand would be somewhat possible.

Is this possible?

**Comment by digorydoo** [comment]
Yes, I think it should be possible with a ScatterChart.

**Comment by xile611** [comment]
It's a feature I have done in my local project. This feature'll be released in 1.0 version of recharts.

**Comment by caddac** [comment]
I see that version 1.0.0-alpha.4 is in NPM, wondering if this feature is in it?

**Comment by prashantShrivastava91** [comment]
is this feature released in latest version?

**Comment by dhinkris** [comment]
any updates on this?

**Comment by stefan2718** [comment]
Looks like it should be possible using a `ComposedChart` [as it accepts a Scatter element](https://github.com/recharts/recharts/blob/1.x/src/chart/ComposedChart.js#L16) (although this is not documented).

I'll post again if I figure out how to do it.

**Comment by stefan2718** [comment]
I figured this one out. Here is my code:

```javascript
const data = [
  {
    "newMarkersClustered": 10000,
    "mcp": 1643,
    "wasm": 790
  },
  {
    "newMarkersClustered": 1666,
    "mcp": 182,
    "wasm": 42
  },
  {
    "newMarkersClustered": 625,
    "mcp": 56,
    "wasm": 11
  },
  {
    "newMarkersClustered": 300,
    "mcpSlope": 0
  },
  {
    "newMarkersClustered": 10000,
    "mcpSlope": 1522
  },
  {
    "newMarkersClustered": 600,
    "wasmSlope": 0
  },
  {
    "newMarkersClustered": 10000,
    "wasmSlope": 678
  }
];

export const Graph = () => {
  return (
    <ResponsiveContainer className="graph-wrapper" width="100%" height="90%" >
      <ComposedChart data={data} >
        <XAxis dataKey="newMarkersClustered" type="number"/>
        <YAxis unit="ms" type="number"/>
        <Scatter name="MCP" dataKey="mcp" fill="red"/>
        <Scatter name="Wasm" dataKey="wasm" fill="blue"/>
        <Line dataKey="wasmSlope" stroke="blue" dot={false}/>
        <Line dataKey="mcpSlope" stroke="red" dot={false}/>
      </ComposedChart>
    </ResponsiveContainer>
  )
}
```
The result:
![alt](https://i.imgur.com/MCG1MD0.png)

Here is the trick:
The first 3 points in the data array are the scatter plot points, where `newMarkersClustered` is the `x` value and `mcp` and `wasm` are different sets of `y` values.

The next 4 points are the start and end points of the trendlines for each data set. I had to calculate their values myself using 'line of best fit' math.
