### ISSUE TITLE
tooltip function example?

### ISSUE THREAD

**Issue by Omortis** [recharts/recharts#588]
Hello,

I am trying to render a LineChart ToolTip elsewhere on my page. It seems the ToolTip function would be the way to do this? From the API:

"If set a React element, the option is the custom react element of rendering tooltip. If set a function, the function will be called to render tooltip content."

I have been unable to access the content of the data returned directly. I am trying this:

`<Tooltip content={ this.showTooltipData.bind(this) } />`

elsewhere:

```
  showTooltipData = (data) => {
    console.log(data);
    // console.log(data.payload[0].color);
  }

```
The attempt above to access the "color" object as above  just returns an "undefined" error, though I can see it in the console log. Can anyone tell me the secret syntax sauce to get at this data?

Thanks!

![image](https://cloud.githubusercontent.com/assets/14285373/24172771/da6da246-0e5f-11e7-9a1e-7e83182d3d02.png)

**Comment by xile611** [comment]
@Omortis Please check this [example](http://recharts.org/#/en-US/examples/CustomContentOfTooltip) for detail.
 Because the payload of `Tooltip` will change when you interact with the chart, so you need to judge whether the payload is existing.

**Comment by Omortis** [comment]
Using the container's props is not that easy as this is deeply nested in a redux state. I have been trying a similar tactic to see if the payload is defined and I can see it an log it, but still can't access it:

```
showTooltipData = (data) => {
  if ( typeof data.payload[0] !== 'undefined') {
    console.log(Object.keys(data.payload[0]));
    console.log("dataKey = " + data.payload[0]["datakey"]);
  }
}
```

The first log shows the expected data, the second log errors out?
