### ISSUE TITLE
Bubble Chart?

### ISSUE THREAD

**Issue by nikolay-g** [recharts/recharts#589]
Does reacharts support bubble charts?

**Comment by xile611** [comment]
Maybe you mean `ScatterChart` ?

**Comment by nikolay-g** [comment]
I mean chart, in which each bubble reflects an element's size and has distinct colour. Something like this - http://blogs.it.ox.ac.uk/acit-rs-team/files/2014/10/bubble_chart.png

**Comment by xile611** [comment]
@nikolay-g Not support! You can use `ScatterChart` to render this kind of bubbles. But I think you can use `divs` to render bubbles too.

**Comment by elisechant** [comment]
Although a bubble chart is similar to a scatter chart, the difference is mainly in the label placement 
* Bubble labels are inside the bubble
* Scatter labels are outside the bubble
as well as the size of the bubble - a 4th data dimension.

Why don't we spec out a bubble chart and add it to the docs?  @xile611 happy?

**Comment by ckifer** [comment]
No there isn't currently a separate bubble chart
