### ISSUE TITLE
why there is a block of blank on the left ?

### ISSUE THREAD

**Issue by p2227** [recharts/recharts#59]
i try to change the viewBox on svg,it can solve. Is there a better way to solve it ?

![a block of blank](https://raw.githubusercontent.com/p2227/p2227.github.io/master/asset/chart.jpg)

**Comment by xile611** [comment]
The default width of  `YAxis` is 60, maybe you can set the width to be a smaller value just like the following example.

```jsx
   <YAxis width={40} />
```
