### ISSUE TITLE
Tooltip Position marker

### ISSUE THREAD

**Issue by RobAWilkinson** [recharts/recharts#594]
Do you want to request a feature or report a bug? Feature (unless this is available already)

Would love a way to find out if a tooltip will be drawn to the right, or the left of the cursor, so I can apply different styles accordingly.

What is the current behavior?
Tooltip dynamically reorients to ensure it doesn't overflow the chart.

What is the expected behavior?

Tooltip passes a prop indicating which orientation (relative to the mouse) it will be drawn

Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Latest.

**Comment by RParvathi** [comment]
Any update on this ?

**Comment by xile611** [comment]
It's recommended to use customized `content` of `Tooltip` to cover default tooltip.
