### ISSUE TITLE
Option for scaling (beginAtZero in chart.js)

### ISSUE THREAD

**Issue by kevart** [recharts/recharts#595]
Do you want to request a feature or report a bug?
feature

What is the current behavior?
0 is the baseline.
Example: [1.1, 1.2, 1.3, 1.2] should have a y range from ~1.0 to ~1.4 and not from 0 to 1.4.

**Comment by xile611** [comment]
@kevart You can set the `baseValue` of `AreaChart`.  [API](http://recharts.org/#/en-US/api)

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
