### ISSUE TITLE
Is it possible to expand hit area for pie chart?

### ISSUE THREAD

**Issue by seleckis** [recharts/recharts#596]
I need to add extra 10px inside the pie chart to be able to use events like onClick, onMouseEnter, etc.
Here is a demo with custom active shape: http://recharts.org/#/en-US/examples/CustomActiveShapePieChart But I need to mouseover a sector extra 10px towards the center of the chart. But it should not be visible.

Is it possible to do that with recharts?
![1](https://cloud.githubusercontent.com/assets/988504/24290725/b79af4fe-108e-11e7-8633-204112a706bd.png)

**Comment by xile611** [comment]
@seleckis You can render an invisible sector inside the visible sector by customized shape and active shape.

**Comment by Ziker22** [comment]
@xile611 Can you please provide some example of this ?
