### ISSUE TITLE
XAxis time scale - r.bandwidth is not a function

### ISSUE THREAD

**Issue by kusold** [recharts/recharts#598]
> Do you want to request a feature or report a bug?

Report a bug

> What is the current behavior?

Throws a javascript error. `r.bandwidth is not a function`

> If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/9y45ut13/).

http://jsfiddle.net/da2a5nb1/1/
Changes from the template:
* Added `date` field to `data`.
* Changed `dataKey` on `XAxis` component to the date field.
* Added `scale="time"` to `XAxis` component.

> What is the expected behavior?

Sets the scale to `time`, similar to d3's.

> Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Tested on:
```
Chrome 56.0.2924.87 (Official Build) (64-bit)
Mac OS 10.12.3
recharts@0.21.2
```

I'm unsure if this is a regression or not, it occurred during my evaluation of recharts.

This could be related to #575, but it is hard to tell since no information was filed with that issue report.

**Comment by peternoyes** [comment]
I ran into the same thing. I fixed it by changing the XAxis to be of type "number" and then calling .getTime() off of the data. I also had to add a domain to the XAxis:

http://jsfiddle.net/hy3yf2rx/1/

To make the dates look right a formatter function would be needed also.
