### ISSUE TITLE
Label for axis does not support HTML element

### ISSUE THREAD

**Issue by neekey** [recharts/recharts#601]
## Do you want to request a feature or report a bug?

A feature.

## What is the current behavior?

If you pass down an HTML element to `label` of XAxis or YAxis, it will not render.

```html
<XAxis label={<span>Hello</span>} dataKey="name"/>
```

## What is the expected behavior?

It should render HTML element.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

`0.19.1`

**Comment by xile611** [comment]
@neekey Use <text> or <tspan> of svg.
