### ISSUE TITLE
Reference area rendering bug

### ISSUE THREAD

**Issue by SergeyShablenko** [recharts/recharts#606]
![image](https://cloud.githubusercontent.com/assets/13334277/24669376/e1bffc9c-1972-11e7-9499-8d31b78fb488.png)

can somebody explain why ReferenceArea is not rendering? Just yesterday everything was fine, and now area disapeared

**Comment by xile611** [comment]
@SergeyShablenko Maybe the data of your chart changed.  Can you create a jsfiddle demo ? I have no idea when only have a image.

**Comment by SergeyShablenko** [comment]
i can`t make demo, sorry
data is persistent, i only change x1, x2 props of reference area

**Comment by SergeyShablenko** [comment]
![image](https://cloud.githubusercontent.com/assets/13334277/24696860/ae0a047a-19f3-11e7-85eb-0835ef02498e.png)

i think bug is that `getRect` method of ReferenceArea returns `x1 = NaN` and `x2 = NaN` for non numeric values

**Comment by xile611** [comment]
@SergeyShablenko How about the domain of `XAxis`?

**Comment by xile611** [comment]
Reopen this when more clues are provided.
