### ISSUE TITLE
Cartesian Grid Over Graph (Rendered last)

### ISSUE THREAD

**Issue by jasonnathan** [recharts/recharts#608]
## Do you want to request a feature or report a bug?
Feature

## What is the current behavior?
The source order (for chart rendering) is [hard-coded](https://github.com/recharts/recharts/blob/master/src/chart/generateCategoricalChart.js#L1022)

## What is the expected behavior?
A few options I can think of:
1. Respect the source order based on the order of the children  but might enforce users to remember order unless there are sane (current) defaults in place
2. Have a flag that renders cartesian grid last. e.g. `gridOnTop: false // default`. However, this will mean only the grid itself is affected
3. Have a prop with an array of components' `displayNames` as strings so we can map over them within the chart rendering function.
4. [Suggestions?] Any other way without losing functionality?

_I have attempted [2] and have a ready pull request  for your review. Feedback appreciated_

Here is an example where the grid is rendered on top of the chart (based on the proposed changes in [2].

![screen shot 2017-04-06 at 11 07 59 am](https://cloud.githubusercontent.com/assets/780157/24736255/75d0e68e-1ab9-11e7-8d6e-8191816afc22.png)

**Comment by jasonnathan** [comment]
@xile611, you must be terribly busy and maybe my solution might not be the best one but some feedback or a pointer in the right direction will be greatly appreciated. A little on the clock with this issue at work 😉

**Comment by xile611** [comment]
@jasonnathan I prefer [1]. I'm doing this too which is also a main part of 1.0 of recharts. I'll try to release 1.0 in this month.

**Comment by jasonnathan** [comment]
Thanks for the update @xile611 and great work with the current refractors!

**Comment by Eric24** [comment]
+1 for option [1]

**Comment by xile611** [comment]
@jasonnathan This feature has been released in 1.0.0-apha.0

**Comment by jasonnathan** [comment]
Thanks!

**Comment by jetpack3331** [comment]
Property gridOnTop doesn't exist in source code, was it removed or renamed?

**Comment by flyingalex** [comment]
You can make it like this:
```
<AreaChart>
// more codes are in here
<CartesianGrid />   // put this at the end of AreaChart element
</AreaChart>
````
