### ISSUE TITLE
Question: Virtual DOM integration & performance

### ISSUE THREAD

**Issue by doriancransac** [recharts/recharts#610]
Hi,

I'd like to ask a question regarding update performance and the integration with React's virtual DOM. I browsed the Guide but couldn't seem to find the information I'm looking for.

I've been using d3.js for a while for its enter/exit functionality which I thought was particularly well suited for my use case (I keep updating many charts while results get streamed back to the client continuously and in real time).

I recently started rewriting my JS client entirely and I was planing on using React as one of the cornerstones of the project. Unfortunately d3's selectors and react's virtual DOM don't seem to make for a good mix (since d3 manipulates the svg elements of the DOM directly) so I was considering moving to a different (react-aware) chart library that wouldn't break the virtual DOM diffs and would allow me to benefit from smart updates in the svg content.

Would someone be so kind as to briefly explain how the rechart components behave with regards to the svg data manipulation and how much care was placed on compatibility with the virtual DOM diffs (and the resulting performance benefits)?

Thanks in advance
Dorian

**Comment by dmngu9** [comment]
Would love to hear thí

**Comment by tfritsch-km** [comment]
Hello
@xile611 I know issues are not the best place for questions, and maybe this is why you closed this one, but what it highlights is that documentation lacks this type of information. Maybe this issue should be renamed to something that better shows what's missing, but the problem in the doc is still here I think, no ?
