### ISSUE TITLE
anti-pattern: updating (unrelated) state in a render() method with Tooltip override

### ISSUE THREAD

**Issue by Omortis** [recharts/recharts#611]
I am overriding Recharts' Tooltip functionality to provide the hover data elsewhere on the page (in another component).

`<Tooltip content={ this.showTooltipData.bind(this) } />`

showToolTipData fires off an action creator which modifies a part of the state tree which the current render method is **not** sensitive to, but I still get the dreaded anti-pattern warning:

`Warning: setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.
`

This warning is both correct and incorrect, as the rendering component is not affected by the state change. The only reason I care about this is that the warning can spam the console (there are 10s of 1000s of points to hover over). 

Is there a better way to do this? I have considered using the the target hover data component's "private" state (as opposed to the redux state now in use) but I need that data elsewhere as well. Moving the functionality to **componentWillMount()** is impossible.

Anyone found a safer way to override the ToolTip function? 

recharts@0.21.2, Chrome 56.0.2924.87 (64-bit)

Thanks,

John

**Comment by nickperkinslondon** [comment]
I tried the same thing -- it's very tempting to use the tooltip as an "event" that changes some state -- I also tried using setTimeout to get past the React error....but the bottom-line is that whenever you change state the chart re-draws itself ( including its little animations, and excluding tool-tips ), so it's a Catch-22...

**Comment by Omortis** [comment]
In this project the charts can have many points (10s of 1000s, may scale up higher). The re-draw action was painful and almost forced me to move to a different tech. I was able to get around the re-draw (block it completely) with:

```
  shouldComponentUpdate = () => {
    return false;
  }

```
Works very well. FYI.

However, even with this in place, I still get the anti-pattern warning...

**Comment by xile611** [comment]
@Omortis You can try this:

```jsx
handleEnter = ({ isTooltipActive, activePayload, activeTooltipIndex, activeLabel}) => {
  
};

handleLeave = () => {
  console.log(arguments);
};

handleMove = (chartState, e) => {
 
};

render() {
  return (
    <LineChart  onMouseEnter={this.handleEnter}  onMouseLeave={this.handleLeave} onMouseMove={this.handleMove}>
    </LineChart>  
  );
}
```

And the `showTooltipData` should be a stateless function/ReactElement.

**Comment by Omortis** [comment]
@xile611  `chartState` in `handleMove()` works well and provides me with the same data as the payload from the tootltip object. Thanks!

To have this data displayed in a table elsewhere on the page (along with other, synchronous data) `showToolTipData()`  updates sections of the redux state which that target display table is sensitive to.  I believe this means my `showToolTipData()` function is _not_ stateless - how else could I get this information to a separate container in real time? Or do I misunderstand? Is this perhaps a question for the redux forums? For the record it works very, very well!

Thanks for the help and the reply, I like the `onMouseMove` event idea.
