### ISSUE TITLE
How can I display XAxis in date format 

### ISSUE THREAD

**Issue by sughanpandita** [recharts/recharts#612]
const data = [];
        for (var i = 0; i < json.length; i++)
        {
            var mtrcs = json[i];

            var mtrName=mtrcs.name;
            var mtrMemory=mtrcs.metrics.memory;
            var mtrCpu=mtrcs.metrics.cpu;

            data.push({

                "name":mtrName,
                "cpu":mtrCpu,
                "memory" : mtrMemory,
            });

        }
        return(

          <div>
              <LineChart width={1300} height={400} data={data} margin={{top: 5, right: 30, left: 20, bottom: 5}}>
                  <XAxis dataKey="name" tickFormatter={dateFormat}/>
                  <YAxis/>
                  <CartesianGrid strokeDasharray="3 3"/>
                  <Tooltip/>
                  <Legend />
                  <Line type="monotone" dataKey="cpu" stroke="#8884d8" activeDot={{r: 8}}/>
                  <Line type="monotone" dataKey="memory" stroke="#82ca9d" />
              </LineChart>
          </div>
      );

    }
}

**Comment by xile611** [comment]
@sughanpandita Just as your demo, use a `dateFormat` to format the ticks.

**Comment by patientplatypus** [comment]
This doesn't work as written. dateFormat is not defined - you've closed the issue prematurely

**Comment by patientplatypus** [comment]
I realize that - the question was "How do I display the XAxis in dateFormat?". Saying, "yes, indeed you do define a date format function yourself" is not answering the question of how to get date ticks on to a time series graph. From what I can tell this is actually a very difficult problem in this library and there is not very good documentation or examples that I could find. It was in fact the reason that I switched to another application.
