### ISSUE TITLE
Position Legend on the right side of a graph

### ISSUE THREAD

**Issue by sortsen** [recharts/recharts#614]
I'm wondering if it's possible to display a vertical list of Legend items on the right of a graph. I have a LineChart with a custom Legend, but it seems the only position the Legend (wrapper) can take now is top or bottom. I've checked all examples and they confirm this notion.

I can achieve my goal with ugly css positioning or other suboptimal ways, but isn't there a proper way of doing this?

**Comment by xile611** [comment]
@sortsen You can change the layout of `Legend`.

```jsx
<Legend layout="vetical" verticalAlign="middle" align="right" />
```

**Comment by richaax** [comment]
for those that cut and paste, there is a type.  change vetical to vertical . :)

**Comment by kiranvj** [comment]
Just in case anyone is looking for more layout options I have added few [here ](https://kiranvj.com/blog/blog/recharts-show-legend-on-top-of-chart/)

`<Legend layout="horizontal" verticalAlign="top" align="center" />`

`<Legend layout="vertical" verticalAlign="top" align="right" />`

![image](https://user-images.githubusercontent.com/3539487/77243508-ceae9780-6c30-11ea-835f-fa2d2340e341.png)
