### ISSUE TITLE
Centre align a rechart

### ISSUE THREAD

**Issue by nikhilbhawsinka** [recharts/recharts#617]
Hi,
I am very new to programming. I was working on a dashboard which i am making using React.
I used Rechart to show the data on graph. Now my problem is that i am not able to centrally align (horizontal) the chart using any of the CSS property. I tried margin: auto; text-align:  center nothing worked. I know this is supposed to be very basic but would love your help here.

**Comment by xile611** [comment]
@nikhilbhawsinka 
Find the className of the outermost div, and add some css to that div.

```
.recharts-wrapper {
  margin : 0 auto;
}
```

**Comment by nikhilbhawsinka** [comment]
Hi Xile,
It worked. Thanks a top. though i would like to understand that declaring the class name as ".rechartswrapper" did not work but ".recharts-wrapper" worked with the same css property. Am i missing something.

**Comment by nikhilbhawsinka** [comment]
Also, there seems to be a left margin which is pre assigned (Meaning, when i centred the chart as you suggusted, its not centered exactly but slightly toward the right). Can i prevent this from happening?

**Comment by jieyou** [comment]
use `http://recharts.org/#/zh-CN/api/ResponsiveContainer` also can auto centre align

**Comment by kerrande** [comment]
Comment above mine had the right idea but 0 effort for guiding people to the correct solution. You need to wrap your chart in a `<ResponsiveContainer />` while specifying the width and height of the container like so:

```
<ResponsiveContainer width='100%' height={400}>
            <LineChart
                data={props.data}
                margin={{
                    top: 5, right: 30, left: 30, bottom: 5,
                }}
             >

            ...

            </ LineChart>
</ ResponsiveContainer>
```

**Comment by Wesley633** [comment]
Olá, abrindo o inspetor pude perceber que o YAxis possui 23,2px de largura, enquanto que CartesianGrid possui 558px de largura e o svg uma largura de 618px para uma tela de 730px de largura. Então, podemos concluir que tudo que precisamos é dar uma margem para esquerda de:

618px - 558px - 23,2px = **36,8px**

**Solução:**
              <LineChart
                  data={data}
                  margin={{
                      left: -36.8,
                  }}
              >

Espero ter ajudado.

**Comment by developermamoon** [comment]
> @nikhilbhawsinka Find the className of the outermost div, and add some css to that div.
> 
> ```
> .recharts-wrapper {
>   margin : 0 auto;
> }
> ```

It worked thank u
