### ISSUE TITLE
[Feature] ScatterChart with multiple YAxes

### ISSUE THREAD

**Issue by digorydoo** [recharts/recharts#619]
I need to implement a ScatterChart with multiple data sets. Each data set has a different symbol and a different range in the y-direction. Currently, I'm able to define a single YAxis only when using ScatterChart. Is it possible to render multiple y-axes?

If it isn't possible, I might consider adding the feature. Is there anything important I should keep in mind when doing so? Is there a good chance you are going to accept a merge request?

**Comment by xile611** [comment]
@digorydoo It's a feature I have done in my local project. This feature'll be released in 1.0 version of recharts.

**Comment by digorydoo** [comment]
When will this be?

**Comment by xile611** [comment]
In late April. @digorydoo

**Comment by digorydoo** [comment]
Sounds great. Hoping this feature will work as expected, I'm closing this issue.
