### ISSUE TITLE
StackedBarChart with positive and negative value

### ISSUE THREAD

**Issue by lorenzo-pomili** [recharts/recharts#621]
I to stack positive and negative value on the same column without overlap,
actually if a column have positive and negative value they overlap, example:

if column have this values 1000, -1000, first value start go 0 to 1000 and second go to 1000 to 0 so the graphs show only the negative value

I expected all positive value over 0 line and all negative value under 0 line 

Error occure in OS: Debian,  Browser: Firefox, but also in OS: MacOS, Browser: Chrome so I suppose it happen anyway

**Comment by xile611** [comment]
@lorenzo-pomili Please show me an online example.

**Comment by lorenzo-pomili** [comment]
I edited example of city this is result:

http://jsfiddle.net/xtrr8nhw/

**Comment by xile611** [comment]
@lorenzo-pomili  Is the behavior of [demo](http://jsfiddle.net/xtrr8nhw/1/) what you want ?

If so, add props `stackOffset="sign"` to `BarChart`.

The default value of `stackOffset` is `"none"` which'll sum the stacked values.

You can also check the [stackOffset of d3](https://github.com/d3/d3-shape#stack-offsets) for more details.

**Comment by lorenzo-pomili** [comment]
Yes exactly! thank you very much, I didn't notice that option sorry for bother and thanks again
