### ISSUE TITLE
Dynamic Fill color option for each bars in simple bar graph

### ISSUE THREAD

**Issue by talk2rajeev** [recharts/recharts#624]
## How can I give different fill color for each bar in simple bar graph?
`<BarChart data={barsData}>
   <XAxis  ...../>
   <YAxis ...../>
   <Bar fill= **dynamic_color_here** ..... />
</BarChart>
` 

**For example 1**:- Let say, I have to show Employee_Name at XAxis and employee_salary at YAxis. Each bar represents a single employee. I want each of my bar to have different color which I want to provide dynamically.

**For example 2**:- month_name at XAxis and max_temp at YAxis. Each bar represents a month. I want each of my bar to have different color based on temperature  which I want to provide dynamically.

**Comment by xile611** [comment]
Similar to [this demo](http://jsfiddle.net/va9nnx5r/).

**Comment by rajeevrj** [comment]
@xile611 Thanks, This works 👍

**Comment by roije** [comment]
@xile611 Doesn't seem to be working.

**Comment by TheBreadMan** [comment]
@xile611  You are a beautiful human being

**Comment by mchong-teal** [comment]
link is broken.

**Comment by amehito** [comment]
this works,Thanks

**Comment by mayank-gangwal** [comment]
> link is broken.

Yes, but got reference from the code, and it works like a charm.
Use this as suggested - `<Cell fill={color} />;`
