### ISSUE TITLE
Brush y coordinate reset by Higher Order Component

### ISSUE THREAD

**Issue by velociwabbit** [recharts/recharts#630]
I have been trying to modify the margin or location of the brush when using a line chart with no success. Right now it slightly overlaps the x axis  tick (labels).

Below is an example of how I am using the brush.  I have also tried with margin as well and to no avail. It appears that all the props for positioning of the brush are being rewritten in   LineChart  or some other component.  
```

        <LineChart width={600} height={200} data={data} syncId="anyId"   margin={{top: 5, right: 10, left: 0, bottom: 10}}>
          <XAxis stroke="#00b4cd"  tick={<AxisLabel angle={-90}/>}  dataKey="minV" />
          <YAxis stroke="#00b4cd"  tick={<AxisLabel angle={  0}/>}/>
          <Tooltip  content={<Toolip/>} />
          <Line type='monotone' dataKey='minV' stroke='#82ca9d' dot={false} fill='#82ca9d' />
         <Brush y={250}/>    
        </LineChart>
```

**Comment by xile611** [comment]
@velociwabbit 

You can specify the `height` of `XAxis` which has default value 30.


```jsx
  <XAxis height={40} />
```
