### ISSUE TITLE
my data not rendering line

### ISSUE THREAD

**Issue by jonathanyee** [recharts/recharts#631]
http://jsfiddle.net/x0Lc6xLp/

Trying to render my current balance (y-axis) with a date (x-axis), but the line for the graph is not showing.  What am I doing wrong?

**Comment by Revln9** [comment]
nothing , i think that the latest release doesn't accept text as X axis datakey , put a number instead of a string and it will work again , if someone can enlighten us about this (rude) change

**Comment by jonathanyee** [comment]
So I figured out it was because i had a duplicate date, which is why it didnt render. So i'm trying to figure out how to customize the label by using "ticks" but its not rendering.

http://jsfiddle.net/b729gudv/
