### ISSUE TITLE
ErrorBar should contribute to x/y-axis 'auto' domain

### ISSUE THREAD

**Issue by jzillmann** [recharts/recharts#634]
I just started using the new error-bar feature (thanks for that!) and the error bar's often crosses the x-axis domain max:
<img width="923" alt="errorbarsoutofdomain" src="https://cloud.githubusercontent.com/assets/148472/25090292/a3f1fc66-2382-11e7-8013-567cabbfd9bc.png">

While i can easily fix that by setting the x-axis domain with a manual calculated dataMax, it just looks not a nice as if the auto would have respected the error-bar max!

**Comment by xile611** [comment]
Thanks! It's a feature in plan.

**Comment by xile611** [comment]
@jzillmann Done in 1.0.0-alpha.0.

**Comment by jzillmann** [comment]
Thanks a lot!
