### ISSUE TITLE
Alter bar size but keep data

### ISSUE THREAD

**Issue by Ziker22** [recharts/recharts#637]
Hi guys,
Imagine i have BarChart with data lets say value1 = 200 and value2=300. I want to normalize these data to percentages so when i have different Bars in BarChart all would have same sizes visually. Then max value on all Bars would be 100(%) but after hover it would show real values (e.g 200 and 300).
Is there some way to do this without hacking into library ?

**Comment by xile611** [comment]
You can use customized content of `Tooltip` like [this demo](http://recharts.org/#/en-US/examples/CustomContentOfTooltip).
