### ISSUE TITLE
CDN fails to load

### ISSUE THREAD

**Issue by MarkHarper** [recharts/recharts#639]
There appears to be an issue with the current CDN script. Recharts fails to load with a "Cannot read property 'string' of undefined" error.

https://jsfiddle.net/markharper/2dx32mbb/

**Comment by xile611** [comment]
@MarkHarper Check the [examples of recharts](http://recharts.org/#/en-US/examples/SimpleLineChart). You should import more external pkgs.

**Comment by MarkHarper** [comment]
I already had the necessary packages installed as well. It turned out to be
an incompatibility issue with the version of react that I was using.


On April 19, 2017 at 8:54:06 PM, xile611 (notifications@github.com) wrote:

@MarkHarper <https://github.com/MarkHarper> Check the examples of recharts
<http://recharts.org/#/en-US/examples/SimpleLineChart>. You should import
more external pkgs.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/recharts/recharts/issues/639#issuecomment-295540238>,
or mute the thread

**Comment by xile611** [comment]
@MarkHarper How about the version of your react ?

**Comment by MarkHarper** [comment]
It was fairly outdated, 15.3.1, I believe. Updating fixed it.


On April 19, 2017 at 11:44:43 PM, xile611 (notifications@github.com) wrote:

@MarkHarper <https://github.com/MarkHarper> How about the version of your
react ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/recharts/recharts/issues/639#issuecomment-295578917>,
or mute the thread

**Comment by xile611** [comment]
OK~  I'm using 15.4 now. I think 15.4 works well.
