### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by dlindahl** [recharts/recharts#64]
When using `0.8.8` installed from NPM, everything works as expected.

When I clone the repo and build locally using `npm install`, `npm run build` and `npm link`, I get the following errors:

```
Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).(…)
```

and

```
Error: removeComponentAsRefFrom(...): Only a ReactOwner can have refs. You might be removing a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).(…)
```

I _think_ those errors are coming from `ResponsiveContainer`, but when I remove that from my app's code, I get:

```
React can't find the root component node for data-reactid value `.0.3.1.$appContent.$mainFeedContent.0.0.0.3.$dc627119-d8b6-4dd5-964a-bd69706b5faa.1.0.$=11.$1.0.0.5.1:$bar-0.0.$rectangle-0.0`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.
```

Both errors reference multiple copies of React, so I'm think that has something to do with it, but I'm unsure how that is happening, especially if `npm run build` is the official way to build this.

Am I missing a step?

**Comment by xile611** [comment]
This problem may due to two react in your local project.
<http://stackoverflow.com/questions/28519287/what-does-only-a-reactowner-can-have-refs-mean>

If you have used webpack, you can add `resolve` in your *webpack.config.js*.

```
  resolve: {
    alias: {
      'react': path.join(__dirname, 'node_modules', 'react'),
    },
    extensions: ['', '.js', '.jsx', '.css', '.scss', '.json']
  },
```

**Comment by dlindahl** [comment]
Turns out I was bit by this: https://github.com/facebook/react/issues/5188
