### ISSUE TITLE
FR: only import needed lodash functions

### ISSUE THREAD

**Issue by rubencodes** [recharts/recharts#642]
Currently, all of Lodash is imported as a dependency. This results in a somewhat large bundle size (relative to the rest of the package), which is not desirable. I'm wondering if the package maintainers have considered instead importing only the lodash functions that are used, instead of the whole thing? I haven't looked at the whole repo but from what I saw it seemed like it was mostly a small subset of functions being used.

If this is desireable, I would be glad to look into this further and start a branch and make a pull request.

**Comment by xile611** [comment]
recharts has used babel plugin `babel-plugin-lodash`. You can check the compiled file of recharts like [this](https://unpkg.com/recharts@0.22.3/lib/chart/generateCategoricalChart.js), the plugin will replace the import of lodash by needed files.

![image](https://cloud.githubusercontent.com/assets/6111424/25259488/fdcd3748-2678-11e7-8f69-b98356a2a575.png)

**Comment by rubencodes** [comment]
Gotcha, might be something wrong with my build then, thanks!

**Comment by raveclassic** [comment]
Could you reconsider using separate lodash packages like `lodash.sortBy` instead of defining whole lodash as a dependency?

**Comment by adeelibr** [comment]
@xile611 But when I compile my code using webpack with recharts in it, I get the entire lodash library.

**Comment by adeelibr** [comment]
I can make a PR for this if you want. @xile611  :)

**Comment by andrew-humu** [comment]
@xile611 I think this is actually a subtle bug.

If you import `'recharts'`, you get the compiled version of this library, which includes import statements which have been transpiled via `babel-plugin-lodash`.  However, if you try to import individual Recharts packages, you end up importing directly from `lib/` files which still specify the entire `lodash` package as a dependency.

For me, a symptom of this is that adding `babel-plugin-recharts` to my babel configuration actually _increases_ my bundle size!
