### ISSUE TITLE
Labels in vertical stacked barchart

### ISSUE THREAD

**Issue by alexabruck** [recharts/recharts#643]
I am trying to build a stacked bar chart that is laid out vertically and can hold many data series that have just one data point each. Basically, it will be just one single horizontal bar containing different segments for each series. I want to have a label on `top` of each segment. 

Here's what I got:
```javascript
<BarChart className="segmented-barchart" data={data} maxBarSize={30}  layout="vertical">
    <XAxis hide type="number" domain={[0, maxTotal]} />
    <YAxis hide type="category" />
    <Tooltip/>
    <Legend />
    { 
        someKeys(data).map( 
          keyName => <Bar unit=" countries" key={keyName} dataKey={keyName} stackId="single-stack" label={{fill: '#000'}} fill={ makeFill(keyName, colorDict) } />
        )
    }
</BarChart>
```
![bildschirmfoto 2017-04-22 um 04 05 11 nachm](https://cloud.githubusercontent.com/assets/5918060/25305103/8edbbe38-2775-11e7-9817-0b361c8cf988.JPG)

There are 2 problems with it like you can see:
1. The labels appear at the right end of each bar to which they belong, making the label appear on top of the bar belonging to the next series
2. The numbers inside those labels are accumulative numbers, not the numbers of the series itself

The Tooltip shows the correct numbers:
![bildschirmfoto 2017-04-21 um 03 15 25 nachm](https://cloud.githubusercontent.com/assets/5918060/25305093/50442aac-2775-11e7-83ed-1273eca587a3.JPG)

And the bar chart without the stacking renders correctly too:
![bildschirmfoto 2017-04-21 um 03 17 38 nachm](https://cloud.githubusercontent.com/assets/5918060/25305088/33908a36-2775-11e7-82b8-4efd984bdab6.JPG)

Thanks for any hints!

**Comment by xile611** [comment]
@alexabruck Use customized label function to cover default behaviors.

**Comment by GouthamGowda** [comment]
Hi alexabruck,
Did you get the solution for the above question??

**Comment by alexabruck** [comment]
Thanks for the reminder 👍
