### ISSUE TITLE
Improvements for hovering over lines

### ISSUE THREAD

**Issue by iEchoic** [recharts/recharts#646]
Hey, love the library so far, great work! Just moved from ChartJS and I'm enjoying how this works w/ React.

## Do you want to request a feature or report a bug?
Feature request (or maybe just help me understand how to do this if it doesn't need a feature?)

## What is the current behavior?
1. It's hard to hover over individual lines, because they're super thin. I want them to look thin, but I want to have some "slop" around them. Is there some way to add a hover "slop" to a line? I could imagine putting a fatter line behind it and hovering, or adding transparent stuff to the edges of the line, but I'd have to hack against the library to do it I think.
2. Dots don't trigger hover events on lines, even though they're part of the line. I don't see anything in the API that has a `onDotHover` or anything similar. How can I capture dot hovers?

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
All

Thanks!

**Comment by xile611** [comment]
I have no idea now, if you want to hover the lines much more easier, you can only change the strokeWidth of `Line`.

**Comment by rishabhjha28** [comment]
> I have no idea now, if you want to hover the lines much more easier, you can only change the strokeWidth of `Line`.

have you found any way to do this???
