### ISSUE TITLE
BarChart onclick mouse coordinates

### ISSUE THREAD

**Issue by Ziker22** [recharts/recharts#647]
Hi,
Is there a way to get something like classic javascript event.pageX/pageY ?
When handling onClick event in bar chart im getting only x,y inside bar

thx in advance

**Comment by xile611** [comment]
@Ziker22 Check [this demo](http://jsfiddle.net/f76d7q18/).

**Comment by Ziker22** [comment]
Thx a lot . Is supposed same approach to work with Pie Charts . Im playing with it with negative resullts :(
