### ISSUE TITLE
legend to have tooltip feature on onClick

### ISSUE THREAD

**Issue by NischithBopaiah** [recharts/recharts#648]
## Do you want to request a feature or report a bug?
i am using  Line chart for my project where i want my functionality to be like , when i click on the legend i want it to show a tool tip   i.e like giving a small hint information about the legend (static information to be shown )
which i am unable to find can you please help me with this like how to proceed.

**Comment by xile611** [comment]
You can bind `onClick` to `Legend`.

[Similar demo](http://recharts.org/#/en-US/examples/LegendEffectOpacity)

**Comment by NischithBopaiah** [comment]
can you please have a look at this code and tell me 

class Line extends React.Component {

  constructor(props) {
    super(props)
    this.state = {
     data: []  
     }
  }

  componentWillMount() {
    this.setState({
      data: [

      {name: 'Page A', uv: 4000, pv: 2400, amt: 2400},
      {name: 'Page B', uv: 3000, pv: 1398, amt: 2210},
      {name: 'Page C', uv: 2000, pv: 9800, amt: 2290},
      {name: 'Page D', uv: 2780, pv: 3908, amt: 2000},
      {name: 'Page E', uv: 1890, pv: 4800, amt: 2181},
      {name: 'Page F', uv: 2390, pv: 3800, amt: 2500},
      {name: 'Page G', uv: 3490, pv: 4300, amt: 2100},
      ]
})
}
  
  render() {
    
  return (

     
        <LineChart
          width={this.state.width} height={400} data={600}
          margin={{ top: 45, right: 30, left: 50, bottom: 5 }}
        >
          <XAxis dataKey="name" tickLine={false} />
          <YAxis type="number" domain={["dataMax"]} mirror tickCount={1} />
          <CartesianGrid strokeDasharray="3 3" />
          <Legend
            iconType="circle"
            wrapperStyle={{ top: 280 }}
            
          />
          <Line dataKey="name" stroke="#1e90ff" dot={false} />
          <Line dataKey="uv" stroke="#FF0000" dot={false} />
          <Line dataKey="pv" stroke="#eedd82" dot={false} />
          <Line dataKey="amt" stroke="#7fffd4" name="amt" dot={false} />
          </LineChart>
        )
  


> 

> `}`

}

i need something like this  just have taken a random image here  "setting"  name , uv , pv , amt to be my actual legends  and onclick i need a tooltip to show a message same follows for others.. 
![legend](https://cloud.githubusercontent.com/assets/9164357/25385782/b7c76efe-29e2-11e7-9e55-191c23e35678.jpg)

**Comment by xile611** [comment]
Similar to [this demo](http://jsfiddle.net/Luk2xapk/).

**Comment by NischithBopaiah** [comment]
i don't want to customize my legend icon as you doing it here http://jsfiddle.net/Luk2xapk/ , all i need is to have the legend icon as it is  and when i Click on the legend a Tooltip to show as it is being displayed in the above pic i posted that's exactly what i am looking for ? can you help me with that ... thanks for your time  👍

**Comment by NischithBopaiah** [comment]
after little  research i did  came to know modifying this file code  **https://raw.githubusercontent.com/recharts/recharts/master/src/component/DefaultLegendContent.js** and using in my project as a  component will do the job so please help me with the modification needed

**Comment by xile611** [comment]
@NischithBopaiah You can just render anything you like when you customized legeng `content`. If you have ever used any react UI project like `ReactBootstrap`, you can use components like `Popover` to render what you want.

I think [http://jsfiddle.net/Luk2xapk/1/](http://jsfiddle.net/Luk2xapk/1/) is what you want.  If this don't meet your needs, then I really can't help you.

**Comment by NischithBopaiah** [comment]
@xile611  thanks 👍
