### ISSUE TITLE
[Feature] Dot plot chart

### ISSUE THREAD

**Issue by rafacianci** [recharts/recharts#650]
## Do you want to request a feature or report a bug?
Feature

## What is the current behavior?
Not Supported.

## What is the expected behavior?
A chart that display dots of different proportions through a timeline, where the scales represents multiples values of an index.

![image](https://cloud.githubusercontent.com/assets/4905837/25354621/01595bf6-290a-11e7-89cb-391a526f0046.png)

**Comment by xile611** [comment]
You can use `ScatterChart` to render this.

**Comment by OzrenMuic** [comment]
> You can use `ScatterChart` to render this.

You can. We did it too. But it's a different chart. If someone would look for it, it's missing.
