### ISSUE TITLE
Place a Polygon within the bounds of the CartesianGrid

### ISSUE THREAD

**Issue by kbouaazzi-ds** [recharts/recharts#651]
Hello, I am looking for a way to place a polygon on a ScatterChart at the CartesianGrid level. Is there a way to achieve this behavior? Ultimately, I am looking for the ability to create Area-like behavior on the ScatterChart since there is not a way to use the ComposedChart with an AreaChart and a ScatterChart so this seemed like the best way to go.

**Comment by xile611** [comment]
You can use `fill = "red"` to set the background-color of `CartesianGrid`.
