### ISSUE TITLE
[feature] extend fill property to accept function, array, or string

### ISSUE THREAD

**Issue by cmaurer** [recharts/recharts#652]
I would like to apply a different color for one or more bars (i.e. if a specific bar is an anomaly).  Since the property only accepts a string, it will only allow for one color for the entire series.  Extending the fill property to allow for either a function, array, or a string, would enable (at least I think after looking at the code) the property to change based on the data.

Thanks,
Chris

**Comment by xile611** [comment]
@cmaurer 

Use `Cell` to set different colors for each bars now, just like [this demo](http://recharts.org/#/en-US/examples/PieChartWithCustomizedLabel)

```jsx
<Bar>
 {
   data.map((entry, index) => {
      return <Cell fill={colors[index]} key={`cell-${index}`} />
  })
 }
</Bar>
```

**Comment by cmaurer** [comment]
@xile611 Thanks.  I looked for a solution, I guess I missed it.  Sorry to open a useless issue.
