### ISSUE TITLE
Conflict with older version of react 15.1.0

### ISSUE THREAD

**Issue by OlegE90** [recharts/recharts#653]
Good morning everybody.

I want to use recharts in my project but main part of my them works on old version react 15.1.0
and i can't quickly rewrite my code to a newer version. In recharts package.json i see this...

"peerDependencies": {
    "react": "^0.14.0 || ^15.0.0",
    "react-addons-transition-group": "^0.14.0 || ^15.0.0"
},

It means that every time i run my assembly. I will get npm ERR! Is it possible to do something about this?

**Comment by xile611** [comment]
@OlegE90 It should not be the bug of recharts. Everything works well in my local project. You can create a simple project to reproduce this problem, otherwise I have no idea what's your problem.
