### ISSUE TITLE
[Feature] Diagonal Reference Line

### ISSUE THREAD

**Issue by tyjohnnew** [recharts/recharts#659]
## Do you want to request a feature or report a bug?
Feature 

## What is the current behavior?
You can only add a horizontal or vertical Line

## What is the expected behavior?
I am trying to add a diagonal reference line that is a x=y line.
http://recharts.org/api/#/en-US/examples/LineChartWithReferenceLines

**Comment by jylopez** [comment]
It would also be nice to be able to add a reference line with an arbitrary slope and y-intercept, y=mx+b.

**Comment by xile611** [comment]
Thanks for your suggestion! We have add this feature to the plan of 2.0.0.
