### ISSUE TITLE
How to get no gaps between bars?

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#660]
I've tried just about everything, but I'm not able to create a bar chart (or actually a composed chart with bars in it) that has no gap between bars. Is this possible?

**Comment by xile611** [comment]
http://jsfiddle.net/1509v3gc/


You can set `barGap={0}`.

**Comment by Eric24** [comment]
No, I mean between the X-axis data points (i.e. no gap between the bars in Page A, Page B, ... in your example).

**Comment by xile611** [comment]
http://jsfiddle.net/1509v3gc/1/

Then you can set `barCategoryGap={0}`.

@Eric24  Maybe you can help us to translate the api of `BarChart` more accurately.

**Comment by Eric24** [comment]
Yep, that works. I'm almost certain I had already tried that and didn't get the result I was looking for, but I must have missed it.

This is certainly not an example of poor API translation. barCategoryGap definitely makes sense (which is why I thought I had tried it), but I'm happy to help if I can.

**Comment by xile611** [comment]
OK, thanks~
