### ISSUE TITLE
[Question] : Styling of Tooltip

### ISSUE THREAD

**Issue by marufsiddiqui** [recharts/recharts#663]
Hi,

First of all this is the best chart library for React. My question, if it is possible to change the design and behaviour of tooltip like this http://labratrevenge.com/d3-tip/. I can't seem to make it so

Best
Maruf

**Comment by xdissent** [comment]
You can pass a `wrapperStyle` prop with styles for the tooltip container, or override the tooltip content completely with a `content` fn prop:

```js
function tooltipContent (tooltipProps) {
  return <div>items: {tooltipProps.payload.length}</div>
}
```

Then `<Tooltip content={tooltipContent} />`

**Comment by marufsiddiqui** [comment]
@xdissent thanks for the quick reply. The behaviour of the tooltip is to move it along the hover. i.e. if you hover over a bar then first you see a grey box to show that it is hovered like so
<img width="155" alt="screen shot 2017-04-28 at 16 17 03" src="https://cloud.githubusercontent.com/assets/3726399/25532624/4276fbbc-2c2e-11e7-8dfa-080b680cef86.png">
I want to have something like the d3-tip. The tooltip should only be shown on hover on top of the bar, there should not be any grey box and also the tooltip should not move along mouse hover. Not sure if I'm able to describe what I am thinking

**Comment by xdissent** [comment]
Ah yeah, the positioning is done outside the tooltip content, so that won't help. You'd need to inherit from Tooltip and change the props on the rendered element:

```js
class FixedTip extends Tooltip {
  render () {
    const el = super.render()
    // calc new x and y from props maybe
    const {x, y} = someCalculations(this.props)
    const {style} = el.props
    return cloneElement(el, {style: {...style, x, y}})
  }
}
```

Note that inheritance is required for recharts to find the tooltip element in your chart

**Comment by xdissent** [comment]
And you can turn off the grey box with `cursor={false}` I believe.

**Comment by marufsiddiqui** [comment]
@xdissent thank you very much. I'll try it out

**Comment by ohtanya** [comment]
@marufsiddiqui were you able to accomplish the tooltip at the top of the bar?

**Comment by alex-polunochev** [comment]
How the width of the `cursor` (grey background) can be changed?

**Comment by Tharinducs** [comment]
Can someone help to create my recharts tooltip like this image? I tried a lot but I was unable to do it. Here I am providing my sandbox link for the code.

https://codesandbox.io/s/6v4kp8qm1k

![Screenshot (48)](https://user-images.githubusercontent.com/19866657/55377273-d661c180-5531-11e9-9d12-e94ff16318b6.png)

**Comment by chrisLoPresti** [comment]
@Tharinducs any luck?

**Comment by vinodyadav84** [comment]
is that possible to change tooltip cursor fill static color to liner gradient ?

**Comment by pranavapty** [comment]
@Tharinducs any leads? I am looking for the same output.

**Comment by ckifer** [comment]
@pranavapty try inline styles

No idea why classes don't work here - they should. But 
https://codesandbox.io/s/areachart-forked-ydrmh4?file=/src/components/MonthlyHits.js

inline styles work fine

**Comment by abidra** [comment]
@pranavapty my solution 
https://codesandbox.io/p/sandbox/simple-bar-chart-forked-kcltc7?file=%2Fsrc%2FApp.tsx
But, the arrow on the left since i need it to be on the left
you can adjust the position inside `style.css`
