### ISSUE TITLE
Missing first bar in vertical bar chart

### ISSUE THREAD

**Issue by maurocolella** [recharts/recharts#665]
## Do you want to request a feature or report a bug?
Report a bug.

## What is the current behavior?
One bar is missing when using a vertical layout for a bar chart.

## Steps to reproduce:
See https://github.com/recharts/recharts/issues/90
Between the two graphs, one bar is not rendered when changing the layout mode to `vertical.`

I have the very same problem. Axes are properly set to use categories and numbers respectively, but the first bar is missing.

**Comment by xile611** [comment]
@maurocolella Can you create a jsfiddle demo to reproduce this problem.

**Comment by macbruker** [comment]
@xile611: Is this jsfiddle demo what you need? 
http://jsfiddle.net/x07vs9em/

_(I just forked one of the examples)_

**Comment by jozefpetro** [comment]
Same problem here

**Comment by xile611** [comment]
You should add `<XAxis type="number" />`
