### ISSUE TITLE
Legend Onclick not working after adding Content  and overrides my Legend CSS

### ISSUE THREAD

**Issue by NischithBopaiah** [recharts/recharts#666]
@xile611  as per  your fiddle http://jsfiddle.net/Luk2xapk/1/ this worked but i  had few other requirement so had to add a onClick as well on Legend so i added onClick and i was overriding the .recharts-legend-item CSS for having a border-radius in my legend now after the JsFiddle integration it looks like only Content is working and my onClick doesn't work and it overides my css as well 

complete code here 

const {LineChart, Line, Symbols, Surface, XAxis, YAxis, CartesianGrid, Tooltip, Legend} = Recharts;
const { OverlayTrigger,  Tooltip: BootstrapTooltip, Popover } = ReactBootstrap;

const data = [
      {name: 'Page A', uv: 4000, pv: 2400, amt: 2400},
      {name: 'Page B', uv: 3000, pv: 1398, amt: 2210},
      {name: 'Page C', uv: 2000, pv: 9800, amt: 2290},
      {name: 'Page D', uv: 2780, pv: 3908, amt: 2000},
      {name: 'Page E', uv: 1890, pv: 4800, amt: 2181},
      {name: 'Page F', uv: 2390, pv: 3800, amt: 2500},
      {name: 'Page G', uv: 3490, pv: 4300, amt: 2100},
];
const SimpleLineChart = React.createClass({

  handleClick(e){
   alert("alert comes here ");
  },
  
  renderPopoverTop(dataKey) {
  	return (
    	<Popover id={`popover-${dataKey}`} title={`${dataKey} popover`}>
        <strong>{dataKey}</strong> info here.
      </Popover>
    );
  },
  
  renderCusomizedLegend(props) {
  	const { payload } = props;
    
    return (
      <div className="customized-legend">
       {
       		payload.map((entry, index) => {
            const { dataKey, color } = entry;
            const url = dataKey === 'pv' ?
             '//jsfiddle.net/img/logo@2x.png':
             '//avatars0.githubusercontent.com/u/9164357?v=3&s=60';
             
           
            return (
            	<OverlayTrigger 
              	key={`overlay-${dataKey}`} 
                trigger="hover" 
                placement="top" 
                overlay={this.renderPopoverTop(dataKey)}
              >
                 <span className="legend-item">
                 	 <Surface width={10} height={10} viewBox="0 0 10 10">
                 	   <Symbols cx={5} cy={5} type="square" size={100} fill={color} />
                   </Surface>
                   <span>{dataKey}</span>
                 </span>
              </OverlayTrigger>
            );
          })
       }
      </div>
    );
  },

	render () {
  	return (
      <div className="main-legend-style">
        <LineChart width={600} height={300} data={data}
              margin={{top: 5, right: 30, left: 20, bottom: 5}}>
         <XAxis dataKey="name"/>
         <YAxis/>
         <CartesianGrid strokeDasharray="3 3"/>
         <Tooltip/>
         <Legend content={this.renderCusomizedLegend} onClick={this.handleClick} />
         <Line type="monotone" dataKey="pv" stroke="#8884d8" activeDot={{r: 8}}/>
         <Line type="monotone" dataKey="uv" stroke="#82ca9d" />
        </LineChart>
      </div>
    );
  }
})

ReactDOM.render(
  <SimpleLineChart />,
  document.getElementById('container')
);

 css code  here for overriding  .recharts-legend-item 

.main-legend-style .recharts-legend-item {
  border: 2px solid #a1a1a1;
  padding: 6px 11px;
  font-size: small;
  border-radius: 146px;
  margin: -6px;
  margin-bottom: -13px;
}

please help me to fix this what am i doing wrong here,  the onClick is not firing and CSS is not getting a border-radius after overriding , both were working fine before this came <Legend content={this.renderCusomizedLegend} />  

thanks :)

**Comment by NischithBopaiah** [comment]
solved hence closing

**Comment by kaleem-elahi** [comment]
How did you solved.. ? pls share

**Comment by tommy-ling** [comment]
> 

i'm late to the party but facing the same issue. I know it's long time ago but would you mind explaining what do you mean by "moving onClick to the method where I am rendering custom content?"

Thank you.

**Comment by rago4** [comment]
In case anyone still facing this issue, here's how I've solved that:

```tsx
import type { LegendProps } from 'recharts'

function CustomLayout({ payload, onClick }: LegendProps) {
  return !payload?.length ? null : (
    <div>
      {payload.map((item, index) => (
        <button
          key={item.value}
          onClick={onClick ? (event) => onClick(item, index, event) : undefined}
        >
          ...
        </button>
      ))}
    </div>
  )
}
```

Then you can use it like this:

```tsx
<Legend
  content={<CustomLegend />}
  onClick={(item) => {
    // do anything
  }}
/>
```
