### ISSUE TITLE
Issues with `axis.domain` settings

### ISSUE THREAD

**Issue by liubko** [recharts/recharts#667]
#### `domain={[1, "dataMax"]}`
http://jsfiddle.net/liubko/x1yoboc7/652/
![1](https://cloud.githubusercontent.com/assets/4257937/25587362/65652f06-2eac-11e7-8c99-3e9470bb5dec.png)

#### `domain={[1, "auto"]}`
http://jsfiddle.net/liubko/x1yoboc7/653/
![2](https://cloud.githubusercontent.com/assets/4257937/25587475/ecba2f4c-2eac-11e7-8b49-0a77785e28dc.png)

## What is the expected behavior?
- ticks should be equally distributed across yAxis
- when `domain` contains `auto` it shouldn't violate other constraints

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
- recharts: 0.22.1
- browser: chrome
- os: macOS Sierra 10.12.4

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
