### ISSUE TITLE
Need guide to extend the recharts

### ISSUE THREAD

**Issue by xiaosansiji** [recharts/recharts#668]
Hi, I have been used Recharts for couples of weeks, and i do think it's a really good library for me. Today my boss give me a requirement to display the relationship of some things just like [this](https://bl.ocks.org/mbostock/4062045)(a node graph). But Recharts dosen't support graph now.
![image](https://cloud.githubusercontent.com/assets/7600149/25602464/d087663a-2f26-11e7-911d-076d8f4268dc.png)

  How can I get started to encapsulate d3 like Recharts?  I can't get any info from the online document.
Or maybe all I need is just read the code of Recharts? :)
 Or I should use d3 alone?

**Comment by xile611** [comment]
@xiaosansiji You can read the source code of Recharts. 

If you have used react, you can use react and d3.
Otherwise, you can use d3 alone.

**Comment by CrisLi** [comment]
@xiaosansiji 
Any plan about adding relationship chart to this library? :)

**Comment by xiaosansiji** [comment]
@CrisLi 
 I used d3 and react alone to render force map just like [this](https://github.com/uber/react-vis/blob/master/examples/force-directed-graph/force-directed-graph.js) .You still can use recharts components such as ResponsiveContainer.  
 Or you can use this [libray](https://github.com/xswei/d3js_doc/tree/master/API/d3-force-master). 
 Recharts focus on common needs, topological graph isn't in their plans as far as I know.
