### ISSUE TITLE
[RadarChart] "fullMark" property is not supported (deprecated?)

### ISSUE THREAD

**Issue by dlindahl** [recharts/recharts#67]
On the [Radar Chart example page](http://recharts.org/examples/#SimpleRadarChart), the `data` array contains a `fullMark` property with a value of `150`:

```js
const data = [
    { subject: 'Math', A: 120, B: 110, fullMark: 150 },
    { subject: 'Chinese', A: 98, B: 130, fullMark: 150 },
    { subject: 'English', A: 86, B: 130, fullMark: 150 },
    { subject: 'Geography', A: 99, B: 100, fullMark: 150 },
    { subject: 'Physics', A: 85, B: 90, fullMark: 150 },
    { subject: 'History', A: 65, B: 85, fullMark: 150 },
];
```

Adding that property to my dataset did not seem to have any effect. Additionally, changing the maximum value in my array of data changed the rendering of all other data points.

It looks like `fullMark` has been deprecated in favor of `domain: [0, 150 /* desired max value */]` on `PolarRadiusAxis`.

If that is correct, a change to the example page is likely needed which I will gladly submit a PR for if desired.

**Comment by xile611** [comment]
It's correct the domain of RadarChart  is specified in `domain`  on `PolarRadiusAxis`, and `fullMark` is a original value. If `domain` isn't specified, then the domain is calculated by the minimum and maximum value of dataset .So I gave two examples in  the example page.

But now we can't support such data:
```js
const data = [
    { subject: 'Math', A: 120, B: 110, fullMark: 150 },
    { subject: 'Chinese', A: 98, B: 130, fullMark: 150 },
    { subject: 'English', A: 86, B: 130, fullMark: 150 },
    { subject: 'Geography', A: 99, B: 100, fullMark: 100 },
    { subject: 'Physics', A: 85, B: 90, fullMark: 100 },
    { subject: 'History', A: 65, B: 85, fullMark: 100 },
];
```
That means each element in the `data` may have different scale. Now I have thought of two ways to specify the domain of each element in a `data`.

First, specify domain in `data`:
```js
const data = [
    { subject: 'Math', A: 120, B: 110, fullMark: 150, domain: [0, 150] },
    { subject: 'Chinese', A: 98, B: 130, fullMark: 150, domain: [0, 150] },
    { subject: 'English', A: 86, B: 130, fullMark: 150, domain: [0, 150] },
    { subject: 'Geography', A: 99, B: 100, fullMark: 100, domain: [0, 100] },
    { subject: 'Physics', A: 85, B: 90, fullMark: 100, domain: [0, 100] },
    { subject: 'History', A: 65, B: 85, fullMark: 100, domain: [0, 100] },
];
```

Second, specify domain in `Cell`:
```js
<RadarChart cx={300} cy={250} outerRadius={150} width={600} height={500} data={data}>
  <Radar name="Mike" dataKey="A" stroke="#8884d8" fill="#8884d8" fillOpacity={0.6}>
    {
        data.map((entry, index) => (
          <Cell domain={[0, entry.fullMark]} key={`cell-${index}`}/>
        ))
    }
  </Radar>
  <Radar name="Lily" dataKey="B" stroke="#82ca9d" fill="#82ca9d" fillOpacity={0.6}/>
  <PolarGrid />
  <Legend />
  <PolarAngleAxis dataKey="subject" />
</RadarChart>
```

**Comment by alexchern** [comment]
Hi there.

I tried the above. It doesn't seem to work... It just plots according to the max number... no scaling :-(

Thanks,

Alex

**Comment by icesun** [comment]
The above does not work for me too. 
The following code does not work.
`    {
        data.map((entry, index) => (
          <Cell domain={[0, entry.fullMark]} key={`cell-${index}`}/>
        ))
    }`



When I check <cell>. It's parents are <Bar /><Scatter /><Pie /><RadialBar />. <Radar /> is not in the list. I guess it is the reason?

**Comment by hknowlton** [comment]
I am having the same issue. Does anyone find a workaround for this?

**Comment by sanehab** [comment]
@hknowlton 
If you want to specify fullMark for all all data then you can use the domain property on PolarRadiusAxis. If u want to specify different fullMark for different data then none of the above worked for me. 

For specifying fullMark for different data I had to scale the data myself, and then show the original data when needed in tooltips.

**Comment by hknowlton** [comment]
Thanks @sanehab . Yes I just went with the normalized data approach!

**Comment by Alex-Rudoy** [comment]
for those of you who will stumble on the same issue, use
`<PolarRadiusAxis domain={[0, 1]} tick={false} axisLine={false}/>`
