### ISSUE TITLE
Responsive Pie Chart not animating in Firefox

### ISSUE THREAD

**Issue by mhanger** [recharts/recharts#670]
In PieChart.js, if I don't add a width and height to the PieChart, FF will not animate it.

If I use this render, there is animation in Chrome, IE, but not FF:

(see attachment)

**Comment by xile611** [comment]
Fixed in version 1.0.0 + .

**Comment by greaveselliott** [comment]
Similar issue with the Responsive Pie Chart. Animation and labels work intermittently, resizing the view port seems to trigger the labels after a short delay.
