### ISSUE TITLE
Chart resizes when horizontal legend changes height

### ISSUE THREAD

**Issue by IanVS** [recharts/recharts#671]
## Do you want to request a feature or report a bug?
Reporting a bug, I think.

## What is the current behavior?
The whole chart resizes when the (horizontal) legend grows from one to two rows.

## Minimal demo

http://jsfiddle.net/npbq3jbh/2/

You can resize the window containing the chart until the legend is two lines high, and notice that the bottom of the chart moves.

## What is the expected behavior?
I would not expect that the chart would be resizing when the legend is at the top of the chart.  Or, if the chart does resize, the bottom should be fixed and the top should move out of the way.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
This seems to be present in all recent versions.

**Comment by xile611** [comment]
@IanVS You can set `height` of `Legend`, otherwise the chart will update when the height of `Legend` change.
