### ISSUE TITLE
Linear graph repeating yAxis tick values

### ISSUE THREAD

**Issue by pedroabreu** [recharts/recharts#673]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?

Yaxis repeats values if there are not bigger than the maximum number of ticks (5 by default)

It doesn't happen if I pass an array of zeroed values but if one of the entries has a value of 1, this happens

[Bug image](http://imgur.com/a/bNofn)

[zeroed image](http://imgur.com/a/zEBOy)

## What is the expected behavior?

Should behave the same way as the zeroed graph. The max tick should be the same number of the number of ticks displayed

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

recharts: 0.22.4

**Comment by xile611** [comment]
@pedroabreu  If the ticks of `YAxis` is required to be integer, you can specify

```jsx
<YAxis allowDecimals={false} />
```

the props `allowDecimals` has default value `true`.

**Comment by xile611** [comment]
@pedroabreu Please create a demo to reproduce your problem.

**Comment by pedroabreu** [comment]
@xile611 the issue is not related to recharts, so I'll close this issue (sorry for wasting your time)

For future reference, issue is demoed here http://jsfiddle.net/Luk2xapk/2/ and it works fine BUT I'm formatting the values to integer (because they are always integer) but because I allow decimals, all the decimals are parsed to integer, which makes me with an axis of [0, 0, 1, 1, 1 ] (everything rounded up)

Thanks and good work on the plugin 👍
