### ISSUE TITLE
Extra character in the data

### ISSUE THREAD

**Issue by imtmh** [recharts/recharts#676]
I want to show extra characters in the data that i pass, in my case, I wanted to display a $ (dollar) symbol in the graph (in tooltip or on y-axis) the example is given in this fiddle below

[http://jsfiddle.net/tirumaleshkc/9d72Lnzq/](http://jsfiddle.net/tirumaleshkc/9d72Lnzq/)

I see the data in the tooltip, but its not displayed in the graph (obvious reason must be its not a number)

Is there any way to display the graph that way?

**Comment by xile611** [comment]
@imtmh You can add `formatter` to `Tooltip`.

**Comment by imtmh** [comment]
Your suggestion will solve only the Tooltip, still, it doesn't help me to see the graph. I got to know that it accepts the data only if it is in the form of numbers and no strings allowed. 

I converted my data to have only numbers and then added a prop `unit='$'` to `Line` to solve the problem.
