### ISSUE TITLE
Rechart animation of sector

### ISSUE THREAD

**Issue by alexliu-github** [recharts/recharts#678]
Hi, I have question about using React-Motion in Rechart component. If I have already using React-Motion every component I wrote, would like to know if I could use React-Motion in some of the components like Sector. For example, you have a demo of PieChart using activeIndex and activeShape as call back to draw additional shape, I would like to animate the sector.  
Have you thought about just using React-Motion in the Rechart? 
Thank you.

**Comment by alexliu-github** [comment]
Ideally, the animation should be just pluggable, yet currently it is coupled with components in the source code,

**Comment by redbmk** [comment]
@alexliu-github did you find a good solution for this? I just came across https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animate, which seems pretty promising.
