### ISSUE TITLE
pie chart demo doesn't show anything

### ISSUE THREAD

**Issue by kylelix7** [recharts/recharts#679]
## Do you want to request a feature or report a bug?
bug
## What is the current behavior?
piechart in demo does NOT show anything. console indicates a lot of errors. most are related to that component's state is not set properly

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/9y45ut13/).
run the demo, and click piechart example, nothing happens

## What is the expected behavior?
pie chart(s) show up

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
latest master on chrome 58.0.3029.96 (64-bit) on Ubuntu 16.04

**Comment by drborges** [comment]
Same here...

**Comment by drborges** [comment]
Downgrading the lib to `v0.22.4` worked for me.

**Comment by alexsinfarosa** [comment]
Yes, downgrading worked for me as well.

**Comment by xile611** [comment]
Fixed in version 1.0.0-alpha.1

**Comment by vuuet** [comment]
I still got this bug in v1.0.0-alpha.1

**Comment by Domthegrom** [comment]
Bump, still is not resolved in v1.1
