### ISSUE TITLE
How to rotate tick text?

### ISSUE THREAD

**Issue by endigo** [recharts/recharts#680]

**Comment by endigo** [comment]
Oh sorry i found it. http://recharts.org/#/en-US/examples/CustomizedLabelLineChart

**Comment by quaqua** [comment]
In case, anybody else is looking for this example:

That documentation endpoint doesn't exist any more. But the fiddle code is still there (found it in the commits log):

http://jsfiddle.net/344uh0ax/62/

**Comment by akuji1993** [comment]
Thank you very much for this @quaqua

**Comment by ckeeney** [comment]
The fiddle is broken and the docs link is broken.  Is there an updated link to the docs for this?

**Comment by fes300** [comment]
looks like the fiddle is not working anymore

**Comment by patrikCeprOict** [comment]
Or you can use component:

```
import React from "react";

export const CustomizedAxisTick = ({
    x,
    y,
    payload,
    rotateAngle = -45,
}: {
    x?: number;
    y?: number;
    payload?: any;
    rotateAngle?: number;
}) => {
    return (
        <g transform={`translate(${x},${y})`}>
            <text x={0} y={0} dy={16} textAnchor="end" fill="#666" transform={`rotate(${rotateAngle})`}>
                {payload.value}
            </text>
        </g>
    );
};
```
