### ISSUE TITLE
Mouse coordinates from PieChart's onClick method

### ISSUE THREAD

**Issue by Ziker22** [recharts/recharts#681]
Hi,
Is there a way to get actual x/y coordinates of mouse click no trelative ones im getting ?

ths for reply in advance

**Comment by xile611** [comment]
@Ziker22 

```jsx
const handleClick = (entry, index, e) => {
  console.log(e.pageX, e.pageY);
};

<PieChart>
  <Pie onClick={handleClick} />
</PieChart>
```

**Comment by SenelithPerera** [comment]
@xile611 can the same thing be done to the bar charts and other charts too ?
