### ISSUE TITLE
Stacked bar chart RTL support

### ISSUE THREAD

**Issue by Ziker22** [recharts/recharts#682]
Hi,
Im using rechart together with postcss-rtl
Im trying to add right-to-left support for arabic countries and i encountered problem
Several elements are not flipped
 - tooltip
 - Y axis label
 - bars are not in reversed order

Is there a way to fix it or should i somehow start hacking into it ?

thx

**Comment by surenachiron** [comment]
did you find any way?

**Comment by ckifer** [comment]
There is a reversed prop on the XAxis which may help. Otherwise, you should be able to swap the side that the YAxis is on easily enough and change which side text is aligned to.
