### ISSUE TITLE
Categories order in yAxis

### ISSUE THREAD

**Issue by mmeliabit** [recharts/recharts#683]
Hello,
I am trying to add a yAxis to a LineChart to represent some boolean variables. I want the ticks to be labelled "Y" and "N". I set yAxis type to "category", but I cannot find a way to make the "Y" always appear at the upper position on the axis. It depends on the first Line values: if all values of the first line are "true", then the "Y" tick appears at the lower position; if they are all "false" it appears at the lower position.

I tried to change yAxis type to number, map true to "1", and false to "0" and then format axis labels to show "Y" and "N" instead of "0" and "1". It works, but if I do so, "0" and "1" will appear in the Tooltip instead of "Y" and "N". I cannot use Tooltip formatter, because the same chart has variables which are not boolean.

Is there a way to force an order of category-axes ticks or a way to format only some Tooltip values?

**Comment by AliceR** [comment]
I have the same question, my categories are "A", "B", "C", "D" - and obviously I want them to appear in alphabetic order. Any updates on this?

**Comment by sharynneazhar** [comment]
Any updates on how to do this? 

Similar to AliceR, I want to create an alphabetical category.

**Comment by burgua** [comment]
I have used ugly workaround for this purpose. I inserted line with null as values, but with correct order of categories. In this way I can manipulate the order of category-axes ticks.

<pre>
[{
	"data": [{
		"name": "KW 27",
		"value": null
	}, {
		"name": "KW 28",
		"value": null
	}, {
		"name": "KW 29",
		"value": null
	}]
}, {
	"data": [{
		"name": "KW 27",
		"abgeschickte Bewerbungen, 2017": 1300
	}, {
		"name": "KW 28",
		"abgeschickte Bewerbungen, 2017": 1871
	}, {
		"name": "KW 29",
		"abgeschickte Bewerbungen, 2017": 2524
	}],
	"name": "abgeschickte Bewerbungen, 2017"
}, {
	"data": [{
		"name": "KW 27",
		"abgeschickte Bewerbungen, 2018": 1228
	}, {
		"name": "KW 28",
		"abgeschickte Bewerbungen, 2018": 1795
	}, {
		"name": "KW 29",
		"abgeschickte Bewerbungen, 2018": 2444
	}],
	"name": "abgeschickte Bewerbungen, 2018"
}]
</pre>

**Comment by Brandon-Pampuch** [comment]
Doesn't this workaround leave 5 empty points at the beginning of your graph?

**Comment by Brandon-Pampuch** [comment]
I found that Chart.js has this exact functionality. 
[](https://www.chartjs.org/samples/latest/scales/non-numeric-y.html)
