### ISSUE TITLE
Axis of type category should render all `ticks` when they are specified manually.

### ISSUE THREAD

**Issue by liubko** [recharts/recharts#684]
## Do you want to request a feature or report a bug?
I guess it's a bug, or maybe I just got an idea wrong. Would appreciate any input on this.

## What is the current behavior?
I have `YAxis` of type `category`, and I manually specified `ticks`. But if chart data doesn't have any values for some tick aka category it wouldn't show up on the axis

#### Demo:
http://jsfiddle.net/liubko/x1yoboc7/672/

## What is the expected behavior?
in that particular [demo](http://jsfiddle.net/liubko/x1yoboc7/672/) I would expect to see tick with `d` label  at the `yAxis`

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
recharts: 0.22.1
browser: chrome
os: macOS Sierra 10.12.4

**Comment by xile611** [comment]
@liubko  You can render customized ticks by specifying the `tick` to be a function or react element.
It's not a bug now.
