### ISSUE TITLE
How can i change the font and color of the xaxis and yaxis.

### ISSUE THREAD

**Issue by Rinoy888** [recharts/recharts#685]
When iam setting the stroke of axis the whole axis line is getting effected , i just want the text to be changed..How can i do that??

**Comment by xile611** [comment]
@Rinoy888 

```jsx
  <XAxis tick={{ fill: 'red' }} />
```

**Comment by jt9001** [comment]
Can this be used to change the font-size of axis labels? Thanks!

**Comment by ThePianoDentist** [comment]
<XAxis tick={{fontSize: 5}} />

does the job for me

**Comment by lumio** [comment]
@DmitryGG, look at http://recharts.org/en-US/api/YAxis#tickLine (works for both `XAxis` and `YAxis`)

```
<YAxis
  tickLine={{ stroke: 'red' }}
/>

**Comment by EdisonDevadoss** [comment]
How can I change the font size for Brush?

**Comment by mave838** [comment]
How can I have different colour for every font on YAxis?

**Comment by siridamineni** [comment]
How can I have a different color for every tick on XAxis?

**Comment by dondxniel** [comment]
How can I style the label? They seem to be overlapping the tick in my case.
