### ISSUE TITLE
Draggable points

### ISSUE THREAD

**Issue by Hegoakerbeltz** [recharts/recharts#686]
Hi,

I am trying to allow the user to drag the points of a line chart, which would modify the underlying data and redraw the line both while the mouse is down and released.

Something like this: [this](http://www.fusioncharts.com/dev/chart-guide/drag-able-charts/creating-drag-able-charts.html#creating-a-drag-able-line-2d-chart) or [this](https://www.rgraph.net/canvas/docs/adjusting-line.html)

This may be a feature request, but for now I am simply hoping that this either can easily be done, or that someone has already managed to do something similar, before I go into it.

Many thanks,

**Comment by xile611** [comment]
@Hegoakerbeltz I think If you can bind events to the `dots` of `Line`, you can achieve what you want.

**Comment by Hegoakerbeltz** [comment]
Many thanks for the reply. 

I didn't realise you could based on #560. I'll give it another go.

**Comment by maxdow** [comment]
Hi , i try to do the same thing. Did you finally find a working solution @Hegoakerbeltz ?

**Comment by lluisemper** [comment]
Has someone accomplish doing this? @maxdow  @Hegoakerbeltz

**Comment by andreamazz** [comment]
I'm also interested in being able to move single points via drag.
I was able to achieve this by adding a click (up/down/move) handler to the single dots. In the move handler I then update the state, causing a re-render. While this works, the performance can take a significant hit when the dataset has a fair amount of points to draw. 
Is there a workaround? 

I was thinking about drawing the single point and its immediate neighbors on a layer above the chart while the user is interacting, mimicking the original chart, and only update the data source when the click is released, but  I have no idea on how to retrieve the neighbor positioning inside the chart. 

Any help would be appreciated.

**Comment by andreamazz** [comment]
> Hi @andreamazz,
> 
> Did you find a solution? I'm facing a similar problem.

Not really, I dropped recharts and wrote my own chart with react-konva as a base.

**Comment by ItsTonyDavid** [comment]
> > Hi @andreamazz,
> > Did you find a solution? I'm facing a similar problem.
> 
> Not really, I dropped recharts and wrote my own chart with react-konva as a base.

I found a solution, but Im using the `BarChart`, and instead using a point, I used a line. But I believe the same principle might be useful for a [ReferenceDot](https://recharts.org/en-US/api/ReferenceDot).


```
export function BarPlot({ results, current }) {
  const [isMoving, setIsMoving] = useState(false);
  const [value, setValue] = useState(current)

  const handleMouseMove = (event) => {
    if (event && event.activeLabel && isMoving) {
      setValue(event.activeLabel);
    }
  };

  const handleOnClick = (data) => {
    setValue(data.date)
  };

  return (
    <ResponsiveContainer width="100%" height={200}>
      <BarChart
        data={results}
        onMouseMove={handleMouseMove}
        onMouseUp={() => {setIsMoving(false)} }
      >
        <XAxis dataKey="date"/>
        <Tooltip cursor={{fill: 'transparent'}}/>
        <Bar dataKey="count" fill="#4c9a1a" onClick={handleOnClick}/>
        <ReferenceLine
          x={value}
          stroke="red"
          strokeWidth={3}
          onMouseDown={() => {setIsMoving(true)} }
          onMouseUp={() => {setIsMoving(false)} }
        />
      </BarChart>
    </ResponsiveContainer>
  )
}
```

**Comment by YonatanToker** [comment]
Another solution but different library: Chart.js + chartjs-plugin-dragdata.

**Comment by Steveb599** [comment]
Anyone managed to do that with pie chart?

**Comment by ckifer** [comment]
Linking example for PieChart https://github.com/recharts/recharts/pull/5777
