### ISSUE TITLE
Unable to use string in YAxis lables

### ISSUE THREAD

**Issue by Swarna-Jain** [recharts/recharts#688]
I have written code for y Axis follows:
<YAxis tickCount={2} tick={["online", "offline"]} />
but unable to display strings on Y Axis.
How to set strings as Y Axis labels.

**Comment by xile611** [comment]
@Swarna-Jain  Can you create a jsfiddle example ?

**Comment by Swarna-Jain** [comment]
Solved issue

**Comment by xile611** [comment]
OK~

**Comment by dimosmera** [comment]
I think I'm looking to do something similar.
@Swarna-Jain I'm curious, how did you solve this?

**Comment by PoojaSpiking** [comment]
Hi, @Swarna-Jain, I'm trying to solve a similar issue. Can you please let me know how you did it? Thanks.
