### ISSUE TITLE
dynamic <Bar/>'s do not update correctly

### ISSUE THREAD

**Issue by sh3nan1gans** [recharts/recharts#695]
There seems to be a bug around updating bar components that are added dynamically. 

Failing example: (notice that we have to update the data in state in order to see the new color state)
http://jsfiddle.net/9x9cnfpr/3/

Workaround example: (here I added an extra <Bar/> component that isn't generated by a .map function)
http://jsfiddle.net/5gy5oaru/2/

Please let me know if I can help. Great project btw! I've been enjoying using it.

**Update**: I've found that removing everything but the Bar components from within the BarChart component allows for the fill of the bars to be changed. Here's an example:
http://jsfiddle.net/eceh1hyj/1/

@xile611 - any ideas on this?

**Comment by xile611** [comment]
@sh3nan1gans I think this has been fixed. I can't find your problem.
