### ISSUE TITLE
Gap between bar

### ISSUE THREAD

**Issue by semeleven** [recharts/recharts#696]
## Do you want to request a feature or report a bug?
report a bug
## What is the current behavior?
Now bar chart have gap between bar, but in props barCategoryGap={0} and barGap={0}
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/9y45ut13/).
http://jsfiddle.net/tos40az6/
## What is the expected behavior?
No gap between bar
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Current version and latest Chrome

**Comment by edward12699** [comment]
i come across it too ,,,

**Comment by Simek** [comment]
Any plans on digging in to that @xile611?

**Comment by codecvlt** [comment]
Would be great to have this fixed! Currently barCategoryGap does not seem to have any effect. When you have just one category on the x axis with two bars, they are very widely spaced and this doesn't look very good.

**Comment by samueldepooter** [comment]
Sadly, this still seems to be the case?

@xile611 I could take a look at it but with the holidays coming up it's not going to be too soon. Do you have a status update on this issue?

**Comment by Simek** [comment]
After working on this problem for a while I have noticed that can use `Area` to recreate desired visualisation. It's "hacky" way, but works on current released version.

For example for the pair of `startTs` and `stopTs` you need to created four points:
```
return [
	Object.assign({ ts: startTs - 1, val: null }),
	Object.assign({ ts: startTs, val }, ...dataForTs),
	Object.assign({ ts: endTs, val }),
	Object.assign({ ts: endTs + 1, val: null })
];
```
<img width="1089" alt="screenshot 2018-12-27 at 11 55 01" src="https://user-images.githubusercontent.com/719641/50477803-46f6c080-09ce-11e9-8965-250be436858b.png">

**Comment by mike31s** [comment]
I had the same issue.  Try using negative values! ` barCategoryGap={-20} ` did the trick for me

**Comment by gugiserman** [comment]
I'm having the same issue in a vertical layout, but negative gaps also didn't work in my case.

**Comment by Viveckh** [comment]
This behavior seems to result from using `barCategoryGap` at the Chart level and `barSize` at the Bar level TOGETHER. If you are using `barSize` in your Bar component, make sure to remove that and `barCategoryGap` at the chart level should work just fine.

**Comment by shrutikaponde** [comment]
> This behavior seems to result from using `barCategoryGap` at the Chart level and `barSize` at the Bar level TOGETHER. If you are using `barSize` in your Bar component, make sure to remove that and `barCategoryGap` at the chart level should work just fine.

Removing `barSize` and adding `barCategoryGap={0}` at chart level worked in my case.

**Comment by skipjack** [comment]
Related:

https://stackoverflow.com/questions/55215557/recharts-issue-with-gaps-between-bars

**Comment by skipjack** [comment]
Afaik, the only way to get a consistent gap between bars when specifying `barSize` is either...

- Make sure your `data` always (you can add empty records or trim/rollup additional ones).
- Customize `height` or `width` depending on your `layout`.

Here's an example of the latter in a vertical bar chart:

``` js
<BarChart
    width={width}
    height={Math.min(height, data.length * (barHeight + 4))}
    data={data}
    layout="vertical"
    barSize={barHeight}
>
    {/* ... */}
</BarChart>
```

The `Math.min` will keep it from going over some max `height` though past that point the bar size and gap will start to shrink.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
