### ISSUE TITLE
Chart break (leave gap) when data is null

### ISSUE THREAD

**Issue by chin-idean** [recharts/recharts#702]
## Do you want to request a feature or report a bug?
Feature
## What is the current behavior?
Leave a gap if the data is null

http://jsfiddle.net/ktwfp03m/5/

## What is the expected behavior?
Drawing continuous line 
Look like this http://jsfiddle.net/ktwfp03m/6/

**Comment by chin-idean** [comment]
I found that there is a support for `connectNulls` props for Area, Line but it doesn't look same as it should be when data is 0

**Comment by xile611** [comment]
@chin-idean When use `connectNulls` for `Line` or `Area`, If the second point is Null, we'll skip the second point, and  connect the first point and the third point now, just like the behavior of `Area`.
There's some bug of  `connectNulls` of `Line` now.

In you case, it's recommended to fill 0 for null entries before added to charts.

**Comment by natasha-robarge** [comment]
Why was this reverted? This is also happening for bar charts - is there a way to stop the chart from breaking for stacked bar charts?
