### ISSUE TITLE
Line Chart Interval - Ticks 

### ISSUE THREAD

**Issue by Shadowman4205** [recharts/recharts#704]
Hello i am new with this ,
```
<LineChart width={600} height={300} data={data}
            margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
                        <XAxis dataKey="cycle" interval={50} type="number" domain={['dataMin', 'auto']} />/>
                        <YAxis tickSize={10} ticks={[0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35]} />
                        <CartesianGrid strokeDasharray="3 3" />
                        <Tooltip />
                        <Legend />
                        <Line type="monotone" dataKey="max" stroke="#8884d8" />
                        <Line type="monotone" dataKey="avg" stroke="#82ca9d" />
 </LineChart>
```
First using for YAxis: 
using tickSize=10 do not show all ticks it show only 6 of them in this example it show
> 0.05, 0.1, 0.15, 0.2, 0.25, 0.35
Expected
> 0.05, 0.1, 0.15, 0.2, 0.25,0.30, 0.35
Why this does not work?

Second for XAxis 
in my data the min cycle is 100, how make it so the tick will go something like this
>100,150,200,250,300,350........etc

what am i missing? i cannot get it.

**Comment by xile611** [comment]
@Shadowman4205 

When you specify `ticks={[0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35]}`, the rendered ticks are just what you have specified. If you just want 10 ticks, then 10 ticked will be calculated internally by recharts.

So for the second problem, you can just spect `ticks={[100, 150, 200, 300, ....]}`

**Comment by Shadowman4205** [comment]
Thanks but like i said 
i expect get  > 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35 but i getting > 0.05, 0.1, 0.15, 0.2, 0.25, 0.35. Missing 0.3

**Comment by kimjuny** [comment]
@Shadowman4205 Did you solve this problem? I'm having same problem. Some ticks are just missing even I specified explicitly which ticks to show.

**Comment by kimjuny** [comment]
@xile611 @Shadowman4205 https://github.com/recharts/recharts/issues/745

**Comment by juampick** [comment]
Same issue around here @kimjuny @xile611 @Shadowman4205

**Comment by juampick** [comment]
I've just solved doing this:
```
<YAxis
          type="number"
          yAxisId="right"
          orientation="right"
          domain={[0, 200]}
          ticks={[0, 10, 20, 30, ...., 200]}
          allowDecimals={true}
          allowDataOverflow={true}
          stroke={lineSelected.stroke}
          interval={0}/>
```

Thanks! Hope this helps, I think that the magic was the: `interval={0}`, I've tested before with `interval="0"` and didn't work.

**Comment by vtarelkin** [comment]
@juampick @kimjuny @xile611

setting interval works ONLY if specified ticks one by one otherwise the next to last tick is missing. Any solution on this? Don't want to mention all ticks in domain explicitly (which may be different)
