### ISSUE TITLE
PieResponsiveContainer appears to be broken

### ISSUE THREAD

**Issue by mcnuttandrew** [recharts/recharts#707]
The fiddle corresponding to the PieResponsiveContainer example appears to be broken. I'm on latest chrome on latest macOS.

http://jsfiddle.net/svrquh32/?utm_source=website&utm_medium=embed&utm_campaign=svrquh32

**Comment by wesbos** [comment]
All the pie charts are broken for me too

**Comment by palashkaria** [comment]
@mcnuttandrew looks like a CSS issue in that fiddle
http://jsfiddle.net/svrquh32/6/

**Comment by palashkaria** [comment]
update: I see the [demo](http://recharts.org/#/en-US/examples/PieResponsiveContainer) is the same as the fiddle. I think what they are trying to show is PieChart can adjust size based on it's container.

What you are looking for is responsive according to screen width, I assume? To do that, you can use %, vh, vw units, or any other method you like. Eg. is this [fiddle](http://jsfiddle.net/svrquh32/7/),
