### ISSUE TITLE
XAxis and YAxis Label Displaying Over Data

### ISSUE THREAD

**Issue by mvpowers** [recharts/recharts#709]
## Do you want to request a feature or report a bug?
- Report a bug

## What is the current behavior?
- Labels are displaying over dataKey

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/9y45ut13/).
- Create chart with XAxis Label and/or YAxis Label
- http://jsfiddle.net/6sp2ejx6/?utm_source=website&utm_medium=embed&utm_campaign=6sp2ejx6
- screenshot: http://i.imgur.com/NIfXH3Q.png

## What is the expected behavior?
- Labels should not display over dataKey

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
- Recharts 1.0.0-alpha.0
- os: Ubuntu 16.04.2 LTS
- browser: Firefox 53.0.2 (64-bit)
- browser: Google Chrome Version 58.0.3029.110 (64-bit)

**Comment by xile611** [comment]
@mvpowers You can change the position of labels like the following:
```jsx
<XAxis dataKey="name" label={{ value: "Pages", position: "insideBottomRight", dy: 10}} />
<YAxis label={{ value: "index", position: "insideLeft", angle: -90,   dy: -10}} />
```

**Comment by mvpowers** [comment]
@xile611 This works perfectly. Thank you.

**Comment by bsplosion** [comment]
It's incredible how flexible recharts can be, all while failing to document its strengths.

The `dx` and `dy` props are nowhere to be found in the current API docs for Label (https://recharts.org/en-US/api/Label) or the axes (https://recharts.org/en-US/api/YAxis), nor any other class I could identify.  I'm not even sure where those are located in the code - drilling through dependencies just reveals the axis `label` prop as type `string | number | ReactElement | object`, which completely masks functionality.

**Comment by vitalii-bilous-epa** [comment]
It's not documentation failing, it's more about inheritance. So, just keep in mind, that all elements are svg and they all have some basic properties. But yes, for guys, who start working with recharts it can be confusing

**Comment by bsplosion** [comment]
@vitalii-bilous-epa do all SVG properties work with all recharts classes?  If not, then the documentation should really either call out those that _do_ work, or state that all work except a specific subset.

Not all recharts classes map to SVG elements, by the way, which is one source of confusion.  If they're consistent about mapping all SVG properties when a class implements it, the documentation could just be updated to include an "SVG element" flag or something of the sort to indicate you can use all SVG props given a class.
