### ISSUE TITLE
Server-side rendering?

### ISSUE THREAD

**Issue by Renaud009** [recharts/recharts#71]
I have been trying to render ComposedChart and BarChart from the server. The grid and axis get rendered but data content isn't. I see no error nor warnings. It is suppose to be working? I see no mention about server-side rendering at http://recharts.org/

Thanx

**Comment by xile611** [comment]
Recharts support server side render. But some components need to calculate the width or height of a  dom node, so some component can't show in server side, just like `Tooltip`, ResponsiveContainer.

Maybe you  can show  your code, or give me a jsfiddle example.

**Comment by Renaud009** [comment]
My isomorphic app is based on react-starter-kit. I forked it so you can see the whole code here: https://github.com/Renaud009/react-starter-kit. I just added recharts library with npm and copied the ComposedChart component based on this example http://recharts.org/examples#LineBarAreaComposedChart.

Making a GET localhost:3001 with Postman shows me that items (ex. try to find class recharts-line-dots) are not rendered on the first call but axis as well as grid are.

Maybe it has to do with the animation?

**Comment by xile611** [comment]
Yeah. It was because animation of `Line`, `Area`, `Bar` was added by default.
You can solve this problem by removing animation.
```jsx
<ComposedChart width={600} height={400} data={data}
            margin={{top: 20, right: 20, bottom: 20, left: 20}}>
  <XAxis dataKey="name"/>
  <YAxis />
  <Tooltip/>
  <Legend/>
  <CartesianGrid stroke='#f5f5f5'/>
  <Area isAnimationActive={false} type='monotone' dataKey='amt' fill='#8884d8' stroke='#8884d8'/>
  <Bar isAnimationActive={false} dataKey='pv' barSize={20} fill='#413ea0'/>
  <Line isAnimationActive={false} type='monotone' dataKey='uv' stroke='#ff7300'/>
</ComposedChart>
```

**Comment by Renaud009** [comment]
Thank you, it works like a charm.

And good job with this chart library.

**Comment by sauravexodus** [comment]
Doesn't work anymore

**Comment by adamsoffer** [comment]
This doesn't work anymore :/ Any suggestions?

**Comment by hkgnp** [comment]
Any updates from the devs for this issue?

**Comment by VikaShcherbanych** [comment]
Maybe there is a solution to render ResponsiveContainer on the server side. I will be grateful for any advice

**Comment by ckifer** [comment]
It can't be rendered on the server since the server doesn't know the size of your screen

**Comment by jjjrmy** [comment]
@ckifer how can you set a fixed width/height? it doesn't allow it within the chartConfig. If I change the ChartContainer to a Div then it works fine.
```
    <ChartContainer config={chartConfig} >
      <BarChart
        data={data}
        width={500}
        height={300}
```

**Comment by ckifer** [comment]
ChartContainer isn't a component that exists. What component are you using?

**Comment by jjjrmy** [comment]
> ChartContainer isn't a component that exists. What component are you using?

Oh actually you're right - that was something from Tremor library.
