### ISSUE TITLE
[FEATURE] Support multiple y-axes in ScatterChart.

### ISSUE THREAD

**Issue by digorydoo** [recharts/recharts#711]
Current behaviour: When defining multiple data sets for a ScatterChart, all of them share the same x-axis and y-axis.

Feature request:  I need to be able to define multiple y-axes. Each data set should have its own y-axis. All the y-axes should appear at the left-hand side of the chart. Each y-axis should be drawn in the colour of the dataset (the same as scatterProps.fill). The x-axis should be shared by all the datasets.

**Comment by xile611** [comment]
This feature is supported in 1.x of Recharts.

You can add multiple y-axes in ScatterChart like the following codes.

```jsx
         <ScatterChart width={400} height={400} margin={{ top: 20, right: 20, bottom: 0, left: 20 }}>
            <XAxis type="number" dataKey="x" name="stature" unit="cm" />
            <YAxis yAxisId="left" type="number" dataKey="y" name="weight" unit="kg" />
            <YAxis yAxisId="right" type="number" dataKey="y" name="weight" unit="kg" />
            <ZAxis type="number" dataKey="z" range={[50, 1200]} name="score" unit="km" />
            <CartesianGrid />
            <Tooltip/>
            <Legend/>
            <Scatter yAxisId="left" name="A school" data={data01} fillOpacity={0.3} fill="#ff7300" />
            <Scatter yAxisId="right" name="B school" data={data02} fill="#347300" />
          </ScatterChart>
```

You can also check [this demo](http://recharts.org/#/en-US/examples/MultipleYAxesScatterChart)
