### ISSUE TITLE
Problem with YAxis domain, when not adding YAxis to LineChart

### ISSUE THREAD

**Issue by tuliglowicz** [recharts/recharts#714]
## What is the current behavior?
I am making a chart with neither XAxis nor YAxis. The chart displays Y domain as [0, max]. Since the differences between values are small the chart looks like it was almost a straight line. I would like to be able to change the Y domain, but the only way to do it is to add YAxis, which completely destroys my layout. I have overcame this problem by subtracting the minimal value from all the values, but it is too cumbersome. It has to be easier way, without interfering with the data.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo 
I get:
![chart](https://cloud.githubusercontent.com/assets/423060/26640998/9f6f05ac-4629-11e7-876c-1eaf0bc9db33.png)

## What is the expected behavior?
I want to have:
![chart](https://cloud.githubusercontent.com/assets/423060/26640701/bda34bd8-4628-11e7-9cb6-4937398b4171.png)

## Questions, in case I missed something
- Is it possible, to add YAxis with domain prop, but not drawing the Axis, and not taking space for it?
- Is there any other way to change Ydomain boundary values? Perhaps somehow from the LineChart level?

**Comment by xile611** [comment]
@tuliglowicz You can add a `YAxis` which has props `hide={true}`.

```jsx
<LineChart>
  <YAxis  hide />
</LineChart>
```

**Comment by tuliglowicz** [comment]
Please tell me it wasn't in API doc on http://recharts.org/#/en-US/api/YAxis ? Otherwise I must be blind. ;)
