### ISSUE TITLE
Bars in bar chart no longer displays when using state variable for data

### ISSUE THREAD

**Issue by flamencoflsh** [recharts/recharts#716]
@xile611 @arcthur @evilucifero @jasonHzq @techniq @McMenemy @supersteves @jochenberger 
Hi!  I am encountering an odd error... 

I am currently using a bar chart.  I started out by setting the data to a test variable I created within the local file, and everything is working beautifully.  However, I updated the test variable to a state variable that I set using getInfo() so I can use real data from my database.  

At this point, the chart still "renders" in that when I mouseover, I can still see the tooltip which shows that the correct data is being used.  However, the actual bars themselves in the bar chart are no longer rendering (so I was basically mousing over blank space to see the tool tips).  Do you know what this is about?

Thank you!

**Comment by xile611** [comment]
@flamencoflsh Can you create a jsfiddle demo to reproduce your problem? It seem that the length of data is too big which is bigger than the width of chart.

**Comment by flamencoflsh** [comment]
Hi @xile611, I've attached a screenshot of the bar chart when it does work with the local data (i.e. "dataMonths"), and another of what it looks like when I pull in data to a state variable (i.e. this.state.dataMonths) using loadInfo() and  I've also checked and the correct data is being pulled in.  From the tooltip, you can also confirm that it is using the correct data and the correct number of bars, except the bars themselves (and the y-axis numbers) are not visible.  

![screen shot 2017-05-31 at 4 57 21 pm](https://cloud.githubusercontent.com/assets/9296896/26667934/576a3924-465c-11e7-8477-4ccf2da85465.png)

![screen shot 2017-05-31 at 11 54 18 pm](https://cloud.githubusercontent.com/assets/9296896/26667970/830c3f28-465c-11e7-83dc-2205e83a7b01.png)

**Comment by xile611** [comment]
@flamencoflsh Check the type of data loaded from server, maybe the type of 'points' is string not number.
