### ISSUE TITLE
Pie chart breaks updating from 0.22.3 to 0.22.4

### ISSUE THREAD

**Issue by ciaoben** [recharts/recharts#717]
Updating to version `0.22.3` to version `0.22.4` breaks this chart.
```
            <PieChart width={330} height={250}>
              <Tooltip />
              <Pie
                data={quotaData}
                outerRadius={100}
                dataKey="email prova"
                innerRadius={30}
                fill="#8884d8"
                paddingAngle={1}
                label={({ value, date }) => `${date}GB`}
              >
                {quotaData.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={COLORS[index]} />
                ))}
              </Pie>
            </PieChart>
```

It doesn't render anymore and gives no errors.
Am I missing something? I see nothing related on the changelog.

It asks me for a `dataKey` prop on the `<Pie>` component to be required, but even adding it, it does not render.

Meanwhile, I will try to find out what happen and will report here more details if needed.

**Comment by wesbos** [comment]
None of the pie charts are working on the website right now too, is this related?

**Comment by mattmast** [comment]
I have the same question as wesbos.

**Comment by pbdm** [comment]
have got the seme issue

**Comment by pbdm** [comment]
seem's that Pie has change it's props, add dataKey slove the problem
if the data is like 
```
const data02 = [{name: 'A1', value: 100},
                    {name: 'A2', value: 300},
                   {name: 'B1', value: 100},
                   {name: 'B2', value: 80},
                   {name: 'B3', value: 40},
                   {name: 'B4', value: 30},
                   {name: 'B5', value: 50},
                  {name: 'C1', value: 100},
                  {name: 'C2', value: 200},
                   {name: 'D1', value: 150},
                   {name: 'D2', value: 50}]
```
the dateKey could be `value`

**Comment by ninahaack** [comment]
I got the same errors. Putting value as datekey following the example of @pbdm worked, but onMouseEnter is not working.

**Comment by oliverwatkins** [comment]
None of the pie charts work for me as well

**Comment by ciaoben** [comment]
Why close? I am on the last `recharts`version, and in the chart of the first post of this issue, if I had a `dataKey="value"`, it shows the chart but onMouseEnter does not work, as @ninahaack told
