### ISSUE TITLE
Change label font color

### ISSUE THREAD

**Issue by sun2rise** [recharts/recharts#720]
I simply want to change the color of the text in the label but i don't know with property to use..

for example if I want to use a white color for the font in the label I am trying this:

```
const whiteLabel = ({ x, y, stroke, value }) => {
  return (
    <div style={{ color: '#FFFFFF' }}>
      <text x={x} y={y} dy={-4} fill={stroke} fontSize={10} textAnchor="middle">{value}</text>);
    </div>
  );
};
```

which is WRONG..

How to fix this?

Thanks, Alessandro

**Comment by xile611** [comment]
@sun2rise Use svg nodes not html nodes.

**Comment by santoshmmt** [comment]
Can someone explain with example

**Comment by jayqui-omada** [comment]
Agreed, @xile611's answer is curt and opaque. Can you please elaborate or provide more context?

**Comment by peterbartos** [comment]
The key is not to use `color` style but `fill` style. E.g.:

    <Label angle={270} position='insideLeft' offset={10}
        value=" TA / Pouls"
        style={{ textAnchor: 'middle', fontSize: '80%', fill: 'rgba(0, 0, 0, 0.87)' }}>

**Comment by phonnz** [comment]
I had the same problem trying to change the color of a reference line and I found two ways to solve it 

Simplest:
Importing Label component and passing the component as param to label. 
Ex.
`
<ReferenceLine x='3/22/20' stroke="red" label={<Label value="FASE II MX" fill={'white'} /> } style={{fill: 'white'}} />
`

**Comment by dionysis9901** [comment]
> The key is not to use `color` style but `fill` style. E.g.:
> 
> ```
> <Label angle={270} position='insideLeft' offset={10}
>     value=" TA / Pouls"
>     style={{ textAnchor: 'middle', fontSize: '80%', fill: 'rgba(0, 0, 0, 0.87)' }}>
> ```

Not working for me

**Comment by Mudassar045** [comment]
> > The key is not to use `color` style but `fill` style. E.g.:
> > ```
> > <Label angle={270} position='insideLeft' offset={10}
> >     value=" TA / Pouls"
> >     style={{ textAnchor: 'middle', fontSize: '80%', fill: 'rgba(0, 0, 0, 0.87)' }}>
> > ```
> 
> Not working for me

Worked for me! just set `fill="#color"`

**Comment by jayqui-omada** [comment]
Looking at the [docs for the Label component](https://recharts.org/en-US/api/Label), this feature does not appear in the documentation. Do folks know why it is not? Should it be?

**Comment by 9alex12** [comment]
> > > The key is not to use `color` style but `fill` style. E.g.:
> > > ```
> > > <Label angle={270} position='insideLeft' offset={10}
> > >     value=" TA / Pouls"
> > >     style={{ textAnchor: 'middle', fontSize: '80%', fill: 'rgba(0, 0, 0, 0.87)' }}>
> > > ```
> > 
> > 
> > Not working for me
> 
> Worked for me! just set `fill="#color"`

Worked for me `style={{fill: 'white'}}`
