### ISSUE TITLE
StackedBarChart label with sum from stacks

### ISSUE THREAD

**Issue by sun2rise** [recharts/recharts#721]
Hi, I am looking at the [StackedBarChart example](http://recharts.org/#/en-US/examples/StackedBarChart) but I need to write the total value from the stacks above each bar.
Like using a common label on the higher part of the chart.
How can I accomplish this?

Thanks,
Alessandro

**Comment by xile611** [comment]
@sun2rise 

You can use new component `LabelList` in 1.0.0 +;

[Demo](http://jsfiddle.net/wbyphjLw/)
