### ISSUE TITLE
None of the pie charts are working on the homepage

### ISSUE THREAD

**Issue by oliverwatkins** [recharts/recharts#723]

**Comment by jpdevries** [comment]
Possibly related to https://github.com/recharts/recharts/issues/717

**Comment by oliverwatkins** [comment]
This is extremely dissapointing. Version "1.0.0-alpha.0" should not have been released as the latest release if the entire pie charts do not work. Which version should we switch down to to get pie charts working again?

**Comment by xile611** [comment]
Fixed in 1.0.0-alpha.1.

**Comment by oliverwatkins** [comment]
yay! :)
