### ISSUE TITLE
ResponsiveContainer warning broken in test environment

### ISSUE THREAD

**Issue by YassineA** [recharts/recharts#727]
## Do you want to request a feature or report a bug?
Bug report

## What is the current behavior?
Even if a proper size is defined in the ResponsiveContainer, the ResponsiveContainer component will log a warning in tests thinking the calculated size is 0 while displaying the right values: 
Example for minWidth(200) & minHeight(100):
```
WARN: 'The width(0) and height(0) of chart should be greater than 0,
       please check the style of container, or the props width(100%) and height(100%),
       or add a minWidth(200) or minHeight(100) or use aspect(undefined) to control the
       height and width.'
```

[The calculatedWidth / calculatedHeight in ResponsiveContainer don't take the minWidth & minHeight into account.](https://github.com/recharts/recharts/blob/ed88040d5a81597095728898576e826940db67ee/src/component/ResponsiveContainer.js#L99)

## steps to reproduce:
- clone recharts repo
- run `npm run test`
- test is passing but still displaying the warning

## What is the expected behavior?
No warning when the right value is passed. Even when a minWidth / minHeight / aspect is passed, the calculated width or height is still 0. It renders properly in the browser, this only happens in tests.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Tested on 1.0.0-alpha.0, on macOS 10.12.4 running tests with Mocha & Enzyme. Same thing with version 0.22.1.

**Comment by Viral-Inc** [comment]
+1

**Comment by morsh** [comment]
This didn't do the work for me since both containerWidth & Height remained 0.
I used the following mitigation to solve this issue while testing with enzyme:

```
    let containerProps = {};
    if ('a case where I know this will happen') {
      containerProps['width'] = 100; // some default values
      containerProps['aspect'] = 1;
    }

    return (
      <ResponsiveContainer {...containerProps}>
        {children}
      </ResponsiveContainer>
    );
  }
```

This if not optimal, but it's a quick mitigation.

**Comment by AntonioRedondo** [comment]
Although @mogavin states this is fixed on https://github.com/recharts/recharts/pull/762 I just came across with this `withd=0` and `height=0` behaviour when using Recharts 1.4.1 `ResponsiveContainer` on tests. @morsh suggestion works but I don't think is a definitive solution.

**Comment by kodermax** [comment]
How to get rid of the warning?

**Comment by anujparikh** [comment]
same with me, whenever I am using Responsive Container. I am getting same error while unit testing the code

**Comment by sli** [comment]
Yep, I am also still encountering this warning on 1.6.2.

**Comment by kennblvnp** [comment]
still receiving it as well...

**Comment by sraisty1c** [comment]
also receiving this warning with 2.0.0-beta.1

**Comment by brentwashburne** [comment]
The `renderChart()` function in lib/component/ResponsiveContainer.js (recharts@2.0.0-beta.1) ignores the `minWidth` and `minHeight` props when determining `calculatedWidth` and `calculatedHeight`.  This causes the warning message to appear when rendering a `<ResponsiveContainer>` outside of a browser (in a test case).

Strangely, it uses a `maxHeight` prop which is not in the documentation.

**Comment by gugiserman** [comment]
This is what I did in `jest.setup.js` to mitigate the issue for now:

```js
const MockResponsiveContainer = props => <div {...props} />

jest.mock('recharts', () => ({
  ...jest.requireActual('recharts'),
  ResponsiveContainer: MockResponsiveContainer,
}))
```

**Comment by olelivalife** [comment]
Is this being fixed in v2? I didn't found a solution for ignoring the warning yet...

**Comment by pankajsanam** [comment]
> This is what I did in `jest.setup.js` to mitigate the issue for now:
> 
> ```js
> const MockResponsiveContainer = props => <div {...props} />
> 
> jest.mock('recharts', () => ({
>   ...jest.requireActual('recharts'),
>   ResponsiveContainer: MockResponsiveContainer,
> }))
> ```

Unfortunately, it's not working on v2.0.0

**Comment by gilamran** [comment]
A fast solution would be to define some mock value for the `clientWidth` and `clientHeight` on the `beforeAll`

```
beforeAll(() => {
  jest.spyOn(HTMLElement.prototype, 'clientHeight', 'get').mockReturnValue(100);
  jest.spyOn(HTMLElement.prototype, 'clientWidth', 'get').mockReturnValue(100);
});

**Comment by Harukisatoh** [comment]
> This is what I did in `jest.setup.js` to mitigate the issue for now:
> 
> ```js
> const MockResponsiveContainer = props => <div {...props} />
> 
> jest.mock('recharts', () => ({
>   ...jest.requireActual('recharts'),
>   ResponsiveContainer: MockResponsiveContainer,
> }))
> ```

That works, thanks!

**Comment by kpldvnpne** [comment]
> A fast solution would be to define some mock value for the `clientWidth` and `clientHeight` on the `beforeAll`
> 
> ```
> beforeAll(() => {
>   jest.spyOn(HTMLElement.prototype, 'clientHeight', 'get').mockReturnValue(100);
>   jest.spyOn(HTMLElement.prototype, 'clientWidth', 'get').mockReturnValue(100);
> });
> ```

This is not working for me

**Comment by hshoja** [comment]
> This is what I did in `jest.setup.js` to mitigate the issue for now:
> 
> ```js
> const MockResponsiveContainer = props => <div {...props} />
> 
> jest.mock('recharts', () => ({
>   ...jest.requireActual('recharts'),
>   ResponsiveContainer: MockResponsiveContainer,
> }))
> ```

it worked like this for me in React 18 and Testing-library/react 13

```
jest.mock('recharts', () => ({
  ...jest.requireActual('recharts'),
  ResponsiveContainer: props => <div {...props} />,
}))
```

**Comment by Avichai997** [comment]
> Reference in

works!

**Comment by nicolasschabram** [comment]
I had some trouble with the solutions above. I managed to make it work with the following mock:

```js
// /__mocks__/recharts.js

import { Children, cloneElement } from "react";

export function ResponsiveContainer(props) {
  return (
    <div>
      {Children.map(props.children, (child) =>
        cloneElement(child, { width: 100, height: 100 })
      )}
    </div>
  );
}

export * from "recharts";
```

**Comment by marilari88** [comment]
If anyone is interested in a Vitest solution
```javascript
  vi.mock('recharts', async (importOriginal) => {
    const originalModule = (await importOriginal()) as Record<string, unknown>
    return {
      ...originalModule,
      ResponsiveContainer: () => createElement('div'),
    }
  })

```

**Comment by vilelalabs** [comment]
> This didn't do the work for me since both containerWidth & Height remained 0. I used the following mitigation to solve this issue while testing with enzyme:
> 
> ```
>     let containerProps = {};
>     if ('a case where I know this will happen') {
>       containerProps['width'] = 100; // some default values
>       containerProps['aspect'] = 1;
>     }
> 
>     return (
>       <ResponsiveContainer {...containerProps}>
>         {children}
>       </ResponsiveContainer>
>     );
>   }
> ```
> 
> This if not optimal, but it's a quick mitigation.

Only that solved for me (using 2.12.5 under react 18 on NextJS 14.1.4 and node 21.5.0)

**Comment by ckifer** [comment]
ResponsiveContainer also now has an initialDimentions prop - you can use that and it won't affect anything except for cases like this (instead of starting at zero you start at whatever a good default is)

**Comment by bvandrc** [comment]
Surprised this ticket is from 2017 and still not resolved...

**Comment by ckifer** [comment]
This is closed and existed before the current maintainers, I have never seen this issue before. I think we have plans to just remove the warnings in general because we get more complaints about them than they are useful.

**Comment by bvandrc** [comment]
@ckifer good to know! Just wanted to bump this since it's still relevant is all. The solutions here have worked to fix it so no rush. Even just making it a console warning instead of throwing an error would be fine!

**Comment by ckifer** [comment]
It's just a console warning as far as I understand? It throws an error?

**Comment by bvandrc** [comment]
@ckifer my bad, it is a console warning. Lapsed that our test setup errors on console warnings.

**Comment by PavelVanecek** [comment]
My plan is to move all warnings to the devtools package and expose as a prop so that people can choose if they want to throw or log or whatnot.

**Comment by dawsonbooth** [comment]
FWIW for anyone still using these workarounds you can use the original `ResponsiveContainer` from Recharts if you mock as follows:

```tsx
// or jest
vi.mock('recharts', async importOriginal => {
  const originalModule = await importOriginal<typeof import('recharts')>()
  return {
    ...originalModule,
    ResponsiveContainer: (
      props: React.ComponentProps<typeof originalModule.ResponsiveContainer>,
    ) => <originalModule.ResponsiveContainer width="100%" height={300} {...props} />,
  }
})

// ResizeObserverMock not needed if using Vitest's browser mode
const ResizeObserverMock = vi.fn(function () {
  return {
    observe: vi.fn(),
    unobserve: vi.fn(),
    disconnect: vi.fn(),
  }
})

vi.stubGlobal('ResizeObserver', ResizeObserverMock)

```
