### ISSUE TITLE
ReferenceLine renders label in center of chart

### ISSUE THREAD

**Issue by mrwillis** [recharts/recharts#730]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
ReferenceLine's label is rendering in the center of the chart, as opposed to above it or beside it.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/9y45ut13/).
See example on the official site: [http://recharts.org/#/en-US/examples/LineChartWithReferenceLines](url)

## What is the expected behavior?
ReferenceLine's label should render close to the ReferenceLine itself

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Latest version (v1.0.0-alpha.0)

I see in the example it is busted, but on this link it seems to be fine: [http://recharts.org/#/en-US/api/ReferenceLine](url)

**Comment by flushentitypacket** [comment]
This seems to be an issue with the X and YAxis components as well.

**Comment by ckumaresanmba** [comment]
Please check this link. Let me know how to resolve it.
http://jsfiddle.net/ckumaresanmba/ar5j5Lye/

**Comment by botaifilip** [comment]
Have the same problem too

**Comment by fengshuo** [comment]
same issue

**Comment by tuala** [comment]
I can confirm this is a problem in Reference Line (using Responsive Container if that matters).
The label is not inheriting the coordinates from the line or something so it ends up in the middle of the chart.

**Comment by xile611** [comment]
You can try the props `position` of label.
```jsx
<ReferenceLine x="Page C" stroke="red" label={{ position: 'top',  value: 'Max PV PAGE', fill: 'red', fontSize: 14 }}/>
```
[Doc of Label](http://recharts.org/#/en-US/api/Label).

**Comment by madanaya** [comment]
I was trying to align label to right of the reference line. I got it working by making label child component of referenceline.

<ReferenceLine  y={4700} stroke="black" strokeWidth={2}>
        <Label value="R-bar" position="insideRight"/>
</ReferenceLine>

**Comment by kerenren** [comment]
As of 2023, the label can be a react element type, so I passed the `Label` element inside label and it works: 
`<ReferenceLine  y={4700} stroke="black" strokeWidth={2} label={<Label value="R-bar" position="insideRight"/> } />  `
