### ISSUE TITLE
Not all ticks showing in PolarRadiusAxis

### ISSUE THREAD

**Issue by kresten8** [recharts/recharts#733]
When I want to show a Radar chart with a custom domain, e.g. <PolarRadiusAxis domain={[1, 5]} /> it only shows the first and last tick (1 and 5), while all the ticks need to be visible.
When I leave the domain out, it does show the ticks, but the domain is needed to have different radar charts to all have the same scale.

`<RadarChart height={300} width={300} data={data}>
                        {series}
                        <PolarGrid />
                        <Legend />
                        <PolarRadiusAxis domain={[1, 5]} />
                        <PolarAngleAxis dataKey="label" orient="inner"/>
                    </RadarChart>`

**Comment by kaizoku-kenshin** [comment]
Can you provide a more solid example?
