### ISSUE TITLE
the tooltip is not good like 0.22.4

### ISSUE THREAD

**Issue by MeloDai** [recharts/recharts#734]
i use the 1.0.0-alpha.1, and when i draw the scatter chart, the tooltip is not working well.

when mouseenter the dot, the tooltip is shown, and it also shows two lines to point the dot, 
but when mouse touches these lines and still inside the dot, the tooltip disappears
i think it is a small bug

**Comment by xile611** [comment]
@MeloDai Change the order or <Tooltip /> and <Scatter /> change resolve this, all the components are rendered in order now.
