### ISSUE TITLE
CSP problems on string length calculation

### ISSUE THREAD

**Issue by maxvektor** [recharts/recharts#735]
I want to report a bug:
`setAttribute('style'...)` breaks a CSP when using `style-src: self` policy .
https://github.com/recharts/recharts/blob/7cb33048cc795810b4cba2836def37d86074af36/src/util/DOMUtils.js#L70
This place causes multiple errors in console when script is used with CSP policy that forbids inline styling.
Unfortunately there is no way to show it on jsfiddle. As I understand they don't ban inline styling and neither does your demo page.
I think there is a simple way to fix it:
https://stackoverflow.com/questions/24713440/banned-inline-style-csp-and-dynamic-positioning-of-html-elements/29089970#29089970
The only problem I see is to deal with caching.

**Comment by jordanch** [comment]
Any movement on this? We need to adhere to the same CSP policy and have adopted recharts.

**Comment by whphhg** [comment]
I'm running into the same `inline-src` issue while using CSP.

**Comment by adrianriddle** [comment]
Any movement on this issue?
