### ISSUE TITLE
Warning: Failed prop type: Invalid prop `data` of type `object` supplied to `LineChart`, expected an array.    

### ISSUE THREAD

**Issue by greaveselliott** [recharts/recharts#739]
Following the example or recharts.org, I'm passing an array of objects to a LineChart component. This seems to work visually, but throws the following error in the console.
`Warning: Failed prop type: Invalid prop `data` of type `object` supplied to `LineChart`, expected an array.  `  

Is this working as intended?

**Comment by xile611** [comment]
The propType of props `data` in LineChart is `PropTypes.arrayOf(PropTypes.object)`.

**Comment by xnog** [comment]
Sorry, didn't understand the reply. I am facing the same error in console. What should I do to avoid this?

**Comment by thekeenant** [comment]
The `data` property must be an array of objects, like shown in the examples:

```javascript
const data = [
      {name: 'Page A', uv: 4000, pv: 2400, amt: 2400},
      {name: 'Page B', uv: 3000, pv: 1398, amt: 2210},
      {name: 'Page C', uv: 2000, pv: 9800, amt: 2290},
      {name: 'Page D', uv: 2780, pv: 3908, amt: 2000},
      {name: 'Page E', uv: 1890, pv: 4800, amt: 2181},
      {name: 'Page F', uv: 2390, pv: 3800, amt: 2500},
      {name: 'Page G', uv: 3490, pv: 4300, amt: 2100},
];
...
<BarChart width={600} height={300} data={data}>
  ....
```

Check what type your `data` property is.

**Comment by xnog** [comment]
It's a list, but i always get the error in the console but works. Maybe is something with Mobx.

**Comment by frjtrifork** [comment]
@xnog You need to invoke .slice() on the observable mobx array. Internally an observable array in mobx is actually an object - to get the raw array you should create a shallow copy by using .slice. 
See [https://mobx.js.org/refguide/array.html#observable-arrays](https://mobx.js.org/refguide/array.html#observable-arrays)

> Bear in mind however that Array.isArray(observable([])) will yield false, so whenever you need to pass an observable array to an external library, it is a good idea to create a shallow copy before passing it to other libraries or built-in functions (which is good practice anyway) by using array.slice(). In other words, Array.isArray(observable([]).slice()) will yield true.

**Comment by yamazed** [comment]
Just add a slice() call to your data as in:

data: {this.props.myData.myarray.slice()}

**Comment by UmerMo** [comment]
Try this `PropTypes.arrayOrObservableArrayOf(shape({})).isRequired`
