### ISSUE TITLE
Failed prop type: The prop `dataKey` is marked as required in `Pie`, but its value is `undefined`.     in Pie (created by PieChartContainer)

### ISSUE THREAD

**Issue by greaveselliott** [recharts/recharts#740]
My current implementation of the PieChart component works, but throws the following error in the console.

> Failed prop type: The prop `dataKey` is marked as required in `Pie`, but its value is `undefined`.     in Pie (created by PieChartContainer)

I've bumped my Recharts version to the latest build of Recharts 1.0.0.alpha.1 which allowed the Pie chart to render, but didn't suppress the error. 

Is this working as intended?

See a snippet of my implementation below...

    ```
        <PieChart onMouseEnter={this.onPieEnter}>
              <Pie data={this.props.data} labelLine={false} label={renderCustomizedLabel} innerRadius={60} outerRadius={120} fill="#8884d8">
                { this.props.data.map((entry, index) => <Cell key={index} fill={this.COLORS[index % this.COLORS.length]}/>) }
              </Pie>
              <Tooltip/>
              <Legend />
            </PieChart>
```

**Comment by cj4luv** [comment]
you should  add prop 'dataKey' in 'Pie' component.

example

        <PieChart width={800} height={400} >
          <Pie dataKey="value" data={data} cx={250} cy={200} innerRadius={112} outerRadius={122} >
            {
              data.map((entry, index) => <Cell key={index} fill={COLORS[index % COLORS.length]}/>)
            }
          </Pie>
          <Tooltip/>
        </PieChart>

**Comment by chrisjpatty** [comment]
This still doesn't work for me. The official documentation says to add `nameKey` and `valueKey` to the `Pie` component, but doing so has no effect. When I put my value data key under the `dataKey` prop it still does not render. Here's my code:

```
<PieChart height={250}>
    <Pie data={data} cx="50%" cy="50%" outerRadius={50} fill="#6179b6" dataKey="value" />
    <Tooltip />
  </PieChart>
```
```
const data = [{ name: 'Last 30', value: 2200 }, { name: 'Last 7', value: 977 }, { name: 'Today', value: 625 }]

**Comment by jampy** [comment]
Please note that as of today, the Recharts website doesn't mention neither `dataKey` nor `nameKey`/`valueKey`:

![image](https://user-images.githubusercontent.com/820758/28491721-2c0d2562-6ef6-11e7-9d70-d7091c395637.png)

![image](https://user-images.githubusercontent.com/820758/28491725-4bd5676a-6ef6-11e7-8152-846873df21d4.png)

**Comment by chuyinweilai** [comment]
It looks like it's caused by the label `ResponsiveContainer`.
I have a same problem, then I remove `ResponsiveContainer`,it works.
Your can have a try.

**Comment by chrisjpatty** [comment]
@chuyinweilai That did fix my problem, thanks!

**Comment by zwy706670363** [comment]
@chrisjpatty could you tell how to fix the problem, I met the same trouble。
`render() {
        return (
            <div className="chart piechart">
                <PieChart width={800} height={400}>
                    <Pie data={data01} cx={200} cy={200} outerRadius={60} fill="#8884d8"/>
                    <Pie data={data02} cx={200} cy={200} innerRadius={70} outerRadius={90} fill="#82ca9d" label/>
                </PieChart>
            </div>
        );
    }`

**Comment by debovis** [comment]
@xile611 

adding prop 'dataKey'='value in 'Pie' component solved the problem, please update the following example. Thanks

http://recharts.org/#/en-US/examples/CustomActiveShapePieChart

**Comment by xile611** [comment]
@debovis Get it! Thank you!

**Comment by lockjohn** [comment]
I'm having a similar problem, with my console error telling me that dataKey props is required but is undefined, however I can see that data is defined in my debugger at my data={data} entry to the Pie component. However when I check the element with the Chrome React Extension it shows the right number of objects in my data array but they are empty? (see screen shot)

```import React from 'react';
import { ResponsiveContainer, PieChart, Pie } from 'recharts';
import { ClipLoader } from "react-spinners";


class DonutChart extends React.Component {
    constructor() {
        super ()
    }

    componentDidMount() {
        this.props.getExchanges("BTC", "USD");
        this.props.getTotal("USD");
    }

    renderChart (data) {
        if (!data) {
                return (
                    <div style={{ height: 160, marginLeft: 400, marginTop: 80 }}>
                        <ClipLoader
                            className='spinner'
                            sizeUnit={"px"}
                            size={70}
                            color={'rgb(155, 166, 178)'}
                        />
                    </div>
                )
        } else {
            // console.log(data);
            // debugger;
        return (
        
            <ResponsiveContainer width={800} height={400}>
                <PieChart >
              <Pie 
              data={data} 
              datakey="volume24hTo"
              nameKey="exchange" 
              cx="50%" cy="50%" 
              innerRadius={40} outerRadius={80} 
              fill="#82ca9d" 
               />
            </PieChart>
        </ResponsiveContainer>
        )
         
        }
    }

    render() {
        const data = this.props.chartData;
        return (
            <div>
                <p className="blockquote">Hey this is bootstrap styling in Donut Area</p>
                {this.renderChart(data)}
            </div>
        )
    }```

**Comment by lockjohn** [comment]
![screen shot 2018-08-28 at 8 45 24 pm](https://user-images.githubusercontent.com/39103639/44764304-e92b9800-ab03-11e8-837a-ae4da38766c5.png)

**Comment by vtarelkin** [comment]
As for 2020 there is still no updates in examples

**Comment by devnoot** [comment]
@chuyinweilai This fixed my issue, thanks!

3 years later and the docs still do not mention `dataKey`
