### ISSUE TITLE
BUG : Using customized Axis labels does not work

### ISSUE THREAD

**Issue by oliverwatkins** [recharts/recharts#741]
I have the following code in my chart :

`<XAxis label={<Hello />} />`

My customized label is this :  

    var Hello = React.createClass({
      render: function() {
        return <div>Hello!</div>;
      }
    });

When I run this code the x-axis shows with the ticks and tick values, but there is no x-axis label.

If I instead use a plain string :  

 `<XAxis label="Hello" />`

the x-axis label shows but it overlaps the tick values.

I just want an x-axis label that does not overlap the ticks.

**Comment by xenovon** [comment]
Same Issues here

**Comment by mrdannael** [comment]
Same here.

**Comment by mjenczmyk** [comment]
Doesn't work for me either.

**Comment by rafalkowalski** [comment]
Same here.

**Comment by perduta** [comment]
Works for me.

**Comment by perduta** [comment]
I have exact same issue.

**Comment by xile611** [comment]
<img width="807" alt="wangwang20170710164104" src="https://user-images.githubusercontent.com/6111424/28009695-e89f101c-658e-11e7-84e2-6a182e7da026.png">


The component `<Hello />` has been rendered, but the `div` is rendered is svg, so the `Hello` is not visible. 

Please use svg elements instead, or just use `label="hello"`.

**Comment by mjenczmyk** [comment]
@xile611 Thanks - you seem to be right, that solves the problem.
