### ISSUE TITLE
Tooltip under chart

### ISSUE THREAD

**Issue by edbond** [recharts/recharts#742]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
Tooltip render under chart

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/9y45ut13/).
see http://imgur.com/GsbSTEQ

## What is the expected behavior?
Tooltip over bar chart

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Latest version recharts "0.21.2-0", mac, chrome

**Comment by xile611** [comment]
@edbond  Can you create a jsfiddle demo to reproduce your problem.

**Comment by edbond** [comment]
Sorry jsfiddle template doesn't work for me, Chrome + Mac.
There are two components on image (two table rows) with bar chart and overlap occurs as seen on image.
If there is working template I'll make a demo

**Comment by xile611** [comment]
@edbond  Checkout this [jsfiddle template](http://jsfiddle.net/x1yoboc7/612)

**Comment by edbond** [comment]
Thanks a lot, here is a demo:
https://jsfiddle.net/x1yoboc7/818/

![image](https://user-images.githubusercontent.com/1044/28018169-dfe946ea-6584-11e7-943d-785b55c74c0b.png)

This happens only for small height. If you hover top chart you'll the tooltip is under second chart.

Thanks!

**Comment by xile611** [comment]
@edbond Specify the z-index of '.recharts-tooltip-wrapper':

```css
.recharts-tooltip-wrapper {
  z-index: 100;
}
```
