### ISSUE TITLE
ticks for YAxis not working (partially missing) except for v0.12.7

### ISSUE THREAD

**Issue by kimjuny** [recharts/recharts#745]
Reproduce Demo:

https://codepen.io/kimjuny90/pen/WOOpgN

This is a working demo (for Rechart version 0.12.7). You can try any other version of Recharts(i.e. 0.19.0 or else), ticks for YAxis will be partially missing.

This is what is expected, all 6 ticks showed up. (v0.12.7)

![expected](http://imgur.com/CMZ9EFq.png)

This is a bug maybe, only 4 ticks left? (any version except v0.12.7)

![bug](http://imgur.com/wOFmPz6.png)

**Comment by Shadowman4205** [comment]
I just calculate manually xTicks and yTicks
<XAxis dataKey="test1" allowDecimals={false} ticks={xTicks} type="number" domain={['dataMin', 'auto']} />
<YAxis ticks={yTicks} domain={[0, _.max(yTicks)]} />

It is still does not  give exactly what i want for xTicks but its ok for now. If you will find any good solution share it please.

**Comment by kimjuny** [comment]
@Shadowman4205 above example is also a manually calculated example. 6 ticks were explicitly set to YAxis but only 4 are shown.

**Comment by dpehrson** [comment]
I can also confirm this behavior. On 1.0.0-alpha.2 and on a line chart with:

`<XAxis ... ticks={[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]}/>` tick number 9 is missing from both the  `XAxis` and the `CartesianGrid`

**Comment by shahchaitanya** [comment]
Hi @dpehrson. I'm facing the same problem. Can you tell me how you solve it?

**Comment by kennblvnp** [comment]
I am facing the same problem. How do we fix this?

**Comment by ohadco** [comment]
Same thing happend to me, and adding `interval={0}` solved the problem.
```
<YAxis
    ticks={[...]}
    interval={0}
/>
```

**Comment by olelivalife** [comment]
@ohadco no I think adding ticks works, not interval...

**Comment by ButcherV** [comment]
@xile611 why you closed this issue?

**Comment by mmplanet** [comment]
@xile611 this is still an issue. The "interval" property is ignored.

**Comment by vtarelkin** [comment]
@xile611 still an issue in 2021
