### ISSUE TITLE
BarChart layout vertical doesn't seem to be working

### ISSUE THREAD

**Issue by husek** [recharts/recharts#746]
It only renders the first bar, check it out:
http://jsfiddle.net/aougnz8t/38/

**Comment by Heedster** [comment]
You have not provided the axises, which provides the dataKey="name" to an axis and overrides the type of the axis (by default xaxis is category and yaxis is number which needs to be inverted)
`<XAxis type="number" />
 <YAxis dataKey="name" type="category"/>`

**Comment by dungnv-vieted** [comment]
https://jsfiddle.net/vuh6cLyz/ need layout=vertical
