### ISSUE TITLE
LineChart -- Null points are being connected after a resize, even when connectNulls is false

### ISSUE THREAD

**Issue by dsifford** [recharts/recharts#748]
## Do you want to request a feature or report a bug?

Bug

## What is the current behavior?

1. Create a valid LineChart (with nulls) in a ResponsiveContainer.
2. Observe that the null points are not connected.
3. Resize the container.
4. Observe that the nulls are now being classified as 0 and are connected.

## What is the expected behavior?

Nulls remain non-connected after the resize.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Current version: latest.
Did it work previously? I'm not sure. It likely did not.

**Comment by Heedster** [comment]
@dsifford Can you share some code? I use a responsive container and draw a lot of charts which has nulls, this has never happened to me.

**Comment by dsifford** [comment]
@Heedster Sure...

Here's the code: https://github.com/aliemteam/ALiEM/blob/master/aliem/lib/js/social-media-index/smi-plot.tsx

Here it is live: https://aliem.com/social-media-index

To trigger the issue, load it on mobile in portrait mode, then rotate to landscape and notice the lines.

**Comment by al3x-huang** [comment]
I have this issue as well.

**Comment by al3x-huang** [comment]
I notice that both our graphs misbehave the same way: the null point seems to be plotted somewhere off the top/bottom of the graph then reconnected.

**Comment by hklebs-cs** [comment]
I have the issue @al3x-huang describes, I have null points on the graph with connectNulls="true" and when resizing they graph off the top of the plot

**Comment by al3x-huang** [comment]
Has anyone been able to find workarounds for this?
