### ISSUE TITLE
Duplicate Data Keys along main axis cause a crash

### ISSUE THREAD

**Issue by warbrett** [recharts/recharts#75]
Ideally I think both should be rendered side by side. I've tried digging into this to see if I could provide a fix but it looks like it's touching several parts of the library.

To replicate the error change line:
https://github.com/recharts/recharts/blob/master/demo/component/BarChart.js#L10
to:
```
{ name: 'food', uv: 3300, pv: 4567, amt: 6500 }
```
and try and view the barchart demo.

I'd be more than happy to try and put in the work here if someone could point me in the right direction of which pieces would need to be modified.

**Comment by xile611** [comment]
This problem has been fixed in version 0.10.0. And this problem was caused because `scalePoint` in d3-scale eliminate duplicate data internally.
But I am curious how can a list data has two duplicate element which have different values. Can you show me an example?

**Comment by warbrett** [comment]
Wow that was fast!  Thank you for all of your hard work! 👍 

In my case I was abusing the charts a little bit, using the dataKeys on a horizontal barchart to be the values so it was a little easier to read, and then color coding the bars for identification below them if that makes sense.
