### ISSUE TITLE
PieChart with multiple Pies doesn't show custom labels / animation

### ISSUE THREAD

**Issue by tonoslav** [recharts/recharts#750]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
When I create **PieChart** with one **Pie** with custom labels everything works great (animation, labels)
But when I add another Pie to the same **PieChart** , there is no animation and no labels

**Working example**
![image](https://user-images.githubusercontent.com/3399021/27537077-7507af00-5a72-11e7-8656-0fd21f1a5577.png)

**Multiple Pies**
![image](https://user-images.githubusercontent.com/3399021/27537091-83bf71cc-5a72-11e7-857b-d7339033d383.png)

**Code**
>         import { PieChart as Chart, Pie, Cell } from 'recharts'
....
>         return isLoading ? null : (
>             <Chart width={width} height={width/2.5}>
>                 {_.map(pies , (pie, index) => (
>                     <Pie
>                         cx={15 + (index * 33) + '%'} 
>                         cy={150} 
>                         data={pie.data} 
>                         dataKey="value"
>                         isAnimationActive={true}
>                         key={pie.type}
>                         labelLine={true}
>                         label={this._label}
>                         outerRadius="50%"
>                     >
>                         {_.map(pie.products, product => (
>                             <Cell 
>                                 key={'t' + pie.type + 'p' + product} 
>                                 fill={this._makeColor('t' + pie.type + 'p' + product)}
>                             />
>                         ))}
>                     </Pie>
>                 ))}
>             </Chart>
>         )

In second example **label** function is not even executed

**Data example**
https://pastebin.com/RRSx9G3V

## What is the expected behavior?
To show labels and animation too with multiple Pies

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts: 1.0.0-alpha.1
Multiple browsers tried on Windows 10

**Comment by xile611** [comment]
@tonoslav  It works well in [this demo](http://jsfiddle.net/0u7kwpvp/). You can create a jsiddle demo to reproduce your problem.

**Comment by AlexMold** [comment]
@tonoslav Doesn't work and for me, but only if a Pie have descendants a Cell

**Comment by tonoslav** [comment]
@xile611 as @AlexMold said, I need that Cells too for coloring sectors

**Comment by mqtsuo02** [comment]
I had a similar problem in storybook's view.
But in normal build environment, the label is displayed.
so, the problem may be in the difference of build environment.

**Comment by AlexMiroshnikov** [comment]
Potentially can be related to #1083 . In order to confirm it, once can try the given example with `isAnimationActive={false}` prop and check if the labels still fail.
