### ISSUE TITLE
how can I add string to Pie Chart Tooltip

### ISSUE THREAD

**Issue by nuugut** [recharts/recharts#751]
my data is look like this
{name: "xxxx", percentage:30}
and I use nameKey="name" and dataKey="percentage"

and tooltip in pie chart show "xxxx : 30"

I want to add % to the Tooltip so it should be "xxxx : 30%"

how can I do that?

Thanks in advance

**Comment by xile611** [comment]
@nuugut Use the props `formatter` of [`Tooltip`](http://recharts.org/#/en-US/api/Tooltip);

```jsx
<Tooltip formatter={someFormatterFunction} />
```

**Comment by nuugut** [comment]
@xile611 

do you have any example of {someFormatterFunction}?

Thanks

**Comment by braiandickson** [comment]
@nuugut 

I have this simple example of the formatter:

`const formatTooltip = value => `${value} ${unit}`;`

Then into my chart component:

`<Tooltip formatter={formatTooltip} ... />`

(I used the "..." for the other props)

**Comment by zzgab** [comment]
Hi @gutakk, did you manage to do it? I don't see how to pass a formatter function to a <Pie> component.
