### ISSUE TITLE
PieChart mouse events aren't getting the right args

### ISSUE THREAD

**Issue by fmauNeko** [recharts/recharts#752]
## Do you want to request a feature or report a bug?
Report a bug

## What is the current behavior?
Parameters passed to PieChart's onMouseEnter are wrong: data is null and index is undefined

## Demo
This official example which is broken with 1.0.0-alpha.x: http://jsfiddle.net/pwpLb0e7/

## What is the expected behavior?
Getting the informations about the event in data var, and the index of the hovered slice in the index var

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
I know that Recharts ^1.0.0-alpha.0 is affected in Chromium 59.0.3071.109 x64 on Linux, and that it was working as intended with Recharts 0.22.4

**Comment by RafaPolit** [comment]
I am experiencing the same issue.

Doing some reverse engineering, I was able to fix the behavior moving the function call inside the Pie element (not the PieChart), and changing the enter event to move (binding it to the element):
```
onMouseMove={this.onPieEnter.bind(this)}
```
This fixes the behavior, but it is not working on mobile devices.

**Comment by ZephD** [comment]
The problem with that fix is "move" is called all the time as the mouse moves around the chart segment, which may impact performance.

**Comment by RafaPolit** [comment]
Yes, yes, of course! I meant it as a temporal fix to get the intended result, not as a permanent solution, the bug still needs fixing!

**Comment by ZephD** [comment]
Ahh. "Workaround". :)
