### ISSUE TITLE
Gantt Chart / Timeline Chart

### ISSUE THREAD

**Issue by ZephD** [recharts/recharts#753]
I'm trying to get a vertical bar chart, where each bar (row) is made up of many separated bars (stacked).

Similar to 
https://i.stack.imgur.com/auKMw.png

Is this possible with Recharts?

**Comment by ZephD** [comment]
With Recharts BarChart, each "bar" must be a separate _key_ in the data object.
This means each object _must_ have the same number of bars.
What if this is not the case?

Ideally, Stacked Bars should use a (sorted) object/value array to stacked display bars, rather than separate keys (which, incidentally, could be in _any_ order).

**Comment by OlegBrony** [comment]
So... is it possible to draw some gantt chart with recharts?

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.

**Comment by Leonardofreua** [comment]
is it possible to draw some gantt chart with recharts?

**Comment by satheesh3** [comment]
I was able to achieve it using scatter chart and custom shape. Example here https://codesandbox.io/p/sandbox/scatter-chart-with-cells-forked-d3ndsv
