### ISSUE TITLE
Tooltip not showing upon tap on mobile devices.

### ISSUE THREAD

**Issue by RafaPolit** [recharts/recharts#754]
## Do you want to request a feature or report a bug?
Report a bug (or perhaps a feature request if this was not thought of upfront?)

## What is the current behavior?
Tooltip on bar chart not showing upon tap on mobile devices.

## If the current behavior is a bug, please provide the steps to reproduce:
Go to your own examples page:
http://recharts.org/#/en-US/examples/SimpleBarChart

Using a tablet or cell phone, tap on any of the columns.

## What is the expected behavior?
The tooltip should be shown upon tapping.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
V 1.0.0-alpha.1 on iPhone and iPad using iOS.  No idea if this was previously working.  I'm new to this repo.

Thanks very much.

**Comment by nathantn** [comment]
I submitted a PR (https://github.com/recharts/recharts/pull/755) that should fix this

**Comment by dsifford** [comment]
I tried your fix @nathantn and it doesn't seem to work for me so there might be some other issue as well.

Off the bat, I'm noticing that the `coordinates` prop is not respected ever if you set it. That's bothersome as well if not related to this issue.

**Comment by dsifford** [comment]
Update: I was able to get tooltip to render if I used `onClick` rather than `onTouchStart`. This works with or without @nathantn's fix.

**Comment by Hammarang** [comment]
I'm having the same issues with displaying tooltips as mentioned here. Maybe you could submit your fix in a pull request @dsifford? Thanks

**Comment by dsifford** [comment]
@Hammarang the tweak I mentioned isn't a codebase fix, it just involves attaching a different event handler to whatever it is that you want the tooltip to be displayed on...

In my case, it was a custom `Dot`..

So, all I did was this:

```jsx
// dot.js
export default class Dot extends React.PureComponent<any> {
    render() {
        const {
            cx,
            cy,
            opacity,
            id,
            fill,
            onMouseOver,
            onMouseOut,
            value,
        } = this.props;
        if (!value) return null;
        return (
            <circle
                onClick={onMouseOver}
                onMouseOver={onMouseOver}
                onMouseOut={onMouseOut}
                r={10}
                id={id}
                opacity={opacity}
                cx={cx}
                cy={cy}
                strokeWidth={3}
                stroke={fill}
                fill={fill}
            />
        );
    }
}
```
 
```jsx
// plot.js
import Dot from './dot';

export default class extends Component {
// constructor, handlers, etc ....
render() {
   return (
     // other stuff
     <Line
           type="linear"
           strokeWidth='3'
           activeDot={false}
           dot={
               <Dot
                 fill={c}
                 id={site}
                 onMouseOver={this.hover}
                 onMouseOut={this.resetActive}
               />
            }
     />
  )
}

**Comment by dylanitorium** [comment]
I encountered this issue and was attempting to debug it by capturing the click event from an AreaChart. I was able to tap to active a tooltip on mobile after I added _any_ onClick handler such as:

```js
 <AreaChart onClick={() => {}}>
  // axis, area, tooltip etc
 </AreaChart>
```

and it worked. ¯\_(ツ)_/¯

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
