### ISSUE TITLE
Adding custom tooltip/popup in pie or bar chart 

### ISSUE THREAD

**Issue by alexliu-github** [recharts/recharts#756]
I would like to add my own custom tooltip ( popup which a list of links or icons, so a user can click on it to perform some actions). This popup would show when a user hovers over the pie sector or bar in the chart. I wonder if anyone has done it or someone has any idea how to go about it? Thanks in advance.

**Comment by ZephD** [comment]
Does this help?
http://recharts.org/#/en-US/examples/CustomContentOfTooltip

**Comment by xile611** [comment]
@alexliu-github Use customized `content` of `Tooltip`.

**Comment by neomehta** [comment]
@alexliu-github Were you ever able to do it ?
I need the same for me. please let me know if there is any way, I have been looking at source codes and lots of things to accomplish, however its still not done.
