### ISSUE TITLE
Multi-colored fill for Area chart

### ISSUE THREAD

**Issue by hashwin** [recharts/recharts#757]
Hi, 
First off, awesome project. Love how seamless and reusable the components are.

I wanted to see if it was possible to shade _vertical_ sections of an area chart with different colors. Something like this:
![image](https://user-images.githubusercontent.com/406115/27671546-1e3045d8-5cb2-11e7-8e0f-fa771e4aa7c9.png)

I coudn't see anything similar in the examples. Any idea if this is possible?

**Comment by ZephD** [comment]
You would have to render each colour as a separate <Area/> inside <AreaChart/>

**Comment by xile611** [comment]
@hashwin [Here] is a workaround, use linear gradient.

**Comment by alexeikaratai** [comment]
@xile611 give me pls example, thx.

**Comment by jgentes** [comment]
Here's the example: http://recharts.org/api/#/en-US/api/AreaChart

**Comment by PierreAndreis** [comment]
@jgentes is there a way to use gradient fill with pies?

**Comment by jgentes** [comment]
@PierreAndreis I don't know.. maybe try the same approach for area?

```
<defs>
    <linearGradient id="colorUv" x1="0" y1="0" x2="0" y2="1">
      <stop offset="5%" stopColor="#8884d8" stopOpacity={0.8}/>
      <stop offset="95%" stopColor="#8884d8" stopOpacity={0}/>
    </linearGradient>
    <linearGradient id="colorPv" x1="0" y1="0" x2="0" y2="1">
      <stop offset="5%" stopColor="#82ca9d" stopOpacity={0.8}/>
      <stop offset="95%" stopColor="#82ca9d" stopOpacity={0}/>
    </linearGradient>
  </defs>
```

**Comment by PierreAndreis** [comment]
@jgentes got that working, using `fill={url(#colorPv)` props on `PieChart`.
It may be obvious, but not familiar with SVG so it took me some time.
Thanks!

**Comment by wohaoainidemeili** [comment]
I am curious about how you fixed the problem. Is here any example?

**Comment by Alphavader** [comment]
same here - any example to apply an gradient to the Pie would be awesome!

**Comment by prjanja** [comment]
For anyone struggling with linear gradient for pie chart, here is an example:
https://codesandbox.io/s/friendly-minsky-k1rje

**Comment by antondankov93** [comment]
> @hashwin [Here] is a workaround, use linear gradient.

Can you repeat the example link, please?

**Comment by kishankanugula** [comment]
So, Do we have any workarounds to individually color tiny parts of the area chart, or we cannot do it with recharts?
