### ISSUE TITLE
[Question] Tooltip to use name field, not array position

### ISSUE THREAD

**Issue by mjsevilla** [recharts/recharts#758]
## What is the current behavior?
The default tooltip is using the data point's array index as the name instead of the object's name field.

## What is the expected behavior?
I want the tooltip to use the data point's name as shown in the Recharts examples and API.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Rechart version: 1.0.0-alpha.1
Browser: Chrome
Not sure if it works in previous versions of Recharts.

## Code
`const deviceData = [
  {name: 'Misfit', amount: 75, fill: '#82ca9d'},
  {name: 'Samsung', amount: 96, fill: '#a4de6c'},
  {name: 'Other (not listed)', amount: 36, fill: '#d0ed57'},
  {name: 'Apple Watch', amount: 230, fill: '#83a6ed'},
  {name: 'Jawbone', amount: 125, fill: '#8dd1e1'},
  {name: 'Fitbit', amount: 200, fill: '#8884d8'},
];`

`   <PieChart width={800} height={400}>
      <Pie data={deviceData} dataKey="amount" cx={150} cy={110} innerRadius={50} outerRadius={80} label />
      <Legend iconSize={10} width={120} height={140} layout='vertical' verticalAlign='middle' align="right" />
      <Tooltip payload={deviceData} />
   </PieChart>`

**Comment by ZephD** [comment]
Checkout the formatter or labelFormatter props of the tooltip.

**Comment by mjsevilla** [comment]
It just says, "the formatter function of value in tooltip," and, "the formatter function of label in tooltip," respectively. The API doesn't explain how to use a lot of different functionality, yet the example show them being used :\

**Comment by ZephD** [comment]
Something like:
`formatter={index => data[index]}`
assuming the formatter receives the index, which by what you ask is the case.

**Comment by mjsevilla** [comment]
I don't know what the formatter is receiving. Using the default `<Tooltip />` results in the tooltip using the data array index as the name. Yet, the API examples are showing the tooltip using the correct name key from the data table. Also, that didn't work. Is there anywhere in the docs that explains how to use the Tooltip component?

**Comment by ZephD** [comment]
No more than http://recharts.org/#/en-US/examples/CustomContentOfTooltip

You can console log what the formatter gets.

`formatter={(a,b,c) => { console.log(a,b,c); }`

**Comment by mjsevilla** [comment]
Why did you close this @xile611? My issue still hasn't been fixed. Console logging what the formatter gets, I have found that the desired name is located in `name = payload["payload"]["name"]`. But now I don't know how to tell the formatter to use that instead of the array indices. @xile611, you commented on a similar issue last year saying that if the data has a `name` key, then the `Legend` and `Tooltip` will use that by default. My `Legend` is grabbing the `name` key just fine, but my `Tooltip` doesn't want to. I am trying `formatter={(value, name, payload) => { name = payload["payload"]["name"]; }` to set the `name` key, but that does not work.

**Comment by ZephD** [comment]
What ever the formatter returns is what gets displayed.

`formatter={(value, name) => name}`

**Comment by mjsevilla** [comment]
`formatter={(value, name, payload) => payload["payload"]["name"]}`

That doesn't work. I need `payload` in there b/c that's the object where the correct name is.

**Comment by mjsevilla** [comment]
`<Tooltip />` -> `0: 10`
`<Tooltip formatter={(value, name) => name} />` -> `0: 0`
`Desired output` -> `Fitbit: 10`

**Comment by mjsevilla** [comment]
Even the `Tooltip` from [TwoSimplePieChart](http://recharts.org/#/en-US/examples/TwoSimplePieChart) is using the array indices of the JSON data when there is clearly a `name` key being used.

**Comment by ZephD** [comment]
Any chance you can paste your JSON object? (Or sample of)

**Comment by mjsevilla** [comment]
@ZephD it's in the original post under the Code section :)

**Comment by ZephD** [comment]
http://jsfiddle.net/sj0cfqc8/38/

`<Pie data={deviceData} " nameKey="name" />`

This took me WAY to fucking long to find.

@xile611 
Why is nameKey and dataKey not defaulted to "name" and "value" respectively?

**Comment by mjsevilla** [comment]
@ZephD THANK YOU! Ugh, finally. I wish the docs were more details. They're honestly pointless: `formatter`: `the formatter function` :|

**Comment by dbiesiada** [comment]
I found this page when encountered similar issue.
I fixed it using labelFormatter property instead of formatter mentioned above,

check the following example:
<Tooltip labelFormatter={(index) => data[index].name} />

**Comment by zhuber** [comment]
This was super annoying, but here's what I ultimately wanted and found out how to do it:

```
<Tooltip separator=": " formatter={(value) => `${value} items`} />
```
