### ISSUE TITLE
Using Tooltip with Treemap?

### ISSUE THREAD

**Issue by eranimo** [recharts/recharts#76]
Can you use Tooltip with Treemap? I can't find any place in the docs where it says which components can use Tooltip.

**Comment by xile611** [comment]
Thanks~ Treemap will support Tooltip in next version.

**Comment by xile611** [comment]
Done in version 0.10.1

**Comment by eranimo** [comment]
@xile611 wow thanks!

**Comment by TotallWAR** [comment]
Could you provide an example with tooltip and treemap?
