### ISSUE TITLE
TwoSimplePieChart example not showing labels

### ISSUE THREAD

**Issue by evisong** [recharts/recharts#760]
## Do you want to request a feature or report a bug?

This is possibly a bug.

## What is the current behavior?

Just visit http://recharts.org/#/en-US/examples/TwoSimplePieChart

![image](https://user-images.githubusercontent.com/651208/27813311-a39dddae-60a7-11e7-92f5-48999bf4130f.png)

Labels around pie chart are missing.

## What is the expected behavior?

The pie chart should show labels.

**Comment by evisong** [comment]
Seems a bug of jsfiddle? 

![image](https://user-images.githubusercontent.com/651208/27813369-066cd8f4-60a8-11e7-8927-0d9592ebd182.png)

**Comment by evisong** [comment]
I've re-forked official React JSFiddle, the same issue: https://jsfiddle.net/fzcfmrj8/1/

**Comment by DungNV512** [comment]
Same with me.

**Comment by robhadfield** [comment]
Using this example on my app has the same affect, no labels. What should they look like?

**Comment by RoarkeRandall** [comment]
Same issue. Upgraded to latest and this occurred. Last tested version was 0.15.2 and labels were working.

**Comment by CiroAngeleri** [comment]
Had the same issue, reverted to 0.15.2 and labels work fine now. The jsfiddle official example doesn't seem to be updated

**Comment by xile611** [comment]
It works now.
