### ISSUE TITLE
asking about legend and tooltip in bar chart

### ISSUE THREAD

**Issue by nuugut** [recharts/recharts#761]
1. Can I change font size of the legend and tooltip of Bar Chart?
2. Can I change alignment of XAxis dataKey? default is horizontal, can I change to Diagonal?
3. Can I filter tooltip which value equal to 0 will not showing in the tooltip?

Thanks

**Comment by xile611** [comment]
@nuugut 

Question 1:  You can use css to change the font-size of `Legend` and `Tooltip`;
Question 2 : You can change the `angle` and `textAnchor` of `XAxis`,  `<XAxis dataKey="name" angle={-45} textAnchor="end" />`
Question 3: You can use customized `content` of `<Tooltip />`;

**Comment by maracuja-juice** [comment]
textAnchor doesn't exist on the XAxis.

**Comment by ArthurAttout** [comment]
Setting 

`<Legend style={{fontSize: 12}}/> `

Doesn't set the size of the font. How is it supposed to be done ?

**Comment by Yuddomack** [comment]
@ArthurAttout 

try this :)

`<Legend wrapperStyle={{fontSize: "10px"}}/>`

**Comment by mistat44** [comment]
@Yuddomack Cheers mate! worked
