### ISSUE TITLE
Everything gets re-rendered for no apparent reason

### ISSUE THREAD

**Issue by Poirette** [recharts/recharts#763]
## Do you want to request a feature or report a bug?

Bug

## What is the current behavior?

When I move my mouse over a bar chart, everything gets re-rendered for every little move, even if i'm not hovering a bar showing a tooltip.
I checked on a custom legend if nextProps were equals to current props, an it was. But the shallow equality returned false, which is a bug / problem in my opinion.

I didn't find any open issue about this.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/9y45ut13/).

Sorry, couldn't have Perf working in js fiddle.

## What is the expected behavior?

For every component composing the Chart, and the chart itself, they shouldn't be re rendered if their props don't change.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Recharts 1.0.0-alpha.1

**Comment by xile611** [comment]
@Poirette Maybe something else is updating the container of chart every time. The chart will update if:
```js
nextProps.data !== data || nextProps.width !== width ||
        nextProps.height !== height || nextProps.layout !== layout ||
        nextProps.stackOffset !== stackOffset || !shallowEqual(nextProps.margin, margin)
```

or 

```js
!isChildrenEqual(nextProps.children, children)
```
[Check the diff code](https://github.com/recharts/recharts/blob/master/src/chart/generateCategoricalChart.js#L178)
