### ISSUE TITLE
TypeError: Cannot read property 'parentElement' of null

### ISSUE THREAD

**Issue by Carlows** [recharts/recharts#765]
## Do you want to request a feature or report a bug?

Report a bug

## What is the current behavior?

I'm trying to use the ResponsiveContainer to wrap a component but in tests (Jest), i'm getting the following error:

```
TypeError: Cannot read property 'parentElement' of null
```

Here's a gist with the test and the component:

https://gist.github.com/Carlows/e276e740a2a739d3a73cb1053d386134

The same error happened to me when trying to render the LineChart component in a test. 

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Version 0.22.0, I'm not aware of this working or not working in other versions, but I didn't found anything related to this anywhere.

**Comment by Carlows** [comment]
I updated to latest version and still same problem, no one else having this issue?

**Comment by Carlows** [comment]
Full error:

```
TypeError: Cannot read property 'parentElement' of null
      at ResizeDetector.containerSize (node_modules/react-resize-detector/lib/components/ResizeDetector.js:87:55)
      at ResizeDetector.componentDidMount (node_modules/react-resize-detector/lib/components/ResizeDetector.js:63:33)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:25
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:263:11
      at CallbackQueue.notifyAll (node_modules/react-test-renderer/lib/CallbackQueue.js:76:22)
      at ReactTestReconcileTransaction.close (node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:26)
      at ReactTestReconcileTransaction.closeAll (node_modules/react-test-renderer/lib/Transaction.js:209:25)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:156:16)
      at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:69:27)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:143:20)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactUpdates.js:97:27)
      at Object.render [as create] (node_modules/react-test-renderer/lib/ReactTestMount.js:128:18)
      at Object.test (node_modules/@storybook/addon-storyshots/dist/test-bodies.js:21:44)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/index.js:147:25)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

Seems like it's coming from this component:

https://github.com/maslianok/react-resize-detector/blob/b31f737ea9cda208410fc96aadc4e27b59984172/src/components/ResizeDetector.js

**Comment by canuzunoglu** [comment]
same here

**Comment by henrinormak** [comment]
Any updates on this, it is definitely reproducable in jest tests.

**Comment by hendrikmolder** [comment]
The issue comes from the ResponsiveContainer component and is caused by the use of refs. As a workaround you can [mock refs in snapshot testing](https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html#mocking-refs-for-snapshot-testing)

The following test should work

```
import React from 'react';
import renderer from 'react-test-renderer';
import { BarChart } from '../';

function createNodeMock() {
  const doc = document.implementation.createHTMLDocument();
  return { parentElement: doc.body };
}

describe('BarChart', () => {
  test('renders properly', () => {
    const data = [
      { name: 'A-1', value: 0 },
      { name: 'A-2', value: 10 },
      { name: 'A-3', value: 80 },
      { name: 'A-4', value: 60 },
      { name: 'A-5', value: 45 },
    ];

    const tree = renderer.create(
      <BarChart data={data} color="#ff6363" />,
      { createNodeMock }
    ).toJSON();
    expect(tree).toMatchSnapshot();
  });
});
```

**Comment by GiancarlosIO** [comment]
@hendrikmolder yeah, that works for me, thanks dude :)

**Comment by elektronik2k5** [comment]
So in case anyone needs to resolve this error in [@storybook/addon-storyshots](https://github.com/storybooks/storybook/tree/master/addons/storyshots), here's how:
```tsx
import initStoryshots, { snapshotWithOptions, } from '@storybook/addon-storyshots'
import 'jest-styled-components'
import { ReactElement, } from 'react'

function createNodeMock(element: ReactElement<HTMLElement>) {
  if (element.type === 'div') {
    return {
      scrollWidth: 111,
      scrollHeight: 222,
      offsetWidth: 333,
      offsetHeight: 444,
      parentElement: {
        scrollWidth: 555,
        scrollHeight: 666,
        offsetWidth: 777,
        offsetHeight: 888,
        currentStyle: {
          position: 'relative',
        },
      },
    }
  }
  return null
}

initStoryshots({
  test: snapshotWithOptions({
    createNodeMock,
  }),
})
```
This is in TypeScript. If you need JavaScript, just strip the type annotations.

**Comment by UsulPro** [comment]
Hey @xile611
this issue is fixed in `react-resize-detector` (see https://github.com/maslianok/react-resize-detector/pull/40)
But this package is still depends on an old version
https://github.com/recharts/recharts/blob/13997461cd7f82302704c14a20fb123b2433338c/package.json#L64
Don't you consider to update the version of this dependency to the [latest](https://github.com/maslianok/react-resize-detector/releases)?

**Comment by JohnGrisham** [comment]
> So in case anyone needs to resolve this error in [@storybook/addon-storyshots](https://github.com/storybooks/storybook/tree/master/addons/storyshots), here's how:
> 
> ```tsx
> import initStoryshots, { snapshotWithOptions, } from '@storybook/addon-storyshots'
> import 'jest-styled-components'
> import { ReactElement, } from 'react'
> 
> function createNodeMock(element: ReactElement<HTMLElement>) {
>   if (element.type === 'div') {
>     return {
>       scrollWidth: 111,
>       scrollHeight: 222,
>       offsetWidth: 333,
>       offsetHeight: 444,
>       parentElement: {
>         scrollWidth: 555,
>         scrollHeight: 666,
>         offsetWidth: 777,
>         offsetHeight: 888,
>         currentStyle: {
>           position: 'relative',
>         },
>       },
>     }
>   }
>   return null
> }
> 
> initStoryshots({
>   test: snapshotWithOptions({
>     createNodeMock,
>   }),
> })
> ```
> 
> This is in TypeScript. If you need JavaScript, just strip the type annotations.

Good workaround, although this should probably be fixed by updating the resize detector as @UsulPro suggests.  I'll use this workaround until a stable release of the beta comes out.
