### ISSUE TITLE
AreaChart small values and a few very large values

### ISSUE THREAD

**Issue by Krakof** [recharts/recharts#766]
Hi,
I have problem with areaChart. I can't show few small  values among number of large ones.
For example: I have values [0, 0, 4522, 9500, 9, 0, 0, 0] 9 and 0 values are at the same level  at this chart, so I can't notice the difference.
How can  I add some visual difference between small values?
Thanks in advance

**Comment by xile611** [comment]
@Krakof The behavior of chart is right, you can try to adjust the data for your visual dimands.
