### ISSUE TITLE
Tooltip on barchart is in releases after v0.22.4

### ISSUE THREAD

**Issue by 100kristine** [recharts/recharts#767]
## Do you want to request a feature or report a bug?

Report a bug

## What is the current behavior?

In any versions later than v0.22.4, the tooltip renders above the graph.

<img width="333" alt="screen shot 2017-07-07 at 5 00 28 pm" src="https://user-images.githubusercontent.com/5431793/27980726-af272702-6336-11e7-9e6f-84b4661ebbc1.png">

In console, the nesting of the tooltip div seems to have moved

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/9y45ut13/).

        <Tooltip
          cursor={{ stroke: 'light grey', strokeWidth: 2 }}
          labelFormatter={d => moment(d).format('MM/DD')}
        />

## What is the expected behavior?
Tooltip cursor should be behind the bars of the chart.

<img width="437" alt="screen shot 2017-07-07 at 5 07 15 pm" src="https://user-images.githubusercontent.com/5431793/27980736-c28117f4-6336-11e7-9c7e-376ce120408d.png">

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

v1.0.0-alpha.0 and v1.0.0-alpha.1, Mac OS 10.12 affected, works in versions before this

**Comment by xile611** [comment]
@100kristine Change the order  of `<Bar />` and `<Tooltip />`. Move `<Tooltip />` to be after `<Bar />` .

**Comment by 100kristine** [comment]
@xile611 Thanks for the response - I think that I do have Tooltip after bar though - is there something that I'm missing?

```
<BarChart width={graphWidth} height={graphHeight} margin={{ top: 20 }}>
        <XAxis
          dataKey='day'
          padding={{left: 30, right: 30}}
          tickFormatter={day => moment(day).format('MM/DD')}
        />
        <YAxis
          domain={[0, 'auto']}
        />
        {datakeys.map((entry, index) => {
          return (
            <Bar
              dataKey={entry}
              fill={chartColors[barcolors[index]]}
              minPointSize={5}
            />
          );
        })}
        <Legend />
        <Tooltip
          cursor={{ stroke: 'light grey', strokeWidth: 2 }}
          labelFormatter={d => moment(d).format('MM/DD')}
        />
      </BarChart>
```
