### ISSUE TITLE
Tooltip Stops Displaying at Bottom of Large Bar Charts

### ISSUE THREAD

**Issue by bcongdon** [recharts/recharts#768]
## Do you want to request a feature or report a bug?
Bug Report

## What is the current behavior?
For horizontal bar charts, the tooltip stops rendering when the mouse moves down past ~1000 pixels from the top of the chart.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/9y45ut13/).
https://jsfiddle.net/h03zu2Lf/3/

The tooltip does not render for the lower entries in this chart. Change the ResponsiveContainer's height to ~250px. Then the tooltip does render for all entries in the chart.

## What is the expected behavior?
Tooltip should render for all bars in this bar chart regardless of how far down it is in the chart.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
* v1.0.0-alpha.1
* Chrome under MacOS
* Unsure

**Comment by xile611** [comment]
@bcongdon Check the latest version of recharts, I think this has been fixed. Reopen this if it still not works.
