### ISSUE TITLE
Is there any way to using Line in a BarChart?

### ISSUE THREAD

**Issue by trungpham-agilityio** [recharts/recharts#771]
I want to using Line in a BarChart. I tried but no luck. You can have a look at: http://jsfiddle.net/0c6nx13n/

**Comment by xile611** [comment]
@trungpham-agilityio You can use [ComposedChart](http://recharts.org/#/en-US/api/ComposedChart).

**Comment by trungpham-agilityio** [comment]
@xile611 : yes, I did it. But not work, could you please have a look at my example and give to me your feedback http://jsfiddle.net/0c6nx13n/2/ ? Seem I did any wrongs.

**Comment by xile611** [comment]
[Right demo](http://jsfiddle.net/0c6nx13n/4/).

**Comment by trungpham-agilityio** [comment]
@xile611 : thank you :)
