### ISSUE TITLE
ResponsiveContainer Styling

### ISSUE THREAD

**Issue by al3x-huang** [recharts/recharts#772]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
Adding `id` attribute to `<ResponsiveContainer>` doesn't produce a component with that attribute.
  
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal 
`<ResponsiveContainer id="container"/>` and setting the style `#container{background-color:red}` doesn't produce a svg with the red background color. Further inspection shows that the component doesn't pass along the ID attribute

## What is the expected behavior?
A `<ResponsiveContainer/>` with the set ID attribute.

**Comment by xile611** [comment]
@al3x-huang You can add css like:

```css
.recharts-responsive-container {
  background-color:red;
}
```
