### ISSUE TITLE
Bullet Chart

### ISSUE THREAD

**Issue by al728** [recharts/recharts#773]
Hi! I was wondering If there were any plans of adding Bullet Charts to the current library similar to the ones listed below. 

https://bl.ocks.org/mbostock/4061961
http://nvd3.org/examples/bullet.html

The current workaround we have is creating a sideways composed bar chart with two "markers" built with single point lines. It works alright but was still curious about further chart type developments.

Thanks!

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.

**Comment by manobalas** [comment]
Can you please let us know ... How to use the bullet chart ?

**Comment by Favourz1** [comment]
> Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.

Hi @xile611, 
Was the bullet chart type added?
