### ISSUE TITLE
How to fix the values of X and Y axis?

### ISSUE THREAD

**Issue by vidushijain** [recharts/recharts#774]
Hi,

I am trying to make 9 box plot graph using scatter graph in react js. 
I want to fix the value of X and Y axis. for example the value of X axis labels should be 1.2, 2.8 , 4.4 , 6 and similarly form Y axis. I don't want to derive these value from any column.
How can we do that?

Thanks a lot.

**Comment by Amthieu** [comment]
If by label you mean the axis ticks, here's how you can do it:  
``` javascript
<XAxis ticks={[1.2, 2.8, 4.4, 6]} />
```

**Comment by vidushijain** [comment]
Hi @Amthieu 
Thanks for your response.
For example lets take this example from there official website.

http://jsfiddle.net/zdhvvt2e/?utm_source=website&utm_medium=embed&utm_campaign=zdhvvt2e

In this I was X axis to have these points 100,120,140,160,180. 
I tried using ticks but when i apply it the whole graph disappears.

I know I am missing something. But don't know what.

Thanks once again :)

**Comment by Amthieu** [comment]
The example is just missing type="number" in order to display the ticks you want. You can also specify a domain to make it look better. Here is what I used for your values:  
``` javascript
<XAxis dataKey={'x'} name='stature' unit='cm' ticks={[100, 120, 140, 160, 180]} domain={[80, 200]} type="number" />
```

**Comment by vidushijain** [comment]
@Amthieu Thanks a lot :) It worked :D

**Comment by victorsilent** [comment]
I'm using unit="U$" and getting only values, without U$
`<YAxis unit='U$'/>`

**Comment by xile611** [comment]
@victorsilent We have fix the bug of unit.It'll released today.

**Comment by ravenberg** [comment]
I think it is important to note that you might have to set an interval between ticks when defining them as a fixed set. Could help mentioning.

**Comment by LouisMuriuki** [comment]
how would this be done in time format?

**Comment by Mompa786** [comment]
how can we add a manual axis limit in scatterchart can anyone have solution

**Comment by ckifer** [comment]
@Mompa786 not sure exactly what the ask is, but you can use the domain prop (domain={[0, 1000]}) to limit the domain on an X or Y axis. This is a closed issue so if that isn't the ask feel free to create a new one so it gets more visibility
