### ISSUE TITLE
Module not found: Error: Can't resolve 'recharts-scale'

### ISSUE THREAD

**Issue by darcusfenix** [recharts/recharts#775]
Hi

I did a npm update, but when webpack rebuilt my project appears this log below.

```
ERROR in ./~/recharts/es6/util/ChartUtils.js
Module not found: Error: Can't resolve 'recharts-scale' in '.../node_modules/recharts/es6/util'
```
version => 1.0.0-alpha.2

**Comment by xile611** [comment]
@darcusfenix `recharts-scale` which is a dependency of recharts isn't installed. Please check the node_modules.

**Comment by zerihun-tesfaye** [comment]
yarn add  recharts-scale
 or
 npm i recharts-scale
