### ISSUE TITLE
Position first & last Bar from start

### ISSUE THREAD

**Issue by Artkoch** [recharts/recharts#780]
Usually Bars are distributed with a gap at the beginning of a chart.
 
![screen shot 2017-07-13 at 16 29 13](https://user-images.githubusercontent.com/12727615/28168786-de6e4840-67e8-11e7-840c-d07da492da42.png)

How to make Recharts distribute Bars starting from the very beginning till end, so that there will be no gap. Like at the image below?

![screen shot 2017-07-13 at 16 34 36](https://user-images.githubusercontent.com/12727615/28168874-30e96438-67e9-11e7-8c2e-86c56c786eaa.png)

**Comment by xile611** [comment]
You can change the `scale` of `<XAxis />` to be `'point'`, and add padding

![image](https://user-images.githubusercontent.com/6111424/76817029-bdcee200-683c-11ea-8fd7-0722bddd101c.png)
