### ISSUE TITLE
Remove stroke when value is 0 in stacked bar charts

### ISSUE THREAD

**Issue by joewang704** [recharts/recharts#781]
![image](https://user-images.githubusercontent.com/7842675/28184513-88b07c7c-67c8-11e7-9955-c68626eac104.png)

When creating a stacked bar chart, if any of the top-most bars has a value of 0, it will still show (as you can see on the bar with height 0) but does not display when the stroke is removed.

**Comment by Simek** [comment]
This problem still exist.
