### ISSUE TITLE
Axis Labels Look Awful

### ISSUE THREAD

**Issue by ardasahiner** [recharts/recharts#782]
In [this commit](https://github.com/recharts/recharts/commit/08c50dabecf4231f59f32a8c0ccc532976b4ce1f), I see that the labels were gotten rid of in the source code in a lot of places. I'm seeing some issues with this because now I can no longer create custom labels for axes, and the labels that are created look really bad. See your own example: http://recharts.org/#/en-US/examples/ComposedChartWithAxisLabels

<img width="543" alt="screen shot 2017-07-13 at 10 48 30 pm" src="https://user-images.githubusercontent.com/14845624/28199825-78032d48-681d-11e7-9ec7-031ca13322e4.png">

The default XAxis label overlaps with the axis ticks and the YAxis label looks even worse. Worse, there is no way to customize the label anymore. Please let me know what I can do or please fix this change. Thanks!

**Comment by ardasahiner** [comment]
Resolved: For anyone else who runs into this issue, axes now take a `[Label](https://github.com/recharts/recharts/blob/master/src/component/Label.js)` child that can be formatted much more nicely.

**Comment by juampick** [comment]
Thanks @ardasahiner ... I'm having the same issue? Do you have an example on how can I format it?

**Comment by juampick** [comment]
I've got resolved @ardasahiner. For future reference what I do is the following: 
```
<YAxis unit="LBs">
     <Label value="LBs" position="insideTopLeft" offset={10} />
</YAxis>
```

Thanks

**Comment by jpdevries** [comment]
I'm struggling to format an Axis label to be rotated vertically. Any examples would be appreciated. ![](http://j4p.us/2s070G060T2x/Screen%20Shot%202017-08-01%20at%202.02.41%20AM.png)

**Comment by juampick** [comment]
+1 @jpdevries

**Comment by Germanika** [comment]
@jpdevries @juampick In case you haven't found a solution to this yet, here's what I came up with:
```
<YAxis>
    <Label value='Vertical Label!' angle={270} position='left' style={{ textAnchor: 'middle' }} />
<YAxis>
```

**Comment by nhooey** [comment]
@xile611 Setting `textAnchor="middle"` in @Germanika's example above doesn't work. I have to set the `style` as they did. Is this a bug?

**Comment by xile611** [comment]
Change the position of label which has default value 'center' which is in the horizontal center and the vertical center of the view box of `XAxis`.

[Doc of Label](http://recharts.org/#/en-US/api/Label)

**Comment by ponciusz** [comment]
Try this:

`<XAxis stroke="#bbb" type="number">
    <Label
    value="Litres"
    position="insideBottomRight"
    offset={0}
    content={props => {
        return (
        <text
            style={{ fontSize: "12px" }}
            x={props.viewBox.x + props.viewBox.width}
            y={props.viewBox.y + props.viewBox.height + 3}
            text-anchor="end"
            fill="#bfbfbf"
        >
            {props.value}
        </text>
        );
    }}
    />
</XAxis>`

**Comment by ElanUtta** [comment]
Hi, where I can find the documentation to customize my label?

**Comment by bmaclean** [comment]
@ElanUtta https://recharts.org/en-US/api/Label

**Comment by jzybert** [comment]
> Resolved: For anyone else who runs into this issue, axes now take a `Label` child that can be [formatted](https://github.com/recharts/recharts/blob/master/src/component/Label.js) much more nicely.

For anyone looking, the link has changed https://github.com/recharts/recharts/blob/master/src/component/Label.tsx

**Comment by GreenRidingHood** [comment]
![Screen Shot 2022-01-27 at 1 26 16 AM](https://user-images.githubusercontent.com/17296724/151311173-83595300-2462-4335-825c-ed198a2fc378.png)
![Screen Shot 2022-01-27 at 1 26 08 AM](https://user-images.githubusercontent.com/17296724/151311174-09cf67a9-e971-4607-82e8-dd48791707b1.png)

**another example for label position,** 
if you increase offset number on the `<Label />`  tag that will help to push down Axis label, if you lost label, you have to increase `<LineChart />` margin bottom number until you see the label
