### ISSUE TITLE
stacked area chart - wrong draw order

### ISSUE THREAD

**Issue by georgesboris** [recharts/recharts#785]
When using stacked area charts the bottom dataset should be rendered on top of the next one and so forth. This would prevent this boundaries overlaps that creates such awful visual problems.

<img width="347" alt="captura de tela 2017-07-17 as 9 07 41 am" src="https://user-images.githubusercontent.com/3660797/28267240-85892a58-6acf-11e7-85aa-5d6d516539d4.png">

**Comment by georgesboris** [comment]
Is the 0 values expected to be removed from the stacked datasets so they won't appear on top of the bottom ones?

**Comment by su-narthur** [comment]
Yes! This bug can make stacked area charts look pretty bad. Anyone find a solution?

<img width="663" alt="screen shot 2017-09-19 at 5 41 21 pm" src="https://user-images.githubusercontent.com/20328940/30616890-d0a5d9d6-9d61-11e7-93af-dc4d7ebe88a7.png">

<img width="602" alt="screen shot 2017-09-19 at 5 41 11 pm" src="https://user-images.githubusercontent.com/20328940/30616894-d3ce00b6-9d61-11e7-8137-a3808696b9c0.png">

[JSFiddle example](http://jsfiddle.net/t41dctho/52/)

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
