### ISSUE TITLE
Making Tooltip Scrollable

### ISSUE THREAD

**Issue by braxtonchristensen** [recharts/recharts#787]
## Do you want to request a feature or report a bug?
feature request
## What is the current behavior?
the tooltip will just continue down on to the next chart and even off the page.

## What is the expected behavior?
to allow tooltip to have a max height and scroll
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
any and all

**Comment by Eric24** [comment]
Another possible option here might be to allow the tooltip window to be larger than the chart container.

**Comment by braxtonchristensen** [comment]
That's really not ideal, I made the tool tip scrollable by hooking into the onWheel event on the chart and using refs to change the scrollTop of the tooltip by the DeltaY of the scroll I don't remember the full details as I did it about a month ago. But that was the basic idea. Don't forget to throttle your scroll event :)

**Comment by maxieduncan** [comment]
I was able to do make the tooltip scrollable with some simple css:
`
.recharts-default-tooltip {
  overflow-y: auto;
  .recharts-tooltip-item-list {
    height: <height of tooltip>
  }
}`

**Comment by maxieduncan** [comment]
I was able to do make the tooltip scrollable using this css:
`.recharts-default-tooltip { overflow-y: auto; .recharts-tooltip-item-list { height: <height of tooltip> } }`

and specifying the wrapper style on the Tooltip to enable pointer events:
`<Tooltip wrapperStyle={{pointerEvents: 'auto'}}/>`

It seems that the wrapper has the element style `pointer-events` set to `none` which made enabling scrolling tricky to enable, presumably as it can be difficult to mouseover and interact with.

**Comment by RParvathi** [comment]
Is there an update to recharts or resolution to allow scrolling the tooltip content ?

**Comment by braxtonchristensen** [comment]
@RParvathi Not, as far as I know, sounds like @maxieduncan had a pretty good solution although it sounded like getting the cursor into the tooltip might not have been an easy thing to do, hooking into the scroll event worked for our needs.  Since this issue didn't get a ton of love over the last year, you might be stuck with a hack if you are attached to this charting library.

**Comment by xile611** [comment]
It's recommended to use customized `content` of `Tooltip` to cover default tooltip.

**Comment by akzarma** [comment]
As I needed this feature urgently, I made a custom scrollable tooltip. I have also made a public repo which contains the sample project.
[https://github.com/akzarma/Recharts-Custom-Tooltip](url)
