### ISSUE TITLE
Dot not appearing on asynchronously loaded data for linear graph

### ISSUE THREAD

**Issue by VicFrolov** [recharts/recharts#789]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
Dots do not show up on asynchronously loaded data, unless screen is resized

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).
```
      <ResponsiveContainer width="100%" height="80%">
        <LineChart
          data={data}
          margin={{ top: 5, right: 50, left: 0, bottom: 5 }}
        >
          <XAxis dataKey="name" />
          <YAxis />
          <CartesianGrid
            strokeDasharray="3 3"
            horizontal={false}
          />
          <Tooltip />
          <Legend />
          <Line
            type="monotone"
            dataKey="mood"
            stroke="rgba(43, 191, 217, 0.9)"
            dot={{ stroke: '#ff0000', strokeWidth: 2 }}
            activeDot={{ r: 1 }}
            strokeWidth={5}
          />
          <ReferenceLine y={7} label="Max" stroke="green" strokeDasharray="3 3" />
        </LineChart>
      </ResponsiveContainer>
```

I have a variable `data`, if I write it myself, the dots show up in red, but if the data is loaded asynchronously, the graph is drawn, everything works as it should, except the dots are white. On window resize, which i assume is due to responsiveContainer, they are then updated to be red

## What is the expected behavior?
For the red dots to appear

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Should be using the latest recharts that I installed using npm, this is on a Chrome browser

**Comment by tmf-chris** [comment]
This relates to another issue #804 - it isn't because it is an async load (I think...) it is because it is rerendering the same data. If it is only rendered once, the dots show, but if rendered (with the same data) the dots then do not show.

**Comment by n1ckp** [comment]
I am also having this issue. It seems somewhere in the re-render process after new data is propagated through, it stops short of rendering the dots.

**Comment by DeadcatDev** [comment]
Up, same issue here. Any fix?

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.

**Comment by khwaja-abdul-ahad** [comment]
@VicFrolov It may be due to continues re-rendering of the graph.
