### ISSUE TITLE
Renaming groups in Legend/Tooltip

### ISSUE THREAD

**Issue by michalg42** [recharts/recharts#79]
Hi

I haven't found anything about it in documentation, so I guess it isn't possible at the moment.

It would be useful to be able to change name in easy way of groups. Now they inherits labels from property name of data series.

In my case I need it to be translated for instance. Of course I can create new data series where I put new elements with changed keys, but in my opinion it's not good solution to this problem.

I think it would be good idea to send into Chart element array/object with mapped labels, something like, if I have values like:
[{name: 'A', x: 5, y: 7}, {name: 'B', x: 2, y: 6}, {name: 'C', x: 4, y: 4}, {name: 'D', x: 3, y: 1}]
I would like to send there something like this:
{x: 'My X value', y: 'My Y value'}

**Comment by xile611** [comment]
@michalg42 

In your case, you can set the props `name` of each chart item just like the following example:

```jsx
<LineChart width={400} height={400} data={data}  margin={{top: 10, bottom: 10, left: 30, right: 30}}>
  <XAxis dataKey="name" />
  <Tooltip/>
  <Legend/>
  <CartesianGrid stroke="#f5f5f5" />
  <Line name="My X value" dataKey="x" stroke="#ff7300" />
  <Line name="My Y value"  dataKey="y" stroke="#387908" />
</LineChart>
```

Thanks! I'll add this in the document.

**Comment by michalg42** [comment]
Thanks, that's exactly what I was looking for. :)
