### ISSUE TITLE
Tooltip "active" prop being overwritten

### ISSUE THREAD

**Issue by alexandersoto** [recharts/recharts#790]
I'm running into an issue where the `active` and `payload` props for a Tooltip are being overwritten. Code:

```
<ResponsiveContainer
          width="100%"
          height={this.props.height}
        >
          <PieChart
            width={diameter}
            height={diameter}
          >
            <Pie
              data={this.props.data}
              dataKey="value"
            >
            </Pie>
            <Tooltip
              active={true}
              payload={this.props.payload}
            />
          </PieChart>
</ResponsiveContainer>
```

The `active` prop is false when I inspect the tooltip with React dev tools. And they payload never changes, although `this.props.payload` changes.

What controls the tooltip, and is there a way to control it manually?

**Comment by GiancarlosIO** [comment]
Same here :(

**Comment by infiman** [comment]
Hi. Actually, this problem still remains:

> The active prop is false when I inspect the tooltip with React dev tools. And they payload never changes, although this.props.payload changes.

But I somehow managed to make it permanently visible by using this styles prop:
```
wrapperStyle={{
  visibility: 'visible',
}}
```

However, the whole chart still listening each mouse over and repaints Tooltip, even though it's fixed by style.

Maybe it will be useful for someone.

@GiancarlosIO @alexandersoto

**Comment by xile611** [comment]
Duplicated with #791
