### ISSUE TITLE
Tooltip not appearing on pie charts when cells re-render

### ISSUE THREAD

**Issue by alexandersoto** [recharts/recharts#791]
I'm trying highlight the selected sector of a pie chart, and the following code works. The issue is that the tooltip won't appear. If I remove the `onMouseEnter` and `onMouseLeave` events, then the tooltips show up fine. But of course, I can't render the selected sector differently in that case. I think there's an issue with tooltips not appearing when the Cells re-render. 

```
<ResponsiveContainer
  width="100%"
  height={this.props.height}
>
  <PieChart
    width={diameter}
    height={diameter}
  >
    <Tooltip/>
    <Pie
      data={this.props.data}
      dataKey="value"
      onMouseEnter={(e, activeIndex) => this.setState({ activeIndex }) }
      onMouseLeave={() => this.setState({ activeIndex: -1 }) }
    >
      {
        _.map(this.props.data, (entry, i) => (
          <Cell
            key={`cell-${i}`}
            fill={COLORS.CONTRASTING_COLORS[i]}
            fillOpacity={this.state.activeIndex === i ? 1 : 0.25}
          />
        ))
      }
    </Pie>
  </PieChart>
</ResponsiveContainer>
```

I tried to fix this issue by "actively" controlling the tooltip, but that didn't work either: https://github.com/recharts/recharts/issues/790

**Comment by zinroc** [comment]
Any progress with this? I just ran into the same issue

**Comment by zinroc** [comment]
Figured it out, this works for me: 

<Tooltip content={<CustomTooltip />} wrapperStyle={{visibility: this.props.activePieSlice ? 'visible' : 'hidden'}} />

**Comment by trabek** [comment]
anything new?

**Comment by bluetidepro** [comment]
I have this same bug in `1.0.0-beta.10`, did you ever get a way to fix this, @alexandersoto?

**Comment by alexandersoto** [comment]
Unfortunately I never did.

**Comment by hugobarragon** [comment]
> Hi, I faced this problem.
> After using `<CustomTooltip />`, it works and can show tooltip with re-render pie-chart.
> 
> ```
>         <Tooltip
>             active={true}
>             wrapperStyle={{
>               visibility: 'visible',
>             }}
>             content={<CustomTooltip />}
>           />
> ```
> but this not worked
> 
> ```
>         <Tooltip
>             active={true}
>             content={<CustomTooltip />}
>           />
> ```

Could you provide the custom tool tip you are using?

**Comment by xile611** [comment]
Duplicated with #791

**Comment by gaurav5430** [comment]
@xile611 this is #791 , i think you closed this by mistake ?

**Comment by gaurav5430** [comment]
active={true} does not seem to make any difference to the behaviour of the tooltip at all.

Is there a way to always show the tooltip?

**Comment by Kartstig** [comment]
I am also having this problem

**Comment by gaurav5430** [comment]
> I am also having this problem

What exactly is the problem you are facing? The active prop does not work?
Do you want your tooltip to be always visible?
Did the visibility override, as suggested in other comments, work for you?

@Kartstig

**Comment by simonhessner** [comment]
I have the same problem. I want to keep the Tooltip active all the time. The reason is that when I update the data in the state, the tooltip flickers (disappears + appears immediately). Since I change the data in the state based on MouseMove events, it flickers a lot. The solution would be to have the tooltip active as long as the mouse is somewhere on the graph, but I don't know how to achieve it.

**Comment by srossross** [comment]
is there a guide on how to extend or create new components?

**Comment by gaurav5430** [comment]
What exactly is your requirement for extending or creating new components? What are you expecting?
@srossross

**Comment by Kartstig** [comment]
> What exactly is the problem you are facing? The active prop does not work?

Correct. `active` prop doesn't work as expected

> Do you want your tooltip to be always visible?

Yes

> Did the visibility override, as suggested in other comments, work for you?

Yes I was able to get it to work with the wrapperStyle as suggested by @azamiya

**Comment by simonhessner** [comment]
Not sure, but this PR might also help with that: https://github.com/recharts/recharts/pull/2150
