### ISSUE TITLE
Barchart with brush display the entire data 

### ISSUE THREAD

**Issue by Vijayk93** [recharts/recharts#792]
I m using recharts in my project.When using bar chart with brush it works perfect.
Current behaviour is the data is displayed within the selected bounds.
Is there a way to show the entire data cells but only highlight the data cells in the selected bounds and fade away the rest?

**Comment by xile611** [comment]
@Vijayk93 It's not supported now. You can try to render customized chart use `BarChart`, `Brush`, `ReferenceArea`.
