### ISSUE TITLE
curved bars without custom component

### ISSUE THREAD

**Issue by raviteja83** [recharts/recharts#793]
is it possible to have the top corners of the bar rounded without using a custom component?

**Comment by selrond** [comment]
@xile611 why's thic closed?

**Comment by FrantisekVrab** [comment]
`radius={[0, 5, 5, 0]}` on Bar component .. this just doesn't work

**Comment by raviteja83** [comment]
@FrantisekVrab can you post a codesandbox or something showing what doesn't work exactly?

**Comment by jibin23** [comment]
@FrantisekVrab solution works, putting ```radius={[0, 5, 5, 0]}``` as props to ```<Bar>``` component.

**Comment by jeffmbreis** [comment]
Not working for me too

**Comment by michaelscraft** [comment]
Works just fine in jsfiddle 👍
https://jsfiddle.net/michaelscraft/0bnt4o19/12/

**Comment by pmsoltani** [comment]
I'm using recharts@1.7.1 and it's working just fine.

**Comment by Haraldson** [comment]
How to apply this only for the last segment of each bar in a stacked bar chart?
