### ISSUE TITLE
How can I make sure times on my XAxis are evenly distributed?

### ISSUE THREAD

**Issue by jacklaplante** [recharts/recharts#794]
I'm grabbing measurements from my database to populate a chart. On the YAxis of my chart is the value of the measurement and on the XAxis if the date/time that the measurement was recorded. However, because measurements aren't recorded at a regular interval, some times don't have measurements. But the chart puts all of the times together as if they were all recorded at the same interval.

So the XAxis ends up looking like this:
<img width="1136" alt="screen shot 2017-07-19 at 12 01 10 pm" src="https://user-images.githubusercontent.com/8061745/28377242-2d1e805a-6c7a-11e7-8925-28b27fad9066.png">

Where the dates are not evenly distributed.

How can I fix this? I tried using the `scale='utcTime'` param of the `XAxis` component but that didn't work.

**Comment by ojame** [comment]
@jacklaplante Did you end up finding a solution for this? I've tried multiple scale types (even as a function, which results in another bug) but I'm having no luck for even distribution.

**Comment by bluetidepro** [comment]
@ojame @jacklaplante Any luck with this? Did you find a solution? Still having the same problem.
