### ISSUE TITLE
Tooltip label

### ISSUE THREAD

**Issue by pcatalina** [recharts/recharts#796]
Tooltip's label does not change.
The default label is the dataKey of YAxis. I want to change it to a simple string

` <BarChart
                    width={600}
                    height={350}
                    data={data}
                    layout="vertical"
                >
                   ...
                    <YAxis
                        dataKey="info"
                        ...
                    />
                    <Tooltip label="Info" />
                    ...
                </BarChart>`

When I change label I expect it to change also in the box when I am over a bar.

recharts v0.22.4

**Comment by adack123** [comment]
Ping on this, 

It's not very clear in the docs on how this is done.. Any insights?

**Comment by eranhirs** [comment]
Something like this PR, but for `Tooltip.js` https://github.com/recharts/recharts/pull/219

**Comment by abishek3876** [comment]
I had the same issue and for anybody trying to solve this can use `labelFormatter` instead.

`<BarChart width={600} height={350} data={data} layout="vertical" > ... <YAxis dataKey="info" ... /> <Tooltip labelFormatter={() => "Info"} /> ... </BarChart>
`
Now, it displays the label as "Info" properly.
If you're curious, have a look at https://github.com/recharts/recharts/blob/master/src/component/DefaultTooltipContent.js#L100 to know why it's working.

**Comment by samhunta** [comment]
This is still an issue...

**Comment by ZephD** [comment]
The Label prop is the dataKey of the selected data point.
"Usually calculated internally".
Setting it manually means your tooltip is always selected the "info" data point.
Use the labelFormatter={() => 'Info'} instead.

**Comment by phamj88** [comment]
Is there a working example of label used as its intended purpose?
`<Tooltip label="pv"`
Should show pv as the label correct? But that doesnt work.

https://jsfiddle.net/k5kbpve6/4/

**Comment by ZephD** [comment]
I couldn't get it to work as you'd like.
I'm guessing it just gets overwritten by the internally calculated label.
I also couldn't find where this happens in the code.

**Comment by JoeyGarcia** [comment]
Would really like to have this usable, I hope this issue will get some attention please. Thanks

**Comment by warreee** [comment]
Me as well, is there a temporary workaround?

**Comment by gtnx** [comment]
Same here

**Comment by sajjanbalar** [comment]
Me too. How do I change the format of the whole thing?

**Comment by hybmg57** [comment]
You need to use both `label` and `labelFormatter`
```
<Tooltip label="{timeTaken}" labelFormatter={(name) => 'Time Taken: ' + name} />
```

**Comment by burhanrashid52** [comment]
If I just need to concate the text we can simple use this.
```javascript
<Tooltip formatter={(label) => label + " %"}/>
```

**Comment by BrenoVelasco** [comment]
Three years have passed and not a single solution. Please, this is so basic it's embarassing.

**Comment by amalChandran** [comment]
You can use formatter to solve this:
`const formatter = (value, name, props) => {
  let formattedName = labelByCategory[name]
  let formattedValue = Math.round(value * 100) / 100
  return [formattedValue, formattedName, props]
}`

`<Tooltip formatter={formatter} />`

**Comment by bartoosten** [comment]
I was running into the same issue, I found out if I apply a name prop to Line component it get inherited to the Tooltip component. This example has a name property 'Price', will get displayed in the Tooltip label
```JSX
<Line
    type="monotone"
    dataKey="1"
    name="Price"
    stroke="rgb(173, 155, 246)"
    strokeWidth={2}
    dot={false}
    activeDot={{ r: 8 }}
/>
```

Maybe that's an option for some people here.

**Comment by langerkirill** [comment]
I figured out that if you use a custom tooltip from this [other answer] (https://github.com/recharts/recharts/issues/275) you can simply change the label property and then give the Tooltip a custom title:
```
export const CustomTooltip = props => {
    // we don't need to check payload[0] as there's a better prop for this purpose
    if (!props.active) {
        // I think returning null works based on this: http://recharts.org/en-US/examples/CustomContentOfTooltip
        return null
    }
    
    // mutating props directly is against react's conventions
    // so we create a new payload with the name and value fields set to what we want
    const newPayload = [
        {
            readableTime: 'readableTime',
            // all your data which created the tooltip is located in the .payload property
            value: props.payload[0].payload.readableTime,
            // you can also add "unit" here if you need it
        },
        ...props.payload,
    ];

    // we render the default, but with our overridden payload
    return <DefaultTooltipContent {...props} payload={newPayload} label={"asdf"}/>;
};
```
<img width="107" alt="Screen Shot 2021-11-10 at 3 30 50 PM" src="https://user-images.githubusercontent.com/35643849/141204341-fdb4a996-28df-4d4e-8a6a-72519eeef974.png">
