### ISSUE TITLE
Line onClick not working

### ISSUE THREAD

**Issue by mclarentgp** [recharts/recharts#797]
I got the latest release of recharts and the line chart onClick event does not work.  I tried changing the strokeWidth and that did not help.

**Comment by Heedster** [comment]
I am facing the same issue

**Comment by nivedhithaVenkatachalam** [comment]
@mclarentgp Did you get it to work? I am facing the same issue. LineChart onClick works but not the Line onClick.

**Comment by jblom** [comment]
Hi, I also got the same issue... For the time being will try to fix it with e.g. https://github.com/recharts/recharts/issues/261

**Comment by xile611** [comment]
![image](https://user-images.githubusercontent.com/6111424/32931515-93d57af4-cb9f-11e7-9d70-2843290f8681.png)


How about the version of recharts? Both the onClick of `LineChart` and the onClick of `Line` works in my local project.

**Comment by jblom** [comment]
thanks, will test it next week (and will report about the result).

**Comment by dmr** [comment]
Is this working yet?

**Comment by jlcarvalho** [comment]
You can pass the onClick property to the activeDot attribute, like:

```jsx
<Line activeDot={{ onClick: console.log }} />
```

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
