### ISSUE TITLE
Tooltip does not work for PieChart on mobile Safari

### ISSUE THREAD

**Issue by sartios** [recharts/recharts#799]
## Do you want to request a feature or report a bug?

Report a bug

## What is the current behavior?

PieChart tooltip does not work on mobile Safari.

I test it on mobile Chrome and it works.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).

I used the official example:

http://jsfiddle.net/sj0cfqc8/?utm_source=website&utm_medium=embed&utm_campaign=sj0cfqc8

## What is the expected behavior?

On click over a pie chart sector, the active tooltip to be shown.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Safari/602.1

**Comment by sartios** [comment]
In case I override onClick of PieChart component then some tooltips are been displayed

**Comment by Monkeychip** [comment]
@sartios can you provide a code snippet of your solution?  Running into the same problem.

**Comment by HermantNET** [comment]
Running into this issue as well. Any solutions until this gets fixed?

**Comment by samueldepooter** [comment]
Still seems broken... Any update on this?

**Comment by mcmxc** [comment]
Guys, try to apply `.recharts-wrapper * { cursor: pointer; }` and see if it helps. Works for line chart on ios devices

**Comment by loopbender** [comment]
experiencing the same issue, tap on mobile doesn't trigger onMouseEnter events (piechart activeShape example). It does work for Tooltip component though. (all barchart examples).

@mcmxc's solution does provide a temporary workaround -thx for that-, but it's not very stable, as some taps don't still trigger the event.

**Comment by mcmxc** [comment]
> @mcmxc's solution does provide a temporary workaround -thx for that-, but it's not very stable, as some taps don't still trigger the event.

try to play with css selectors (to apply `cursor: pointer` to). For me it works pretty much stable

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
