### ISSUE TITLE
How to dynamically load data

### ISSUE THREAD

**Issue by XIEJUNXIRUOFENG** [recharts/recharts#803]
componentDidMount() {
        this.iterator = setInterval(() => {
            const newData = {name: defaultData.length, uv: this.mockData(), pv: this.mockData(), amt: this.mockData()}
            defaultData.push(newData);
            this.setState({
                data: defaultData
            });
        },1000)
    }；
write setInterval in componentDidMount and push newData in data, but The page is not new；

**Comment by xile611** [comment]
@XIEJUNXIRUOFENG Create a new object each time you update data
```jsx
this.setState({
  data: [... defaultData, newData],
});
```
