### ISSUE TITLE
PieChart: labels won't render if the state was changed before animation finish

### ISSUE THREAD

**Issue by eranbnn** [recharts/recharts#806]
When animation and labels are enabled, setting the state while the animation is still in progress, interrupts the animation and jumps to fully rendered state, but Recharts' `this.state.isAnimationFinished` is still `false`, so renderLabel function won't render the actual labels.

It is simply reproduced by using onEnter function and hovering the pie before animation is finished:
http://jsfiddle.net/2rt6rj2h/118/

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
