### ISSUE TITLE
Give an example for color maps

### ISSUE THREAD

**Issue by morloy** [recharts/recharts#809]
The `StackedAreaChart` currently uses hard-coded colors.
It took me some time to figure out how to use a predefined colormap for automated coloring.

There's a very nice example in [BarChart.js](https://github.com/recharts/recharts/blob/master/demo/component/BarChart.js) using `d3-scale`.

Maybe it would be worth incorporating this into the examples?

**Comment by xile611** [comment]
Try [this demo](http://recharts.org/#/en-US/examples/CustomShapeBarChart)
