### ISSUE TITLE
[Bug] Custom label for Bar has wrong horizontal position

### ISSUE THREAD

**Issue by michalg42** [recharts/recharts#810]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
Customized label for BarChart has wrong position and with given data (x, y, width, height, etc.) it's not possible to set it in the horizontal center of bar. (It worked this way in recharts v0.20.5)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).
http://jsfiddle.net/teuwcpcL/1/
It's example from recharts.org that has added label to one of the bars.

## What is the expected behavior?
In func arguments it either has x that centers it horizontally, or there is one more argument with width of bar to calculate middle on your own.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.0.0-alpha.2, newest version of Chrome, Linux Mint.
It worked in v0.20.5

**Comment by brendonco** [comment]
Got the same problem with custom label horizontal positioning. Should center the position of the text e.g. textAnchor="middle".

```
const CustomLabel = ({
  x,
  y,
  value,
  fill,
  ...props
}) =>
  <text 
   x={x} 
   y={y}
   dy={-10}
   fill={fill}
   fontSize='1.2em'
   textAnchor="middle">
    {value}
  </text>
```

**Comment by xile611** [comment]
use the default label and change the [position](http://recharts.org/#/en-US/api/Label)  :
```jsx
<Bar  label={{ position: 'top', offset: 10 }} />
```

or calculate the coordinate by
```
textX = x + width / 2
textY = y
```

Check this [demo](http://jsfiddle.net/wou4ckza/)
