### ISSUE TITLE
axis label components not rendering

### ISSUE THREAD

**Issue by MiLeung** [recharts/recharts#812]
e.g.

`<YAxis strokeWidth={3} label={<h1>Test</h1>} />`

does not render a Test header

**Comment by huxiaoyun** [comment]
if u search the dom element , u'll find the label  element exist， but u need to set it's x , y to show it .

for example,    http://jsfiddle.net/huxiaoyun/x2m72age/1/

`<XAxis dataKey="name" label={<text><tspan x="260" y="360">hehe</tspan></text>}/>`

**Comment by ravenberg** [comment]
@huxiaoyun Thank you for your example. How can configure the label to not be on top of the ticks?

**Comment by xile611** [comment]
@ravenberg Change the `position` of label

Check the doc of [label position](http://recharts.org/#/en-US/api/Label)
```jsx
<XAxis dataKey="name" label={{value:'hehe',stroke: 'red',fontSize:20, position: 'insideBottom'}}/>

```
