### ISSUE TITLE
How do you display the XAxis with a date format

### ISSUE THREAD

**Issue by patientplatypus** [recharts/recharts#815]
This issue https://github.com/recharts/recharts/issues/612 was never properly resolved and I am running into the same problem. dateFormat is not defined and I'm getting an error when I try and replicate the code. Please address.

**Comment by JacquiManzi** [comment]
@patientplatypus I think you misunderstood that issue.

`dateFormat` in the issue you listed above is a function that you are required to define yourself.

example:
```     <XAxis
                dataKey="x"
                tickFormatter={formatXAxis(timeframe)}
         />
```
function formatXAxis(timeframe) {
... 
}

**Comment by huxiaoyun** [comment]
just follow @JacquiManzi  's demo 

`
<XAxis dataKey="name" tickFormatter={this.formatXAxis}/>
`

`
formatXAxis = (tickItem) => {
    // do something to format tick label
}
`

**Comment by daneshgit** [comment]
<XAxis dataKey="date" tickFormatter={d3.timeFormat('%I:%M:%S')}/>

**Comment by rushikadam12** [comment]
<XAxis dataKey="date"     tickFormatter={(date) => new Date(date).toLocaleDateString('en-UB')}/>
//this will give you date OR if you want  for time just use toLocaleTimeString()
