### ISSUE TITLE
[Bug] Legend doesn't show icons or colors when using payload

### ISSUE THREAD

**Issue by rapmue** [recharts/recharts#818]
When using Legend in a LineChart and declaring a payload instead of using names on the Lines, no icon is shown when choosing "line" and no color is inherited from the line when using "square" or so.

Base of the tests: http://jsfiddle.net/hkj1h0o7/ Where you can see, that the Legend is correct, but without meaningful names. One could use the property name on the component Line to achieve the desired results. But if you want to switch the legend type per data serie you have to use the payload property on Legend.

As you can see: http://jsfiddle.net/hkj1h0o7/1/ the legend does not inherit colors and is also missing the line.

If I add the color forcefully to the payload, everything works as expected: http://jsfiddle.net/hkj1h0o7/2/

But I think one can not force a user to specify the color twice...

**Comment by catzilla-007** [comment]
also encountered this issue. workaround is explicitly adding the color to the payload

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue guide.
