### ISSUE TITLE
Need click events on the data of Pi Charts

### ISSUE THREAD

**Issue by KalpanaPagariya** [recharts/recharts#819]
## Do you want to request a feature or report a bug?
Feature
## What is the current behavior?
Right now we have click event on the whole pie. 
Instead of that, can we have click events on the different parts of pie.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
recharts version: 1.0.0-alpha.2
OS: Windows 10

**Comment by jozefpetro** [comment]
Hello, I don't think that this is neccesary to implement on Pie component, because it can be easily achieved by rendering each part manually using Cell component inside of Pie. Than you can access events on every single part of your pie chart. This code shows just an idea of how it can be done :) 
```
<PieChart>
    <Pie data={data} dataKey="xxx" innerRadius={60}>
                {data.map((entry, index) => (
                  <Cell
                    key={entry.id}
                    onClick={(e) => { HERE YOU CAN HANDLE EVENTS RELATED TO EACH PART }}
                  />
                ))}
    </Pie>
</PieChart>
```

**Comment by KalpanaPagariya** [comment]
Thanks @jozefpetro , I will try to do this.

**Comment by Atharv-02** [comment]
How can we raise a part of pie chart using the onClick function

**Comment by ckifer** [comment]
Hi @Atharv-02 

You can use `activeIndex` and `activeShape` similar to this sandbox (except with onClick)

https://codesandbox.io/s/pie-chart-of-two-levels-forked-jgzfmh?file=/src/App.tsx

Since this issue is closed, if this demo doesn't help please create a new issue in the repo so it is more visible to those that can help
