### ISSUE TITLE
Feature request: animate on data change

### ISSUE THREAD

**Issue by ingro** [recharts/recharts#82]
Hello! First of all thanks for this excellent chart library!
A little thing that I'm missing is the option to animate again the chart when the underlying data change, to provide a visual feedback to the user when this happens.

Actually I've achieved this in an hacky way, by wrapping the chart in a component and force a full redraw of the chart by changing the component state inside the `componentWillReceiveProps` callback, but that's not an ideal solution.

Do you think this is a feature that could be implemented in the future?

**Comment by xile611** [comment]
Yeah,  this feature is being planned. And `Treemap` has implemented this feature.
@jasonHzq

**Comment by ingro** [comment]
Cool, thanks for the info!

**Comment by xile611** [comment]
Done in v0.10.4.

**Comment by ingro** [comment]
Great, I will try it asap! :)

**Comment by tsnevillecom** [comment]
It seems to only animate the last bar or line when the data is changed. The other data shows up instantaneously. http://jsfiddle.net/x1yoboc7/249/
