### ISSUE TITLE
Ability to set multiple y-axes

### ISSUE THREAD

**Issue by swiftfoot** [recharts/recharts#821]
## Do you want to request a feature or report a bug?
Request a feature

## What is the current behavior?
currently a graph can only have 1 y-axis, I'd like to compare multiple types of data on the same graph by specifying a y-axis for a particular line, and allowing multiple y-axises to be specified as long as they have unique datakey elements

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).

An example of what I would want: 
http://jsfiddle.net/x1yoboc7/902/

**Comment by swiftfoot** [comment]
https://github.com/recharts/recharts/issues/174

This does work, good example listed above..

**Comment by IsmaelTerreno** [comment]
To set multiple axis the main thing to take account is the `yAxisId` to make the relation between the chart and the axis like in the following example:

http://recharts.org/en-US/examples/BiaxialLineChart

**Comment by redimongo** [comment]
This seems not to work for AreaChart - Any suggestion?
