### ISSUE TITLE
I am not able to show the status of pie chart 

### ISSUE THREAD

**Issue by KalpanaPagariya** [recharts/recharts#822]
## Do you want to request a feature or report a bug?
Request

## What is the current behavior?
I am not able to show the status of pie chart where we show like colorwise filled checckbox and its meaning either below or above pie chart.
![image](https://user-images.githubusercontent.com/18165261/29002880-194a94d4-7aca-11e7-8e7b-879011b36819.png)

## What is the expected behavior?
![image](https://user-images.githubusercontent.com/18165261/29002889-452113a8-7aca-11e7-99ef-d2b90bf880bd.png)

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts version: 1.0.7
Windows 10

**Comment by xile611** [comment]
@KalpanaPagariya Reopen this issue if more information can be supported.

Maybe you can check the [demos](http://recharts.org/#/en-US/examples/CustomActiveShapePieChart) of PieChart in our website.
