### ISSUE TITLE
Radar Chart Polygon Difficult To See when Adjacent Radars are Zero

### ISSUE THREAD

**Issue by nrlewis** [recharts/recharts#826]
## Do you want to request a feature or report a bug?
Request a Feature? 

## What is the current behavior?
In Radar Chart, when one axis has a value, but the the two adjacent axis have a zero value, then the Radar object displays a thin line that is difficult to see:

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).

https://jsfiddle.net/404eth22/

## What is the expected behavior?

A clearer shape  that maybe fans out along the center

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

 "recharts": "^1.0.0-alpha.2",

I think this is the current expected behavior

**Comment by balthazar** [comment]
A radar chart is a.. radar chart. Unless you provide a pull request implementing this "feature" it's very unlikely someone else will do it for you. Are you sure a radar chart is the appropriate chart in your case? You could have a simple conditional switching to another type of chart if your data size is less than 3 pretty easily.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
