### ISSUE TITLE
RadialBarChart angle and direction not working

### ISSUE THREAD

**Issue by aryalprakash** [recharts/recharts#827]
How should I use startAngle and endAngle in RadialBarChart?

It's not working the way stated on example. I don't see any effect on changing the values.

Also clockWise set to false doesn't rotate chart anticlockwise.

**Comment by NicolasThebaud** [comment]
I too noticed the same behaviour as stated above.
I tried to modify the exemple fiddle, but when changing the 'startAngle', 'endAngle' or 'clockWise', nothing seems to be happening.

**Comment by xile611** [comment]
Duplicated to #955
