### ISSUE TITLE
Labels shomtimes not show

### ISSUE THREAD

**Issue by totaki** [recharts/recharts#829]
## Do you want to request a feature or report a bug?
bug
## What is the current behavior?
Some times i dont see label

![2017-08-11 15-25-51](https://user-images.githubusercontent.com/6254062/29213110-7c84de72-7eaa-11e7-8410-8650306c340e.png)
![2017-08-11 15-26-13](https://user-images.githubusercontent.com/6254062/29213231-0f19c8d8-7eab-11e7-8510-704fe2988c66.png)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).

```
const _dataTypesMap = {
    "0": () => <Bar dataKey="clientQuestions" fill="#6aafff" minPointSize={1} />,
    "1": () => <Bar dataKey="arPercent" fill="#b8e986" minPointSize={1} label={{ fill: 'red', fontSize: 20, dataKey: "nps" }}/>,
    "2": () => <Bar dataKey="awsPercent" fill="#f16c97" minPointSize={1} />
};

const _getCharts = (dataTypes) => {
    return dataTypes.map(t => _dataTypesMap[t]())
};

const DashboardChart = ({ stats, dataTypes }) => {
  return (
      <BarChart width={1008} height={200} data={stats}
          margin={{ top: 5, right: 5, left: 5, bottom: 5 }}>
          <Tooltip content={<_Tooltip/>} payload={stats}/>
          { _getCharts(dataTypes) }
      </BarChart>
  )
};
```

## What is the expected behavior?
I want see all times label

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
rechart - 1.0.0-alpha.1
OS Ubuntu 16.04 - 64x
Browser Firefox 56.0b1 (64-бит)

**Comment by eldyvoon** [comment]
@totaki You have to specify `label` prop in the Bar component, refer to label in the api doc for more customization. 

working example: http://jsfiddle.net/qbmg1567/541/

**Comment by totaki** [comment]
I try set only label prop without props, i try set CustomLabel and have same result, label sometimes show or sometimes not.

**Comment by eldyvoon** [comment]
@totaki I can't reproduce the bug that you're saying in the jsfiddle, I can see the label all the time. If you load data via ajax try set prop of `isAnimationActiveBoolean` to false.

**Comment by totaki** [comment]
Thank you it's work

**Comment by silentbobbert** [comment]
The JS filddle doesnt work, nothing is rendered, nevermind the labels. I have intermittent display issues. When my home page loads, there is no animation and no labels. When I change state, unrelated to the pie chart (not passing the changing state as props to the chart), the chart seems to reanimate and display the labels. It seems its only the initial render where the animation has stopped working and the labels are not shown.

**Comment by shreniksv** [comment]
I am also facing the same issue. Labels do not render on initial render. It works fine when animation is disabled but I would like to have both animation and labels.

**Comment by shreniksv** [comment]
@totaki & @silentbobbert: Did you find any solution to label issue instead of disabling animation?

**Comment by silentbobbert** [comment]
I am still using

`isAnimationActive={false}`

Which allows my labels to be rendered. I left myself this comment:

`//should be able to remove this prop, I think there is a bug in Pie stopping labels from rendering. This is a temp fix.`

So it looks like I made a note of the issue, and moved onto something else!

**Comment by jks8787** [comment]
I am also having this same issue, and at the moment the only way to keep the labels from disappearing is to have  isAnimationActive `false` :(

**Comment by ebarns** [comment]
This issue is present in "recharts": "^1.0.0-beta.10",

I'd prefer to have the animations but turning them off did the trick. The labels show up once the next render is triggered on the label.
any solutions other than no animation?

**Comment by pengcheng95** [comment]
Hi, has there been a fix to the labels other than having isAnimationActive false? I am currently using recharts 1.1.0 and it still fails to display the labels if I hover to quickly over the chart on initial load

**Comment by osvaldoalvaradodev** [comment]
Same problem.
¿any way to stay TRUE animation and label visibles when update component?

When i disable animation.... less UX

thanks for this awesome lib! :)

**Comment by Perogy** [comment]
Also having a weird issue with this for barchart. At first I had my constant graph data defined in the render function itself, the labels didn't show up unless I disabled animation. Moved my graph data outside of the render function and it started to work.

**Comment by andrefox333** [comment]
> isAnimationActiveBoolean

Which component do you set this prop? I'm also setting the data via an api call and sometimes the labels appear but most of the time it's nowhere to be found.

**Comment by andrefox333** [comment]
> Also having a weird issue with this for barchart. At first I had my constant graph data defined in the render function itself, the labels didn't show up unless I disabled animation. Moved my graph data outside of the render function and it started to work.

What do you mean outside of the render function?

**Comment by Perogy** [comment]
> What do you mean outside of the render function?

I think it was something like this...

**inside render function (doesn't work)**

```javascript
class Test extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    let graphData = [];
    
    for (let i = 0; i < this.props.data.arr.length; i++) {
      graphData.push({data1: this.props.data.data1[i], data2: this.props.data.data2[i]});
    }

    return (
      <BarChart width={graphWidth} height={400} data={graphData}>
        <XAxis allowDecimals={false} dataKey="data1"/>
        <YAxis allowDecimals={false} hide={true}/>
        <Bar maxBarSize={50} label={{position: "top"}} fill="#8884d8" dataKey="data2"/>
      </BarChart>
    );
  }
}
```

**outside render function (does work)**

```javascript
class Test extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      graphData: []
    };
  }

  componentWillMount() {
    this.setState((state) => {
      let newGraphData = [];
      for (let i = 0; i < this.props.data.arr.length; i++) {
        graphData.push({data1: this.props.data.data1[i], data2: this.props.data.data2[i]});
      }
      return {
        graphData: newGraphData
      };
    });
  }

  render() {
    return (
      <BarChart width={graphWidth} height={400} data={this.state.graphData}>
        <XAxis allowDecimals={false} dataKey="data1"/>
        <YAxis allowDecimals={false} hide={true}/>
        <Bar maxBarSize={50} label={{position: "top"}} fill="#8884d8" dataKey="data2"/>
      </BarChart>
    );
  }
}
```

When the graph data is in the state of the component before render it seems to work.

**Comment by FishwithCat** [comment]
In React 16.9.0
Label works well when wrapped with React.memo 
e.g:
`const chart = Rect.memo((props) => <MyBarchart {...props}>, 
(prevProps, nextProps) => 
     Immutable.is(Immutable.fromJS(nextProps.data), Immutable.fromJS(prevProps.data))
)`

**Comment by avinashsingh953** [comment]
Render the chart only after data is loaded use

`const data = []

const MyChart = ({ passedData }) => {
  while (data.length > 0) {
    data.pop()
  }

  passedData.each((item) => (
    data.push(item)
  )

  return (
    {data && <PieChart>
      <Pie data={data} />
    </PieChart>}
  )
}`

**Comment by avinashsingh953** [comment]
Render chart only if data is not null

`const data = []`
`const MyChart = ({ passedData }) => {`
          `while (data.length > 0) { `
                   `data.pop()`
  `}`

 ` passedData.each((item) => (`
    `data.push(item)`
 ` )`

  `return (`
    **`{data &&<PieChart>`
     ` <Pie data={data} />`
  `  </PieChart>}`**
 ` )`
`}`

**Comment by deepubansal** [comment]
`onAnimationEnd={()=>{this.setState({});}}` this seems to have done the trick !

**Comment by YuJianrong** [comment]
Have the same issue, why this issue is closed?

**Comment by PXke** [comment]
Same issue here,  I took a quick look to the code, but it seems animation is relying on react-smooth. So probably an error there? Or in the way it is used?

**Comment by apedroferreira** [comment]
same issue here, looks like the chart animation conflicts with other animations in the page sometimes and ends up not showing the labels when the chart animation ends

**Comment by SoYoung210** [comment]
Hi, I have same issue. I used hooks like this and it works well.

```tsx
const [isAnimation, setIsAnimation] = useState(true);

const [activeIndex, setActiveIndex ] = useState(-1);

return (
      <PieChart margin={{ top: 0, bottom: 20 }} width={ 300 } height={ 180 }>
        <Pie
          data={ sortedDataByValue }
          innerRadius={ 40 }
          outerRadius={ 80 }
          startAngle={ 90 }
          endAngle={ -360 }
          isAnimationActive={ isAnimation }
          onAnimationEnd={ () => setIsAnimation(false) }
          dataKey='value'
          stroke=''
          labelLine={ false }
          label={ ({
            cx,
            cy,
            midAngle,
            innerRadius,
            outerRadius,
            value,
            index,
          }: PieLabelRenderProps) => {
            /* some logics */
           const isActive = activeIndex === index;

            return (
              isActive
                ? (
                  <CustomTooltip
                    position={{ x, y }}
                    color={ fillColor }
                    value={ value }
                  />
                )
                : <></>
            );
          } }
        >
          { sortedDataByValue.map((data, index) => renderCell(data, index, setActiveIndex)) }
        </Pie>
      </PieChart>
)
```

**Comment by gabrielmicko** [comment]
This is still an issue why this is closed?

**Comment by hu1da** [comment]
I'm using "recharts": "1.8.5" some times labels are shown only after  window resize. I've set isAnimationActive={false} .it seems do the trick but I'd prefer more explicit solution

**Comment by gabrielmicko** [comment]
I only found a workaround that you always rerender no mattter what by adding `key="makeid()"` to the  `ResponsiveContainer`. That solved my problem until it's fixed.

**Comment by HardGITer** [comment]
I found a good workaround for this problem.
You can render the bar label directly in the **Bar** component of the chart. and chart labels will be rendered along with the columns. And yes, in the rendering of the columns you can get their values from props with passed in CustomBar key. in my example it is a **barDataKey**

here is code example

custom bar:
```js
const CustomBar = ({
  x,
  y,
  width,
  height,
  className,
  barDataKey,
  ...props
}) => {
  const yAxisShift = -4;
  const xAxisShift = 3.5;
  return (
    <g>
      <text
        styleName={className}
        x={x}
        y={y}
        dy={yAxisShift}
        dx={xAxisShift}
        textAnchor="middle"
      >
        {props[barDataKey]}
      </text>
      <rect styleName={className} x={x} y={y} width={width} height={height} />
    </g>
  );
};
```

bars config: 
```js
const barsConfig = [{
  dataKey: 'first_key',
  label: "label text",
  className: 'first-key-bar',
},
{
  dataKey: 'second_key',
   label: "label text",
  className: 'second-key-bar',
}];
```

method for rendering bars:
```js
const renderBars = () =>
    barsConfig &&
    barsConfig.map(item => (
      <Bar
        shape={
          <CustomBar className={item.className} barDataKey={item.dataKey} />
        }
        barSize={DEFAULT_BAR_SIZE}
        key={item.dataKey}
        dataKey={item.dataKey}
      />
    ));
```

**Comment by hmtri1011** [comment]
it still persists on v1.8.5, not sure why it was closed

**Comment by Shubham-DK** [comment]
Still facing the issue please reopen the issue, as now we have to turn of the animation inorder to show the label.
it works fine in JS Fiddle but not working in my project.

`import React from "react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  LabelList,
} from "recharts";
const OrchestrationWorklistPage = (props) => {
  const data = [
    { name: "10-06-2020", withFallout: 2400, withoutFallout: 2400 },
    { name: "14-06-2020", withFallout: 1398, withoutFallout: 2210 },
    { name: "15-06-2020", withFallout: 9800, withoutFallout: 2290 },
    { name: "17-06-2020", withFallout: 3908, withoutFallout: 2000 },
  ];
  return (
    <>
      
      <BarChart
        width={800}
        height={400}
        data={data}
        margin={{ top: 20, right: 30, left: 20, bottom: 5 }}
       
      >
        <CartesianGrid strokeDasharray="3 3" />
        <XAxis dataKey="name" label={{ value: "CAD", position: "bottom" }} />
        <YAxis
          label={{ value: "COUNTS", angle: -90, position: "insideLeft" }}
        />
        <Tooltip />
        <Legend align="right" />
        <Bar dataKey="withFallout" stackId="a" fill="#8884d8"  isAnimationActive={true}>
          <LabelList dataKey="withFallout"  position="inside"/>
        </Bar>
        <Bar dataKey="withoutFallout" stackId="a" fill="#82ca9d"  isAnimationActive={false}>
          <LabelList dataKey="withoutFallout" position="inside" />
        </Bar>
      </BarChart>
    </>
  );
};

export default OrchestrationWorklistPage;
`

**Comment by talkhunat** [comment]
@SoYoung210 Thanks for the example, it worked for me!

**Comment by VahidBo** [comment]
I have the same issue.

**Comment by migcv** [comment]
This issue continues to happen, I'm currently in the latest version, version `2.0.4`. To make the labels always show I need to pass the prop `isAnimationActive={false}` to the `Pie` component. It would be nice to re-open this issue.

**Comment by avindra** [comment]
The animation problems have been discussed across various issues.

It stems from `recharts/react-smooth`: https://github.com/recharts/react-smooth/issues/44

**Comment by rahulraj-120799** [comment]
Thanks this worked

**Comment by RandomExplosion** [comment]
Hit something simmilar here today

**Comment by Dusankol** [comment]
Wrap your chart into ResponsiveContainer and set key. I had the same problem with BarChart, but this solved the issue
<ResponsiveContainer key={uuid()}>
<Chart />
.....
</ResponsiveContainer>

**Comment by talaikis** [comment]
`isAnimationActive={false}` works for <Bar />, Recharts 2.0.8

**Comment by Darren120** [comment]
doesn't work when adding legend along with tooltip.

**Comment by AndreasGZ** [comment]
I found out for me, in my components, although the Labels seems to not be rendered, actually when I check the Component-Tree, the LabelList and Labels exist. But the size of the LabelList is 0px 0px, so I can't see them.
Maybe there is a chance to add a check to the LabelList-Component.

**Comment by Loiklak** [comment]
> The animation problems have been discussed across various issues.
> 
> It stems from `recharts/react-smooth`: [recharts/react-smooth#44](https://github.com/recharts/react-smooth/issues/44)

In case you did not read the forementioned issue like me, try to check if you are not in this situation :

> Ensure your parent component does not rerender during the animation if possible. For me, I found that a parent component issue was causing my chart to rerender too often. That fix is not shown here.

Fixing the parent rerender during the animation worked for me 🥳

**Comment by chilled-capybara** [comment]
> Ensure your parent component does not rerender during the animation if possible. For me, I found that a parent component issue was causing my chart to rerender too often.

A solution/workaround I came up with is to protect the chart component from unnecessary rerenders by [memomising](https://reactjs.org/docs/react-api.html#reactmemo) the props, where that upstream rerender is unavoidable. This avoids the need to disable or override animation props.

```tsx
const Chart = React.memo(
  (props: Props): JSX.Element => <ChartyGoodness /* props */ />,
  (prevProps, nextProps) => myFavouriteDeepEquals(prevProps, nextProps)
);
```

or more succinctly;
```tsx
const Chart = React.memo(
  (props: Props): JSX.Element => <ChartyGoodness /* props */ />,
  myFavouriteDeepEquals
);
```

If you only need a shallow compare you can omit the second argument,

**Comment by rwieruch** [comment]
Bug still there in `2.1.13`. @migcv work around still works.

**Comment by nazkeyramazan** [comment]
rechart-'2.1.14' version, bug still there. when use data for chart is work well, but if fetch data from API labels of chart not show
