### ISSUE TITLE
XAxis don't show first item dataKey value as label

### ISSUE THREAD

**Issue by jetpack3331** [recharts/recharts#831]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
XAxis don't show first item as label

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.0.0-alpha.3

Code here:
```
const data = [
			{name: 'Včera', value: 2200},
			{name: 'Dnes', value: 2600},
			{name: 'Zítra', value: 2300}
		]

<LineChart width={200} height={100} data={data}>
   <Line type="monotone" dataKey="value" stroke="#8884d8" />
   <XAxis dataKey="name"  />
</LineChart>

```

Image of rendered code

![screen_recharts](https://user-images.githubusercontent.com/3585148/29251961-0fbbd456-805f-11e7-9660-4973b6aa037d.png)

**Comment by nathmack** [comment]
Did you figure this out?

**Comment by nathmack** [comment]
figure it out. Passing the prop `interval="preserveStartEnd"` to XAxis resolves it

**Comment by jetpack3331** [comment]
Thx @nathmack
