### ISSUE TITLE
Text is selected when using the brush

### ISSUE THREAD

**Issue by hashwin** [recharts/recharts#832]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?

When dragging the brush and the cursor moves outside of the brush area, text gets selected causing the brush dragging to stop. So if not dragging explicitly inside the brush, the experience seems very buggy.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).

![aug-14-2017 00-03-30](https://user-images.githubusercontent.com/406115/29252401-0fa14e86-8084-11e7-9207-56f3f316483b.gif)

Can be reproduced here: http://recharts.org/#/en-US/examples/BrushBarChart
## What is the expected behavior?

Text should not be selected when dragging the cursor using the Brush and should continue to work on dragging as long as the mouse button is pressed.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Mac OS 10.12.6
Chrome  60.0.3112.90 
Recharts 0.22.4

**Comment by hashwin** [comment]
FWIW This is also implemented with d3 and works really well (with added benefit of scroll to zoom):
https://bl.ocks.org/mbostock/34f08d5e11952a80609169b7917d4172

![aug-14-2017 00-15-46](https://user-images.githubusercontent.com/406115/29252481-cc61e44e-8085-11e7-8871-1e7b8e83cb42.gif)

**Comment by li-xinyang** [comment]
A simple CSS trick could solve this issue by setting the style property of text element to `user-select: none`.

**Comment by xile611** [comment]
@hashwin Just add `user-select: none;`  as @li-xinyang has said.

**Comment by hashwin** [comment]
@xile611 @li-xinyang While it does stop text from being selected, I still cannot drag while the cursor is outside the brush, as demonstrated in the gif I posted, leading to a poor UX when using it. Notice the cursor in the d3 gif above when compared to the one here:

![aug-21-2017 23-48-39](https://user-images.githubusercontent.com/406115/29532578-6d3b5e0e-86cb-11e7-9d61-be5978fa8c4b.gif)

**Comment by modsushi** [comment]
this is such a basic UX requirement really, even bostocks examples have it right.

**Comment by bmtdh** [comment]
Did anyone come up with a solution to this problem?
