### ISSUE TITLE
BarChart Label center on top of Bar

### ISSUE THREAD

**Issue by brendonco** [recharts/recharts#835]
I use custom bar label sample from: [https://github.com/recharts/recharts.org/blob/master/src/components/GuideView/CustomBarLabel.js](https://github.com/recharts/recharts.org/blob/master/src/components/GuideView/CustomBarLabel.js)

```
const CustomBarLabel = ({ payload, x, y, value }) => {
  return <text x={x} y={y} fill="#666" textAnchor="middle" dy={-6}>{value}</text>;
}

CustomBarLabel.propTypes = {
  x: PropTypes.number,
  y: PropTypes.number,
  payload: PropTypes.object,
};
```

<img width="562" alt="screen shot 2017-08-15 at 4 15 38 pm" src="https://user-images.githubusercontent.com/6521691/29307582-0b7fea18-81d5-11e7-9a73-3122c2eb0cba.png">

textAnchor="middle" should center the text. Unless need to do extra calculation about the bar width, x, y and transform?

Not Working: http://jsfiddle.net/qbmg1567/544/

Using old version of rechart recharts@0.12.7:

Working: 
https://codepen.io/smartyboots/pen/KmdYLr

**Comment by nweinstein7** [comment]
I was able to get your example working by passing in the barWidth and then doing 

```const BarLabel = ({ payload, x, y, value, barWidth }) => {
  return (
    <text x={x + barWidth / 2} y={y} fill="#777" dy={-6} textAnchor="middle">
      {value}
    </text>
    );
}
```
