### ISSUE TITLE
Brush width does not change

### ISSUE THREAD

**Issue by donszek** [recharts/recharts#837]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
The width of the brush does not change

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).
http://jsfiddle.net/wn4jhdu5/14/

## What is the expected behavior?
Brush to change width when i change the width props

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
latest

**Comment by huxiaoyun** [comment]
OK... i am following this question...

**Comment by huxiaoyun** [comment]
we fixed already, brush will use  user props first priority,  it will update soon... thank u for ur report.

**Comment by donszek** [comment]
@huxiaoyun thanks for the update and clarification
