### ISSUE TITLE
how to custom y-axis'label?

### ISSUE THREAD

**Issue by wonghoman** [recharts/recharts#838]
Hi, how to custom y-axis'label in <YAxis type="number">?
I just want to add an unit(%) after y-axis'label under type="number" circumstances, like:
90%|
........ |
60%|
........ |
30%|————————————————————————————
            one          two         three        four         five

I just want to add % after 30/60/90;
I expect it's type="number" not type="category";

how can i do? I'm looking forward to your reply.

**Comment by xile611** [comment]
@wonghoman  

Add props `tickFormatter` to `YAxis`.
[demo](http://jsfiddle.net/nrt2a6ec/)

**Comment by wonghoman** [comment]
@xile611 Thanks for your reply!
