### ISSUE TITLE
Brush resets even on data reference change

### ISSUE THREAD

**Issue by Heedster** [recharts/recharts#839]
## Do you want to request a feature or report a bug?
Bug

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem 
http://jsfiddle.net/wn4jhdu5/15/

## What is the expected behavior?
Brush  should not change.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
js fiddle uses the latest version, we use 0.22.4 internally in our project, happens in both.

**Comment by donszek** [comment]
Yes, I agree with Heedster. I think brush's startIndex and endIndex should not be changed when the datareference or datakey change. 

@xile611 Does this sound like "the expected behaviour" to you too?

**Comment by ZephD** [comment]
This is like issue #401. It's back.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
