### ISSUE TITLE
Allow setting width as a percentage

### ISSUE THREAD

**Issue by aarohmankad** [recharts/recharts#841]
## Do you want to request a feature or report a bug?

Request a feature

## What is the current behavior?

The width and height props only accept numbers, not strings with percentages.

## What is the expected behavior?

To allow the width and height props to be percentage strings:

```jsx
<AreaChart
  width={ "50%" }
  height={ "35%" }
  data={ data }>
    ...
</AreaChart>
```

**Comment by howardya** [comment]
@aarohmankad  If it helps, you can use ResponsiveContainer. You can do something like,

```jsx
<div style={{ width: '50%', height: '35%'}}>
  <ResponsiveContainer>
    <AreaChart> ... </AreaChart>
  </ResponsiveContainer>
</div>
```
