### ISSUE TITLE
Categorical Colors to Multi-Line Chart

### ISSUE THREAD

**Issue by CharukaK** [recharts/recharts#842]
## Do you want to request a feature or report a bug?
request a feature

## What is the current behavior?
There's no proper way to generate multi line chart based on a category value in the data set

## What is the expected behavior?
In a scenario with a data set similar to one given below,
```javascript
data = [
      {name: 'Rotary', rpm: 4000, torque: 2400, amt: 2400},
      {name: 'Piston', rpm: 3000, torque: 1398, amt: 2210},
      {name: 'Rotary', rpm: 2000, torque: 9800, amt: 2290},
      {name: 'Piston', rpm: 2780, torque: 3908, amt: 2000},
      {name: 'Rotary', rpm: 1890, torque: 4800, amt: 2181},
      {name: 'Piston', rpm: 2390, torque: 3800, amt: 2500},
      {name: 'Rotart', rpm: 3490, torque: 4300, amt: 2100},
];
```

Recharts should be able to generate a graph like this,
![screenshot from 2017-08-22 13-53-56](https://user-images.githubusercontent.com/18122888/29557830-eed07f4a-8747-11e7-8b17-e7e7b8bea5bf.png)

based on the given dataKey to categorize the data

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts? 
1.0.0-alpha.3

my current approach(http://jsfiddle.net/CharukaK/tce4s5p8/1/) for the problem is to generate rechart friendly data set based on the data
assigning the y-axis value to the category key and generate the graph,

```javascript
data = [
      {Rotary:2400, rpm: 4000},
      {Piston:1398, rpm: 3000},
      ...
];
```
for the line:
```javascript
<Line type="monotone" connectNulls={true} dataKey="Rotary" stroke="#8884d8" />
<Line type="monotone" connectNulls={true} dataKey="Piston" stroke="#82ca9d" />
```
This approach works however in the case of null value I also need a disconnected line similar to,
![screenshot from 2017-08-22 16-46-51](https://user-images.githubusercontent.com/18122888/29563048-8dbb5736-8759-11e7-8fa9-bbdf98e5cb31.png)

I tried with the scatter plot it works for a scenario where the x-Axis is numerical but fails in a case where the x Axis type is a category

I would like to know if recharts supports this kind of a scenario or is there an alternative way to achieve this.
It would be really useful if this can be achieved from the charting library

**Comment by JonasJonny** [comment]
Maybe this https://github.com/recharts/recharts/issues/866 could help you.

I searched for a solution how to draw multi lines like you want to achieve but not for an every  axis X value and http://jsfiddle.net/qbmg1567/602/ by @zephD is the solution. 
But his approach needed `connectNulls` to solve my own problem. 

Thanks to both.

**Comment by ZephD** [comment]
"Solution" -> "Workaround" :)

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue guide.

**Comment by callmedeeray** [comment]
The response, "Please try the latest version," does not work for every single issue because this feature is still missing in the current version.  Thus this should not have been closed.
