### ISSUE TITLE
Question: BarChart left margin

### ISSUE THREAD

**Issue by qborreda** [recharts/recharts#843]
I'm trying to have my BarChart(s) centered inside a `Responsive Container`, but they keep leaving a lot of space to the left of the YAxis. 

I have tried forcing css margins, to no avail, and I haven't even been able to locate a single rule that makes this margin larger than it should, or weird paddings on `rechart-surface` .. 
What can I do about it?

[Click for an imgur image of the issue](http://imgur.com/OPePWPa)

**Comment by aarohmankad** [comment]
I am also encountering this issue, and would really like to be able to change the amount of margin on the left. (Ideally remove it altogether.)

![image](https://user-images.githubusercontent.com/3311321/29630690-dea60fa4-87f1-11e7-992a-5fc61d5ea957.png)

**Comment by ledicana** [comment]
The temporary solution I use is to change the margin of the whole chart. I am using AreaChart, and have set the left margin of the chart to, e.g. -20px. 
But the solution isn't good enough, since it doesn't scale with the number of digits on YAxis. I couldn't find a way to get the domain values or at least dataMax, so I can adjust the margin accordiong to the number of digits.

**Comment by jetpack3331** [comment]
Same issue here. I'm dealing same problem with LineChart. There is lot of space on left side of chart

**Comment by InSuperposition** [comment]
I see the issue on the `<LineChart />` component when I don't pass the `mirror` prop, however the margins are correct if I set the that prop to `true`

**Comment by Antlitz** [comment]
<LineChart margin={{right: 15, left: 15}} ...>
...
<YAxis ... tick={{dx: -15}}
</LineChart>

some hack :(

**Comment by codenameyau** [comment]
The default width for YAxis is 60, so I solved it by setting it to 40. You can also dynamically set the width to avoid clipping.

```javascript
<YAxis width={40} />
```

**Comment by jefferymills** [comment]
@codenameyau How would you go about dynamically setting the width? I'm trying to get rid of any extra space that's not needed for the ticks. But I need to know what the tick labels are going to be first so I can determine how much width is needed.

**Comment by maplethorpej** [comment]
@jefferymills You'd probably have to determine the maximum width of the y-axis labels based on character length. That is, loop through the list, find the longest string and use that to approximate the YAxis width dynamically.

**Comment by disname** [comment]
Facing the same problem. "Max-width" solution will fix this issue from my point of view

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.

**Comment by myyellowshoe** [comment]
Still getting the extra left padding in v1.8.5. Setting the width on the YAxis mentioned by @codenameyau does the trick. Though would prefer something a little more dynamic.

**Comment by emanuellresende** [comment]
yaxis comes with a default width of 40 reduce it to 20 which will remove that margin

<Yaxis width={ 20 }
