### ISSUE TITLE
Centered tooltip on BarChart

### ISSUE THREAD

**Issue by dbenfouzari** [recharts/recharts#844]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
I want my Tooltip to be centered on a bar in my BarChart. Actually it's right aligned and I have to manually position it. But if my Tooltip grows I have to manually set its new offset. Is it possible to automatically center it to my bar ?

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).
http://jsfiddle.net/d475hbmn/

**Comment by xile611** [comment]
Sorry, not supported yet. It's recommended to use customized `content` of `Tooltip` to cover default tooltip.
