### ISSUE TITLE
has support a  four-quadrant LineChart?

### ISSUE THREAD

**Issue by ccjoe** [recharts/recharts#845]
or y axis value has less than 0,  it's lower than x axis, EG:

![image](https://user-images.githubusercontent.com/4242643/29603024-1928b514-8815-11e7-8201-1833abae6fc4.png)

**Comment by xile611** [comment]
@ccjoe 
Check this [demo](http://jsfiddle.net/u3xdu0sq/)
y axis value can has value less than 0.
