### ISSUE TITLE
Question: Handling 0% case in pie graph

### ISSUE THREAD

**Issue by ghost** [recharts/recharts#848]
Question - Is it expected that a pie graph does not render when all values are zero?

Sample code:
```
const {PieChart, Pie, Legend, Tooltip} = Recharts;

const data = [{name: 'Group A', value: 0}, {name: 'Group B', value: 0}]

const SimplePieChart = React.createClass({
	render () {
  	return (
    	<PieChart width={800} height={400}>
        <Pie data={data} cx={500} cy={200} innerRadius={40} outerRadius={80} fill="#82ca9d"/>
        <Tooltip/>
       </PieChart>
    );
  }
})

ReactDOM.render(
  <SimplePieChart />,
  document.getElementById('container')
);
```
I was hoping to render something similar to this screenshot. Instead, nothing renders.
![screen shot 2017-08-24 at 8 24 37 am](https://user-images.githubusercontent.com/17085131/29666298-b193db36-88a5-11e7-8497-1eae6b47d114.png)

I'm using recharts `v1.0.0-alpha.3`

**Comment by sppatel** [comment]
I am experiencing the same issue.  Not sure how to solve this.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.

**Comment by mateotherock** [comment]
I know this is closed, but I am on the most recent version and ran into this as well on my project. For anyone else though what I basically did was if my data was all 0 I had it set up to conditionally change a few things. For one, I had to add an item to the data array with something like 'No Audits' with a value of 1 so it would take up the whole pie. From there it is really just a matter of conditionals...Don't show the Tooltip if data is 0, in the legend you would filter out the 'No Audits' item before returning the mapped payload, etc. 

From there I got something that looks like the attached here:
![NoAudits](https://user-images.githubusercontent.com/33496950/77335434-c0718180-6ceb-11ea-8624-9e8f56eee0bc.png)

**Comment by michael-lynch** [comment]
Yeah, I took a similar approach to @mateotherock. Calculate the sum of your values and if it's zero, render a fallback `<Pie>`.

```
const PieChart = ({ data }) => {
  const values = data.map(item => item.value);

  const sum = values.reduce((acc, value) => {
    return acc + value;
  });

  return (
    <RePieChart>
      {/* render default Pie */}
      <Pie data={data} />
      {sum === 0 && (
        {/* render 100% fallback Pie */}
        <Pie data={[{name: 'No Data', value: 1]}} fill="#eeeeee" />
      )}
    </RePieChart>
  );
}
```

In my case, I had a `<Tooltip>`, so I also wrapped that with a condition so it wouldn't appear on the fallback `<Pie>`.

```
{sum !== 0 && <Tooltip content={<MyTooltipComponent />} />}
```
