### ISSUE TITLE
Ability to extend LEGEND_TYPES in ReactUtils file

### ISSUE THREAD

**Issue by b-o-l-l-a** [recharts/recharts#850]
## Do you want to request a feature or report a bug?
Request a feature

## What is the current behavior?
LEGEND_TYPES within the recharts/es6/util/ReactUtils file is an array

`export var LEGEND_TYPES = ['line', 'square', 'rect', 'circle', 'cross', 'diamond', 'star', 'triangle', 'wye', 'none'];
`

It'd be nice to be able to extend this to include other types. My use case is for a dashed line. To do this, I append 'dash' into the LEGEND_TYPES variable, and then include the following in the DefaultLegendContent file:

`      } else if (data.type == 'dash') {
          return React.createElement('path', {
            strokeWidth: 4,
            fill: 'none',
            stroke: color,
            strokeDasharray: "6 6",
            d: 'M0,' + halfSize + 'h' + SIZE,
            className: 'recharts-legend-icon'
        });`

^^ This could be handled with the content attribute of legend, but since 'dash' isn't included in LEGEND_TYPES, it would be break. It'd be nice to be able to extend LEGEND_TYPES, and then the user would create a custom React component to pass into content which makes use of that particular legend type.

It breaks because Legend specifies default propTypes of payload.type as one of LEGEND_TYPES.

`  payload: PropTypes.arrayOf(PropTypes.shape({
    value: PropTypes.any,
    id: PropTypes.any,
    type: PropTypes.oneOf(LEGEND_TYPES)
  })),`

Let me know if anything's unclear. Thanks!

**Comment by b-o-l-l-a** [comment]
For completeness sake, it breaks because Legend specifies default propTypes of payload.type as one of LEGEND_TYPES.

`  payload: PropTypes.arrayOf(PropTypes.shape({
    value: PropTypes.any,
    id: PropTypes.any,
    type: PropTypes.oneOf(LEGEND_TYPES)
  })),`

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
