### ISSUE TITLE
Draw a straight line on bar chart

### ISSUE THREAD

**Issue by eldyvoon** [recharts/recharts#853]
Is it possible to mark a straight line on a bar chart? ComposedChart can't achieve that. 

## Do you want to request a feature or report a bug?
feature
## What is the current behavior?
can't draw a straight line on bar chart
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).
http://i.imgur.com/pMVOt5X.png
## What is the expected behavior?
Able to draw straight line on a bar chart

**Comment by xile611** [comment]
@eldyvoon Use `ReferenceLine` to draw a straight line. The docs of ReferenceLine is [here](http://recharts.org/#/en-US/api/ReferenceLine)

**Comment by damianobarbati** [comment]
Yes but it's very limited indeed :(

I have a trend which has a target (now drawn with a ReferenceLine). The target changed over time.
So I have to draw a broken straight line, one from origin to 31st march, another from 1st april to infinity (this is the target which changed on 1st April).
I'm having hard times trying to figure out how to do this.

@xile611 can you give me any hints on how to achieve it?

**Comment by kasturisameer** [comment]
![image](https://user-images.githubusercontent.com/36661062/68335811-2fff1f80-0103-11ea-97d6-cc924222ddff.png)

I want to show a small vertical line on long horizontal bar. I tried this using **ReferenceLine**, but no success.
@xile611 - Is there any way I can achieve?

**Comment by kulkarnipradnyas** [comment]
@kasturisameer  have you got any solution? i have similar use case.

**Comment by datdinhquoc** [comment]
i need a slanted line, not horizontal, possible?
