### ISSUE TITLE
ResponsiveContainer not loading charts

### ISSUE THREAD

**Issue by vikkya** [recharts/recharts#854]
When i try using `<ResponsiveContainer width="100%" height={400}> `my charts are not appearing. 
Also when i try giving width in % for BarChart or PieChart or any other im getting any error width is NaN string is passed.

here is my code:
```
<ResponsiveContainer width="100%" height={200}>
            <BarChart width={300} height={200} data={data} margins = {{ top: 50, right: 0, bottom: 100, left: 0 }} >
                <XAxis dataKey="monthName" />
                <YAxis />
                <CartesianGrid />
                <Legend />
                <Tooltip />
                <Bar dataKey="transactions" fill="#7B1FA2" />
            </BarChart>
            </ResponsiveContainer>
```
can you please tell me where am i doing wrong or something to do with your side.

**Comment by howardya** [comment]
ResponsiveContainer is always 100% of the width of its container element. However the container element needs to have a fixed width or % of another container element which has well defined width.

**Comment by vikkya** [comment]
@howardya can you please explain with a sample code. That would be lil helpfull

**Comment by howardya** [comment]
how about this http://jsfiddle.net/4zja5eo0/17/ ? 

The div containing the <ResponsiveContainer> has 50% width. 

Also this one http://jsfiddle.net/4zja5eo0/18/

**Comment by vikkya** [comment]
@howardya both the code are working fiddle but when i do it in my local system Charts are not displayed. No error in console too

**Comment by howardya** [comment]
Most likely is your parent element, or the parent of your parent element. 

Or there is no height defined.

For responsive to works, the parent container needs to have well defined height. 

Try debugging it by setting the parent element to have background-color: black then slowly work your way up the tree till it reaches the body or html tag. 

Or try some of the suggestions [here](https://www.google.com.sg/search?q=css+with+percentage+not+working)

**Comment by vikkya** [comment]
http://jsfiddle.net/dqj2k8dc/ 
my code is in this format 
responsiveness is not happening @howardya

**Comment by howardya** [comment]
how about this http://jsfiddle.net/dqj2k8dc/1/

you need to have 100% in all the div container all the way up until 
1. reach the html/body 
2. reach a div container which explicitly has the width defined.

**Comment by vikkya** [comment]
This is working fine in fiddle but, not sure what is going wrong with me. 
i will start from scratch and try for solving the problem
Thanks @howardya  for ur help.

**Comment by matepaiva** [comment]
@vikkya this solves your problem: https://css-tricks.com/NetMag/FluidWidthVideo/Article-FluidWidthVideo.php

Just wrap your ResponsiveContainer with this below (the paddingBottom will define the proportion of your container (a square, a rectangle etc.):

`
    <div style={{
            paddingBottom: '56.25%', /* 16:9 */
            position: 'relative',
            height: 0
          }} >
            <div style={{
              position: 'absolute',
              top: '0',
              left: '0',
              width: '100%',
              height: '100%'
            }}>
              <ResponsiveContainer>
                 ...
              </ResponsiveContainer>
            </div>
          </div>
`

**Comment by xile611** [comment]
@vikkya Just guarantee the width of parent node.
