### ISSUE TITLE
Pie cell  fill property do not work, the cell color use default #808080 

### ISSUE THREAD

**Issue by zteBill** [recharts/recharts#857]
`           <Pie data={this.state.termData} dataKey="value" cx={200} cy={200} startAngle={180} endAngle={-180} outerRadius={80} label={renderLabelContent}>
            {
               this.state.termData.map((entry, index) => {
                console.log(colors[index % 10]);
                  <Cell key={`slice-${index}`} name={entry.name} value={entry.value} fill={colors[index % 10]}/>
                }
                )
            }`

**Comment by iphonic** [comment]
I am having the same issue https://github.com/recharts/recharts/issues/1043
