### ISSUE TITLE
Brush doesn't change hinting value after setState and props

### ISSUE THREAD

**Issue by magdalko** [recharts/recharts#858]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
When I try to pass data from Brush to state or/and to parent props the Brushes hint ( 
![image](https://user-images.githubusercontent.com/31534726/29961676-a7c7c1ce-8f00-11e7-92f5-a5fb207d64d6.png)) is not changing the value (it always stays the startIndex value and end index Value even if you move). 

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).
`  
handleChange(index){
      this.indexFrom = this.state.data[index.startIndex].Date
      this.indexFrom = this.indexFrom.replace(/-/g,'')
      this.indexTo = this.state.data[index.endIndex].Date
      this.indexTo = this.indexTo.replace(/-/g,'')
      this.props.dFrom(this.indexFrom)
      this.props.dTo(this.indexTo)
}

  render(){
    return(
        
            <ResponsiveContainer width="100%" height={40} >
                <AreaChart height={0} data={this.state.data} margin={{top: 5, right: 0, left: 0, bottom: 0}}>
            
                    <Area type='monotone' dataKey='AlarmCnt' stroke='#8884d8' fill='#8884d8' padding={{bottom: 10}} />
                    <Brush data={this.state.data} dataKey='Date' fill="#ECECEC" onChange={this.handleChange.bind(this)}>
                        <AreaChart   >
                            <Area dataKey="AlarmCnt" stroke="#ff7300" fill = "#ff7300" dot={false} />
                            
                        </AreaChart>
                    </Brush>
                </AreaChart>
            </ResponsiveContainer>
            
    )}
}

`

If I comment now the `this.props.dFrom(this.indexFrom)
      this.props.dTo(this.indexTo)` I will get proper behaviour of brush but then I don't have access to the dFrom and dTo in other components.
## What is the expected behavior?
I should send the values from Brush to other components.
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
chrome 60.0.3112.101
react 15.6.1

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
