### ISSUE TITLE
Cartesian grid vertical fill color

### ISSUE THREAD

**Issue by saravanareddy** [recharts/recharts#860]
I have a requirement to alternate the fill color in the grid. I am able to set the fill color, but is there a way to customize it so that I can alternate between two colors. Diagram attached. 

It would be great if the fill took an array as input and cycle through the input colors. Something like:

`
<CartesianGrid vertical horizontal={false} verticalFill={['#555555', '#444444']} fillOpacity={0.2} />
`
Thank you. 

![chart](https://user-images.githubusercontent.com/1454752/29993250-51208336-8fcf-11e7-9723-a392f307a98d.jpg)

**Comment by saravanareddy** [comment]
Is there a way to specify style to the vertical grid lines? I want to make my lines white.

**Comment by saravanareddy** [comment]
@xile611 thank you for adding this to features list. 

For the time being I could set the background to one color and use ReferenceArea to create a rectangular block of the second color with a white stroke to meet my requirements. 

My question is how do I get the starting co-ordinates of the ticks markers along the x-axis? If I know that, I think I will be good. Thank you.

**Comment by costagolub** [comment]
#867 pushed request about this

**Comment by saravanareddy** [comment]
@costagolub anyway for me to specify the grid line color? Would be nice to have a prop under CartesianGrid to specify color for the vertical and horizontal grid lines.

**Comment by costagolub** [comment]
@saravanareddy so what exactly do you want to achieve. Do specify the colors for the grid lines in the props of CartesianGrid? I added this into the pull request where possible to specify `verticalFill ` and `horizontalFill` that accepts arrays with colors that will be altered as well as controlled opacity like `fillOpacityVertical`. Does that make sense?

**Comment by saravanareddy** [comment]
@costagolub thank you for your commits. `verticalFill` and `horizontalFill` along with the opacity option give me the ability to shade the rectangular regions in whichever way I want. That's great!

But, if you look at the reference image in my original post. You will notice that the grid has white lines at the ticks, followed by the rectangular region(using verticalFill and fillOpacityVertical). Right now, by default the grid lines are drawn in `gray` color and I would like to customize that to any color of my choice. Hope my requirement makes sense. Thank you.

**Comment by costagolub** [comment]
@saravanareddy I see now what you mean. Thank you for clarification. 
If you're using `XAxis` and `YAxis` for adding lines with ticks you can just disable them with prop `axisLine={false}` like `<XAxis axisLine={false} dataKey="name" stroke="#666" /> `

In this case, only ticks stay on the screen but if you want to have these lines in a different color out of ticks then I can't say if it's possible now with `Axis` component because as I see property stroke inherits for both lines, ticks, and text but I could be wrong. Probably this might be enhanced

**Comment by saravanareddy** [comment]
@costagolub, looks like I misunderstood how the grid lines work. I thought they were a property of `CartesianGrid` since by setting `vertical={false} horizontal={false}` the lines completely disappeared from the chart. 

But yeah it would be super helpful if we could customize the color of the lines. Should I open a new issue for that? Thank you.

**Comment by costagolub** [comment]
@saravanareddy yes, if you're talking about lines on the grid (not ones that are on the edges of the cartesian) there are such properties, you can also set a color of these lines by adding a `stroke ` property and other SVG properties that can be set on the line with the appropriate color but it will apply both to horizontal and vertical lines now.
Probably you can open it.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.

**Comment by jvaclavik** [comment]
Hello guys, 
this feature would be really amazing to have. Especially if I could specify the color for each column separately (because for example you have months in a year and you want to have every year with a separated color). Is there some progress with this issue? I found just non-merged PR.
Thanks for the info

**Comment by lakshmidwivedi** [comment]
Can you help me make bar chart like this there is vertical={false} in cartesian then removed all vertical line we want  only remove bar line. 
![image](https://user-images.githubusercontent.com/54531198/118117188-ea629780-b408-11eb-97af-ad074739d4e7.png)
