### ISSUE TITLE
Is possible to remove top and bottom horizontal lines from CartesianGrid?

### ISSUE THREAD

**Issue by nathantn** [recharts/recharts#861]
How can I remove the top and bottom grid lines from this chart?

![screen shot 2017-09-01 at 11 07 30 am](https://user-images.githubusercontent.com/5244313/29973574-6b0fdbe4-8f06-11e7-96a2-068fc5a075d5.png)

Current code:
```javascript
<LineChart>
  <CartesianGrid
    vertical={false}
    strokeDasharray="4 4"
    stroke="#aab8c2"
  />

  <YAxis
    domain={['dataMin', 'dataMax']}
    opacity="0"
    style={{ display: 'none' }}
    width={0}
    ticks={[this.isMinValueNegative() ? 0 : this.getMinValue()]}
  />
</LineChart>
```

**Comment by xile611** [comment]
@nathantn Use horizontal={false}  to remove all the horizontal lines. Or use css to remove top and bottom lines.

```
.recharts-wrapper .recharts-cartesian-grid-horizontal line:first-child,
.recharts-wrapper .recharts-cartesian-grid-horizontal line:last-child {
      stroke-opacity: 0;
}
```

**Comment by nathantn** [comment]
In this case I need to keep the horizontal line of the middle, so horizontal={false} doesn't work for me. I was able to remove them with css, however the top and bottom lines are added in a different order that it is shown on the screen, they are the last two elements in the DOM.

**Comment by StephaneBischoff** [comment]
> In this case I need to keep the horizontal line of the middle, so horizontal={false} doesn't work for me. I was able to remove them with css, however the top and bottom lines are added in a different order that it is shown on the screen, they are the last two elements in the DOM.
> Thanks @xile611

.recharts-wrapper .recharts-cartesian-grid-horizontal line:nth-last-child(-n+2) {
    stroke-opacity: 0;
}

**Comment by Wileyhomeroom34** [comment]
observe this https://stylesheets.space/questions/how-to-eliminate-tick-lines-from-recharts-in-react insight
