### ISSUE TITLE
Change bar chart hover color?

### ISSUE THREAD

**Issue by Xeoncross** [recharts/recharts#863]
## Feature Request

I tried looking at `<BarChart />`, [`<Bar />`](https://github.com/recharts/recharts/blob/master/src/cartesian/Bar.js), and `<ResponsiveContainer />` but I don't see any option for changing the default `<Bar />` hover from gray (`fill: #ccc`) to another color.

## What is the current behavior?

Hover color is gray

![gray bar](https://user-images.githubusercontent.com/56460/30000728-07303d9e-903c-11e7-871a-ca40821189ee.png)

React Tools shows:

![screen shot 2017-09-03 at 9 11 27 am](https://user-images.githubusercontent.com/56460/30003748-e9118f56-9087-11e7-92fb-7865a7ad6a42.png)

**Comment by JamesWooldridge** [comment]
This style can be defined using the `cursor` prop on `Tooltip`. See [Tooltip docs](http://recharts.org/#/en-US/api/Tooltip).

**Comment by xile611** [comment]
@Xeoncross Change the order of <Tooltip />  and <Bar />, the elements of each component is rendered in order.

**Comment by bziorkiewicz** [comment]
Updated link: http://recharts.org/en-US/api/Tooltip

**Comment by borhan365** [comment]
Update in 2022: simply use the cursor={false} <Tooltip cursor={false} />

**Comment by nmn-yd** [comment]
If you want to add the hover color on tool tip you can use : 
`<Tooltip cursor={{ fill: "var(--clr-gray-2)" }} /> `
Fill property
