### ISSUE TITLE
Refill colors of pie chart on resize window

### ISSUE THREAD

**Issue by vadimnike** [recharts/recharts#864]
I use ResponsiveContainer component for Pie Chart and while resizing screen recharts-pie-sector change fill color by default values and after stop it resizing  pie chart return my colors.How  I can avoid refilling colors and continue use ResponsiveContainer  for my charts??
My code below

**Comment by vadimnike** [comment]
```
`
    <ResponsiveContainer width="100%" aspect={2}>

     <PieChart width={width} height={height}>
        <text  x="50%" y="50%" textAnchor="middle" dominantBaseline="center">
          {data.map((entry) => entry.amount) }
        </text>
        <Pie
          data={data}
          cx={cx}
          cy={cy}
          startAngle={startAngle}
          endAngle={endAngle}
          innerRadius={innerRadius}
          outerRadius={outerRadius}
        >
          { data.map((entry, index) => <Cell fill={colors[index % colors.length]} />) }
        </Pie>
      </PieChart>
    </ResponsiveContainer>`
```

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
