### ISSUE TITLE
Multi-line repeates categories on x axis

### ISSUE THREAD

**Issue by ZephD** [recharts/recharts#866]
## Do you want to request a feature or report a bug?
Feature

## What is the current behavior?
provide data as a x, y1, y2, y3... data set.
Problem is having to hard-code the number of y1 y2 y3 into the data and code

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).
Problem: http://jsfiddle.net/qbmg1567/599/
Worse problem: http://jsfiddle.net/qbmg1567/600/
Workaround: http://jsfiddle.net/qbmg1567/602/

## What is the expected behavior?
Provide data as a per-line, x-y dataset

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
All, All, Nope

**Comment by Brian-Gaffney** [comment]
I can't get the jsfiddles to work.

Getting 404 for the `react-dom` and `react-with-addons` JS resources from https://npmcdn.com.

https://npmcdn.com/react@16.2.0/dist/react-with-addons.min.js - 404
https://npmcdn.com/react-dom@16.2.0/dist/react-dom.min.js - 404

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.

**Comment by mohsen-gis** [comment]
Is this bug fixed? Any solution?

**Comment by letspython3x** [comment]
Yes, set `allowDuplicatedCategory={false}` in `<XAxis>`
`<XAxis dataKey="part" allowDuplicatedCategory={false}>`

[More](https://stackoverflow.com/a/58133769/3940406)
