### ISSUE TITLE
Scatter Chart: lineType 'fitting' does not work

### ISSUE THREAD

**Issue by eranbnn** [recharts/recharts#868]
maybe I'm missing something, but the "fitting" option does nothing:
http://jsfiddle.net/zdhvvt2e/75/

should it render a trend line?

Thanks.

**Comment by LACoderDeBH** [comment]
This is still not working for me. It shows up in the legend but does not render on the graph. Has it been resolved? If so, what should I do to make it work?

If not - do you have suggestions on how to do this manually?

Thank you! Love your library!

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
