### ISSUE TITLE
Custom Label for ReferenceDot

### ISSUE THREAD

**Issue by klapouchy** [recharts/recharts#869]
I'd like to know how can I create a custom label for a [ReferenceDot](http://recharts.org/#/en-US/api/ReferenceDot)

Here is my attempt:

http://jsfiddle.net/Lphcscom/

**Comment by xile611** [comment]
@klapouchy 

Try the following:
```jsx
 <ReferenceDot  {...values} r={10} fill="red"  alwaysShow={true} isFront={true}  label="any text" />
```
[Doc of Label](http://recharts.org/#/en-US/api/Label)
