### ISSUE TITLE
Show the wrong tooltip.

### ISSUE THREAD

**Issue by shinima** [recharts/recharts#87]
When my pointer(indicated by the red point) is in the red rectangle, the tooltip of Page-B shows up. But I suppose that the tooltip of Page-B shows up when the pointer is in the the blue rectangle.

![1](https://cloud.githubusercontent.com/assets/5550931/15037838/ec5ec434-12d0-11e6-8fd3-5646bdae0e27.png)

I am using Chrome 50 and edge on Windows.

如图, 当鼠标在红色框里面的时候, 将显示Page-B的提示工具. 不应该是鼠标在蓝色框的时候才显示Page-B的提示么?

**Comment by xile611** [comment]
Thanks! It seems to be a bug.

**Comment by xile611** [comment]
Fixed in v0.10.4
