### ISSUE TITLE
Unable to mark few values(Infinite, null) on graph

### ISSUE THREAD

**Issue by anilapu** [recharts/recharts#870]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
IGraph is not showing for Infinite and null 
## Example
http://jsfiddle.net/Anusha_Nilapu/s3Ltp0y3/3/
## What is the expected behavior?
User should identify null or infinity on graph instead of empty

**Comment by anilapu** [comment]
I can able to see infinity on graph but dots are not connected once value is infinity
This is the example: http://jsfiddle.net/Anusha_Nilapu/qgbkt1v3/1/

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
