### ISSUE TITLE
Candlestick charts?

### ISSUE THREAD

**Issue by rszemplinski** [recharts/recharts#871]
Was wondering if there were plan of adding a candlestick chart to the mix?

**Comment by ryanand26** [comment]
I managed to achieve a candlestick chart using ErrorBars, as described at https://github.com/recharts/recharts/issues/267#issuecomment-267739342

**Comment by lukechilds** [comment]
@ryanand26 Are you able to change the candle colour for increase/decrease? Any chance you could share your code?

**Comment by ryanand26** [comment]
I can't share the code but I ended up using two error bars and two dataKeys, one for each direction, then feeding null to one and the data to the other depending which color was needed.

**Comment by lukechilds** [comment]
@ryanand26 Thanks for the reply, totally understand about not being able to share code. Any chance you could send me a sneaky screenshot, even privately?

We really like the look of recharts but just wanna know if what we wanna do is gonna be possible, to make it look good or too hacky.

**Comment by moonlight16** [comment]
Any progress on this?

**Comment by moonlight16** [comment]
> I managed to achieve a candlestick chart using ErrorBars, as described at [#267 (comment)](https://github.com/recharts/recharts/issues/267#issuecomment-267739342)

I guess I was looking for more like Japanese Candlesticks:
https://en.wikipedia.org/wiki/Candlestick_chart

Do you know if anyone is working on this?  This is an important graph feature for financial charts.

**Comment by DaanVermunt** [comment]
@moonlight16 
Not sure if you still need it, but here is my implementation of Candlestick charts using recharts
`import * as React from 'react'
import {CartesianGrid, XAxis, YAxis, Tooltip, Legend, Bar, ErrorBar, ComposedChart, Line, Cell} from 'recharts'


interface StockDailyDataPoint {
    // TODO: should be date
    date: number
    high: number
    low: number
    open: number
    close: number
}

interface CandleStickDataPoint {
    date: number
    low: number
    high: number
    errorLowUp?: number
    errorHighUp?: number
    errorLowDown?: number
    errorHighDown?: number
    height: number
    errorLineHigh: number
    errorLineLow: number
    up: boolean
}

interface CandleStickProps {
    data: Array<StockDailyDataPoint>
}

// {date: 11, high:5, low: 1, open: 4, close: 2}
const CandleStick = (props: CandleStickProps) => {

    // TODO: map data to fit chart

    const data = props.data.map((point: StockDailyDataPoint): CandleStickDataPoint => {
       return {
           date: point.date,
           low: Math.min(point.close, point.open),
           high: Math.max(point.close, point.open),
           height: Math.abs(point.close - point.open),
           errorLineHigh: (Math.min(point.close, point.open) - point.low)/2 + Math.abs(point.close - point.open),
           errorLineLow: Math.min(point.close, point.open) - (Math.min(point.close, point.open) - point.low)/2,
           errorLowUp: point.close > point.open ? (Math.min(point.close, point.open) - point.low)/2 : undefined ,
           errorHighUp: point.close > point.open ? (point.high - Math.max(point.close, point.open))/2: undefined,
           errorLowDown: point.close <= point.open ? (Math.min(point.close, point.open) - point.low)/2 : undefined ,
           errorHighDown: point.close <= point.open ? (point.high - Math.max(point.close, point.open))/2: undefined,
           up: point.close > point.open,
       }
    });

    const maxHeight: number = data.reduce((max, point) =>
        Math.max(point.high + (point.errorHighUp ? point.errorHighUp : 0), max)
        , 0);
    const minHeight: number = data.reduce((min, point) =>
        Math.min(point.low - (point.errorLowDown ? point.errorLowDown : 0), min)
        , 0);

    // make duplicate for error up and down error



    return <ComposedChart width={500} height={500} data={data}>
        <CartesianGrid strokeDasharray="5 5" />
        <XAxis dataKey="date" />
        <YAxis domain={[minHeight, maxHeight + 5]}/>
        <Tooltip />
        <Legend />
        {/*Floating bar*/}
        <Bar dataKey="low" fillOpacity={0} stackId={'stack'} barSize={20} />
        <Bar dataKey="height" stackId={'stack'} barSize={20}>
            {data.map((entry) => (
                <Cell fill={entry.up  ? '#00906F' : '#B23507'} />
            ))}
        </Bar>

        {/*Error down*/}

        <Line dataKey={'high'} stroke={'none'} isAnimationActive={false} dot={false}>
            <ErrorBar dataKey={'errorHighDown'} width={2} strokeWidth={2} stroke={'#B23507'}/>
        </Line>

        <Line dataKey={'low'} stroke={'none'} isAnimationActive={false} dot={false}>
            <ErrorBar dataKey={'errorLowDown'} width={2} strokeWidth={2} stroke={'#B23507'}/>
        </Line>

        {/*Error up */}
        <Line dataKey={'high'} stroke={'none'} isAnimationActive={false} dot={false}>
            <ErrorBar dataKey={'errorHighUp'} width={2} strokeWidth={2} stroke={'#00906F'}/>
        </Line>

        <Line dataKey={'low'} stroke={'none'} isAnimationActive={false} dot={false}>
            <ErrorBar dataKey={'errorLowUp'} width={2} strokeWidth={2} stroke={'#00906F'}/>
        </Line>


    </ComposedChart>
};

export default CandleStick;
`

It is still a work in progress but all the parts are there

**Comment by moonlight16** [comment]
> @moonlight16
> Not sure if you still need it, but here is my implementation of Candlestick charts using recharts
> 

Thanks.  fwiw I did find this awesome project:
http://rrag.github.io/react-stockcharts/index.html

**Comment by PavelVanecek** [comment]
See https://recharts.github.io/en-US/examples/Candlestick/
