### ISSUE TITLE
Tooltip: Show custom tooltip content on null values

### ISSUE THREAD

**Issue by Malachi-M** [recharts/recharts#877]
## Do you want to request a feature or report a bug?
- request a feature
## What is the current behavior?
If a null value is present always hide the tooltip wrapper with an inline style of `visibility: hidden`

https://github.com/recharts/recharts/blob/ed88040d5a81597095728898576e826940db67ee/src/component/Tooltip.js#L131

## What is the expected behavior?
Allow the user to optionally show or hide a tooltip in the case of a null value. We currently have created a tooltip to handle null cases yet it will never display do to the current functionality with null values.

#### Version
"recharts": "^1.0.0-alpha.4"

#### Browser / OS 
Chrome: Version 60.0.3112.113 (Official Build) (64-bit)
OS: macOS Sierra Version 10.12.6

To my knowledge this feature has not worked in previous versions of Recharts.

**Comment by Malachi-M** [comment]
Hello. I saw the change to allow null values was reverted. Is there any plan to address this behavior in the future?

**Comment by Malachi-M** [comment]
Hello thanks for addressing this issue. I am wondering if you can re-open this issue or do as you see fit to address the following to ensure the functionality of allowing a `null` value for a tooltip. 

This line of code,
https://github.com/recharts/recharts/blob/65ef1509f54b9fbdd90c8d7cf16ccd3b65e75d65/src/component/Tooltip.js#L135
I believe is hindering this line:
https://github.com/recharts/recharts/blob/65ef1509f54b9fbdd90c8d7cf16ccd3b65e75d65/src/component/Tooltip.js#L139
from allowing the `visibility` property to be set to `visible` due to the `finalPayload.length;` conditional. A value of `null` won't pass this condition.

Thanks so much for your work on this project.

**Comment by Malachi-M** [comment]
Hello @xile611. I am wondering if, time allowing, you can take a look at the previous comment that will allow full functionality for handling null value within the Tooltip component.

Thanks for creating/maintaining a great charting library.

**Comment by christiancho** [comment]
@Malachi-M Have you tried passing `filterNull={false}` as a prop to `Tooltip`?
