### ISSUE TITLE
X-axis is only shows scale but not dates

### ISSUE THREAD

**Issue by abdulkhaliquem9** [recharts/recharts#878]
![image](https://user-images.githubusercontent.com/27613442/30242483-ebc3cb10-95b4-11e7-9b91-76e1f9ab003c.png)

what could be the solution, Is there any thing related to padding bottom with respect to the x-axis, so that I can pull the x-axis a little bit up.
I tried to add height attribute in x-axis, but it applies padding to the line but It did not worked to make the dates visible.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
