### ISSUE TITLE
Fill color overlays the stroke in AreaChart

### ISSUE THREAD

**Issue by liubko** [recharts/recharts#879]
If the `strokeWidht` is big enough it's visible how fill color overlays the line itself

## What is the current behavior?

http://jsfiddle.net/liubko/ktwfp03m/159/

![screen shot 2017-09-10 at 12 16 03 pm](https://user-images.githubusercontent.com/4257937/30247683-3aaedc8e-9622-11e7-9399-a6b0be448c44.png)

## What is the expected behavior?
I would expect the `stroke` to be drawn above the `fill`

## version
1.0.0-alpha.4

**Comment by xile611** [comment]
Try the version 1.0.0-alpha.5
