### ISSUE TITLE
Allow for specifying more interpolations (new feature).

### ISSUE THREAD

**Issue by kujon** [recharts/recharts#88]
Currently the curve types are restricted to 'linear', 'monotone', 'step', 'stepBefore' or 'stepAfter'. `d3-shape` supports more of them, so it might be a good idea to allow any of them to be specified.

My reasoning behind it is that recharts have already got a glorious API and it would be good to allow people to create more chart types based on it (I personally need the chord diagram).

**Comment by xile611** [comment]
Fixed in version 0.10.5.

Now props `type` in  `Curve` supports `'basis'`, `'basisClosed'`, `'basisOpen'`, `'linear'`, `'linearClosed'`, `'natural'`, `'monotone'`, `'step'`, `'stepBefore'` and `'stepAfter'`.
Add `type` can set to be a interpolation function, just like:

```jsx
import { curveCardinalClosed  } from 'd3-shape';

...
  <Curve type={curveCardinalClosed.tension(1)} points={points} />
...
```

**Comment by kujon** [comment]
Thanks a lot! Do you guys fancy Chord Diagram contribution? Something along those lines: http://www.global-migration.info/

**Comment by xile611** [comment]
PR is welcome! But we haven't think very clear whether such charts which are not very widely used should be contained in Recharts.
