### ISSUE TITLE
ResponsiveContainer with the initial animation of the chart

### ISSUE THREAD

**Issue by happysuns** [recharts/recharts#881]
My chart can be loaded normally but when I use the ResponsiveContainer API but did not initially load the animation。
`                <ResponsiveContainer height={300}
                                     width="100%"
                >
                  <AreaChart data={data}
                             height={300}
                             margin={{top: 10, right: 30, left: 0, bottom: 0}}
                             width={500}
                  >
                    <XAxis dataKey="name"/>
                    <YAxis/>
                    <Legend height={36}
                            verticalAlign="top"
                    />
                    <CartesianGrid strokeDasharray="6 6"/>
                    <Tooltip/>
                    <Area dataKey="weChat"
                          fill="#8884d8"
                          stackId="1"
                          stroke="#8884d8"
                          type="monotone"
                    />
                    <Area dataKey="aliPay"
                          fill="#82ca9d"
                          stackId="1"
                          stroke="#82ca9d"
                          type="monotone"
                    />
                    <Area dataKey="gateWay"
                          fill="#ffc658"
                          stackId="1"
                          stroke="#ffc658"
                          type="monotone"
                    />
                    <Area dataKey="quick"
                          fill="#ffe658"
                          stackId="1"
                          stroke="#ffe658"
                          type="monotone"
                    />
                  </AreaChart>
                </ResponsiveContainer>`

**Comment by xile611** [comment]
@happysuns Can you create an online demo of your problem? And what's the version of Recharts?

**Comment by happysuns** [comment]
@xile611  Thanks I seem to find the reason

**Comment by xile611** [comment]
OK~  I'll close this.

**Comment by deepfunc** [comment]
I have the same problem, how to fix it? @happysuns
