### ISSUE TITLE
Area chart fill color can't filter based on data value

### ISSUE THREAD

**Issue by el37** [recharts/recharts#882]
i tried to create area chart that the fill color should be different when the data < 0 and the other condition will follow the default color.

<Area type="monotone" dataKey="uv" stroke="#8884d8" fill={ data.uv > 0 ? "#FF0044" : "00FF33" } />

the code should give a custom color but it didn't.

how i can solve this problem ?

**Comment by KuriatoV** [comment]
also need answer(

**Comment by xile611** [comment]
@el37 @KuriatoV Can you give an example of the chart you want?

**Comment by KuriatoV** [comment]
![screenshot from 2017-09-11 17-57-59](https://user-images.githubusercontent.com/19538309/30429734-3e7ec922-9961-11e7-9775-0a44a61cd24d.png)

**Comment by KuriatoV** [comment]
any news or thoughts ?)

**Comment by KuriatoV** [comment]
maybe now?)))

**Comment by ThePianoDentist** [comment]
This is also something I would like to see implemented.
I would like to say I'd have a go at implementing it myself, but am brand new to the library and will probably be too time consuming for me

**Comment by ThePianoDentist** [comment]
I figured out how to do this within recharts utilising LinearGradient of svg.

example fiddle:
http://jsfiddle.net/ecztwz31/2/

please feel free to improve my JS if possible (still relatively new to react/es6 stuff)
I think this would be a useful example to add to site, I'll wait for critique on fiddle, then this weekend I can do a pull request to add this as an example to site. (I think name should be DoubleAreaChart)

**Comment by ThePianoDentist** [comment]
pls note when checking/improving my code above to submit example I found a bug where would accidentally get a gradient if all points were positive/all points negative

corrected code http://jsfiddle.net/s61v52d6/

**Comment by ThePianoDentist** [comment]
Noticed another small issue with my code, new fiddle that seems to work for all possible data ranges:
http://jsfiddle.net/fpm003na/3/

will update links in old requests so people dont accidentally use my bugged attempts

**Comment by trylimits** [comment]
The above snippet works fine in most cases, even with more than one data set. However, if a `Brush` component is added the snippet has to be extended a little bit in order to behave correctly.
When determining the min/max data values the applied bounds have to be respected. This can be done by providing an `onChange` callback to the `Brush` and `slice` the data array accordingly.

**Comment by gaurav5430** [comment]
This is helpful.
the gradient solution works well for any static decisions based on the complete available data, but what if we need to decide the color based on the current value of the data?

Or maybe we would need to create multiple gradient stops dynamically based on all data

**Comment by AminAshtiani** [comment]
> Noticed another small issue with my code, new fiddle that seems to work for all possible data ranges:
> http://jsfiddle.net/fpm003na/3/
> 
> will update links in old requests so people dont accidentally use my bugged attempts

Your answer is helpful.

I was wondering how can compare values with specific value, Not zero and then fill the area?

for example I want to fill area greater than 1 with green and area with lower than 1 with red
