### ISSUE TITLE
How can i restart animation from zero position => to props, without reload page. 

### ISSUE THREAD

**Issue by alexeikaratai** [recharts/recharts#887]
How can i restart animation from zero position => to props, without reload page. When i change data, graph doest restart animation from zero point.  Need restart animation from zero poin to current.

**Comment by xile611** [comment]
@alexeikaratai You can add a `key` to chart when you change data.

**Comment by alexeikaratai** [comment]
@xile611 could u please explain me what do u mean?

**Comment by SeqviriouM** [comment]
HI! 

I join @alexeikaratai question. I have the same problem: when Line draws at first by points its animation works perfectly. But when I try to change points (for example send another data from props) animation haven't restarted from zero point. Is it possible to restart animation when data has changed?

**Comment by jwhscholten** [comment]
Generate a new key each time you update data on the main React component so it will rerender.

e.g.
this.state = {key : 1}

on your component
<AreaChart key={this.state.key}>

In data update function 
this.setState({key: 2});

Make sure your keys are stable and predictable:
https://reactjs.org/docs/reconciliation.html#trade-offs
