### ISSUE TITLE
Feature Request: Option to pass a function to connectNulls

### ISSUE THREAD

**Issue by cephirothdy2j** [recharts/recharts#889]
## Do you want to request a feature or report a bug?
Feature

## What is the current behavior?
Currently `connectNulls` is a boolean, and there is no way to programmatically decide whether to connect two points in Area and Line components.

## What is the expected behavior?
What I'd love to do is decide (based on the gap size, for example) whether to connect the null points between two valid points. This would result in large gaps being disconnected, while small gaps still connect.

I'm willing to fork, do the work and issue a PR but I'd appreciate it if somebody could point me in the right direction. Looks like I'll have to edit the <Curve> component to get this done.

Thanks!

**Comment by veddermatic** [comment]
Have you started on this? I need this functionality, and will implement it, but don't want to duplicate work.

**Comment by xile611** [comment]
Maybe you can use a customized `shape` to change the behavior
