### ISSUE TITLE
Brush interval

### ISSUE THREAD

**Issue by exdeniz** [recharts/recharts#890]
I have big data (0.. 800000). How do set interval for full range equal 1000?

**Comment by tongyy** [comment]
[Brush API](http://recharts.org/#/en-US/api/Brush)
Using startIndex and endIndex

**Comment by exdeniz** [comment]
startIndex and endIndex these are not the options.  I want to skip some values, like [0,10,20,30]

**Comment by tongyy** [comment]
Is it like that in your case? [0.... 800000] => [0,1000,2000,....800000]
When you move your traveler of brush, it should move and change the chart every gap of 1000 instead of 1.
I have some idea to add "gap" or "interval" props for brush.

**Comment by exdeniz** [comment]
@tongyy exactly! brush with every 800000 point very slowly working.

**Comment by tongyy** [comment]
#952 I opened the PR.
