### ISSUE TITLE
Adding arrow to tooltip ?

### ISSUE THREAD

**Issue by abhayjeetgupta** [recharts/recharts#895]
## Do you want to request a feature or report a bug?
Feature Request
## What is the current behavior?
I can create a custom tooltip. 

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).
No
## What is the expected behavior?
I want to add triangle to tooltip so it should point to the related bar or pie.

**Comment by costagolub** [comment]
@abhayjeetgupta I will prepare pull request about this feature if it's okay.

**Comment by abhayjeetgupta** [comment]
@costagolub yes please.

**Comment by nathmack** [comment]
I have a similar request https://github.com/recharts/recharts/issues/911

**Comment by jabsatz** [comment]
@costagolub where you able to get some work done on this?

**Comment by xile611** [comment]
Sorry, not supported yet. It's recommended to use customized `content` of `Tooltip` to cover default tooltip.
