### ISSUE TITLE
No shape display when ScatterChart data source contains same X value 

### ISSUE THREAD

**Issue by JackyW83** [recharts/recharts#897]
Guys,

I simply change the data to below, the x value in both data01 and data02  are same (210). 
Now, the shape in Chart disappeared, it will appear if there is no collision in X-axis. any idea about this,  thank you.

check the issue at  http://jsfiddle.net/tbgdjnqp/20/

const {ScatterChart, Scatter, XAxis, YAxis, ZAxis, CartesianGrid, Tooltip, Legend} = Recharts;
const data01 = [{x: 210, y: 260, z: 240}];
const data02 = [{x: 210, y: 200, z: 200}];

const ThreeDimScatterChart = React.createClass({
	render () {
  	return (
    	<ScatterChart width={400} height={400} margin={{top: 20, right: 20, bottom: 20, left: 20}}>
      	<XAxis dataKey={'x'} name='stature' unit='cm'/>
      	<YAxis dataKey={'y'} name='weight' unit='kg'/>
        <ZAxis dataKey={'z'} range={[60, 400]} name='score' unit='km'/>
        <CartesianGrid />
      	<Tooltip cursor={{strokeDasharray: '3 3'}}/>
        <Legend/>
      	<Scatter name='A school' data={data01} fill='#8884d8' shape="star"/>
        <Scatter name='B school' data={data02} fill='#82ca9d' shape="triangle"/>
      </ScatterChart>
    );
  }
})

ReactDOM.render(
  <ThreeDimScatterChart />,
  document.getElementById('container')
);

**Comment by jgentes** [comment]
+1

**Comment by henrinormak** [comment]
Also affected by this, I wouldn't mind investigating, but I am not really sure where I should look, any pointers from anyone more familar with this?

**Comment by zwalker** [comment]
I found that setting the type to number fixed my problem <XAxis type="number" />

**Comment by JackyW83** [comment]
zwalker solution works, close this issue.

> I found that setting the type to number fixed my problem <XAxis type="number" />
