### ISSUE TITLE
Please add documentation and include Sankey in the demo link

### ISSUE THREAD

**Issue by raviteja83** [recharts/recharts#898]
Recharts is awesome. Thanks a lot for the effort.

I have noticed that Sankey is part of the codebase but it's missing in the examples and the guide sections. It will be awesome if you can add it.

**Comment by TheSp00k** [comment]
Would be nice to get an update on this. Is it lacking only documentation or is it not usable yet?

**Comment by JackNeto** [comment]
Any updates on this?
