### ISSUE TITLE
Numeric automatic Domain always includes 0 in the x-axis domain for vertical lines

### ISSUE THREAD

**Issue by scottdickerson** [recharts/recharts#899]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
If I have a line chart with a straight line up and down, the automatically calculated x axis domain is including the 0 point to be part of the domain and only the dataMax value on the right side so it's hard to view the line

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).
http://jsfiddle.net/qbmg1567/620/

## What is the expected behavior?
The automatic domain calculation logic for numeric x-axis domains should be enhanced to handle values without including the 0 point in the axis domain.  It should make an x-axis domain that balances the vertical line on both sides.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
"recharts": "0.20.8",

**Comment by swiftfoot** [comment]
In addition, with a line like this, the tooltip is only being triggered for a few of the y points on the line, not each of them as I move from point to point

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
