### ISSUE TITLE
Be confused about layout: "vertical" in BarChart

### ISSUE THREAD

**Issue by yenshih** [recharts/recharts#90]
I had read the API and examples about BarChart and wanna to mix it into my project.
First, I copied the JS code from [http://recharts.org/examples/#SimpleBarChart](url) to my React Project. And I got the graph below.
![qq 20160509175008](https://cloud.githubusercontent.com/assets/14069488/15109689/3db56b26-160f-11e6-9293-e2a102717289.png)
Everything is ok. But after I made some changes...
```javascript                    
<BarChart
    width={800}
    height={400}
    layout="vertical"
    data={data}
    margin={{top: 5, right: 30, left: 20, bottom: 5}}
>
    <XAxis />
    <YAxis type="category" dataKey="name" />
```
![qq 20160509174358](https://cloud.githubusercontent.com/assets/14069488/15109773/b71c50e2-160f-11e6-972e-104395647d6e.png)
The uv is disappeared from Page A, and XAxis is totally wrong, obviously.
I was wondering if you could point out my configuration mistakes about layout: "vertical". I will be greatly appreciated.

**Comment by xile611** [comment]
You should specify `type` in `XAxis` to be `number`.

```jsx
<BarChart 
  width={600} 
  height={300} 
  data={data} 
  layout="vertical"
  margin={{top: 5, right: 30, left: 20, bottom: 5}}
>
  <XAxis type="number"/>
  <YAxis type="category" dataKey="name" />
  <CartesianGrid strokeDasharray="3 3"/>
  <Tooltip/>
  <Legend />
  <Bar dataKey="pv" fill="#8884d8" />
  <Bar dataKey="uv" fill="#82ca9d" />
</BarChart>
```

Because the default value of `type` in `XAxis` is `'category'`.

**Comment by macgyver** [comment]
seems like the default types of `XAxis` and `YAxis` are tuned for a `horizontal` layout chart - would it be an improvement to the library if the defaults for the axes would change automatically when the chart's layout is switched?
