### ISSUE TITLE
Ability to distinguish dotted and dashed line of same colour in the legend

### ISSUE THREAD

**Issue by devison** [recharts/recharts#900]
## Do you want to request a feature or report a bug?

New feature

## What is the current behavior?

If there is a solid and dotted line of same colour, currently unable to identify these in the legend.  (Unless I've missed a feature).

![image](https://user-images.githubusercontent.com/4816012/30600659-f8232cfc-9d57-11e7-948e-cdaf543b1854.png)

See also #850.

**Comment by xile611** [comment]
Duplicated to #970
