### ISSUE TITLE
pie charts label overlapping and label hidden 

### ISSUE THREAD

**Issue by Bopaiah-MD** [recharts/recharts#903]
the issues regarding pie charts label overlapping and label getting hidden 
![pie_hidden_label](https://user-images.githubusercontent.com/30290037/30648698-4a8aa5e4-9e3c-11e7-8615-4f6994589d16.jpg)

this occurs when value is small .
Note: i tried increasing  the pie chart size
@xile611 ? is there a fix for this

**Comment by MDB-20** [comment]
can any 1 commen

**Comment by giulioambrogi** [comment]
any update on this?

**Comment by andrevinsky** [comment]
Yes, however, what if the task is to show labels? This is applied to Scatter, too.

**Comment by alexsmartens** [comment]
Hi @andrevinsky,
did you figure out how to handle scatter plot labels overlap?

**Comment by 7hibault** [comment]
+1

**Comment by alexrus123** [comment]
Hi, what's the work around? anyone figured out? I'll post it if I find it

**Comment by tinkermachine** [comment]
Looking for a workaround here too. Seems like a pretty long standing issue that has not been resolved

**Comment by sivapriya-k** [comment]
Hi, did anyone figure it out? How to handle overlapping labels in scatter chart?

**Comment by hyeda1103** [comment]
I had to display the labels always, and also prevent overlapping between them. I made a custom label to solve this issue, and the following function is the one that I assigned to `label` property of `Pie` component:
```
const renderCustomizedLabel = (props) => {
  const { cx, cy, midAngle, outerRadius, fill, payload, percent } = props;
  const sin = Math.sin(-RADIAN * midAngle);
  const cos = Math.cos(-RADIAN * midAngle);
  const delta = Math.abs(1 / cos) + 10;
  const sx = cx + outerRadius * cos;
  const sy = cy + outerRadius * sin;
  const mx = cx + (outerRadius + delta) * cos;
  const my = cy + (outerRadius + delta) * sin;
  const ex = mx + Number(cos.toFixed(1)) * 20;
  const ey = my;
  const textAnchor = cos >= 0 ? "start" : "end";

  return (
    <g>
      <path
        d={`M${sx},${sy}L${mx},${my}L${ex},${ey}`}
        stroke={addAlpha(theme.palette.common.white, 0.2)}
        fill="none"
      />
      <rect x={ex + (cos >= 0 ? 1 * 5 : -1 * 17)} y={ey - 4} width={12} height={8} fill={fill} />
      <text
        x={ex + (cos >= 0 ? 1 : -1) * 21}
        y={ey + 4}
        textAnchor={textAnchor}
      >
        {`${payload.name}: ${(percent * 100).toFixed(2)}%`}
      </text>
    </g>
  );
};

...

<Pie
  dataKey="value"
  data={data}
  label={renderCustomizedLabel}
  labelLine={false}
  cx="50%"
  cy="50%"
  innerRadius={56}
  outerRadius={80}
>
..
</Pie>
```
The result is shown in the following picture. There are duplicate labels, but it is okay to ignore them:
![20221212_152426](https://user-images.githubusercontent.com/61447729/206975983-52b0dd2e-f8ab-4c60-8318-417871f51f1f.png)

**Comment by Bumboobee** [comment]
It been five years and still no verified sollution was found to this issue?

Need that asap. Anyone figure out how to solve this behavior?

**Comment by andrevinsky** [comment]
> Hi [@andrevinsky](https://github.com/andrevinsky), did you figure out how to handle scatter plot labels overlap?

Sorry, no. I just read your question. But on the other hand, off the project that I've had recently, this label-clutter needs to be handled by the designs :) Namely, if a number of labels happened to be near one spot, you have to come up with the single label replacement saying: we have here N+ labels. Hover or click on it, to see the list or have other behavior. So, there's no neat out-of-the-box solution.
