### ISSUE TITLE
Highlighting week days on the chart

### ISSUE THREAD

**Issue by sunndeath** [recharts/recharts#904]
Good afternoon.
Can I highlight the weekend-days in gray on the chart, thus: 

![image](https://user-images.githubusercontent.com/8881978/30705243-929b1d3e-9efd-11e7-91e7-abdcf7e73a84.png)

If so, how?
Thank you.

**Comment by xile611** [comment]
@sunndeath You can try [`ReferenceArea`](http://recharts.org/#/en-US/api/ReferenceArea).
