### ISSUE TITLE
BiaxialBarChart with negative stack chart

### ISSUE THREAD

**Issue by myangsc** [recharts/recharts#905]
## Do you want to request a feature or report a bug?
Feature

## What is the current behavior?
I think it doesn't work somehow, I use stackId, yAxisId in the bar, and it complain something locally, it also doesn't draw a right image in the jsfiddle demo

http://jsfiddle.net/hdks6k6x/32/

![image](https://user-images.githubusercontent.com/24736857/30725833-46d75ba2-9efc-11e7-822f-317e36adbc96.png)

`<BarChart
      stackOffset="sign"
     >
       <XAxis dataKey="name"/>
       <YAxis yAxisId="left" orientation="left" stroke="#8884d8"/>
       <YAxis yAxisId="right" orientation="right" stroke="#82ca9d"/>
       <CartesianGrid strokeDasharray="3 3"/>
       <Tooltip/>
       <Legend />
       <Bar yAxisId="left" dataKey="pv" fill="#8884d8" stackId="a" />
       <Bar yAxisId="right" dataKey="uv" fill="#82ca9d" stackId="a" />
      </BarChart>`

**Comment by elisechant** [comment]
@myangsc can you describe what you expect it should look like?

**Comment by myangsc** [comment]
@elisechant  hi, I expect it looks like this 
![image](https://user-images.githubusercontent.com/24736857/30767711-163d7036-9fb4-11e7-8bb9-265641feee8a.png)

BUT with different scale for positive yAxis and negative yAxis.

Because in my use case, the data range of positive data is much larger than the negative data, if using same scale, it will make negative chart very short.

Hopefully this can be understand, I feel like rechart should be able to do it, because it already able to do BiaxialBarChart, http://recharts.org/#/en-US/examples/BiaxialBarChart and http://recharts.org/#/en-US/examples/BarChartStackedBySign http://recharts.org/#/en-US/examples/BarChartStackedBySign

I just want to combine these two, but it looks like there is some error

**Comment by myangsc** [comment]
@xile611 can you guys take look for this? if possible, also with a demo, thanks~
