### ISSUE TITLE
Fix jsnext:main entry

### ISSUE THREAD

**Issue by damianobarbati** [recharts/recharts#906]
Current `jsnext:main` entry in `package.json` is a transpiled file when it shouldn't be: the whole purpose of `jsnext:main` is to let developers transpile everything in their own environments!
`jsnext:main` should just be plain `./src/index.js` file here.

On the other side, `module` entry defines just the main "export" statement thus it's ok to link the transpiled content.

**Comment by xile611** [comment]
@damianobarbati Thank you for your suggestion. And I have check some articles (like [this](https://shuheikagawa.com/blog/2017/01/05/main-jsnext-main-and-module/)) and some popular repos, all the repos specify `jsnext:main` to be `es6/index.js`.
