### ISSUE TITLE
Custom label disappears from Pie chart when changing `isAnimationActive` prop

### ISSUE THREAD

**Issue by nsmirn0v** [recharts/recharts#907]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
When I change isAnimatedActive property on Pie chart, custom labels disappear.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).
[demo](http://jsfiddle.net/2rt6rj2h/181/)

## What is the expected behavior?
Labels should not disappear.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
recharts version `^1.0.0-alpha.4`

**Comment by kamthamc** [comment]
@nsmirn0v I am not sure if its a bug or not but labels will not be rendered while animation is active.
https://github.com/recharts/recharts/blob/c8d80efe854874f69a40968c89ccde56b448b7db/src/polar/Pie.js#L344

**Comment by nsmirn0v** [comment]
Looks like `state.isAnimationFinished` doesn't get updated when `isAnimationActive` property changes.
@kamthamc it's a bug

**Comment by kamthamc** [comment]
@nsmirn0v then its a bug with react-smooth i guess,
https://github.com/recharts/recharts/blob/c8d80efe854874f69a40968c89ccde56b448b7db/src/polar/Pie.js#L261
https://github.com/recharts/recharts/blob/c8d80efe854874f69a40968c89ccde56b448b7db/src/polar/Pie.js#L280

**Comment by kamthamc** [comment]
@nsmirn0v I think I found the issue https://github.com/recharts/recharts/blob/c8d80efe854874f69a40968c89ccde56b448b7db/src/polar/Pie.js#L489

its checking for active animation and since the old and new sectors are same its not performing the animation which in result isAnimationActive is never false when changed from false to true causing the labels to never render

**Comment by kamthamc** [comment]
Resolved the issue http://jsfiddle.net/8zqd4cgg/2/
