### ISSUE TITLE
Chart without Y-Axis and with solid colors

### ISSUE THREAD

**Issue by iphonic** [recharts/recharts#908]
Hi, I am using recharts **1.0.0-apha.5** in my reactjs webapp. In my chart I don't want to show Y-Axis, for which I didn't include Y-Axis in component definition it was gone but it broke X-Axis labels, I used interval={0} to bring all the x-axis labels, but it doesn't look good check image below

![screen shot 2017-09-23 at 3 27 23 pm](https://user-images.githubusercontent.com/5745637/30772203-6049f1b6-a074-11e7-8356-23f62c71a170.png)

Check the code below

```
const {AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend} = Recharts;
const data = [{name: "2017-02-03", ios: 2, android: 0},
                {name: "2017-08-30", ios: 2, android: 0},
                {name: "2017-09-02", ios: 1, android: 0},
                {name: "2017-09-05", ios: 1, android: 0},
                {name: "2017-09-06", ios: 1, android: 0},
                {name: "2017-09-07", ios: 1, android: 0},
                {name: "2017-09-09", ios: 3, android: 0},
                {name: "2017-09-11", ios: 1, android: 0},
                {name: "2017-09-15", ios: 0, android: 1}];

const AreaCharts = React.createClass({
	render () {
  	return (
      <ResponsiveContainer>
                <AreaChart data={data}
                      margin={{top: 10, right: 30, left: 0, bottom: 0}}>
                  <XAxis dataKey="name" interval={0}/>
                  <CartesianGrid strokeDasharray="2 2"/>
                  <Tooltip/>
                  <Area type='monotone' dataKey='ios' stroke='#3e9112' fill='#7ec857' />
                  <Area type='monotone' dataKey='android' stroke='#0e6dd3' fill='#0f80fb' />
                </AreaChart>
              </ResponsiveContainer>
    );
  }
})

ReactDOM.render(
  <AreaCharts />,
  document.getElementById('container')
);
```

I tried to add jsFiddle but some what Recharts doesn't work with jsFiddle.

So as in image above, I have two problems

1. Removing Y-Axis disturbs the UI completely.. How to Fix?
2. I wan't to use the exact defined color which I am supplying to the component, how to achieve that?

Thanks.

**Comment by kamthamc** [comment]
@iphonic its broken regardless of whether you add YAxis or not because of the width. X/Y Axis should allow / smartly(depending on the available width for text) render labels horizontally/vertically or with an angle.

**Comment by xile611** [comment]
@iphonic Just as what @kamthamc has said, you should add a angle to ticks of XAxis, If you want to show all the ticks. 
And I don't quite understand the second question...
