### ISSUE TITLE
Can not import due to react-dom not found

### ISSUE THREAD

**Issue by emiloberg** [recharts/recharts#91]
Hi,

When adding recharts to a fairly simple React project and importing it as `import x from 'recharts'` I'm getting this error in my Webpack build.

```
ERROR in ./~/recharts/lib/component/Legend.js
Module not found: Error: Cannot resolve module 'node_modules/react-dom/dist/react-dom.min/server' in /Users/emiloberg/code/charttest/node_modules/recharts/lib/component
 @ ./~/recharts/lib/component/Legend.js 51:14-41

ERROR in ./~/recharts/lib/component/Tooltip.js
Module not found: Error: Cannot resolve module 'node_modules/react-dom/dist/react-dom.min/server' in /Users/emiloberg/code/charttest/node_modules/recharts/lib/component
 @ ./~/recharts/lib/component/Tooltip.js 47:14-41
```

I can't really figure out why (and not where that `.min` part comes from), but looking at the `Legend.js` and `Tooltip.js` files they're importing ReactDOM as: 
```
import ReactDOMServer from 'react-dom/server';
```

That points to the source files.

Replacing the import lines in those two files with this line will solve the problem: 

```
//import ReactDOMServer from 'react-dom/server';
import ReactDOMServer from 'react/lib/ReactDOMServer';
```

Please let me know what I can do to help debugging.

**Comment by jasonHzq** [comment]
In fact,  `react-dom/server` package is equivalent to `react/lib/ReactDOMServer` package.

The code in `react-dom/server` is as below:

```
'use strict';

module.exports = require('react/lib/ReactDOMServer');

```

We can't diagnose the problem without your webpack config code, can you show your webpack config code here ?

**Comment by emiloberg** [comment]
Ah finally figured it out. I was using an old webpack config and had (for some reason I can't even think of)  an alias set up; `'react-dom': 'node_modules/react-dom/dist/react-dom.min'`
