### ISSUE TITLE
Pass Tooltip orientation to custom Tooltip

### ISSUE THREAD

**Issue by nathmack** [recharts/recharts#911]
## Do you want to request a feature or report a bug?

Feature

## What is the current behavior?

No enough data

## What is the expected behavior?

To have get an indication of whether the tooltip is on the left or right of the cursor
eg.
![image](https://user-images.githubusercontent.com/15811469/30844680-71b048b8-a2d3-11e7-9506-d336e5c9be5a.png)
![image](https://user-images.githubusercontent.com/15811469/30844609-22173aaa-a2d3-11e7-8f99-da27074a321a.png)

It would be really got to get some indication of what side of the line the tooltip is rendering, so I can pass a direction prop to my custom tooltip

**Comment by xile611** [comment]
Sorry, not supported yet. It's recommended to use customized `content` of `Tooltip` to cover default tooltip.

**Comment by trainoasis** [comment]
@xile611 still not in 2023 or am I missing something? Thanks

**Comment by hadassaplotnik** [comment]
How about now, is this supported yet?
