### ISSUE TITLE
React 16 Support

### ISSUE THREAD

**Issue by kamthamc** [recharts/recharts#913]
## Do you want to request a feature or report a bug?
feature
## What is the current behavior?
failing in React 16
## What is the expected behavior?
it should run seamlessly just as in React 15
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts alpha 5, React 16, chrome & safari

**Comment by iEchoic** [comment]
+1 - this appears to be due to not updating from React.PropTypes to the 'prop-types' library, not sure if there are more issues underneath that

**Comment by kamthamc** [comment]
If its just the prop-types i can update it. Looks like no one is reviewing prs

**Comment by juampick** [comment]
+1

**Comment by viztor** [comment]
@kamthamc It's already all 'prop-types', there are other issues around.

**Comment by liorbrauer** [comment]
Hi, just wanted to point out that some of the dependencies are incompatible with React 16, like react-resize-detector and others

**Comment by liorbrauer** [comment]
@xile611 thanks for the update! 

I believe there's a dependency that prevents recharts from working with React 16:
- `react-smooth` (0.3.0) - doesn't support react 16
