### ISSUE TITLE
Don't load examples

### ISSUE THREAD

**Issue by jfajardo** [recharts/recharts#914]
Please the examples don't load
http://recharts.org/#/en-US/examples/StackedBarChart

**Comment by eskawl** [comment]
React was not loading in the examples. React 16.0.0 moved files from the dist folder to umd.

From the release notes:

>The names and paths to the single-file browser builds have changed to emphasize the difference between development and production builds. For example:
react/dist/react.js → react/umd/react.development.js
react/dist/react.min.js → react/umd/react.production.min.js
react-dom/dist/react-dom.js → react-dom/umd/react-dom.development.js
react-dom/dist/react-dom.min.js → react-dom/umd/react-dom.production.min.js

**Comment by xile611** [comment]
The examples have been updated.
