### ISSUE TITLE
If there is no scroll bar on the page, animation of pie is not working.

### ISSUE THREAD

**Issue by KalpanaPagariya** [recharts/recharts#917]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
If I give hieght of page which will show scroll bar, then the animation of pie is working. If tehre is no scroll bar, then animation effect is not coming for pic chart.

## What is the expected behavior?
pie chart should show animation.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
"recharts": "^1.0.0-apha.5",

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.
