### ISSUE TITLE
Custom reference icon for bar chart

### ISSUE THREAD

**Issue by reginavlee** [recharts/recharts#922]
## Do you want to request a feature or report a bug?
Request a feature

I am rendering a Bar Chart and am currently using Reference dots in the chart. However, I would like to render custom svg icons (like checks or x marks) instead of circles as reference points and was wondering if the code supported that, and if not, if it was a feasible feature that could be added.

Using v0.22.4

**Comment by xile611** [comment]
@reginavlee Use props `shape` which can be a function or react element to render customized shape.

```jsx

<ReferenceDot shape={renderShape} />
```

**Comment by reginavlee** [comment]
Thanks, I've got an icon showing up now. However, it's not in the correct position. I've tried passing down the props to the custom element and the html shows that i received the x, y, cx, and cy values but it is shifted on the graph.

Reference Dot:
`<ReferenceDot shape={<ValidateCheck />} x={index} y={5} key={`referencedot-${index}`} isFront={true} />`
(where index = 60 for example)

Custom Icon:
`const ValidateCheck = (props) => {
  <svg width="13" height="10" viewBox="0 0 13 10" {...props} xmlns="http://www.w3.org/2000/svg">
    <title>Path 277</title>
    <path stroke="#57DA06" stroke-width="2" d="M1 5l3.5 3.5 7-7.5" fill="none" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round"/>
  </svg>
}`

For Reference:
<img width="566" alt="screen shot 2017-10-03 at 11 22 14 am" src="https://user-images.githubusercontent.com/14262965/31141813-4484b7f2-a82d-11e7-954d-28537a3b351e.png">

<img width="876" alt="screen shot 2017-10-03 at 11 21 55 am" src="https://user-images.githubusercontent.com/14262965/31141798-381beef4-a82d-11e7-8489-dd2bad250443.png">

I would like the check marks to be where the circle reference dots are.

**Comment by levininja** [comment]
For anyone else trying to render custom shapes, here's an example:

```
//custom component
const SmallDot = (props)=>{
    const radius = 2.5;
    const diameter = radius * 2;
    return (
        <svg width={diameter} height={diameter} style={{"overflow": "visible"}}>
            <circle cx={props.cx} cy={props.cy} r={radius} stroke="green" strokeWidth="0" fill={props.color} />
        </svg>
    );
}

//usage
<Scatter name={model.name} data={model.data} key={model.name} fill={#ddd} dot={ dotStyle } line shape={<SmallDot color={fillColor} />}  />

```
the recharts component passes in cx and cy for you.

**Comment by intelcoder** [comment]
Is shape prop gone ? I cannot see that in doc.

**Comment by owensco** [comment]
If anyone wants to do this with `react-icons`...
```
import * from 'react-icons/fa';

const CustomDot = (props) =>{
  return (
    <FaStar size={28} x={props.cx} y={props.cy} />	
  );
}

<Scatter ... shape={<CustomDot />}  />
```
Looks like the props changed from `cx` and `cy` to simply `x` and `y` respectively.

**Comment by Baal-Marduk** [comment]
Hey, furthemore if you'd like to align your icon, just do as follow:

`    const ArrowUp = (props) => {
            return (
                <HiArrowUp
                    size={28}
                    x={props.x - props.width / 2}
                    y={props.y - props.height / 2}
                />
            )
    }`
