### ISSUE TITLE
Legend font size

### ISSUE THREAD

**Issue by nc-sjoquistn** [recharts/recharts#923]
There is an easy way to change the size of the icons in the Legend by providing the `iconSize` prop, but why is there no similar `fontSize` prop? If given one, it seems the other should be provided as well...

**Comment by eldyvoon** [comment]
You can always use custom content and add ur own element, from there you can adjust your element size using CSS.

**Comment by jdlacey-clevertech** [comment]
I don't think this should be closed. It seems like an oversight to allow the icon size to be changed via a prop but in order to change the font size you need to provide your own content.

**Comment by MasroorHamdani** [comment]
Do we have any solution so far or is it still open.
As rightly mentioned by @jdlacey-clevertech it doesn't make sense to add custom legend just to change the font size.

**Comment by kmayur35** [comment]
wrap chart inside div with .classname and use this code for font-size adjustment
ex-
<div classname="chartWrap">
    <LineChart />
</div>

.chartWrap {
  &>div>div>ul>li>span {
    font-size: 12px;
  }
}

this worked for me.

**Comment by talwarabhimanyu** [comment]
On inspecting the DOM element related to the legend entries, each entry's classNam="recharts-legend-item". So the following lines of CSS work fine:
`.recharts-legend-item {
        font-size: 0.75rem;
}`

**Comment by lippyDesign** [comment]
Would this work? `<Legend wrapperStyle={{fontSize: "10px"}}/>`. seems to reduce the size of the legend text for me

**Comment by KavinduGihan630** [comment]
> wrapperStyle={{fontSize: "10px"}}

thank

**Comment by salahelfarissi** [comment]
Thank you
