### ISSUE TITLE
Funnel Chart 

### ISSUE THREAD

**Issue by DennisKo** [recharts/recharts#925]
Feature request

We are currently evaluating which charting library we gonna use. Is it possible to create a "Funnel" chart in recharts? Similiar to this: https://jakezatecky.github.io/d3-funnel/ 

The examples site is not working atm and its hard to judge just by the API :/

**Comment by kenzouno1** [comment]
+1

**Comment by VadLogan** [comment]
+ 1

**Comment by mazyn** [comment]
+1

**Comment by maduraPradeep** [comment]
+1

**Comment by 00karthik** [comment]
+1

**Comment by linweigao** [comment]
Is this an official funnel chart by recharts? https://bit.dev/recharts/recharts/funnel-chart

**Comment by pedroota** [comment]
Any updates here?

**Comment by ckifer** [comment]
Funnel chart exists and is supported
