### ISSUE TITLE
Examples are broken on http://recharts.org/#/en-US/examples

### ISSUE THREAD

**Issue by goldensunliu** [recharts/recharts#926]
![image](https://user-images.githubusercontent.com/1348993/30981679-19ae686c-a453-11e7-96aa-76b0538120b6.png)

404ing on all the resources needed to load the examples from JSFiddle

**Comment by spartan082189** [comment]
Getting the same errors

**Comment by blakegilchrist** [comment]
Same issue here. Broken asset links, 404 errors.

**Comment by ThePianoDentist** [comment]
it's effort.

but I was able to view the examples by 

- clicking the Js-fiddle link.
- click external resources
- delete the react-with-addons and react-dom links
- replace them (with the add button) with https://npmcdn.com/react@^15/dist/react-with-addons.min.js
and https://npmcdn.com/react-dom@^15/dist/react-dom.min.js
- move them both up the order to just below browser.js (addons above dom)

if desperately need to see examples now. hopefully npmcdn.com sorts out their issue (I have not informed them. assumed someone else has)

**Comment by henrinormak** [comment]
Isn't this related to the fact that React is now bundled differently? According to [this](https://reactjs.org/blog/2017/09/26/react-v16.0.html#installation) & [this](https://reactjs.org/blog/2017/09/26/react-v16.0.html#packaging), I would say this is not npmcdn's fault, as the URL should be different for React 16.

**Comment by quytang** [comment]
Hi there
Any update? I need the example to show demonstration on my team discussion.
It's urgent 😢

**Comment by xile611** [comment]
The examples have been updated.

**Comment by talJoffeExelate** [comment]
looks like it is broken again...
![screen shot 2018-04-02 at 15 42 23](https://user-images.githubusercontent.com/16097292/38196571-7debce70-368c-11e8-8357-a3965d682968.png)
