### ISSUE TITLE
Pie Chart - No Label Shown

### ISSUE THREAD

**Issue by quangas** [recharts/recharts#929]
Trying to get a label shown on a simple pie chart. No lines or anything are shown.

```
var COLORS = ['#3DCC91', '#FFB366', '#FF7373', '#FFCC00', '#3B22FF'];

        <PieChart width={300} height={200}>
          <Pie data={data} cx="50%" cy="50%" dataKey="value" label={true} labelLine={true}>
            {
              data.map((entry, index) => (
                <Cell key={index} fill={COLORS[index % COLORS.length]}  />
              ))
            }
          </Pie>
          <Tooltip />
          <Legend />
        </PieChart>
```

Why do none of the examples work on jsFiddle or on the main site? It just renders blank page.

UPDATE
So, I dropped back to version 0.22.4 and it shows the label. The latest version doesn't show it.

**Comment by Danielh21** [comment]
I have the same issue, but I would like not to roll back!

**Comment by davidsonsns** [comment]
I had the same problem. I came back to the version as the @quangas said and it worked. in the end i went to another lib

**Comment by stevelacy** [comment]
@davidsonsns which lib did you switch to?

**Comment by fgiarritiello** [comment]
Having the same problem. Switching back to 0.22.4 works but then I get other problems.

**Comment by davidsonsns** [comment]
I'm using this @stevelacy [react-chartjs-2](https://github.com/jerairrest/react-chartjs-2)

**Comment by pebanfield** [comment]
In my case setting isAnimationActive={false} resolves the issue. Of course this means doing without the animation.

The line of code below seems to be the problem - 

https://github.com/recharts/recharts/blob/master/src/polar/Pie.js#L346

The intent is to not render labels until animation completes which makes sense. However, there appears to be a race condition that means labels are never rendered.

**Comment by xile611** [comment]
http://jsfiddle.net/8wLgvst6/

The labels are visible when isAnimationActive is false or true.

**Comment by pebanfield** [comment]
Hmm - well I am definitely reproducing the issue but I have more than one Pie shape in my PieChart. 

This issue also appears to be present in the examples. I am away from my computer but I will try produce a fiddle to reproduce the issue when I get back. Thanks!

**Comment by pebanfield** [comment]
@xile611 - I added an additional Pie shape to your fiddle and it works fine. So that's not the problem. I also tried changing a few other properties to try to isolate the issue I am seeing in my build and did not reproduce the issue in your fiddle. It seems to be pretty stable.

My webpack based build is very different from the test and so I am unable to isolate any further at this time. Since the other users on this thread mention an old version and the fiddle is working with a new version - it seems to me like this issue could be closed. I can open another separate issue if I can isolate a problem in my build. Thanks.

**Comment by ethan-deng** [comment]
I think there is currently a bug with the Customized Label. If you go to http://recharts.org/#/en-US/examples/PieChartWithCustomizedLabel directly, the customized label will be drawn. But if you go to any other link first such as http://recharts.org/#/en-US/examples/SimpleScatterChart then click on "PieChartWithCustomizedLabel", then the customized label won't be drawn.

**Comment by Ziker22** [comment]
I think this is still not working.
I'm on 1.0.0-beta.10

Also example which @xile611 provided http://jsfiddle.net/8wLgvst6/ is all blank

**Comment by jaylucas** [comment]
isAnimationActive={false} worked for me. Although my labels are aligning a little funny.

**Comment by justduy** [comment]
I use `<Pie label={customLabel} />` and I also get the problem, unless I deactivate the animation it won't show.
**react**:  ^16.2.0
**recharts**: ^1.0.0-beta.10

**Comment by JonyTek** [comment]
Still happening here too. The work around seems to be disabling the animation which isn't ideal.

**Comment by arashkiani** [comment]
So we have to choose between animation or label ... 

react : 16.3.1
rechart : 1.0.0-beta.10

**Comment by KyleAsaff** [comment]
still having this problem as well, seems to happen when fetching async data then the label draw function is never called

**Comment by ovation22** [comment]
I'm seeing the issue as well in beta 10. Appears to be happening in the JSFiddle as well. Is there something I can do to help to get this resolved?

**Comment by drastus** [comment]
Why this was closed? The problem still exists (Recharts 1.3.4).

**Comment by samueldepooter** [comment]
Still an issue in 1.4.1.
- animation enabled: no labels
- animation disabled: labels show

**Comment by kostiantyn-solianyk** [comment]
I think you can do custom label for pie without disabling the animation, and it can be even simply.

example:
prop label={item => this.renderCustomLabel(item)}

and in renderCustomLabel method you can return svg element like <text><tspan>/<tspan/></text>

renderCustomLabel = item => (
    <text
      fill={item.fill}
      x={item.x}
      y={item.y}
      stroke='none'
      alignmentBaseline='middle'
      className='recharts-text recharts-pie-label-text'
      textAnchor='end'
    >
      <tspan x={item.x} textAnchor={item.textAnchor} dy='0em'>{item.name}</tspan>
   </text>

when l did the way like that. It worked for me.

**Comment by tdotholla** [comment]
still happening in `"recharts": "^1.5.0"` 

`isAnimationActive={false}` resolves the issue.

**Comment by sarink** [comment]
I tried to keep a state flag for this, but it turns out that `onAnimationEnd` is never called. I've settled for setting a flag in a `setTimeout` after the initial render (for now).

**Comment by jonasgroendahl** [comment]
Still a problem , isAnimationActive={false} resolves the issue.

**Comment by YassienW** [comment]
`"recharts": "^1.6.2"`

Still happening, i guess a new issue should be opened.

**Comment by ObaldThePedro** [comment]
Still happening. 2019

**Comment by SeanThompsonUptick** [comment]
This has been an issue for over 2 years now.  Seems they don't gaf.

**Comment by crtormen** [comment]
I didn't even want animation.

**Comment by Vladis466** [comment]
Still having trouble sleeping due to this issue :(
Might be time to submit a PR.

**Comment by semanser** [comment]
I was trying to investigate this issue, because I was getting it before, but it seems like all the demos are working fine right now. 

Can someone reproduce this issue with the latest version of recharts and `yarn demo` command?

**Comment by JonyTek** [comment]
It's a tough one to reproduce as it's intermittent. I noticed it again just last week although I am on an old version 1.7.1. I haven't been watching releases but assume it's still there since there hasn't been much activity in this issue. Good luck.

**Comment by 1nfinity-5starZ** [comment]
Still happening. My fix was to use  isAnimationActive={false}

**Comment by zilahir** [comment]
the problem happens for me, if i am rendering 2 different `<Piechart />`. Removing one of them solving the issue, also using `isAnimationActive={false}` does the trick. 

What I am thinking is to somehow handle whether the animation had been complete, then sate a state, showing the labels, but havent tried.

**Comment by semanser** [comment]
It would be nice to have a repo where this bug can be reproduced. Or maybe jsfiddle.

**Comment by Cuxs** [comment]
Still happening

**Comment by agilityhawk** [comment]
Turning your PieChart into a PureComponent seems to fix the issue for the most part.
Tried it out on my chart by wrapping it with React.memo(pieChartComponent) and that seems to fix the issue.

Ref: https://github.com/recharts/recharts/issues/1083#issuecomment-535078802

Hope this helps.

**Comment by MateuszFislak** [comment]
> Turning your PieChart into a PureComponent seems to fix the issue for the most part.
> Tried it out on my chart by wrapping it with React.memo(pieChartComponent) and that seems to fix the issue.
> 
> Ref: [#1083 (comment)](https://github.com/recharts/recharts/issues/1083#issuecomment-535078802)
> 
> Hope this helps.

In case functional component wrapping function for rendering labels in useCallback also fixes the issue.

**Comment by jabberwo** [comment]
Still happening today.  Like those before me, turning off animation made it work.

Note, it happens in my webpacked app -- but not in the storybook I used during component development.

**Comment by mehrdadab** [comment]
I have the same issue. I can only see the labels when I set isAnimationActive to false

**Comment by stsiwo** [comment]
I had the same issue, but useCallback solved the issue even if using isAnimationActive={true} like @MateuszFislak mentioned. Thanks!!

**Comment by harmonikas996** [comment]
Making PieChart a separate React component and wrapping it with `memo(ComponentName)` solved the issue for me.

**Comment by Darren120** [comment]
> Still an issue in 1.4.1.
> 
> * animation enabled: no labels
> * animation disabled: labels show

animations disabled doesn't show

react nextjs

using tooltip plus legend with pichart

looks like a race condition as sometimes it show and other times it doesnt

**Comment by sujin-lifology** [comment]
Still the issue not solved

animation enabled: no labels
animation disabled: labels show
