### ISSUE TITLE
Render Ref Lines/Dots over chart

### ISSUE THREAD

**Issue by emiloberg** [recharts/recharts#93]
Currently, the reference lines/dots are rendered _before_ the actual chart component (in `[generateCategoricalChart.js`](https://github.com/recharts/recharts/blob/master/src/chart/generateCategoricalChart.js#L750-L751))

As SVGs do not have the concept of z-index but rather renders elements as they appear in the document this means that we can't have ref lines/dots _on top of_ chart data.

Is there a reason for ref lines/dots being rendered below?

**Comment by jasonHzq** [comment]
Yes, we think the ReferenceLine and the ReferenceDot are auxiliary so we render them before chart.

In AreaChart or BarChart, the ref lines/dots may be sheltered from the chart, you may set a fillOpacity to Bar or Area.

What do you think？

**Comment by emiloberg** [comment]
I'm not really following. Could you perhaps post a small example of how to shelter the refs from e.g. a Bar chart?

**Comment by jasonHzq** [comment]
of course, you can see what I mean in jsfiddle:

http://jsfiddle.net/hzongquan/435Lf8sa/4/

**Comment by jasonHzq** [comment]
We have modified the render order. Chart render before the refs now , so the refs will above the chart . 

And if you want let refs render below chart, you can add a prop `isAbove` which means chart render above the refs. The sample code is as below: 

```
<BarChart width={400} height={400} data={data} isAbove >
  <XAxis dataKey="name" />
  <YAxis />
  <Legend />
  <Tooltip />
  <CartesianGrid vertical={false} />
  <ReferenceLine y={3200} stroke="red" />
  <Bar dataKey="uv" fill="#ff7300" />
  <Bar dataKey="pv" fill="#387908" />
  </Bar>
</BarChart>
```

You can use this feature when the next version is released.

Thanks!

**Comment by emiloberg** [comment]
This is awesome! Cheers!

**Comment by AnkRaiza** [comment]
Hi, how about rendering the elements in the order we provide?,  i'm currently trying to show the axis inside the bars on the barchart but can't use z-index, if i could render the axis at the end this would take priority whitout the z index, `<BarChart width={400} height={400} data={data}  >
  <YAxis />
  <Legend />
  <Tooltip />
  <CartesianGrid vertical={false} />
  <XAxis dataKey="name" />
</BarChart>`

**Comment by ppseprus** [comment]
Hey! I know this is already closed, and my question is not even entirely related, but maybe you guys have ran into it... It is #1325
Im interested if it is possible to only show references after the animation has ended... Anyone?
Thanks!

**Comment by jrlimtiaco** [comment]
@ppseprus Did you find a solution?
