### ISSUE TITLE
LabelList with variable positions

### ISSUE THREAD

**Issue by nc-sjoquistn** [recharts/recharts#930]
Is there an easy way to calculate the position for each `Label`? I have a line graph with 2 lines, and want to display the label on top for the top line and underneath for the bottom line (the lines may cross, so one is not strictly greater than the other).

**Comment by xile611** [comment]
@nc-sjoquistn Try the props `position="top"` and `position="bottom"` for the 2 lines.

**Comment by nc-sjoquistn** [comment]
Yes, but is there a way to give each point a different label position? When the 2 lines get near each other at certain points, it would be nice to reverse the positions (eg, if line 1 is `position="top"` and line 2 is `position="bottom"`, I want to switch this at certain x positions to be line 1 `position="bottom"` and line 2 `position="top"`)

**Comment by xile611** [comment]
@nc-sjoquistn Not support yet! I think multiple `<LableList />` are only suitable for some **beautiful** datas.
