### ISSUE TITLE
Radar chart ignoring fullMark ?

### ISSUE THREAD

**Issue by mcoeur** [recharts/recharts#933]
When providing different values for the "fullMark" attribute of multiple data entries, only the biggest value seems to be used.

Is there any way to use different scales for different entries ? 

On the following example, I want the maximum value for the subject "History" to be 10, but it's currently ignored : http://jsfiddle.net/sjs0t7am/1/

Also, is there a way to display multiple graduated axis on the radar ?

**Comment by yaroslav-perec** [comment]
@mcoeur  
Maybe this will help you [`](https://github.com/recharts/recharts/issues/67)

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
