### ISSUE TITLE
Error: React.Children.only expected to receive a single React element child.

### ISSUE THREAD

**Issue by jgentes** [recharts/recharts#935]
## Do you want to request a feature or report a bug?
bug

## What is the current behavior?
When using an iterator (scattercharts.map(s => <Scatter.../>) to generate Scatter components from an array, an error occurs during render.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).
I would! The current fiddles are broken due to an npmcdn.com issue with React 16 :(

## What is the expected behavior?
The parent <ScatterChart/> container should allow multiple children.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Alpha 5 of recharts, latest Chrome. Not sure if this is new or a regression.

**Comment by bcornett** [comment]
I'm doing the same thing with a `LineChart` and get this error.
```js
{Array.from({length: lineCount}).map((x, i) => (
  <Line key={i} dataKey={`line${i}value`} />
))}
```

**Comment by sorodrigo** [comment]
Same here :(

**Comment by eldyvoon** [comment]
This happens in RadarChart too, other charts is fine.

**Comment by ryanand26** [comment]
I got the same issue with a composed chart. I worked around it by storing the created array of lines/areas, not recreating it on each render.

**Comment by sorodrigo** [comment]
Another fix is spreading the resulting array.
```jsx
...[/* full with magic */].map(line => (<Line stuff={stuff} />))
```

**Comment by jgentes** [comment]
@sorodrigo I wasn't able to use the spread operator to fix the issue. And I'm not sure that works:

`...Array.map` - wouldn't it need to be `[...Array].map`?

**Comment by rafaelc0sta** [comment]
Also experiencing this :(

**Comment by ryanand26** [comment]
@rafaelc0sta @jgentes Can you create a demo on jsfiddle? The code I had with the issue was really convoluted so not suited to a demo.

**Comment by xile611** [comment]
Any idea to reproduce this case ? I can't reproduce this case in my local project.

**Comment by jgentes** [comment]
I've been trying, and as a result of trying I somehow got it working, although I don't know what I've done differently. But I'm happy now, so I'll go ahead and close this. Thanks for the help @ryanand26 and @xile611

**Comment by rafaelc0sta** [comment]
The problem happens when you re-do the lines in the render() method. If the lines stay the same (lines, not data), the problem goes away. Moving the lines to the constructor() makes it work.

**Comment by jgentes** [comment]
I'm going to reopen because I was able to reproduce based on what @rafaelc0sta mentioned. If the initial render includes one <Scatter/> and a subsequent render adds another <Scatter/> it throws the error.

@rafaelc0sta if you move the lines to constructor() then it won't update, so it doesn't really solve the problem for me.

**Comment by jgentes** [comment]
I doubt this is helpful, but I tried upgrading to React 16 and it may include better error details:

```
invariant.js?7313:42 Uncaught Error: React.Children.only expected to receive a single React element child.
    at invariant (invariant.js?7313:42)
    at Object.onlyChild [as only] (react.development.js?99ee:1020)
    at isChildrenEqual (ReactUtils.js?2c11:354)
    at Object.isChildrenEqual (ReactUtils.js?2c11:362)
    at CategoricalChartWrapper.componentWillReceiveProps (generateCategoricalChart.js?7ce3:126)
    at callComponentWillReceiveProps (react-dom.development.js?cada:9795)
    at updateClassInstance (react-dom.development.js?cada:9974)
    at updateClassComponent (react-dom.development.js?cada:10224)
    at beginWork (react-dom.development.js?cada:10605)
    at performUnitOfWork (react-dom.development.js?cada:12573)
invariant @ invariant.js?7313:42
onlyChild @ react.development.js?99ee:1020
isChildrenEqual @ ReactUtils.js?2c11:354
isChildrenEqual @ ReactUtils.js?2c11:362
componentWillReceiveProps @ generateCategoricalChart.js?7ce3:126
callComponentWillReceiveProps @ react-dom.development.js?cada:9795
updateClassInstance @ react-dom.development.js?cada:9974
updateClassComponent @ react-dom.development.js?cada:10224
beginWork @ react-dom.development.js?cada:10605
performUnitOfWork @ react-dom.development.js?cada:12573
workLoop @ react-dom.development.js?cada:12682
callCallback @ react-dom.development.js?cada:1299
invokeGuardedCallbackDev @ react-dom.development.js?cada:1338
invokeGuardedCallback @ react-dom.development.js?cada:1195
performWork @ react-dom.development.js?cada:12800
scheduleUpdateImpl @ react-dom.development.js?cada:13185
scheduleUpdate @ react-dom.development.js?cada:13124
enqueueSetState @ react-dom.development.js?cada:9646
ReactComponent.setState @ react.development.js?99ee:218
onStateChange @ connectAdvanced.js?4805:205
dispatch @ createStore.js?6413:173
dispatch @ VM156368:2
(anonymous) @ middleware.js?416a:22
(anonymous) @ index.js?e2e7:14
(anonymous) @ index.js?1014:41
dispatch @ VM156368:2
processEvent @ Monitor-dux.jsx?3185:268
(anonymous) @ Monitor-dux.jsx?3185:294
(anonymous) @ Monitor-dux.jsx?3185:294
(anonymous) @ Obj.js?2650:47
exports.filter @ Obj.js?2650:46
(anonymous) @ Monitor-dux.jsx?3185:283
Promise resolved (async)
getEvents @ Monitor-dux.jsx?3185:281
componentDidMount @ RobotDetail.jsx?6da8:33
commitLifeCycles @ react-dom.development.js?cada:11505
commitAllLifeCycles @ react-dom.development.js?cada:12294
callCallback @ react-dom.development.js?cada:1299
invokeGuardedCallbackDev @ react-dom.development.js?cada:1338
invokeGuardedCallback @ react-dom.development.js?cada:1195
commitAllWork @ react-dom.development.js?cada:12415
workLoop @ react-dom.development.js?cada:12687
callCallback @ react-dom.development.js?cada:1299
invokeGuardedCallbackDev @ react-dom.development.js?cada:1338
invokeGuardedCallback @ react-dom.development.js?cada:1195
performWork @ react-dom.development.js?cada:12800
scheduleUpdateImpl @ react-dom.development.js?cada:13185
scheduleUpdate @ react-dom.development.js?cada:13124
scheduleTopLevelUpdate @ react-dom.development.js?cada:13395
updateContainer @ react-dom.development.js?cada:13425
(anonymous) @ react-dom.development.js?cada:17105
unbatchedUpdates @ react-dom.development.js?cada:13256
renderSubtreeIntoContainer @ react-dom.development.js?cada:17104
render @ react-dom.development.js?cada:17129
renderWithHotReload @ App.jsx?f880:93
(anonymous) @ App.jsx?f880:78
(anonymous) @ tend.d461911751abda673965.js:94
__webpack_require__ @ vendor.d461911751abda673965.js:696
fn @ vendor.d461911751abda673965.js:117
(anonymous) @ tend.d461911751abda673965.js:1735
__webpack_require__ @ vendor.d461911751abda673965.js:696
webpackJsonpCallback @ vendor.d461911751abda673965.js:26
(anonymous) @ tend.d461911751abda673965.js:1
react-dom.development.js?cada:8305 The above error occurred in the <ScatterChart> component:
    in ScatterChart (created by EventGraph)
    in div (created by ResponsiveContainer)
    in ResponsiveContainer (created by EventGraph)
    in div (created by EventGraph)
    in EventGraph (created by Robots)
    in div (created by TabPane)
    in Transition (created by Fade)
    in Fade (created by TabPane)
    in TabPane (created by Tab)
    in Tab (created by Robots)
    in div (created by TabContent)
    in TabContent (created by Tabs)
    in div (created by Tabs)
    in TabContainer (created by Tabs)
    in Tabs (created by Uncontrolled(Tabs))
    in Uncontrolled(Tabs) (created by Robots)
    in div (created by Robots)
    in div (created by Robots)
    in div (created by Robots)
    in div (created by Robots)
    in div (created by Robots)
    in div (created by ContentWrapper)
    in ContentWrapper (created by Robots)
    in Robots (created by Robots)
    in Robots (created by RouterContext)
    in section (created by Base)
    in div (created by Base)
    in Base (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by Routes)
    in Routes
    in Provider
    in AppContainer
```

**Comment by hklebs-cs** [comment]
I am running into this same issue. It seems to occur when a part of the state is updated which isn't relevant to the chart.  I was able to reproduce it here: http://jsfiddle.net/sh4vuy4c/17/

**Comment by jgentes** [comment]
Excellent, nice job @hklebs-cs! Maybe @xile611 could take a look now that it's reproducible.

I created a new jsFiddle because yours was using minified libraries and you couldn't see the error in the console. Here's the latest: http://jsfiddle.net/jgentes/sh4vuy4c/22/

**Comment by mansdahlstrom1** [comment]
Having the same problem!

My LineChart component is a stateless component and is used by a wrapper component which has a state. Whenever the state is updated in the parent wrapper (not the data. Only other variables in the state) I get the same error. A solution would be highly appreciated :)

**Comment by ZheyangSong** [comment]
Hey, for my project, the problem occurs when using the `ScatterChart`... After my team's analysis, the issue stems from lines of these two files:
https://github.com/facebook/react/blob/7e7127387ba64f57299eaff8656542cea6fb3a2d/packages/react/src/ReactChildren.js#L405-L407
https://github.com/recharts/recharts/blob/b95a84aa1e879c0f6de05219696a54220048a976/src/util/ReactUtils.js#L370

Since `this.props.children` can return multiple types (ReactNode, ReactNode[] or undefined), **[line370](https://github.com/recharts/recharts/blob/b95a84aa1e879c0f6de05219696a54220048a976/src/util/ReactUtils.js#L370) in ReactUtils.js** should pass the single node rather than the whole array into the checker.

This seems to be an easy fix. Not sure if anyone is interested in raising a PR to fix it. Thanks.

**Comment by ryanand26** [comment]
I've created a test case for this issue in my fork. Unfortunately I don't know the innards of React well enough to be confident in changing the equality check but hopefully this gives someone a head start.
[Fork commit](https://github.com/DaftApethIndustries/recharts/commit/7d0785b72592d04a88440979d5df7acfacd30254)

**Comment by xile611** [comment]
Try the latest version 1.0.0-beta.3.

**Comment by ZheyangSong** [comment]
@ryanand26 I took a look at your PR. Great Job! But, removing `Children.only` seems alter the code's logic, because after the change, `isSingleChildEqual` (which internally expects two ReactNodes to before shallow comparision, check out [this line](https://github.com/recharts/recharts/blob/9511adcf62ea0d8bb847b6b4c4d90e62b8ee73f9/src/util/ReactUtils.js#L351))  will always return false for single node array. As a result, it in turn affects this line https://github.com/recharts/recharts/blob/9d42367e658cab6bed0a8f2517f17be9e0cf0957/src/chart/generateCategoricalChart.js#L185. The code governed by this condition affects Brush and etc.

**Comment by ryanand26** [comment]
@ZheyangSong @xile611  I've looked into it a bit more and the root cause seems to be that the single elements return a count of one but are wrapped in an array. The code change in the fork above is probably safer than the first attempt.

**Comment by ZheyangSong** [comment]
@ryanand26 Yes, it is the root cause. You can find more details regarding it from my earlier comment in this thread. Glad to see you pin the issue down! 👍
