### ISSUE TITLE
Scatter with data that have similar x value doesn't plot any thing.

### ISSUE THREAD

**Issue by alishir** [recharts/recharts#940]
## Do you want to request a feature or report a bug?
it is a bug report
## What is the current behavior?
`Scatter` plot doesn't show anything when there is two data point with same `x` value in data:

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.net.
Yes here is the demo: http://jsfiddle.net/t1mh8whp/

## What is the expected behavior?
`Scatter` should plot scatter plot currectly.
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
recharts version is 1.0.0-apha.5. I didn't check previous versions.

**Comment by xile611** [comment]
@alishir You can specify the type of `<XAix />` to be `number` which has default value "category".
