### ISSUE TITLE
How many data points are reasonable? 

### ISSUE THREAD

**Issue by justduy** [recharts/recharts#941]
Currently I have 6000+ data points, and the area graph especially is affecting the performance heavily. Not sure if recharts should handle more than 6000 points.

**Comment by alyssaq** [comment]
You should probably downsample depending on how big the displayed chart needs to be. I generally plot less than 600 points on a chart

**Comment by stramec** [comment]
Is there a way to hook the Brush component in to returning it's new start and end values on the change event? I have the same problem of 8000+ data points, I'd like to average out and then request more data points if the user zooms in with the Brush.

**Comment by jparklev** [comment]
Hey @stramec, did you ever find a solution to this?

**Comment by cula** [comment]
> hook the Brush component in to returning it's new start and end values on the change event

+1

**Comment by xile611** [comment]
Duplicated with #1356
