### ISSUE TITLE
Line Chart - Line below the X-axis

### ISSUE THREAD

**Issue by Danielh21** [recharts/recharts#942]
Hi, first of all great Library I really enjoy it!

I found some weird behavior when using a Line Chart.
My Line goes below the X-axis which leads to a weird looking Chart.
I have reproduced the "bug" in this jsfiddle : http://jsfiddle.net/danielh21/7euyzdu6/10/

My values for the Chart are {x:0, x:0, x:0, x:1} and before last datapoint my line goes below the X-axis.
Can anyone explain why this is happening? 

Thanks in advance

**Comment by xile611** [comment]
@Danielh21 It's recommended to use  type `monotone` which will generate almost-smooth curve 
and guarantee the monotonicity of all the points at the same time.

```
<Line  type="monotone" />
```

**Comment by Danielh21** [comment]
Thanks! I will just use monotone then!
I consider this issue to be closed!
