### ISSUE TITLE
Point animation duration and first render delay even if isAnimationActive=false

### ISSUE THREAD

**Issue by ackvf** [recharts/recharts#945]
## Do you want to request a feature or report a bug?
bug
## What is the current behavior?
If a Linechart is set with `isAnimationActive={false}` the line dots are rendered after a default delay 1500ms.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).
```
      <LineChart ... >
        <Line animationDuration={0} isAnimationActive={false} ... />
        <Line isAnimationActive={false} ... />
      </LineChart>
```
## What is the expected behavior?
Expected is that if `isAnimationActive=false` there will be no delay to drawing points
OR better api documentation to suggest also setting `animationDuration={0}`.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

    "recharts": "^1.0.0-apha.5",

**Comment by samhuk** [comment]
Hey, I'm encountering this at the moment with latest v2. I can see that it was marked as completed. Was there a workaround?
