### ISSUE TITLE
[Feature]: Is it possible to make y-Axis width auto calculated?

### ISSUE THREAD

**Issue by IvanKalinin** [recharts/recharts#947]
Hi there. So, everything is in the header.
Currently we can only adjust fixed width for y-Axis. It would be nice to have an option for auto width. That  could remove extra white space on the container left edge.
Design 
![image](https://user-images.githubusercontent.com/12299212/31399364-e569c450-ada0-11e7-9c74-2542651f1a2b.png)

vs Real world

![image](https://user-images.githubusercontent.com/12299212/31399397-fda238f4-ada0-11e7-8a4b-5307b033ce7a.png)

**Comment by itwasmattgregg** [comment]
+1

**Comment by xile611** [comment]
Duplicated with #2027

**Comment by saroj-nf** [comment]
i am looking for same

**Comment by marluscw** [comment]
+1

is there any hack to fix this?

**Comment by uixmat** [comment]
still looking for a way to do this 🙏🏼
