### ISSUE TITLE
Not able to give dynamic height and width to piechart

### ISSUE THREAD

**Issue by KalpanaPagariya** [recharts/recharts#948]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
I am not able to give the dynamice height and width to piechart. It always expect number only. (no percentage)
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).
Any demo of recharts

## What is the expected behavior?
there should be a way to give dynamic height and width to pie chart

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
recharts version:  "recharts": "^1.0.0-apha.5",
OS: windows 10

**Comment by yaroslav-perec** [comment]
@KalpanaPagariya 
perhaps this will help you [http://recharts.org/#/en-US/api/ResponsiveContainer](url)
