### ISSUE TITLE
Performance issue with realtime data

### ISSUE THREAD

**Issue by Kroderia** [recharts/recharts#949]
There is a realtime datasource which generate 50 numbers every 500ms.
I load the data every 2500ms, which is 250 numbers, into a buffer. Then a timer with 50ms interval  will get 5 numbers from the buffer and push it (by `setState`) into the LineChart, like an animation.
However, the `setState` is really slow, it costs 30ms to 60ms to finish. Is there anyway to interact with the chart to add data?

**Comment by xile611** [comment]
@Kroderia Svg can't render too much points now. Maybe you can change the interaction of such huge number of points.
