### ISSUE TITLE
Animation questions

### ISSUE THREAD

**Issue by joeshub** [recharts/recharts#95]
Does anyone have an example of how the line chart animation can be modified? I'm trying to see if we can have it be unique and maybe come up from the bottom instead of from the left. Thank you!

Also, if I disable animations, does react-smooth get bundled still?

Thank you!

**Comment by jasonHzq** [comment]
It's a good idea to customize animation , I'm sorry for Recharts not support it yet.  We will add this feature soon.

**Comment by xile611** [comment]
react-smooth will still get bundled If animation is disabled.

**Comment by adrianmc** [comment]
@xile611 how do I disable animation?

**Comment by xile611** [comment]
@adrianmc You can set the props `isAnimationActive` to `false` in `Bar`, `Line`, `Pie`, etc.
[Here](http://recharts.org/api) is the document.

**Comment by adrianmc** [comment]
Oh I see, I didn't realize it was specific to the Bar component and not the BarChart component. Thanks.

**Comment by carlbernardo** [comment]
@xile611 @jasonHzq Rather than start a new issue, I thought I would add to this. Is there a way to trigger the animation only when the graph is enters the view e.g. you scroll down to the graph area and then it starts animating? I'd rather not delay the animation using `animationBegin` or slow it down using `animationDuration`. Thanks!

**Comment by carlbernardo** [comment]
Although not ideal, I ended up using some conditional logic to display the graph component based on React's event system, specifically `onMouseEnter`. I can go into further detail if anyone was interested. Would still like to know a better way to solve that however.

**Comment by xile611** [comment]
Duplicated with issue #293 .

**Comment by ethan-deng** [comment]
I think there is currently a bug with the Customized Label. If you go to http://recharts.org/#/en-US/examples/PieChartWithCustomizedLabel directly, the customized label will be drawn. But if you go to any other link first such as http://recharts.org/#/en-US/examples/SimpleScatterChart then click on "PieChartWithCustomizedLabel", then the customized label won't be drawn.

**Comment by ferddecoded** [comment]
> Although not ideal, I ended up using some conditional logic to display the graph component based on React's event system, specifically `onMouseEnter`. I can go into further detail if anyone was interested. Would still like to know a better way to solve that however.

would you still be able to share your solution?
i am trying to utilize on scroll event on recharts

**Comment by ferddecoded** [comment]
> Although not ideal, I ended up using some conditional logic to display the graph component based on React's event system, specifically `onMouseEnter`. I can go into further detail if anyone was interested. Would still like to know a better way to solve that however.

@c9rl would you still be able to share the solution you figured out?

**Comment by brc-dd** [comment]
> trigger the animation only when the graph is enters the view

I was able to do this using a simple hook and setting `isAnimationActive` prop of `Bar`, `Line`, `Pie`, etc. when the element is visible. Here is my code for reference:

```ts
// https://stackoverflow.com/a/65008608/11613622
import type React from 'react';

import { useEffect, useState } from 'react';

const useOnScreen = (ref: React.RefObject<Element>): boolean => {
  const [isIntersecting, setIntersecting] = useState(false);

  useEffect(() => {
    const observer = new IntersectionObserver(([entry]) => {
      setIntersecting(entry.isIntersecting);
    });

    observer.observe(ref.current!);
    return (): void => {
      observer.disconnect();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return isIntersecting;
};

export default useOnScreen;
```

```tsx
const Foo: React.FC = () => {
  const ref = useRef<HTMLDivElement>(null);
  const isVisible = useOnScreen(ref);

  return (
    <div ... ref={ref}>
      <BarChart ...>
        ...
        <Bar ... isAnimationActive={isVisible} />
        ...
      </BarChart>
    </div>
  );
};
```
