### ISSUE TITLE
Text component - labels alignment

### ISSUE THREAD

**Issue by hc1skalyanasundaram** [recharts/recharts#950]
I'm using Text component to render XAxis tick labels. But the labels are misaligned and displayed somewhere else, not on the xaxis. ANy help in getting the right props to display the labels correctly?

This is my customized tick component
class CustomizedTick extends Component {

    render() {
        const {x, y, stroke, payload} = this.props;

        return (
                <Text style={{fontSize:2}} width={100} textAnchor="middle" scaleToFit={true} >{payload.value}</Text>
                );

    }
}
<img width="437" alt="screen shot 2017-10-11 at 3 20 11 pm" src="https://user-images.githubusercontent.com/26306011/31461506-b43bfa54-ae97-11e7-8981-5a950dacc247.png">

**Comment by yaroslav-perec** [comment]
@hc1skalyanasundaram 
Try to add `x={x}` and `y={y}`
<Text x={x} y={y} style={{fontSize:2}} width={100} textAnchor="middle" scaleToFit={true} >{payload.value}</Text>
