### ISSUE TITLE
Incorrect number of ticks after setting tickCount

### ISSUE THREAD

**Issue by xueeey** [recharts/recharts#953]
## Do you want to request a feature or report a bug?
Possible bug?

## What is the current behavior?
Not the right number of ticks

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).

```
<XAxis
  dataKey="time"
  tickFormatter={formatShortDate}
  type="number"
  domain={['dataMin', 'dataMax']}
  tickCount={3}
  interval={0}
  padding={20}
/>
```

![image](https://user-images.githubusercontent.com/1673356/31543668-1c664f94-b00f-11e7-9345-23eb66ad401a.png)

## What is the expected behavior?

Expected 3 ticks but only have 2. From reading the docs, by setting interval to 0, it should show all 3 ticks.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Mac OSX 10.12.6
Chrome 
Recharts: v1.0.0-alpha.6

Would be great if there was some deeper explanation of how ticks work.

Thanks

**Comment by tuberrabbit** [comment]
I have the same issue about incorrect tickCount

**Comment by maracuja-juice** [comment]
@li-xinyang But I need to use interval={'preserveStartEnd'}

**Comment by rogerjak** [comment]
Same issue for me, my type is number (time axis) and tickCount don't matter.
I want 2 ticks and interval="preserveStartEnd".

**Comment by veddermatic** [comment]
yeah, tickCount on an x axis doesn't work no matter what in my experience. I've had to create an array of ticks manually to have any control.

**Comment by genbit** [comment]
you need to have the following condition:
- not set scale property
- domain={['auto', 'auto']}
- type="number"

than tickCount will work, as per:

https://github.com/recharts/recharts/blob/1fa433b89e67ea816c8dda11202d4c8cead25935/src/util/ChartUtils.js#L758

**Comment by albert-schilling** [comment]
Sorry, to warm this up. But I had difficulties applying @genbit 's suggestion, so maybe this addition can help others:

My goal was to display a time based line chart with values coming in every couple of milliseconds and a defined maximum data length, plus, with the additional challenge of pushing in a null value when the server is disconnected to indicate an interruption of the data stream.

To have Recharts calculate the correct time based distance between data points and still only have the desired tick count of 5, I just had to calculate the correct interval for the length of my data array:

`interval={data.length / 5}`

In total, the X-axis looked something like this:

`<XAxis
                dataKey="timestamp"
                scale='time'
                type="number"
                domain={['auto', 'auto']}
                interval={data.length / 5}
                tickFormatter={ ...
               ...
</XAxis>`

![image](https://user-images.githubusercontent.com/59568178/89024627-b14bb180-d325-11ea-80f6-b03e3c82b666.png)

**Comment by sangtm-04** [comment]
I use the property "ticks" and I have to calculate which values will display in axis. 
For example: If I want to display 3 ticks, the properties look like this:

```
<XAxis
  type="number"
  tickFormatter={{stroke: 'red', strokeWidth: 2}}
  domain={['dataMin', 'dataMax']}
  tickCount={3}
  interval={0}
  ticks={[0, 6000, 12000]}
/>
```
So you can try this. Hope this help

**Comment by kalmanh** [comment]
@sangtran04 - If you are providing your own `ticks` array, do you even need to provide the `tickCount` ?
