### ISSUE TITLE
Hiding YAxis line when there is CartessianGrid

### ISSUE THREAD

**Issue by erayalakese** [recharts/recharts#954]
## Do you want to request a feature or report a bug?
I want to hide Y Axis line but keep ticks. So `<YAxis axisLine={false} />` should do it but it's not working as expected. Probably conflicting with vertical CartesianGrid. I'm not sure if it's a problem with axis component or CartesianGrid component.
## What is the current behavior?
It's not hiding Y Axis line.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).
http://jsfiddle.net/mnchu2q3/1/
(if you remove CartesianGrid component (line 19) it's working as expected.
## What is the expected behavior?
Y axis line should be invisible.
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts 1.0.0-alpha.5
Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by ZephD** [comment]
In your demo, there is no y-axis line, with or without the CartesianGrid.
The line that exists is green, and is drawn by the CartesianGrid.

As you can see by this version:
http://jsfiddle.net/mnchu2q3/3/

I made the Y-axis's line red and the CartesianGrid's green and dashed.
Note there is no red line behind the green dashed line.
