### ISSUE TITLE
StopPropagation for some Mouse Events

### ISSUE THREAD

**Issue by ZephD** [recharts/recharts#957]
## Do you want to request a feature or report a bug?
Feature

## What is the current behaviour?
Mouse events (mostly relating to the drag event) propagate down to components behind the chart.
This causes problems with those components if they also listen to the mouse event.
For example, if the chart is inside a draggable panel, trying to adjust the brush will also move the whole panel.
This is how it currently works in [d3](https://github.com/d3/d3/releases/tag/v3.2.2)

## If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).
Template does not work?

## What is the suggested behaviour?
Components which _use_ a mouse event should prevent propagation of the mouse event.
This includes the Brush's drag feature.
One solution would be to pass the mouse event to the onChange handler, so we can optionally control the event ourselves.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
0.22.0

**Comment by nypinstripes** [comment]
@ZephD Currently experiencing this as well, was there any resolution? @xile611
