### ISSUE TITLE
Word-wrap overflown X-axis labels

### ISSUE THREAD

**Issue by James2516** [recharts/recharts#961]
https://github.com/recharts/recharts/issues/198

This is supposedly fixed by https://github.com/recharts/recharts/pull/243 but it doesn't seem to work.

How do I use it? `<XAxis dataKey="name" interval={0} width={30} label={<Text width={30} />} />`?
@techniq

**Comment by techniq** [comment]
I haven't used recharts in a while, and have [extracted](https://github.com/techniq/react-svg-text) out the `<Text />` component to use in other projects (like [vx](https://github.com/hshoff/vx)) but all that is required to have `<Text />` wrap is an explicit width like you have.  I don't know how best to integrate Text with an axis but maybe you are supposed to pass props directly to it, such as:

```js
<XAxis dataKey="name" interval={0} width={30} label={props => <Text width={30}>{props.text}</Text>} />
```

but I'm just guessing.  I took a quick peak at the source of [XAxis](https://github.com/recharts/recharts/blob/master/src/cartesian/XAxis.js) but didn't see how it uses the label prop.

**Comment by James2516** [comment]
Doesn't work unfortunately...

**Comment by havietduc91** [comment]
> Doesn't work unfortunately...

Hi James2516, I just only use `width` param for XAxis or YAxis and it's working fine, maybe it helps you!
![screenshot 3](https://user-images.githubusercontent.com/4966192/46184312-454e2b80-c2ff-11e8-8267-52628999acf6.png)

Please click the bellow link to know more!
https://jsfiddle.net/vuh6cLyz/3/

**Comment by lisamartin00** [comment]
I was finally able to figure it out based on their Line Chart Example fiddle, which uses a custom component passed into the `<XAxis> tick` property.
https://jsfiddle.net/alidingling/5br7g9d6/

You can do something similar to what they've done and return the `<Text>` element
https://jsfiddle.net/lisamartin00/exasjofp/
Now you can set a fixed width and the text will wrap.  You may still need to write some custom media queries to adjust the `font-size` for smaller screen widths, e.g.
` @media screen and (max-width: 480px){
.recharts-cartesian-axis-ticks {
      font-size: 10.5px;
    }
`

**Comment by deadlyfingers** [comment]
If you need word wrap on long string or word which has no spaces I have a fiddle which shows how to chunk long text strings and splits it up into multiple `tspan` elements. https://jsfiddle.net/deadlyfingers/jngsxqyo/77/

**Comment by bertho-zero** [comment]
I created a `CustomizedAxisTick` for that:

```jsx
function CustomizedAxisTick({
  maxLines = 3,
  payload,
  ...rest
}) {
  const [text, setText] = useState(payload.value);
  const [suffix, setSuffix] = useState('');

  const measuredRef = useCallback(node => {
    if (node === null) {
      return;
    }

    let numberOfLines = node.state.wordsByLines.length;
    let tempText = text;
    const tempSuffix = numberOfLines > maxLines ? '…' : '';

    while (numberOfLines > maxLines) {
      tempText = tempText.slice(0, -1);
      numberOfLines = node.getWordsByLines({
        ...rest,
        children: tempText + tempSuffix
      }, true).length;
    }

    if (tempText !== text) {
      setText(tempText);
      setSuffix(tempSuffix);
    }
  }, [maxLines, rest, text]);

  return (
    <g>
      <Text {...rest} ref={measuredRef}>
        {text + suffix}
      </Text>
      <title>{payload.value}</title>
    </g>
  );
}

// ...

  <YAxis
    dataKey="agenda.title"
    type="category"
    width={133}
    tick={<CustomizedAxisTick maxLines={3} />}
  />
```

Unlike the other solutions seen here, this is based on a maximum number of lines while respecting the width. If it goes beyond that adds an ellipsis and a title to the hover.

![image](https://user-images.githubusercontent.com/8525267/80077896-6cf28d80-854e-11ea-8b7d-deed37b6c90b.png)

I noticed that `getWordsByLines` from `Text` does not cut long words that are longer than the width.

**Comment by Morantron** [comment]
> I created a `CustomizedAxisTick` for that:
> 
> ```js-jsx
> export default function EllipsisAxisTick({ maxLines = 3, payload, ...rest }) {
>   const [text, setText] = useState(payload.value);
>   const [suffix, setSuffix] = useState('');
> 
>   const measuredRef = useCallback(
>     node => {
>       if (node === null) {
>         return;
>       }
>       let { wordsByLines } = node.state;
>       let biggestLine = wordsByLines.reduce((a, b) => (a.width > b.width ? a : b));
>       let tempText = text;
>       const tempSuffix = wordsByLines.length > maxLines || biggestLine.width > rest.width ? '…' : '';
> 
>       while (wordsByLines.length > maxLines || biggestLine.width > rest.width) {
>         tempText = tempText.slice(0, -1);
>         wordsByLines = node.getWordsByLines(
>           {
>             ...rest,
>             children: tempText + tempSuffix
>           },
>           true
>         );
>         biggestLine = wordsByLines.reduce((a, b) => (a.width > b.width ? a : b));
>       }
> 
>       if (tempText !== text) {
>         setText(tempText);
>         setSuffix(tempSuffix);
>       }
>     },
>     [maxLines, rest, text]
>   );
> 
>   return (
>     <g>
>       <Text {...rest} ref={measuredRef}>
>         {text + suffix}
>       </Text>
>       <title>{payload.value}</title>
>     </g>
>   );
> }
> 
> // ...
> 
>   <YAxis
>     dataKey="agenda.title"
>     type="category"
>     width={133}
>     tick={<EllipsisAxisTick maxLines={3} />}
>   />
> ```
> 
> Unlike the other solutions seen here, this is based on a maximum number of lines while respecting the width. If it goes beyond that adds an ellipsis and a title to the hover.
> 
> ![image](https://user-images.githubusercontent.com/8525267/80077896-6cf28d80-854e-11ea-8b7d-deed37b6c90b.png)
> 
> I noticed that `getWordsByLines` from `Text` does not cut long words that are longer than the width.

This does no longer works in 2.0.0 because getWordsByLine is no longer accessible through the ref

I think it was introduced in this commit fc1669aa5a722ce2c1dc1da3ab04222781996f4d

Would be cool to expose it again or maybe include this multine ellipsis approach in the <Text /> component itself, as it seems to work very well

cc @xile611  @bertho-zero

**Comment by Morantron** [comment]
I've accidentally created a PR to include `maxLines` prop in the Text component itself

**Comment by ababos** [comment]
Any solution to this?  I have the "2.0.9", version.
