### ISSUE TITLE
Change the brush startIndex and endIndex enhancement

### ISSUE THREAD

**Issue by magdalko** [recharts/recharts#963]
Hi!

I have the navigation brush on the top and the reference graph just under. When I change the brush scope, the reference graph is changing with the same data from the brush (above have the dates and I take the dates from the brush and collect the data for the chosen dates). I wanted to revert the function to have a possibility to change the brush scope while I change the graph scope. So when I for example click on the button which changes the scope on the reference graph, the brush should update with new dates shown on the graph below. 

I used startIndex and EndIndex but it works only when the component with Brush unmounts and then mounts again. Any solution for that? Any possibilities to add the functionality?

**Comment by lorenzos** [comment]
Same issue here. I'm using the `Brush` like a "controlled component", passing `onChange`, `startIndex` and `endIndex` props. Everything works, except the labels on the sides of the brush traveller, which are not updated. 

Here's a reproduction of the issue: <http://jsfiddle.net/so3jbn10/>. As you can see, everything works as expected: when I change the brush, the component state is updated, and chart domain and the brush are updated accordingly; only brush labels are wrong.

**Comment by waqidvolli** [comment]
Same issue, My brush uses the state to set the start and end index. At a later point, when I update the state, the brush does not reflect this change. If I resize the browser window, the brush then gets updated. I tried to force a re-render by calling forceUpdate() after setState. Did not help.

**Comment by pedrobernardina** [comment]
No solutions yet? Any hack? I need to control brush position/size via state and I'd like to avoid using d3 directly to achieve this behaviour.

**Comment by pedrobernardina** [comment]
```javascript
componentWillReceiveProps {
  ...
  if(nextProps.startIndex !== startIndex) {
    this.setState({ startX: this.scale(nextProps.startIndex) })
  }
  if(nextProps.endIndex !== endIndex) {
    this.setState({ endX: this.scale(nextProps.endIndex) })
  }
}
```

adding this change to /src/cartesian/Brush.js seems to do the trick, but I don't know if this breaks anything.

**Comment by azhulmukhametova** [comment]
Also interested in this. I need to have the possibility to "reset" brushed region by a button but setting startIndex/endIndex has no effect.

**Comment by maksufa** [comment]
Same here. I've prepared an implementation of manual zoom for the chart and need to control brush by start and end indices then, however, it doesn't work as expected.

**Comment by fedonev** [comment]
Hacky workaround:  updating the chart's `data` prop results in a re-render of the chart and brush with the new `brushRange` values.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue guide.

**Comment by makis-spy** [comment]
In case anyone else encounters this issue what worked for me is 

`<Brush dataKey='label' startIndex={this.state.startIndex} endIndex={this.state.endIndex}  onChange={(a)=>{
                clearTimeout(this.so)
                this.so = setTimeout(()=>{
                  this.setState({
                    startIndex : a.startIndex,
                    endIndex : a.endIndex,
                  })
                },1000)

              }}/>`

**Comment by Mukesh054** [comment]
@makis-spy 
Thanks Buddy ..... Appreciated!!!!!!

**Comment by brendan-limpide** [comment]
> In case anyone else encounters this issue what worked for me is
> 
> ```
> <Brush dataKey='label' startIndex={this.state.startIndex} endIndex={this.state.endIndex}  onChange={(a)=>{
>                 clearTimeout(this.so)
>                 this.so = setTimeout(()=>{
>                   this.setState({
>                     startIndex : a.startIndex,
>                     endIndex : a.endIndex,
>                   })
>                 },1000)
> 
>               }}/>
> ```

@makis-spy can you elaborate on this? I'm unsure of what `this.so` is supposed to be exactly. And I'm trying to adapt this for a functional component with hooks
