### ISSUE TITLE
Scatter Chart linear X-Axis

### ISSUE THREAD

**Issue by KeKs0r** [recharts/recharts#964]
## What is the current behavior?
I am trying to generate a scatter chart with some data which has an x and y values.
X ranges from 1-5 and y ranges from 0-25. I just want to plot all data points into a single chart which respects the ranges as axis.

## Example
My Current Component looks like this:
```javascript
  render() {
    const { data } = this.props;
    const mapped = data.map(d => {
      return {
        x: parseInt(d.orig_x),
        y: Math.round(d.orig_y)
      }
    })

    console.log(mapped.slice(1, 10))
    const limitedData = _.sortBy(mapped.slice(1, 10), 'x')

    return (
      <ScatterChart width={500} height={400} margin={{ top: 20, right: 20, bottom: 20, left: 20 }}>
        <XAxis dataKey="x" name='x' domain={[0, 5]} />
        <YAxis dataKey="y" name='y' domain={[0, 25]} />
        <CartesianGrid horizontal={false} vertical={false} />
        <Scatter name='data' data={limitedData} fill='#8884d8' />
        <Tooltip cursor={{ strokeDasharray: '3 3' }} />
      </ScatterChart>
    )
  }
```

The current code results in a chart which looks like this:
![image](https://user-images.githubusercontent.com/2970814/31896923-3eb69550-b815-11e7-8966-38d54abdf7c3.png)

## What is the expected behavior?
The expected behaviour would be that all data points with an X value of e.g. 3 would be on the same point on the x-axis. But in the current version, there are multiple 3 on the x-axis. Is there a way to prevent this?

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts: 1.0.0-alpha.6
Browser: Chrome

**Comment by jetzhou** [comment]
I had the same problem!

Use `<XAxis type='number' dataKey="x" name='x' domain={[0, 5]} />`, that should do it!

**Comment by xile611** [comment]
@KeKs0r Update the `type` of <XAxis> which has default value 'category'.

**Comment by lidaof** [comment]
I used Date as x-axis and somehow it's not working..any suggestions? thanks.

![image](https://user-images.githubusercontent.com/102806/38276260-043421d0-375a-11e8-89ac-e491efa805f9.png)

**Comment by Kobzol** [comment]
Try setting `allowDuplicatedCategory={false}` on the XAxis component.

**Comment by lidaof** [comment]
hi @Kobzol thank you so much, works perfect!

**Comment by jalishchauhan2224** [comment]
@Kobzol  thank you sir for this used full information
