### ISSUE TITLE
Onclick event for stacked bars

### ISSUE THREAD

**Issue by Shubham-Sinha** [recharts/recharts#966]
In case of stacked bar graph 
```jsx
<Bar dataKey="less_than_50" stackId="name" fill="#4CAF50" onClick={(data, index) => console.log(data, index)} />
<Bar dataKey="between_50_and_75" stackId="name" fill="#2196F3" onClick={(data, index) => console.log(data, index)} />
<Bar dataKey="more_than_75" stackId="name" fill="#f44336" onClick={(data, index) => console.log(data, index)} />
```
![chart](https://preview.ibb.co/eZYuAm/rechart_stacked.png)

One can click on a single bar only, not on individual stacks of each bar. Is there any way of clicking the red, green, blue stacks individually ?

**Comment by hueitan** [comment]
Please try to click the bar example in this fiddle http://jsfiddle.net/7nbdquhq/, and expect to see the alert `${color} ${index}` when clicking the different bar, I believe this is enough for you to determine which bar is clicked.

**Comment by ckifer** [comment]
@anandbasnal https://codesandbox.io/s/stacked-bar-chart-onclick-h6ldmt

**Comment by anandbasnal** [comment]
> @anandbasnal https://codesandbox.io/s/stacked-bar-chart-onclick-h6ldmt

Can we also add an active class (or a bolder style) to the selected bar's XAxis value, just to show it focused on click?

**Comment by ckifer** [comment]
You could change the color of the bar but I don't think it's going to be easily possible to modify the corresponding X axis tick style

**Comment by anandbasnal** [comment]
> You could change the color of the bar but I don't think it's going to be easily possible to modify the corresponding X axis tick style

The problem is that, we can change the color of single bar, but not stacked bars
