### ISSUE TITLE
[BUG] LineChart offset bottom & height change when interacting with the <Brush /> + having verticalAlign="bottom" on <Legend />

### ISSUE THREAD

**Issue by ahmedelgabri** [recharts/recharts#974]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
When you have a `<Legend verticalAlign="bottom" />` & `<Brush />` component & using React 16 the `<Brush />` will jump & it will overlap the `<Legend />`. Works fine with React `15.6.2`. So it's related to #916 

I can reproduce it using the demo from http://recharts.org/#/en-US/examples/BrushBarChart, just with a simple change. adding `verticalAlign="bottom"` to `<Legend />`

With react `15.6.2`: Works fine https://codesandbox.io/s/8y47xvyno8
With react `16`: Doesn't work https://codesandbox.io/s/01lw4np5l

BTW, this is also reproducible if you just run `npm run demo` & check the LineChart example. 

The issue it seems that the offsets passed from `<LineChart />` are not right. Mainly `bottom` & `height`

## What is the expected behavior?
`<Brush />` shouldn't jump or overlap `<Legend />`

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

I'm testing agains the latest version, ~`v1.0.0-beta.0`~ `v1.0.0-beta.1` & the bug is reproducible in Safari, Chrome & Firefox on macOS (didn't have windows machine next to me to test yet, but I assume it will be the same)

And yes it worked fine before & it even works fine in this version but if `<Legend />` doesn't have `verticalAlign="bottom"`

**Comment by ahmedelgabri** [comment]
BTW, this is also reproducible if you just run `npm run demo` & check the `Line Chart` example.

**Comment by ahmedelgabri** [comment]
@xile611 any ideas where to look to fix this? And what might be causing this?

**Comment by ahmedelgabri** [comment]
I'm even asking for pointers so I can open a PR, still no answer for more than 20 days. @xile611

**Comment by ahmedelgabri** [comment]
An answer to the issue will nice, we are blocked by this bug & we offered to help in fixing the issue but still no reply at all.

**Comment by ahmedelgabri** [comment]
If you put this 

```js
if (displayName === 'Line') console.log(displayName, { height: item.props.height, bottom: item.props.bottom, brushBottom: item.props.brushBottom })
``` 
under this line you can the change 

https://github.com/recharts/recharts/blob/22cd55dcd7dc13ba4338dd51f16c0569ba704fe0/src/chart/generateCategoricalChart.js#L1407

You will also realize that the change in `height` is the exactly the same value that gets subtracted from `offset.bottom`, for example if you run the LineChart demo page & check the last chart. This is the result of the console.log on the initial render

```js
{
  "height": 252,
  "bottom": 108,
  "brushBottom": 50
}
```

And this is after you move one of the sliders

```js
{
  "height": 270,
  "bottom": 90,
  "brushBottom": 50
}
```

Height increased by 18 while bottom decreased also by 18.

**Comment by ahmedelgabri** [comment]
Fixed in the latest release.

**Comment by liping1994** [comment]
today, I meet the same problem as you， but I don't konw how to solve it.

**Comment by liping1994** [comment]
I downloaded the latest version，and  I've already solved it, thank you very much.
