### ISSUE TITLE
Dot mouse event handler are not being invoked

### ISSUE THREAD

**Issue by ranjib** [recharts/recharts#976]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
onClick, onMouseUp etc event handler are not being invoked, as specified in the API: http://recharts.org/#/en-US/api/Dot

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal 
```jsx
import React from 'react'
import {LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend} from 'recharts'

export default class Charts extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      data: [
        {name: 'Page A', uv: 4000, pv: 2400, amt: 2400},
        {name: 'Page B', uv: 3000, pv: 1398, amt: 2210},
        {name: 'Page C', uv: 2000, pv: 9800, amt: 2290},
        {name: 'Page D', uv: 2780, pv: 3908, amt: 2000},
        {name: 'Page E', uv: 1890, pv: 4800, amt: 2181},
        {name: 'Page F', uv: 2390, pv: 3800, amt: 2500},
        {name: 'Page G', uv: 3490, pv: 4300, amt: 2100}
      ],
    }
   this.onClick = this.onClick.bind(this)
  }

  onClick(ev){
    console.log(ev)
  }

  render(){
     var customDot={
        r: 6,
        onClick: this.onClick
      }
    return(
      <div className='container'>
        <LineChart width={600} height={300} data={this.state.data} >
          <Line  dataKey="pv" stroke="#8884d8" dot={customDot} />
        </LineChart>
      </div>
    )
  }
}
```
## What is the expected behavior?

When user click on the "dot" s console log statement will be executed.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

recharts: 0.20.2, latest chrome running on MasOS sierra

I am trying to implement draggable line charts, using the mouse event handlers. This has been discussed earlier as well 

https://github.com/recharts/recharts/issues/686
https://github.com/recharts/recharts/issues/560

But I could not find any solution in those threads as well,

**Comment by kiranvj** [comment]
Use` activeDot={customDot}` instead of `dot={customDot}`
