### ISSUE TITLE
yarn check v1.2.1 node v8.8.0 npm 5.5.1 ERROR react 16.0

### ISSUE THREAD

**Issue by alexeikaratai** [recharts/recharts#977]
error "recharts#react-transition-group@^2.2.1" doesn't satisfy found match of "react-transition-group@1.2.1"
error "recharts#react-resize-detector#react@^0.14.7 || ^15.0.0" doesn't satisfy found match of "react@16.0.0"
error "recharts#react-smooth#react@^0.14.0 || ^15.0.0" doesn't satisfy found match of "react@16.0.0"
error "recharts#react-smooth#react-dom@^0.14.0 || ^15.0.0" doesn't satisfy found match of "react-dom@16.0.0"

**Comment by kennyy0123** [comment]
Same problem here.

**Comment by dmr** [comment]
react-resize-detector's current version is 1.1.0 and the only change was the react 16 compatibility --> can be updated?

**Comment by alexeikaratai** [comment]
@dmr after update, this problem not fixed!

**Comment by xile611** [comment]
@alexeikaratai Try the latest version: recharts@1.0.0-beta.1.

**Comment by alexeikaratai** [comment]
@xile611 thx! at all!
