### ISSUE TITLE
LineChart Line number 

### ISSUE THREAD

**Issue by insomniahl** [recharts/recharts#979]
## Do you want to request a feature or report a bug?
report a bug
## What is the current behavior?
when lines only one data in array, i change tabs will error. but when lines length > 1, it`s ok
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).
http://jsfiddle.net/c03v6fpn/
## What is the expected behavior?
Data processing should be the same regardless of one or more data
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
recharts@1.0.0-apha.5
i use re-tabs together

![error](https://user-images.githubusercontent.com/15605581/32088988-f69981c0-baac-11e7-951e-84324ee9c32e.png)

**Comment by ryanand26** [comment]
That works for me (after fixing the fiddle), http://jsfiddle.net/ryanand26/4avzc2kg/. I was hoping you'd a nice test case for issue I've see at https://github.com/recharts/recharts/issues/935

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
