### ISSUE TITLE
Radar chart can't pass multiple props to component

### ISSUE THREAD

**Issue by eldyvoon** [recharts/recharts#980]
## Do you want to request a feature or report a bug?
bug
## What is the current behavior?

Can't pass multiple props to radar chat

`Uncaught (in promise) Error: React.Children.only expected to receive a single React element child.
    at invariant (invariant.js?4599*:44)
    at Object.onlyChild [as only] (onlyChild.js?27e3*:33)
    at isChildrenEqual (ReactUtils.js?5b63:354)`

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).

Create a wrapper component for radar chart, pass 2 props to the component, the error can be seen.

## What is the expected behavior?

It should not has the error, other chart is working fine.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Latest version, chrome, mac.

**Comment by xile611** [comment]
@eldyvoon Can you show more code about your case?

**Comment by xile611** [comment]
![image](https://user-images.githubusercontent.com/6111424/32433126-e43b8616-c314-11e7-8129-6bc55fe6757e.png)

@eldyvoon I can't reproduce your case. Can you create an online demo ?

**Comment by eldyvoon** [comment]
yeah I created a miniature, it works fine, I wonder what's my problem, will try to debug more deeper later.

**Comment by xile611** [comment]
@eldyvoon Reopen this issue if you can support more information about your case.
