### ISSUE TITLE
Cannot read property 'ReactCurrentOwner' of undefined

### ISSUE THREAD

**Issue by dlonli** [recharts/recharts#982]
I keep getting this issue, i tried updating my reactjs & react dom and it doesn't help.

**Comment by stvogel** [comment]
Hi dlonli,
could you tell me what happened so that this error is gone and you closed this issue?
I'm facing the same error-message.

Thanks
Stefan

**Comment by littlehome-eugene** [comment]
I had the same error, 
I changed import from `umd` version to `lib` version
