### ISSUE TITLE
Custom dataKey value

### ISSUE THREAD

**Issue by studioraygun** [recharts/recharts#983]
Apologies if this has already been asked but I couldn't find the answer I need.

When setting dataKey, for example

`<Bar dataKey="unique_visitors"...`

It would be useful to be able to pass a label value in here, i.e. "Unique Visitors". This is because I would like to decouple my labelling from my actual data source. Is this possible?

**Comment by xile611** [comment]
@studioraygun  Do you want to create a single label for the <Bar /> or something else ?

**Comment by studioraygun** [comment]
@xile611 A label would be fine:

`<Bar dataKey="unique_visitors" label="Unique Visitors"...`

So when hovering you see the label, not the dataKey.

**Comment by xile611** [comment]
@studioraygun If you mean the corresponding label in `Tooltip`, you can try the props `name`.

```jsx
<Bar dataKey="unique_visitors" name="Unique Visitors"...
```

**Comment by xile611** [comment]
@studioraygun Reopen this if the demo don't match your case.
