### ISSUE TITLE
how can I customize the tick using tickFormatter in PolarAngleAxis for RadarChart? 

### ISSUE THREAD

**Issue by abdulkhaliquem9** [recharts/recharts#984]
I want the radarchart to display the labels with customized font styles and oriention (in terms of rotation).
 Basically I want to decrease the font size and rotate the text, can some body give me an example of tickFormmater in PolarAngleAxis.
`<PolarAngleAxis dataKey="subject"  tickFormatter={........??????}/>`

**Comment by xile611** [comment]
@abdulkhaliquem9 Update the props `tick` of PolarAngleAxis:

```jsx
<PolarAngleAxis  tick={{ fill: 'red', fontSize: 20,  angle: 30 }} />
```
If you want to render different angle of each tick, you can use a customized function to render tick.

**Comment by rishabh-uabler-100** [comment]
Do you guys have any idea on how to show a svg/png image at place of text for tick?
