### ISSUE TITLE
[feature] Recharts customizations

### ISSUE THREAD

**Issue by mikyweb** [recharts/recharts#986]
## Do you want to request a feature or report a bug?
Feature

## What is the expected behavior?
Pie Chart width different legend and shadow (see the attachment)
![seecom 66 sezione merchandising vista piechart livello ii warda](https://user-images.githubusercontent.com/2683993/32226317-8f17a7b2-be48-11e7-910e-95440ad1301b.png)

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
You can use the latest release of Recharts, React 16.0.0 and the charts must work on Chrome (latest release), Firefox (latest release), Internet Explorer (latest release) and touch / mobile devices.

**Comment by mikyweb** [comment]
Hi @xile611 are you willing to work at customization even with cash compensation? Thanks

**Comment by mikyweb** [comment]
@xile611 can i have a response please ? Thanks

**Comment by hueitan** [comment]
I tried to customize the example pie chart, here's what I got and surprise that the chart is almost free to customize everything 😄 

jsfiddle link : http://jsfiddle.net/c007u90y/
screenshot : 
![screen shot 2017-11-09 at 11 18 11 pm](https://user-images.githubusercontent.com/2560096/32632542-4d35aa8e-c5a4-11e7-9260-e5dee33335c9.png)

**Comment by mikyweb** [comment]
Thank you for the answer and the example. But as you see I have a different legend, all elements are aligned to the left or right, without overlapping.
Do you have any suggestions? Thank you

**Comment by hueitan** [comment]
as what I mentioned above, it is customizable, try it.
