### ISSUE TITLE
[feature] Bar background customization similar to radialbar

### ISSUE THREAD

**Issue by Inveracity** [recharts/recharts#987]
## Feature request
(I think this is a feature request as I've attempted searching through the source code to see if this was feasible at all)

The radialbar sports a nice background for each individual bar, I would love to have this the basic vertical bar charts

radialbar from the examples page:
![radial](https://user-images.githubusercontent.com/8753040/32237965-a3964838-be66-11e7-83d6-28d7edfd78a6.jpg)

In essence what I want to do:
![image](https://user-images.githubusercontent.com/8753040/32238171-62f8d57e-be67-11e7-96fb-84191ead175c.png)

I hope that sounds like a nice feature, otherwise I'd love pointers on how I could still achieve this by other means (I'm very much a novice in React still).

Thanks!

**Comment by hueitan** [comment]
there's already the example on the official example page. Try to use another Bar to draw the background bar.

StackedBarChart example link : http://recharts.org/#/en-US/examples/StackedBarChart
jsfiddle : http://jsfiddle.net/w368Lj4x/
screenshot :
![screen shot 2017-11-09 at 11 39 25 pm](https://user-images.githubusercontent.com/2560096/32633298-407acab0-c5a7-11e7-8d7e-c24c195abb84.png)

**Comment by Inveracity** [comment]
Interesting idea @hueitan 
though pulling the data from an API and calculating the offset just for cosmeting reasons seems like overkill if it can be done through the same means as the radialbar, plus it polutes the tooltip on mouse-over.
But I appreciate your solution, thanks!
