### ISSUE TITLE
ResponsiveContainer is not working

### ISSUE THREAD

**Issue by radjivC** [recharts/recharts#989]
## Do you want to request a feature or report a bug?
BUG
## What is the current behavior?
ResponsiveContainer is not responsive 
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).

I have use the use example and ResponsiveContainer is not working

## What is the expected behavior?
Be responsive
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Chrome last version

Cheers

**Comment by xile611** [comment]
@radjivC Try the latest version: recharts@1.0.0-beta.1.

**Comment by stmkjp** [comment]
same here. tried with the latest version : recharts@1.0.0-beta.1.
