### ISSUE TITLE
Animation problem in graphs

### ISSUE THREAD

**Issue by Rahulkr204** [recharts/recharts#990]
## Do you want to request a feature or report a bug?
Problem in a feature
## What is the current behavior?
Not able to animate graphs on change of data.
## What is the expected behavior?
Should animate with every change in data

**Comment by xile611** [comment]
@Rahulkr204 Please give a example of what you want.

**Comment by huei-tan-sociomantic** [comment]
I'm not sure what's your use case, but I get the expected animation graphs when updating the data.

![recharts-animation-640px-hd](https://user-images.githubusercontent.com/18140315/32553766-0f8dd70e-c498-11e7-8a8b-05121d0fa550.gif)

**Comment by ItisSyedimran** [comment]
set attribute to animation true.
`<Bar
      isAnimationActive.................................................
 />`

**Comment by Rahulkr204** [comment]
I'm facing this problem.
![animation](https://user-images.githubusercontent.com/8544323/32594867-abd8fc0e-c553-11e7-983a-b686756b9393.gif)

**Comment by xile611** [comment]
@Rahulkr204  Set the props `isAnimationActive` to be `true`


```jsx
<Line isAnimationActive={true} />
```

**Comment by Rahulkr204** [comment]
@xile611 That helped, I was considering it be default true.
