### ISSUE TITLE
Align ReferenceLine to the left of the BarChart bar.

### ISSUE THREAD

**Issue by milasevicius** [recharts/recharts#994]
Is it possible to align ReferenceLine to the left of the Bar chart bar?

Currently it looks like this:
<img width="1013" alt="screen shot 2017-11-02 at 13 42 22" src="https://user-images.githubusercontent.com/1790265/32324343-b9c4dba6-bfd3-11e7-8ae3-e07fc7d9d488.png">

But I want that yellow line to align with the white dot. Thanks.

**Comment by xile611** [comment]
@milasevicius Don't support now.

**Comment by stream7** [comment]
@xile611 this looks similar to https://github.com/recharts/recharts/issues/1457

Are you open to PRs? Could you provide any pointers?
