### ISSUE TITLE
How to draw a goal line in a Radial Bar? 

### ISSUE THREAD

**Issue by gplatt** [recharts/recharts#998]
I would love to be able to define a goal line in radial bars (as shown below).

![image](https://user-images.githubusercontent.com/465729/32438975-48336956-c2f5-11e7-8fcf-8acb489e5657.png)

Is this possible?

Image from [this](https://powerbi.microsoft.com/en-us/documentation/powerbi-service-tutorial-radial-gauge-charts/) article.

**Comment by xile611** [comment]
@gplatt It's a workaround to use `customized shape` of <RadialBar />.
