### ISSUE TITLE
ComposedChart or BarChart custom label x position

### ISSUE THREAD

**Issue by eldyvoon** [recharts/recharts#999]
How to get the width of the bars in custom label? I need that to set the `x` for my ComposedChart

https://imgur.com/a/TJNa3

```
class CustomLabel extends Component {
	render() {
		const {x, y, stroke, value} = this.props;

		console.log(this.props) // I found nothing here
		return (
			<text 
				x={x * 2}
				y={y + 16}
	            fontSize={14}
	            textAnchor="middle"
	            >{value != 0 ? value + '%': ''}</text>
	    )
	}
}
```

**Comment by xile611** [comment]
@eldyvoon You can get width and height from `this.props`.

**Comment by eldyvoon** [comment]
@xile611 the width and height of the bar?

**Comment by xile611** [comment]
@eldyvoon Yeah, you can get the width and height of the corresponding bar from the props of `< CustomLabel  />`.
